### ISSUE TITLE
Feature Request: Config var for dev server host / port

### ISSUE THREAD

**Issue by eheaton** [JeffreyWay/laravel-mix#1000]
- Laravel Mix Version: 1.2.1
- Node Version: 6.10.3
- NPM Version: 5.2 
- OS: Mac OS Sierra

### Description:
 It'd be great to be able to set the host / port on the WebPack dev server, via. a config option. You can partially do it with the `devServer` WebPack config options, but the inline request string is hard coded in the WebPackConfig

WebPackConfig.js:68
```
        this.webpackConfig.output = {
            ...
            publicPath: Mix.isUsing('hmr') ? (http + '://localhost:8080/') : ''
            ...
        };
```

**Comment by ankurk91** [comment]
@eheaton
Then laravel blade helper **mix()** also needs to be configurable.

**Comment by JeffreyWay** [comment]
If this is needed, can someone submit a PR to make the localhost:8080 bit a config option in src/Config.js?

**Comment by sifex** [comment]
Added PR for this, 
https://github.com/JeffreyWay/laravel-mix/pull/1246

**Comment by kylekatarnls** [comment]
@JeffreyWay Yes this is usefull for running multiple Laravel instance at the same time.
