### ISSUE TITLE
Please Update vue-template-compiler to the latest version

### ISSUE THREAD

**Issue by bunnypro** [JeffreyWay/laravel-mix#1002]
- Laravel Mix Version:1.2.2
- Node Version: 6.11.1
- Yarn Version: 0.27.5
- OS: Ubuntu 16.04

### Description:
as the title says, i have an issue when using vue version 2.4.1 its requires vue-template-compiler@2.4.1

**Comment by ankurk91** [comment]
@bunnypro
For the time being you can install your own on top of Laravel mix
```
npm install vue-template-compiler@2.4.1 --save-dev
# YARN
yarn add vue-template-compiler@2.4.1
```
Now webpack will use your version instead of installed by laravel mix. You may want to update vue loader as well.

**Comment by JeffreyWay** [comment]
If it ever gets out of sync, either manually install vue-template-compiler like @ankurk91 suggested, or nuke your node_modules directory and reinstall.

**Comment by ctf0** [comment]
a simpler solution

```bash
yarn remove laravel-mix
# then 
yarn add laravel-mix
```

**Comment by ldiebold** [comment]
@ctf0 your solution worked for me.

Deleting node_modules and reinstalling did not.

**Comment by tinyfly** [comment]
If you delete your node_modes to update you may have to delete your lock file too.
