### ISSUE TITLE
Compile not complete

### ISSUE THREAD

**Issue by iyezhou** [JeffreyWay/laravel-mix#1007]
- Laravel Mix Version: 1.0.7 (`npm list --depth=0`)
- Node Version (`v8.1.2`): 
- NPM Version (`5.0.3`): 
- OS: Windows 10

### Description:

Hi, I can execute `npm run dev` and return successfull, but when I call the complied js file in blade php, like

`<script src="{{asset('js/index.js')}}"></script>`

then reports error

`Uncaught Error: app.model: namespace should be defined`

picture one is source jsx file

![src](https://user-images.githubusercontent.com/26378961/28254786-9663cce4-6ae2-11e7-9a38-f009235e61e9.png)

picture two is dist js file, got an error, seems complie not complete

![dst](https://user-images.githubusercontent.com/26378961/28254780-8774521c-6ae2-11e7-97b7-8ef8e9f0bf71.png)

**Comment by JeffreyWay** [comment]
It doesn't seem like this is a Mix-specific issue. I'd need to see what your codebase looks like, and why it can't find your app namespace.
