### ISSUE TITLE
Enhancement: Version a directory's contents

### ISSUE THREAD

**Issue by thepenguin1** [JeffreyWay/laravel-mix#1008]
would it be possible to include a new option to version the contents of a directory?

E.g. Mix.versionDirectory("/public/img");

I like the idea of being able to version all of my images for easy cache busting.

**Comment by JeffreyWay** [comment]
Yeah, it's on my todo list. It'll be `mix.version('directory/path')`. Will try to knock it out this week.

**Comment by thepenguin1** [comment]
Great stuff!!
