### ISSUE TITLE
 Failed to compile with 1 errors, tried many fixes

### ISSUE THREAD

**Issue by jld5650** [JeffreyWay/laravel-mix#1009]
- Laravel Mix Version: #.#.# (`npm list --depth=0`) With this command I was given a long list of errors
- Node Version (`node -v`):  8.1.4
- NPM Version (`npm -v`): 5.0.3
- OS: Windows 8 Version 6.2

### Description:

Hello!

I've been looking for the solution to this for about a day. Laravel mix has given me this error since I created the project 'nphase'. I removed node_modules, cleared cache and npm install multiple times. I updated node.js/npm to the later versions and I have tried different package.json files given in other solutions.

Thanks in advance for your help.

----------------------------------------------------
npm run dev

C:\xampp\htdocs\nphase>npm run dev

> @ dev C:\xampp\htdocs\nphase
> npm run development

> @ development C:\xampp\htdocs\nphase
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress
--hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 10% building modules 0/1 modules 1 active ...nphase\resources\assets\sass\app.s
 10% building modules 1/2 modules 1 active ...nphase\resources\assets\sass\app.s
 10% building modules 2/3 modules 1 active ...nphase\resources\assets\sass\app.s
 10% building modules 3/4 modules 1 active ...ode_modules\style-loader\addStyles
 10% building modules 4/5 modules 1 active ...nphase\resources\assets\sass\app.s
 95% emitting

 ERROR  Failed to compile with 1 errors                                 12:46:40

This dependency was not found:

* C:\xampp\htdocs\nphase\ app.js in multi ./ app.js ./resources/assets/sass/app.
scss

To install it, you can run: npm install --save C:\xampp\htdocs\nphase\ app.js
            Asset      Size  Chunks             Chunk Names
      /js/ app.js   8.66 kB       0  [emitted]  /js/ app
mix-manifest.json  68 bytes          [emitted]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin
/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/we
bpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\owner\AppData\Roaming\npm-cache\_logs\2017-07-17T16_46_41_
323Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\owner\AppData\Roaming\npm-cache\_logs\2017-07-17T16_46_41_
428Z-debug.log

-----------------------------------------------------------------
webpack.mix.js file

const { mix } = require('laravel-mix');

mix.js(' app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');

**Comment by JeffreyWay** [comment]
Is it because of the space before `app.js` in your `mix.js()` call?

**Comment by jld5650** [comment]
Yes it was that! I figured that out and ended up having more errors but I ended up just recreating the project and used yarn instead of npm to install and it worked.

Thank you again
