### ISSUE TITLE
mix.copy does not allow for the glob params.

### ISSUE THREAD

**Issue by Landish** [JeffreyWay/laravel-mix#101]
laravel.mix.js

```js
mix.copy('src/images/*{.png,.jpg}', 'dist/images');
```
Let's say I have 2 files:  

```
/src/images/example.png
/src/images/example.jpg
```
when I run the `npm run webpack` it copies whole `images` dir into `dist`:

```
/dist/images/src/images/example.png
/dist/images/src/images/example.jpg
```

and should be:
```
/dist/images/example.png
/dist/images/example.jpg
```

**Comment by JeffreyWay** [comment]
Hmm - maybe update to the latest version of Mix and try again. I just tested this out in a new project, and it worked. I did...

```js
mix.copy('tests/Unit/*{.txt,.php}', 'somewhere/else');
```

...and it only copied txt and php files.

**Comment by Landish** [comment]
@JeffreyWay Nope! 

Still having that issue on version 0.5.1.

I even tried to implement directory structure according to your example and ended up with this:

<img width="238" alt="screen shot 2017-01-22 at 20 48 26" src="https://cloud.githubusercontent.com/assets/534610/22184065/5cde14e4-e0e4-11e6-9b5b-60e329bb03d9.png">

**Comment by zgabievi** [comment]
+1 same issue to me.

![screen shot 2017-01-23 at 23 40 55](https://cloud.githubusercontent.com/assets/1515299/22219812/baca9b90-e1c5-11e6-97ca-d5ab6905e6d4.jpg)

**Comment by JeffreyWay** [comment]
This seems to be an issue with the copy plugin we're using. 

https://github.com/kevlened/copy-webpack-plugin/issues/73

Looks like it may be fixed in the next release.

**Comment by JeffreyWay** [comment]
This is fixed now in #135.

**Comment by ianhk** [comment]
I'm not sure about this fix - it means you can't copy a tree without it being flattened. 

My solution is to use the 'context' copy-webpack-plugin option. Context allows you to specify the root that the copy is relative to - rather than implying it all from the 'from' arg.

Something like: 

`mix.copy2 = function (from, to, root) {
    var options = {
        from: from,
        to: Mix.Paths.root(to)
    };
    if (root) {
        options.context = root;
    }
    Mix.copy = (Mix.copy || []).concat(options);
};`

**Comment by njt1982** [comment]
Just had a very similar problem myself:

    .copy('resources/assets/app/**/*.html', 'public/templates')

This ends up making a path like this:

    public/templates/resources/assets/app/modelName/show.html'`

When, really, all I need (and what exlixir's `.html` method did) is this:

    public/templates/modelName/show.html'

[Looking at the examples](https://github.com/kevlened/copy-webpack-plugin#examples), I suspect ( need to do something like this:

    { context: 'resources/assets/app', from: '**/*.html', to: 'public/templates' },

**Comment by njt1982** [comment]
Out of interest... The `copy-webpack-plugin` offers brilliant reconfigurability and options; why do we wrap it up and take all that away with such an oversimplified and opinionated from/to/flatten setup?

Why not just pass `Mix.copy` params DIRECTLY to the plugin? Have I missed something?

- [ ]

**Comment by njt1982** [comment]
I added the following to my webpack.mix.js:

```
mix.copyContext = function (from, to, root) {
  var options = {
    from: from,
    to: mix.config.Paths.root(to)
  };
  if (root) {
    options.context = root;
  }
  mix.config.copy = (mix.config.copy || []).concat(options);
  return this;
};
```

Notable differences to @ianhk 's one...

* It uses the `mix` instance, no need to require `Mix` (which I has issues doing for some reason)... Is this ok, or is it rubbish?! ;) 
* It returns `this` so we can continue to chain it like all the other commands.

I still believe that altering copy to accept the same structure (basically param passthru) to the plugin makes far more sense + makes less code for you to maintain ;)

**Comment by j-solis** [comment]
This works for me (flattens but that's what I wanted). If you are still using elixer and want to preserve structure just run the same in elixer. I currently work in laravel 5.2 so I use elixer for legacy and useful features and mix for all the added ones. Have Laravel Mix 0.8.8

mix.copy('resources/assets/**/*{.woff,eot}',
    'public/test');

**Comment by tfsimondouglas** [comment]
This is still an issue.

```
mix.copy('resources/assets/**/*.svg', './public/images')
```
and get

```
/public/resources/assets/images/[svgs]
```
expected:
```
/public/images/[svgs]
```

Proof:
```
mix.copy('resources/assets/images/test.svg', './public/images')
```
produces:
```
/public/images/test.svg
```

**Comment by sharifzadesina** [comment]
Same problem!!! why this issue is closed?

**Comment by Tonio31** [comment]
I think the problem you're describing is what is described in the [documentation of laravel 5.4](https://laravel.com/docs/5.4/mix#copying-files-and-directories)

> When copying a directory, the copy method will flatten the directory's structure. To maintain the directory's original structure, you should use the copyDirectory method instead:
> 
> mix.copyDirectory('assets/img', 'public/img');

**Comment by sharifzadesina** [comment]
@Tonio31 The problem is that the `copy` method doesn't flatten directory's structure. see the example of @tfsimondouglas

**Comment by jeshtan** [comment]
Same problem here using v0.12.1

**Comment by jeshtan** [comment]
Hi guys, please get latest codes from master branch which solved this issue.

**Comment by ruchern** [comment]
@jeshtan Revert back to `v0.11.4` first and wait for `v1.0` release.
