### ISSUE TITLE
Import less in js file error

### ISSUE THREAD

**Issue by maxonly** [JeffreyWay/laravel-mix#1010]
- Laravel Mix Version: 1.2.2
- Node Version : 8.0.0
- NPM Version :  5.3.0
- OS: Windows 10

### Description:
I import less file in app.js 

`import './theme/iview/index.less';`

Error: 
![image](https://user-images.githubusercontent.com/7932853/28310016-ac84af6a-6bdd-11e7-959b-4de14748ac2c.png)

**Comment by JeffreyWay** [comment]
When you use `mix.less()`, we will automatically install the necessary dependencies. In your case, though, we have no way of knowing. So you need to run:

```
npm install less less-loader --save-dev
```

And you should be good to go.
