### ISSUE TITLE
Cannot resolve babel-loader and sass-loader

### ISSUE THREAD

**Issue by journeyman73** [JeffreyWay/laravel-mix#1011]
I have updated my node_modules and now I cannot process my styles and js. I get cannot resolve babel-loader and sass-loader errors, they have been downloaded into laravel mix node_module folder

I have also done a fresh install of laravel 5.4 and I get the same issue.

Any ideas on why?

Cheers

**Comment by JeffreyWay** [comment]
Not without seeing the info from the issue template that you deleted.

**Comment by nanadjei2** [comment]
Am getting the same error `                                                                                                                             
ERROR in ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 
form-object-rest-spread"]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./resources/assets/js/comp
Module build failed: SyntaxError: c:/xampp/htdocs/L5.5/resources/assets/js/components/Form.vue: this is a reserved word (5:3)`
