### ISSUE TITLE
mix.inProduction is true when npm run dev

### ISSUE THREAD

**Issue by mkarnicki** [JeffreyWay/laravel-mix#1014]
- Laravel Mix Version: 1.0.7 (`npm list --depth=0`)
- Node Version (`node -v`): 7.2.0
- NPM Version (`npm -v`): 5.0.3
- OS: OS X 10.11.6

### Description:

When I run `npm run dev` mix.inProduction returns true.

### Steps To Reproduce:

webpack.mix.js:

```
const { mix } = require('laravel-mix')

if (mix.inProduction) {
    console.log('WTF')
} else {
    console.log('not in production')
}
```

You'll see WTF logged in console, instead of 'not in production'.

Thank :)

**Comment by mkarnicki** [comment]
So lame... closing issue.

mix.inProduction**()**

**Comment by fbens** [comment]
TypeError: mix.inProduction is not a function

**Comment by DanLaufer** [comment]
`if(process.env.NODE_ENV == 'development') {` works for me instead.
