### ISSUE TITLE
Copying a dot file such as `.htaccess`

### ISSUE THREAD

**Issue by u01jmg3** [JeffreyWay/laravel-mix#1015]
- Laravel Mix Version: `1.2.2`
- Node Version `6.9.4`
- NPM Version `3.10.10`
- OS: Windows

### Description:

How to copy a dot file such `.htaccess` using Mix

### Steps To Reproduce:

Previously in Elixir this worked: `mix.copy('resources/assets/*.htaccess', elixir.config.publicPath + '/')`.

However, trying the same in Mix (`mix.copy('resources/assets/*.htaccess', publicPath + '/')`), gives no matches.

Is there a new syntax to follow?

**Comment by VinceG** [comment]
@u01jmg3 
```
mix.copy('resources/assets/.htaccess', publicPath + '/.htaccess')
```
Try that. you have to specify the destination file as well for hidden files (or dot files).

**Comment by u01jmg3** [comment]
Works a treat, thanks
