### ISSUE TITLE
disableSuccessNotifications() method is not working on standaloneSass changes

### ISSUE THREAD

**Issue by zacksmash** [JeffreyWay/laravel-mix#1017]
- Laravel Mix Version: 1.2.2
- Node Version (`node -v`): 8.1.4
- NPM Version (`npm -v`): 5.3.0
- OS: macOS 10.12.5

### Description:
Using the `standaloneSass()` method in combination with the `disableSuccessNotifications()` method is not suppressing success notifications

### Steps To Reproduce:

Compile some Sass using the `standaloneSass()` method in combination with the `disableSuccessNotifications()` which will result in you still receiving notifications.

**Comment by JeffreyWay** [comment]
Can confirm. I'll fix this soon.

**Comment by JeffreyWay** [comment]
Fixed. Will be in next tagged release.

**Comment by byustephen** [comment]
Thanks for fixing this. I can confirm that `disableSuccessNotifications()` works on Laravel 5.7.
