### ISSUE TITLE
Image references within Blade templates are not being recognized during build

### ISSUE THREAD

**Issue by andrade1379** [JeffreyWay/laravel-mix#1018]
- Laravel Mix Version: 1.2.3
- Node Version (`node -v`): 8.1.4
- NPM Version (`npm -v`): 5.0.3
- OS: OSX El Capitan

### Description:
I have a fresh install of Laravel and within my blade templates I have references to an image like so:
```
<a class="navbar-brand" href="#"><img alt="Logo" src="{{ URL::asset('images/logo.png') }}"></a>
```
I have the image in:
```
resources
    - assets
        - images > logo.png
```
But when I run `npm run watch` Or `npm run dev` all other image references that I have within CSS and or in a .vue file get optimized and moved into
```
public
    - images
```
except for the image I am pointing to within my blade template. Is there a way to get webpack to parse blade templates for any image references? Or is there a loader that is blade specific.

Or does this need to be a manual process of adding the image to the public directory myself? or to use mix.copy() to copy that directory when the build is run.

Thank you

**Comment by devcircus** [comment]
That asset helper is referencing public/images/logo.png, a non-existent image.  If I'm not mistaken, in order for an image to be handled by mix and referenced correctly, it must be used in a file managed by webpack / mix. If you have images that aren't referenced in css, scss, less, js, etc., that you also want moved, you need to use mix.copy.

**Comment by andrade1379** [comment]
Right... I figured that much but was wondering if there was any plan on creating a blade-loader to check for file formats with .blade? Thanks guys!

**Comment by ashish-czone** [comment]
I think @andrade1379 has a valid point. I am wondering the same thing. 
Clearly there will be many cases when a .css file will only be required in a particular .blade file. Right now, it doesn't get processed by mix. Any plan of a 'blade-loader' to include scss and image files used in .blade templates?

**Comment by strarsis** [comment]
+1 - also for srcset/sizes img elements.

**Comment by 8ctopus** [comment]
A bit late to the show, but did anyone build that plugin?

**Comment by strarsis** [comment]
@8ctopus: There are two webpack loaders:
https://www.npmjs.com/package/webpack-blade-native-loader (recently updated)
https://www.npmjs.com/package/webpack-blade-loader

But can one of these be configured to handle the image URLs?

**Comment by 8ctopus** [comment]
@strarsis Thank you, I'll have a look at those.
