### ISSUE TITLE
How to set up to allow output support umd

### ISSUE THREAD

**Issue by sinchang** [JeffreyWay/laravel-mix#102]
I'm writing a javascript library need support umd.

official webpack setting:
```
output: {
    path: __dirname + '/lib',
    filename: outputFile,
    library: libraryName,
    libraryTarget: 'umd',
    umdNamedDefine: true
  },
```

and in laravel-mix, how to set?

**Comment by canying1** [comment]
so do I

**Comment by cretueusebiu** [comment]
Use the [mix.webpackConfig](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/quick-webpack-configuration.md):

```javascript
mix.js('src/main.js', 'dist/libraryName.js')

mix.webpackConfig({
  output: {
    library: 'libraryName',
    libraryTarget: 'umd',
    umdNamedDefine: true
  }
})
```

**Comment by canying1** [comment]
thacks

**Comment by lichnow** [comment]
@cretueusebiu it not work when use mix.less or mix.stylus ,because of the multiple entries ,another entry is css file!

**Comment by uttam-p** [comment]
Thanks a lot cretueusebiu
