### ISSUE TITLE
Request to add some options

### ISSUE THREAD

**Issue by EmranAhmed** [JeffreyWay/laravel-mix#1020]
I don't want to disable OS notifications but I need to change only notification `title` and `image`, it will be great if I can do this from `webpack.mix.js` and change jpg, gif, png public path. Because I am developing a wordpress plugin with laravel-mix so absolute path of images from will not help. 

I don't want to make `processCssUrls: false` on sass because I also need to copy image/fonts from node_modules to specific directory :)

Thank you

**Comment by JeffreyWay** [comment]
I think your usecase might be pretty rare, unfortunately. So I don't think we'll expose the option to configure that.

**Comment by farrance** [comment]
For anyone still wanting to do this, there is a workaround.

Use mix in your webpack.mix.js to disable notifications.

```
// Disable notification as we'll do custom ones later
mix.disableNotifications();
```

Require the webpack-notifier into your webpack.mix.js

```
// Require the notifier
let WebpackNotifierPlugin = require( 'webpack-notifier' );
```

Use the webpackConfig helper to re-include the plugin with your own settings.

```
mix.webpackConfig( {
    
    plugins: [
        new WebpackNotifierPlugin( {
            title: 'Your fancy title',
            alwaysNotify: true,
            contentImage: '/path/to/icon.png'
        } )
    ]

} );
```
