### ISSUE TITLE
Webpack require

### ISSUE THREAD

**Issue by xakzona** [JeffreyWay/laravel-mix#1027]
- Laravel Mix Version: 1.0.7
Then want to use webpack asynchronius require method like
`require(['script])` it will create some file in my public folder (for example, /public/9.js).
How can I define other output folder for this files? ("public/js" my path)

**Comment by JeffreyWay** [comment]
We have a PR that fixes this, so closing for now.

**Comment by xakzona** [comment]
Hello, sorry again, have you fixed this issue?
