### ISSUE TITLE
Confirm message

### ISSUE THREAD

**Issue by andre-dw** [JeffreyWay/laravel-mix#1029]
Is there some way to show a confirm message when compiling production assets?

I'm using the MIX_ prefix in my .env variables for changes in the api url.
I want to show a confirm message to ask if you already did this before building the production assets.

This was my idea but when i do this mix doesn't wait for the prompt but just thinks there is nothing to compile so stops the process.
```
let mix = require('laravel-mix');
let inquirer = require('inquirer');

inquirer.prompt([{ type: 'confirm', name: 'env', message: 'question?'}], function( answers ) {
 // if no stop

// if yes
    mix.setPublicPath('./')
 	  .js('resources/assets/js/web.js', 'public/js')
	  .sass('resources/assets/sass/web.scss', 'public/css')
	  .sass('resources/assets/sass/bootstrap.scss', 'public/css')
          .version();
});

```

**Comment by JeffreyWay** [comment]
I'm not sure honestly. Could be an async issue. Either way, not really a Mix issue.

**Comment by andre-dw** [comment]
@JeffreyWay No not an issue. More a question. Don't know how to label that or where to ask.
