### ISSUE TITLE
Vue packages version mismatch

### ISSUE THREAD

**Issue by guemidiborhane** [JeffreyWay/laravel-mix#103]
I'm trying to switch a project from Elixir to Mix everything was working fine before the switch but now that i installed the packages and added the scripts it shows me an error about the vue-loader version mismatch

```
ERROR in ./app/resources/js/components/navbar.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.0.5
- vue-template-compiler@2.1.8

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
```

Thank you in advance.

**Comment by JeffreyWay** [comment]
Bumping your Vue dependency should fix it.

**Comment by guemidiborhane** [comment]
fixed the issue by removing the node_modules directory and running yarn to install all the dependencies.
