### ISSUE TITLE
mix.scripts/styles/combine() should accept a folder

### ISSUE THREAD

**Issue by JeffreyWay** [JeffreyWay/laravel-mix#1030]
Just realized that you can't pass a folder path to `mix.scripts()`, `mix.styles()`, or `mix.combine()`. We need to add support for this.

**Comment by decadence** [comment]
@JeffreyWay Is this recursive or not? AFAIK `**/*` usually means recursive.
And how does it handle case when we have css, js and others files in one folder?
Thanks.

**Comment by JeffreyWay** [comment]
It's recursive.

You can do `mix.scripts('folder/path')`, which will combine all nested files. Or `mix.scripts('folder/path/*.js')` will limit it to only JS files.

**Comment by decadence** [comment]
Thanks
