### ISSUE TITLE
[Improvement] Run Specific Mix Task Only

### ISSUE THREAD

**Issue by bloggervista** [JeffreyWay/laravel-mix#1032]
For many user with slow environment is it possible to run certain task only. 

Like running sass only not javascript portion using flags like --sass instead of going to webpack.mix file and commenting javascript portion and fixing semicolons?

I found mix takes around 4-5 seconds in ssd but takes huge time without ssd so is it possible like it is possible to run specific test only in phpunit.

Thank you

**Comment by ankurk91** [comment]
gulp and webpack runs differently. Laravel mix uses webpack and you can not run webpack task individually.
You can try watch mode -
```
npm run watch
```
for incremental builds. watch mode is quite fast than ``npm run dev``

**Comment by JeffreyWay** [comment]
Agree with @ankurk91.
