### ISSUE TITLE
'Watch mode' not working with version 1.3.0

### ISSUE THREAD

**Issue by SquareBeard** [JeffreyWay/laravel-mix#1039]
Hello, since version 1.3.0 whenever I modify a watched file, I get the "build successful" message but the resulting file has not changed. It works if I manually relaunch the whole compilation.
In case it's relevant, I'm using Windows.
Reinstalling v1.2.2 fixed the issue.

**Comment by zishanj** [comment]
Same issue here, it even refreshes my browser but it loads old files.

**Comment by MadMikeyB** [comment]
Related? https://github.com/webpack/enhanced-resolve/issues/97

**Comment by JeffreyWay** [comment]
Yeah, I expect it to be related to that enhanced-resolve issue. This is now fixed in https://github.com/webpack/enhanced-resolve/releases/tag/v3.4.1, so do an npm update and it should be resolved.
