### ISSUE TITLE
Multiple sass - manifest.json

### ISSUE THREAD

**Issue by iulyanp** [JeffreyWay/laravel-mix#104]
Hello,

I'm playing with this package and I found an issue with v0.4.0.
When I'm compiling .sass() multiple times the files are compiled correctly, but in the manifest.json file, I have only the last sass file.

For example:
```
mix
    .setPublicPath('web/')
    .js('assets/js/app.js', 'js')
    .js('assets/js/test.js', 'js')
    .js([
        'assets/js/config.js',
        'assets/js/options.js',
    ], 'js/combined.js')
    .sass('assets/sass/app.scss', 'css')
    .sass('assets/sass/styles.scss', 'css/module')
    .version()
;
```
The manifest.json file is:
```
{
  "app.css": "css/module/styles.45412ab64431b1666506.css",
  "app.js": "js/app.9d8dabd2d8595e403a18.js",
  "combined.js": "js/combined.a0c5bca274c7728b1589.js",
  "test.js": "js/test.a739dbab7c7b445e07ae.js",
 }
```
The same without versioning.
```
{
  "app.css": "css/module/style.css"
  "app.js": "js/app.js"
  "combined.js": "js/combined.js"
  "test.js": "js/test.js"
}
```
As you can see, in the manifest.json file, the `app.css` key has "css/module/style.css" value instead of "css/app.css".

Best regards,

**Comment by JeffreyWay** [comment]
I'm fixing this right now.

**Comment by eblin** [comment]
I had the same issue, I submitted a PR #111  for this, hopefully it gets merged, but if it doesn't take a look at the commit: https://github.com/eblin/laravel-mix/commit/218105fd10fd57dcc8446942e42dd332b822bb9c

**Comment by JeffreyWay** [comment]
This is fixed in master right now. I'll tag it soon.

**Comment by iulyanp** [comment]
Thank you @JeffreyWay!!
