### ISSUE TITLE
ModuleConcatenationPlugin should only on production build

### ISSUE THREAD

**Issue by hinaloe** [JeffreyWay/laravel-mix#1040]
- Laravel Mix Version: 1.3.0
- Node Version (`node -v`): 6.11.1
- NPM Version (`npm -v`): 5.3.0
- OS: OSX 10.11

### Description:
ModuleConcatenationPlugin looks have memory leak issue. in `watch` or hmr, I sometime crash with memory leak. It should only use on `inProductiton`

**Comment by JeffreyWay** [comment]
Done and tagged in https://github.com/JeffreyWay/laravel-mix/commit/32a564e9f5d1f021d597bcd53b7246e5e964dc7a
