### ISSUE TITLE
browserSync options

### ISSUE THREAD

**Issue by atilkan** [JeffreyWay/laravel-mix#1041]
- Laravel Mix Version: 1.3.0
- Node Version : 8.0.0
- NPM Version : 5.3.0
- OS: Mac OS X

### Description:
I am trying to setup a standalone dev environment without using laravel. I get error when i run this command  : `npm run watch`
The line causes the problem is `server: {baseDir: 'dev'}` 
Notification window says **Build Successful** but terminal throws error.

### This is **working** _webpack.mix.js_
```
mix.js('src/js/main.js', 'dev/js')
    .stylus('src/stylus/main.styl', 'dev/css')
    .browserSync({
        port:'3000'
    });
```
### This is **not working** _webpack.mix.js_
```
mix.js('src/js/main.js', 'dev/js')
    .stylus('src/stylus/main.styl', 'dev/css')
    .browserSync({
        port:'3000',
        server: {baseDir: 'dev'} // this is the only difference
    });
```

### This is **error log** from npm
```
Invalid config. You cannot specify both server & proxy options.    **I don't do that**
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webapp@1.0.0 watch: `NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webapp@1.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by webmarkelov** [comment]
```You cannot specify both server & proxy options```
Pass in the property **proxy**  a value **false**
```javascript
.browserSync({
        proxy: false,
        port:'3000',
        server: {baseDir: 'dev'} // this is the only difference
    });

```

**Comment by atilkan** [comment]
@webmarkelov **I don't specify both server & proxy.** I understand it is not me passing the proxy. The defaults. Thank you for clearing out.
