### ISSUE TITLE
cant copy any file to another location in then api after run copy task!

### ISSUE THREAD

**Issue by lichnow** [JeffreyWay/laravel-mix#1043]
should `push` the `CustomTasksPlugin` before `BuildCallbackPlugin` to let `then` api to build after compile before `copy` task

my mix task

```
mix
	.setResourceRoot('/' + theme + '/')
	.setPublicPath(compile)
	.js('assets/scripts/app.js', 'js')
	.sass('assets/styles/app.scss', 'css')
	.copyDirectory('assets/images', 'dist/images')
	.then((stats) => {
		if (fs.existsSync(paths.public) && fs.statSync(paths.public).isDirectory()) {
			fsEx.removeSync(paths.public);
		}
		fsEx.copySync(paths.compile, paths.public);
	});
```

after I copy images to dist/images,it cant copy dist/images to public/default/images
,because the customtasksplugin pushed after buildcallbackplugin, and i solve it like this

```
// webpack-plugins.js
plugins.push(
        new CustomTasksPlugin()
    );

    plugins.push(
        new BuildCallbackPlugin(stats => Mix.dispatch('build', stats))
    );
```
like this,please change the code,thanks

**Comment by JeffreyWay** [comment]
Which version of Mix do you have installed? You should be able to copy images to dist/images, and then copy dist/images to public/default/images just fine in Mix 1.0+.

**Comment by lichnow** [comment]
```
You should be able to copy images to dist/images, and then copy dist/images to public/default/images
```

this work fine,but I think `then` task should run after `copy` task,because copy `task`  usually is a compile task same as other webpack task ,like less-loader task,commonplugin task...
