### ISSUE TITLE
HMR Files Not Found

### ISSUE THREAD

**Issue by ellisio** [JeffreyWay/laravel-mix#1044]
- Laravel Mix Version: 1.3.0
- Node Version (`node -v`): v8.2.0
- NPM Version (`npm -v`): 5.3.0
- OS: macOS

### Description:

When I attempt to run `yarn run hot` with the default configuration, HMR is _not_ compiling JS or CSS when attempting to load http://localhost:8080/css/app.css, or http://localhost:8080/js/app.js.

Nothing has changed since I finished working on Friday. No `yarn upgrades`, no `composer updates`, etc. Everything is identical to my working environment as of Friday.

This is the error message in full:

```
ERROR

The requested URL could not be retrieved

The following error was encountered while trying to retrieve the URL: /js/app.js

Invalid URL

Some aspect of the requested URL is incorrect.

Some possible problems are:

Missing or incorrect access protocol (should be http:// or similar)

Missing hostname

Illegal double-escape in the URL-Path

Illegal character in hostname; underscores are not allowed.

Your cache administrator is webmaster.
```

This is our `webpack.min.js`:

```
const { mix } = require('laravel-mix');

/**
 * Configuration
 */
if (process.env.NODE_ENV === 'production') {
    mix.disableNotifications();
}

/**
 * SCSS Compilation
 */
mix.sass('resources/assets/sass/app.scss', 'public/css');

/**
 * JavaScript Autoloading
 *
 * @see https://github.com/JeffreyWay/laravel-mix/blob/master/docs/autoloading.md
 */
mix.autoload({
    jquery: ['$', 'window.jQuery', 'jQuery', 'jquery'],
    tether: ['window.Tether', 'Tether'],
    'tether-shepherd': ['Shepherd']
});

/**
 * JavaScript Compilation
 *
 * > Compilation
 * @see https://github.com/JeffreyWay/laravel-mix/blob/master/docs/mixjs.md
 *
 * > Extraction
 * @see https://github.com/JeffreyWay/laravel-mix/blob/master/docs/extract.md
 */
mix.js('resources/assets/js/app.js', 'public/js').extract([
    // Core Libraries
    'lodash',
    'axios',
    'promise',
    'moment',
    'moment-timezone',

    // jQuery/Bootstrap
    'jquery',
    'jquery-ui',
    'jquery.payment',
    'jquery.phone',
    'bootstrap',

    // Tether/Shepherd
    'tether',
    'tether-shepherd',

    // Vue
    'vue',
    'vuex',
    'vue-router',
    'vue-directive-tooltip-alt',
    'vue-js-toggle-button',
    'emoji-mart-vue',

    // Laravel Echo
    'pusher-js',
    'laravel-echo',

    // Sentry Error Handling
    'raven-js',
    'raven-js/plugins/vue',

    // Vendor Libraries
    'autosize',
    'clipboard',
    'deep-equal',
    'howler',
    'js-cookie',
    'selectize',
    'taggle',
    'uuid'
]);

/**
 * Copy Assets
 */
mix.copy('node_modules/push.js/serviceWorker.js', 'public/js/serviceWorker.js');
```

**Comment by ellisio** [comment]
I kid you not, this was fixed by rebooting my computer _twice_. This is how I feel right now:

![image](https://user-images.githubusercontent.com/127468/28534263-5f7f6492-705d-11e7-8def-21b5ee34242b.png)

**Comment by alanpaulprice** [comment]
I had the same issue. My app was running on port 80 (default), but it was expecting the js and css files on port 8080. The issue was only present when running `mix watch` with the `--hot` flag. `mix watch` alone worked fine.

For me, it was related to having multiple docker containers running on the same port simultaneously. I fixed it by killing the other docker containers (`docker-compose down`), rebuilding (`docker-compose build`) my app's container, before spinning it up again (`docker-compose up`).
