### ISSUE TITLE
ExtractTextPlugin cant get css file

### ISSUE THREAD

**Issue by lichnow** [JeffreyWay/laravel-mix#1047]
use `mix.sass` or `mix.less` ,will add to style src to the first entry, and it auto push to `Config.preprocessors` which use `ExtractTextPlugin`,but it will not reload on change with
`npm run hot`,becuase ` ExtractTextPlugin` not work in hmr model

Other problem is the library model be `umd`,`mix.sass` and `mix.less` add the style src file to first entry ,this will brock the `umd` script file.

So I `require('./../sass/app.scss')` in `app.js`,hmr hot reload work,but cant generate css file by `ExtractTextPlugin`

The suggestion is remove `sass` and `less` ,`stylus` api,and let sass,less or other style file be `require` in script file, and check if is hot  model or not.if in hot model,not use ` ExtractTextPlugin`,else use ` ExtractTextPlugin`,this useful to do perfect compile by webpack!

**Comment by ruchern** [comment]
Can you post your configuration and the package versions?

**Comment by lichnow** [comment]
@ruchern 

My config like this,is laravel default config

```
let mix = require('laravel-mix');

mix
	.js('resources/assets/js/app.js', 'public/js')
	.sass('resources/assets/sass/app.scss', 'public/css');
```

now I change it like this

```
const ExtractTextPlugin = require("extract-text-webpack-plugin");
let mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */
if (!Mix.isUsing('hmr')) {
	mix.webpackConfig({
		module: {
			rules: [{
				test: /\.scss$/,
				use: ExtractTextPlugin.extract({
					fallback: "style-loader",
					use: ['css-loader', 'sass-loader']
				})
			}]
		},
		plugins: [
			new ExtractTextPlugin({
				filename: (getPath) => {
					return getPath('css/[name].css').replace('css//js', 'css');
				},
				allChunks: true
			})
		]
	});
}

mix
	.js('resources/assets/js/app.js', 'public/js')
	// .sass('resources/assets/sass/app.scss', 'public/css');
```
and app.js

```
if (process.env.NODE_ENV === 'development') {
	if (module.hot) {
		module.hot.accept();
	}
}
require('./../sass/app.scss');
require('./bootstrap');
```

and index.blade.php

```
@if (!file_exists(public_path('hot')))
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">
    @endif
```

It works,so @JeffreyWay please and `ExtractTextPlugin` to `laravel-mix` not only vue-loader,and add a determine if or not is hmr model to check use inline or generate css.

finally,can add somethine to laravel `mix` function,thx your work!
