### ISSUE TITLE
Vuex ...mapActions() syntaxt not working?

### ISSUE THREAD

**Issue by breadlesscode** [JeffreyWay/laravel-mix#105]
Hi guys,

https://vuex.vuejs.org/en/mutations.html#committing-mutations-in-components

this syntax does not work in laravel mix? It's too bad. 

Why laravel mix does not use buble-loader? Is bable the better choice?

Greetings to all

**Comment by taddis** [comment]
@breadlesscode 

`npm install --save-dev babel-plugin-transform-object-rest-spread`

And add this to your .babelrc

`{
   "plugins": ["transform-object-rest-spread"]
}`

https://babeljs.io/docs/plugins/transform-object-rest-spread/
