### ISSUE TITLE
Vendor CSS 

### ISSUE THREAD

**Issue by RomanMarkelov** [JeffreyWay/laravel-mix#1050]
- Laravel Mix Version: 1.3.1

### Description:

When I use any a vendor library, example the slick-carousel:
```js
export default (selector, options = {}) => {

  if (!selector) {
    throw new Error('Selector is empty');
  }

  if (!(selector instanceof jQuery)) {
    selector = $(selector);
  }

  if (!selector.length) {
    return;
  }

  require.ensure([], require => {
    require('slick-carousel/slick/slick.min.js');
    require('slick-carousel/slick/slick.css');
    require('slick-carousel/slick/slick-theme.css');

    $(selector).slick(options);
  });
};

```
I get some structure:
<pre><code>|____dist
| |____images
| | |____vendor
| | | |____slick-carousel
| | | | |____slick
| | | | | |____ajax-loader.gif
</code></pre>

In a browser the style-loader append vendor styles down inside head element:
```html
<head>
    <link rel="stylesheet" href="/public/css/main.css">
    <style type="text/css">/* Slider */
        .slick-loading .slick-list
             {
                background: #fff url(/images/vendor/slick-carousel/slick/ajax-loader.gif) center center no-repeat;
              }
            ....
     </style>
</head>
```

### Troubles:
1) Main.css has a weak cascade before vendor styles 
2) As I use other a framework not the laravel I have other file structure and me need write rules in nginx.conf or .htaccess for right access to /images/vendor/...

### Solution:
1) Add in mix a new feature which extracting vendors styles in vendor.css
```js
   mix.setRelativePath('../')
```

```html
<head>
    <!-- all vendor styles move in the vendor.css -->
    <link rel="stylesheet" href="/public/css/vendor.css">
    <link rel="stylesheet" href="/public/css/main.css">
</head>
```
in vendor.css

```css
  .slick-loading .slick-list
     {
         background: #fff url(../images/vendor/slick-carousel/slick/ajax-loader.gif) center center no-repeat;
      }
     ....
```

**Comment by webmarkelov** [comment]
Solution how resolve relative, absolute paths to files [here](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/css-preprocessors.md#an-examplel)

**Comment by webmarkelov** [comment]
Add a [option](https://github.com/webpack-contrib/style-loader#insertat) in [CSS Compilation ](https://github.com/JeffreyWay/laravel-mix/blob/master/src/builder/webpack-rules.js#L39l) it is fix the trouble cascade

**Comment by webmarkelov** [comment]
[PR](https://github.com/JeffreyWay/laravel-mix/pull/1070) rejected but the issue open. Any time is style-loader can break layout when inserting css snippets after main.css file. @JeffreyWay  What do you suggest to resolve the problem?

**Comment by hellogerard** [comment]
I _think_ this is the same issue that I want. But in any case...

I am looking for a way to extract vendor CSS into its own file, just like I can do so with JS. Currently, I can `import` a vendor CSS file and it gets rendered into the `head` as inline styles. This works, but I would rather extract that text into a `vendor.css` file. I didn't see a way to do this. Is this possible?
