### ISSUE TITLE
[1.4.2] Code splitting chunks location path is wrong when loaded in the browser

### ISSUE THREAD

**Issue by santigarcor** [JeffreyWay/laravel-mix#1055]
- Laravel Mix Version: 1.4.2
- Node Version: 6.11.1
- NPM Version: 3.10.10
- OS: Ubuntu 16.04

### Description:
I'm using code splitting in vue, and when i run my app in the browser it doesn't find the appropriate chunk file because it doesn't use the absolute path (`/js/0.js`) but the relative path(`js/0.js`). It work when i add the `publicPath: '/'` to the webpackConfig.

### Steps To Reproduce:
In the webpack.mix.js file add:
```js
.webpackConfig({
  output: {
    chunkFilename: 'js/[name].[chunkhash].js'
  },
});
```
And in the app.js file: 
```js
Vue.component('some-component', () => import('./components/SomeComponent.vue'));
```
Import the app.js, manifest.js in the view and test it.

**Comment by micbenner** [comment]
This may not be related...  for me the versioned chunks are put into the public folder when they should be in the public/js folder.

**Comment by michaeldzjap** [comment]
@micbenner Yes, experiencing the same thing. I have specified my output path as `public/js` in webpack.mix.js, but chunks are placed in `public`.

**Comment by ankurk91** [comment]
related #936
