### ISSUE TITLE
How to prevent `public` folder has been created

### ISSUE THREAD

**Issue by dinhquochan** [JeffreyWay/laravel-mix#1056]
- Laravel Mix Version: laravel-mix@1.4.2
- Node Version 8.1.2
- NPM Version 5.1
- OS: MacOS/Homebrew

![screen shot 2017-07-27 at 11 51 00](https://user-images.githubusercontent.com/9979458/28654930-42d08292-72c2-11e7-8b49-894bd85e1fd2.png)

[FIXED]

> Delete `node_modules` folder and `package-lock.json` file and run `npm install` again. npm v5 has an issue with deleting packages. In fact, [npm@5.1.0](https://github.com/npm/npm/issues/17929) had major problems.

NEW PROBLEM: [[SEE COMMENT](#issuecomment-318296114)]

**Comment by ruchern** [comment]
Delete `node_modules` folder and `package-lock.json` file and run `npm install` again. npm v5 has an issue with deleting packages. In fact, npm@5.1.0 had major problems.

**Comment by dinhquochan** [comment]
I fixed, but. My webpack.mix.js

```js
let mix = require('laravel-mix');

mix.js('cnv/resources/assets/js/app.js', 'assets/js')
    .sass('cnv/resources/assets/sass/app.scss', 'assets/css');
```

not `public` but after build, `public` folder has been created? how to fix?

**Comment by JeffreyWay** [comment]
@dinhquochan You can use `mix.setPublicPath('')` to specify where your public directory root should be.
