### ISSUE TITLE
How to add custom rules?

### ISSUE THREAD

**Issue by fearrr** [JeffreyWay/laravel-mix#1060]
- Laravel Mix Version: #.#.# (`npm list --depth=0`) latest
- Node Version (`node -v`): v8.1.4
- NPM Version (`npm -v`): 5.3.0
- OS: Windows 10

### Description:
Some scripts do not have the correct preparation for modular assembly. It is necessary to introduce here such fix, for the `pace-progress` package, how i can to do?
```
{ 
    test: require.resolve("pace-progress"), 
    loader: "imports?define=>false" 
}
```

I tried to do so, but got an error
```
mix
    .js  ('resources/assets/js/app.js',              'public/js')
    .sass('resources/assets/sass/app.scss',          'public/css')

    .webpackConfig({
        module: {
            rules: [
                {
                    test: require.resolve("pace-progress"),
                    loader: "imports?define=>false"
                }
            ]
        }
    })
```

**Comment by webmarkelov** [comment]
Hi, @fearrr ! Try use [null-loader](https://github.com/webpack-contrib/null-loader)

**Comment by nonamez** [comment]
did it work?
