### ISSUE TITLE
npm run dev error in laravel 5.4. Please kindly help...thanks

### ISSUE THREAD

**Issue by hengsunrith** [JeffreyWay/laravel-mix#1069]
0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.nvm/versions/node/v4.7.3/bin/node',
1 verbose cli   '/home/ubuntu/.nvm/versions/node/v4.7.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@2.15.11
3 info using node@v4.7.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev @
6 info dev @
7 verbose unsafe-perm in lifecycle true
8 info @ Failed to exec dev script
9 verbose stack Error: @ dev: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
9 verbose stack Exit status 126
9 verbose stack     at EventEmitter.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.7.3/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.7.3/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:854:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
10 verbose pkgid @
11 verbose cwd /home/ubuntu/workspace
12 error Linux 4.9.17-c9
13 error argv "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/node" "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/npm" "run" "dev"
14 error node v4.7.3
15 error npm  v2.15.11
16 error code ELIFECYCLE
17 error @ dev: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
17 error Exit status 126
18 error Failed at the @ dev script 'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
18 error This is most likely a problem with the  package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by ruchern** [comment]
npm and node are seriously outdated.

**Comment by hengsunrith** [comment]
Can u recommend it? I am still young with it...thanks

**Comment by ruchern** [comment]
`npm i -g npm` and `sudo apt update && sudo apt upgrade nodejs`

**Comment by hengsunrith** [comment]
Really thanks for ur help :)
