### ISSUE TITLE
Undefined function mix()

### ISSUE THREAD

**Issue by stevepop** [JeffreyWay/laravel-mix#107]
I added the following to my blade layout
`<link rel="stylesheet" href="{{ mix('css/app.css') }}">`

I however got the following error;

`Call to undefined function mix() (View: resources/views/layouts/master.blade.php`

It however works when I chage 'mix' to 'elixir'. I though the main reason for using mix is to migrate from Elixir?

**Comment by kpilard** [comment]
mix isn't part of Laravel 5.3. You can add the mix method yourself.

https://github.com/JeffreyWay/laravel-mix-example/blob/master/app/mix.php
https://github.com/JeffreyWay/laravel-mix-example/blob/master/composer.json
