### ISSUE TITLE
Jquery works at first compilance, but after updating sass, it crashs. 

### ISSUE THREAD

**Issue by yammadev** [JeffreyWay/laravel-mix#1073]
- Laravel Mix Version:  `^1.4`
- Node Version (`6.11.0`): 
- NPM Version (`5.3.0`): 
- OS: Windows 

### Description:
When I use `npm run watch` in my `Laravel` project, `jquery` works good, however, when I update some `sass` file and run the website again, `jquery` now it's not detected. If I update a `js` file, it works again, and If I repeat updating `sass` it doesn't work again. 

### Steps To Reproduce:
1. `npm run watch`
2. Check the website and `jquery` works as expected. 
3. Update some `sass` file.
4. Check the browser and now the jquery does not work. 

I hope you can help me with this, thanks in advance.

**Comment by richardjkeys** [comment]
Having the same issue, but missing Axios. EVERY time the SCSS file is saved. Think this might be related: https://github.com/webpack/webpack/issues/959
