### ISSUE TITLE
Exemple of HMR (hot module replacement) with React

### ISSUE THREAD

**Issue by ricardovf** [JeffreyWay/laravel-mix#1075]
Took me some time to make this work, so i share here how i made it work with laravel-mix 1.4.0, just for reference if someone is looking. The reference i took from here: http://gaearon.github.io/react-hot-loader/getstarted/

This will enable HMR when using React, keeping the internal state of the components.

Laravel-mix did a great work, it almost work out of the box.

`````
yarn add babel-preset-react browser-sync browser-sync-webpack-plugin react react-dom react-router
`````
Add to your .babelrc (without this, the internal state is not kept):

`````
{
  "plugins": [ "react-hot-loader/babel" ]
}
`````

Your app.jsx should look something like this:

`````
import 'react-hot-loader/patch';
import React from 'react';
import ReactDOM from 'react-dom';
import {AppContainer} from 'react-hot-loader';
import ExempleMainComponentApp from './Components/ExempleMainComponentApp';

const render = Component => {
  ReactDOM.render(
      <AppContainer>
          <Component/>
      </AppContainer>,
      document.getElementById('app-root')
  );
};

render(ExempleMainComponentApp);

if (process.env.NODE_ENV === 'development' && module.hot) {
  module.hot.accept('./Components/ExempleMainComponentApp', () => { render(ExempleMainComponentApp) });
}
`````

run and go to http://localhost:3000/
`````
yarn run hot
`````

**Comment by im-sunil** [comment]
Hello @ricardovf , I followed  steps,but  code HRM working ok,problem is **react state not preserving** ,
I followed what you mentioned,If possible can you provide you sample.

**Comment by ricardovf** [comment]
Are you using any lib to manage state? Probabily my version of laravel-mix is different, please look for some updated docs on hot reload
