### ISSUE TITLE
When run npm run dev, it is error. And I already update nodejs & npm. Please kindly help...Thanks.

### ISSUE THREAD

**Issue by hengsunrith** [JeffreyWay/laravel-mix#1078]
sunrith:~/workspace $ npm run dev

> @ dev /home/ubuntu/workspace
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/home/ubuntu/workspace/node_modules/laravel-mix/setup/webpack.config.js:1
(function (exports, require, module, __filename, __dirname) { let path = require('path');
                                                              ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireConfig (/home/ubuntu/workspace/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/ubuntu/workspace/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
sunrith:~/workspace $

**Comment by JeffreyWay** [comment]
The fact that you're getting this error...

```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

tells me that you do have an old version of Node installed. You deleted the issue template, so I can't say for sure, but that's my bet.

**Comment by hengsunrith** [comment]
Yes, sure JefferyWay. I have old version of node. Sorry for late reply.
