### ISSUE TITLE
extra file named 0.js

### ISSUE THREAD

**Issue by jkudish** [JeffreyWay/laravel-mix#108]
First of all, thanks a lot for putting this together @JeffreyWay, this is really awesome and it's making our lives so much easier already ❤️ 

I'm switching a non-Laravel, react app over to laravel-mix. I've got it working now, but I'm wondering about this extra `0.js` (and corresponding 0.js.map) file. Any idea what might be creating it?

```
> npm run build 

> cross-env NODE_ENV=production webpack --progress --hide-modules

 DONE  Compiled successfully in 34886ms

                                             Asset       Size  Chunks                    Chunk Names
                                           /app.js    2.53 MB       1  [emitted]  [big]  app
  fonts/icons.eot?25a32416abee198dd821b0b17a198a8f    76.5 kB          [emitted]         
  fonts/icons.ttf?1dc35d25e61d819a9c357074014867ab     153 kB          [emitted]         
 fonts/icons.woff?c8ddf1e5e5bf3682bc7bebf30f394148    90.4 kB          [emitted]         
fonts/icons.woff2?e6cf7c6ec7c2d6f670ae9d762604cb0b    71.9 kB          [emitted]         
                                             /0.js    65.3 kB       0  [emitted]         
  fonts/icons.svg?d7c639084f684d66a1bc66855d193ed8     392 kB          [emitted]  [big]  
                                       /styles.css     496 kB       1  [emitted]  [big]  app
                                         /0.js.map     470 kB       0  [emitted]         
                                       /app.js.map    12.4 MB       1  [emitted]         app
                                   /styles.css.map   88 bytes       1  [emitted]         app
                                     manifest.json  539 bytes          [emitted]         
```

Using Laravel mix v0.4.0 with webpack 2.2.0-rc.7

Here are my [config files](https://gist.github.com/jkudish/99df61d44747cc291dc2a8741efdc8a5)

Any ideas?

Thanks!

**Comment by fortael** [comment]
Most important is what in your **app.js**

[https://webpack.github.io/docs/code-splitting.html](https://webpack.github.io/docs/code-splitting.html)

**Comment by jkudish** [comment]
Thanks @fortael for pointing me in the right direction.

A polyfill that I was using was calling `require()` and causing the code splitting.

Turns out I didn't really need that polyfill anymore anyway, so I removed it, and now everything there's no more extra files created.
