### ISSUE TITLE
Syntax Error: Deleting local variable in strict mode

### ISSUE THREAD

**Issue by vov4ik08** [JeffreyWay/laravel-mix#1080]
Hello. For some scripts i see error
Syntax Error: Deleting local variable in strict mode
Please, help

**Comment by JeffreyWay** [comment]
I can't help when you didn't provide any information.

**Comment by Falcornus** [comment]
In my case this appears when I am trying to import an old library "jquery.prettyPhoto". 

How I can exclude this error ?

**Comment by vedmant** [comment]
I have the same problem, the package jquery.prettyPhoto itself is outdated and violates strict js rules, you can delete line: `delete settings;` in the source file to fix this.

**Comment by nynevi** [comment]
I guess we all came here because of prettyPhoto.

I hate having to modify vendor source files but I had to. thanks @vedmant
