### ISSUE TITLE
Laravel Mix breaks when moving laravel files into subdir after setting public path

### ISSUE THREAD

**Issue by driesrobeyns** [JeffreyWay/laravel-mix#1081]
- Laravel Mix Version: 1.4.2
- Node Version: 6.9.1
- NPM Version: 5.3.0
- OS: Windows 10

I am experiencing the same issue. Due to the limitation of the host one of my clients is using I was forced to organize my site as follows:

/public_html/warranty (for the public files)
/private_html/warranty (for all other files & folder related to laravel)

Laravel is running fine on the server but Mix is not due to the change in folders. Setting mix.publicPath(../../public_html_warranty) allows me to start the webpack server but none of the js files can be located on the server. (ie localhost:8080/js/app.js)

When running npm run production it will get stuck @ 95%.

When looking at the mix-manifest.json it is clear why:

```
"/D:/X Labs/productRegistration/public_html/warranty/D:/X Labs/productRegistration/public_html/warranty/js/app.js": 
"/D:/X Labs/productRegistration/public_html/warranty/D:/X Labs/productRegistration/public_html/warranty/js/app.js"
```
The paths are incorrect.

Steps to reproduce:

Install laravel
Move laravel files into subdir
Adjust publicPath var from subdir to public

> npm run hot

**Comment by TopFuel** [comment]
I was having a similar problem, [try this and see if it works for you](https://github.com/JeffreyWay/laravel-mix/issues/960#issuecomment-315992883).
