### ISSUE TITLE
mix() should not throw an exception in production.

### ISSUE THREAD

**Issue by adampatterson** [JeffreyWay/laravel-mix#1083]
- Laravel Mix Version: 1.2.2
- Node Version: v7.3.0
- NPM Version: v5.3.0
- OS: OSx 10.12.5

### Description:
First, I know that mix() is in Laravels Foundation. But I wanted feedback here first before posting this to Laravel.

I understand the value in knowing that an asset is missing and know that it can be resolved. What I am covering here is the severity of how mix() fails.

Throwing an exception over a file that might exist but didn't get versioned is a bit drastic.

We use Docker and Docker builds our assets so it's common to make a change and not re-run Mix before committing. My site will work perfectly fine without a number of included scripts that are loaded on all pages but if you throw that exception you essentially take down the entire site.

I would like to see the exception locally but all the page to function in production while possibly being broken or malfunctioning. If it's possible to send a notification or post a message to the error handler that would let sentry pick that up then that would be even better.

The other issue at least for me is that because a 500 error is thrown I have not been able to create a custom error page for it. Worked in 5.2 but not in 5.4 so our customers don't have any recourse. Again yes, we have error logging but that's not the point.

### Steps To Reproduce:

{{ mix('/static/css/base-not-versioned.css')}}

The exception is thrown.

**Comment by ruchern** [comment]
Yes, I saw your description but Laravel-Mix have nothing to do with `mix()` at all.

**Comment by adampatterson** [comment]
@ruchern Thanks! I will move this over there. It's confusing when an external package is part of a framework with complementary documentation and integrations.

ref laravel/framework#20355
