### ISSUE TITLE
How to pass options via CLI?

### ISSUE THREAD

**Issue by ameenross** [JeffreyWay/laravel-mix#1086]
- Laravel Mix Version: 0.12.1
- Node Version: 8.1.4
- NPM Version: 5.0.3
- OS: Ubuntu 16.04

### Description:

So I want to disable notifications. I can do that using `mix.disableNotifications()`, but that would mean I have to hardcode it in my `webpack.mix.js`. I don't want that. I want to have a separate run task in package.json which has notifications disabled. So how are you supposed to set notifications=false from CLI?

### Steps To Reproduce:

- Try to figure out how to pass notifications=false from CLI
- Fail

**Comment by panda-madness** [comment]
You have access to a global `process` object, which, among other thins, has an `argv` property with all command line arguments.

More here:
https://nodejs.org/docs/latest/api/process.html#process_process_argv

**Comment by ameenross** [comment]
Yeah, but I can't invent a CLI argument, because webpack will just tell me off: "Unkown argument: some-option"

**Comment by panda-madness** [comment]
A quick web search led me here:
https://github.com/webpack/webpack/issues/2254#issuecomment-203528744

**Comment by webmarkelov** [comment]
Webpack run in node.js environment and always can get access to global variables.

**Comment by ameenross** [comment]
If you don't understand the issue, don't reply. It only creates noise. My question is the other way around: how to set a variable, in this case configuration.

I have tried various things to no avail. I ended up setting an environment variable, and checking for it in my mix file, then passing it on. But that's a clunky workaround

On August 2, 2017 8:12:31 PM GMT+02:00, Roman Markelov <notifications@github.com> wrote:
>Webpack run in node.js environment and always can get access to global
>variables. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/JeffreyWay/laravel-mix/issues/1086#issuecomment-319753718

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by joshmanders** [comment]
> If you don't understand the issue, don't reply. It only creates noise. 

Yikes, no need to be rude, he's trying to help you.

> I have tried various things to no avail. I ended up setting an environment variable, and checking for it in my mix file, then passing it on. But that's a clunky workaround

This is your only option as laravel-mix uses webpack cli tool and that uses all args passed.

**Comment by ameenross** [comment]
Sorry about that, didn't mean to be rude.

Well I would expect to be able to do something webpack normally allows, like use `--define`. I would think it's possible to change Mix to use some object as default config to enable using define, wouldn't it? Or just add some CLI args, I read something about that being possible for webpack plugins.

In any case my question is mostly about documentation. I won't be the only one looking for a solution to this problem. If env vars and some custom code in your mix file is the only way then so be it. But it needs to be documented IMO.

On August 2, 2017 8:27:34 PM GMT+02:00, Josh Manders <notifications@github.com> wrote:
>> If you don't understand the issue, don't reply. It only creates
>noise. 
>
>Yikes, no need to be rude, he's trying to help you.
>
>> I have tried various things to no avail. I ended up setting an
>environment variable, and checking for it in my mix file, then passing
>it on. But that's a clunky workaround
>
>This is your only option as laravel-mix uses webpack cli tool and that
>uses all args passed.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/JeffreyWay/laravel-mix/issues/1086#issuecomment-319757734

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jackmu95** [comment]
I stumbled across the same problem and found a solution that worked quite well for me:
```js
const mix = require('laravel-mix');
const argv = require('yargs').argv;

...

if (argv.env.notifications === false) {
  mix.disableNotifications();
}
```

The command:
```bash
npm run development -- --env.notifications false
```

**Comment by ameenross** [comment]
That's almost the same I did: `npm run prod-silent`

Entry in package.json: `cross-env NODE_ENV=production MIX_NOTIFICATIONS=false node_modules/webpack/bin/webpack.js --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`

```js
// webpack.mix.js

// ...
if (process.env.MIX_NOTIFICATIONS == 'false') {
    mix.disableNotifications();
}
```
