### ISSUE TITLE
Save fonts and images to specific folders

### ISSUE THREAD

**Issue by MikeDynamic** [JeffreyWay/laravel-mix#1090]
Hi, 

I am using the latest Webpack and Laravel-mix version. 

I am new to both :) 

I am able to save the js and sass files to the folders that I require but have not been able to set the specific folders that I need the images and fonts to save too. 

This is a non Laravel build and I am trying to use it on an existing project that does not use the file structure recommended. 

Could someone please point me in the right direction. 

Thank you

**Comment by MikeDynamic** [comment]
I am using .copydirectory() to copy the assets file that is created to the correct folder. 
I this the correct way or is there an easier way?

**Comment by webmarkelov** [comment]
Hi, @MikeDynamic! I resolved similar task [here](https://github.com/JeffreyWay/laravel-mix/issues/1050l)

**Comment by MikeDynamic** [comment]
Thank you very much @webmarkelov. This is exactly what I was looking for!
