### ISSUE TITLE
hmr not working on fresh laravel 5.4 

### ISSUE THREAD

**Issue by terrylow** [JeffreyWay/laravel-mix#1091]
- Laravel Mix Version: 1.4.2
- Node Version (`node -v`):  v7.7.4
- NPM Version (`npm -v`):  4.1.2
- OS:  Windows 10

### Description:
hmr break when extract() and autoload() is being used, vue components not being render, other command such as
`npm run dev`,`npm run production` and `npm run watch` works perfectly, just`npm run hot` is not working.

It works, if i removed the extract() and autoload() statements

### Steps To Reproduce:

1. add the following lines to webpack.mix.js

`.extract(['jquery', 'axios', 'vue', 'lodash'])`
`.autoload({
        jquery: ['$', 'window.jQuery', 'jQuery', 'jquery'],
        vue: ['vue', 'window.Vue'],
        axios: ['axios', 'window.axios'],
        lodash: ['lodash', 'window._']
    })`
2. issue `npm run hot`

a git repo to reproduce the problem [here](https://github.com/terrylow/mix-hmr-issue-demo)

**Comment by ankurk91** [comment]
What do you mean by **break** did you get any error on terminal ?
Are you getting 404 for css or js  in developer console ?

Its working me, here is my wepack.mix.js
```
mix.js('resources/assets/js/app.js', 'public/js')
  .extract([
    'jquery',
    'bootstrap-sass',
    'axios',
    'vue',
    'lodash',
    'chart.js'
  ])
  .autoload({
    jquery: ['$', 'window.jQuery', 'jQuery'],
    lodash: ['_', 'window._'],
    vue: ['Vue', 'window.Vue'],
    axios: ['axios', 'window.axios'],
  })
  .sass('resources/assets/sass/vendor.scss', 'public/css')
  .sourceMaps(false)
  .disableNotifications();

// version does not work in hmr mode
if (process.env.npm_lifecycle_event !== 'hot') {
  mix.version()
}

```
just to remember that you should always access your virtual host (http://laravel.dev) not the `http://localhost:8080` in browser.

**Comment by matical** [comment]
90% sure he's talking about [this](https://github.com/JeffreyWay/laravel-mix/pull/1059). It's a Windows only issue, Linux (and probably OSX) runs fine regardless.

If extraction isn't being used, HMR and everything else is fine.
When using extraction, webpack's dev server will not serve up `vendor.js` at all (it'll return 404).

As a temporary workaround, you can specify a manual path to `vendor.js` as a 2nd argument to `extract()`.

```js
mix.extract(['vue'], 'public/js/vendor.js')
```

**Comment by terrylow** [comment]
@ankurk91 im access my vhost  correctly, and no error on terminal and browser console, but it seem webpack dev server is not running (no HMR log messages in the browser)

@matical your PR is working, that solve the problem, and hmr works again.
