### ISSUE TITLE
BrowserSync does not refresh on dd()

### ISSUE THREAD

**Issue by kennith** [JeffreyWay/laravel-mix#1093]
- Laravel Mix Version: 1.4.2
- Node Version (`node -v`): v6.10.0 
- NPM Version (`npm -v`): 3.10.10
- OS:  Windows 8 64-bit

### Description:
The browserSync does not refresh if the page returns with dd() because the browserSync js was not inserted on page without ```<html><body></body></html>``` tags.
``` <script async="" src="/browser-sync/browser-sync-client.js?v=2.18.13"></script>```

### Steps To Reproduce:
```
// Controller
// No auto refresh when file change
public function index() 
{
  dd('test');
}
```

**Comment by ruchern** [comment]
This seems to be a `Browsersync` issue and not Laravel Mix issue.

**Comment by ankurk91** [comment]
@kennith 
`dd` means dump and die.
BrowserSync requires a JS file to injected into page to work, dd will terminate the php process before injected that JS.

**Comment by kennith** [comment]
@ankurk91 BrowserSync inject JS after the body tag. In dd, the body tag does not exist. It only has the pre tag, therefore, JS was not injected.

In Laravel-Elixir, DD works well with BrowserSync and the BrowserSync support for dd function is added in pull request [#366](https://github.com/laravel/elixir/pull/366). I was hoping the same function will be supported in Mix as well out of the box. 

If anyone wants BrowserSync support for dd function in Mix, they can add  the following lines in their BrowserSync options in webpack.mix.js (credit to @jnbn) 

```
snippetOptions: {
  rule: {
	match: /(<\/body>|<\/pre>)/i,
	fn: function (snippet, match) {
		return snippet + match;
	}
  }
}
```

**Comment by ankurk91** [comment]
Maybe you can submit a PR. :)
