### ISSUE TITLE
Question  : Twigjs with laravrel-mix in standalone

### ISSUE THREAD

**Issue by paallaire** [JeffreyWay/laravel-mix#1094]
- Laravel Mix Version: #.#.# (`npm list --depth=0`) : 1.4.2
- Node Version (`node -v`):  v8.2.1
- NPM Version (`npm -v`): 5.3.0
- OS: Window 7

### Description:

I would like to add twigjs into laravrel-mix in standalone.

I found this loader (twig-loader) that seems do the job. (https://github.com/zimmo-be/twig-loader)

Previously I used gulp with gulp-twig. (https://www.npmjs.com/package/gulp-twig)

I try this ( below ) but nothing happens.
```
mix
  ...
  .webpackConfig(
  {
    module: {
      rules: [
        {
          test: /\.twig$/,
          loaders: "twig-loader"
        }
      ]
    }
  });
```

**Question**
How do I add a loader as a twig-loader in lavarel-mix in standalone (compiling  .twig => .html) ?

Here is my configuration of webpack.mix.js

```
mix
  .setPublicPath(path.normalize("public/dist"))
  .setResourceRoot("/dist/")
  .js('assets/scripts/main.js', 'scripts')
  .sass('assets/styles/main.scss', 'styles')
  .options({
    postCss: [
      require('lost')()
    ]
  })
  .browserSync({
    proxy: false,
    server: {
      baseDir: "./public/"
    },
    ghostMode: {
      clicks: true,
      links: true,
      forms: true,
      scroll: true
    },
    reloadDelay: 1000
  })
  .webpackConfig(
  {
    module: {
      rules: [
        {
          test: /\.twig$/,
          loaders: "twig-loader"
        }
      ]
    }
  });
```

**Comment by JeffreyWay** [comment]
You have it right. I just tested it out, and the template compiled properly. All I did was:

1. npm install twig-loader
2. Update webpack.mix.js

```js
let mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */


mix.js('resources/assets/js/app.js', 'js')
 .webpackConfig(
  {
    module: {
      rules: [
        {
          test: /\.twig$/,
          loaders: "twig-loader"
        }
      ]
    },
    node: {
        fs: "empty" // avoids error messages
    }
  });
```

3. Create a test file: `resources/assets/js/dialog.html.twig`

```js
My name is {{ name }}
```

4. Compile the template in `resources/assets/js/app.js`:

```js
let template = require('./dialog.html.twig');
var html = template({ thing: 'John Doe' });

console.log(html);

```

5. `npm run dev`

That's it. When I check the compiled `public/js/app.js`, it displays "My name is John Doe".
