### ISSUE TITLE
MIX_ prefixed variable in .env not present in webpack.mix.js

### ISSUE THREAD

**Issue by jper92** [JeffreyWay/laravel-mix#1096]
- Laravel Mix Version: 1.4.2
- NPM Version: 5.3.0
- OS: macOS 10.12.6

### Description:
I place some variables inside my `.env` file prefixed with `MIX_` as it is stated in documentation (https://laravel.com/docs/5.4/mix#environment-variables) that should be available in my `process.env` variable but it's not being injected, what am I missing here?

.env:
```
MIX_SOME_VAR=some_value
```
webpack.mix.js:
```js
let mix = require('laravel-mix');
console.log(process.env); // a large object without my var
console.log(process.env.MIX_SOME_VAR); // undefined
...

```

I made sure to restart my `npm run watch` process after placing the variable

**Comment by JeffreyWay** [comment]
You can't access those env vars from your webpack.mix.js file, but you can from your main script. So if you have:

```js
mix.js('resources/assets/js/app.js', 'js');
```

And then app.js has:

```js
console.log(process.env.MIX_SOME_VAR);
```

Once you compile down, it'll be:

```js
console.log("some_value");
```

**Comment by mariavilaro** [comment]
boh, this is not cool at all, I wanted to compile different sass files depending on a .env value :"(

**Comment by the94air** [comment]
@mariavilaro thanks for sharing the solution link with us. Saved me a lot of time.

**Comment by diegocam** [comment]
The prefix `MIX_` works, but why do we need to prefix variables with it? What if I want to use the same variables for both PHP and JS? For example lets say I have AWS keys as such:
```
AWS_ACCESS_KEY=somekey
AWS_ACCESS_SECRET_KEY=somesecretkey
```
does that mean that now I have to have two sets, one with `MIX_` and another without it, like this?
```
AWS_ACCESS_KEY=somekey
AWS_ACCESS_SECRET_KEY=somesecretkey

MIX_AWS_ACCESS_KEY=somekey
MIX_AWS_ACCESS_SECRET_KEY=somesecretkey
```
If so, it just doesnt make sense to me that we need to duplicate our variables. Why not make all variables accessible without the need to add `MIX_` to it, or am I not understanding it correctly?

**Comment by rachid804** [comment]
@diegocam the purpose of .env is to make your credentials secret, if every variable is available that means your secrets are accessible to anyone, that's why the MIX_ prefix. But we have this options
```
AWS_ACCESS_KEY=somekey

MIX_AWS_ACCESS_KEY="${AWS_ACCESS_KEY}"
```
Access secret should do not me shared with mix ;)

**Comment by antonioreyna** [comment]
if i change the value of the env_var should i need to recompile the js? my vue app is not getting the new value

**Comment by fgilio** [comment]
@antonioreyna yes, you have to recompile

**Comment by likunyan** [comment]
@MelMacaluso 
Your code not work.

ENV_VAR=somevalue
MIX_ENV_VAR="${ENV_VAR}"

"${ENV_VAR}" is ok

**Comment by Hesesses** [comment]
I have the following:
```
.env
MIX_API_URL=http://api.mydomain.com

theme.js
console.log(process.env.MIX_API_URL);

webpack.mix.js
mix.js('js/' + theme + '.js', public_path + 'js');

compiled theme.js
console.log(process.env.MIX_API_URL); // undefined
```

Any ideas whats wrong?

**Comment by oroalej** [comment]
@Hesesses Did you try doing `config:cache` or restarting the watch?

**Comment by Hesesses** [comment]
@oroalej I had webpack.mix.js and .env files in different folders as I am using Statamic CMS (build on laravel)

I added `var dotenv = require('dotenv').config({path:'../../.env'});` top of the file to point the .env file and everything works now 🔥

**Comment by danielgraziani91** [comment]
> @MelMacaluso 
>
> ENV_VAR=somevalue
> MIX_ENV_VAR="${ENV_VAR}"

Some time ago I was able to do that but today, starting a new project, it doesn't work... What's going on?

**Comment by AlcipPopa** [comment]
@danielgraziani91 you should avoid using "${ENV_VAR}" and use ${ENV_VAR} instead.

**Comment by piotrku** [comment]
Doesn't work anymore for me too, although theoretically it is possible: 
https://github.com/vlucas/phpdotenv#nesting-variables
