### ISSUE TITLE
can not support es6 async?

### ISSUE THREAD

**Issue by callect** [JeffreyWay/laravel-mix#1108]
in webpack.mix.js
```
.babel([
        'resources/assets/js/backend/chart.js',
    ], 'public/js/system/chart.js')
```
in resources/assets/js/backend/chart.js

```
let chart =  async () => {
...
}
```
when i run npm run watch ,the browser console report this:
_Uncaught ReferenceError: regeneratorRuntime is not defined_
`var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee() {`

What should i do?

**Comment by johnRivs** [comment]
Require `babel-preset-es2015` and `babel-preset-stage-3` and create a `.babelrc` file at the root of your project containing this:
```
{
    "presets": ["es2015", "stage-3"]
}

```

**Comment by callect** [comment]
@johnRivs I try...,still not work ):
