### ISSUE TITLE
Laravel-mix generates app.js which is not acceptable, javascript breaks with this app.js

### ISSUE THREAD

**Issue by iscraper** [JeffreyWay/laravel-mix#1114]
- Laravel Mix Version: #.#.# (`0.8.9`)
- Node Version (`6.11.1): 
- NPM Version (3.10.10`): 
- OS: Windows 8

### Description:

I have successfully combined my multiple JS files into single file and replaced all those files reference with app.js in my code. When I run my website, it is throwing multiple javascript errors in console window and everything is stop working.

### Example of errors

repond is not defined

jQuery(...).owlCarousel is not a function

### Steps To Reproduce:

mix.js( [
	
	'public/assets/front/js/bootstrap.min.js',
	'public/assets/front/js/jquery.isotope.min.js',
	'public/assets/front/js/easing.js',
	'public/assets/front/js/jquery.ui.totop.js',
	'public/assets/front/js/owl.carousel.js',
	'public/assets/front/js/jquery.fitvids.js',
	'public/assets/front/js/repond.js',
	'public/assets/front/js/jquery.plugin.js',
	'public/assets/front/js/jquery.magnific-popup.min.js',
	'public/assets/front/js/typed.js',
	
	] , 'public/js/app.js');

**Comment by JeffreyWay** [comment]
Looks like you want `mix.scripts()` instead. All you need is basic concatenation.
