### ISSUE TITLE
external css/js files should add with laravel mix, or can i add them in main.html file ? I add them in main.html file , and use only mix.js for using vuejs , but some of css files, and js files not render !!!

### ISSUE THREAD

**Issue by ShahabHomayouni** [JeffreyWay/laravel-mix#1116]
- Laravel Mix Version: #.#.# (`npm list --depth=0`) 1.0
- Node Version (`node -v`): 6.11.1
- NPM Version (`npm -v`): 3.10.10
- OS: windows 10/64

**Comment by emielmolenaar** [comment]
There should be a character limit on issue subjects :+1:
