### ISSUE TITLE
Laravel Mix dependency not installing correctly via NPM on Vagrant Box on Windows 10

### ISSUE THREAD

**Issue by hdwebpros** [JeffreyWay/laravel-mix#1117]
### Description:
Hi, there. I'm having issues getting NPM to install Laravel Mix dependencies specifically within a Vagrant Box in Windows.

By having
`"laravel-mix": "^1.0",` and `"cross-env": "^5.0.5",`
in a brand new project's package.json causes issues when running any sort of `npm install` (I tried, sudo, --no-bin-links, etc). I did this via a Vagrant Box I had built by using PuPHPet. I can confirm all works as expected on our Mac OS, and even Windows natively.

Natively in WIndows, we can install latest Node and NPM (tested for Node 8.4.0 and NPM 5.3.0), run `npm install`, run `npm install -g cross-env`, and then we are able to use the Mix NPM scripts (`npm run (prod|dev|watch)`)

Unfortunately, we develop in a Vagrant Box on Windows across a few computers. 

The fsevents module seems to cause some issues. I also ran into some etxtbsy text file is busy issues too.

I had our senior dev confirm this issue we are having across multiple windows computers.

### Steps To Reproduce:
- Go to puphpet.com, create an archive for your Vagrant built (with composer, node, etc)
- Extract your build, navigate to it, run `vagrant up`
- SSH into your build `vagrant ssh` and install a Laravel project via composer
- In your package.json, in devDependencies, add:
```
"devDependencies": {
    "cross-env": "^5.0.5",
    "jquery": "^3.2.1",
    "laravel-mix": "^1.0",
  }
```
- run `npm install`

**Comment by ruchern** [comment]
This is potentially a npm issue rather than Laravel Mix issue. Npm v5 has problems with installing packages and dependencies. Try using yarn?

**Comment by hdwebpros** [comment]
I haven't yet, but I certainly can try. I'll keep you posted

**Comment by hdwebpros** [comment]
Well, Yarn is an NPM tool. Since my time is limited for testing it out, we will just have devs on Windows run NPM natively to install the Mix dependency

**Comment by machinecodeblue** [comment]
yeah did the same thing.  GitBash on windows. rather than Vagrant

**Comment by BonBonSlick** [comment]
Same, fresh install of laravel broken.
