### ISSUE TITLE
Laravel 5.4, axios error  cannot read property 'common' of undefined 

### ISSUE THREAD

**Issue by maxonly** [JeffreyWay/laravel-mix#1120]
- Laravel Mix Version: 1.4.2
- Node Version : 8.0.0
- NPM Version : 5.3.0
- OS: Windows 10

### Description:
I create a new Laravel project,   I noticed a console error.

> Uncaught TypeError: Cannot read property 'common' of undefined

![image](https://user-images.githubusercontent.com/7932853/29395465-7cfcfc16-8343-11e7-82c9-dddef93969d7.png)

This is my webpack.mix.js 
```
let mix = require('laravel-mix');

mix.options({ extractVueStyles: true });

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');
```

### Steps To Reproduce:

1. Create new laravel5.4 project and npm install
2. Add below code to webpack.mix.js 
   `mix.options({ extractVueStyles: true })`
3. Add `<example></example>` to `welcome.blade.php` file
4. Add below style to example.vue
  ```
<style lang="scss" scoped>
    .container {
        margin-top: 50px;
    }
</style>
```
5. Run `npm run watch-poll`
6. Save `Example.vue` file

**Comment by davidhsianturi** [comment]
Just run `npm run development`

**Comment by JeffreyWay** [comment]
Just tried. I can't reproduce this, so assuming it has already been patched.

**Comment by ruchern** [comment]
@max-boy What is the version of your Vue in `package.json`?

**Comment by max-boy** [comment]
@ruchern 2.4.2

**Comment by ruchern** [comment]
@max-boy After a closer look, your declaration for the XMLHttpRequest seemed to be wrong.

windows.axios.defaults.headers.common = [ 'X-Requested-With': 'XMLHttpRequest' ]
