### ISSUE TITLE
Variable prefixed with MIX_ in .env file is not available for use

### ISSUE THREAD

**Issue by paradox37** [JeffreyWay/laravel-mix#1121]
- Laravel Mix Version: 1.4.2 (`npm list --depth=0`)
- Node Version (`node -v`): 8.2.1
- NPM Version (`npm -v`): 5.3.0
- OS: Windows 10 x64
- Laravel Version: 5.4.33

### Description:
Variable prefixed with MIX_ in .env file is not available for use.

### Steps To Reproduce:
Set up project and define host using WAMP. Define MIX_SENTRY_DSN_PUBLIC in .env.

When using mix.browserSync(process.env.MIX_SENTRY_DSN_PUBLIC) it will not work.
When I use console.log(process.env.MIX_SENTRY_DSN_PUBLIC) it shows undefined in console.
If I use mix.browserSync('http://example.com') then it works.

**Comment by JeffreyWay** [comment]
This is expected behavior. You can't access MIX_ variables from your webpack.mix.js file.

**Comment by paradox37** [comment]
Not according to Laravel documentation: https://laravel.com/docs/5.4/mix#environment-variables
