### ISSUE TITLE
sh: webpack: command not found after use yarn add

### ISSUE THREAD

**Issue by morawcik** [JeffreyWay/laravel-mix#1122]
- Laravel Mix Version: 1.4.2
- Node Version (`node -v`): 8.1.1
- NPM Version (`npm -v`): 5.3.0
- Yarn Version: 0.16.1
- OS: macOS Sierra (10.12.6)

### Description:
After using command yarn add when I try yarn run watch (for e.g) I got:

> rafal$ yarn run watch
yarn run v0.16.1
$ NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
sh: webpack: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Steps To Reproduce:
I can't try reproduce it at this moment but I can tell what I have done.

1. Install Laravel Mix for standalone app used Yarn followed by wiki guide
2. Install with yarn add:
- cross-env@5.0.5
- laravel-mix@1.4.2
- v-tooltip@2.0.0-beta.8
- vue@2.4.2
- vue-router@2.7.0
- vuex@2.3.1

3. Create git repository used Bitbucket
4. Clone project at other Mac (this one at the begining)
5. yarn install
6. yarn run watch
7. Stoped watch
8. Add babel-plugin-transform-object-rest-spread@6.26.0 with yarn add (for e.g - can be anything else)
9. yarn run watch and I got this error (even tried npm run watch)

To temporary fix (until next yarn add command) I have to use npm install command - then I can use watch again.

Yes I clear everything without result.

**Comment by JeffreyWay** [comment]
Yeah I think this is a weird yarn bug. I was reading a couple weeks ago about how, on a recent version, when you install a new dependency, Yarn actually uninstalls other dependencies. 👀

Anyways, there's nothing on the Mix end I can specifically do. Just have to reinstall all node dependencies until that issue is fixed.

**Comment by ruchern** [comment]
@JeffreyWay that's odd. This is a known issue with npm v5 instead of yarn.

**Comment by asimqt** [comment]
@ruchern Do you have more details/conversation about this npm issue?

**Comment by ruchern** [comment]
@asimqt https://github.com/npm/npm/issues/17929 A problem I personally faced since npm became v5.
