### ISSUE TITLE
Load data from .env file

### ISSUE THREAD

**Issue by stephan-v** [JeffreyWay/laravel-mix#1123]
I know the `dotenv` npm package is being used in this project and it seems to have been set up properly. However when I simply want to retrieve some data from my `.env` file I simply get `undefined` returned.

Even trying to log something like: `APP_NAME` from my `.env` file with:

`console.log(process.env.APP_NAME)`

Results in `undefined`.

Am I missing something here?

**Comment by bumTomica** [comment]
`require('dotenv').config()`?

**Comment by JeffreyWay** [comment]
You need to precede your .env property name with MIX_.

**Comment by mtvbrianking** [comment]
For new variables, you might need to to restart `php artisan serve` and also rerun `npm run watch`. ([Source](https://medium.com/@saber.tabatabaee/thats-work-with-mix-new-variable-but-need-to-restart-php-artisan-serve-and-also-restart-npm-run-9e76fe59415a))
