### ISSUE TITLE
Laravel Mix versioning doesn't work with the new query string id hash method

### ISSUE THREAD

**Issue by skatetdieu** [JeffreyWay/laravel-mix#1124]
- Laravel Mix Version: 1.4 (`npm list --depth=0`)
- Node Version (`7.7.3`): 
- NPM Version (`5.3.0`): 
- OS: Windows 10

### Description:
Laravel Mix used to create a new file for versioning with a has in the file name for each version like this:
`/assets/js/app.c334151f1417c9b922e9.js`

[In fact, someone put in an issue that old files weren't cleared up.](https://github.com/JeffreyWay/laravel-mix/issues/814)

It seems like the fix to that issue was to add a query string hash to cache bust files for browsers like this:
`/assets/js/app.js?id=c334151f1417c9b922e9`

With this new query string cache bust, the browser refuses to clear its cache of the old version of css and js files. 

The only way I can get it to forget old files is to delete the created mix file, reload the page so it doesn't find it, run npm to create the mix file again, and then reload the page so it finds the new version.

Even if I turn off `mix.version();` the files are still cached on the browser until I deleted it, reload the page so it doesn't find the file, run npm, and then reload the page.

### Update:
It seems like the root of this is the `mix.sourceMaps();` function, or more of the way the browser is caching the source code from the source map. 

If I take off the source maps from the files the cache busting works once again.

**Comment by Pauly-** [comment]
I'm having the same issue. Did you find a solution for this?

**Comment by skatetdieu** [comment]
I did get it fixed. I'm not sure what your setup is like but I'm using a vagrant setup to run a virtual box linux installation with it. 

It turns out it was my vagrant file setup. I needed to add `\n EnableSendfile off` to my vagrant file to the line where you say `echo "<VirtualHost *:80>`. 

That ended up fixing it for me.

**Comment by Pauly-** [comment]
I'm using Laravel Forge for production and Laravel Valet for local development. However, it is production related this issue as I'm only using versioning in production. I assume that the manifest file of mix is cached? Don't know if that was the case for you.. Otherwise, it is a bit different my issue.. though the same topic.

**Comment by skatetdieu** [comment]
Hmm, no I was experiencing this on npm run dev, watch, or production. But it turned out to be an issue with vagrant so I'm not sure how to solve it since you're using valet. 

Try using versioning in dev or watch to see if you get this still. Maybe there's a similar setting on valet as I did on vagrant.
