### ISSUE TITLE
webpack 3.x and plugin extract-text-webpack-plugin3 not work

### ISSUE THREAD

**Issue by maxonly** [JeffreyWay/laravel-mix#1125]
- Laravel Mix Version: 1.4.2
- Node Version : 8.0.0
- NPM Version : 5.3.0
- OS: Windows 10

### Description:
npm run dev not error ,when i watch ,there is error

`Uncaught TypeError: __webpack_require__(...) is not a function`

Reference:  [extract-text-webpack-plugin/issues/579](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/579)

**Comment by natezerk** [comment]
Confirmed as an issue.

**Comment by JeffreyWay** [comment]
I'm not sure we can do much on the Mix end, other than downgrade that dependency. I'd prefer not to do that, so I'll keep an eye on that GitHub issue.
