### ISSUE TITLE
Issue with jQuery plugins

### ISSUE THREAD

**Issue by alexelev** [JeffreyWay/laravel-mix#1127]
- Laravel Mix Version: 1.4.2
- Node Version: 6.11.2 
- NPM Version: 3.10.10
- OS: Windows 7

### Description:
There is a problem with connecting and using jQuery plugins (Owl Carousel 2). The plugin is installed by npm, it gives an error when used
![screenshot_302](https://user-images.githubusercontent.com/3392106/29494247-b30d40d2-85ae-11e7-842a-4bcd6a2f65c4.jpg)
I tried to solve it using the code below, but the problem is still here.
```
mix.autoload({
        jquery: ['$', 'window.jQuery']
    })
    .js('resources/assets/js/app.js', 'public/js')
    .version()
    .sourceMaps();
```
![screenshot_303](https://user-images.githubusercontent.com/3392106/29494253-c8466384-85ae-11e7-91cf-67910c252e83.jpg)
My package.json file
![screenshot_304](https://user-images.githubusercontent.com/3392106/29494276-2eb3d516-85af-11e7-98b5-3bc3f85a5a62.jpg)
In [plugin's github](https://github.com/OwlCarousel2/OwlCarousel2#load) says 
![screenshot_305](https://user-images.githubusercontent.com/3392106/29494293-a6b28d0a-85af-11e7-9399-c466f19acb52.jpg)
but if i do this in my app.js I have an error
![screenshot_306](https://user-images.githubusercontent.com/3392106/29494303-d13ff6d4-85af-11e7-9daa-3c2585a304ee.jpg)

### Steps To Reproduce:
Install clean laravel 5.5 project, execute `composer install` && `npm install`, make `npm install --save owl.carousel`. In your welcome.blade.php and app.js create a basic example from [basic demo](https://owlcarousel2.github.io/OwlCarousel2/demos/basic.html). Make `npm run watch` or `npm run dev` or just fork [it](https://github.com/alexelev/mix-test).

**Comment by rgehan** [comment]
I'm curious as to why you are doing your third import like that.

Couldn't you just do `import "owl.carousel"` ?

**Comment by alexelev** [comment]
Of course, I can do so `import 'owl.carousel'`.
![screenshot_314](https://user-images.githubusercontent.com/3392106/29554330-5becfb92-8727-11e7-8ea9-193ae7bfe2a8.jpg)
And here is the result.
![screenshot_315](https://user-images.githubusercontent.com/3392106/29554362-7dbba480-8727-11e7-9bb4-a8384acaae6c.jpg)

**Comment by ruchern** [comment]
@alexelev You probably need to play around with something like this

```javascript
window.owlCarousel = require('owl.carousel')
```

**Comment by ShahabHomayouni** [comment]
I have this problem too, how can add our external js files (jquery plugins and ...) in the vue project?
Should it be add in main.html? or another way ( bootstrap.js => how? ) , can anyone help?

**Comment by karlbalagtey** [comment]
having the same issue with jquery plugins, is there a proper way of importing jquery plugins in es6 using laravel mix?

i tried this already https://github.com/JeffreyWay/laravel-mix/issues/229

**Comment by jirehstudios** [comment]
FWIW, I was having a similar issue and it seems that jQuery plugins work well when included in the default `bootstrap.js` file after jQuery. In the example above, I am including `cropper`

```javascript

window._ = require('lodash');

/**
 * We'll load jQuery and the Bootstrap jQuery plugin which provides support
 * for JavaScript based Bootstrap features such as modals and tabs. This
 * code may be modified to fit the specific needs of your application.
 */

try {
    window.$ = window.jQuery = require('jquery');

    require('bootstrap-sass');
    require('cropper');
} catch (e) {}

/**
 * We'll load the axios HTTP library which allows us to easily issue requests
 * to our Laravel back-end. This library automatically handles sending the
 * CSRF token as a header based on the value of the "XSRF" token cookie.
 */

window.axios = require('axios');

window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';

/**
 * Next we will register the CSRF Token as a common header with Axios so that
 * all outgoing HTTP requests automatically have it attached. This is just
 * a simple convenience so we don't have to attach every token manually.
 */

let token = document.head.querySelector('meta[name="csrf-token"]');

if (token) {
    window.axios.defaults.headers.common['X-CSRF-TOKEN'] = token.content;
} else {
    console.error('CSRF token not found: https://laravel.com/docs/csrf#csrf-x-csrf-token');
}
```
