### ISSUE TITLE
confused about server-side (node) js vs what can be done with mix and laravel directly

### ISSUE THREAD

**Issue by vesper8** [JeffreyWay/laravel-mix#1129]
Sorry if this is a little bit out of scope but I'm sure many of you have the answer I'm looking for.

I'm trying to use a scraper https://github.com/mwpenny/kijiji-scraper which basically scrapes some data off a craigslist-like website

The "demo code" is simply this:

```
var kijiji = require("kijiji-scraper")

var prefs = {
  "locationId": 1700185,
  "categoryId": 27,
}

var params = {
  "minPrice": 0,
  "maxPrice": 100000,
  "keywords": "toyota",
  "adType": "OFFER"
}

kijiji.query(prefs, params, function(err, ads) {
  //Use the ads array
  console.log(ads);
});
```

after I've installed the package npm install kijiji-scraper

If I put the above code in a file in my root directory and just run "node myfile.js" it just works

now my goal was to add this to my /resources/assets/js/app.js instead because I want to be able to repeat the call with Vue and I want to display the data in real-time as well and I want to interact with it and store it with Laravel.

I've tried simply adding it at the bottom of my app.js and then I get a bunch of errors when running 'npm run dev'

The author is trying to help me and says that I should be able to get this to work thanks to Browserify but this is lost on me. Is this possible? Or am I going at it completely the wrong way?

I figure another alternative is to build something in pure node that stores the data in my database and then just access the data that way in my Laravel/Vue application

**Comment by JeffreyWay** [comment]
Put that code in your app.js file, install Laravel Mix, run `npm run dev`, and then let us know specifically what errors you're seeing. Can't do much to help otherwise.

**Comment by vesper8** [comment]
Sure. I'd like to mention though that I have now gotten around the issue by having Laravel call "node script.js" via exec. Script.js contains the kijiji-scraper code, and then through console.log sends the results back to Laravel. This works very nicely and I think is a cleaner solution anyway.

But I remain curious whether it's possible to run this kind of server-side node code in app.js so here's the errors I get if I try to do that

I ran npm install kijiji-scraper

then I add the example code to my app.js:

```
var kijiji = require("kijiji-scraper")

var prefs = {
    "locationId": 1700185,
    "categoryId": 27
}

var params = {
    "minPrice": 0,
    "maxPrice": 100000,
    "keywords": "toyota",
    "adType": "OFFER"
}

kijiji.query(prefs, params, function(err, ads) {
    //Use the ads array
    console.log(ads);
});
```

then when I do npm run dev I get these errors:

```
 ERROR  Failed to compile with 7 errors                                                                                                                                   21:54:15

These dependencies were not found:

* fs in ./~/kijiji-scraper/~/request/lib/har.js
* net in ./~/forever-agent/index.js, ./~/tough-cookie/lib/cookie.js and 1 other
* tls in ./~/forever-agent/index.js, ./~/kijiji-scraper/~/tunnel-agent/index.js

To install them, you can run: npm install --save fs net tls


This relative module was not found:

* ./package in ./~/cheerio/index.js
```

I did try installing all these dependencies manually although I don't think I should need to since they are dependencies of the kijiji-scraper itself

but even after adding these I still get these errors:

```
 ERROR  Failed to compile with 2 errors                                                                                                                                   21:49:11

This dependency was not found:

* fs in ./~/kijiji-scraper/~/request/lib/har.js

To install it, you can run: npm install --save fs


This relative module was not found:

* ./package in ./~/kijiji-scraper/~/cheerio/index.js
```

**Comment by socieboy** [comment]
@JeffreyWay no answer for this? I'm having the same issue, using Mix to compile the assets for a server side node application. exactly same issue
```
This dependency was not found:

* fs in ./~/kijiji-scraper/~/request/lib/har.js

To install it, you can run: npm install --save fs
```

Installing it manually but same thing.
