### ISSUE TITLE
How to add header and footer comments

### ISSUE THREAD

**Issue by dsmsky2008** [JeffreyWay/laravel-mix#1131]
- Laravel Mix Version: 1.0
- Node Version: 6.11.0
- NPM Version: 4.1.0
- OS: Windows 10 Home

### Description:

The adding header comments api not found in laravel-mix, and laravel-elixir-header component can't be used in laravel-mix， any suggestions?  thanks!

**Comment by JeffreyWay** [comment]
You can manually scan the files, but we don't offer anything out of the box to add headers to each file.

**Comment by dsmsky2008** [comment]
@JeffreyWay Thanks, I find another npm package "[module-header](https://www.npmjs.com/package/module-header)" solved my problem,  it would be perfect  for generates an licence header comments.
