### ISSUE TITLE
Trigger mix from command line

### ISSUE THREAD

**Issue by pkid169** [JeffreyWay/laravel-mix#1133]
Hi,

Is it possible to pass in a list of files via command line and have `laravel-mix` dynamically compile them and output in certain folder? E.g.

`node mixjs.js file1.js file2.js`

And the code in `mixjs.js` looks something like:

```javascript
let mix = require('laravel-mix');

var files = process.argv.slice(2)

mix.js(files, 'compiled.js')
    .then(() => {
        console.log('webpack has finished building!');
    });
```

**Comment by JeffreyWay** [comment]
No you can't do that.
