### ISSUE TITLE
Laravel mix does not compile import or require statements

### ISSUE THREAD

**Issue by WouterFlorijn** [JeffreyWay/laravel-mix#1135]
- Laravel Mix Version: 1.4.2
- Node Version: 6.11.2
- NPM Version: 3.10.10
- OS: Windows 10

## Issue

Laravel Mix does not compile `import` or `require`. Instead, it simply copies them.

It does not perform minification in production mode either, but that's a side-issue.

## Steps to reproduce

1. Create a new npm project.
2. Install laravel-mix through npm and copy the scripts to your package.json.
3. `npm install` some package.
4. Create `app.js`:
```
import package from 'package'; // Or package = require('package');
```
5. Add `mix.babel('inputpath/app.js', 'outputpath/app.js');` to your `webpack.mix.js`.
6. Run `npm run dev` or any other compilation script.

The output file will just be the same as the input file. Meanwhile, other ES6 features _are_ compiled correctly (tested with classes and arrow syntax for example).

Am I missing something, or is this a bug?

**Comment by fiskhandlarn** [comment]
Same thing happens to me. I found a workaround [here](https://github.com/JeffreyWay/laravel-mix/issues/971#issuecomment-322300417). Don't know if it affects performance though.

```
mix.js('resources/assets/js/app.js', 'public/js');

mix.webpackConfig({
  module: {
    rules: [{
      test: /\.js?$/,
      use: [{
        loader: 'babel-loader',
        options: mix.config.babel()
      }]
    }]
  }
});
```

**Comment by WouterFlorijn** [comment]
@fiskhandlarn Thanks! That works for now. However, it seems like using `mix.babel` should just work.

For me, using `mix.js` without the config you mentioned works in development mode, but crashes in production mode (during minification). With the config, it also works in production.

**Comment by fiskhandlarn** [comment]
@WouterFlorijn I agree, that would have been the best/easiest. :)

**Comment by JeffreyWay** [comment]
If the package you're requiring was written in es6, it won't be compiled down. You'd need to require the compiled version of that package.

**Comment by fiskhandlarn** [comment]
@JeffreyWay The package I'm trying to require is my own written ES6 code for the app/site. It would be nice to be able to compile that with `mix.babel`. :)
