### ISSUE TITLE
mix helper function in php layout outputting full url and not encompensating https when served via https website

### ISSUE THREAD

**Issue by mrgodhani** [JeffreyWay/laravel-mix#1137]
- Laravel Mix Version: 1.4.2 (`npm list --depth=0`)
- Node Version 8.4.0: 
- NPM Version 5.3.0): 
- OS: MacOS Sierra

### Description:

Running Laravel Mix and using mix() helper function in app layout is returning full url instead of path which causing issue of mismatching https.

### Steps To Reproduce:

1)  Run yarn run dev or yarn run production
2) Check source code of the html on page load. CSS is outputted as full url and doesn't match https if the website is served in https.

**Comment by JeffreyWay** [comment]
This is more of a Laravel framework issue, but I think somebody submitted a PR to use absolute urls, and then it was later reverted. Maybe composer update?
