### ISSUE TITLE
Issue with: webpack.config.js

### ISSUE THREAD

**Issue by authlab-frontdev** [JeffreyWay/laravel-mix#1138]
In your installation guide you wrote:

> However, should you need to configure it, you may copy the file to your project root, and then update your `package.json` NPM scripts accordingly: `cp node_modules/laravel-mix/setup/webpack.config.js ./`.

But, in the file itself `(webpack.config.js)` you required file from it's respective path `require('../src/index')` . Now I wanna know how it'll work if I copy that to my project root!

**Comment by devcircus** [comment]
If you choose to customize that file, of course you need to update the paths in it, as you would any file that you move to another location.

**Comment by authlab-frontdev** [comment]
In that case, it should be mentioned in the documentation! However, it worked in 0.8.* versions out of the box.

**Comment by ruchern** [comment]
@authlab-frontdev There are changes to webpack config from `v1.0.0` release.

**Comment by JeffreyWay** [comment]
Yeah this changed with 1.0. If there's a portion of the docs that still references copying the file over, we'll need to delete that.
