### ISSUE TITLE
How to use owl carousel with laravel 5.4 mix ?

### ISSUE THREAD

**Issue by shankhadevpadam** [JeffreyWay/laravel-mix#1140]
- Laravel Mix Version: #.#.# (`1.4.2`)
- Node Version (`7.2.0`): 
- NPM Version (`5.3.0`): 
- OS: Ubuntu 16.04

### Description:
I have added the owl carousel in my project using 
```
import 'owl.carousel/dist/assets/owl.carousel.css';
import $ from 'jquery';
import 'imports?jQuery=jquery!owl.carousel';

``` 
But didn't work, what is the actual process of adding jquery plugin using webpack mix.

**Comment by JeffreyWay** [comment]
Try:

```js
mix.js('resources/assets/js/app.js', 'public/js')
    .autoload({
        jquery: ['$', 'window.jQuery', 'jQuery']
    });
```

**Comment by tapash** [comment]
in webpack.mix.js

`mix.js('resources/assets/js/app.js', 'public/assets/js').autoload({
    jquery: ['$', 'window.jQuery', 'jQuery']
});`

and in app.js file:

`import owlCarousel from 'owl.carousel';`

**Comment by heihachi88** [comment]
Just

`import 'owl.carousel'` is enough, if you installed it with npm
