### ISSUE TITLE
copyDirectory not work in mix.then

### ISSUE THREAD

**Issue by superbull** [JeffreyWay/laravel-mix#1144]
- Laravel Mix Version: 1.4.2
- Node Version (`node -v`): v7.6.0
- NPM Version (`npm -v`): 4.1.2
- OS: windows7

### Description:
After compiling assets I want to copy the results to another directory.  So I use the `mix.then` event hook, but it doesn't work. But it works outside the `mix.then` block.

### Steps To Reproduce:
Try a `mix.copyDirectory` inside `mix.then`

### code
```javascript
mix.setPublicPath('./');
mix.react('src/index.js', 'public/react')
  .then(() => {
    mix.copyDirectory('public/react', '../MVC/wwwroot/react');
  });
```

**Comment by JeffreyWay** [comment]
Mix doesn't work that way, so you can't do this.

**Comment by vesper8** [comment]
@JeffreyWay what is the proper way to have mix perform more mix actions on files that are being created with mix ?

Is there a way to run two passes of mix that doesn't involve running two commands?

**Comment by dextermb** [comment]
This would be useful to know the answer to, @JeffreyWay.
