### ISSUE TITLE
Does laravel-mix export the js object  just in the `app.js`?

### ISSUE THREAD

**Issue by vaxilicaihouxian** [JeffreyWay/laravel-mix#1145]
- Laravel Mix Version: 1.4.2 (`npm list --depth=0`)
- Node Version (`node -v`): v8.2.1
- NPM Version (`npm -v`): 5.3.0
- OS: CentOS 6.7

### Description:
I follow the manual of laravel mix and want to use jquery in vendor.js

But I found that I must load app.js before my blade component(not Vue).

Here is my app.blade.php

```
<!doctype html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title') </title>
    @include('partials/head')
</head>
<body>
    @include('partials/header')
    <div class="ui container fluid" id="app">
        @yield('vue-app-content')
    </div>
    <script src="{{ asset('js/app.js') }}"></script>
    <div class="ui container fluid" id="blade">
        @yield('blade-content')
    </div>
    <script src="{{ asset('js/semantic.js') }}"></script>
        @yield('scripts')
    @include('partials/footer')
</body>
</html>
```

I want to load app.js just before the semantic.js (eq. below the div#blade).But the browser throw out an exception 'jQuery is not defined'.

I have already load manifest.js,vendor.js in the `head` blade page.

Dose it export the js object(like axios,jquery .etc) just in the `app.js`?

**Comment by JeffreyWay** [comment]
I'm not entirely sure what you mean, but if you import jQuery in app.js, and then another script depends on it, make sure you assign jQuery globally.

```js
window.$ = window.jQuery = require('jquery')
```

**Comment by vaxilicaihouxian** [comment]
I found that `bootstrap.js` and `app.js` will be compiled to `app.js`.So the jQuery will be export in the app.js and I must load `compiled app.js` first.
I asked this question because that I thought that the vendor.js will assign jQuery to the `window` object.I'm wrong.
Thanks for your reply.

**Comment by Bonobomagno** [comment]
you can do it easer.
Just go on default laravel bootstrap.js, remove any vue things (if u don't use it). On bootstrap.js you can also read an import jquery. 
After go on default app.js and remove che import of boostrap.js. 
Now you can import boostrap on a custom vendor.js file and change app.js for only non vendor things. 
I suggest this approach becouse you can personalize better the 2 entry points.

**Comment by vaxilicaihouxian** [comment]
I know what you mean.But I need to use Vue.And I found that I can not use any `script` tag in blade page.So I add an another content div `<div id='blade-content'></div>` beelow the `vue app div` and `app.js`.
At last I can use script tag in that blade div and also can use jQuery(because app.js has already bind that to `window`)
Thanks.

**Comment by slidenerd** [comment]
OMG I am only seeing this now, so essentially when you autoload vue, you can use it without importing Vue from 'vue' in app.js file and if I dont do window.Vue you are telling me that Vue wont be defined if I make a script block that executes after app.js damn

My flow is I have
  body
    include partials/header

    .container
      include partials/flash
      block content

    include partials/footer

    :mix(js) '/assets/scripts/manifest.js'
    :mix(js) '/assets/scripts/vendor.js'
    :mix(js) '/assets/scripts/app.js'

I am loading app.js at the bottom but inside my block content I want to make a script block where I can access Vue and it is always undefined. I tried moving these to the header and yet Vue is not defined. I was assuming autoload assigns Vue to window making window.Vue set but how does this work

should I import Vue from 'vue'
and window.Vue = Vue

or

should I just
window.Vue = Vue waiting for autoload to inject Vue

or

should I disable autoload and say
import Vue from 'vue';
window.Vue = Vue
Some clarification would be appreciated
