### ISSUE TITLE
inline css

### ISSUE THREAD

**Issue by Bonobomagno** [JeffreyWay/laravel-mix#1146]
- Laravel Mix Version: #.#.# 1.4.2

There is a way to use again inline css for webpack?
I need it for inline in some  blade mails

Thanks :)

**Comment by JeffreyWay** [comment]
Mix will create a dedicated output file for your CSS. You can inline it with PHP if you want.

**Comment by Bonobomagno** [comment]
you suggest to use something like ?
`{{readfile(mix('/public/css/mail.css')}}`

I think that still a feature request can be needed.

**Comment by mezhevikin** [comment]
For googlers! Bonobomagno's method does not work. You should this:

`{!! readfile(public_path(mix('css/app.css'))) !!}`

**Comment by slavicd** [comment]
For googlers - mezhevikin's answer doesn't work properly either. It will output the number of bytes read, which you don't want. Use this code:
`{!! file_get_contents(public_path('css/app.css')) !!}`

**Comment by mezhevikin** [comment]
Hi @slavicd ! You are right. Now my old method does not work.  It looks like this is due to a change in the blade parser.
However, I would recommend using **readfile** instead of **file_get_contents**, since it does not read data into RAM.
Just use php directly in your blade template.
```
<style>
     <?php readfile(public_path('css/admin.css')) ?>
</style>
```

**Comment by eusonlito** [comment]
And a "pure" blade version:

```html
<style>@php(readfile(public_path('css/app.css')))</style>
```
