### ISSUE TITLE
Hot reload not working, How to display localhost:8080 with homestead

### ISSUE THREAD

**Issue by GMounir** [JeffreyWay/laravel-mix#1147]
- laravel Version: 5.5
- Laravel Mix Version: "^1.0",
- Node Version:  6.11.2
- NPM Version: 3.10.10
- Windows : 8 - 64 bit
- Laravel Homestead 

Hello i installed fresh **laravel project version (5.5)**, i **run npm install**... everyting work fine, the only thing is when i run (**npm run hot**) in **vm** environment, no error shows  but **(Hot module replacement)** is not working,  when i typed _localhost:8080_ it also did not work .
i follow the instructions in this [line](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/hot-module-replacement.md) for @JeffreyWay.
i added the line in the blade page it gave me this error.
![capture-d ecran-2017-08-30-18 00](https://user-images.githubusercontent.com/13512081/29885102-6d586128-8dad-11e7-803c-2a8ad5c09bdc.png)

please can someone help me ...

**Comment by sifex** [comment]
This was something kinda hard for me to grasp as well.

> The key to making hot reloading work within a Laravel application is ensuring that all script sources reference the Node server URL that we just booted up. This will be http://localhost:8080. Now you could of course manually update your HTML/Blade files, like so:

```php
<body>
    <div id="app">...</div>
    <script src="http://localhost:8080/js/bundle.js"></script>
</body>
```

https://github.com/JeffreyWay/laravel-mix/blob/master/docs/hot-module-replacement.md

**Comment by baj84** [comment]
Thanks @sifex! That worked for me.

**Comment by trogne** [comment]
This is not working anymore. Can someone provide a real solution for hot-reload using windows/homestead ?
