### ISSUE TITLE
Set path for mix-manifest.json

### ISSUE THREAD

**Issue by geodeveloper** [JeffreyWay/laravel-mix#1150]
**Environment:**
Laravel Mix Version: 1.4.2
Node Version: 6.10.0
NPM Version: 3.10.10
OS: OS X

**Description**
Hi,
In older version 0.x there was no problem with this since the manifest file was generated in the main folder of output path (inside public folder), but in the latest version, the manifest file is always generated in public folder. For example:

**Behaviour on 0.x**
`mix.js('resources/assets/js/app.js','public/build/js')` --> manifest file is generated in `/public/build/mix-manifest.js`

**Behaviour on 1.4.2**
`mix.js('resources/assets/js/app.js','public/build/js')` --> manifest file is generated in `/public/mix-manifest.js`

My question is: Is there a way to set the path for manifest file? The idea is that I want to have 2 different manifest files, one for dev env and another for prod env.

Thank you.

**Comment by zarkin404** [comment]
@geodeveloper you can use the mix.setPublicPath() to set the path.

**Comment by geodeveloper** [comment]
@zarkin404 thanks for the tip, I already tried this but doesn't work as expected, for example:

`let mix = require('laravel-mix').setPublicPath('public/build');` it generates the manifest file like this `public/build/public/mix-manifest.json`

... but it should generate into `public/build/mix-manifest.json`

Thanks.

**Comment by zarkin404** [comment]
@geodeveloper maybe you shold normalize the path like this: `setPublicPath(path.normalize('public/build'))`

**Comment by geodeveloper** [comment]
@zarkin404 thanks for the reply and suggestion. I've tried but the result is the same. Note: I've updated my previous comment (I had a bad example, the problem is with the duplicated`public` folder` when using `setPublicPath`.

Thanks.

**Comment by geodeveloper** [comment]
@zarkin404 I got it working, was my fault, I had to update also the `mix.js('resources/assets/js/app.js','public/build/js')`, that's why I have duplicate `public`, just removed the `public` and now works as expected.

Thanks for your help, closing this issue.

**Comment by zarkin404** [comment]
@geodeveloper yeah, because the output path of the mix.js() is based on the public path, and the default public path is `/public`, once you set the public via mix.setPublicPath('foo'), the assets output path will be '/foo/{the output path you specified}'.

**Comment by vintprox** [comment]
IMO last longing optino is to set `path.public` for whole application through provider. I found a cleaner solution [here](https://stackoverflow.com/a/47518119/2396907):
```
// app/Providers/AppServiceProvider.php

...
	public function boot()
	{
...
		$this->app->bind('path.public', function() {
			return base_path() . '/../xn--o1aat.xn--p1ai/forum';
		});
...
	}
...
```

**Comment by josegus** [comment]
> @geodeveloper you can use the mix.setPublicPath() to set the path.

where do you get this hidden options? I couldn'n find it in the mix docs

**Comment by geodeveloper** [comment]
@josegus it's on doc: https://laravel-mix.com/docs/5.0/faq

Have a great day.
