### ISSUE TITLE
Watch not detecting js changes

### ISSUE THREAD

**Issue by nitishrajuprety** [JeffreyWay/laravel-mix#1156]
- Laravel Mix Version: 1.4.2 (`npm list --depth=0`)
- Node Version (`node -v`): 8.4.0
- NPM Version (`npm -v`): 5.3.0
- OS: Windows 10 Pro Version 1703 (OS Build 15063.540)

### Steps To Reproduce:

Mix in watch mode does not detect changes in js file but works fine sass file.

Here is my webpack code:

let mix = require('laravel-mix');

mix.sass('resources/assets/sass/style.scss', '../assets/css/app.css')
.scripts([
'node_modules/vue/dist/vue.min.js',
'resources/assets/js/script.js'
], '../assets/js/app.js')
.options({
processCssUrls: false,
publicPath: './'
});

**Comment by JeffreyWay** [comment]
Sorry for the delay. I can't seem to reproduce this. Were you able to get it figured out?
