### ISSUE TITLE
Version changed logic

### ISSUE THREAD

**Issue by alan-zhang-** [JeffreyWay/laravel-mix#1162]
before, 

version will make file like this:
"/js/app.js": "/js/app8cfc169200d19b892b09.js",

now it append id:
"/js/app.js": "/js/app.js?id=8cfc169200d19b892b09",

I prefer the old logic as a few CND provider total ignore get parameters.

**Comment by JeffreyWay** [comment]
The new version uses the query string. You can stick with sub 1.0 of Mix if you want the old versioning style for now.
