### ISSUE TITLE
Vue packages version mismatch

### ISSUE THREAD

**Issue by asivaneswaran** [JeffreyWay/laravel-mix#1164]
- Laravel Mix Version: 1.4.2
- Node Version (`node -v`):  6.10.2
- NPM Version (`npm -v`): 5.4.0
- OS: Mac (On Homestead)
- Vue version: 2.3.4

### Description:
I have the error:

```
Vue packages version mismatch:

- vue@2.3.4
- vue-template-compiler@2.4.2
```
It happend after I updated Laravel mix and Cross-env.

I nuked the node_modules (`rm -rf` and `npm cache clear --force`). And tried reinstalling it, but I still got the same error.

### Steps To Reproduce:

npm run dev

**Comment by dgoetzit** [comment]
Did you ever figure this out? Having the same issue now

**Comment by ruchern** [comment]
@dgoetzit Just manually install the `vue-compiler-template` package on your own.

E.g.

```bash
npm install -D vue-template-compiler
```

**Comment by dgoetzit** [comment]
Thanks!

**Comment by jeff-h** [comment]
There's a [note](https://github.com/JeffreyWay/laravel-mix/blob/1daf45a8f202db30617c366e45d52d063645d5f8/docs/faq.md#why-am-i-seeing-a-vue-packages-version-mismatch-error) in the docs regarding this now. Google still sent me here though.
