### ISSUE TITLE
Purifying css assets doesnt work.

### ISSUE THREAD

**Issue by smoleniuch** [JeffreyWay/laravel-mix#1169]
- Laravel Mix Version: 0.12.1
- Node Version (`node -v`): v6.11.2
- NPM Version (`npm -v`): 3.10.10

- OS: Linux Mint

### Description:
Purifying option doesnt work while compiling css files.

### Steps To Reproduce:

**This is inside my mix file:**
```javascript
mix.style('resources/assets/css/some.css', 'public/css/some.css').options({

  purifyCss: {
            paths: ['/home/smolen/Projects/laravel-test/resources/views/welcome.blade.php'],
            verbose:true,
            minimize:true,
        }

})
```
**This is my css file which stay the same after compiling:**
```css

.unused-class{

  color:red;

}

.used-class{

  color:blue;

}

```

**This is in my blade file:**

```php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

    </head>
    <body>
      <div class="used-class"></div>
    </body>
</html>

```

**Comment by Stichoza** [comment]
Confirming. PurifyCss doesn't work when passed as third parameter to `.sass()` method. But it works when set from `.options()`.

Any updates on this?

**Comment by JeffreyWay** [comment]
Did you get this figured out? I'm assuming it's related to your path. Out of the box, it seems to be working for me.

**Comment by ruchern** [comment]
You should use something like 

```javascript
path.resolve(__dirname, 'resources/views/welcome.blade.php');
```
