### ISSUE TITLE
version 0.5.0 is not available via npm

### ISSUE THREAD

**Issue by kpilard** [JeffreyWay/laravel-mix#117]
https://www.npmjs.com/package/laravel-mix
`Possible versions: "0.1.0, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.7, 0.2.8, 0.2.10, 0.3.0, 0.4.0`

**Comment by anchiceratops** [comment]
The Mix version 5 was published 4 hours ago. I guess you must wait for it to be available (waiting for npmjs.com to fetch the latest release).

**Comment by anchiceratops** [comment]
Whoops, sorry actually I don't know about this. Maybe @JeffreyWay has the answer.

**Comment by Gimcrack** [comment]
You can get 0.5 by changing your package.json file thus:

`"laravel-mix": "https://github.com/JeffreyWay/laravel-mix/tarball/master",`

**Comment by JeffreyWay** [comment]
It's live now.
