### ISSUE TITLE
How to turn off processCssUrls and on again

### ISSUE THREAD

**Issue by pr4xx** [JeffreyWay/laravel-mix#1170]
- Laravel Mix Version: 0.12.1
- Node Version (`node -v`): 6.5.0
- NPM Version (`npm -v`): 3.10.3
- OS: Win7

### Description:
I am compiling bootstrap and admin-lte both with less. Because of an strange error, I have to use `processCssUrl: false` in order to successfully compile admin-lte. But because of this option, webpack will no longer copy the glyphicon font files to the right direction. Even manually copying the font file with `mix.copy` does not help, because mix decides to rewrite the bootstrap font url to something like `url('../../../node_modules/bootstrap/fonts/` which, of course, does not work in the browser. I discovered that my only option right now is to compile bootstrap with `processCssUrls: true` and admin-lte with `processCssUrls: false`. But this does not work in one webpack.mix file.
Is there any way to tell mix for each file to use some options or not?

PS: This happens when I compile admin-lte without the option:
`This relative module was not found:
../../../node_modules/admin-lte/build/img/boxed-bg.jpg`

**Comment by ankurk91** [comment]
```js
// Configure default options
// @see https://github.com/JeffreyWay/laravel-mix/blob/master/docs/options.md
mix.options({
  processCssUrls: true,
});
```

**Comment by pr4xx** [comment]
@ankurk91 I am not sure if I do not understand your answer of if you did not read my issue entirely. I am using your options object, but it will apply it on every file in the webpack.mix file.

**Comment by acacha** [comment]
https://github.com/JeffreyWay/laravel-mix/blob/ea9e96d76f6f345eebd2818fdc0fa63b0fc37c65/docs/css-preprocessors.md

**Comment by pr4xx** [comment]
Thanks very much!
