### ISSUE TITLE
Laravel 5.5 "mix.js" in mix-manifest.json

### ISSUE THREAD

**Issue by aaesis** [JeffreyWay/laravel-mix#1171]
Hi Jeff,

Got an issue:

1. My code in webpack.mix.js:

![screen shot 2017-09-07 at 2 08 20 pm](https://user-images.githubusercontent.com/802180/30148616-d73dd666-93d6-11e7-9177-60b736fffdc9.png)

2. When running "yarn run prod/dev", got a "mix.js" in mix-manifest.json file. Please see below screenshot:

![screen shot 2017-09-07 at 2 14 55 pm](https://user-images.githubusercontent.com/802180/30148653-f53b2e16-93d6-11e7-8929-9cbcbec428f7.png)

3. Error occurs in the middle of compiling. Please see below screenshot:

![screen shot 2017-09-07 at 2 15 58 pm](https://user-images.githubusercontent.com/802180/30148683-1bfc3b4e-93d7-11e7-9c84-d799bcffaf30.png)

**Comment by JeffreyWay** [comment]
You shouldn't override the entry and output webpack options. Laravel Mix needs to be responsible for that.
