### ISSUE TITLE
Best local font workflow

### ISSUE THREAD

**Issue by victorronnow** [JeffreyWay/laravel-mix#1172]
- Laravel Mix Version: 1.4.2
- Node Version: 8.4.0
- NPM Version: 5.4.0
- OS: 10.12.6

### Description:
I want to apply a local font to my project. Where do I store my files?
Do I put them inside the resources/assets directory and then output them to my public folder?
Or do I store them directly in the public directory?

I've tried the first option but I get an error:

### Steps To Reproduce:

Put the font-files directory that contains all the font files inside the resources/assets directory.

- resources
  - assets
    - font-files
      - Akkurat.woff2
      - Akkurat.woff
    - js
    - scss
      - _fonts.scss
      - default.scss

Inside my scss directory, I have a default.scss file linked to a fonts.scss file that contains the following:

     @font-face {
           font-family: 'Akkurat';
           font-style:  normal;
           font-weight: 400;
           src: url("./font-files/Akkurat.woff2") format("woff2"),
                url("./font-files/Akkurat.woff") format("woff");
     }

What am I doing wrong?

**Comment by ruchern** [comment]
You may want to direct place this in the `app.js` file instead.

```javascript
require('path/to/font')
```

**Comment by victorronnow** [comment]
## Quick update.

I've put the `fonts` directory inside the `resources/assets` directory.

```
resources
`-- assets
    |-- fonts
    |   |-- Akkurat.woff
    |   `-- Akkurat.woff2
    |-- js
    |   `-- default.js
    `-- sass
        |-- default.scss
        `-- welcome
            |-- _custom.scss
            |-- _fonts.scss
            |-- _variables.scss
            `-- welcome.scss
```

My `resources/assets/welcome/_fonts.scss` file looks like this:

    @font-face {
      font-family: 'Akkurat';
      font-style:  normal;
      font-weight: 400;
      src: url("../../fonts/Akkurat.woff2") format("woff2"),
           url("../../fonts/Akkurat.woff") format("woff");
    }

This outputs a `fonts` directory inside the **`root`** directory, _which I don't want!_
I want it to outputted in the `public` directory!

Like this:

```
public
|-- css
|   |-- default.css
|   `-- welcome.css
|-- fonts
|   |-- Akkurat.woff
|   `-- Akkurat.woff2
|-- js
|   `-- default.js
`-- welcome.html
```

Could you please fix this or tell me if i'm doing something wrong?

**Comment by ankurk91** [comment]
![screenshot from 2017-09-17 10-11-58](https://user-images.githubusercontent.com/6111524/30518053-b039fbfa-9b90-11e7-9ee6-cf5720c64160.png)
Keep your local fonts in ``resources/assets/fonts``
Then refer them in your css (see screenshot),
Laravel mix will auto copy them to `public/fonts`
