### ISSUE TITLE
Should laravel-mix rebrand under a new name? 

### ISSUE THREAD

**Issue by Olian04** [JeffreyWay/laravel-mix#1174]
As mentioned by [francescobianco here](https://github.com/JeffreyWay/laravel-mix/pull/927#issuecomment-325167674), laravel-mix is being used by allot of projects outside of the laravel stack. Is it now perhaps the time to start thinking about a rebrand? Could it be the time for laravel-mix to "leave" the laravel name behind?

I'm fairly new to laravel-mix, but I've been using it almost daily since i found it about a year ago, that being said I've never used the laravel stack. I would love to hear some thoughts on whether or not the laravel-mix community would like to see laravel-mix become its own entity, or if it should remain as a part of the laravel brand?

**Comment by jkudish** [comment]
I have used it on primarily Laravel projects but also a few non-Laravel projects as it was easier then to setup a whole webpack flow manually. I definitely see its use case outside of the Laravel ecosystem. Not sure that it warrants a whole name change though; that'll probably just confuse more people then add any real value.

Just my 2 cents though. Curious about @JeffreyWay's thoughts 😄

**Comment by devcircus** [comment]
Laravel is the namespace under which the package was created and is maintained. I think it fits perfectly as-is. It's a package made by the laravel community mainly for use inside laravel apps. It works great outside laravel and I use it that way myself on a few projects but would love to keep close to its roots.

**Comment by JeffreyWay** [comment]
Yeah, no plans to separate Mix from the Laravel brand. Even though it works anywhere, it's still optimized for Laravel projects,.
