### ISSUE TITLE
Incorrect export

### ISSUE THREAD

**Issue by routegroup** [JeffreyWay/laravel-mix#1177]
- Laravel Mix Version: 1.4.2
- Node Version: 8.1.2
- NPM Version: 5.1.0
- OS: macOS Sierra 10.12.6

### Description:
When it comes to compile with stylus (i guess problem comes from preprocessors), additional module is created with comment and return void.
```js
file: dist/app.js
88: // removed by extract-text-webpack-plugin
```
and exported default from compiled file. If I would try to import default value from app.js it will return an empty object. If it's without styles then it compiles in correct way. It's important if we'll try to export compiled js (like use laravel-mix for generating code for package).

### Steps To Reproduce:
1. Install laravel-mix
2. Create files (source below)
3. npm run dev (value of export is an empty object) [full outcome](https://pastebin.com/ZtqLHTkg)
```js
file: dist/app.js
70: __webpack_require__(1);
71: module.exports = __webpack_require__(2);
```
4. comment out or remove line with compiling stylus in webpack.mix.js
5. npm run dev (value of export is equal of app.js) [full outcome](https://pastebin.com/jGfJqeD3)
```js
file: dist/app.js
70: module.exports = __webpack_require__(1);
```

### Files:
- src/main.styl (can be empty, doesnt matter)
- src/app.js
```js
export default {
  a: 'a'
}
```   
- webpack.mix.js
```js
const mix = require('laravel-mix')

mix
  .setPublicPath('dist')
  .js('src/app.js', 'app.js')
  .stylus('src/main.styl', 'main.css')
```

**Comment by nekosaur** [comment]
I just came across this problem as well, with laravel-mix `2.0.0`
