### ISSUE TITLE
standaloneSass() doesn't create an output file.

### ISSUE THREAD

**Issue by zacksmash** [JeffreyWay/laravel-mix#1186]
- Laravel Mix Version: 1.4.3
- Node Version (`node -v`): 8.4.0
- NPM Version (`npm -v`): 5.3.0
- OS: macOS 10.13

### Description:
standaloneSass() doesn't output anything.

### Steps To Reproduce:
EDIT: 
Install NPM Deps using Yarn

`rm -rf node_modules && yarn`

Create a `webpack.mix.js` file and compile sass using the `standaloneSass()` method.

**Comment by zacksmash** [comment]
Seems to be an issue with Yarn...? When I install NPM Deps with Yarn, only browser sync gets added to the ~/node_modules/.bin directory.

**Comment by JeffreyWay** [comment]
Late to respond, but I'm pretty sure this was fixed in a recent release.
