### ISSUE TITLE
Watch won't compile both Vue & scss files

### ISSUE THREAD

**Issue by daniesy** [JeffreyWay/laravel-mix#1188]
- Laravel Mix Version: 1.4.3 (`npm list --depth=0`)
- Node Version (`node -v`): 6.10.3
- NPM Version (`npm -v`): 5.4.1
- OS: Mac OS Sierra

### Description:
When using `npm run watch` modifying any .scss file will break the .Vue compiled files.

### Steps To Reproduce:

1. Have a laravel project with both .scss files and .Vue files
2. Run `npm run watch`, wait until everything is done, and check your results in the browser. Everything works ok. 
3. Now make some changes in one of your .scss files, wait until everything is done, and check the results in the browser. The .vue files won't get loaded and you'll get lots of errors.

`TypeError: __webpack_require__(...) is not a function`
` Error in beforeCreate hook: "TypeError: __webpack_require__(...) is not a function"`

4. I need to run `npm run watch` again to make it work.

My webpack mix looks like this:

```
mix.js('resources/assets/js/app.js', 'public/js')
    .js('resources/assets/js/auth.js', 'public/js')
    .js('resources/assets/js/dashboard.js', 'public/js')
    .js('resources/assets/js/onboarding.js', 'public/js')
    .js('resources/assets/js/people.js', 'public/js')
    .js('resources/assets/js/header.js', 'public/js')
    .js('resources/assets/js/sidebar.js', 'public/js')

    .js('resources/assets/js/global/application.js', 'public/js')
    .extract(['vue', 'lodash', 'moment']);

mix.sass('resources/assets/sass/app.scss', 'public/css');

if (mix.inProduction()) {
    mix.version();
}

if (!mix.inProduction()) {
    mix.sourceMaps();
}

mix.copy('resources/assets/img', 'public/img');
```

Also, it take a lot of time to compile (about 7seconds) with watch on. This never happened with the previous version of laravel mix (1.0.7)

**Comment by gorpetric** [comment]
I can confirm, same happening to me. OS: Windows

**Comment by dany68** [comment]
I can also confirm having the same problem on macOS High Sierra (10.13).
I need to re-compile by making a change in a Vue.js file, after making a change in a scss file.
Here is the error output:

`Uncaught TypeError: Cannot set property '__file' of undefined
    at Object.defineProperty.value (app.js:44664)
    at __webpack_require__ (app.js:20)
    at Object.disposed (app.js:44633)
    at __webpack_require__ (app.js:20)
    at Object.<anonymous> (app.js:3602)
    at __webpack_require__ (app.js:20)
    at Object.defineProperty.value (app.js:3591)
    at __webpack_require__ (app.js:20)
    at app.js:63
    at app.js:66`

**Comment by NBAH1990** [comment]
+1

**Comment by NBAH1990** [comment]
fixed it this way:
```javascript
mix.options({
     extractVueStyles: true
});
```

also I had a problem with the bootstrap-vue package, I just imported it another way way
```javascript
import BootstrapVue from 'bootstrap-vue/dist/bootstrap-vue.esm';
// instead of
import BootstrapVue from 'bootstrap-vue';
```
