### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by ShootToThrill** [JeffreyWay/laravel-mix#1199]
tongchuandeMacBook-Pro:articles tongchuan$ npm install laravel-mix --save-dev
npm WARN prefer global marked@0.3.6 should be installed with -g
/Users/tongchuan/Workspace/articles
├── autoprefixer@7.1.4  extraneous
├── babel-core@6.26.0  extraneous
├── babel-loader@7.1.2  extraneous
├── babel-preset-env@1.6.0  extraneous
├── concatenate@0.0.2  extraneous
├── css-loader@0.28.7  extraneous
├── dotenv@4.0.0  extraneous
├── dotenv-expand@4.0.1  extraneous
├── extract-text-webpack-plugin@3.0.0  extraneous
├── file-loader@0.11.2  extraneous
├── friendly-errors-webpack-plugin@1.6.1  extraneous
├── fs-extra@3.0.1  extraneous
├── html-loader@0.4.5  extraneous
├── img-loader@2.0.0  extraneous
├── lodash@4.17.4 
├── md5@2.2.1  extraneous
├── node-sass@4.5.3  extraneous
├── postcss-loader@2.0.6  extraneous
├── resolve-url-loader@2.1.0  extraneous
├── sass-loader@6.0.6  extraneous
├── style-loader@0.18.2  extraneous
├── vue-template-compiler@2.4.4  extraneous
├── webpack@3.6.0  extraneous
├── webpack-chunk-hash@0.4.0  extraneous
├── webpack-dev-server@2.8.2  extraneous
├── webpack-merge@4.1.0  extraneous
└── webpack-notifier@1.5.0  extraneous

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/tongchuan/.nvm/versions/node/v7.10.0/bin/node" "/Users/tongchuan/.nvm/versions/node/v7.10.0/bin/npm" "install" "laravel-mix" "--save-dev"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! path /Users/tongchuan/Workspace/articles/node_modules/js-beautify/js/bin/css-beautify.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/tongchuan/Workspace/articles/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/tongchuan/Workspace/articles/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tongchuan/.npm/_logs/2017-09-18T13_56_18_588Z-debug.log

**Comment by sunscreem** [comment]
There's are a lot of people seeing this today. 

https://github.com/beautify-web/js-beautify/issues/1247

**Comment by chevol** [comment]
Is there a work around or anything?

**Comment by sunscreem** [comment]
Yes.

Delete your node_modules folder, and in your package.json add this:

```
"js-beautify": "~1.6.14",
```

in the "devDependancies" section.

Then do an npm_install and you should be sorted :)

(Took me a LONG time to sort until someone pointed out I was accidentally adding `^1.6.14` instead of `~1.6.14`)

**Comment by sunscreem** [comment]
(Or wait a few hours until the dev wakes up and fixes this!)

**Comment by chevol** [comment]
See, I was doing the samething you were for the last hour. I had `^1.6.14` instead of `~1.6.14` Thank you, that solved my issue so I can work until this gets updated.

**Comment by yansern** [comment]
This is fixed in 1.4.5. Just do an `npm update`. #1206

**Comment by chevol** [comment]
Thank you sir!
