### ISSUE TITLE
Using extract(); the manifest.js output path is different from vendor.js (new)

### ISSUE THREAD

**Issue by getriebesand** [JeffreyWay/laravel-mix#1203]
- Laravel Mix Version: #.#.# (`npm list --depth=0`) 1.4.3
- Node Version (`node -v`): 6.10.0
- NPM Version (`npm -v`): 5.3.0
- OS: Windows7

### Description:
See Bugreport #553
The path ob vendor.js and manifest.js differs.
The path of manifest.js is the same path as path of last processed js file.

### Steps To Reproduce:
mix.setPublicPath('public')
mix
    .extract([
        'vue',
        'lodash',
        'axios'
    ],'js/vendor');
mix.js('resources/assets/js/app.js', 'public/js');
mix.js('resources/assets/js/acp/app.js', 'public/js/acp');

vendor.js is in public/js
manifest.js is in public/js/acp

**Comment by getriebesand** [comment]
duplicate of #1118

**Comment by goper-leo** [comment]
Have you solve this? Im using laravel-mix 1.7.2
