### ISSUE TITLE
Bump vue-template-compiler to 2.4.4

### ISSUE THREAD

**Issue by MikeElghali** [JeffreyWay/laravel-mix#1204]
- Laravel Mix Version: 1.4.3 (`npm list --depth=0`)
- Node Version (`node -v`): 6.11.3
- NPM Version (`npm -v`): 5.4.2
- OS: MacOS Sierra 10.12.6

### Description:

A new version of Vue (v2.4.4) is available. So, vue-template-compiler needs to be updated.

**Comment by ruchern** [comment]
Alternatively, you can add `vue-template-compiler` to your devDependiences.
