### ISSUE TITLE
Notification duration

### ISSUE THREAD

**Issue by FrozenDroid** [JeffreyWay/laravel-mix#1207]
- Laravel Mix Version: 1.4.2
- Node Version (`node -v`): v8.4.0
- NPM Version (`npm -v`): 5.3.0
- OS: Ubuntu 17.04

### Description:
It'd be very nice if you could specify the duration of the build notifications. I save my code very often, and so, build notifications overlap a lot, which isn't optimal. I could see if I can write up a PR.

### Steps To Reproduce:
N/A

**Comment by JeffreyWay** [comment]
Can't control that right now, but you can always disable them entirely if you want. `mix.disableNotifications()`.

**Comment by joshlewis** [comment]
I agree with @FrozenDroid, we need more granular control over notification duration.  I tried `defaults write com.apple.notificationcenterui bannerTime 1` on macOS High Sierra and that had no effect, sadly.
