### ISSUE TITLE
[Proposal] Option to use smartStrategy() in .webpackConfig method

### ISSUE THREAD

**Issue by dragermrb** [JeffreyWay/laravel-mix#1213]
Maybe something like this:

```
mix.webpackConfig({
    plugins:[ new ngAnnotatePlugin({add: true}) ] // My custom config
}, {
    plugins: 'prepend' // Plugins strategy
});
```

This allows to prepend plugins. In this example, **ngAnnotatePlugin** will run before **UglifyJsPlugin**, which is recommended in AngularJS applications.

**Comment by JeffreyWay** [comment]
Closing this in favor of your PR.
