### ISSUE TITLE
Vue components scss styles autoprefixing

### ISSUE THREAD

**Issue by lawniczek-piotr** [JeffreyWay/laravel-mix#1215]
Hi, as long as my scss styles in Vue components work pretty well, they are not prefixed in the end. I've searched through web but couldn't find any solution. Is there any way to set this in my .mix file ? As far as I know, in vue-loader options I need to add something like:

options: {
    postcss: [require('autoprefixer')()]
}

however I got no idea how to do it in laravel-mix.

**Comment by ruchern** [comment]
Related #1189. You might want to follow the changes in that PR before it's being merged.

**Comment by lawniczek-piotr** [comment]
@ruchern I've got to admit i didn't look into pull requests. Works as I expected, thanks :)

**Comment by stephan-v** [comment]
Is there any update on when this will get released? I too need this and I would rather just update my dependencies than to monkey-patch my current config again.

**Comment by ruchern** [comment]
@stephan-v It does seem like this fix is already in the latest version.

**Comment by stephan-v** [comment]
It was merged 17 days ago and the last release was 20 days ago? Am I misreading something? I will check though.

**Comment by ruchern** [comment]
@stephan-v Well, `v1.4.5` was not tagged by @JeffreyWay though.

**Comment by stephan-v** [comment]
Ah I see on `NPM` it has indeed been updated, very nice. Thanks!

**Comment by ruchern** [comment]
@stephan-v Commit was tagged `v.1.4.5` as 67e52924558e88773484af1d006d563ed3246017.

**Comment by stephan-v** [comment]
Yes I pulled in the v.1.4.5 update but the fix has not yet been included. #1189 fixes my issue though, guess I will have to wait.

**Comment by stephan-v** [comment]
And it has just been released, nice.
