### ISSUE TITLE
Uglify not working with ES6

### ISSUE THREAD

**Issue by tillkruss** [JeffreyWay/laravel-mix#1216]
Uglify hasn't been working for months. `uglifyjs-webpack-plugin` [hasn't been updated](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/releases) since July 21st and there have been no commits on the repo since then.

Is there a workaround to get `uglify` working with the latest Laravel Mix version?  
Can we maybe just switch to the beta or switch to `uglify-es`?

**Comment by tillkruss** [comment]
As reference, I'm getting the following error:

```
Unexpected token: punc ())
```

```js
mix.options({
    uglify: true,
});
```

**Comment by JeffreyWay** [comment]
Uglify is already turned on by default. Are you pulling in a package that was written in ES6? If not, everything should compile properly I think. 

Can you give me a simple script example that won't compile down? I'll test it out.

**Comment by ankurk91** [comment]
If you pull an es6 js file from `node_modules` like
```js
import someName from 'somePackage/src/es6-syntax-file.js';
```
mix will not apply babel to it.
Correct me if i am wrong.

**Comment by tillkruss** [comment]
@JeffreyWay: It's a Bootstrap v4 modules that's written in ES6.

### Setup

```bash
git clone https://github.com/tillkruss/laravel-mix-1216
cd laravel-mix-1216
npm install
npm run production
```

### Error

```log
ERROR  Failed to compile with 1 errors                                                                                                                                                      

dist/test.js from UglifyJs
Unexpected token: punc ()) [./node_modules/bootstrap/js/src/util.js:10,0][dist/test.js:10342,15]
```

**Comment by ankurk91** [comment]
Babel loader is set to exclude `node_modules`
https://github.com/JeffreyWay/laravel-mix/blob/master/src/builder/webpack-rules.js#L11
I think this was to speed up build.

**Comment by tillkruss** [comment]
@ankurk91: Genius! Thanks, that works like a charm.

@JeffreyWay: Feel free to close this. Not sure if the issue is actually resolved.

**Comment by tillkruss** [comment]
@ankurk91: Importing from `dist` works, but it seems to import the entire `bootstrap.js` file, including all modules, not just the ones I imported.

**Comment by ankurk91** [comment]
Did you extract bootstrap with
```
Mix.extract(['bootstrap'])
```
If so webpack will discard selective import.

If NOT then try 
webpack bundle analyser to visualise the modules and their size.

**Comment by tillkruss** [comment]
No, I'm trying to import only specific BSv4 modules. 

How would I run the bundle analyser and why?

**Comment by ankurk91** [comment]
I was suggesting bundle analyzer to get the correct size of each module included.

Here is the link -
https://github.com/th0r/webpack-bundle-analyzer

**Here is how to use this in Laravel mix**
```
npm install --save-dev webpack-bundle-analyzer
```
Then in your webpack.mix.js
```js
var BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;

mix.webpackConfig({
  plugins: [
     new BundleAnalyzerPlugin(),
  ]
});
```
Then run 
```
npm run prod
```
Wait for `http://127.0.0.1:8888/` to be ready for your browser.
You can remove this package after using.

**Comment by tillkruss** [comment]
Yeah, when I'm using `import Modal from 'bootstrap/dist/js/bootstrap.js';` the entire `bootstrap.js` is imported.

From `src`:

<img width="2479" alt="bs-from-src" src="https://user-images.githubusercontent.com/665029/30774643-cd41b84c-a03a-11e7-8aea-9b085f0c157a.png">

From `dist`:

<img width="2482" alt="bs-from-dist" src="https://user-images.githubusercontent.com/665029/30774642-cba244ac-a03a-11e7-95f1-786ee809d737.png">

**Comment by ankurk91** [comment]
Strange,
Don't know what is missing to fulfill tree shaking requirements
https://webpack.js.org/guides/tree-shaking/

**Comment by tillkruss** [comment]
@JeffreyWay: Any insights?

**Comment by ankurk91** [comment]
According to bs v4 docs we can can selective import like this 
```js
import 'bootstrap/js/dist/util';
import 'bootstrap/js/dist/dropdown';
```
may be you should give it a try.
https://getbootstrap.com/docs/4.0/getting-started/webpack/

**Comment by ankurk91** [comment]
Yeah just found compiled individual js files,

https://unpkg.com/bootstrap@4.0.0-beta/js/dist/

**Comment by tillkruss** [comment]
@ankurk91: Neat, that worked!

```js
import 'bootstrap/js/dist/modal';
import 'bootstrap/js/dist/dropdown';

mix.webpackConfig({
    plugins: [
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            Popper: ['popper.js', 'default'],
            Util: 'exports-loader?Util!bootstrap/js/dist/util',
        }),
    ]
});
```
