### ISSUE TITLE
mix.copyDirectory flattens the destination structure if wildcards used in src.

### ISSUE THREAD

**Issue by rusowyler** [JeffreyWay/laravel-mix#1217]
- Laravel Mix Version: 1.4.5
- Node Version: v7.7.3 
- NPM Version: 4.1.2 
- OS: Sierra 10.12.6

### Description:

mix.copyDirectory flattens the destination structure if wildcards used in src.

**For example:** 
mix.copyDirectory('angular/app/**/*.html', 'public/views/app/') should copy only htmls and preserve the directory structure.

### Steps To Reproduce:

**Source files:** 
* app/client/file.html
* app/client/file.scss
* app/client/file.js

**webpack.mix.js**
* mix.copyDirectory('app/**/*.html', 'public/views/app/')

**Expected result**
* public/views/app/client/file.html

**Result**
* public/views/app/file.html

THANKS!

**Comment by JeffreyWay** [comment]
This would need to wait for a new major release, since a lot of people rely on the current functionality.  I'll make a note of it though.

**Comment by madsem** [comment]
Def need this too now. Trying to use mix with themes and expected that copyDirectory would mirror the dir structure I have in /resources... into the /public dir.

Too many themes (multi-domain. multi-tenant app) to do this by hard coding the names

**Comment by nitescent** [comment]
Has it been done?
