### ISSUE TITLE
How do I add versioning on JS and CSS files for a non Laravel app

### ISSUE THREAD

**Issue by jackbarham** [JeffreyWay/laravel-mix#1218]
I know this not an issue, but I can't figure how (or if it is possible) to version the build assets?

I'm using s standard `index.html` file in the `dist` folder, the same directory as the compiled `.css` and `.js` files along with `mix-manifest.json`.

Is there a way to dynamically reference the hashed IDs from the `index.html` file.

In `webpack.mix.js` I have:

```js
mix.js('src/js/app.js', 'dist/')
    .sass('src/sass/app.scss', 'dist/')
    .setPublicPath('dist')
    .version()
```

**Comment by devcircus** [comment]
The manifest file will still be generated. You just need a script to read that file and replace the filename in your html with the filename+querystring from the manifest. If you're comfortable with backend languages, read through Laravel's "mix" solution. Search for "asset versioning in php" or whichever language you require. There are open source solutions available. Symfony's Encore has versioning also. You could read through that code as well for ideas.

**Comment by jackbarham** [comment]
Thanks for the feedback. This is a single static page marketing site with no backend hosted on S3 & CloudFront, I'm using laravel-mix for the local build process. I was wondering if there is a solution in the build process to do this.

**Comment by JeffreyWay** [comment]
Yeah right now, you'd need to load that manifest file and build the URL.

We're adding an option for file-based versioning soon, so that should solve your problem.

**Comment by jackbarham** [comment]
Thanks, Jeffery. I'll keep an eye out for it.

**Comment by artemsky** [comment]
maybe it will help you for now.
I came with this problem far time ago. And created my own helper for non-laravel projects

```
if (! function_exists('mix')) {
    /**
     * Get the path to a versioned file.
     *
     * @param  string  $path
     * @param  string  $manifestDirectory
     * @return string
     *
     * @throws \Exception
     */
    function mix($path, $manifestDirectory = 'public')
    {

        if (! starts_with($path, '/')) {
            $path = "/{$path}";
        }

        $path = substr($path, 7);

        if ($manifestDirectory && ! starts_with($manifestDirectory, '/')) {
            $manifestDirectory = "/{$manifestDirectory}";
        }

            if (! file_exists($manifestPath = $_SERVER['DOCUMENT_ROOT'] . $manifestDirectory.'/mix-manifest.json')) {
                throw new Exception('The Mix manifest does not exist.');
            }

            $manifest = json_decode(file_get_contents($manifestPath), true);

        if (! array_key_exists($path, $manifest)) {
            throw new Exception(
                "Unable to locate Mix file: {$path}. Please check your ".
            'mix-manifest.json output paths and try again.'
        );
        }
        return base_url($manifestDirectory.$manifest[$path]);
    }
}
```
