### ISSUE TITLE
Unable to mix output .js file to the parent directory

### ISSUE THREAD

**Issue by jackbarham** [JeffreyWay/laravel-mix#1220]
- Laravel Mix Version: 1.4.5
- Node Version: 8.2.1 
- NPM Version: 5.4.2
- OS: macOS 10.12.6

I've created a `src` folder within a WordPress themes directory for all build scripts, node modules, etc (so I can hide it when publishing to the server). 

In that folder I have `webpack.mix.js`:

```js
mix.sass('sass/style.scss', '../style.css')
	.js('js/script.js', '../script.js')
```

This publishes the `style.css` in the themes (parent) directory as required, but when I do the same for the `script.js` file it publishes it in the current `src` folder but creates a list of all folders from my system Users directory `Users/jackbarham/Code/etc/.../etc/theme/src/script.js` all the way to the output file.

I've tried altering paths, but I can't get it to work or understand why it's working for CSS but not JS.

**Comment by huglester** [comment]
Hello,
same issue here.

have you found a sollution yet?

**Comment by jackbarham** [comment]
No, I haven't yet. Please let me know if you do.

**Comment by ruchern** [comment]
Can you try

```javascript
mix.sass('sass/style.scss', './../style.css')
	.js('js/script.js', './../script.js')
```

**Comment by jackbarham** [comment]
I've tried that already and get exactly the same output. CSS is correct but not JS.

**Comment by jackbarham** [comment]
As a side note: I was previously using Laravel Elixir (a different package, I know) but that compiled both assets into the correct folder using the same path as above.

**Comment by ruchern** [comment]
Try replacing

`.js()` with `.scripts()`

and see if it worked.

Ref: https://laravel.com/docs/5.5/mix#vanilla-js

**Comment by jackbarham** [comment]
Yes! That's worked :)

**Comment by jeremy-smith-maco** [comment]
Doesn't seem to work for `.copy()` though. -.-

**Comment by benface** [comment]
Same problem here.

**Comment by lukeparkinson** [comment]
I have the same problem - this seems like a good work around for the time being: https://github.com/JeffreyWay/laravel-mix/issues/174#issuecomment-275256893

**Comment by renanfenrich** [comment]
This worked for me: mix.setPublicPath('../parent-folder/');

**Comment by mev01** [comment]
I did sth like taht and it's working.
`
mix.setPublicPath('../')
	.js('resources/assets/js/app.js', 'js')
        .sass('resources/assets/sass/app.scss', 'css');
`

**Comment by LorrainInfinity** [comment]
thanks @eliamariutti , your solution was the good one for me !
