### ISSUE TITLE
no display error if file is not found

### ISSUE THREAD

**Issue by rhyudek1** [JeffreyWay/laravel-mix#1223]
- Laravel Mix Version: 1.4.5
- Node Version: 8.0.0
- NPM Version: 5.4.1
- OS: Ubuntu Server 17.04

If a file specified in .script is not existing compile is running normal.
I expected an error like it is happening in .js.

### Steps To Reproduce:

```
mix.styles([
    'node_modules/html5-boilerplate/dist/css/main.css',
    'node_modules/datatables/media/css/dataTables.bootstrap.css'
], 'public/css/vendor.css');
```

**results**
`/css/vendor.css  58.5 kB          [emitted]`

**results If I change the filenames**
`/css/vendor.css  0 kB          [emitted]`

But no errors or warnings.

**Comment by Dsudenfield** [comment]
This also seems to happen if there is a syntax error in the webpack.mix.js file. For instance this code below did not error even though I accidentally left the semi colon on my first .js(). After downgrading to 1.0 it let me know that I had an unexpected token . 
```
mix.js('resources/assets/js/header/header.js', 'public/js');
    .js(footer_scripts, 'public/js/footer.js')
    .version();
```

**Comment by MrJmpl3** [comment]
I recommend this function in another issues , but the issues is closed too =v

**Comment by Dragas** [comment]
Yep. Came into this issue as well. The transpiler should provide atleast a warning or color the lines which outputted 0 bytes in red. But instead you get only this
![an image](https://i.imgur.com/UKcpeMR.png)

**Comment by rhyudek1** [comment]
any news ?

**Comment by truewx** [comment]
Any update on this?
