### ISSUE TITLE
Paths are resolved inconsistently (are they?)

### ISSUE THREAD

**Issue by lmeysel** [JeffreyWay/laravel-mix#1226]
Having the following config
```
mix.setPublicPath(__dirname + '/output')
    .js('input-foo/app.js', 'js')
    .sass('input-foo/layout.scss', 'css');
```
mix generates the subfolder /output/css where the css files are stored, `/output/images` for the images referenced from the css, but the JS is bundled into `/output/output/js`.

In fact, the whole subfolder structure is recreated and then /js added - i.e.
```
mix.setPublicPath(__dirname + '/foo/bar/baz')
     .js('input-foo/app.js', 'js');
```
leads to the js-path `/foo/bar/baz/foo/bar/baz/js`. JS is bundled into the right folder, when i set the public path to the project root, but then the fonts- and images-folders are not created in the subdirectory i want it to be.

(I wonder how that works when using mix included in a laravel-application, because there the public path is not set explicitly, but the fonts- and images-folders are created in the public folder. When using mix in a non-laravel-environment mix crashes when not setting the public path explicitly).

I am running on windows 10 machine, might be interesting due to the fact we're talking about paths...

**EDIT:** After reading #1153 i tried to set public path not absolute but with windows' path-separator (i.e. backslash), now everything works as expected: setPublicPath('foo\bar\baz') - but it must not have a leading or trailing slash.

**Comment by webmarkelov** [comment]
I have a problem, too.

**Comment by lmeysel** [comment]
I also found a workaround/solution for that. The problem was the path-separator. When `mix.setPublicPath('output/assets')`, the problem is like described in my first post. But when `mix.setPublicPath('output'+path.sep+'assets')`, everything works fine for me (but not when using path.resolve(..) though).

**Comment by grenaria** [comment]
This issue is not only for windows. I am having the same thing happen when the path for setPublicPath is an absolute path inside of a CentOS Vagrant box. Everything else compiles fine into the absolute public path (SCSS, Vue, etc) but the app.js from the js command gets put into a directory relative to the executable path with the absolute path appended to it.
