### ISSUE TITLE
extract() Not Creating vendor.js and manifest file

### ISSUE THREAD

**Issue by stevepop** [JeffreyWay/laravel-mix#123]
Hi,

I have the following webpack.mix.js configuration;
```
mix.js('resources/assets/js/frontend.js', 'dist/js');

mix.js('resources/assets/js/backend.js', 'dist/backend/js')
   	.sass('resources/assets/sass/app.scss', 'dist/css')
	.sass('resources/assets/sass/backend.scss', 'dist/backend/')
	.copy('resources/assets/libs/font-awesome/fonts', 'public/dist/css/fonts');

mix.extract(['jquery', 'vue', 'axios', 'lodash', 'moment', 'bootstrap-sass']);
```
I however notice that the extract function is not creating the vendor.js and manifest files as written in the manual.  This is being used in a Laravel 5.3 application. The only files creates are the frontend.js and backend.js files.

**Comment by JeffreyWay** [comment]
Are you importing jQuery, Vue, etc in your frontend.js area?

**Comment by stevepop** [comment]
Ah! Thanks @JeffreyWay, that was what I was missing! I can see the files now.

**Comment by craigward** [comment]
Can you show me your final file?

I'm having same issues that I can't find the answer to in the docs. Below is part of my file, but not sure if that is correct or not?

`mix.js('node_modules/jquery/dist/jquery.js', '../think-cms/public/')
   .js('js/public.js', '../think-cms/public/')
   .extract(['jquery']);`
