### ISSUE TITLE
multiple mix installations

### ISSUE THREAD

**Issue by lucasff** [JeffreyWay/laravel-mix#1234]
Hi!

I have two scoped applications using `mix`, one uses `Angular.JS` and the other one `React`. When I run `npm run dev` on each, the `mix-manifest.json` gets overridden by the other. There's a way to "merge" the values of the `mix-manifest.json` and keep the existing values?

**Comment by ankurk91** [comment]
https://github.com/fandogh/laravel-multimix

**Comment by vahidalvandi** [comment]
upgrade to mix 4
