### ISSUE TITLE
Option in version() to choose querystring or file name with hash

### ISSUE THREAD

**Issue by ricardogreis** [JeffreyWay/laravel-mix#1241]
Hello,
It would be nice to be able to choose how mix version function handle the cache-busting. 
Looks some people prefer querystring, but file names with the hash works very well for me.
What do you think?

Thanks.

**Comment by JeffreyWay** [comment]
I have this planned already.

**Comment by samwalshnz** [comment]
Thanks Jeffrey. 

@ricardogreis FYI - there's been plenty of tickets where this has been discussed - I've been guilty of bringing it up in another ticket before realising it's already been discussed as well. I believe the following ticket is the best place to discuss it: https://github.com/JeffreyWay/laravel-mix/issues/1022

**Comment by vesper8** [comment]
really hoping this can be done soon.. cache busting has been busting my balls bigtime! even though I use version.. Chrome seems to be so stuborn somehow and I have issues with cache busting nearly every time I deploy new js assets

**Comment by sagargulati** [comment]
When should we expect? https://github.com/JeffreyWay/laravel-mix/issues/1241#issue-262719770

**Comment by terryupton** [comment]
+1 - any ETA on this at all?

**Comment by Quezler** [comment]
+1

**Comment by Daidalos117** [comment]
+1
