### ISSUE TITLE
Unexpected token: name (Dom7)

### ISSUE THREAD

**Issue by sebastiansulinski** [JeffreyWay/laravel-mix#1244]
- Laravel Mix Version: 1.4.5
- Node Version: v8.6.0
- NPM Version: 5.4.2
- OS: macOS Sierra

I just updated laravel-mix to the latest version and when I run `npm run production` I now get the following error:

```
js/dist/app.js from UglifyJs
Unexpected token: name (Dom7) [./node_modules/dom7/dist/dom7.modular.js:14,0][js/dist/app.js:24688,6]
```

It works fine with `npm run watch` - just when I try to compile for production.
Looks like `dom7` package related?

**Comment by sebastiansulinski** [comment]
I think this is actually related to the issue with one of the plugins (`swiper`).

**Comment by AGhasemzadeh** [comment]
Hello,
I have this problem how can I fix it?

**Comment by sebastiansulinski** [comment]
For me it was `nolimits4web/Swiper` that was causing this problem - I've downgraded to `v3.4.2` and the problem went away.

**Comment by mrowles** [comment]
v4 and v3 have different API's though, meaning this force a code change and not just a library downgrade. It's a tree-shaking thing for me when compiling with AOT in Angular2.

**Comment by rickbolton** [comment]
@mrowles @sebastiansulinski I've pulled in the latest swiper version `4.0.5` from `4.0.3` and it's now working with `yarn run production` I guess there might have been a fix released recently?

**Comment by josiah47** [comment]
This is happening for me with swiper version 4.0.6, npm run build causes
Unexpected token: name (Dom7) [./node_modules/dom7/dist/dom7.modular.js:14,0]

**Comment by sebastiansulinski** [comment]
Please try the following configuration #1323 and see if it resolves the problem.

**Comment by mateuszgwozdz** [comment]
> For me it was `nolimits4web/Swiper` that was causing this problem - I've downgraded to `v3.4.2` and the problem went away.

How did you figure this was related?

**Comment by sebastiansulinski** [comment]
When you check the package codebase you’ll see it is now using modules - hence needs es6 compiling.
