### ISSUE TITLE
Stylus: Unexpected character '@' (1:0)

### ISSUE THREAD

**Issue by daniel-chris-lucas** [JeffreyWay/laravel-mix#1245]
- Laravel Mix Version: 1.4.5
- Node Version: 6.9.2
- NPM Version: 3.10.9
- OS: macOS 10.13.0

### Description:

When installing vuetify I need to compile the stylus assets. When the assets are compiling I get the following errors:

```
error  in ./node_modules/vuetify/src/stylus/components/_selection-controls.styl

Module parse failed: /Users/dan/Code/Sites/practiceo/practiceo/node_modules/vuetify/src/stylus/components/_selection-controls.styl Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import '../bootstrap'
| @import '../theme'
|
```

The initial import works correctly but the succeeding imports cause errors.

### Steps To Reproduce:

Install vuetify: `yarn add vuetify`

Create the stylus entry point (`resources/assets/stylus/app.styl`) with the following content:

```
@import '../../../node_modules/vuetify/src/stylus/app'
```

Update `webpack.mix.js`file:
mix.stylus('resources/assets/stylus/app.styl', 'public/css/app.css');

**Comment by silvioiannone** [comment]
Can confirm this issue:

>  ERROR  Failed to compile with 1 errors                                                                                                                       > 12:07:25 PM
>
> error  in ./node_modules/vuetify/src/stylus/components/_content.styl
>
> Module parse failed: /Users/silvioiannone/Programming/Projects/Cluster/node_modules/vuetify/src/stylus/components/_content.styl Unexpected character '@' (1:0)
> You may need an appropriate loader to handle this file type.
> | @import '../bootstrap'
> |
> | .content

**Comment by johnboc** [comment]
Has anyone got to the bottom of this problem yet? I have just upgraded to Laravel 5.5 and am now getting this error. I also use Vuetify.

**Comment by pachoulie** [comment]
I experience the issue as well 😞

**Comment by pachoulie** [comment]
By adding the following to my webpack.mix.js, it compiles fine :)
```javascript
mix.webpackConfig({
  module: {
    rules: [
      {
        test: /\.styl$/,
        loader: ['style-loader', 'css-loader', 'stylus-loader', {
          loader: 'vuetify-loader',
          options: {
            theme: path.resolve('./node_modules/vuetify/src/stylus/theme.styl')
          }
        }]
      }
    ]
  }
})
```

**Comment by johnboc** [comment]
Thanks pachoulie, you've saved my day. For me, I needed the following code:
```
    mix.webpackConfig({
        module: {
            rules: [
                {
                    test: /\.styl$/,
                    loader: ['style-loader', 'css-loader', 'stylus-loader']
                }
            ]
        }
    })
```

**Comment by SumNeuron** [comment]
@johnboc where does that go in the rollup config?

**Comment by johnboc** [comment]
What do you mean by rollup config? The code goes in  webpack.mix.js

**Comment by SumNeuron** [comment]
I was hoping there was a rollup version...
