### ISSUE TITLE
JS always compiles to hidden directory

### ISSUE THREAD

**Issue by craigward** [JeffreyWay/laravel-mix#125]
```
mix.sass('scss/third-party.scss', '../think-cms/public')
   .sass('scss/public.scss', '../think-cms/public')
   .js('js/public.js', '../think-cms/public');
```

The above code when compiled with `npm run dev` gives the following output:
```
 DONE  Compiled successfully in 3225ms

                              Asset       Size  Chunks                    Chunk Names
        .think-cms/public/public.js     271 kB       0  [emitted]  [big]  public
../think-cms/public/third-party.css     227 kB       0  [emitted]         public
     ../think-cms/public/public.css     576 kB       0  [emitted]  [big]  public
                  mix-manifest.json  216 bytes          [emitted]
```

This is the output from mix-manifest.json
```
{
  ".think-cms/public/public.js": ".think-cms/public/public.js",
  "../think-cms/public/third-party.css": "../think-cms/public/third-party.css",
  "../think-cms/public/public.css": "../think-cms/public/public.css"
}
```

Is there something I am doing wrong as the JS file always compiles into a hidden directory?

**Comment by bvangraafeiland** [comment]
Seems to be a bug, iirc the './' part is stripped out somewhere in the js process. I suppose the assumption is that you use mix in the root folder of your project, why don't you?

**Comment by craigward** [comment]
For now, I am just using the .copy() to move the file

the way I structure my projects folder wise is

-Project Name
-- frontend theme (all scss, js, mix config etc)
-- Laravel installation
-- Backend theme (all scss, js, mix config etc)
-- Homestead (mostly use Valet these days)

I find that structure helps me stay organised as projects grow. I hated it when the root folder had loads of files like package.json, grunt, gulp, PHPUnit etc. I found it hard to know which file was for which part of the project. Might just be me, but I find this works.

**Comment by bvangraafeiland** [comment]
I've looked at it a bit more, and you should set the public path to wherever you want the output to be placed. In your case that should probably be like `mix.setPublicPath('../think-cms')`, or alternatively `mix.config.publicPath = '../think-cms'`. Does that work?

**Comment by craigward** [comment]
Yeah, setPublicPath() works, can't believe I overlooked that in the API comments at the bottom of the file :/
