### ISSUE TITLE
Contributing guide?

### ISSUE THREAD

**Issue by pori** [JeffreyWay/laravel-mix#1252]
Hey there! 

I was interested in contributing but didn't see a relevant guide anywhere in the repo. If there's any on getting started, that would be lovely! 

It'd be helpful to have since there are quirks like tests running under `sudo` for the dev environment that I don't really understand. 🤷🏼‍♀️

**Comment by ruchern** [comment]
Just submit pull request. 😂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kylekatarnls** [comment]
Hi @pori, I'm also interested in contributing, and I'm agree `sudo` in the package.json command is a bit surpising and quite of an exclusion for Windows users. So I would propose to set it to `"test": "sudo nyc ava --verbose || nyc ava --verbose"`, this way everybody could run it. With my machine `nyc ava --verbose` succeed so I guess `sudo` is not always necessary.

I'm also agree a CONTRIBUTING.md with some guidlines, how to clone, install dependencies and run npm even if it's classical, it make a good entry point for new contributors to get their dev environments quickly ready. I guess we could write such guide for next devs if @JeffreyWay is agree.
