### ISSUE TITLE
Webpack config cannot extend plugins

### ISSUE THREAD

**Issue by justkidding96** [JeffreyWay/laravel-mix#126]
Hi everybody,

I  noticed that I can't implemented a plugin through the given extend method. My code looks like this:
```javascript
mix.webpackConfig({
    plugins: [
        new BrowserSyncPlugin({
            host: 'localhost',
            port: 3000,
            server: { baseDir: ['./public'] },
            files: ['public/**']
        })
    ]
});
```
Did I miss something or is this not going to work? @JeffreyWay Maybe u can explain a little more over the extend method?

**Comment by justkidding96** [comment]
This issue is fixed with the solution mentioned above 👍

**Comment by mathieutu** [comment]
Glad I'm not the only one with this problem. 
I think you should re open the issue, just the time before the PR will be merged and the problem fixed.
