### ISSUE TITLE
Vue@2.5.0 packages version mismatch with vue-template-compiler@2.4.4

### ISSUE THREAD

**Issue by huydbui** [JeffreyWay/laravel-mix#1262]
- Laravel Mix Version: 1.5.0 (`npm list --depth=0`)
- Node Version (`node -v`): 8.6.0 
- NPM Version (`npm -v`):  5.3.0
- OS: Docker php:7.1.10-fpm

### Description:
Module build failed: Error:

Vue packages version mismatch:

- vue@2.5.0
- vue-template-compiler@2.4.4

### Steps To Reproduce:
- Everything is working fine with ("vue": "^2.4.4")

- As soon as I run: npm update, only vue got update to v2.5.0.

- Run "npm run watch" and I see the error above.

- Reinstall vue v2.4.4 brings everything back to normal.

**Comment by ruchern** [comment]
Just run this `npm install -D vue-template-compiler` on your own to fix the issue.

**Comment by huydbui** [comment]
For some reason it only failed on my desktop. Even after I removed node_modules and reinstalled all packages. On my laptop, everything is fine. Same project, same package.json. Anyway, sorry for this ticket. Case closed!
