### ISSUE TITLE
Running test (npm test or yarn test) without using sudo

### ISSUE THREAD

**Issue by ruchern** [JeffreyWay/laravel-mix#1265]
- Laravel Mix Version: v1.5.0 (`npm list --depth=0`)
- Node Version (`node -v`): v8.7.0
- NPM Version (`npm -v`): v5.5.1
- OS: macOS 10.13.1

### Description:
`npm test` or `yarn` test requires `sudo` since the script for "test" is explicitly set as `sudo nyc ava --verbose`. Is there a way to run the test without using `sudo`?

### Steps To Reproduce:
1. Run `npm test` or `yarn test`

**Comment by ankurk91** [comment]
Ref #1267

**Comment by bloggervista** [comment]
@ankurk91  how is that related with it. That ref is for windows user. And it seems op is raising issue for mac. I guess you want to ref other issue :)

**Comment by ankurk91** [comment]
That PR not only fixes windows issues but also the need of sudo in tests.

**Comment by pori** [comment]
What was the original need for sudo, exactly?
