### ISSUE TITLE
Error when compiling material-components-web

### ISSUE THREAD

**Issue by rafael-franca** [JeffreyWay/laravel-mix#1269]
- Laravel Mix Version (`npm list --depth=0`): 1.5.0
- Node Version (`node -v`): 6.11.4
- NPM Version (`npm -v`): 5.5.1
- OS: Windows 10 (1709) Fall Creators Update 16299.15.

### Description:
Error when compiling Material Components Web.

> \js\app.js from UglifyJs
Unexpected token operator «=», expected punc «,» [./node_modules/@material/auto-init/index.js:21,0][\js\app.js:31806,46]

### Steps To Reproduce:
Execute ```npm install --save material-components-web````.
Add ```window.mdc = require('material-components-web');``` to app.js in Laravel.
Add ```@import "node_modules/material-components-web/material-components-web";``` to app.scss in Laravel.

Execute ```npm run dev```, it's OK!
Execute ```npm run prod```, show this error:

> \js\app.js from UglifyJs
Unexpected token operator «=», expected punc «,» [./node_modules/@material/auto-init/index.js:21,0][\js\app.js:31806,46]

**Comment by ankurk91** [comment]
Replace this line
```js
window.mdc = require('material-components-web');
```
with this
```
window.mdc = require('material-components-web/dist/material-components-web');
```
and report back here

**Comment by rafael-franca** [comment]
@ankurk91 Thanks for you reply! It's works perfectly. :)

**Comment by rafael-franca** [comment]
Searching in Google, I found [this](https://ctf0.wordpress.com/2017/09/12/laravel-mix-es6/). When I tested, surprise, **it's worked perfectly**.

In resume..

1. Execute: ```npm install --save-dev babel-preset-es2015 babel-preset-stage-2 babel-preset-env``` if you use _npm_, or ```yarn add --dev babel-preset-es2015 babel-preset-stage-2 babel-preset-env``` if you prefer use _yarn_.

2. Then, add these lines before your _mix.js()_:
```
mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.jsx?$/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['env', 'es2015', 'stage-2']
                    }
                }
            }
        ]
    }
});
```

**Comment by ankurk91** [comment]
You are overriding the babel-loader configs.
Laravel mix already comes with babel-preset-env.

As is said, Laravel-mix excludes `node_modules` for babel-loader, see

https://github.com/JeffreyWay/laravel-mix/blob/07facaa2e700700c34c0aebf77ec2c28cc065973/src/builder/webpack-rules.js#L9-L18

So don't override the loader. This will slow down the build process.
Just reference right module in your code.
