### ISSUE TITLE
npm run watch .js error file

### ISSUE THREAD

**Issue by ItsLhoudini** [JeffreyWay/laravel-mix#1278]
When I run command "npm run watch" or "npm run watch-poll", the script generates a bugged .js file, and the browser console shows "Uncaught SyntaxError: Invalid or unexpected token".

If I try to open the js file with Sublime Text (Finder show me Zero KB), seems that the script falls in a never ending loop writing in the js file null and after the compiled js script, null and so on...

No problem running the "npm run watch" with only the scss files or, with the js, running "npm run dev".

Here's my configs:

**Node**: 8.1.4
**NPM**: 5.5.1
**Laravel mix**: 1.5.0

**Webpack.mix.js:**

```
const {mix} = require('laravel-mix');
const dotenv = require('dotenv-webpack');

mix.webpackConfig({
    plugins: [
        new dotenv({
            path: './.env', // Path to .env file (this is the default)
            safe: true // load .env.example (defaults to "false" which does not use dotenv-safe)
        })
    ]
})
    .js('./resources/assets/javascripts/app.js', './public/assets/javascripts/web.min.js')
    .sass('./resources/assets/stylesheets/main.scss', './public/assets/stylesheets/main.min.css')
    .scripts([
            './public/assets/javascripts/web.min.js',
            './node_modules/jquery-migrate/dist/jquery-migrate.min.js',
            './node_modules/jquery.stellar/jquery.stellar.js'
        ], './public/assets/javascripts/web.min.js'
    )
    .extract([
        'axios',
        'jquery',
        'lodash',
        'vue'
    ]);

```
HELP ME!

**Comment by artemsky** [comment]
why you trying to pack your output script. `web.min.js`
it's not valid code

**Comment by ItsLhoudini** [comment]
So what can I do? How can I fix it?

**Comment by artemsky** [comment]
One of the possible solutions in my option.

1. Remove `scripts`
2. Import you deps directly in **app.js**

```
import 'jquery-migrate';
import 'jquery.stellar';
```

**Comment by ItsLhoudini** [comment]
Good!
Another problem is importing jquery-migrate generates an error "define cannot be used indirect". So I pack the code for this reason.

**Comment by artemsky** [comment]
So that is an issue with `jquery-migrate` `^3.0.1`+ - https://github.com/jquery/jquery-migrate/issues/273

You should require `3.0.0` (without`^`) in your **package.json**

or disable amd import for this lib

```
mix.webpackConfig({
 module: {
        rules: [
            {
                test: require.resolve("jquery-migrate"),
                use: "imports-loader?define=>false",
            }
        ],
    },
})
```

**Comment by ItsLhoudini** [comment]
WORKS FINE! Thanx

**Comment by alihamidreza** [comment]
no way
