### ISSUE TITLE
Minification in dev

### ISSUE THREAD

**Issue by ionesculiviucristian** [JeffreyWay/laravel-mix#1280]
How can I apply minification when running `npm run dev` on every file change? I don't want to use the production variant each time I'm finished with the changes.

**Comment by JeffreyWay** [comment]
You can’t. Why would you want minified code for development?

**Comment by ionesculiviucristian** [comment]
Because some projects require small modifications frequently and the extra step becomes annoying over time.

**Comment by antoinejaunard** [comment]
Hey, i'm looking for the exact same thing.
Did you find a way to accomplish it? Thanks

**Comment by glennjacobs** [comment]
You can do this, just change the scripts in the package.json file and change the node environment.
