### ISSUE TITLE
Browser sync is not reloading browser when I make changes on PHP blade files. 

### ISSUE THREAD

**Issue by thisprojectworks** [JeffreyWay/laravel-mix#1288]
- Laravel Mix Version: 1.5.1 
- Node Version (`node -v`): v8.7.0
- NPM Version (`npm -v`): 5.4.2
- OS: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-81-generic x86_64) (**HOMESTEAD**)

### Description:

I can not make 'browserSync' work properly on a fresh install of laravel 5.5
The browser is not refresh when I make a change in blade PHP files. But It is working well with the .sass and .js files.

This is my webpack.mix.js:

```
mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .browserSync({
        proxy: 'dearpeninsula.app'
    });
```

I try to put the option files, and with this option, browsersync is not working on changes files of any type:

```
mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .browserSync({
        proxy: 'dearpeninsula.app',
        files: ['resources/views/**/*.*', 'resources/assets/**/*.*']
    });

```
I have to say, that I have a head and a body tag in the blade file, I work with the standard welcome.blade.php file that laravel provide in the installation. 

### Steps To Reproduce:

I install a fresh Laravel 5.5 with the command laravel new, in a fresh directory. 
I aplicate 'php artisan key:generate' command to generate laravel's key. 
I install npm with command npm install.

I add to the file webpack.mix.js browserSync. 
```
mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .browserSync({
        proxy: 'dearpeninsula.app'
    });
```
I execute 'npm run dev'
I execute 'npm run watch-poll' because 'npm run watch' is not working and not compile any changes in files.

And that is all. 

Many thanks for your help, yesterday I expend many hours to try to fix it without results.

**Comment by marcamos** [comment]
I have a similar configuration; the difference in mine (below) is that I've kept the `php` file-extension in place:

```js
mix
  .autoload({
    jquery: ['$', 'window.jQuery', 'jQuery'],
    'ally.js/ally.js': ['ally']
  })
  .js('_js/app.js', 'public/lib/js')
  .sass('_scss/app.scss', 'public/lib/css')
  .options({
    processCssUrls: false
  })
  .sourceMaps()
  .browserSync({
    proxy: 'starter.dev',
    files: [
      'public/lib/css/app.css',  // Generated .css file
      'public/lib/js/app.js',    // Generated .js file
      // =====================================================================
      // You probably need only one of the below lines, depending
      // on which platform this project is being built upon.
      // =====================================================================
      'public/**/*.+(html|php)',          // Generic .html and/or .php files [no specific platform]
      'laravel/resources/views/**/*.php', // Laravel-specific view files
      'craft/templates/**/*.+(html|twig)' // Craft-specific templates, as html and/or twig
    ]
  });
```

**Comment by thisprojectworks** [comment]
It still does not work with that configuration...

**Comment by g0thman** [comment]
gulp.task('browser-sync', function() {
    browserSync.init({
      watch: true,         // <-- try adding this line to your code when you have a live-reload problem 
      server: {
          baseDir: './'
      },
      port: 8080
  });
});

**Comment by g0thman** [comment]
```
gulp.task('browser-sync', function() {
    browserSync.init({
      watch: true,    // <-- try adding this line when you have a live-reload problem
      server: {
          baseDir: './'
      },
      port: 8080
  });
});
```

**Comment by stuartcusackie** [comment]
based on the answers above by alesvaupotic and marcamos:

```
mix.js('resources/js/admin.js', 'public/js')
   .sass('resources/sass/app.scss', 'public/css')
   .browserSync({
	   	proxy: 'homestead.test',
	    files: [
		      'public/css/app.css',
		      'public/js/app.js',
		      'app/**/*',
		      'routes/**/*',
		      'resources/views/**/*',
              'resources/lang/**/*'
	    ]
	});
```

**Comment by ilgala** [comment]
> This works for me in L5.7.
> Based on the answers above by alesvaupotic and marcamos:
> 
> ```
> mix.js('resources/js/app.js', 'public/js')
>    .sass('resources/sass/app.scss', 'public/css')
>    .browserSync({
> 	   proxy: 'homestead.test',
> 	   files: [
>                 'public/css/app.css',
> 		'public/js/app.js',
> 		'app/**/*',
> 		'routes/**/*',
> 		'resources/views/**/*',
>                 'resources/lang/**/*'
> 	    ]
>     });
> ```

This configuration works for me with Laravel 5.7... I've just changed the `files` attribute from

    [
      'public/css/app.css',
      'public/js/app.js',
      'app/**/*',
      'routes/**/*',
      'resources/views/**/*',
      'resources/lang/**/*'
    ]

to

    [
        'resources/**/*'
    ]

In order to reload the browser only while developing frontend stuff

**Comment by pcampina** [comment]
IN 2020 (Laravel 7), config is:

```
mix
  .js("resources/js/app.js", "public/js")
  .sass("resources/sass/app.scss", "public/css")
  .browserSync({
    proxy: 'localhost', // your domain test
    port: 32816 // your port
  });
```

**Comment by Faeza97** [comment]
> IN 2020 (Laravel 7), config is:
> 
> ```
> mix
>   .js("resources/js/app.js", "public/js")
>   .sass("resources/sass/app.scss", "public/css")
>   .browserSync({
>     proxy: 'localhost', // your domain test
>     port: 32816 // your port
>   });
> ```

 Can you show your node setup in docker-compose.yml ?

**Comment by pcampina** [comment]
@Faeza97 I don't use node inside docker for this case but i'm recomend to you [lando](https://docs.lando.dev/config/node.html) to set this made easy peasy

**Comment by rasmuscnielsen** [comment]
So I just found that my issue with BrowserSync not picking up changes wasn't related to the mix configuration at all.

Rather, after debugging waaay longer than I'd like to admit, I found that having the project folder located inside a Google Drive synced folder was causing the issue 😄 

Hope this might help someone else!

**Comment by 60ss** [comment]
add meta tag csrf-token into html head
`<meta name="csrf-token" content="{{ csrf_token() }}">`

**Comment by james0r** [comment]
For me the issue was I was passing some paths to `files: []` that I guess were malformed, and BrowserSync was just silently failing to update the browser. I ended up just changing my watch files paths and it's reloading fine now.
