### ISSUE TITLE
hot-reload wrong paths on Windows

### ISSUE THREAD

**Issue by TeroBlaZe** [JeffreyWay/laravel-mix#129]
It seems to be like #78 issue but with css also

http://localhost:8080/css/app.css
> Cannot GET /css/app.css

http://localhost:8080/public/css/app.css
> OK

The problem also with #97 PR is that now
http://localhost:8080/js/app.js === http://localhost:8080/public/js/app.js
The files accessible from both URLs but the files with /public/** path is non hot-reloadable

**Comment by bvangraafeiland** [comment]
For me, with just `npm install laravel-mix`, then copying the `scripts` part to `package.json`, creating dummy files in `src/`, then running `npm webpack` followed by `npm hmr`, I do get the CSS file at http://localhost:8080/dist/app.css (Windows 7 here). Could you try doing those steps?

**Comment by TeroBlaZe** [comment]
@bvangraafeiland I'm using it with laravel 5.3 as a replacement of elixir.

**Comment by Drake-Guo** [comment]
Same problem here as of v0.8.9

**Comment by JeffreyWay** [comment]
Fixed in 0.10.0.
