### ISSUE TITLE
Feature Request: PurifyCSS options per file

### ISSUE THREAD

**Issue by OzairP** [JeffreyWay/laravel-mix#1293]
- Laravel Mix Version: 1.0.0 (`npm list --depth=0`)
- Node Version (`node -v`): 8.6.0
- NPM Version (`npm -v`): 5.3.0
- OS: macOS Sierra

### Description:
It would be great if we can run PurifyCSS/UnCSS per file. That way our responsive utilities will not get removed.

```JS
mix
	.sass('resources/assets/sass/app.sass', 'public/css', {
          'purifyCSS': true
    })
	.sass('resources/assets/sass/responsive.sass', 'public/css')
```

**Comment by JeffreyWay** [comment]
I don't have any plans to add this for now, since it's a fringe feature that not many people use.
