### ISSUE TITLE
Bug with solution

### ISSUE THREAD

**Issue by JackEllis** [JeffreyWay/laravel-mix#1296]
npm run hot would return: 

Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

I found that I had to go into package.json and change npm run hot to have "--host http://LOCAL_URL_IM_USING" and then it worked great

**Comment by JeffreyWay** [comment]
Okay thanks. Will try to add a note to the docs.
