### ISSUE TITLE
Add entry object

### ISSUE THREAD

**Issue by Goldfinch** [JeffreyWay/laravel-mix#1299]
Just recently have updated laravel-mix and faced with one problem.

On the previous version that I had before (v0.12.1), in webpack.mix.js I've been using **entry** through **mix.config** to add some custom assets, it looked like so:

```javascript
for (let file of glob.sync('./resources/pages/*.njk', { ignore: '**/_*' })) {
  mix.config.entry().entry.add('mix', path.resolve(file));
}
```
since v1.0.0, the [entry()](https://github.com/JeffreyWay/laravel-mix/blob/v0.12.1/src/Mix.js#L49) method was removed from Mix class.

What is the proper way to call and add entry object on the latest version?

**Comment by artemsky** [comment]
take a look - https://github.com/JeffreyWay/laravel-mix/pull/1248

**Comment by JeffreyWay** [comment]
@Goldfinch You shouldn't edit Mix's entry object directly. Any tweaks to entry should be performed via Mix's API.
