### ISSUE TITLE
Compiling SASS and Plain CSS into a single CSS file

### ISSUE THREAD

**Issue by FilipQL** [JeffreyWay/laravel-mix#130]
Hi,

On [Vuecasts](http://vuecasts.com/) I watched the video that introduces Laravel Mix.  I am wondering if there is going to be any new feature that will more elegantly solve the problem of compiling SASS and plain CSS into a single CSS file: https://laracasts.com/discuss/channels/elixir/compiling-sass-and-plain-css-into-a-single-css-file?

**Comment by JeffreyWay** [comment]
Can your Sass entry point not just import the CSS file?

**Comment by FilipQL** [comment]
@JeffreyWay Importing the CSS file in Sass entry point didn't work... at least it didn't work with some "pure" CSS libraries (such as Animate.css) installed via npm... As  ejdelmonico suggested on Laracasts forum - we need to change the css extension to scss, import it and use mix.sass. I was wondering whether there will be a more elegant solution in the future.

**Comment by OwenMelbz** [comment]
Might not be a global .css fix.

However for animate.css we're loading it fine via app.scss defining only the animations we want

```css
@import 'node_modules/animate.css/source/base';
@import 'node_modules/animate.css/source/sliding_entrances/slideInDown';
@import 'node_modules/animate.css/source/sliding_exits/slideOutUp';
```

**Comment by FilipQL** [comment]
@OwenMelbz Cool 👍

**Comment by romanzpolski** [comment]
after installing animate.css with npm,  
in /resources/assets/sass/app.scss place this:

@import 'node_modules/animate.css/animate';

Then run laravel-mix, works fine for me. Laravel 5.4

**Comment by bradley-varol** [comment]
I'd like this feature. The following doesn't compile with mix:

```js
mix.sass([
    'node_modules/package_name/css/package_name.css',
    // ...
], 'public/css/app.css');
```
