### ISSUE TITLE
Allow node-sass 4.6.0?

### ISSUE THREAD

**Issue by roddypratt** [JeffreyWay/laravel-mix#1306]
Any chance that the node-sass dependency could be updated to allow 4.6.0?

I seem to have shot myself in the foot with by updating to node.js 9.1 -  which 4.5.3 doesn't have a prebuilt binary for.  So (being on windows) I'm into Windows node-gyp build hell...

**Comment by ruchern** [comment]
Have you tried manually install `node-sass` into your `devDependencies`?

**Comment by roddypratt** [comment]
Hmm. I did `yarn add node-sass --dev` which runs fine and adds `"node-sass": "^4.6.0"` to package.json. but when I then add laravel-mix, it still fails downloading `https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node` (which doesn't exist).

**Comment by ruchern** [comment]
What about adding `Laravel Mix` then `node-sass`? Does that not work?

**Comment by roddypratt** [comment]
Laravel Mix explicitly requires node-sass 4.5.3 according to it's package.json, so when you do `yarn add laravel-mix` yarn tries to download the correct pre-built binary for node-sass, according to your node.js version. I have node.js 9 installed, and there's no node-sass 4.5.3 binary for that version.

**Comment by roddypratt** [comment]
just seen this commit message: https://github.com/JeffreyWay/laravel-mix/commit/03ae69849ac6c7454e299f964a9f977eab7e36c8

So looks like the 4.5.3 dependency is intentional right now, and Jeffrey is aware :)

**Comment by roddypratt** [comment]
@ruchern @JeffreyWay Looks like node-sass 4.6.1 has fixed the watcher bug.

**Comment by JeffreyWay** [comment]
@roddypratt Checking that discussion, it still seems like folks are having problems - even with 4.6.1. So I'm going to hold off a bit longer.

**Comment by LeoColomb** [comment]
> So I'm going to hold off a bit longer.

Then is it possible to keep this issue open? Will make it easier to follow resolution for everyone.

> Checking that discussion, it still seems like folks are having problems

Which discussion? On https://github.com/sass/node-sass/pull/2147 nothing has been added/reported since release 4.6.1...

Thx! 👍

**Comment by JeffreyWay** [comment]
https://github.com/sass/node-sass/issues/2139

**Comment by bungcip** [comment]
I also got the same error when upgrading my node to 9.2 in windows 10. Is there is any workaround beside downgrading my node version?

**Comment by LeoColomb** [comment]
@bungcip You can pin `lavarel-mix` to version `1.5.0`, but keep in mind it can be buggy.

@JeffreyWay Looks like node-sass [4.7.0](https://github.com/sass/node-sass/releases/tag/v4.7.0) has fixed the watcher bug (seems really fixed this time 😄).

**Comment by bungcip** [comment]
@LeoColomb, thank you. pinned to `1.5.0` for now.
