### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by Ace217** [JeffreyWay/laravel-mix#1308]
whenever i run npm install in cmd, i get the following error:

npm ERR! path C:\xampp\htdocs\basicwebsite\node_modules\errno\cli.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\xampp\htdocs\basicwebsite\node_modules\errno\cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

-->

- Laravel Mix Version: 1.0
- Node Version (`node -v`): 9.0.0
- NPM Version (`npm -v`): 5.5.1
- OS: Windows 10 x64

can someone help me please?

**Comment by artemsky** [comment]
issue with node 9

try to
```
rm -rf node_modules && rm package-lock.json && npm cache clean -f && npm i
```

**Comment by Ace217** [comment]
@artemsky
getting this
'rm' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ruchern** [comment]
@artemsky OP is using Windows. 

@Ace217 can you try `rmdir` in place of `rm`?

**Comment by artemsky** [comment]
@ruchern @Ace217 
I thought all dev's using git-bash instead of PS/CMD on windows)

**Comment by Ace217** [comment]
@artemsky @ruchern 

after making a new laravel project, npm install worked fine, but now i'm getting an error on npm run dev:

C:\xampp\htdocs\hellolaravel
λ npm run dev

> @ dev C:\xampp\htdocs\hellolaravel
> npm run development


> @ development C:\xampp\htdocs\hellolaravel
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

module.js:544
    throw err;
    ^

Error: Cannot find module 'pseudomap'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\ammar\AppData\Roaming\npm\node_modules\cross-env\node_modules\lru-cache\index.js:7:11)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ammar\AppData\Roaming\npm-cache\_logs\2017-11-10T07_15_24_979Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ammar\AppData\Roaming\npm-cache\_logs\2017-11-10T07_15_25_022Z-debug.log

**Comment by BonBonSlick** [comment]
```
bonbon@bonbons:/var/www/testtask$ rm -rf node_modules && rm package-lock.json && npm cache clean -f && npm i
npm WARN using --force I sure hope you know what you are doing.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN notice [SECURITY] tunnel-agent has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=tunnel-agent&version=0.4.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] hoek has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=2.16.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> node-sass@4.9.0 install /var/www/testtask/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/bonbon/.npm/node-sass/4.9.0/linux-x64-59_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /var/www/testtask/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.9.0 postinstall /var/www/testtask/node_modules/node-sass
> node scripts/build.js

Binary found at /var/www/testtask/node_modules/node-sass/vendor/linux-x64-59/binding.node
Testing binary
Binary is fine

> gifsicle@3.0.4 postinstall /var/www/testtask/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> mozjpeg@5.0.0 postinstall /var/www/testtask/node_modules/mozjpeg
> node lib/install.js

  ✔ mozjpeg pre-build test passed successfully

> optipng-bin@3.1.4 postinstall /var/www/testtask/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> pngquant-bin@4.0.0 postinstall /var/www/testtask/node_modules/pngquant-bin
> node lib/install.js

  ⚠ The `/var/www/testtask/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/var/www/testtask/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bonbon/.npm/_logs/2018-05-27T16_07_25_960Z-debug.log

```

**Comment by premwebdeveloper** [comment]
I am facing same error during npm install  


E:\xampp\htdocs\laravelchat>npm install
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guide

> node-sass@4.9.0 install E:\xampp\htdocs\laravelchat\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\Dell\AppData\Roaming\npm-cache\node-sass\4.9.0\win32-ia32-64_b

> uglifyjs-webpack-plugin@0.4.6 postinstall E:\xampp\htdocs\laravelchat\node_modules\webpack\n
> node lib/post_install.js


> node-sass@4.9.0 postinstall E:\xampp\htdocs\laravelchat\node_modules\node-sass
> node scripts/build.js

Binary found at E:\xampp\htdocs\laravelchat\node_modules\node-sass\vendor\win32-ia32-64\bindin
Testing binary
Binary is fine

> gifsicle@3.0.4 postinstall E:\xampp\htdocs\laravelchat\node_modules\gifsicle
> node lib/install.js

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: write EIO
    at afterWriteDispatched (internal/stream_base_commons.js:75:25)
    at writeGeneric (internal/stream_base_commons.js:70:3)
    at WriteStream.Socket._writeGeneric (net.js:757:5)
    at WriteStream.Socket._write (net.js:769:8)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at WriteStream.Writable.write (_stream_writable.js:294:11)
    at Squeak.log (E:\xampp\htdocs\laravelchat\node_modules\squeak\index.js:143:14)
    at Squeak.(anonymous function) [as success] (E:\xampp\htdocs\laravelchat\node_modules\sque
    at E:\xampp\htdocs\laravelchat\node_modules\gifsicle\lib\install.js:33:6
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:425:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at WriteStream.stderr._destroy (internal/process/stdio.js:45:7)
    at WriteStream.destroy (internal/streams/destroy.js:32:8)
    at afterWriteDispatched (internal/stream_base_commons.js:75:17)
    at writeGeneric (internal/stream_base_commons.js:70:3)
    [... lines matching original stack trace ...]
    at doWrite (_stream_writable.js:410:12)
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must inst
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@3.0.4 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gifsicle@3.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output ab

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2018-06-22T12_37_14_858Z-debug.log
