### ISSUE TITLE
Set custom path for chunk files

### ISSUE THREAD

**Issue by leonfather** [JeffreyWay/laravel-mix#1309]
- Laravel Mix Version: 1.6.0 (`npm list --depth=0`)
- Node Version (`node -v`): 
- NPM Version (`npm -v`): 
- OS: 

### Description:
Hello, My laravel structure is : 
/myApp/ (/app, /config, /resources....) <= laravel
/wpublic (/js, /css) <= here i put my index.php file, this is the content of my public folder 
How can i set a custom path for chunk files?
For example for js files i want using this path /wpublic/js and for chunks /wpublic/js/chunks

**Comment by artemsky** [comment]
Take a look here - https://github.com/JeffreyWay/laravel-mix/pull/1248

**Comment by ankurk91** [comment]
[Search](https://github.com/JeffreyWay/laravel-mix/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20chunk) before creating new issue

```js
//webpack.mix.js
mix.webpackConfig({
    output: {
        chunkFilename: 'js/[name].js',
    },
});
```

**Comment by leonfather** [comment]
@ankurk91 This is not what i want. please try to undestand question before answering

**Comment by ankurk91** [comment]
@leonfather

> How can i set a custom path for chunk files?

I gave answer to above question.

**Comment by leonfather** [comment]
@ankurk91 Thank you

**Comment by JibrilYasin** [comment]
Hi @ankurk91 ,, I have a problem. When I access a url with parameters like "http://localhost/laravel/5.4/edit-user/1" with the vue router everything is fine. But when I refresh the browser, I found the error and redirect to url "http://localhost/laravel/5.4/".

**Comment by ankurk91** [comment]
I suspect you have enabled html5mode in your Vue router.
Usually js routes url includes a hash bang `#` .
You are getting 404 because that routes does not exits.
You should watch Vue js routing video on laracast.

**Comment by ankurk91** [comment]
Read more about html5mode here :
https://router.vuejs.org/en/essentials/history-mode.html

**Comment by JibrilYasin** [comment]
Solve the issue when I edit the webpack.mix. js from "publicPath:/protected/public/" to "publicPath : http://localhost/laravel/5.4/protected/public/"

**Comment by JibrilYasin** [comment]
But how to be a dynamic baseurl? without adding "http://localhost/laravel/5.4/" on publicPath

**Comment by ankurk91** [comment]
Public Path should be a physical harddisk location.
There is a difference between path and url.
I would suggest to create a virtual host for your  laravel installation.

**Comment by JibrilYasin** [comment]
empp,, so what if I upload to hosting later?

**Comment by ankurk91** [comment]
Don't run too fast. Solve your issues one by one. Learn the basics, clear the concepts. 
I can't teach you the whole development flow.
Jeffrey way runs a free website called Laracasts for people like you.
Invest some time in watching those webseries and you will no longer require asking such questions.

**Comment by theshashiverma** [comment]
@ankurk91 Thank you so much bro

**Comment by theshashiverma** [comment]
@ankurk91 can we also extract the css chunks file? as we extract the js chunk files. I am using laravel with vuejs. Please help me

**Comment by ankurk91** [comment]
I would suggest to to use dynamic component with scoped css.

https://github.com/JeffreyWay/laravel-mix/issues/1249#issuecomment-335112415
https://alligator.io/vuejs/lazy-loading-vue-cli-3-webpack/
