### ISSUE TITLE
Empty sourcemap generated on production

### ISSUE THREAD

**Issue by MartijnBastiaansen** [JeffreyWay/laravel-mix#1310]
- Laravel Mix Version: 1.6.1 
- Node Version: 8.9.1
- NPM Version: 5.5.1
- OS: centos 6.9

### Description:
.sass method with .sourceMaps() generates an empty sourcemap on production. On develop mode it's writes the sourcemap into the css file

mix config:
`mix.sass('resources/assets/sass/beheer/style.scss', 'public/css/beheer').sourceMaps();`

The scss files imports multiple other scss files

The outcome of the .map file is:

`{"version":3,"file":"/css/beheer/style.css","sources":[],"mappings":"","sourceRoot":""}`

We tried the workaround with ` mix.webpackConfig({devtool: 'inline-source-map'})` but we are trying to get the mapfiles filled with the correct data

### Steps To Reproduce:
We have got a fresh install of laravel and are trying to get the source maps working. That is also the reason that our mix config is really basic at the moment.

**Comment by natocTo** [comment]
Maybe related to https://github.com/JeffreyWay/laravel-mix/pull/1303

You can try.

``` javascript
mix.options({
    sourcemaps: 'source-map',
    uglify: {
        sourceMap: true
    }
})
```

**Comment by natocTo** [comment]
Maybe related to https://github.com/JeffreyWay/laravel-mix/pull/1303

You can try.

``` javascript
mix.options({
    sourcemaps: 'source-map',
    uglify: {
        sourceMap: true
    }
})
```

**Comment by MartijnBastiaansen** [comment]
mix.options is working and the sourcemap is filled now.

But there is a weird bug where webpack is repeating the folder structure:

`// WEBPACK FOOTER //
// ./resources/assets/sass/beheer/resources/assets/sass/beheer/additions/_buttons-add.scss`

And the folder structure isn't inside of the dev tools, but is just one folder with the above name
