### ISSUE TITLE
extract required files into vendors

### ISSUE THREAD

**Issue by ArashAlikhani** [JeffreyWay/laravel-mix#1312]
I have a vendor js file that I have to require explicitly in my module js file:
```
window.$ = require('jquery');
require('../semantic/semantic');
window._ = require('lodash');
window.ax = require('axios');
```
I want to know if it is possible to extract it with other vendors?
I tried to define it like this in extract function:
```
mix.js('resources/assets/js/admin.js', 'public/js')
    .extract(['jquery', 'resources/assets/semantic/semantic.js', 'lodash', 'axios']);
```
but got `This dependency was not found` error.
I also tried other options like `../semantic/semantic` or `semantic` and some other options that I think may work but nothing worked.
I want to know if it is possible to extract a file with other vendor npm packages or not?

**Comment by ankurk91** [comment]
When you specify 
```
resources/assets/semantic/semantic.js
```
Webpack thinks that is a package that is installed in node_modules folder.
Did you tried this -
```js
.extract(["./resources/assets/semantic/semantic.js"])
```

**Comment by ArashAlikhani** [comment]
It worked fine. Thanks a lot @ankurk91
