### ISSUE TITLE
[QUESTION] is there a way to automatically compile when deploying on Forge?

### ISSUE THREAD

**Issue by fabiolrs** [JeffreyWay/laravel-mix#1313]
Currently what I do is run npm run production prior to committing my code, so I can commit the uglyfied/minified versions and automatically deploy to Forge.

Is there a more elegant way?

**Comment by stefanzweifel** [comment]
You could update your Deploy Script in Forge to run `npm run production` for you.

Could look like this:

```shell
cd /home/forge/example.com
git pull origin master
npm install # Install dependencies
npm run production # Run build process
```

**Comment by fabiolrs** [comment]
Cool. Will try. Issue can be closed.

Thanks

**Comment by ruchern** [comment]
@fabiolrs You can close issues you created

**Comment by ryanpaulfyfe** [comment]
> You could update your Deploy Script in Forge to run `npm run production` for you.
> 
> Could look like this:
> 
> ```shell
> cd /home/forge/example.com
> git pull origin master
> npm install # Install dependencies
> npm run production # Run build process
> ```

This worked for me, but something to note is that I ran into issues with the broader build script itself as the production server had git changes as a result, so during deploy it wouldn't work without doing a git stash first - 

```
git stash
git pull origin master
```
