### ISSUE TITLE
Multiple resource root in one app

### ISSUE THREAD

**Issue by the94air** [JeffreyWay/laravel-mix#1317]
- Laravel Mix Version: v1.6.1
- Node Version: v9.1.0
- NPM Version: v5.5.1
- OS: Ubuntu 16.04

### Description:
@ankurk91 I am trying to use multiple root URLs in one project but no matter what I did laravel-mix will use the second url in all cases `http://admin-cdn.app.dev/`. Any way to get around this? thanks.

### Steps To Reproduce:
```javascript
mix.setResourceRoot('http://client-cdn.app.dev/')
   .sass( ... , ... );

mix.setResourceRoot('http://admin-cdn.app.dev/')
   .sass( ... , ... );
```

**Comment by ankurk91** [comment]
This has been asked previously.

https://github.com/JeffreyWay/laravel-mix/issues/1234
https://github.com/JeffreyWay/laravel-mix/issues/989

**Comment by the94air** [comment]
Thanks for the fast response.

**Comment by the94air** [comment]
@ankurk91 [laravel-multimix](https://github.com/fandogh/laravel-multimix) Solved my issue. Thanks
