### ISSUE TITLE
production build breaks vuex

### ISSUE THREAD

**Issue by hailwood** [JeffreyWay/laravel-mix#1318]
- Laravel Mix Version: 1.6.1
- Node Version: 8.2.0 
- NPM Version: 5.5.1
- OS: Ubuntu 16.10

### Description:
Uglify in laravel-mix appears to break vuex.

The app runs fine when running `npm run hot`, 
at first glance the app also appears to run fine running `npm run prod` - however when trying to dispatch any vuex action - `this.$store.dispatch(...)` it simply does nothing.
No errors, but the store is not updated.

a `console.dir(this.$store)` shows the store is injected, so I'm not sure what's going on.
if I disable uglify as per the below code, everything works fine.

```
mix.options({uglify: false});
```

I'm not sure where to log this issue, against mix, the webpack uglify plugin, the uglify plugin itself, or vuex, so thought I'd start at the top.

**Comment by kleisauke** [comment]
I had the same problem. It seems this problem is gone when keeping unreferenced functions and variables. Like this:

```js
mix.options({
  uglify: {
    uglifyOptions: {
      compress: {
        unused: false
      }
    }
  }
});
```

**Comment by hailwood** [comment]
Hey @JeffreyWay ,
Is this fixed, the wrong place to log it, or something else?

--
Matt
