### ISSUE TITLE
HMR not working on style changes (Styles expected to be inline under hot mode)

### ISSUE THREAD

**Issue by mm-x** [JeffreyWay/laravel-mix#1320]
- Laravel Mix Version: 1.6.1
- Node Version (`node -v`): 8.9.1
- NPM Version (`npm -v`): 5.5.1
- OS: Windows 10 (Tried also on Mac OS Sierra)

### Description: 
Styles are meant to be inline when running in HMR so that style changes are reflected without browser refresh. However the configuration in laravel mix seems to ignore disabling extracting styles when not in production.

### Steps To Reproduce: 
With a basic configuration as below. npm run hot opens the browser as expected at localhost:8080 with auto injected JS and CSS. Expected the CSS to be inline. Any change to CSS does trigger the rebuild, and HMR seems to detect a change, but nothing is applied in the browser i.e changing background color.

```
mix
	.setPublicPath('dist')
	.webpackConfig({
		plugins: [
			new HtmlWebpackPlugin({
				template: 'src/views/index.html',
			}),
		],
		devServer: {
			open: true,
		}
	})
	.js('src/js/app.js', 'js')
	.sass('src/sass/app.scss', 'css');
```

Went in node modules and changed webpack-rules.js at line 137 to the below:
```
tap(new ExtractTextPlugin({
                filename: outputPath,
                disable: process.env.NODE_ENV !== 'production'
            }), extractPlugin => {
```
which now allows HMR to pick up changes done to CSS (sass file above).

Can you please confirm if this is an actual issue/misconfiguration? I understand as per webpack documentation that this is the correct way to have HMR triggered and apply CSS changes.

Thanks,

**Comment by MarlBurroW** [comment]
Sounds like a duplicate of this issue right #1208 right ?

**Comment by mm-x** [comment]
That's correct. Closing as duplicate of #1208
