### ISSUE TITLE
Issue when installing Browser Sync with NPM

### ISSUE THREAD

**Issue by KillermenBE** [JeffreyWay/laravel-mix#1322]
- Laravel Mix Version: 1.6.1
- Node Version: 8.5.0
- NPM Version: 5.3.0 & 5.5.1
- OS: Windows 10

### Description:
Laravel Mix works good if you don't use Browser Sync which is installed using NPM (and not using the installation of Laravel Mix).

When loading a page using Browser Sync, it throws the following error:

```
C:\Users\davy.decoster\Documents\OculariumV2\node_modules\browser-sync\node_modules\ws\lib\Receiver.js:306
  if (mask != null && buf != null) bufferUtil.unmask(buf, mask);
                                             ^

TypeError: Cannot read property 'unmask' of undefined
    at Receiver.unmask (C:\Users\davy.decoster\Documents\OculariumV2\node_modules\browser-sync\node_modules\ws\lib\Receiver.js:306:46)
    at Receiver.finish (C:\Users\davy.decoster\Documents\OculariumV2\node_modules\browser-sync\node_modules\ws\lib\Receiver.js:505:25)
    at Receiver.expectHandler (C:\Users\davy.decoster\Documents\OculariumV2\node_modules\browser-sync\node_modules\ws\lib\Receiver.js:493:33)
    at Receiver.add (C:\Users\davy.decoster\Documents\OculariumV2\node_modules\browser-sync\node_modules\ws\lib\Receiver.js:103:24)
    at Socket.realHandler (C:\Users\davy.decoster\Documents\OculariumV2\node_modules\browser-sync\node_modules\ws\lib\WebSocket.js:825:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)
```

Package.json

`{
  "private": true,
  "version": "0.0.20",
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "bootstrap-sass": "^3.3.7",
    "browser-sync": "^2.18.13",
    "browser-sync-webpack-plugin": "^1.2.0",
    "cross-env": "^5.1.1",
    "css-loader": "^0.28.7",
    "jquery": "^3.1.1",
    "laravel-mix": "^1.6.1",
    "lodash": "^4.17.4",
    "postcss-loader": "^2.0.8",
    "sass-loader": "^6.0.6",
    "vue": "^2.5.3",
    "vue-loader": "^13.5.0",
    "vue-resource": "^1.3.4",
    "webpack": "^3.8.1"
  },
  "dependencies": {
    "axios": "^0.16.2",
    "bootstrap-select": "^1.12.4",
    "bugsnag-js": "^3.3.2",
    "font-awesome": "^4.7.0",
    "interactjs": "*",
    "jqtree": "^1.4.3",
    "jquery-ui-dist": "^1.12.1",
    "jstree": "^3.3.4",
    "jstree-bootstrap-theme": "^1.0.1",
    "moment": "^2.19.1",
    "tinymce": "^4.7.2",
    "tinymce-vue-2": "0.0.2",
    "vue-bugsnag": "0.0.4",
    "vue-color": "^2.4.2",
    "vue-tinymce": "^1.0.5"
  }
}
`

### Steps To Reproduce:

1. When Browser Sync is needed, Laravel Mix will add the dependencies to the package.json and will try to install it using Yarn. Then everything works fine and Browser Sync works.
2. Delete the node_modules-directory
3. Re-install it using NPM. 
4. Run npm watch with mix.browserSync in webpack.mix.js

**Comment by stephan-v** [comment]
It breaks for me as well, it tries to run a `yarn add` command when I don't even have yarn installed.

Even after I installed the `webpack-browsersync-plugin` it still needs the `browser-sync` module as well.

**Comment by KillermenBE** [comment]
Anyone?

**Comment by JeffreyWay** [comment]
Sorry for delay. I install Browsersync through npm every time with no issues. It will only use Yarn if you have a yarn.lock file in the project.
