### ISSUE TITLE
mix.js() Does not compile to ES5

### ISSUE THREAD

**Issue by sebastiansulinski** [JeffreyWay/laravel-mix#1323]
I'm using mix with Laravel `5.5.20` - as it comes out of the box.
My `webpack.mix.js` file contains:

```javascript
let mix = require('laravel-mix');

mix
    .js('resources/assets/js/front/app.js', 'public/assets/js/front')
    .sass('resources/assets/sass/front/app.scss', 'public/assets/css/front')
    .sourceMaps()
    .version();
```

and when I run any of the `run` calls, including production - I get minified version, but without being compiled to ES5 - keywords such as `const`, `let` are persisted to the compiled file.

It's never happened before so I'm wondering whether it is anything my end or is there any issue with the package?

**Comment by sebastiansulinski** [comment]
It would appear it's related to the `swiper` package I was using with my project and the fact that default webpack config excludes everything that comes from within `node_modules` or `bower_components` so for those who also run into the same issue - here's the config set up I had to add to my `webpack.mix.js` file to make it work:

```javascript

let mix = require('laravel-mix');

mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.jsx?$/,
                exclude: /(node_modules\/(?!(dom7|swiper)\/).*|bower_components)/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: Config.babel()
                    }
                ]
            }
        ]
    }
});

...
```

**Comment by chemisax** [comment]
Hello,
I'm trying to make it work with laravel mix and swiper 4.0.7.
None of the above solutions seem to work.

I was able to solve it by modifying the loader:

```
{
        test: /\.jsx?$/,
        exclude: /((node_modules\/(?!dom7|swiper))|bower_components)/,
        loader: 'babel-loader' + Mix.babelConfig()
},
```

And then adding `transform-exponentiation-operator` to `.babelrc` plugins. (It seems swiper is also using ES7).

**Comment by milkovsky** [comment]
@sebastiansulinski thank you very much for sharing the solution! I had exactly the same solution.

**Comment by stuartcusackie** [comment]
I had a similar problem but I am not using the swiper package. Using the code above still fixed it though.

I found out later that it was this package that was causing my problem:
https://github.com/sindresorhus/camelcase

I used another camel-case package and it solved my problem without the above code.
