### ISSUE TITLE
mixin does not accept a content block - sass

### ISSUE THREAD

**Issue by clarkeash** [JeffreyWay/laravel-mix#1324]
- Laravel Mix Version: 1.6.1
- Node Version: 8.7.0
- NPM Version: 5.5.1
- OS: MacOS High Sierra (10.13.1)

### Description:
When compiling sass I get the following error:

```
Module build failed:
			@include placeholder {
           ^
      Mixin "placeholder" does not accept a content block.
```

Mixin definition:
```
@mixin placeholder {
    &::-webkit-input-placeholder {@content}
    &:-moz-placeholder           {@content}
    &::-moz-placeholder          {@content}
    &:-ms-input-placeholder      {@content}  
}
```

Usage:
```
@include placeholder {
    font-style:italic;
    color: lighten($default-text-color, 20%);
}
```

I dont know a huge amount about sass (just the basics) and this code comes from a theme I have purchased. From what I have googled this code appears to be valid, so I am not sure if this is an issue with mix or not.

**Comment by clarkeash** [comment]
It seems to work in a codepen: https://codepen.io/anon/pen/pddqmM

**Comment by marko-stimac** [comment]
I get the same error for same code without using Laravel mix, I have just regular SASS code with Gulp on a Wordpress website.

* NPM 5.4.2
* Node 6.11.2
* Gulp 3.9.1
