### ISSUE TITLE
Laravel Mix + Heroku Issue (Additional Dependencies Required)

### ISSUE THREAD

**Issue by SevenEcks** [JeffreyWay/laravel-mix#1325]
- Laravel Mix Version: 1.6.0

### Description:
Laravel Mix is great, and it is even smart enough to install it's own dependencies if it finds something missing. However, if deploying to Heroku, and a dependency is missing, it installs the dependency but then requires you to rerun mix. This breaks builds on Heroku, which does the deployment automatically. The user could open a shell to the server and rerun mix, or include two npm run productions in their deployment scripts, but these are less than ideal solutions.

The message from Mix 'Additional dependencies need to be installed' and 'Please run mix again' are helpful for identifying that there is a problem, but they don't say what dependencies, making it difficult to pre-install those to ensure they are installed by npm/yarn.

This issue crops up when upgrading from an older version of Mix / Laravel.

Suggested Resolution: Display names of missing dependencies in the existing console.log

### Steps To Reproduce:
Try not including a dependency that Mix wants.

**Comment by jgill-inhouse** [comment]
For me, the issue was some dependencies were in devDependencies, but really should have been in dependencies, since npm install is running in a production environment. 

But, I agree. It should really say what's missing.
