### ISSUE TITLE
Set custom exclude string for babel

### ISSUE THREAD

**Issue by LostKobrakai** [JeffreyWay/laravel-mix#1327]
- Laravel Mix Version: 1.6.1 

### Description:
My project does have npm dependencies like this: `"phoenix": "file:../deps/phoenix"`. No matter what I set in the .babelrc as ignored folders, webpack seems to try to run babel on those dependencies, which results in the following error:

```
ERROR in ../deps/phoenix_html/priv/static/phoenix_html.js
Module build failed: ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "base" at 0, attempted to resolve relative to "../deps/phoenix_html/priv/static"
```

Excluding the folder in the `webpack-rules.js` does solve the issue, but I'd rather edit that from within the webpack.mix.js.

**Comment by laracasts** [comment]
You can do this by creating your own custom .babelrc file. It'll then be merged with Mix's at runtime.

**Comment by michaeljoyner** [comment]
Just in case this helps anyone else in the future, I had the same problem and could not solve it with a custom .babelrc file with ignored folders or files. The solution that worked for me was to set the resolve.symlinks config option to false in my project's webpack.mix.js file, as shown below.

`mix.webpackConfig({
       resolve: {
           symlinks: false
       }
   })`

**Comment by fgilio** [comment]
@michaeljoyner solution worked for me too, thanks!

**Comment by AhmedBHameed** [comment]
@michaeljoyner You saved my day

**Comment by drybp** [comment]
@michaeljoyner solution worked for me too, thanks!
