### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by ionesculiviucristian** [JeffreyWay/laravel-mix#1328]
After struggling with this problem https://github.com/JeffreyWay/laravel-mix/issues/1197, I found the solution for my configuration.

Working on a project from a local network drive (linu-to-linux, samba connection to the server), I was able to fix it by running the `npm run watch-poll` command. Now all my js files are merges and correctly watched. This is a situation that is vaguely described here https://laravel.com/docs/5.5/mix#running-mix but better at https://webpack.js.org/configuration/watch/#watchoptions-poll:

`If watching does not work for you, try out this option. Watching does not work with NFS and machines in VirtualBox.`

This should be added to the documentation for people like me that haven't yet started working with webpack but use mix just for compiling/minification etc.

**Comment by laracasts** [comment]
Since it's fresh on your mind, a PR would greatly be appreciated. :)
