### ISSUE TITLE
infinite loop on watch when require the output of generated css in app.js

### ISSUE THREAD

**Issue by Qanah** [JeffreyWay/laravel-mix#1332]
- Laravel Mix Version: (`1.6.1`)
- Node Version (`v8.8.1`): 
- NPM Version (`5.5.1`): 
- OS: macOS High Sierra 10.13.1

### Description:

I tried to require app.css file from app.js, because I have more than one language using import or require

### Steps To Reproduce:
first i install new laravel project from 
`composer create-project --prefer-dist laravel/laravel blog`

after that i run `npm install`

then edit `blog/resources/assets/js/app.js`
and add `require('../../../public/css/app.css');`
https://webpack.github.io/docs/stylesheets.html#using-css

then run `npm run watch`

the infinite loop on watch will start

how can i fix that

**Comment by ankurk91** [comment]
You should fill the `ISSUE_TEMPLATE` in order to get proper community support.

**Comment by devcircus** [comment]
Your setup will definitely cause an infinite loop. Maybe look over the mix instructions one more time.

**Comment by Qanah** [comment]
@devcircus I’m using default setup

**Comment by ankurk91** [comment]
@Qanah
Nope you don't have default installation.

Remove this line
```js
require('../../../public/css/app.css');
```
and then try to reproduce the issue.

**Comment by Qanah** [comment]
@ankurk91 & @devcircus Thanks for response but if i have case like this i need from the webpack including my assets is there any way to do something like this

**Comment by ankurk91** [comment]
@Qanah 
I am trying to understand, what is the content of `./public/css/app.css`.
Does this file include your custom css code?
Can you change this file location to something like `./public/custom/app.css`.
Why cant you relocate this file to `./resources/assets` folder.

**Comment by jjhesk** [comment]
got the same problem now since i upgrade the node to newer version 9.11

**Comment by jawabapp** [comment]
close it I am sorry this miss understanding from me

**Comment by Qanah** [comment]
close it I am sorry this miss understanding from me
