### ISSUE TITLE
Mix manifest path truncated on build, causing file not found error

### ISSUE THREAD

**Issue by lewishowles** [JeffreyWay/laravel-mix#1333]
- Laravel Mix Version: 1.6.1
- Node Version: v9.2.0
- NPM Version: 5.5.1
- OS: macOS 10.13

### Description:

With the following mix file

```
mix.setPublicPath('./')

mix.options({
   processCssUrls: false
});

mix.js('resources/assets/js/app.js', 'build/js')
   .sass('resources/assets/css/global.scss', 'assets/css/Kelrick-The-Blues.21.css', { outputStyle : 'compressed' })
   .version();
```

running `npm run watch` compiles the Sass, but then generates an incorrect mix manifest, leading to an error and crashing watch.

```
{
    "/build/js/app.js": "/build/js/app.js",
    "/ssets/css/Kelrick-The-Blues.21.css": "/ssets/css/Kelrick-The-Blues.21.css"
}
```

```
Error: ENOENT: no such file or directory, open '/Users/lewishowles/Downloads/_Gulp/ssets/css/Kelrick-The-Blues.21.css'
```

### Steps To Reproduce:

Simply running `npm run watch` on this project.

This seems to be a recent thing as it worked flawlessly yesterday. To my knowledge nothing else has changed on my machine, though I have run update on laravel-mix (don't think it was outdated anyway) and reinstalled npm during debugging this morning.

I have also tried moving projects to another folder (in case it was something weird like the underscore in the path).

If I change the path in my mix file to something like aassets, then it correctly outputs the mix manifest to /assets/, but obviously compiles the files to the wrong location.

I have also tried running production, and it outputs the same result.

**Comment by chrisbethelepb** [comment]
I am having the same issue.

**Comment by overflowsith** [comment]
Quick fix: try to change `mix.setPublicPath('./')` to `mix.setPublicPath(__dirname)`

That's because under the hood during the sass build the public path is used like a regex (Manifest.js:123)

**Comment by lewishowles** [comment]
Perfect, that does the trick.
