### ISSUE TITLE
how to use purgeCss with mix.combine ?

### ISSUE THREAD

**Issue by vesper8** [JeffreyWay/laravel-mix#1335]
Just read https://murze.be/reducing-the-size-of-a-css-file

Which led me to a new package called purgeCss which is supposed to be a big improvement on purefyCss and can shrink your css files to a tiny size in some cases as described in the article above

Package page: https://github.com/FullHuman/purgecss

this led me to this laravel mix base template: https://gist.github.com/reinink/83058f9af402aa474010844f7f2b1c54

Now the above example works on a single app.css. But in my case I would like to apply purgeCss on a bunch of different files that are being combined through mix.combine like so:

```
mix.combine([
    'resources/assets/css/bootstrap-modals-override.css',
    'resources/assets/css/my.animations.css',
    'resources/assets/css/my.containers.css',
    'resources/assets/css/my.core.css',
    'resources/assets/css/my.footer.css',
    'resources/assets/css/my.forms.css',
    'resources/assets/css/my.header.css',
    'resources/assets/css/my.menu.css',
    'resources/assets/css/my.plugins.css',
    'resources/assets/css/my.responsive.css',
], 'public/dist/css/general.css');
```

I've installed all the dependencies and am setting the plugins like in the template above. But it is having no effect on my combined css files such as general.css above

Would appreciate some help!

**Comment by vesper8** [comment]
Here's my full code

```
let mix = require('laravel-mix');
let glob = require('glob-all');
let purgeCss = require('purgecss-webpack-plugin');

mix.js('resources/assets/js/app.js', 'public/dist/js');
mix.sass('resources/assets/sass/app.scss', 'public/dist/css');

mix.combine([
    'resources/assets/css/bootstrap-modals-override.css',
    'resources/assets/css/my.animations.css',
    'resources/assets/css/my.containers.css',
    'resources/assets/css/my.core.css',
    'resources/assets/css/my.footer.css',
    'resources/assets/css/my.forms.css',
    'resources/assets/css/my.header.css',
    'resources/assets/css/my.menu.css',
    'resources/assets/css/my.plugins.css',
    'resources/assets/css/my.responsive.css',
], 'public/dist/css/general.css');

const webpackConfig = {
    output: {
        chunkFilename: 'dist/js/[name].js',
        publicPath: "/",
    },
    resolve: {
        modules: [
            'node_modules'
        ],
        alias: {
            'vue$': 'vue/dist/vue.js',
        },
    },

    // fix css files 404 issue
    devServer: {
        contentBase: path.resolve(__dirname, 'public'),
    },
};

if (mix.inProduction()) {

    mix.webpackConfig({
        plugins: [
            new purgeCss({
                paths: glob.sync([
                    path.join(__dirname, 'resources/views/**/*.blade.php'),
                    path.join(__dirname, 'resources/assets/js/**/*.vue')
                ]),
                extractors: [
                    {
                        extractor: class {
                            static extract(content) {
                                return content.match(/[A-z0-9-:\/]+/g) || []
                            }
                        },
                        extensions: ['html', 'js', 'php', 'vue']
                    }
                ]
            })
        ]
    });
}

mix.version();

mix.webpackConfig(webpackConfig);
```

`npm run production` runs without errors but does not shrink the general.css at all.. clearly I'm doing something wrong.

**Comment by MikeElghali** [comment]
Hi @JeffreyWay 

Can you consider to integrate this plugin?

Regards.

**Comment by ockam** [comment]
@vesper8 You may want to have a look at this [gist](https://gist.github.com/andrewdelprete/277a5a2af33aea2481c54a6a8b35d6c3).

It works as advertised for me, but I have another problem: the plugin is used on every css that goes through the pipeline, and I would like the use it on only some selected css files.

@JeffreyWay, if you consider adding this plugin, would be nice to have granular control over which file it process.

**Comment by andrewdelprete** [comment]
@vesper8 - It looks like Mix.combine() only aggregates a group of files into one and most likely doesn't run the output (general.css) through Webpack. You may be able to write a simple npm script that runs after Mix and calls PurgeCSS directly on general.css.

https://github.com/FullHuman/purgecss#cli

// @ockam

**Comment by vesper8** [comment]
yea I figured you can run the CLI command after the result of combine()

What  I ended up doing is just got rid of my use of combine() and made a file with a bunch of @import instead so I don't have to use .combine(). I was then able to use postCss()

**Comment by laracasts** [comment]
You can purge CSS with mix.combine(). That command is separate from your webpack build. All it does is combine/concatenate files.

**Comment by nazaporta** [comment]
Hi @vesper8
I'm trying to implement something similar and I'm interested to see how you did it. Would it be possible for you to share the code of how you removed the use of combine() and used @import instead, so you could use postCss()? It would be really helpful. Thanks in advance!
