### ISSUE TITLE
Node-sass package is out of date

### ISSUE THREAD

**Issue by hoquangthaiholy** [JeffreyWay/laravel-mix#1338]
Recently, when I try to install laravel-mix. It raises an error because of version 4.5.3 is out of date. Maybe, we need to change dependence on node-sass in package.json:

from
`"node-sass": "4.5.3"`
to
`"node-sass": "^4.5.3",`

Is it right?

**Comment by georgewritescode** [comment]
Happened to me too, gives a 404 error when trying to download the binary for

https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node

However, if we change it to the latest binary it works fine:
https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-59_binding.node

Problem with the hard coding it seems

**Comment by ruchern** [comment]
@georgewritescode Just manually do `npm install -D node-sass@latest` if you have to.
