### ISSUE TITLE
Vue (SassLoader) does not autoprefix without mix.sass()

### ISSUE THREAD

**Issue by tobiasthaden** [JeffreyWay/laravel-mix#1341]
Maybe this is not one of the most 80% use cases:

If I have no .sass or .scss files to compile because of the use of inline styles only. 
The autoprefixer does not make his job. 

**webpack.mix.js**

    let mix = require('laravel-mix');
    
    mix.js('src/main.js', 'build/js');

**a .vue file**
    
    <template>
        
    </template>
    
    <script>
        //
    </script>
    
    <style lang="scss" scoped>
        .wrap {
            display: flex;
        }
    </syle>

Otherwise, if their is a .scss file, the styles inside the .vue file are perfectly prefixed:

**webpack.mix.js**

    let mix = require('laravel-mix');
    
    mix.sass('src/file-that-i-dont-use.scss', 'build/css');
    
    mix.js('src/main.js', 'build/js');

**Comment by Shenfq** [comment]
you can use mix.options， like this：

```
mix.options({
    postCss: [
        require('autoprefixer')()
    ]
});
```

**Comment by tobiasthaden** [comment]
Thank you @Shenfq 

Here is the part were it is mentioned in the docs: [https://github.com/JeffreyWay/laravel-mix/blob/master/docs/options.md](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/options.md)
