### ISSUE TITLE
Production sourcemaps not working with uglifyjs

### ISSUE THREAD

**Issue by stephan-v** [JeffreyWay/laravel-mix#1345]
- Laravel Mix Version: 1.6.0 (`npm list --depth=0`)
- Node Version (`node -v`): 8.9.0
- NPM Version (`npm -v`): 5.0.3
- OS: Ubuntu 16.04

### Description:

Mix will not output a sourcemap for javascript files when running:

    npm run production

### Steps To Reproduce:

- Create a new laravel installation
- Update the webpack.mix.js file:

```
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');

mix.webpackConfig({
    devtool: 'source-map'
});
```
Run:

    npm run prodution

It will break, Javascript sourcemaps will not be generated. Uglify also seems to strip the sourceMappingUrl comment from the original Javascript files.

As soon as you add:

```
mix.options({
    uglify: false
});
```
Everything seems to work fine. 

It seems as the devtool option from Webpack does not play nice with the uglifyjs-webpack-plugin. Since almost nobody uses source maps in production I am guessing this does not come up often.

**Comment by ankurk91** [comment]
ref
#1344
