### ISSUE TITLE
confused about vue code splitting and chunks

### ISSUE THREAD

**Issue by vesper8** [JeffreyWay/laravel-mix#1347]
So I set my app up to work with code splitting for a few weeks now. Took some trial and error but all's running good now and I have a bunch of chunks generated every time I build.. up to 31.js now

I still also have the main app.js built.. which is now 2.6MB uncompressed

But I'm confused about how this works. My understanding of it is that by using code-splitting Webpack intelligently breaks up your app (the whole of which sums up to 2.6MB) into chunks, so that when a user visits a page that only makes use of a few vue components, he only has to download the chunks he needs.. this could be chunks 3, 5 and 9 for a total of 800kb

Do I have this part right so far?

Now the bit that confuses me is that when I view the source.. the same app.js is still being loaded. Since in my blade template I use mix('/dist/js/app.js')

So I must be doing something wrong.. because it would seem the chunks are never actually used in my current setup?

Would love some clarification.. thanks!

**Comment by ankurk91** [comment]
Close your issue if you find this link useful
https://github.com/JeffreyWay/laravel-mix/issues/1249

**Comment by vesper8** [comment]
Thank you for sharing but I already read that weeks ago and my current implementation is basically as described in the issue. I already have code splitting/chunks working.. that doesn't change that I don't think I understand how all of this is supposed to work as far as increasing performance and saving the user time or bandwidth or both.

Even though I have webpack producing all these chunks.. what good is that if the user has to load the same huge 2.6MB app.js

The part I am confused about is, after you've done all of this in webpack / vue scaffolding, how do you tell Laravel/Laravel Mix to only use certain chunks based on the needs of the current page?

**Comment by ankurk91** [comment]
You might be bundling all of your vendor js into app.js.

These links may help you.
https://www.youtube.com/watch?v=rn97hCNQsKI
https://vuejsdevelopers.com/2017/07/03/vue-js-code-splitting-webpack/

**Comment by Reached** [comment]
The question that @vesper8 raises is something I also have been thinking about.

My setup currently works with code splitting, and it's loading the chunks correctly (when I switch to another it would load chunk 0.js eg.) However the entire app.js file is still loaded once the page loads, so what is the actual point of this? :)
