### ISSUE TITLE
Enabling babel plugin within webpack.mix.js

### ISSUE THREAD

**Issue by matthayzon-sk** [JeffreyWay/laravel-mix#1349]
Hi there, in the example below I am trying to use the <a href="https://github.com/matfish2/vue-tables-2">vue-tables-2</a> templates option to return markup using JSX and the rendered output is displaying a string instead of compiled HTML, due to the babelrc jsx plugin not being enabled within the laravel-mix context. I installed the JSX compiler as mentioned <a href="https://github.com/vuejs/babel-plugin-transform-vue-jsx">here</a>, however, since I am using laravel-mix, I am not able to enable the plugin, as there is no .babelrc file. I appreciate any suggestions on how to accomplish this.

According to the JSX compiler docs, this is what the babelrc file should look like:

```
{
  "presets": ["env"],
  "plugins": ["transform-vue-jsx"]
}

```

To recap, I'm trying to enable the transform-vue-jsx plugin using laravel-mix

Vue component snippet where I am trying to return JSX:
```
templates: {
                   status(h, row, index){
                            return <span class='label label-success'>RUNNING</span>;
                        }
                    },
```

webpack.mix.js

```
let mix = require('laravel-mix');


mix.js('public/vue/main.js', './public/vue/compiled.js');

```

npm commands:
```

"test": "echo \"Error: no test specified\" && exit 1",
    "dev": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
```

**Comment by ankurk91** [comment]
Create a `.babelrc` file on your project root.
Install any Babel plugin.
Specify the Babel plugin name in .babelrc.
Done.
Babel should auto merge your config with Laravel mix.

**Comment by matthayzon-sk** [comment]
Thanks for the feedback. Note, I created the .babelrc file as described althought running `npm run  watch` doesn't seem to enable the plugin by default / not sure its auto-merging my config with laravel-mix, is there any additional setting perhaps I need to include in my webpack.mix.js file? I appreciate the help.

**Comment by laracasts** [comment]
If you have a .babelrc file, it'll be merged with Mix's 100%.
