### ISSUE TITLE
.browserSync() incorrectly picks up "--watch" option specified for mocha-webpack

### ISSUE THREAD

**Issue by spaceemotion** [JeffreyWay/laravel-mix#1353]
- Laravel Mix Version: 1.6.2
- Node Version: 8.4.0 
- NPM Version: 5.5.1
- OS: Sierra

### Description:
When using a command like `cross-env mocha-webpack --watch tests/JavaScript/**/*.spec.js` (even if the --watch option is in a dedicated `mocha-webpack.opts` file), Mix picks up the "--watch" option that is supposed to be only for mocha-webpack. This only happens when the browserSync function is used.

### Steps To Reproduce:
1. Use/Install laravel-mix and mocha-webpack as described by vue-test-utils (or the laracasts setup video)
2. Run the above mentioned command

**Comment by laracasts** [comment]
Hmm, good catch. I'll have a think on how we can check for this better.

**Comment by spaceemotion** [comment]
As a temporary fix I added `Mix.isWatching = () => false` to our setup script to disable this behavior.
