### ISSUE TITLE
mix vue files in separate files for loading only when needed?

### ISSUE THREAD

**Issue by deathkillz** [JeffreyWay/laravel-mix#1355]
### Description:
im trying to get to load only the vue/js components i need to minimize overhead (only load mix generated js files when needed)

im using a default core.js file that holds all components needed on basically every page.
then i want to load only components that are used on specific pages.

so something like

> mix.js('resources/assets/js/core.js', 'public/js')      /*core components always needed*/
>    .js('resources/assets/js/package_todo.js', 'public/js');    /*todo components*/
>    .js('resources/assets/js/package_chat.js', 'public/js');    /*chat components*/

index.php (only needs the core components)
>        <navigation-component></navigation-component>
>        <script src="{{ mix('/js/core.js') }}"></script>

chat.php (besides the core components it now also needs to load chat components)
 >       <navigation-component></navigation-component>
 >       <chat-component></chat-component>
 >       <script src="{{ mix('/js/core.js') }}"></script>
 >       <script src="{{ mix('/js/chat.js') }}"></script>

core.js
> require('./bootstrap');
> window.Vue = require('vue');
> Vue.component('navigation-component', require('./components/core/Navigation.vue'));
> new Vue({
>    el: '#app'
> })

package_chat.js (perhaps some extend() function?)
> Vue.component.extend('chat-component', require('./components/chat/Chat.vue'));

is this possible with mix somehow or if not now, will this be in the future?

or is there an other way to accomplish this or is it just inherent to how vue works that you need to include all of your components all the time, any time?

**Comment by ankurk91** [comment]
Did you search before submitting the issue
https://github.com/JeffreyWay/laravel-mix/issues/1249

**Comment by deathkillz** [comment]
yes.. but i was hoping there was some kind of simple way with laravel mix to simply load the relevant components based on where they are actually needed instead of having one large app.js file loading every single component available for every page even thought most of it is only needed on specific pages... i can hardly imagine i'd the only one trying to do something like that.

judging from what i have found so far and the link you include there is (at least not yet) any simple way of including specific components except for all the beta stuff and proposals being discussed and (for me) too complex hacks which require in depth knowledge of webpack and npm/node.

being a backend guy, i dont come from a front-end node/javascript background and have just average javascript experience althought i can usually hold my own with vanilla javascript/jquery and all, but reading all that indepth stuff makes me cringe with so many parts depending on other parts... and a lot of time those node/js packages are never backwards compatible so once you think you found a solution it turns out it just has been deprecated.

i love laravel mix because it makes these things simple and give me the opportunity to just write code without having to worry too much about diving in the whole javascript bowels of things but i guess some things still are hard. for now at least.

learning vue, webpack, npm, es6 and that node stuff for the first time, all at the same time is really confusing and when things dont work, everytime i'm like where they heck do look this time to find out what just went wrong.

it's almost like if you try to learn several things at once and it something fails your brain also expunges everything else that you did successfully manage to get to work.. not just the failed attempt. 1 step up.. 5 steps down.

anyway, i'll stick to just loading everything in a single app.js file until i gain more knowledge on this whole webpack thing or perhaps in the future it is possible with laravel mix or something.. or my knowledge increases enough for me to write some code for mix and share.

vamos a ver...
