### ISSUE TITLE
Missing source maps using Babel

### ISSUE THREAD

**Issue by fmntf** [JeffreyWay/laravel-mix#1356]
- Laravel Mix Version: 1.6.2
- Node Version (`node -v`): 7.10.1
- NPM Version (`npm -v`): 4.2.0
- OS: Ubuntu 16.04.3

### Description:
Source maps are not generated neither for JS nor CSS files using Babel.

### Steps To Reproduce:
Run `npm run dev` using the following webpack.mix.js file:

    mix.babel([
        'node_modules/mylib/dist/mylib.js'
    ], 'public/js/vendor.js');
    
    mix.babel([
        'resources/assets/js/app.js'
    ], 'public/js/app.js');
    
    mix.styles([
        'node_modules/mylib/dist/mylib.css'
    ], 'public/css/vendor.css');
    
    mix.styles([
        'resources/assets/css/app.css',
    ], 'public/css/app.css');
    
    if (mix.inProduction()) {
        mix.version();
    } else {
        mix.webpackConfig({devtool: 'inline-source-map'});
        mix.sourceMaps();
    }

The results is the same with and without `'inline-source-map'`. Am I doing something wrong?

**Comment by samtsai** [comment]
Can you try with calling the `options` API:
```
mix.options({
  sourcemaps: 'inline -source-map'
});
```
