### ISSUE TITLE
ReferenceError: Can't find variable: webpackJsonp

### ISSUE THREAD

**Issue by wirelessed** [JeffreyWay/laravel-mix#1361]
- Laravel Mix Version: 1.6.2
- Node Version: 6.5.0
- NPM Version: 3.10.3

### Description:
My webpack.mix.js is using extract(), mix.autoload() for jQuery, bootstrap, react and other things. My page is loading manifest.js followed by vendor.js correctly. We installed bugsnag on our production website and we have quite a number of users getting
````
window.onerror · ReferenceError: Can't find variable: webpackJsonp
  | webpackJsonp([2],{"+KdC":function(e,t,n){"use strict";function r(e,t){var n={};return n[e.toLowerCase()]=t.toLow
-- | --
````
or 
````
INVALID CHUNK ENCODING
Cannot read property 'call' of undefined 
at n (manifest.js)
````

The profile of the users getting this are mostly using Mobile iOS Safari v9/10/11. Any idea why is it so?

### Steps To Reproduce:
Can't trace how I reproduced. But I managed to get it once on my staging server.[](url)

**Comment by mustafawm** [comment]
It's strange that it's happening on a certain group of users!

The only time I had a similar error was due to the fact that I was running serving from a container. The issue was resolved after setting `EnableSendfile` to **off**  in  apache's `httpd.conf

**Comment by eugenedw** [comment]
This has been answered here:
https://forum.ionicframework.com/t/ionic-referenceerror-cant-find-variable-webpackjsonp/98011
  
```
<!-- The vendor js is generated during the build process
       It contains all of the dependencies in node_modules -->
  <script src="build/vendor.js"></script>
```

I'd had the same issue and adding the vendor.js line resolved the problem.

**Comment by wirelessed** [comment]
@eugenedw Thanks for your answer but I already have the vendor.js line.

@mustafawm We tried to check our `EnableSendfile`, it was already set to off.

**Comment by JeffreyWay** [comment]
Could it be a caching issue? When I've seen this error before, it's because the manifest file was cached at the browser level and needed to be cleared to reflect the new changes.
