### ISSUE TITLE
Problem with postcss

### ISSUE THREAD

**Issue by sh4d1t0** [JeffreyWay/laravel-mix#1363]
- Laravel Mix Version: 1.7.2
- Node Version: 9.2.1
- NPM Version: 5.5.1 
- OS: Mac Os with Laravel Valet

Hi, I have a trouble with postcss when I put the lines to activate it:

```
.options({
    postCss: [
        require('postcss-css-variables')()
    ]
})
```

I have the next message on console:

Error: Cannot find module 'postcss-css-variables'
error @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`

**Comment by mikaelhoodin** [comment]
I think you have to install the plugin through yarn or npm first, https://github.com/JeffreyWay/laravel-mix/blob/master/docs/css-preprocessors.md#postcss-plugins

**Comment by JeffreyWay** [comment]
Yep, it's telling you exactly what the problem is: it can't find the postcss-css-variables module, because you haven't installed.
