### ISSUE TITLE
Disable Output

### ISSUE THREAD

**Issue by sumityadav** [JeffreyWay/laravel-mix#1364]
- Laravel Mix Version: 1.7.2
- Node Version (`node -v`): 6.12.2 
- NPM Version (`npm -v`): 3.10.10
- OS: macOS Sierra

### Description:
Is there a way to disable the output (specifically after "Compiled successfully" or entirely)?
![Screenshot](https://content.screencast.com/users/sumityadav/folders/Jing/media/1b7015e3-af94-4eec-89a5-131af12bd39a/00000594.png)

### Steps To Reproduce:

1. Install Laravel (`laravel new mix`)
2. Install npm dependencies (`yarn`)
3. Run `yarn production`

**Comment by JeffreyWay** [comment]
No.
