### ISSUE TITLE
mix-manifest.json path contains backslash

### ISSUE THREAD

**Issue by bennoz** [JeffreyWay/laravel-mix#137]
OS: Windows 10
PHP: 7.1.0
laravel-mix: 0.5.2
npm: 4.0.5
Node.js: 7.4.0

I am using the following `webpack.mix.js`:
```
let mix = require('laravel-mix').mix;

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .copy('node_modules/famfamfam-flags/dist/png/', 'public/img/flags');

```

`mix-manifest.json`:
```
{
  "/js/app.js": "/js/app.f93f48fd83d448491cc9.js",
  "/css\\app.css": "/css\\app.b960f2c012c15f311cf5.css"
}
```

`app.blade.php` snippet:
```
<link rel="stylesheet" href="{{ mix('css/app.css') }}">
<script src="{{ mix('js/app.js') }}"></script>
```

Resulting in
```
Unable to locate Mix file: /css/app.css. Please check your webpack.mix.js output paths and try again. (View: D:\...\app.blade.php) (View: D:\...\app.blade.php)
```

When I replace the `\\` in the manifest with forward slashes, the `mix` helper will output the correct path.

**Comment by bvangraafeiland** [comment]
Working fine for me (Windows 7 though), no backslashes in the manifest file. Can you try doing this with a minimal install of `laravel-mix` (so no laravel framework, just a node application) and see what the manifest file contains?

**Comment by JeffreyWay** [comment]
Fixed.
