### ISSUE TITLE
Class static properties are not supported

### ISSUE THREAD

**Issue by JasonTheAdams** [JeffreyWay/laravel-mix#1370]
- Laravel Mix Version: 1.7.2
- Node Version: 8.9.0
- NPM Version: 5.6.0
- OS: MacOS High Sierra

### Description & Steps:
Trying to compile some JS which contains something like:
```js
class MyClass extends Component {
  static PropTypes = {
    ...
  }
}
```

When transpiling it throws an error for an unexpected token at the equal sign.

I was hoping this was resolved in #971, so I updated to 1.7.2, but no dice.

I admittedly don't know enough about which version of ESCMA needs to be supported in order for this to work. Does Laravel Mix somewhere document which version it supports?

It would be great to have static methods and properties supported!

**Comment by helmerdavila** [comment]
I installed it with Babel
`npm install --save-dev babel-plugin-transform-class-properties`
Then, create a `.babelrc` in the root of your project
```json
{
  "plugins": ["transform-class-properties"]
}
```

**Comment by JasonTheAdams** [comment]
Thanks, @helmerdavila! So Laravel Mix will automatically take that into account?

I'm familiar with Babel, but haven't used it, yet. Is it reliable to do things like that?

**Comment by helmerdavila** [comment]
Maybe in the future this will be included by default

**Comment by devcircus** [comment]
Class properties are an experimental feature of js in the draft phase. At some point in the future, it may become a js feature. Until then you'll need to pull in the plugin.
