### ISSUE TITLE
Config.publicPath cannot contain dot characters

### ISSUE THREAD

**Issue by unclecheese** [JeffreyWay/laravel-mix#1373]
- Laravel Mix Version: 1.7.2
- Node Version 8.9.2
- NPM Version 5.5.1
- OS: macOS 10.13

### Description:

If `Config.publicPath` contains a dot character, e.g. `setPublicPath('./')`, this ends up getting parsed as unescaped regex in `Manifest.noramlizePath()`, which ends up truncating the first character of the path.

### Steps To Reproduce:

_webpack.mix.js_
```
mix.setPublicPath('./')
  .scss('path/to/main.scss', 'path/to/dist.css');
```

Resulting `manifest.json`:
```
{
  '/ath/to/dist.css': '/ath/to/dist/css'
}
```

Granted, setting `./` as a public path is probably redundant in most cases (I removed it and it works fine), but it seems to me the `mix` API should be robust enough that it doesn't lead to bizarre results like this that leave devs digging through internals to figure out what configuration error they made.

**Comment by gummi-io** [comment]
I have the same issue, having dot in the public path works before 1.4.2 tho. Not sure which version does it stop working

**Comment by JeffreyWay** [comment]
Fixed.
