### ISSUE TITLE
Feature request: Add static server

### ISSUE THREAD

**Issue by nurbek-ab** [JeffreyWay/laravel-mix#1375]
- Laravel Mix Version: 1.7.2
- Node Version: 8.6.0
- NPM Version: 5.3.0
- OS: Windows 7 x64

### Description:
Please add an optional static server in case a project is just a collection of html files or if a server already exists provide information on how to launch it from laravel-mix.

**Comment by kylekatarnls** [comment]
Hi, put your HTML files in the public directory then run laravel-mix should act like a static server. Could it be good for you this way?

**Comment by JeffreyWay** [comment]
I don't think should be a responsibility of Mix's.
