### ISSUE TITLE
Usage of const

### ISSUE THREAD

**Issue by kylekatarnls** [JeffreyWay/laravel-mix#1377]
Hi,

I noticed this project nearly use only `let` statements when most of variables does not change, so best-practice would be to use `const`. Is there a reason for this. If so, the few `const` statements should probably be replaced for consistency.

**Comment by JeffreyWay** [comment]
I don't like const. You're free to submit a PR to convert any of them to `let` if you wish.

**Comment by kylekatarnls** [comment]
Sounds to me like unfair discrimination.

`const` have real benefits, such as saying to other developers: "this reference is immutable". And so it also highlight the real `let` statements. In many codes, you would have more `const`s than `let`s and so you can clearly identify a variable that can change its value. And when you see a `const` declaration, you know this declaration will remain true.

With the right IDE, you will get on const many reliable autocompletion as a predictable value when the same with let can give wrong information as multiple values possible.

Before changing all const to let, I hope you would consider using each statement for its purpose.

An article among others:
http://wesbos.com/let-vs-const/

**Comment by JeffreyWay** [comment]
`const` is not immutable. 

In reality, it provides little benefit. Instead, it makes for ugly code, when you have a bunch of `const` and `let` references littered together. It looks ugly.

**Comment by kylekatarnls** [comment]
`const` is an immutable binding in Node (not yet implemented in all browsers, but laravel-mix run on node, so your example in a browser is not relevant) and push is a method of Array, it does not change the binding, only the data inside (I'm not speeking of immutable properties, there is `Object.freeze` for that). Each tool has its role. When you have `const` and `let`, its help you to distinguish both, it's a more strict approach, the ugly adjective seems a bit subjective to me.

For example, when you `require()` an object, you can always use `const`, and it makes a lot of sense to say `const myLib = require('myLib')` because it would be a bad idea to use this same variable name to store something else later.

In multiple experiences, using `const`/`let` over the old `var` brought clarity and disambiguation. It's probably something to try to understand the benefit.

The simple rule (would match the prefer-const of eslint: https://eslint.org/docs/rules/prefer-const) would be: if you want to reassign a value, you explicitly say it with `let`, anything else should be `const`. In this way, when a dev will try to change a const value, he will get an error from his IDE or from Node at runtime and so it forces him to ask himself a very good question before eventually change it to `let`: "Is it a good idea to reuse the same variable and change its value?"

I hope it can help to take an enlightened decision about this code-style point.

**Comment by JeffreyWay** [comment]
I can think of a hundred more pressing issues than this. You started by saying it’s immutable, and then later clarified that only the binding is. This is a point of confusion for just about every person who encounters const. 

It honestly doesn’t even register on the list of concerns or needs I have for the Mix codebase.

**Comment by kylekatarnls** [comment]
That's because laravel-mix is a great and important project we love that we wish it at the top of best-practices it's nothing like a reproach. And it's not because we do not immediately understand all about a new syntax in a language that we should avoid to use it. I would not give you unneeded work, I will do the pull-request (all let or all const where it's relevant) whatever you finally prefer. But I wanted to be sure I well understand the constraints and not run into some go-quickly choice.
