### ISSUE TITLE
Laravel webpack build not clean, generated js files under public

### ISSUE THREAD

**Issue by serak** [JeffreyWay/laravel-mix#1380]
- Laravel Mix Version: #.#.# (`npm list --depth=0`) = 1.7.2
- Node Version (`node -v`):  v8.9.1
- NPM Version (`npm -v`):  v5.5.1
- OS:  Windows 10x64

### Description:

lavaravel webpack compiles vue components with require(./component.vue) to public/0.js,1.js .... instead of public/js/0.js ,1.js ...

### Steps To Reproduce:
create two components , 1 main and on loaded dynamically using Vue.component('mycomp',()=>import('component1.vue'));
without laravel and vuejs 2.5 , vue-cli 2.9.2 npm run build builds the dist structure correctly like

dist|
.......static/
................/css
.............../js
.................../0.js
............../font

but in laravel this structure gets messed up

thanks

**Comment by ankurk91** [comment]
Search before reporting
https://github.com/JeffreyWay/laravel-mix/issues/1309
