### ISSUE TITLE
Question: Is it possible to dump the final webpack config?

### ISSUE THREAD

**Issue by jameshulse** [JeffreyWay/laravel-mix#1382]
When using laravel-mix with 3rd party plugins, if I run in to an issue is there a way to extract the webpack config to show them?

**Comment by kohenkatz** [comment]
Mix dispatches a `configReady` event with the `webpackConfig` object.

You should be able to listen for it using something like this:

```
Mix.listen('configReady', function(webpackConfig) {
    // Add code here to output the webpack config or dump it to a file.
})
```

**Comment by jameshulse** [comment]
This is awesome! Thanks @kohenkatz, I never would have found that.

**Comment by mblarsen** [comment]
You can also use:

```
mix.dump()
```

**Comment by MohamedLamineAllal** [comment]
listen is no more exposed! There is `after()` or `then()`. Is it possible to extract the config from them ?
