### ISSUE TITLE
Backslashes on Windows (again)

### ISSUE THREAD

**Issue by kohenkatz** [JeffreyWay/laravel-mix#1383]
- Laravel Mix Version: 1.7.2
- Node Version (`node -v`): 8.9.1
- NPM Version (`npm -v`): 5.5.1
- OS: Windows 10 x64

### Description:

Trying to use `html-webpack-plugin` as well as trying to use Webpack lazy loading both have an issue on Windows because the paths to the JS and CSS files have backslashes in them instead of forward slashes. While Chrome transparently corrects them to forward slashes, other browsers (Firefox, for example), do not. (The reason it is an issue for lazy loading is that the `manifest.js` file contains the backslashed paths too.)

The fix for this is simple and was already done once in #323 (for JS files only), but I wanted to find out if there was a reason that it was removed (or whether it was just accidental) before I submit a new PR to put it back.

The fix for JS files is just adding `.replace(/\\/g, '/')` at the end of the line [here](https://github.com/JeffreyWay/laravel-mix/blob/9672822ba9de96ea89c2a7c0b50f189bee426fc2/src/builder/Entry.js#L67), [here](https://github.com/JeffreyWay/laravel-mix/blob/9672822ba9de96ea89c2a7c0b50f189bee426fc2/src/builder/Entry.js#L90), and [here](https://github.com/JeffreyWay/laravel-mix/blob/9672822ba9de96ea89c2a7c0b50f189bee426fc2/src/builder/webpack-entry.js#L30).

The fix for CSS files is adding the same thing at the end of the line [here](https://github.com/JeffreyWay/laravel-mix/blob/9672822ba9de96ea89c2a7c0b50f189bee426fc2/src/builder/webpack-rules.js#L135).

### Steps To Reproduce:

(Note: This is a non-Laravel project example, but in a Laravel project the same issue occurs.)

Folder structure:

```
- src
\- html
  \- index.html
\- js
  \- main.js
  \- ... // doesn't matter
\- styles
  \- app.scss
```

`webpack.mix.js`

```
const { mix } = require('laravel-mix');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const InlineChunkWebpackPlugin = require('html-webpack-inline-chunk-plugin');
const path = require('path');

mix
	.setPublicPath('build')
	.webpackConfig({
		plugins: [
			new HtmlWebpackPlugin({
				inject: true,
				template: 'src/html/index.html',
			}),
			new InlineChunkWebpackPlugin({
				// Adding `path.normalize` here should not be necessary,
				// but it is because of this backslash issue.
				inlineChunks: [path.normalize('/js/manifest')]
			})
		],
	})
	.js('src/js/main.js', 'js')
	.extract([
		'axios',
		'bootstrap-sass',
		'jquery',
		'vue',
		'vue-router',
		'vuex',
	], 'js/vendor')
	.sass('src/styles/app.scss', 'css')
	.version();
```

The actual contents of the JS and CSS files don't actually matter.

**Comment by kohenkatz** [comment]
Anyone?

**Comment by tpraxl** [comment]
@kohenkatz BTW: I'm currently working on a new PR for automated tests that include linux, osx (Travis) and windows (AppVeyor). I applied the suggested fixes, but this alone seems not to be sufficient. See https://ci.appveyor.com/project/tpraxl/laravel-mix/build/1.0.5

**Comment by kohenkatz** [comment]
@tpraxl I never said that it was complete, I only said it fixed the specific issue I have.  
I can certainly do more to make the tests pass, but I wonder if there might be some places where it *does* make sense to use the OS path separator. The important thing to check is whether a call will be used in the browser, in which case it must be `/`, or whether it will be used by Node to load from the filesystem, in which case the OS path is better.

Thoughts?

**Comment by kohenkatz** [comment]
@tpraxl I have one change to `src/Manifest.js` and a whole bunch of test changes.

## `src/Manifest.js`

```
     hash(file) {
         let hash = new File(path.join(Config.publicPath, file)).version();

+        let filePath = this.normalizePath(file);
+
+        this.manifest[filePath] = filePath + '?id=' + hash;
-        this.manifest[file] = file + '?id=' + hash;

         return this;
     }
```

## `test/Api.js`

```
 test('mix.setPublicPath()', t => {
     let response = mix.setPublicPath('somewhere/else');

     t.is(mix, response);

-    t.is('somewhere/else', Config.publicPath);
+    t.is(path.normalize('somewhere/else'), Config.publicPath);

     // It will also trim any closing slashes.
     mix.setPublicPath('somewhere/else/');

-    t.is('somewhere/else', Config.publicPath);
+    t.is(path.normalize('somewhere/else'), Config.publicPath);
 });
```

## `test/file.js`

```
 test('it knows the relative path to the file', t => {
     let file = new File('path/to/file.js');

     let newFile = new File('../path/to/file.js');

-    t.true(['path/to/file.js', 'path\\to\\file.js'].includes(file.relativePath()));
+    t.is(path.normalize('path/to/file.js'), file.relativePath());

-    t.true(['../path/to/file.js', '..\\path\\to\\file.js'].includes(newFile.relativePath()));
+    t.is(path.normalize('../path/to/file.js'), newFile.relativePath());
 });


 test('it can force the file to begin from the public path for the project.', t => {
     Config.publicPath = 'public';

     let file = new File('some/path/here.js');

     let newFile = file.forceFromPublic();

     t.true(newFile instanceof File);

-    t.is('public/some/path/here.js', newFile.relativePath());
+    t.is(path.normalize('public/some/path/here.js'), newFile.relativePath());
 });


 test('it knows the path to the file starting from the project public directory', t => {
     let file = new File('public/js/file.js');

-    t.is('/js/file.js', file.pathFromPublic(Config.publicPath));
+    t.is(path.normalize('/js/file.js'), file.pathFromPublic(Config.publicPath));

     file = new File('js/file.js');

-    t.is('/js/file.js', file.pathFromPublic(Config.publicPath));
+    t.is(path.normalize('/js/file.js'), file.pathFromPublic(Config.publicPath));
 });
```

## `test/PurifyPaths.js`

```
 test('that it builds the purify file paths properly', t => {
     let options = PurifyPaths.build({
         paths: ['foo.html']
     });

     t.deepEqual(options, { paths: ['foo.html'] });

     let stubs = [
-        path.resolve(__dirname, 'stubs/one.html'),
-        path.resolve(__dirname, 'stubs/two.html')
+        path.resolve(__dirname, 'stubs/one.html').replace(/\\/g, '/'),
+        path.resolve(__dirname, 'stubs/two.html').replace(/\\/g, '/')
     ];

     new File(stubs[0]).makeDirectories().write('foo');
     new File(stubs[1]).makeDirectories().write('bar');

     // If the user gives a regular expressions, we need to glob it.
     options = PurifyPaths.build({
         paths: [__dirname + '/stubs/*.html']
     });

     // So let's make sure that updates the paths array properly...
     t.deepEqual(options, { paths: stubs });

     // Clean up.
     fs.remove(__dirname + '/stubs');
 });
```

**Comment by kohenkatz** [comment]
## `test/WebpackConfig.js`

```
 test('Autoprefixer should always be applied after all other postcss plugins', t => {
     mix.sass('resources/assets/sass/sass.scss', 'public/css')
        .options({
            postCss: [
               require('postcss-custom-properties')
            ]
        });

+    let filePath = path.normalize('/resources/assets/sass/sass.scss');
+
     let plugins = new WebpackConfig()
         .build()
-        .module.rules.find(rule => rule.test.toString().includes('/resources/assets/sass/sass.scss'))
+        .module.rules.find(rule => rule.test.toString().includes(filePath))
         .use.find(loader => loader.loader == 'postcss-loader')
         .options.plugins.map(plugin => plugin().postcssPlugin);

     t.deepEqual(['postcss-custom-properties', 'autoprefixer'], plugins);
 });
```

**Comment by tpraxl** [comment]
Thanks for your suggestions. I applied them, which reduced the amount of fails. :+1: 

However, not all failing tests are fixed and I would suggest to keep this discussion clean. You are very welcome to contribute to my fork by posting pull requests to https://github.com/tpraxl/laravel-mix/tree/feature/automated-testing-for-pull-requests 

I also enabled issues, should we need to discuss things further. 

When all issues are resolved, I'll post the PR to JeffreyWay/laravel-mix and hope that it will be merged :)

**Comment by parth279927** [comment]
1. Use Double Backslashes in Strings
In PHP strings, a single backslash is used as an escape character. To use a literal backslash, you need to escape it by using double backslashes (\\).

Example:

`$path = "C:\\path\\to\\directory";`
2. Use Forward Slashes
PHP can handle forward slashes (/) in file paths on Windows. Using forward slashes can help avoid the issue of escaping backslashes.

Example:

**$path = "C:/path/to/directory";**
