### ISSUE TITLE
copy directory, copy only changed files

### ISSUE THREAD

**Issue by MordiSacks** [JeffreyWay/laravel-mix#1386]
### Description:
I use `mix.copyDirectory`  to copy my images (that are not referenced in css files) to public path
It would by nice if it will copy only changed files, prior to laravel-mix, I used gulp with [gulp-changed](https://www.npmjs.com/package/gulp-changed) to achieve this functionality.

Another thing about `mix.copyDirectory` I'm not sure if it passes the images to optipng, etc.
if not, would be nice if did, maybe a new function like `mix.images`
that will implement minimization and "copy only if changed"

another not related feature request i have is an option to set root path of css assets
right now, it will copy images to public/images and replace css pathes
 `./path-to-my-images/image.png`
to
`/images/image.png`

If you use virtual hosts or valet that's fine
but I like to use wamp (windows)
and my root is usually something like this
`localhost/PhpstormProjects/foo/public`
so if the path to the asset is set to `/images/image.png`
it is trying to load `localhost/images/image.png` , when it should be `localhost/PhpstormProjects/foo/public/images/image.png` 
so if their was a way to add a prefix to the assets path I could do this 
`mix.setAssetsPrefix('PhpstormProjects/foo/public')` or maybe
`mix.setAssetsPrefix('//localhost/PhpstormProjects/foo/public')`

that would we awesome

edit:
It turns out this exists
`mix.setResourceRoot('');`

Thank's and happy new year ☺

**Comment by MordiSacks** [comment]
I discovered `mix.setResourceRoot('');`
so that solves my second issue

**Comment by JeffreyWay** [comment]
Since `mix.copy()` is a specialty call that is separate from the main webpack build, my instinct is to keep it as basic as possible. If there's an easy way to quickly check if the file has been updated, we can do that. But otherwise, let's keep it as it is.
