### ISSUE TITLE
Can anybody suggest a good translation plugin ? Currently I am using vue-multilanguage

### ISSUE THREAD

**Issue by soumyabmr** [JeffreyWay/laravel-mix#1389]
- Laravel Mix Version: laravel-mix@1.7.2
- Node Version v8.9.1 
- NPM Version 5.6.0
- OS:  Linux

### Description:
Please help me to find a good translation plugin for vue . The one am using is  vue-multilanguage but the problem is I couldn't translate the alerts ,warnings , toaster messages swal etc .

**Comment by ankurk91** [comment]
https://curated.vuejs.org/module/github_com::kazupon::vue-i18n
