### ISSUE TITLE
SASS Rounding Error

### ISSUE THREAD

**Issue by helloiamlukas** [JeffreyWay/laravel-mix#139]
Due to a rounding error the scss/sass file won't get compiled properly (e.g. Bootstrap 3).

Is it possible to set the sass precision value manually? 

Otherwise it would be nice to set a higher precision by default e.g.
`sass-loader?sourceMap&precision=8`

**Comment by QWp6t** [comment]
just edit your webpack.config.js file: https://github.com/JeffreyWay/laravel-mix/blob/master/setup/webpack.config.js#L138

**Comment by JeffreyWay** [comment]
@helloiamlukas I'm not too familiar with Sass rounding errors. Is this something we can add to the sass-loader and be done with it? Are there any side effects that I need to worry about?

**Comment by helloiamlukas** [comment]
@QWp6t Yeah I already know, that's the workaround. But as Laravel ships with Bootstrap out of the box, I think this should work without touching the Webpack configuration. 

@JeffreyWay As far as I can see there aren't any negative side effects. I have been using a higher precision for years, haven't had any problems until now. It is even recommended in the official [Bootstrap docs](https://github.com/twbs/bootstrap-sass#sass-number-precision).

**Comment by JeffreyWay** [comment]
Okay, I'll merge your PR. Thanks!
