### ISSUE TITLE
IE (11/Edge) can't handle <components>

### ISSUE THREAD

**Issue by Jaspur** [JeffreyWay/laravel-mix#1390]
- Laravel Mix Version: #.#.# (`npm list --depth=0`)
- Node Version (`node -v`): v8.9.1
- NPM Version (`npm -v`): 5.6.0
- OS: MacOS

### Description:
Components aren't displayed in IE11 en IE Edge (probably also not in IE10). But they aren't displayed. I already added these two:
```
require('es6-promise').polyfill();
require("babel-polyfill");
```
But not the solution to a working component. 

### Steps To Reproduce:
Make a component and open IE edge or IE 11

**Comment by JeffreyWay** [comment]
I can't reproduce this. If you can provide exact steps with an illustration of what fails, we can take another look.
