### ISSUE TITLE
i want add React CSS Modules

### ISSUE THREAD

**Issue by msadeghifard1989** [JeffreyWay/laravel-mix#1391]
hi
 i want add React CSS Modules 
https://github.com/gajus/react-css-modules
please help me
add css-loader style-loader webpack

**Comment by moeen-basra** [comment]
@msadeghifard1989 try following webpack config and check if it works for you
`mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.css$/,
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: 'css-loader?modules,localIdentName="[name]-[local]-[hash:base64:6]"'
                }),
            }
        ]
    },
    resolve: {
        extensions: ['.scss'],
    },
});`

**Comment by besrabasant** [comment]
I am not able to make it work... And hasn't anybody yet tried _this_. I mean `css-modules`
