### ISSUE TITLE
I can't Enable mix.options on specific  files

### ISSUE THREAD

**Issue by DiaaEddin** [JeffreyWay/laravel-mix#1393]
I want postCss to process the first sass   file "uikit-rtl.sass". but it's processing all sass files.
```
mix.sass('resources/assets/sass/uikit-rtl.scss', 'public/css/uikit-rtl.css')
    .options({
        postCss: [
            css => {
                css.insertBefore(css.nodes[0], postcss.comment({text: 'rtl:begin:rename'}));
                css.insertAfter(css.nodes[css.nodes.length - 1], postcss.comment({text: 'rtl:end:rename'}));
            },
            rtlcss({
                stringMap: [{
                    name: 'previous-next',
                    priority: 100,
                    search: ['previous', 'Previous', 'PREVIOUS'],
                    replace: ['next', 'Next', 'NEXT'],
                    options: {
                        scope: '*',
                        ignoreCase: false
                    }
                }]
            })
        ]
    });
mix.sass('resources/assets/sass/uikit-ltr.scss', 'public/css/uikit.css'); 
```

**Comment by Nathanw** [comment]
From what I can tell from reading the docs is that you can pass the options as the third argument to the `sass()` method call, this will then only apply the options to the specified files. This can be seen on this page of the docs: https://github.com/JeffreyWay/laravel-mix/blob/master/docs/css-preprocessors.md.

**Comment by DiaaEddin** [comment]
that is right. but these options are for node-sass plugin where I want to pass postCss plugin options.[https://github.com/sass/node-sass#options](https://github.com/sass/node-sass#options)

**Comment by JeffreyWay** [comment]
At the moment, your postcss plugins will be applied to all calls to mix.sass(). There's no way to selectively exclude certain files.
