### ISSUE TITLE
Vue.js CSS extraction

### ISSUE THREAD

**Issue by mrcsmcln** [JeffreyWay/laravel-mix#14]
Any plans for [extracting CSS](https://vue-loader.vuejs.org/en/configurations/extract-css.html)? If not, should this just go in `webpack.config.js` as per usual?

**Comment by PascaleBeier** [comment]
Isn't this vue-loader territory? I'd be happy using vue-loader as usual in `webpack.config.js`.

**Comment by mrcsmcln** [comment]
It probably is, but given that Mix has out of the box support for Vue.js, I was wondering if this was planned.

**Comment by JeffreyWay** [comment]
I haven't yet decided on what to do about Vue component CSS extraction. We already extract your Sass/Less. 

You can of course manually update the webpack.config.js file. Something like:

```js
{
    test: /\.vue$/,
    loader: 'vue-loader',
    options: {
        loaders: {
            css: plugins.ExtractTextPlugin.extract({
                loader: 'css-loader',
                fallbackLoader: 'vue-style-loader'
            })
          }
    }
}
```
