### ISSUE TITLE
Files loaded via worker-loader are not re-written in dist folder

### ISSUE THREAD

**Issue by dotnetCarpenter** [JeffreyWay/laravel-mix#1400]
- Laravel Mix Version: 1.7.2 (`npm list --depth=0`)
- Node Version (`node -v`): 8.9.3
- NPM Version (`npm -v`): 5.6.0
- worker-loader@1.1.0
- OS: OS X El Capitan 10.11.6 (15G18013)

### Description:
Files loaded via worker-loader are not updated in dist folder.
E.i. If I have `Loader.worker.js` and update the file, webpack will create a new file ala `[hash].worker.js`.

### Steps To Reproduce:
1. Install worker-loader: `npm i --save-dev worker-loader`
2. In `webpack.mix.js` add the following code snippet:
```js
mix.webpackConfig({
    module: {
      rules: [
        {
          test: /\.worker\.js$/,
          use: { loader: 'worker-loader' }
        }
      ]
    }
})
```
3. Create a file that we will import as a web worker: `src/demo.worker.js`
4. Create a file that will import the web worker: `src/consumer.js`
5. In `src/consumer.js` add the following snippet:
```js
import Worker from './demo.worker.js'
const worker = new Worker()
```
6. Run `npm run watch` or similar (get laravel-mix to build your files)
7. Observe that you get a file in the `dist/`folder called something like: `f4384db8eaa14bba0948.worker.js`
8. You can change the file name or add some code to `src/demo.worker.js` - for instance you could add:
```js
self.addEventListener('message', event => {
  console.log(event.data)
  self.postMessage({ hello: 'world' })
})
```
9. A new file ala `b3f9bf0ecd0dddebfb10.worker.js` will appear in the `dist/` folder.

Over time your `dist/` folder will be flooded with web worker files. It will never be cleaned up and you have to do `rm -r dist && npm run dev` to get a proper `dist/` folder.

**Comment by JeffreyWay** [comment]
I'm not familiar with that loader, but I assume this is because Mix has no way of knowing that it should delete the file. You can add a callback to `mix.then()`, and manually clear out any files in your dist folder that match a regex for that file name format.

**Comment by dotnetCarpenter** [comment]
Gotcha. But I fail to find any documentation for `mix.then`. I can see it in the [tests](https://github.com/JeffreyWay/laravel-mix/blob/3f8843aa2cf6b55d0b14f35fe9db589e73b4f230/test/Api.js#L275) but not in the docs or on https://laravel.com/docs/master/mix.

Ref worker-loader: https://github.com/webpack-contrib/worker-loader

**Comment by ethanclevenger91** [comment]
If you came here looking for a one-liner, use the `del` package I suppose. Before the mix commands in your `webpack.mix.js` file, add:

`del(['public/*.worker.js'])`

Though I suppose I didn't test if this works while using `npm run watch`...
