### ISSUE TITLE
mix.inProduction is not a function

### ISSUE THREAD

**Issue by mmjjb** [JeffreyWay/laravel-mix#1403]
- Laravel Mix Version: 0.8.9
- Node Version: 9.3.0 
- NPM Version: 5.5.1
- OS: Ubuntu 16

### Description:
inProduction() is not recognized after migration, maybe wrong version?

### Steps To Reproduce:
if (mix.inProduction()) {
    mix.version();
}

### Result
TypeError: mix.inProduction is not a function

**Comment by JeffreyWay** [comment]
Upgrade your install of Laravel Mix. It's incredibly out-dated.

**Comment by mmjjb** [comment]
Fixed

**Comment by valdezalbertm** [comment]
I got this error and it's 2020. LOL.
