### ISSUE TITLE
mix.version() breaks test

### ISSUE THREAD

**Issue by bambamboole** [JeffreyWay/laravel-mix#1404]
- Node Version: 8.9.2 
- NPM Version: 5.5.1
- OS: macOS 10.13.2

Dependencies
```
├── axios@0.17.1
├── cross-env@5.1.3
├── expect@22.0.5
├── jsdom@11.5.1
├── jsdom-global@3.0.2
├── laravel-mix@1.7.2
├── lodash@4.17.4
├── mocha@4.1.0
├── mocha-webpack@1.0.1
├── vue@2.5.13
└── vue-test-utils@1.0.0-beta.9
```

### Description:
I followed the laracasts session for writing vue tests with laravel mix.

I ended up with the following command:
```
cross-env NODE_ENV=development node_modules/mocha-webpack/bin/mocha-webpack --webpack-config=node_modules/laravel-mix/setup/webpack.config.js --require tests/Javascript/setup.js tests/Javascript/**/*.spec.js"
```

When I have the following lines in my `webpack.mix.js` :
```
if (mix.inProduction() || process.env.npm_lifecycle_event !== 'hot') {
    mix.version();
}
```
Then mocha-webpack fails with the following error:
```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/bambamboole/Sites/laravel-5-boilerplate/public/bundle.js'
```

When I remove the three lines the tests work properly.

**Comment by maimake** [comment]
I have another problem while using `mix.version()` in HMR mode. As long as I change any js file, `npm run hot` will crash. 

```

fs.js:642
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/mai/Develop/learn/web/laravel/tmp/public/0.573e035ec1e2130e4bb6.hot-update.js'

```

I found the reason is that mix-manifest.json will add a hot-update item while changing files. 

```json
{
    "/js/app.js": "/js/app.js",
    "/css/app.css": "/css/app.css",
    "/0.573e035ec1e2130e4bb6.hot-update.js": "/0.573e035ec1e2130e4bb6.hot-update.js"
}
```
so that, when hashing the manifest again, it throws an exception "no such file or directory"

I think it'd better check the filename first before adding a item to the manifest.

```js
    hash(file) {

        let filePath = path.join(Config.publicPath, file);
        if (filePath.indexOf('hot-update'))
            return this;

        let hash = new File(filePath).version();

        this.manifest[file] = file + '?id=' + hash;

        return this;
    }
```

**Comment by kylemilloy** [comment]
Similar issue also exists when using `mix.extract()`

Temporary solution for me is to make multiple webpack files based on my env and then change my package's scripts to set these using cross-env. This way you can just set what you need per environment (production does a whole slew of image compression, extraction and versioning for example) whereas development forgoes versioning and image compression and testing just compiles everything. 

Anyways...I have my primary webpack.mix.js that just contains a single line:
`require('./webpack.mix.${process.env.NODE_ENV}.js}')`

Be sure to use backticks for string concatenation.

**Comment by MGMonge** [comment]
As a temporal fix you can add a conditional on your `webpack.mix.js`  file to solve the issue on your tests
```javascript
let mix = require('laravel-mix')

mix
    .js('resources/assets/js/main.js', 'public/js')
    .less('resources/assets/less/app.less', 'public/css')

if (process.env.NODE_ENV === 'testing') {
    mix.disableNotifications();
} else {
    mix.copy('node_modules/font-awesome/fonts', 'public/fonts', false)
        .version()
}
```
but each time you run the tests the `mix-manifest.json` will change for
```json
{
    "/bundle.js": "/bundle.js"
}
```
and this will break your laravel app 😞 so you need to compile the assets again to fix it.

To set the environment for you npm script you have to install the `cross-env` package

```batch
npm install cross-env --save-dev
```

and run your tests like this 
```batch
cross-env NODE_ENV=testing mocha-webpack --webpack-config=node_modules/laravel-mix/setup/webpack.config.js --require=tests/js/setup.js 'tests/js/**/*.spec.js
```

**Comment by nckg** [comment]
I added temporary fix for the `mix-manifest.json ` rewrite. You can see it in this comment: https://github.com/JeffreyWay/laravel-mix/issues/1576#issuecomment-395332379
