### ISSUE TITLE
Preventing some files or directory from being minified

### ISSUE THREAD

**Issue by radd2004** [JeffreyWay/laravel-mix#1409]
- Laravel Mix Version: 1.7.2
- Node Version (`node -v`): v9.3.0
- NPM Version (`npm -v`): 5.6.0
- OS: Mac (High Sierra) / Darwin

### Description:
Here is the sitch (I have these copy commands):
`
mix
    .copy('node_modules/slick-carousel/slick/*.js', 'assets/js/vendor/slick-carousel/')
    .copy('node_modules/bootstrap/dist/js/*.js', 'assets/js/vendor/bootstrap/')
    .copy('node_modules/jquery/dist/*.js', 'assets/js/vendor/jquery/')
    .copy('node_modules/popper.js/dist/umd/*.js', 'assets/js/vendor/popperjs/')
    .copy('node_modules/vue/dist/*.js', 'assets/js/vendor/vue/')
    .copy('node_modules/vue/dist/vue.min.js', 'assets/js/vendor/vue/')
    .copyDirectory('node_modules/vue-router/dist', 'assets/js/vendor/vue-router/')
    .copy('node_modules/vuex/dist/*.js', 'assets/js/vendor/vuex/')
    .copy('node_modules/stickyfilljs/dist/*', 'assets/js/vendor/stickyfilljs/')
`

when building for production, mix tries to minify "everything touched by webpack," including apparently these file that I simply want to copy from one place to another and nothing else. 

How can I simply copy these files without mix trying to minify them? Do I just have to use something else for my copying needs?

### Steps To Reproduce:

zip of files (couldn't get github to nicely format code blocks
[webpack_mix_js_and_package_json.zip](https://github.com/JeffreyWay/laravel-mix/files/1628067/webpack_mix_js_and_package_json.zip)

package.json:  

`
{
  "name": "just-wanna-copy",
  "version": "1.0.0",
  "description": " ",
  "main": "index.js",
  "scripts": {
    "cypress:open": "node_modules/.bin/cypress open",
    "cypress:run": "node_modules/.bin/cypress run",
    "test": "npm run cypress:run",
    "dev": "NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-local": "NODE_ENV=local node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "NODE_ENV=development webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "browser-sync": "^2.18.13",
    "browser-sync-webpack-plugin": "^1.2.0",
    "cypress": "^1.0.3",
    "laravel-mix": "^1.7.2"
  },
  "dependencies": {
    "bootstrap": "^4.0.0-beta.2",
    "jquery": "^3.2.1",
    "popper.js": "^1.12.6",
    "select2": "^4.0.6-rc.0",
    "simplemde": "^1.11.2",
    "slick-carousel": "^1.8.1",
    "stickyfilljs": "^2.0.3",
    "vue": "^2.5.3",
    "vue-router": "^3.0.1",
    "vue": "^3.0.1"
  }
}
`

webpack.mix.js . 

`
let mix = require('laravel-mix');

mix
    .disableNotifications()
    .options({
        processCssUrls: false,
        uglify: {
            uglifyOptions: {
                parallel: true,
                ecma: 8,
                mangle: {
                    reserved: ['$super', '$', 'exports', 'require', 'jQuery', 'jquery']
                }
            }
        }
    })
    .setPublicPath('assets');

mix
    .copy('node_modules/slick-carousel/slick/*.js', 'assets/js/vendor/slick-carousel/')
    .copy('node_modules/bootstrap/dist/js/*.js', 'assets/js/vendor/bootstrap/')
    .copy('node_modules/jquery/dist/*.js', 'assets/js/vendor/jquery/')
    .copy('node_modules/popper.js/dist/umd/*.js', 'assets/js/vendor/popperjs/')
    .copy('node_modules/vue/dist/*.js', 'assets/js/vendor/vue/')
    .copy('node_modules/vue/dist/vue.min.js', 'assets/js/vendor/vue/')
    .copyDirectory('node_modules/vue-router/dist', 'assets/js/vendor/vue-router/')
    .copy('node_modules/vuex/dist/*.js', 'assets/js/vendor/vuex/')
    .copy('node_modules/stickyfilljs/dist/*', 'assets/js/vendor/stickyfilljs/')

    .copy('node_modules/bootstrap/dist/css/*.css', 'assets/css/vendor/bootstrap/')
    .copy('node_modules/slick-carousel/slick/*.css', 'assets/css/vendor/slick-carousel/')
    .copy('node_modules/select2/dist/css/*.css', 'assets/css/vendor/select2/');
`
`npm install`
`npm run production`

**Comment by ankurk91** [comment]
`copy()` method does not minify files.

**Comment by textoo** [comment]
@ankurk91 got the same issue, copy() tries to minify files even if it's not it's purpose .

**Comment by ankurk91** [comment]
Laravel mix has changed a lot since my comment above.

I am no longer using Mix, our whole organisation is using our own webpack solution which fulfills all of our needs.

https://github.com/ankurk91/laravel-bundler
