### ISSUE TITLE
using eslint-loader or pre/post loaders.

### ISSUE THREAD

**Issue by vk92kokil** [JeffreyWay/laravel-mix#141]
How to use eslint-loader in webpack.mix.js file
I have added extra webpackConfig in the file. but this doesn't work.
```javascript
.webpackConfig({
            plugins: [
                new webpack.LoaderOptionsPlugin({
                    options: {
                        eslint: {
                            configFile: path.join(__dirname, '.eslintrc'),
                        },
                    },
                })
            ],
            module: {
                rules: [{
                    test: /\.js$/,
                    exclude: /node_modules/,
                    inlclude: [path.join(__dirname, './client')],
                    enforce: 'pre',
                    use: [{
                        loader: 'eslint-loader'
                    }],
                }, ],
            },
  })
```

**Comment by JeffreyWay** [comment]
I see a typo, "inlclude", but not sure if that's related. 

Are you requiring webpack into your webpack.mix.js file? If you need to configure your Webpack config file significantly like this, it's best to copy our webpack.config.js file to your project root, and then work off of that directly.

**Comment by cerw** [comment]
@JeffreyWay atm you can not just copy the config file as its just loader for WebPack builder and it has lines like: 

```
require('../src/index');
let WebpackConfig = require('../src/builder/WebpackConfig');
```

Which will fail once this file is moved to project root directory. 

How to add custom webpack plugins officaly ?

**Comment by niltoncsr** [comment]
Some problem here. I investigated and found out that the generated configuration object has in `test` key the value of `{}` when passing a regular expression on our "webpack.mix.js". Maybe that's the only issue that's causing that, I'll try look more deeply later.

Got the generated code by placing `require('fs').writeFile('generated_webpack.js', JSON.stringify(new WebpackConfig().build(), null, 2), 'utf-8')` on "node_modules/laravel-mix/setup/webpack.config.js"
