### ISSUE TITLE
#RGBA colors in Less-files are mangled in production builds.

### ISSUE THREAD

**Issue by Svish** [JeffreyWay/laravel-mix#1412]
**laravel-mix:** v1.7.2
**node:** v8.9.3
**less-loader:** v4.0.5
**less:** v2.7.3
**os:** Microsoft Windows [Version 10.0.16299.125]

Given this type of `webpack.mix.js` configuration:

```js
const mix = require('laravel-mix');
const lessParams = {
	strictMath: true,
	compress: false,
};
mix.less('resources/assets/less/app.less', 'public/css', lessParams);
```

The following input:

```less
background: #0001;
border-color: transparent transparent #0005 transparent;
border-color: #0005 transparent transparent transparent;

```
Gives the following output:

**with `compress=false`:**
```css
background:#0001;
border-color:transparent transparent #0005;
border-color:#0005 transparent transparent;
```

**with `compress=true`:**
```css
background:background:#0001 1;
border-color:transparent transparent #0005 5;
border-color:#0005 5 transparent transparent;
```

The default for `npm run prod` seems to be `compress=true`, so I experienced having my CSS work fine while developing, but not when built for production. Pretty understandable the browser didn't understand when `#RGBA` values are converted to `#RGBA A`...

When I reported this issue to the [less.js](https://github.com/less/less.js/issues/3153) project, I was told the compress option was actually [deprecated](http://lesscss.org/usage/#command-line-usage-compress) in [2015](https://github.com/less/less.js/blob/v2.7.3/CHANGELOG.md#220)...

**Comment by JeffreyWay** [comment]
Yeah, don't set `compress=true` as a Less option. Mix will compress your CSS without touching that option.

**Comment by Svish** [comment]
I didn't set it, it's true by default. I.e. to avoid the issue I had to explicitly set `compress=false`.
