### ISSUE TITLE
[Question] CSS url() rewriting with resources flattering & versioning

### ISSUE THREAD

**Issue by IlCallo** [JeffreyWay/laravel-mix#1413]
- Laravel Mix Version: 1.7.2
- Node Version: 6.12.3 
- NPM Version: 3.10.10
- OS: Ubuntu 16.04

### Description:
It's documented that when using `processCssUrls: true` (the default), all resources are flattened when copied and then the url is rewritten. Is it Laravel Mix who does this? Or is it the `css-loader`?
The problem here is that I want them to be copied with the structure defined by the original url.

I could do it with copyDirectory (which I do), but at the same time there seems to be no way to apply versioning to images referenced via url() into a CSS file when `processCssUrls` is disabled.

Am I missing something here? Where should I check to change this behaviour or to obtain versioning without flattening?

**Comment by ankurk91** [comment]
It is being handled by `file-loader` I believe.
