### ISSUE TITLE
Get mix.sass up and running with postCss-critical css

### ISSUE THREAD

**Issue by Teun87** [JeffreyWay/laravel-mix#1415]
Hi,

I've tried to set up Sass with an extra PostCSS plugin, but unfortunately it doesn't work. Below is my webpack.mix.js:

```
let mix = require('laravel-mix');
mix
    .js('templates/src/js/app.js', 'web/assets/dist/')
    .sass('templates/src/scss/app.scss', 'web/assets/dist/')
    .sourceMaps()
    .options({
        postCss: [
            require('postcss-critical-css')({
                preserve: false,
                outputPath: 'web/assets/dist/'
            })
        ]
    })
    .browserSync({
        proxy: '127.0.0.1:8080',
        files: [
        'templates/**/*.twig',
        'templates/js/**/*',
        'templates/css/**/*.css'
    ]
})

mix.setPublicPath('./web');
```

Everything seems to work fine, but when I run 'npm run watch' I get the following warning: 

> 'WARNING in ./node_modules/css-loader?{"url":true,"sourceMap":true,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null,null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/XX/Sites/XX/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./templates/src/scss/app.scss
> (Emitted value instead of an instance of Error)   resolve-url-loader cannot operate: CSS error
>   /Users/XX/Sites/XX/templates/src/scss/app.scss:7:3: missing '}'
>   at error (/Users/XX/Sites/XX/node_modules/css/lib/parse/index.js:62:15)
>  @ ./templates/src/scss/app.scss 4:14-266
>  @ multi ./templates/src/js/app.js ./templates/src/scss/app.scss'
> 

Also when I look at the file that is being generated (critical.css) by the PostCSS-plugin only extra lines get added and old lines are not deleted. So, the file only gets bigger and bigger :)

The file does not appear in the mix-manifest.json.

Could someone help me?

Thanks Teun

**Comment by JeffreyWay** [comment]
Hmm, I just tried pulling in that critical plugin and using your config. Everything seems to be working. 

Looks like your issue is here:

```
CSS error
/Users/XX/Sites/XX/templates/src/scss/app.scss:7:3: missing '}'
```
