### ISSUE TITLE
NPM scripts on Windows require "SET NODE_ENV"

### ISSUE THREAD

**Issue by bchellingworth** [JeffreyWay/laravel-mix#1416]
- Laravel Mix Version: #.#.# (`npm list --depth=0`)
- Node Version (v6.9.1`): 
- NPM Version (5.6.0): 
- OS: Windows 10

### Description:
The scripts that are listed that you add to the package.json file do not work on windows. You need to add `"SET" before NODE_ENV`

Perhaps this could be added to the wiki?
`  "scripts": {
    "dev": "SET NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "SET NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "SET NODE_ENV=development webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "SET NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  }`
 

### Steps To Reproduce:

Install on windows :P

**Comment by JeffreyWay** [comment]
Yep, feel free to PR the docs with a Windows example for the suggested scripts. :)
