### ISSUE TITLE
Watch poll High CPU

### ISSUE THREAD

**Issue by ottz0** [JeffreyWay/laravel-mix#1418]
Im using Laravel and laravel-mix using Vagrant and all of a sudden npm run watch does not work. So I started using watch poll, however it keeps crashing my VM as it is maxing out my CPU

**Comment by JeffreyWay** [comment]
Polling will definitely push your CPU more. Try setting a longer poll interval. Within your `package.json` file, update your `watch-poll` script to use a five second interval, like this:

```js
    "watch-poll": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll=5000 --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
```

**Comment by bhulsman** [comment]
@JeffreyWay What is the default poll interval?

For the project I'm working on currently the CPU load is 90% or over using watch-poll. Not sure why the CPU load is suddenly so high, been using watch-poll for other projects without hogging the CPU.

Anyway, with an interval of 200ms, CPU usage go's down to ~50%, which is acceptable.

**Comment by ayyobro** [comment]
+1 I am having this very same issue

**Comment by paulm17** [comment]
I got tired of my MBPr 2012 having it's fans on all the time.  I set the polling to 5000 and this fixed the issue for me.  Using the latest laravel for what it's worth.
