### ISSUE TITLE
CSS loader [path] is incorrect when attempting to load babel-plugin-react-css-modules

### ISSUE THREAD

**Issue by andrewfschorr** [JeffreyWay/laravel-mix#1421]
## CSS loader [path] is incorrect 

- Laravel Mix Version: laravel-mix@1.7.2
- Node Version: v7.7.4
- Yarn version: 1.3.2
- OS: Mac OS, 10.12.6 

### Description:

Seems that when my css loader is attempting to load css modules via babel-plugin-react-css-modules, the `[path]` variable is resolving incorrectly, with many more underscores/dashes to: `.-_-_-_-_-resources-assets-js-components-- `

This is compared to my .babelrc which looks like 
```
{
    "plugins": [
      ["react-css-modules", {
      }]
    ]
  }
```

(for which the default is `[path]___[name]__[local]___[hash:base64:5]`) and complies to `resources-assets-js-components-___index__a___3boKA` see screen shot below.

### Steps To Reproduce:

Install a fresh laravel 5.5, with react and the following package.json
```
{
  "private": true,
  "scripts": {
    "dev": "yarn run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.17",
    "babel-eslint": "^8.2.1",
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "babel-preset-react": "^6.23.0",
    "bootstrap": "^4.0.0-beta.3",
    "cross-env": "^5.1",
    "eslint": "^4.15.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-prettier": "^2.5.0",
    "eslint-plugin-react": "^7.5.1",
    "jquery": "^3.2",
    "laravel-mix": "^1.0",
    "lodash": "^4.17.4",
    "popper.js": "^1.12.9",
    "prettier": "1.10.2",
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  },
  "dependencies": {
    "babel-plugin-react-css-modules": "^3.3.2"
  }
}
```
 
Change your `webpack.rules.js` to incorporate the CSS loader (to isolate path variable):
```
    // CSS Compilation.
    rules.push({
        test: /\.css$/,
        exclude: Config.preprocessors.postCss ? Config.preprocessors.postCss.map(postCss => postCss.src.path()) : [],
        loaders: ['style-loader', 'css-loader?modules,localIdentName="[path]"']
    });
```

Add a react component with a DOM element that looks something like the following:

`<div styleName='a'>hello</div>`

and see the variance between the DOM node class name and the associated style class in the injected style tag.

![image](https://user-images.githubusercontent.com/538485/35136495-f23fa9b4-fcb1-11e7-8827-cb9050bf0e68.png)

**Comment by hadar111** [comment]
The same happened to me, @andrewfschorr have you solve this issue till now ?

**Comment by andrewfschorr** [comment]
@hadar111 while mix is amazing for 90% of the use cases, as stated, it was too limiting for me wrt CSS modules so I replaced it with a custom webpack configuration 😄

**Comment by hadar111** [comment]
@andrewfschorr Cool,
I'm also solved the issue by moving into custom config. 

Thanks
