### ISSUE TITLE
Wrong css order on production

### ISSUE THREAD

**Issue by aerni90** [JeffreyWay/laravel-mix#1422]
- Laravel Mix Version: 1.7.2
- Node Version (`node -v`): 
- NPM Version (`npm -v`): 
- OS: maxOS Sierra 10.12.6

### Description:
When using "npm run prod", the css output is different to "npm run dev" and "npm run watch". It puts the css classes in a wrong order. This might be related to [CSS Output Order Differs between Production and Dev #815](https://github.com/vuejs-templates/webpack/issues/815), [get wrong css order after using HashedModuleIdsPlugin #5733](https://github.com/webpack/webpack/issues/5733), [get wrong css order after using HashedModuleIdsPlugin #642](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/642)

### Steps To Reproduce:
It's hard to reproduce this, as I don't know myself when and why this happens. For now I just stumbled upon one style in my css that gets left out and overwritten by this issue. I can provide you with all my source files if needed.

**Comment by JeffreyWay** [comment]
I think it's related to the extract plugin. We're at their mercy until it's fixed. Nothing on the Mix end we can do, I don't think.
