### ISSUE TITLE
[Proposal] Use multiple extract

### ISSUE THREAD

**Issue by RomainLanz** [JeffreyWay/laravel-mix#143]
Hey !

With the arrival of HTTP2 it will be better to provide small chunk of assets instead of 1 or 2 big files.

It would be great if `extract()` can be called multiple times to create different bundle of assets. This can also be useful to lazy-load dependencies.

The api will looks like the code bellow.

```javascript
mix.js('resources/assets/js/app.js', 'public/js')
  .extract(['vue', 'jquery'], 'bundle')
  .extract(['lodash'], 'anotherBundle')
  .sass('resources/assets/sass/app.scss', 'public/css')
```

**Comment by RomainLanz** [comment]
Thanks ! <3

**Comment by familysoltani** [comment]
Now extract doesn't work at all!

**Comment by mijgame** [comment]
When using autoload, how do I specify in which `extract` the autoloaded package will be included?
Given the following configuration:
```javascript
mix.sass('resources/assets/sass/app.scss', 'public/css')
	.js('resources/assets/js/app.js', 'public/js')
	.autoload({
		jquery: ['$', 'window.jQuery', 'jQuery']
	})
	.extract(['lodash', 'jquery', 'vue', 'axios', 'sweetalert2', 'pikaday'], 'js/vendor')
	.extract(['trumbowyg'], 'js/editor')
	.copy('node_modules/trumbowyg/dist/ui/icons.svg', 'public/img/icons.svg')
	.version();
```

What happens, is that jQuery gets included in the `editor` package, which is not what I want. Is my configuration wrong or is this a problem with Mix?

**Comment by 96andl** [comment]
It would not work with versioning because manifest.js file creates only for the last vendor.js bundle and works only with last bundle.
**If someone have solution for this, please notify me..**

**Comment by andreportaro** [comment]
> It would not work with versioning because manifest.js file creates only for the last vendor.js bundle and works only with last bundle.
> **If someone have solution for this, please notify me..**

@Spartaques Splitting each build into it's own `webpack.mix` file seems like a possible solution, though not ideal

http://www.compulsivecoders.com/tech/how-to-build-multiple-vendors-using-laravel-mix/
