### ISSUE TITLE
[Question] vue components generated a javascript file

### ISSUE THREAD

**Issue by yuuk** [JeffreyWay/laravel-mix#1438]
- Laravel Mix Version: 1.0
- Node Version (`node -v`): v6.11.2
- NPM Version (`npm -v`): 3.10.10
- OS: windows 7

### Description:
vue components generated a javascript file, how can i change the folder

![qq 20180126151637](https://user-images.githubusercontent.com/9426456/35430303-aa6754b4-02b2-11e8-9ab8-975aadc710bf.png)

**Comment by ankurk91** [comment]
These are called chunks.
Please search inside the closed issues you should find the related issues
