### ISSUE TITLE
Unable to import Bootstrap 4.0.0 components into my Vue project

### ISSUE THREAD

**Issue by plexus77** [JeffreyWay/laravel-mix#1441]
- Laravel Mix Version: 2.0.0
- Node Version v9.4.0: 
- NPM Version 5.6.0: 
- OS: Osx High Sierra 10.13.2 (17C2205)

### Description:
I am trying to compile a Laravel / Vue project after updating the dependencies, previously everything was working fine but now I am receiving a compilation error.

> ERROR in ./node_modules/bootstrap/js/src/dropdown.js
> Module parse failed: Unexpected token (217:8)
> You may need an appropriate loader to handle this file type.
> |&nbsp;&nbsp;_getConfig(config) {
> |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;config = {
> |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...this.constructor.Default,
> |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...$(this._element).data(),
> |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...config

I have already tried installing the babel object rest spread plugin and that hasn't helped.  It was installed for the previous version but tried it without and then added it back in again with no change.

Not sure why this has started happening, please help.

### Steps To Reproduce:
I have this in a bootstrap.js file

`require('bootstrap/js/src/collapse')`

When I run

`npm run watch`

I get the error.

**Comment by plexus77** [comment]
I ended up using bootstrap-vue instead and everything builds again now.  Still not sure why the issue was happening though.

**Comment by ankurk91** [comment]
Don't import from bootstrap `src` folder.
Always import from `dist` folder

**Comment by plexus77** [comment]
That causes other issues actually, i can’t see any reason why I shouldn’t be able to build from the arc directory or why it would throw an error because of the object spread operator.

**Comment by ankurk91** [comment]
Babel loader has been disabled for files coming from `node_modules`.

`src` folder has es6 files while `dist` has es6 files.

**Comment by ankurk91** [comment]
You should follow the official bootstrap guide
https://getbootstrap.com/docs/4.0/getting-started/webpack/

**Comment by plexus77** [comment]
You'r right @ankurk91 thanks for taking the time... I should have looked through the bootstrap docs again.  That said, I did in fact try importing collapse from the dist directory and while the compilation was successful I started receiving javascript errors in the browser related to the collapse plugin.

Anyway I guess that is an issue seperate to Laravel Mix.

Thanks again :)
