### ISSUE TITLE
Uncaught TypeError: $(...).modal is not a function

### ISSUE THREAD

**Issue by Crupuk** [JeffreyWay/laravel-mix#1444]
- Laravel Mix Version: #.#.# (`npm list --depth=0`)

```
npm list --depth=0
+-- @ladjs/bootstrap-social@7.0.2 (github:niftylettuce/bootstrap-social#f7d456c7982cdd865a8ac75025a5e68b4c71c925)
+-- axios@0.17.1
+-- bootstrap@4.0.0
+-- cross-env@5.1.3
+-- font-awesome@4.7.0
+-- jquery@3.3.1
+-- laravel-mix@1.7.2
+-- lodash@4.17.4
+-- popper.js@1.13.0
`-- vue@2.5.13
```

- Node Version (`node -v`): 

```
node -v
v8.9.4
```

- NPM Version (`npm -v`): 

```
npm -v
5.6.0
```

- OS:  Windows with HomeStead ( npm / node running on the host )

### Steps To Reproduce:

With a fresh laravel install i'm trying to display a bootstrap modal but i get this error : 

```
(index):181 Uncaught TypeError: $(...).modal is not a function
    at (index):181
```

```
    $('#exampleModalCenter').modal({
        show: true
    });
```

I'm new to webpack / laravel-mix / ... And i don't know how to get more information.
In app.js I found this : 

![image](https://user-images.githubusercontent.com/670728/35553531-8bca2b56-0598-11e8-9904-bc899989a7cf.png)

But still doesn't work.

```
php artisan --version
Laravel Framework 5.5.28
```

Thanks for your help.

**Comment by ankurk91** [comment]
Check for mix autoload() method documentation

**Comment by Crupuk** [comment]
Hi @ankurk91 ,

Thanks for the reply.
I have read the doc but i can't figure to make it work.

This is my files : 

resources/assets/js/app.js

`require('./bootstrap');`

webpack.mix.js

```
let mix = require('laravel-mix');

mix.autoload({
    jquery: ['$', 'global.jQuery',"jQuery","global.$","jquery","global.jquery"]
});

mix.js(['resources/assets/js/app.js',
    'node_modules/bootstrap/dist/js/bootstrap.js'],'public/js').sourceMaps()
    .sass('resources/assets/sass/app.scss', 'public/css');
```

And resources/js/bootstrap.js : 

```
try {
    window.$ = window.jQuery = require('jquery/dist/jquery.slim');

    require('bootstrap');

} catch (e) {
}


require('bootstrap/js/dist/util');
require('bootstrap/js/dist/modal');
```


With this configuration and after running `npm run dev` I get this error in the browser console : 

![image](https://user-images.githubusercontent.com/670728/35616822-ae1a9c7a-0676-11e8-9040-85a71181c7ae.png)

And the code : 

```
$(document).ready(function() {
    $(document).on('show.bs.modal', function (event) {
        var day = $(event.relatedTarget) // Button that triggered the modal
        var recipient = day.data('date') // Extract info from data-* attributes
        // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
        // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
        var modal = $(this)
        modal.find('.modal-title').text('New message to ' + recipient)
    })
})
```

Never trigger.

**Comment by ankurk91** [comment]
You are doing it wrong.

You have required full bootstrap js file then you are including selective files then you have extracted full bootstrap js as well.
You have messed up, please go and read the documentation 
OR
watch **webpack for everyone** series on laracast.

**Comment by imonoid** [comment]
@Crupuk have you solved this issue?  also experiencing this one.  the modal will open when using data parameters in the button, but the show.bs.modal is never triggered.  when i try to manually call the modal, i also get the error you are experiencing.

**Comment by Crupuk** [comment]
@imonoid  not yet, and for now i'm trying to learn webpack on laracast.
Already try to make a project from scratch and still not working.

If you find something , please tell me :-p

**Comment by cshawaus** [comment]
Hi @Crupuk,

Bootstrap 4 no longer uses module definitions for the core JavaScript, instead, you now need to explicitly expose each static module by using the below.

```
const webpack = require('webpack')

mix.webpackConfig({
  plugins: [
    new webpack.ProvidePlugin({
      $               : 'jquery',
      jQuery          : 'jquery',
      'window.jQuery' : 'jquery',
      Popper          : ['popper.js', 'default'],
      Alert           : 'exports-loader?Alert!bootstrap/js/dist/alert',
      Button          : 'exports-loader?Button!bootstrap/js/dist/button',
      Carousel        : 'exports-loader?Carousel!bootstrap/js/dist/carousel',
      Collapse        : 'exports-loader?Collapse!bootstrap/js/dist/collapse',
      Dropdown        : 'exports-loader?Dropdown!bootstrap/js/dist/dropdown',
      Modal           : 'exports-loader?Modal!bootstrap/js/dist/modal',
      Popover         : 'exports-loader?Popover!bootstrap/js/dist/popover',
      Scrollspy       : 'exports-loader?Scrollspy!bootstrap/js/dist/scrollspy',
      Tab             : 'exports-loader?Tab!bootstrap/js/dist/tab',
      Tooltip         : "exports-loader?Tooltip!bootstrap/js/dist/tooltip",
      Util            : 'exports-loader?Util!bootstrap/js/dist/util',
    }),
  ],
})
```

This could be adapted to `mix.autoload` but I haven't had a chance to test it fully.

**Comment by Crupuk** [comment]
I will try . Thx @cshawaus

**Comment by freehandman** [comment]
I have a similar problem, mind, however, is with the $(' ...').carousel() function in my code.
I think @cshawaus has a point. I will try that.

**Comment by duvg** [comment]
hi, i have similar problem and put code in webpack.min.js, type in terminal npm run watch but the error persists @cshawaus

**Comment by lucasstephen122** [comment]
Thanks , guys

**Comment by DevinKWu** [comment]
`jquery/dist/jquery.slim`change to `jquery/dist/jquery` will work

**Comment by cronywalls** [comment]
The $(…)[.modal is not a function](http://net-informations.com/jq/iq/modal.htm) is usually caused because scripts are loaded in the wrong order . The browser will execute the scripts in the order it finds them. If in a script you attempt to access an element that hasn't been reached yet then you will get an error. Make sure that you don't have a script above one that it requires.

**Comment by jordanraji** [comment]
In your JS file add this:

`require('bootstrap/js/dist/modal');`

**Comment by SoroushOracle** [comment]
Thanks @cshawaus  
My problem solved:)

**Comment by sandipsonagra** [comment]
> @cshawaus it display an error
> 
> ```
> ReferenceError: webpack is not defined
>     at Object.
> ```
> 
> even when I changed it to
> 
> ```
> mix.webpackConfig(webpack => {
>     return {
>         plugins: [
>             new webpack.ProvidePlugin({
>                 $: 'jquery',
>                 jQuery: 'jquery',
>                 'window.jQuery': 'jquery',
>                 Popper          : ['popper.js', 'default'],
>                 Alert           : 'exports-loader?Alert!bootstrap/js/dist/alert',
>                 Button          : 'exports-loader?Button!bootstrap/js/dist/button',
>                 Carousel        : 'exports-loader?Carousel!bootstrap/js/dist/carousel',
>                 Collapse        : 'exports-loader?Collapse!bootstrap/js/dist/collapse',
>                 Dropdown        : 'exports-loader?Dropdown!bootstrap/js/dist/dropdown',
>                 Modal           : 'exports-loader?Modal!bootstrap/js/dist/modal',
>                 Popover         : 'exports-loader?Popover!bootstrap/js/dist/popover',
>                 Scrollspy       : 'exports-loader?Scrollspy!bootstrap/js/dist/scrollspy',
>                 Tab             : 'exports-loader?Tab!bootstrap/js/dist/tab',
>                 Tooltip         : "exports-loader?Tooltip!bootstrap/js/dist/tooltip",
>                 Util            : 'exports-loader?Util!bootstrap/js/dist/util',
>             })
>         ]
>     };
> });
> ```
> 
> it still not working, I use bootstrap 4 and I can't load any component until now :(

const mix = require('laravel-mix');
const webpack = require('webpack'); // Import webpack

mix.webpackConfig(webpack => {
    return {
        plugins: [
            new webpack.ProvidePlugin({
                // Your ProvidePlugin configuration
            })
        ]
    };
});
use this to solve
