### ISSUE TITLE
None-vue js and other js with sass

### ISSUE THREAD

**Issue by jordanramstad** [JeffreyWay/laravel-mix#1449]
- Laravel Mix Version: 1.7.2
- Node Version (`node -v`):  9.2.0
- NPM Version (`npm -v`):  5.5.1
- OS: Windows 10

### Description:
First of all, although at face value this is a bug, its just some weird functionality that might not have a real solution at the laravel mix level, just a kind of gotcha.

If you for instance want to webpack (using `mix.js()` a service worker and your app (basically just so you can use es6 in it) along with using inline scss in your vue components. You need to make sure the order of your mix functions in the chain have the main `app.js` first, then your service worker `sw.js` then your `app.scss`

Like so:
```
mix
    .js('src/app.js', 'dist/js')
    .js('src/sw.js', 'dist/sw.js')
    .sass('src/assets/sass/app.scss', 'dist/css')
```

If you do not, your rendered css file will only contain styles contained in your single file components, not your scss files. Weird issue and caught me for awhile.

### Steps To Reproduce:

Make sure to have an app that utilizes scss in the components (I use css modules as well though, but does not feel that it will matter)
`<style lang="scss" module>`

Order your assets like so:
```
mix
    .js('src/sw.js', 'dist/sw.js')
    .js('src/app.js', 'dist/js')
    .sass('src/assets/sass/app.scss', 'dist/css')
```
Paths should be able to be anything, service worker is just a simple example,  but should be true for anything as long as it does not require/import any vue components in it.

Options that are needed to ensure everything works (regardless of js order):
```
.options({
    processCssUrls: false,
    extractVueStyles: true,
    globalVueStyles: 'src/assets/sass/_variables.scss'
})
```
Although to test probably no need for a global variables file.

You should see the rendered css file not contain any styles from the scss files. Only the Components. Swapping the order of the js functions in mix will fix it though.

I think this has more to do with how webpack passes the files through the loaders then anything else it does not feel like anything can be done about it, but I could be wrong.

**Comment by SirAuron** [comment]
Something similar has happened to me, although a little bit differently.

First let me be more clear about my settings:
- in mix file there are a few `.scss` files which are compiled into their own `.css` counterparts;
- I use Vue SFC written in TypeScript;
- I had to add the following rule to allow sass-loader to compile material-components-web (which uses a 
    a name spaced package)
    ```
    test: /(@material|vue-mdc-adapter|sass\/logged).*\.scss$/,
    loader: 'sass-loader',
    options: {
    includePaths: [
        path.resolve(__dirname,'node_modules'),
    ],
    ```
- I set Mix options like the following:
    ```
    mix.options({
        extractVueStyles: "vue_extracted_styles.css",
        imgLoaderOptions: {
            enabled: false, // This will disable minifying of images
        },
    });
    ```
- I tryed using both Laravel Mix Version: 1.7.2 and the new 2.0.0. version.

It does not matter how I order the compile instructions: the extraction of Vue SFC styles will always take the first `.sass` file name it ecounters along the compile declaration and completely overwrite its content.
So, say that my first `.scss` file is `landing.scss`, which will became `/public/css/guest/landing.css` , all Vue extracted styles will be put in this `landing.css` file and all its previous content will be erased.

Currently, the only available workaround I found is to create a `vue_extracted_styles.scss` containing a single harmless rule and making it the first `.scss` file to be parsed. In this way, all extracted declarations will be put in the correct file.

In all honesty, I started to understand how Webpack works just in these two previous weeks, so I have no clue on whatever is causing this kind of bug.
