### ISSUE TITLE
[Help] How to use a custom loader in laravel mix?

### ISSUE THREAD

**Issue by ludo237** [JeffreyWay/laravel-mix#145]
Hello everyone.

I'm trying to use the stylus loader in laravel mix, but at the moment this configuration will not work 

```
mix.webpackConfig({
    module: {
        loaders: [{
            test: /\.styl$/,
            loader: 'css-loader!stylus-loader'
        }]
    }
});
```

The problem is that I don't know how to use is inside the chain of functions because of course `mix.stylus` is not recognized.

What is the best approach when you need to use a custom loader like this one in laravel-mix?

**Comment by JeffreyWay** [comment]
If you need special plugins and configuration, copy Laravel Mix's webpack.config.js file to your project root, and then follow the stylus-loader instructions for adding it to your config file.

**Comment by garethellis36** [comment]
If you're finding this thread through Google Search in 2020 or later, you no longer need to copy webpack.config.js as suggested by Jeffrey above.

While I found that using mix.webpackConfig() would not work for adding loaders, [mix.extend()](https://laravel-mix.com/docs/5.0/extending-mix) can be used for this purpose:


Define an extension as follows:
```
mix.extend("addWebpackLoaders", (webpackConfig, loaderRules) => {
    loaderRules.forEach((loaderRule) => {
        webpackConfig.module.rules.push(loaderRule);
    });
});
```

Then call it like this:
```
mix.addWebpackLoaders([
    {
        test: /jQuery[\/\\]chosen\.jquery\.js$/,
        use: "imports-loader?this=>window"
    },
    {
        test: /jQuery[\/\\]alertify\.js$/,
        use: "imports-loader?define=>false,this=>window"
    }
]);
```

**Comment by johnRivs** [comment]
@garethellis36 Do you happen to know how to make a Markdown file go through the loader?
