### ISSUE TITLE
HMR not working after upgrade from 1.7.2 to 2.0.0

### ISSUE THREAD

**Issue by nkostadinov** [JeffreyWay/laravel-mix#1454]
- Laravel Mix Version: 2.0.0
- Node Version (`node -v`): v6.9.1
- NPM Version (`npm -v`): 5.6.0
- OS: Windows 10 Pro 64bit

### Description:
I recently upgraded from 1.7.2 to 2.0.0 and HMR stopped working. The mix file is the same and when I run 'npm run hot' it compiles succesfully. 
When I open the site the resources seemed to load correctly but there was no HMR message and it was not working.
I noticed that the server was serving the files from the /dist folder. I deleted them and now I get 404 Cannot GET /dist/... on every file. So the issues is that the dev server is serving only the local files but I cannot find out why and how to fix it. 
I tried to delete node_modules and reinstall npm but the issue is still there.

### Steps To Reproduce:
upgrade from 1.7.2 to 2.0.0
npm run hot (no HMR)

**Comment by sifex** [comment]
This is definately a Windows issue I think. I'm rolling out Mix next week, going to look into this one.

**Comment by nkostadinov** [comment]
I think it's the same as #1437

**Comment by Ben-Mack** [comment]
I'm also facing the same issue, js file pointed to `localhost:8080` correctly, files changed got compiled, but the changes does not reflect on page. 
Downgrade `laravel-mix` from `2.0.0` to `1.7.2` and HMR working good again 

I'm using `node 8.9.4`, `npm  5.6.0`, `Laravel 5.5`, `latest Win 10 64bit`

**Comment by Manfred047** [comment]
Same problem with Laravel 5.6 Windows 10 64bit

**Comment by frdteknikelektro** [comment]
Please post your webpack.mix.js

**Comment by nkostadinov** [comment]
This is my mix file:

```
mix
  .setPublicPath('./')
  .js('frontend/main.js', 'dist/')
  .sourceMaps()
  .options({
    postCss: [
      require('autoprefixer')(),
    ]
  })
  .webpackConfig({
    resolve: {
      alias: {
        '@': path.resolve('frontend'),
        'css': path.resolve('frontend/assets/scss'),
      }
    },
    output: {
      chunkFilename: mix.inProduction() ? './dist/chunks/[name].[chunkhash].js' : './dist/chunks/[name].js',
    }
  })
```

**Comment by misenhower** [comment]
Cross-posting here, I found a potential fix for this: https://github.com/JeffreyWay/laravel-mix/issues/1437#issuecomment-365484126

**Comment by isometriq** [comment]
Experiencing similar problem...
The `mix-manifest.json` gets updated correctly and "hot" files are served correctly.
But I don't see a connection nor any request ..end result: page is not updated with hot-update.

**Comment by itsmill3rtime** [comment]
people keep posting "fixes" which are more like bandaids. would be nice if a dev would actually fix the underlying issue. till then i'll be staying on 1.7.2
