### ISSUE TITLE
Mix Manifest missing first letter of sass file.

### ISSUE THREAD

**Issue by hartey11** [JeffreyWay/laravel-mix#1455]
- Laravel Mix Version: 1.7.2
- Node Version 8.4.0
- yarn version v1.3.2 
- MacOS High Sierra: 

Hi,

When I run yarn run production. A mix-manifest.json is generated but the css generated from sass is missing the first letter. I have tried several different names, paths etc but the first letter is always removed? The javascript files are added correctly.

webpack.mix.js
`.sass('styles/app.scss', 'styles/')`

mix-manifest.json
`"/tyles/app.css": "/tyles/app.css",`

**Comment by nkostadinov** [comment]
I had the same problem so upgraded to 2.0. Now this problem is gone but HMR is not working

**Comment by hartey11** [comment]
Thanks! Updating worked
