### ISSUE TITLE
extractVueStyles adds my vue styles to the start of app.css

### ISSUE THREAD

**Issue by rstadler333** [JeffreyWay/laravel-mix#1460]
- Laravel Mix Version: 2.0.0
- Node Version: v8.9.4
- NPM Version: v8.9.4
- OS: Ubuntu 17.10

### Description:
after trying every thinkable and unthinkable solution, I still can't get it to work.
I am using laravel-mix in a pure Vue / non-Laravel Project. I am trying to do a prod build with extractVueStyles to a custom location. However it doesn't extract the css to it's own css file but instead adds it to the first line of the app.css file. this has the consequence that some styles are overwritten by global styles in next few lines.

my package.json
``` JSON
{
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.17",
    "babel-polyfill": "^6.26.0",
    "cross-env": "^5.1.3",
    "laravel-mix": "^2.0.0",
    "lodash": "^4.17.5",
    "mini.css": "^2.3.7",
    "moment": "^2.20.1",
    "purify-css": "^1.2.6",
    "purifycss-webpack": "^0.7.0",
    "ts-loader": "^3.4.0",
    "typescript": "^2.7.1",
    "vee-validate": "^2.0.3",
    "vue": "^2.5.13",
    "vue-class-component": "^6.1.2",
    "vue-property-decorator": "^6.0.0",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  }
}

```

my webpack.mix.js:
``` JS
mix.setPublicPath(path.resolve('./'));

mix.sass('src/scss/app.scss', 'css/app.css')
    .js('src/js/app.js', 'js/app.js')
    .copyDirectory('src/img', 'img')
    .copyDirectory('src/video', 'video');

if (mix.inProduction()) {
  mix.copy('src/index.prod', 'index.html')
      .options({
        extractVueStyles: 'css/components.css',
        processCssUrls: false
      })
      .minify(['js/app.js','css/app.css'])
      .version();
} else {
  mix.copy('src/index.dev', 'index.html')
      .sourceMaps();
}
```

everything else works perfectly. except that it is writing the styles into the app.css.

What am I missing?

### Steps To Reproduce:
1. delete `node_modules` and `package-lock.json`
2. `npm cache clear --force`
3. `npm install`
4. `npm run prod`

#### Expected: 
- css/
| - app.css <- global styles
| - app.min.css <- minified global styles
| - components.css <- vue styles
| - components.min.css <- minified vue styles

#### Result:
- css/
| - app.css <- vue + global styles
| - app.min.css <- minified vue + global styles
| - components.min.css (0 bytes)

**Comment by cfabrice** [comment]
Same problem here !

**Comment by tpraxl** [comment]
I can confirm that. Just tested it by adding some fixtures and a test to the laravel-mix tests:

```js
test.cb.only('it extracts vue styles correctly', t => {
    // Given we have a js file that imports vue
    mix.js('test/fixtures/fake-app/resources/assets/js/app-with-vue.js', 'js/app.js')
        // And a scss file with some styles
        .sass('test/fixtures/fake-app/resources/assets/sass/app.scss', 'css/app.css')
    // and we want to extract vue styles
        .options({extractVueStyles: 'css/components.css'});
    // When we compile it
    compile(t, () => {
        // Then we expect the js to be built
        t.true(File.exists('test/fixtures/fake-app/public/js/app.js'));
        // And the app.css to be built
        t.true(File.exists('test/fixtures/fake-app/public/css/app.css'));
        // And the extracted vue styles to be in their own css
        t.true(File.exists('test/fixtures/fake-app/public/css/components.css'));

    })

});
```

It fails when it asserts that components.css is in place. I'll have a look into it.

**Comment by tpraxl** [comment]
Currently, it looks to me as if extract-text-webpack-plugin doesn't work correctly, because the given filename is correctly resolved and passed to the constructor of this plugin, which seems to be the correct way of doing this, given a brief inspection of the sources. Directly afterwards, a dump of the plugin reveals that its filename is set to app.css (instead of components.css).

**Comment by tpraxl** [comment]
Got it. It's a bug. I'll create a PR for it.

**Comment by rstadler333** [comment]
thanks so much for the fast resolution 😁

**Comment by tpraxl** [comment]
You're welcome.

**Comment by ThomHurks** [comment]
@JeffreyWay I will investigate further tomorrow, but this broke the CSS in my app. Reverting to 2.0 fixes the problem for now.

**Comment by ThomHurks** [comment]
@JeffreyWay This breaks unfortunately.
For me it now:
- Suddenly creates a new CSS file called "vue-styles.css"
- Just dumps vue-styles.css into /public/, *not* into /public/css/
- I actually want it to concatenate to app.css as I use scoped CSS, so I have no conflicts anyway.
Also insert here the usual rant about semver not being respected, etc, etc.
