### ISSUE TITLE
Toast customization

### ISSUE THREAD

**Issue by randohinn** [JeffreyWay/laravel-mix#1461]
- OS:  Win10

### Description:

Would be cool if we could customize the toast message. I find it's size to be too wide, but don't want to turn toast off aswell OS-wide...

**Comment by cshawaus** [comment]
Looking into the documentation for `node-notifier` it doesn't appear this is possible as all notifications use the built-in OS API which is controlled by a non-configurable system level setting or static implementation.

If you don't want any notifications, you can simply disable them by using the following.

```js
mix.disableNotifications();
```
