### ISSUE TITLE
.env(dotenv) key naming unclear.

### ISSUE THREAD

**Issue by stephan-v** [JeffreyWay/laravel-mix#1463]
Why do the Laravel docs specifically state to prefix .env when the `dotenv` package is being used and you can possibly put anything there that you would want and not have to start with that prefix.

> You may inject environment variables into Mix by prefixing a key in your .env file with MIX_:
> 
> MIX_SENTRY_DSN_PUBLIC=http://example.com

I might understand if the reasoning behind this is to prevent collisions with other keys that might be present in the default environment setup. But if that is the case than please make that part clear to avoid any confusion since the code does not implicitly do anything with the `MIX_` prefix.

**Comment by eberkund** [comment]
I think the purpose is to be very explicit with what gets included in the JS bundle, you don't want to accidentally leak all your private API keys.

**Comment by stephan-v** [comment]
Any other key still seems to be accessible though.

**Comment by JeffreyWay** [comment]
We filter out any non MIX_ prefixed env vars. 

https://github.com/JeffreyWay/laravel-mix/blob/master/src/plugins/MixDefinitionsPlugin.js#L37
