### ISSUE TITLE
npm run dev prod watch erorrs again...

### ISSUE THREAD

**Issue by tropa** [JeffreyWay/laravel-mix#1464]
npm list --depth=0 

npm ERR! missing: lcid@1.0.0, required by os-locale@2.1.0
npm ERR! missing: mem@1.1.0, required by os-locale@2.1.0
npm ERR! missing: cross-spawn@5.1.0, required by execa@0.7.0
npm ERR! missing: get-stream@3.0.0, required by execa@0.7.0
npm ERR! missing: is-stream@1.1.0, required by execa@0.7.0
npm ERR! missing: npm-run-path@2.0.2, required by execa@0.7.0
npm ERR! missing: p-finally@1.0.0, required by execa@0.7.0
npm ERR! missing: signal-exit@3.0.2, required by execa@0.7.0
npm ERR! missing: strip-eof@1.0.0, required by execa@0.7.0
npm ERR! missing: lru-cache@4.1.1, required by cross-spawn@5.1.0
npm ERR! missing: shebang-command@1.2.0, required by cross-spawn@5.1.0
npm ERR! missing: which@1.3.0, required by cross-spawn@5.1.0
npm ERR! missing: shebang-regex@1.0.0, required by shebang-command@1.2.0
npm ERR! missing: path-key@2.0.1, required by npm-run-path@2.0.2
npm ERR! missing: invert-kv@1.0.0, required by lcid@1.0.0
npm ERR! missing: mimic-fn@1.2.0, required by mem@1.1.0
npm ERR! missing: find-up@2.1.0, required by read-pkg-up@2.0.0
npm ERR! missing: read-pkg@2.0.0, required by read-pkg-up@2.0.0
npm ERR! missing: locate-path@2.0.0, required by find-up@2.1.0
npm ERR! missing: p-locate@2.0.0, required by locate-path@2.0.0
npm ERR! missing: path-exists@3.0.0, required by locate-path@2.0.0
npm ERR! missing: p-limit@1.2.0, required by p-locate@2.0.0

and so on

npm run dev 

npm ERR! errno 1
npm ERR! public_html@1.0.0 dev: `npm run development`
npm ERR! Exit status 1

and so on...

ALL the recomendations are done - there is no effect.

What me to do? Application were run and working, nothing changed, restarting of nmp run watch complted those errors.

**Comment by tropa** [comment]
debug log

http://prntscr.com/icacvd

**Comment by ankurk91** [comment]
```
rm -rf node_modules
npm install
```
