### ISSUE TITLE
Extract nested dependencies

### ISSUE THREAD

**Issue by tillkruss** [JeffreyWay/laravel-mix#147]
Is there a way to extract nested dependencies?

I've got the following setup, that fails to extract `clipboard` into the `vendor.js` file and remains in `app.js`:

webpack.mix.js:
```js
mix.js('resources/assets/js/app.js', 'public/js');
mix.extract('clipboard');
```

app.js:
```js
require('./_sharing');
```

_sharing.js:
```js
import Clipboard from 'clipboard';
```

**Comment by JeffreyWay** [comment]
Yeah I think that should work. When you compile everything down, are you getting the `vendor.js` file? Does it  contain any reference to Clipboard?

**Comment by tillkruss** [comment]
I get a `vendor.js` and `manifest.js`, but the `clipboard` module is inside `app.js` and not in `vendor.js`.

**Comment by JeffreyWay** [comment]
I think you need to use an array for mix.extract().

**Comment by tillkruss** [comment]
That works, thanks Jeffrey!
