### ISSUE TITLE
extract vendors doesn't import global object in window

### ISSUE THREAD

**Issue by wawanopoulos** [JeffreyWay/laravel-mix#1478]
- Laravel Mix Version: 2.0.0
- Node Version : 6.7.0 
- NPM Version : 5.6.0
- OS: Mac OSX

### Description:

I use the following code in my webpack.mix.js to:
- extract vendor libraries (moment, jquery) into a vendor.js file
- load jquery as global into my app using autoload

```
mix.autoload({
        jquery: ['$', 'window.jQuery', 'jQuery']
    })
   .js(['asset/entry.js'], 'public/js/app.js')
   .extract(['moment', 'jquery', 'datepicker])
   .sourceMaps();

if (mix.inProduction()) {
    mix.version();
}
```

In my blade file:

```
<script src="{{ asset(mix('js/manifest.js')) }}"></script>
<script src="{{ asset(mix('js/vendor.js')) }}"></script>
<script src="{{ asset(mix('js/app.js')) }}" type="text/javascript"></script>
```

There is no error on compilation using npm run watch, but i don't have access to the jQuery object is on global scope and i get jQuery is undefined error when datepicker is loaded. (Whereas jquery should be loaded before).

What is the best practive to use autoload and extract methods ?

**Comment by ankurk91** [comment]
extract() does not make modules available in global scope.
You should be using `autoload` method
https://github.com/JeffreyWay/laravel-mix/blob/master/docs/autoloading.md

**Comment by wawanopoulos** [comment]
Whatever the library that i want to include the autoload seems doesn’t working. I don’t have access to jquery in global scope.
