### ISSUE TITLE
Mix.combine doesn't output the compiled file into the mix-manifest.json

### ISSUE THREAD

**Issue by iulyanp** [JeffreyWay/laravel-mix#148]
Hello @JeffreyWay ,

I'm having a lot of fun playing with laravel-mix v0.5 and I think I found one small issue.
I'm trying to combine some css files and everything works fine, the files are concatenated, but I can't find the combined file into mix-manifest.json.

For example:
```
mix
    .combine([
        'assets/css/animate.css',
        'assets/css/icomoon.css',
        'assets/css/magnific-popup.css',
        'assets/css/simple-line-icons.css'
    ], 'css/all.css')
    .js('assets/js/app.js', 'js')
;
```

```
# mix-manifest.json
{
  "js/app.js": "js/app.js"
}
```

Is this the expected behavior?

Best regards,

**Comment by JeffreyWay** [comment]
Yes, that's expected, since copying files is sort of an added feature. It's not connected to the Webpack compilation process at all.
