### ISSUE TITLE
Combine and merge css files

### ISSUE THREAD

**Issue by AndriyGo** [JeffreyWay/laravel-mix#1481]
Let's assume I have one.css and two.css.
In one.css:

`nav {
    z-index: 1;
}`

In two.css:

`nav {
    padding: 0 20px;
}`

If I run `.combine(['one.css', 'two.css'], 'Public/all.css')` I get:

```
nav {
    z-index: 1;
}
nav {
    padding: 0 20px;
}
```

Instead, I would like to merge the attributes to get:

```
nav {
    z-index: 1;
    padding: 0 20px;
}
```

Is this possible? :)

**Comment by tpraxl** [comment]
Your example is about javascript files that contain css code.

Please consider using sass: 

one.sass: 

```sass
nav {
   z-index: 1;
}
```

```sass
@import "two"

nav {
   padding: 0 20px;
}

```

`mix.sass('one.sass', 'Public')`

This will result in the desired output.

**Comment by AndriyGo** [comment]
Sorry, my bad. I made a typo. Those were scss files. Unfortunately, it still does not produce the result I want :(

**Comment by tpraxl** [comment]
You are right. Sorry for my wrong answer. I guess this is a sass / webpack question then.

**Comment by RichDonnellan** [comment]
@AndriyGo Off-topic, but you should be able to use `~` (tilde) instead of writing out `node_modules` each time. The syntax would be:

```css
@import "~materialize-css/sass/components/color-variables";
@import "~materialize-css/sass/components/variables";
...
```

**Comment by JeffreyWay** [comment]
`mix.combine()` will never do any optimizations like that. All it does is concatenate and minify (if in production) files. Nothing else.
