### ISSUE TITLE
"Cannot GET /js/app.js" in HMR Mode

### ISSUE THREAD

**Issue by nkrh** [JeffreyWay/laravel-mix#1483]
- Laravel Mix Version: 2.0.0
- Node Version (`node -v`):  8.9.4
- NPM Version (`npm -v`): 5.6.0
- Laravel Version: 5.6.3
- OS: Windows 10

### Description:
When I access http://localhost:8080/js/app.js in HMR mode (`npm run hot`), the server returns 404 with message: "Cannot GET /js/app.js".

### Steps To Reproduce:

1. Create new laravel project by using `laravel new <project_name>` command
2. Run `npm install`
3. **Delete public/js/app.js** to avoid confusion. Assets are [served from memory](https://github.com/webpack/docs/wiki/webpack-dev-server#content-base)
4. With browser, go to http://localhost:8080/js/app.js

**Comment by nkrh** [comment]
This is the workaround, inspired from #1437 :

Put this into webpack.mix.js.
```javascript
Mix.listen('configReady', (webpackConfig) => {
  if (Mix.isUsing('hmr')) {
    // Remove leading '/' from entry keys
    webpackConfig.entry = Object.keys(webpackConfig.entry).reduce((entries, entry) => {
      entries[entry.replace(/^\//, '')] = webpackConfig.entry[entry];
      return entries;
    }, {});

    // Remove leading '/' from ExtractTextPlugin instances
    webpackConfig.plugins.forEach((plugin) => {
      if (plugin.constructor.name === 'ExtractTextPlugin') {
        plugin.filename = plugin.filename.replace(/^\//, '');
      }
    });
  }
});
```

**Comment by misenhower** [comment]
Just wanted to say thanks for making me aware of `configReady`, that's really useful 👍

**Comment by finndev** [comment]
@nkrh

I think this doesn't fix hot-reloading of css though.

**Comment by pjhartin** [comment]
@nkrh - I think @finndev's comment is with regards to your comment on #1437

**Comment by nkostadinov** [comment]
The proposed fix works but this is a workaround. All users using windows have this problem i'm still waiting for an official fix. There are many issues regarding this since v2.0.0 

@JeffreyWay do you plan to apply some of the proposed solutions or we should use them this way ?

**Comment by JoeSchr** [comment]
Awesome, that actually works!

Wish I hadn't wasted hours blaming dockers and fs-events module on windows, but I'm happy now...

**Comment by patrick-hertling** [comment]
Wow, I spend an oweful lot of time looking for a solution. What @nkrh did propose did work for me.

**Comment by georgewritescode** [comment]
@nkrh Thanks for your solution there.
I've written up a little post on how I was able to get Hot Module Reloading working with Laravel Mix and React which includes your suggestion as well as other bits I worked out.

https://medium.com/@grmcameron/laravel-mix-hot-module-reloading-with-react-966ade9ff244

**Comment by jeankvd** [comment]
I'm using laravel's react scaffolding and this doesn't fix the issue for me

**Comment by theNailz** [comment]
Stil broken in the latest stable laravel/laravel release; when will this ship?

**Comment by orckid-lab** [comment]
- Laravel 5.7
- laravel-mix 3.0.0
- node 10.11.0
- npm 6.4.1
- OS: Windows 10

Issue still occurs. had to use workaround as specified above, as indicated it doesn't fix HMR for CSS

**Comment by nkostadinov** [comment]
I dont think anyone will fix this. But with the new vue-cli you actually don't need laravel mix anymore.

**Comment by orckid-lab** [comment]
@nkostadinov I was not aware that vue-cli can be used with laravel? I assume you're referring to the template by yyx990803/laravel-vue-cli-3 but doesn't that forces/drives to an SPA implementation?

**Comment by nkostadinov** [comment]
Actually I'm not using laravel as backend but the idea of mix is to provide config to webpack for easier management. It's not really bound to the framework. You just need to add manifest plugin and configure it to emit a manifest.json file.

**Comment by rosnaib11** [comment]
@nkrh It works

**Comment by chebonv** [comment]
> This is the workaround, inspired from #1437 :
> 
> Put this into webpack.mix.js.
> 
> ```js
> Mix.listen('configReady', (webpackConfig) => {
>   if (Mix.isUsing('hmr')) {
>     // Remove leading '/' from entry keys
>     webpackConfig.entry = Object.keys(webpackConfig.entry).reduce((entries, entry) => {
>       entries[entry.replace(/^\//, '')] = webpackConfig.entry[entry];
>       return entries;
>     }, {});
> 
>     // Remove leading '/' from ExtractTextPlugin instances
>     webpackConfig.plugins.forEach((plugin) => {
>       if (plugin.constructor.name === 'ExtractTextPlugin') {
>         plugin.filename = plugin.filename.replace(/^\//, '');
>       }
>     });
>   }
> });
> ```

for the users like me, Make sure you terminate the npm while running and issue the` npm run hot` command again for it work

**Comment by msonowal** [comment]
It does not work in latest version when using different public path

**Comment by ssi-anik** [comment]
> This is the workaround, inspired from #1437 :
> 
> Put this into webpack.mix.js.
> 
> ```js
> Mix.listen('configReady', (webpackConfig) => {
>   if (Mix.isUsing('hmr')) {
>     // Remove leading '/' from entry keys
>     webpackConfig.entry = Object.keys(webpackConfig.entry).reduce((entries, entry) => {
>       entries[entry.replace(/^\//, '')] = webpackConfig.entry[entry];
>       return entries;
>     }, {});
> 
>     // Remove leading '/' from ExtractTextPlugin instances
>     webpackConfig.plugins.forEach((plugin) => {
>       if (plugin.constructor.name === 'ExtractTextPlugin') {
>         plugin.filename = plugin.filename.replace(/^\//, '');
>       }
>     });
>   }
> });
> ```

When using `mix('path/to/asset-file')` to get the assets, it checks whether `public/hot` exists or not. If the `hot` file exists, it uses the URL from that file and appends the `path/to/asset-file` to that URL to serve the asset.

Even though the `hot` file contains a **trailing** `/`, and forces the `path/to/asset-file` to use **leading** `/` it becomes `//url:port//path/to/asset-file` and still this works fine.

I was using `mix.js().styles().version()`. The `version` method should be used like below. Otherwise, **hot** command doesn't work and at least that's what I found in my case. :grimacing:

```javascript
if (mix.inProduction()) {
  mix.version();
}
```

With:
- Laravel: `6.x`
- Laravel-Mix: `5.x`
