### ISSUE TITLE
Only .extract([...])'d .vue <style>s are included if any .vue is extracted.

### ISSUE THREAD

**Issue by hailwood** [JeffreyWay/laravel-mix#1484]
- Laravel Mix Version: 2.0.0 (`npm list --depth=0`)
- Node Version (`node -v`): 9.5.0 
- NPM Version (`npm -v`): 5.6.0
- OS: 

### Description:
If you include a .vue file in your `.extract([...], 'vendor.js')` call in the webpack.mix.js (as you might with any third party component that is used) and include `.options({extractVueStyles: 'app.css'})` only the vue components listed in the extract array get their styles extracted, the rest do have them removed from the component, but they are not added to the app.css.

### Steps To Reproduce:
Minimal Reproduction repo: https://github.com/hailwood/laravel-mix-extract-bug

```bash
git clone https://github.com/hailwood/laravel-mix-extract-bug.git
npm install
npm run prod
```
Open the app.css

Expected: 
```css
.from-example-component{background:green}.from-another-example-component{background:green}
```
Actual:
```css
.from-example-component{background:green}
```

If the .vue component is not included in the extract array we get the expected output,
if both .vue components are listed in the extract array we get the expected output.

Neither of these "workarounds" are desirable.

Given the way it's overriding the expected vue-styles.css (or appropriate name), I feel that bug is that rather than creating a new `ExtractTextPlugin` to extract the vendor vue styles, it's instead reusing the existing one and overriding the output. This is just a guess of course.

Links of interest:
[webpack.mix.js](https://github.com/hailwood/laravel-mix-extract-bug/blob/master/webpack.mix.js)
[ExampleComponent.vue](https://github.com/hailwood/laravel-mix-extract-bug/blob/master/resources/components/ExampleComponent.vue)
[AnotherExampleComponent.vue](https://github.com/hailwood/laravel-mix-extract-bug/blob/master/resources/components/AnotherExampleComponent.vue)
[app.js](https://github.com/hailwood/laravel-mix-extract-bug/blob/master/resources/app.js)
[app.css (final output)](https://github.com/hailwood/laravel-mix-extract-bug/blob/master/app.css)

**Comment by jjhesk** [comment]
same problem here
