### ISSUE TITLE
Vulnerability found in Laravel Mix 2.0

### ISSUE THREAD

**Issue by rap2hpoutre** [JeffreyWay/laravel-mix#1485]
- Laravel Mix Version: 2.0.0 (`npm list --depth=0`)
- Node Version (`node -v`): v8.1.2
- NPM Version (`npm -v`): 5.6.0
- OS: MacOS

### Description:

Running `nsp check` gives this result:

```
(+) 1 vulnerability found
┌────────────┬────────────────────────────────────────────────────────────────────┐
│            │ Prototype pollution attack                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Name       │ hoek                                                               │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ CVSS       │ 4 (Medium)                                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Installed  │ 2.16.3                                                             │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Vulnerable │ <= 4.2.0 || >= 5.0.0 < 5.0.3                                       │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Patched    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                        │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Path       │ xxxxxx@undefined > laravel-mix@2.0.0 > chokidar@1.7.0 >        │
│            │ fsevents@1.1.3 > node-pre-gyp@0.6.39 > hawk@3.1.3 > hoek@2.16.3    │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ More Info  │ https://nodesecurity.io/advisories/566                             │
└────────────┴────────────────────────────────────────────────────────────────────┘
```

I just ran this because Github said:

> We found potential security vulnerabilities in your dependencies.

### Steps To Reproduce:
Install https://nodesecurity.io/opensource then run `nsp check`

**Comment by tpraxl** [comment]
Do I interpret this right? hoek@2.16.3 is vulnerable? So it's essentially hawk@3.13, then node-pre-gyp@0.6.39, then fsevents@1.1.3 (which won't be installed on linux systems), then chokidar@1.7.0 that is vulnerable and this is why mix is vulnerable?

Thanks for announcing this. Seriously. But shouldn't we report this to any of the involved libraries in the dependency chain in the first place?

**Comment by rap2hpoutre** [comment]
@tpraxl I think it's related to Mix because `Mix` requires `chokidar` to version 1.7.0 (see: https://github.com/JeffreyWay/laravel-mix/blob/master/package.json#L39) and chokidar is now in version 2.0. 

So I think we could update to version 2.0 to fix the problem, but I don't know if there are breacking changes. I asked here: https://github.com/paulmillr/chokidar/issues/683 and if there is no breaking change I will submit a PR.

In other words, Mix is not vulnerable itself but it seems it relies on a vulnerable version of _something_.

**Comment by tpraxl** [comment]
@rap2hpoutre Thanks for the info and your engagement!
