### ISSUE TITLE
Vue-loader options.

### ISSUE THREAD

**Issue by BlitZz96** [JeffreyWay/laravel-mix#1487]
I see no docs on how to interact with vue-loader trough .mix

[https://vue-loader.vuejs.org/en/options.html](https://vue-loader.vuejs.org/en/options.html) has more options than what you have included in the [docs/options.md](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/options.md).

I would want to use the [preservewhitespace](https://vue-loader.vuejs.org/en/options.html#preservewhitespace). However, I cannot seem to find any what to add this option by today. Am I looking at the wrong place, or?

Simply adding vue-loader as a rule in webpackConfig did not seem to work. Looked like it initialized vue-loader twice and broke it with [Failed to mount component: template or render function not defined](https://github.com/vuejs/vue-loader/issues/844#issuecomment-308976557)

How do we go with adding custom vue-loader options?

**Comment by isometriq** [comment]
Same here, maybe there is way to get the config and alter it somehow..

**Comment by isometriq** [comment]
Actually according to this
https://github.com/JeffreyWay/laravel-mix/blob/master/docs/quick-webpack-configuration.md

It should do a deep merge

**Comment by isometriq** [comment]
mix.preLoaders() and mix.postLoaders() are available
https://github.com/JeffreyWay/laravel-mix/commit/e45503786c0fa50a13cc0755bcf9c18eff569e5d

but otherwise it seems the whole config is needed
https://github.com/JeffreyWay/laravel-mix/issues/875

**Comment by isometriq** [comment]
actually its
```
mix.options({
        vue: {
            preLoaders: {

            }
            postLoaders: {

            }
        }
    })
```

**Comment by mezhevikin** [comment]
@BlitZz96 Hello. I'd like to remove whitespaces from vue templates. I added your code to my webpack.mix.js.

```
   mix.options({
        vue: {
            preserveWhitespace: false
        }
    });
```

But I,m getting anyway `[this._v("\n                    I'm an example component.\n                ")]`.
What's wrong?

**Comment by binotaliu** [comment]
Please notice that `preserveWhitespace` and `whitespace` is [compilerOptions](https://vue-loader.vuejs.org/options.html#compileroptions). Not options of `vue-loader` but `vue-template-compiler`.
Correct way to set this is:

```javascript
mix.options({
  vue: {
    compilerOptions: {
      whitespace: 'condense'
    }
  }
})
```

This github issue shows on the top of my search result page. So I just leave the right answer here.
