### ISSUE TITLE
Multiple webpack config

### ISSUE THREAD

**Issue by kbumsik** [JeffreyWay/laravel-mix#1489]
Hello, I would like to use [multiple webpack configurations as in official Webpack](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations).

I tried two things to do that:
1. multiple webpack configs as a list `mix.webpackConfig([config1, config2...]); This is the standard way in Webpack.
2. Call `mix.webpackConfig()` multiple times

Both won't work, case 1 outputs error and case 2 only accepts the single last `mix.webpackConfig()` call and ignores others.

Anyone have an idea about this?
Thank you.

**Comment by ankurk91** [comment]
AFAIK This is not supported.

**Comment by JeffreyWay** [comment]
Yeah, not supported at the moment.

**Comment by LeoColomb** [comment]
See #989
