### ISSUE TITLE
ERR_CONNECTION_RESET error 

### ISSUE THREAD

**Issue by abrhambas01** [JeffreyWay/laravel-mix#1490]
http://localhost:8080/dist/js/app.js net::ERR_CONNECTION_RESET
Why do I experience this error in my devtools console? 

And hmr won't work . Is it because of that ?

**Comment by ruchern** [comment]
Need more details as this is coming from your localhost and we have no access to it.

**Comment by abrhambas01** [comment]
@ruchern. Sometimes I experience that error and then there are times that hmr's fine. How can you have an access to it.?

**Comment by ankurk91** [comment]
Community can not help you unless you fill **ISSUE_TEMPLATE** properly.
