### ISSUE TITLE
Why we "require()" Vue.js components without ".default" in Laravel projects and how it works?

### ISSUE THREAD

**Issue by iboved** [JeffreyWay/laravel-mix#1492]
Hi!
Can you explain please? Why we reqire Vue.js components in [Laravel](https://laravel.com/docs/5.6/frontend#writing-vue-components) like so (without ".default"):

`Vue.component('example', require('./components/Example.vue'));`

And how it works?
But the vue-loader [update guide](https://github.com/vuejs/vue-loader/releases/tag/v13.0.0) says:
Old CommonJS-style requires will also need to be updated:

```
// before
const Foo = require('./Foo.vue')

// after
const Foo = require('./Foo.vue').default
```

I have found also that Babel@6 doesn't export default module.exports any more - [T2212 Kill CommonJS default export behavior](https://github.com/babel/babel/issues/2212).
So, how does "require()" work in Laravel without a ".default", and it does not work on a clean (non Laravel) Vue.js project installed via vue-cli?

Thank you in advance.

**Comment by ankurk91** [comment]
I think  you should read this
https://github.com/vuejs/vue-loader/blob/master/docs/en/options.md#esmodule

**Comment by raniesantos** [comment]
The file is gone, do you know where they moved the content?

**Comment by ankurk91** [comment]
Here we go
https://github.com/vuejs/vue-loader/blob/v14.0.0/docs/en/options.md
