### ISSUE TITLE
[Hint] TypeError: Cannot read property 'afterCompile' of undefined (Set ts-loader version to 3.5)

### ISSUE THREAD

**Issue by okaufmann** [JeffreyWay/laravel-mix#1498]
- Laravel Mix Version: 2.0
- Node Version (`node -v`): 9.4.0
- NPM Version (`npm -v`): 5.6.0
- OS: Windows 10

### Description:
laravel-mix will verify and install missing loaders automatically.

In the case of ts-loader it will currently install Version 4 which will drop support(https://github.com/TypeStrong/ts-loader/blob/master/CHANGELOG.md) for webpack 3.x. As this is currently the used version by laravel-mix the following error will occur:

    TypeError: Cannot read property 'afterCompile' of undefined

To solve this just set the version of ts-loader explicit to latest 3.5 version.

There is already a WIP for supporting webpack 4.

### Steps To Reproduce:

- install laravel-mix (`npm install laravel-mix`)
- transpile a file mit mix.ts('path/to/file.ts')

**Comment by yaquawa** [comment]
Same issue here.
