### ISSUE TITLE
MIX NOT WORK!!!!!

### ISSUE THREAD

**Issue by Jatapiaro** [JeffreyWay/laravel-mix#1502]
### Description:

Everything is fine, it's a Laravel fresh project, but in the moment i run npm run production, watch or dev, everything stops working and only I can see a damn white screen. No other thing. If I just checkout the previous version of my app.js file everything works, but again if i just run npm run prod,, nothing works. 

You can see what is happening here: https://youtu.be/WkPEdxj4HT4

### Steps To Reproduce:

Just do a fresh laravel project, execute npm install and then npm run prod. Nothing will work

**Comment by browner12** [comment]
Cannot duplicate. Please provide much more information. What does your dev console output say? What HTML is generated by the page? What does your `webback.mix.js` file look like?  What does the generated CSS look like?

People can't debug your issue if you just say it doesn't work.

**Comment by NoelDavies** [comment]
@Jatapiaro please provide samples of your `./webpack.mix.js`, `./package.json` and perhaps launch a new terminal and record your exact interaction using a tool like https://asciinema.org/
