### ISSUE TITLE
npm run production error

### ISSUE THREAD

**Issue by testdnmedia** [JeffreyWay/laravel-mix#1503]
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
internal/child_process.js:340
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1003:13)
    at ChildProcess.spawn (internal/child_process.js:340:11)
    at Object.exports.spawn (child_process.js:499:9)

**Comment by robbyrice** [comment]
This looks like it might be a permissions issue, but because you haven't filled out the issue template and have given no information on your environment there is not much help we can give you.
