### ISSUE TITLE
npm run hot will not compile less(defined by mix.less), is this normal behaviour or a bug or i mis-configure?

### ISSUE THREAD

**Issue by kidsit** [JeffreyWay/laravel-mix#1507]
- Laravel Mix Version: 1.0.0
- Node Version (`node -v`): v8.9.1
- NPM Version (`npm -v`): v5.5.1
- OS: windows 10

### Description:
Everything works perfect, when dev vue app, run 
npm run hot 
to enable the HMR feature.
In the mix file, it seems that 
mix.less('app.less','app.css') DOES NOT COMPILE THE LESS.
Less will be compiled when in 
npm run dev/watch 
mode.

### Steps To Reproduce:
1. in webpack.mix.js:
    mix.js('resources/assets/js/app.js', 'public/js')
   .less('resources/assets/less/app.less', 'public/css');
2. in git bash command window, run 
   `
     npm run hot
    `
3. Vue dev is perfect, while the above less file will not be compiled.

Is this a expected behaviour or something i have not configured perfect?

**Comment by camiant** [comment]
same issue here... any idea?
