### ISSUE TITLE
Use nextcss with laravel-mix

### ISSUE THREAD

**Issue by the94air** [JeffreyWay/laravel-mix#1508]
I installed nextcss Dependencies and I am not able to configure it with laravel mix. Nothing useful in the documentation. Any help?
```
npm install postcss postcss-cssnext
```

**Comment by JeffreyWay** [comment]
This works...

```js
Config.autoprefixer = false;

mix.postCss('resources/assets/css/test.css', 'css', [
    require('postcss-cssnext')
]);
```

Anything else you're trying to accomplish that doesn't work?

**Comment by the94air** [comment]
Nope. Thanks so much.
