### ISSUE TITLE
'node_modules' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by lukashl** [JeffreyWay/laravel-mix#151]
After npm install and npm run dev, console show:

> @ dev C:\Users\lukas\apps\
> node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

'node_modules' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.15014
npm ERR! argv "C:\\NodeJS\\node.exe" "C:\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script 'node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by nickarellano** [comment]
I had the same issue. I just had to modify every instance of 
"node_modules/cross-env/bin/cross-env.js" with just "cross-env"

**Comment by lukashl** [comment]
nickarellano it's working ;)

**Comment by cjmaxik** [comment]
Doesn't work for me

node v7.4.0
npm  v4.0.5
[npm-debug.txt](https://github.com/JeffreyWay/laravel-mix/files/728280/npm-debug.txt)

**Comment by cringer** [comment]
I get the same issue.  Likely due to the fact we are using Windows.  I was really excited to use this new version too...

**Comment by Hendriksie** [comment]
I have the exact same problem.

As @cjmaxik mentioned above, just put "node" before the 4 scripts defined in the package.json and you are good to go.

**Comment by cjmaxik** [comment]
@Hendriksie, nope, this doesn't work.

**Comment by rask** [comment]
Windows 7 64-bit, NodeJS 6.9.4, npm 4.1.1.

Adding `node` in front of the script commands worked here. I use GitBash that came with Git.

Any ideas if this change then later on works normally on a non-Windows system?

**Comment by Hendriksie** [comment]
@cjmaxik, thats weird, I put it in the package.json and when I run `npm run dev` it works perfectly.

**Comment by Hendriksie** [comment]
@rask, I tested it on Homestead through SSH, and when having "node" in front of the scripts it still works.

**Comment by iainheng** [comment]
Same issue in Windows 10.

**Comment by glukash** [comment]
add `node ./` in each line, so they look like this:

```javascript
    "dev": "node ./node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "node ./node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "node ./node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "node ./node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
```

**Comment by GDanielRG** [comment]
I tried adding the "node" before but didn't work either. I wasn't even able to npm install correctly I get errors with the webpack package with the fsevents dependency. Is somebody getting the same error on windows?

`-- laravel-mix@0.5.3
  +-- concatenate@0.0.1
  | `-- globs@0.1.2  (git://github.com/stephenmathieson/node-globs.git#80bb9161c8c178f8836fff34da3afd1cbc87cedb)
  `-- UNMET PEER DEPENDENCY webpack@2.2.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN extract-text-webpack-plugin@2.0.0-beta.5 requires a peer of webpack@^2.1.0-beta.19 || ^2.2.0-rc.0 but none was installed.
npm WARN webpack-dev-server@2.2.0 requires a peer of webpack@^2.2.0 but none was installed.

**Comment by JeffreyWay** [comment]
We updated the Laravel repo to add "node" to the beginning of each NPM script. 

@GDanielRG You have something unrelated to this issue. You can file a new one if it's still not working after checking your Node/NPM versions and redoing npm install.

**Comment by GDanielRG** [comment]
@JeffreyWay  Yes indeed I was having another issue which I just resolved and adding the node at the beginning of script worked! thanks!

**Comment by saidbakr** [comment]
I have the same issue, I just followed the Laracast tutorial **Laravel Mix and the Front-end**

npm run dev

```
@ dev C:\Users\Said\Desktop\Project\laravel\blog
> node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Users\Said\Desktop\Project\laravel\blog\node_modules\cross-env\dist\bin\cross-env.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Said\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v7.7.1
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Said\AppData\Roaming\npm-cache\_logs\2017-03-08T01_49_42_466Z-debug.log
```

**Comment by elasticsteve** [comment]
just updated laravel/laravel and the new package.json

now nothing works!

Windows here.
```> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

'cross-env' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Steve Rhodes\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
```

**Comment by wing5wong** [comment]
Also have the same issue as above.
`Windows 10 1607, OS Build 14393.726

npm -v
3.10.10

node -v
v6.10.0
`

**Comment by wing5wong** [comment]
Resolved by updating package.json, and reinstalling node-sass manully.

```
{
  "private": true,
  "scripts": {
    "dev": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.15.3",
    "bootstrap-sass": "^3.3.7",
    "jquery": "^3.1.1",
    "laravel-mix": "^0.8.1",
    "lodash": "^4.17.4",
    "vue": "^2.2.2"
  }
   ,"bin": {
    "cross-env": "dist/bin/cross-env.js"
}
}
```

followed by 
```
npm install node-sass
```

working correctly now.

**Comment by shylor** [comment]
@wing5wong You are a life saver. I was going nuts! +1

**Comment by Umelev** [comment]
Using Homestead and receiving still error as follows even if following wing5wong's method:


> @ dev /home/vagrant/www/test
> node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

undefined:1
�FU�]���k�-8T��8��-rm�_J��p���8��-rm�_J��p���8��-rm�_J��p��
^

SyntaxError: Unexpected token � in JSON at position 0
....

npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v7.8.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

**Comment by rask** [comment]
@Umelev that looks like you have a syntax error in your configs. Validate your JSON and see if it continues.

**Comment by AttaUrRehman24** [comment]
You can solve this problem 100% 
https://github.com/AttaUrRehman24/laravel-mix

**Comment by ruchern** [comment]
@AttaUrRehman24 Why don't use you Gist instead of a git repo which does absolutely nothing?

**Comment by Umelev** [comment]
@rask Thank you for your reply. 

The thing was that something had completely messed up my .babelrc file which caused npm fail... No idea what was it but working now.

**Comment by gbrits** [comment]
For anyone who is struggling and just wants to skip the Laravel mix npm commands & environments until a fix comes out for Windows - you could just talk to Webpack directly:

`webpack --config=node_modules/laravel-mix/setup/webpack.config.js`

**Comment by nathanburgess** [comment]
Install _cross-dev_ globally with `npm install -g cross-dev` and modify _package.json_ by placing `node` in front of each executed Javascript.

For example, my _package.json_ now looks like this:  
```
    "development": "cross-env NODE_ENV=development node node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
```

**Comment by zohaibshahzadkhan** [comment]
npm install -save-dev  babel-preset-es2015
 "scripts": {
    "compile": "babel src --presets react,es2015 --out-dir static",
    "watch": "babel src --presets react,es2015 --out-dir static --watch",
    "test": "echo \"Error: no test specified\" && exit 1"
  }
Works for me

**Comment by brianhaferkamp** [comment]
If anyone still is running into an issue with getting this to run in the WIndows OS command line, try this:

"watch": "SET NODE_ENV=development & node node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"

Add "SET" before "NODE_ENV and then "& node" before the file name. That is the only thing that worked for me.

Hope this helps.

**Comment by ngoctaucao01** [comment]
> I have the exact same problem.
> 
> As @cjmaxik mentioned above, just put "node" before the 4 scripts defined in the package.json and you are good to go.
How can I put "node" before 4 scripts

**Comment by Truptimayee1234** [comment]
my package. json file is 👍 {
  "name": "odyssey-automation-ui",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "node_modules/.bin/cypress",
    "test_smoke": "./node_modules/.bin/cypress-tags run -e TAGS=\"@Smoke\"",
    "test_districtAdmin": "./node_modules/.bin/cypress-tags run -e TAGS=\"@DistrictAdmin\"",
    "test_Manager": "./node_modules/.bin/cypress-tags run -e TAGS=\"@Manager\"",
    "test_schoolAdmin": "./node_modules/.bin/cypress-tags run -e TAGS=\"@SchoolAdmin\"",
    "test_Teacher": "./node_modules/.bin/cypress-tags run -e TAGS=\"@Teacher\"",
    "test_Parent": "./node_modules/.bin/cypress-tags run -e TAGS=\"@Parent\"",
    "test_Student": "node node_modules/.bin/cypress-tags run -e TAGS=\"@Student\"",
    "test_Student1": "npm run test -- --spec \"cypress/integration/Student/*\"",
    "test_regression": "./node_modules/.bin/cypress-tags run -e TAGS=\"@Regression\"",
    "cucumber-report": "node cucumber-html-reports.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/edgenuity/odyssey-automation-ui.git"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/cypress-cucumber-preprocessor": "^4.0.1",
    "cypress": "^9.5.4",
    "cypress-cucumber-preprocessor": "^4.2.0",
    "cypress-iframe": "^1.0.1",
    "multiple-cucumber-html-reporter": "^1.18.0"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    }
  },
  "dependencies": {
    "mocha": "^9.2.0",
    "mochawesome": "^6.3.1"
  }
}
 I am gerrting   'node_modules' is not recognized as an internal or external command,
operable program or batch file. error  while trying to run any script on local as well as on server.

**Comment by Annaati** [comment]
I have this issue in NextJS App in windows 10 and I'm using npm.
I have tried adding "node" infront of the scripts in package.json as suggested  and deleting & reinstalling the node modules but all invain, nothing is working.


here is the full erro

`

'Web3\Apps\coinbase-blockchain-app\node_modules\.bin\' is not recognized as an internal or external command,
operable program or batch file.
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'D:\Study\next\dist\bin\next'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

`
