### ISSUE TITLE
Extracting not working if the vendor is not a package

### ISSUE THREAD

**Issue by MajedDH** [JeffreyWay/laravel-mix#1510]
- Laravel Mix Version: 1.7.2 (`npm list --depth=0`)
- Node Version (`node -v`): v6.11.2
- NPM Version (`npm -v`): 3.10.10
- OS: Win 7 64-bit.

### Description:
Can't extract a library which is not installed . it is inside `resources/assets/js`

### Steps To Reproduce:
`.js('resources/assets/js/app.js', 'public/js')
    .extract(['bootstrap-sass', 'resources/assets/js/EXAMPLE_LIB/index.js', 'vue', 'lodash', 'jquery', 'vue-infinite-loading', 'axios'])` didn't work.
I've tried those and none worked:

`resources/assets/js/EXAMPLE_LIB/index.js`

`resources/assets/js/EXAMPLE_LIB`

`EXAMPLE_LIB/index.js`

`EXAMPLE_LIB`

**Comment by JeffreyWay** [comment]
Yeah, that won't work. Needs to be a package.

**Comment by MajedDH** [comment]
Can't this be a feature request ? to extract specific files ?
