### ISSUE TITLE
Result of mix function compiling is empty js file.

### ISSUE THREAD

**Issue by asnike** [JeffreyWay/laravel-mix#1511]
- Laravel Mix Version: 2.0
- Node Version (`node -v`): 8.9.4
- NPM Version (`npm -v`): 5.7.1
- OS: vagrant virtualbox on windows 10 

### Description:
I used laravel-mix well in the past. Recently I started a new project, that I compiled a js with mix function in laravel-mix. Result of compiling is empty file.

```js
webpack.mix.js
`let mix = require('laravel-mix');
mix.js('resources/assets/js/app.js', 'public/js')
    .js('resources/assets/js/admin.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .sass('resources/assets/sass/admin.scss', 'public/css');
```

### Steps To Reproduce:
1. npm run dev
2. Check a js file in explorer that is empty file.

**Comment by JeffreyWay** [comment]
Can't reproduce. I'd need more information. If you try it in a fresh project, do you still see the empty file?

**Comment by TGNThump** [comment]
I'm getting the same issue.
