### ISSUE TITLE
Dynamic import ignores mix.setResourceRoot() path

### ISSUE THREAD

**Issue by artemsky** [JeffreyWay/laravel-mix#1513]
- Laravel Mix Version: 2.0.0
- Node Version: v8.9.4
- NPM Version: 5.6.0
- OS: Windows 10.16299.248 x64

### Description:

[Dynamic import](https://webpack.js.org/api/module-methods/#import-) chunk path is incorrect.
It ignores `mix.setResourceRoot('/admin/')`

Example config

```
mix.js('src/assets/js/admin/app.js', 'assets');
  .setPublicPath('public/admin/')
  .setResourceRoot('/admin/')
```

This will produce
```bash
.
    index.html
├───admin
    │   my-chunk-name.js
    └───assets
            app.js
            manifest.js
```

When I go to index page. I see
```
app.test/my-chunk-name.js Failed to load resource: the server responded with a status of 404 (Not Found)
manifest.js:104 Uncaught (in promise) Error: Loading chunk 0 failed.
    at HTMLScriptElement.onScriptComplete (manifest.js:104)
```

Of course. Because it should look for `my-chunk-name.js` in `app.test/admin/my-chunk-name.js`

### Steps To Reproduce:

Example repo - https://github.com/artemsky/mix-dynamic-import-another-folder-root

```bash
npm install
npm run dev
```

Run any static server (for example [this one](https://www.npmjs.com/package/static-server)) from `/public` folder

**Comment by ankurk91** [comment]
Until this issue get fixed,
https://github.com/JeffreyWay/laravel-mix/issues/1249#issuecomment-335112415

**Comment by philippdaun** [comment]
This is still broken as of Mix v4.1.2 — `setResourceRoot` is ignored for dynamic imports.
