### ISSUE TITLE
Extracting vendor CSS?

### ISSUE THREAD

**Issue by sikhlana** [JeffreyWay/laravel-mix#1515]
I'm currently using this to extract my JS vendors:
```javascript
_.forEach(vendors, (value) => {
    let name, path;

    if (typeof value === 'object') {
        name = value[0];
        path = 'js/vendor/' + value[1] + '.js';
    } else {
        name = value;
        path = 'js/vendor/' + value + '.js';
    }

    mix.extract([name], path);
});
```
Which is working as expected. But I couldn't find any option/method to do the same for the SCSS file that is being compiled. This results in a huge CSS file even when it's minified. Is there any way I could do that to styles as well?

**Comment by ankurk91** [comment]
See how i am dong it.

```js
// webpack.mix.js
mix.js('./resources/assets/js/bootstrap.js', './public/js/app.js')
  .sass('resources/assets/sass/vendor.scss', './public/css/vendor.css')
  .sass('resources/assets/sass/theme.scss', './public/css/app.css')
```

```sass
// resources/assets/sass/vendor.scss
// 3rd party vendors that was installed by npm
@import "~bootstrap-sass/assets/stylesheets/bootstrap";
@import '~font-awesome/css/font-awesome.min';
```

**Comment by davehowson** [comment]
> See how i am dong it.
> 
> ```js
> // webpack.mix.js
> mix.js('./resources/assets/js/bootstrap.js', './public/js/app.js')
>   .sass('resources/assets/sass/vendor.scss', './public/css/vendor.css')
>   .sass('resources/assets/sass/theme.scss', './public/css/app.css')
> ```
> 
> ```sass
> // resources/assets/sass/vendor.scss
> // 3rd party packages that was installed by npm
> @import "~bootstrap-sass/assets/stylesheets/bootstrap";
> @import '~font-awesome/css/font-awesome.min';
> ```

Why is this downvoted? I've been using this method successfully for sometime and I want to know if there's anything wrong with it?

**Comment by orim181** [comment]
With that approach @ankurk91 , how would you handle situations where you need to reference the bootstrap variables (e.g. $gray-600;) in your own scss theme files?
