### ISSUE TITLE
NPM Install errors, help please :(

### ISSUE THREAD

**Issue by mrdigitalau** [JeffreyWay/laravel-mix#1518]
Hi Everyone,

I was wondering if anyone could help me with this problem, I just reformatted my computer running Windows 10 Pro 64bit and all of a sudden, NPM install always fails.

- Laravel Mix Version: #.#.# (`npm list --depth=0`)
- Node Version (`node -v`): 8.10.0
- NPM Version (`npm -v`): 5.7.1
- OS: Windows 10 64Bit

### Description:
Running a new laravel installation using "laravel new blog" and then trying to run npm install, I always get an error, because of this, I can't run npm run dev, or npm run watch.

### Steps To Reproduce:

1. run laravel new blog in CMD
2. run npm install in "blog" folder.
3. After running NPM INSTALL, I get this error:

npm ERR! path D:\xampp\htdocs\blog\node_modules\color-support\bin.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'D:\xampp\htdocs\blog\node_modules\color-support\bin.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MRDIGITAL\AppData\Roaming\npm-cache\_logs\2018-03-11T07_59_29_890Z-debug.log

**DEBUG LOG**

31769 warn ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
31770 verbose stack Error: ENOENT: no such file or directory, chmod 'D:\xampp\htdocs\blog\node_modules\color-support\bin.js'
31771 verbose cwd D:\xampp\htdocs\blog
31772 verbose Windows_NT 10.0.16299
31773 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MRDIGITAL\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--force"
31774 verbose node v8.10.0
31775 verbose npm  v5.7.1
31776 error path D:\xampp\htdocs\blog\node_modules\color-support\bin.js
31777 error code ENOENT
31778 error errno -4058
31779 error syscall chmod
31780 error enoent ENOENT: no such file or directory, chmod 'D:\xampp\htdocs\blog\node_modules\color-support\bin.js'
31781 error enoent This is related to npm not being able to find a file.
31782 verbose exit [ -4058, true ]

**Comment by thecrypticace** [comment]
Try installing again after the error (by running `npm install` again). I think I've seen this happen with other random packages before. If that doesn't work clear your npm cache with: `npm cache clean` and try the installation again.

**Comment by mrdigitalau** [comment]
Hi @thecrypticace 
Thank you for your help.
I tried that, but when I ran it, it suggested to npm cache verify.
I did that, it cleaned some stuff but still did not work.

So , I restarted my computer (didn't know what else to do)
Then, deleted my node_modules folder.
Then I ran npm install again, and it worked!

Thanks again for your reply! 

Cheers
