### ISSUE TITLE
HMR Not working with laravel-mix 2.0

### ISSUE THREAD

**Issue by LG0012** [JeffreyWay/laravel-mix#1521]
Hi everyone,

Just wanted to let u know, its seems like HMR is not working with laravel-mix version 2.0.
And after downgrade from 2.0 to 1.0, suddenly HMR started to work.

Screenshot: https://prnt.sc/iqc7kj

If you don't believe me, I can provide a video just in case to show that I'm right.

**Comment by zanematthew** [comment]
I may have a similar issue, after running `npm run hot`, I receive the following;

```
$ npm run hot

> @ hot /Users/zanekolnik/Documents/docker-nginx-php-mysql/web
> node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --watch-poll --config=node_modules/laravel-mix/setup/webpack.config.js
 DONE  Compiled successfully in 9245ms 
 WAIT  Compiling...
 DONE  Compiled successfully in 1465ms
```

Compiling is triggered by making relevant code changes, however, I never see URL still serves the same code, and I never receive the confirmation that HMR is connected in the console.

**Comment by ankurk91** [comment]
HMR works fine for me on Laravel Mix v2.1 , Mac OS, Node v9

**Comment by nkostadinov** [comment]
Same problem as here #1454

**Comment by isometriq** [comment]
Experiencing same problem...
The `mix-manifest.json` gets updated correctly and "hot" files are served correctly.
But I don't a connection nor any request to ..end result: page not updated with hot-update.

**Comment by MrSnoozles** [comment]
@isometroc Same problem here, unfortunately took me the last 4 hours to figure out I'm not doing anything wrong. The fix from @misenhower you linked worked perfectly. Thank you both so much for that.

@JeffreyWay Is it possible to include that fix in a future release? Do you need anything to reproduce the issue first?
