### ISSUE TITLE
TypeError: mix.extend is not a function

### ISSUE THREAD

**Issue by wolfika** [JeffreyWay/laravel-mix#1523]
- Laravel Mix Version: 2.0.0
- Node Version: 9.8.0
- NPM Version: 5.6.0
- OS: Windows 10 Pro, build 1709

### Description:
I'm trying to extend Laravel Mix's functionality [as per the docs says](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/extending-mix.md). Unfortunately, when I call `mix.extend()` in my `webpack.mix.js` file, I get a `TypeError` while running Webpack, saying that the `mix.extend()` function does not exist. Every other method of the `mix` object works, but not this one.

### Steps To Reproduce:

```javascript
// my webpack.mix.js
const mix = require('laravel-mix');

mix.extend('images', () => {
  // ...
});
```

Any ideas why this does not work? Not sure if it's me doing something wrong. Thanks!

**Comment by JeffreyWay** [comment]
The `mix.extend()` functionality hasn't been tagged yet.
