### ISSUE TITLE
Require modules not working at v2.1

### ISSUE THREAD

**Issue by dionysiosarvanitis** [JeffreyWay/laravel-mix#1524]
- Laravel Mix Version: 2.1.0
- Node Version:  9.2.0
- NPM Version:  5.6.0
- OS: Windows 10

### Description:

After upgrading to 2.1 it seems like Vue registered components are completely ignored outputing errors like "Property or method "xxx" is not defined on the instance but referenced during render".  Registration is done by requiring `.vue` files like below from within app.js

`Vue.component('login', require('./pages/Login.vue'))`

Login.vue
```js
<script>
export default {
    data() {
        return {
            model: {
                identity: '',
                password: '',
                remember: false,
            },
        };
    }
};
</script>
```

When registered inline it works 

```js
Vue.component('login', {
    data() {
        return {
            model: {
                identity: '',
                password: '',
                remember: false,
            },
        };
    }
})
```

Reverting to version 2.0 it works again.

**Comment by ankurk91** [comment]
Here is the workaround
```js
Vue.component('login', require('./pages/Login.vue').default)
```
Something is wrong in vue-loader configs.

**Comment by ruchern** [comment]
`v.2.0`
https://github.com/JeffreyWay/laravel-mix/blob/127ca94cdbe99f9ba21a05d4b2c0d53fc1bddc6a/package.json#L61

`v2.1`
https://github.com/JeffreyWay/laravel-mix/blob/dabc3454d8f5289b7b9a0330a22f2a976cd924b1/package.json#L61

There was a major update to `vue-loader`

**Comment by ankurk91** [comment]
@ruchern 
Any way to restore old behaviour ?
How to return `default` by default?

**Comment by ruchern** [comment]
https://github.com/vuejs/vue-loader/releases

I am looking through this releases to see what are the breaking changes.

**Comment by ankurk91** [comment]
I think we can not restore it
https://github.com/vuejs/vue-loader/blob/master/docs/en/options.md#esmodule

**Comment by ruchern** [comment]
I think OP got to try to try something like

```
import Foo from '@/components/Foo`

Vue.component('foo', Foo)

**Comment by ankurk91** [comment]
Laravel need to remove this old config then

https://github.com/JeffreyWay/laravel-mix/blob/master/src/config.js#L107

**Comment by ruchern** [comment]
And force everyone to go to ES6 modules.

**Comment by JeffreyWay** [comment]
Ugh, I can’t force a breaking change like that for this release. We’ll have to wait for a major release. 

Can someone submit a PR that changes the vue-loader requirement back to what it was before?

**Comment by ruchern** [comment]
@JeffreyWay I can submit a PR for that, but I will have to do it over the weekends where I have some spare time for myself.
