### ISSUE TITLE
Different postCss options for different sass file

### ISSUE THREAD

**Issue by FaridAghili** [JeffreyWay/laravel-mix#1528]
- Laravel Mix Version: 2.0.0
- Node Version (`node -v`): 8.9.3
- NPM Version (`npm -v`): 5.7.1
- OS: Windows 10 Pro x64

Here is my webpack.mix.js file:

> let mix = require('laravel-mix');
>
> mix.sass('resources/assets/sass/admin.scss', 'public/css')
>     .options({
>         postCss: [
>             require('postcss-rtl')()
>         ]
>     });
> 
> mix.sass('resources/assets/sass/app.scss', 'public/css');

 

I'm using postcss-rtl for the admin.scss and it works fine. The problem is, I don't want postcss-rtl to work on app.scss file, but couldn't find a way to limit the .options to admin.scss only.

How can it be done? Is it even possbile? If not, what do you suggest?

**Comment by FaridAghili** [comment]
@JeffreyWay 
Is this even possible?

**Comment by FaridAghili** [comment]
OK, I've managed to do this manually!
Run each group of assets with their specific options separately then edit `mix-manifest.json` at the end!
Not so productive, but works!

**Comment by RahulDey12** [comment]
How Can I do that ?
