### ISSUE TITLE
extractVueStyles create vue-styles.css

### ISSUE THREAD

**Issue by Pinegin** [JeffreyWay/laravel-mix#1529]
- Laravel Mix Version: 2.1.1 (`npm list --depth=0`)
- Node Version (`node -v`): v8.9.1
- NPM Version (`npm -v`): 5.7.1
- OS: macOS 10.13.3

### Description:
Embedded styles in .vue form a separate file and do not connect to the general style.

### Steps To Reproduce:

```
mix.options({extractVueStyles: true});
mix.js('sources/app.js', 'assets')
mix.less('sources/app.less', 'assets');
mix.setPublicPath('assets/');
mix.setResourceRoot('/assets/');
```

**Comment by mike-grinspan** [comment]
Same problem here. Seems this was changes as part of #1467, but I preferred it when the styles were merged with my main CSS. Downgraded back to 2.0.0 until there's a resolution.

**Comment by JeffreyWay** [comment]
Yeah, this shouldn't happen. It's a breaking change. I'll review it today. Thanks.
