### ISSUE TITLE
Guil-Util deprecated warning, blocking my app deploy

### ISSUE THREAD

**Issue by skatetdieu** [JeffreyWay/laravel-mix#1530]
- Laravel Mix Version: 2.1.0
- Node Version (`node -v`): 6.10.3
- NPM Version (`npm -v`): 3.10.10
- OS: 3.10.0-123.20.1.e17centos.plus.x86_64 GNU/Linux

### Description:
A dependency called [Gulp-Util](https://github.com/gulpjs/gulp-util) has been deprecated. Here is the dependency tree below.

![image](https://user-images.githubusercontent.com/1899636/37489630-a8b83250-286e-11e8-9003-0cc046c913b2.png)

This is causing my app to not be able to deploy. Is there any way to update dependencies to no longer require gulp-util?

There's even a Medium post about fixing this. https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

### Steps To Reproduce:

Ran npm install. Got this warning:
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by JeffreyWay** [comment]
There's nothing we can do on the laravel-mix side right now. It has to be addressed much lower in the chain.
