### ISSUE TITLE
laravel mix + rekit IDE ( react redux studio )

### ISSUE THREAD

**Issue by jihadismail8** [JeffreyWay/laravel-mix#1532]
i am trying to make a boilerplate which uses laravel as backend and react redux on frontend to build  SPA , rekit studio is cool idea ,but iam trying to integrate them togther , in such a way that blade will serve the first page which contain the compiled app.js file from rekit studio , anybody can help me with that ? or guide me at least ?  link to rekit : http://rekit.js.org/

**Comment by smahdis** [comment]
@jihadismail8

Any update to this?
