### ISSUE TITLE
Cannot deploy my app using laravel-mix since 3 days due to exiting code on pngquant lib

### ISSUE THREAD

**Issue by wawanopoulos** [JeffreyWay/laravel-mix#1539]
- Laravel Mix Version: 2.1.1
- Node Version (`node -v`): 9.6.1
- NPM Version (`npm -v`): 5.6.0
- OS: Debian

Since 3 days, it's impossible for me to use Laravel Mix to deploy my application. The problem is that Laravel Mix requires pngquant library and this library has been updated 3 days ago by adding a line to exit the process when an error occurs! It means that all next npm packages cannot be installed. I don't know if laravel-mix can modify something but the problem is very boring.

Linked to open issue: https://github.com/imagemin/pngquant-bin/issues/78

Here is the stack trace that occurs:

```
pngquant-bin@4.0.0 postinstall /var/www/palm/20180315202846/node_modules/pngquant-bin

node lib/install.js

⚠ The /var/www/pp/20180315202846/node_modules/pngquant-bin/vendor/pngquant binary doesn't seem to work correctly
⚠ pngquant pre-build test failed
ℹ compiling from source
✔ pngquant pre-build test passed successfully
✖ RequestError: pngquant failed to build, make sure that libpng-dev is installed
at ClientRequest.req.once.err (/var/www/pp/20180315202846/node_modules/pngquant-bin/node_modules/got/index.js:111:21)
at Object.onceWrapper (events.js:272:13)
at ClientRequest.emit (events.js:180:13)
at ClientRequest.onConnect (/var/www/pp/20180315202846/node_modules/pngquant-bin/node_modules/tunnel-agent/index.js:168:23)
at Object.onceWrapper (events.js:272:13)
at ClientRequest.emit (events.js:180:13)
at Socket.socketOnData (_http_client.js:476:11)
at Socket.emit (events.js:180:13)
at addChunk (_stream_readable.js:269:12)
at readableAddChunk (_stream_readable.js:256:11)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: node lib/install.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
^C
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2018-03-15T20_19_09_479Z-debug.log
```

**Comment by velu76** [comment]
I had similar issues, the workaround has been as what I explained in my comment:

I got similiar error for Laravel in Ubuntu 17.10. I used @sory19 method as below:
I had the same issue but it is resolved by first installing libpng-dev
Need to follow the following steps:
`sudo apt-get install libpng-dev `and then run `npm install -g pngquant-bin`

Still had same error. This is what I did.

Removed the "node_modules" folder: `sudo rm -rf node_modules`
Re-ran `npm install`
And it worked after that.

**Comment by velu76** [comment]
@wawanopoulos 
From what I have read from here: 
https://github.com/imagemin/pngquant-bin/issues/78

It seems to be an issue with the OS that you are using. So far Ubuntu seems to be fine. Only a few other Linux distros seem to have trouble. This might not be a laravel-mix issue. 

I will let Jeffer Way to confirm with you on this.

**Comment by brickgale** [comment]
Thanks man @velu76

**Comment by softwaredeveloperca** [comment]
For those having problems with Ubuntu.  Try:
wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb \
  && sudo dpkg -i /tmp/libpng12.deb \
  && rm /tmp/libpng12.deb

**Comment by SodomousPrime** [comment]
Thank you @softwaredeveloperca I was having trouble in Ubuntu and your instructions have resolved the issues i was having after the NPM update.

**Comment by ngoctp** [comment]
The issue comes from new release of `imagemin-pngquant` v5.1 requires `pngquant-bin@4.0.0`
The quick fix is to downgrade `imagemin-pngquant` to 5.0.* which requires `pngquant-bin@3.1.1`

Run this command and commit your package.json
`npm install --save-exact imagemin-pngquant@5.0.*`

**Comment by wmtoscar** [comment]
thank you @softwaredeveloperca this is what I was looking for like hell! @wawanopoulos try his solution it will help you to fix it!

**Comment by btica-ro** [comment]
Same issue on alpine. Fixed installing:
```
apk add --update \
           bash \ #needs bash.
           libpng-dev \
           gcc \
           g++ \
           make \
```

**Comment by allangrds** [comment]
Thanks a lot @btica-ro!

**Comment by chasebolt** [comment]
@wawanopoulos i believe your issue, from following the stack trace, stems from a network call the installer is doing. there are 2 PRs open to try and address this issue.

https://github.com/imagemin/pngquant-bin/pull/80
https://github.com/imagemin/pngquant-bin/pull/83

**Comment by rico-ocepek** [comment]
@btica-ro I think you are my new favourite person - thanks (y)

**Comment by SuperGizmo** [comment]
Thank you @softwaredeveloperca This fix worked on Debian 9

**Comment by harunthuo** [comment]
@ngoctp downgrade tweak did it for me. life saver!

**Comment by fgilio** [comment]
Thanks @softwaredeveloperca! Worked perfectly in Ubuntu 18

**Comment by zhegwood** [comment]
Ubuntu 18.04... Had same problem.  "Fixed" issue by piecing together some posts from above @softwaredeveloperca and @ngoctp :

1. run wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb && sudo dpkg -i /tmp/libpng12.deb && rm /tmp/libpng12.deb

2. run npm install --save-exact imagemin-pngquant@5.0.* in your web root.

3. run npm install in your web root.

**Comment by z-flash** [comment]
So many attempts but still getting same error in Windows 10
any idea?

**Comment by ry167** [comment]
I had this error in WSL and fixed it by running `sudo apt-get install gcc g++ make` - don't know exactly which one fixed it but it compiled fine afterwards...

Unfortunately installing `pngquant` itself at the system level didn't work, which is kind of insane...
