### ISSUE TITLE
version function wont work on combine

### ISSUE THREAD

**Issue by yeknava** [JeffreyWay/laravel-mix#154]
after running this code, webpack wont make any vendors.css file.
```
mix.combine([
    'resources/assets/css/bootstrap.min.css',
    'resources/assets/css/font-awesome.min.css',
    'resources/assets/css/awesome-bootstrap-checkbox.css',
], 'public/css/vendors.css').version();
mix.js([
    'resources/assets/js/jquery-2.1.1.min.js',
    'resources/assets/js/bootstrap.min.js',
], 'public/js/vendors.js').version();
```
also mix-manifest.json only contains vendor.js.
```
{
  "/js/vendors.js": "/js/vendors.b9c19de9038af2fc797b.js"
}
```

**Comment by yeknava** [comment]
not sure if i should make a new issue or not but "npm run watch" won't watch any of combine method files.

**Comment by adriaanzon** [comment]
See #53

**Comment by yeknava** [comment]
@adriaanzon there is no other way to do that ? or i must run "npm run dev" after each change in my css files ?

**Comment by adriaanzon** [comment]
You can use `mix.sass()` and import the css files in your sass entry point.
