### ISSUE TITLE
Load sass files from js

### ISSUE THREAD

**Issue by RutgervdBroeck** [JeffreyWay/laravel-mix#1545]
- Laravel Mix Version: 2.1.8
- Node Version: 9.5.0
- NPM Version: 5.6.0
- OS: Mac OS High Sierra

### Description:

In my Laravel mix setup, i'm using the `mix.ts` to render React js components. Inside those components i use my style imports like this: `import "./style.scss";`

This works fine, except for when i want to have those styles in a seperate rendered in a seperate css file, and i don't want the styles to be inserted as style tags. 

I thought i could add my own ExtractTextPlugin implementation like this, when i, for example would like to ship for production eventually.

```
mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: ['css-loader', 'sass-loader']
                })
            }
        ]
    },
    plugins: [
        new ExtractTextPlugin('./public/assets/css/app.css'),
    ]
});
```

From the style.scss i get the following error: 

```
 Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi"
```

Anyone who knows i could achieve this?

**Comment by leotankilevich** [comment]
add `exclude: []` to scss rule
