### ISSUE TITLE
React preset outputs undefined.js

### ISSUE THREAD

**Issue by zlokomatic** [JeffreyWay/laravel-mix#1547]
Hi,

i created the issue at https://github.com/laravel/framework/issues/23617 first. So now also creating it here.

- Laravel Mix Version: 2.1.8 (`npm list --depth=0`)
- Node Version (`node -v`): 8.10.0
- NPM Version (`npm -v`): 5.7.1
- OS: ubuntu 16.04 / vagrant -> homestead

### Description:
After creating a new project and switching to the react preset, webpack outputs a file "undefined.js" along the app.js and app.css

```
Asset     Size  Chunks                    Chunk Names
  /js/app.js  1.69 MB       0  [emitted]  [big]  /js/app
undefined.js  2.64 kB       1  [emitted]         undefined
/css/app.css   187 kB    1, 1  [emitted]         undefined, undefined
```

### Steps To Reproduce:
```
composer create-project --prefer-dist laravel/laravel blog
cd blog
php artisan preset react
npm install && npm run dev

**Comment by JeffreyWay** [comment]
Thanks - fixed.
