### ISSUE TITLE
Source Maps do not work inline or linked with mix.scripts or mix.babel

### ISSUE THREAD

**Issue by adampatterson** [JeffreyWay/laravel-mix#1548]
- Laravel Mix Version: 2.1.9
- Node Version v9.2.0
- NPM Version 5.7.1
- OS: OSX 10.13.3

### Description:
I think source maps is the only thing that I can never get to work 100%

Before I posted this I looked back over as many relevant issues as I could find, none had solutions that worked.  I did a fresh NPM install. No luck.

I have, and always have been using `mix.webpackConfig({devtool: 'inline-source-map'})` I recently switched to `mix.webpackConfig({devtool: 'source-map'})` in an attempt to see if that would help.

### Steps To Reproduce:

* with only .sourceMaps()
  * scripts - No source map
  * babel - No source map
  * js - No source map
  * sass - No source map

* mix.webpackConfig({devtool: 'inline-source-map'})
  * scripts - No source map
  * babel - No source map
  * js - Inline source map
  * sass - Inline source map

* mix.webpackConfig({devtool: 'source-map'})
  * scripts - No source map file
  * babel - No source map file
  * js - created source map  file
  * sass - created source map file

Removing `.sourceMaps()` with the above mix.webpackConfig cause inline and the linked .map files to be created but they don't have any content.

Am I missing something?

**Comment by dakira** [comment]
With a blank installation of Laravel I have the exact same issue with the same results as you. Additionally the maps generated setting `source-map` don't have any effect in devtools.

**Comment by adampatterson** [comment]
@dakira I just noticed that. without `mix.sourceMaps` they are created but empty. With it, it seems to still work. but not for script or babel.

**Comment by greatwitenorth** [comment]
I'm still seeing the exact same issue, is there any progress on this?

**Comment by aariacarterweir** [comment]
Just going to go ahead and necro this, sourcemap generation still just flat out doesn't work for the `scripts()` and `styles()` methods on `mix`.
