### ISSUE TITLE
HMR stays on even if we stop the webpack watcher

### ISSUE THREAD

**Issue by jpmurray** [JeffreyWay/laravel-mix#155]
So if I run `npm run hmr` in a 5.4 install, there is that `hot` file that is created in the public folder so that the `mix()` helper in Laravel knows to serve file from the webpack server that is running. Good.

If you then need to exit the watcher, using `ctrl+c`, the watcher stops, but the `/public/hot` file stays there, and the mix helper still tried to server the file for HRM, we need to do delete the file manually.

Unless I missed something obvious, isn't it weird that we need to go delete the file ourselves?

**Comment by JeffreyWay** [comment]
It will be deleted as you soon as you run Webpack again.

**Comment by jpmurray** [comment]
Good to know, you might want to add a note for this in the docs maybe? I mean, come to think of it, it's kind of obvious it will do it, but I don't necessarily run webpack right after I'm done with HMR, so it might be confusing (for example, coming back to working with a given project, loading the local site but didn't ran webpack again, so all _seems_ broken).

Or it's just me who gets confused easily (probably that's just it), then just ignore me 😊
