### ISSUE TITLE
`uglifyOptions` cannot work when used `babel` or `minify`

### ISSUE THREAD

**Issue by fly-studio** [JeffreyWay/laravel-mix#1551]
- Laravel Mix Version: 2.1.9 (`npm list --depth=0`)
- Node Version (`node -v`): 7.0.0
- NPM Version (`npm -v`): 3.10.8
- OS: Windows 10 1709 Dec

### Description:

Code:

```
mix.options({
	uglify: {uglifyOptions: {output: {ascii_only: true}}}
});
mix.babel('static/js/xx.js', 'static/js/xx.min.js').sourceMaps();
```

When I used `mix.js(...)`, `ascii_only`, it could work, and the unicode chars will be replaced to "\uXX".
But I used `mix.babel(...), mix.minify(...)`,  `ascii_only`, it could not work.

`ascii_only` is an obvious error when I testing. 

### Next
I saw the code in `laravel-mix/src/File.js`, And found the function of 'minify':

```
this.write(uglify.minify(this.path(), Config.uglify).code);
```
The 'ouput' config of 'Config.uglify' is invalid in this place.

**Comment by JeffreyWay** [comment]
Can you be more specific about:

> The 'ouput' config of 'Config.uglify' is invalid in this place.

What specifically is invalid? Seems like that lines up with the uglify2 config.

**Comment by fly-studio** [comment]
@JeffreyWay Sorry for my English, I'm very Sorry.

`mix.minify('js/xxxx.js', 'js/xxxx.min.js').sourceMaps();`

I Mean: 

If I modify 
```
this.write(uglify.minify(this.path(), Config.uglify).code);
```
 to 
```
let extend = require('lodash').extend;
this.write(uglify.minify(this.path(), extend(Config.uglify, {output: {ascii_only: true}})).code);
```

It works well, And I try to run  this code in a new js file  `node new_file.js`
```
let uglify = require('uglify-js');
console.log(uglify.minify('var str = "中文字符";', {output: {ascii_only: true}}).code); 
```
It prints `var str="\u4e2d\u6587\u5b57\u7b26";`.

As you know, `Config.uglify` is `{uglifyOptions: {compress: {....}, ouput: {...}}}` 
and `ouput` is in the `Config.uglify.uglifyOptions`, 
https://github.com/webpack-contrib/uglifyjs-webpack-plugin#uglifyoptions

But `uglify.minify` parameter#2 need the object like `{output: {xxx}}`,  not  `{uglifyOptions: {ouput: {xxxxx}}}`, It maybe lost output's config.

Thank you ! 👍
