### ISSUE TITLE
[2.1.11] After Upgrade to 2.1.11 (PurgeCss+Tailwind ) no longer works

### ISSUE THREAD

**Issue by devcircus** [JeffreyWay/laravel-mix#1554]
- Laravel Mix Version: 2.1.11
- Node Version: 8.9.1 
- NPM Version: 5.6.1
- OS: Windows 10

### Description:
After updating to 2.1.11 from 2.0, PurgeCss no longer works. I was using the exact setup shown [here](https://tailwindcss.com/docs/controlling-file-size), on the Tailwindcss site. When I noticed it no longer worked, I tried using the [Spatie package](https://github.com/spatie/laravel-mix-purgecss), which didn't work and also has [an issue](https://github.com/spatie/laravel-mix-purgecss/issues/22) posted on their repo.

Worth noting also, I tried extracting this purgecss functionality to a plugin using the new extension system and got the same results.

### Before and After upgrade to 2.1.11:
Before, my resulting css file was ~35kb.
After the upgrade, the file is ~240kb.

### Steps To Reproduce:
Use the [example](https://tailwindcss.com/docs/controlling-file-size) from Tailwind's site:
```js
// Based on https://medium.com/@AndrewDelPrete/using-purifycss-to-remove-unused-tailwind-css-classes-173b3ee8ee01

let mix = require("laravel-mix");
let tailwindcss = require("tailwindcss");
let glob = require("glob-all");
let PurgecssPlugin = require("purgecss-webpack-plugin");

// Custom PurgeCSS extractor for Tailwind that allows special characters in
// class names.
// 
// https://github.com/FullHuman/purgecss#extractor
class TailwindExtractor {
  static extract(content) {
    return content.match(/[A-z0-9-:\/]+/g) || [];
  }
}

mix.postCss("./src/styles.css", "public/css", [tailwindcss("./tailwind.js")]);

// Only run PurgeCSS during production builds for faster development builds
// and so you still have the full set of utilities available during
// development.
if (mix.inProduction()) {
  mix.webpackConfig({
    plugins: [
      new PurgecssPlugin({

        // Specify the locations of any files you want to scan for class names.
        paths: glob.sync([
          path.join(__dirname, "resources/views/**/*.blade.php"),
          path.join(__dirname, "resources/assets/js/**/*.vue")
        ]),
        extractors: [
          {
            extractor: TailwindExtractor,

            // Specify the file extensions to include when scanning for
            // class names.
            extensions: ["html", "js", "php", "vue"]
          }
        ]
      })
    ]
  });
}
```

**Comment by devcircus** [comment]
Looks like maybe due to some underlying changes in some dependencies. Maybe just need to get Adam to update the example in the tailwind docs. Will close for now.

**Comment by tpraxl** [comment]
See https://github.com/spatie/laravel-mix-purgecss/pull/23

**Comment by tpraxl** [comment]
There's a new release for https://github.com/spatie/laravel-mix-purgecss

Didn't test it yet, but I believe it works now.

It comes as a laravel-mix plugin now:

```
let mix = require('laravel-mix');
require('laravel-mix-purgecss');

// ...

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .purgeCss();
```

**Comment by adamwathan** [comment]
Does anyone know what changes are needed to the Tailwind docs for this change? I can't for the life of me get it working anymore without using the Spatie package (which is awesome, but I'd prefer our docs to show how to set it up in a more vanilla way.)

**Comment by devcircus** [comment]
I gave up and went the spatie route a while back. May dig back in this afternoon and look at it with fresh eyes

**Comment by JeffreyWay** [comment]
It's fixed and patched now.
