### ISSUE TITLE
Laravel Mix generated hot file (HMR) should use --host and --port argument when provided

### ISSUE THREAD

**Issue by bunnypro** [JeffreyWay/laravel-mix#1560]
- Laravel Mix Version: 2.1.11
- Node Version : 8.10
- Yarn Version : 1.5.1
- OS: KDE Neon (Ubuntu 16.04)

### Description:
Laravel mix generated `hot` file should use --host and --port argument when provided because webpack-dev-server also accept those arguments.

**Comment by ankurk91** [comment]
This feature was there in v2.0
https://github.com/JeffreyWay/laravel-mix/pull/1246

**Comment by bunnypro** [comment]
that feature only support for configuring the `hmrOptions.host` and `hmrOptions.port` in the mix file but not accept `--host` and `--port` arguments. (e.g. `webpack-dev-server --hot --host=0.0.0.0 --port=8089`)

webpack-dev-server is accept `--host` and `--port` argument and webpack-dev-server will server to those specified argument but the generated hot file is ignoring those arguments.

**Comment by sifex** [comment]
So just accepting an overwrite for `hmrOptions`? Should be fairly straight forward.
