### ISSUE TITLE
Docs: create mix() function

### ISSUE THREAD

**Issue by steveheinsch** [JeffreyWay/laravel-mix#1562]
The docs show how to use mix as standalone, but don't mention the `mix()` php function, or have an example of the function, which could be used as standalone for cache busting/versioning of the assets using the mix-manifest.json file.

I think the mix() function should be included in the docs, or as a standalone file. I found one on sitepoint here, which is generic and not tied to laravel: https://www.sitepoint.com/use-laravel-mix-non-laravel-projects/

**Comment by JeffreyWay** [comment]
mix() is a Laravel helper function. It does not exist as part of this project.

**Comment by steveheinsch** [comment]
I understand, but you can't do versioning without it, and it wouldn't be difficult to add the generic one I linked to in the docs so people could use it if they wished. I just thought it would be more useful for people wanting to use all of the functionality outside of laravel.
