### ISSUE TITLE
PostCSS with pure CSS doesn't make any code transformation

### ISSUE THREAD

**Issue by allangrds** [JeffreyWay/laravel-mix#1564]
- Laravel Mix Version: 2.0
- Node Version (`node -v`): 9.8.0
- NPM Version (`npm -v`): 5.6.0
- OS: Ubuntu 17.10

### Description:
I'm trying to use PostCss writing pure CSS, but the compiled CSS doesn't have any transformation. Using PostCSS with Sass works.

### Steps To Reproduce:
**webpack.mix.js**
```
const mix = require('laravel-mix');

mix.styles('resources/assets/css/index.css', 'public/css/app.css')
  .options({
    postCss: [
      require('postcss-cssnext')()
    ],
  });
```

**index.css**
```
:root {
  --mainColor: red;
}

html {
  background-color: var(--mainColor);
  border-radius: 5px;
}
```

**Comment by devcircus** [comment]
See #617.

**Comment by devcircus** [comment]
Also looking over  #1012 may help.

**Comment by allangrds** [comment]
Nice @devcircus. I've read the PR and used the following code:
```
mix.postCss('resources/assets/css/index.css', 'public/css/app.css')
  .options({
    postCss: [
      require('postcss-cssnext')() //eslint-disable-line
    ],
  })
  .version();
```

It works.
