### ISSUE TITLE
 Missing class properties transform.

### ISSUE THREAD

**Issue by iamkallolpratim** [JeffreyWay/laravel-mix#1566]
arrow function did not work with laravel mix. here's the error

<Syntax Error: Missing class properties transform.

   7 |
   8 |
 9 |     handleSubmit = (e) => {
     |     ^
  10 |         console.log('hello');
  11 |     };
  12 |>

**Comment by ankurk91** [comment]
Community can not help you unless you fill out ISSUE_TEMPLATE.
