### ISSUE TITLE
@import inside the scss file located in node_modules folder not working

### ISSUE THREAD

**Issue by ishraftaifur** [JeffreyWay/laravel-mix#1572]
I am currently working with [material.io](https://material.io/components/web/docs/getting-started/) in Laravel Mix and with importing any components of material.io it generates error that the files that are being imported inside the scss file in node_module can not be found. I have found the solution for basic webpack configuration here - 

`
{
  loader: 'sass-loader',
  options: {
    importer: function(url, prev) {
      if(url.indexOf('@material') === 0) {
        var filePath = url.split('@material')[1];
        var nodeModulePath = './node_modules/@material/${filePath}';
        return { file: require('path').resolve(nodeModulePath) };
      }
      return { file: url };
    }
  }
}
`

but how can I configure this in laravel mix?

**Comment by robbyrice** [comment]
To be able to use the material.io components in your project, your scss calls should look like this. The first argument should be to your main sass file.  The second argument should be the folder where you want the compiled css file to go. Hope this helps.
```
mix.sass('path/to/your/main/sass/file.scss', 'path/to/your/output', {
  includePaths: ['node_modules']
});
```
