### ISSUE TITLE
How to create custom directory shortcut?

### ISSUE THREAD

**Issue by jericopulvera** [JeffreyWay/laravel-mix#1582]
I have a project and want to create a custom shortcut.

For example, I have a chat component on this path resources/assets/js/components

and I want to import chat component from components directory from Vue router directory

resources/assets/js/router/index.js

```
// Instead of this
import Chat from '../components/Chat'

// I want it to be like this
import Chat from '@components/Chat'
```
In summary, I want

'@components' to be mapped to 'resources/assets/js/components'

**Comment by jericopulvera** [comment]
Found the answer to my question here #1219 
turns out it's a Webpack thing. 
Just add this in your webpack.mix.js
 ```
mix.webpackConfig({
    resolve: {
        alias: {
            "@components": path.resolve(
                __dirname,
                "resources/assets/js/components"
            )
        }
    }
});
```

**Comment by SimonEast** [comment]
Related to this, I've inherited a project that has imports like this...

```
import Xxx from '@Xxx';
import Xxx from '@Yyy';
```

Ideally I want anything starting with an `@` to be loaded from a specific directory. Unfortunately the configuration above does NOT work with this - it would only work if the import statements were `@/Xxx` whereby I could then create an alias for `@`. I can't seem to find a way to make aliases work in the way I need. Maybe it's a limitation of webpack. 😏
