### ISSUE TITLE
Can't extract scoped npm package?

### ISSUE THREAD

**Issue by benface** [JeffreyWay/laravel-mix#1586]
- Laravel Mix Version: 2.1.11
- Node Version: 9.11.1
- NPM Version: 5.8.0
- OS: macOS High Sierra (10.13.4)

### Description:

It seems trying to `mix.extract()` a `@scoped/npm-package` doesn't work (results in `Module not found: Error: Can't resolve`)

### Steps To Reproduce:

1. `npm install @mobiscroll/javascript-lite`
2. Write this in `webpack.mix.js`:
```
mix.setPublicPath('public')
  .js([
    'src/js/app.js',
  ], 'public/js/app.js')
  .extract([
    '@mobiscroll/javascript-lite',
  ], 'public/js/vendor.js');
```
3. `npm run watch`

### Expected result

No error.

### Actual result

```
 ERROR  Failed to compile with 1 errors                                                 3:47:29 p.m.

This dependency was not found:

* @mobiscroll/javascript-lite in multi @mobiscroll/javascript-lite

To install it, you can run: npm install --save @mobiscroll/javascript-lite
          Asset       Size  Chunks             Chunk Names
     /js/app.js     2.3 kB       0  [emitted]  /js/app
  /js/vendor.js  217 bytes       1  [emitted]  /js/vendor
/js/manifest.js    3.84 kB       2  [emitted]  /js/manifest

ERROR in multi @mobiscroll/javascript-lite
Module not found: Error: Can't resolve '@mobiscroll/javascript-lite' in '/Users/benface/Projects/project'
 @ multi @mobiscroll/javascript-lite
```

Am I doing anything wrong? Thank you for your time.

**Comment by SaurabhKharivale** [comment]
It looks like you haven't installed the dependency as the output suggest.
To install it run `npm install --save @mobiscroll/javascript-lite`

I use mix to extract scoped packages and it works just fine.

**Comment by benface** [comment]
@SaurabhKharivale Thank you for replying. Can you give me an example of a scoped package that works fine with `extract()` so I can test it in my project on my machine? I confirm that I did install the package (it is in `package.json` and at `node_modules/@mobiscroll/javascript-lite`) and am still getting this error. I also tried extracting another scoped package, `@angular/core`, just in case the issue was with mobiscroll, and I'm getting another but similar error (`Can't resolve 'rxjs/Observable'`). Maybe not all dependencies can be extracted?

**Comment by SaurabhKharivale** [comment]
I use these packages and they work fine for me when extracting
`@fortawesome/fontawesome`
`@fortawesome/fontawesome-free-solid`

**Comment by benface** [comment]
Thank you! It does work with these. So is there a problem with `@mobiscroll/javascript-lite` (and `@angular/core` for all it's worth) or is it a bug in Mix?

**Comment by petrorington** [comment]
@benface Hello, were you able to fix the issue by any chance?

**Comment by benface** [comment]
@petrorington No, I gave up. I still don’t know if it’s an issue with Mix or with some specific packages.

**Comment by petrorington** [comment]
@benface I see. I have got a similar issue with ckeditor.

Anyway thank you for your note.
