### ISSUE TITLE
Multiple CSS chunks since 2.x

### ISSUE THREAD

**Issue by aphofstede** [JeffreyWay/laravel-mix#1593]
Not sure if this is an issue, since the output is working, but I thought I'd report it / get some clarification.

When I switch to 2.x, the chunks emitted for the CSS build now reports two entries (`0, 0` / `/javascript/app, /javascript/app`), this used to be only one. Is there something strange going on there?

Another issue is that the chunk names are not as expected (I would expect "/style/app")

Config for CSS is a pretty typical TailwindCSS set-up with PurgeCSS stuck on the end of the pipeline.

```
                  Asset       Size  Chunks                    Chunk Names
     /javascript/app.js     322 kB       0  [emitted]  [big]  /javascript/app
  /javascript/vendor.js     319 kB       1  [emitted]  [big]  /javascript/vendor
/javascript/manifest.js  799 bytes       2  [emitted]         /javascript/manifest
          style/app.css    25.5 kB    0, 0  [emitted]         /javascript/app, /javascript/app
```

**Comment by aphofstede** [comment]
😔

**Comment by JeffreyWay** [comment]
I need reproducible steps, as I've never seen anything like this.
