### ISSUE TITLE
Invalid configuration object

### ISSUE THREAD

**Issue by tillkruss** [JeffreyWay/laravel-mix#16]
Using master, this:
```
mix.js('resources/assets/js/web.js', 'public/js')
   .js('resources/assets/js/app.js', 'public/js');
```

Results in:

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry['app'] should be one of these:
   string | [string]
   The entry point for one output file.
 - configuration.entry should be one of these:
   object { <key>: string | [string] } | string | [string]
   The entry point(s) of the compilation.
```

Is there something I'm doing wrong? Totally new to Webpack.

**Comment by QWp6t** [comment]
```js
mix.js('resources/assets/js/web.js', 'public/js/web.js')
   .js('resources/assets/js/app.js', 'public/js/app.js');
```

OR

```js
mix.js([
  'resources/assets/js/web.js',
  'resources/assets/js/app.js'
], 'dist/bundle.js');
```

sauce: https://github.com/JeffreyWay/laravel-mix/issues/2#issuecomment-269259741

**Comment by tillkruss** [comment]
Actually all 3 fails for me:

```
mix.js('resources/assets/js/web.js', 'public/js')
   .js('resources/assets/js/app.js', 'public/js');

mix.js('resources/assets/js/web.js', 'public/js/web.js');
   .js('resources/assets/js/app.js', 'public/js/app.js');

mix.js('resources/assets/js/web.js', 'public/js/web.js');
```

**Comment by JeffreyWay** [comment]
@tillkruss - Have you updated your webpack.config.js file to the latest version? I'd bet that's the issue.

**Comment by tillkruss** [comment]
@JeffreyWay yes, that did the trick. Thanks a lot!

**Comment by alenabdula** [comment]
I'm getting following with fresh install.

> Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema. - configuration.output.path: The provided value "public" is not an absolute path!

__Steps to reproduce__

1. `laravel new example`
2. `yarn`
3. `npm run watch`

Laravel Installer 1.3.3 & npm 4.4.1

**Comment by JeffreyWay** [comment]
@alenabdula This was fixed last night. Update Mix.

**Comment by alenabdula** [comment]
@JeffreyWay thanks. Great work as always!

**Comment by Inkmonkey** [comment]
@JeffreyWay Thanks for the fix.

Just in case someone else is having trouble with this, the error message also comes in this flavour and is fixed by this update of laravel-mix.

`Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.filename: A relative path is expected. However the provided value "/js/[name].js" is an absolute path!
 - configuration.output.path: The provided value "public" is not an absolute path!`

**Comment by jasonspick** [comment]
`run npm uninstall laravel-mix && npm install --save laravel-mix`

I had an issue where it wouldn't just update.

**Comment by ruchern** [comment]
@jasonspick Try installing with `--save-dev` flags as `Laravel Mix` is installed under `devDependencies` in your `package.json`

**Comment by milad777v2** [comment]
update laravel mix to version 6
