### ISSUE TITLE
Misleading warning from resolve-url-loader

### ISSUE THREAD

**Issue by dharkness** [JeffreyWay/laravel-mix#1602]
- Laravel Mix Version: 2.0.0
- Node Version (`node -v`): 9.11.1
- NPM Version (`npm -v`): 5.8.0
- OS: Ubuntu 17.04 x64

### Description:

Running `yarn watch` works but displays a perplexing warning.

```
WARNING  Compiled with 1 warnings                                      16:31:59
 warning  in ./resources/assets/sass/app.scss
(Emitted value instead of an instance of Error)   resolve-url-loader cannot operate: CSS error
  /home/david/project/resources/assets/sass/app.scss:352:3: missing '}'
  at error (/home/david/project/node_modules/css/lib/parse/index.js:62:15)

@ ./resources/assets/sass/app.scss 4:14-266
```

We have three rules that reference a URL:

```
@import ($brand-font-url);    // "https://fonts.googleapis.com/css?family=Cairo"
background: url(/images/logo.png) no-repeat;
background: url(/images/newsletter.png) no-repeat;
```

The font exists, and both images are located under `/public/images`.

Why does Mix complain about a missing `}`?

### Work-Around:

Setting `processCssUrls` to `false` removes the warning, but a) all our URLs are absolute, and b) we don't need Mix to copy images. However, the message about a missing `}` is misleading as each individual SASS file is syntactically correct, and the final build works.

### Weird:

`app.scss` consists of four `@import` lines, many of which import other files. Removing line 4 (the one that Mix says is in error) does not change the output. I assume it's showing the *resulting* line 4 after importing all the files into one giant file. If so, saying the *actual* file and line number where the error occurs would be much more helpful.

**Comment by devcircus** [comment]
That doesn't look like a warning that mix is throwing. Likely from the underlying loader/webpack
