### ISSUE TITLE
How do you guys use the versioner when using Mix outside of Laravel?

### ISSUE THREAD

**Issue by aligajani** [JeffreyWay/laravel-mix#1604]
- Laravel Mix Version: #.#.# (`npm list --depth=0`)
- Node Version (`node -v`): 
- NPM Version (`npm -v`): 
- OS:

**Comment by ruchern** [comment]
Duplicate of #1605

**Comment by devcircus** [comment]
Just check out how the Laravel framework handles it and build out a method to do the same.

Really you just need to read the manifest file and extract the info you need.

**Comment by aligajani** [comment]
I did check that out, but is there a webpack plugin that does search and replace on HTML files?

**Comment by aligajani** [comment]
Thanks @lukepolo
