### ISSUE TITLE
npm install error laravel 5.6

### ISSUE THREAD

**Issue by webciter** [JeffreyWay/laravel-mix#1611]
operating system ubuntu 17.10

node -v
output: v8.11.1

npm -v
output: 5.8.0

sudo apt-get install libpng-dev
output:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpng-dev is already the newest version (1.6.34-1).
0 to upgrade, 0 to newly install, 0 to remove and 70 not to upgrade.

output from npm install

npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

> node-sass@4.8.3 install /home/administrator/Documents/laravel/basicAdministration/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.3/linux-x64-57_binding.node
Download complete  ] - :
Binary saved to /home/administrator/Documents/laravel/basicAdministration/node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /home/administrator/.npm/node-sass/4.8.3/linux-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /home/administrator/Documents/laravel/basicAdministration/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> node-sass@4.8.3 postinstall /home/administrator/Documents/laravel/basicAdministration/node_modules/node-sass
> node scripts/build.js

Binary found at /home/administrator/Documents/laravel/basicAdministration/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine

> gifsicle@3.0.4 postinstall /home/administrator/Documents/laravel/basicAdministration/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> mozjpeg@5.0.0 postinstall /home/administrator/Documents/laravel/basicAdministration/node_modules/mozjpeg
> node lib/install.js

  ✔ mozjpeg pre-build test passed successfully

> optipng-bin@3.1.4 postinstall /home/administrator/Documents/laravel/basicAdministration/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> pngquant-bin@4.0.0 postinstall /home/administrator/Documents/laravel/basicAdministration/node_modules/pngquant-bin
> node lib/install.js

  ⚠ The `/home/administrator/Documents/laravel/basicAdministration/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/home/administrator/Documents/laravel/basicAdministration/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/administrator/.npm/_logs/2018-04-20T08_27_55_321Z-debug.log

**Comment by artemsky** [comment]
https://github.com/imagemin/mozjpeg-bin/issues/18

**Comment by webciter** [comment]
finally got it to install, think it was all the compiling software, gcc, make etc

**Comment by alexqhj** [comment]
@webciter if you no longer have any issues, perhaps close this so the maintainers save some time? :)

**Comment by Intelioum** [comment]
@webciter How did you fix this?
I have exact same issue

**Comment by daosonit** [comment]
I also have problems like you? and i try in MAC operating system and it working.

**Comment by robindirksen1** [comment]
@zizu21105 thanks!! This fixed it for me on CentOS 7!

**Comment by padure** [comment]
https://github.com/standard/standard/issues/1078

**Comment by PouyaAklion** [comment]
for windows, users just use ` npm cache clean`  command and after that `npm install -g gulp-cli`
this work for me

**Comment by andrewrollason** [comment]
I ran into the same issue deploying a new Laravel 5.6 application to a newly provisioned Forge server (Ubuntu 18.04.1)

Installing libpng-dev via ```sudo apt-get install libpng-dev``` sorted this for me.
