### ISSUE TITLE
ES2015 default parameters error

### ISSUE THREAD

**Issue by NikolaySav** [JeffreyWay/laravel-mix#1612]
- Laravel Mix Version: 2.1.11
- Node Version:  9.11.1
- NPM Version:  5.8.0
- OS: Ubuntu 17.10
- VUE version: 2.5.13

### Description:
enabling ES2015 default parameters plugin, es2015, browser support for ie >= 11 preset does nothing.
default parameters are still used inside the app.js

### Steps To Reproduce:
npm install ymaps-touch-scroll

in .vue component:
import ymapsTouchScroll from 'ymaps-touch-scroll';
use ymapsTouchScroll() function

npm run dev

search app.js for ymapsTouchScroll function, which uses second argument with default value.
Hence IE11 fails at this line.

In my webpack.mix.js:
.js('resources/assets/js/app.js', 'public/js')

In .babelrc:

{
  "presets": [
    "es2015"
  ]
}

or 

{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions", "ie >= 11"]
      }
    }]
  ]
}

**Comment by ruchern** [comment]
Try installing `babel-polyfill`

`npm install --save-dev babel-polyfill`

---

**main.js**

`import 'babel-polyfill'`

**Comment by NikolaySav** [comment]
Thanks you for answer.
babel-polyfill didn't work
Babel still ignored this function.
However another custom functions inside app.js were transpiled correctly.

Solved this problem by importing another file from this package
import ymapsTouchScroll from 'ymaps-touch-scroll/dist/ymaps-touch-scroll.min';
