### ISSUE TITLE
npm install not installing webpack

### ISSUE THREAD

**Issue by moleculezz** [JeffreyWay/laravel-mix#1613]
- Laravel Mix Version: 2.1.11 (`npm list --depth=0`)
- Node Version (`node -v`): 9.11.1
- NPM Version (`npm -v`): 5.8.0
- OS: macOS 10.12.6
### Description:
Can't seem to be able to run any of the npm scripts.
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gdarends/.npm/_logs/2018-04-23T12_39_54_587Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `npm run development -- --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Checking installed dependencies (`npm list --depth=1`) shows the following: (note the UNMET PEER DEPENDENCY)
```
├─┬ laravel-mix@2.1.11
│ ├── autoprefixer@7.2.6
│ ├── babel-core@6.26.0
│ ├── babel-loader@7.1.2
│ ├── babel-plugin-transform-object-rest-spread@6.26.0
│ ├── babel-plugin-transform-runtime@6.23.0
│ ├── babel-preset-env@1.6.1
│ ├── chokidar@2.0.3
│ ├── clean-css@4.1.9
│ ├── concatenate@0.0.2
│ ├── css-loader@0.28.9
│ ├── dotenv@4.0.0
│ ├── dotenv-expand@4.2.0
│ ├── extract-text-webpack-plugin@3.0.2
│ ├── file-loader@0.11.2
│ ├── friendly-errors-webpack-plugin@1.6.1
│ ├── fs-extra@3.0.1
│ ├── glob@7.1.2
│ ├── html-loader@0.4.5
│ ├── img-loader@2.0.1
│ ├── lodash@4.17.5 deduped
│ ├── md5@2.2.1
│ ├── node-sass@4.7.2
│ ├── postcss-loader@2.1.0
│ ├── resolve-url-loader@2.2.1
│ ├── sass-loader@6.0.6
│ ├── style-loader@0.18.2
│ ├── uglify-js@2.8.29
│ ├── uglifyjs-webpack-plugin@1.1.8
│ ├── vue-loader@13.7.1
│ ├── vue-template-compiler@2.5.13
│ ├── UNMET PEER DEPENDENCY webpack@3.11.0
│ ├── webpack-chunk-hash@0.4.0
│ ├── webpack-dev-server@2.11.1
│ ├── webpack-merge@4.1.1
│ ├── webpack-notifier@1.5.1
│ └── yargs@8.0.2
```

### Steps To Reproduce:
```
npm install
npm run dev
```
running `npm install webpack@3.11.0` solves the issue.
I also checked `node_modules/laravel-mix/package.json`, and it contains the webpack dependency. So not sure why it's not installing.

**Comment by moleculezz** [comment]
Just tried `yarn install` instead, and that works fine.

**Comment by 19peaches** [comment]
Having the same issue, except I'm not getting babel-loader either. Strange.

**Comment by 19peaches** [comment]
mine was a bad lock file, so resolved for me.

**Comment by moleculezz** [comment]
Seems that was the case for me as well.

**Comment by kokotonev** [comment]
Can you please explain what is a bad lock file and how did you resolve the problem?

**Comment by robbyrice** [comment]
@kokotonev the lock file is package-lock.json. You can remove it and reinstall your dependencies with the following commands. These commands should be run from the root directory of your project.

```
rm package-lock.json && rm -R node_modules
npm install
```

**Comment by kokotonev** [comment]
@robbyrice thank you for the explanation! Actually, I managed to solve the problem in a different way. I ran `npm update` and then `npm install` again and this solved the issue for me and it installed the missing peer dependencies (which were webpack and webpack-dev-server). I still don't know why this happened though, because the same repo works fine without `npm update` on my colleagues' computers...

**Comment by robbyrice** [comment]
You're welcome. I'm glad you were able to solve the issue. My knowledge of NPM is fairly limited and I'm not too sure why it works the way it does sometimes. I've had something similar happen before, but it usually involved updating a package to a new major version. :shrug:
