### ISSUE TITLE
Can't make work Hot Module Replacement with browserSync proxy

### ISSUE THREAD

**Issue by deryckoe** [JeffreyWay/laravel-mix#1615]
Hi,

I have the following code in webpack.mix.js

```
mix.js('src/app.js', 'dist/').sourceMaps().sass('src/app.scss', 'dist/');
mix.browserSync(
    {
        files: [
            'src/**/*',
            'components/**/*',
            'index.php'
        ],
        proxy: 'wordpress.local',
        browser: ["google chrome canary"],
        https: false

    }
);
```

If I run npm watch task:

```
"watch": "NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
```

Works fine!

If I try to use npm hot task with HMR

```
"hot": "NODE_ENV=development webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",

```

I get:

```
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

I'm running vue inside a WordPress Theme. Works fine, with what, but HMR does not. 
:( and it's a lot faster to use HMR. 

What can I do?

Thanks.

**Comment by ikudosi** [comment]
The best success I've had (and is a bit hacky) when doing `npm run hot` (and still get HMR + BrowserSync to work) is to inject the script in the page via an env variable I created. It's a bit hacky but this was the most cleanest way for instead of trying to fight against the the mix configurations. On my earlier config I 

```
@if(env("APP_ENV") == "local" && env('USE_BROWSERSYNC_WITH_HMR', false))
        <!-- This will allow you to use browsersync with hot reload without any port specification in your browser (when using npm run hot)  -->
        <script async type="text/javascript" src="{{env('APP_URL')}}:3000/browser-sync/browser-sync-client.js?v=2.23.6"></script>
@endif
```

Then I just go to my APP_URL on standard port 80. Hopefully this works or another method works for you!

**Comment by deryckoe** [comment]
Hi @ikudosi.

I apologize for the delaying so much in getting back to this issue. I try and did not work. I'm a little bit lost. There's is documentation related or another tip you can give me in order to make it work?

Thank you very much!
