### ISSUE TITLE
Possible way to obfuscate parsed .env variable?

### ISSUE THREAD

**Issue by grikomsn** [JeffreyWay/laravel-mix#1617]
- Laravel Mix Version: 1.7.2
- Node Version: v9.11.1
- NPM Version: 5.8.0
- OS: macOS High Sierra 10.13.4

### Description:

Compiled assets does not obfuscate environment variables.

#### 1. Create file `domain-protection.js`

I made a JavaScript file that redirects unknown domains to a specific URL (`resources/assets/js/domain-protection.js`):
```js
$(function () {
    const domains = [
        process.env.APP_URL,
        process.env.APP_PUBLIC_URL,
    ];
    if ($.inArray((location.protocol + "//" + location.host), domains) < 0) {
        window.location.href = process.env.APP_URL + '/mirror-detected';
    }
});
```

#### 2. Set environment variables

The environment variables are:
```env
APP_URL=http://localhost:8000
APP_PUBLIC_URL=https://lbp.ddns.net
```

#### 3. Configure `webpack.mix.js`

And I use this code on `webpack.mix.js` to parse the environment variables and obfuscate the code:
```js
const Dotenv = require('dotenv-webpack');
const Obfuscator = require('webpack-obfuscator');

mix.webpackConfig({
    plugins: [
        new Dotenv({
            path: path.resolve(__dirname + '/.env')
        }),
        new Obfuscator(),
    ]
}).js('resources/assets/js/domain-protection.js', 'public/js/domain-protection.js');
```

#### 4. Execute `npm run dev` and `npm run prod`

Both `npm run dev` and `npm run prod` does not obfuscate the parsed environment variable:
- `dev`: https://gist.github.com/grikomsn/20602a64178049ae2e7491bbf427dd09
- `prod`: https://gist.github.com/grikomsn/8804755a1f53051be3a71450ad3a832b

Is there any way to process the variables _then_ obfuscate the strings? Thanks in advance.

**Comment by dwightwatson** [comment]
Can you access those environment variables in your script without using obfuscation? The [docs state that your environment variables need to be prefixed with `MIX_`](https://laravel.com/docs/5.6/mix#environment-variables) in order to be available to your scripts.
