### ISSUE TITLE
.version causes chunkhashes in both dev and production

### ISSUE THREAD

**Issue by SethTompkins** [JeffreyWay/laravel-mix#162]
This line here: https://github.com/JeffreyWay/laravel-mix/blob/master/src/Mix.js#L104

The only check to determine if output should contain a chunkhash is if versioning is enabled. This is contrary to the docs that state that `.version()` will only trigger versioning if `npm run production` is invoked.

**Comment by JeffreyWay** [comment]
Docs need to be updated. This was changed.
