### ISSUE TITLE
Laravel Mix throwing errors when using ExtractTextPlugin with mix.webpackConfig() to extract CSS to dedicated file

### ISSUE THREAD

**Issue by waleedahmad** [JeffreyWay/laravel-mix#1621]
- Laravel Mix Version: 2.1.11 (`npm list --depth=0`)
- Node Version (`node -v`): v8.9.4
- NPM Version (`npm -v`): 5.8.0
- OS: Windows 10

### Description:

I'm trying to extract css from react components using extract-text-webpack-plugin v3.0.2. This is my project's webpack.config.js file. 

```
const { mix } = require('laravel-mix');
const path = require('path');
const ExtractTextPlugin = require("extract-text-webpack-plugin");

mix.autoload({
    jquery : ['$', 'jquery' , 'jQuery', 'jQuery', 'window.jQuery'],
    toastr : ['toastr'],
    bootbox : ['bootbox']
});

mix.react('resources/assets/src/app.js', 'public/assets/bundle')
    .version()
    .disableNotifications();

mix.webpackConfig({
    module: {
        rules: [
            {
                test:  /\.s[ac]ss$/,
                loader: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use : [
                        {
                            loader : 'css-loader',
                        },
                        {
                            loader : 'postcss-loader',
                        },
                        {
                            loader : 'sass-loader',

                        }
                    ]
                })
            }
        ]
    },
    plugins: [
        new ExtractTextPlugin('[name].[contenthash].css')
    ],
    devtool : 'source-map'
}).sourceMaps();

mix.options({
    processCssUrls: false
});
```
When i try to run 

`
$ npm run watch
`

Console outputs these errors

$ npm run watch

@ watch C:\xampp\htdocs\laravel-react
cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 10% building modules 1/1 modules 0 active                                     Webpack is watching the filesâ¦
                                      95% emitting ERROR  Failed to compile with 1 errors22:46:45

 error  in ./resources/assets/src/app.scss

Module build failed:
.code{
^
      Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi"
      in C:\xampp\htdocs\laravel-react\resources\assets\src\app.scss (line 1, column 1)

 @ ./resources/assets/src/app.scss 4:14-356
 @ ./resources/assets/src/app.js
 @ multi ./resources/assets/src/app.js
                                                                                                                        Asset       Size  Chunks             Chunk Names
                                      /assets/bundle/app.js    17.4 kB       0  [emitted]  /assets/bundle/app
    /assets/bundle/app.3440027245db6fde0f324e940fc985b2.css  112 bytes       0  [emitted]  /assets/bundle/app
                                             vue-styles.css   86 bytes       0  [emitted]  /assets/bundle/app
                                  /assets/bundle/app.js.map    21.5 kB       0  [emitted]  /assets/bundle/app
/assets/bundle/app.3440027245db6fde0f324e940fc985b2.css.map  407 bytes       0  [emitted]  /assets/bundle/app
                                         vue-styles.css.map  366 bytes       0  [emitted]  /assets/bundle/app

ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./node_modules/extract-text-webpack-plugin/dist/loader.js?{"omit":1,"remove":true}!./node_modules/style-loader!./node_modules/css-loader?{"url":false,"minimize":true,"sourceMap":true}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./resources/assets/src/app.scss
Module build failed:
.code{
^
      Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi"
      in C:\xampp\htdocs\laravel-react\resources\assets\src\app.scss (line 1, column 1)
 @ ./resources/assets/src/app.scss 4:14-356
 @ ./resources/assets/src/app.js
 @ multi ./resources/assets/src/app.js

Despite these errors laravel-mix still generates javascript and css files under `public/assets/bundle` folder. Along with these files, it's also generating vue-styles.css file which i didn't enable in mix config. This is my mix-manifest file.

```
{
    "/assets/bundle/app.js": "/assets/bundle/app.js?id=f9c93768024dd8f77566",
    "/assets/bundle/app.3440027245db6fde0f324e940fc985b2.css": "/assets/bundle/app.3440027245db6fde0f324e940fc985b2.css?id=2b88fbad7acd87bf141e",
    "/vue-styles.css": "/vue-styles.css?id=abc461987f2653372dd4",
    "/assets/bundle/app.js.map": "/assets/bundle/app.js.map?id=cd0725c0fc0a04308069",
    "/assets/bundle/app.3440027245db6fde0f324e940fc985b2.css.map": "/assets/bundle/app.3440027245db6fde0f324e940fc985b2.css.map?id=f8eb2dbad3ccc82cb890",
    "/vue-styles.css.map": "/vue-styles.css.map?id=51a057f9e6a08be40807"
}
```
It's not writing /assets/bundle/app.css file path to mix-manifest either. This exact webpack.config.js works flawlessly for Laravel 5.5.* project with laravel-mix@0.12.1. What am i doing wrong here?

**Comment by waleedahmad** [comment]
I did some debugging and logged merged config from `mergeCustomConfig()` method in `node_modules\laravel-mix\src\builder\WebpackConfig.js` file. I found multiple rules targeting .s[ac]ss files in output. This is logged output.

```
{ context: 'C:\\xampp\\htdocs\\laravel-react',
  entry:
   { '/assets/bundle/app':
      [ 'C:\\xampp\\htdocs\\laravel-react\\resources\\assets\\src\\app.js' ] },
  output:
   { path: 'C:\\xampp\\htdocs\\laravel-react\\public',
     filename: '[name].js',
     chunkFilename: '[name].js',
     publicPath: '/' },
  module:
   { rules:
      [ { test: /\.html$/, loaders: [ 'html-loader' ] },
        { test: /(\.(png|jpe?g|gif)$|^((?!font).)*\.svg$)/,
          loaders:
           [ { loader: 'file-loader',
               options: { name: [Function: name], publicPath: '/' } },
             { loader: 'img-loader',
               options: { enabled: true, gifsicle: {}, mozjpeg: {}, optipng: {}, svgo: {} } } ] },
        { test: /(\.(woff2?|ttf|eot|otf)$|font.*\.svg$)/,
          loader: 'file-loader',
          options: { name: [Function: name], publicPath: '/' } },
        { test: /\.(cur|ani)$/,
          loader: 'file-loader',
          options: { name: '[name].[ext]?[hash]', publicPath: '/' } },
        { test: /\.jsx?$/,
          exclude: /(node_modules|bower_components)/,
          use:
           [ { loader: 'babel-loader',
               options:
                { cacheDirectory: true,
                  presets:
                   [ [ 'env',
                       { modules: false,
                         targets: { browsers: [ '> 2%' ], uglify: true } } ],
                     'react' ],
                  plugins:
                   [ 'transform-object-rest-spread',
                     [ 'transform-runtime', { polyfill: false, helpers: false } ] ] } } ] },
        { test: /\.css$/, loaders: [ 'style-loader', 'css-loader' ] },
        { test: /\.s[ac]ss$/,
          exclude: [],
          loaders: [ 'style-loader', 'css-loader', 'sass-loader' ] },
        { test: /\.less$/,
          exclude: [],
          loaders: [ 'style-loader', 'css-loader', 'less-loader' ] },
        { test: /\.s[ac]ss$/,
          loader:
           [ { loader: 'C:\\xampp\\htdocs\\laravel-react\\node_modules\\extract-text-webpack-plugin\\dist\\loader.js',
               options: { omit: 1, remove: true } },
             { loader: 'style-loader' },
             { loader: 'css-loader' },
             { loader: 'sass-loader' } ] } ] },
  plugins:
   [ FriendlyErrorsWebpackPlugin {
       compilationSuccessInfo: {},
       onErrors: undefined,
       shouldClearConsole: true,
       formatters: [ [Function: format], [Function: format], [Function: format] ],
       transformers:
        [ [Function: transform],
          [Function: transform],
          [Function: transform] ] },
     DefinePlugin {
       definitions:
        { 'process.env':
           { MIX_PUSHER_APP_CLUSTER: '"mt1"',
             MIX_PUSHER_APP_KEY: '""',
             NODE_ENV: '"development"' } } },
     LoaderOptionsPlugin {
       options:
        { minimize: false,
          options:
           { context: 'C:\\xampp\\htdocs\\laravel-react\\node_modules\\laravel-mix\\src\\builder',
             output: { path: './' } },
          test: { test: [Function: test] } } },
     ManifestPlugin {},
     CustomTasksPlugin {},
     BuildCallbackPlugin { callback: [Function] },
     NamedModulesPlugin { options: {} },
     WebpackChunkHash {
       algorithm: 'md5',
       digest: 'hex',
       additionalHashContent: [Function] },
     ExtractTextPlugin { filename: '[name].css', id: 1, options: {} } ],
  stats:
   { hash: false,
     version: false,
     timings: false,
     children: false,
     errorDetails: false,
     chunks: false,
     modules: false,
     reasons: false,
     source: false,
     publicPath: false },
  performance: { hints: false },
  devtool: 'source-map',
  devServer:
   { headers: { 'Access-Control-Allow-Origin': '*' },
     contentBase: 'C:\\xampp\\htdocs\\laravel-react\\public',
     historyApiFallback: true,
     noInfo: true,
     compress: true,
     quiet: true },
  resolve:
   { extensions: [ '*', '.js', '.jsx', '.vue' ],
     alias: { 'vue$': 'vue/dist/vue.common.js' } } }
```
After adding exclude key to rules, webpack-merge was able to merge it and i was able build it successfully. 
```
mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.s[ac]ss$/,
                exclude : [],
                loader: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use : [
                        {
                            loader : 'css-loader',
                        },
                        {
                            loader : 'sass-loader',

                        }
                    ]
                })
            }
        ]
    },
    plugins: [
        new ExtractTextPlugin('[name].css')
    ],
    devtool : 'source-map'
});
```
But it's still generating vue-style.css file in public folder despite setting extractVueStyles option to false.

```
mix.options({
    extractVueStyles : false,
    processCssUrls: false
});
```
and it's also writing it to mix-manifest file.

```
{
    "/assets/bundle/app.js": "/assets/bundle/app.js?id=0002dcbac1cce459220c",
    "/assets/bundle/app.css": "/assets/bundle/app.css?id=7aa61007f62fc0721e8b",
    "/vue-styles.css": "/vue-styles.css?id=99d5b75dcb63c94555a2",
    "/assets/bundle/app.js.map": "/assets/bundle/app.js.map?id=379fe002e7036e2b77f9",
    "/assets/bundle/app.css.map": "/assets/bundle/app.css.map?id=242f1a0a87d9b453ed65",
    "/vue-styles.css.map": "/vue-styles.css.map?id=3b128f39121c22f92775"
}
```

**Comment by Xationch** [comment]
Did you solve the problem?

**Comment by waleedahmad** [comment]
Yes!

**Comment by Xationch** [comment]
@waleedahmad I've the same problem. Can you share the solution?

**Comment by waleedahmad** [comment]
Which version of mix are you on?

**Comment by Xationch** [comment]
^2.1.14

**Comment by waleedahmad** [comment]
Can i see your webpack.config.js file?

**Comment by bradley-r-martin** [comment]
I have the same issue. webpack.mix.js file:
`let mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

const ExtractTextPlugin = require("extract-text-webpack-plugin");

mix.webpackConfig({
    resolve: {
        alias: {
            '~UI': path.resolve('resources/assets/sass/ui')
        }
    },
    module: {
        rules: [
            {
                test: /\.s[ac]ss$/,
                exclude : [],
                loader: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use : [
                        {
                            loader : 'css-loader',
                        },
                        {
                            loader : 'sass-loader',

                        }
                    ]
                })
            }
        ]
    },
    plugins: [
        new ExtractTextPlugin('[name].css')
    ]
});

mix.react('resources/assets/js/app.js', 'public/js');
mix.sass('resources/assets/sass/app.scss', 'public/css')
mix.styles(
    [
        'resources/assets/css/animate.css'
    ],
    'public/css/vendors.css'
);
  
mix.version();
if (!mix.inProduction()) {
    mix.sourceMaps();
}`

**Comment by bradley-r-martin** [comment]
I am having the same issue. any solution ?

**Comment by leotankilevich** [comment]
Hi @waleedahmad. Can u show your webpack.mix/config.js. I have the same problem
