### ISSUE TITLE
Way to split VueJS components / instances to many *.js files to make performance better

### ISSUE THREAD

**Issue by lrembacz** [JeffreyWay/laravel-mix#1622]
Hi.

Is there a way ? Or is there any improvement planned to split the compiled code into many small .js files or Vue instances and to be able to use them later only for needy subpages to improve performance?

I mean we have many components and we mix them with normal blade files. For now when we want to use any we need to inject app.js file to this page. So if our app.js file is few MB or even more we need to get thie every time we change poge or smth. If we could only include part of components we need for actual page it could improve the performance of the application and make it work faster even when we are using it on lower cpu devices or something.

**Comment by artemsky** [comment]
https://webpack.js.org/guides/code-splitting/#dynamic-imports

**Comment by Bowens20832** [comment]
Do like below, it should work. 

```
<template>
    <div> 
        <sample-component></sample-component>
    </div>
</template>
<script>
    const SampleComponent = resolve => require(['./components/SampleComponent.vue'], resolve);

    export default {
        components:{
            SampleComponent 
        }
    }
</script>
```

**Comment by lrembacz** [comment]
Thanks for your replay :)

**Comment by Bowens20832** [comment]
@lrembacz Did that work for you?

**Comment by andre-dw** [comment]
@lrembacz Thanks, Works perfect! 
Is there some way to automatically create a legacy build so browsers like IE11 use that build?
I know Vue-cli 3.0.0 provides that option 'https://cli.vuejs.org/guide/browser-compatibility.html#modern-mode'. Here some more info: 'https://philipwalton.com/articles/deploying-es2015-code-in-production-today/'

**Comment by muffeen** [comment]
@lrembacz Thanks.
Only one problem I see is that I have versioning enabled (`mix.version()`). Lazy loaded files does not get their version.

**Comment by andre-dw** [comment]
@muffeen https://github.com/JeffreyWay/laravel-mix/pull/1557
