### ISSUE TITLE
Watch / Watch-poll doesnt work if you have a custom webpack.mix.js

### ISSUE THREAD

**Issue by bellwood** [JeffreyWay/laravel-mix#1626]
- Laravel Mix Version: 2.1.11
- Node Version: v8.11.1
- NPM Version: 6.0.0
- OS: CentOS Linux release 7.4.1708 (Core) 3.10.0-693.21.1.el7.x86_64

### Description:

When using a custom webpack.mix.js, if you comment out the default/provided configuration:

```
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
```

...and roll your own, neither watch nor watch-poll works - it mixes everything, successfully, once and there it sits forever stagnant.

If you alternatively merge everything into the default files, then watch/watch-poll works as expected.

I went right off the main Laravel documentation and no where does it state you *need* to use the default for watch/watch-poll to work - so I'd simply crafted my own up.

In the end, it works better anyway, but it burned a lot of cycles to get there - "why doesn't this work!?"

Not sure if this is a bug, the lack of providing feedback to the user, documentation?

**Comment by dwightwatson** [comment]
Can you share the code for your configuration that isn't working?

I have a number of apps that don't use the default configuration and have never run into an issue with watch not getting triggered by file changes.

**Comment by nathanaelphilip** [comment]
it stopped working for me as well, this is the same set up I’ve used for a few months:

Using Version `2.1.11`


```
const mix = require('laravel-mix')

const resources = 'app/resources'
const assets = 'content/themes/strt/assets'

mix.setPublicPath(assets)
mix.setResourceRoot('../')

mix.js(`${resources}/js/app.js`, `${assets}/js`)

mix.sass(`${resources}/scss/app.scss`, `${assets}/css`, {
  includePaths: ['node_modules']
})

mix.copy(`${resources}/fonts`, `${assets}/fonts`)
mix.copy(`${resources}/images`, `${assets}/images`)

// Hash and version files in production.
if (mix.config.inProduction) {
  mix.version()
}
```
