### ISSUE TITLE
Dynamic component loading causes Laravel Mix to loop

### ISSUE THREAD

**Issue by bugsysha** [JeffreyWay/laravel-mix#1628]
- Laravel Mix Version: 2.1.11
- Node Version: 8.11.1
- NPM Version: 6.0.0
- OS: MacOS 10.13.3

### Description:

I need to load components based on computed property.

If I do the following then I get `Module build failed: SyntaxError: Unexpected token` for `import` keyword.

```javascript
// Template.vue file

<template>
    <div class="template">
        <component :is="templateLoader"></component>
    </div>
</template>

<script>
    export default {
        data() {
            return {
                templateName: ''
            }
        },

        computed: {
            templateLoader() {
                if (!this.templateName) {
                    return () => null
                }

                return () => import(`./${this.templateName}/index.vue`)
            }
        }
    }
</script>
```

If I replace the `import` with `require` like below then the app works

```javascript
//...
return require(`./${this.templateName}/index.vue`)
//...
```

but Laravel Mix gets stuck in some kind of a loop that looks like below.

```bash
WAIT Compiling...

10% building modules 0/1 modules 1 active .../user/project /^\.\/.*\/index$/
```

### Steps To Reproduce:

Create a Vue SFC that imports or requires other Vue SFC based on dynamic name which is retrieved from computed property. Everything explained above.

**Comment by ankurk91** [comment]
Read here
https://github.com/JeffreyWay/laravel-mix/issues/1249#issuecomment-335112415

**Comment by zendrax** [comment]
Hi @ankurk91 
Saw your comment yesterday and it didn't help. It resolved the usage of `import` keyword but the watcher still managed to get stuck in infinite loop.
