### ISSUE TITLE
Version() doesn't work on files brought in through copy() or combine()

### ISSUE THREAD

**Issue by thepenguin1** [JeffreyWay/laravel-mix#163]
As stated in the title, this won't version the file:

`mix.copy("resources/assets/css/vendor.css", "public/css").version();`

nor this:

`mix.combine("resources/assets/css/app.css", "public/css").version();`

**Comment by adriaanzon** [comment]
See #53.

You can import those css files in your sass entry point.

**Comment by adriaanzon** [comment]
Using `mix.sass` for your css files directly seems to work too

**Comment by thepenguin1** [comment]
Thanks, I've just discovered that. My only concern is whether this will result in a double minification of JS files when I come to copying them?

**Comment by JeffreyWay** [comment]
.copy() and .combine() are separate from Webpack's bundling process. They're little extras.
