### ISSUE TITLE
How to use versioning outside of a laravel project

### ISSUE THREAD

**Issue by ntraykov** [JeffreyWay/laravel-mix#1635]
When creating a project that is outside of laravel there is no way to use versioning, because there is no mix directive. One way is to create a Mix.php class and implement this functionality, but my frontend project is only html + css + js. Any ideas?

**Comment by cretueusebiu** [comment]
You can copy the `mix` function from [helpers.php](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/helpers.php#L559) and adapt it for your project.

**Comment by ntraykov** [comment]
I understand, but what if my project doesn't contain any php? Even my index is index.html, not php. It appears there is no other chance to implement this unless I replace index.html with index.php...

**Comment by cretueusebiu** [comment]
Mix generates a manifest file, all you have to do is read that and extract the url to the asset. 
If you only have a index.html file, write a script that generates the file based on the manifest and run it after the build process or even add it in `webpack.mix.js`.

**Comment by ntraykov** [comment]
Ok, thanks a lot!

**Comment by ntraykov** [comment]
I've created Mix.php with the functionality of the `mix` function. The problem is if I create index.php instead of index.html, webpack dev server won't parse it and I won't be able to have hot realod. If I access it with http://localhost:8080/index.php the server downloads the file, which is a normal behavior, since it doesn't care about php.

**Comment by devcircus** [comment]
How you implement versioning isn't really a concern of the Mix library. Mix helps out by providing the manifest. It's up to you to parse the file and convert your links.

**Comment by devcircus** [comment]
Google "asset versioning npm" and check out some libraries. You can get some ideas and implement your own.

**Comment by ntraykov** [comment]
It isn't a concern, but it is included in Mix, so I should be able to use it. I thought I am not the only one having this problem, so I don't need to discover the hot water. As long as I understand, the short answer to my question is "no", so I am going to find solutions by myself.

**Comment by ntraykov** [comment]
I figured it out. There is no need to call localhost:8080 directly. The only thing that I have to do is to open my virtual host and point all my assets to localhost:8080. Hot reload works! As for the versioning, I use versioning only on production, where hot reload does not exist and the problem mentioned above is not valid!

**Comment by marcamos** [comment]
I'd be interested in seeing how you did it; I'm in the same boat as you: I'd like to implement versioning, but I often use Mix outside of Laravel projects.

**Comment by gaz-think3** [comment]
@marcamos 

There was never really an answer to this question. So, here is an example of my implementation in a WordPress project.
You can swap out `get_template_directory()` for any path within a PHP Project

```
/**
* Gets mix versions
*
* @param string $file
*
* @return string $file File path
*/
function MixAssets($file) {
    $fileLoc = get_template_directory() . '/path/to/mix-manifest.json';

    if( !file_exists( $fileLoc ) ) {
        return $file;
    } else {
        $mix = file_get_contents($fileLoc);
        $mix = json_decode($mix, true);

        if( isset( $mix[$file] ) ) {
            return $mix[$file];
        } else {
            return $file;
        }
    }
}
