### ISSUE TITLE
Mix Copy with wildcard copies entire directory structure into targeted directory

### ISSUE THREAD

**Issue by blackdrago** [JeffreyWay/laravel-mix#1636]
- Laravel Mix Version: 0.12.1 (working with Laravel 5.4)
- Node Version (`node -v`):  6.12.0
- NPM Version (`npm -v`):  5.8.0
- OS:  CentOS Linux 7 (Core)

### Description:
Whenever trying to copy all of a single file type via wildcard from one directory to another, the entire directory structure is copied to the target directory (rather than just the files).

### Steps To Reproduce:
1. Install chosen-js via NPM (npm i chosen-js)
2. Add the following line to webpack.mix.js:
`mix.copy('node_modules/chosen-js/*.png', 'src/public/css/');`
3. Mix the assets (npm run dev).

**Result**: The two image files are copied into src/public/css/node_modules/chosen-js/
**Expected**: The two images files are copied into src/public/css/

**Note**:  A workaround for this is to directly copy each file into the target directory. Replace the line above with the following:
`mix.copy('node_modules/chosen-js/chosen-sprite.png', 'src/public/css/');
mix.copy('node_modules/chosen-js/chosen-sprite@2x.png', 'src/public/css/');`

And this works as expected, but that requires me to know and hard-code each file.

**Comment by ankurk91** [comment]
You are using Laravel mix v**0.12.1**, don't you think it is too old.
This version was released on `28 May 2017`, around one year ago
