### ISSUE TITLE
img file loader path err

### ISSUE THREAD

**Issue by maxiloEmmmm** [JeffreyWay/laravel-mix#1640]
- Laravel Mix Version: lastest
- Node Version (`node -v`): 8.9.3
- NPM Version (`npm -v`): 5.5.1
- OS: Mac OS

### Description:
npm run hot
assets/image/2.png
assets/image/test/2.png

![image](https://user-images.githubusercontent.com/16779121/39963865-dadd1e6c-56a9-11e8-8c03-c7e9e318d11c.png)
![image](https://user-images.githubusercontent.com/16779121/39963869-ff169b96-56a9-11e8-80f2-07b58a8637d6.png)

两张图片名字一样,路径不同,但是生成路径时没有加入 `path info`, 导致图片会被覆盖

**Comment by maxiloEmmmm** [comment]
I have handled this for the time being
I tried to listen configReady, delete default config,
![image](https://user-images.githubusercontent.com/16779121/39964275-7ea8a4b8-56b3-11e8-9c53-29acecf4c166.png)

**Comment by ankurk91** [comment]
What was the error message?
Would you like to share your `webpack.mix.js`

**Comment by maxiloEmmmm** [comment]
@ankurk91  no err, Two graphs should be generated. One is images/2.png and the other is images/test/2.png. However, the path information is not added, resulting in only one images/2.png
my `webpack.mix.js` is  a layer of my package [this](https://github.com/maxiloEmmmm/maxilo-vue-template)
