### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by bellwood** [JeffreyWay/laravel-mix#1644]
- Laravel Mix Version: 2.1.11
- Node Version: v8.11.2
- NPM Version: 5.6.0
- OS: CentOS 7
- Laravel: 5.6

### Description:

I've googled and SO'd this to death, I keep getting $ is not defined when using jQuery.

### Steps To Reproduce:

webpack.mx.js
```
let mix = require('laravel-mix');

mix.copyDirectory('resources/assets/img', 'public/img')
  .js('resources/assets/js/app.js', 'public/js')
  .sass('resources/assets/sass/app.scss', 'public/css')
  .version();
```

resources/assets/js/app.js
```
require('./vendor/jquery-3.3.1.min');
require('./vendor/popper.min');
require('./vendor/bootstrap.min');
```

`npm run production` gives no issues.

I'm including the built app.js before any page specific JS but keep getting `$ is not defined` no matter what.

I've tried all the autoloading solutions, etc to no avail.

**Comment by ankurk91** [comment]
What is the role of `vendor` folder here.
Why are you loading js files from `vendor`.

Autoloading [example](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/autoloading.md) is only tend to work when using `node_modules` 
There are ways to make it work with any folder but why would someone do that.

**Comment by bellwood** [comment]
`vendor` is simply `resources/assets/js/vendor` and simply serves to keep vendor libs separate from my libs

**Comment by devcircus** [comment]
Looks like you need to autoload jquery. Check the docs on autoloading.

**Comment by bellwood** [comment]
Tried it, unfortunately did not work

**Comment by ankurk91** [comment]
`
php artisan preset bootstrap
`

Remove that vendor folder immediately.

**Comment by bellwood** [comment]
@ankurk91: I was already using the preset just rolling my own bootstrap to decouple it from what laravel packages so I can control it.

Had to make a change to the given bootstrap.js to load my specific bootstrap version, but in the end this worked and resolved my issue. Thank you.
