### ISSUE TITLE
Error on npm run dev with fresh install

### ISSUE THREAD

**Issue by franckysolo** [JeffreyWay/laravel-mix#1647]
- Laravel Mix Version: 2.1.11
```
/home/vagrant/projects/iot
├── axios@0.18.0
├── bootstrap@4.1.1
├── cross-env@5.1.5
├── jquery@3.3.1
├── laravel-mix@2.1.11
├── lodash@4.17.10
├── popper.js@1.14.3
└── vue@2.5.16

npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.2.0
npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.2.0
npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.2.0
```
- Node Version (`node -v`):  v8.11.1
- NPM Version (`npm -v`): 6.0.1
- OS: Ubuntu 16.04 LTS

### Description:

Fresh install of laravel on homestead

I install ajv@^6.0.0 to fix the first warning on npm list --depth=0

### Steps To Reproduce:
```
cd projects/
laravel new iot
cd iot
npm i
```
A warning and error occured
```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-05-20T16_48_40_245Z-debug.log
```

I try another `npm i`
No error but warning is present

Then i run `npm run dev`
An error occured : 

```
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^
Error: spawn EACCES
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at spawn (/usr/lib/node_modules/cross-env/node_modules/cross-spawn/index.js:17:18)
    at crossEnv (/usr/lib/node_modules/cross-env/dist/index.js:32:38)
    at Object.<anonymous> (/usr/lib/node_modules/cross-env/dist/bin/cross-env.js:6:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

I have the issue with mix 2.0, i update the package to 2.1.11 this is the same behaviour

How can i solve this issue?

**Comment by franckysolo** [comment]
How i solve this issue by using yarn install instead of npm install
May be it could help someone!

*Solution:*
```
rm -rf node_modules
yarn install
npm run dev
```
No more errors

**Comment by J5Dev** [comment]
I had the same issue, and updated to the latest version of node/npm, then removed and did a npm install... no more problems, so it seems the issue with npm has been fixed.

**Comment by franckysolo** [comment]
The issue is not fix, fresh install with homestead, last laravel vagrant box and last laravel version

```
error cb() never called!
```
when running npm install

**Comment by J5Dev** [comment]
Yeah, I noticed the other day, I had forgot about this issue.

It seems it was fixed, and has come back... somehow. We have switched all our apps/processes over to yarn, not only does it not seem to be as flakey, but it is so much faster for builds, can highly recommend ;)

**Comment by JeffreyWay** [comment]
This isn’t a Mix-specific issue. There’s no code I change in this repo to fix it.

**Comment by J5Dev** [comment]
> This isn’t a Mix-specific issue. There’s no code I change in this repo to fix it.

Yeah had realised that, seems to be a recurring issue with npm... hence why we moved to yarn :)
