### ISSUE TITLE
Cannot compile css files with @import.

### ISSUE THREAD

**Issue by jeewandhakal25** [JeffreyWay/laravel-mix#1650]
### Description:

This is what there is in webpack.mix.js
```
mix.styles([
    'packages/jeevan/**/public/admin/css/app.css',
], 'public/assets/admin/css/app.css');
```
### After running npm run dev 

in compiled app.css file i got
`@import "modules/AdminLTE.css";`

**Comment by bbashy** [comment]
Had the same. Ended up just converting it to `.scss` file and running it with `.sass()`
