### ISSUE TITLE
Watch not working on lazy loaded routes

### ISSUE THREAD

**Issue by weerdm** [JeffreyWay/laravel-mix#1653]
- Laravel Mix Version: 2.1.11
- Node Version (`node -v`):  v8.11.1
- NPM Version (`npm -v`): 5.6.0
- OS: 

### Description:

Hi!

When using VueJS lazy loading (https://router.vuejs.org/guide/advanced/lazy-loading.html), either watch or cache busting is not working. When I make a change in a lazy loaded component, I can see that watch is triggering NPM to rebuild the assets, however when I refresh the page I don't see the affected changes. When I abort `npm run watch` en run `npm run development` manually,  the changes are working as expected.

Little sidenote: It it also not removing any `old` files.

### Steps To Reproduce:

1. Create a lazy loaded route / component;
2. Run NPM watch
3. Make a change
4. Refresh the page (you now SHOULD see the updated component, but it will show the old one)
5. Cancel npm run watch;
6. Run `npm run development`
7. You should see the affected changes as expected.

**Comment by ankurk91** [comment]
Why dont you use hmr mode
```
npm run hot
```

**Comment by weerdm** [comment]
Sure, but `npm run watch` should also work as expected?

**Comment by weerdm** [comment]
Found the problem. Because I was still calling .version() in my webpack.mix.js file, it was not working expected.
