### ISSUE TITLE
Installing laravel mix prints SyntaxError: Unexpected end of JSON

### ISSUE THREAD

**Issue by azatakmyradov** [JeffreyWay/laravel-mix#1655]
- Laravel Mix Version: #.#.# (`npm list --depth=0`): 
- Node Version (`node -v`): v8.11.2
- NPM Version (`npm -v`): 5.6.0
- OS: Mac OS

### Description:

I just ran `laravel new project` and `npm install` inside of the project.

But if laravel-mix exist in my package.json, it prints this error:

`npm http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-for-of 10789ms attempt #2 (from cache)`

`npm http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-destructuring 11482ms attempt #2 (from cache)`

`npm http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-computed-properties 11492ms attempt #2 (from cache)`

`npm verb stack SyntaxError: Unexpected end of JSON input while parsing near '...ax-trailing-function-'`
`npm verb stack     at JSON.parse (<anonymous>)`
`npm verb stack     at parseJson` `(/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)`
`npm verb stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)`
`npm verb stack     at <anonymous>`
`npm verb stack     at process._tickCallback (internal/process/next_tick.js:188:7)`
`npm verb cwd /Users/azatakmyradov/code/tests`
`npm verb Darwin 17.5.0`
`npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "laravel-mix" "--save-dev" "--verbose"`
`npm verb node v8.11.2`
`npm verb npm  v5.6.0`
`npm ERR! Unexpected end of JSON input while parsing near '...ax-trailing-function-'`
`npm verb exit [ 1, true ]`

Without laravel-mix, it works fine.

Could you please help me to fix this issue. I searched and tried everything I could find. I tried to clean the cache.

**Comment by ankurk91** [comment]
It seems there is an issue from npm itself.
Try again from scratch,it should work fine

**Comment by azatakmyradov** [comment]
@ankurk91 i tried from scratch but it doesn't install it

**Comment by ankurk91** [comment]
Clean your npm cache

https://github.com/npm/npm/issues/19072


https://github.com/vuejs-templates/webpack/issues/990

**Comment by azatakmyradov** [comment]
@ankurk91 I have already tried it. I think I should try down-grading node. That is the only thing I didn't try.

**Comment by milap-virtueinfo** [comment]
@azatakmyradov 
@ankurk91 
Which are the steps for downgrading the node?
I used following version
node -v  => v10.1.0
npm -v  => 5.6.0

I have same issue tried out uninstall, install, cache clear everything.
still getting error while making new application by command ng new my-app-ang.

On same server I used react, so not possible to downgrade node for me. Is there any other solutions?

**Comment by ankurk91** [comment]
Do you know about nvm ?
https://github.com/creationix/nvm

**Comment by azatakmyradov** [comment]
@milap-virtueinfo Actually downgrading didn't help either. However, I tried using yarn instead through a proxy:
`yarn install --proxy http://127.0.0.1:1087`

In my case problem was related to the network. I was able to install laravel-mix with this. But even though I got an issue with libpng I able to compile.

**Comment by milap-virtueinfo** [comment]
@ankurk91  @azatakmyradov 
thank you for your reply, I fixed one by one error during installation. And it run successfully on my machine.
No needed to downgrade the version.
Issue was web pack related file.
