### ISSUE TITLE
Doesn´t work with file-matcher

### ISSUE THREAD

**Issue by giolvani** [JeffreyWay/laravel-mix#1659]
I have js files in differents directories, and for each file I want "mix" this. To find these files I am using a third party lib (https://www.npmjs.com/package/file-matcher), and the mix api does not work in that callback.

The following code, works normaly:
```javascript
let mix = require('laravel-mix');
mix.js('src/file.js', 'dest/file.js');
```

But, the next code, does not work:
```javascript
let mix = require('laravel-mix');
let fm = require('file-matcher');
let fileMatcher = new fm.FileMatcher();
fileMatcher.find({
    path: path.resolve(__dirname, 'src'),
    recursiveSearch: true,
    fileFilter: { fileNamePattern: '**/*.js' } })
    .then(function (files) {
         for (file of files){
            mix.js(file, 'dest/js/');
        }       
    });
```

It doesn´t throw any errors or messages, just no one file is compiled.
Can any good soul help me?

**Comment by ankurk91** [comment]
We can not force mix to run multiple time in a single run.
However original webpack allows.

**Comment by giolvani** [comment]
@ankurk91 tks!
