### ISSUE TITLE
Production mode seems to run css purification even though I have not turned it on

### ISSUE THREAD

**Issue by sunnyjayjay** [JeffreyWay/laravel-mix#1661]
- Laravel Mix Version: 2.1.11 (`npm list --depth=0`)
- Node Version (`node -v`): 8.9.1
- NPM Version (`npm -v`): 4.0.2
- OS: Windows 10

### Description:
npm run prod or npm run production creates a public/css file that excludes some of the css styles that are used in the app. Running npm run dev is fine. 

The problem is in the public/css/artlook.css file.

### Steps To Reproduce:

This is my webpack.mix.js code:

    mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .styles(['resources/assets/css/artlook.css',
        'resources/assets/css/vtabs.css',
        'resources/assets/css/browse.css'
    ], 'public/css/artlook.css')
    .styles(['resources/assets/css/reports.css'], 'public/css/reports.css')
    .scripts(['resources/assets/js/pages/contacts-index.js'], 'public/js/pages/contacts-index.js')
    .scripts(['resources/assets/js/pages/contacts-show.js'], 'public/js/pages/contacts-show.js')
    .scripts(['resources/assets/js/pages/signup-artist.js'], 'public/js/pages/signup-artist.js')
    .scripts(['resources/assets/js/pages/signup-gallery.js'], 'public/js/pages/signup-gallery.js')
    .scripts(['resources/assets/js/passwords.js'], 'public/js/passwords.js')
    .scripts(['resources/assets/js/matchHeight.js'], 'public/js/matchHeight.js');

**Comment by ankurk91** [comment]
You can disable the purity css , see docs

**Comment by sunnyjayjay** [comment]
As I said in the original post, purify css is not turned on.
