### ISSUE TITLE
`mix.copy();` tries to minify JavaScript (includes reduced test case)

### ISSUE THREAD

**Issue by blakewatson** [JeffreyWay/laravel-mix#1666]
- Laravel Mix Version: 2.1.11 (`npm list --depth=0`)
- Node Version (`node -v`): 8.1.3
- NPM Version (`npm -v`): 5.0.3
- OS: macOS 10.13.4

### Description:

When using `mix.copy();` to copy a JavaScript file, Mix tries to minify the file if NODE_ENV=production. If it hits ES2015 syntax, Mix throws an error and recommends using `mix.babel()`.

### Steps To Reproduce:

1. Follow instructions for standalone install of Mix verbatim, including making an empty directory and copying the mix file and npm scripts.

2. Modify the mix file such that the only mix directive is:

`mix.copy('src/app.js', 'dist/app.js');`

3. Create a file, `src/app.js`, and put the following line of code in it:

`var test = () => console.log('hello');`

4. `npm run production`

**Comment by blakewatson** [comment]
@devcircus Correct me if I am wrong, but isn't `mix.copy()` intended to simply move files as is?

**Comment by devcircus** [comment]
Specifically yes. At least that's how I've always understood it. 
I was thinking in the context of copying a file that is then used in the build.
