### ISSUE TITLE
npm install is not working in laravel mix

### ISSUE THREAD

**Issue by babaneng** [JeffreyWay/laravel-mix#1668]
- Laravel Mix Version: #.#.# (`npm list --depth=0`)
- Node Version (`node -v`): 
- NPM Version (`npm -v`): 
- OS:

**Comment by babaneng** [comment]
Cannot find module '/var/www/html/test.sharpremora.com/node_modules/laravel-mix/setup/webpack.config.js'

**Comment by ankurk91** [comment]
Please fill ISSUE_TEMPLATE properly to get community help
