### ISSUE TITLE
Source map is not generated properly for sass

### ISSUE THREAD

**Issue by iainheng** [JeffreyWay/laravel-mix#167]
I installed Laravel and start a new app via command

`laravel new test`

Source maps are not generated properly for my scss and my `webpack.mix.js` looks like

```
const { mix } = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/assets/js/app.js', 'public/js').sourceMaps();

mix.sass('resources/assets/sass/app.scss', 'public/css').sourceMaps();
```

Example output of `public/css/app.css.map` when I run `npm run production`

`
{"version":3,"sources":[],"names":[],"mappings":"","file":"/css/app.css","sourceRoot":""}
`

while running `npm run dev` produces line below at bottom of `public/css/app.css`

`
/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiIvY3NzL2FwcC5jc3MiLCJzb3VyY2VSb290IjoiIn0=*/
`

**Comment by JeffreyWay** [comment]
You only need to call `.sourceMaps()` once.

I'll take a look.

**Comment by iainheng** [comment]
Just tried to call `.sourceMaps()` once but with same result.

Here is my updated `webpack.mix.js` 

```
const { mix } = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/assets/js/app.js', 'public/js');

mix.sass('resources/assets/sass/app.scss', 'public/css').sourceMaps();
```

**Comment by SebastianS90** [comment]
Could my PR #166 help here, i.e. applying `?sourceMap` to all loaders?

**Comment by webmarkelov** [comment]
Alternatively there is a solution  -> **Support for less-loader**  https://github.com/bholloway/resolve-url-loader/pull/41

fix sass and less sourceMap:

```javascript
loader: extractPlugin.extract({
                fallbackLoader: 'style-loader',
                loader: [
                    'css-loader?sourceMap',
                    'postcss-loader',
                    'resolve-url-loader',
                    (Mix.cssPreprocessor == 'sass') ? 'sass-loader?sourceMap&precision=8' : 'less-loader?sourceMap'
                ]
            })
```

**Comment by JeffreyWay** [comment]
I've merged @SebastianS90's PR, so I think that should fix this. 

I'll tag it shortly. Also, note that we won't create any sourcemaps at all in production now. It's only for dev mode.
