### ISSUE TITLE
Need to reload to see browsersync changes

### ISSUE THREAD

**Issue by octoxan** [JeffreyWay/laravel-mix#1673]
- Laravel Mix Version: 2.1.11
- Node Version (`node -v`): v8.10.0
- NPM Version (`npm -v`): 3.5.2
- OS: Ubuntu Budgie 18.04

### Description:
Running browsersync doesn't inject sass/css changes at all until manually reloading the page. Tried Chrome/Opera/Firefox/Vivaldi. It claims it's working. It is successfully rebuilding the file, it's just not injecting it.

The browsersync script tag is even in the footer on localhost:3000.

Also, I don't have this problem with gulp + browsersync.

### Steps To Reproduce:
Create new project (I'm using Magento 1.9.x), make this your mix file:

```
mix.options({
    processCssUrls: false,
}).sass('skin/frontend/package/theme/src/scss/styles.scss', 'skin/frontend/package/theme/css/')
    .browserSync({
        proxy: 'example.test'
    });
```

**Comment by octoxan** [comment]
Have now tried this on 3 Magento 1 installs with no luck.

Works great in Wordpress, standalone (in the vuecasts/laracasts course), and of course in Laravel. Not sure why it won't inject changes in Magento when regular gulp / browsersync will.

Any chance anyone, maybe @JeffreyWay , has an idea?

**Comment by octoxan** [comment]
Can anyone else confirm this is broken with Magento 1? Or have an idea on how to fix it? Not sure if this repo is still active or not but I thought it was?

**Comment by viktorbijlenga** [comment]
This might be a solution: https://github.com/JeffreyWay/laravel-mix/issues/1686#issuecomment-402742305

**Comment by octoxan** [comment]
Confirmed it works with the following config, for Magento 1.x

```js
mix.options({
    processCssUrls: false,
    })
    .setPublicPath(path.resolve('./'))
    .sourceMaps()
    .sass('skin/frontend/package/theme/scss/styles.scss', 'skin/frontend/package/theme/dist/')
    .version()
    .browserSync({
        proxy: 'example.test',
        files: [
            'skin/frontend/package/theme/dist/*.css',
        ]
    });
```
