### ISSUE TITLE
Unable to load svg file contents as a module

### ISSUE THREAD

**Issue by dimitarsi** [JeffreyWay/laravel-mix#1675]
Hi all,
I have been struggling with this problem for a while now, hope the you could help me.

I am unable to provide webpack configuration for loading svg file contents as js module. Instead the module returns string value set to `/images/[name].svg`. 
The following configuration doesn't work.
``` js
const svgLoader =  {
    test: /\.svg$/,
    // loader: 'svg-inline-loader'
    // loader: 'raw-loader'
    loader: 'html-loader',
    options: {
        publicPath: mix.resourceRoot
    }
};

mix.webpackConfig({
    module: {
        rules: [ svgLoader ]
    }
});
```
I have tried with a number of alternative loaders `svg-inline-loader`, `raw-loader`, still doesn't work.
My current workaround is
``` js
const svgLoader =  {
    test: /\.html$/,
    loader: 'html-loader',
    options: {
        publicPath: mix.resourceRoot
    }
};
```
changing the test from `/\.svg/` to `/\.html/` and renaming the svg file to html file.
However this is a bit disappointing and frustrating. 
I am doing something wrong here?

**Comment by ankurk91** [comment]
Try to disable image optimisation

```js
mix.options({
  imgLoaderOptions: {
    enabled: false
  },
});
```
