### ISSUE TITLE
Cannot compile Sass files from a directory by using fs.readdir

### ISSUE THREAD

**Issue by mnrafg** [JeffreyWay/laravel-mix#1680]
- Laravel Mix Version: 2.1.11
- Node Version: v8.11.2
- NPM Version: 4.6.1
- OS: Windows 10 x64

### Description:
However it may not be a bug but, why the following code is not working when I run `npm run dev`?

```
let mix = require('laravel-mix');
const fs = require('fs');

// Compile all Sass files from resources/assets/sass/pages
fs.readdir('resources/assets/sass/pages/', (error, files) => {
  files.forEach(file => {
    mix.sass('resources/assets/sass/pages/' + file, 'public/assets/css/pages');
  });
});
```

### Steps To Reproduce:
Just put the upper code snippet in your `webpack.mix.js` file and enter `npm run dev` in the terminal.

**Comment by ankurk91** [comment]
Can you try your code with `fs.readdirSync`?

**Comment by robbyrice** [comment]
Could you post the exact error your are seeing? Also, I would recommend upgrading your version of NPM.
