### ISSUE TITLE
copy and copyDirectory do not update in real time with NPM RUN WATCH

### ISSUE THREAD

**Issue by sipy** [JeffreyWay/laravel-mix#1684]
- Laravel Mix Version: 2.1.1
- Node Version:  8.9.3
- NPM Version: 5.5.1
- OS: Windows 10

### Description:
How can I copy a folder structure to the `public/` folder in real time using the watcher `npm run watch`? Currently the files are copied only when you run `npm run watch` the first time.

### Steps To Reproduce:

1. Create a folder `img` inside `resources/assets/`
2. Create a laravel mix with: `mix.copy('resources/assets/img/', 'public/img', false)` or `mix.copyDirectory('resources/assets/img/', 'public/img')` 
3. Add an image inside `resources/assets/`
4. Run  `npm run watch`
5. The image is correctly copied inside ` public/img` 
6. Now add another image inside inside `resources/assets/` (with the watcher still running)
7. The image is not copied inside ` public/img` in real time until you stop the watcher and run  `npm run watch` again

**Comment by morcegon** [comment]
Same here.

**Comment by edgarravenhorst** [comment]
Same here.

**Comment by dsktschy** [comment]
I created the plugin to resolve this issue.

[laravel-mix-copy-watched](https://www.npmjs.com/package/laravel-mix-copy-watched)

The `copyWatched` and `copyDirectoryWatched` methods has the same usage as [the `copy` and `copyDirectory` methods](https://laravel-mix.com/docs/4.0/copying-files).

```js
mix.copyWatched(from, to);
mix.copyWatched('from/regex/**/*.txt', to);
mix.copyWatched([path1, path2], to);
mix.copyDirectoryWatched(fromDir, toDir);
```

With the base option, it is also possible to keep a hierarchical structure (like Gulp).

```js
mix.copyWatched('resources/images/**/*', 'public/images', { base: 'resources/images' });
```

Try it !

**Comment by sipy** [comment]
Nice work @dsktschy! I would like to see this feature in the main package as well...

**Comment by sipy** [comment]
This topic should not be closed yet

**Comment by dangelion** [comment]
Any progress on this? I think Laravel Mix should really has to copy files on watch. I tried laravel-mix-copy-watched plugin but it doesn't work that well.

**Comment by martincarvalho** [comment]
Still having this issue

**Comment by michapixel** [comment]
`laravel-mix-copy-watched` is not a real solution, as it doesn't take sub-subfolders into accout, e.g. files from there get copied to subfolder. That's a complete mess.
