### ISSUE TITLE
"npm audit" shows 19 vulnerabilities

### ISSUE THREAD

**Issue by Olian04** [JeffreyWay/laravel-mix#1685]
- Laravel Mix Version: 2.1.11
- Node Version: 9.4.0
- NPM Version:  6.0.0
- OS: Ubuntu 17.04

### Description:
The "new" audit feature of npm complains about 19 detected vulnerabilities in the current release of laravel-mix.
```
+ laravel-mix@2.1.11
added 1414 packages from 710 contributors in 247.968s
[!] 19 vulnerabilities found [19248 packages audited]
    Severity: 19 moderate
```

### Steps To Reproduce:

```
npm i -D laravel-mix
```

**Comment by hebbet** [comment]
duplicate of #1633

**Comment by JeffreyWay** [comment]
Fixed in Mix 4.
