### ISSUE TITLE
Unsure if NPM issue, or mix issue with ! in folder path...

### ISSUE THREAD

**Issue by alturic** [JeffreyWay/laravel-mix#1692]
Unsure if this is an NPM issue, or a laravel-mix issue, but npm run dev complains about the mock-entry.js file not being found, when there is an ! in any part of the folder path.

Ex: D:\Dropbox\IDE Projects\!port\directoryname simply renaming the !port folder to port, everything worked fine.

Latest versions of npm, laravel, laravel-mix (as of 6/23/2018).

**Comment by ankurk91** [comment]
Can you fill the ISSUE_TEMPLATE and tell us about your platform?
