### ISSUE TITLE
Sass and Less not compiling together

### ISSUE THREAD

**Issue by mohamedsabil83** [JeffreyWay/laravel-mix#170]
Hi,
with laravel-elixir, I can compile both sass and less like .less().sass() then combine the result in one file.
Now, with laravel-mix, It compiles the last one less() or sass().
What have to do to compile both in a single (npm run dev)?

**Comment by SebastianS90** [comment]
duplicate, see #159

**Comment by mohamedsabil83** [comment]
Thank you @SebastianS90 for replying. Search first but no result found so open it.

@JeffreyWay hope to make it compiling together a.s.a.p. cause many times work with two frameworks one with sass and the other with less.

Any way to convert less file to sass or the opposite?

**Comment by JeffreyWay** [comment]
Stick with Elixir if you need that kind of flexibility. Right now, you can only compile Sass or Less.

**Comment by mohamedsabil83** [comment]
Great!! Any addition to let elixir work in #L5.4?

**Comment by mohamedsabil83** [comment]
Just using gulp file .. sorry stupid quiz :smile:
