### ISSUE TITLE
disableSuccessNotifications() still shows success notifications

### ISSUE THREAD

**Issue by shkabo** [JeffreyWay/laravel-mix#1700]
- Laravel Mix Version: 2.1.11 (`npm list --depth=0`)
- Node Version (`node -v`): 8.10.0
- NPM Version (`npm -v`): 6.1.0
- OS: Windows 10 x64
---
- Laravel Mix Version: 2.1.11 (`npm list --depth=0`)
- Node Version (`node -v`): 8.11.1
- NPM Version (`npm -v`): 6.1.0
- OS: OSX 10.13.3

### Description:
As title says `disableSuccessNotifications()` doesn't seem to work. I have tried same setup on two machines, but same result.

On the other hand `disableNotifications()` works as intended in my case.

### Steps To Reproduce:
- Install latest Laravel
- Run composer and npm install
- Change to use react instead of vuejs `php artisan preset react`
- Do necessary update after change `npm install && npm run dev`
- Add `mix.disableSuccessNotifications();` to `webpack.mix.js`
- Run `npm run dev` again to check if it's going to display success message
- Success message appears

**Comment by tsaltena** [comment]
Having the same issue here, disableNotifications works, disabling successNotifications doesn't.

**Comment by AlexMartinFR** [comment]
Same issue here, I've found what I think is the issue though:

When npm is **watching** every changes to your files:
- a **single initial successful build notification** is displayed
- for every subsequent successful builds, **no other notifications are thrown**
- failed builds' notifications are still thrown, as intended

If you launch `npm run dev`manually everytime, you can easily think the `.disableSuccessNotifications()` option doesn't work at all.

Can you try with `npm run hot`, or `npm run dev -watch--poll` and see if it's working the way I described it?

PS : Be sure to launch your `npm run` command **after saving** your webpack.mix.js file.

**Comment by superern** [comment]
having the same problem with laravel-mix 2

**Comment by proimage** [comment]
I can confirm what @AlexMartinFR said is what's happening; a single success notification is sent, but not subsequent success notifications. I'm using `npm run watch`.
