### ISSUE TITLE
SASS is recompiled while editing only JS in watch mode

### ISSUE THREAD

**Issue by lukchojnicki** [JeffreyWay/laravel-mix#1706]
- Laravel Mix Version: 2.1.11
- Node Version (`node -v`):  6.11.4
- NPM Version (`npm -v`): 3.10.10
- OS: Windows 10

### Description:

I'm using laravel mix (with LaraveI 5.6). I don't get it why when I'm editing my .js file in watch mode, then .sass is also recompiled with every .js change (wasting time). In other way around, while editing .sass only .sass is compiled, .js not, like it should be.

### Steps To Reproduce:

My app.js for testing is empty.

My webpack.mix as basic as possible:

```
let mix = require('laravel-mix');
mix.js('resources/assets/js/app.js', 'public/js');
mix.sass('resources/assets/sass/app.scss', 'public/css');
```

Let's add just some comment in .js file. Console output:

```
10% building modules 0/1 modules 1 active ...on\www\test\resources\assets\js\app.js
 90% chunk assets processing
 94% asset optimization DONE  Compiled successfully in 143ms16:25:18


 95% emitting       Asset     Size  Chunks             Chunk Names
  /js/app.js  3.88 kB       0  [emitted]  /js/app
/css/app.css   226 kB    0, 0  [emitted]  /js/app, /js/app
```

Usually I'm getting 150-200ms time. But if i remove mix.sass from webpack.mix, then compile time is around 100ms. It's not that bad with this example, but with real source, sourcemaps and other plugins then it is matter of seconds. 
Please help me, how to get rid of it?

**Comment by lukepolo** [comment]
This is how webpack works, currently `scss` is not a first class citizen and must be tagged along with your `js`. Then it gets stripped out with the `extractTextPlugin` (at least in this package)

**Comment by lukepolo** [comment]
They are working on promoting `css` and other types as first class citizens to improve performance!!!! Really excited about it, but who knows when it will come out
