### ISSUE TITLE
Cannot compile and combine multiple files.

### ISSUE THREAD

**Issue by jeewandhakal25** [JeffreyWay/laravel-mix#1707]
I want to combine all assets inside folder 'jeevan' followed by folder structure 'public/admin/js/app.js'

This is in my webpack.mix.js
`mix.combine(['packages/jeevan/*/public/admin/js/app.js'], 'public/assets/admin/js/app.js');`

This is what i've written in app.js
`require('./modules/adminlte');`

I was expecting full adminlte js but what i got is in compiled js file.
`require('./modules/adminlte');`

Help Needed !!!

**Comment by ankurk91** [comment]
You may want to use glob, see example.

https://github.com/JeffreyWay/laravel-mix/issues/1571#issuecomment-377688777

BTW: `mix.js()` support globs already
