### ISSUE TITLE
UglifyOptions are ignored

### ISSUE THREAD

**Issue by achinthas** [JeffreyWay/laravel-mix#1712]
- Laravel Mix Version: 2.1.11
- Node Version (`node -v`): 8.11.1
- NPM Version (`npm -v`): 5.6.0
- OS: Windows 10

### Description:
In the webpack.mix.js when defined the uglifyOptions, it will be getting ignored. When I disable the mangle, but it keeps happening.

### Steps To Reproduce:
Use the following webpack.mix.js configration. 
```
mix.options({
    uglify: {
        uglifyOptions: {
          mangle: false
        }
    },
});

mix.combine([
     'node_modules/jquery/dist/jquery.js',
     'node_modules/bootstrap/dist/js/bootstrap.js',
     'node_modules/angular/angular.js',
     'node_modules/popper.js/dist/umd/popper.js',

   ], 'public/js/vendor.js')

   .combine('resources/assets/js/**/*.js', 'public/js/app.js')
   
   .less('resources/assets/less/app.less', 'public/css')

   .version();
```

**Comment by ankurk91** [comment]
I am not sure if combine method minify the code.
You might want to use `minify()` method instead

https://github.com/JeffreyWay/laravel-mix/blob/master/docs/concatenation-and-minification.md

**Comment by 100phel** [comment]
I have the same issue.
Solution is in changing line 200 in laravel-mix/src/File.js (function called minify):

`this.write(uglify.minify(this.path(), Config.uglify).code);`
to
`this.write(uglify.minify(this.path(), Config.uglify.uglifyOptions).code);`

**Comment by ankurk91** [comment]
i agree, someone has already raised this issue before.

**Comment by 100phel** [comment]
I found this: 
https://github.com/JeffreyWay/laravel-mix/commit/19e057dd1d5b8b3f4abb4a9ff13c3fa2e2586baf#diff-182a1c65ef29ba6e05eee122c71511e6

So, just update to the latest version and it will solve the issue.

**Comment by achinthas** [comment]
This was fixed in the latest version.
