### ISSUE TITLE
ignore compile same files

### ISSUE THREAD

**Issue by vahidalvandi** [JeffreyWay/laravel-mix#1716]
i have large project . laravel mix in large project not have solution for ignore compile same plugins like bootstrap-scss , in each change bootstrap-scss recompiling and this not good.

how i can set interval for one file for example just compile one time after run ``` npm run watch ```

thank you

**Comment by vahidalvandi** [comment]
i found simple way .

just create another mix like bellow

let mixFirst = require('laravel-mix');
let mixSecond  = require('laravel-mix');


//First mix
mixFirst.js(moduleFolder + '/Base/src/Asset/js/Base.js',		'public/app/js')
	.sass(moduleFolder + '/Base/src/Asset/scss/Base.scss',	'public/app/css');

//second mix
mixSecond.js(moduleFolder + '/Base/src/Asset/js/Base.js',		'public/app/js')
	.sass(moduleFolder + '/Base/src/Asset/scss/Base.scss',	'public/app/css');

**Comment by ankurk91** [comment]
@vahidalvandi 
I didn't know about it.
I will try it tomorrow and if this worked, it should go to docs.
Thanks

**Comment by nazaninhesari** [comment]
yes it worked !
