### ISSUE TITLE
Can't catch 'hidden.bs.modal' in vuejs.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [JeffreyWay/laravel-mix#1720]
- Laravel Mix Version: 2.1.11
- Node Version (`node -v`): 8.11.3
- NPM Version (`npm -v`): 6.1.0
- OS: macOS High Sierra
```
├── axios@0.18.0
├── bootstrap@4.1.2
├── cross-env@5.2.0
├── font-awesome@4.7.0
├── jquery@3.3.1
├── jquery.quicksearch@2.4.0
├── laravel-mix@2.1.11
├── lodash@4.17.10
├── multiselect@0.9.12
├── pc-bootstrap4-datetimepicker@4.17.50
├── popper.js@1.14.3
├── sweetalert2@7.25.6
└── vue@2.5.16
```
### Description:
When I want to catch 'hidden.bs.modal' to clear data in variable when hide modal.

But it's not working.

So, I'm try something in `webpack.mix.js`

My webpack file have this code

```
mix
    .autoload({
        'jquery': ['$', 'window.jQuery', 'jQuery'],
        'vue': ['Vue','window.Vue'],
        'moment': ['moment','window.moment'],
    })
```

To solve some problem when use package `pc-bootstrap4-datetimepicker`.

I try to remove it out. It can work with out `.autoload()`.

So I'm not know about `mix` to much, How to solve this problem.

**Comment by ankurk91** [comment]
This is nowhere related to laravel mix, you should be using public forums like

https://forum.vuejs.org/
OR
https://stackoverflow.com/tags/vue.js/new
