### ISSUE TITLE
hmrOptions in config.js

### ISSUE THREAD

**Issue by warlord0** [JeffreyWay/laravel-mix#1721]
- Laravel Mix Version: 2.0.0 (`npm list --depth=0`)
- Node Version (`node -v`): 8.11.3
- NPM Version (`npm -v`): 6.2.0
- OS: Debian 9 Stretch

### Description:

Within `config.js` I notice that `hmrOptions {}` are hard coded to only serve on localhost:8080.

### Steps To Reproduce:

When developing on a remote system or virtual guest OS it would be good to have hmr run on the host/port specified by the `run hot` parameters such as:

```
$ npm run hot --host 192.168.56.2 --port 8080
```

**Comment by schniper** [comment]
Use
```
mix.options({
    hmrOptions: {
      host: 'bla'
      port: 8081
    }
  })
```

**Comment by warlord0** [comment]
I actually dropped this in, so it uses the --host option. But there's probably a tidier way.
```javascript
/**
* Hostname and port used for the hot reload module
*
* @type {Object}
*/
hmrOptions: {
  host: (process.argv.includes('--host')) ? process.argv[process.argv.indexOf('--host')+1] : 'localhost',
  port: '8080'
},
```

**Comment by mvdnbrk** [comment]
Laravel Mix documentation is now at [laravel-mix.com](https://laravel-mix.com).

Added a section about setting the hmrOptions with `mix.options` [here](https://github.com/mvdnbrk/laravel-mix-docs/commit/066918565bd13c1e6cb2692a342c024595ff1da9).

**Comment by warlord0** [comment]
Sorted thanks.

**Comment by warlord0** [comment]
Sorted thanks.
