### ISSUE TITLE
Laravel Mix with Functional Javascript

### ISSUE THREAD

**Issue by burakerdem** [JeffreyWay/laravel-mix#1722]
I want to write Javascript with the classical functional way. I know there are lots of great features with modern Javascript but because I'm a backend developer, I don't want to spend my time with learning modern Javascript. I use jQuery and it's more than enough for me to write classical functional Javascript.

    function someSimpleFunction() {
        // do some simple stuff
    }

So here's the problem. When I write functional Javascript, Laravel Mix removes all my functions. It's probably because of Webpack (which I'm not sure) but I want all my functions remain in the final compiled JS file.

How can I prevent Laravel Mix or Webpack removing my Javascript functions?

Here is my **simplifed** `webpack.mix.js` file.

    mix.less('resources/assets/less/app.less', 'public/assets/css')
        .options({processCssUrls: false})
        .js('resources/assets/js/app.js', 'public/assets/js/app.js')
        .copyDirectory('resources/assets/img', 'public/assets/img');

    if (mix.inProduction()) {
        mix.version();
    }

And here is my **simplified** `resources/assets/js/app.js` file

    // there are lots of functions in functions.js which never compiled into the final JS file
    require('./functions.js');

    require('./events.js');
    // some other js files

`app.js` never contain functions from `functions.js`.

**Comment by warlord0** [comment]
If you're going to write traditional why not just use copy instead of processing them with js?

**Comment by burakerdem** [comment]
@warlord0 I'm copying images and fonts but versioning, concatenating and uglifying JS and LESS files. Laravel Mix is great for my needs, only if I could manage to protect my JS functions.

Is it Webpack that removes functions? If it is, than I'm sure there must be an option to preserve functions but I couldn't find any.
