### ISSUE TITLE
Laravel 5.6 "npm run dev" doesn't work.

### ISSUE THREAD

**Issue by MIMAXUZ** [JeffreyWay/laravel-mix#1723]
I am installing laravel app and NPM, But when i rund <code>npm run dev</code> i have some problems.
</br> 
So i did like that.
</br>
I use this commands : </br>
<pre>
<code>
//My Project FOlder
cd C:\ospanel\domains\localhost
//Installed Latest Version Of NPM
npm install npm@latest -g 

//Installing CROSS-ENV
npm install --save-dev cross-env
and
when I run npm run dev I have a problem.
</code>
</pre>

<pre>
<code>
C:\Users\WSMG>
C:\Users\WSMG>cd C:\ospanel\domains\localhost

C:\OSPanel\domains\localhost>npm install npm@latest -g
C:\Users\WSMG\AppData\Roaming\npm\npx -> C:\Users\WSMG\AppData\Roaming\npm\node_modules\npm\bin\npx-cli.js
C:\Users\WSMG\AppData\Roaming\npm\npm -> C:\Users\WSMG\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
+ npm@6.2.0
updated 1 package in 12.07s

C:\OSPanel\domains\localhost>npm install --save-dev cross-env
npm notice created a lockfile as package-lock.json. You should commit this file.
+ cross-env@5.2.0
added 10 packages from 8 contributors and audited 10 packages in 1.682s
found 0 vulnerabilities

C:\OSPanel\domains\localhost>
C:\OSPanel\domains\localhost>npm run dev

> @ dev C:\OSPanel\domains\localhost
> npm run development

> @ development C:\OSPanel\domains\localhost
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

The system can not find the specified path.
events.js: 183
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules\webpack\bin\webpack.js ENOENT
    at notFoundError (C:\OSPanel\domains\localhost\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\OSPanel\domains\localhost\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\OSPanel\domains\localhost\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\WSMG\AppData\Roaming\npm-cache\_logs\2018-07-26T09_45_11_656Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\WSMG\AppData\Roaming\npm-cache\_logs\2018-07-26T09_45_11_703Z-debug.log

C:\OSPanel\domains\localhost>
C:\OSPanel\domains\localhost>
</code>
</pre>
</br>
This problem occurs when I run NPM.
</br>
I chacked GOOGLE but couldn't find solution for my problem.
<br>
I am using WIndows, And OpenServer, NodeJS Command Promp
</br> 
Also I used <code> npm cache clean --force</code> command and retry to install. But no solution.
Thanks.

**Comment by hypertrading** [comment]
I have the same problem and haven't found a solution yet.

**Comment by MIMAXUZ** [comment]
I have found solution. I removed old nodejs and nom. After than i reinstalled it. And updated to 6.2.x after than i cleaned all cacha. And i run npm imstall on console. All as well.
