### ISSUE TITLE
How I can use global sass variabels in .vue files?

### ISSUE THREAD

**Issue by GrimJacky** [JeffreyWay/laravel-mix#1725]
I want to use [this](https://vue-loader.vuejs.org/guide/pre-processors.html#sharing-global-variables) in my app.
In vue.config.js I'm using this (without laravel-mix):
```
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        data: `@import "@/assets/scss/variables.scss"; 
        @import "@/assets/scss/fonts.scss";`
      }
    }
  }
}
```
How I can use this with laravel-mix? I can't find documentation for this.
So who can help me with this?

**Comment by ankurk91** [comment]
Laravel mix is using an older version of vue-loader while you are reading the latest version docs.

**Comment by GrimJacky** [comment]
@ankurk91 I'm didn`t understand your point. Can you give me documentation example for my case?

**Comment by ankurk91** [comment]
There is no easy way to use vue-loader v15 in laravel mix right now.

Laravel mix is using v13 as of now.
This feature might be available in v13 too.
The docs for older version can only be found in their GitHub repo.

**Comment by alnutile** [comment]
@ankurk91 any follow up on this? You figure it out

**Comment by ankurk91** [comment]
I could not find this feature in v13 docs

https://github.com/vuejs/vue-loader/tree/v13.7.0/docs/en

**Comment by ankurk91** [comment]
You might want to read this
https://github.com/vuejs/vue-loader/issues/328
