### ISSUE TITLE
Problems with JS/jQuery imports

### ISSUE THREAD

**Issue by moso** [JeffreyWay/laravel-mix#1730]
- Laravel Mix Version: 2.1.11
- Node Version: 8.10.0
- NPM Version (`npm -v`): 6.1.0
- OS: Ubuntu 18.04.1

### Description:

I have a lot of JS imports in my main JS-file. Many of them are modules that essentially are just split-up jQuery functions for specific things. Such as init of this and that slider, etc. It's split up so it's easier to maintain.

Even though jQuery is added to my `mix.config` like so:
```javascript
mix.js('src/js/main.js', 'js/')
   .sass('src/sass/main.scss', 'css/', {
       outputStyle: 'nested'
   })
   .autoload({
       jquery: ['$', 'jQuery', 'jquery', 'window.jQuery'],
       'popper.js/dist/umd/popper.js': ['Popper'],
   })
   .extract(['jquery', 'popper.js', 'bootstrap']);
```

...I still have to import jQuery manually in `main.js`, like so:
```javascript
// jQuery
window.$ = $;
window.jQuery = window.$ = require('jquery');
```

Most of my modules work fine. But I get the odd `$(...)<import> is not defined`, where `<import>` being an imported npm package, eg, owl.Carousel. These modules are set up the exact same way. However, the only fix to these specific owl.Carousel-errors is to have jQuery in my `<head>`-tag, which isn't optimal.

I know I can import npm packages in two ways:
- Regular ol' school: `var Package = require('package');`
- And ES6: `import * as Package from 'package';`

But again, I get the odd `Module is not defined` errors.

Is there anything I'm doing wrong here, or am I stretching Mix too far?

Thanks!

**Comment by ankurk91** [comment]
Please share the exact code that you are using for the Carousel library.


I suspect you have imported eat code from node_modules and Babel loader does not trabspile vendor code by default.

**Comment by moso** [comment]
@ankurk91: Here's the hopefully relevant code: https://gist.github.com/moso/502a005f1dd53dfb66f47d779457984b

- First is the `main.js` with all the imports.
- Next is `package.json` with some of the info omitted. But there you can see packages, versions, etc.
- Third is an example of one of those init modules, just made to keep things seperated.
- And lastly we have `webpack.mix.js` for the Mix config.

Thanks!

**Comment by ankurk91** [comment]
Laravel mix uses webpack under the hood.

Several issue has been reported for this before. see
https://github.com/OwlCarousel2/OwlCarousel2/issues/1866

Can you try to update your main.js code with
```
// main.js
// use ES6 import for jQuery too
import jQuery from 'jquery';
window.$ = window.jQuery = jQuery;
```
I believe you have these lines in your blade already
```blade
<script src="{{ mix('js/manifest.js') }}"></script>
<script src="{{ mix('js/vendor.js') }}"></script>
<script src="{{ mix('js/app.js') }}"></script>
```
