### ISSUE TITLE
Dep extract-text-webpack-plugin must be upgraded?

### ISSUE THREAD

**Issue by danaki** [JeffreyWay/laravel-mix#1732]
- Laravel Mix Version: 2.1.11
- Node Version (`node -v`): v10.7.0
- NPM Version (`npm -v`): 6.2.0
- OS: OSX

### Description:

Got the error described here https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701

People in comments suggest to upgrade to extract-text-webpack-plugin@next or 4.0.0-beta, laravel-mix depends on ^3.0.2 

### Steps To Reproduce:

Follow installation instructions from this repo: https://github.com/cretueusebiu/laravel-vue-spa

**Comment by ankurk91** [comment]
https://github.com/webpack-contrib/extract-text-webpack-plugin/releases/tag/v4.0.0-alpha.0


extract-text-webpack-plugin@next requires webpack v4. But laravel mix is using v3.

It should be a major change.

**Comment by ruchern** [comment]
`ExtractTextWebpackPlugin` should now be replaced with `MiniCssExtractPlugin` since the former package is no longer maintained.
