### ISSUE TITLE
"Unknown Word" when running npm run production

### ISSUE THREAD

**Issue by bellwood** [JeffreyWay/laravel-mix#1734]
- Laravel Version: 5.6.31
- Laravel Mix Version: laravel-mix@2.1.11
- Node Version: v8.11.3 
- NPM Version: 6.1.0 
- OS: CentOS Linux release 7.5.1804 (Core)

When running `npm run production` I get the following error:

```
ERROR in ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/lib??postcss!./resources/assets/sass/custom.sass
Module build failed: Syntax Error

(182:11) Unknown word
  180 | ******************************/
  181 | @each $staff in $staff-list {
> 182 |   .team-#{$staff} {
      |           ^
  183 |   background: url("/img/team-#{$staff}-bg.jpg");
  184 |   background-size: cover;
```
(Note: the carrot is under the dollar sign of the `$staff` variable)

### webpack.mix.js
```
let mix = require('laravel-mix');
mix.copyDirectory('resources/assets/img', 'public/img')
  .js('resources/assets/js/app.js', 'public/js')
  .sass('resources/assets/sass/app.scss', 'public/css')
  .options({processCssUrls: true})
  .version(['public/img']);
```

### app.scss
```
@import url(https://fonts.googleapis.com/css?family=Lato|Roboto|Montserrat);
@import url(custom.sass);
```

**Comment by bellwood** [comment]
So, if I move the contents of `custom.sass` into `app.scss` the error goes away... ¯\_(ツ)_/¯

**Comment by periplox** [comment]
I'm having the same issue here. I thik I've found an explanation:

> Only plain CSS should be allowed in the imported files. Any syntax that would be interpreted differently if it were SCSS should produce an error

https://github.com/sass/sass/issues/556#issuecomment-397771726

Unfortunatle, I don't have a solution when using mix.
