### ISSUE TITLE
Just a question. What is the reasoning behind this vue loader config?

### ISSUE THREAD

**Issue by raniesantos** [JeffreyWay/laravel-mix#1735]
Why does laravel-mix set esModule to `false`?

```
vue: {
    preLoaders: {},
    postLoaders: {},
    esModule: false
},
```

I'm asking because setups provided by vue-cli have this set to `true`. I tend to use `require().default` in specific situations, and using it becomes inconsistent for laravel-mix because this config makes me drop `.default`.

**Comment by ankurk91** [comment]
`esModule: false` option is no longer available in vue-loader v14+, laravel mix is using v13.

It has been set to `false` to keep mix behaviour non breaking

**Comment by ankurk91** [comment]
Of course
