### ISSUE TITLE
Missing Files Throw No Error in 2.1.11

### ISSUE THREAD

**Issue by ethanbeyer** [JeffreyWay/laravel-mix#1739]
- Laravel Mix Version (`npm list --depth=0`): `laravel-mix@2.1.11`
- Node Version (`node -v`): `v6.11.3`
- NPM Version (`npm -v`): `6.0.1`
- OS: `MacOS 10.13.6`

*This is a redux of #627, which is closed and I'm not sure if it's visible anymore.*

### Description:
File paths added to `mix.scripts()` that do not exist do not throw any errors, and the build does not fail.

### Steps To Reproduce:

1. Add a `mix.scripts()` call to an existing laravel setup's `webpack.mix.js`.  
Mine is somethink like `mix.scripts(['random/file/exists-not.js', 'another/non/entity.js'], 'public/assets/js/new.js');` .
3. Run `npm run dev`
4. An empty JS file is created and placed at `'public/assets/js/new.js'`.

According to @JeffreyWay in [June of last year](https://github.com/JeffreyWay/laravel-mix/issues/627#issuecomment-309610524), this was fixed in 1.0.0, but I'm still having the problem.

**Comment by joaolisboa** [comment]
Bump.

Hope this gets looked at. In big projects a small typo can go unnoticed, as I've already seen happen, unless the developer changes into production mode to use the compiled files which should be unnecessary as this should throw an error immediately during the build.

**Comment by ethanbeyer** [comment]
Lack of an error still blows my mind. It is otherwise a wonderful library that I am hella thankful for.

**Comment by ethanbeyer** [comment]
Yo. This is still bad Dev-X.

**Comment by joaolisboa** [comment]
I continue to hope this gets solved. I hate having to triple check things when the library should be capable of at least give a warning.

**Comment by ethanbeyer** [comment]
@joaolisboa we are the only ones! 😭
