### ISSUE TITLE
Make sass an optional dependency

### ISSUE THREAD

**Issue by sebastiandedeyne** [JeffreyWay/laravel-mix#1742]
The `node-sass` package takes notoriously long to install. If you don't even need it, this adds a lot of extra time to `npm install`, which is pretty annoying in deploys.

**Comment by stephan-v** [comment]
This repository is dead there are still pull requests from half a year ago. I'd suggest going over to webpack-encore where your voice will actually be heard.

https://github.com/symfony/webpack-encore

**Comment by sebastiandedeyne** [comment]
New major version would be a perfect opportunity for this :)

**Comment by JeffreyWay** [comment]
Okay, will do.

**Comment by smcyr** [comment]
Would be good to not add node-sass in the dependencies method for #1832. Also, the sass loader work with either node-sass or dart-sass:

> The sass-loader requires webpack as a peerDependency and it requires you to install either Node Sass or Dart Sass on your own. This allows you to control the versions of all your dependencies, and to choose which Sass implementation to use.
