### ISSUE TITLE
IE11 Syntax error

### ISSUE THREAD

**Issue by tunkelominna** [JeffreyWay/laravel-mix#1752]
- Laravel Mix Version: 2.1.11 (`npm list --depth=0`)
- Node Version (`node -v`): 5.6.0
- NPM Version (`npm -v`): 8.9.4
- OS: Win10

### Description:
IE11 throws error SCRIPT1002: Syntax error
app.js (6749,49) which is:
pageSizeOptions: { type: Array, default: () => [10, 20, 40, 80, 100] },

pageSizeOptions is coming from vue2-datatable-component.
This means that mixer does not compile to ES5 correct. 
All my vue components are empty when browser is IE11.

**Comment by ankurk91** [comment]
the Babel loader excludes any module coming from node_modules folder, and will not transpile.

Make sure the package is compatible with IE 11 itself.

**Comment by tunkelominna** [comment]
Thanks, this https://github.com/OneWayTech/vue2-datatable/issues/139 solved my issue.
