### ISSUE TITLE
Option preserveWhitespace does not work.

### ISSUE THREAD

**Issue by mezhevikin** [JeffreyWay/laravel-mix#1753]
- Laravel Mix Version: 2.1.14
- Node Version: v8.11.2
- NPM Version: 6.4.0
- OS: macos 10.13.6

### Description:

 I'd like to remove extra whitespaces from vue templates, but **preserveWhitespace** option does not work.

### Steps To Reproduce:
1. Add code to webpack.mix.js.

```
mix.options({
    vue: {
        preserveWhitespace: false,
    }
});

```
2. Run `npm run dev` or `npm run prod` in terminal.

3. Open public/js/app.js:

```
var staticRenderFns = [
  function() {
    var _vm = this
    var _h = _vm.$createElement
    var _c = _vm._self._c || _h
    return _c("div", { staticClass: "container" }, [
      _c("div", { staticClass: "row justify-content-center" }, [
        _c("div", { staticClass: "col-md-8" }, [
          _c("div", { staticClass: "card card-default" }, [
            _c("div", { staticClass: "card-header" }, [
              _vm._v("Example Component")
            ]),
            _c("div", { staticClass: "card-body" }, [
              _vm._v(
                "\n                    I'm an example component.\n                "
              )
            ])
          ])
        ])
      ])
    ])
  }
]
```

**Comment by ankurk91** [comment]
Could not find such option in Vue loader v13 docs

https://github.com/vuejs/vue-loader/tree/v13.7.0/docs/en

**Comment by mezhevikin** [comment]
@ankurk91 Hi. Thanks for the response.
Do you know why laravel-mix do not use last vue-loader?

I tried add  `"vue-loader": "^15.4.0",` to my package.json, but i'm getting an error:

```
ERROR in ./resources/assets/js/components/Categories.vue?vue&type=template&id=4ec2a982&
Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type.
```

**Comment by ankurk91** [comment]
You can not use latest Vue loader with Laravel mix.
Latest Vue loader will require lots of configuration.

> Do you know why laravel-mix do not use last vue-loader?
This is how open source works.

**Comment by carestad** [comment]
Is this still the case with v4 and v5 that uses vue-loader@v15? I still don't see this working, nor the `whitespace: 'condense'` option

**Comment by fractalf** [comment]
Took a while to figure this one out, but this seems to work..
Ref. https://github.com/JeffreyWay/laravel-mix/issues/2463
```
mix.options({
    vue: {
        compilerOptions: {
            preserveWhitespace: false
        }
    }
})
```
