### ISSUE TITLE
Laravel Mix on Production removes functions from JS file

### ISSUE THREAD

**Issue by kkcodes** [JeffreyWay/laravel-mix#1758]
- Laravel Mix Version: 1.7.2 (`npm list --depth=0`)
- Node Version (`node -v`): 8.9.4
- NPM Version (`npm -v`): 5.6.0
- OS: Ubuntu 18.10

### Description:
I am trying to minify my js scripts, so here is what I am doing in my webpack.mix.js file:

mix.js([
     'resources/assets/js/app.js',
   //  'public/pmc_assets/js/jquery-3.3.1.min.js',
     'public/js/jquery.easing.min.js',
     'public/js/star-rating.min.js',
     'public/js/jquery-ui.min.js',
     'public/js/popper.min.js',
     'public/js/bootstrap.min.js',
     'public/js/script.js',
     'public/js/sweetalert.min.js',
     'public/js/dropzone.js',
     'public/js/snackbar.js',
     'public/js/jquery.limitText.js',
     'public/js/firebase.js',
     // 'public/js/moment.js',
     'public/js/iziToast.min.js',
 ], 'public/js/app.js')
.styles([
    'public/css/snackbar.css',
    'public/css/toastr.css'
], 'public/css/front.css');

if (mix.inProduction()) {
    mix.version();
}

However, everything works perfectly for the command npm run dev, but when I try it in production mode, then for the firebase.js file's code

### Steps To Reproduce:

This is the code for firebase.js file

// Initialize Firebase
var config = {

    apiKey: "SECRET_DATA",

    authDomain: "SECRET_DATA",

    databaseURL: "SECRET_DATA",

    projectId: "SECRET_DATA",

    storageBucket: "SECRET_DATA",

    messagingSenderId: "SECRET_DATA"

  };

  firebase.initializeApp(config);

  var database = firebase.database();

  function connection(userId) {

  var myConnectionsRef = firebase.database().ref('users/'+userId+'/connections');
      // stores the timestamp of my last disconnect (the last time I was seen online)
  var lastOnlineRef = firebase.database().ref('users/'+userId+'/lastOnline');

  var connectedRef = firebase.database().ref('.info/connected');

  connectedRef.on('value', function(snap) {
  if (snap.val() === true) {
    // We're connected (or reconnected)! Do anything here that should happen only if online (or on reconnect)

    var con = myConnectionsRef.push();

    // When I disconnect, remove this device
    con.onDisconnect().remove();

    // Add this device to my connections list
    // this value could contain info about the device or a timestamp too
    con.set(true);

    // When I disconnect, update the last time I was seen online
    lastOnlineRef.onDisconnect().set(firebase.database.ServerValue.TIMESTAMP);
  }

});
    }

    function conReal()
    {

    var userRef_on = firebase.database().ref('users');

    userRef_on.on('value', function(snapshot) {

        var source = $("#image-off").val();

        if(snapshot.val() != null)
        {

            $.each(snapshot.val(), function (key, value) {

                source = $("#image-off").val();

                if(value.connections != undefined)
                {

                    source = $("#image-source").val();

                }

                $('#' + key).attr('src', source);

            });

        }
        else
        {

            $('.img-status').attr('src', source);

        }

    });

}

Any help is appreciated, since I can see the benefits, just don't want to call the file separately.

Thanks!

**Comment by rohan0793** [comment]
Happening to me too

`npm run dev` does a good job but uncompressed JS
`npm run prod` removes code, don't know why

Please help?
