### ISSUE TITLE
mix-manifest.json in different directory

### ISSUE THREAD

**Issue by Berian** [JeffreyWay/laravel-mix#1759]
In webpack.mix.js after **mix** definition jus add this:
`global.Mix.manifest.path = function() {
    return path.join('new_direcotry', this.name);
};`
And now everything will work perfect!

Only keep in mind, that you need rewrite PHP helper function **mix**. To do this, just search in internet how to rewrite helper functions in laravel.

;)

**Comment by ankurk91** [comment]
You no need to rewrite the mix helper
```php
function mix($path, $manifestDirectory = '')
```
It accepts manifest folder as second argument already.

**Comment by Berian** [comment]
@ankurk91 Yes, you can do this, but in build stage manifest will be placed in the default folder.
So you need tell to webpack that manifest need to place in different folder, also this folder will be default for mix helper function and you don't need to change layouts.

**Comment by josegus** [comment]
> You no need to rewrite the mix helper
> 
> ```
> function mix($path, $manifestDirectory = '')
> ```
> 
> It accepts manifest folder as second argument already.

doesn't work
