### ISSUE TITLE
[Feature Request] Support Babel 7

### ISSUE THREAD

**Issue by elliotleelewis** [JeffreyWay/laravel-mix#1760]
Would be great to have support for the newly released Babel 7.

The new release switches package IDs from `babel-*` to `@babel/*`, so this does require a code change to support.

Useful resources for this are here:

- https://babeljs.io/blog/2018/08/27/7.0.0
- https://babeljs.io/docs/en/next/v7-migration

**Comment by OwenMelbz** [comment]
@JeffreyWay is this something you'll be looking to do?

Thanks

**Comment by daraghoshea** [comment]
+1 for this.

Been using [jigsaw.tighten.co](http://jigsaw.tighten.co) static site generator and mix is used to compile assets.

However, I'm unable to use the [Functions](https://www.netlify.com/docs/functions/) feature from Netlify as it requires babel v7 and the build keeps failing.

**Comment by ovac** [comment]
+ 1 for this.

**Comment by miguelRivero** [comment]
+1

**Comment by dagman** [comment]
cannot use jspdf-customfonts to add cyrillic font cos package requires babel7

**Comment by dotnetCarpenter** [comment]
@JeffreyWay this issue can be closed now as it is fixed by PR #1807

**Comment by elliotleelewis** [comment]
@dotnetCarpenter Fantastic work! Thanks a ton 😄
