### ISSUE TITLE
Mix overwriting assets with same name

### ISSUE THREAD

**Issue by ThisIsJustARandomGuy** [JeffreyWay/laravel-mix#1761]
- Laravel Mix Version: 2.1.14
- Node Version (`node -v`): v10.0.0
- NPM Version (`npm -v`): 6.1.0
- OS: Windows 10

### Description:
I have some images that use the same names, but are in different subfolders:

```
resources/assets/images/
-- background.png
-- subfolder/background.png
```

Mix, by default, copies both files to public/images/background.png thus overwriting one of the files.

### Steps To Reproduce:

Create two images with the same name, but in different subfolders and use them in an scss file:

```
.class1 {
    background: url(../images/background.png);
}

.class2 {
    background: url('../images/subfolder/background.png);
}
```

### What should happen

I think mix should either keep the directory structure by default or give an option to use the old cache-busting strategy. Is there any way to get this working, currently? I'm using mix in a laravel project.

**Comment by mciesin** [comment]
-   Laravel Mix Version: 4.0.14
-   Node Version: 10.15.0
-   Yarn Version: 1.13.0
-   OS: Windows 10

We still have this issue.
