### ISSUE TITLE
mix-manifest.json loses file hash after copying.

### ISSUE THREAD

**Issue by hariesnurikhwan** [JeffreyWay/laravel-mix#1762]
- Laravel Mix Version: laravel-mix@2.1.14
- Node Version: v8.11.3
- NPM Version: 6.2.0
- OS: MacOS

### Description:

When trying to build for production, if there's a copy directory and version. The copied file `mix-manifest.json` loses the generated file hash. The original compiled assets has the file hash.

This only happens when building for production, others is fine.

### Steps To Reproduce:

webpack.mix.js
```
mix.js("resources/assets/js/app.js", "public/js")
	.sass("resources/assets/sass/app.scss", "public/css")
	.copy("public", "public-test")
	.version();
```

### Steps:
1. Run `npm run prod`.

**Comment by josegus** [comment]
@ankurk91 try it on then function, it is not working, the hash is missing when copied folder

**Comment by ycs77** [comment]
+1

**Comment by ycs77** [comment]
@hariesnurikhwan Force run Laravel Mix copy file method to fix it

```js
// ...

mix.version().then(() => {
  // Run Laravel Mix copy file method
  new (require('laravel-mix/src/tasks/CopyFilesTask'))({
    from: 'public',
    to: new File('../other-public-folder')
  }).run();
})
```
