### ISSUE TITLE
Dynamic import relative path issue

### ISSUE THREAD

**Issue by avinash403** [JeffreyWay/laravel-mix#1764]
- Laravel Mix Version: 2.1.14
- Node Version (`node -v`):10.7.0 
- NPM Version (`npm -v`): 6.3.0
- OS: macOs

### Description:
Scripts calling through dynamic import is not taking `base url` from `<base href="">` tag but taking
`http://hostname` as the base url

### Steps To Reproduce:
Setup an apache server so that your public folder is accessible at `http://localhost/public`. Now create a bundle with components which are imported dynamically. Put `<base href="http://localhost/public">` in you document head. Now load the page in the browser. Parent script get called at the correct url (`http://localhost/public/parentScript.js`) but the component script calls at `http://localhost/childScript.js` missing `public` from the url

**Comment by avinash403** [comment]
Well, the issue is not reading the baseURL

**Comment by ankurk91** [comment]
What happens if you visit website with
```
php artisan serve
```

**Comment by avinash403** [comment]
I know what you mean. But there's a purpose of having a base tag in the head. There are people who use it without having server configured for pointing toward root folder just by the domain name. It should be working in all the scenarios

**Comment by ankurk91** [comment]
Laravel mix does not supports dynamic imports by default, how did you enabled this feature?

**Comment by avinash403** [comment]
Its a es6 feature which was there a long time back. Why would laravel-mix not support that?
https://developers.google.com/web/updates/2017/11/dynamic-import

**Comment by ankurk91** [comment]
This feature need some additional configuration.
https://github.com/JeffreyWay/laravel-mix/issues/1249#issuecomment-335112415

You need to configure babel plugin
https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import/

**Comment by avinash403** [comment]
Yes did. But the base url isn't taken(instead taking the domain name) while importing the dynamic scripts. You can try creating the above scenario.

**Comment by avinash403** [comment]
Yes thanks

**Comment by avinash403** [comment]
@ankurk91  any update on the issue?

**Comment by ankurk91** [comment]
I just test this in a plain webpack project and found that it does not respect the base url.

**Comment by avinash403** [comment]
So is it a bug in webpack?
