### ISSUE TITLE
npm ERR! Linux 4.15.0-32-generic npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev" npm ERR! node v8.10.0 npm ERR! npm  v3.5.2 npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by Aggidevara** [JeffreyWay/laravel-mix#1765]
- Laravel Mix Version: #.#.# (`npm list --depth=0`)
- Node Version (`node -v`): 
- NPM Version (`npm -v`): 
- OS:

**Comment by ankurk91** [comment]
Can you fill the ISSUE_TEMPLATE and write steps to re-produce ?
