### ISSUE TITLE
Browserslist "not dead" not working, upgrade css-loader

### ISSUE THREAD

**Issue by tbleckert** [JeffreyWay/laravel-mix#1766]
### Description:
Trying to use the browserlists query "not dead" but gets "Unknown browser query `dead`". This seems to be due to old versions of css-loader, https://twitter.com/browserslist/status/1016396835353776128 . Version 1.0 is needed but Laravel Mix uses ^0.28.9.

### Steps To Reproduce:
Install and use @babel/preset-env/babel-preset-env and use the query "not dead" in your browserslist configuration.

**Comment by ankurk91** [comment]
Where did you put browserslist  configuration?
Can you share whole configuration?

**Comment by tbleckert** [comment]
Root level of the project, same as the webpack.mix.js. Looks like this:

```
last 1 version
> 1%
not dead
```

If I remove "not dead" it works.

**Comment by ankurk91** [comment]
`not dead` is not a valid option in browserslist v1.7, see

https://github.com/browserslist/browserslist/tree/0875962ca176f3c130c071caba6ebd69454e374d
