### ISSUE TITLE
Installation of Laravel Mix in Ubuntu 16.04 is stuck for hours now

### ISSUE THREAD

**Issue by abrhambas01** [JeffreyWay/laravel-mix#1767]
I am on Ubuntu 16.04 and I didn't install laravel-mix on the first npm install, I just installed it later on but now i'm still stucked with this : 

linux@ElementaryOSMachine:/opt/lampp/htdocs/projectName$ npm install laravel-mix --save-dev

> npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.

> npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.

[            ......] \ extract:is-typedarray: sill extract is-typedarray@~1.0.0 extracted to /opt/lampp/htdocs/acadence/node_modules/.staging/is-typedarray-5db40cc1 (196660ms),

what could be the possible error

**Comment by ankurk91** [comment]
Can you fill ISSUE_TEMPLATE ?
