### ISSUE TITLE
Laravel mix docs appear to not be aligned with the api

### ISSUE THREAD

**Issue by mikebonds** [JeffreyWay/laravel-mix#1771]
- Laravel Mix Version: 2.1.14
- Node Version (`node -v`): 8.9.3
- NPM Version (`npm -v`): 5.5.1
- OS: OSX 10.13.5

### Description:
The following fails in the latest version of laravel-mix:

```js
let mix = require('laravel-mix');

mix.js('src/app.js', 'dist/')
   .js('src/forum.js', 'dist/');
```

This results in the following error:
`TypeError: mix.js is not a function`

**Comment by ankurk91** [comment]
How does your `package.json` look like. Are you using laravel php framework ?

**Comment by mikebonds** [comment]
@ankurk91 after taking a quick look at the laravel mix api, I'm pretty sure those methods are not defined, unless they are being injected by something else.

**Comment by ankurk91** [comment]
I don't know how are you looking at API.

When you hit `npm run dev` the execution start from this file

https://github.com/JeffreyWay/laravel-mix/blob/52582c120f2eaef0146d63a43c41235f40e3f030/setup/webpack.config.js#L2

**Comment by mikebonds** [comment]
API: https://github.com/JeffreyWay/laravel-mix/blob/master/src/Api.js
API Export: https://github.com/JeffreyWay/laravel-mix/blob/master/src/index.js#L69

And yeah, I'm using laravel.

**Comment by ankurk91** [comment]
As said previously the execution start from the file mentioned above -
See how this file gets loaded by webpack -

https://github.com/laravel/laravel/blob/7028b17ed8bf35ee2f1269c0f9c985b411cb4469/package.json#L5

Our file `wevpack.mix.js` on project root gets loaded later.

You will notice that mix loads it components using this file
https://github.com/JeffreyWay/laravel-mix/blob/52582c120f2eaef0146d63a43c41235f40e3f030/src/components/ComponentFactory.js

Components are responsible for registering methods, in your case `js`

Where do you get `mix.js is not defined`, on terminal?

**Comment by mikebonds** [comment]
The error is coming after running `npm run dev` or `npm run watch`. 

If you try having the following in  webpack.mix.js it will fail due to the `js` method being undefined.

https://laravel-mix.com/docs/2.1/mixjs
```js
let mix = require('laravel-mix');

mix.js('src/app.js', 'dist/')
   .js('src/forum.js', 'dist/');
```

What component is registering the `js` method?

**Comment by ankurk91** [comment]
Here we go
https://github.com/JeffreyWay/laravel-mix/blob/52582c120f2eaef0146d63a43c41235f40e3f030/src/components/JavaScript.js#L18

**Comment by mikebonds** [comment]
Alright, I will need to test some more to see what is exactly happening.
