### ISSUE TITLE
Generated hot file includes erroneous new line making mix blade helper fail to output URL

### ISSUE THREAD

**Issue by chriscornford** [JeffreyWay/laravel-mix#1773]
- Laravel Mix Version: 2.1.14
- Node Version (`node -v`): 10:11:0
- NPM Version (`npm -v`): 6.4.1
- OS: OSX 10.13.6

### Description:
When running `npm run hot` the generated hot file in the public dir has a new line after the URL which is causing Laravel mix blade URL helper to add a `<br />` when outputting the URL e.g. `http://localhost:8080/<br />/react-js/main.js`. This issue doesn't occur if you downgrade to `laravel-mix@2.1.11`.

It appears to be because of this `/laravel-mix/src/File.js:155` (`body = body + os.EOL;`)

```
    /**
     * Write the given contents to the file.
     *
     * @param {string} body
     */
    write(body) {
        if (typeof body === 'object') {
            body = JSON.stringify(body, null, 4);
        }

        body = body + os.EOL;

        fs.writeFileSync(this.absolutePath, body);

        return this;
    }
```

**Comment by rebirthtobi** [comment]
I'm also experiencing this problem in Laravel 5.6

**Comment by ankurk91** [comment]
Ref
https://github.com/laravel/framework/pull/25699
