### ISSUE TITLE
PR #1669 broke the autoloader

### ISSUE THREAD

**Issue by Jon4t4n** [JeffreyWay/laravel-mix#1774]
- Laravel Mix Version: 2.1.14
- Node Version: 8.9.0 
- NPM Version: 6.4.0 
- OS: Windows 10 Pro 10.0.17134

### Description
I think PR #1669 broke the autoloading if the name contains dots.

After upgrading from version 2.0 to 2.1.14 it no longer works to autoload "alertify.js" using Laravel Mix.

### Steps To Reproduce
This code stopped working after upgrading:
```js
mix.autoload({
    'alertify.js': ['window.alertify', 'alertify'],
});
```

### Error
```
Module not found: Error: Can't resolve 'alertify' in '***'
```

**Comment by marcamos** [comment]
I concur; I _was_ autoloading `ally.js` and, after a recent update, it simply stopped working. I achieved the same goal by switching my project to use `webpackConfig` — my switch / diff is here: https://github.com/fromtheoutfit/starter/commit/897825638f8b2196bb3cf48e1fba9a786bc346dc

**Comment by marcamos** [comment]
This was recently brought up in the Mix repo:

* https://github.com/JeffreyWay/laravel-mix/pull/1669#issuecomment-416833673
* https://github.com/JeffreyWay/laravel-mix/issues/1774

**Comment by ankurk91** [comment]
For now you can use webpack provide plugin

```js
mix.webpackConfig({
  plugins: [
    new webpack.ProvidePlugin({
      Vue: ['vue/dist/vue.esm.js', 'default'],
      'window.Vue': 'vue',
      $: 'jquery',
      jQuery: 'jquery',
      'window.jQuery': 'jquery',
      Popper: ['popper.js', 'default'],
    }),
  ]
});
```
You need to modify above code according to your requirements.
