### ISSUE TITLE
How can one replace all classes both in css/js with other random strings via mix?

### ISSUE THREAD

**Issue by MovingGifts** [JeffreyWay/laravel-mix#1778]
Given something like this:
`js file: <div className="active big">Laravel Mix Rocks!</div>`
`scss file: .active { color: red; } .big { fontSize: 33 }`

Mix makes magic

and outputs this:
`js file: <div className="jFHKNd vmod">Laravel Mix Rocks!</div>`
`scss file: .jFHKNd { color: red; } .vmod { fontSize: 33 }`

Any idea what the magic looks like in mix? Any thoughts?

**Comment by ankurk91** [comment]
Is this vue js code ?
If yes, checkout 
https://vue-loader.vuejs.org/guide/scoped-css.html

I believe react has similar feature.
