### ISSUE TITLE
hot on valet domains

### ISSUE THREAD

**Issue by henrikdahl** [JeffreyWay/laravel-mix#178]
How can you get `webpack-dev-server` to work with laravel valet domains? I can't get it working ✌️

**Comment by bertatbagaar** [comment]
I'm interested in this as well.

**Comment by adriaanzon** [comment]
Use the `mix()` helper provided with Laravel 5.4

https://github.com/JeffreyWay/laravel-mix/blob/master/docs/hot-module-replacement.md#usage-in-laravel

**Comment by henrikdahl** [comment]
@adriaanzon 

Your suggestion solution links scripts to the localhost:8080 which doesn't work when you run Laravel Valets custom domains. It's a bit more complicated than that ✌️

https://webpack.js.org/configuration/dev-server/#devserver

It's probably something in this direction but I've tried most of it to no avail.

```
mix.webpackConfig({
    devServer: {
        
    }
});
```

**Comment by adriaanzon** [comment]
Hmm, I'm also using Valet and HMR works fine for me. Is localhost:8080 accessible for you when `npm run hot` is running?

**Comment by henrikdahl** [comment]
`localhost:8080` gives `Cannot GET /`

Everything fresh install and latest versions no customization

**Comment by adriaanzon** [comment]
Alright that looks good. And if you go to `localhost:8080/js/app.js` (or wherever your javascript output file lives)? Does it show your compiled javascript file?

**Comment by adriaanzon** [comment]
(It looks good because it only needs to serve your assets. `localhost:8080` doesn't serve your whole app.)

**Comment by henrikdahl** [comment]
@adriaanzon 

Thanks! You were right. Got JS working now but SASS doesn't hot reload, any clue? ✌️

**Comment by adriaanzon** [comment]
Yeah, hot reloading sass ins't supported: https://github.com/JeffreyWay/laravel-mix/issues/92#issuecomment-273558018

**Comment by henrikdahl** [comment]
Thanks!
