### ISSUE TITLE
Active development stopped?

### ISSUE THREAD

**Issue by fragkp** [JeffreyWay/laravel-mix#1780]
Hey!

First of all, I want to say thank you for this realy great package!
This package covers a 80% of all use cases, but I'm sure, we can catch easily hit 95%.

But it feels like there is a lack of maintance.

They are many issues and PRs open, without any response. Personly, I wait for these two PRs (#1691, #1719) to be merged, since July.
I can unterstand, that its hard to work on this project (appveyor always failing, fast moving ecosystem, support all type of OS).

------

So, how we (as an open source community) and @JeffreyWay can solve or improve this issue?
Search for more maintainers, label issues or verify PRs?

**Comment by JeffreyWay** [comment]
Still actively being developed. But you're right that I have put this repo on hold while I finish up an important unrelated work project that needs all my attention. 

Beginning in November, I'll be doing a lot of work here to get ready for the webpack 5 release.
