### ISSUE TITLE
Feature Request: Long term caching

### ISSUE THREAD

**Issue by evenstensberg** [JeffreyWay/laravel-mix#1781]
### Description:

Is there any plans to support long time caching? I.e that bundles have hashes, not referenced by name tag. Right now mix is using a variant of the manifest plugin, but if you want to actually use filenames as hashes, you'll need to revise the filename to use hashes and find a different way to reference those when using `mix` inside a blade template

**Comment by evenstensberg** [comment]
hehe :)

**Comment by tpetry** [comment]
Does issue #1022 has the information you need?

**Comment by evenstensberg** [comment]
Probably 🗡

**Comment by JeffreyWay** [comment]
Mix does support querystring-based versioning. For file-versioning, there are Mix plugins you can pull in.
