### ISSUE TITLE
Suggestion: Pure typescript project template for Mix

### ISSUE THREAD

**Issue by lighth7015** [JeffreyWay/laravel-mix#1786]
I am going to be working on a project here in the not too distant future where I'm going to be relying heavily on Typescript, and it would be nice to be able to use TS + Vue in an enterprise setting, or at least pure TS in an enterprise setting (read: enterprise project layout).

Just saying, keep up the good work!

**Comment by ankurk91** [comment]
https://github.com/maxgaurav/laravel-mix-with-typescript

**Comment by lighth7015** [comment]
Are there any samples without SFC? because I tend to code with Notepad++, which doesn't like them.

**Comment by lighth7015** [comment]
Not kidding.

**Comment by xoco70** [comment]
@lighth7015 Code with Sublime !
