### ISSUE TITLE
[Question] How to get Laravel Mix(npm) code assist in VSCode?

### ISSUE THREAD

**Issue by cvetan** [JeffreyWay/laravel-mix#1788]
In Laravel Mix series, you get code assist all the way for Laravel mix, when you reference mix variable.

It doesn't work in my VSCode. Do I need some packages installed and what to get that? I also went through VSCode series, you didn't mention JS intellisense anywhere, besides ES Lint, but I don't think that is related.

**Comment by tianyong90** [comment]
Because there no typing files for this package

**Comment by cvetan** [comment]
How does Jeff then gets code completion inside VS Code?
