### ISSUE TITLE
How to clean generated files?

### ISSUE THREAD

**Issue by Germey** [JeffreyWay/laravel-mix#179]
It seems that there is not a `clean` method to remove generated files? 
What should I do for `clean`?
use `webpackConfig` to config `clean` in webpack.config.js?

**Comment by cjmaxik** [comment]
They are cleaned before each run automatically, I believe.

**Comment by Germey** [comment]
@cjmaxik Thanks

**Comment by Germey** [comment]
No, for example:
firstly I run 
`mix.copy('resources/assets/admin/', 'public/admin/')`
they copied all files in to `public/admin` flatten.
then I add a para as `mix.copy('resources/assets/admin/', 'public/admin/', flatten=false)`
It didn't remove the `admin` folder and re-generate files, it only add files to `admin ` folder. So `admin` folder has the all generated files these 2 times.
So, I want to find a `clean` method to clean all the generated files.

**Comment by Germey** [comment]
@JeffreyWay Could you please add `clean` or similar functions?

**Comment by JeffreyWay** [comment]
It can be risky to add those functions, because it could potentially delete files that you've added after the fact. 

If you've changed your webpack.mix.js file, it's best to manually delete the copied output directory, and try again.
