### ISSUE TITLE
Cannot get source() from mix.combine

### ISSUE THREAD

**Issue by jLynx** [JeffreyWay/laravel-mix#1792]
- Laravel Mix Version: #.#.# (`npm list --depth=0`) 2.1.14
- NPM Version (`npm -v`): 6.1.0
- OS: Windows 10

### Description:
I cannot get the source of assets that are made with mix.combine. It only get the source with mix.js

```
asset.source();
asset.sourceAndMap();
asset.map();
```
all return null as the only thing that is set in that asset is `{ size: [Function: size], emitted: true }`

### Steps To Reproduce:

```
mix.combine([
    'resources/assets/js/logger/file1.js',
    'resources/assets/js/logger/file2.js',
], 'public/js/example.js').then((stats) => {
	
    for (var file in stats.compilation.assets) {
        if(!file.toString().includes("example.js"))	//Only accepts example.js for testing
            continue;
	var asset = stats.compilation.assets[file], input, inputSourceMap;
	console.log(asset);
        input = asset.source();	//Fails here

        console.log("Done");
    }
});

```

**Comment by JeffreyWay** [comment]
`mix.combine()` is separate from your core webpack build. Webpack doesn't support basic concatenation, so we do that as a separate task from your core build.
