### ISSUE TITLE
webpack-chunk-hash does not update when WebpackJsonP index updates

### ISSUE THREAD

**Issue by stephan-v** [JeffreyWay/laravel-mix#1798]
### Description:

After discussing the issue about the [webpack-chunk-hash](https://github.com/alexindigo/webpack-chunk-hash) plugin, I am left wondering why `laravel-mix` chose to not use the native hash functionality but instead chose for that solution.

There are problems with the plugin which can cause massive issues when using dynamic imports:

https://github.com/webpack/webpack/issues/8300#issuecomment-434098477

I personally do not have experience how the chunk hash is generated but I assume the default functionality from Webpack does actually take the `WebpackJsonP` module index in account so a new hash is generated whenever this index changes.

If the index is not taken into account, the index of the file will no longer match up with the correct module causing dynamically imported modules to not load. If no new hash will be generated when the index changes, the same module will be served from the browser cache. The served module might have an index that is no longer existent within your `manifest.js` file.

### Steps To Reproduce:

1. Set up Webpack for dynamic imports according to this [little tutorial](https://github.com/JeffreyWay/laravel-mix/issues/1249#issuecomment-335112415).
2. Create multiple dynamically imported modules(3 should be fine).
3. Build once.
4. Check the `WebpackJsonP` index of the dynamic modules and the matching indices within the `manifest.js` file.
5. Delete a dynamically imported module.
6. Re-build.

After having done this you are served with dynamic modules from your browser cache since no new chunk hash is generated when it should have been. 

Your `manifest.js` is now most likely trying to call modules with a `WebpackJsonP` of let's say `[3]` which might not even exist or is the wrong module.

### Possible solution:

I think the default chunk hash functionality does take the module index into account and will generate a new chunk hash when this changes. This will `cache bust` the file and make sure we get the newly generated file instead of an outdated.

**Comment by stephan-v** [comment]
I have created a `webpack.config.js` in my root directory which holds all my monkey-patching logic for this repository since this repository not been updated in a while. I simply removed the plugin for now.

```
const config = require('laravel-mix/setup/webpack.config');   

// Try and find the WebpackChunkHash plugin.
const WebpackChunkHash = plugins.find(
    plugin => plugin.constructor.name === 'WebpackChunkHash'
);

// Remove the plugin.
plugins.splice(plugins.indexOf(WebpackChunkHash), 1);

module.exports = config;
```

Now when the `WebpackJsonP` index changes a new hash is being generated for the file and everything seems to work properly.

I'd love to hear thoughts about why the `webpack-chunk-hash` was chosen in the first place. The repository of `webpack-chunk-hash` claims  to be more performant but I don't see that much of a difference yet.

**Comment by CyberSecutor** [comment]
A small bugfix on the above code snippet:

This snippet will remove the last plugin if `WebpackChunkHash` is not found because indexOf will return -1;
```js
// Remove the plugin.
plugins.splice(plugins.indexOf(WebpackChunkHash), 1);
```

So there should be a check surrounding the splice:
```js
// Remove the plugin if it is found (should only be found when .version() is called for production).
if (plugins.indexOf(WebpackChunkHash) >= 0) {
    plugins.splice(plugins.indexOf(WebpackChunkHash), 1);
}
```

**Comment by stephan-v** [comment]
![giphy](https://user-images.githubusercontent.com/2384912/49500846-e9a99c80-f871-11e8-9606-c6f2f2fcb113.gif)

**Comment by ankurk91** [comment]
May be try this plugin

https://github.com/medz/webpack-laravel-mix-manifest

**Comment by stephan-v** [comment]
@ankurk91 That is an option, but since @JeffreyWay is currently working on upgrading this to Webpack 4 I would love to see this get reviewed since I don't think the plugin is even necessary anymore.

**Comment by JeffreyWay** [comment]
To be honest, I can't remember why I pulled in webpack-chunk-hash. There must have been some issue where the default hashing wasn't being calculated the way I needed. Not sure.

I removed it, and all the tests are still passing. So we'll give this a go for a bit, and if issues do crop up, I'll revert with an explanation why it was necessary.

**Comment by JeffreyWay** [comment]
https://github.com/JeffreyWay/laravel-mix/commit/845fec3866dc43673281ee816cc6620bc48f3e01

**Comment by tomvo** [comment]
@JeffreyWay We're experiences the same issues on Laravel Mix 3, any chance this can be backported to Mix 3 or is there any option to disable `webpack-chunk-hash` in v3 and just use the `HashedModuleIdsPlugin`?

**Comment by stephan-v** [comment]
@tomvo Just use the snippets that were posted before? I doubt this will get integrated into V3 since it will be hard to oversee the repercussions.

**Comment by tomvo** [comment]
@stephan-v Makes sense. We'll fork and check.
