### ISSUE TITLE
How to use cleanCss in Laravel mix?

### ISSUE THREAD

**Issue by SamThilmany** [JeffreyWay/laravel-mix#1800]
As probably most frontend developers I'm often using a CSS framework like Bootstrap. As I don't want to touch the code of the framework to be able to update it whenever I want, I include it via `npm` to my project and import the code to my main `scss` file. After importing the framework, I import my custom `scss` files which, sometimes, overwrite some styles of the framework. When using Laravel Mix the `scss` code is nicely compiled to a minified `css` file, but all those `scss` overwrites are now duplicate `css` styles. This bloats the `css` file and elongates the website loading time.

`cleanCss` optimises the code by merging `css` rules and deleting unnecessary stuff.

Unfortunately, it seems that `cleanCss` does not work in Laravel Mix. To test, I made the following `scss` file:

```
// Bootstrap
.alert {
	position: relative;
	padding: 0.75rem 1.25rem;
	margin-bottom: 1rem;
	border: 1px solid transparent;
	border-radius: 0.25rem;
}

.alert-danger {
	color: #721c24;
	background-color: #f8d7da;
	border-color: #f5c6cb;
}

// Custom
$danger-color: #c2100c;

.alert {
	position: relative;
	padding: 0.75rem 1.25rem;
	margin-bottom: 1rem;
	border: 0;
	border-left: 4px solid transparent;
	border-radius: 0;
}

.alert-danger {
	color: $danger-color;
	background-color: transparentize($danger-color, 0.8);
	border-color: $danger-color;
}
```

The output that I want is:

```
.alert {
	position: relative;
	padding: .75rem 1.25rem;
	margin-bottom: 1rem;
	border: 0;
	border-left: 4px solid transparent;
	border-radius: 0
}
.alert-danger {
	background-color: #f8d7da;
	color: #c2100c;
	background-color: rgba(194,16,12,.2);
	border-color: #c2100c
}
```

Using the [`cleanCSS`](https://jakubpawlowicz.github.io/clean-css/) website this is also the result.

In my project, however, the `css` code is output with the double rules, just like the `scss` source. How can I include `cleanCSS` to Laravel Mix?

Here is my `webpack.mix.js`:

```
let mix = require( 'laravel-mix' );

// Mix Options
mix.options( {
	cleanCss: {
		level: {
			2: {
				all: true
			}
		}
	}
} );

mix.setPublicPath( './assets/dist' );

// Compile assets
mix..sass( 'assets/src/scss/test.scss', 'assets/dist/css' );
```

**Comment by marcamos** [comment]
Not sure if this is helpful (or, even the same thing), but I use [purgeCSS](https://github.com/spatie/laravel-mix-purgecss) successfully, as configured [here](https://github.com/fromtheoutfit/starter/blob/master/webpack.mix.js#L36).

**Comment by JeffreyWay** [comment]
Yeah I recommend purgecss.
