### ISSUE TITLE
 NPM run dev - events.js:167       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by magdalena-dering** [JeffreyWay/laravel-mix#1802]
> 

- Laravel Mix Version: 2.1.14 (`npm list --depth=0`)
- Node Version (`node -v`):  VitrualBox v8.11.4, Windows v8.12.0
- NPM Version (`npm -v`):  VirtualBox 6.4.0, Windows 6.4.1

- OS: Windows, VirtualBox -  Ubuntu 18.04.1 LTS

### Description:
I installed Laravel Homestead, Vagrant and HeidiSQL to locate my database. 
When I run command such as "npm run production"/ "npm run development" it's producing errors like:
<img width="957" alt="error" src="https://user-images.githubusercontent.com/22090839/47788761-eec77900-dd12-11e8-9240-1d0713ad758d.png">

I tried many times to re-install everything step by step e.g.:
rm -rf .node_modules
npm install

I've found similar or the same errors on [https://github.com/JeffreyWay/laravel-mix/issues](https://github.com/JeffreyWay/laravel-mix/issues) but it doesn't work for me. 

What's more, when I installed npm I got error as below: 
<img width="678" alt="error2" src="https://user-images.githubusercontent.com/22090839/47788908-61385900-dd13-11e8-8ed1-3f4a6800c44f.png">

### Steps To Reproduce:
npm run dev/ development
npm run prod/ production

### Package.json
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.18",
        "bootstrap": "^4.0.0",
        "popper.js": "^1.12",
        "cross-env": "^5.1",
        "jquery": "^3.2",
        "laravel-mix": "^2.0",
        "lodash": "^4.17.5",
        "vue": "^2.5.7"
    }
}

**Comment by patrickomeara** [comment]
Hi @magdalena-dering I'm hitting this error trying to upgrade to Mix 4.

Did you find a solution?
