### ISSUE TITLE
Unable to use Laravel Mix with custom `node_modules` location

### ISSUE THREAD

**Issue by nikoheikkila** [JeffreyWay/laravel-mix#1803]
- Laravel Mix Version: **2.1.14** (`npm list --depth=0`)
- Node Version (`node -v`): **v10.12.0**
- NPM Version (`npm -v`): **6.4.1**
- OS: **Alpine Linux 3.8**

### Description:

I'm unable to use Laravel Mix with customized `node_modules` location. I'm preparing a demo Laravel app with Docker where Laravel 5.7 and Laravel Mix are running in two separate containers. For convenience, I'd like to place `node_modules` to filesystem root within container to avoid problems with volumes.

### Steps To Reproduce:

These are most useful to be run inside a Docker container. For detail here's my Dockerfile:

```dockerfile
FROM node:10.12-alpine

ENV NODE_ENV=development

RUN npm install -g yarn

WORKDIR /app

COPY package.json webpack.mix.js *yarn* ./
COPY resources/js/ ./resources/js/
COPY resources/sass/ ./resources/sass/

RUN yarn install

COPY . .

CMD ["yarn", "run", "watch"]
```

And the `docker-compose.yml`:

```yaml
  webpack:
    build:
      context: '.'
      dockerfile: 'Dockerfile.webpack'
    command: 'yarn run watch'
    volumes:
      - '.:/app'
```

The `.yarnrc` that is copied to container contains one line:

```sh
--modules-folder /node_modules
```

In `package.json` I have modified the default Laravel Mix configuration to point to `/node_modules`:

```json
"scripts": {
        "dev": "yarn run development",
        "development": "NODE_ENV=development /node_modules/webpack/bin/webpack.js --progress --hide-modules --config=/node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "yarn run development -- --watch --watch-poll",
        "hot": "NODE_ENV=development /node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=/node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "yarn run production",
        "production": "NODE_ENV=production /node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=/node_modules/laravel-mix/setup/webpack.config.js"
    }
```

When the container runs `yarn run watch` upon start I'll get following error:

```sh
$ NODE_ENV=development /node_modules/webpack/bin/webpack.js --progress --hide-modules --config=/node_modules/laravel-mix/setup/webpack.config.js --watch --watch-poll
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/webpack.mix'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/node_modules/laravel-mix/setup/webpack.config.js:12:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

Is there a way to resolve this by merging my own Webpack configuration with Mix or should I replace the entire configuration with my own? For reference I can produce a working Webpack watch & build with custom `node_modules` location with other apps but Laravel Mix doesn't work so well in this manner.

**Comment by ankurk91** [comment]
```
resolve: {
    modules: [
      path.resolve(__dirname, 'node_modules'),
    ],
}
```
https://webpack.js.org/configuration/resolve/#resolve-modules

**Comment by nikoheikkila** [comment]
Hi @ankurk91. Your solution does not work as it results in the same error. Looks like the Yarn process dies before even entering the `webpack.mix.js` file.

Browsing the issues I came across #1719 and tried to reimplement this fix by modifying the `Paths.js`. Now everything works fine without touching the Mix or Webpack configuration at all. 🎉 

Of course, modifying Mix source code is not optimal solution so let's wait for @JeffreyWay to merge the pull request above and then this issue can probably be closed. :shipit:

**Comment by JeffreyWay** [comment]
Merged. Sorry for the wait. :)
