### ISSUE TITLE
Error installing laravel-mix on WSL

### ISSUE THREAD

**Issue by YahzeeSkellington** [JeffreyWay/laravel-mix#1804]
I'm unable to run `npm install` with Laravel Mix. The error shows a 404 trying to download from [https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-67_binding.node](https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-67_binding.node) and visiting that link on the browser also shows a 404. I check on the releases page for node-sass and the list only goes up until linux-x64-64, not x64-67 like Laravel Mix requests.

I tried running the install inside Laravel and on its own and it's the same output:

```
> node-sass@4.9.4 install /mnt/d/Sites/blog/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-67_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
```

- Laravel Mix Version: 2.1.14
- Node Version: 
- NPM Version: 
- OS: WSL on Windows 10

**Comment by ankurk91** [comment]
It is most likely node-sass issue

**Comment by esb-ben** [comment]
Same issue

**Comment by rossbearman** [comment]
`node-sass@4.9.4` doesn't support Node 11. If you manually require the following in your `package.json` it should resolve the issue.

`"node-sass": "^4.10.0",`

See [this node-sass PR](https://github.com/sass/node-sass/pull/2522) for details.

**Comment by JeffreyWay** [comment]
We’re moving away from node-sass as part of the Mix 4 release. So that will fix this issue.
