### ISSUE TITLE
Unable versioning sass and less in one shot

### ISSUE THREAD

**Issue by maengkom** [JeffreyWay/laravel-mix#181]
Hello @JeffreyWay,

In my project I have sass and less file, but if versioning always produce the last line, in this example below the forum.css will be created but not app.css. If I reverse the order, app.css will be created but not forum.css. Perhaps I miss something how to treat this case ?

Example 1
```
mix.sass('resources/assets/sass/app.scss', 'public/css')
    .less('resources/assets/less/forum.less', 'public/css')
    .version();
```

Example 2
```
mix.sass('resources/assets/sass/app.scss', 'public/css')
    .version();

mix.less('resources/assets/less/forum.less', 'public/css')
    .version();
```

**Comment by SebastianS90** [comment]
There are already two issues for this: #159 #170

**Comment by JeffreyWay** [comment]
I didn't anticipate any scenario where people would want to use multiple CSS preprocessors in a single app.

Right now, you can only use one or the other.

**Comment by donnysim** [comment]
A valid scenario is when you buy a template ant it only has .less files but your project is using .scss. Learned that I can't compile both after upgrading #feelsbadman

**Comment by marcelogarbin** [comment]
> A valid scenario is when you buy a template ant it only has .less files but your project is using .scss. Learned that I can't compile both after upgrading #feelsbadman

I just got into this situation, did you manage to solve it? Thank you
