### ISSUE TITLE
Resolve url loader error when resolving relative path

### ISSUE THREAD

**Issue by evsign** [JeffreyWay/laravel-mix#1816]
- Laravel Mix Version: 2.1.14
- Node Version (`node -v`): 11.1.0
- NPM Version (`npm -v`): 6.4.1
- OS: linux

### Description:
`resolve-url-loader` cannot properly resolve path for image in `url()` and produces error:
```
ERROR in ./node_modules/css-loader??ref--12-2!./node_modules/postcss-loader/lib??postcss!./node_modules/resolve-url-loader??ref--12-4!./node_modules/s
ass-loader/lib/loader.js??ref--12-5!./resources/sass/folder/file.scss
Module build failed: Error: resolve-url-loader: CSS error
  predicate must return an absolute path or the result of calling next()
  at file:///var/www/resources/sass/folder/file.scss:6:3
    at encodeError (/var/www/node_modules/resolve-url-loader/index.js:218:12)
    at onFailure (/var/www/node_modules/resolve-url-loader/index.js:175:14)
 @ ./resources/sass/folder/file.scss 4:14-277
```
### Steps To Reproduce:
1. Get laravel 5.7 app
2. Create `file.scss` in `resources/sass/folder/file.scss` with content
```
.page-register-v2 {
  &:before {
    background-image: url("image.jpg");
  }
}
```
3. Place file `image.jpg` in `resources/sass/folder/image.jpg`
4. write
```js
mix.sass('resources/sass/folder/file.scss', 'public/css/folder');
```
in `webpack.mix.js`
5. run `npm run dev`

**Comment by tewshi** [comment]
In order to get this working, i declared this variable in my `_variables.scss` file:
`$fa-font-path: '/@fortawesome/fontawesome-free/webfonts';`
