### ISSUE TITLE
Can't load bootstrap 4 component

### ISSUE THREAD

**Issue by abdulrahman19** [JeffreyWay/laravel-mix#1817]
- Laravel Mix Version: (`v2.1.14`)
- Node Version (`v8.11.2`): 
- NPM Version (`v6.4.1`): 
- OS: `Ubuntu 18.10`

### Description:
I load Jquery and Vue js in separated file in the header and all other components in another file in the footer. 

this code for the header file
```
try {
    window.$ = window.jQuery = require('jquery');
} catch (e) {}

window.Vue = require('vue');
```
and this for the footer file
```
...
try {
    window.Popper = require('popper.js').default;

    require('bootstrap');
} catch (e) {}
...
...
```

but when I try to use any bootstrap 4 component it gives me this error in the browser.

```
Uncaught TypeError: $(...).alert is not a function
```
I use this code in the blade file
```
<script type="text/javascript">
$(function() {
    $('.alert').alert('close');
});
</script>
```

I try to use 
```
mix.autoload({
   jquery: ['$', 'window.jQuery', 'jQuery']
});
```
also this
```
mix.webpackConfig(webpack => {
    return {
        plugins: [
            new webpack.ProvidePlugin({
                $: 'jquery',
                jQuery: 'jquery',
                'window.jQuery': 'jquery',
                Popper          : ['popper.js', 'default'],
                Alert           : 'bootstrap/js/dist/alert',
                Button          : 'bootstrap/js/dist/button',
                Carousel        : 'bootstrap/js/dist/carousel',
                Collapse        : 'bootstrap/js/dist/collapse',
                Dropdown        : 'bootstrap/js/dist/dropdown',
                Modal           : 'bootstrap/js/dist/modal',
                Popover         : 'bootstrap/js/dist/popover',
                Scrollspy       : 'bootstrap/js/dist/scrollspy',
                Tab             : 'bootstrap/js/dist/tab',
                Tooltip         : "bootstrap/js/dist/tooltip",
                Util            : 'bootstrap/js/dist/util',
            })
        ]
    };
});
```
but nothing working, only when I load Jquery in the footer file it works, but I need to load jquery in the header and of course I won't load it twice, once in the header and other in the footer.

So I hope someone help me... thanks.

**Comment by ankurk91** [comment]
You can not use imported module, in your case `jQuery`; outside of `app.js`.
You are trying to use `$` in a script tag that is on template itself.

**Comment by abdulrahman19** [comment]
@ankurk91 but Vue imported without any problem!
why Jquery not? or I didn't understand you answer well.
another thing, the `alert` module loaded and working fine but the error still appears, really I don't understand what going on :smiley: 
![screenshot from 2018-11-15 18-54-27](https://user-images.githubusercontent.com/22733622/48568426-0b190780-e908-11e8-882b-1b7ab632216e.png)

If you can tell me with steps how to fix the problem, I'll be so thankful.

**Comment by noogen** [comment]
@abdulrahman19 explaining @ankurk91 reference: In order to use jQuery externally, you must load jquery externally as script tag in the `head` tag.  Add `popper.js` and `bootstrap.js` after jquery script tag.  Then add this to your webpack mix config to tell webpack that it is externally loaded.

```javascript
mix.webpackConfig({
  externals: {
    'jquery': 'jQuery'
  }
```

Now you can use jQuery in both vanilla js and Vue as `import $ from 'jquery'`; webpack will know to use the external jQuery reference and not to package the script.

Again, all you need is to define jQuery as external in webpack.  Remove all other reference of your jQuery webpack config such as autoload and webpack.ProvidePlugin, you're just going to cause `jQuery` conflict issue (multiple jQuery on the page - imported has bootstrap but external doesn't)

**Comment by LTroya** [comment]
Try doing `console.log` on the `try-catch`, there should be another error. Any variable in `window` object is global. If you do in the browser `$` and `Enter`, you should see the jQuery object.

If there is an jquery object, you may be overriding jquery with some `script` tag. Ex:

```
<script src="jquery.js"></script>

// This script add $.alert() function
<script src="alert.js"></script>


<script src="jquery.js"></script>
<script>
    $.alert() // This will give you an error since the $.alert() function was attached to the first jquery
              // import and not the second one.
</script>
```

Hope it helps.
