### ISSUE TITLE
npm run dev error 

### ISSUE THREAD

**Issue by GODDEY77** [JeffreyWay/laravel-mix#1818]
$ npm run dev watch

> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "watch"

'cross-env' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gadoo\AppData\Roaming\npm-cache\_logs\2018-11-15T04_04_32_784Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development "watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gadoo\AppData\Roaming\npm-cache\_logs\2018-11-15T04_04_32_942Z-debug.log

//Please what can i do to rectify this error

**Comment by ankurk91** [comment]
Please fill out ISSUE_TEMPLATE to get proper support
