### ISSUE TITLE
jquery uniform is not a function

### ISSUE THREAD

**Issue by DevMakoto** [JeffreyWay/laravel-mix#1819]
- Laravel Mix Version: 2.1.14
- Node Version (`node -v`): v10.6.0
- NPM Version (`npm -v`): 6.4.1
- OS: Windows 10 x64 

### Description:
With a fresh laravel install i'm trying to display a uniform styles but i get this error :

### Steps To Reproduce:
install package
```
npm install --save jquery.uniform
```

in boostrap.js
```
.
.
try {
    window.Popper = require('popper.js').default;
    window.$ = window.jQuery = require('jquery');

    require('bootstrap');

    require('jquery.uniform');
} catch (e) {}
.
.
```

in app.js
```
require('./theme');
```

in theme.js
```
        document.addEventListener('DOMContentLoaded', function () {
            $('.radio').uniform();
        });
```

in webpack.mix.js
```
mix.options({
    processCssUrls: false
});


mix.extract(['vue', 'lodash', 'popper.js', 'jquery', 'bootstrap', 'jquery.uniform']);

mix.autoload({
        jquery: ['$', 'window.$', 'window.jQuery', 'jQuery']
    });

mix.js('resources/js/app.js', 'public/js');

```

in console
```
Uncaught TypeError: $(...).uniform is not a function
```

So I hope someone help me... thanks.

**Comment by azdanov** [comment]
What's causing this is `mix.autoload`, since it will `prepend var $ = require('jquery') to every location that it encounters either the global $ identifier, or window.jQuery` as mentioned in the [docs](https://laravel-mix.com/docs/2.1/autoloading).

A workaround for this is to remove `mix.autoload` from `webpack.mix.js`. This will force `./theme.js` to use window `$`.

**Comment by DevMakoto** [comment]
error in console jQuery no defined

**Comment by azdanov** [comment]
Try removing `mix.extract`?

**Comment by DevMakoto** [comment]
using alone
```
mix.js('resources/js/app.js', 'public/js');
```
I have no problem but I would like to have plugins separated in vendor.js

**Comment by azdanov** [comment]
Could be one of the dependencies messing up with the `vendor.js`. Try starting with `mix.extract(['jquery']);` and adding one by one to find which dependencies are responsible.

**Comment by DevMakoto** [comment]
dependencies "jquery.uniform" in extract cause error

**Comment by azdanov** [comment]
Can't think of anything regarding `jquery.uniform`.

It's doing some monkey patching on jQuery when required, which messes up with webpack's common chunks extraction.

You could use a [CDN](https://cdnjs.com/libraries/Uniform.js) for uniform and `mix.extract` for jquery and the rest. Not ideal, but it will keep the vendor dependencies separate from the application code.
