### ISSUE TITLE
`mix.postCss()` options, like `parser: 'postcss-scss'`, how?

### ISSUE THREAD

**Issue by lkraav** [JeffreyWay/laravel-mix#1826]
- Laravel Mix Version: laravel-mix@2.1.14
- Node Version (`node -v`): 8.12.0
- NPM Version (`npm -v`): 6.4.1
- OS: Gentoo Linux

### Description:
Configuration object seems to only take an array of plugins, but PostCSS is further configurable.

Are options like `parser: 'postcss-scss'` for https://github.com/postcss/postcss-scss/ supposed to be configured through webpack `postcss-loader` configuration level, or...?

### Steps To Reproduce:

It would be intuitive to do something like `mix.postCss( `${devPath}/scss/screen.scss`,             'css', { options, [ require('postcss-plugin')() ] )`

**Comment by JeffreyWay** [comment]
With the next release of Mix, you'll be able to create postcss.config.js file for any options like this.

**Comment by opdavies** [comment]
Was this included? I've tried using the SugarSS syntax with Tailwind and it's not parsing the Tailwind directives for me, though maybe I'm missing something. It works fine using the regular CSS syntax.

Here's a quick example repo - https://github.com/opdavies/laravel-mix-postcss-sugarss-test/tree

**Comment by ak4rp0v** [comment]
@opdavies In your example you are loading a .sss file, therefore you need to add this to your mix file and it will work like charm:
`mix.webpackConfig({
		module: {
			rules: [
				{
					test: /\.sss?$/,
					loader: 'postcss-loader'
				}
			]
		}
	})`

**Comment by opdavies** [comment]
Thanks @ak4rp0v. I had to make a couple of small tweaks to my `postcss.config.js` file too, but it's working now.
