### ISSUE TITLE
Vue Scss code not being extracted since 2.1

### ISSUE THREAD

**Issue by bengallienne** [JeffreyWay/laravel-mix#1828]
-   Laravel Mix Version: 2.1.14
-   Node Version : 8.11.3
-   NPM Version: 6.4.1
-   OS: Mac

### Description:
Since upgrading from version 2.0.0 of Laravel Mix to 2.1.* our styles that are inside Vue Single File components are now longer being extracted to the main CSS file. Reverting back to version 2.0.0 resolves the issue with no other changes necessary

### Steps To Reproduce:
Create a fresh laravel install, add some SCSS code to the example vue component, and attempt to setup mix to extract the CSS to a separate file. It will only read and compile SCSS that is in separate files, and not inside Single File Components. I guess something changed from version 2.0 to 2.1 but we cannot determine what it was. Can you help please?

**Comment by taai** [comment]
@bengallienne You have configure the Laravel Mix to extract CSS from ```.vue``` files to do that.

In your ```webpack.mix.js``` file:

```javascript
mix.options({
    extractVueStyles: true
})
```

This works for me on v2.1.x and v3.0.0 too.

**Comment by JeffreyWay** [comment]
Yep ^

**Comment by bengallienne** [comment]
@taai sorry for the slow reply, I didn't get a notification that you had posted. I already have that in my settings and it doesn't make a difference. Is it ok to reopen this please @JeffreyWay?

**Comment by bengallienne** [comment]
For reference, that part of our mix file looks like this

`.options({
       extractVueStyles : true,
       processCssUrls: false,
       globalVueStyles: 'resources/assets/sass/_variables.scss'
   })
   .webpackConfig({
        devtool: 'source-map',
        resolve: {
            modules: [
                path.resolve(__dirname, 'vendor/laravel/spark-aurelius/resources/assets/js'),
                path.resolve(__dirname, 'node_modules')
            ],
            alias: {
                'vue$': 'vue/dist/vue.js'
            }
        }
   })`
