### ISSUE TITLE
Missing Origin Validation in webpack-dev-server dependency

### ISSUE THREAD

**Issue by Yakoot** [JeffreyWay/laravel-mix#1830]
### Description:

high | Missing Origin Validation
------------ | -------------
Package | webpack-dev-server
Patched in | >=3.1.6
Dependency of | laravel-mix
Path | laravel-mix > webpack-dev-server
More info | https://nodesecurity.io/advisories/725

### Steps To Reproduce:
yarn audit

**Comment by ankurk91** [comment]
https://github.com/JeffreyWay/laravel-mix/pull/1810

**Comment by sustained** [comment]
@Yakoot This is probably fixed in [the latest release](https://github.com/JeffreyWay/laravel-mix/releases/tag/4.0.0-beta.1). :+1:

**Comment by Yakoot** [comment]
super, I'll check

**Comment by hardeverick** [comment]
Can anyone confirm is this is fixed and if so how can we apply the fix on existing installations of Laravel 5.7 w/ laravel-mix v2.1.14?

**Comment by JeffreyWay** [comment]
You can't fix this issue with v2 of Mix. The fix requires an upgrade to webpack 4. You can pull in the Mix 4 beta right now, or you can wait a week or so for it to officially be released to the public.

**Comment by Yakoot** [comment]
> Can anyone confirm is this is fixed and if so how can we apply the fix on existing installations of Laravel 5.7 w/ laravel-mix v2.1.14?

fixed in beta, I checked

**Comment by hardeverick** [comment]
Thanks. I will update.

**Comment by joleenshook** [comment]
how do we fix this for Laravel 5.5 w/laravel-mix with ^1.0 dependency?

**Comment by JeffreyWay** [comment]
@joleenshook You can't, but it only affects people who are using hot reloading (`npm run hot`). If you're not running that command, you can ignore this issue.

**Comment by joleenshook** [comment]
Perfect thanks.

**Comment by panchalnv** [comment]
I am getting below error:

 === npm audit security report ===


                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance


  High            Missing Origin Validation

  Package         webpack-dev-server

  Patched in      >=3.1.11

  Dependency of   react-scripts

  Path            react-scripts > webpack-dev-server

  More info       https://nodesecurity.io/advisories/725

found 1 high severity vulnerability in 35709 scanned packages
  1 vulnerability requires manual review. See the full report for details.
