### ISSUE TITLE
laravel mix expects node_modules directory inside application directory

### ISSUE THREAD

**Issue by tback** [JeffreyWay/laravel-mix#1835]
-   Laravel Mix Version: 2.1.14
-   Node Version: v11.3.0
-   NPM Version: 6.4.1
-   OS: debian stretch amd64 in docker on debian stretch amd64

### Description:
Laravel mix expects node_modules directory inside application directory. Deferring from that configuration leaves me with assets in wrong places and no documentation on how to control the output path.
This is related to https://github.com/JeffreyWay/laravel-mix/issues/1411. This example doesn't try to install laravel-mix globally because this still fails.

### Steps To Reproduce:
1. clone https://github.com/tback/mix-container-docker-issue-1835
```
2. make run 
```
3. Assets are written to public/app/app/css/app.css and public/app/app/public/app/public/js/app.js not public/css/app.css and public/js/app.js

**Comment by JeffreyWay** [comment]
There's a `mix.setPublicPath()` method you might use to tinker with the output path. 

But Mix will assume that node_modules is in the project root. Happy to accept a PR to change that.
