### ISSUE TITLE
Disable manifest file generation

### ISSUE THREAD

**Issue by KKSzymanowski** [JeffreyWay/laravel-mix#1836]
Is there a way to disable generation of the `mix-manifest.json` file?

**Comment by JeffreyWay** [comment]
No. If you don't need it, add a post compile script that does something like `rm public/mix-manifest.json`.

**Comment by KKSzymanowski** [comment]
Thank you.

**Comment by rodrigoriome** [comment]
Well, this command is not cross-platform...
