### ISSUE TITLE
Compile every SCSS file to it's own CSS file

### ISSUE THREAD

**Issue by Puzo** [JeffreyWay/laravel-mix#1837]
-   Laravel Mix Version: 3.0.0
-   Node Version: 10.14.1
-   NPM Version: 6.4.1
-   OS: Windows 10

I am using yarn and laravel-mix with webpack to compile my .scss files to .css and also to compile my Javascript files. All good here, so far. How can I achieve that every .scss file has it's own .css in the same folder?

For example:

`assets/styles/components/component1.scss`
`assets/styles/components/component1.css`
`assets/styles/components/component2.scss`
`assets/styles/components/component2.css`
`etc.`

So far, my webpack.mix.js file looks like this:

```
const mix = require('laravel-mix');
const webpack = require('webpack');

mix.setPublicPath(path.resolve('./'))
   .webpackConfig({
     plugins: [
       new webpack.ProvidePlugin({
         Popper: ['popper.js', 'default'],
         $: "jquery",
         jQuery: "jquery"
       })
     ]
   })
   .copyDirectory('assets/images', 'dist/images')
   .copyDirectory('assets/fonts', 'dist/fonts')
   .sass('assets/styles/app.scss', 'dist/css', { outputStyle: 'compressed' })
   .version()
   .options({
     processCssUrls: false,
     uglify: {
       uglifyOptions: {
         output: {
           max_line_len: false,
           beautify: false
         }
       }
     }
   });

if( process.env.NODE_ENV ) {
  require(`${__dirname}/webpack.mix.${process.env.NODE_ENV}.js`);
}
```

**Comment by JeffreyWay** [comment]
Either scan your Sass directory and dynamically call mix.sass() for each file, or do it manually. 

I'm not sure why you'd need so many mix.sass() calls. I don't have a single project with more than two calls.

**Comment by Puzo** [comment]
Good idea, thanks.

Same here, but our client wants to have all .css files too (not only .scss files).
