### ISSUE TITLE
Combine sass (or less)?

### ISSUE THREAD

**Issue by jpmurray** [JeffreyWay/laravel-mix#184]
Hello,

The docs speaks of the `mix.combine()` method, that allows to combine files. But it would seems that it only combine files that are already compiled (I might be wrong, if I am, sorry!).

With Elixir, I could combine multiple sass and less files in one big compiled css file like so:

```
mix.sass([
        'app.scss',
        'controllers.scss'
    ], 'public/assets/css');
```

Trying the same with laravel-mix results in an error `Path must be a string`, so that's clearely not working. Is it impossible at the moment to do so? Or did I miss something entirely?

**Comment by JeffreyWay** [comment]
You should have your main entrypoint Sass file import any other files that it needs to be combined with.

**Comment by jpmurray** [comment]
It... Totally makes sense. Thank you for that, I don't really know why I stuck with what I did before actually ! :D

**Comment by Zedonboy** [comment]
me too i wasn't smart..
thanks @JeffreyWay you're my Hero
