### ISSUE TITLE
Followup: Enabling versioning breaks building

### ISSUE THREAD

**Issue by radmen** [JeffreyWay/laravel-mix#1841]
-   Laravel Mix Version: 3.0.0
-   Node Version (`node -v`): 10.13.0
-   NPM Version (`npm -v`): 6.4.1
-   YARN version: 1.12.3
-   OS: Linux

### Description:

This is a followup of #1607.

When `mix` is used outside of Laravel context it fails to generate `mix-manifest.json` containing versions of generated files.

This happens because `publicPath` remains empty.
https://github.com/JeffreyWay/laravel-mix/blob/7dc010451870c0b23d8e22fe5d0fa67714d7df5f/src/index.js#L35-L37

TBH I don't consider it as a bug in the library, more likely it's something that should be stated somewhere in the docs.

Maybe `mix` should say that `publicPath` is empty?

### Steps To Reproduce:

I've prepared [simple repository](https://github.com/radmen/laravel-mix-issue-1607) which has a minimum setup of `laravel-mix`.
To reproduce the problem one should follow the steps describe in the repos README file.

**Comment by JeffreyWay** [comment]
We know where the public directory should be if you're in a Laravel app. Otherwise, you have to specify it yourself with `mix.setPublicPath()`.

**Comment by radmen** [comment]
@JeffreyWay I agree. Yet the reported issue (not mine) clearly says that this is a problem.

Maybe `mix` should report in such case that public path has to be set?
