### ISSUE TITLE
Problem with versioning and folder that contains dot in the name

### ISSUE THREAD

**Issue by martinstefanov** [JeffreyWay/laravel-mix#1842]
- Laravel Mix Version: 3.0.0
- Node Version 10.9.0
- NPM Version 6.2.0
- OS: win 10

## Description:

There is error generating versions If one copy folder that contains dot in the name with copy() or copyDirectory() .
For example:
```
.copyDirectory('resources/assets/js/joyride-2.1', 'public/js');
```
## Steps To Reproduce:
webpack.mix.js
lines like:
```
    .copyDirectory('resources/assets/js/joyride-2.1', 'public/js');
```

Resulting in error:
```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:489:3)
    at tryReadSync (fs.js:328:20)
    at Object.readFileSync (fs.js:365:19)
```
I have tried:
```    
.copyDirectory('resources/assets/js/joyride-2.1/*', 'public/js/joyride-2.1'); 
```
and
```    
.copyDirectory('resources/assets/js/joyride-2.1/*', 'public/js/joyride-2.1/'); 
```
Resulting to copy the folder files in file: public/js/joyride-2.1

If destination folder has no dot then copy works:
```
    .copyDirectory('resources/assets/js/joyride-2.1/*', 'public/js/joyride-2');
```

I think the problem is here:
https://github.com/JeffreyWay/laravel-mix/blob/a53d6705ffc68fa79b46dcfbf1c205bcc8fdef7b/src/File.js#L256
https://github.com/JeffreyWay/laravel-mix/blob/a53d6705ffc68fa79b46dcfbf1c205bcc8fdef7b/src/File.js#L257

**Comment by martinstefanov** [comment]
@lfelizari 
Did you try with adding '/*': 
`.copyDirectory('node_modules/tableexport.jquery.plugin/*','public/vendor/tableexport-jquery-plugin');`
This is a workaround that I found for source folder, but I didn't found workaround for destination folder.

**Comment by martinstefanov** [comment]
@lfelizari
I hope it will be accepted and merged soon. For me that looks ok.
Do you have idea if there is performance slowdown?

**Comment by pavelsavushkinblastmotion** [comment]
For googlers: one of the "hack" solution for that situation:
```bash
yarn add -D <alias>@npm:<package>
```

Example:
```bash
yarn add -D datatables-buttons@npm:datatables.net-buttons
```
The same for NPM.

**Comment by themightystephen** [comment]
I am also encountering the same problem with node packages with dots in their name causing `copyDirectory()` to fail. martinstefano's workaround (https://github.com/JeffreyWay/laravel-mix/issues/1842#issuecomment-449549533) does the job but not ideal. I'd rather be using the original package name consistently throughout my application.

I see that an open merge request with a potential solution exists: https://github.com/JeffreyWay/laravel-mix/pull/1926. Could this be considered for merge into master?

**Comment by AdamGaskins** [comment]
I'm having this issue too using `pdf.js-viewer`!

Can `copy()` just copy files and `copyDirectory()` actually copy directories? :(
