### ISSUE TITLE
Sass is required even if is not used

### ISSUE THREAD

**Issue by natocTo** [JeffreyWay/laravel-mix#1848]
-   Laravel Mix Version: 4.0.2
-   Node Version (`node -v`): 8.11:4
-   NPM Version (`npm -v`): 6.4.1
-   OS: Windows 10

### Description:

I have only js, less and Vue files in application but still error occurs that missing 'sass' dependencies. I have no sass in webpack.mix.js and also in the project.
 
After I install sass and sass-loader everything working fine. But it is strange I must install this even if I dont use them. Maybe it is bug so I report it. :)

I have one more project where I acctualy use sass and there was upgrade so simple. Great job.

**Comment by matrunchyk** [comment]
@JeffreyWay can we have this fixed? Thank you!

**Comment by koole** [comment]
I'm also having this same issue. I've worked around it by just installing `sass` in my project, installing `sass-loader` wasn't even necessary.
