### ISSUE TITLE
Laravel-Mix 4.0.2 breaks async/await in Vue components

### ISSUE THREAD

**Issue by ThomHurks** [JeffreyWay/laravel-mix#1849]
-   Laravel Mix Version: 4.0.2 (`npm list --depth=0`)
-   Node Version (`node -v`): 11.3
-   NPM Version (`npm -v`): 6.5.0
-   OS: MacOS Mojave

### Description:
I'm using Vue components, and in some components I use async/await:
```javascript
methods: {
  async someMethod() {
    await this.foo();
  }
}
```
This always worked fine, but with Laravel-Mix 4 I'm getting this error in the browser console in Chrome 71:
```
regeneratorRuntime is not defined
```
and my entire app is broken.

After some digging around this is the workaround:
```shell
npm install --save-dev @babel/plugin-transform-runtime
npm install --save @babel/runtime
```

```javascript
mix.extend(
    new class {
        dependencies() {
            return ["@babel/plugin-transform-runtime"];
        }
        babelConfig() {
            return {
                plugins: [
                    [
                        "@babel/plugin-transform-runtime",
                        {
                            "regenerator": true
                        }
                    ]
                ]
            };
        }
    }()
);
```

This is a regression however, as Laravel-Mix pre-4 supported async/await out-of-the-box. This is probably not intended, but a bug?

**Comment by ThomHurks** [comment]
I don't have a .babelrc file, but I did already extend mix with the Babel plugin ```@babel/plugin-proposal-unicode-property-regex```, but this worked fine before. Is it possible that using a Babel plugin causes this now?

**Comment by JeffreyWay** [comment]
Not sure.

Can you add `console.log(Config.babel())` to the bottom of your webpack.mix.js file, and paste the output?

**Comment by ThomHurks** [comment]
When I completely remove the ```mix.extend()``` part then my project compiles fine (of course I removed the regexes using unicode properties first). So without Babel plugins all is good.

The result (so without plugins) of ```Config.babel()``` is this:
```javascript
{ cacheDirectory: true,
  presets:
   [ [ '@babel/preset-env',
       { modules: false,
         targets: { browsers: [ '> 2%' ] },
         forceAllTransforms: true } ] ],
  plugins:
   [ '@babel/plugin-proposal-object-rest-spread',
     [ '@babel/plugin-transform-runtime', { helpers: false } ] ] }
```
My app then loads fine.

When I add back the plugin, so my webpack.mix.js is:
```javascript
mix.options({
  extractVueStyles: true,
  globalVueStyles: 'resources/sass/vue_variables.scss',
  vue: {
    esModule: true
  }
});

mix.extend(
    'unicodeRegex',
    new class {
        dependencies() {
            return ["@babel/plugin-proposal-unicode-property-regex"];
        }
        babelConfig() {
            return {
                plugins: ["@babel/plugin-proposal-unicode-property-regex"]
            };
        }
    }()
);

mix.sourceMaps();
mix.js('resources/js/app.js', 'public/js');
mix.sass('resources/sass/app.scss', 'public/css');
mix.unicodeRegex();

if (mix.inProduction()) {
  mix.version();
}
console.log(Config.babel());
```
then the output is:
```javascript
{ cacheDirectory: true,
  presets:
   [ [ '@babel/preset-env',
       { modules: false,
         targets: { browsers: [ '> 2%' ] },
         forceAllTransforms: true } ] ],
  plugins:
   [ '@babel/plugin-proposal-object-rest-spread',
     [ '@babel/plugin-transform-runtime', { helpers: false } ] ] }
```

So it looks the same, but when I open my app in my browser I get:
```
Uncaught ReferenceError: regeneratorRuntime is not defined
```
in my ```methods: {}``` block in the Vue component.

**Comment by ThomHurks** [comment]
By the way, the ```npm install --save @babel/runtime``` step is not necessary. The babel docs said to install that one too, but without it everything still works.
