### ISSUE TITLE
npm run dev fails with "Path must be a string"

### ISSUE THREAD

**Issue by JeffreyWay** [JeffreyWay/laravel-mix#185]
Ported from https://github.com/laravel/framework/issues/17528

```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
```

@Frondor - It would be helpful to me if you go through these files in the stacktrace...

```
    at new File (c:\wamp\www\web\node_modules\laravel-mix\src\File.js:14:30)
    at Object.module.exports.preprocess (c:\wamp\www\web\node_modules\laravel-mix\src\index.js:108:14)
    at Object.module.exports.sass (c:\wamp\www\web\node_modules\laravel-mix\src\index.js:84:27)
    at Object.<anonymous> (c:\wamp\www\web\webpack.mix.js:17:5)
```

...and add a few `console.logs` to figure out why it's saying that no string was provided here: https://github.com/JeffreyWay/laravel-mix/blob/master/src/File.js#L14

**Comment by Frondor** [comment]
Sure! I'll do that as soon as I arrive home

**Comment by Frondor** [comment]
I'm a completely stranger working with node, but I think I found something

```
module.exports.preprocess = (type, src, output) => {
    src = new Mix.File(path.resolve(src)).parsePath();
    output = new Mix.File(output).parsePath(); // <-------- HERE!

    if (output.isDir) {
        output = new Mix.File(
            path.posix.join(output.path, src.name + '.css')
        ).parsePath();
    }

    Mix[type] = (Mix[type] || []).concat({ src, output });

    Mix.cssPreprocessor = type;

    return this;
};
```
When doing `mix.sass('app.scss');`, you're expecting `output` (which sometimes can be `undefined`, like in this case) as a `File` to `File.js` constructor:
```
let fs = require('fs');
let path = require('path');
let uglify = require('uglify-js');
let UglifyCss = require('clean-css');

class File {
    /**
     * Create a new File instance.
     *
     * @param {string} file
     */
    constructor(file) {
        this.file = file;
        this.fileType = path.parse(file).ext; // <------ path.parse(undefined).ext
    }
...
```

Then this error pops up. So I tried writing the outputs manually:
```
mix.sass('app.scss', 'css/test.css')
   .js('vendor.js', 'js/test.js');
```
It "works" but now, the issue is the path. It's taking the root of my project for both types of assets:
![](https://i.gyazo.com/b8107d7010b8ecea0c1b7fb36a7a5b58.png)

**Comment by JeffreyWay** [comment]
So when it was failing before, were you just doing `mix.sass('app.scss')` without anything for the second argument?

**Comment by Frondor** [comment]
Exactly, just like default example.

Now, I tried this and worked, definitely not good looking but working:
```
const { mix } = require('laravel-mix');

    mix.sass('resources/assets/sass/app.scss', 'css/app.css')
    	.copy('node_modules/bootstrap-sass/assets/fonts/', 'public/fonts/')
    	.js('resources/assets/js/vendor.js', 'js/vendor.js')
    	.js('resources/assets/js/home.js', 'js/home.js')
    	.js('resources/assets/js/cuenta.js', 'js/.cuentajs');
```

**Comment by JeffreyWay** [comment]
But this is the default example: https://github.com/laravel/laravel/blob/master/webpack.mix.js

Notice that it specifies the full paths for input and output.

Laravel Elixir had default paths that you could assume, but we removed those for Mix, since it ended up confusing people. 

Anyways, glad it's working now.

**Comment by Frondor** [comment]
Alright, thanks!

Probably you want to make some error handling there, so people don't get confused by these weird errors.
Like checking for undefined outputs and file not found.

**Comment by themsaid** [comment]
I ran into this issue earlier, and turned out I didn't provide a second argument to `less()`, `less('resources/assets/less/app.less')` thinking it would work like in Elixir. I think that's the same mistake the same mistake @Frondor did in the original issue.
