### ISSUE TITLE
Laravel-Mix 4.0.2 breaks /deep/ in Vue component styling

### ISSUE THREAD

**Issue by ThomHurks** [JeffreyWay/laravel-mix#1850]
-   Laravel Mix Version: 4.0.2 (`npm list --depth=0`)
-   Node Version (`node -v`): 11.3
-   NPM Version (`npm -v`): 6.5
-   OS: MacOS Mojave

### Description:
I have a Vue component where I need scoped styling to affect a child component.[ I use ```/deep/``` for this.](https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements) This has always worked pre Laravel-Mix 4.
```html
<style lang="scss" scoped>
    /deep/ .some-styling {
    }
```

With Laravel-Mix 4, I get the following error on ```npm run dev```:
```
         }
     ^
      Expected selector.
    & /deep/ .some-foo-styling{
      ^
```
or 
```
    .some-other-styling {
^
      Expected selector.
/deep/.some-styling{
^

```
It seems clear that Mix no longer understands what ```/deep/``` is, so I tried replacing it with the thing that it's an alias for: ```>>>```

Mix now compiles without error, but sadly the generated CSS is wrong.
It should be:
```CSS
[data-v-507877ae] .some-styling {
}
```
but instead it generates:
```CSS
 > .some-styling[data-v-507877ae] {
}
```
which means that the class must now be a direct descendant, so my styling breaks.

**Comment by JeffreyWay** [comment]
Seems like deep selectors is deprecated?

https://github.com/sass/dart-sass/issues/154

Looks like node-sass still supports it, while Dart Sass does not.

Try switching over entirely to node-sass, and let me know if that changes the output.

```js
npm remove sass
npm install node-sass
```

```js
mix.sass('src', output', { implemention: require('node-sass'));
```

```js
npm run dev
```

**Comment by ThomHurks** [comment]
I thought ```/deep/``` was just something that is compiled and that ```vue-loader``` does. It never shows up in the client CSS. There is a Vue issue where some people are confused https://github.com/vuejs/vue-loader/issues/913 

I tried doing what you suggest and I still get the same error. The Vue-Loader documentation [still says it's possible](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors) and it worked before Laravel-Mix v4, so it's odd. Does Node-Sass maybe refuse to recognize ```>>>``` or ```/deep/``` in a newer version that is now used?

**Comment by JeffreyWay** [comment]
Not sure. I've never even heard of deep selectors until this thread, haha. I'll look into it in the morning. 

Thanks for the help today!

**Comment by ThomHurks** [comment]
And you thanks for working on Laravel-Mix and helping me! ❤️

I did find some other bug reports on Vue-Loader where people are also saying that ```/deep/``` doesn't work for them https://github.com/vuejs/vue-loader/issues/1407 and https://github.com/vuejs/vue/issues/8841 and I saw some similar reports from Angular.

My current guess is that ```/deep/``` used to be valid SASS/SCSS and that ```vue-loader``` treated it specially when using it in ```scoped``` component styles. However, when SASS/SCSS parsers remove support for it, then that's not going to work anymore... If this is correct then I may simply have to refactor my Vue components.

**Comment by nsivertsen** [comment]
Hi! Above, you mention using

```js
mix.sass('src', 'output', { implemention: require('node-sass') });
```
to override the Sass implementation. But as far as I can tell, this only works when you're compiling Sass source files, not Sass in Vue SFCs, right? It seems usage of Dart Sass is hardcoded for Vue components. Maybe I'm just overlooking some configuration option? Thanks!

**Comment by ThomHurks** [comment]
Hmm, if that's true then that explains why switching back to ```node-sass``` didn't help.

**Comment by nsivertsen** [comment]
We should probably also check for node-sass here:

https://github.com/JeffreyWay/laravel-mix/blob/master/src/components/Vue.js#L119-L123

**Comment by JeffreyWay** [comment]
@nsivertsen That code checks to see if you have Dart Sass installed. If you do, it uses that as the implementation. Otherwise it sticks with the default, which is node-sass.

**Comment by nsivertsen** [comment]
Yeah, seeing the same behaviour.

**Comment by JeffreyWay** [comment]
Ah yep, that'll do it. If calling `mix.sass()`, it always specifies `sass` as a required dependency, even if you've manually pulled in `node-sass`. So once the Vue component has to determine which Sass implementation to use, it sees that `sass` is installed, and assumes that's the one you want. Fixing now.

**Comment by ThomHurks** [comment]
Great, thanks!

**Comment by nsivertsen** [comment]
Thank you!

**Comment by dmitry-ivanov** [comment]
@ThomHurks As I understood, the workaround is to use `node-sass` implementation, right?

But it's just a temporary solution, no?

`/deep/` and `>>>` are both deprecated, and one day, they would be removed from the `node-sass` too?

**Comment by ThomHurks** [comment]
Yes, ```/deep/``` and ```>>>``` used to be part of SCSS/SASS, so they're valid when parsed using ```node-sass``` for now. The Vue loader then gives them special meaning when you use them inside a scoped component. If ```node-sass``` removes ```/deep/``` and ```>>>``` in the future and it's no longer valid SCSS in ```node-sass``` too, then I guess Vue has to invent something else. The problem is that the style is parsed before the Vue loader processes it, so whatever they invent should be added to ```node-sass``` and ```dart-sass``` too.

This issue has been reported to Vue a while ago, but they're not taking any action. If everyone's code breaks some day they'll probably act fast though. That's how it usually works ;)

**Comment by LaravDev** [comment]
Using node-saas only withouth saas on the dependencies solved this for me

**Comment by nobiit** [comment]
Hi everyone, here is the solution:

```js
mix.options({
    postCss: [
        postcss.plugin('deepCssVueScoped', () => {
            let sign = '[deep]';
            return function (root, result) {
                root.walkRules((rule) => {
                    if (~rule.selector.indexOf(sign)) {
                        rule.selector = rule.selector.replace(sign, '/deep/');
                    }
                });
            };
        })
    ]
});
```

And use it as follows: 

```scss
.auth {
    display: flex;
    [deep] .auth-container {
        position: relative;
        .auth-title {
            .logo {
                height: 100px;
                width: 100px;
            }
        }
    }
}
```
