### ISSUE TITLE
babel-preset-react-app 6.1.0 not working 

### ISSUE THREAD

**Issue by rwinzhang** [JeffreyWay/laravel-mix#1857]
-   Laravel Mix Version: 4.0.6
-   Node Version: 10.14.1
-   NPM Version: 6.4.1 (I am using yarn 1.12.3)
-   OS: Mojave 10.14.2

### Description:

I am trying to include `babel-preset-react-app 6.1.0` for react purpose and put snippet below on `.babelrc`, but the merging is not working with `presets` config.

```
{
  "presets": ["react-app"]
}
```

But if I put snippet below with `plugins` config, it works.

```
{
  "plugins": ["@babel/plugin-proposal-class-properties"]
}
```

### Steps To Reproduce:

Here is my config (I use `js` instead of `react` and it works well when I am using `mix 2.1.14` with `babel-preset-react-app 3.1.2`. I just try to upgrade the dependency.

```
mix
  .js('resources/assets/app/js/app.js', 'public/js');
```

**Comment by silvioiannone** [comment]
Same happening for me but with `transform-vue-jsx`.

The `.babelrc` file seems to be ignored. It was working with `2.x`.

My `.babelrc` file:

```
{
  "presets": ["env"],
  "plugins": ["transform-vue-jsx"]
}
```

**Comment by rwinzhang** [comment]
@JeffreyWay my config output looks like below

```
{
  presets:
    [['/Users/your_user/your_project/node_modules/@babel/preset-env/lib/index.js',
      [Object]],
      '/Users/your_user/your_project/node_modules/babel-preset-react-app/index.js'],
  plugins:
    ['/Users/your_user/your_project/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js',
      ['/Users/your_user/your_project/node_modules/@babel/plugin-transform-runtime/lib/index.js',
        [Object]]],
  cacheDirectory: true,
}
```
