### ISSUE TITLE
SyntaxError: Unexpected token: operator (>)

### ISSUE THREAD

**Issue by AnthonyPorthouse** [JeffreyWay/laravel-mix#186]
Output when running `npm run production`

```
 ERROR  Failed to compile with 1 errors

 error

/js/app.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./resources/assets/js/store/helpers.js:3,32][/js/app.js:1317,39]
```

The Line in question looks like this:
```js
const newTags = tags.filter(value => value !== currentValue);
```

**Comment by rderimay** [comment]
That coule be the same issue as mine #188 actually ?

**Comment by JeffreyWay** [comment]
@AnthonyPorthouse I can't reproduce this. Are you using a custom .babelrc file in your project root?

**Comment by AnthonyPorthouse** [comment]
@JeffreyWay Yes, I have the fix that @rderimay mentioned from #188 enabled as I'm using Vuex.

My .babelrc looks like this:
```js
{ "plugins": ["transform-object-rest-spread"] }
```

**Comment by SebastianS90** [comment]
Your `.babelrc` overrides the [default settings](https://github.com/JeffreyWay/laravel-mix/blob/4b44830d680dc317860cd7e62ce0f03ddccf075c/src/Mix.js#L204). Try adding the `es2015` preset:

```
{
    "plugins": [
        "transform-object-rest-spread"
    ],
    'presets': [
        ['es2015', { 'modules': false }]
    ]
}
```

**Comment by AnthonyPorthouse** [comment]
Thanks for the heads up on this @SebastianS90, this did indeed fix the problem.

@JeffreyWay This information would probably be super useful in the docs. Oh and great work on this!
