### ISSUE TITLE
[4.0.6] npm run watch will cause webpack keep rebuilding

### ISSUE THREAD

**Issue by koshuang** [JeffreyWay/laravel-mix#1860]
-   Laravel Mix Version: 4.0.6 (`npm list --depth=0`)
-   Node Version (`node -v`): 10.13.0
-   NPM Version (`npm -v`): 6.4.1
-   OS: Ubuntu

### Description:

When I run `npm run watch`, webpack keeps rebuilding assets. I have no idea how to fix it.
Not sure if it's really related to `laravel-mix`.
Please check out the sample repo.

### Steps To Reproduce:

Sample repo: https://github.com/koshuang/laravel-mix-v4-test

**Comment by JeffreyWay** [comment]
Because you're not in a Laravel project, you need to add `mix.setPublicPath()` to your `webpack.mix.js` file.

```js
mix.js('resources/assets/js/app.js', 'public/js/')
    .sass('resources/assets/sass/app/app.scss', 'public/css/')
    .setPublicPath('public');
```

**Comment by koshuang** [comment]
Hi @JeffreyWay, 

Thanks for the instruction! It works after I add `.setPublicPath('public');`.

But when I follow the tutorial https://laravel-mix.com/docs/4.0/workflow, it has same issue.

You can test it in this branch https://github.com/koshuang/laravel-mix-v4-test/tree/laravel-mix-v4-workflow-with-laravel.

**Comment by anjunatl** [comment]
Future `npm run watch` loopers,

- if you've committed any [fonts](https://github.com/JeffreyWay/laravel-mix/issues/228#issuecomment-276866093) or [images](https://github.com/JeffreyWay/laravel-mix/issues/228#issuecomment-278325103) into `public/` , move them into `resources/` or elsewhere & copy them to `public/` in `webpack.mix.js`
- if you're using font-awesome this might apply to you: https://github.com/JeffreyWay/laravel-mix/issues/228#issuecomment-276722669
