### ISSUE TITLE
Change babel defaults

### ISSUE THREAD

**Issue by olach** [JeffreyWay/laravel-mix#1861]
I noticed in the source code that Mix sets some defaults to Babel:

```js
presets: [
    [
        '@babel/preset-env',
        {
            modules: false,
            targets: {
                browsers: ['> 2%']
            },
            forceAllTransforms: true
        }
    ]
],
```

I would suggest to make som changes here.

1. `modules: false` is not needed anymore. The default value is `auto` which means `false` in latest version of Babel. See: https://github.com/babel/babel-loader/issues/521

2. Remove `targets`. It's better if Babel gets its target setting from a Browserslist config. If this `targets` is set, it will override the users Browserslist config. This can be confusing. Maybe add a default Browserslist config for new projects, maybe in package.json?

3. ~~I think that `forceAllTransforms` can be removed now when Terser is used instead of UglifyJS? But I am not sure.~~ Edit: Don't remove this, I realize now that this is a sensible default for Laravel Mix to transform all ES6+ code to old ES5. But since all code will be transformed, the `targets`could be removed because it is not used when `forceAllTransforms` is true.

4. There is another option that enables automatic polyfills depending of browser support from Browserslist.`useBuiltIns: "usage"`. It's a really great feature, but I don't know yet if it's a good idea to enable it for all users. This settings requires this dependency: `@babel/polyfill`. What do you think?

**Comment by JeffreyWay** [comment]
Thanks for this. I've done the first two:

https://github.com/JeffreyWay/laravel-mix/commit/38e579e1742ed474ff1f5f449d36b5fea7cf5aba

For #4 `useBuiltIns`, I probably need to research that a bit more. This Babel stuff gets confusing pretty quickly.

**Comment by olach** [comment]
Thanks. I'm not an expert on this either. Regarding the first `modules: false`. I think its safe to remove it, but I'm not sure. What do you think?

**Comment by JeffreyWay** [comment]
Yeah, based on the last comment on that thread you linked to, seems like it's unnecessary.

> For example, if you are calling Babel using babel-loader, modules will be set to false because webpack supports ES modules
