### ISSUE TITLE
[4.0.8] PostCss not applied to SCSS styles inside .vue components

### ISSUE THREAD

**Issue by smcyr** [JeffreyWay/laravel-mix#1871]
-   Laravel Mix Version: 4.0.8
-   Node Version: 10.13.0
-   NPM Version: 6.5.0
-   OS: Windows 10

### Description:

If I have both SCSS and PostCSS inside a Vue component, just the scss is transpiled while the PostCSS is ignored.

### Steps To Reproduce:

Add Scss and PostCSS to a .vue component:
```
<template>...</template>
<script>...</script>
<style lang="scss" scoped>
	.search-item {
		&.focus {
			@apply bg-grey-lighter;
		}
	}
</style>
```

With a simple mix config:
```
mix
	.setPublicPath('web/dist')
	.js('assets/scripts/main.js', 'scripts')
	.sass('assets/styles/main.scss', 'styles')
	.options({
		extractVueStyles: true,
		postCss: [
			require('tailwindcss')('./tailwind.js')
		]
	})
	.extract()
	.version();
```

The result:
```
.search-item.focus[data-v-94be9d9a] {
@apply bg-grey-lighter;
}
```

The expected result:
```
.search-item.focus[data-v-94be9d9a] {
background-color: #f1f5f8;
}
```

**Comment by JeffreyWay** [comment]
Fixed on master. I'll tag it soon.

**Comment by smcyr** [comment]
Thanks! I confirm that it's working now with 4.0.10.
