### ISSUE TITLE
v4.x Error: TypeError · Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by mikebronner** [JeffreyWay/laravel-mix#1874]
1. [x] Update Laravel Mix to the latest version. (`npm update laravel-mix` or `yarn upgrade laravel-mix --latest`)
2. [x] Nuke your dependencies, and reinstall from scratch: `rm -rf node_modules && npm cache clear && npm install`.
3. [x] Check your `package.json` file, and ensure that there are no old Laravel Elixir dependencies that might be interfering with Mix.

-   Laravel Mix Version: 4.0.12
-   Node Version (`node -v`): 10.14.1
-   NPM Version (`npm -v`): 6.4.1
-   OS: macOS 10.14.2

### Description:
When loading any page that includes the generated `js/app.js` file, I get the following error:
```js
TypeError Attempted to assign to readonly property. 
    unknown normalizeProps
    unknown mergeOptions
    unknown extend
    unknown createComponent
    unknown _createElement
    unknown anonymous
    unknown _render
    unknown updateComponent
    unknown get
    unknown Watcher
    unknown mountComponent
    unknown _init
    unknown Vue
    unknown eval code
    http://.../js/app.js:1151:5 ./resources/js/app.js
    http://.../js/app.js:20:34 __webpack_require__
    http://.../js/app.js:1244:20 
    http://.../js/app.js:20:34 __webpack_require__
    http://.../js/app.js:84:37 
    http://.../js/app.js:85:12 global code
```

### Steps To Reproduce:
Load any page with the generated `js/app.js` file.

#### webpack.mix.js
```
let mix = require('laravel-mix');
let tailwindcss = require('tailwindcss');

mix.js('resources/js/app.js', 'public/js')
    .copyDirectory('resources/img', 'public/images')
    .copyDirectory("resources/fonts", "public/fonts")
    .sass('resources/sass/app.scss', 'public/css')
    .sass('resources/sass/fontawesome.scss', 'public/css')
    .options({
        processCssUrls: false,
        postCss: [ tailwindcss('./tailwind.js') ],
    })
;
```

#### package.json
```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "@bugsnag/js": "^5.0.2",
        "@bugsnag/plugin-vue": "^5.0.2",
        "axios": "^0.18",
        "cross-env": "^5.1",
        "laravel-echo": "^1.4.0",
        "laravel-mix": "4.*",
        "lodash": "^4.17.5",
        "sass": "^1.15.2",
        "sass-loader": "7.*",
        "socket.io-client": "^2.1.1",
        "tailwindcss": "^0.6.5",
        "vue": "*",
        "vue-template-compiler": "^2.5.21"
    }
}
```

#### resources/js/app.js
```js
import bugsnag from '@bugsnag/js';
import bugsnagVue from '@bugsnag/plugin-vue';
global.bugsnagClient = bugsnag({
    apiKey: window.bugsnag_token,
    beforeSend: function (report) {
        report.groupingHash = report.errorMessage;
    },
});

require('./bootstrap');

global.Vue = require('vue');
bugsnagClient.use(bugsnagVue, Vue);

global.app = new Vue({
    el: '#app'
});
```

For now the only remedy I have been able to find is to revert back to `laravel-mix 3.*`. Anything I can do to further help troubleshoot this?

**Comment by JeffreyWay** [comment]
I *think* this is related to strict mode and Babel 7, but I'm not sure. Can you try this plugin?

https://github.com/genify/babel-plugin-transform-remove-strict-mode

Once you create a .babelrc file and add it, does that affect your compile results?

**Comment by JeffreyWay** [comment]
I *think* this is related to strict mode. 

Can you add `console.log(Config.babel());` to the bottom of your `webpack.mix.js` file, and paste the results here? I want to ensure that the env preset `modules: false` option is set for you.

**Comment by mikebronner** [comment]
Hi @JeffreyWay, thanks for the quick response and suggestion! I added the package as suggested above, and checked my code to make sure there is no `use strict;` anywhere. The results remained the same, and the error persists. Here is the output as directed above:

```
{ presets:
   [ [ '/Users/mike/Developer/Sites/githelpdesk.com/node_modules/@babel/preset-env/lib/index.js',
       [Object] ] ],
  plugins:
   [ '/Users/mike/Developer/Sites/githelpdesk.com/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js',
     [ '/Users/mike/Developer/Sites/githelpdesk.com/node_modules/@babel/plugin-transform-runtime/lib/index.js',
       [Object] ],
     '/Users/mike/Developer/Sites/githelpdesk.com/node_modules/babel-plugin-transform-remove-strict-mode/lib/index.js' ],
  cacheDirectory: true }
``` 

It does not show a `modules: false` as you were expecting. What can I do to fix that?

**Comment by JeffreyWay** [comment]
Are you sure? It's not included here?

```
console.log(Config.babel().presets);
```

**Comment by mikebronner** [comment]
Ah, yes, that spit out the following:
```json
[ [ '/Users/mike/Developer/Sites/githelpdesk.com/node_modules/@babel/preset-env/lib/index.js',
    { modules: false, forceAllTransforms: true } ] ]
```

**Comment by mikebronner** [comment]
Interesting! So the implication here is that since I have no imports in any of my own modules, some other NPM package that I am using is causing this. I guess the best way to go about that would be to disable all non-laravel-standard items from `package.json` and add them back in one by one until it breaks? Thanks for your help in trying to nail this issue down. :)

**Comment by mikebronner** [comment]
OK, I found the solution -- well, you found it, I implemented it. :) The problem was not that I had import statements inside my modules, but that I was `require`ing my view modules, instead of importing them. 

So instead of this:
```js
Vue.component("comment", require("./components/Comment.vue"));
```

I did this, which fixed the problem:
```js
import Comment from "./components/Comment.vue";
Vue.component("comment", Comment);
```

Thanks for your pointers!

**Comment by mikebronner** [comment]
Ah, thanks! :) I was pocking around on the documentation website, I must have missed all that. :) Will check release notes going forward.
