### ISSUE TITLE
Compiling multiple js files for different pages, output css file don't contains external css

### ISSUE THREAD

**Issue by radislaw** [JeffreyWay/laravel-mix#1875]
-   Laravel Mix Version: 4.0.12
-   Node Version 10.11.0
-   NPM Version 6.5.0
-   OS: Ubuntu 16.04.5 LTS

### Steps To Reproduce:
I want to split js files for different pages on the site (home.js, catalog.js, etc.). When I add just one file for compoilation:

``` js
mix.js('/assets/js/home.js', 'public/home/js')
   .sass( '/assets/sass/app.scss', 'public/css/app.css')
   .extract(['vue'])
   .version()
```
everything works fine. But if I add another js file:

``` js
mix.js(`/assets/js/home.js`, 'public/home/js')
   .js(`/assets/js/catalog.js`, 'public/catalog/js')
   .sass( '/assets/sass/app.scss', 'public/css/app.css')
   .extract(['vue'])
   .version()
```
output css contains only styles from .vue files

Difference between output catalog.js and home.js:

home.js:
```
__webpack_require__(/*! /home/user/PhpstormProjects/engine/resources/engine/assets/js/home.js */"./resources/engine/assets/js/home.js");
module.exports = __webpack_require__(/*! /home/user/PhpstormProjects/engine/resources/engine/assets/sass/app.scss */"./resources/engine/assets/sass/app.scss");
```

catalog.js:
```
module.exports = __webpack_require__(/*! /home/user/PhpstormProjects/engine/resources/engine/assets/js/catalog.js */"./resources/engine/assets/js/catalog.js");

```

**Comment by runfan** [comment]
I have this issue too, an I have only one bound js can working fine, and another cannot work.

**Comment by daylightstudio** [comment]
I have this issue as well. Makes it difficult when working in a team when the absolute path to the source files are different and the comment changes even when the source files did not.
