### ISSUE TITLE
Laravel-mix: how to change fonts build directory

### ISSUE THREAD

**Issue by ArnasL** [JeffreyWay/laravel-mix#1876]
Problem solved mix 4.0

**Comment by ankurk91** [comment]
I don't care from where my fonts are being placed in `public/fonts` directory as long as they are being loaded by browser correctly.

**Comment by mgsmus** [comment]
There is a `$fa-font-path` variable in font-awesome. You can change the output path, just add to your scss before font-awesome import but I'm not sure if laravel mix can copy them to new folder for you. You may have to copy font files from node_modules via mix.copyDirectory()

**Comment by dennisfrank** [comment]
I wonder that myself. I would like to publish fonts to `public/assets/fonts`. I tried to `mix.copy` `public/fonts` to `public/assets/fonts` but that does not fix the font file paths in the compiled css files (`url(/fonts…`).

**Comment by ytilotti** [comment]
> Overwrite `fileLoaderDirs.fonts` in `webpack.mix.js` worked for me:
> 
> ```
> let mix = require('laravel-mix');
> mix.config.fileLoaderDirs.fonts = 'assets/fonts';
> ```

Since the version 6, this solution not working anymore. Do:
```
let mix = require('laravel-mix');
mix.options({
    fileLoaderDirs:  {
        fonts: 'assets/fonts';
    }
});
```

**Comment by michaldoda** [comment]
> > Overwrite `fileLoaderDirs.fonts` in `webpack.mix.js` worked for me:
> > ```
> > let mix = require('laravel-mix');
> > mix.config.fileLoaderDirs.fonts = 'assets/fonts';
> > ```
> 
> Since the version 6, this solution not working anymore. Do:
> 
> ```
> let mix = require('laravel-mix');
> mix.options({
>     fileLoaderDirs:  {
>         fonts: 'assets/fonts';
>     }
> });
> ```

Thank you @ytilotti! fyi it might be a typo (comma instead of semicolon), best

```
let mix = require('laravel-mix');
mix.options({
    fileLoaderDirs:  {
        fonts: 'assets/fonts',
    }
});
```

**Comment by ytilotti** [comment]
Thanks @michaldoda, I edited! A beautiful typing error^^
