### ISSUE TITLE
vue-template-compiler installed despite no reference to Vue

### ISSUE THREAD

**Issue by Log1x** [JeffreyWay/laravel-mix#1877]
-   Laravel Mix Version: laravel-mix@4.0.12
-   Node Version (`node -v`): v11.4.0
-   NPM Version (`npm -v`): 6.4.1
-   OS: macOS 10.13.6

### Description:

I suspect starting in 4.0.10 with the introduction to [this](https://github.com/JeffreyWay/laravel-mix/commit/531ab623df61b13eeb711973b9bcc39594f6082b) commit, `vue-template-compiler` appears to be installing despite the project not using Vue nor having any reference to it whatsoever.

**Comment by JeffreyWay** [comment]
`vue-template-compiler` has always been included with Mix. You're just seeing it more directly now. `mix.js()` does assume a Vue application, even if it doesn't require it.

**Comment by billriess** [comment]
@JeffreyWay 

Why does `mix.react()` also assume a Vue application though?

**Comment by mabasic** [comment]
I do not want to have vue-template-compiler dependency in my package.json file. Can it not be forced to install?

**Comment by Kovah** [comment]
I would like to see an option to turn this off. In #1891 @JeffreyWay mentioned that Laravel Mix was build with Vue in mind but the current documentation indicates that it's more a universal build tool to make configuration with Webpack easier. Getting vue-template-compiler _force installed_ via Yarn even if I do not use any Vue and not using Yarn is irritating especially for starters.

If there is an option to turn this off or properly configure it, I would be pleased to get to know it. :)

**Comment by othneildrew** [comment]
A **quick fix** that I found that was especially helpful for me was to use the `mix.scripts` method. This assumes an array of files to combine and does not install any vue dependencies. 

`webpack.mix.js` looks like this:
```js
mix.scripts(['resources/js/app.js'], 'public/js/app.js')
   .sass('resources/sass/app.scss', 'public/css');
```

If you're writing ES6+ JS like I am you can also use the `mix.babel()` which works actually the same but will use plugins like babel-loader to transform ES6+ code.

Hope this helps :smile:

**Comment by paullaffitte** [comment]
Unfortunately, if you want to use the `import` keyword, you need modules and you need webpack, so you need to use the .js function.
I did a PR as mentionned above, but if it's not merge soon, you can use this **hack** (I checked the code of the library. If you're not using vue, it should not cause any issue, if you're using vue why are you reading this issue first?)

```js
const JavaScript = require('laravel-mix/src/components/JavaScript');

class JS extends JavaScript {
  dependencies() {
    return [];
  }
}

mix.extend('js', new JS());
```
It's not very pretty but at least it works, at least for `laravel-mix:4.0.7`. It's just ignoring the 'vue-template-compiler' dependency required by the JavaScript component (that is based on the Vue one), and which is the only current dependency of this components.

**Comment by dendihandian** [comment]
Laravel-Mix is great, That's why I used it for another non-laravel project. But the project doesn't need Vue, how to disable this when running `yarn dev`?

**Comment by paullaffitte** [comment]
Normally it should have been removed in version 5 as this comment shows https://github.com/JeffreyWay/laravel-mix/pull/2339#issuecomment-700261567. So try to upgrade your version, otherwise I don't have any idea.

**Comment by dendihandian** [comment]
@paullaffitte I think it still there. 
Now I'm using a new laravel scaffolding with `"laravel-mix": "^5.0.1",` inside the package.json and it still installing vue-template-compiler.

**Comment by bjornbjorn** [comment]
Yeah, looks like this still is the case with "laravel-mix": "^5.0.1" .. the first time you run `yarn install` it will add vue-template-compiler.

**Comment by paullaffitte** [comment]
Sorry I meant version 6 actually, I just edited my answer.

**Comment by cod4rvin** [comment]
Here is another approach for non Vue projects. Add below lines in `webpack.mix.js` before build steps.
Seems to work in laravel-mix 5.

```javascript
mix.override(function (webpackConfig) {
    webpackConfig.plugins = webpackConfig.plugins.filter(plugin => plugin.constructor.name !== 'VueLoaderPlugin');
    return webpackConfig;
})
```
