### ISSUE TITLE
cssnano options don't seem to work

### ISSUE THREAD

**Issue by Vercoutere** [JeffreyWay/laravel-mix#1878]
-   Laravel Mix Version: 4.0.12
-   Node Version (`node -v`): 8.12.0
-   NPM Version (`npm -v`): 6.4.1
-   OS: MacOS Mojave

### Description:

Running Mix while providing custom cssnano configuration options doesn't seem to have any effect, while as of version 4.0 it should be possible to configure cssnano in this way according to the release notes. (https://github.com/JeffreyWay/laravel-mix/releases/tag/v4.0.0)

### Steps To Reproduce:

These are the contents of my mix file:

```
mix.postCss('resources/assets/css/app.css', 'public/css/app.css')
    .options({
        cssNano: { preset: 'advanced' }
    });
```

When running `npm run prod` I would expect cssnano to apply the advanced optimisations as listed in their documentation, but that doesn't happen.
Providing an invalid preset also doesn't throw an error, so it seems this configuration just isn't being loaded.

**Comment by ndberg** [comment]
Looks like this is still the case?

@Vercoutere how did you fix this?

**Comment by pharkasbence** [comment]
Is there any solution for this problem?

**Comment by Vercoutere** [comment]
Hey, my Laravel Mix config for using PostCSS with cssnano (for production builds only) currently looks somewhat like this:

```
mix.postCss('resources/assets/css/app.css', 'public/css', [
    ...(mix.inProduction() ? [require('cssnano')({ preset: 'advanced' })] : [])
]);
```
