### ISSUE TITLE
Dynamic import with .extract() not compiling sass

### ISSUE THREAD

**Issue by AhsanAbrar** [JeffreyWay/laravel-mix#1879]
-   Laravel Mix Version: 4.0.12
-   Node Version 11.3.0
-   NPM Version 6.4.1
-   OS: Windows 10

### Description:
when i use .extract() compiled css file is empty:

here is the app.js

```js
import Vue from 'vue'

Vue.component('test', () => import('./components/Test.vue'))

const app = new Vue({
	el: '#app'
})
```

here is the webpack.mix.js

```js
const mix = require('laravel-mix')

mix.js('resources/js/app.js', 'public/js')
   .sass('resources/sass/app.scss', 'public/css')
   .extract()
```

everything working fine without .extract()

but when i add .extract() there are empty app.css file

i spend lot's of time to fix the issue but failed.

but all scenario was working fine with Laravel Mix 3

**Comment by JeffreyWay** [comment]
See the Mix 4 release notes. This is a known issue and can’t be fixed until Webpack 5 is out.
