### ISSUE TITLE
Autoprefixer with sass not working

### ISSUE THREAD

**Issue by min1mal** [JeffreyWay/laravel-mix#1880]
-   Laravel Mix Version: 4.0.12
-   Node Version 10.14.2:
-   NPM Version 6.4.1:
-   OS: Windows 10

### Description:
Autoprefixer not working for sass, tested alone and with laravel.

With Laravel Mix 3.* it is working perfectly.

### Steps To Reproduce:

Install Laravel Mix, create a scss file with example:
.some {
    display: flex
}

and try to compile. The result is without prefix.

**Comment by JeffreyWay** [comment]
Flexbox is well-supported at this point. Vendor prefixes are no longer necessary.

If you *must* overwrite the defaults, see here: https://www.npmjs.com/package/autoprefixer#browsers
