### ISSUE TITLE
Could not even once succeed in npm run dev

### ISSUE THREAD

**Issue by ozgurkalan** [JeffreyWay/laravel-mix#1883]
-   Laravel Mix Version: 4.0.12
-   Node Version (`node -v`): v11.4.0
-   NPM Version (`npm -v`): 6.4.1
-   OS: MacOs Mojave 10.14.2 

### Description:

- Tried several new laravel installs and tested on different folders
- rm -rf node_module - npm chache clear - npm install tried several times
- tested a standalone laravel-mix 
- went through Quaro, Stackflow, Medium and Reddit for similar webpack errors
- uninstalled global webpack & webpack-cli after testing reinstalled with latest versions
- tried global webpack commands other than package.json scripts
- tried to install webpack & webpack-cli from root laravel, each time npm asked for a missing Babel package (the ones in Babelconfig.js)
- tried compiling laravel-mix in its node_module
- updated and re-run my previous webpack projects (react, wordpress etc) with current updated versions (all working fine)

> Could be an issue related to x64 Mojave, but latest versions of webpack projects are working well in different projects.

**No way, could not even pass the very first "npm run dev" step.**

### Latest log:
**sh: node_modules/webpack/bin/webpack.js: No such file or directory**

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.4.1
3 info using node@v11.4.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 info lifecycle @~dev: @
7 verbose lifecycle @~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ozinclouds/Desktop/lara/ozlara/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ozinclouds/.composer/vendor/bin
9 verbose lifecycle @~dev: CWD: /Users/ozinclouds/Desktop/lara/ozlara
10 silly lifecycle @~dev: Args: [ '-c', 'npm run development' ]
11 silly lifecycle @~dev: Returned: code: 1  signal: null
12 info lifecycle @~dev: Failed to exec dev script
13 verbose stack Error: @ dev: `npm run development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid @
15 verbose cwd /Users/ozinclouds/Desktop/lara/ozlara
16 verbose Darwin 18.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v11.4.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @ dev: `npm run development`
22 error Exit status 1
23 error Failed at the @ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ozgurkalan** [comment]
> If you're seeing `sh: node_modules/webpack/bin/webpack.js: No such file or directory`, this isn't a Mix issue. It's related to your `npm install`. It can't even find webpack in your dependencies list. Do you see that file in your `node_modules` directory?

Hi Jeffrey,

I am aware of the error msg and given bold text above. I did a double check again, there is 100 % webpack.js in laravel-mix node_module. 

As in Laravel package.json, there is no explicit call for webpack:
` "devDependencies": {
        "axios": "^0.18",
        "bootstrap": "^4.0.0",
        "cross-env": "^5.1",
        "jquery": "^3.2",
        "laravel-mix": "^4.0.7",
        "lodash": "^4.17.5",
        "popper.js": "^1.12",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.15.2",
        "sass-loader": "^7.1.0",
        "vue": "^2.5.17"
    }`

I have re-installed my prv project packages recently, npm seems to work there fine. 
What am I doing wrong?

**Comment by JeffreyWay** [comment]
Laravel Mix includes webpack as a dependency here:

https://github.com/JeffreyWay/laravel-mix/blob/master/package.json#L63

So if you're doing a full `npm install`, and it can't find `node_modules/webpack/bin/webpack.js`, I'm not sure I can be of much help, unfortunately. Something odd is happening with the installation on your end. 

If I receive more reports, I'll look deeper into it. But so far, yours is the only issue I've seen about this.

**Comment by ozgurkalan** [comment]
@JeffreyWay hi, 

Finally, I have a solution. I wanted to give feedback.

It is somehow related to webpack installed globally, or something else :). Inspired from [https://laracasts.com/discuss/channels/laravel/laravel-mix-tons-of-errors?page=1](url). Thanks to @jijoel.

# Solution:

In package.json, I have replaced `node_modules/laravel-mix/node_modules/webpack/bin/webpack.js` with **webpack**. Sample for development:
`"cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"`


👍
