### ISSUE TITLE
On Build Finished event?

### ISSUE THREAD

**Issue by thepenguin1** [JeffreyWay/laravel-mix#189]
Is there some way to hook into a compilation complete event so that I can execute a small piece of JavaScript code within the webpack.mix.js once a build is finished?

**Comment by JeffreyWay** [comment]
Not at the moment, but we can add that.

**Comment by thepenguin1** [comment]
Fantastic!

For those interested, I'm currently wrapping the code in a setTimeout function with a delay that is appropriate for my current build process, though admittedly this is far from perfect :)

**Comment by JeffreyWay** [comment]
Okay, you'll do:

```js
mix.js('from', 'to')
    .then(() => console.log('Webpack is done building'));
```

I'll tag this update in the morning.

**Comment by thepenguin1** [comment]
Marvellous! Thanks so much @JeffreyWay :)
