### ISSUE TITLE
Laravel Mix 4 installs vue-template-compiler package even if it is redundant

### ISSUE THREAD

**Issue by filipkrstic** [JeffreyWay/laravel-mix#1891]
-   Laravel Mix Version: 4.0.12
-   Node Version: 8.11.1
-   NPM Version: 6.4.1
-   OS: Microsoft Windows 10

### Description:
I have started new Laravel project using latest version (5.7.19) and it is shipped with Laravel Mix 4.0.7. In this project I don't need any frontend scaffolding so I removed Vue scaffolding. After that when I ran `npm install` and then `npm run watch` I am getting this in the console:

> Additional dependencies must be installed. This will only take a moment.
>
>Running: yarn add vue-template-compiler --dev --production=false
>warning " > sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
>
>Okay, done. The following packages have been installed and saved to your package.json dependencies list:
>
>- vue-template-compiler

Why Laravel Mix 4 install this additional and obviously redundant package `vue-template-compiler` on the fly when I have removed Vue from scaffolding and how to get a rid of that package?

After all, I have tried to use Laravel Mix 4.0.7 and 4.0.12 - same thing in both cases.

### Steps To Reproduce:
1. Install new fresh copy of Laravel
2. Run `php artisan preset none`
3. Run `npm install`
4. Run `npm run watch`

**Comment by vladshoob** [comment]
I have a similar problem without setting preset to none, but using default one shipped for Laravel.

I was able to run my npm run ... after
npm install  vue-template-compiler

**Comment by JeffreyWay** [comment]
Mix has always installed this package. The only difference is it's now being pulled in locally. 

Mix was originally built with Vue in mind, so until the next major release, this dependency needs to stay. Just ignore it.

**Comment by lkraav** [comment]
Duplicate of https://github.com/JeffreyWay/laravel-mix/issues/1877

**Comment by mabasic** [comment]
I do not want to have vue-template-compiler dependency in my package.json file. Can it not be forced to install?

**Comment by MunGell** [comment]
Hey, @JeffreyWay you mentioned that this dependency needs to stay until the next major release.
I am on v5 right at the moment and still getting it. Any chance removing it anytime soon?

**Comment by paullaffitte** [comment]
If you need a quick-fix before my PR is merged, I also gived a hack to remove the dependency by hand. https://github.com/JeffreyWay/laravel-mix/issues/1877#issuecomment-596111404
