### ISSUE TITLE
extractVueStyles not working

### ISSUE THREAD

**Issue by mike-grinspan** [JeffreyWay/laravel-mix#1896]
-   Laravel Mix Version: 4.0.12
-   Node Version: 11.4.0
-   Yarn Version: 1.12.3
-   OS: Ubuntu 18.04 Vagrant box on a Windows 7 host

### Description:
With `extractVueStyles` set to either a filename or `true`, no styles get extracted.

### Simplest Reproducible `webpack.mix.js`:
```
require('laravel-mix')
	.options({ extractVueStyles: 'css/app.css' })
	.js('resources/assets/js/app.js', 'public/js')
	.sass('resources/assets/scss/app.scss', 'public/css', { implementation: require('node-sass') });
```

### Steps To Reproduce:
* Use the above `webpack.mix.js` file
* `yarn build`

### Potentially Helpful Info:
- I'm running `vue-loader` 14.2.3 due to an issue with 15 (https://github.com/vuejs/vue-loader/issues/1443)
- I'm using `node-sass` instead of `sass`

**Comment by k8n** [comment]
I'm noting that component styles _are_ extracted when 'scss' preprocessor is specified, i.e.
```
<style lang="scss">
.this_gets_extracted {}
</style>
```
```
<style type="text/css">
.this_will_not_get_extracted {}
</style>
```

Also `extract-text-webpack-plugin` should not be used with webpack 4, [according to the doc](https://github.com/webpack-contrib/extract-text-webpack-plugin). See [vue-loader doc note](https://vue-loader.vuejs.org/guide/extract-css.html#webpack-4) on proper use. Yet, laravel mix 4 still uses the old plugin: [1](https://github.com/JeffreyWay/laravel-mix/blob/master/src/components/Preprocessor.js#L2), [2](https://github.com/JeffreyWay/laravel-mix/blob/master/src/components/Vue.js#L2). @JeffreyWay, Perhaps this is the cause of this issue.

**Comment by ZebTheWizard** [comment]
I noticed this when I was experiencing the same problem.
this works:
```
mix.js('src/index.js', 'dist/index.js')
    .setPublicPath('dist/')
    .setResourceRoot('src/')
    .options({
        extractVueStyles: "dist/vue.css"
    })
```
however, when I try use purifyCss it does not work.
```
mix.js('src/index.js', 'dist/index.js')
    .setPublicPath('dist/')
    .setResourceRoot('src/')
    .options({
        extractVueStyles: "dist/vue.css",
        purifyCss: true
    })
```

**Comment by lk77** [comment]
Hello,

any update on this issue ?

**Comment by machacekmartin** [comment]
Any news on extractVueStyles?
