### ISSUE TITLE
App modules appear in vendor extraction when passing no args to extract

### ISSUE THREAD

**Issue by rtheunissen** [JeffreyWay/laravel-mix#1900]
Using the latest version of mix, we've noticed that some project modules are ending up in our auto-extracted `vendor.js` file. Is the expected behavior instead that only files from node_modules be auto-extracted? What might cause project files to be included?

**Comment by rtheunissen** [comment]
The [webpack documentation](https://webpack.js.org/plugins/split-chunks-plugin/) states that:

> webpack will automatically split chunks based on these conditions: **New chunk can be shared** OR modules are from the node_modules folder.

Is it likely that this means that app code which is shared across bundles might end up in vendor.js? If that is the case, I believe we should explicitly only include files under node_modules.

**Comment by rtheunissen** [comment]
A side-effect of this is that modules imported by two separate scripts on the same page will import the same thing twice, because the shared chunk is no longer in vendor.js

I think a good solution here would be to add a `common.js` file to the manifest/vendor stack, which includes common chunks that are not part of node_modules.

I'm playing with this config at the moment:

```
optimization: {
    splitChunks: {
        cacheGroups: {
            vendor: {
                test: /[\\/]node_modules[\\/]/,
                name: path.join(paths.build, "vendor"),
                chunks: 'all',
                priority: -10,
                enforce: true,
            },
            common: {
                name: path.join(paths.build, "common"),
                chunks: 'all',
                minChunks: 2,
                priority: -20,
                reuseExistingChunk: true
            }
        }
    }
}

**Comment by lkraav** [comment]
Is there a specific analysis command to run for this problem detection?

**Comment by rtheunissen** [comment]
@lkraav I don't know of any. I used a variety of bundle analyzers to determine which modules ended up in which bundle, which is when I noticed that some of our app code was in the automatically extracted `vendor.js` because it was shared between bundles.

**Comment by lkraav** [comment]
https://github.com/FormidableLabs/webpack-dashboard/ has alerted me about bundle duplicates before, but currently I see no alerts, so perhaps I'm not affected (yet).

**Comment by rtheunissen** [comment]
@lkraav there are no duplicates. We have script A and script B that both import module C (in our own application code, not an installed dependency). Webpack sees that module C is a shared chunk, so it includes it as an exclusion, which is how module C ends up in vendor.js
