### ISSUE TITLE
NPM run watch stop building at 70 %

### ISSUE THREAD

**Issue by Akashaj09** [JeffreyWay/laravel-mix#1902]
-   Laravel Mix Version: 4.0.12 (`npm list --depth=0`)
-   Node Version: v11.6.0  (`node -v`):
-   NPM Version: 6.5.0 (`npm -v`):
-   OS:  Windows 10

###Description
I have read a lot about this but none of them helped me. After updating laravel mix, webpack and webpack-cli to latest version npm run watch is not working. Its stopped at 70%. 

###Package.json

{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.18",
        "babel-plugin-root-import": "^5.1.0",
        "bootstrap": "^4.1.3",
        "cross-env": "^5.1",
        "jquery": "^3.2",
        "laravel-mix": "^4.0.12",
        "lodash": "^4.17.5",
        "node-sass": "^4.11.0",
        "npm-registry-fetch": "1.1.0",
        "popper.js": "^1.14.5",
        "resolve-url-loader": "2.3.1",
        "sass": "^1.15.2",
        "sass-loader": "^7.1.0",
        "uglify-es": "git+https://github.com/mishoo/UglifyJS2.git#harmony",
        "vue": "^2.5.7",
        "vue-template-compiler": "^2.5.21"
    },
    "dependencies": {
        "bootstrap-vue": "2.0.0-rc.11",
        "chart.js": "2.6.0",
        "font-awesome": "^4.7.0",
        "imagemin": "^5.3.1",
        "laravel-echo": "^1.5.2",
        "moment": "^2.22.2",
        "moment-timezone": "^0.5.23",
        "simple-line-icons": "^2.4.1",
        "socket.io-client": "^2.2.0",
        "vee-validate": "^2.1.3",
        "vue-awesome-notifications": "^2.2.9",
        "vue-bootstrap-datetimepicker": "^5.0.1",
        "vue-chartjs": "2.8.1",
        "vue-multiselect": "^2.1.3",
        "vue-router": "^3.0.1",
        "vue-search-select": "^2.7.0",
        "vue-strap": "github:wffranco/vue-strap",
        "vue-tel-input": "^2.0.10",
        "vuex": "^3.0.1"
    }
}

###Webpack.mix.js
mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .sass('resources/sass/responsive.scss', 'public/css/responsive.css');

mix.js('resources/dashboard/js/app.js', 'public/backend/js')
    .sass('resources/dashboard/scss/style.scss', 'public/backend/css')
    .sass('resources/dashboard/scss/responsive.scss', 'public/backend/css/responsive.css');

mix.webpackConfig({
    output: {
        chunkFilename: 'js/[name].[chunkhash].js',
    },
});

Here is the screenshoot '
https://imgur.com/a/2lGWnWs

**Comment by aaronkorn** [comment]
Try deleting your .lock files.

See
https://laravel-mix.com/docs/4.0/troubleshooting

**Comment by ngstwr** [comment]
What was the solution for this? I have been facing this issue whenever I try to upgrade laravel-mix package to v4.

**Comment by Akashaj09** [comment]
Deleting lock file won't do anything. The problem i face is mix is not compatible with weebpack 4. So restore to previous version. I don't know what to with latest version
