### ISSUE TITLE
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents

### ISSUE THREAD

**Issue by alighasemzadeh** [JeffreyWay/laravel-mix#1910]
-   Laravel Mix Version: 4.0.12
-   Node Version (`node -v`):9.4.0
-   NPM Version (`npm -v`):5.6.0
-   OS:

### Description:
When I run `npm run production` I get:
````
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
````
### Steps To Reproduce:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by JeffreyWay** [comment]
It's only a warning.
