### ISSUE TITLE
Mix requires vue-template-compiler even though Vue is not used in the project

### ISSUE THREAD

**Issue by janschloss** [JeffreyWay/laravel-mix#1916]
-   Laravel Mix Version: 4.0.7

**Comment by JeffreyWay** [comment]
Mix has always required that package. You're just seeing it more explicitly now. You can ignore it.

**Comment by janschloss** [comment]
Thanks for your answer @JeffreyWay 

Could it be a feature request to only include vue-template-compiler if Vue is used?

**Comment by lkraav** [comment]
This is a duplicate of https://github.com/JeffreyWay/laravel-mix/issues/1877
