### ISSUE TITLE
Unable to output js files to different locations

### ISSUE THREAD

**Issue by brandonferens** [JeffreyWay/laravel-mix#192]
When compiling js files, the first file's output directory in the list is set as the output directory for all. This is referenced in `Mix.js:109` where `this.js[0].output.base` is used. I understand that webpack wants a single value for `output.filename`, but is there a work around or a fix so that files can get compiled to wherever I want them?

Example:
```
mix.js('resources/assets/js/index.js', 'public/js/')
    .js('resources/assets/js/subdirectory/index.js', 'public/js/subdirectory');
```
Both files get compiled and put in the base js directory.

**Comment by JeffreyWay** [comment]
Update your Mix dependency.

**Comment by brandonferens** [comment]
Awesome. Thanks for the quick response.
