### ISSUE TITLE
Using laravel mix outputs distorted urls( with 

### ISSUE THREAD

**Issue by shamseerahammedm** [JeffreyWay/laravel-mix#1922]
I tried `.options({ processCssUrls: false }) ` ( Even though its a css thing ) it didn't solve my problem ,

Images from my composer server loads correctly :

> http://127.0.0.1:8000/product_images/burgerjpg1546494562.jpg

But this is how my webpack browser sync url ( i mean using laravel mix ) of the same image looks like,

> http://localhost:3000/product_images/%7B%7Bimage%7D%7D

```
mix.js('resources/js/site_js/custom.js', 'public/js')
   .sass('resources/sass/site_styles/style.scss', 'public/css')
   .sass('resources/sass/site_styles/mediaquery.scss', 'public/css')
   .options({
           processCssUrls: false
       })
   .browserSync({
      //proxy: process.env.APP_URL,
      proxy: 'http://127.0.0.1:8000',
      files: [
         'resources/views/**/*.php',
         'app/Http/**/*.php',
         'public/assets/js/**/*.js',
         'public/**/*.css',
      ]
   });
```

this is my mix file.

what should i do ?

**Comment by JeffreyWay** [comment]
Duplicate.

**Comment by shamseerahammedm** [comment]
Whats the fix ?

**Comment by shamseerahammedm** [comment]
Whats the fix ? @JeffreyWay
