### ISSUE TITLE
extractVueStyles  cant work

### ISSUE THREAD

**Issue by kemplaw** [JeffreyWay/laravel-mix#1924]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`)
-   Node Version (`node -v`): 10.14.0
-   NPM Version (`npm -v`): 6.4.1
-   OS: windows 7 sp1 x64

### Steps To Reproduce:
use mix.options({
     extractVueStyles: true
  })

**Comment by kemplaw** [comment]
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --color --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "npm run development -- --watch",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run build",
    "build": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "babel-loader": "^8.0.5",
    "cross-env": "^5.1",
    "css-loader": "^0.28.11",
    "laravel-mix": "^4.0.13",
    "style-loader": "^0.23.1",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "vue-loader": "^15.5.1",
    "vue-template-compiler": "^2.5.21",
    "webpack-bundle-analyzer": "^3.0.3"
  },
  "dependencies": {
    "@babel/polyfill": "^7.2.5",
    "area-data": "^5.0.6",
    "axios": "^0.18.0",
    "crypto-js": "^3.1.9-1",
    "echarts": "^4.2.0-rc.2",
    "element-ui": "^2.4.9",
    "fixed-quill-image-resize": "^1.0.0",
    "moment": "^2.22.2",
    "quill-image-extend-module": "^1.1.2",
    "vue": "^2.5.21",
    "vue-area-linkage": "^5.0.2",
    "vue-quill-editor": "^3.0.6",
    "vuex": "^3.0.1"
  }
}

**Comment by JeffreyWay** [comment]
If you're not going to describe the problem, I'm not going to help.
