### ISSUE TITLE
Documentation doesn't inform users about vue-loader

### ISSUE THREAD

**Issue by opensaurusrex** [JeffreyWay/laravel-mix#1928]
-   Laravel Mix Version: 4.0.14 (`npm list --depth=0`)
-   Node Version (`node -v`): v11.6.0
-   NPM Version (`npm -v`): 6.5.0
-   OS: macOS Mojave 10.14.2

### Description:

So I was having issues with running my mix for a little while and was getting the following error when trying to run it: 

    Mac:project me$ npm run watch

    > project@0.4.5 watch /Users/.../project
    > npm run development -- --watch

    > project@0.4.5 development /Users/.../project
    > cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"

    /Users/.../project/node_modules/webpack-cli/bin/cli.js:426
				throw err;
				^
    Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
    Make sure the rule matching .vue files include vue-loader in its use.

Come to find out, you had moved `vue-loader` into the project and being that I was upgrading from v3 to v4, I didn't see anything in the documentation that stated that I no longer needed to use the following:

    let mix = require('laravel-mix');
    let VueLoaderPlugin = require('vue-loader/lib/plugin');
    
    mix.webpackconfig({
      module: {
        rules: [
          {
            test: /\.vue$/,
            loader: 'vue-loader'
          }
        ]
      },
      plugins: [
        new LiveReloadPlugin(),
        new webpack.ProvidePlugin({
          $: 'jquery',
          jQuery: 'jquery',
          'window.jQuery': 'jquery'
        }),
      ],
    });

Would you be able to add some documentation somewhere in the upgrade logs, stating that it is no longer needing to manually be included? For anyone upgrading that was previously using v2, it may cause issues if they don't know about it. Unless you have and I am just missing them.

### Steps To Reproduce:

Add the Vue Loader plugin in like above, and try runnning it. Lack of documentation regarding `vue-loader` had me repeatedly reinstalling and trying out different things until I found that you had the `vue-loader` in the `laravel-mix` `package.json` and I tried removing it to find that it worked perfectly without it.

**Comment by JeffreyWay** [comment]
vue-loader was included with Mix on day one. Nothing has changed.
