### ISSUE TITLE
Run prod without progress

### ISSUE THREAD

**Issue by SudoGetBeer** [JeffreyWay/laravel-mix#1929]
Is it possible to run 'npm run prod' without the progress output?

Our envoyer deploy log is really 'messy' because of that.

I tried --progress which worked for some time I think.

**Comment by stefanzweifel** [comment]
You could update your build script to pipe the output to `/dev/null`.

```shell
npm run prod > /dev/null 2>&1
```

**Comment by SudoGetBeer** [comment]
@stefanzweifel yeah I know, but I thought I maybe can get the minimal output with the runtime etc in Envoyer
