### ISSUE TITLE
sass is required even when it is not in dependencies

### ISSUE THREAD

**Issue by mciesin** [JeffreyWay/laravel-mix#1934]
-   Laravel Mix Version: 4.0.14
-   Node Version: 10.15.0
-   Yarn Version: 1.13.0
-   OS: Windows 10

### Description:
I want to use node-sass instead of sass because I am also using Vue and /deep/ selectors. On the other hand, I also have several `mix.sass(...)` calls, because of standalone sass files.

#1850 fixed the issue of having `sass` in dependencies, but still in `src/components/Sass.js` we have got:
```js
pluginOptions(pluginOptions) {
    return Object.assign(
        {
            precision: 8,
            outputStyle: 'expanded',
            implementation: () => require('sass')
        },
        pluginOptions,
        { sourceMap: true }
    );
}
```

There is a fixed `require('sass')` here, although I don't have sass in my dependencies, nor is it required by dependencies of Sass component, which results in `Cannot find module 'sass'` error displayed.

IMO there should be a condition check, similar to one in dependencies of Sass component or in sassCallback from Vue component (`src/components/Vue.js`), leaving the implementation field empty or with node-sass when `Mix.seesNpmPackage('sass')` is false.

**Comment by JeffreyWay** [comment]
You should only see "Cannot find modules 'sass'" if you did not override the implementation in your `mix.sass()` call.

**Comment by mciesin** [comment]
Yes, you are right.

But when you have dozens of sass calls, it is very inconvenient to override the implementation in every call. When you have only one sass lib in your dependencies, it is a clear sign, that the user wants to default to this particular implementation :).

You assumed this in two other places, so for me it would be natural to also check for existance of sass implementation in the place described in this issue ;).

What do you think :)?
