### ISSUE TITLE
Multiple .sass() with the same entry point doesn't work.

### ISSUE THREAD

**Issue by RobinBertilsson** [JeffreyWay/laravel-mix#1936]
-   Laravel Mix Version: 4.0.14
-   Node Version: 8.12.0
-   NPM Version: 6.4.1
-   OS: macOS Mojave 10.14.2

### Description:
When you're using multiple mix.sass() with the same entry point, webpack will throw an error, saying "configuration.entry['mix'] should not contain the item 'default.scss' twice". This is a huge problem in my situation, and i think others might have the same issue.

For a better usecase, please take a look at my example code [here](https://github.com/RobinBertilsson/laravel-mix-multiple-sass-same-entry-issue/blob/master/webpack.mix.js)

### Steps To Reproduce:
1. Clone my [repository](https://github.com/RobinBertilsson/laravel-mix-multiple-sass-same-entry-issue.git).
2. `npm i && npm run dev`

**Comment by timgavin** [comment]
@RobinBertilsson I asked for help with this on the Laracasts forum and there actually is a way to do it

https://laracasts.com/discuss/channels/elixir/combining-multiple-less-files

In my case I created a `desktop.less` file and a `mobile.less` file, then imported my less files into each. Something like:

#### desktop.less
```
@import 'variables.less';
@import 'desktop_styles.less';
@import 'shared.less';
```

#### mobile.less
```
@import 'variables.less';
@import 'mobile_styles.less';
@import 'shared.less';
```

In my `webpack.mix.js` file

```
mix.less('resources/assets/less/desktop.less', 'public/app.less');
mix.less('resources/assets/less/mobile.less', 'public/mobile.less');
```

Worked perfectly.

**Comment by RobinBertilsson** [comment]
@timgavin, well yeah - that's not the problem i have, i you don't have the same content in desktop.less and mobile.less, however, mine does.

The only way to solve this (for me) was to create two exactly identical .scss files, (default1.scss and default2.scss).

Which is wrong if you ask me.

**Comment by princezuk** [comment]
You can disable "uniqueItems" in webpack API Schema, go to /node_modules/webpack/schemas/WebpackOptions.json and set "uniqueItems": false.
