### ISSUE TITLE
Mix silently skips missing files with no errors

### ISSUE THREAD

**Issue by PaulMesko** [JeffreyWay/laravel-mix#1937]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`): 4.0.14
-   Node Version (`node -v`): 10.15
-   NPM Version (`npm -v`): 6.4.1
-   OS: Windows 10 1809

### Description:
Mix does not give any warnings or errors on running when source files are missing.  It will spit out a compiled file using whatever it found, and silently ignore the rest.  Yikes.  This makes the package essentially unusable if you care about the integrity of your compiled assets.

### Steps To Reproduce:
1. Create a new laravel project
2. Set up mix: `npm install`
3. Add some files to webpack.min.js for mix to compile using `mix.styles` or `mix.scripts` (or others?)
`mix.scripts(['resources/js/jquery.js',
                    'resources/js/bootstrap.js'], 'public/js/app.js');`
4. `npm run dev` (or production)
`     Asset     Size  Chunks             Chunk Names
\js\app.js  206 KiB          [emitted]`
5. Delete or rename one of the js source files and run it again
6. Observe how mix silently ignores the missing source file and produces no warnings or errors.
 `     Asset      Size  Chunks             Chunk Names
\js\app.js  84.9 KiB          [emitted]`

Alternatively you can just put some made up file names in:
`mix.scripts(['resources/js/important.js',
			 'resources/js/important2.js'], 'public/js/app.js');`
`Asset     Size  Chunks             Chunk Names
\js\app.js  0 bytes          [emitted]`

**Comment by bulkbinclub** [comment]
Also experiencing this issue (caused quite a headache and production bugs).

Laravel Mix Version: 4.0.15
Node Version: 8.11.3
NPM Version: 6.1.0

**Comment by renegadedata** [comment]
This is still an issue with both the combine and scripts method. Missing files are ignored and no errors are generated, which makes these features virtually unusuable.

Windows 10
Laravel Mix Version 4.1.2
Node Version 10.16.0
NPM Version 6.7.0
