### ISSUE TITLE
Mix still overwriting assets with same name

### ISSUE THREAD

**Issue by mciesin** [JeffreyWay/laravel-mix#1938]
-   Laravel Mix Version: 4.0.14
-   Node Version: 10.15.0
-   Yarn Version: 1.13.0
-   OS: Windows 10

### Description:
Description available here: #1761.

This is a very annoying behavior, especially when working with many files and many developers.

**Comment by pawel-wlodarski** [comment]
up!

**Comment by wzaleski** [comment]
Same... ;(

**Comment by penance316** [comment]
Did anyone ever get a solution to this? 
I am requiring images like this from VUE.
``require(`./Data/${this.dynamicField}/mymaps-${this.anotherDynamicField}.png`);``

I have 2 dynamic fields here but the final images gets loaded into the "images" directory so they end up overriding each other.
images/mymaps-1.png
images/mymaps-1.png
images/mymaps-2.png
images/mymaps-2.png

I have attempted changing the webpack config to output the entire path for images.
```
test: /\.(png|jpe?g|gif|webp)$/,
        loaders: {
          loader: 'file-loader',
          options: {
            name: '[path][name].[ext]?[hash]',
            context: 'resources/assets',
          },
        },
```
This will build the images into the correct directory however the VUE component still ends up looking for the images in the original directory like "images/abc.png".

**Comment by alexanderhorner** [comment]
This shouldn't be closed!
