### ISSUE TITLE
'npm run watch' endless loop of rebuilding css

### ISSUE THREAD

**Issue by lkreher** [JeffreyWay/laravel-mix#1942]
-   Laravel Mix Version: laravel-mix@4.0.14
-   Node Version: 10.15.0
-   NPM Version: 6.4.1
-   OS: Windows 10

### Description: 
Trying to compile an scss file, the _watch_ task will build the css over and over multiple times per second.

### Steps To Reproduce:
**webpack.mix.js**
```
let mix = require('laravel-mix');
mix.sass('resources/assets/sass/test.scss', 'public/css');
```
**test.scss**
```
@import 'test2';

@font-face {
    font-family: 'Open Sans Light';
    src: url('../fonts/open-sans-v15-latin-300.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}
```
**_test2.scss**
```
/*
A
*/
```

**Result:**
```
 10% building 1/1 modules 0 active
webpack is watching the files…
98% after emitting SizeLimitsPlugin DONE  Compiled successfully in 1620ms12:08:58
Asset       Size  Chunks             Chunk Names
                                                     /css/test.css  204 bytes     mix  [emitted]  mix
fonts/open-sans-v15-latin-300.ttf?177cc92d2e8027712a8c1724abd272cd     27 KiB          [emitted]
 WAIT  Compiling...12:08:58

 98% after emitting SizeLimitsPlugin DONE  Compiled successfully in 33ms12:08:58
Asset       Size  Chunks             Chunk Names
                                                     /css/test.css  204 bytes     mix  [emitted]  mix
fonts/open-sans-v15-latin-300.ttf?177cc92d2e8027712a8c1724abd272cd     27 KiB          [emitted]
 WAIT  Compiling...12:08:58

 98% after emitting SizeLimitsPlugin DONE  Compiled successfully in 24ms12:08:59
Asset       Size  Chunks             Chunk Names
                                                     /css/test.css  204 bytes     mix  [emitted]  mix
fonts/open-sans-v15-latin-300.ttf?177cc92d2e8027712a8c1724abd272cd     27 KiB          [emitted]
[... continuing forever]
```

The font file linked by `url()` exists and is copied as expected. Using a single line comment instead of a multiline comment in _test2.scss works as expected and does not exhibit this behavior. Moving the multiline comment to test1.scss and removing the `@import` works as expected, and removing the `@font-face` also prevents the loop. It's the combination of `@import`, `@font-face` and the multiline comment in the imported file that cause the _watch_ task to loop.

Needless to say, _dev_ and _prod_ tasks work perfectly fine, everything is compiled properly, no errors anywhere.

**Comment by lkreher** [comment]
The issue does not exist in `laravel-mix@3.0.0`

**Comment by ankurk91** [comment]
Are you using sass-loader ?

**Comment by lkreher** [comment]
> Are you using sass-loader ?

yes

```
+-- sass@1.16.0
+-- sass-loader@7.1.0
```

**Comment by pjhartin** [comment]
I've got the same issue using postCss

Continually get 
`98% after emitting SizeLimitsPlugin` output to console

**Comment by raicem** [comment]
I'm having a very similar issue as well. If I import a image to my bundle it goes into endless loop when working using `npm run watch`. `npm run dev` works fine and creates my bundle.

**Comment by StanAngeloff** [comment]
This is a sample script which will reproduce the issue in a new empty directory:

```sh
#!/bin/sh

curl -LO https://raw.githubusercontent.com/laravel/laravel/5.7/package.json

npm i

echo "const mix = require('laravel-mix'); mix.sass('./sass/default.scss', 'css/default.css');" > webpack.mix.js

mkdir -p sass/
echo "body { background-image: url('../images/logo.svg'); }" > sass/default.scss

mkdir -p images/
curl -L https://upload.wikimedia.org/wikipedia/commons/3/30/Vector-based_example.svg -o images/logo.svg

npm run watch
```

For the issue to manifest itself, the Sass file has to be in its own directory and has to import an image from an upper-level directory. The CSS must be outputted in a separate directory, too.

This doesn't seem to be related to `node-sass` at all (after examining `package-lock.json`, `node-sass` is not present.

**Comment by rafailml** [comment]
Any solutions of this?

**Comment by Morpheus-ro** [comment]
if you put the image to `resources/images` they will be automatically copied to the `public/images` and there will be no loop present :)
the same goes with the font `resources/fonts` copied to `public/fonts`

**Comment by ncla** [comment]
rafailml solution worked. I recently upgraded laravel-mix to v5 and it was producing endless loop too. I just did `yarn remove sass sass-loader`, then `yarn run watch` and it offered to install the dependencies automatically.

```
 	Additional dependencies must be installed. This will only take a moment.
 	Running: npm install sass-loader@8.* sass --save-dev --production=false
```

My `sass` and `sass-loader` dependencies were outdated.
```
-        "sass": "^1.15.2",
-        "sass-loader": "^7.1.0",
+        "sass": "^1.25.0",
+        "sass-loader": "^8.0.2",
```

After that the issue was gone. This could be prevented for others in the future by providing upgrade guide to v5, which does not exist currently.

**Comment by amans199** [comment]
credits to **Morpheus-ro** 
for those who are searching for more clear solution >>
Don't put any new files ( fonts or images ) in the public or dist folder .. put them in your resources and the compiler will take care of copying them into your public folder ..

**Comment by AlexioVay** [comment]
This issue seems like it can have multiple error sources. In my case I it was relevant to **Tailwind CSS** and the `purge` option. I don't remember exactly what package I have installed but I copy pasted the following to my `tailwind.config.js`:

    module.exports = {
        mode: 'jit',
        purge: {
            content: [
                './public/**/*.html',

After I have removed the line `'./public/**/*.html',` it worked.

**Comment by f-liva** [comment]
I have found a solution to use pattern globes as usual on Tailwind 3. Install the fast-glob package and define the pattern list with it, like this:

`yarn add fast-glob -D`

and then

```js
module.exports = {
    content: require('fast-glob').sync([
        './**/*.php'
    ]),
    theme: {
        extend: {},
    },
    plugins: [],
}
```
It works perfectly and solves the problem of the rebuild loop.

**Comment by baezor** [comment]
> 

This one fixed my issue! Thanks!

**Comment by mostafa-A48** [comment]
> This issue seems like it can have multiple error sources. In my case I it was relevant to **Tailwind CSS** and the `purge` option. I don't remember exactly what package I have installed but I copy pasted the following to my `tailwind.config.js`:
> 
> ```
> module.exports = {
>     mode: 'jit',
>     purge: {
>         content: [
>             './public/**/*.html',
> ```
> 
> After I have removed the line `'./public/**/*.html',` it worked.

Removing the `'./public/**/*.html',` is not the solution you should put it there for working with jit mode then use this [solution](https://github.com/laravel-mix/laravel-mix/issues/1942#issuecomment-998148038)

**Comment by mostafa-A48** [comment]
For those who currently switched to `Tailwind CSS V3` and are uing `jit` mode this `[solution](https://github.com/laravel-mix/laravel-mix/issues/1942#issuecomment-998148038)` actually works.
In my case I am using [Laravel Jigsaw](https://jigsaw.tighten.co/) here is my tailwind.config.js file
![mix-with-tailwindcss3](https://user-images.githubusercontent.com/44500373/148210891-5b65e395-680b-47ce-b0ff-4aa5d15fa49c.JPG)

**Comment by adrelliott** [comment]
@mostafa-A48 this solved it for me - thanks!

For anyone reading this using the 'blog' starter template with jigsaw, you also need to include `vue` as an extension. 

my `tailwind.config.js` file:

````
module.exports = {
    content: require('fast-glob').sync([
        'source/**/*.{blade.php,md,html,vue}'.  // Added 'vue'
        ],{ dot: true }),
    theme: { ...

````

**Comment by COBNETCKNN** [comment]
> This solution makes it possible to continue using glob patterns even with Laravel Mix:
> 
> `yarn add fast-glob -D` and then
> 
> ```js
> module.exports = {
>     content: require('fast-glob').sync([
>         './**/*.php'
>     ]),
>     theme: {
>         extend: {},
>     },
>     plugins: [],
> }
> ```
> 
> It works perfectly and solves the problem of the rebuild loop.

After hours of trying to fix this, this worked for me.

**Comment by Jarrid** [comment]
> This issue seems like it can have multiple error sources. In my case I it was relevant to **Tailwind CSS** and the `purge` option. I don't remember exactly what package I have installed but I copy pasted the following to my `tailwind.config.js`:
> 
> ```
> module.exports = {
>     mode: 'jit',
>     purge: {
>         content: [
>             './public/**/*.html',
> ```
> 
> After I have removed the line `'./public/**/*.html',` it worked.

This was 100% my issue after upgrading to tailwindcss 3.0.  That's what I get for copying the docs EXACTLY.

**Comment by shaffe-fr** [comment]
Using `fast-glob` worked:
```js
content: require('fast-glob').sync([
    './css/**/*.css',
    './js/**/*.js',
    './**/*.php',
], { dot: true }),
```

I also added the following to the webpack.mix.js:
```js
.webpackConfig({
        resolve: {
          fallback: {
            fs: false,
            os: false,
            path: false,
            stream: false,
          },
        }
    })
```

**Comment by chriskirby-dev** [comment]
Seems to me like almost all these issues have something to do with a post-compilation file being written which kicks off watch once again over and over if you are adding a file after compilation if you have your own manifest file or something like that and are saving it to resources This will throw watch into an infinite loop.
