### ISSUE TITLE
url() paths incorrect for images in CSS when using HMR

### ISSUE THREAD

**Issue by jameshulse** [JeffreyWay/laravel-mix#1944]
-   Laravel Mix Version: 4.0.5
-   Node Version (`node -v`): 10.13.0
-   NPM Version (`npm -v`): 6.4.1
-   OS: OS X

### Description:

Assets which are loaded via `url(...)` in my SASS are incorrectly being given a relative path such as: `./images/icon.svg` when using hot module reloading. All assets should be loaded via the webpack-dev-server so the paths should honour the `hmrOptions`.

The hmrOptions are *correctly* applied to the base webpack publicPath (see: https://github.com/JeffreyWay/laravel-mix/blob/master/src/builder/WebpackConfig.js#L65-L69) but the publicPath for the file-loader always defaults to `/`.

I propose similar logic should take HMR into account in the file-loader logic.

### Steps To Reproduce:

1. Include an svg icon from a SASS file
2. Configure a host and port using `hmrOptions`
2. Use `mix.sass(...)` to compile your SASS assets
3. Run webpack using `--hot` via the mix config
4. The svg icon will 404 as it will be using a relative path such as `url(./images/icon.svg)` rather than `url(http://localhost:8080/images/icon.svg)`.

### Solution

To fix the issue temporarily I have conditionally overwritten the `resourceRoot` configuration value:

```
mix.options({
    hmrOptions: {
        host: 'http://localhost',
        port: '8080',
    },
    resourceRoot: Mix.isUsing('hmr') ? 'https://localhost:8080/' : '/',
})
```

**Comment by ankurk91** [comment]
If you have absolute that in your css like -
```
url("/images/image.jpg");
```
you are telling webpack to skip processing it, and this image should be loaded from the document root (to be served by apache NOT by node), in Laravel file should be placed at path `public/images/image.jpg` in order to load.

Read more
https://css-tricks.com/quick-reminder-about-file-paths/

Notice  that a slash `/` make huge difference in CSS.

**Comment by jameshulse** [comment]
Thank for the reply, I forgot that detail as I was writing out the examples but I can confirm that the paths in my CSS are *relative* and not absolute. I'll edit it to add the dots.
