### ISSUE TITLE
4.0.12 not parsing .vue files with pug templating engine 

### ISSUE THREAD

**Issue by MatsLeal** [JeffreyWay/laravel-mix#1953]
-   Laravel Mix Version: 4.0.12
-   Node Version v8.1.3
-   NPM Version 6.4.1
-   OS: MacOs Mojave 

### Description:

When upgrading laravel mix from 2.1.11 to 4.0.12, the pug loader ( used in .vue files to simplify html syntax ) stops working, laravel-mix does not detect that loader anymore and there fore throws this error
`component template requires a root element rather than just text.`

### Steps To Reproduce:

Create a new laravel app
Cdin into the folder of the app and run this commands

nom install pug, npm install bulma

Create a .vue component under the resources/js/components folder, and import that component in your resources/js/app.js main file

The component has to look like this 

```
<template lang="pug">
nav.navbar

</template>

<script>
export default {


  data () {
    return {

    }
  }
}
</script>

<style lang="sass" scoped src="bulma">
</style>
```

In past versions of laravel mix, that component would be compiled down, but in the current version, upon running `npm run watch` we receive an error ( specified in the initial part of the description )

Please aid us on this issue

**Comment by jevets** [comment]
@MatsLeal 
Adding the webpack config fixed it for me:
https://github.com/JeffreyWay/laravel-mix/issues/1885

@ankurk91 That used to work, but now it seems to require the extra webpack config
