### ISSUE TITLE
Vendor css file and extractVueStyles, I'm missing something..

### ISSUE THREAD

**Issue by renzo-s** [JeffreyWay/laravel-mix#1954]
-   Laravel Mix Version: 4.0.14
-   Node Version (`node -v`): 11.0.0
-   NPM Version (`npm -v`): 6.6.0
-   OS: OSX

### Description:
Hi all!

I'm trying to get rid of the injected styles in the `<head>` from node_module packages (vue components). I've been digging around several days now, but I'm guessing I'm missing a piece of the puzzle.

Tried several forms of;
`extractVueStyles: '[name].css'` => This never resulted in any extracted files.

After I couldn't get that to work, I found several similar questions / issues:

  - https://github.com/JeffreyWay/laravel-mix/issues/1589
  - https://github.com/JeffreyWay/laravel-mix/issues/1050
  - https://github.com/JeffreyWay/laravel-mix/issues/1896

Reading up on this, the `ExtractTextPlugin` / `mini-css-extract-plugin` seemed to make sense to try. The `ExtractTextPlugin` resulted in errors like `TypeError: Cannot read property 'find' of undefined`. Ok, this plugin is depricated for Webpack 4 anyway. Maybe there are unresolved issues.

Then `mini-css-extract-plugin` resulted in errors like `Error: Rule can only have one result source (provided use and loaders)`. I figured that Mix was already doing some extracting magic behind the scenes and the loaders were clashing.

So what am I missing to achieve creating a vendor.[HASH].css? 17 style tags (some of which are empty), with such a high specificity (since it's injected) is not really something to go into production with.

Thanks in advanced for any pointers.

My webpack.mix.js file:

```js

const mix = require('laravel-mix');
const webpack = require('webpack');

const domain = 'my-domain.mac'

mix.browserSync({
    host:  domain,
    proxy: 'https://'+domain,
    open: 'external',
    browser: 'google chrome canary',
    files: [
       /* .. not relevant for example .. */
    ],
    https: {
        key: `/Users/my-name/.valet/Certificates/${domain}.key`,
        cert: `/Users/my-name/.valet/Certificates/${domain}.crt`,
    }
})

mix
    .setPublicPath('html/')
    .disableNotifications()
    .webpackConfig({
        // Ignore all momentjs locales, decreases bundle size greatly
        plugins: [
            new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
        ],
    })
    .options({
        // Tried several options like, true, vendor.css
        extractVueStyles: '[name].css',
    })
    .js('resources/js/shared.js', 'js/')
    .js('resources/js/login.js', 'js/')
    .js('resources/js/users.js', 'js/')
    .sass('resources/scss/style.scss', 'css/')
    .extract()

if (mix.inProduction()) {
    mix.version()
} else {
    mix.webpackConfig({ devtool: 'inline-source-map' })
    mix.sourceMaps()
}
```

**Comment by bigperson** [comment]
I  have some problem.

**Comment by incraigulous** [comment]
I have this issue too!
