### ISSUE TITLE
Invalid Host/Origin header when running hot

### ISSUE THREAD

**Issue by zimonline** [JeffreyWay/laravel-mix#1955]
-   Laravel Mix Version: 4.0.7 
-   Node Version (`node -v`): v11.6.0
-   NPM Version (`npm -v`): 6.5.0
-   OS: macOS 10.14.2

### Description:
When I run
```bash
npm run hot
```
or
```bash
yarn run hot
```
I get this in the console
``` 
app.js:22362 Invalid Host/Origin header
error	@	app.js:22362
onmessage	@	app.js:22632
EventTarget.dispatchEvent	@	app.js:3691
(anonymous)	@	app.js:4408
SockJS._transportMessage	@	app.js:4406
EventEmitter.emit	@	app.js:3607
WebSocketTransport.ws.onmessage	@	app.js:6482
app.js:22365 [WDS] Disconnected!
close	@	app.js:22365
onclose	@	app.js:22608
EventTarget.dispatchEvent	@	app.js:3691
(anonymous)	@	app.js:4490
setTimeout (async)		
SockJS._close	@	app.js:4478
SockJS._transportMessage	@	app.js:4418
EventEmitter.emit	@	app.js:3607
WebSocketTransport.ws.onmessage
```
### Steps To Reproduce:
New install of Laravel

app.js
```javascript
import Vue from 'vue';

Vue.component('sample-component', require('./components/sample-component.vue').default);

const app = new Vue({
    el: '#app'
});
```

sample-component.vue
```javascript
<script>
    export default {
    }
</script>

<template>
    <div>
        Sample Fault Component
    </div>
</template>
```

welcome.blade.php
```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>Sample Fault Page</title>
    </head>
    <body>
        <div id="app">
           <sample-component />
        </div>

        {{--
            This works if I run yarn run dev
            <script src="/js/app.js"></script>
        --}}
        <script src="http://localhost:8080/js/app.js"></script>
    </body>
</html>
```

**Comment by zimonline** [comment]
> Add ` --disable-host-check` parameter to `hot` script in package.json
> 
> ```
> "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --disable-host-check --config=node_modules/laravel-mix/setup/webpack.config.js",
> ```
> Read more
> https://webpack.js.org/configuration/dev-server/#devserver-disablehostcheck

Thanks. I can confirm this works and as hot is only used in development the security issues are not relevant.

**Comment by domstubbs** [comment]
It looks as though explicitly configuring the HMR host is another pretty simple solution to this:

    mix.options({
        hmrOptions: {
            host: 'your.test.domain'
        }
    });

Having said that, if you need to support multiple devs who may be using different test domains it’s going to be simpler just to disable the check outright.

**Comment by zimonline** [comment]
As I can't ever see where people would run hot in production 
 --disable-host-check
should be there by default so that this works out of the box.
