### ISSUE TITLE
Invalid asset revisions with workbox-webpack-plugin

### ISSUE THREAD

**Issue by Rainrider** [JeffreyWay/laravel-mix#1956]
-   Laravel Mix Version: 4.0.14 (`npm list --depth=0`)
-   Node Version (`node -v`): v11.4.0
-   NPM Version (`npm -v`): 6.4.1
-   OS: Windows 10 Pro

### Description:

When using [workbox-webpack-plugin](https://www.npmjs.com/package/workbox-webpack-plugin) to generate a service worker, the resulting precache-manifest includes files with the same revision hash despite having different contents. Which files have the same revision hash depends on the list order in webpack.mix.js. This behavior breaks workbox precaching because cache updates depend on the revision hashes.

### Steps To Reproduce:

1. run `composer create-project laravel/laravel test`
2. run `npm remove laravel-mix`
3. run `npm i laravel-mix --save-dev`
4. run `npm i workbox-webpack-plugin --save-dev`
5. create new file `resources/assets/js/add.js` (can be empty, contents don't matter)
6. change webpack.mix.js to:  
```js
let mix = require('laravel-mix');
const workbox = require('workbox-webpack-plugin');

mix.webpackConfig({
  plugins: [new workbox.GenerateSW()],
  output: {
    publicPath: '' // see https://github.com/JeffreyWay/laravel-mix/issues/1717
  }
});

mix.js('resources/assets/js/app.js', 'public/js')
   .js('resources/assets/js/other.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');
```
7. run `npm run dev` (or `npm run prod`, it doesn't matter)
8. observe app.js and app.css having the same revision hash in the `public/precache-manifest{hash}.js`
9. change `resources/assets/sass/app.scss` contents (the change itself doesn't matter)
10. re-run step 7
11. observe no change in either hashes
12. switch other.js and app.js order in webpack.mix.js:  
```js
mix.js('resources/assets/js/other.js', 'public/js')
   .js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');
```
13. observe other.js and app.css having the same revision hash now

**Comment by OzanKurt** [comment]
Any updates about this?
