### ISSUE TITLE
inProduction() is not working in mix version 4

### ISSUE THREAD

**Issue by bsrinisrini** [JeffreyWay/laravel-mix#1957]
-   Laravel Mix Version: 4.0.7 (`npm list --depth=0`)
-   Node Version (`node -v`): 8.12.0
-   NPM Version (`npm -v`): 6.4.1
-   OS: CentOS 7

### Description:
I had mix.config.inProduction in mix version 2.1.14 and it was working fine. 
Now trying to upgrade mix version to 4.0.7 and it is throwing error for mix.confix.inProduction - config is undefined.
Based on documentation I have tried mix.inProduction(), but it is also throws error inProduction is undefined.

### Steps To Reproduce:

Just add below condition in webpack.mix.js and trying to run `npm run dev`
if(mix.inProduction()) {
console.log("Inside production");
mix.version();
}

**Comment by jkudish** [comment]
I had the same issue. It's because of `Deprecated .mix Property Removed` as listed here: https://github.com/JeffreyWay/laravel-mix/releases/tag/v4.0.0

Just change:

```
const { mix } = require('laravel-mix');
```

to:

```
const mix = require('laravel-mix');
```
