### ISSUE TITLE
Copy function creates extraneous subfolders

### ISSUE THREAD

**Issue by mark-vesterskov** [JeffreyWay/laravel-mix#196]
First off, I'm loving Mix! My workflow has tripled in speed with HMR: you've done an amazing job of making the hardly-understood webpack usable for the regular joe like me. Thanks, @JeffreyWay.

I'm on Mix 0.5.8 via NPM.

When I'm doing a copy with the flatten option off, the output folder is appended the full directory structure of the input folder.

Example:

Say i have a file in `node_modules/font-awesome/fonts/folder/file.txt` and the following Mix config:

`mix.copy('node_modules/font-awesome/fonts/**', 'public/fonts/', false);`

Results in file being output to `public/fonts/node_modules/font-awesome/fonts/folder/file.txt`.

Expected:

File being output to `public/fonts/folder/file.txt`.

**Comment by adriaanzon** [comment]
Remove the `false` argument on `mix.copy`, that will 'flatten' the directory structure. See https://github.com/JeffreyWay/laravel-mix/blob/master/docs/copying-files.md

**Comment by JeffreyWay** [comment]
Yeah flattening should do it.

**Comment by mark-vesterskov** [comment]
That I've tried - but flattening the structure means that all files end in the `public/fonts/` folder, regardless of their folder structure in the from-folder.

So removing the false argument (which was the setting before todays 0.5.8 release) results in file being output to `public/fonts/file.txt.` and not `public/fonts/folder/file.txt.` as expected. Does it make sense?

**Comment by JeffreyWay** [comment]
@mark-vesterskov - You shouldn't need to add the two stars, like you did here:

```js
mix.copy('node_modules/font-awesome/fonts/**', 'public/fonts/', false);
```

Just do:

```js
mix.copy('node_modules/font-awesome/fonts', 'public/fonts/', false);
```

**Comment by mark-vesterskov** [comment]
@JeffreyWay Thanks - it was a remnant from my old Gulp build process. All is well, stars removed.
