### ISSUE TITLE
The laravel mix issue with react

### ISSUE THREAD

**Issue by moeen-basra** [JeffreyWay/laravel-mix#1964]
-   Laravel Mix Version: 4.0.14
-   Node Version (`node -v`): 11.1.0
-   NPM Version (`npm -v`): 6.5.0
-   Yarn Version (`yarn -v`): 1.12.3
-   OS: Ubunut 16.04

### Description:
I'm using react with laravel and when I'm running command `yarn dev` in case of defaut webpack config its working fine. When I try to extract vendors using following configration in webpack.mix
```
mix.react('resources/js/app.js', 'public/js')
  .extract()
  .sass('resources/sass/app.scss', 'public/css')
```
 Its creating chunks in public root instead of public/js/ directory and scss not getting compile at all

### Steps To Reproduce:

Change the `webpack.mix.js` configration 

```
mix.react('resources/js/app.js', 'public/js')
  .extract()
  .sass('resources/sass/app.scss', 'public/css')
```

or even when I provide list of libs in extract function

```
mix.react('resources/js/app.js', 'public/js')
  .extract(['react', 'react-router-dom'])
  .sass('resources/sass/app.scss', 'public/css')
```

**Comment by batFormat** [comment]
Try this.

```
mix.react('resources/js/app.js', '')
    .setPublicPath('public/js/app')
    .webpackConfig({
        output: {
            publicPath: '/app/',
            chunkFilename: 'chunk/[name].js'
        }
    });
```
