### ISSUE TITLE
infinite panding js in hot if i add .version()

### ISSUE THREAD

**Issue by dementor5** [JeffreyWay/laravel-mix#1971]
-   Laravel Mix Version: 4.0.14 (`npm list --depth=0`)
-   Node Version (`node -v`):10.15.1
-   NPM Version (`npm -v`): 6.7.0
-   OS:

### Description:
If i add .version() to webpack.mix.js it brakes hot. Page simple not loading - infinite pending of css and js assets loading: https://ibb.co/chWw9w0

### Steps To Reproduce:
composer create-project --prefer-dist laravel/laravel blog
cd blog
add `.version()` to the webpack.mix.js:
<pre>
mix.js('resources/js/app.js', 'public/js')
   .sass('resources/sass/app.scss', 'public/css')
   .version();
</pre>
add `<script src="{{ mix('js/app.js') }}"></script>` before `</body>` in resources/views/welcom.blade.php
npm i
php artisan serve
npm run hot
open http://localhost:8000/
add: console.log('test'); to the bottom of resources/js/app.js and save it

**Comment by ankurk91** [comment]
hot does not work with version.
