### ISSUE TITLE
manifest path is wrong

### ISSUE THREAD

**Issue by dvlpr91** [JeffreyWay/laravel-mix#1972]
Hi...

my **webpack.mix.js**
```
...

mix.extract(['axios'], 'public/js/core').autoload('axios');

mix.js([
  'resources/js/a/app.js'
], 'public/js/a');

mix.js([
  'resources/js/b/app.js'
], 'public/js/b');

...

mix.version();
```

**result**

...
public/js/core.js (vendor)
public/js/b/manifest.js
...

what?

**Comment by msonowal** [comment]
@dvlpr91 
Did you manage to fix this?

**Comment by dvlpr91** [comment]
> @ dvlpr91
> 이 문제를 해결할 수 있었 습니까?

No, I cant.
This can not be done.

**Comment by dvlpr91** [comment]
> @dvlpr91
> Did you manage to fix this?

No, I cant.
This can not be done.

**Comment by kebien6020** [comment]
After looking around in the source code I managed with this:

```js
mix .override(config => {
        config.optimization.runtimeChunk.name = '/js/manifest'
    })
```

**Comment by adampatterson** [comment]
This was closed, but I have the same issue only it works with the `.js` but the `.react` seems to be causing the issue now.
