### ISSUE TITLE
Proposal: Exclude folders from copyDirectory

### ISSUE THREAD

**Issue by austenc** [JeffreyWay/laravel-mix#1973]
-   Laravel Mix Version: 4.0.14
-   Node Version: 11.3.0
-   NPM Version: 6.5.0
-   OS: Mojave

### Description:

Hello! I'd like to revisit the idea of how copyDirectory works. I think we can change this in a backwards-compatible way and also fill a hole in mix's functionality since the prior version where `copy` had this method signature
`copy(from, to, flatten = true)`

Although `copy` and `copyDirectory` work for most cases, _it seems like many people are missing a way to copy a directory but exclude certain files/folders_. For example, in one of our apps we have some older jquery code that we don't want to load on every page. This is organized into subfolders of js files, and we need to publish them to the public folder. I'd like to use mix to copy all the js files (while maintaining folder structure!), but not copy things like `.vue` components. 

### Steps To Reproduce:
In the example screenshot, the `components` folder contains `.vue` files. There is no way to copy everything in the JS folder _except_ the components directory _while maintaining original folder structure_.
![image](https://user-images.githubusercontent.com/575421/52127130-7365b400-25ee-11e9-87fe-1d6f0324f76a.png)

Happy to discuss options or provide more info as for why we'd need this if wanted. Thank you!

**Comment by austenc** [comment]
Is this something that might be added again in a future version of mix? Seems like it would be pretty useful and I've yet to find any workaround.

**Comment by Furgas** [comment]
Would be great to have. My use case is that I'm using Subversion (yeah, I know) and pulling some assets via svn:externals. When external are checked out, for each external there is a `.svn` directory with SVN internal data. I'd like to exclude `.svn` folders from copying by Mix. For production build currently I'm using:
```
"scripts": {
    "build": "cross-env NODE_ENV=production webpack --progress --hide-modules && rimraf public/*/*/.svn"
  }
```
In `watch` or `hot` builds it won't work that way and things breaks often because TortoiseSVN (I'm on Windows) likes to block some files in `.svn` folders.

**Comment by austenc** [comment]
I'd be happy to submit a PR for this if it would be something that might be added back in. Would love to not publish our vue component source files to the public folder 👍

**Comment by austenc** [comment]
@jeffreyway is this something that would be a welcome addition?

**Comment by jordanade** [comment]
Still need this.

```[webpack-cli] Error: Cannot overwrite directory '/Users/jordan/Projects/jottful/public/css/icomoon/.DS_Store' with non-directory '/Users/jordan/Projects/jottful/resources/assets/sass/icomoon/.DS_Store'.```
