### ISSUE TITLE
[Vue warn]: Failed to mount component: template or render function not defined.  (found in root instance)

### ISSUE THREAD

**Issue by jericopulvera** [JeffreyWay/laravel-mix#198]
When I compiled using laravel mix in one of my old projects I get this error
```
[Vue warn]: Failed to mount component: template or render function not defined. 
(found in root instance
```

it works fine on Laravel elixir. why do I get this error?

**Comment by jericopulvera** [comment]
solved it by deleting all of the folders in node_modules that has vue in it and run npm install again.

**Comment by sandervanhooft** [comment]
@jericopulvera Reinstalling the node modules (`rm -rf node_modules/ && npm i`) didn't fix it for me. Any clue?

**Comment by sandervanhooft** [comment]
Nvm, it was a issue with the Vue package I was using :).

**Comment by adelynx** [comment]
It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.

**Comment by MRROOX** [comment]
> It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.

It Works for me thank you!

**Comment by nitesh146** [comment]
> It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.

Worked for me too! thanks a lot...

**Comment by afshinhatampour** [comment]
> It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.

thank you worked for me

**Comment by mwangaben** [comment]
Nice works @adelynx

**Comment by ricus-zero2one** [comment]
> It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.

Had to update +- 200 vue components to add .default but happy to say it works

**Comment by mwangaben** [comment]
nice thanks for the insight

**Comment by L-tech** [comment]
> It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.

Thanks. This worked for me

**Comment by Jacq** [comment]
I had also this error: "Failed to mount component: template or render function not defined ..."
, when loading an App.vue only with <template><div>Hello</div></template> using:
new Vue({
    el: '#app',
    render: h => h(App),
})

I had no issues with the missing .default, I am using import. I found other relations of this error to the use of the vue runtime instead of the full vue dist >but that was not my case.

Finally I notice that I had enabled the VueLoaderPlugin and the vue-loader rule:
> {
>         test: /\.vue$/,
>         loader: 'vue-loader'
> }
If I remove that rule the above error goes away.
Was my rule overriding some vue default configuration from laravel-mix which created the above error?, 
Cheers

**Comment by pengmingzengdd01** [comment]
＠adelynx 

> It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.

Thanks,It works

**Comment by audetcameron** [comment]
So is the answer changing 
```
 Vue.component('example-component', require('./components/ExampleComponent.vue'));

```
to
```
 Vue.component('example-component', require('./components/ExampleComponent.vue').default);
```
for all components?

**Comment by creditfirst612** [comment]
> It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.

thanks. it works fine to me.

**Comment by thaque20** [comment]
> 
> 
> It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.

Thanks. I'm new to laravel vue. And working on my first project. This seemed a deadline for me, and yet, the solve found. Thanks a lot.

**Comment by sbassah** [comment]
> It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.

Thanks. It worked for me.

**Comment by nandapp** [comment]
> It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.

Super works, you save my day, thanks

**Comment by SerafimArts** [comment]
Very strange, but I did not fix it...

![image](https://user-images.githubusercontent.com/2461257/71919098-df548300-3194-11ea-9945-26d8a2740bb8.png)

`Test.vue`:
```
<template>
    <span>Example</span>
</template>

<script>
    export default {
        name: "ui-test"
    }
</script>
```

**Comment by imtiazraqib** [comment]
> It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.

This was the fix I needed, thank you so much.

**Comment by muhammadali7768** [comment]
> solved it by deleting all of the folders in node_modules that has vue in it and run npm install again.

Thanks removing node_modules directory and running `npm install ` worked for me

**Comment by nolros** [comment]
FWIW in some cases, such as running Vue CLI ui,  the package-json.lock file is changed. People then just delete the CLI project, but the lock file still has CLI code which will cause rendering issues like above.   I spent half the day troubleshooting this for a customer today. Discovered that they had created a Vue CLI project in their existing app and then deleted the Vue CLI project directory without any changes in CLI ui. So none of the above worked. I only came upon the reference when reading the lock file. I deleted the `package-lock.json` file and then ran `npm install `which recreated a new lock file and everything was back to normal.

**Comment by farhangkomad** [comment]
> It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.

Worked for me too! Thanks ..

**Comment by chaderenyore** [comment]
cxv

**Comment by chaderenyore** [comment]
> It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.

Everyone is saying it's working...
Please help me cause It doesnt apply to me.

**Comment by audetcameron** [comment]
> > It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.
> 
> Everyone is saying it's working...
> Please help me cause It doesnt apply to me.

what version of laravel-mix are you using ?

**Comment by chaderenyore** [comment]
> > > It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.
> > 
> > 
> > Everyone is saying it's working...
> > Please help me cause It doesnt apply to me.
> 
> what version of laravel-mix are you using ?

Please am not Using laravel.
am using pure vue.js

**Comment by audetcameron** [comment]
> > > > It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.
> > > 
> > > 
> > > Everyone is saying it's working...
> > > Please help me cause It doesnt apply to me.
> > 
> > 
> > what version of laravel-mix are you using ?
> 
> Please am not Using laravel.
> am using pure vue.js

if you are not using larave-mix, outside of laravel.  Then I suggest you start here https://vuejs.org/v2/guide/single-file-components.html

**Comment by mtariq786** [comment]
> It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.

worked for me also!

**Comment by arukompas** [comment]
For me, the problem was with the Vue.js version 2.2.2
```
export default {
  components: {
    VideoPlayer: () => import('App/components/VideoPlayer.vue'),
  }
}
```

This caused the error `[Vue warn]: Failed to mount component: template or render function not defined.` when trying to load that component.

**Solution** was to upgrade the Vuejs to the latest version 2.6.12. As soon as I did that, dynamically loaded components started working. Hope this helps someone who's in the same boat :)

**Comment by hnamvuong** [comment]
> So is the answer changing
> 
> ```
>  Vue.component('example-component', require('./components/ExampleComponent.vue'));
> ```
> 
> to
> 
> ```
>  Vue.component('example-component', require('./components/ExampleComponent.vue').default);
> ```
> 
> for all components?
> 
> Update:
> 
> https://laravel-mix.com/docs/4.0/upgrade
> 
> :)

thank u so much! it work for me

**Comment by Silver-IT** [comment]
I got the similar issues now regarding vue.js in Laravel Jetstream Livewire.
I don't have errors but I have got several warnings now.

```
[Vue warn]: Property or method "style" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)

[Vue warn]: Property or method "open" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
```

I got some more warnings either.
Is there anyone who have faced this kind of issue and ready to fix all of these?

**Comment by azizbekr** [comment]
> It should be **require('./components/Example.vue').default**. Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require.

Thanks)) it works!!!

**Comment by MuhammadNuman24** [comment]
I also apply the above strategies but no one work  for me

**Comment by MuhammadNuman24** [comment]
Only Home component is not running here is my code `import Vue from 'vue'
import VueRouter from 'vue-router'
import About from "../views/About.vue"
Vue.use(VueRouter)

const routes = [
  {
    path: '/',
    name: 'Home',
    component:{
      default:()=>import('../views/laptop.vue'),
      Mobile:()=>import('../views/mobile.vue')
    }
  },
  {
    path: '/about',
    name: 'About',
    component: About,
  }`

Can anuone help me to solve the issue

**Comment by pnk0006** [comment]
I am having the same issue. in my project, we are not using vue-router. we are creating components and the backend will render a path and enable components for pages. here is my dependencies 
"dependencies": {
    "chart.js": "^3.6.2",
    "facebook-login-vuejs": "^2.1.3",
    "google-maps-api-loader": "^1.1.1",
    "idempotent-babel-polyfill": "^7.0.0",
    "jest-junit": "^6.4.0",
    "jest-localstorage-mock": "^2.4.0",
    "jest-serializer-vue": "^2.0.2",
    "lodash": "^4.17.21",
    "simple-vue-validator": "^0.16.0",
    "sinon": "^7.4.1",
    "swiper": "^6.8.4",
    "vue": "^2.6.14",
    "vue-browser-geolocation": "^1.8.0",
    "vue-chartjs": "^3.5.1",
    "vue-country-region-select": "^2.0.16",
    "vue-google-login": "^2.0.5",
    "vue-jest": "^3.0.4",
    "vue-loading-overlay": "^3.0.4",
    "vue-select": "^3.13.0",
    "vue-slick-carousel": "^1.0.6",
    "vue-template-compiler": "^2.6.14",
    "vue-toasted": "^1.1.28",
    "vue2-datepicker": "^3.10.2",
    "vuelidate": "^0.7.6",
    "vuex": "^3.6.2"
  }
  
  can anyone help me to solve this issue I have to use this swiper

**Comment by audetcameron** [comment]
> I am having the same issue. in my project, we are not using vue-router. we are creating components and the backend will render a path and enable components for pages. here is my dependencies "dependencies": { "chart.js": "^3.6.2", "facebook-login-vuejs": "^2.1.3", "google-maps-api-loader": "^1.1.1", "idempotent-babel-polyfill": "^7.0.0", "jest-junit": "^6.4.0", "jest-localstorage-mock": "^2.4.0", "jest-serializer-vue": "^2.0.2", "lodash": "^4.17.21", "simple-vue-validator": "^0.16.0", "sinon": "^7.4.1", "swiper": "^6.8.4", "vue": "^2.6.14", "vue-browser-geolocation": "^1.8.0", "vue-chartjs": "^3.5.1", "vue-country-region-select": "^2.0.16", "vue-google-login": "^2.0.5", "vue-jest": "^3.0.4", "vue-loading-overlay": "^3.0.4", "vue-select": "^3.13.0", "vue-slick-carousel": "^1.0.6", "vue-template-compiler": "^2.6.14", "vue-toasted": "^1.1.28", "vue2-datepicker": "^3.10.2", "vuelidate": "^0.7.6", "vuex": "^3.6.2" }
> 
> can anyone help me to solve this issue I have to use this swiper

what version of laravel and or mix?   newer versions of mix have a .vue() function directly in the mix.js config.
