### ISSUE TITLE
processCssUrls option is not working when used with the styles method

### ISSUE THREAD

**Issue by raghavendra89** [JeffreyWay/laravel-mix#1985]
-   Laravel Mix Version: 4.0.14
-   Node Version: 10.15.1
-   NPM Version: 6.4.1
-   OS: Mac OS 10.14

### Description: 
`processCssUrls` option is not working when used with the `styles` method. 
I'm trying to concatenate several plain css files. I also want to process the relative urls in these css files. But the urls are copied as they are.

### Steps To Reproduce:
1. Write the below code in the webpack.mix.js file with the corresponding files
   
    ```let mix = require('laravel-mix');
    mix.styles([
            'public/assets/global/plugins/font-awesome/css/font-awesome.min.css',
            'public/assets/global/plugins/bootstrap/css/bootstrap.min.css',
            'public/assets/custom/css/custom.css',
        ], 'public/css/global.css').options({
            processCssUrls: true
        });

2. Run `npm run production`

**Does the processCssUrls option work with the styles method?**

**Comment by josegus** [comment]
Same here, did not find any solution to thiss. Maybe this is not an issue, since this example is not in the docs.

**Comment by kyranb** [comment]
Having this issue too.
