### ISSUE TITLE
Extract is moving too many modules to vendor

### ISSUE THREAD

**Issue by mciesin** [JeffreyWay/laravel-mix#1986]
-   Laravel Mix Version: 4.0.14
-   Node Version: 10.15.1
-   Yarn Version: 1.13.0
-   OS: Windows 10

### Description:
When extracting a lib using the extract e.g. `->extract(['vue'])`, all the libs that start with `vue`: `vuex`, `vue-tables-2`, etc. are moved to `vendor.js`.

Scripts that exist inside local node_modules of another module e.g. `node_modules\vue-tables-2\node_modules\vue\dist\vue.common.js` are moved too.

**Comment by pawel-wlodarski** [comment]
Nice solution! @JeffreyWay merge this PR please.
