### ISSUE TITLE
Wrong directory when compiling javascript and extracting vendor libraries combined with a custom webpack output

### ISSUE THREAD

**Issue by eriktisme** [JeffreyWay/laravel-mix#1992]
-   Laravel Mix Version: 4.0.14
-   Node Version (`node -v`): v11.7.0
-   NPM Version (`npm -v`): 6.5.0
-   OS: macOS Mojave

### Description:
When running ```yarn run development``` or ```yarn run production``` with  a custom webpack output and ```extract()``` the compiled js file and vendor is in the wrong directory.

### Result
```
// Actual
"/js//js/vendor.js": "/js//js/vendor.js?id=2634320e6a395cad66fa",
"/js//js/main.js": "/js//js/main.js?id=9290e4a2c71e4335353d",
"/js/manifest.js": "/js/manifest.js?id=cf5b735f0847479e5b7f",

// Expected
"/js/vendor.js": "/js/vendor.js?id=2634320e6a395cad66fa",
"/js/main.js": "/js/main.js?id=9290e4a2c71e4335353d",
"/js/manifest.js": "/js/manifest.js?id=cf5b735f0847479e5b7f",
```

### Steps To Reproduce:
- Add the code below to your webpack.mix.js
- Run ```yarn run development``` or ```yarn run production```

```
mix
.js('resources/app/js/main.js', 'public/js')

.version()

.extract()

.webpackConfig({
  output: {
    publicPath: '/',

    chunkFilename: 'js/[name].js'
  },
});
```

**Comment by wishinghand** [comment]
I'm getting the same issue. Hard to believe this is still out in the open. Are there just not that many developers using Vue on top of Laravel and extracting vendors?
