### ISSUE TITLE
SCRIPT1003: Expected ':' main.js (143651,12) Error in I.E-11 after updating laravel mix version from 2.0 to 4.0.14

### ISSUE THREAD

**Issue by Sukhpall-Singh** [JeffreyWay/laravel-mix#1994]
-  Laravel Veriosn: 5.7.25
-   Laravel Mix Version: 4.0.14
-   Node Version : v10.14.1
-   NPM Version : 6.4.1:
-   OS: Windows

### Description:

I have created a vuejs template with laravel integration. On creating project with vue-laravel, by default the laravel-mix version is 2.0 and at that time my project is running well in all browsers. But now I am updating version of laravel-mix from 2.0 to 4.0.14. On updating it, blank screen should be display on I.E browser. As I am new in vue+laravel and not enough knowledge about it. I am trying to resolve this issue by following many links but didn't get the results. Please anyone knows how it should be possible to run vue+laravel project on IE and what changes are required. 

 Here is my webpack.mix.js file code:

  ```
  //webpack.mix.js

    let mix = require('laravel-mix');
    
    /*
     |--------------------------------------------------------------------------
     | Mix Asset Management
     |--------------------------------------------------------------------------
     |
     | Mix provides a clean, fluent API for defining some Webpack build steps
     | for your Laravel application. By default, we are compiling the Sass
     | file for the application as well as bundling up all the JS files.
     |
     */
     mix.autoload({
      'jquery': ['$', 'window.jQuery', 'jQuery'],
     })
       
    mix.js('resources/js/main.js', 'public/js');
```

Here is my development dependencies in package.json file:

     
   ```
 // package.json
    "devDependencies": {
      "axios": "^0.18",
      "babel-preset-stage-2": "^6.24.1",
      "bootstrap": "^4.1.3",
      "cross-env": "^5.2.0",
      "jquery": "^3.3.1",
      "laravel-mix": "^4.0.14",
      "lodash": "^4.17.11",
      "node-sass": "^4.11.0",
      "popper.js": "^1.14.6",
      "sass-loader": "^7.1.0",
      "vue": "^2.5.19",
      "vue-template-compiler": "^2.5.22"
    },
"dependencies": {
        "amcharts3": "^3.21.14",
        "auth0-js": "^9.8.2",
        "axios": "^0.18.0",
        "babel-cli": "^6.26.0",
        "babel-plugin-syntax-dynamic-import": "^6.18.0",
        "babel-polyfill": "^6.26.0",
        "babel-preset-es2015": "^6.24.1",
        "chart.js": "^2.7.3",
        "echarts": "^4.2.0-rc.2",
        "vue-count-to": "^1.0.13",
        "vue-echarts": "^3.1.3",
        "vue-i18n": "^8.4.0",
        "vue-resource": "^1.5.1",
        "vue-router": "^3.0.2",
        "vuetify": "^1.4.4",
        "vuex": "^3.0.1",
        "weather-icons": "^1.3.2"
    }
```
.babelrc file code:

  ```
  //.babelrc
    {
      "plugins": ["syntax-dynamic-import"]
    }

```
If anyone needs more info let me know. Thanks!

**Comment by dpgalloway** [comment]
Seeing the same issue. Was this ever resolved?

**Comment by Sukhpall-Singh** [comment]
Yeah, I resolved by removing the package "vue-loading-spinner". It may dependency issue with laravel-mix version. Check your packages that whether your package is compatible with laravel version or not. If you don't know the package due to which you are facing the issue then remove your package one by one and then check which package arising this issue.
It might helps you.
