### ISSUE TITLE
Extract() doesn't create vendor file on running for production

### ISSUE THREAD

**Issue by Mushr0000m** [JeffreyWay/laravel-mix#1996]
-   Laravel Mix Version: 4.0.14 (`npm list --depth=0`)
-   Node Version (`node -v`): 8.0.0
-   NPM Version (`npm -v`): 5.5.1
-   OS:

### Description:
I'm trying to extract all `node_modules` vendor to a separate `vendor.min.js` file, and it's working perfectly when running `npm run dev`, but when running `npm run prod` the `vendor.min.js` file is not created and not present in the `manifest.js`. I have no clue why I'm having this issue only for prod, here is my `webpack.mix.js` :
```
mix.sass('resources/sass/app/master.scss', 'theme/app.min.css');
mix.ts('resources/js/app/master.ts', 'theme/app.min.js');
mix.extract('theme/vendor.min.js');
mix.version();
mix.options({
    processCssUrls: false,
    autoprefixer: {
        options: {
            browsers: ['last 5 versions', 'Explorer >= 10', '> 1%']
        }
    }
});
mix.webpackConfig({
    resolve: {
        alias: {
            '@app': path.resolve(__dirname, 'resources/js/app'),
            '@vendor': path.resolve(__dirname, 'vendor')
        }
    }
});
```

### Steps To Reproduce:

Use the same `webpack.mix.js` as a pasted before and it should do the same.

**Comment by peakhmr** [comment]
I can't even setup alias, It just doesn't work and when I use dynamic import `mix.extract()` blow up 😂
