### ISSUE TITLE
Fantastic Work Jeffrey!

### ISSUE THREAD

**Issue by strebl** [JeffreyWay/laravel-mix#2]
Thanks Jeffrey for your fantastic work!
Already tested it a little bit, really amazing!
As I know you, I think you'll polish that even more and add some features.
I saw something that didn't work yet. But I'll wait until you say it's is "finished".
I don't want that you think I expect a finished product yet^^
Just wanted to say thank you 😊

**Comment by JeffreyWay** [comment]
Thanks! But tell me what didn't work.

**Comment by strebl** [comment]
In my case, trying to use the code splitting feature of vue / webpack didn't work.
https://router.vuejs.org/en/advanced/lazy-loading.html

Maybe that's not the 80% case you're targeting. But I think it's not that hard to support that.
I enabled it by adding following line to the webpack config:
```js
module.exports.output.chunkFilename = '/js/[id].backend.[hash].js'
if (!Mix.hmr) {
    module.exports.output.publicPath = ''
}
```
I didn't test anything else. Just tried to get it working.

Another thing I found is that it isn't possible to have multiple `.js()` calls like:
```js
mix.sass('resources/assets/sass/app.scss', 'public/css')
   .js('resources/assets/js/frontend/frontend.js', 'public/js')
   .js('resources/assets/js/backend/backend.js', 'public/js')
   .version(['js/frontend.js', 'js/backend.js', 'css/app.css'])
```

I don't expect anything, just reporting my findings.

**Comment by tillkruss** [comment]
I'd love to see support for multiple `.js()` calls as well.

**Comment by JeffreyWay** [comment]
I added support for multiple mix.js() calls the other day. Give it a try. 

You can also now pass an array for your src files. This will merge them into the one bundle.

```js
mix.js(['path/to/one.js', 'path/to/two.js'], 'dist/bundle.js');

mix.js('path/to/file.js', 'dist/');
     .js('path/to/other.js', 'dist');
```

**Comment by josephemmanuel** [comment]
Pls how  do i solve this issue
i am new to webpack
'Code splitting / Lazy Loading Vue Routes
In my case, trying to use the code splitting feature of vue / webpack didn't work.
https://router.vuejs.org/en/advanced/lazy-loading.html'
