### ISSUE TITLE
asset_url configuration is not supported by mix() 

### ISSUE THREAD

**Issue by TheBigK** [JeffreyWay/laravel-mix#2001]
-   Laravel Mix Version: 4.0.14
-   Node Version (`node -v`): 11.9.0
-   NPM Version (`npm -v`): 6.8.0
-   OS: MacOS (High Sierra)

### Description:
Laravel Mix does not obey the `asset_url` available in Laravel that allows having dynamic asset URL - local or CDN. 

Here's the reference tweet by Taylor Otwell: https://twitter.com/taylorotwell/status/1062866359607062528?s=20

We are therefore unable to take advantage of Cache Bursting feature of Laravel Mix while hosting our assets on the CDN.

As of now loading assets urls via `mix()` method refers to the local version of the assets inside `public` directory. It'd be awesome if there is a way to make `mix()` make use of the `asset_url`. 

I'm not sure if it's a bug or a feature that's missing from Mix. But it'd be awesome to have it! Thanks.

**Comment by ankurk91** [comment]
You should report it to `laravel/framework`.

The `mix()` needs to adjusted, nothing related to this repo.

**Comment by TheBigK** [comment]
I think it's something that mix could handle. I'm talking about the function that loads the URLs inside blade templates-

```
<script src="{{ mix('js/app.min.js')}}"></script>

```
If the asset URL is defined, this should append the CDN or local URL. 

I'm aware that this could be changed via a tweak; but it'd be nice to have it supported by mix itself.

**Comment by edcoreweb** [comment]
@TheBigK the `mix()` function is not defined in this repo. It's part of `laravel/framework`.
So you cannot change it here. This is @ankurk91 was saying.

**Comment by TheBigK** [comment]
Alrighty, thank you. Will report it there.
