### ISSUE TITLE
[Request] Add support for swc transpiler

### ISSUE THREAD

**Issue by winkbrace** [JeffreyWay/laravel-mix#2005]
### Request

swc claims to transpile to javascript much quicker than babel. It would be great to be able to select it as a transpiler in configuration settings.

https://swc-project.github.io/

**Comment by ankurk91** [comment]
SWC is quite new and it does not have all of the transformations that babel has.
I would suggest to wait unless it is mature enough.

There are many other babel alternatives for example:
https://github.com/Rich-Harris/buble

**Comment by winkbrace** [comment]
Ok :)

**Comment by lmammino** [comment]
Any plan to reconsider this since now SWC is much more established (even used with next.js)?

**Comment by d8vjork** [comment]
Not fully tested yet, but needed this for some massive projects I'm maintaining with Laravel mix.

https://github.com/open-southeners/laravel-mix-swc
