### ISSUE TITLE
laravel mix 4.0.15 extract styles from js files

### ISSUE THREAD

**Issue by leotankilevich** [JeffreyWay/laravel-mix#2006]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`)
-   Node Version (`node -v`):
-   NPM Version (`npm -v`):
-   OS:

### Description:
My webpack.mix.js file 

require('dotenv').config();

let mix = require('laravel-mix');

mix.js('frontend/src/static/js/entries/UI.js', 'dist/js').js('frontend/src/static/js/entries/index.js', 'dist/js');

    mix.sass('frontend/src/static/scss/main.scss', 'dist/css');

mix.setPublicPath('backend/web/');

mix.combine(['backend/web/dist/css/main.css', 'backend/web/dist/css/style.css'], 'backend/web/dist/css/dashboard.css');

mix.sourceMaps();

mix.browserSync({
    proxy: `http://dash.terminal.${process.env.BS_ENV}.vagrant/`,
    files: [
        'frontend/{*,**/*}.scss',
        'frontend/{*,**/*}.js',
        'frontend/{*,**/*}.twig',
        'backend/views/{*,**/*}.php',
        'backend/views/{*,**/*}.twig',
        'backend/widgets/{*,**/*}.twig',
        'backend/widgets/{*,**/*}.js',
        'backend/widgets/{*,**/*}.css',
    ]
});

mix.options({
    processCssUrls: true,
    extractVueStyles: process.env.NODE_ENV === 'development' ? false : 'backend/web/dist/css/style.css',
    postCss: [
        require('postcss-flexbugs-fixes')
    ],
    autoprefixer: {
        options: {
            browsers: [
                'last 6 versions',
            ],
            errors: true
        }
    }
});
### Steps To Reproduce:

when i'm starting production build, style extracted only from the last js entry point in mix.js() method.
It worj only when i call mix.js(['frontend/src/static/js/entries/UI.js','frontend/src/static/js/entries/index.js'], 'dist/js'), but i need two separate bundles.
How to extract style from react-components and plain js-files?

**Comment by BenesX** [comment]
i use laravel and get the similar problem with you, packing a empty css file to me

**Comment by Deg5112** [comment]
I think this might be related but when i have mix.react and mix.sass, the generated app.css is more or less empty. if i remove mix.sass it works
