### ISSUE TITLE
Vue styles before the other CSS after saving in watch mode instead of after

### ISSUE THREAD

**Issue by vHeemstra** [JeffreyWay/laravel-mix#2007]
-   Laravel Mix Version: 4.0.14
-   Node Version: 8.12.0
-   NPM Version: 6.8.0
-   OS: Win 10

### Description:
When running `npm run watch`:
-  the first (initial) produced `app.css` has all SCSS and CSS styles first and the Vue extracted SCSS and CSS styles second (this is great 👍)
-  but after saving one of the SCSS or Vue files, the order of these is swapped (Vue styles first, others second) (not so great...)

Why is this? And how can I fix it?

### Steps To Reproduce:

1) Take the default Laravel installation
2) Install [postcss-calc](https://github.com/postcss/postcss-calc) (`npm install postcss-calc --save-dev`)
3) Add a Vue component file with a `<style lang="scss">` block with some styles
4) Change mix/webpack set-up:
```
mix
    .js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .options({
        postCss: [
            require('autoprefixer'),
            require('postcss-calc'),
            require('cssnano')({
                discardComments: {
                    removeAll: true,
                },
            }),
        ],
        extractVueStyles: true, // either here or above the postCss doesn't change the outcome
    })
    .extract();

if (mix.inProduction()) {
    mix.version();
} else {
    mix
        .webpackConfig({
            devtool: 'source-map'
        })
        .sourceMaps();
}
```
5) Run `npm run watch`
6) View `app.css`
7) Save the Vue component file and/or SCSS file (with or without changes made)
8) Review the rebuilt `app.css` --> different order of content from 6.

I would really appreciate any help with this and a big 👍 to all contributors for the excellent Laravel system!

**Comment by vHeemstra** [comment]
Is there any news on this issue?

**Comment by vHeemstra** [comment]
Did anyone find a solution?

**Comment by oziged** [comment]
Any updates?
