### ISSUE TITLE
Exclude dependency library for custom js.

### ISSUE THREAD

**Issue by maengkom** [JeffreyWay/laravel-mix#201]
I have a custom js below just few lines of set DataTables code. And set in mix :

`mix.js('resources/js/a_type.js', 'public/js/a_type.js');
`

the output always include jquery library so the filesize is big. How to remove jquery from output js ?
```
\\ a_type.js
var table = $('#table').DataTable({
    order: [1, 'desc'],
    ajax: { url: '/vm/type/data', type: 'POST' },
    columns: [
        { data: 'id', name: 'id' },
        { data: 'name', name: 'name' },
        { data: 'created_at', name: 'created_at' },
        { data: 'updated_at', name: 'updated_at' },
    ]
})
```

**Comment by adiachenko** [comment]
Chain `.autoload({})` call in your mix config.

Currently, ProvidePlugin kinda replaces `$('#table')` in your code with `require('jquery')('#table')`.

**Comment by JeffreyWay** [comment]
I'm not entirely sure how to interpret your question, but you can either:

1. Remove the jQuery references in your source code.
2. Use mix.extract() to move jQuery into its own vendor file.

**Comment by maengkom** [comment]
Thanks @adiachenko @JeffreyWay 

Sorry I'm new to webpack, and @adiachenko explaination is my solution. Now if I have jquery sign `$` in these js files : 

```
mix.js('resources/js/a.js', 'public/js/a.js');
mix.js('resources/js/b.js', 'public/js/b.js');
```

will exclude jquery code when I comment the `$: 'jquery'` line.

    ```
    new webpack.ProvidePlugin(Mix.autoload || {
        jQuery: 'jquery',
        // $: 'jquery',    <== here
        jquery: 'jquery',
        'window.jQuery': 'jquery'
     }),
    ```

**Comment by JeffreyWay** [comment]
Yes. It ensures that jQuery is available anywhere, if you reference it. If you don't want that, you can do `mix.autoload({})`.

**Comment by pantagruel964** [comment]
I excluded jQuery from webpack.config and package.json and got conflicts with some plugins and npm run can't finish compiling with some jQuery UI components without jQuery. It's terrible.
My solution is use mix.combine instead of mix.js.
