### ISSUE TITLE
npm run hot doesn't work with mix.version()

### ISSUE THREAD

**Issue by Lunatig** [JeffreyWay/laravel-mix#2011]
-   Laravel Mix Version: 4.0.14
-   Node Version : v10.15.0
-   NPM Version (`npm -v`): 6.4.1
-   OS: Windows 10

when i run 
npm run hot
all working well before first changes in css or js files.
in console
[HMR] Waiting for update signal from WDS...
[WDS] Hot Module Replacement enabled.
After changes. 
[WDS] App updated. Recompiling... 

but if i disable mix.version() all working

**Comment by ankurk91** [comment]
Search before reporting, it has been reported tons of times

**Comment by Lunatig** [comment]
Thanks. but css still does not update

**Comment by Lunatig** [comment]
> I worked around it by wrapping the mix.version call in an if statement:
> 
> ```js
> if (!process.argv.includes('--hot')) {
>     mix.version()
> }
> ```

**Comment by scheinercc** [comment]
@ankurk91 while that might be true, this is the only thread I found and even that took me a while. So I am glad it was raised ... again!? Is there a fix planned to make them both work together? Is there an open ticket for it? Or can you link some old closed once for reference? Thanks!

**Comment by ankurk91** [comment]
Agree this should have been fixed within source code but no one cares.
