### ISSUE TITLE
Proposal: Add a default vue Blade template or update documentation

### ISSUE THREAD

**Issue by xatzy** [JeffreyWay/laravel-mix#2013]
### Description:

Just spent an afternoon to try to make a view JS blade template work. Issue was that there was a .extract within webpack.min.js which (for optimization reasons if I understand correctly) generates multiple files, which have to be included within the blade templates if we want vue.js to work:
<script src="/js/manifest.js"></script>
<script src="/js/vendor.js"></script>
<script src="/js/app.js"></script>

I don't think this was documented anywhere so I would suggest adding a basic VuejsExample.blade.template somewhere or adding a section on vue.js in the documentation to specify that this extract function exists , because it was very hard to debug this

### Steps To Reproduce:

Create a blade template for view, with a component, only include for instance js/frontend.js in the blade template. The component will stay empty.

**Comment by rs-sliske** [comment]
https://github.com/JeffreyWay/laravel-mix/blob/master/docs/extract.md
