### ISSUE TITLE
Modifying options for the SASS loader

### ISSUE THREAD

**Issue by leinelissen** [JeffreyWay/laravel-mix#2015]
Hey guys,

Some time ago, I created a plugin for enabling CSS Modules for React builds. It doesn't do a whole lot, but add some babel config, and inject options into any css-loader it can find. The code is available [here](https://github.com/leinelissen/laravel-mix-react-css-modules/blob/master/src/ReactCSSModules.js).

The plugin was built for Mix v2, but also works in v3. v4 is generally fine, except that it doesn't work with SASS correctly. If a user sets up the SASS importer in `webpack.mix.js`, it'll correctly convert everything to CSS, but it won't correctly activate the CSS modules functionality.

I have noticed that SASS is now optionally included in the Webpack config. This apparently also means that I cannot modify any SASS-related rules in my plugins `webpackConfig()` function, since it's not part of the base Webpack config. 

Is this assumption correct? And is there a way of modifying the SASS-related rules, or would I have to inject any SASS-rules directly from my plugin? I would preferably just modify the options for any css-loaders I can find, so that it can work with any CSS preprocessor that is required.

I trust you can offer some guidance. Thanks in advance!

Lei

**Comment by evan-duncan** [comment]
Is there a way to work around this by setting a custom `webpackConfig` in my webpack.mix.js file?

**Comment by leinelissen** [comment]
@evan-duncan Probably, but this means you'll have to be able to actually override the CSS loader that Laravel Mix provides. I have tried testing this, but my results have come up dry, as the `webpackConfig` option only allows for deep merges, and the loaders come as an array. Actually overwriting the config object is only supported as part of plugins. I hope you can work something out, but until this issue is fixed, I cannot really do anything.

**Comment by evan-duncan** [comment]
@leinelissen It looks like you're not rewriting all of the css-loaders in your extension. I removed the length check on this line and it seems to be working https://github.com/leinelissen/laravel-mix-react-css-modules/blob/master/src/ReactCSSModules.js#L71
