### ISSUE TITLE
npm run prod dropped

### ISSUE THREAD

**Issue by AlexeyTcapaev** [JeffreyWay/laravel-mix#2019]
![image](https://user-images.githubusercontent.com/25639891/53465726-2398d200-3a60-11e9-8184-9cc27d751191.png)

-   Laravel Mix Version: 4.0.14
-   Node Version 11.9.0
-   NPM Version 6.8.0
-   OS:Win10

### Steps To Reproduce:
mix.file:
![image](https://user-images.githubusercontent.com/25639891/53465767-5a6ee800-3a60-11e9-9d52-df966dbcd54b.png)
app.js
![image](https://user-images.githubusercontent.com/25639891/53465794-6a86c780-3a60-11e9-8ac2-aabf581018c7.png)
and after build try to open :
![image](https://user-images.githubusercontent.com/25639891/53465816-7f635b00-3a60-11e9-8fc7-b2d9282b1ba9.png)
![image](https://user-images.githubusercontent.com/25639891/53465826-8ab68680-3a60-11e9-9e20-cc39a67bd2fc.png)

**Comment by AlexeyTcapaev** [comment]
UPD:i rollback mix version to  "laravel-mix": "^2.0", and it works greatest -_-

**Comment by edcoreweb** [comment]
I think you are using dynamic imports which are not supported anymore.

**Comment by AlexeyTcapaev** [comment]
@edcoreweb thank you for answer, why not supported?

**Comment by edcoreweb** [comment]
See https://laravel-mix.com/docs/4.0/upgrade

**Comment by AlexeyTcapaev** [comment]
@edcoreweb thanks again!
