### ISSUE TITLE
Is it possible to replace babel with swc？

### ISSUE THREAD

**Issue by dsewnr** [JeffreyWay/laravel-mix#2026]
-   Laravel Mix Version: 1.7.2
-   Node Version: 8.11.3
-   NPM Version: 6.7.0
-   OS: Ubuntu 18.04

### Description:
Due to the performance reasons.
https://swc-project.github.io/

**Comment by shrpne** [comment]
I like swc, but I think main goals of laravel-mix is to be easy to use and provide bulletproof output.
For now, babel is the most bulletproof transpiler and most popular, so other developers get used to it.

**Comment by dsewnr** [comment]
@shrpne agree, I think it can be another option, not fully replace. :)

**Comment by HDVinnie** [comment]
Would be nice if a alternative option. Dont like idea of full replace though.
