### ISSUE TITLE
Can't get jQuery plugin to recognise jQuery

### ISSUE THREAD

**Issue by elasticsteve** [JeffreyWay/laravel-mix#203]
With Elixir I used the [jquery-visible plugin](https://github.com/customd/jquery-visible).

One could argue this is not the place to post, but after tearing my hair out all day yesterday, I couldn't make such a simple thing work with Laravel Mix. Elixir = no problem.

Here's my bootstrap.js:

```
window.$ = window.jQuery = require('jquery');

require('./jquery.visible.js');
```

I also tried `window.visible = require('./jquery.visible.js');`

...but no matter what I do, I always get this when loading the page:

![error](https://cloud.githubusercontent.com/assets/10718044/22371664/39ad8e8c-e490-11e6-9c51-5f2832707d4a.jpg)

webpack.mix.js:
`  .js('resources/assets/js/app.js', 'public/js/app.js')`

app.js:
`require('./bootstrap');`

PS: I found [this](http://stackoverflow.com/questions/35358625/jquery-is-not-defined-when-use-es6-import) talking about the issue, but couldn't understand...

**Comment by JeffreyWay** [comment]
I just created a new project, and added your code. It all worked.
https://cl.ly/3i0z1n17212G

https://cl.ly/3r2x3o072i2z

**Comment by elasticsteve** [comment]
Thanks for your effort!

The error happens when you call it. Did you do that too?

Here is the part of my main.js where the error happens:
```
$(document).ready(function () {
    if (!$('#es-nav-group1').visible()) {
        //  console.log("visible");
        $('#es-nav-group1').css("opacity", 1);
    }
});
```

it's in the `if` line (10219:30) where I get the console error that I posted above.

```
jQuery.Deferred exception: $(...).visible is not a function TypeError: $(...).visible is not a function
    at HTMLDocument.<anonymous> (http://elastic.app/js/main.js:10319:30)
    at mightThrow (http://elastic.app/js/main.js:3643:29)
    at process (http://elastic.app/js/main.js:3711:12) undefined
jQuery.Deferred.exceptionHook @ jquery.js?27d9*:3846
process @ jquery.js?27d9*:3642
main.js:16 Uncaught TypeError: $(...).visible is not a function
    at HTMLDocument.<anonymous> (main.js:16)
    at mightThrow (jquery.js?27d9*:3570)
    at process (jquery.js?27d9*:3638)
```

**Comment by JeffreyWay** [comment]
Yes, it works everywhere I tried. 

I think you're working with a lot of legacy code here, and Mix was specifically built to be a wrapper around Webpack, to allow for modules, ES2015, etc. 

So if you can't get it to work, either use `mix.combine()` like I said earlier, or of course there's no reason why you have to leave Laravel Elixir. That will still exist, and is useful as a general purpose task runner.

**Comment by JeffreyWay** [comment]
If you can send me a GitHub repo with the simplest possible reproducible example of this not working, I'm happy to take a look. Otherwise, going to give this a close.

**Comment by elasticsteve** [comment]
@JeffreyWay so you did actually call the visible function and it worked? Just want to make sure before I start entering into the long process of a new minimal project to narrow down what's the issue. Thanks!

And in your option:

```
window.$ = window.jQuery = require('jquery');
require('./jquery.visible.js');
```

is the correct way, right?

not `import` or `window.visible = require('./jquery.visible.js');`

If it works with you, at least it gives me a good starting point.

**Comment by elasticsteve** [comment]
Yes, I was thinking about keeping Elixir, but I wasn't sure for how long that will be a viable option and I might be forced again down the line to switch. If I can, I'd rather tackle the task now, when I'm at the start of what is going to be a monster project.
