### ISSUE TITLE
Hot reloading injects every CSS file in webpack.mix.js into the DOM

### ISSUE THREAD

**Issue by kfirba** [JeffreyWay/laravel-mix#2030]
-   Laravel Mix Version: 4.0.14
-   Node Version (`node -v`): 10.14.2
-   NPM Version (`npm -v`): 6.4.1
-   OS: Centos 7

### Description:
There is a major issue we've experienced once we've upgraded from laravel mix v2 to v4.

In our `webpack.mix.js` file we have several js and sass files that we compile. When I ran `yarn run hot` and  viewed a webpage that includes the **first** js file in `webpack.mix.js` for some odd reason it would inject into the page every other sass file (because I have source maps enabled it adds them as a blob):
![image](https://user-images.githubusercontent.com/8510486/54201736-10154e80-44d7-11e9-995a-32f8253d5784.png)

The `webpack.mix.js` file looks like this:

```js
/*
|--------------------------------------------------------------------------
| User dashboard
|--------------------------------------------------------------------------
*/
mix.js('resources/js/user-dashboard/main.js', 'public/js/user-dashboard.js')
    .extract()
    .sass('resources/sass/app.scss', 'public/css');

/*
|--------------------------------------------------------------------------
| Admin dashboard
|--------------------------------------------------------------------------
*/
mix.js('resources/js/admin-dashboard/main.js', 'public/js/admin-dashboard.js')
    .babel('resources/js/ckeditor-init.js', 'public/js/ckeditor-init.js')
    .sass('resources/sass/admin/admin.scss', 'public/css');

/*
|--------------------------------------------------------------------------
| Market Homepage
|--------------------------------------------------------------------------
*/
mix.sass('resources/sass/market/market.scss', 'public/css')
    .js('resources/js/market/fly/main.js', 'public/js/fly.js')
    .js('resources/js/market/hotels/main.js', 'public/js/hotels.js');

/*
|--------------------------------------------------------------------------
| Market Results
|--------------------------------------------------------------------------
*/
mix.sass('resources/sass/market/results.scss', 'public/css')
    .js('resources/js/market/results.js', 'public/js/results.js');
```

When I view a webpage that includes any other JS file (not the `user-dashboard.js` file) the above code does not get injected and everything looks and behaves just as expected.

The fix I currently found for the issue is to compile a fake javascript file first and then the rest of the files:

```js
// fixes the issue:
mix.js('resources/fake.js', 'public/js');

/*
|--------------------------------------------------------------------------
| User dashboard
|--------------------------------------------------------------------------
*/
mix.js('resources/js/user-dashboard/main.js', 'public/js/user-dashboard.js')
    .extract()
    .sass('resources/sass/app.scss', 'public/css');

/*
|--------------------------------------------------------------------------
| Admin dashboard
|--------------------------------------------------------------------------
*/
mix.js('resources/js/admin-dashboard/main.js', 'public/js/admin-dashboard.js')
    .babel('resources/js/ckeditor-init.js', 'public/js/ckeditor-init.js')
    .sass('resources/sass/admin/admin.scss', 'public/css');

/*
|--------------------------------------------------------------------------
| Market Homepage
|--------------------------------------------------------------------------
*/
mix.sass('resources/sass/market/market.scss', 'public/css')
    .js('resources/js/market/fly/main.js', 'public/js/fly.js')
    .js('resources/js/market/hotels/main.js', 'public/js/hotels.js');

/*
|--------------------------------------------------------------------------
| Market Results
|--------------------------------------------------------------------------
*/
mix.sass('resources/sass/market/results.scss', 'public/css')
    .js('resources/js/market/results.js', 'public/js/results.js');
```

Does anyone have any idea why such a thing happens?

**Comment by ankurk91** [comment]
https://www.npmjs.com/package/css-hot-loader
is a great solution for this issue.

**Comment by kfirba** [comment]
@ankurk91 How can I use it? Also, if this issue is right there in the code base, why not just use `css-hot-loader` by default?

**Comment by ankurk91** [comment]
When I was not able to customise the Mix, I created my own solution that works fine for me.
https://github.com/ankurk91/laravel-bundler

**Comment by sebastiaanluca** [comment]
We're having the same major issue with hot reload and CSS files. We're only compiling 2 CSS files using PostCSS and one JS file, but the second CSS file gets included in every single page when using hot reload. Works fine when using `watch` (no CSS injection) or regular asset building.

**Comment by carestad** [comment]
Affected by this as well. Adding a `mix.js()` statement first that just points to a empty .js file weirdly enough fixes the issue.

**Comment by sebastiaanluca** [comment]
Ping.

**Comment by imuller** [comment]
Same issue here. Fix from @kfirba fixed it for me, thanks!
