### ISSUE TITLE
Extending Mix does not run sequentially.

### ISSUE THREAD

**Issue by StevenSerrien** [JeffreyWay/laravel-mix#2032]
-   Laravel Mix Version: laravel-mix@2.1.14 (`npm list --depth=0`)
-   Node Version (`node -v`): v8.11.2
-   NPM Version (`npm -v`): 5.6.0
-   OS: OSX

### Description:
When following the documentation for extending mix and creating method, I am successful at that. However, when running this as the last chained method on `mix.foo()`, this method gets executed immediately after running `npm run dev`. I have the feeling this should run sequentially like the other built-in functions for `

### Steps To Reproduce:

Follow the first example @ https://laravel-mix.com/docs/2.1/extending-mix
The console.logs are being executed earlier than the js-compiles.

###Reason

I'm trying to add a `mix`extension, that uses the compiled css from on of the tasks, but running it currently, it executes directly and does not wait for the compiled css to be in place.

**Comment by gabolecointere** [comment]
I have a similar issue.

I'm copying and optimizing images at build time and then adding versioning, but I have to run the build two times to have the images versioned. Looks like version() is run before the images are copied into the public folder. Summarizing, I have something like this:

` // images optimization
mix.webpackConfig({
    plugins: [
        new CopyWebpackPlugin([{
            from: 'resources/assets/img',
            to: 'img', // Laravel mix will place this in 'public/img'
        }]),
        new ImageminPlugin({
            test: /\.(jpe?g|png|gif|svg)$/i,
            plugins: [
                imageminMozjpeg({
                    quality: 80,
                })
            ]
        })
    ]
});

mix.version(['public/img'])`

Any workaround around this? Is there a way that I can force it to run sequentially? 

Thanks in advance
