### ISSUE TITLE
code splitting dont transpile es6 module from node_modules

### ISSUE THREAD

**Issue by MichalKrakow** [JeffreyWay/laravel-mix#2033]
-   Laravel Mix Version: 4.0.0
-   OS: Windows

### Description:
When module from node modules uses es6 (swiper.js) after using extract vendor.js contains es6 code.

### Steps To Reproduce:
add (for example) swiper.js to your project
use it somewhere
use code splitting in your webpack.mix.js - .extract(['swiper'])
open in IE11 you will get raw class definition with syntax error

I have little experience with webpack and babel configuration but my first guess is that 'code splitting dont transpile es6 module from node_modules'.

I have to force it for some modules with: 
```
rules: [
        {
            test: /\.jsx?$/,
            include: [
            	path.resolve('node_modules/vue-sparklines'),
            	path.resolve('node_modules/vue-echarts'),
            	path.resolve('node_modules/resize-detector'),
                path.resolve('node_modules/vuetable-2')
            ],
            exclude: /node_modules\/(?!(dom7|swiper)\/).*/,
            use: [
                {
                    loader: 'babel-loader',
                    options: Config.babel()
                }
            ]
        }
 ]
```
This config works without code splitting and opens fine in ie.
If i extract 'swiper' specifically with mix.extract the vendor.js consist of es6 code for this particular modules.

My second guess is that the @babel/polyfill does not load with vendor but i've tried to load it manually as first script with same results.

**Comment by ankurk91** [comment]
Swiper.js package already provides es5 code

https://unpkg.com/swiper.js@1.0.0/dist/

Any *.js file coming from node_modules will be excluded by babel-loader config.

**Comment by MichalKrakow** [comment]
Hi, thanks for taking interest in the issue.
The problem i'm facing is when i tell webpack to compile specific module from node_modules
```
exclude: /node_modules\/(?!(dom7|swiper)\/).*/,
// also the inclue section of original post
```
it works only when module extraction is off.
When use module extraction compilation of node_modules stops working.

**Comment by jmariller** [comment]
Hi @MichalKrakow, not sure if you have found any solution in the meantime?

I am facing exactly the same issue with `three.js` as an other example, which has recently included ES6 syntax in their library, resulting into issues for IE>=9.

**Comment by jmariller** [comment]
@JeffreyWay I know you are very busy, however if you see this could you possibly share your views and possibly re-open this issue? Many thanks!

**Comment by jmariller** [comment]
Thank you so much for your quick answer, @MichalKrakow

This did help, I tried adding the module section that you described into my webpack and now it is working!

For anybody else who would be facing the same problem with `threejs`, here is my adaptation from what Michal provided (thanks again!):
```
mix.webpackConfig({
    module: {
        rules: [{
            test: /\.jsx?$/,
            include: [
                path.resolve('node_modules/three')
            ],
            use: [{
                loader: 'babel-loader',
                options: Config.babel()
            }]
        }]
    }
});
```
