### ISSUE TITLE
Problem with custom webpack configuration.

### ISSUE THREAD

**Issue by bedus-creation** [JeffreyWay/laravel-mix#2039]
Laravel Mix (4.0.15)
OS Ubuntu 18.04

# Steps to Reproduce:
1. Create a New laravel project (Laravel 5.8, as it uses laravel-mix 4)
2. Import a component dynamically.

```
Vue.component('example', () => import('./components/Example.vue'));
``` 

I have been using babel dynamic import to import this.   
```
 "@babel/plugin-syntax-dynamic-import": "^7.2.0",
```
You may need .babelrc in the root.

3. try to put the chunks file into public/js/prod It works file till now.

```
let mix = require('laravel-mix');

mix.webpackConfig({
    resolve: {
        extensions: ['.js', '.vue', '.json'],
        alias: {
            // 'vue$': 'vue/dist/vue.esm.js',
            '@': __dirname + '/resources/assets/js'
        },
    },
    output: {
        chunkFilename: 'js/prod/[name].js',
    },
});


mix.js('resources/assets/js/app.js', 'js')
    .version();

```

4. try to extract the plugins, & It causes problem.

```
mix.js('resources/assets/js/app.js', 'js')
    .mix.extract(['vue','jquery', 'popper.js'])
    .version();
```
5. Now the file app.js and vendor.js goes to js/prod//js/app.js and js/prod//js/vendor.js respectively.
There is no way to put the app.js and vendor.js in /js and chunks in /js/prod. In the previous version which was available.

![Screenshot from 2019-03-17 17-23-35](https://user-images.githubusercontent.com/25701752/54489931-85b75b00-48d9-11e9-9973-a07af366b0bf.png)

**Comment by bedus-creation** [comment]
I think the problem is with mix.extract(); works fine when use

**Comment by bedus-creation** [comment]
Please remove this laravel-mix v4 version and back to laravel v2.

**Comment by kfirba** [comment]
+1. The same issue here.
