### ISSUE TITLE
Bootstrap 4.3.1 validation icons

### ISSUE THREAD

**Issue by Webotvorba** [JeffreyWay/laravel-mix#2041]
I have problem with bootstrap and laravel mix compilation.

This rule

.form-control.is-invalid, .was-validated .form-control:invalid {
  background-position: center right calc(.375em + .1875rem) !important;
}
is being interpreted as

.form-control.is-invalid, .was-validated .form-control:invalid {
  background-position: 100% calc(.375em + .1875rem) !important;
}
and in result the validation icon as at far right. When I change the 100% in inspector to center right it works. Any help how I can fix this?

Mix config:

mix.js('resources/assets/js/'+project+'.js',        'public/js')
        .sass('resources/assets/sass/'+project+'.scss', 'public/css');

**Comment by DesertCat** [comment]
I confirm the exact same problem with Symfony Encore.
In production mode (when minification enabled) css for background positoin is invalid.

**Comment by DesertCat** [comment]
Revealed that it is well-known problem with cssnano minifier used in [Optimize CSS Assets Webpack Plugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin) : 
https://github.com/cssnano/cssnano/issues/712

**Comment by abhishekdev** [comment]
While this is a cssnano parsing issue, I feel this could be prevented in bootstrap code by writing more specific values for the `background-position` and deferring the code shorthand/defaulting to the  minifiers.

As pointed in the https://github.com/cssnano/cssnano/issues/712#issue-411106381, there is a workaround for this:

```diff
---background-position: center right $input-height-inner-quarter;
+++background-position: right $input-height-inner-quarter center;
```

![Screen_Shot_2019-04-23_at_3_16_03_PM](https://user-images.githubusercontent.com/227926/56609873-2e915e00-65dc-11e9-9183-10645280d403.png)

I wonder if this scenario has anything to do with how the [CSS spec details out background-position](https://www.w3.org/TR/css-backgrounds-3/#the-background-position) this (ref: https://www.w3.org/TR/css-backgrounds-3/#the-background-position)

> Note that a pair of keywords can be reordered while a combination of keyword and length or percentage cannot. So center left is valid while 50% left is not.
