### ISSUE TITLE
4.0.15: GitHub tag/release missing?

### ISSUE THREAD

**Issue by lkraav** [JeffreyWay/laravel-mix#2048]
https://github.com/JeffreyWay/laravel-mix/releases shows 4.0.14, but `npm audit` just recommended installing 4.0.15.

**Comment by ankurk91** [comment]
npm does not installs/download from Github.

https://www.npmjs.com/package/laravel-mix/v/4.0.15

**Comment by lkraav** [comment]
I'm aware of the difference.
