### ISSUE TITLE
Subfolders not respected when specifying output path

### ISSUE THREAD

**Issue by sorenchr** [JeffreyWay/laravel-mix#205]
Subfolders used when specifying output paths are ignored, the following:

`mix.js('resources/assets/js/test.js', 'public/js/some/test.js')`

Will produce a **test.js** file directly in the _public/js_ folder, no subfolder. This is because when the `Mix` module creates the Webpack `entry` option it just uses filenames:

```
{
    test: [ '/home/vagrant/projects/testproj/resources/assets/js/test.js' ]
}
```

And the filename and path in the `output` entry in `Mix` is specified as just the public path + the filename.  

```
output() {
    // We'll only apply a chunkhash in production, as it's a costly step.
    let filename = this.versioning ? '[name].[chunkhash].js' : '[name].js';

    return {
        path: this.hmr ? '/' : this.publicPath,
        filename: path.posix.join(this.js[0].output.base, filename).replace(this.publicPath, ''),
        publicPath: this.hmr ? 'http://localhost:8080/' : './'
    };
}
```

To fix this, the entry filenames should be relative paths, like the following:

```
{
    'some/test.js': [ '/home/vagrant/projects/testproj/resources/assets/js/test.js' ]
}
```

**Comment by JeffreyWay** [comment]
You're using an old version of Mix. It works on the current version.

https://cl.ly/0T261n1A1M47
