### ISSUE TITLE
Invalid regular expression in Extract.js:104

### ISSUE THREAD

**Issue by mobyface** [JeffreyWay/laravel-mix#2052]
When using mix.extract in my webpack.mix.js, I got following error.

`/.../.../.../node_modules/webpack-cli/bin/cli.js:231
                                throw err;
                                ^

SyntaxError: Invalid regular expression: /(?<!node_modules.*)[\\/]node_modules[\\/](axios|vue|vuetify)[\\/]/: Invalid group
    at RegExp (native)
    at Extract.createCacheGroup (/home/socylist/app/production/node_modules/laravel-mix/src/components/Extract.js:104:25)`

In my configuration mix.extract is only executed when I run npm run prod. This is my extract command:

`mix.extract(["axios", "vue", "vuetify"]);`

Looks like line 104 in Extract.js is changed since version 4.0.15, so I downgraded to version 4.0.14

**Comment by amoralesdesign** [comment]
same problem here

**Comment by jandante** [comment]
Hi, I also have this issue with v.8 of node.
How do you downgrade extract.js in you Laravel Project? It's not in composer.json.

**Comment by mobyface** [comment]
You can downgrade laravel-mix to 4.0.14 by editing packages.json like line below and run 'npm update'

`"laravel-mix": "4.0.14",`

So you are saying that for you 4.0.15 is working in combination with NODE version 10.x? Which version of NPM do you have?

**Comment by jandante** [comment]
Oh i thought I needed to downgrade the package extract.js and not laravel-mix.

With these versions I had no issue anymore:
node 10.15.3
npm 6.4.1

**Comment by valentinsosnov** [comment]
Still getting "SyntaxError: Invalid regular expression" on v4.0.16
