### ISSUE TITLE
`npm run hot` not working

### ISSUE THREAD

**Issue by footballman17** [JeffreyWay/laravel-mix#2057]
I installed the latest version of Laravel (now 5.8) and enter two commands:

```
npm install
npm run hot
```
and get page-error on `http://localhost:8080` - 

> Cannot GET /.

I get this error in all my laravel-projects, when I use `npm run hot`. Other commands such as `npm run development`, `npm run watch` work as needed.
My OS - Windows 7.

Help;-)

**Comment by michaelroper** [comment]
@footballman17 if you try `http://localhost:8080/mix-manifest.json`, that should work. 
There is no default index page being server from the webpack dev server, which is why you'd get that error.

**Comment by rbrisita** [comment]
Add this to a `webpack.mix.js` file:

```js
let mix = require('laravel-mix');

mix.webpackConfig({
    devServer: {
        proxy: {
            '*': 'http://localhost:8000'
        }
    }
});
```
Run the backend server (`php artisan serve`) and then `npm run hot`. This will proxy all frontend requests to the backend so files can be processed correctly. More information [here](https://webpack.js.org/configuration/dev-server#devserverproxy).

With that said, `npm run hot` should work without developer modification.
