### ISSUE TITLE
terser mangle is breaking js on fresh laravel install

### ISSUE THREAD

**Issue by professor-bulb** [JeffreyWay/laravel-mix#2059]
-   Laravel Mix Version: 4.0.15
-   Node Version (`node -v`): 8.12.0
-   NPM Version (`npm -v`): 6.4.1
-   OS: ubuntu

### Description: 
Laravel 5.8 fresh install, enabling vue example component, and then enabling mangle in mix causing js to break.

### Steps To Reproduce:
install a fresh laravel project
run npm install / yarn
inside  \resources\views\welcome.blade.php
delete the body content and add:
`<div id="app">`
`        <example-component></example-component>`
`    </div>`
`<script src="js/app.js"></script>`

inside webpack.mix.js
add options:
mix.options({
   terser:{
       terserOptions:{
           mangle:{
               //properties:{}
           }
       }
   }
});

now if you run npm run dev and npm run prod both work fine and load the page,
when you uncomment the properties:
mix.options({
   terser:{
       terserOptions:{
           mangle:{
               properties:{}
           }
       }
   }
});

the npm run prod build successful,
the js code breaks:
Uncaught TypeError: Cannot set property 'placeholder' of undefined
    at app.js:1
    at Kn (app.js:1)
    at t (app.js:1)

i have traced this error to loadash code,
but couldn't fix this,
i have tried with debug enabled, but didn't get any help from it.
also tried keep_quoted true, but didn't change anything.

**Comment by professor-bulb** [comment]
this unmangled loadash code  does work when running npm run dev:
arrayEach(['bind', 'bindKey', 'curry', 'curryRight', 'partial', 'partialRight'], function(methodName) {
      lodash[methodName].placeholder = lodash;
    });

but when running npm run prod,
it breaks inside the loop on the bindKey string,
i tried to add it to the reserved array, 
then it breaks on the next string,
i tried to add the entire array to reserved, 
and then the error was too broad to trace.

**Comment by ankurk91** [comment]
Why don't you report this issue here
https://github.com/terser-js/terser

**Comment by professor-bulb** [comment]
because i am not sure from where the problem is.
is there a way to mangle out of the box?
