### ISSUE TITLE
Can't find variable exports

### ISSUE THREAD

**Issue by renedekat** [JeffreyWay/laravel-mix#206]
Hi,

I've upgrade my node packages today and when I run 
```
npm run dev
```
Everything compiles fine. However, I get an error when trying to load the page (see subject)

```
/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(1)))
```

If I disable the following in bootstrap.js (Laravel 5.4) the error is gone, but I don't think that should be the desired solution. 

```
window.$ = window.jQuery = require('jquery');
```

**Comment by JeffreyWay** [comment]
I'd need to see your full `npm run dev` output.

**Comment by renedekat** [comment]
Right, this is solved by upgrading from "webpack": "2.2.0-rc.5" to "webpack": "2.2.0-rc.7"

**Comment by JeffreyWay** [comment]
You don't need the RC anymore. You can get "webpack": "^2.2.0". 

(But Laravel Mix does already include that as a dependency.) Anyways, glad you got it sorted.

**Comment by renedekat** [comment]
@JeffreyWay Just found that out :) Project been in the making for a while and hadn't updated yet.
