### ISSUE TITLE
possible to babel + bundle ?

### ISSUE THREAD

**Issue by dhaval-cygnet** [JeffreyWay/laravel-mix#2065]
-   Laravel Mix Version: ^0.12.1
-   Node Version (`node -v`):8.10.0
-   NPM Version (`npm -v`): 5.6.0
-   OS: Linux

### Description:
I have es6 code where one index.js file and it has all dependency import.
now if I use mix.babel then it transpile but not found any option to bundle.
Is any way something like babel + bundle which transpile all es6 code and if have any dependency import then manage it and create bundle file.
for example if index.js has 'import app from './module/app.js'  then output will have all code transpiled and bundled one file(which has app code).

**Comment by ankurk91** [comment]
Have you heard of `mix.js()` method?

**Comment by dhaval-cygnet** [comment]
Yes it combine all js. But if any js has import dependency then not get manage. I have found workaround to created one webpack file for entry which have dependency and build and later add that in mix.js(). You can close issue.

**Comment by arnoson** [comment]
@dhaval-cygnet how exactly did you manage to work around? I have the exact same problem. I don't want to use `mix.js()` because i don't want any webpack specific code included in my bundles. So I use `mix.babel()` but still want all my imorts bundled together.
