### ISSUE TITLE
Hot Module Replacement Not Working

### ISSUE THREAD

**Issue by mehedimi** [JeffreyWay/laravel-mix#2066]
Hi !
I am facing some problem about laravel mix hot module replacement. Everything is good as it is. But when I update my vue file then error occurred on browser console. This error is not verbose that's why I can't understand, to solve that problem. 

![Screenshot from 2019-04-09 11-45-21](https://user-images.githubusercontent.com/10108409/55869694-d5bbd180-5ba8-11e9-8f6e-68abeca61375.png)

**Comment by ankurk91** [comment]
I don't know why you are saying that error is not verbose enough.
I think have everything to debug, file name and line number.

**Comment by mehedimi** [comment]
Yes I have file name and line number, but this error occurred on webpack compiled file. And It's highly complicated to catch error. I have attach a screenshot, Please see It! 

![Screenshot from 2019-04-11 14-59-34](https://user-images.githubusercontent.com/10108409/55944685-f3ea0600-5c6a-11e9-9b85-9728df75e7f9.png)

**Comment by ankurk91** [comment]
try re-installing laravel-mix
