### ISSUE TITLE
Getting unexpected results from fresh Mix install

### ISSUE THREAD

**Issue by kylebragger** [JeffreyWay/laravel-mix#207]
Hey there. I'm getting some unexpected/odd results when using Mix. 

Relevant details:
- My config: https://gist.github.com/kylebragger/59f59cf2e1edf3d500401dca79d12532
- node v6.3.1
- npm 3.10.3
- Fresh install of Laravel 5.4.5

My asset structure:

```
resources/
  assets/
    sass/
      app.scss
    css/
      normalize.css
```

When I run `npm run dev` as directed, I expect to end up with a versioned all.css file in my public/css directory (which I could access with the mix() helper in my templates), and which would contain normalize.css + sass.all.css, combined.

However, I end up with a public/css/all.css which *only* contains normalize.css, and a versioned copy of sass.all.css in public/resources/assets/css.

Am I missing something obvious in the documentation?

**Comment by JeffreyWay** [comment]
Mix is going to compile all of your assets to the public directory. So that's expected behavior. You can compile your Sass, and then combine them after the fact.

```js
mix.sass('resources/assets/sass/app.scss', 'public/css')
   .combine(['resources/assets/css/normalize.css', 'public/css/app.css'], 'public/css/all.css');
```

**Comment by kylebragger** [comment]
I just used your mix snippet from above and now end up with a versioned app.css file in public/css which only contains the contents of my original app.scss.

Sorry for being daft but is my original flow supported? It's generally how I was doing things with Elixir.

**Comment by JeffreyWay** [comment]
Yeah I think that's going to because the file is versioned. So when you try to combine public/css/app.css, it no longer exists. It's now public/css/app.234213412132.css. 

I'll think about how to fix that.

**Comment by kylebragger** [comment]
Ah, I was assuming the ops were executed in the chaining order. But do you mean that the versioning might happen before then?

**Comment by JeffreyWay** [comment]
When use add mix.version() it automatically sets the output file name to the versioned form of what you provide. It doesn't version after the fact. It's part of the bundle process. 

So you're trying to combine a file that doesn't exist. Webpack doesn't quite work like Gulp in that regard. That's why they're different projects.

**Comment by JeffreyWay** [comment]
What you'll have to do is use a * for the hash portion of the file that you're trying to combine.

```js
mix.sass('resources/assets/sass/app.scss', 'public/css')
   .combine(['resources/assets/css/normalize.css', 'public/css/app.**.css'], 'public/css/all.css')
   .version();
```

Don't think there's any way around that.

**Comment by kylebragger** [comment]
Thanks for the info. I know it's not the same as Gulp, was just trying to wrangle things so as to get a similar/the same end result. It looks like your above snippet ends up working insofar as all.css has all the combined file contents, but app.css is the one that gets versioned. Not sure if that's helpful or not. I'll continue to play around, too. Thanks!
