### ISSUE TITLE
Processing CSS urls from node_modules dependencies. 

### ISSUE THREAD

**Issue by nichalko** [JeffreyWay/laravel-mix#2073]
-   Laravel Mix Version: 4.0.15
-   Node Version (`node -v`): v11.1.0
-   NPM Version (`npm -v`): 6.4.1
-   OS: Win10

### Description:
Importing css from node_modules that contains another import, gives an error:

```
ERROR in ./resources/styles/bundles/base.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/styles/bundles/base.css)
Module not found: Error: Can't resolve '../fonts/fontawesome-webfont.woff?v=4.7.0' in D:\dev\myapp\app\resources\styles\bundles'
 @ ./resources/styles/bundles/base.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/styles/bundles/base.css) 7:235885-235937
 @ ./resources/styles/bundles/base.css
```

webpack.mix.js:
```
const mix = require('laravel-mix');

mix.options({
    postCss: [
        require('postcss-import'),
        require('precss'),
        require('autoprefixer'),
        require('postcss-mixins'),
        require("cssnano")
    ],
});

mix.postCss('resources/styles/bundles/base.css', 'public/css')
```

base.css :
```
/* VENDORS */
@import "normalize.css";
@import "font-awesome";
(...)
```

### Steps To Reproduce:

Install laravel, install normalize, fontawesome, install postcss import, precss, poctcss-mixins, cssnano.

Run 'npm run watch'.

There is a way to deal with it by passing:
```
.options({
        processCssUrls: false,
    });
```
to ```mix.postCss()```

but that means I have to manually copy files over to public dist folder? 

I am guessing, even though I use `postCss` in `mix` it still uses some sass magic to import stuff? 

This guess is based on the fact, that when I use plain gulp + postcss + postcss import plugin, it handles the imports correctly without errors.

**Comment by ptr2null** [comment]
Some SCSS files use the <@import> directive from SASS and references on a <_variables.scss> file. If there are any URL or path strings laravel-mix isn't able to resolve them. Font-Awesome for example makes problems with that.

##Solution##
https://bit.ly/2XteH0K
