### ISSUE TITLE
After updating to v4, NPM run keep stucking at 70%

### ISSUE THREAD

**Issue by ngstwr** [JeffreyWay/laravel-mix#2076]
-   Laravel Mix Version: 4.0.15
-   Node Version (`node -v`): 10.15.2
-   NPM Version (`npm -v`): 6.4.1
-   OS: MacOS Mojave - 10.14.5 Beta

### Description:
Was working fine before, after upgrading to v4 and running 'npm run dev' it keeps stucking at "70% building 4966/4966 modules 0 active". 

Tried everything I found (answer posted on few similar issues), nothing seems to work. Have already read the release notes and using node-sass implementation. 

### Package.json:
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "@babel/plugin-syntax-dynamic-import": "^7.2.0",
        "@babel/preset-stage-2": "^7.0.0",
        "browser-sync": "^2.26.3",
        "browser-sync-webpack-plugin": "^2.2.2",
        "compression-webpack-plugin": "^2.0.0",
        "cross-env": "^5.1",
        "laravel-mix": "^4.0.7",
        "mockjs": "^1.0.1-beta3",
        "node-sass": "^4.11.0",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.15.2",
        "sass-loader": "^7.1.0",
        "vue-template-compiler": "^2.6.10",
        "webpack-bundle-analyzer": "^3.3.2"
    },
    "dependencies": {
        "@fortawesome/fontawesome-free": "^5.8.1",
        "animate.css": "^3.7.0",
        "axios": "^0.18.0",
        "blueimp-md5": "^2.10.0",
        "bootstrap-vue": "^2.0.0-rc.11",
        "camelcase-keys": "^5.2.0",
        "chart.js": "^2.8.0",
        "headroom.js": "^0.9.4",
        "html2canvas": "^1.0.0-alpha.12",
        "jquery-resizable-dom": "^0.32.0",
        "js-cookie": "^2.2.0",
        "lodash": "^4.17.11",
        "marquee3000": "^1.0.9",
        "moment": "^2.24.0",
        "nouislider": "^13.1.4",
        "nprogress": "^0.2.0",
        "register-service-worker": "^1.6.2",
        "screenfull": "^4.2.0",
        "snakecase-keys": "^2.1.0",
        "sweetalert2": "^8.8.7",
        "uuid": "^3.3.2",
        "vue": "^2.6.10",
        "vue-avatar": "^2.1.7",
        "vue-chartjs": "^3.4.2",
        "vue-context-menu": "^2.0.6",
        "vue-flatpickr-component": "^8.1.2",
        "vue-form-wizard": "^0.8.4",
        "vue-fullscreen": "^2.1.5",
        "vue-i18n": "^8.10.0",
        "vue-lazyload": "^1.2.6",
        "vue-moment": "^4.0.0",
        "vue-multiselect": "^2.1.4",
        "vue-notification": "^1.3.16",
        "vue-router": "^3.0.6",
        "vue-simple-calendar": "^4.2.1",
        "vue-toasted": "^1.1.26",
        "vue-trumbowyg": "^3.4.2",
        "vue2-dropzone": "^3.5.9",
        "vue2-transitions": "^0.3.0",
        "vuedraggable": "^2.20.0",
        "vuescroll": "^4.12.1",
        "vuex": "^3.1.0",
        "vuex-persistedstate": "^2.5.4",
        "wnumb": "^1.1.0"
    }
}

### webpack.mix.js:
const mix = require('laravel-mix');
const webpack = require('webpack');

const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const CompressionPlugin = require('compression-webpack-plugin');

mix.copy('resources/public', 'public')
    .js('resources/js/app.js', 'public/js/app.js')
    .sass('resources/sass/style.scss', 'public/css', {
         implementation: require('node-sass')
    })
    .browserSync('http://todo.as')
    .webpackConfig({
        devtool: "cheap-module-source-map",
        plugins: [
            new BundleAnalyzerPlugin(),
            new CompressionPlugin({
                filename: "[path].gz[query]",
                algorithm: "gzip",
                test: /\.js$|\.css$|\.html$|\.svg$/,
                threshold: 10240,
                minRatio: 0.8
            }),
            new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
        ],
        // output: {
        //     chunkFilename: 'public/js/[name].[contenthash].js',
        // },
        resolve: {
            alias: {
                '@resources': path.resolve(__dirname, 'resources'),
                '@sass': path.resolve(__dirname, 'resources', 'sass'),
                '@js': path.resolve(__dirname, 'resources', 'js'),
                '@api': path.resolve(__dirname, 'resources', 'js', 'api'),
                '@components': path.resolve(__dirname, 'resources', 'js', 'components'),
                '@filters': path.resolve(__dirname, 'resources', 'js', 'filters'),
                '@mixins': path.resolve(__dirname, 'resources', 'js', 'mixins'),
                '@plugins': path.resolve(__dirname, 'resources', 'js', 'plugins'),
                '@utils': path.resolve(__dirname, 'resources', 'js', 'utils'),
                '@views': path.resolve(__dirname, 'resources', 'js', 'views'),
                '@var': path.resolve(__dirname, 'resources', 'var')
            }
        }
    });

mix.autoload({
    'jquery': ['window.jQuery', 'jQuery']
});

if (mix.inProduction()) {
    mix.version();
}

### babel.rc:
{
    "presets": [
        "@babel/preset-env"
    ],
    "plugins": [
        "@babel/plugin-syntax-dynamic-import"
    ]
}

Here are the last few lines at the time of build (I kept pressing Enter key on iTerm to get these):

 69% building 4932/4937 modules 5 active ...edLoader/loaders/SquareBounceRotate.vue
 70% finish module graph FlagDependencyExportsPlugin
 70% chunk graph

 76% basic chunk optimization RemoveParentModulesPlugin

 77% advanced chunk optimization SplitChunksPlugin
 70% building 4951/4966 modules 15 active ...dex=0&id=34967e50&scoped=true&lang=css&

 70% building 4958/4966 modules 8 active ...dex=0&id=34967e50&scoped=true&lang=css&
 70% building 4966/4966 modules 0 active

**Comment by Akashaj09** [comment]
Larvel mix is not compatible with Weebpack 4. I also faced the same problem. So restored to previous version

**Comment by ngstwr** [comment]
I thought mix was updated to webpack 4 when it's own v4 was released in December. 

https://github.com/JeffreyWay/laravel-mix/releases?after=v4.0.5

**Comment by ngstwr** [comment]
May be Jeffrey can confirm if this is the same issue he has mentioned on the release notes of v4. 

"If your project heavily uses JavaScript dynamic imports, you may need to hold off until the release of webpack 5 early next year. There are known compile issues related to this that we cannot fix until then. Once webpack 5 is out, Mix will be updated shortly after. If you're unfamiliar with dynamic imports, then this very likely won't affect your project."

**Comment by ngstwr** [comment]
@JeffreyWay Can you please confirm this? If I really have to wait for webpack 5, then I will proceed with laravel-mix pre v4 on my current project.

**Comment by AlexGodbehere** [comment]
Same problem here. @JeffreyWay, are you able to confirm that Laravel Mix `4.0.15` is incompatible with dynamic import?

**Comment by craigpaul** [comment]
@ngstwr @AlexGodbehere It's not necessarily Laravel Mix that's incompatible with dynamic imports, it's webpack 4 itself. This is in the upgrade guide for version 4 of Laravel Mix.

> If your project heavily uses JavaScript dynamic imports, you may need to hold off until the release of webpack 5 early next year. There are known compile issues related to this that we cannot fix until then. Once webpack 5 is out, Mix will be updated shortly after. If you're unfamiliar with dynamic imports, then this very likely won't affect your project.
