### ISSUE TITLE
Dependencies not found - looking in node_modules when it shouldn't

### ISSUE THREAD

**Issue by elasticsteve** [JeffreyWay/laravel-mix#208]
My  `bootstrap.js`:

```
window._ = require('lodash');

window.$ = window.jQuery = require('jquery');
require('./jquery.visible.js');

import Vue from 'vue';
window.Vue = Vue;

$.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
});

window.UIkit = require('../uikit/js/uikit.js');
    require('../uikit/js/components/grid.js');
    require('../uikit/js/components/notify.js');
    require('../uikit/js/components/parallaxSteve.js');
    require('../uikit/js/components/upload.js');
    require('../uikit/js/components/sticky.js');
    require('../uikit/js/components/tooltip.js');
```

on `npm run dev` I get:

```
 ERROR  Failed to compile with 6 errors

These dependencies were not found in node_modules:

* uikit
* uikit
* uikit
* uikit
* uikit
* uikit

Did you forget to run npm install --save for them?
```

Why is it looking in node_module for uikit when I loaded with `window.uikit = require('../uikit/js/uikit.js');`?

Directories:
![pic1](https://cloud.githubusercontent.com/assets/10718044/22390827/4e94453e-e4e5-11e6-939c-8c7f6367a92a.jpg)

This is what the beginning of `grid.js` looks like (it's looking for `window.UIkit`):
```
/*! UIkit 2.27.2 | http://www.getuikit.com | (c) 2014 YOOtheme | MIT License */
(function(addon) {

    var component;

    if (window.UIkit) {
        component = addon(UIkit);
    }
...
```

I'm on Win 10.

**Comment by JeffreyWay** [comment]
Yeah looks like UI Kit is looking for a global object here. I assume that's why it's failing. 

You can review mix.autoload(). Or again, for these legacy projects, it's just as easy to do mix.combine() to concatenation the files and be done with it.

**Comment by elasticsteve** [comment]
But isn't window.UIkit = global?

This is all very confusing!

The only way I managed to make it work is to add uikit to my npm dependencies and have it in my node_modules folder.

```
 "dependencies": {
    "uikit": "^2.0.0"
  }
```

bootstrap.js:
```
window.UIkit = require('uikit');
    require('../uikit/js/components/grid.js');
    require('../uikit/js/components/notify.js');
    require('../uikit/js/components/parallaxSteve.js');
    require('../uikit/js/components/upload.js');
    require('../uikit/js/components/sticky.js');
    require('../uikit/js/components/tooltip.js');
```

BTW, I got the ajax working without TokenMismatch and jQuery.visible in my new test project. I don't know if it had something to do with the Windows issues we had in the other thread a moment ago and the vue-loader etc.
Will port it over to the real project and see if it all works now. Phew! Glad if I can get that part working! Rather use Mix than Elixir if I can.
