### ISSUE TITLE
Env vars assigned through putenv aren't accessible through env.process

### ISSUE THREAD

**Issue by iredmedia** [JeffreyWay/laravel-mix#2084]
If in my broadcast.php file I do the following:

```
if (getenv('PUSHER_URL')) {
    $url = parse_url(getenv('PUSHER_URL'));
    putenv('MIX_PUSHER_KEY='.$url['user']);
    putenv('PUSHER_SECRET='.$url['pass']);
    putenv('PUSHER_APP_ID='.explode('/', $url['path'])[2]);
}
```

Then `MIX_PUSHER_KEY` isn't accessible from env.process. I realize this is likely due to the fact that these vars are only available for the current request, so I'm sort of at a loss here. :shrug:

Is there any way around this?

**Comment by rs-sliske** [comment]
afaik env variables in mix are only read at build time

you might want to look at how laravel passes the xsrf token to axios via meta tag in the base template
