### ISSUE TITLE
Browsersync call being ignored by webpack

### ISSUE THREAD

**Issue by kylemilloy** [JeffreyWay/laravel-mix#2085]
-   Laravel Mix Version: 4.0.15
-   Node Version: 11.6.0
-   NPM Version: 6.9.0
-   OS: macOS 10.14.4

### Description:
I have 

### Steps To Reproduce:
Fresh install. Mix looks to be ignoring browsersync. I'm running `npm run watch` and can confirm the `NODE_ENV` is being set to development. --verbose doesn't output any errors when compiling. Sass, JS, copy all works fine just seems to be an issue with BS. I've tried a restart and this still persists. No issue with other projects...just this one.

```js
// package.json
"devDependencies": {
    "browser-sync": "^2.26.5",
    "browser-sync-webpack-plugin": "^2.2.2", // (I've also tried 2.0.1 specifically)
    "cross-env": "^5.1",
    "laravel-mix": "^4.0.7",
    "laravel-mix-purgecss": "^4.1.0",
    "resolve-url-loader": "^2.3.1",
    "sass": "^1.15.2",
    "sass-loader": "^7.1.0",
    "tailwindcss": "^1.0.0-beta.7",
    "vue": "^2.5.17",
    "vue-template-compiler": "^2.6.10"
}
```

```js
// webpack.mix.js
const mix = require('laravel-mix');
const tailwindcss = require('tailwindcss');
require('laravel-mix-purgecss');

mix.copy('resources/img', 'public/img')
    .copy('resources/fonts', 'public/fonts')
    .js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .options({
        processCssUrls: false,
        postCss: [tailwindcss('tailwind.config.js')]
    })
    .purgeCss()
    .browserSync('levvel.test');

if (mix.inProduction()) {
    mix.version();
} else {
    mix.sourceMaps();
}
```

**Comment by kylemilloy** [comment]
Was missing `resources/img` folder. This failed silently while allowing the js/scss to compile properly.

**Comment by jaesung2061** [comment]
Can we reopen this? This silent error caused me a HUGE headache and I actually just went without BrowserSync for a while.
