### ISSUE TITLE
Compiling files without bundling them together

### ISSUE THREAD

**Issue by Sicklou** [JeffreyWay/laravel-mix#2086]
Hello Guys !

I have a simple question but couldn't find any answer.
I want to compile every file of a folder but not bundling them together.
Let's say I have two files in my folder:

- home.js

- test.js

Then I want mix to compile each one and have one file for each other.

`mix  .js('resources/js/pages/*', 'public/js/pages/[name].js')`

I don't know if I can do it with Mix.

**Comment by rdarcy1** [comment]
I think you can do this with a number of calls to the `js` method, looping through the files in your pages directory:

```js
const directory = 'resources/js/pages';

// Require the filesystem object
const fs = require('fs');

// Get a list of files in the pages directory
const pages = fs.readdirSync(directory);

// Compile each page to a separate file
pages.forEach(page => mix.js(`${directory}/${page}`, `public/js/pages/${page}`));

```
