### ISSUE TITLE
processCssUrls images output to undesirable directory

### ISSUE THREAD

**Issue by bellwood** [JeffreyWay/laravel-mix#2090]
-   Laravel Mix Version: 2.1.14
-   Node Version: 8.16.0
-   NPM Version: 6.4.1
-   OS: CentOS 7

### Description:

Image paths from 'processCssUrls:true' outputs to undesirable directory

### Steps To Reproduce:

In my CSS I have paths, as example: ../resources/assets/img/example.png

After processing, this file will show up in: public/images/example.png

Desired output: public/img/example.png

How do I change the output folder for processed CSS images?

Config:
```
let mix = require('laravel-mix');

mix.copyDirectory('resources/assets/img', 'public/img')
    .js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css', {
    outputStyle: 'compressed'
  })
    .version(['public/img'])
    .minify('public/js/app.js')
    .options({
        processCssUrls: true,
        imgLoaderOptions: {
            enabled: false,
        },
        postCss: [
            require('postcss-discard-comments')({
                removeAll: true
            })
        ]
    });

**Comment by gskgrek** [comment]
Try
```
.options({
   [...]
    fileLoaderDirs: {
        images: 'images',
        fonts: 'fonts'
    }
});
```

**Comment by bellwood** [comment]
@gskgrek this worked perfectly. Thank you very much =)

**Comment by FuriosoJack** [comment]
> Try
> 
> ```
> .options({
>    [...]
>     fileLoaderDirs: {
>         images: 'images',
>         fonts: 'fonts'
>     }
> });
> ```
` .options({  
    fileLoaderDirs: {
        images: 'public/images',
        fonts: 'public/fonts'
    }`
