### ISSUE TITLE
Error: Cannot find module 'sass'

### ISSUE THREAD

**Issue by stoplion** [JeffreyWay/laravel-mix#2103]
Fresh install.
```
let mix = require('laravel-mix');
mix.sass('src/client/styles/index.scss', 'dist/')
   .js('src/client/js/index.js', 'dist/')
   .setPublicPath('dist');
```
getting a `Error: Cannot find module 'sass'`

**Comment by gnatih** [comment]
`npm cache clear --force`
`npm install sass`

**Comment by DebashisMahanty** [comment]
thankyou bro

**Comment by NelJulgan** [comment]
thanks a lot!

**Comment by sanaaleem** [comment]
> `npm cache clear --force` `npm install sass`

Thank you so much!

**Comment by NguyenKeo** [comment]
npm install sass
I ran. Thank you so much!

**Comment by graf-script** [comment]
> `npm cache clear --force`
> `npm install sass`

Люблю

**Comment by graf-script** [comment]
> `npm cache clear --force`
> `npm install sass`

Люблю

**Comment by chenzuo** [comment]
npm cache clear --force
npm install sass

**Comment by AlexPu5hkar** [comment]
Thx so much. I've been trying to run my code for two days.
