### ISSUE TITLE
TypeError: Cannot set property 'esModule' of undefined

### ISSUE THREAD

**Issue by Meklad** [JeffreyWay/laravel-mix#2104]
-   Laravel Mix Version: 4.0.15
-   Node Version: 8.11.4
-   NPM Version: 5.6.0
-   OS: Linux Mint 19.4

### Description:
After running "npm install"  than run "npm run dev" or "npm run watch" this error happen: 

![TypeError: Cannot set property 'esModule' of undefined](https://i.ibb.co/B6cs62m/Screenshot-from-2019-05-15-17-16-34.png)

### Steps To Reproduce:

1- pull the project from gitlab.
2- cd to the project directory.
3- run "composer install" because this is laravel project.
4- run "npm install".
5- run "npm run dev".

**Comment by enghelewa** [comment]
@Meklad Looks like yarn is using a node version different from npm.
Multiple solutions are mentioned [here](https://github.com/yarnpkg/yarn/issues/6617)
