### ISSUE TITLE
current version doesn't work

### ISSUE THREAD

**Issue by vertic4l** [JeffreyWay/laravel-mix#2112]
-   Laravel Mix Version: 4.0.15 (`npm list --depth=0`)
-   Node Version (`node -v`): 11.13.0
-   NPM Version (`npm -v`): 6.7.0
-   OS: OS X

### Description:

Just installed laravel-mix. I just want to get the versioning part work, so:

package.json:
`"postproduction": "webpack -p --mode production --config webpack.mix.js"`

but when running:
`TypeError: mix.version is not a function`

dafuq?

webpack.mix.js:

```
const mix = require('laravel-mix');

mix.version(['public/dist/app.js', 'public/dist/dashboard.js', 'public/dist/vendor.js']);
```

ideas ?

**Comment by Log1x** [comment]
You don't pass `webpack.mix.js` directly to webpack, it's not a webpack config.

```
webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
```
