### ISSUE TITLE
[Proposal] Best code splitting when we use mix.extract(); 

### ISSUE THREAD

**Issue by ecreeth** [JeffreyWay/laravel-mix#2114]
## Actual Code Splitting
When we use `mix.extract ();` it generates three main files:
- Application Code: `app.js`
- Vendor Libraries: `vendor.js`
- Manifest (webpack Runtime): `manifest.js`

The files of `vendor.js` and` manifest.js` are fine that are always loaded, but in the `app.js` there is a large amount of code that we do not use in some pages.

### Best Code Splitting
- Application Code In Separate Files: `hello.js`, `counter.js`, `todos.js`, `header.js`, `link.js`, `card.js`
- Vendor Libraries: `vendor.js`
- Manifest (webpack Runtime): `manifest.js`

#### The javascript code that we will always need throughout our page
``` blade 
<!-- resources/views/layouts/app.blade.php -->

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Laravel</title>

        <link rel="stylesheet" href="{{ mix('css/app.css') }}">
    </head>
    <body>
        <div id="app">
           <div id="header"></div> <!-- JS component -->
           @yield('content')
        </div>

          <script src="/js/manifest.js"></script>
          <script src="/js/vendor.js"></script>
          <script src="/js/header.js"></script>
          @stack('scripts')
    </body>
</html>
````
#### Import the code that needs to be loaded into a specific page
``` blade 
<!-- resources/views/pages/todos.blade.php -->
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    You are logged in!
                      <div id="todos"></div> <!-- JS component -->
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script src="{{ mix('js/todos.js') }}"></script>
@endpush
````

**Comment by QWp6t** [comment]
Seems like dynamic imports would be more appropriate here.

**Comment by ecreeth** [comment]
> Seems like dynamic imports would be more appropriate here.

Of course, but it would be better to divide our code when we use mix.extract();

**Comment by QWp6t** [comment]
Right. Dynamic imports will divide your code for you. You're asking for a feature that basically already exists, is what I'm saying.

**Comment by JeffreyWay** [comment]
Agree with @QWp6t. You can use dynamic imports once Mix 5 is out (after webpack 5 is released).
