### ISSUE TITLE
How to use Vue CSS Modules with Laravel-mix?

### ISSUE THREAD

**Issue by supremeo** [JeffreyWay/laravel-mix#2115]
-   **Laravel Mix Version: 4.0.15** (`npm list --depth=0`)
```
├── axios@0.18.0
├── bootstrap@4.3.1
├── cross-env@5.2.0
├── jquery@3.4.1
├── laravel-mix@4.0.15
├── lodash@4.17.11
├── popper.js@1.15.0
├── resolve-url-loader@2.3.2
├── sass@1.20.1
├── sass-loader@7.1.0
├── vue@2.6.10
└── vue-template-compiler@2.6.10
```
-   Node Version (`node -v`): `v10.9.0`
-   NPM Version (`npm -v`): `6.9.0`
-   OS: **macOS Mojave** 

### Description:

Unable to use Vue CSS Modules. Please see: https://vue-loader.vuejs.org/guide/css-modules.html

_Example_
```vue
<template>
      <ul>
          <li v-for="item in data" :key="item">{{ item }}</li>
      </ul>
</template>

<script>
export default {
  props: {
    data: {
      type: Array,
      required: true
    }
  },
  mounted() {
    console.log(this.$style);  // actual: {}
                                               // expected: { red: "red_1VyoJ-uZ" }
  }
};
</script>

<style module>
.red {
    color: red;
}
</style>
```

#### Attempting to extend webpackConfig with Vue documentation suggested config throws an error (see below):
```
mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.css$/,
                use: [
                    "vue-style-loader",
                    {
                        loader: "css-loader",
                        options: {
                            // enable CSS Modules
                            modules: true,
                            // customize generated class names
                            localIdentName: "[local]_[hash:base64:8]"
                        }
                    }
                ]
            }
        ]
    }
})
```

The error: 
```
Error: Rule can only have one result source (provided use and loaders) in {
  "test": {},
  "loaders": [
    "style-loader",
    {
      "loader": "css-loader",
      "options": {
   ...
```

**Comment by supremeo** [comment]
By the way, I can get this to work by modifying `/laravel-mix/src/components/Css.js` as follows:

```js
let AutomaticComponent = require('./AutomaticComponent');

class Css extends AutomaticComponent {
    /**
     * webpack rules to be appended to the master config.
     */
    webpackRules() {
        return [
            {
                test: /\.css$/,
                loaders: [
                    'style-loader',
                    { loader: 'css-loader', options: { modules: true, importLoaders: 1 } }, // modules: true 
                    {
                        loader: 'postcss-loader',
                        options: this.postCssOptions()
                    }
                ]
            },
```

@JeffreyWay is it possible to override this loader's options without updating the library?

**Comment by supremeo** [comment]
I solved this. @JeffreyWay  please disregard. If anyone needs it: 

```js
mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.css$/,
                loaders: [
                    "style-loader",
                    {
                        loader: "css-loader",
                        options: { modules: true, importLoaders: 1 }
                    }
                ]
            }
        ]
    }
})
```

**Comment by oruj91** [comment]
> I solved this. @JeffreyWay please disregard. If anyone needs it:
> 
> ```js
> mix.webpackConfig({
>     module: {
>         rules: [
>             {
>                 test: /\.css$/,
>                 loaders: [
>                     "style-loader",
>                     {
>                         loader: "css-loader",
>                         options: { modules: true, importLoaders: 1 }
>                     }
>                 ]
>             }
>         ]
>     }
> })
> ```

sorry but with this config another all rest css except module.css styles doesn't work

**Comment by BoldAnchor** [comment]
This is still an issue.

> > I solved this. @JeffreyWay please disregard. If anyone needs it:
> > ```js
> > mix.webpackConfig({
> >     module: {
> >         rules: [
> >             {
> >                 test: /\.css$/,
> >                 loaders: [
> >                     "style-loader",
> >                     {
> >                         loader: "css-loader",
> >                         options: { modules: true, importLoaders: 1 }
> >                     }
> >                 ]
> >             }
> >         ]
> >     }
> > })
> > ```
> 
> sorry but with this config another all rest css except module.css styles doesn't work

The solution here does work if it is added to the 'webpack.mix.js', but this then overrides 'webpack.config.js'.

I tried the following: 

>  ```js
> module.exports.module = {
>     rules: [
>         {
>           test: /\.css$/,
>                 loaders: [
>                     "style-loader",
>                     {
>                         loader: "css-loader",
>                         options: { modules: true, importLoaders: 1 }
>                     }
>                 ]
>     ]
>  })
>```
> 

Within 'webpack.config.js' but get now result when using '<style module>'
