### ISSUE TITLE
After Updating laravel-mix to v4

### ISSUE THREAD

**Issue by Nitish27** [JeffreyWay/laravel-mix#2118]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`)
-   Node Version (`node -v`): v11.7.0
-   NPM Version (`npm -v`): 6.8.0
-   OS:

### Description:
After Updating laravel-mix to v4 got this error:
-> Module parse failed: Unexpected token
-> You may need an appropriate loader to handle this file type:
### Steps To Reproduce:
update laravel-mix to v4 and run npm run production.
<img width="748" alt="Screenshot 2019-06-05 at 6 06 57 PM" src="https://user-images.githubusercontent.com/5227839/58956753-c62dc300-87bc-11e9-941d-5c648d0d9ae7.png">

**Comment by JeffreyWay** [comment]
Please provide more information so we can help.

**Comment by Nitish27** [comment]
i am using laravel: 5.5 and update my laravel-mix to v4. after update npm run production and develop stop compiling vue component and sass

**Comment by AndrewSavetchuk** [comment]
+1. I have the same problem
