### ISSUE TITLE
Image in CSS with url function generate error dependency was not found in node_modules

### ISSUE THREAD

**Issue by acacha** [JeffreyWay/laravel-mix#212]
Using Laravel Elixir with fresh laravel 5.4 installation in Ubuntu Linux.

It seems there is a problem when using less and url function in css to use and image:

Example css:

```
.layout-boxed {
  background: url('../img/boxed-bg.jpg') repeat fixed;
}
```

Error:

```
$ npm run dev
 ERROR  Failed to compile with 1 errors

This dependency was not found in node_modules:

* ../img/boxed-bg.jpg
```

Note: no problem occurs if image path is no relative (f.ex. /img/boxed-bg.jpg)

Repository example with error:

https://github.com/acacha/elixirProblem

**Comment by acacha** [comment]
Sorry I'have seen now this could be a duplicated bug. See: https://github.com/JeffreyWay/laravel-mix/issues/187

**Comment by ifaouibadi** [comment]
+1

**Comment by JeffreyWay** [comment]
Thanks. Closing this, in favor of #187.
