### ISSUE TITLE
relative urls not resolving properly since 4.0.16

### ISSUE THREAD

**Issue by ammonkc** [JeffreyWay/laravel-mix#2122]
-   Laravel Mix Version: 4.0.16
-   Node Version: v12.4.0
-   NPM Version: 6.9.0
-   Yarn Version: 1.16.0
-   OS: CentOS 7

### Description:
After updating to laravel-mix 4.0.16, relative urls in scss are not resolving. I know that version 4.0.16 bumped resolve-url-loader dependency to v3.1.0. Was there a breaking change that I missed? Manually downgrading resolve-url-loader to v2.3.1 resolves the issue. Do I need to update the webpack config to support resolve-url-loader's postcss engine?

```
ERROR in ./resources/sass/admin/admin.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../node_modules/craftable/scss/img/correct.png' in '/Users/ammonkc/Develop/code/ptpkg/resources/sass/admin'
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/webpack/lib/Compilation.js:821:10
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/webpack/lib/NormalModuleFactory.js:397:22
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/neo-async/async.js:2825:7
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/neo-async/async.js:6886:13
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/enhanced-resolve/lib/Resolver.js:184:12
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/ammonkc/Develop/code/ptpkg/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/ammonkc/Develop/code/ptpkg/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/ammonkc/Develop/code/ptpkg/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/ammonkc/Develop/code/ptpkg/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:402:1)
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/ammonkc/Develop/code/ptpkg/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/ammonkc/Develop/code/ptpkg/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/ammonkc/Develop/code/ptpkg/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:22:13
    at /Users/ammonkc/Develop/code/ptpkg/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
 @ ./resources/sass/admin/admin.scss
```

### Steps To Reproduce:

1. Update laravel-mix to v4.0.16
2. `npm run dev`

**Comment by aromka** [comment]
Also getting this error when running `npm run dev`
```
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Node Sass version 3.13.1 is incompatible with ^4.0.0.
```
Downgrading back to 4.0.15 fixes the error

**Comment by marcelaerts** [comment]
Got the same.

**Comment by JeffreyWay** [comment]
@ammonkc Hmm - I'm trying to figure out how downgrading `resolve-url-loader` fixed your problem. We haven't yet tagged a version of Mix that uses v3.1.0 of that package. It's only on the master branch.

**Comment by djpolmd** [comment]
I have the same Issue on resolve-url-loader : 3.1.0
98% after emitting SizeLimitsPlugin ERROR  Failed to compile with 7 errors                                                                                                                                                                                                              9:14:05 PM

These relative modules were not found:

* ../../../node_modules/craftable/scss/img/correct.png in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss
* ../../../node_modules/craftable/scss/img/envelope.png in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss
* ../../../node_modules/craftable/scss/img/error.png in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss
* ../../../node_modules/craftable/scss/img/lock.png in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss
* ../../../node_modules/img/correct.png in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss
* ../../../node_modules/img/error-triangle.png in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss
* ../../../node_modules/img/error.png in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss

**Comment by djpolmd** [comment]
Also 3.1.1 is broken,  I retrieve to   "resolve-url-loader": "^2.3.2" in my pakege.json , good work ;-(
