### ISSUE TITLE
extract-text-webpack-plugin deprecation

### ISSUE THREAD

**Issue by JohnMica** [JeffreyWay/laravel-mix#2126]
-   Laravel Mix Version:  "4.0.16"

### Description:

not sure if you are actually using this plugin for css or not but ```extract-text-webpack-plugin``` has been deprecated

https://github.com/webpack-contrib/extract-text-webpack-plugin

The recommended new plugin is https://github.com/webpack-contrib/mini-css-extract-plugin

### Steps To Reproduce:
just follow the link above and it seems that the plugin has been deprecated since the beta release

**Comment by JeffreyWay** [comment]
Already known. We have to continue using extract-text-webpack-plugin until webpack 5 is for various compatibility reasons.
