### ISSUE TITLE
Multi-File Components are Broken

### ISSUE THREAD

**Issue by mgrinspan** [JeffreyWay/laravel-mix#2129]
Inspired by #1893

-   Laravel Mix Version: 4.0.16
-   Node Version: 11.15.0
-   Yarn Version: 1.16.0
-   OS: Ubuntu 18.04.2

### Description:
Running `yarn run production` results in hundreds of the following (1 per file in each component I assume):

```
text "module.exports = "..." outside root element will be ignored.
```

The `...` in the error is the contents of the file being required.

### Steps To Reproduce:
1) Create a new Laravel project with `laravel new`
2) Run `yarn install`
3) Split `ExampleComponent.vue` into separate .vue, .js, and .html files
4) Run `yarn run production`

### Known Workarounds
1) Rename all `.html` files to `.htm` https://github.com/JeffreyWay/laravel-mix/issues/1893#issuecomment-457877758

OR

2) Change your `vue-loader` constraint in your package.json to `<15.0.0`

OR

3) Remove `rules.push({ test: /\.html$/, loaders: ['html-loader'] });` from `src/builder/webpack-rules.js`. This obviously will be overwritten after a reinstall/upgrade of the package. https://github.com/JeffreyWay/laravel-mix/issues/1893#issuecomment-450224631

OR

4) (EDIT 7/15/2019) A new method `mix.override(...)` was added that can be used to remove this rule. It's not a flawless solution but it should work as long as the offending rule is not changed. If it is changed, you should be able to update workaround code below.

```es6
mix.override(config => {
	const index = config.module.rules.findIndex(rule => rule.test.toString() === /\.html$/.toString());

	if(index === -1) {
		console.warn('Index for erroneous rule could not be found.');
	} else {
		config.module.rules.splice(index, 1);
	}
});
```

**Comment by dhrumil4u360** [comment]
None of work around works for me... Ended up rolling back laravel-mix to v3 finally!

npm remove laravel-mix
npm install laravel-mix@3.0.0

**Comment by robbyrice** [comment]
My understanding is that @JeffreyWay is waiting for webpack 5 to do another major release. However, the latest release is v4.1.4 which was done a little over a week ago (you can take a look here https://www.npmjs.com/package/laravel-mix). The GitHub releases and the NPM releases are not necessarily the same.
