### ISSUE TITLE
Cache Busting on Webpack Chunks

### ISSUE THREAD

**Issue by vpillinger** [JeffreyWay/laravel-mix#2131]
-   Laravel Mix Version: 4.0.16 (`npm list --depth=0`)
-   Node Version (`node -v`): v10.15.3
-   NPM Version (`npm -v`): 6.9.0
-   OS: Windows 10 WSL

### Description:
There does not seem to be a good cache-busting mechanism for webpack chunks that plays nicely with Git.
### Steps To Reproduce:

1) Create a standard laravel/mix project the with the mix.version() option.
2) Create a dynamic import: 
import(`./dashboard.js` /* webpackChunkName: "js/dashboard" */);
just put `console.log('version1')` in the imported file.
3) npm run dev -- This creates the following
js/app.js
js/dashboard.js
4) Go to site, observe `version1` in the console
5) Change the chunk to `console.log('version2')`
6) Go to site, observe `version1` in the console

The issue:
The mix-manifest file will get versioning, but the webpack chunk mechanism ignores it:
eg
```
{
    "/js/app.js": "/js/app.js?id=68f34ebc16f9097ba774",
    "/dashboard.js": "/dashboard.js?id=77a5c8ae270db4d8cf2d",
}
```

Workaround:

Add [hash] to the chunkName, but this causes files to be added/deleted in Git constantly, which is not ideal.

Ideal Solution:
There is a way to make webpack chunks use query-string cache busting like Laravel Mix currently does.

**Comment by vpillinger** [comment]
I found out how to do this, but I will leave the solution here for the next person to try to solve this.

First add this to your webpack config:

```
mix.webpackConfig({
    output: {
        chunkFilename: '[name].js?id=[chunkhash]',
    }
});
```

Then, when you specify the chunk name using this: `/* webpackChunkName: "js/dashboard" */`
You will get this as a result: `js/dashboard.js?id=0791710073c12eff5a3d` in the webpack output dialog.

The file will be saved as `js/dashboard.js` but referenced in the browser as ` js/dashboard.js?id=0791710073c12eff5a3d`.

**Comment by gtempesta-pixartprinting** [comment]
Will the id be identical to the one generated by the `mix.version()` function (the one you see in mix-manifest)?

**Comment by gtempesta** [comment]
Will the id be identical to the one you see in mix-manifest?

**Comment by gtempesta** [comment]
I have checked and the ids are different, but even with different ids we verified that cache busting is working with this approach.

**Comment by kirkbushell** [comment]
Have you tested on mobile? I had to move away from ids/cache busted laravel mix feature as often on mobile it would not actually fetch the new version.

**Comment by gtempesta** [comment]
Yes it worked also on mobile. Now we have completely removed Laravel Mix from the project but at the time there were no issue on mobile.

**Comment by kirkbushell** [comment]
Hmmm, I've tested this out locally and find that once production files are built, dev no longer works. Did you have this also?

**Comment by kirkbushell** [comment]
Or maybe a better question is, how are you separating out production/local builds?

**Comment by gtempesta** [comment]
No. But we had very customized settings: three settings for development (css, js and js for legacy browsers) and three settings for production. Now we have a very different setup so I can't help much.

**Comment by kirkbushell** [comment]
No worries, thanks @gtempesta !

**Comment by emyasnikov** [comment]
In my case the `[chunkhash]` value also differs from the one in `mix-manifest.json` file, but it seems the correct id is only needed to generate link using `mix()` function in blade templates.

**Comment by philbates35** [comment]
I faced the same problem today after a deploy to production. Thought the solution above works, what I didn't like is that that is overriding the core Mix `chunkFilename()` [function](https://github.com/laravel-mix/laravel-mix/blob/0c2b20dfb4436b44acdc6cbcf83fbd6c1a4063a1/src/builder/WebpackConfig.js). So I took similar but slightly different approach to make sure that the core Mix behaviour was kept:

```js
mix.override(webpackConfig => {
    const chunkFileName = webpackConfig.output.chunkFilename;
    
    webpackConfig.output.chunkFilename = (pathData, assetInfo) => {
        return `${chunkFileName(pathData, assetInfo)}?id=[chunkhash]`;
    };
}
```
