### ISSUE TITLE
Effective Code splitting for libraries?

### ISSUE THREAD

**Issue by schmidtflo** [JeffreyWay/laravel-mix#2141]
### Question:

With Laravel Mix, is it possible to code-split not only the external libraries into an `vendor.js` file with the `.extract()`-method, but also splitting single libs and load them only if necessary?

Example: We have a huge Vue application (online shop), and on one page new users can register an account. There we're using Algolias places.js. This is a huge lib - around 40kb gzipped. We want to load it only when needed on the register page, not on all pages in the vendor.js-file.

From the webpack side, this seems to be possible: https://webpack.js.org/guides/code-splitting/#dynamic-imports

It would be very good to have the same option in Laravel Mix.

**Comment by wishinghand** [comment]
You can definitely route split.

In your Vue Router file, import like this:
`const AlgoliaComponent = () => import(/* webpackChunkName: "AlgoliaComponent" */ 'components/AlgoliaComponent')`

Make sure you have a `.babelrc` file with 
```
{
	"plugins": ["@babel/plugin-syntax-dynamic-import"]
}
```
in it, and install that in your `package.json`. 

You'll also need to be on laravel-mix v4.

**Comment by schmidtflo** [comment]
Thanks for the answer, but we're not using Vue Router, we have a setup with inline-templates, which are filled by Blade, in combination with regular Vue Components.

**Comment by wishinghand** [comment]
Good info to know. You may want to update your original post.

Since it seems like you're mostly doing server side routing, I don't think this is actually an issue, right? You could have an Algolia component that only gets imported in Vue on the Blade template file that matches whichever route you need it for.
