### ISSUE TITLE
Important issue with Babel Parser.

### ISSUE THREAD

**Issue by nickolasnikolic** [JeffreyWay/laravel-mix#2146]
-   Laravel Mix Version: 4.0.16 (`npm list --depth=0`)
-   Node Version (`node -v`):
nn@nick:/media/nn/Data/dev/web/word.dance$ node -v
v12.4.0

-   NPM Version (`npm -v`):
nn@nick:/media/nn/Data/dev/web/word.dance$ npm -v
6.9.0

-   OS:
Ubuntu 18.0.4

### Description:

nn@nick:/media/nn/Data/dev/web/word.dance$ npm install
npm WARN deprecated mixin-deep@1.3.1: Critical bug fixed in v2.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@2.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! path ../@babel/parser/bin/babel-parser.js
npm ERR! code ENOSYS
npm ERR! errno -38
npm ERR! syscall symlink
npm ERR! ENOSYS: function not implemented, symlink '../@babel/parser/bin/babel-parser.js' -> '/media/nn/Data/dev/web/word.dance/node_modules/.bin/parser'

### Steps To Reproduce:

npm install

with the following package json:

{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.19",
        "bootstrap": "^4.1.0",
        "cross-env": "^5.1",
        "laravel-mix": "^4.0.16",
        "lodash": "^4.17.5",
        "popper.js": "^1.12",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.15.2",
        "sass-loader": "^7.1.0",
        "vue": "^2.5.17",
        "vue-template-compiler": "^2.6.10"
    }
}

**Comment by manishfor030** [comment]
Similar setup with Node version - 10.16.0 (Stable LTS for Ubuntu 18.04) also gives similar error.
