### ISSUE TITLE
Can't use window global variable after migration from 2.0 to 4.*

### ISSUE THREAD

**Issue by Sogl** [JeffreyWay/laravel-mix#2149]
-   Laravel Mix Version: 4.0.15 (`npm list --depth=0`)
-   Node Version (`node -v`): 12.4.0
-   NPM Version (`npm -v`):6.9.0
-   OS: Docker Ubuntu 16

### Description:

I have three files.

1. Main `app.js`:
```
require('./bootstrap');
require('./custom');
```
2. `bootstrap.js` with all my libs:
```js
try {
    window.$ = window.jQuery = require('jquery');

    require('bootstrap');
    //lazyframe
    window.lazyframe = require('lazyframe');

} catch (e) {}

```

3. And `custom.js`:
```js
//all loaded
$(document).ready(function() {
   
    //YouTube lazy load
    let elements = $('.lazyframe');
    lazyframe(elements, {
        apikey: 'myyoutubeapi',
    });
});
```

It worked with Laravel-mix 2.0, but after migration to 4.0.15 I see this error:

![image](https://user-images.githubusercontent.com/7556290/60285826-0f35ea80-9917-11e9-9205-5a9e1c0a40bc.png)

I didn't change anything in my code. I also tried to add `.default` without success:
```js
window.lazyframe = require('lazyframe').default;
```

How to fix?

### Steps To Reproduce:

Try to install https://github.com/vb/lazyframe like in my example.

**Comment by MaximVanhove** [comment]
Can you try to remove the try catch and see if any error pops up there?

**Comment by AdrienPoupa** [comment]
Have you tried https://laravel-mix.com/docs/4.1/autoloading ?
