### ISSUE TITLE
not clean old versioned file if using lazy load

### ISSUE THREAD

**Issue by shwhl** [JeffreyWay/laravel-mix#215]
if I use lazy load in Vue like
```
'component': () => System.import('./component.vue')
```
webpack will generate `app.xxxxxx.js` and `0.yyyyyy.js` (chunk file)
when webpack build next time, it will remove `app.xxxxxx.js`, generate new `app.zzzzzz.js` and `0.aaaaaa.js`, but not removing old `0.yyyyyy.js` file.
since laravel-mix can remove `app.xxxxxx.js` file, I'd like to know if it's possible to remove old chunked js file as well?

**Comment by SebastianS90** [comment]
You could add something like this to your `webpack.mix.js` file:

```javascript
// Clean up the public folder
['css', 'fonts', 'img', 'js'].forEach(p => {
    let path = './public/' + p;
    if (fs.existsSync(path)) {
        fs.readdirSync(path).forEach(file => {
            fs.unlinkSync(path + '/' + file);
        });
    }
});
```

This iterates over all files in `public/css`, `public/fonts`, `public/img`, `public/js` and deletes them before the build starts.

**Comment by shwhl** [comment]
@SebastianS90 this is a good solution, and I can also run `rm` before building, but I think putting all those files into versioning file list inside versioning class of the code is a better practice, so they can be deleted when building again.

**Comment by JeffreyWay** [comment]
Fixed in 1.0.

**Comment by Lorempn2** [comment]
Hi, I am experiencing the same issue and on the latest version of Mix. My old chunk files are not removed. This is in my mix config:

``
    .webpackConfig({
        output: {
            publicPath: "/",
            chunkFilename: "js/[name]-[hash].js"
        }
    })
``

Thanks.

**Comment by DannyFeliz** [comment]
Still having this issue
