### ISSUE TITLE
Laravel Mix - Phpstorm

### ISSUE THREAD

**Issue by gmartha07** [JeffreyWay/laravel-mix#2151]
Hello
I'm using phpstorm with the Laravel Plugin enabled and also with the Barry (laravel-ide-helper) package.
My webpack.mix.js file is showing this message (image attached).
Is there any way to fix this?

I'm using Laravel Mix version 4.0.7

Thank you

![laravelmix](https://user-images.githubusercontent.com/34976736/60621659-9ae6c580-9db4-11e9-8ded-b88884fbbd9a.jpg)

**Comment by JeffreyWay** [comment]
Apologies, but this isn't an issue with the Mix codebase. Better asked in a PHPStorm forum.
