### ISSUE TITLE
Webpack not working if its Monday

### ISSUE THREAD

**Issue by bernisnukic** [JeffreyWay/laravel-mix#2153]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`)
4.0.16
-   Node Version (`node -v`):
v10.9.0
-   NPM Version (`npm -v`):
6.4.1
-   OS:
Windows 10

### Description:

When running "npm run watch" it fails with an error:

TypeError: process.getuid is not a function

This error only happens if the day is monday and the issue has been fixed in latest version of webpack: https://github.com/webpack/webpack-cli/issues/962

### Steps To Reproduce:

1. npm run watch

**Comment by aezur** [comment]
@bernisnukic  Yup. This is causing issues for a few of us at my workplace.
Workaround: Delete your `node_modules` folder and then run `npm install`.

**Comment by egXcoder** [comment]
Yeah, its kind of annoying error. It happened with me on different occasions without any reason. My fix is to remove webpack-cli folder from node-modules. Then run npm install
