### ISSUE TITLE
Mix combine and scripts methods silently skip missing files with no errors

### ISSUE THREAD

**Issue by renegadedata** [JeffreyWay/laravel-mix#2166]
This issue has been reported multiple times and marked stale and closed each time without a resolution:

https://github.com/JeffreyWay/laravel-mix/issues/627
https://github.com/JeffreyWay/laravel-mix/issues/1937
https://github.com/JeffreyWay/laravel-mix/issues/2097

It still exists with a fresh Node / NPM install and these versions:

Laravel Mix Version 4.1.2
Node Version 10.16.0
NPM Version 6.7.0

The steps to reproduce the error are listed in the above issue links. Please get a fix for this!

Thank you,

Ben

**Comment by sunscreem** [comment]
Still an issue for me too with 4.1.2 also.

**Comment by Warafux** [comment]
We really need this.
