### ISSUE TITLE
Synchronize GitHub and NPM

### ISSUE THREAD

**Issue by SuddenlyRust** [JeffreyWay/laravel-mix#2168]
On NPM v4.1.2 has already been released but on GitHub 4.0.14 is still the latest version. Could you please synchronize that? Thank you Jeffrey :^)

![image](https://user-images.githubusercontent.com/14092921/61698521-86ee0e00-ad39-11e9-8501-f4b15c754142.png)

**Comment by ankurk91** [comment]
Why would someone install this package from GitHub?

**Comment by SuddenlyRust** [comment]
There is no need to install it from GitHub @ankurk91. I just have a habit when I see a new version of a package that I first look at "releases" in GitHub. Usually a list of all relevant changes are listed there.

I just close this issue if there is no need for this.

**Comment by ankurk91** [comment]
Agree, people those who have watched the repo for new versions should get a notification.

I usually do - `yarn outdated` weekly.
