### ISSUE TITLE
Unable to install laravel-mix on clean Homestead

### ISSUE THREAD

**Issue by tuktukvlad** [JeffreyWay/laravel-mix#2169]
-   Laravel Mix Version: 4.0.7 and other (`npm list --depth=0`)
-   Node Version (`node -v`): 12.0.5
-   NPM Version (`npm -v`): 6.9.0
-   OS: Ubuntu 18.04

### Description:

Unable to install laravel-mix on clean Homestead.

npm ERR! path /vagrant/www/node_modules/babel-code-frame/node_modules/ansi-regex/package.json.3837021191
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/vagrant/www/node_modules/babel-code-frame/node_modules/ansi-regex/package.json.3837021191'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

Have tride:
rm -rf node_modules
rm package-lock.json yarn.lock
npm cache clear --force
npm install

The result is the same

### Steps To Reproduce:

npm install

**Comment by samuelmaurice** [comment]
I encountered the same problem. I don't know what the underlying problem is but you can fix this by using Yarn instead of NPM for now. It's seems it is an issue related to VirtualBox.

So, simply run `rm -rf node_modules && yarn install` and you're good to go!
