### ISSUE TITLE
Skip compile at start-up

### ISSUE THREAD

**Issue by mintymatt** [JeffreyWay/laravel-mix#2170]
### Skipping the compile/build on start-up

When running `yarn watch` it would be nice if laravel-mix didn't re-compile and emit the output. Is there a hidden way this can be done for custom projects like my own?

Thank-you!

-   Laravel Mix Version: 4.0.14
-   Node Version: v10.14.1
-   NPM Version: 6.1.0
-   Yarn Version: 1.15.2
-   OS: Windows 10

### Description:
Unable to skip the build on start-up.

### Steps To Reproduce:

Running laravel-mix with any of the following scripts in `package.json`:

```
"scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
```

**Comment by ankurk91** [comment]
This is a webpack feature, please report there.
https://github.com/webpack/webpack
