### ISSUE TITLE
Laravel Mix not serving transpiled ES5 code to IE11

### ISSUE THREAD

**Issue by DLO33** [JeffreyWay/laravel-mix#2174]
-   Laravel Mix Version: 4.0.7
-   Node Version: 8.10.0
-   NPM Version:5.6.0
-   OS: Windows 10 (xampp)

### Steps To Reproduce:

In IE11 I'm receiving a SCRIPT1003: Expected ':' error due to ES6 syntax
![image](https://user-images.githubusercontent.com/35256407/61987546-d8104180-b05a-11e9-9727-4a5dff13c340.png)

I have two JS files
- public/js/app.js
- public/js/app.es5.js [transpiled ES6 to ES5]

I'm using babel for transpiling, which all looks correct but when I look at the error, IE is still serving the ES6 code base and not ES5.

I'm relatively new to webpack so I could be missing config or something else perhaps?

Error Code from IE11 console
![image](https://user-images.githubusercontent.com/35256407/61987715-178b5d80-b05c-11e9-9035-e3e2740a8f58.png)

app.js
![image](https://user-images.githubusercontent.com/35256407/61987767-6c2ed880-b05c-11e9-9b87-a2a0292c1974.png)

app.es5.js
![image](https://user-images.githubusercontent.com/35256407/61987748-56211800-b05c-11e9-9e4e-79a7482433b8.png)

webpack.mix.js
```
mix.js("resources/js/app.js", "public/js")
    .babel(['public/js/app.js'], 'public/js/app.es5.js')
    .sass("resources/sass/app.scss", "public/css")
    .polyfill({
        enabled: true,
        useBuiltIns: "usage",
        targets: { firefox: "50", ie: 11 }
    })
    .version();
```

.babelrc
```
{
  "presets": [
    [ "@babel/preset-env", {
      "useBuiltIns": "entry",
      "targets": {
                    "ie": "11"
                }
    }]
  ]
}
```

**Comment by zhernosekim** [comment]
Can you do this transpiling without laravel-mix? I think, it's not its fault.

**Comment by jeankvd** [comment]
I am getting the same error when just having a .babelrc with

```{
  "plugins": ["@babel/plugin-transform-shorthand-properties"]
}```

**Comment by shangendakunda** [comment]
@DLO33, did you ever get a working solution..? Also Finding ES6 code after transpiling which is causing IE11 issues..

**Comment by serak** [comment]
this issue also happened to me after i upgraded "laravel-mix": "^4.1.4" from "laravel-mix": "^2.1.14" and
"vue": "^2.5.17 to  "vue": "^2.6.10"
and vue insisted i install "vue-template-compiler" after all this upgrade and ow it works only with Vue.component('name',require('').default)); still not sure which broke my code

**Comment by theWebKeyGuy** [comment]
Any answer on this question yet?....

**Comment by teflondepa** [comment]
I resolved the issue by following the steps below:

1. npm -i babel-polyfill
3. in webpack.mix.js I added:
require('babel-polyfill');
....
mix.js('...').styles([..]).polyfill({
        enabled: true,
        corejs: 2,
       useBuiltIns: "usage",
        targets:  "ie 9"
     })

Also ensure that you are not using any packages that cannot be transpiled to ES5.. For instance, I was using CKEditor 5 which somehow had features that could not be transpiled..

**Comment by teflondepa** [comment]
Sorry, I think you must also install core-js, i.e.: npm i core-js

**Comment by serak** [comment]
Thank you all actually a combination of all the above worked for me

```
npm install @babel/polyfill
npm install core-js
npm install laravel-mix-polyfill
```

and inside webpack.mix.js

`require('laravel-mix-polyfill');
const TargetsPlugin = require('targets-webpack-plugin')`
mix.webpackConfig({
    plugins: [
        new TargetsPlugin({
          browsers: ['last 2 versions', 'chrome >= 41', 'IE 11'],
        }),
      ]});
mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css/app.css')
    .polyfill({
        enabled: true,
        useBuiltIns: "usage",
        targets: {"ie": 11},
        debug: true,
        corejs: 3, 
     });
`
And inside app.js 
`
require('./bootstrap');
import '@babel/polyfill';
`

**Comment by cyborg-z** [comment]
@serak 
npm install --save-dev targets-webpack-plugin

**Comment by hugomejia** [comment]
If, this can help anyone, the solution proposed by @serak (& @cyborg-z) actually worked for my but only after updating Node to version 14.4.
