### ISSUE TITLE
Laravel mix's webpack.config.js pulls in a load of shite which makes it impossible to copy into home directory, and laravel-mix doesn't seem to support removing the default rules

### ISSUE THREAD

**Issue by tomc1998** [JeffreyWay/laravel-mix#2175]
laravel-mix@4.1.2
node: v8.10.0
npm: 3.5.2

With the default laravel project (made with laravel new), the laravel mix webpack.config.js file actually just imports a bunch of other stuff, rather than being a normal config file - this makes it really difficult to copy out into your project directory to customise. You have to dig inside and change the require paths to point into your node_modules, and even after that I'm getting this:

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { defaultRules?, exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, strictExportPresence?, strictThisContextOnImports?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
```

On top of this, laravel mix seem to be unable to remove the default rules? The above issue wouldn't be so bad if laravel mix WAS an '80%' solution, but trying to add an SVG loader is impossible because the default svg rule can't be removed ???

**Comment by tomc1998** [comment]
Even copying the entire laravel-mix directory into the project root results in this

```
TypeError: Cannot redefine property: tap                                    
    at Function.defineProperty (<anonymous>)              
    at Object.<anonymous> (/var/www/node_modules/laravel-mix/src/helpers.js:21:8)
```

I have absolutely no idea how people are using this today, what's everyone else's setup??

**Comment by JeffreyWay** [comment]
I have no idea what you're trying to do, but you shouldn't be copying the Mix directory in `node_modules` to your project root. Of course that's not going to work.

You can override any of the default rules with `mix.override(() => {});`
