### ISSUE TITLE
error on npm install with nuxt js

### ISSUE THREAD

**Issue by oldnana** [JeffreyWay/laravel-mix#2185]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`)
-   Node Version (`v8.10.0`):
-   NPM Version (`3.5.3`):
-   OS:

### Description:
Hi everyone . i'm trying to deploy a web app , and when I'm tryring to npm install , this is what happens  , I hope someone can help me with this 
### Steps To Reproduce:

npm ERR! Linux 4.15.0-55-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /var/www/sample
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/var/www/sample'
npm ERR!  { Error: EACCES: permission denied, access '/var/www/sample'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/var/www/sample' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Linux 4.15.0-55-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path npm-debug.log.1060306220
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.1060306220'
npm ERR!  { Error: EACCES: permission denied, open 'npm-debug.log.1060306220'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.1060306220' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/sample/npm-debug.log

**Comment by robbyrice** [comment]
As the error indicates, the folder that you are working in does not have the correct permissions. Make sure that you have read and write permissions for the /var/www/sample folder and you should be all set.

**Comment by oldnana** [comment]
hi I've already solved this issue , seems like I forgot to add ' sudo' on my command
