### ISSUE TITLE
Mix not detecting https on hmr via mix.webpackConfig

### ISSUE THREAD

**Issue by hailwood** [JeffreyWay/laravel-mix#2187]
-   Laravel Mix Version: 4.1.2
-   Node Version (`node -v`):12.8.0
-   NPM Version (`npm -v`): 6.10.3
-   OS: Ubuntu 19.04

### Description:
Laravel mix expects you to enable https in the dev server by using the `--https` flag.
But this isn't the only way to enable https, we like to configure the `devServer` property in `mix.webpackConfig` something like the following.

```js
mix.webpackConfig({
  devServer: {
    overlay: true,
    disableHostCheck: true,
    https: {
      key: fs.readFileSync(process.env.WEBPACK_KEY),
      cert: fs.readFileSync(process.env.WEBPACK_CERT),
    },
  }
});
````

Unfortunately the only way Laravel Mix looks for https is via `let http = process.argv.includes('--https') ? 'https' : 'http';`

The issue with this is that if we add `--https` to the command then it ignores the options from our webpack config, and we shouldn't have to if we have it configured via webpackConfig.

This means that the initial build works, everything loads, but as soon as we attempt to hmr update anything it tries to request it from the dev server using http which obviously isn't configured (since the dev server HAS picked up our https config via webpackConfig).

At the bare minimum I would expect an option for us to be able to force a protocol (`Config.hmrOptions.protocol`) but the ideal solution would be to add a check for https configuration via webpackConfig.

As a cheap workaround adding `process.argv.push('--https');` to the top of my webpack.mix.js does seem to work.

**Comment by hailwood** [comment]
Still an active issue @JeffreyWay

**Comment by hailwood** [comment]
Still an active issue

**Comment by hailwood** [comment]
Still an active issue

**Comment by tnorthcutt** [comment]
Thanks for this, @hailwood. Seems like it addresses my use-case perfectly: https://twitter.com/tnorthcutt/status/1285961653239140353
