### ISSUE TITLE
Several sass files not processing correctly

### ISSUE THREAD

**Issue by zgabievi** [JeffreyWay/laravel-mix#219]
I have following code in `webpack.mix.js` on Laravel project:

```js
mix.js('resources/assets/js/app/app.js', 'public/js')
   .sass('resources/assets/sass/app/app.scss', 'public/css')
   .sass('resources/assets/sass/admin/app.scss', 'public/css/admin.css');
```

on command `npm run dev` I'm getting following error:

```
Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi" in PATH/resources/assets/sass/app/app.scss (line 1, column 1)
```

And `mix-manifest.json` file has this content:

```json
{
  "/js/app.js": "/js/app.js",
  "/css/app.css": "/css/app.css"
}
```

If I try to build without `app.scss` or `admin/app.scss/` file (solo sass method), It's working fine.

**Comment by edjeavons** [comment]
I am seeing this as well. 

As reported by @zgabievi, each file compiles on it's own but compiling multiple CSS files returns that error on each of them.

Compiling multiple JS files works fine, which may help to narrow down the problem.

**Comment by edjeavons** [comment]
I've narrowed down my particular problem to duplicate file _and_ directory names.  https://github.com/JeffreyWay/laravel-mix/issues/222#issuecomment-275947029

**Comment by JeffreyWay** [comment]
@edjeavons - Your issue is still valid, but @zgabievi's isn't anymore. He just needs to update his Laravel Mix dependency, and it should work.

**Comment by zgabievi** [comment]
@JeffreyWay thanks
