### ISSUE TITLE
Laravel mix SASS is very slow and HMR is weird

### ISSUE THREAD

**Issue by debute** [JeffreyWay/laravel-mix#2194]
-   Laravel Mix Version: 4.1.2 (`npm list --depth=0`)
-   Node Version (`node -v`): v10.16.0
-   NPM Version (`npm -v`): 6.9.0
-   OS: Windows 10 Pro, version 1903 (build 18362.267)

### Steps To Reproduce slow compiling:

1. install clean laravel as said in documentation
2. install npm dependecies (`npm i`) and run `npm run hot`
3. change any .scss file and compiling takes around 6 seconds!!!

I think this is horrible when we are talking about  HMR. My simple starter kit (made with gulp and browserify) compiles and injects CSS with miliseconds, even for much bigger files, but Laravel Mix seems to be better way because of webpack. Also I noticed, that speed is very slow while importing bootstrap (`@import '~bootstrap/scss/bootstrap';`). When I remov it, then it compiles 100-200ms, which is good, but I need bootstrap for grid mixins, breakpoints and more.

Right after running a command
![1](https://user-images.githubusercontent.com/3219895/63058444-08762d80-beed-11e9-9fe9-30f5c28fece7.png)

Compiling. Slow, but it is first compile, so its OK
![2](https://user-images.githubusercontent.com/3219895/63058445-090ec400-beed-11e9-80ad-00be119ab5f2.png)

Very very slow compiling, because I only changed one line of style
![3](https://user-images.githubusercontent.com/3219895/63058446-090ec400-beed-11e9-82aa-947420fb8851.png)

### Steps To Reproduce weird injecting:

1. have some style, for example: set body background to red
2. run `npm run hot`
3. do some work...
4. go back to your body style and remove "background line"
5. body in browser remains RED

Before you run, you have your CSS file where is defined, that body has red background. After run, it is not simple to change. Since injected CSS is acting like "style" element, then remove "background line" from CSS will do nothing, because older style (from imported CSS file) has this styling. If you change that line from red to white, it will be OK. But this is not a solution. HMR has no logic here, if you have to rewrite your own style.

Will this be fixed? Because I don't really see a point of using Laravel Mix, while things like this happen. I also make extensions for mix, but this makes me somehow angry.

If you "don't believe me" I can record my screen while creating fresh new Laravel application. Maybe it's problem of my computer, but how?

**Comment by AndreasHerss** [comment]
@krehak did you find a solution to the CSS issue? i'm having the same problem :S

**Comment by AndreasHerss** [comment]
Update: my "fix" was to put the link to my stylesheet at the bottom of the document, just before body closing tag, as HMR injects style in head, the document comes after now.

**Comment by krehak** [comment]
@AndreasHerss I didn't find any solution yet, maybe tomorrow I can try something, but I switched to my hybrid parcel.js+gulp+postcss project, which works surprisingly very fast (with tailwind+typescript). For my real project (to make money) I use best-known duo webpack+gulp... But I will surely look into your fix, it would be cool if it will work.

**Comment by krehak** [comment]
@AndreasHerss sry, I am very lazy and forget about this. I tried your fix, but it didn't work for anything. Compilation speed is still slow as before and injecting styles is much worse. Now, when you have style at the end of the page, then while developing with HMR (npm run hot) is impossible, because the style at the end will be overriding injected styles to the head. So you change your SCSS and you won't be able to see the difference - it is like it didn't change at all.
