### ISSUE TITLE
Use npm if project does not have yarn.lock file

### ISSUE THREAD

**Issue by mikeerickson** [JeffreyWay/laravel-mix#2196]
-   Laravel Mix Version: 4.1.2
-   Node Version: 12.2.0
-   NPM Version: 6.10.3
-   OS:

### Description:

When installing vue dependencies (such as `vue-template-compiler`) use the users desired package manager by checking if `yarn.lock` file exists.  If not, use `npm`

In my case, I always use `npm` thus if I have removed `yarn.lock` file, the first time running `npm run watch` it will install `vue-template-compiler` using yarn.

### Steps To Reproduce:

1. create new laravel application `laravel new test`
2. remove `yarn.lock`
3. run `npm install` (for first time)
4. run `npm run watch`

When it determines `vue-template-compiler` is not installed, it will install it using yarn regardless of the desired package manager.

I am proposing to check the existence of `yarn.lock` and if it does not existing (indicating the project is likely managed with npm) to use npm to install dependencies, thus not messing with the current `node_modules`

As it stands, it assumes yarn is being used and is forced to rebuild the whole `node_modules` installation.

See associated PR proposal

**Comment by JeffreyWay** [comment]
npm is exclusively used now.
