### ISSUE TITLE
Compatibility with sass-loader 8.0.0

### ISSUE THREAD

**Issue by danielbachhuber** [JeffreyWay/laravel-mix#2206]
-   Laravel Mix Version: 4.1.2

### Description:

A heads up that Laravel mix doesn't seem to be compatible with sass-loader 8.0.0 (just released) which has some breaking changes.

### Steps To Reproduce:

See build failure in https://github.com/danielbachhuber/simple-event-tracking/pull/3

**Comment by it-can** [comment]
getting this error:

```
ERROR in ./resources/assets/scss/fontawesome.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'outputStyle'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/test/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:49:11)
    at Object.loader (/test/node_modules/sass-loader/dist/index.js:36:28)
    at /test/node_modules/webpack/lib/NormalModule.js:313:20
    at /test/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /test/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/test/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/test/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /test/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at /test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
 @ ./resources/assets/scss/fontawesome.scss
```

**Comment by Xenonym** [comment]
[`node-sass@8.0.0` changed the format of its `options` object](https://github.com/webpack-contrib/sass-loader/releases/tag/v8.0.0) such that all `node-sass`/`dart-sass` options are now in a `sassOptions` property instead of being directly in the `options` object itself: 

> ⚠ BREAKING CHANGES
> [...]
> - move all sass (includePaths, importer, functions) options to the sassOptions option.

**Comment by it-can** [comment]
can someone create a PR?

**Comment by sergeifilippov** [comment]
What's a work around?

Changing `package.json` valus `"sass-loader": "^7.0.0",` now throwns the following:

```
ERROR in ./src/css/scss/site.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Dart Sass version 1.23.0-module.beta.1 is incompatible with ^1.3.0.
```

**Comment by jeshusho** [comment]
I solved this incident by doing the following:
npm uninstall --save-dev sass-loader
npm install --save-dev sass-loader@7.1.0

**Comment by sergeifilippov** [comment]
> What's a work around?
> 
> Changing `package.json` valus `"sass-loader": "^7.0.0",` now throws the following after `npm run dev`:
> 
> ```
> ERROR in ./src/css/scss/site.scss
> Module build failed (from ./node_modules/css-loader/index.js):
> ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> Error: Dart Sass version 1.23.0-module.beta.1 is incompatible with ^1.3.0.
> ```

A work around for now is switching back to using `node-sass`.

Install node-sass

```
npm install --save-dev node-sass
yarn add node-sass
```

In `webpack.mix.js`

```
...
mix.sass(`${_src}/css/scss/app.scss`, `${_dist}/css`, {implementation: require('node-sass')})
...
```

**Comment by hotrush** [comment]
@sergeifilippov confirmed, switching to node-sass helped

**Comment by patrickcarlohickman** [comment]
@sergeifilippov Dart sass accidentally released their 1.23 beta version as the latest version. If you update your `package.json` to target `"sass": "^1.22.10"`, that'll fix your specific issue.

**Comment by hotrush** [comment]
@patrickcarlohickman that also works, but for me spawns lot of warnings)

**Comment by tofikhidayat** [comment]
I tried to return the sass loader to version 7 and it worked

**Comment by sergeifilippov** [comment]
Switched back to using `dart-sass` by:

A workaround for now is switching back to using node-sass.

Remove `node-sass`

```
npm remove --save-dev node-sass
yarn remove node-sass
```

In `webpack.mix.js`

...
mix.sass(`${_src}/css/scss/app.scss`, `${_dist}/css`)
...

So far no issues 👍

**Comment by jinxkitt108** [comment]
> I solved this incident by doing the following:
> npm uninstall --save-dev sass-loader
> npm install --save-dev sass-loader@7.1.0

can i see your webpack.mix.js codes.. i am having hard time using Vuetify 2

**Comment by jinxkitt108** [comment]
> Switched back to using `dart-sass` by:
> 
> A workaround for now is switching back to using node-sass.
> 
> Remove `node-sass`
> 
> ```
> npm remove --save-dev node-sass
> yarn remove node-sass
> ```
> 
> In `webpack.mix.js`
> 
> ...
> mix.sass(`${_src}/css/scss/app.scss`, `${_dist}/css`)
> ...
> 
> So far no issues 👍

i am using vuetify 2 and im having issues with this webpack.mix.js set up.

const mix = require('laravel-mix');

mix.webpackConfig({
   resolve: {
         extensions: ['.js', '.vue'],
         alias: {
               '@': __dirname + '/resources'
         }
   }

});

mix.js('resources/js/app.js', 'public/js')
   .sass('resources/sass/app.scss', 'public/css');

im getting error......

ERROR in ./resources/js/routes.js
Module not found: Error: Can't resolve '@js/components/About' in 'C:\wamp64\www\sfawsdev.j\resources\js'
 @ ./resources/js/routes.js 4:0-41 15:15-20
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/routes.js
Module not found: Error: Can't resolve '@js/components/Home' in 'C:\wamp64\www\sfawsdev.j\resources\js'
 @ ./resources/js/routes.js 3:0-39 11:15-19
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

**Comment by robbyrice** [comment]
A quick and dirty work-around to this is to edit the src/components/Sass.js file and change the following function from this
```
pluginOptions(pluginOptions) {
    return Object.assign(
        {
            precision: 8,
            outputStyle: 'expanded',
            implementation: () =>
                Mix.seesNpmPackage('node-sass')
                    ? require('node-sass')
                    : require('sass')
        },
        pluginOptions,
        { sourceMap: true }
    );
}
```

to this
```
pluginOptions(pluginOptions) {
    return {sassOptions: Object.assign(
        {
            precision: 8,
            outputStyle: 'expanded',
            implementation: () =>
                Mix.seesNpmPackage('node-sass')
                    ? require('node-sass')
                    : require('sass')
        },
        pluginOptions,
        { sourceMap: true }
    )};
}
```
If you go this route it means that this change will most likely be over-ridden with future updates to laravel-mix. However, any future updates will hopefully provide compatibility with sass-loader 8 so this shouldn't be a problem.

**Comment by Nothing-Works** [comment]
same problem here, have to roll back to 7.x versions.

**Comment by bedus-creation** [comment]
> I solved this incident by doing the following:
> npm uninstall --save-dev sass-loader
> npm install --save-dev sass-loader@7.1.0

Indeed

**Comment by sergeifilippov** [comment]
This has been fixed with [v5.0.0](https://github.com/JeffreyWay/laravel-mix/releases/tag/v5.0.0)

**Comment by bedus-creation** [comment]
> This has been fixed with [v5.0.0](https://github.com/JeffreyWay/laravel-mix/releases/tag/v5.0.0)

Yeah, But I have been using laravel-mix v3, as v4 and V5 has issue with dynamic import.

**Comment by ubaidillahSriyudi** [comment]
> I solved this incident by doing the following:
> npm uninstall --save-dev sass-loader
> npm install --save-dev sass-loader@7.1.0

thanks it's really work !

**Comment by FaycalBorsali** [comment]
> I solved this incident by doing the following:
> npm uninstall --save-dev sass-loader
> npm install --save-dev sass-loader@7.1.0

Thank yous it worked for me !
But is it a permanent solution or just a quick workaround ?

**Comment by Wildindfw** [comment]
> npm install --save-dev sass-loader@7.1.0

I got this 

npm ERR! Cannot read property 'match' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cjord\AppData\Roaming\npm-cache\_logs\2020-02-23T08_04_13_205Z-debug.log

**Comment by IOIIOOIO** [comment]
I'm having this same issue. Downgrading to sass-loader 7.1 worked for me.

**sass-loader: 8.0.2**
**laravel-mix: 5.0.4**

my code in webpack.mix.js:

`
const mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css', {
       precision : 5
    })
`

**Comment by hosseinazeemi** [comment]
> I solved this incident by doing the following:
> npm uninstall --save-dev sass-loader
> npm install --save-dev sass-loader@7.1.0

Thank you it worked for me !

**Comment by AyoAyomide** [comment]
> I solved this incident by doing the following:
> npm uninstall --save-dev sass-loader
> npm install --save-dev sass-loader@7.1.0

thanks really works

**Comment by Jleagle** [comment]
sass-loader@7.1.0 was released on 2018-08-01 so downgrading that far can't be a good solution.

**Comment by seyfer** [comment]
what is the most recent solution?
