### ISSUE TITLE
styles of every component is in the dom

### ISSUE THREAD

**Issue by brickgale** [JeffreyWay/laravel-mix#2207]
-   Laravel Mix Version: 4.0.15
-   Node Version (`node -v`): 8.16.0
-   NPM Version (`npm -v`): 6.4.1
-   OS: mac osx (inside docker shell)

### Description:
When your app has a `vue-router` with multiple routes or pages already, you can see or notice that you can see a lot of `<style>` inside `<head>` which includes from all components whether it is unmounted or not. 

### Steps To Reproduce:
- just having multiple routes/pages with `vue-router`
- inspect your `<head>` tag and notice when you route change, no updates on list of `<style>` (s) usually it mounts a new `<style>` when route change on `vue-cli` projects which is the correct behaviour.

NOTE: just noticed this cause my project configuration is on theming, encountering css duplicates when you have two components that are almost similar in content. (might not be an issue on smaller projects)

**Comment by bgildea** [comment]
I would like to see a solution to this as well...
