### ISSUE TITLE
@font-face show in results windows 10

### ISSUE THREAD

**Issue by pixieaka** [JeffreyWay/laravel-mix#221]
@font-face {
    font-family: 'kufi';
    src: url('../fonts/kufi/kufi.eot');
    src: url('../fonts/kufi/kufi.eot?#iefix')format('embedded-opentype'),
         url('../fonts/kufi/kufi.woff') format('woff'),
         url('../fonts/kufi/kufi.ttf') format('truetype'),
         url('../fonts/kufi/kufi.svg#kufi') format('svg');
    font-style: normal;
    font-weight: normal;
}

                                                           Asset       Size  Chunks                    Chunk Names
                 fonts/kufi.svg?669b3085f0be52cd1f3064430589f466     334 kB          [emitted]  [big]
  fonts/fontawesome-webfont.eot?674f50d287a8c48dc19ba404d20fe713     166 kB          [emitted]
  fonts/fontawesome-webfont.svg?912ec66d7572ff821749319396470bde     444 kB          [emitted]  [big]
  fonts/fontawesome-webfont.ttf?b06871f281fee6b241d60582ae9369b9     166 kB          [emitted]
 fonts/fontawesome-webfont.woff?fee66e712a8a08eef5805a46892932ad      98 kB          [emitted]
fonts/fontawesome-webfont.woff2?af7ae505a9eed503f8b8e6982036873e    77.2 kB          [emitted]
                 fonts/kufi.eot?fd8d5b98b9874e5acc6de2d2cbf1931b    35.8 kB          [emitted]
                 fonts/kufi.ttf?a9b030e29a35f523a137ee0175be419f    81.2 kB          [emitted]
                fonts/kufi.woff?0b2c0e74f616b916c9ca2027f3ddc2f3    38.9 kB          [emitted]
                                                      /js/app.js     271 kB       0  [emitted]  [big]  /js/app
                                                /css/app-ltr.css     183 kB       0  [emitted]         /js/app
                                                /css/app-rtl.css     183 kB       0  [emitted]         /js/app
                                               mix-manifest.json  116 bytes          [emitted]

**Comment by alanondra** [comment]
Why is it presuming that someone wants the files in that location anyway? This should be an optional configuration. Its default behavior should be to output CSS using the paths given without making copies of the files. Now it just performs extra processes the developer didn't ask for and using extra space without permission.

**Comment by JeffreyWay** [comment]
@pixieaka That's expected behavior. Your compiled CSS will reference the correct path.

**Comment by alanondra** [comment]
You need to either use absolute paths (because apparently all Laravel projects live at the base directory) or make a copy of `webpack.config.js` from their Node package and delete the reference to that config file from your NPM job configs.
