### ISSUE TITLE
Feature: Code splitting, create more chunk file as create-react-app does.

### ISSUE THREAD

**Issue by domzgarcia** [JeffreyWay/laravel-mix#2214]
-   Laravel Mix Version:   "laravel-mix": "^4.0.7",
-   Node Version (`node -v`): v10.16.0
-   NPM Version (`npm -v`): 6.4.1
-   OS: Windows

### Description:
Generate more chunk files using mix.react()
Is it possible to create more chunk file as create-react-app does?
Right now it only creates App.js, what happened if my react application gets bigger?
Thanks, Jeff!

### Steps To Reproduce:
Not applicable.

**Comment by ciamarro** [comment]
It's possible and quite painless.  I'm playing around with this now
[https://laravel-news.com/using-dynamic-imports-with-laravel-mix](url)

**Comment by domzgarcia** [comment]
I've tried that but in react. using React.lazy import and adding comment
doesn't work

**Comment by domzgarcia** [comment]
Hi, @ciamarro may I request using reactjs? thank you

**Comment by ciamarro** [comment]
Hey @domzgarcia .  I was using Vue.  The article did say mention React, but the example is in Vue

**Comment by domzgarcia** [comment]
Yeah, @ciamarro , but what I was looking for is an implementation in ReactJS not in Vue. Vue is very easy and straight forward. It would be helpful if you can provide a sample in REACT instead.
