### ISSUE TITLE
question about vue translation

### ISSUE THREAD

**Issue by zhengfen** [JeffreyWay/laravel-mix#2215]
Hi, All,

as for translation, I use barryvdh/laravel-translation-manager for admin users to manage translations.

then martinlindhe/laravel-vue-i18n-generator to share Laravel localizations with vue front-end

when user update translations, js will not be updated automatically

I added in controller \Artisan::call('vue-i18n:generate');

is there a way to run 'npm run production' from controller?

any ideas? Thank you in advance.
----------------

I actually found the solution from doc of martinlindhe/laravel-vue-i18n-generator

php artisan vue-i18n:generate --format umd

I dont know umd, that's why I did not read that part carefully in the beginning....

sorry that I asked a silly question

**Comment by ndberg** [comment]
For what do you want to call npm run production from code? that would be very hacky.
