### ISSUE TITLE
Produces 0 byte CSS files when using dynamic imports and .extract

### ISSUE THREAD

**Issue by EmperorArthur** [JeffreyWay/laravel-mix#2219]
-   Laravel Mix Version: 4.1.4
-   Node Version: v10.15.2
-   NPM Version: 6.11.1
-   OS: Linux

### Description:
When using dynamic imports with `.extract` the compiles css file is 0 bytes!  This is regardless of #2217.

### Steps To Reproduce:

Unfortunately, I do not have the time to produce a working separate test repository at this time.
I have collected what I believe to be a working test case here.

When compiling with these options, the addition and removal of the `.extract()` determines if app.css is a zero byte file or not.

webpack.mix.js:
```
mix.setPublicPath('...')
mix.setResourceRoot('/static/.../generated');
mix.sass('resources/sass/app.scss', 'css');
mix.js('resources/js/app.js', 'js').extract();
```

app.js:
```
import Vue from 'vue';
Vue.component('app', () => import('./App'));
window.app = new Vue({el: '#app',});blue
```

App.vue:
```
<template>
    <div class="test">
        test
    </div>
</template>

<script>
    export default {
        name: "App",
    }
</script>
```

app.scss:
```
.test {
  color: red;
}
```

**Comment by YeisonHunt** [comment]
I had a  similar problem. When I use dynamic import with components, in locals it works fine but when i deploy production, the dynamic components are not loaded. Some help with that friends ?

**Comment by pixleight** [comment]
I'm having the exact same issue; the combination of `extract()` in Mix and `import()` in JS is generating 0-byte CSS.

Example terminal output when using both methods:

Asset | Size | Chunks |   | Chunk Names
----- | ---- | ------ | - | -----------
/assets/css/app.css | 0 bytes | /assets/javascript/app, /assets/javascript/manifest, /assets/javascript/vendor | [emitted] | /assets/javascript/app, /assets/javascript/manifest, /assets/javascript/vendor
/assets/javascript/app.js | 102 KiB | /assets/javascript/app | [emitted] | /assets/javascript/app
/assets/javascript/manifest.js | 9.02 KiB | /assets/javascript/manifest | [emitted] | /assets/javascript/manifest
/assets/javascript/vendor.js | 329 KiB | /assets/javascript/vendor | [emitted] | /assets/javascript/vendor
assets/javascript/test-component.js | 7.76 KiB | assets/javascript/test-component | [emitted] | assets/javascript/test-component

**Comment by pmochine** [comment]
Yes had the same issue right now @EmperorArthur , what I don't understand why @JeffreyWay released Laravel Mix 5.0, when webpack 5 is not out yet.

**Comment by markkimsal** [comment]
Webpack claims the problem is with the deprecated `extract-text-webpack-plugin` and recommends using `mini-css-extract-plugin`

https://github.com/webpack/webpack/issues/6703
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/738

**Comment by ed-fruty** [comment]
@markkimsal, @pmochine, @thecrypticace, @JeffreyWay, @pixleight, @YeisonHunt, @EmperorArthur

Does anyone has ready solution or working example ?

**Comment by thecrypticace** [comment]
@ed-fruty I don't have any workable solutions for webpack 4. This will be fixed in the next release that uses webpack 5. The work on this is already in progress.

**Comment by wmcmurray** [comment]
@ed-fruty I was able to [work around this](https://github.com/JeffreyWay/laravel-mix/issues/2123#issuecomment-619314801) in webpack 4 using `mini-css-extract-plugin`.

Hope it helps !

**Comment by skeeith** [comment]
Up until now, this is still an issue.

**Comment by brada1703** [comment]
Any update?

**Comment by janzankowski** [comment]
+1 to fixing this.

**Comment by thecrypticace** [comment]
This isn't an issue any longer in Mix v6
