### ISSUE TITLE
Sourcemaps off/on

### ISSUE THREAD

**Issue by FDiskas** [JeffreyWay/laravel-mix#223]
Source-maps should be available only in development. On productions it should be removed.
So I suggest respect the ENV

```js
mix
  .js('resources/assets/js/app.js', 'public/js')
  .sourceMaps(!mix.inProduction)
````

**Comment by JeffreyWay** [comment]
Thanks! It'll disable them automatically behind the scenes now.

**Comment by growlead** [comment]
mix.inProduction - FUNCTION

mix
  .js('resources/assets/js/app.js', 'public/js')
  .sourceMaps(!**mix.inProduction()**)
