### ISSUE TITLE
[Laravel 6.0] Error display broken for view error with mix.browserSync

### ISSUE THREAD

**Issue by kylekatarnls** [JeffreyWay/laravel-mix#2239]
-   Laravel Mix Version: 4.1.4
-   Node Version (`node -v`): 12.9.1
-   NPM Version (`npm -v`): 6.10.2
-   OS: Windows

### Description:
Raw display of JS file on view error:
![Raw JS file instead of error](https://user-images.githubusercontent.com/5966783/64488139-899eb700-d244-11e9-8639-468ed32b70c7.png)

### Steps To Reproduce:
- Fresh install of Laravel 6.0
- Add `mix.browserSync({proxy: 'localhost:8000'});` to **webpack.mix.js**
- Replace **welcome.blade.php** content with `{{ 1/0 }}` (to trigger Division by zero exception)
- Run `npm run watch`
- Open http://localhost:3000/

### Expected
The nice error display we have in http://localhost:8000/ (dispay with `Facade\Ignition\Exceptions\ViewException`)

### Observed
![Raw JS file instead of error](https://user-images.githubusercontent.com/5966783/64488139-899eb700-d244-11e9-8639-468ed32b70c7.png)

Original issue: https://github.com/laravel/framework/issues/29909

**Comment by fitztrev** [comment]
PR #2227 will fix this

**Comment by kylekatarnls** [comment]
Great, thanks.

**Comment by kylekatarnls** [comment]
Hi @JeffreyWay the stale bot locked this issue, but the PR is still open for 2 months and get no comments and was not merged. Please re-open.
