### ISSUE TITLE
help me pls 

### ISSUE THREAD

**Issue by ihatepoper** [JeffreyWay/laravel-mix#2244]
This dependency was not found:

* C:\xampp\htdocs\finals\resources\sass\theme.scss in multi ./resources/js/app.js ./resources/sass/app.scss ./resources/sass/theme.scss

To install it, you can run: npm install --save C:\xampp\htdocs\finals\resources\sass\theme.scss
                Asset      Size   Chunks             Chunk Names
         /css/app.css   436 KiB  /js/app  [emitted]  /js/app
           /js/app.js   1.4 MiB  /js/app  [emitted]  /js/app
\js\sweetalert.min.js  39.9 KiB           [emitted]

ERROR in multi ./resources/js/app.js ./resources/sass/app.scss ./resources/sass/theme.scss
Module not found: Error: Can't resolve 'C:\xampp\htdocs\finals\resources\sass\theme.scss' in 'C:\xampp\htdocs\finals'
 @ multi ./resources/js/app.js ./resources/sass/app.scss ./resources/sass/theme.scss /js/app[2]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ihatepoper\AppData\Roaming\npm-cache\_logs\2019-10-05T13_57_25_654Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ihatepoper\AppData\Roaming\npm-cache\_logs\2019-10-05T13_57_25_851Z-debug.log

**Comment by alanondra** [comment]
How are you trying to import it in `/resources/sass/app.scss`?
