### ISSUE TITLE
Build is excruciatingly slow

### ISSUE THREAD

**Issue by joeyhub** [JeffreyWay/laravel-mix#2251]
Laravel Mix Version: 2.1.14
Node: 12.11.1
OS: Centos 7

On modest machine:

Compiled successfully in 696660ms

On workstation:

Compiled successfully in 117331ms

Somewhere in the dependency chain through the vendor packages something is causing it to lock up but I can't get mix to give me any verbosity on what's blocking.

**Comment by joeyhub** [comment]
This is a project I picked off someone else. I have no idea where mix starts and webpack ends. A smart and competent developer made it but they also put their faith in laravel + spark and when I'm doing the devops such as the build I'm faced with a nexus of madness and complexity.

I saw briefly node stuck on 100% CPU. strace just showed futexes. Will strace harder later to grab the preceding IO.

It looks like the problem is it's behind sass and things don't integrate well. If I run sass it fails on those weird ~ namespaces. Is there a say I can just run sass with whatever config that is then man sass to pass the verbosity options?

I see things like version and extract but then I realise they're about server to client and nothing to do with backend build caching.

If anything is webpack's responsibility please let me know. Though I've tried a few obvious things and gotten a huge listing of files, etc it seems really hard to find out how to do things like time per leaf, then branch, etc or with extract what the vendors actually are.

**Comment by mpash** [comment]
@joeyhub can you provide an example of your `webpack.mix.js` file? There are many things you can do to improve speed. It is more likely you're not optimizing your JavaScript with tree-shaken imports and using the `webpack.ContextReplacementPlugin` for packages like `moment`. It would also be helpful to run a bundle analysis tool such as https://github.com/webpack-contrib/webpack-bundle-analyzer

**Comment by joeyhub** [comment]
As far as I've been able to tell it gets stuck on sass/scss. It's definitely that eating a huge proportion of the time.

It apparently doesn't support tracking individual files, caching, etc.

There are various things that come up in search but none of them work to speed it up.

This might also be compounded by whatever mix and laravel defaults is doing with plugins.

It's a black box.
