### ISSUE TITLE
[BUG REPORT] extractVueStyles has conflict with extract method

### ISSUE THREAD

**Issue by kfeng0806** [JeffreyWay/laravel-mix#2257]
-   Laravel Mix Version: 5.0
-   Node Version (`node -v`): v12.5.0
-   NPM Version (`npm -v`): 6.12.0
-   OS: MacOs 10.14.6

### Description:

When enable `extractVueStyles` vue component scoped styles does not extract to dedicated css file if enable vendor extract.

After some research i finally found the problem cause in some library has import or require css like `require('xxx/xxx/xxx.css')`
Mix only extract library import css but skipped all vue component styles.

### Steps To Reproduce:
My mix config
``` javascript
mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .options({
        extractVueStyles: '/css/extract.css'
    })
    .extract(['vue-cropperjs'])
```

In the example above i am using `"vue-cropperjs": "^3.0.0"`, in `VueCropper.js` https://github.com/Agontuk/vue-cropperjs/blob/v3.0.0/dist/VueCropper.js#L11 has `require('cropperjs/dist/cropper.css');` if i comment this line, all vue component style extract properly otherwise only `cropperjs/dist/cropper.css` extract in `extract.css`

**Comment by timrspratt** [comment]
Just had this happen, extracted vendor imports using `mix.extract()` and set `extractVueStyles: true`, with a single `app.css` file, the only contents is the vendor CSS and no CSS from `<style>` tags inside `.vue` files and also nothing from `app.scss`.

**Comment by nobrother** [comment]
Is there any workaround for this bug?

**Comment by thecrypticace** [comment]
Can you provide a minimal reproduction repo so we can look into it?
