### ISSUE TITLE
Npm Run Dev not working with laravel 6 

### ISSUE THREAD

**Issue by yousoftme** [JeffreyWay/laravel-mix#2258]
$ npm run dev

> @ dev C:\xampp\htdocs\laravel6
> npm run development

'npm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by yousoftme** [comment]
![npm path](https://user-images.githubusercontent.com/39268245/67074524-c09cac80-f1a2-11e9-9d86-318f2d070a41.JPG)

**Comment by JosuelRocha** [comment]
probably problem with your npm installation, try downloading and installing again. https://nodejs.org/en/ or add the path C:\Program Files\nodejs to your OS Environment Variables.

**Comment by yousoftme** [comment]
Solved By Running 
`npm run dev`
as administrator in cmd

**Comment by alanondra** [comment]
Sounds like your environment variables were only set for the admin user account when you installed it.

You can change it for your normal user account by going to Control Panel > User Accounts then clicking "Change my environment variables" on the left-hand side.
