### ISSUE TITLE
How to bypass mix-manifest.json for some files?

### ISSUE THREAD

**Issue by OwenMelbz** [JeffreyWay/laravel-mix#2263]
We're in a situation where we have 2 mix configs, 1 of the configs has a really slow build script in it, which is why we removed from the main process, and only needs to be rebuilt once in a blue moon.

This works fine - however even though `version()` isnt turned on, the slow build overwrites the `mix-manifest.json`.

The slow build doesn't need to be in this at all, is there anyway to tell Mix not to build this manifest? e.g. removing the plugin from the chain

Thanks

**Comment by alanondra** [comment]
From looking at the source code, it looks like the file is created as an instance of `Manifest` and attached to the `Mix` instance. I'm just spitballing, but see if you can change `mix.manifest.name` in your "mixpack" config file(s).

But then there's the issue of Laravel looking for that file if you use the `asset` helper function in your template...
