### ISSUE TITLE
npm run dev fails on fresh 5.4 install

### ISSUE THREAD

**Issue by JordanDalton** [JeffreyWay/laravel-mix#227]
I encountered this on a fresh 5.4 install.

```
Jordans-MacBook-Pro:Mix jordandalton$ npm run dev

> @ dev /Users/jordandalton/Code/Projects/Mix
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/Users/jordandalton/Code/Projects/Mix/node_modules/laravel-mix/setup/webpack.config.js:120
        let extractPlugin = new plugins.ExtractTextPlugin(
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:54:16)
    at Module._compile (module.js:375:25)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at requireConfig (/Users/jordandalton/Code/Projects/Mix/node_modules/webpack/bin/convert-argv.js:96:18)
    at /Users/jordandalton/Code/Projects/Mix/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v5.2.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jordandalton/Code/Projects/Mix/npm-debug.log
```

So I tried updating laravel-mix to 0.5.9 but no luck. Also updated node and npm to latest versions...no luck as well.

**Comment by JeffreyWay** [comment]
Upgrade Node.

**Comment by davidnsparks** [comment]
Im using 6.9.4 node and have the same issue on a fresh install - HELP :(

**Comment by ggdx** [comment]
Same and Node 7.5.0

**Comment by davidnsparks** [comment]
I added

"babel": { "presets": [ "es2015" ] }

To pacakge.json and it fixed everything.


On Feb 10, 2017, at 8:49 AM, Daniel White <notifications@github.com<mailto:notifications@github.com>> wrote:


Same and Node 7.5.0

**Comment by ggdx** [comment]
There it is. Thanks @davidnsparks !

**Comment by ahadabasi** [comment]
I encountered this on a fresh 5.4 install too.
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 silly lifecycle @~predev: no script for predev, continuing
7 info lifecycle @~dev: @
8 verbose lifecycle @~dev: unsafe-perm in lifecycle true
9 verbose lifecycle @~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\wamp\www\hamkelasi\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\ProgramData\ComposerSetup\bin;c:\Program Files\Git\cmd;C:\Gradle\gradle-2.13\bin;C:\Python\Scripts\;C:\Python\;C:\Users\edu7\AppData\Roaming\Composer\vendor\bin\;%Program Files%\nodejs\node_modules\;C:\Ruby23-x64\bin;C:\Users\edu7\AppData\Roaming\npm\;%Program Files%\Git\bin\;C:\bin\;D:\wamp\bin\mysql\mysql5.7.11\bin\;D:\wamp\bin\MongoDB\bin\;D:\wamp\bin\php\php7.0.4\
10 verbose lifecycle @~dev: CWD: D:\wamp\www\hamkelasi
11 silly lifecycle @~dev: Args: [ '/d /s /c',
11 silly lifecycle   'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js' ]
12 silly lifecycle @~dev: Returned: code: 2  signal: null
13 info lifecycle @~dev: Failed to exec dev script
14 verbose stack Error: @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @
16 verbose cwd D:\wamp\www\hamkelasi
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.10.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
22 error Exit status 2
23 error Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by ahadabasi** [comment]
I use node v6.10.0 and npm v3.10.10 and have the same issue on a fresh install:

    0 info it worked if it ends with ok
    1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
    1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
    1 verbose cli   'run',
    1 verbose cli   'dev' ]
    2 info using npm@3.10.10
    3 info using node@v6.10.0
    4 verbose run-script [ 'predev', 'dev', 'postdev' ]
    5 info lifecycle @~predev: @
    6 silly lifecycle @~predev: no script for predev, continuing
    7 info lifecycle @~dev: @
    8 verbose lifecycle @~dev: unsafe-perm in lifecycle true
    9 verbose lifecycle @~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\wamp\www\hamkelasi\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\ProgramData\ComposerSetup\bin;c:\Program Files\Git\cmd;C:\Gradle\gradle-2.13\bin;C:\Python\Scripts\;C:\Python\;C:\Users\edu7\AppData\Roaming\Composer\vendor\bin\;%Program Files%\nodejs\node_modules\;C:\Ruby23-x64\bin;C:\Users\edu7\AppData\Roaming\npm\;%Program Files%\Git\bin\;C:\bin\;D:\wamp\bin\mysql\mysql5.7.11\bin\;D:\wamp\bin\MongoDB\bin\;D:\wamp\bin\php\php7.0.4\
    10 verbose lifecycle @~dev: CWD: D:\wamp\www\hamkelasi
    11 silly lifecycle @~dev: Args: [ '/d /s /c',
    11 silly lifecycle   'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js' ]
    12 silly lifecycle @~dev: Returned: code: 2  signal: null
    13 info lifecycle @~dev: Failed to exec dev script
    14 verbose stack Error: @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
    14 verbose stack Exit status 2
    14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
    14 verbose stack     at emitTwo (events.js:106:13)
    14 verbose stack     at EventEmitter.emit (events.js:191:7)
    14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
    14 verbose stack     at emitTwo (events.js:106:13)
    14 verbose stack     at ChildProcess.emit (events.js:191:7)
    14 verbose stack     at maybeClose (internal/child_process.js:877:16)
    14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
    15 verbose pkgid @
    16 verbose cwd D:\wamp\www\hamkelasi
    17 error Windows_NT 10.0.10586
    18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
    19 error node v6.10.0
    20 error npm  v3.10.10
    21 error code ELIFECYCLE
    22 error @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
    22 error Exit status 2
    23 error Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
    23 error Make sure you have the latest version of node.js and npm installed.
    23 error If you do, this is most likely a problem with the  package,
    23 error not with npm itself.
    23 error Tell the author that this fails on your system:
    23 error     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
    23 error You can get information on how to open an issue for this project with:
    23 error     npm bugs
    23 error Or if that isn't available, you can get their info via:
    23 error     npm owner ls
    23 error There is likely additional logging output above.
    24 verbose exit [ 1, true ]

I also added `"babel": { "presets": [ "es2015" ] }` to `pacakge.json`

**Comment by thisismyaim** [comment]
Same problem Node 7.7.1, Added "babel": { "presets": [ "es2015" ] } but still error

**Comment by ahadabasi** [comment]
Try reinstalling `node-sass`, it worked for me.
`npm install node-sass`

**Comment by lcpiragibe** [comment]
Add in devDependencies in package.json:

"babel-preset-es2015": "^6.22.0"

**Comment by AttaUrRehman24** [comment]
You can solve this problem 100%
https://github.com/AttaUrRehman24/laravel-mix

**Comment by harryhan24** [comment]
@AttaUrRehman24 100%? no absolutely not

**Comment by ahmed-raza** [comment]
Im having the same problem, tried everything mentioned above upgraded node/npm as well no success so far.

**Comment by GregKeaney** [comment]
For what it's worth.  I have same issue.  Upgrading node did nothing.  Using phpStorm I was getting an unresolved asset error.  Resolved that with this - https://stackoverflow.com/questions/29805943/set-background-css-image-in-phpstorm-cannot-resolve-file 

Still failed until I changed first line of webpack.mix.js

from - let mix = require('laravel-mix');
to - const mix = require('laravel-mix');

Runs now, frankly not exactly sure why.

**Comment by JeffreyWay** [comment]
There's no way that that change fixed it. It had to be something else.

**Comment by GregKeaney** [comment]
I agree as it has now returned.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: ` cross-env NODE_ENV=development node_modules/webpack/bin/webpac
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional log

And this:

This relative module was not found:

* ./images/invictus_logo.png in ./node_modules/css-loader?{"url":true,"sourceMap":fa
lse,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"
postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root
":"C://xampp//htdocs//invictus//node_modules"}!./node_modules/sass-loader/lib/loader
.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sas
s/invictus.scss

**Comment by GregKeaney** [comment]
Very odd.  Followed the solution here - https://github.com/JeffreyWay/laravel-mix/issues/805

npm run dev now works ONLY if my second myapp.sass file does not include an image asset that phpStorm feels it can't locate.  If I mark my public dir as Resouces Root and then use the url 'images/my_image.png', phpStorm locates it but npm run dev fails.

The message popup say ERROR: Can't resolve .images/my_image.png.

??  this is all new.

**Comment by NicolasVanhecke** [comment]
@GregKeaney Not sure if this will fix anything, but problems with image (or just url's in general), might be fixed by adding this at the bottom of your `webpack.mix.js`. Something to do with relative/absolute paths to files and images and far as I understand.   
  
`mix.options({ processCssUrls: false });`

**Comment by telliott22** [comment]
I had the same issue, solved it by adding babel-preset-es2015 and node-sass to devDependcies in package.json:

```
   "devDependencies": {
    "babel-preset-es2015": "^6.22.0",
    "node-sass": "^4.5.3",
....
  },
```

And running `npm install`
