### ISSUE TITLE
Mix.version() doesnt work with non laravel projects

### ISSUE THREAD

**Issue by nanaaikinson24** [JeffreyWay/laravel-mix#2271]

**Comment by tbleckert** [comment]
@nanaaikinson24 What do you mean? We use it all the time. You just have to read the mix-manifest.json manually.

**Comment by nanaaikinson24** [comment]
let mix = require("laravel-mix");

mix.webpackConfig({
  resolve: {
    alias: {
      "@dev": path.resolve(__dirname, "development/")
    }
  }
});

// Mix api
mix
  // Admin
  .js("development/admin/js/auth/login.js", "assets/js/admin/auth/login.js")
  .js(
    "development/admin/js/subject/index.js",
    "assets/js/admin/subject/index.js"
  )
  .js(
    "development/admin/js/subject/create.js",
    "assets/js/admin/subject/create.js"
  )
  .js("development/admin/js/subject/edit.js", "assets/js/admin/subject/edit.js")

  .js(
    "development/admin/js/programme/index.js",
    "assets/js/admin/programme/index.js"
  )

  .sass("development/frontend/scss/app.scss", "assets/css/frontend/app.css")

  .sass("development/common/utilities.scss", "assets/css/utilities.css")
.version();

When i run npm run prod, i get this error
 
Error: ENOENT: no such file or directory, open 'C:\assets\css\frontend\app.css'                                                                               
    at Object.openSync (fs.js:451:3)                                                                                                                          
    at Object.readFileSync (fs.js:353:35)                                                                                                                     
    at File.read (C:\xampp\htdocs\premodal-server\node_modules\laravel-mix\src\File.js:166:19)                                                                
    at File.version (C:\xampp\htdocs\premodal-server\node_modules\laravel-mix\src\File.js:173:25)                                                             
    at Manifest.hash (C:\xampp\htdocs\premodal-server\node_modules\laravel-mix\src\Manifest.js:52:65)                                                         
    at C:\xampp\htdocs\premodal-server\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:77:26                                                 
    at Collection.each (C:\xampp\htdocs\premodal-server\node_modules\collect.js\dist\methods\each.js:21:14)                                                   
    at CustomTasksPlugin.applyVersioning (C:\xampp\htdocs\premodal-server\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:76:37)             
    at C:\xampp\htdocs\premodal-server\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:15:22                                                 
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\xampp\htdocs\premodal-server\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:18
:1)                                                                                                                                                           
    at AsyncSeriesHook.lazyCompileHook (C:\xampp\htdocs\premodal-server\node_modules\tapable\lib\Hook.js:154:20)                                              
    at C:\xampp\htdocs\premodal-server\node_modules\webpack\lib\Compiler.js:304:22                                                                            
    at Compiler.emitRecords (C:\xampp\htdocs\premodal-server\node_modules\webpack\lib\Compiler.js:499:39)                                                     
    at C:\xampp\htdocs\premodal-server\node_modules\webpack\lib\Compiler.js:298:10                                                                            
    at C:\xampp\htdocs\premodal-server\node_modules\webpack\lib\Compiler.js:485:14                                                                            
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\xampp\htdocs\premodal-server\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15
:1)                                                                                                                                                           
    at AsyncSeriesHook.lazyCompileHook (C:\xampp\htdocs\premodal-server\node_modules\tapable\lib\Hook.js:154:20)                                              
    at C:\xampp\htdocs\premodal-server\node_modules\webpack\lib\Compiler.js:482:27                                                                            
    at C:\xampp\htdocs\premodal-server\node_modules\neo-async\async.js:2818:7                                                                                 
    at done (C:\xampp\htdocs\premodal-server\node_modules\neo-async\async.js:3522:9)                                                                          
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\xampp\htdocs\premodal-server\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:
1)                                                                                                                                                            
    at C:\xampp\htdocs\premodal-server\node_modules\webpack\lib\Compiler.js:464:33                                                                            
    at C:\xampp\htdocs\premodal-server\node_modules\graceful-fs\graceful-fs.js:57:14                                                                          
    at FSReqCallback.oncomplete (fs.js:157:23)                                                                                                                
npm ERR! code ELIFECYCLE                                                                                                                                      
npm ERR! errno 1                                                                                                                                              
npm ERR! premodal-server@1.0.0 production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modul
es/laravel-mix/setup/webpack.config.js`                                                                                                                       
npm ERR! Exit status 1                                                                                                                                        
npm ERR!                                                                                                                                                      
npm ERR! Failed at the premodal-server@1.0.0 production script.                                                                                               
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                            
                                                                                                                                                              
npm ERR! A complete log of this run can be found in:                                                                                                          
npm ERR!     C:\Users\Nana Aikinson\AppData\Roaming\npm-cache\_logs\2019-11-06T13_49_01_423Z-debug.log                                                        
error Command failed with exit code 1.                                                                                                                        
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by tbleckert** [comment]
@nanaaikinson24 Can you confirm that the assets directory exists?

**Comment by ivanvermeyen** [comment]
Hey,

I just had a similar issue. Mix couldn't find the output CSS file when I enabled `mix.version()`
The file did exist though.

I have added this line to my `webpack.mix.js` file:

```
mix.setPublicPath('public');
```

You probably need to set this to your own desired output folder.
This worked for me, so maybe also for you...

**Comment by roarkmccolgan** [comment]
I can confirm that ```.setPublicPath('public');``` sorts out the error but version does not actually version the files, just outputs files with no version:

```
mix.setPublicPath('static').js('src/app.js', 'dist/').postCss('src/app.css', 'dist/', [
  require('tailwindcss'),
]).version();
```

```
 DONE  Compiled successfully in 3973ms                                                                                                                       1:59:59 PM
       Asset      Size     Chunks             Chunk Names
/dist/app.js  4.33 KiB  /dist/app  [emitted]  /dist/app
dist/app.css   862 KiB  /dist/app  [emitted]  /dist/app
```

**Comment by ivanvermeyen** [comment]
Hmmm, it does for me:

```js
const mix = require('laravel-mix');
require('laravel-mix-purgecss');

mix.setPublicPath('public');

mix.js('resources/js/app.js', 'public/js');
mix.extract(['jquery']);

mix.sass('resources/sass/app.scss', 'public/css');
mix.purgeCss();

mix.version();
```

```js
{
    "/js/app.js": "/js/app.js?id=fcf809135010e9554baa",
    "/css/app.css": "/css/app.css?id=2b94fed76e92f6ce2693",
    "/js/manifest.js": "/js/manifest.js?id=41f053ba9a94d81b39f8",
    "/js/vendor.js": "/js/vendor.js?id=cb4c1759a762a91ab602"
}
```

I'm using:

```js
"laravel-mix": "^5.0.0",
```

**Comment by fahmilatib** [comment]
@roarkmccolgan the versions are set in your `mix-manifest.json` file. In you case, since you set the public path to `static`, a new manifest file is generated in that folder.
