### ISSUE TITLE
Autoprefixer not honouring config options

### ISSUE THREAD

**Issue by mrgodhani** [JeffreyWay/laravel-mix#2273]
-   Laravel Mix Version: 5.0.0 (`npm list --depth=0`)
-   Node Version (`node -v`): 12.12.0
-   NPM Version (`npm -v`): 6.11.3
-   OS: Mac

### Description:
Autoprefixer does not seem to honor override. Previously in version 3, it used to add prefixes for IE for flexboxes now it doesn't do the same thing anymore

### Steps To Reproduce:
1) Try to compile css
2) On output `-ms-` prefixes are not there for Flex related attributes. Also, overriding options for autoprefixer as per the documentation is not working.

**Comment by matt-h** [comment]
@mrgodhani did you close this because you figured it out? I'm having the exact same issue currently.

**Comment by mrgodhani** [comment]
@matt-h  Yes actually you have to define browser list in your package.json

**Comment by gilleard** [comment]
Fwiw I think the docs are out of date - if you're using `mix.options({ autoprefixer:` without including `enabled: true` then it won't run anymore. Suspect it's related to the switch to collect.js
