### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by JarnoNijhof** [JeffreyWay/laravel-mix#2274]
I tried to install dev but it shows an error when I run it:
```
PS C:\Users\Jarno\workspace\track-server> npm run dev
npm ERR! path C:\Users\Jarno\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Jarno\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jarno\AppData\Roaming\npm-cache\_logs\2019-11-07T10_08_08_100Z-debug.log
PS C:\Users\Jarno\workspace\track-server>
```

I did the following;
1. `npm install webpack-dev-server --save-dev`
2. Add the following code to package.json file:
```
"scripts": {
  "start:dev": "webpack-dev-server"
}
```
3. `npm run start:dev`

when I got the error I show above, I did this;
`npm rm -rf node_modules`
`npm rm package-lock.json`
`npm cache clear --force`
`npm i`

After this I tried to `npm run start:dev`/`npm run dev` again but it's still not working...

Can someone solve this?

**Comment by mackied0g** [comment]
For some reason, I'm getting a very similar error only after I run `npm run dev`: 

`npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/usrname/Development/code/thisproject/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/usrname/Development/code/Athisproject/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/usrname/.npm/_logs/2019-11-15T21_10_12_844Z-debug.log`

**Comment by JarnoNijhof** [comment]
Hi,
I fixed it...
I runned it after I quit the current loaded project in the terminal. ( crtl + C/command + C)
I tried it last time just again after the error and it works.

Mayby it's a bug because I have it multiple times right now...

**Comment by Pwawazi** [comment]
I found out that this error occurs when I'm in the wrong file directory

**Comment by marix88** [comment]
> 

Thank you, you are right, so I managed to install the npm! My path was incomplete, I was in another directory which contains the directory where my file is located, when my path should have included the name of the directory which directly contains my file.

**Comment by ubathebee** [comment]
Thanks so much guys. been having this problem couldnt reconsile the directory until now
