### ISSUE TITLE
Suggest to upgrade webpack cli dependency to >= 3.3.5 to prevent Mix from crashing on Mondays (when on Windows)

### ISSUE THREAD

**Issue by epalmans** [JeffreyWay/laravel-mix#2277]
-   Laravel Mix Version: 4.0.16
-   Node Version: 10.15.0
-   NPM Version: 6.9.2
-   OS: Windows 10 (build 10.0.18362.418)

### Description:

Laravel Mix crashes on Monday. Sounds weird, but it's due to a known bug with webpack-cli prior to version 3.3.5. See https://github.com/webpack/webpack-cli/issues/962

### Steps To Reproduce:

On a Windows machine, run ```npm run <mix script command>``` on a Monday.

### Suggested solution:

Upgrade ```webpack-cli``` dependency to ```~3.3.5```.

**Comment by ankurk91** [comment]
https://github.com/JeffreyWay/laravel-mix/blob/d432101c23198252e3952d8d89ee246d209265a8/package.json#L67

You can re-install `laravel-mix` it should pick latest version
