### ISSUE TITLE
Production js() size of larger than script() function

### ISSUE THREAD

**Issue by ahmeti** [JeffreyWay/laravel-mix#2283]
-   Laravel Mix Version: 4.1.4
-   Node Version: v11.12.0
-   NPM Version: 6.13.0
-   OS: macOS Catalina - v10.15.1

### Description:

I compared **js()** and **scripts()** functions on **npm run production** command.

I noticed that the size of the **js()** function is much larger than **scripts()** function.

I would like to show you samples.

 _Sample 1 does not appear differences._
_Sample 2 also looks very different._

What do you think about this subject?

#### Sample 1. Only jQuery Comparison

```js
// resources/js/app.js - in laravel
window.$ = window.jQuery = require('jquery');

// webpack.mix.js - in laravel
const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js/')
    .scripts('node_modules/jquery/dist/jquery.min.js', 'public/js/app2.js');
```
<img width="392" alt="test-jquery" src="https://user-images.githubusercontent.com/5817450/69496752-664fe380-0ee6-11ea-813f-4c3331998b0a.png">

#### Sample 2. jQuery + Chart.js Comparison

```js
// resources/js/app.js - in laravel
window.$ = window.jQuery = require('jquery');
require('chart.js');

// webpack.mix.js - in laravel
const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js')
    .scripts([
        'node_modules/jquery/dist/jquery.min.js',
        'node_modules/chart.js/dist/Chart.min.js',
    ], 'public/js/app2.js');
```
<img width="441" alt="test-chartjs" src="https://user-images.githubusercontent.com/5817450/69496820-4c62d080-0ee7-11ea-874b-adb41351ad9b.png">

**Comment by ankurk91** [comment]
ss() = webpack + uglify

scripts() = combine + uglify (no module support)
