### ISSUE TITLE
npm run hot merges stylesheets

### ISSUE THREAD

**Issue by reed-jones** [JeffreyWay/laravel-mix#2284]
-   Laravel Mix Version: v5.0.0
-   Node Version (`node -v`): 13.1.0
-   NPM Version (`npm -v`): 6.12.1
-   OS: macOS Mojave 10.14.6

### Description:
When compiling multiple stylesheets with mix, `npm run hot` seems to merge them and server them all, regardless of whether or not that sheet is included on the page.

### Steps To Reproduce:

```js
// webpack.mix.js
mix.sass('resources/sass/page_one.scss', 'public/css/page_one.css')
    .sass('resources/sass/page_two.scss', 'public/css/page_two.css') 
    .sass('resources/sass/page_three.scss', 'public/css/page_three.css') ;
```

// then in your head tags
```html
<link rel="stylesheet" href="{{ mix('css/page_three.css') }}">
```

npm run dev/watch/prod all work normally, but `npm run hot` will load all three stylesheets.

**Comment by Jchedev** [comment]
I have the same problem. Any thoughts?

**Comment by reed-jones** [comment]
I have been using 'watch' instead for now, however potentially #2199 fixes this?

**Comment by reed-jones** [comment]
Hmm, thanks stale bot... Still an issue though unfortunately.

**Comment by owalerys** [comment]
This is still an issue.
