### ISSUE TITLE
Weird issue with global variable sharing in SCSS

### ISSUE THREAD

**Issue by sinemacula** [JeffreyWay/laravel-mix#2285]
-   Laravel Mix Version: 3.0.0
-   Node Version: 10.16.3
-   NPM Version: 6.9.0
-   OS: MacOS Catalina 10.15.1

### Introduction

I fully appreciate that I am using an old version of Laravel Mix and as such, this may not be supported, however, I am hoping that the issue will be very simple and therefore one might be willing to lend a bit of helping hand.

_The reason I am using Laravel Mix v3 is simply because of the known dynamic importing issue in Webpack 4, thus, upgrading is sadly not an option._

My current mix configuration is quite complex so I will do my best to only include the _potentially_ relevant snippets from my code.

### The Issue

I have a variable in my JavaScript that I share with my SCSS like so:

```
rules: [
    {
        test: /\.scss$/,
        loader: 'sass-loader',
        options: {
            data: `$static-url: '${config.app.urls.static}';`
        }
    }
]
```

The above works perfectly in all of my projects apart from this specific one. The only difference with this project is that I am using Laravel Mix version 3, instead of version 4/5/6.

In this particular project, the `$static-url` variable is succesfully shared with my `.scss` files, but **not** with the SCSS within my Vue templates and I cannot figure out why...

In other words, if I try to do something like the following, it won't work:

```
<template>

    <div class="foo"></div>

</template>

<style lang="scss" scoped>

    .foo {
        background-image: url($static-url + '/assets/images/example.jpg');
    }

</style>
```

The above throws the following error:

> Undefined variable: "$static-url".

Just to be clear, it **does** work on my `.scss` files, the issue is only with my Vue templates.

### What I have tried

I have tried various things such as:

- Upgrading `sass-loader` to v8.0.0 and using `prependData` - this didn't work as v8.0.0 is not compatible with this version of webpack/mix
- Adding `css-loader` and `vue-style-loader` to the test - this throws a different error stating `Invalid CSS after "...load the styles":...`

Can anyone see what I am doing wrong or is this a bug? If this is a bug then what other alternatives do I have in order to add a Javascript variable into my SCSS?

### Additional Information

Not sure if this is relevant but I am using the following package versions (removed irrelevant packages):

```
"devDependencies": {
    "cross-env": "^5.2.1",
    "css-declaration-sorter": "^4.0.1",
    "dotenv-webpack": "^1.7.0",
    "imports-loader": "^0.8.0",
    "laravel-mix": "^3.0.0",
    "node-sass": "^4.12.0",
    "sass": "^1.23.0",
    "sass-loader": "^7.3.1",
    "vue": "^2.6.10",
    "vue-template-compiler": "^2.6.10"
}
```

In addition, could this be to do with dynamic importing? I am declaring my Vue views like so:

```
const Welcome       = () => import(/* webpackChunkName: "welcome" */ './views/Welcome');
const Login         = () => import(/* webpackChunkName: "login" */ './views/Login');
const Home          = () => import(/* webpackChunkName: "home" */ './views/Home');
const NotFound      = () => import(/* webpackChunkName: "not-found" */'./views/NotFound');
```

**Comment by fractalf** [comment]
@sinemacula I'm also having this problem, did you ever resolve this problem?

```
mix
    .js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css', {
        implementation: require('node-sass'),
        prependData: () => {
            return '@import "resources/sass/colors.scss";'
        }
    })
```

Trying to use any variable in `colors.scss` just gives me `SassError: Undefined variable.`
