### ISSUE TITLE
how to define custom prefix in manifest.json

### ISSUE THREAD

**Issue by clearcodecn** [JeffreyWay/laravel-mix#2286]
this is my manifest.json file:

```
{
    "/app.js": "/app.js?id=8b59023b5e739db1a980",
    "/app.css": "/app.css?id=c59e2305529dbba1c228",
    "/play.js": "/play.js?id=86b70a467400fd9ec055"
}

```

and how can I add custom prefix like this output :

```
{
    "/app.js": "/prefix/app.js?id=8b59023b5e739db1a980",
    "/app.css": "/prefix/app.css?id=c59e2305529dbba1c228",
    "/play.js": "/prefix/play.js?id=86b70a467400fd9ec055"
}


```

**Comment by ilyen85** [comment]
I might be wrong, but I think you can achieve this with 
`mix.setPublicPath("public/prefix/")`

You should set this in your `webpack.mix.js` file. The line above will put your assets in the "public/prefix/" folder.
