### ISSUE TITLE
No error when .css is not found with mix.styles()

### ISSUE THREAD

**Issue by BasvanH** [JeffreyWay/laravel-mix#2289]
-   Laravel Mix Version: 5.0.0
-   Node Version: v10.15.3
-   NPM Version: 6.4.1
-   OS: Windows Server 2016

### Description:
When using mix.styles() like:
```
mix.styles([
      'node_modules/perfect-scrollbar/css/perfect-scrollbar.css',
      'node_modules/owl.carousel/dist/assets/owl.carousel.css',
      'bogusdir/owl.carousel/dist/assets/owl.theme.default.css'
   ], 'public/css/vendors/global.css');
```

And there's an non existing path in the array, you get no error or warning during compile. This is confusing and hard to find .css where you made a typo in the path name.

### Steps To Reproduce:
As described above, use .styles with a non existing path.

**Comment by BasvanH** [comment]
Please fix, thanks 👍

**Comment by paullaffitte** [comment]
Actually it seems that it's not an issue with laravel-mix but with one of it's dependency named [concatenate](https://github.com/stephenmathieson-boneyard/node-concatenate). As you can see it's used `FileCollection.merge` function to merge the files. The repository looks unmaintained so it's maybe a better solution to use another package instead, like [concat](https://www.npmjs.com/package/concat) or [concat-files](https://www.npmjs.com/package/concat-files).
