### ISSUE TITLE
JavaScript Module Loading Possibly Broken

### ISSUE THREAD

**Issue by JVMartin** [JeffreyWay/laravel-mix#229]
Hi Jeffrey (and others),

Love your work.

Replacing Bootstrap with Foundation in Elixir works great, but the same swap does not work in Mix.  I've spent over 8 hours trying to figure out why before bugging you here.

[I've created a simple modification to your laravel-mix-example that illustrates the issue](https://github.com/JVMartin/laravel-mix-example/commit/15ffa6752fc0e094784c2cb53641bcfcac6524a6).

Trying to run the resulting js results in the error `foundation is not a function`, because the Foundation code has not been ran at all (and so `$.fn.foundation` has not been defined):
![screenshot from 2017-01-29 22-49-33](https://cloud.githubusercontent.com/assets/4450814/22414554/477e2c10-e675-11e6-8577-364e72287bf4.png)

As best I can tell, the module loader in Elixir generates strings like so:
![screenshot from 2017-01-29 22-44-45](https://cloud.githubusercontent.com/assets/4450814/22414508/dd9b3fc2-e674-11e6-9c51-a40b1fa43b0d.png)

It appears to do this with some kind of experimental loader called [`buble-loader`](https://github.com/sairion/buble-loader).  The `eval()` call ensures the code gets ran.

Mix, on the other hand, uses perhaps a different Babel loader, resulting in actual code instead of a string:
![screenshot from 2017-01-29 22-54-20](https://cloud.githubusercontent.com/assets/4450814/22414644/0b2153b8-e676-11e6-88fb-a578a4bd1f1c.png)

For some reason, the jQuery plugin is never registered, it's as if it's dealing with a different jQuery instance?

[Several others are having the same issue.](https://laravel.io/forum/01-28-2017-laravel-mix-foundation-is-not-a-function)

Thanks in advance for any guidance.

**Comment by adriaanzon** [comment]
Were you using `mix.webpack` with Laravel Elixir?

It looks like this is an issue with Foundation: https://github.com/zurb/foundation-sites/issues/7386

**Comment by JeffreyWay** [comment]
Yeah that's weird. I can't get it to work either. Some odd foundation bug. 

If somebody figures out a fix, please post here.

**Comment by ItsRD** [comment]
Got the same problems, trying to get it fixed, but no solution so far...

**Comment by JVMartin** [comment]
Hmm...  I'm not sure that Foundation is the issue.

If you set up your app.js as just:
```js
window.$ = window.jQuery = require('jquery');
```

And then set up your template's scripts like this:
```js
<script src="{{ mix("js/app.js") }}"></script>
<script>
	jQuery(function() {
		alert('hello');
	});
</script>
```

It also throws an undefined error:
![screenshot from 2017-01-30 11-39-09](https://cloud.githubusercontent.com/assets/4450814/22438415/c2f6e786-e6e0-11e6-9990-8f83d233b255.png)

**Comment by JVMartin** [comment]
@ItsRD Thanks for the hack - while that seems to get Foundation running, I found it impossible to actually bind to any events like the modal open event and whatnot, no matter what I tried.

Everything I do in Elixir "just works", whereas most event-driven / jquery binding stuff doesn't work in Mix no matter what I try.

**Comment by JeffreyWay** [comment]
jQuery plugins can be confusing with Webpack - usually because they're legacy plugins that assume there will be a global jQuery object available to work with.

**Comment by JVMartin** [comment]
What's odd is how amazingly well Elixir's webpack works, even though it seems to be dependent on that "experimental" JS loader.

@JeffreyWay What do you think about perhaps using the same webpack JS loader that Elixir uses ([`buble-loader`](https://github.com/sairion/buble-loader)) in Mix?

**Comment by JeffreyWay** [comment]
@JVMartin - Maybe. I like Buble a lot. 

We're you using `mix.webpack()` with Laravel Elixir? Or `mix.scripts()`?

Webpack has always been confusing, when it comes to jQuery plugins. But I'd like to get this all figured out so that people don't even have to think about it.

I was able to get it working by:

1. Adding `mix.autoload({})` to your `webpack.mix.js` file.
2. Running `npm install script-loader`
3. Setting bootstrap.js to:

```js
import 'script-loader!jquery';
import 'script-loader!foundation-sites';

$(document).foundation();
```

**Comment by JVMartin** [comment]
Interesting.  I am using `mix.webpack()`.  I actually tried `script-loader` early on in my experiments, but was missing the `mix.autoload({})` which is probably why I had no success with it.

Here's what's working for me, using Elixir:

**gulpfile.js**
```js
elixir(mix => {
	mix.sass('app.scss');
	mix.webpack('app.js');
	mix.version(['css/app.css', 'js/app.js']);
});
```


**resources/assets/js/bootstrap.js**
```js
// Window-bound objects.
window._ = require('lodash');
window.$ = window.jQuery = require('jquery');
window.Vue = require('vue');
window.tinymce = require('tinymce/tinymce');
window.axios = require('axios');
window.axios.defaults.headers.common = {
	'X-Requested-With': 'XMLHttpRequest'
};

// Other packages.
require('foundation-sites');
require('any-other-jquery-plugin');
```

**resources/assets/js/app.js**
```js
require('./bootstrap');

$(document).foundation(); // Works great

$('#modal').bind('open.zf.reveal', function() { // Works great
	alert('Works great!');
});
```

Everything I throw at Elixir's webpack like this - jquery plugins, etc. - all work great without any additional tweaking.

I know next to nothing about converting ES6 to ES5, I wish I could be of more assistance in figuring out what's going wrong in Mix.

**Comment by AndyBursh** [comment]
@JeffreyWay Thanks for the `mix.autoload({})` tip. That worked perfectly for me, from a fresh Laravel 5.4 install with Laravel Mix.

For others, my relevant files are below (with a little experiment to prove the event binding works).

*boostrap.js*
```

window._ = require('lodash');

/**
 * We'll load jQuery and the Bootstrap jQuery plugin which provides support
 * for JavaScript based Bootstrap features such as modals and tabs. This
 * code may be modified to fit the specific needs of your application.
 */

window.$ = require('jquery');
window.jQuery = window.$;

/**
 * Vue is a modern JavaScript library for building interactive web interfaces
 * using reactive data binding and reusable components. Vue's API is clean
 * and simple, leaving you to focus on building your next great project.
 */

window.Vue = require('vue');

/**
 * Require Foundation JS
 */
require("foundation-sites");

/**
 * We'll load the axios HTTP library which allows us to easily issue requests
 * to our Laravel back-end. This library automatically handles sending the
 * CSRF token as a header based on the value of the "XSRF" token cookie.
 */

window.axios = require('axios');

window.axios.defaults.headers.common = {
    'X-Requested-With': 'XMLHttpRequest'
};
```

*app.js*
```

/**
 * First we will load all of this project's JavaScript dependencies which
 * includes Vue and other libraries. It is a great starting point when
 * building robust, powerful web applications using Vue and Laravel.
 */

require('./bootstrap');

/**
 * Next, we will create a fresh Vue application instance and attach it to
 * the page. Then, you may begin adding components to this application
 * or customize the JavaScript scaffolding to fit your unique needs.
 */

Vue.component('example', require('./components/Example.vue'));

const app = new Vue({
    el: "#app",

    mounted(){
        $(document).foundation();

        $("#dropdown-pane").on("hide.zf.dropdown", () => {
            console.log("Dropped down");
        });
    }
});
```
*webpack.mix.js*
```
const { mix } = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

// Prevents Mix's automatic configuring of jQuery, so that we
// can set it up ourselves later
// https://github.com/JeffreyWay/laravel-mix/issues/229#issuecomment-276230983
mix.autoload({});

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');
```

**Comment by amosmos** [comment]
This works great but for some reason when running the production code this fails...

@AndyBursh Can you check if running `yarn run production` works or fails for you?

Thanks!

**Comment by AndyBursh** [comment]
@amosmos I can't, sorry. I don't have a Mix project to test it on.
