### ISSUE TITLE
v5 upgrade docs shows 'Upgrade to v4' instead of v5

### ISSUE THREAD

**Issue by Jamesking56** [JeffreyWay/laravel-mix#2301]
https://laravel-mix.com/docs/5.0/upgrade shows the upgrade guide for v3 -> v4 instead of the upgrade guide for v4 -> v5

**Comment by mowangjuanzi** [comment]
I need it!!!

**Comment by Jamesking56** [comment]
Not stale

**Comment by sanjitkung** [comment]
Have same issue. Please help!

**Comment by pkid169** [comment]
Instruction doesn't seem to have changed since 4.0 so probably all you need to do is this -

npm remove laravel-mix
npm install laravel-mix@^5.0.0 --save-dev

or

yarn remove laravel-mix
yarn add laravel-mix@^5.0.0 --dev
