### ISSUE TITLE
Running npm production keeps creating <type>.LICENSE files?

### ISSUE THREAD

**Issue by francoism90** [JeffreyWay/laravel-mix#2304]
-   Laravel Mix Version: 5.0.1 (`npm list --depth=0`)
-   Node Version: (`node -v`): v13.5.0
-   NPM Version (`npm -v`):6.13.4
-   OS: Arch Linux

### Steps To Reproduce:

1. Run `npm run dev`, no .LICENSE files
2. Run `npm run prod`:

```
/js/app.js    207 KiB       0  [emitted]         /js/app
 /js/app.js.LICENSE  120 bytes          [emitted]         
/js/app.js.br   46.6 KiB          [emitted]         
/js/manifest.js   1.46 KiB       1  [emitted]         /js/manifest
/js/manifest.js.br  645 bytes          [emitted]         
/js/vendor.js   1.22 MiB       2  [emitted]  [big]  /js/vendor
/js/vendor.js.LICENSE  690 bytes          [emitted]         
/js/vendor.js.br    237 KiB          [emitted]
```
Is this something new? It doesn't happen on a clean Laravel install. I don't mind including LICENSE files, but they also contain version numbers, that may not be a suitable for production?

Thanks.

**Comment by iamjoshkendall** [comment]
The `terser-webpack-plugin` is creating these files. To disable it you need to customize the `mix.options` in your `webpack.mix.js` like this:

```js

mix.options({
  terser: {
    extractComments: false,
  }
})
```

**Comment by francoism90** [comment]
@iamjoshkendall Thanks! That indeed stops creating the `*.LICENSE` files. :)

**Comment by pathaksa** [comment]
> The `terser-webpack-plugin` is creating these files. To disable it you need to customize the `mix.options` in your `webpack.mix.js` like this:
> 
> ```js
> mix.options({
>   terser: {
>     extractComments: false,
>   }
> })
> ```

this worked for me
