### ISSUE TITLE
Creating extra js files

### ISSUE THREAD

**Issue by AlamTheInnov** [JeffreyWay/laravel-mix#2305]
app.js as default configuration

`const mix = require('laravel-mix');

/*
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/js/app.js', 'public/js')
   .sass('resources/sass/app.scss', 'public/css');
`

when running npm run dev/watch and then you look to the public/folder it contain extra js files with name 0.js, 1.js, 2.js and so on to 20/25.js other all are fine like public/js/app.js is fine but don't know why the extra files are creating?

Laravel version: 6.x

**Comment by noogen** [comment]
Did you check what are in those files?  This usually happen when you're importing javascript dynamically - https://javascript.info/modules-dynamic-imports

One way to spot dynamic import is to see if you are doing import in the middle or code somewhere.  If it is dynamic import, then change your code by statically import it to a variable somewhere at the top of your code and then use the variable later on.

**Comment by skeeith** [comment]
You must by dynamically importing javascript files.
