### ISSUE TITLE
BrowserSync fails with watch task: Assertion failed: (0), function uv_close, file ../deps/uv/src/unix/core.c, line 187

### ISSUE THREAD

**Issue by krimo** [JeffreyWay/laravel-mix#2313]
-   Laravel Mix Version: 5.0.1 (`npm list --depth=0`)
-   Node Version (`node -v`): 13.6.0
-   NPM Version (`npm -v`): 6.13.4
-   OS: macOS

### Description:
With a clean install of laravel mix on a non laravel project, browsersync fails and exits on the first file change after running `npm run watch`;

My webpack.mix.js file:

```
mix.js("src/app.js", "dist/")
	.sass("src/app.scss", "dist/")
	.browserSync("modular-wordpress.test");
```

### Steps To Reproduce:
- Run `npm run watch`
- Modify a scss or js file
- It fails with this output:

```
       Asset       Size     Chunks             Chunk Names
/dist/app.js    280 KiB  /dist/app  [emitted]  /dist/app
dist/app.css  127 bytes  /dist/app  [emitted]  /dist/app
Assertion failed: (0), function uv_close, file ../deps/uv/src/unix/core.c, line 187.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modular-wordpress@1.0.0 development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the modular-wordpress@1.0.0 development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/krimo/.npm/_logs/2020-01-18T18_07_52_384Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modular-wordpress@1.0.0 watch: `npm run development -- --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the modular-wordpress@1.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/krimo/.npm/_logs/2020-01-18T18_07_52_407Z-debug.log
```

**Comment by KrimoPixelsmith** [comment]
This seems related to https://github.com/webpack/webpack/issues/10037

**Comment by KrimoPixelsmith** [comment]
An update: after updating to Node 13.8.0 and npm 6.13.6, I no longer get the error message and the styles/scripts are compiled properly.

However, browsersync/mix does not inject the styles/reload for js. It's effectively like not having browsersync enabled at all. BrowserSync is working fine on other projects without mix; any insight @JeffreyWay ?

**Comment by teledirigido** [comment]
I am using Laravel Mix, Node `v13.8.0`, npm `6.13.6` and MacOS 10.13.6 and had this error too. I have updated BrowserSync on my package.json to `^2.26.7` run `$ yarn install` and it seems to be solved for now.
