### ISSUE TITLE
Npm run dev doesn't update app.js file!

### ISSUE THREAD

**Issue by ponikar** [JeffreyWay/laravel-mix#2319]
hello there,
   i am trying to compile ma js assets on shared hosting. the command "npm run dev" is working but it does not display the latest output of js file!

 Compiled successfully in 14434ms                                                                      11:46:20 PM

                                               Asset       Size   Chunks             Chunk Names
                                          /js/app.js   1.53 MiB  /js/app  [emitted]  /js/app
   images/error.svg?bc94754a1121c6aa50eecb2c5291c9a9  452 bytes           [emitted]
 images/loading.svg?619d2b3b6e7c86f0356ae1802c60309e  513 bytes           [emitted]
    images/logo.svg?52d414db396c02720c42eb3edfe5b301  656 bytes           [emitted]
images/send-btn.svg?3a2e84484dbb074a57ec87db030966cd  547 bytes           [emitted]
    images/sent.svg?99a39793437abd5edffe9fc26d3dfaee  311 bytes           [emitted]

I am getting this message but it won't change anything.

It would be so good of any of you would be helpful to me!

**Comment by paullaffitte** [comment]
Did you find a solution already? Otherwise could you provide the steps to reproduce?

**Comment by ponikar** [comment]
No i didn't find anything about that. You have to compile it on local and then after re-upload the entire SDK.

**Comment by paullaffitte** [comment]
Oh so it works locally? Wierd... Are you sure to use the same version of node on both systems? Did you push the package-lock.json? Could you share your configuration file?

**Comment by ponikar** [comment]
It seems I've found the solution! You have to install node modules on your server! I have not tried this solution but It may work
