### ISSUE TITLE
Sass compilation speed decreases dramatically when using url()

### ISSUE THREAD

**Issue by thepenguin1** [JeffreyWay/laravel-mix#232]
I have discovered that compiling sass takes considerably more time when my stylesheet includes `url()` references. Take for example the following CSS:

```
/* Web Fonts */
@font-face { font-family: "FontAwesome"; font-style: normal; font-weight: 400; src: local("Font Awesome"), local(FontAwesome-Regular), url("/fnt/FontAwesome-Regular.woff2") format("woff2") }
@font-face { font-family: "Proxima Nova"; font-style: normal; font-weight: 400; src: local("Proxima Nova"), local(ProximaNova-Regular), url("/fnt/ProximaNova-Regular.woff2") format("woff2") }
@font-face { font-family: "Proxima Nova"; font-style: normal; font-weight: 700; src: local("Proxima Nova Bold"), local(ProximaNova-Bold), url("/fnt/ProximaNova-Bold.woff2") format("woff2") }
@font-face { font-family: "Roboto"; font-style: normal; font-weight: 400; src: local("Roboto"), local(Roboto-Regular), url("/fnt/Roboto-Regular.woff2") format("woff2") }
@font-face { font-family: "Roboto"; font-style: normal; font-weight: 700; src: local("Roboto Bold"), local(Roboto-Bold), url("/fnt/Roboto-Bold.woff2") format("woff2") }
@font-face { font-family: "Oleo Script"; font-style: normal; font-weight: 400; src: local("Oleo Script"), local(OleoScript-Regular), url("/fnt/OleoScript-Regular.woff2") format("woff2") }
```

Without these lines, my compilation time is 372ms, but with these lines included, it jumps to 3207ms. 

It seems with each additional use of `url()` (for example, `background-image`), the compilation time increases and quickly becomes unusable. Particularly for `nom run watch` (over 3 seconds).

**Comment by JeffreyWay** [comment]
Yeah this is from the resolve-url-loader. It slows everything down drastically. 

Let me research this a bit and add a fix.

**Comment by adiachenko** [comment]
Create another entry to speed up re-compile.

I don't entirely inderstand how laravel-mix processes styles, but what most of webpack boilerplates for single-page javascript applications do is to handle examples like the above to the file-loader (unless the content is really small in which case it will be directly converted to url). 

And my point is, they still slow as heck, no way around that. You just need to organize your entry points in such a way that only an initial compilation will suffer the blow to performance.

**Comment by thepenguin1** [comment]
Do you mean not chaining? E.g. 

mix.sass().version();
mix.js().version();

Instead of mix.js().version().sass() etc

**Comment by adiachenko** [comment]
@thepenguin1 Yeah, instead of having one `app.scss` or whatever it's called nowadays, you create another entry sass file to store some rarely changed stuff like bootstrap and your fonts. That's what people usually do with webpack, because even if you take `url()` out of the equation, **extract-text-plugin** will be still much slower than raw **style-loader**.

**Comment by thepenguin1** [comment]
Got it. Thanks for the tip!

**Comment by JeffreyWay** [comment]
f5cb20274c24258dfb5c18741e627cc6235f03a6

**Comment by SYNTAG** [comment]
@JeffreyWay It is still slow. Do I need to install fast-sass-loader manually or something?

**Comment by haheute** [comment]
I moved my `url('/fonts/...` (`@font-face`) out of the SASS file into a plain css document.
That reduced compile time from 27sec to 7sec.
Only thing I don't understand is, why `/absolute` paths make the compilation slow, as I read they are ignored.

**Comment by cspor** [comment]
@SYNTAG oh my god, you saved me. Thank you so much for your second edit.

My compile times went up to over 20 seconds and after digging around and removing parts of scss I noticed that it was the urls that were causing the slow compile times but didn't know why or what was wrong with them.

Now i'm at 0.2 seconds again. Woohoo!

**Comment by SYNTAG** [comment]
@cspor Glad I was able to help! :)
