### ISSUE TITLE
"Error: EISDIR: illegal operation on a directory" on running `npm run production`

### ISSUE THREAD

**Issue by seewhy17** [JeffreyWay/laravel-mix#2320]
-   Laravel Mix Version: 4.1.4 (`npm list --depth=0`)
-   Node Version (`node -v`): 12.13.0
-   NPM Version (`npm -v`): 6.12.0
-   OS: Windows 10 Pro Build 1909 

### Description:
I ran `npm run production` and got this
```
λ npm run production

> @ production C:\wamp64\www\Admotad-Finance-DEPLOY
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js



 DONE  Compiled successfully in 6458ms                                                                             10:12:18 PM

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:506:3)
    at tryReadSync (fs.js:331:20)
    at Object.readFileSync (fs.js:368:19)
    at File.read (C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\laravel-mix\src\File.js:166:19)
    at File.version (C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\laravel-mix\src\File.js:173:25)
    at Manifest.hash (C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\laravel-mix\src\Manifest.js:52:65)
    at C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:77:26
    at Collection.each (C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\collect.js\dist\methods\each.js:21:14)
    at CustomTasksPlugin.applyVersioning (C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:76:37)
    at C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:15:22
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\tapable\lib\Hook.js:154:20)
    at C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\webpack\lib\Compiler.js:304:22
    at Compiler.emitRecords (C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\webpack\lib\Compiler.js:499:39)
    at C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\webpack\lib\Compiler.js:298:10
    at C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\webpack\lib\Compiler.js:485:14
    at _next1 (eval at create (C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at eval (eval at create (C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1)
    at onAfterEmit (C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\laravel-mix-imagemin\src\ManifestPlugin.js:20:13)
    at _next0 (eval at create (C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:34:1)
    at C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\copy-webpack-plugin\dist\index.js:114:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:30:1)
    at AsyncSeriesHook.lazyCompileHook (C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\tapable\lib\Hook.js:154:20)
    at C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\webpack\lib\Compiler.js:482:27
    at C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\neo-async\async.js:2818:7
    at done (C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\neo-async\async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\webpack\lib\Compiler.js:464:33
    at C:\wamp64\www\Admotad-Finance-DEPLOY\node_modules\graceful-fs\graceful-fs.js:57:14
    at FSReqCallback.oncomplete (fs.js:146:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cyril\AppData\Roaming\npm-cache\_logs\2020-02-02T21_12_19_105Z-debug.log
```

### Steps To Reproduce:

its a regular Laravel Project, I think showing my webpack.mix.js might provide some context
```
const mix = require('laravel-mix');
require('laravel-mix-tailwind');
require('laravel-mix-imagemin');
require('laravel-mix-purgecss');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/js/app.js', 'public/js/')
   .copyDirectory('resources/css/pickdate.js', 'public/css/pickdate.js')
   .copyDirectory('resources/js/purify.js', 'public/js/')
   .copyDirectory('resources/js/dayjs.min.js', 'public/js/')
   .copyDirectory('resources/js/ng-banks/', 'public/js/ng-banks/')
   .sass('resources/sass/app.sass', 'public/css')
   .tailwind('./tailwind.config.js')
   .options({
     processCssUrls: false,
     postCss: [ require('./tailwind.config.js') ],

   })
   .imagemin(
         'images/**.*',
         {
             context: 'resources',
         },
         {
             optipng: {
                 optimizationLevel: 5
             },
             jpegtran: null,
             plugins: [
                 require('imagemin-mozjpeg')({
                     quality: 100,
                     progressive: true,
                 }),
             ],
         }
     )
   .browserSync('http://localhost:8080/');

if (mix.inProduction()) {
  mix
   .version()
   .purgeCss();
}
```
I also noticed when I ran `npm list --depth=0` there were some missing peer dependencies

```
λ npm list --depth=0
C:\wamp64\www\Admotad-Finance-DEPLOY
+-- algoliasearch@3.35.1
+-- axios@0.19.0
+-- browser-sync@2.26.7
+-- browser-sync-webpack-plugin@2.0.1
+-- copy-webpack-plugin@5.0.5
+-- cross-env@5.2.1
+-- dayjs@1.8.18
+-- dompurify@2.0.7
+-- imagemin-mozjpeg@8.0.0
+-- imagemin-webpack-plugin@2.4.2
+-- instantsearch.js@4.1.1
+-- jquery-datetimepicker@2.5.21
+-- laravel-mix@4.1.4
+-- laravel-mix-imagemin@1.0.3
+-- laravel-mix-purgecss@4.2.0
+-- laravel-mix-tailwind@0.1.0
+-- lodash@4.17.15
+-- resolve-url-loader@2.3.2
+-- sass@1.23.7
+-- sass-loader@7.3.1
+-- sweetalert2@9.5.3
+-- tailwindcss@1.1.4
+-- vue@2.6.11
+-- vue-instantsearch@2.6.0
+-- vue-template-compiler@2.6.10
`-- UNMET PEER DEPENDENCY webpack@^1 || ^2 || ^3

npm ERR! peer dep missing: webpack@^1 || ^2 || ^3, required by browser-sync-webpack-plugin@2.0.1
npm ERR! peer dep missing: preact@<10, required by preact-compat@3.19.0
npm ERR! peer dep missing: preact@^8.2.7, required by preact-context@1.1.4
npm ERR! peer dep missing: preact@<10, required by preact-compat@3.19.0

```

**Comment by crinalljoshua** [comment]
Also having this problem, but it only appears to manifest when trying to use `mix.copy()` or `mix.copyDirectory()` when there's a `.` in the name of a directory in the source filepath. Replacing dots in source directories with other characters (i.e. `_`) gets around the issue, regardless of how I name the destination filepath, but this is not a scalable solution.

- Laravel Mix Version (`npm list --depth=0`): 4.1.2
- Node Version (`node -v`): 10.15.3
- NPM Version (`npm -v`): 6.9.0
- OS: Ubuntu 18.04.2 LTS

# Description #

Running `npm run dev` produces the following output:

```
> @ dev /home/vagrant/code/project
> npm run development


> @ development /home/vagrant/code/project
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 DONE  Compiled successfully in 37972ms

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:493:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:369:19)
    at File.read (/home/vagrant/code/octopus/node_modules/laravel-mix/src/File.js:166:19)
    at File.version (/home/vagrant/code/octopus/node_modules/laravel-mix/src/File.js:173:25)
    at Manifest.hash (/home/vagrant/code/octopus/node_modules/laravel-mix/src/Manifest.js:52:65)
    at manifest.forEach.file (/home/vagrant/code/octopus/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:81:47)
    at Array.forEach (<anonymous>)
    at CustomTasksPlugin.applyVersioning (/home/vagrant/code/octopus/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:81:18)
    at compiler.plugin.stats (/home/vagrant/code/octopus/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:14:22)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vagrant/code/octopus/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (/home/vagrant/code/octopus/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/home/vagrant/code/octopus/node_modules/webpack/lib/Compiler.js:304:22)
    at Compiler.emitRecords (/home/vagrant/code/octopus/node_modules/webpack/lib/Compiler.js:499:39)
    at emitAssets.err (/home/vagrant/code/octopus/node_modules/webpack/lib/Compiler.js:298:10)
    at hooks.afterEmit.callAsync.err (/home/vagrant/code/octopus/node_modules/webpack/lib/Compiler.js:485:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vagrant/code/octopus/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (/home/vagrant/code/octopus/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEachLimit.err (/home/vagrant/code/octopus/node_modules/webpack/lib/Compiler.js:482:27)
    at /home/vagrant/code/octopus/node_modules/neo-async/async.js:2818:7
    at done (/home/vagrant/code/octopus/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vagrant/code/octopus/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at outputFileSystem.writeFile.err (/home/vagrant/code/octopus/node_modules/webpack/lib/Compiler.js:464:33)
    at /home/vagrant/code/octopus/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-02-19T14_27_45_584Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-02-19T14_27_45_598Z-debug.log
```

# Steps to reproduce #

This only occurs in my environment when trying to use `mix.copy()` or `mix.copyDirectory()` on any directories that have a `.` somewhere in the filepath. Note that directly copying individual files works just fine, regardless of any dots in directory names. Below is my `webpack.mix.js` (trimmed down for brevity):

```
const mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

// Copying files directly works with no issues
mix.copy('node_modules/vue-multiselect/dist/vue-multiselect.min.css', 'public/css/vue-multiselect/dist/vue-multiselect.min.css');

// X-Editable
mix.copy("node_modules/x-editable/dist/jqueryui-editable/js/jqueryui-editable.min.js", "public/node_modules/x-editable/dist/jqueryui-editable/js/jqueryui-editable.min.js");

// AG Grid
mix.copyDirectory('node_modules/ag-grid-community', 'public/node_modules/ag-grid-community');
mix.copyDirectory('node_modules/ag-grid-enterprise', 'public/node_modules/ag-grid-enterprise');

// DataTables
// These appear to be the offending lines. Note that renaming the source directory to
// `datatables_net`/`datatables_net-zf` gets around the issue, but this is not a practical
// or scalable solution.
mix.copyDirectory("node_modules/datatables.net", "public/node_modules/datatables.net");
mix.copyDirectory("node_modules/datatables.net-zf", "public/node_modules/datatables.net-zf");

```

**Comment by ericsssan** [comment]
> Also having this problem, but it only appears to manifest when trying to use `mix.copy()` or `mix.copyDirectory()` when there's a `.` in the name of a directory in the source filepath. Replacing dots in source directories with other characters (i.e. `_`) gets around the issue, regardless of how I name the destination filepath, but this is not a scalable solution.
> 
> 
> 
> - Laravel Mix Version (`npm list --depth=0`): 4.1.2
> 
> - Node Version (`node -v`): 10.15.3
> 
> - NPM Version (`npm -v`): 6.9.0
> 
> - OS: Ubuntu 18.04.2 LTS
> 
> 
> 
> # Description #
> 
> 
> 
> Running `npm run dev` produces the following output:
> 
> 
> 
> ```
> 
> > @ dev /home/vagrant/code/project
> 
> > npm run development
> 
> 
> 
> 
> 
> > @ development /home/vagrant/code/project
> 
> > cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
> 
> 
> 
>  DONE  Compiled successfully in 37972ms
> 
> 
> 
> Error: EISDIR: illegal operation on a directory, read
> 
>     at Object.readSync (fs.js:493:3)
> 
>     at tryReadSync (fs.js:332:20)
> 
>     at Object.readFileSync (fs.js:369:19)
> 
>     at File.read (/home/vagrant/code/project/node_modules/laravel-mix/src/File.js:166:19)
> 
>     at File.version (/home/vagrant/code/project/node_modules/laravel-mix/src/File.js:173:25)
> 
>     at Manifest.hash (/home/vagrant/code/project/node_modules/laravel-mix/src/Manifest.js:52:65)
> 
>     at manifest.forEach.file (/home/vagrant/code/project/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:81:47)
> 
>     at Array.forEach (<anonymous>)
> 
>     at CustomTasksPlugin.applyVersioning (/home/vagrant/code/project/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:81:18)
> 
>     at compiler.plugin.stats (/home/vagrant/code/project/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:14:22)
> 
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vagrant/code/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
> 
>     at AsyncSeriesHook.lazyCompileHook (/home/vagrant/code/project/node_modules/tapable/lib/Hook.js:154:20)
> 
>     at emitRecords.err (/home/vagrant/code/project/node_modules/webpack/lib/Compiler.js:304:22)
> 
>     at Compiler.emitRecords (/home/vagrant/code/project/node_modules/webpack/lib/Compiler.js:499:39)
> 
>     at emitAssets.err (/home/vagrant/code/project/node_modules/webpack/lib/Compiler.js:298:10)
> 
>     at hooks.afterEmit.callAsync.err (/home/vagrant/code/project/node_modules/webpack/lib/Compiler.js:485:14)
> 
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vagrant/code/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
> 
>     at AsyncSeriesHook.lazyCompileHook (/home/vagrant/code/project/node_modules/tapable/lib/Hook.js:154:20)
> 
>     at asyncLib.forEachLimit.err (/home/vagrant/code/project/node_modules/webpack/lib/Compiler.js:482:27)
> 
>     at /home/vagrant/code/project/node_modules/neo-async/async.js:2818:7
> 
>     at done (/home/vagrant/code/project/node_modules/neo-async/async.js:3522:9)
> 
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vagrant/code/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
> 
>     at outputFileSystem.writeFile.err (/home/vagrant/code/project/node_modules/webpack/lib/Compiler.js:464:33)
> 
>     at /home/vagrant/code/project/node_modules/graceful-fs/graceful-fs.js:45:10
> 
>     at FSReqWrap.args [as oncomplete] (fs.js:140:20)
> 
> npm ERR! code ELIFECYCLE
> 
> npm ERR! errno 1
> 
> npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
> 
> npm ERR! Exit status 1
> 
> npm ERR! 
> 
> npm ERR! Failed at the @ development script.
> 
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> 
> 
> npm ERR! A complete log of this run can be found in:
> 
> npm ERR!     /home/vagrant/.npm/_logs/2020-02-19T14_27_45_584Z-debug.log
> 
> npm ERR! code ELIFECYCLE
> 
> npm ERR! errno 1
> 
> npm ERR! @ dev: `npm run development`
> 
> npm ERR! Exit status 1
> 
> npm ERR! 
> 
> npm ERR! Failed at the @ dev script.
> 
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> 
> 
> npm ERR! A complete log of this run can be found in:
> 
> npm ERR!     /home/vagrant/.npm/_logs/2020-02-19T14_27_45_598Z-debug.log
> 
> ```
> 
> 
> 
> # Steps to reproduce #
> 
> 
> 
> This only occurs in my environment when trying to use `mix.copy()` or `mix.copyDirectory()` on any directories that have a `.` somewhere in the filepath. Note that directly copying individual files works just fine, regardless of any dots in directory names. Below is my `webpack.mix.js` (trimmed down for brevity):
> 
> 
> 
> ```
> 
> const mix = require('laravel-mix');
> 
> 
> 
> /*
> 
>  |--------------------------------------------------------------------------
> 
>  | Mix Asset Management
> 
>  |--------------------------------------------------------------------------
> 
>  |
> 
>  | Mix provides a clean, fluent API for defining some Webpack build steps
> 
>  | for your Laravel application. By default, we are compiling the Sass
> 
>  | file for the application as well as bundling up all the JS files.
> 
>  |
> 
>  */
> 
> 
> 
> // Copying files directly works with no issues
> 
> mix.copy('node_modules/vue-multiselect/dist/vue-multiselect.min.css', 'public/css/vue-multiselect/dist/vue-multiselect.min.css');
> 
> 
> 
> // X-Editable
> 
> mix.copy("node_modules/x-editable/dist/jqueryui-editable/js/jqueryui-editable.min.js", "public/node_modules/x-editable/dist/jqueryui-editable/js/jqueryui-editable.min.js");
> 
> 
> 
> // AG Grid
> 
> mix.copyDirectory('node_modules/ag-grid-community', 'public/node_modules/ag-grid-community');
> 
> mix.copyDirectory('node_modules/ag-grid-enterprise', 'public/node_modules/ag-grid-enterprise');
> 
> 
> 
> // DataTables
> 
> // These appear to be the offending lines. Note that renaming the source directory to
> 
> // `datatables_net`/`datatables_net-zf` gets around the issue, but this is not a practical
> 
> // or scalable solution.
> 
> mix.copyDirectory("node_modules/datatables.net", "public/node_modules/datatables.net");
> 
> mix.copyDirectory("node_modules/datatables.net-zf", "public/node_modules/datatables.net-zf");
> 
> 
> 
> ```

Thanks your “dots in file name” solved my problem at the moment. This should be in doc.

**Comment by voyula** [comment]
same issue.

**Comment by llgreg** [comment]
Still happening

**Comment by RomuloLim** [comment]
same issue.
