### ISSUE TITLE
What is happening with TailwindCSS SASS

### ISSUE THREAD

**Issue by mike-a** [JeffreyWay/laravel-mix#2322]
TailwindCSS installation for Laravel-mix states:  

> _Note for Sass users: Due to an unresolved issue with one of Mix's dependencies, to use Sass with Tailwind you'll need to disable processCssUrls._

Is this fixed?

**Comment by reed-jones** [comment]
It is not

**Comment by RahulDey12** [comment]
How Long It can takes upto
