### ISSUE TITLE
Slow performance and/or hanging when running `npm run dev` or `npm run production` inside Docker container when sass files include absolute paths to image files instead of relative

### ISSUE THREAD

**Issue by scottjs** [JeffreyWay/laravel-mix#2325]
-   Laravel Mix Version: 4.1.4 (`npm list --depth=0`)
-   Node Version (`node -v`): v10.19.0
-   NPM Version (`npm -v`): 6.13.4
-   OS: Debian 10.2 (Docker: `FROM php:7.3-fpm`)

### Description:

A strange issue I've just started noticing since upgrading to Laravel Mix 4.1 (from 4.0) is that now `npm run dev` and `npm run production` hangs at around 11% when running these commands inside of the Docker container when the code is mapped via shared volumes. 

When it hangs I can hear my CPU fans spinning up to full and just stays there.

This problem goes away if I do the following: 
- Disable shared volumes in Docker, or exclude the folders where the images are referenced in CSS, e.g. exclude the `public/imgs` directory where the sass images are pointed to
- Downgrade back to Laravel Mix 4.0
- Run the commands on the host machine
- Remove absolute references to images and use relative instead, e.g. `../../public/img/my-image.png` instead of `/img/my-image.png`
- Set `.options({ processCssUrls: false });` in `webpack.mix.js` as per the solution to  [this issue](https://github.com/JeffreyWay/laravel-mix/issues/49), which is my chosen solution for now although not ideal. 

None of these options are ideal for our team/project as it means making some changes to an existing project and our team's workflow that was working just fine on Laravel Mix 4.0. 

I'm just creating this issue to share some of my findings here just in case others come across the same issue, however it would be good to know what has changed between Laravel Mix 4.0 and 4.1 and if anybody knows of any other solutions that might help? 

### Steps To Reproduce:

1. Setup Laravel in a Docker environment, I'm using Docker Compose. 
2. Setup a Docker shared volume to map the code into the container, e.g. `.:/var/www/html`
3. Create some sass with images set up using absolute paths rather than relative e.g. `../../public/img/my-image.png` instead of `/img/my-image.png`
4. Run `npm run dev` inside of the container (npm/node) will need to be installed/available

If I get some time later I will try to share an example project.

**Comment by beamsies** [comment]
@scottjs Did you ever find a solution? I'm experiencing the same.

**Comment by scottjs** [comment]
> @scottjs Did you ever find a solution? I'm experiencing the same.

We ended up setting the `processCssUrls: false` option in `webpack.mix.js` mentioned above, doesn't seem to have caused any further issues for us.
