### ISSUE TITLE
laravel mix with browserSync and websockets

### ISSUE THREAD

**Issue by martijnimhoff** [JeffreyWay/laravel-mix#2333]
-   Laravel Mix Version: 4.1.4
-   Node Version: v11.15.0
-   NPM Version: 6.7.0
-   OS: Ubuntu 18.04
-   Websocket implementation: beyondcode/laravel-websockets: 1.3.0

### Description:

I'm trying to get hot reloading to work while I have a websocket implementation (in the application itself, not the browserSync sockets implementation). I need some way to proxy the websockets back and forth. Currently the websocket is trying to connect on localhost:6001. However my application is running on local domain: `project.dev`. So this needs to be proxied to ws://project.dev:6001. I've already found this option:
```
  mix.browserSync({
    proxy: {
      target: 'http://project.dev',
      ws: true
    },
    port: 3000,
  });
```
However that does not work. (I mean the `ws` option).

Anyone any ideas?

**Comment by reed-jones** [comment]
Might not be the solution you are looking for, but have you tried not using browsersync at all, and instead `npm run hot` ?
