### ISSUE TITLE
 Error: Can't resolve 'ree-validate'

### ISSUE THREAD

**Issue by b0nb0n** [JeffreyWay/laravel-mix#2336]
-   Laravel Mix Version: laravel-mix@4.1.4
-   Node Versionv 8.10.0
-   NPM Version 3.5.2
-   OS: Ubuntu

### Steps To Reproduce:

Hi,

When I try to compile via npm run watch, I've theses erros:

ERROR in ./resources/js/modules/article/pages/add/Page.js
Module not found: Error: Can't resolve 'ree-validate' in '/var/www/laravel-react/resources/js/modules/article/pages/add'
 @ ./resources/js/modules/article/pages/add/Page.js 32:0-39 47:26-37
 @ ./resources/js/modules/article/pages/add/index.js
 @ ./resources/js/modules/article/routes.js
 @ ./resources/js/routes/routes.js
 @ ./resources/js/routes/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/modules/article/pages/edit/Page.js
Module not found: Error: Can't resolve 'ree-validate' in '/var/www/laravel-react/resources/js/modules/article/pages/edit'
 @ ./resources/js/modules/article/pages/edit/Page.js 32:0-39 47:26-37
 @ ./resources/js/modules/article/pages/edit/index.js
 @ ./resources/js/modules/article/routes.js
 @ ./resources/js/routes/routes.js
 @ ./resources/js/routes/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/modules/auth/pages/login/Page.js
Module not found: Error: Can't resolve 'ree-validate' in '/var/www/laravel-react/resources/js/modules/auth/pages/login'
 @ ./resources/js/modules/auth/pages/login/Page.js 32:0-39 49:26-37
 @ ./resources/js/modules/auth/pages/login/index.js
 @ ./resources/js/modules/auth/routes.js
 @ ./resources/js/routes/routes.js
 @ ./resources/js/routes/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/modules/auth/pages/register/Page.js
Module not found: Error: Can't resolve 'ree-validate' in '/var/www/laravel-react/resources/js/modules/auth/pages/register'
 @ ./resources/js/modules/auth/pages/register/Page.js 32:0-39 47:26-37
 @ ./resources/js/modules/auth/pages/register/index.js
 @ ./resources/js/modules/auth/routes.js
 @ ./resources/js/routes/routes.js
 @ ./resources/js/routes/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/modules/user/pages/edit/Page.js
Module not found: Error: Can't resolve 'ree-validate' in '/var/www/laravel-react/resources/js/modules/user/pages/edit'
 @ ./resources/js/modules/user/pages/edit/Page.js 32:0-39 47:26-37
 @ ./resources/js/modules/user/pages/edit/index.js
 @ ./resources/js/modules/user/routes.js
 @ ./resources/js/routes/routes.js
 @ ./resources/js/routes/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

I've tried few things:

- reinstall node_modules
- npm i ree-validate
- see package.json => ree-validate is OK

Everything is OK but the error still persists.

Do you have an idea ?

Thank's :)

**Comment by JosueMorales** [comment]
Hey! I just ran into the same issue.. it looks like there's an issue with the latest version of ree-validate (3.3.0)

I solved it installing the previous version (3.0.2) with the following command: 
`npm install --save ree-validate@3.0.2`

Hope that helps!
