### ISSUE TITLE
Display Image from Storage Folder in Laravel Mix - React

### ISSUE THREAD

**Issue by irshath1022im** [JeffreyWay/laravel-mix#2346]
I am using Laravel with React, the images are stored in :

storage\app\public\product_images

while I am using the
`<img src='\storage\app\public\product_images\sprintLogo.png' />
`
it is failed, no image shown,,,could u pls guide,

**Comment by shraoned** [comment]
Facing the same issue, please suggest a solution

**Comment by Isaac-Makawa** [comment]
//filesystems
public_path('video_thumbnail') => storage_path('app/video/thumbnail'),

//react component
<img src={`/video_thumbnail/${video.thumbnail}`} alt="thumbnail"/>
