### ISSUE TITLE
Accessing Dynamic values inside javascript files

### ISSUE THREAD

**Issue by MehdiAghighi** [JeffreyWay/laravel-mix#2352]
## Accessing dynammic values inside javascript files which is being complied by laravel mix

i am using mix.react() in my code to compile a jsx file like below:
```
import App from "./App"
ReactDOM.render(<App />, 
document.getElementById("app"))
```
here i have a problem, my App component uses something dynamic in it that should come from laravel.

i mean i wanna pass a prop to App component which is coming from laravel just like blade which we do this {{ var }}
and that should be something like below:
```
import App from "./App"
ReactDOM.render(<App data="{{data}}" />, 
document.getElementById("app"))
```
and i want "data" to come from laravel and database because it is going to render something dynamic in there which should come from the server

do you have any ideas ?!

**Comment by iastate-zuo** [comment]
I don't believe it's possible right now. 

If I'm understanding the source code correctly, invoking `mix.react` is basically saying "compile my react app and serve the build files from the output", I think the blade template does not play magic here -- it's just going to serve the react build files, by replacing the mix call with the url to the location of the build files.

This means that when serving the React application, the framework is not going to pull the build files and inline the scripts in the template (which is a preferred strategy as the build files could be too large to fit into the initial loading page). Hence there is no way to parse and inline the data from the template.

Lacking the ability to inline data is a common short fall for almost all server platforms except NodeJS, which has the ability to perform server rendering. Nevertheless, there are a couple of work around you could try:

1. inline your data in the template, save the data to a global variable and retrieve the data on your application's entry point; however, if your data set is large, it could slow down the initial response, and your application data are going to be essentially in plain text in the HTML. 

2. add a script to prefetch data on parallel to the application, though you'd still need a mechanism to awake the application when data become available, or store data somewhere before the application's fully loaded, depending on which IO finishes first. 

3. similar to option 2, but invoke the prefetch inside your application, you could have more control on the initial rendering in this way, though the application could take longer for initial rendering as it has to wait for the data to arrive.

And there are a few tricky alternatives as well, like invoking server rendering with PHP's V8JS engine, but I won't recommend these approaches.
