### ISSUE TITLE
Multiple files with different processCssUrls value

### ISSUE THREAD

**Issue by mnabialek** [JeffreyWay/laravel-mix#2357]
-   Laravel Mix Version: 5.0.4
-   Node Version (`node -v`): 10.16.1
-   NPM Version (`npm -v`): 6.13.6
-   OS: MaxOS
### Description:

I'm not really sure if it's a bug or feature but it seems it's impossible to compile multiple SCSS files - when some of them have enabled processCssUrls and some of them don't

I have existing project which I would like to convert in TailwindCss but TailwindCss needs processCssUrls to be set to false but my other current files need it set to be to true.

### Steps To Reproduce:

When running code like this `app.scss` will still use processCssUrls as it was set to `false`

```
const tailwindcss = require('tailwindcss');

mix.sass('resources/sass/tailwind.scss', 'public/css')
    .options({
        processCssUrls: false,
        postCss: [ tailwindcss('./resources/tailwind.config.js') ],
    });

mix.sass('resources/sass/app.scss', 'public/css').options({
    processCssUrls: true,
}).version();
```

but when removing 

```
const tailwindcss = require('tailwindcss');

mix.sass('resources/sass/tailwind.scss', 'public/css')
    .options({
        processCssUrls: false,
        postCss: [ tailwindcss('./resources/tailwind.config.js') ],
    });

```

it compiles fine.

**Comment by proea** [comment]
is there such an opportunity?

**Comment by proea** [comment]
Any update ? :)

**Comment by proea** [comment]
still actual
