### ISSUE TITLE
npm run dev (the same with other commands) fail in Windows 10 subsystem bash.

### ISSUE THREAD

**Issue by ac1982** [JeffreyWay/laravel-mix#236]
- Laravel Version: 5.4.6
- PHP Version:7.1.1
- Database Driver & Version:MySQL 5.7
- Windows 10 V1607 with latest updates.
- Windows Subsystem Bash Ubuntu 14.04.
- Laravel-mix 0.5.16

### Description:
After upgrade to 5.4.6, fresh install project in windows 10 and with node 7.4 works fine. But npm in windows 10 subsystem bash fail with "95% emitting ERROR  Failed to compile with 3 errors"

### Steps To Reproduce:
1. Node 7.4 and npm 4.1.2 in windows 10 subsystem bash.
2. fresh install laravel 5.4.6.(in bash)
3. npm install.(in bash)
4. npm run production.(in bash)
```
npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "production"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @ production: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ production script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/Users/alexe/PhpstormProjects/fabtek/npm-debug.log
```
Also upload the log in detail.
[npm-debug.txt](https://github.com/laravel/framework/files/736975/npm-debug.txt)

There was a same issue opened in  https://github.com/laravel/framework/issues/17620

**Comment by adiachenko** [comment]
I don't use Bash on Windows, but `npm run dev` probably won't work anyways even if you get other issues under control as WSL doesn't have inotify support on a publicly released builds. Unless laravel-mix is a sole perpetrator and you don't get the same kind of issues with other webpack boilerplates it may be more productive to just wait until Windows 10 Creators Update. They seem to have fixed ton of issues on a newer builds.

**Comment by JVMartin** [comment]
I've seen this error before.  Pretty sure this will fix it:
```bash
sudo ln -s /usr/bin/nodejs /usr/bin/node
```

**Comment by ac1982** [comment]
@JVMartin, I installed Node.js via package manager. So, `node` could be called without make soft link. 
So, it is not the case of node command name here.

**Comment by ssuhat** [comment]
+1 happen to me on windows 10 system.

**Comment by lszymkowiak** [comment]
Same here, happens only when referring to files from node_modules:

```
node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
ERROR  Failed to compile with 3 errors

error  in ./resources/assets/backend/less/app.less

Module build failed: Can't resolve './node_modules/font-awesome/less/font-awesome.less'
```

**Comment by Yuant-tobing** [comment]
If you get an error message when you run the command : **`npm install`** or `**npm run dev**` on laravel v5.4.*  project. *, please follow the steps below :

make sure your nodejs version v6. * and npm v4. *

1 command: $ `npm rebuild`
2 commands: $ `npm install` {not excluding --no-bin-link}
3 command: $ `npm run dev`

everything will go well and I have tried on laravel v.5.4 project. I hope, this solution can help you and others.

**Comment by mostafa6765** [comment]
![ice_screenshot_20170308-040152](https://cloud.githubusercontent.com/assets/17185462/23680271/c9eaf9e2-03b4-11e7-9939-bd94c04e7855.png)
How can solve this mix

**Comment by acornx9** [comment]
**@mostafa6765:** I had the same problems on Windows 10 with Laragon. 
The path in your **packages.json** is wrong for cross-env.js. By paths for the npm commands are like this:

dev": "node node_modules/cross-env/bin/cross-env.js...

BUT cross-env is actually in node_modules/cross-env/**dist**/bin/

Edit your **packages.json** so it looks like the screenshot I've include and try again. It works fine after you have fixed your paths.

![image](https://cloud.githubusercontent.com/assets/26564689/24135397/c2a3d462-0dc6-11e7-938d-370835c2c1e7.png)

**Comment by ismailzafar** [comment]
Thanks @Yuant-tobing your solution works for me.

**Comment by poorya6868** [comment]
![capwwture](https://cloud.githubusercontent.com/assets/24212660/26441884/951a6f6a-4147-11e7-8d0c-1a57f12b139f.PNG)
             

how can solve this??

**Comment by ruchern** [comment]
@poorya6868 See below. You do not have the `dev` scripts in `package.json`

```json
"scripts": {
    "dev": "xxx"
}
```
