### ISSUE TITLE
Dynamic Import (chunk) specific vendor?

### ISSUE THREAD

**Issue by MovingGifts** [JeffreyWay/laravel-mix#2362]
In a Laravel/React app, we were able to get dynamic imports (chunking) to work on a component level, which removes the component from the `app.js` bundle.

The dynamically imported component had a heavy 3rd party library being imported into it. The issue is that the heavy 3rd party library (which does not do tree shaking) ends up in the `vendor.js` bundle when we use `mix.extract()` which is logical.

We want to dynamically import (chunk) the 3rd party library to only get pulled in when the react view that needs it is loaded for the user, so it is not included in the `vendor.js` by default.

Any idea how to accomplish this?

**Comment by chris-hud** [comment]
Working through a similar problem. One specific vendor file is necessary, but is 1mb alone. It will be used ~1% of the time, and I would like to only load it when that specific component loads.

**Comment by MovingGifts** [comment]
@JeffreyWay any idea how to accomplish this?

**Comment by walidbagh** [comment]
any idea about this ?
