### ISSUE TITLE
mix-manifest loses hash after copying

### ISSUE THREAD

**Issue by josegus** [JeffreyWay/laravel-mix#2365]
-   Laravel Mix Version: 5.0.4 (`npm list --depth=0`)
-   Node Version v12.16.0:
-   NPM Version 6.13.4:
-   OS: Ubuntu 19.04

### Description:

When trying to build for production, if there's a copy directory and version. The copied file mix-manifest.json loses the generated file hash. The original compiled assets has the file hash.

This happens whenever I run watch, watch-poll, dev or prod.

### Steps To Reproduce:

webpack.mix.js
```
mix.js("resources/assets/js/app.js", "public/js")
	.sass("resources/assets/sass/app.scss", "public/css")
	.copy("public", "public-test")
	.version();
```

Run "npm run {watch|watch-poll|dev|prod}"

**Comment by ycs77** [comment]
+1

**Comment by ycs77** [comment]
@josegus Force run Laravel Mix copy file method to fix it

```js
// ...

mix.version().then(() => {
  // Run Laravel Mix copy file method
  new (require('laravel-mix/src/tasks/CopyFilesTask'))({
    from: 'public',
    to: new File('../other-public-folder')
  }).run();
})
```
