### ISSUE TITLE
workbox-webpack-plugin service worker installation error and mix.js PrecacheRoute url

### ISSUE THREAD

**Issue by hengsoo** [JeffreyWay/laravel-mix#2378]
I have been trying to implement PWA to my website recently using `workbox-webpack-plugin` and `laravel-mix-workbox` extension. I generate the service-worker.js by running `npm run watch`, sadly on the chrome console my website always shows _Service worker installation failed._ and some urls errors.

`laravel-mix-workbox` extension link:
https://github.com/speniti/laravel-mix-workbox

**Mix version:** 5.0.1
**laravel-mix-workbox:** 0.1.2
**workbox-webpack-plugin:** 5.1.2

**Steps to reproduce:**
**My webpack.mix.js**
```
const mix = require('laravel-mix');

require('laravel-mix-workbox');

mix.webpackConfig({
    output: { publicPath: '' }
});

mix.sass('resources/sass/style.scss', 'public/css/style.css')
   .copy('resources/js/lib/jquery-3.4.1.min.js', 'public/js/jquery.min.js')
   .copy('resources/js/lib/popper.min.js', 'public/js/popper.min.js')
   .copy('resources/js/lib/bootstrap.min.js', 'public/js/bootstrap.min.js')
   .copy('resources/js/plugins/owl-carousel/owl.carousel.min.js', 'public/js/owl.carousel.min.js')
   .scripts('resources/js/base.js', 'public/js/base.js')
   .version()
   .generateSW()
   .browserSync('http://mysite.com');
```

**In base.js, my code to initialize the service-worker**
```
if ('serviceWorker' in navigator) {
    // Use the window load event to keep the page load performant
    window.addEventListener('load', () => {
        navigator.serviceWorker.register('/service-worker.js');
    });
}
```

**The generated service-worker.js  precacheAndRoute consists the following code:**
```
  workbox.precacheAndRoute([{
    "url": "/css/style.css",
    "revision": "4438f0a3d7e94b76b0db59c779a74c63"
  }, {
    "url": "images/owl.video.play.png?4a37f8008959c75f619bf0a3a4e2d7a2",
    "revision": "4a37f8008959c75f619bf0a3a4e2d7a2"
  }, {
    "url": "mix.js",
    "revision": "d05d9cea142aa75e593f8735cb53a473"
  }], {});

});
```
The urls generated didn't follow my mix file and I can't find any resources online that explain why this happened. I have also tried not using the `laravel-mix-workbox` extension, and configure workbox directly through mix.webpackConfig's plugins, but it produces the same result as above.

**Comment by daquadra** [comment]
@hengsoo, did you resolve this issue?

**Comment by uacode** [comment]
```
exclude: [
                /\.(?:png|jpg|jpeg|svg)$/,
                'mix.js'
            ],
```
