### ISSUE TITLE
Comments in .env variable declarations is being read 

### ISSUE THREAD

**Issue by juliomotol** [JeffreyWay/laravel-mix#2379]
-   Laravel Mix Version: 5.0.1 (`npm list --depth=0`)
-   Node Version (`node -v`): 8.9.4
-   NPM Version (`npm -v`): 5.6.0
-   OS: Windows 10

### Description:

Comments in .env variable declarations is being read.

### Steps To Reproduce:

In our `.env`, we have an `ASSET_URL` that has a commented variable for our local development. From time to time, we uncomment this just to check if things are working well with our cdn.

```
ASSET_URL=#https://some.cdn-provider.net

MIX_ASSET_URL=${ASSET_URL}
```

In Laravel, the `ASSET_URL` is blank but when using `process.env.MIX_ASSET_URL` the `#https://some.cdn-provider.net` appears on the compiled scripts. It would be great if it had the same behavior with Laravel

**Comment by FeBe95** [comment]
This seems to be an issue with the `dotenv` package that is being used here. Laravel Mix is using an old version of `dotenv` which treated inline comments to be part of the value itself. 
https://github.com/laravel-mix/laravel-mix/blob/b116bf064a7aa60dcc05cc9a03edbe9eb3a3ae2f/package.json#L65
This has changed from `dotenv` version `15.x` on:
> Comments begin where a # exists, so if your value contains a # please wrap it in quotes. This is a breaking change from >= v15.0.0 and on.

see: https://github.com/motdotla/dotenv?tab=readme-ov-file#comments
