### ISSUE TITLE
Copying Files, flatten = false

### ISSUE THREAD

**Issue by iemir** [JeffreyWay/laravel-mix#238]
Issue when tried to use flatten = false

<img width="810" alt="screen shot 2017-01-30 at 1 47 27 pm" src="https://cloud.githubusercontent.com/assets/4745772/22434538/c69fef86-e71c-11e6-9f90-102f6f1addff.png">

**Comment by JeffreyWay** [comment]
Not sure why you're getting that, but just do:

```
mix.copy('./resources/assets/icons/, 'public', false);
```
