### ISSUE TITLE
How to use on demand components from ElementUi with laravel-mix?

### ISSUE THREAD

**Issue by iwasherefirst2** [JeffreyWay/laravel-mix#2381]
-   Laravel Mix Version: 5.0.4
-   Node Version: v13.5.0
-   NPM Version: 6.13.4
-   OS: Ubutnu 18.04

### Description:

I would like to use single components from ElementUi. In their docs they explain how to either get the full bundle, or only on demand components. 

Thats how to get the full bundle :

```
// content of app.vue
import Vue from 'vue';
import Element from 'element-ui';
import 'element-ui/lib/theme-chalk/index.css';

Vue.use(Element)

const app = new Vue({
    el: '#app'
});
```
To only get demanded components, one has to add a configuration to `.babelrc` as described [here](https://element.eleme.io/#/en-US/component/quickstart#on-demand) and change `app.vue` to:

```
import Vue from 'vue';
import { Button, Select } from 'element-ui';

Vue.use(Button)
Vue.use(Select)


new Vue({
  el: '#app'
});
```
I don't know how I can apply the changes to `.babelrc` with `laravel-mix`. Just using the above code without applying the changes to `.babelrc` won't change the file size when compared to the full bundle.

Is is possible to use demand components from ElementUi with laravel-mix? If so, how do I add the changes to babelrc?

### Steps To Reproduce:
1. Install Laravel-mix as standalone application as explained [here](https://laravel-mix.com/docs/5.0/installation#stand-alone-project).

2. Use any of the both scripts for `app.vue` (they both give the same output, thats the problem :) )

3. Use this for `webpack.mix.js` 

```
let mix = require('laravel-mix');

 mix.webpackConfig({
   externals: {
    vue: 'Vue'
  }
 });

 mix.options({
   extractVueStyles: 'dist/components.css',
 });

mix.js('src/app.js', 'dist/');
```

4. `npm run prod` will return same file size for full bundle and for only using 2 components (685 kb)

**Comment by bugsmonitor** [comment]
This is my babel config from webpack.mix.js file:

```js
mix.babelConfig({
  plugins: [
    '@babel/plugin-syntax-dynamic-import',
    [
      'component',
      {
        libraryName: 'element-ui',
        style: false
        // 'styleLibraryName': 'theme-chalk'
      }
    ]
  ]
})
```
style: false because I use import in my .scss file.
