### ISSUE TITLE
Call on undefined (extract-text-webpack-plugin). Chain for .scss compilation

### ISSUE THREAD

**Issue by antonstsk** [JeffreyWay/laravel-mix#2388]
-   Laravel Mix Version: 5.0.4
-   Node Version (8.16.2):
-   NPM Version (6.14.4):
-   MacOS Catalina

### Description:
Guys does anyone had same issue? Can't compile SCSS while hot server is running.
Some of the loaders gives wrong output I guess.
Only happens with hot command.

### Steps To Reproduce:
```javascript
const mix = require('laravel-mix');
const glob = require('glob');
const path = require('path');

const ENTRIES_DIR = './assets/modules';
const DIST_DIR = './public';

if (mix.inProduction()) {
    // Enabling source maps with default settings
    mix.sourceMaps();

    // Versioning in filename instead of query parameter
    require('laravel-mix-versionhash');
    mix.versionHash(); // IMPORTANT: Doesn't work with BrowserSync

    // Concatenates all used node_modules to vendor.js
    mix.extract();
} else {
    mix.webpackConfig({ devtool: 'inline-source-map' })
}

// Helpers
const getEntryName = fileName => path.basename(path.dirname(path.dirname(fileName)));
const makeSass = fileName => mix.sass(fileName, `${DIST_DIR}/css/${getEntryName(fileName)}.css`);
const makeJs = fileName => mix.js(fileName, `${DIST_DIR}/js/${getEntryName(fileName)}.js`);

// Processing
glob.sync(`${ENTRIES_DIR}/*/styles/index.s*ss`).forEach(makeSass);
glob.sync(`${ENTRIES_DIR}/*/scripts/index.js`).forEach(makeJs);
```

### Console error:
![image](https://user-images.githubusercontent.com/33395021/80735328-d35c4a80-8b10-11ea-8d60-88994abdba1d.png)

**Comment by orckid-lab** [comment]
Yes having the same issue but not sure how to override mix so that it doesn't use the extract-text-webpack-plugin. I believe this is related https://github.com/webpack/webpack/issues/6094#issuecomment-618235590

**Comment by antonstsk** [comment]
@orckid-lab thanks for your answer. I've already switched to [webpack-encore](https://github.com/symfony/webpack-encore)
