### ISSUE TITLE
Question: what is the status of supporing of dynamic important

### ISSUE THREAD

**Issue by lptn** [JeffreyWay/laravel-mix#2395]
I found this acrtile: https://laravel-news.com/using-dynamic-imports-with-laravel-mix

Seems it was implmented in Laravel Mix 4.0.16, current version is 5.0.4

This is what [docs for v5.0 says](https://laravel-mix.com/docs/5.0/upgrade):
>If your project heavily uses JavaScript dynamic imports, you may need to hold off until the release of webpack 5 early next year. There are known compile issues related to this that we cannot fix until then. Once webpack 5 is out, Mix will be updated shortly after. If you're unfamiliar with dynamic imports, then this very likely won't affect your project.

the same says [docs for v 4.1](https://laravel-mix.com/docs/4.1/upgrade) and even [docs for v 4.1](https://laravel-mix.com/docs/4.0/upgrade)

What is the latest vesion of mix that supports this feature?

**Comment by msonowal** [comment]
@lptn 
It was last 4.0 afair
as jeffery says waiting for webpack 5 to be released

**Comment by lptn** [comment]
thanks @msonowal 
PS: webpack 5 in beta now: https://github.com/webpack/webpack/releases
