### ISSUE TITLE
BrowserSync how to watch controllers/blade files in other directories ?

### ISSUE THREAD

**Issue by jbiancovns** [JeffreyWay/laravel-mix#2397]
By default mix watch for controllers files in the app/Http folder and blades files of resources/ views and triggers BrowserSync reload hook, but I need to also watch for changes on others directories that are not in the default installation of the framework like a package directory. 

Example:

root
- app
- bootstrap
- config
- database
- packages **<-- new directory to watch** 
- public
- resources
- routes
- storage
- tests

Thx

**Comment by nmfzone** [comment]
I think this is not an issue. It's a question, then you may use Stackoverflow for that.
