### ISSUE TITLE
BrowserSync file changes not being detected and injected - glob issue?

### ISSUE THREAD

**Issue by noahcostello** [JeffreyWay/laravel-mix#2409]
-   Laravel Mix Version: 5.0.4
-   Node Version (`node -v`): v12.17.0
-   NPM Version (`npm -v`): 6.14.4
-   OS: macOS Catalina 10.15.4

### Steps To Reproduce:

1. Follow the standalone project setup steps at https://laravel-mix.com/docs/5.0/installation#stand-alone-project

2. Update your webpack.mix.js file to use browsersync and point to a directory with css files like so:
```
let mix = require('laravel-mix');

mix.browserSync('mydevsite.test')
```
No file changes detected

3. Add file path with glob wildcard
```
mix.browserSync({
    proxy: 'devsiteurl.test',
    files: [
      "web/**/*.css"
    ]
  })
```
Still no file changes are detected.

4. Watch a specific file
```
mix.browserSync({
    proxy: 'devsiteurl.test',
    files: [
      "web/css/app.css"
    ]
  })
```
Change to this specific file is detected and injected

5. Watch the entire directory
```
mix.browserSync({
    proxy: 'devsiteurl.test',
    files: [
      "web"
    ]
  })
```
Change to files in the directory are detected and injected

**Other Details**

When going through the setup steps from the mix docs, I noticed the following npm warnings. It seems there are some unsupported packages for the current node version. Possibly related?

```
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.17.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN browser-sync-webpack-plugin@2.0.1 requires a peer of webpack@^1 || ^2 || ^3 but none is installed. You must install peer dependencies yourself.
```

**Comment by jeffwhitfield** [comment]
I'm running into this too. Not getting any error though on NPM packages. But, yeah, have to add the files option and glob wildcards don't work. I'm currently just specifying the directories I want to watch...which works but it's not ideal. There are likely to be situations where I want to avoid watching certain file types and not others for a given directory. Globs are what allows for that.

**Comment by kbav** [comment]
I can also confirm this. BrowserSync only works on proxy watches if I specifically identify the specific files / directories to watch, rather than use a glob pattern.

**Comment by rasmuscnielsen** [comment]
Just a note aside for someone else that might find this issue with no clue what the issue might be: 

I found that having the project folder located inside a Google Drive synced folder was causing my BrowserSync not to pick up on file changes (Mac). As soon as I moved the project folder it worked as a charm.

Hope this might help someone else!
