### ISSUE TITLE
mix.sass does not allow glob params

### ISSUE THREAD

**Issue by paper9oll** [JeffreyWay/laravel-mix#241]
webpack.mix.js

```
mix.sass('resources/assets/styles/**/*.scss', 'public/styles')
```

Let's say I have 2 files:
```
resources/assets/styles/app.scss
resources/assets/styles/content/content.scss
```

when I run the `npm run dev` it compile the `scss` into `css` and "copies" them to `public` directory:

```
public/styles/app.css
public/styles/content/content.css
```

**Comment by JeffreyWay** [comment]
Right - you need to be specific with your Sass entry point. 

Generally, you'll have a single app.scss entry, and that file will import any other .scss files/partials it needs.

**Comment by paper9oll** [comment]
Hi thanks for the reply.

Say i got multiple scss files like 20+ for individual pages, does that means i have to declare mix.sass for every single one of scss files?

**Comment by zacksmash** [comment]
@paper9oll No, you would have a `main.scss` file which you would add your `@import` statements to

main.scss
``` 
@import '_file.scss';
@import '_file2.scss';
@import '_file3.scss';
...
```

Then, in your `web pack.mix.js` file, you would run `mix.sass('path/to/main.scss', 'public/path')` or `mix.standaloneSass('path/to/main.scss' 'public/path')`, which is a tiny bit faster.

**Comment by zacksmash** [comment]
@paper9oll I've actually come up with a Sass globbing solution. 

So, here's what I did and it works pretty well.

Install the import-glob-loader module

`npm install import-glob-loader --save-dev`

Then, in your `webpack.mix.js` file add this:

```
// Add Sass globbing
mix.webpackConfig({
  {
    module: {
      preloaders: [{
        test: /\.scss/,
        loader: 'import-glob-loader'
      }]
    }
  }
})
```

You should now be able to do things like `@import 'folder/*';` in your main.scss file. Let me know if that works!

**Comment by maxfenton** [comment]
Is there a way in that `main.scss` to use globbing like `@import 'components/*.scss'` ?

**Comment by jethro-2018** [comment]
It would be great if we could do this.
