### ISSUE TITLE
Split css by vue components

### ISSUE THREAD

**Issue by sokolovdm** [JeffreyWay/laravel-mix#2414]
-   Laravel Mix Version: 4.1.4
-   Node Version: 12.6.1
-   NPM Version: 6.13.4
-   OS: macOS 10.15.4

Hello
I am importing css files inside tag `<style>` in every vue components and then webpack includes them in tag `<head>`.
Problem: Now in head i get all styles from all components, even if they are not on the page.
Is it possible to get only exactly needed styles?

Thanks.

**Comment by Wiejeben** [comment]
You can use the `extractVueStyles ` option for that. https://laravel-mix.com/docs/5.0/options

**Comment by sokolovdm** [comment]
extractVueStyles: true - delete all styles from head

**Comment by elambro** [comment]
@sokolovdm Did you find a solution for this?
