### ISSUE TITLE
Sass Include Path Not Working With Symlink

### ISSUE THREAD

**Issue by vrushank** [JeffreyWay/laravel-mix#2420]
-   Laravel Mix Version: 4.1.4 (`npm list --depth=0`)
-   Node Version (`node -v`): v12.16.2
-   NPM Version (`npm -v`): 6.14.4
-   OS: MacOS 10.15.4

### Description: 
I have following structure of my project where I want to have a common folder for scss files in html project and just a symlink in other projects. Purpose behind this structure is to not copy sass folder each time I make change in HTML styles. 

- HTML
  - src
    - sass

- Laravel
  - resources
    - sass
      - base

- Angular
  - src
    - @core
      - sass
        - base

- React
  - src
    - @core
      - sass
        - base

- Vue
  - src
    - @core
      - sass
        - base

If I copy and paste the scss files from **HTML -> src -> sass** folder to **Laravel -> resources -> sass -> base** folder and then run **yard dev**, it compiles all the scss files and works perfectly.

Main thing is I have following import for bootstrap in scss file.
`@import "bootstrap/scss/functions";`

I have added **includePaths: ["node_modules"]** while compiling via gulp-sass

Now created symlink for HTML -> src -> sass to Laravel -> resrouces -> sass -> base, Angular -> src -> @core -> sass -> base, React -> src -> @core -> sass -> base, Vue -> src -> @core -> sass -> base

After creating symlink added **includePaths: ["node_modules"]** in all of those projects as well. All is working fine in HTML, Angular, React, Vue but not Laravel.

I have tried following with webpack.mix.js in order to compile using symlink but could not get any success. **app.scss** file has includes from **base** folder which is symlink folder.

`
const sassOptions = {
  precision: 5,
  includePaths: ["node_modules", "resources/assets/"]
};

mix.sass('resources/sass/app.sass', 'public/css'), sassOptions);
`

`
mix.webpackConfig({
  module: {
    rules: [
      {
        test: /\.(scss|sass)$/,
        use: [
          {
            loader: 'sass-loader',
            options: {
              includePaths: ['node-modules']
            }
          }
        ]
      }
    ]
  }
});
`

`
mix.webpackConfig(webpack => {
   return {
    plugins: [
      new webpack.LoaderOptionsPlugin({
        test: /\.s[ac]ss$/,
        options: {
          includePaths: [
            path.resolve(__dirname, './node_modules')
          ]
        }
      })
    ]
  };
});
`

I have applied all of above solutions without any success.

Please help me to implement symlink concept as I want to be in sync for all the scss files with all the project and don't want to copy scss files each time I make change in any project.

Any help is appreciated.

**Comment by ewertonvaz** [comment]
Hello, the only solution I found for this was changing the webpack.mix.js file and adding the full path for the scss source files , for example:

<code>mix.js('resources/js/app.js', 'public/js')
   .sass('/home/ewertonvaz/laravelapp/resources/sass/app.scss', 'public/css');
</code>

Note that if you are using Windows you have to delete drive letter reference and the path name must  be written with double slash.

**Comment by vrushank** [comment]
Hello ewertonvaz,

I will try this today and will get back to you with result.

**Comment by vrushank** [comment]
I just tried using absolute paths as per @ewertonvaz suggestion but still facing the same issue.

My below includes are not working
`@import "bootstrap/scss/functions";`

It shows this error: "Can't find stylesheet to import." it's not able to find in node modules even after adding include paths and making them absolute.

**Comment by tamaranga** [comment]
@vrushank Try to disable symlinks resolving in Webpack config:
```
mix.webpackConfig({
    resolve: {
        symlinks: false
    }
});
```

**Comment by vrushank** [comment]
@tamaranga I already tried it but didn't work.
