### ISSUE TITLE
It is possible to extract vendor from multiple files ?

### ISSUE THREAD

**Issue by shankhadevpadam** [JeffreyWay/laravel-mix#2422]
-   Laravel Mix Version: 5.0.1 (`npm list --depth=0`)
-   Node Version (`node -v`):13.14.0
-   NPM Version (`npm -v`):6.14.5
-   OS:

### Description:
Is it possible to extract the vendor from multiple files? I have multiple app.js files for each module and I want to extract the vendor like this.

```
mix.js('resources/js/admin/pages/user/user.js', 'public/js/admin/pages/user/').extract(['vue', 'jquery']);
mix.js('resources/js/admin/pages/role/role.js', 'public/js/admin/pages/role/').extract(['vue', 'jquery'];
mix.js('resources/js/admin/pages/product/product.js', 'public/js/admin/pages/product/').extract(['vue', 'jquery'];
```

**Comment by denjaland** [comment]
We compile more files for different versions of our website, and just have one .extract() call; each website has the vendors extracted, and we include the same vendor.js file in each of the theme templates.

You can just chain everything; at least that's how we do it, and it seems to be working fine (although I must admit anything webpack does will always be a bit of a blackbox to me...)

**Comment by robertotcestari** [comment]
This would be useful if we need to separate backend from frontend js.

**Comment by denjaland** [comment]
> This would be useful if we need to separate backend from frontend js.

What do you mean by that?  This is all frontend js?

**Comment by robertotcestari** [comment]
Sorry, i meant separate from user and admin pages 😬

Em qui, 18 de jun de 2020 14:22, David Heremans <notifications@github.com>
escreveu:

**Comment by groenroos** [comment]
Also looking for this functionality, to have multiple separate `vendor.js` outputs for the different parts of the app.

**Comment by G3z** [comment]
I'm still struggling with this :

My solution is to create 2 files `webpack.admin.mix.js` and `webpack.mix.js`

I also edited npm scripts like so
```
"development": "mix && mix --mix-config webpack.admin.mix",
"production": "mix --production && mix --mix-config webpack.admin.mix --production"
```
not very elegant but it works
