### ISSUE TITLE
Error running 'npm run dev'

### ISSUE THREAD

**Issue by sbc640964** [JeffreyWay/laravel-mix#2424]
-   Laravel Mix Version: 5.0.4
-   Node Version: 13.3.0:
-   NPM Version: 6.13.1:
-   OS: windows 10

The cmd screen:

> @ dev C:\xampp\htdocs\blog
> npm run development

> @ development C:\xampp\htdocs\blog
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

C:\xampp\htdocs\blog\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^

Error: Package exports for 'C:\xampp\htdocs\blog\node_modules\kleur' do not define a valid './colors' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:614:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (C:\xampp\htdocs\blog\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\xampp\htdocs\blog\node_modules\autoprefixer\lib\autoprefixer.js:9:13)
    at Module._compile (C:\xampp\htdocs\blog\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (C:\xampp\htdocs\blog\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at C:\xampp\htdocs\blog\node_modules\laravel-mix\src\components\Preprocessor.js:62:41
    at C:\xampp\htdocs\blog\node_modules\laravel-mix\src\components\Preprocessor.js:69:31
    at global.tap (C:\xampp\htdocs\blog\node_modules\laravel-mix\src\helpers.js:10:5)
    at C:\xampp\htdocs\blog\node_modules\laravel-mix\src\components\Preprocessor.js:27:13
    at Array.forEach (<anonymous>)
    at Sass.webpackRules (C:\xampp\htdocs\blog\node_modules\laravel-mix\src\components\Preprocessor.js:22:22)
    at ComponentFactory.applyRules (C:\xampp\htdocs\blog\node_modules\laravel-mix\src\components\ComponentFactory.js:155:23)
    at C:\xampp\htdocs\blog\node_modules\laravel-mix\src\components\ComponentFactory.js:66:48
    at C:\xampp\htdocs\blog\node_modules\laravel-mix\src\Dispatcher.js:34:47
    at Array.forEach (<anonymous>)
    at Dispatcher.fire (C:\xampp\htdocs\blog\node_modules\laravel-mix\src\Dispatcher.js:34:28)
    at Mix.dispatch (C:\xampp\htdocs\blog\node_modules\laravel-mix\src\Mix.js:118:25)
    at WebpackConfig.buildRules (C:\xampp\htdocs\blog\node_modules\laravel-mix\src\builder\WebpackConfig.js:90:13)
    at WebpackConfig.build (C:\xampp\htdocs\blog\node_modules\laravel-mix\src\builder\WebpackConfig.js:23:14)
    at Object.<anonymous> (C:\xampp\htdocs\blog\node_modules\laravel-mix\setup\webpack.config.js:29:38)
    at Module._compile (C:\xampp\htdocs\blog\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (C:\xampp\htdocs\blog\node_modules\v8-compile-cache\v8-compile-cache.js:161:20) {
  code: 'MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\פלש\AppData\Roaming\npm-cache\_logs\2020-06-21T10_45_49_481Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I deleted the package folder, cleaned up a cache, and reinstalled, nothing helped.

**Comment by leofusemind** [comment]
There's a related issue here: https://github.com/postcss/autoprefixer/issues/1328

**Comment by leofusemind** [comment]
I think this has been fixed as of today.

**Comment by miryamfv** [comment]
same error:
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/13.2.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'development'
1 verbose cli ]
2 info using npm@6.14.7
3 info using node@v13.2.0
4 verbose run-script [ 'predevelopment', 'development', 'postdevelopment' ]
5 info lifecycle @~predevelopment: @
6 info lifecycle @~development: @
7 verbose lifecycle @~development: unsafe-perm in lifecycle true
8 verbose lifecycle @~development: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/miryamfv/Proyectos/dz0/node_modul$
9 verbose lifecycle @~development: CWD: /Users/miryamfv/Proyectos/dz0
10 silly lifecycle @~development: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setu$
10 silly lifecycle ]
11 silly lifecycle @~development: Returned: code: 1  signal: null
12 info lifecycle @~development: Failed to exec development script
13 verbose stack Error: @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_module$
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1023:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:281:5)
14 verbose pkgid @
15 verbose cwd /Users/miryamfv/Proyectos/dz0
16 verbose Darwin 19.4.0
17 verbose argv "/usr/local/Cellar/node/13.2.0/bin/node" "/usr/local/bin/npm" "run" "development"
18 verbose node v13.2.0
19 verbose npm  v6.14.7
20 error code ELIFECYCLE
21 error errno 1`

**Comment by alex-kudrya** [comment]
Update Node to 14.7.0 to fix it

**Comment by jeyyuu** [comment]
I have the same problem, please help!
This is the log.

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\ACER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v13.6.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 info lifecycle @~dev: @
7 verbose lifecycle @~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @~dev: PATH: C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\wamp64\www\sirletwebsite\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\ACER\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Microsoft VS Code\bin;C:\composer;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files (x86)\Common Files\Ulead Systems\MPEG;C:\wamp64\bin\php\php7.4.14;C:\Users\ACER\AppData\Roaming\npm;C:\Program Files\nodejs;C:\Users\ACER\AppData\Roaming\Composer\vendor\bin;C:\Users\ACER\AppData\Local\GitHubDesktop\bin;C:\wamp64\bin\php\php7.4.14;C:\Users\ACER\AppData\Roaming\npm
9 verbose lifecycle @~dev: CWD: C:\wamp64\www\sirletwebsite
10 silly lifecycle @~dev: Args: [ '/d /s /c', 'npm run development' ]
11 silly lifecycle @~dev: Returned: code: 1  signal: null
12 info lifecycle @~dev: Failed to exec dev script
13 verbose stack Error: @ dev: `npm run development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @
15 verbose cwd C:\wamp64\www\sirletwebsite
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ACER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v13.6.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error @ dev: `npm run development`
22 error Exit status 1
23 error Failed at the @ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by shalaka-deshan0110** [comment]
I got this error installing new laravel 8 project

> mix

[webpack-cli] TypeError: compiler.plugin is not a function
    at BrowserSyncPlugin.apply (/home/.../node_modules/browser-sync-webpack-plugin/lib/BrowserSyncPlugin.js:22:12)
    at createCompiler (/home/.../node_modules/webpack/lib/webpack.js:69:12)
    at create (/home/.../node_modules/webpack/lib/webpack.js:113:15)
    at webpack (/home/.../node_modules/webpack/lib/webpack.js:121:46)
    at f (/home/.../node_modules/webpack/lib/index.js:37:15)
    at WebpackCLI.createCompiler (/home/.../node_modules/webpack-cli/lib/webpack-cli.js:1165:24)
    at async WebpackCLI.bundleCommand (/home/.../node_modules/webpack-cli/lib/webpack-cli.js:1292:20)
    at async Command.<anonymous> (/home/.../node_modules/webpack-cli/lib/webpack-cli.js:322:21)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/home/.../node_modules/webpack-cli/lib/webpack-cli.js:708:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `mix`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.../.npm/_logs/2021-01-19T05_31_16_999Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by mustafaxpp** [comment]
please, someone, help me 
![Capture](https://user-images.githubusercontent.com/59034013/107726930-e41e2b80-6cf2-11eb-80f5-68dc1f56d2d9.PNG)

**Comment by apolopena** [comment]
@JeffreyWay this issue does not seem to be resolved. Updating node does not fix it. I am getting the error on:

- **Node v14.16.0**
- **Ubuntu 20.04.2 LTS**

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/gitpod/.nvm/versions/node/v14.16.0/bin/node',
1 verbose cli   '/home/gitpod/.nvm/versions/node/v14.16.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'development'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.16.0
4 verbose run-script [ 'predevelopment', 'development', 'postdevelopment' ]
5 info lifecycle @~predevelopment: @
6 info lifecycle @~development: @
7 verbose lifecycle @~development: unsafe-perm in lifecycle true
8 verbose lifecycle @~development: PATH: /home/gitpod/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/workspace/gitpod-laravel8-starter/node_modules/.bin:/home/gitpod/.nvm/versions/node/v14.16.0/bin:/tmp/yarn--1616783743790-0.4004209842427078:/workspace/gitpod-laravel8-starter/node_modules/.bin:/home/gitpod/.config/yarn/link/node_modules/.bin:/home/gitpod/.yarn/bin:/home/gitpod/.nvm/versions/node/v14.16.0/libexec/lib/node_modules/npm/bin/node-gyp-bin:/home/gitpod/.nvm/versions/node/v14.16.0/lib/node_modules/npm/bin/node-gyp-bin:/home/gitpod/.nvm/versions/node/v14.16.0/bin/node_modules/npm/bin/node-gyp-bin:/home/gitpod/.sdkman/candidates/maven/current/bin:/home/gitpod/.sdkman/candidates/java/current/bin:/home/gitpod/.sdkman/candidates/gradle/current/bin:/home/gitpod/.rvm/gems/ruby-2.6.6/bin:/home/gitpod/.rvm/gems/ruby-2.6.6@global/bin:/home/gitpod/.rvm/rubies/ruby-2.6.6/bin:/home/gitpod/.pyenv/plugins/pyenv-virtualenv/shims:/home/gitpod/.pyenv/shims:/workspace/.cargo/bin:/workspace/.pip-modules/bin:/workspace/.rvm/bin:/ide/bin:/home/gitpod/.pyenv/bin:/home/gitpod/.pyenv/shims:/workspace/go/bin:/home/gitpod/go/bin:/home/gitpod/go-packages/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin/:/home/gitpod/.nvm/versions/node/v14.16.0/bin:/home/gitpod/.cargo/bin:/home/gitpod/.rvm/bin
9 verbose lifecycle @~development: CWD: /workspace/gitpod-laravel8-starter
10 silly lifecycle @~development: Args: [ '-c', 'mix' ]
11 silly lifecycle @~development: Returned: code: 1  signal: null
12 info lifecycle @~development: Failed to exec development script
13 verbose stack Error: @ development: `mix`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/gitpod/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/gitpod/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid @
15 verbose cwd /workspace/gitpod-laravel8-starter
16 verbose Linux 5.4.0-1024-gcp
17 verbose argv "/home/gitpod/.nvm/versions/node/v14.16.0/bin/node" "/home/gitpod/.nvm/versions/node/v14.16.0/bin/npm" "run" "development"
18 verbose node v14.16.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error @ development: `mix`
22 error Exit status 1
23 error Failed at the @ development script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
