### ISSUE TITLE
MIX_* .env variables not available in browser

### ISSUE THREAD

**Issue by dharkness** [JeffreyWay/laravel-mix#2425]
-   Laravel Mix Version: 5.0.4
-   Node Version: 13.12.0
-   NPM Version: 6.14.4
-   Yarn Version: 1.22.4
-   OS: Ubuntu 18.04.4

### Description:

I cannot access any `process.env` variables in my built `app.js` in Chrome, but I can see them in the `webpack.mix.js` build script.

### Steps To Reproduce:

1. Add `MIX_BASE_URL` variable to `.env`
1. Dump `process.env` to console in `webpack.mix.js`
1. Dump `process.env` to console in `app.js`
1. Run `php artisan config:clear`
1. Restart `yarn watch`
1. See list of variables including `MIX_BASE_URL` in the console (good)
1. See `{}` in DevTools (bad)

We created this project with Laravel 7.13.0 just a couple of weeks back.

**Comment by dharkness** [comment]
Here are the config and build script:

`webpack.config.js`
```
// This allows autocomplete and navigation in IDE.

module.exports = {
    resolve: {
        extensions: ['.js', '.css', '.scss'],
        alias: {
            '~': __dirname + '/resources/js',
            '^': __dirname + '/resources/sass',
        },
    },
};
```

`webpack.mix.js`
```
const mix = require('laravel-mix');
const config = require('./webpack.config');

// Externalized so IDE can parse it for import paths
mix.webpackConfig(config);

mix.babelConfig({
    plugins: [
        // allows fat-arrow syntax for class methods
        '@babel/plugin-proposal-class-properties',
        // allows ?. for accessing properties safely
        '@babel/plugin-proposal-nullish-coalescing-operator',
        // allows "export * as values from" syntax
        'transform-export-extensions',
    ],
});

mix.react('resources/js/index.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css');


// Environment-specific configuration

if (mix.inProduction()) {
    mix.version();
}
else {
    mix.browserSync('dealer-portal.test');
}
```

**Comment by kaphert** [comment]
@dharkness I experienced a similar thing but the variable does give a value when I append the variable name. I don't know if this expected behavior or a bug but maybe it helps you out. 

```
console.log(process.env); // returns {}
console.log(process.env.YOURVARIABLE); // does give the result
```

**Comment by dharkness** [comment]
@kaphert You are indeed correct; it works. I tried this originally
```
console.log('url', process.env.MIX_DWS_URL);
```
and got `undefined` so I switched it to `process.env` to see all the variables. I must have done the switch before running `php artisan config:clear` and borked it too early. Thank you so much.

**Comment by krushallochawala-kombee** [comment]
I have faced one issue , I have project on bitbucket and than we have migrated it to github and we are not able to fetch env variable from the .env file 

how can I fix this?

I am using vue 2 , laravel and webpack.mix
