### ISSUE TITLE
Running mix creates an empty app.css file and adds the app.scss as a chunk to the app.js file

### ISSUE THREAD

**Issue by davebolger** [JeffreyWay/laravel-mix#2434]
-  laravel-mix 5.0.4
-   Node Version: 12.18.2
-   NPM Version: 6.14.5
-   OS: OSX 

And also
-  laravel-mix 5.0.4
-  Node Version: 12.17.0
-  NPM Version: 6.14.4
-  OS: Ubuntu 18.04

### Description:
Running Laravel Mix on a fresh install of Laravel doesn't output anything to app.css file. 

```
Asset     Size   Chunks             Chunk Names
/css/app.css  0 bytes  /js/app  [emitted]  /js/app
/js/app.js  592 KiB  /js/app  [emitted]  /js/app
```
It appears that the sass file is included in a webpack chunk. 
```
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {
__webpack_require__(/*! /test/resources/js/app.js */"./resources/js/app.js");
module.exports = __webpack_require__(/*! //test/resources/sass/app.scss */"./resources/sass/app.scss");
```

webpack.mix.js
```
const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js')
  .sass('resources/sass/app.scss', 'public/css');
```

### Steps To Reproduce:
Create a new Laravel application 
```
laravel new test
```

Install node modules
```
npm install
```

Add css to resources/sass/app.scss
```
html {
  margin:0;
}
```

Run Laravel Mix
```
npm run dev
```

**Comment by herojhc** [comment]
I also have the problem when i use babel-plugin-syntax-dynamic-import

**Comment by yugen** [comment]
I'm having this problem, too, but only when trying to code-split for dynamic module loading.
when I register components like this
```
import MyComponent from './components/my_component';
vue.component('my-component', MyComponent);
```
My css compiles as expected, but when I register components like this
```
window.Vue.component('my-component', resolve => {
    import(/* webpackChunkName: "my-component" */ './components/my_component')
        .then(comp => {
            resolve(comp.default)
        })
})
```
my emitted app.css file is empty.

**Comment by wilsenhc** [comment]
I've been having this same problem for quite some time. 
There's already many threads about this issue but no fix yet. 
Check #2123

**Comment by JeffreyWay** [comment]
This was a known issue for Mix 5 that has been patched in the upcoming v6.
