### ISSUE TITLE
webpackConfig() plugins are merged before the default config

### ISSUE THREAD

**Issue by KaelWD** [JeffreyWay/laravel-mix#2439]
-   Laravel Mix Version: 5.0.3
-   Node Version (`node -v`): 12
-   NPM Version (`npm -v`): n/a
-   OS: n/a

### Description:

[vuetify-loader](https://github.com/vuetifyjs/vuetify-loader) expects to be initialised *after* vue-loader, but `mix.webpackConfig()` applies the user plugins first so VueLoaderPlugin fails due to the use of `oneOf` (https://github.com/vuetifyjs/vuetify-loader/issues/144)

### Steps To Reproduce:

* `laravel new test`
* `yarn add --dev vuetify vuetify-loader`
* Set webpack.mix.js to:
```js
const mix = require('laravel-mix');
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin');

mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .webpackConfig({
        plugins: [
            new VuetifyLoaderPlugin({
                options: {}
            }),
        ]
    });
```
* run `yarn dev`; it will fail

**Comment by tminich** [comment]
Try upgrading to the current version of mix (5.0.4 for me), I'm basically using the same setup and it works fine. If that's not it, try putting .webpackConfig first and see if that changes anything.

**Comment by KaelWD** [comment]
Are you using vuetify-loader? It needs to run after VueLoaderPlugin so we can use `oneOf`

**Comment by tminich** [comment]
Yes, but despite updating it seems I'm still on 1.5 which apparently doesn't have the issue.
But my final plugin list doesn't even include vue-loader, so Mix doesn't seem to inject it at all for me. Maybe check if it even is in your plugin list (I use Mix.listen('configReady', config => {}), perhaps you can just load it manually before vuetify-loader?

**Comment by KaelWD** [comment]
This mix extension should work: https://github.com/Nothing-Works/vuetifyjs-mix-extension

Or you can create your own:
```js
mix.extend('vuetify', new class {
    webpackConfig (config) {
        config.plugins.push(new VuetifyLoaderPlugin())
    }
})
```

**Comment by KaelWD** [comment]
The problem is that the vue extension uses `webpackConfig`: https://github.com/JeffreyWay/laravel-mix/blob/master/src/components/Vue.js

Given the following config we can see that `extension.webpackConfig` is called *after* `mix.webpackConfig` and `configReady`, in fact `mix.webpackConfig` is applied before any extensions. 
```js
mix.extend('extension', new class {
    webpackConfig (config) {
        console.log('extension webpackConfig')
    }
    webpackRules () {
        console.log('webpackRules')
    }
    webpackPlugins () {
        console.log('webpackPlugins')
    }
})

mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .extension()
    .webpackConfig(() => console.log('webpackConfig'))

Mix.listen('configReady', config => {
    console.log('configReady')
})
```

if `mix.webpackConfig` ran after all extensions and had access to the config object then this wouldn't be a problem.

**Comment by tminich** [comment]
Ok, that's bad. One could argue about .webpackConfig, but configReady definitely should run last (or there should be another trigger that does)

**Comment by jonnywilliamson** [comment]
Just bumping this as I'm having the exact same issue.

Had to use this as a work around: https://github.com/vuetifyjs/vuetify-loader/issues/144#issuecomment-659308887

Thanks @KaelWD
