### ISSUE TITLE
Support for VUE 3

### ISSUE THREAD

**Issue by pflirae** [JeffreyWay/laravel-mix#2440]
When it is planned to include VUE 3 support ??

**Comment by LaravelFreelancerNL** [comment]
With vuejs 3 hitting RC status this has become a very welcome improvement.

**Comment by mjb1431** [comment]
Agreed. Like like to hear a proposed timeline as well.

**Comment by Vac1911** [comment]
Update?

**Comment by mayanksdudakiya** [comment]
Any update, please?

**Comment by Masterbranch1** [comment]
Is there any update of VUE 3 support?

**Comment by rdarcy1** [comment]
Until support is added, you can use webpack directly:

```js
// webpack.config.js

const path = require('path');
const { VueLoaderPlugin } = require('vue-loader');

module.exports = (env = {}) => ({
    mode: env.prod ? 'production' : 'development',
    devtool: env.prod ? 'source-map' : 'eval-cheap-module-source-map',
    entry: [
        path.resolve(__dirname, './resources/js/app.ts'),
    ],
    output: {
        path: path.resolve(__dirname, './public/js'),
        filename: "app.js"
    },
    resolve: {
        alias: {
            '@': path.resolve(__dirname, './resources/js'),
        },
        extensions: ['.ts', '.js', '.vue'],
    },
    module: {
        rules: [
            {
                test: /\.vue$/,
                use: 'vue-loader'
            },
            {
                test: /\.ts$/,
                loader: 'ts-loader',
                options: {
                    appendTsSuffixTo: [/\.vue$/],
                }
            },
        ]
    },
    plugins: [
        new VueLoaderPlugin(),
    ],
});
```

Minimal Laravel config based on https://github.com/vuejs/vue-next-webpack-preview
Note this isn't transpiling for backwards compatibility.

Run with `webpack` or `npx webpack`

**Comment by KABBOUCHI** [comment]
@mayanksdudakiya and @Masterbranch1 you can use temporary this package https://github.com/KABBOUCHI/laravel-mix-vue3 until the official support is out.

**Comment by rrrrando** [comment]
This solution also works for me:

[https://stackoverflow.com/questions/63967346/install-vue-3-0-in-laravel/63994238#63994238](https://stackoverflow.com/questions/63967346/install-vue-3-0-in-laravel/63994238#63994238)

If you use inline template like i do then you have to switch to using slots since inline-template is deprecated.

**Comment by JeffreyWay** [comment]
Support is in Mix v6.
