### ISSUE TITLE
Remove global variables

### ISSUE THREAD

**Issue by thierry2015** [JeffreyWay/laravel-mix#2445]
-   Laravel Mix Version: 5.0.4 (`npm list --depth=0`)
-   Node Version (`node -v`): 14.5.0
-   NPM Version (`npm -v`): 6.14.5
-   OS: MacOS 10.14.6

### Description:

Laravel Mix is currently referencing global variables instead of exported ones from internal files.
This causes issues on advanced usages of Laravel Mix as a Webpack decorator instead of a standalone builder.

When we use it to create two configuration objects with two separate configurations (with different public paths, for instance), there are some glitches happening since all the plugins share the same global objects and references to them on Webpack/Mix events.

As a developer, I want to be able to use Laravel Mix as a Webpack decorator, in order to create a more opinionated and standardized bundler for the teams I am working with.

### Steps To Reproduce:

- Create a custom `webpack.config.js` and make sure that Webpack uses it instead of the Laravel Mix one.
- Loop over two different public paths to create multiple Webpack configuration objects and expose the result through `module.exports`.
- Inside the loop, flush all the `laravel-mix` module cache to make sure to reload a fresh instance of Laravel Mix instead of the singleton one.
- Make `Array.prototype.tap` configurable as Laravel Mix configures it without checking if it already exists (can be a different issue, but related to the same use case).
- Load `laravel-mix` main file (Api instance).
- Manually install the components through a fresh ComponentFactory (inline require).
- Configure a public path from the current iteration value.
- Add some entries in Laravel Mix Api, such as `.scss()` (make sure the entry exists and the proper dependencies are already installed).
- Dispatch `init` through the global Mix instance (should be from the manually required file instead IMO).
- Create a new WebpackConfig builder instance and build the configuration.
- Return the configuration in the `map` method.
- Run Webpack with the created file.
- Observe that the `mix.js` of the last public path was properly deleted, but not the first one, because the plugins shared the same `Config` global variable, which contains the configuration of the last iteration.
- Observe that the `mix-manifest.json` of the last public path was properly created, but not the first one, for the same reason.

Here is a working example of the `webpack.config.js` just described above

```javascript
// webpack.config.js
const publicPaths    = ['dist/first', 'dist/second'];
const laravelMixPath = require.resolve('laravel-mix').replace(/(?<module>.*\/node_modules\/laravel-mix).*/u, '$<module>');

const webpackConfig = publicPaths.map((publicPath) => {
	// Make sure we get a fresh Laravel Mix instance by deleting
	// all existing cached modules inside laravel-mix folder.
	Object.keys(require.cache).forEach((key) => {
		if (key.startsWith(laravelMixPath)) {
			delete require.cache[key];
		}
	});

	// Allow configuration of the `tap` method in the prototype of `Array`.
	Object.defineProperty(Array.prototype, 'tap', { configurable: true });

	// Load Laravel Mix bootstrapped Api.
	const mix = require('laravel-mix');

	// Install all components through a fresh ComponentFactory instance.
	const ComponentFactory = require('laravel-mix/src/components/ComponentFactory');
	new ComponentFactory().installAll();

	// Set the public path of the bundle and add a simple SCSS file entry.
	// .foo { color: #c0ffee; }
	mix
		.setPublicPath(publicPath)
		.sass('some/file.scss', 'app.css');

	// Dispatch the `init` event through global Mix variable.
	global.Mix.dispatch('init', Mix);

	// Load the WebpackConfig builder and return the build result.
	const WebpackConfigBuilder = require('laravel-mix/src/builder/WebpackConfig');

	return new WebpackConfigBuilder().build();
});


module.exports = webpackConfig;
```

Here is the executed command:
```
 node ./node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development ./node_modules/webpack/bin/webpack.js --config=./webpack.config.js --progress --hide-modules
```

Created files:
- dist/
  - first/
    - app.css
    - mix.js
  - second/
    - app.css
    - mix-manifest.json

I would be glad to make a PR, but I just want to make sure that's a step you are willing to take, first since it changes a bit the purpose and the global architecture, and would result in a breaking change, mostly for Laravel Mix plugins.

**Comment by thierry2015** [comment]
I would like to know if this is an improvment you guys think would be interesting to implement, before I go forward with a PR.

Thank you for your time, and I have to highlight that your package is a real game changer for a lot of developers where I am currently working

**Comment by JeffreyWay** [comment]
The globals aren't ideal, I agree. Mix was a tricky thing to build. 

But I can't introduce any change that breaks the plugin ecosystem. I think, for your needs, you should just use webpack directly.
