### ISSUE TITLE
npm run production hangs on shared hosting

### ISSUE THREAD

**Issue by hcphoon01** [JeffreyWay/laravel-mix#2447]
-   Laravel Mix Version: 5.0.4
-   Node Version (`node -v`): v14.6.0
-   NPM Version (`npm -v`): 6.14.6
-   OS: Linux

### Description:

I am trying to install my laravel app that has been cloned from git on my shared hosting server but when I try to run `npm run prod` or `npm run production` it just displays this in the terminal and then hangs.

```
> @ prod /home/user/laravelapp
> npm run production


> @ production /home/user/laravelapp
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
```

### Steps To Reproduce:

1. Run `npm run prod` right after running `npm install` on a fresh laravel install

**Comment by jEstevezRod** [comment]
I'm having this issue, anybody knows how to solve it?

**Comment by SchizoDuckie** [comment]
@jEstevezRod addding  `.disableNotifications()` as the first line in `webpack.mix.js` is what worked for me:
```
mix
    .disableNotifications()
    .options({processCssUrls: false})

    // Copy webfont files from /vendor directories to /public directory.
    .copy('vendor/fortawesome/font-awesome/fonts', 'public/build/fonts/font-awesome')
    .copy('vendor/twbs/bootstrap-sass/assets/fonts/bootstrap', 'public/build/fonts/bootstrap')
```
