### ISSUE TITLE
yarn run production "No command specified"

### ISSUE THREAD

**Issue by rickbolton** [JeffreyWay/laravel-mix#245]
<img width="1038" alt="screen shot 2017-01-31 at 10 04 16" src="https://cloud.githubusercontent.com/assets/10371256/22460420/b510580c-e79c-11e6-90fc-dbb87eb487ad.png">

I'm running into an issue when running the command 'yarn run production'

If you change the name e.g. changing production to anything else like "prod" or "production2" the command runs fine first time. It's possibly linked to this closed yarn issue (https://github.com/yarnpkg/yarn/issues/2009) 

Here are my node, npm and yarn versions:

<img width="215" alt="screen shot 2017-01-31 at 10 08 22" src="https://cloud.githubusercontent.com/assets/10371256/22460616/989421f8-e79d-11e6-8c17-89618ce1e88f.png">

To confirm npm run production works fine and yarn run dev, watch and hot work fine also

**Comment by adriaanzon** [comment]
Update Yarn

**Comment by rickbolton** [comment]
@adriaanzon That worked - Thank you! 😄
