### ISSUE TITLE
Problem with first load app.js

### ISSUE THREAD

**Issue by xaru123** [JeffreyWay/laravel-mix#2453]
-   Laravel Mix Version:4.1.4
-   Node Version (`node -v`): v12.14.1
-   NPM Version (`npm -v`): 6.14.5

-   OS: Windows

### Description:
Is there an instruction to optimize app.js size? the first download of a 5.5 MB file takes 10 seconds. which is very long. can someone tell me what to look for?
Maybe it is ok. but i think it is not fast at all.

It is my webpack.mix.js
```

const mix = require('laravel-mix');
mix.autoload({
    jquery: ['$', 'window.jQuery', "jQuery", "window.$", "jquery", "window.jquery"]
});

mix.webpackConfig({
    output: {
        chunkFilename: 'js/chunk/[name].js'
    }
    
});

mix.options({ processCssUrls: true })
    .js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .copyDirectory('resources/layout', 'public/layout')//шаблон
    .copyDirectory('resources/images', 'public/img')
    .copyDirectory('resources/css/template', 'public/css/template')
    .copyDirectory('resources/css/dashboard', 'public/css/dashboard')
    .copyDirectory('resources/css/report', 'public/css/report')
    .copyDirectory('resources/css/arm', 'public/css/arm')
    .copyDirectory('resources/js/dashboard', 'public/js/dashboard')
    .copyDirectory('resources/js/common', 'public/js/common')
    .copyDirectory('resources/js/report', 'public/js/report')
    .copyDirectory('resources/js/arm', 'public/js/arm')
    .copyDirectory('resources/js/module', 'public/js/module')
    .copyDirectory('resources/media', 'public/media')
    .copyDirectory('resources/vendors', 'public/vendors')
    .copyDirectory('resources/instruction', 'public/instruction')
```

**Comment by rebaz88** [comment]
did you use --prod for production?

**Comment by xaru123** [comment]
Yes, 5.5 MB is result of production's tests

**Comment by Chopinsky** [comment]
Seems like you're packing all 3rd party vendor code into the `app.js` all together, and it can result in a monstrous package size. Usually there're tricks to 1) let the vendor code out, load them separately in your webpage, and 2) spilt the chunk into smaller pieces, and dynamically loading components that are needed in the scope or context. 

For example, my `vue` applications always have this setup in `webpack.mix.js`:

```
mix.webpackConfig({
    externals: { "vue": "Vue" },
});
```

And in my code, I can import "Vue" however I want, though the "Vue" library and its dependencies won't be packed into the build files (production or development). The downside of this approach is that you will have to find a CDN that serves the 3rd party libraries, and update the versions in your webpage scripts on each major upgrades.
