### ISSUE TITLE
Error after running npm run dev

### ISSUE THREAD

**Issue by diya-ing** [JeffreyWay/laravel-mix#2454]
-   Laravel Mix Version: Laravel Framework 7.22.4
-   Node Version: v14.7.0
-   NPM Version: 6.14.7
-   OS: Windows 10

Description: Getting errors after running npm run dev

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Lenovo\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Lenovo\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2020-07-31T15_45_31_070Z-debug.log

Help needed asap!

**Comment by roelofjan-elsinga** [comment]
It seems like you executed "npm run dev" in the wrong directory. Or at least package.json wasn't in the directory you were in when executing the command.

**Comment by diya-ing** [comment]
Yeah I got it and solved! Thanks @roelofjan-elsinga
