### ISSUE TITLE
mix.version() intermittently "forgets" about some files, seemingly at random

### ISSUE THREAD

**Issue by yangm97** [JeffreyWay/laravel-mix#2458]
-   Laravel Mix Version: 5.0.4 (`npm list --depth=0`)
-   Node Version (`node -v`): v14.7.0
-   NPM Version (`npm -v`): 6.14.7
-   OS: macOS Big Sur Developer Beta (hardly ever), Windows 10 (sometimes) and Linux whatever ships with the node docker image, running on Gitlab CI (almost always)

### Description:

Ok first I'd like to steal my own issue to reflect on something else: I've been using the `.copy()` + `.version()` combo to provide cache busting from static assets required by my blade views (that is, using `asset(mix())` on those pesky `<img>`s) but that workflow has led me to numerous issues, such as slow watch performance (plus massive resource usage) and ultimately `.version()` not adding all assets to the `mix-assets.json`, which in turn makes laravel fail very hard. 

However, I believe this little workflow I've built for myself isn't ideal and I would like to know from you guys how/if it could be improved, since I'm forced to use `.version()` even on development so those files get added to the `mix-manifest.json`. There's also the problem with `.copy()` flattening the directory structure by default, which makes the Laravel `mix()` function not find those assets, since there appears to be no url rewrite logic from their side.

Maybe if we had a mix plugin inspired by [html-loader](https://webpack.js.org/loaders/html-loader/#attributes) which parses views looking for `mix()` tokens and automatically adds those to the webpack pipeline? I've never developed plugins for webpack nor mix but would be willing to do so given someone can hold my hand 😛

Anyway, (finally) back on the subject of this issue, it doesn't seem like the `.copy()` method is at fault here, I've confirmed the files do get copied and have experimented with manually `require`'ing those assets from some javascript file but still `.version()` occasionally "forgets" about some file unpredictably.

At first it might look like some cache issue but I've nuked the `node_modules` directory numerous times and it reproduces across multiple environments (my macOS dev machine, a windows dev machine and the linux CI). It also appears to have worsened with the addition of the `clean` plugin so my bets are on some sort of concurrency issue.

So while I could get rid of `mix()` and `.version()` (or override `mix()` so it fails softly by returning the given string with no cache busting added) I really would rather keep them, since they provide a way to fail during build/tests whenever a developer forgets to add some asset rather than on deployment.

### Steps To Reproduce:

Since the issue happens intermittently, regardless of using `watch` or `prod`, I don't think I can provide reproduction steps. However, my `resources/` directory consists of 48 directories and 291 files, and bellow is two versions of my `webpack.mix.js`, one from before the clean plugin and another after:

```
const mix = require('laravel-mix')

mix
  .autoload({
    jquery: ['$', 'jQuery', 'window.jQuery']
  })
  .copy('resources/images/', 'public/images', true)
  .copy('resources/videos/', 'public/videos', true)
  .copy('resources/vendor/', 'public/vendor', true)
  .js('resources/js/app.js', 'public/js')
  .sass('resources/sass/app.scss', 'public/css')
  .version([
    'css/**/*',
    'images/**/*',
    'js/**/*',
    'videos/**/*',
    'vendor/**/*'
  ])

if (mix.inProduction()) {
  mix
    .setResourceRoot('/assets/')
}

if (process.env.NODE_ENV === 'development') {
  mix
    .browserSync('127.0.0.1:8000')
}
```

```
const mix = require('laravel-mix')
require('laravel-mix-clean')

mix
  .autoload({
    jquery: ['$', 'jQuery', 'window.jQuery']
  })
  .copy('resources/images/', 'public/images', true)
  .copy('resources/videos/', 'public/videos', true)
  .copy('resources/vendor/', 'public/vendor', true)
  .copy('vendor/proengsoft/laravel-jsvalidation/resources/views', 'resources/views/vendor/jsvalidation')
  .copy('vendor/proengsoft/laravel-jsvalidation/public', 'public/vendor/jsvalidation')
  .js('resources/js/app.js', 'public/js')
  .sass('resources/sass/app.scss', 'public/css')
  .version([
    'css/**/*',
    'images/**/*',
    'js/**/*',
    'videos/**/*',
    'vendor/**/*'
  ])
  .clean({
    cleanOnceBeforeBuildPatterns: [
      '**/*',
      '!index.php',
      '!favicon.ico',
      '!robots.txt'
    ]
  })

if (mix.inProduction()) {
  mix
    .setResourceRoot('/assets/')
}

if (process.env.NODE_ENV === 'development') {
  mix
    .browserSync('127.0.0.1:8000')
}
```

Looks legit, right? The issue should reproduce (_when it wants to_) on both, but it does seem to reproduce more often with the clean plugin added.

**Comment by JeffreyWay** [comment]
I don't think too many people are versioning all their assets in this way. I'm not.

I'd be happy to look into this, but I do need some way to reproduce what you're seeing. I know you said that may not be possible, but that makes my job even harder. I don't even know where to start.

**Comment by yangm97** [comment]
> I don't think too many people are versioning all their assets in this way. I'm not.

I see. Any tips on that regard? I haven't found a better way to version static assets which are attached to the layout (say, a logo using `<img>`).

> I'd be happy to look into this, but I do need some way to reproduce what you're seeing. I know you said that may not be possible, but that makes my job even harder. I don't even know where to start.

Have you tried my mix config along with an assets directory full of files? Maybe the performance issue is linked to skipping files, so some sort of profiling could lead us somewhere?
