### ISSUE TITLE
All sass files get recompiled even though only one sass file is changed

### ISSUE THREAD

**Issue by arnoson** [JeffreyWay/laravel-mix#2459]
-   Laravel Mix Version: 5.0.4
-   Node Version: 12.18.3
-   NPM Version: 6.14.6
-   OS: MacOS High Sierra 10.13.6

### Description:
I watch two sass files, and when I change one of them, both get recompiled, but only the changed one should get recompiled.

### Steps To Reproduce:

* Install laravel mix standalone as described in the [docs](https://laravel-mix.com/docs/5.0/installation)
* Create two sass files, `one.scss` and `two.scss`, inside a `src` folder
* Use the following `webpack.mix.js` file
```js
// webpack.mix.js
const mix = require('laravel-mix')

mix
  .sass('src/one.scss', 'dist')
  .sass('src/two.scss', 'dist')
```
* run `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --watch --config=node_modules/laravel-mix/setup/webpack.config.js`
* change one of the two sass files

**Comment by arnoson** [comment]
I stumbled upon this webpack dev server [issue](https://github.com/webpack/webpack-dev-server/issues/1503#issuecomment-513988617). It seems that the other file isn't recompiled, but webpack prints the the old compiled files together with the newly compiled ones. I added `mix.version()` and checked the hashes and they confirm that only one file changes.

**Comment by sebszocinski** [comment]
Why was this closed? the files are still being "changed" which causes other watches such as Shopify Themekit to process/upload ALL files instead of just the one you changed...

**Comment by arnoson** [comment]
I closed the issue myself. I hadn't any additional watchers an so for me the problem was solved, because they actually didn't get recompiled, it just looked like it. Maybe it would be good to open a new issue with your specific case?
