### ISSUE TITLE
Error: EPERM: operation not permitted, read

### ISSUE THREAD

**Issue by h6s8n** [JeffreyWay/laravel-mix#2461]
after 'npm run dev' i have this error:

i tested on fresh laravel and nothing changes,thank's for your help.

ERROR in ./node_modules/axios/lib/helpers/cookies.js
Module build failed: Error: EPERM: operation not permitted, read
 @ ./node_modules/axios/lib/adapters/xhr.js 88:20-51
 @ ./node_modules/axios/lib/defaults.js
 @ ./node_modules/axios/lib/axios.js
 @ ./node_modules/axios/index.js
 @ ./resources/js/bootstrap.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pudge\AppData\Roaming\npm-cache\_logs\2020-08-11T20_43_32_248Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pudge\AppData\Roaming\npm-cache\_logs\2020-08-11T20_43_32_348Z-debug.log
![image_2020-08-12_01-17-14](https://user-images.githubusercontent.com/49354487/89947387-9e947f00-dc39-11ea-9502-b7ed74119c49.png)

**Comment by robbyrice** [comment]
Looks like you don't have the proper permissions set in the node_modules directory.

**Comment by h6s8n** [comment]
> Looks like you don't have the proper permissions set in the node_modules directory.

I think some thing crashed,cuse all thing  work correctly  befor!without needing to set anything.

**Comment by h6s8n** [comment]
I understood what the problem was,
This problem occurred after I added this line:
in my vue js component:
            axios.get('/chat/messages').then((response) => {
                this.messages = response.data
            });

after deleted all error resolved!!!

**Comment by h6s8n** [comment]
I think axios library need to fixed,

**Comment by h6s8n** [comment]
> Looks like you don't have the proper permissions set in the node_modules directory.


PS C:\Users\Pudge\Desktop\blog> npm config ls -l
; cli configs
long = true
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.14.6 node/v12.18.3 win32 x64"

; builtin config undefined
prefix = "C:\\Users\\Pudge\\AppData\\Roaming\\npm"

; default values
access = null
allow-same-version = false
also = null
always-auth = false
audit = true
audit-level = "low"
auth-type = "legacy"
before = null
bin-links = true
browser = null
ca = null
cache = "C:\\Users\\Pudge\\AppData\\Roaming\\npm-cache"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
cidr = null
color = true
commit-hooks = true
depth = null
description = true
dev = false
dry-run = false
editor = "notepad.exe"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
format-package-lock = true
fund = true
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "C:\\Users\\Pudge\\AppData\\Roaming\\npm\\etc\\npmrc"
globalignorefile = "C:\\Users\\Pudge\\AppData\\Roaming\\npm\\etc\\npmignore"
group = 0
ham-it-up = false
heading = "npm"
https-proxy = null
if-present = false
ignore-prepublish = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "C:\\Users\\Pudge\\.npm-init.js"
init-version = "1.0.0"
json = false
key = null
legacy-bundling = false
link = false
local-address = undefined
loglevel = "notice"
logs-max = 10
; long = false (overridden)
maxsockets = 50
message = "%s"
; metrics-registry = null (overridden)
node-options = null
node-version = "12.18.3"
noproxy = null
offline = false
onload-script = null
only = null
optional = true
otp = null
package-lock = true
package-lock-only = false
parseable = false
prefer-offline = false
prefer-online = false
; prefix = "C:\\Program Files\\nodejs" (overridden)
preid = ""
production = false
progress = true
proxy = null
read-only = false
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
rollback = true
save = true
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
save-prod = false
scope = ""
script-shell = null
scripts-prepend-node-path = "warn-only"
searchexclude = null
searchlimit = 20
searchopts = ""
searchstaleness = 900
send-metrics = false
shell = "C:\\WINDOWS\\system32\\cmd.exe"
shrinkwrap = true
sign-git-commit = false
sign-git-tag = false
sso-poll-frequency = 500
sso-type = "oauth"
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
timing = false
tmp = "C:\\Users\\Pudge\\AppData\\Local\\Temp"
umask = 0
unicode = false
unsafe-perm = true
update-notifier = true
usage = false
user = 0
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch} {ci}" (overridden)
userconfig = "C:\\Users\\Pudge\\.npmrc"
version = false
versions = false
viewer = "browser"

this is my config list.

**Comment by h6s8n** [comment]
I tried everything
npm cache clean --force
rm node_modules
npm install
turn of windows defender 
But it did not work
Finally I reset my Windows and it was fixed.

**Comment by sin-ara** [comment]
@h6s8n how did u fix this error. I am experiencing the same error and i haven't been able to solve it since last two days. Nor i could find a solution online which would do the job.

**Comment by sin-ara** [comment]
i meant any other solution except resetting.

**Comment by mdnurulmomen** [comment]
If none of the above ways work and your platform is **Ubuntu**, **Linux**, most probably you've placed your projects at other places except Root directory.

My preferred directories to place your project.

- /var/www/

- /var/www/html/

- /home/USER/www/ (or similar things like /home/USER/websites/, .../public_html/, etc.)

**You can try again after moving your project to the one of above directories.**

**Comment by h6s8n** [comment]
> i meant any other solution except resetting.

Change your node version and test again. This issue is from a few years ago, and I don't remember it well.
