### ISSUE TITLE
How can I set multiple `setPublicPath`

### ISSUE THREAD

**Issue by krittidet** [JeffreyWay/laravel-mix#2466]
```
const mix = require('laravel-mix');

// BACKEND
mix.setPublicPath('public/js/backend');
mix.js('resources/js/Backend/app.js', '/');
mix.js('resources/js/Backend/script.js', '/');

mix.setPublicPath('public/css/backend');
mix.sass('resources/sass/Backend/app.scss', '/');

// FRONTEND
mix.setPublicPath('public/css/frontend');
mix.sass('resources/sass/Frontend/layout.scss', '/');
mix.sass('resources/sass/Frontend/main.scss', '/');
mix.sass('resources/sass/Frontend/custom.scss', '/');
```

but all file builded to the `public/css/frontend` folder only

Acture:
 `app.js` store in `public/css/frontend`
 `script.js` store in `public/css/frontend`

 `app.css` store in `public/css/frontend`

 `layout.css` store in `public/css/frontend`
 `main.css` store in `public/css/frontend`
 `custom.css` store in `public/css/frontend`

Expect:
 `app.js` store in `public/js/backend`
 `script.js` store in `public/js/backend`

 `app.css` store in `public/css/backend`

 `layout.css` store in `public/css/frontend`
 `main.css` store in `public/css/frontend`
 `custom.css` store in `public/css/frontend`

**Comment by blackdrago** [comment]
You can achieve this by adding `.setPublicPath` to the mix directives. For example:

```javascript
// BACKEND
mix.js('resources/js/Backend/app.js', '/').setPublicPath('public/js/backend');
mix.js('resources/js/Backend/script.js', '/').setPublicPath('public/js/backend');
...
mix.sass('resources/sass/Frontend/layout.scss', '/').setPublicPath('public/css/frontend');
mix.sass('resources/sass/Frontend/main.scss', '/').setPublicPath('public/css/frontend');
mix.sass('resources/sass/Frontend/custom.scss', '/').setPublicPath('public/css/frontend');
```

**Comment by JeffreyWay** [comment]
No, you can't set multiple public paths. That's not how Mix works. 

If all you care about is different output directories, that's what the second argument to `mix.js/sass()` is for.

```js
mix.js('resources/js/Backend/app.js', 'public/js/backend');
mix.sass('resources/sass/Frontend/layout.scss', 'public/css/frontend');
```
