### ISSUE TITLE
Doesn't compile both less and sass files

### ISSUE THREAD

**Issue by vedmant** [JeffreyWay/laravel-mix#247]
I have following configuration:

mix.js('resources/assets/js/app.js', 'public/js').extract(['vue'])
.less('resources/assets/less/theme.less', 'public/css')
.sass('resources/assets/sass/app.scss', 'public/css');

However less files are not compiled, it works fine if I comment out .sass line.

**Comment by adriaanzon** [comment]
Support for this was added just recently. Update your laravel-mix dependency to [0.6.0](https://github.com/JeffreyWay/laravel-mix/releases/tag/v0.6.0)
