### ISSUE TITLE
[Feature Request] Include APP_ENV by default

### ISSUE THREAD

**Issue by Braunson** [JeffreyWay/laravel-mix#2475]
### Description:

It would be handy to include `APP_ENV` along side `NODE_ENV` without having to prefix it in the `.env` file with [`MIX_`](https://github.com/JeffreyWay/laravel-mix/blob/master/src/webpackPlugins/MixDefinitionsPlugin.js#L34). I can put in a PR if this is of interest.

**Comment by JeffreyWay** [comment]
I think we'll keep it as it is for now.
