### ISSUE TITLE
Assign different PostCSS plugin by asset

### ISSUE THREAD

**Issue by thomasjulienalain** [JeffreyWay/laravel-mix#2476]
-   Laravel Mix Version: ^5.0.4
-   Node Version (`node -v`): v10.15.1
-   NPM Version (`npm -v`): 6.4.1
-   OS: Windows 10

### Description:

Hello !

I am trying to generate 2 different CSS files from SASS :
- One for frontend : app.scss
- One for backend : editor.scss

I am using tailwind via PostCSS :

```

mix.sass('resources/assets/styles/app.scss', 'styles')
  .sass('resources/assets/styles/editor.scss', 'styles');

[...]

mix.options({
    processCssUrls: false,
    postCss: [
        require('tailwindcss')('./tailwind.config.js'),
    ]
});
```

I would like to use a specific Postcss plugin (postcss-editor-styles) only for editor.scss, 

I tryied this, i have no error compiling, but in the end, the postcss-editor-styles apply for both files instead of just editor.scss.

```
mix.sass('resources/assets/styles/app.scss', 'styles')
  .options({
    processCssUrls: false,
    postCss: [
      require('tailwindcss')('./tailwind.config.js'),
    ]
  });

mix.sass('resources/assets/styles/editor.scss', 'styles')
  .options({
    processCssUrls: false,
    postCss: [
      require('tailwindcss')('./tailwind.config.js'),
      require('postcss-editor-styles'),
    ]
  });

```
Here is my webpack.mix.js :
https://gist.github.com/thomasjulienalain/6764754618334a7c104fbed7289954a8

Is there a better way to restrict a specific plugin to only one file ?

Thank you !

**Comment by JeffreyWay** [comment]
Right, `mix.options()` isn't exclusive to each `mix.sass()` call. Mix doesn't work that way. 

Instead, add your editor-specific PostCSS plugins as the fourth argument to `mix.sass()`.

Something like this:

```js
mix.sass('resources/assets/styles/app.scss', 'styles');

mix.sass('resources/assets/styles/editor.scss', 'styles', {}, [
  require('postcss-editor-styles')
])

mix.options({
    processCssUrls: false,
    postCss: [
      require('tailwindcss')('./tailwind.config.js')
    ]
});
```
