### ISSUE TITLE
HashedModuleIdsPlugin related issue in production mode

### ISSUE THREAD

**Issue by Tigran-Harutyunyan** [JeffreyWay/laravel-mix#2477]
Laravel Mix Version: ^5.05
Node Version (node -v): v13.12.0
NPM Version (npm -v): 6.14.4
OS: MacOS Mojave
 
### Description:

Hello.
Came across an issue of using mix.version() on production.
In webpack mix I have the following.
if (!mix.inProduction()) {
	mix.sourceMaps();
} else {
	mix.version();
}
  
Build process  with The mix.version() in prod mode mode will stuck forever on 83% before module ids HashedModuleIdsPlugin.   
It runs perfectly on dev version.
Found out that it just compiles fine if the following lines are commented in Version.js that is located in components folder.
webpackPlugins() {
    if (Mix.inProduction()) {
            return [new webpack.HashedModuleIdsPlugin()];
     }
}

I have no clue on this because errors are not reported. Also it is not an option to manually comment out that block in modules.
Any clue is appreciated.
Thanks

**Comment by JeffreyWay** [comment]
We aren't using that plugin in the upcoming release, so this should automatically fix whatever issue you were experiencing.
