### ISSUE TITLE
Auto Extract replacement ?

### ISSUE THREAD

**Issue by mdottavi** [JeffreyWay/laravel-mix#2478]
-   Laravel Mix Version: 4.1.4
-   Node Version : v12.18.3
-   NPM Version : v10.22.0
-   OS: Ubuntu 18.04.5

-  webpack version: 4.43.0

### Description:
As for Documentation laravel-mix-auto-extract extension is not suitable for webpack >4 ,
and it's github repo is archived.
Considering webpack4.x is out since more then 2,5 years and that also 5.x is getting out 
Is there any suitable replacement for autoExtract features integrated in laravel-mix ? 

Thanx a lot.

**Comment by gtempesta** [comment]
Auto Extract used the `CommonsChunkPlugin` from Webpack, which is now deprecated in favor of `optimization.splitChunks`. 
In order to have a similar result you can remove the call to `.extract()` and edit the optimization key in the argument of the `webpackConfig` method. 

Here is a configuration which let's you have slightly more choice than just using `.extract()` from Laravel Mix.

```javascript
.webpackConfig({
  output: {
    filename: '[name].js',
    chunkFilename: '[name].js?id=[chunkhash]',
    publicPath: '/',
    path: path.resolve(__dirname, 'public'),
  },
  optimization: {
    runtimeChunk: {
      name: '/js/manifest',
    },
    splitChunks: {
      cacheGroups: {
        default: false,
        vendors: false,
        vendor: {
          // name, chunk and test must be at the same level
          name: 'js/vendor',
          chunks: 'all',
          test(module, chunk) {
            if (module.context) {
              // only node_modules are needed
              const isNodeModule = module.context.includes('node_modules');
              // but not specific node_modules
              const isToBundleSeparately = [
                'intl',
                'date-time-format-timezone',
              ].some(str => module.context.includes(str));
              if (isNodeModule && !isToBundleSeparately) {
                  return true;
              }
            }
            return false;
          },
        },
      },
    },
  },
})
```
