### ISSUE TITLE
Error with npm run production

### ISSUE THREAD

**Issue by mohamedsabil83** [JeffreyWay/laravel-mix#248]
When I use (npm run dev) everything done as is. but when use (npm run production) I got error with following:

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "production"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @ production: `node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ production script 'node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mohamedsabil83/www/blacklist/npm-debug.log

[npm-debug.log.zip](https://github.com/JeffreyWay/laravel-mix/files/742127/npm-debug.log.zip)

**Comment by ssuhat** [comment]
+ 1 with this. but mine run on `npm run dev` (non laravel project)

**Comment by betteryourweb** [comment]
+1 Same here, `npm run production`

**Comment by betteryourweb** [comment]
Well, I've found my problem. One thing was I didn't have webpack installed gloablly on that server (every other project I have on this particular server uses gulp or laravel-elixir), as well, I had two versions of node (5.8 && 7) and I ran npm install then upgraded my system which set 7 as my primary, but compile with 5. Sorry... Non issue

**Comment by mohamedsabil83** [comment]
@betteryourweb I'm upgrading to node7 many days ago but not sure for that. you suggest to remove npm package from my laravel project and install it again the try (npm run production) again?

**Comment by betteryourweb** [comment]
Essentially, that would have worked for me. So I say try it...

**Comment by mohamedsabil83** [comment]
Thanx @betteryourweb, as you suggest, I removed node_modules folder and install libraries again with order (npm install). now it's work at a glance.
