### ISSUE TITLE
Extract all Vue logic from mix.js()

### ISSUE THREAD

**Issue by JeffreyWay** [JeffreyWay/laravel-mix#2483]
As part of the big Mix 6 upgrade, we should take this opportunity to extract all Vue-specific logic from the `mix.js()` call. This will be a breaking change, but it's as good a time as any to do it. Like `mix.react()`, we'll need to add a `mix.vue()` command.

**Comment by thecrypticace** [comment]
I'm working on #2481 / #2482 / #2483 (this issue) right now. How are you thinking this will work with things like `mix.ts()`? Right now they hardcode support for Vue (but not react). For me it seems like `mix.js` should still be used but `mix.vue()` and `mix.react()` are effectively _features_ that can be enabled for use in any used language.

My thinking is we could write something like the following:

```js
// 1. enable Vue support
mix.vue()

// 2.a. Compile app JS
mix.js("app/js/app.js", "public/js/app.js")

// 2.b. alternatively compile app TypeScript
mix.js("app/ts/app.ts", "public/js/app.js")
```

**Comment by JeffreyWay** [comment]
I'll talk with you in the PR thread.
