### ISSUE TITLE
Bootstrap-sass error when compiling for production

### ISSUE THREAD

**Issue by jesperbjoernandersen** [JeffreyWay/laravel-mix#2485]
-   Laravel Mix Version: 5.5.5
-   Node Version (`node -v`): 10.21
-   NPM Version (`npm -v`): 6.14.4
-   OS: Windows 10

### Description:

There seems to be an issue with "bootstrap-sass": "^3.4.1 when compiling for production.
I was able to pinpoint it to @import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap/type";

Inside the file "_type.scss" I commented out:

@include bg-variant('.bg-primary', $brand-primary);
@include bg-variant('.bg-success', $state-success-bg);
@include bg-variant('.bg-info', $state-info-bg);
@include bg-variant('.bg-warning', $state-warning-bg);
@include bg-variant('.bg-danger', $state-danger-bg);

Removing these lines made me able to compile for production, so there's some kind of issue here, not sure what.

**Comment by JeffreyWay** [comment]
If this is a Mix issue, I’d need reproducible steps using the simplest example you can manage.
