### ISSUE TITLE
npm run dev return error status 2

### ISSUE THREAD

**Issue by ssuhat** [JeffreyWay/laravel-mix#249]
I'm using latest [Laravel Mix][1] to compile my JS file.

But every time I run npm run dev (scripts come from Laravel package.json) it always return me an error (If something fail when compile) but never show me what exactly went wrong.

[![Error][2]][2]

Never happen when using laravel elixir.

Here is the package.json script:

    "scripts": {
    "dev": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },

My app.js:

        import React from 'react';
	import ReactDOM from 'react-dom';
	import {browserHistory} from 'react-router';
	import { Provider } from 'react-redux';
	import configureStore from './store';
	import routes from './routes';

	const initialState = {};
	const store = configureStore(initialState, browserHistory);

	ReactDOM.render(
	    <Provider store={store}>
	        {routes}
	    </Provider>, document.getElementById('main-content')
	);

Any solution?

  [1]: https://github.com/JeffreyWay/laravel-mix
  [2]: https://i.stack.imgur.com/jtlFa.png

**Comment by JeffreyWay** [comment]
I assume because you're using JSX there, but haven't added support to your webpack.config.js. 

Mix doesn't ship with JSX compilation.

**Comment by ssuhat** [comment]
@JeffreyWay Hi, I'm using ES6 on React so my file extension using .js not .jsx

On laravel elixir I can compile it finely using .babel without any issue. I look at Laravel Mix using babel loader. should do the same right?

**Comment by QWp6t** [comment]
you need react preset. basically every react 101 guide shows you how to set this up. google is your friend.
