### ISSUE TITLE
[request] A simple way to load different Vue components on different Laravel pages

### ISSUE THREAD

**Issue by ipearx** [JeffreyWay/laravel-mix#2494]
I've been playing around with Vue 3 and Laravel 8. Thanks to the laravel-mix-vue3 project for making this easy while Mix's official Vue 3 support is under way.

The way I'd like to structure my apps is to use laravel routes and pages as individual Vue mini-apps. A made up example:
/ = a homepage 'app', only one or two simple components.
/map = a mapping page that loads in map libraries and is a complicated vue app with many components.
/help = a documentation 'app' that lets users browse the help files.

For some reason such a setup is incredibly difficult to get working, and I just get the feeling the whole system is WAY over complicated. So I really appreciate Mix as a way to simplify it for people like myself who don't have the time to learn build systems.

- To clarify, I don't want to use the new Jetstream system (either of them).
- A user shouldn't need to download libraries and code that aren't relevant to the section or page of the website they are on.
- I like the Vue component system and separate .vue files. So the compilation step is great.
- The .extract() function didn't seem to work with laravel-mix-vue3 properly (every file output was huge). Hopefully this will work as expected with official Vue3 support in mix?
- I'd like to use the .extract() to output the common libraries between pages/sections into their own files. e.g. the vue library or axios.
- I like tree shaking. Get rid of the stuff we're not actually using makes a lot of sense.
- I don't really want to use lazy loading, if I load the map page, I know all the code I need for it, and want to download it all.

My request is to make it easy to specify which pages load which Vue components or other libraries. I suspect if I can get .extract() working with Vue 3, then I can do it somewhat manually.

**Comment by thecrypticace** [comment]
This might be a good case for not using Mix's extract utilities and instead using webpack's automatic chunk splitting features. If I have time later this week I'll write up something on how to do this but this comment is a pretty good place to start: https://github.com/JeffreyWay/laravel-mix/issues/2478#issuecomment-698318588

**Comment by ipearx** [comment]
Thanks @thecrypticace, I'll take a look!

I get the feeling if extract worked as expected I would be sorted. And hopefully it will with @JeffreyWay 's work on integrating Vue3.

e.g. if my app has a photo gallery page, and a map page, I'd expect to get the files:
vendor.js // all common libraries used by all pages e.g. Vue, axios etc.
gallery.js // all Vue components and libraries needed for the gallery page.
map.js // all Vue components and libraries needed for the map page.

To accomplish this, I can create a separate app.js file for each page, compile each separately, and use extract to extract the common libraries which the browser would cache between pages. 

I'd still like to figure out a way to:
- Dynamically load the appropriate Vue component on individual pages (i.e. not have to make a separate app.js file for each page!) AND keep tree shaking for small files. An example:

I might have lots of pages e.g:
/login
/register
/forgot-password
/map
/gallery
/my-account

and I'd like each to start with it's component e.g. 
/login uses TheLogin.vue component with the html tag <the-login></the-login>
etc...

I managed to get this working with laravel-mix-vue3 by switching it to use the vue.esm-bundler.js distribution of Vue. Then it can dynamically set the template of the root Vue component in the blade file is used. BUT that looses tree shaking and thus large JS files are generated (300Kb each JS for basic Hello World).  Which makes sense, as if it can't pre-compile all the templates, how can it know what to get rid of.

**Comment by thecrypticace** [comment]
So you will be able to use async chunk splitting + Vue 3's defineAsyncComponent to achieve some parts of this. But with the way `.extract()` works it'll still pull all dependencies from node modules into vendor.js. I actually have need for something like this as well so I may take a good at prototyping an API for this to see what it would look like in Mix but its highly unlikely it'll be before 6.0 is released.

**Comment by ipearx** [comment]
Thanks I was literally just reading about Vue 3's defineAsyncComponent as you wrote your reply :) I could use a bit more information about it, the documentation doesn't quite explain it enough for me. I assume it lets you dynamically load components AFTER the web page has loaded? I simply don't want to load anything in the first place that's not relevant to the current page. I guess this might be a way to achieve it.

**Comment by thecrypticace** [comment]
Correct! In Vue 2 you can define a component as a function that returns a promise and it'll include the necessary files when the component is used but with Vue 3 you have to use `defineAsyncComponent` to do this. It acts as a sort of wrapper around such a function and handles loading, errors, timeout, Suspense support, and some other details.
