### ISSUE TITLE
Generate manifest for each javascript

### ISSUE THREAD

**Issue by henry-spanka** [JeffreyWay/laravel-mix#250]
I have the following `webpack.mix.js`:
```js
mix.js('resources/assets/js/app.js', 'public/js').extract(
    ['foundation-sites', 'jquery', './resources/assets/js/laravel.js'], 'public/js/vendor.js'
);
mix.sass('resources/assets/sass/app.scss', 'public/css');

mix.js('resources/assets/admin/js/app.js', 'public/admin/js').extract(
    ['bootstrap-less', 'jquery', './resources/assets/admin/js/laravel.js'], 'public/admin/js/vendor.js'
);
```
This does work fine, however only one manifest is generated for `admin` javascript. This causes issues as I want to have a manifest for each mixed javascript to properly reference them in Blade using `mix('path')`

Output:
```
                                /js/app.f5a95ef2399c6a36eae4.js    1.08 MB    0, 4  [emitted]  [big]  /js/app
                                    /admin/js/app.69d60a6a37568b8adc3a.js     879 kB    1, 4  [emitted]  [big]  /admin/js/app
                                 /admin/js/vendor.0ccb9485f3e36472e423.js     337 kB    2, 4  [emitted]  [big]  /admin/js/vendor
                                       /js/vendor.d928eb65fcaa6bc93bbd.js     329 kB    3, 4  [emitted]  [big]  /js/vendor
                               \admin\js\manifest.d41d8cd98f00b204e980.js    5.68 kB       4  [emitted]         \admin\js\manifest
                                        /css/app.a3294d13b651cbe42440.css    1.33 MB    0, 4  [emitted]  [big]  /js/app
                                  /admin/css/app.a3294d13b651cbe42440.css     670 kB    0, 4  [emitted]  [big]  /js/app
```

**Comment by henry-spanka** [comment]
I'm referring to the latter (manifest.js) but I don't like referencing the manifest in the admin folder in blade templates that generate client content. It's not a big deal but would be nice if two manifests would be generated.

**Comment by henry-spanka** [comment]
@JeffreyWay just tested your suggestion and it doesn't work. The manifest MUST be generated for each javascript resource independently.

Error: 
```
Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (manifest.d41d8cd….js:53)
    at Object.15 (vendor.d4eabf3….js:2404)
    at __webpack_require__ (manifest.d41d8cd….js:53)
    at Object.79 (vendor.d4eabf3….js:2411)
    at __webpack_require__ (manifest.d41d8cd….js:53)
    at webpackJsonpCallback (manifest.d41d8cd….js:24)
    at vendor.d4eabf3….js:1
```
```
Uncaught TypeError: Cannot read property 'jquery' of undefined
    at app.609e1c2….js:12223
    at app.609e1c2….js:12235
    at Object.<anonymous> (app.609e1c2….js:12737)
    at Object.8 (app.609e1c2….js:12739)
    at __webpack_require__ (manifest.d41d8cd….js:53)
    at Object.<anonymous> (app.609e1c2….js:382)
    at Object.35 (app.609e1c2….js:438)
    at __webpack_require__ (manifest.d41d8cd….js:53)
    at Object.20 (app.609e1c2….js:325)
    at __webpack_require__ (manifest.d41d8cd….js:53)
```

**Comment by eblin** [comment]
I would suggest you put the manifest outside the admin and somewhere like `common` folder. Reason is that, although you are getting different bundles with `mix.js()` the `manifest.js` is really what glues everything together regardless of where those bundles are being included, this is part of code splitting that webpack does. I'm not even sure webpack can output multiple `manifest.js`

More info: https://webpack.js.org/guides/code-splitting-libraries/#manifest-file

**Comment by JeffreyWay** [comment]
I'm sure you only need one manifest.json file, so there may be a separate issue at play. You can create a new issue if you can determine what that is.

**Comment by arcanedev-maroc** [comment]
Hi @JeffreyWay,

I had same issue as @henry-spanka.

What he mean is that extracting vendor libs from different app.js (one for front and other fro admin).

The generated `mix-manifest.json` will be something like this:

```json
{
  "/css/app.css":          "/css/app.css",
  "/js/app.js":            "/js/app.js",
  "/js/vendors.js":        "/js/vendors.js",
  "/admin/css/app.css":    "/vendor/foundation/css/app.css",
  "/admin/js/app.js":      "/admin/js/app.js",
  "/admin/js/vendors.js":  "/admin/js/vendors.js",
  "/admin/js/manifest.js": "/admin/js/manifest.js"
}
```

As you can see, the `mix-manifest.json` is missing `"/js/manifest.js"` and it crash the application when you call `{{ mix("js/manifest.js") }}` with this message:

```
Unable to locate Mix file: /js/manifest.js. Please check your webpack.mix.js output paths and try again. (View: [path-view]) (View: [path-view])
```

Can you help us @JeffreyWay to solve this issue ? 

I really want to help to solve this issue but i know nothing about how webpack works.

Best regards

**Comment by arcanedev-maroc** [comment]
Related: #224

**Comment by moyvera** [comment]
@henry-spanka did you find some solution ?? @arcanedev-maroc ???

**Comment by iraklisg** [comment]
@arcanedev-maroc explicitly defining the vendor output path did the trick form me :+1: 
```
mix.js('resources/assets/js/main/app.js', 'public/js/main');
mix.js('resources/assets/js/admin/app.js', 'public/js/admin')
    .extract([
        'vue',
        'axios',
        'jquery',
        'bootstrap-sass'
    ], '/js/vendor.js');
```
Nevertheless, following that approach, isn't it reasonable to only extract the common libraries used between the _front_ and the_back_ site?
