### ISSUE TITLE
Allow automatic hmr port selection

### ISSUE THREAD

**Issue by mortenscheel** [JeffreyWay/laravel-mix#2503]
This is related to #2308, which was fixed by allowing an optional --hmr-port argument.

Since webpack-dev-server will find an available port automatically (if no port is specified), I wonder if it would be possible to have mix use whatever port the dev-server chooses? That would make it possible to have multiple projects with hmr running simultaneously without having to do manual port management.

**Comment by JeffreyWay** [comment]
Happy to accept a PR.
