### ISSUE TITLE
[6.*] webpack-cli  type error and ReferenceError / Postcss 8 error

### ISSUE THREAD

**Issue by MrJuliuss** [JeffreyWay/laravel-mix#2514]
-   Laravel Mix Version: v6.0.0-beta.2
-   Node Version (`node -v`): v12.18.3
-   NPM Version (`npm -v`): 6.14.8
-   OS: 

### Description:

Hello, i got an error on `npm run dev` :

```
[webpack-cli] TypeError: Cannot read property 'includes' of undefined

[webpack-cli] TypeError: Cannot read property 'compilers' of undefined
```

I try to update laravel-mix to master, and got new error :

```
[webpack-cli] ReferenceError: path is not defined
```

### Steps To Reproduce:

```
npm run dev
```

**Comment by MrJuliuss** [comment]
It seems the error came with 

```
mix.alias({
    vue$: path.join(__dirname, 'node_modules/vue/dist/vue.esm-bundler.js')
});
``` 

If i comment this line, the compilation begins (but failed) : 

```
Syntax Error: Error: PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users

```

**Comment by JeffreyWay** [comment]
Just to be sure, can you bump to v6.0.0-beta.3 and try again?

Also, you shouldn't need that `mix.alias()` line. We already do that.

**Comment by MrJuliuss** [comment]
Hi

With v6.0.0-beta.6 (and removing mix.alias()), i got this error, on vue 3 components

```
Syntax Error: Error: PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
```

**Comment by JeffreyWay** [comment]
We may need to make `postcss` a peer dependency, but I'm confused why I can't reproduce what you're seeing.

Can you nuke your node_modules directory and do a fresh install from scratch. Then check if you're still seeing the same error?

**Comment by MrJuliuss** [comment]
Yes i already nuke my `node_modules` before my tests :(

**Comment by MrJuliuss** [comment]
I also have this error in simple scss files : 

```
 error  in ./resources/sass/shop.scss

Error: PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
```

**Comment by emilsrits** [comment]
`npm i --save-dev postcss` makes it work, but I notice that now it puts another **app.css** under **public/js** directory.

![Screenshot_19](https://user-images.githubusercontent.com/15720299/95217376-c77d5e80-07fb-11eb-8f23-7e21fd0e5e82.png)

**Comment by MrJuliuss** [comment]
@emilsrits oh great, everything compiles now. 
But i don't have a double `app.css` in two directories like you. 

@JeffreyWay What do you think, should i add `postcss` directly in my app like @emilsrits saids or we can fix it in Mix ?

**Comment by MrJuliuss** [comment]
Ok it compilet, but i can't see any components. 

It seems i have a problem with esm-bundler :( 

Not error, but warnings

```
shop.js:22881 You are running the esm-bundler build of Vue. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle. See http://link.vuejs.org/feature-flags for more details.
```

```
[Vue warn]: Failed to resolve component: template-test 
```

**Comment by MrJuliuss** [comment]
@JeffreyWay ok all works with : 

```
let path = require('path');
mix.alias({
    vue$: path.join(__dirname, 'node_modules/vue/dist/vue.esm-bundler.js')
});
mix.webpackConfig(webpack => { return {
    plugins: [new webpack.DefinePlugin({ '__VUE_OPTIONS_API__': 'true', '__VUE_PROD_DEVTOOLS__': 'false' })],
}});
```

It seems i need to alias `vue`, because i use some custom vue3 packages which are included in others. 

```
•
└── my_app
    └── my_package 
        └── my sub package // sub package needs alias to use vue3
``` 

Like this :

**Comment by MrJuliuss** [comment]
Update : 

I tried to use new options `runtimeOnly` instead of mix.alias in `webpack.mix.js`, but it does not work. It return an alias to `vue/dist/vue.esm-bundler.js`, but it seems we need `node_modules/vue/dist/vue.esm-bundler.js` . 

Any idea ?

**Comment by MrJuliuss** [comment]
Ok thanks :+1:

**Comment by thecrypticace** [comment]
Sorry it's been a bit. I've been able to use `mix.vue()` properly w/o issue incl. with the new `runtimeOnly` flag. `node_modules` isn't needed in the path. Can you provide a reproduction repo? It would be super helpful!

**Comment by MrJuliuss** [comment]
Hi, it's a little complicated to provide you a reproduction repo...
My project loads many npm packages (repo) (with non-precompiled components), with many levels (like explain in my previous comment)

It works with : 

```
let path = require('path');
mix.alias({
    vue$: path.join(__dirname, 'node_modules/vue/dist/vue.esm-bundler.js')
});
```
`vue.esm-bundler.js` path looks like : `/var/www/my_app/node_modules/vue/dist/vue.esm-bundler.js'

It seems without this, mix can't find the bundler :(

**Comment by MrJuliuss** [comment]
Just found this webpack documentation : https://webpack.js.org/configuration/resolve/#resolvealias 


alias: | import 'xyz' | import 'xyz/file.js'
-- | -- | --
{} | /abc/node_modules/xyz/index.js | /abc/node_modules/xyz/file.js
{ xyz: '/abc/path/to/file.js' } | /abc/path/to/file.js | error
{ xyz$: '/abc/path/to/file.js' } | /abc/path/to/file.js | /abc/node_modules/xyz/file.js
{ xyz: './dir/file.js' } | /abc/dir/file.js | error
{ xyz$: './dir/file.js' } | /abc/dir/file.js | /abc/node_modules/xyz/file.js
{ xyz: '/some/dir' } | /some/dir/index.js | /some/dir/file.js
{ xyz$: '/some/dir' } | /some/dir/index.js | /abc/node_modules/xyz/file.js
{ xyz: './dir' } | /abc/dir/index.js | /abc/dir/file.js
{ xyz: 'modu' } | /abc/node_modules/modu/index.js | /abc/node_modules/modu/file.js
{ xyz$: 'modu' } | /abc/node_modules/modu/index.js | /abc/node_modules/xyz/file.js
{ xyz: 'modu/some/file.js' } | /abc/node_modules/modu/some/file.js | error
{ xyz: 'modu/dir' } | /abc/node_modules/modu/dir/index.js | /abc/node_modules/modu/dir/file.js
{ xyz$: 'modu/dir' } | /abc/node_modules/modu/dir/index.js | /abc/node_modules/xyz/file.js

**Comment by thecrypticace** [comment]
Yeah that's the documentation I looked through to verify `node_modules` shouldn't be necessary. When we alias we're making use of rows 11 & 13. I think we could likely add node_modules and it shouldn't break anything but I'm kind of at a loss as to why it seems to be necessary for you in the first place.

Does the issue reproduce for you in a brand new project that uses Mix v6 beta 10?

**Comment by mikebronner** [comment]
@emilsrits @MrJuliuss I figured out that the double CSS file happens if you require a CSS file from JS, as recommended by some JS packages.
