### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Karim-Megahed** [JeffreyWay/laravel-mix#2515]
somehow **require() is not defined** 

resources/js/app.js

```
require('./bootstrap.js');

window.Vue = require('vue');

Vue.component( 'ExampleComponent', require('./components/ExampleComponent.vue') );

const app = new Vue({
    el: '#app',
});
```

webpack.mix.js

```
const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css');
```

node version: 12.18.4
npm version: 6.14.6
laravel-mix: 4.1.4

Any help would be highly appreciated

**Comment by JeffreyWay** [comment]
I'd need more information.

You're on a really old version of Mix, so maybe start by upgrading to at least v5.

**Comment by Karim-Megahed** [comment]
I did upgrade laravel-mix to version 5 but same error persists.

**Uncaught ReferenceError: require is not defined
    at app:7**

This is the error from the console.

Could you tell me what information would you need to know?

**Comment by JeffreyWay** [comment]
When are you seeing that require() error? During compilation or when you load the site in the browser?

**Comment by Karim-Megahed** [comment]
During loading in the browser, compilation happens without errors

**Comment by JeffreyWay** [comment]
There must be something else going on, because I can't reproduce what you're see. I've never seen that error. 

It sounds like, somehow, the file being given to the browser hasn't been compiled.

**Comment by Karim-Megahed** [comment]
Yes, I also think that this file is not compiled

https://drive.google.com/file/d/1QWf0HYLWe2HPnhSQJclkRsjlG8F1DDyd/view?usp=sharing

here's a screenshot from the browser sources, could you please take a look

**Comment by ahmadzaza98** [comment]
did you solve the probleme ? I have the same issue

**Comment by saadabdurrazaq** [comment]
I have the same problem. Any solution?

**Comment by APerezdelatorre** [comment]
How did you solve this?

**Comment by TheChitoMahn** [comment]
I have the same issue but with vite.

**Comment by Stacss** [comment]
> I have the same issue but with vite.

how you fix it?
