### ISSUE TITLE
fonts copied to public but no directive in webpack.mix.js

### ISSUE THREAD

**Issue by hulkur** [JeffreyWay/laravel-mix#252]
i have modified default webpack.mix.js to redirect js and css files but fonts are still placed under public/

There is no directive about fonts in default file, why are fonts handled at all ?

**Comment by hulkur** [comment]
From #246 I see that i have to set publicPath if my public is not actually public/

I think this should be explicitly set in default mix file and other assets with relative path from that (tested, works)

**Comment by JeffreyWay** [comment]
Okay, thanks!
