### ISSUE TITLE
The Elliptic package 6.5.2 for Node.js allows ECDSA signature malleability via variations in encoding, leading '\0' bytes, or integer overflows.

### ISSUE THREAD

**Issue by bsomeshwer** [JeffreyWay/laravel-mix#2520]
Hi

Issue:
```
The Elliptic package 6.5.2 for Node.js allows ECDSA signature malleability via variations 
in encoding, leading '\0' bytes, or integer overflows. 
This could conceivably have a security-relevant impact if an application relied on a 
single canonical signature.
```
I'm using Elliptic 6.5.3 version but still I'm facing this issue in my project.
Could you please let me know what could be the reason for this?

```
I tried npm install elliptic@6.5.3
and
npm audit fix
and I played around lot of other ways but still issue persists.
```

Thanks

Image reference:

**`Note: Actually, this issue is throwing by laravel-mix. laravel-mix is internally using few packages and those packages are internally using elliptic.  `**

![image](https://user-images.githubusercontent.com/39646194/95183838-29ca6500-07e4-11eb-8025-61493d846e55.png)

**Comment by JeffreyWay** [comment]
Check the path in that screenshot. It's many dependencies below mix. Without knowing more, I don't think I can do anything on the Mix end.
