### ISSUE TITLE
[6.*] Imported styles from node_modules get compiled to js output directory

### ISSUE THREAD

**Issue by emilsrits** [JeffreyWay/laravel-mix#2522]
-   Laravel Mix Version: 6.0.0-beta.4
-   Node Version: v14.12.0
-   NPM Version: 6.14.8
-   OS: Ubuntu 18.04.2 LTS (WSL)

### Description:

Styles that are imported from packages inside **node_modules** get compiled to **public/js** directory.

E.g.: having `@import "~normalize.css/normalize.css";` at the top of your **app.scss** will compile it to **public/js/app.css** instead of **public/css/app.css**.

### Steps To Reproduce:

- Add `@import "~normalize.css/normalize.css";` (or some other package)  to **resources/sass/app.scss**
- Run `npm run dev` or other command to compile your assets
- Check under your js output destination for **app.css** file which contains styles from the imported package

```
mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css');
```

![Screenshot_19](https://user-images.githubusercontent.com/15720299/95230431-8e001f80-080a-11eb-8063-306ead0d9485.png)

**Comment by thecrypticace** [comment]
This was fixed in v6.0.0-beta.6. Please check the latest beta and let us know if you see any further issues.
