### ISSUE TITLE
Files Copy & Replace content (strings etc)....

### ISSUE THREAD

**Issue by saas786** [JeffreyWay/laravel-mix#2528]
### Description:

Feature request.

While you are at it (rebuilding most of the mix for webpack v5), is it possible if you can improve
copy mix? So it works like standard copying tools offered by grunt, gulp etc?

Its been already discussed here:
https://github.com/JeffreyWay/laravel-mix/issues/541
https://github.com/JeffreyWay/laravel-mix/issues/540

and solutions you provided in those issues are no longer applicable.

So it will be nice if copy mix can 
a) Keep the directory structure, if directory is being passed as input.
b) We could pass patterns as input, at least like how **glob.sync** works. Which would allow for filter like ignore pattern etc.
c) When files are being watched, it will be nice if it detects file deletion / additions as well.

Also if its possible to either create new replace mix? or allow copy mix to be filterable / hookable,
so while a file is being copied, we could replace its content (string / pattern replacement) on the fly and that changed files copied to destination.

**Comment by JeffreyWay** [comment]
**a) Keep the directory structure, if directory is being passed as input.**

Mix already does this.

**b) We could pass patterns as input, at least like how glob.sync works. Which would allow for filter like ignore pattern etc.**

You can already pass basic wildcards.

**c) When files are being watched, it will be nice if it detects file deletion / additions as well.**

Not sure if Mix does this or not, but it's not at the top of my todo list at the moment. Takes two seconds to restart the watcher.

**Also if its possible to either create new replace mix? or allow copy mix to be filterable / hookable,
so while a file is being copied, we could replace its content (string / pattern replacement) on the fly and that changed files copied to destination.**

Eh, I think I'll pass on that. 

Here's the full docs for what `mix.copy()` can do.

https://github.com/JeffreyWay/laravel-mix/blob/master/docs/copying-files.md
