### ISSUE TITLE
redirecting assets outside laravel root requires double ../

### ISSUE THREAD

**Issue by hulkur** [JeffreyWay/laravel-mix#253]
Default target for compiled assets is `public/js`

My server setup is that public folder and laravel root are on same path level

With elixir I had to redirect assets to `../htdocs/js`, with mix this will put them still in laravel root. Basically in `./htdocs/js`. It works if I set it to `../../htdocs/js`

Seems like it ignores first dot.

If I put `.../htdocs/js` then does not complain but neither is anything generated

**Comment by david-ridgeonnet** [comment]
Have you tried specifying it so in your webpack it has:

```
mix.setPublicPath('../htdocs');
```

Then you can reference JS / CSS destinations like so:

```
mix.js('resources/assets/js/app.js', 'js');
mix.sass('resources/assets/sass/app.scss', 'css');
```

if you exclude the htdocs in the first part, you would need to add it to the second parts prior to the `'js'` and `'css'`

**Comment by hulkur** [comment]
That's what I did.
```
mix
   .setPublicPath('../htdocs')
   .js('resources/assets/js/app.js', 'js')
   .sass('resources/assets/sass/app.scss', 'css');
```

But I think it should work the other way also

**Comment by JeffreyWay** [comment]
Yeah - correct approach is to set the publicPath. Everything is based on that.
