### ISSUE TITLE
compiling a SASS and a CSS file into a single file

### ISSUE THREAD

**Issue by sxshateri** [JeffreyWay/laravel-mix#2531]
im trying to compile a SASS file and a CSS file into a single file but seems its not possible. 

```
mix.js('resources/js/app.js', 'public/js')
    .sass('resources/scss/app.scss', 'public/css')
    .styles('resources/css/app.css', 'public/css');
```
I'm getting errors to use full file name for the output file and when i do that it only writes the .scc content into the public/app.css file. my guess is it will compile the 'resources/scss/app.scss' file then overwrites it with 'resources/css/app.css'.

any idea how to make this work?

**Comment by JeffreyWay** [comment]
`mix.styles()` is used for concatenation. Are you sure that's what you want here? 

You can't compile multiple source files to the same output. One would overwrite the other.
