### ISSUE TITLE
Libraries specified in extract do not load.

### ISSUE THREAD

**Issue by alanondra** [JeffreyWay/laravel-mix#254]
As expected, the `manifest.js`, `vendor.js`, and `app.js` files all emit, and I load them in `<head/>` in that order using the `mix()` helper function. I've got this configuration:
```
mix.js(
	['resources/assets/js/app.js'],
	'public/assets/js'
).extract([
	'jquery',
	'jquery-ui',
	'jquery-mask-plugin',
	'blueimp-gallery'
]);
```

Both of the main variables `jQuery` and `blueimp` are undefined. From what I can see it _looks_ like the files are compiled in order in `vendor.js` but they're still not being run. I've also tried using `defer` but that doesn't affect it.

**Comment by JeffreyWay** [comment]
I just created a sample app, and it all seems to be working.

https://www.dropbox.com/s/ilwk1xnvda807vu/Screenshot%202017-02-01%2011.21.54.png?dl=0

Make sure that `app.js` does in fact require those modules that you're extracting.

**Comment by alanondra** [comment]
I did in fact have to do that:
```
window.jQuery = window.$ = require('jquery');
window.jQuery.ui = require('jquery-ui');
window.blueimp = require('blueimp-gallery');
```
But this begs the question of why it has to do that in the first place. Shouldn't the libraries be able to do this themselves? Now, for instance, in the case of Blueimp's gallery, I have to use it in a way not in accordance with its documentation which made it a bit more difficult to actually get up and running.

**Comment by JeffreyWay** [comment]
> But this begs the question of why it has to do that in the first place.

Because mix.extract() is extracting modules from your Webpack build. If you never require those files, there's nothing to extract.
