### ISSUE TITLE
Unable to expose bundle as library for inline scripts

### ISSUE THREAD

**Issue by dakujem** [JeffreyWay/laravel-mix#2541]
-   Laravel Mix Version: 5.0.7
-   Node Version: 14.9.0
-   NPM Version: 6.14.8
-   OS: Win 10

I'm trying to access the bundled library in inline scripts, but the object I'm getting is always empty. It might just be me being a noob to JS, or simply something that is not supported by Mix.

As far as I can tell, Webpack enables us to [expose the bundle as a library](https://webpack.js.org/guides/author-libraries/). I'm trying to achieve this using mix, this way:

```js
// webpack-mix.js
const mix = require('laravel-mix');

mix.js('src/app.js', 'assets')
  .sass('src/app.scss', 'assets')
  .webpackConfig({
    output: {
      // export itself to a global var
      libraryTarget: "var",
      // name of the global var: "App"
      library: "App",
    },
  })
```
Then I have this HTML snippet:
```html
<script src="/assets/app.js"></script>
<script>
	App.helloWorld('okay!');
</script>
```
This fails though, as the `App` object is always empty (as seen in the console).

I tried both `module.exports` and `export default`, same result. I can see in the generated bundle there is an assignment to the correct variable, but the var is simple an empty object upon evaluation.

The bundled file start like this:
```js
var App =
/******/ (function(modules) { // webpackBootstrap
// ...
```

Also, the code inside works, since if I run the exported method in the script, it is executed.:
```js
function helloWorld(msg) {
  alert(msg || 'Hello World!');
}

helloWorld(); // this call is properly executed on every page load

// but neither this export works
module.exports = {
  helloWorld
}
// nor this one
export default helloWorld 
```

All I can do to make it work is `window.App = { helloWorld }` which I find a hack.

Any help is welcome.
And again, sorry for my level of JS (in)experience.

**Comment by JeffreyWay** [comment]
I'm pretty sure most developers assign it to the window, just like you demonstrated at the end of your comment. That's what I'd recommend.

**Comment by dakujem** [comment]
Okay, thank you for your time.

I'll stick to that for now.
