### ISSUE TITLE
Unknown argument: --hide-modules 

### ISSUE THREAD

**Issue by bcorcoran** [JeffreyWay/laravel-mix#2546]
Laravel Mix 6.0.0-beta.10
Node version 14.13.1
NPM version 6.14.8

--hide-modules (as listed in the scripts section of the docs for the master branch) brings up a webpack-cli error because the arg doesnt exist anymore.

**Comment by Aslam97** [comment]
Related to #2523

**Comment by bcorcoran** [comment]
I resolved it by removing the argument, so the actual issue is that the docs still include it as a recommendation.

**Comment by Urbanizacija69** [comment]
What argument did u remove?

**Comment by thecrypticace** [comment]
You can remove `--hide-modules`.

However, it is recommended that you use the mix executable. Please refer to the upgrade guide: https://github.com/JeffreyWay/laravel-mix/blob/628f6062cceb77610b1813e3179abcbd043a4642/UPGRADE.md

**Comment by CroitoriuDan** [comment]
how can i remove the --hide-modules?

**Comment by allandereal** [comment]
> how can i remove the --hide-modules?

From the package.json file on the development & production options under scripts.
