### ISSUE TITLE
TypeError: src.forEach is not a function with laravel-mix@0.6.0

### ISSUE THREAD

**Issue by iraklisg** [JeffreyWay/laravel-mix#255]
**What I did**
`yarn upgrade laravel-mix` from version 0.5.9 to version 0.6.0
Then I run 
 `npm run dev` 

**What was expected**
To be able to bundle the assets without errors, like when using v.0.5.9 (provided the same `webpack.mix.js` and `webpack.config.js` file)

**What I get**
 The following TyperError

```
/home/user/.nvm/versions/node/v7.4.0/bin/node /home/user/.nvm/versions/node/v7.4.0/lib/node_modules/npm/bin/npm-cli.js run dev

> @ dev /home/user/webApps/apptree2
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/home/user/webApps/apptree2/node_modules/laravel-mix/src/index.js:139
    src.forEach(file => {
        ^

TypeError: src.forEach is not a function
```
**Other steps**
I run `yarn add laravel-mix@0.5.9` and subsequently  `npm run dev` and the process successfully finished with `exit code 0`

**Comment by adriaanzon** [comment]
Are you, by any chance, running `mix.combine()` with a string as first argument? If so, it's probably because of this change: https://github.com/JeffreyWay/laravel-mix/commit/bd1d69c1d8de7c96a5fca275dc5549b5837105ca

**Comment by JeffreyWay** [comment]
Yeah, we need to see your webpack.mix.js file. You must pass an array as the first argument to `mix.combine()`.

**Comment by iraklisg** [comment]
@adriaanzon yes, that is true

@JeffreyWay below my webpack.mix.config 

```
let mix = require('laravel-mix');

// Extend laravel mix configuration to load .css files
mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.css$/,
                loader: 'style-loader!css-loader'
            }
        ]
    }
});

mix.combine('resources/assets/js/opendata/dataset_form.js', 'public/js/opendata/dataset_form.js')

```

By turning the source from string to array 
`mix.combine(['resources/assets/js/opendata/dataset_form.js'], 'public/js/opendata/dataset_form.js')`
the process is successfully finished

**Comment by adriaanzon** [comment]
In this case, `mix.copy()` instead of `mix.combine()` would have been more fitting

**Comment by iraklisg** [comment]
@adriaanzon indeed. However, I have to say that if the user simply wants to concatenate some scripts and then version them, both `mix.copy()` and `mix.combine()` are not a solution. It would be very helpful (especially for the users that previously used gulp and `laravel-elixir` in their projects) if this functionality was included in `laravel-mix`

**Comment by JeffreyWay** [comment]
I'm sure there's some Webpack loader that can allow us to version files that aren't part of the main bundle. 

PRs happily accepted, if anyone wants to research it.

**Comment by iraklisg** [comment]
@JeffreyWay I just opened a new issue #284 requesting this feature :stuck_out_tongue: Hopefully someone could provide some help with this
