### ISSUE TITLE
mix not found

### ISSUE THREAD

**Issue by apocalyarts** [JeffreyWay/laravel-mix#2550]
-   Laravel Mix Version: 6.0.0-beta.10
-   Node Version 12.14.1
-   NPM Version 6.13.6
-   OS: Windows 10

### Description:
I am on latest Laravel Homestead. Just did a fresh install of my Homestead box and updated the package.json of my project accordingly. When running npm run development I get this error:

sh: 1: mix: not found

### Steps To Reproduce:
npm run development

**Comment by iamthefreeman** [comment]
Hey, looks like a common issue people are having, @JeffreyWay has posted this reply to a similar issue: https://github.com/JeffreyWay/laravel-mix/issues/2523#issuecomment-704629653

**Comment by apocalyarts** [comment]
He doesn't even find the mix command, so I assume it is maybe a PATH related Windows VM issue?

**Comment by iamthefreeman** [comment]
Could be? 

What's your output of `npx mix -p` or `npx mix`

(might be worth taking a quick look over the upgrade docs: https://github.com/JeffreyWay/laravel-mix/blob/master/UPGRADE.md#update-your-npm-scripts)

**Comment by xxRockOnxx** [comment]
I am not sure how I'm able to replicate this but I got a new setup too and sometimes this happens. I just simply reinstall and it goes away.

When this happened I checked the laravel-mix in node_modules and it was empty and that's why `mix` wasn't found.

**Comment by Calinou** [comment]
I'm running into this issue as well, with both Node.js 12.18.0 and 14.3.0. OS is Fedora 33, and I made sure to remove `node_modules` before running `yarn` to install dependencies.

<details>
<summary>package.json</summary>

```json
{
  "private": true,
  "scripts": {
    "development": "mix",
    "doc": "redoc-cli bundle public/developer/v1/openapi.yaml && move-file redoc-static.html public/developer/v1/index.html",
    "hot": "mix --hot",
    "lint": "npm-run-all --sequential lint:css lint:ts",
    "lint:css": "stylelint \"resources/css/**/*.css\"",
    "lint:ts": "eslint \"resources/ts/**/*.ts\"",
    "production": "mix --production",
    "watch": "mix watch",
    "watch-poll": "mix watch -- --watch-options-poll=1000"
  },
  "dependencies": {
    "@barba/core": "^2.9.7",
    "autoprefixer": "^10.0.4",
    "balloon-css": "^1.2.0",
    "cross-env": "^7.0.3",
    "fork-awesome": "^1.1.7",
    "laravel-mix": "^5.0.9",
    "move-file-cli": "^2.0.0",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.1.14",
    "postcss-import": "^13.0.0",
    "postcss-nesting": "^7.0.1",
    "postcss-url": "^10.1.1",
    "redoc-cli": "^0.10.2",
    "resolve-url-loader": "^3.1.2",
    "tailwindcss": "^2.0.1",
    "ts-loader": "^8.0.11",
    "typescript": "^4.1.2",
    "vue-template-compiler": "^2.6.12",
    "webpack": "^5.9.0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.9.0",
    "@typescript-eslint/parser": "^4.9.0",
    "eslint": "^7.14.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-plugin-import": "^2.22.1",
    "husky": "^4.3.0",
    "stylelint": "^13.8.0",
    "stylelint-config-standard": "^20.0.0",
    "webpack-cli": "^4.2.0"
  },
  "eslintConfig": {
    "env": {
      "browser": true,
      "es6": true
    },
    "extends": [
      "airbnb-base",
      "eslint:recommended",
      "plugin:@typescript-eslint/eslint-recommended",
      "plugin:@typescript-eslint/recommended",
      "plugin:@typescript-eslint/recommended-requiring-type-checking"
    ],
    "rules": {
      "no-alert": "off",
      "no-unused-expressions": "off"
    },
    "globals": {
      "Atomics": "readonly",
      "SharedArrayBuffer": "readonly"
    },
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
      "project": "./tsconfig.json"
    }
  },
  "stylelint": {
    "extends": "stylelint-config-standard",
    "rules": {
      "at-rule-no-unknown": [
        true,
        {
          "ignoreAtRules": [
            "responsive",
            "screen",
            "tailwind",
            "variants"
          ]
        }
      ]
    }
  },
  "husky": {
    "hooks": {
      "pre-commit": "yarn lint && vendor/bin/php-cs-fixer fix --dry-run --diff"
    }
  }
}
```
</details>

**Comment by albertcito** [comment]
I had the same issue. And it works after run `npm install laravel-mix@latest`

**Comment by apocalyarts** [comment]
I am now on 6.0.9 and the issue persists.

**Comment by thecrypticace** [comment]
@apocalyarts Can you provide your package.json and package-lock.json / yarn.lock file? I can't think of any situation in which the mix binary wouldn't be installed unless explicitly disabled.

**Comment by apocalyarts** [comment]
@thecrypticace First of all: it is now working in my project and I don't know why. 

I was curious, if it had to to with me trying to run npm install natively on my Windows Machine, updating and restarting and so on. I tried to reproduce the error and it works like this:

On Homestead (via Virtualbox) on Windows 10:
```
composer create-project laravel/laravel example-app
cd example-app
npm install --no-bin-links
npm run dev

> sh: 1 : mix: not found
```

It looks like mix is not correctly installed/found when using Homestead. 

If I proceed to delete the node_modules folder and use CMD on Windows It's working:

```
cd c:\code\example-app
npm install
npm run dev
```

**Comment by thecrypticace** [comment]
It's not working because you're installing using `--no-bin-links`. This explicitly disables creation of the `node_modules/.bin` folder and will prevent scripts like webpack or mix from working.

**Comment by anthonyoride** [comment]
It's not working because dependencies in your package.json was'nt installed. run `npm cache clean --force` and try running npm install again

**Comment by zablik** [comment]
In my case, the problem was in a project directory where I ran the build. I've added time the directory name so it looked like
`my-project-12:23:34`.

Colons (":" symbols) caused this error `sh: 1 : mix: not found`

**Comment by SamKani92** [comment]
This is also happening to me. Fresh Laravel 8.12 installation. Don't have any colons in the folder name, Have tried clearing cache and reinstalling via both NPM and Yarn. Have tried updating Laravel Mix to the latest versions.

I'm using --no-bin-links because npm install never works without it.

Mix: Tried multiple 6,0 versions.
Node: 12.19.0
NPM: 7.6.3
OS: Windows 10

```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
    "devDependencies": {
        "axios": "^0.21",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "postcss": "^8.1.14"
    },
    "dependencies": {
        "bootstrap": "^5.0.0-beta2"
    }
}
```
This is ridiculous.

**Comment by ebenezerj** [comment]
> I had the same issue. And it works after run `npm install laravel-mix@latest`

After hours of trying other suggestions, this comment helped me resolve the issue. Thanks.

**Comment by camohub** [comment]
I have this issue if I **run npm install --production** on production server. It seems mix is included only for dev

**Comment by cyberorca** [comment]
> I had the same issue. And it works after run `npm install laravel-mix@latest`

it work, i'm using laravel 8 inside docker container via Laradock, thanks!

**Comment by KevinCastroP** [comment]
> I had the same issue. And it works after run `npm install laravel-mix@latest`

this works for me, thank's

**Comment by phpspider** [comment]
Is someone facing issues in js files that these are not minifying after this?
I use the following commands

- npm install laravel-mix@latest
- npm cache clean -f
- nvm install 12.14 //Upgrade nodejs version (12.14)
- npm run dev

**Comment by viraljetani** [comment]
> It's not working because you're installing using `--no-bin-links`. This explicitly disables creation of the `node_modules/.bin` folder and will prevent scripts like webpack or mix from working.

I was having the same issue while using a seperate node container in my docker environment and when removing '--no-bin-links' in my dockerfile config 'entrypoint: ['npm', '--no-bin-links']'

Thank you @thecrypticace

**Comment by mahesh1234** [comment]
> I had the same issue. And it works after run `npm install laravel-mix@latest`

I face this issue on i installed webpack on project.
running below resolved my issue.
`npm install laravel-mix@latest`

**Comment by sudeerax** [comment]
useful to review the Update to Mix 6 docs for any additional steps. 
https://laravel-mix.com/docs/6.0/upgrade

**Comment by OneMohrTime** [comment]
Laravel Mix wasn't the sole culprit for me. I was able to get around this by bumping `laravel-mix`, `sass-loader`, and `webpack` to their latest versions, detailed here: https://stackoverflow.com/questions/65718391/laravel-npm-command-mix-not-found/65720215#65720215

**Comment by felloz** [comment]
> npm cache clean --force

It didnt work
