### ISSUE TITLE
[6.*] Impossible to copy a directory

### ISSUE THREAD

**Issue by sdebacker** [JeffreyWay/laravel-mix#2551]
-   Laravel Mix Version: 6.0.0-beta.10
-   Node Version: v14.12.0
-   NPM Version: 6.14.8
-   OS: macOS 10.15.7

### Description:

Impossible to copy a directory

### Steps To Reproduce:

`mix.copy('node_modules/ckeditor4/skins', 'public/components/ckeditor4/skins');`

or 

`mix.copyDirectory('node_modules/ckeditor4/skins', 'public/components/ckeditor4/skins');`

run

`npx mix`

throws

`Promise rejection: Error: EISDIR: illegal operation on a directory, read`

**Comment by arcanedev-maroc** [comment]
Laravel Mix Version: 6.0.0-beta.10
Node Version: v12.18.3
NPM Version: 6.14.8
Yarn Version: 1.22.4
OS: Window 8.1

Same issue here !
