### ISSUE TITLE
[6.*] Dynamic import .version()

### ISSUE THREAD

**Issue by Eldair** [JeffreyWay/laravel-mix#2552]
-   Laravel Mix Version: 6.0.0-beta.10
-   Node Version: 14.13.0
-   OS: Ubuntu 20

### Description:
Using `mix.version()` option in combination with dynamic imports (`import(/* webpackChunkName: 'user' */ './pages/user.vue')`) will output files with version numbers in mix-manifest.json (`/js/main/users.js": "/js/main/users.js?id=8208cf4609cdc5b641cc`) but they are not referenced like so when dynamically loaded.
![image](https://user-images.githubusercontent.com/470003/95989798-05e1d180-0e2b-11eb-9155-c8147addc9ee.png)

If I add 
```
mix.webpackConfig({
        output: {
            chunkFilename: 'js/main/[name].js?id=[chunkhash]',
        },
    })
```
then files are loaded with version numbers (and those version numbers are not the same as ones in mix-manifest.json)
![image](https://user-images.githubusercontent.com/470003/95989955-39246080-0e2b-11eb-85da-246c1ac13da6.png)

Is this how it should be? Is there some preferred way of versioning chunks or I'm maybe missing something.

Also, I was using the `chunkFilename` option in v5 as well.

**Comment by thecrypticace** [comment]
1. We should definitely update this. Though I _think_ we should use `[contenthash]` not `[chunkhash]` but I'll have to verify first.
2. We should update mix manifest to use the same hash mechanism (if it doesn't already)

**Comment by amcsi** [comment]
I believe it was even mentioned in the Mix upgrade guide https://laravel-mix.com/docs/4.1/upgrade

> If your project heavily uses JavaScript dynamic imports, you may need to hold off until the release of webpack 5 early next year. There are known compile issues related to this that we cannot fix until then. Once webpack 5 is out, Mix will be updated shortly after. If you're unfamiliar with dynamic imports, then this very likely won't affect your project.

I thought that was referring to versioning not being supported for dynamic imports (thus the file can be cached stale). I kind of thought that Laravel Mix 6 would fix that, but maybe that warning line was actually referring to something else.

**Comment by arukompas** [comment]
Anyone has a temporary hack'ish workaround for cache-busting dynamic imports?

**Comment by Eldair** [comment]
@arukompas 
This should work
```
mix.webpackConfig({
    output: {
        chunkFilename: '[name].js?id=[contenthash]',
    },
});
```

**Comment by arukompas** [comment]
That worked for me, @Eldair , thanks! 💯

**Comment by amcsi** [comment]
It's great that there's a weboldal escape hatch for this. But it would still be nice if Mix did this automatically.

**Comment by Eldair** [comment]
This is not fixed.
