### ISSUE TITLE
[Feature request] extractToSeparateFiles()

### ISSUE THREAD

**Issue by hivokas** [JeffreyWay/laravel-mix#2554]
Right now there is an `extract()` method which extracts modules into a separate `vendor.js` file.
Does it make sense to introduce `extractToSeparateFiles()` (we may use another name) that extracts modules to separate files?

```js
mix.extractToSeparateFiles(['lodash', 'axios', 'moment'], 'js/modules');

// Will result in `js/modules/lodash.js` etc.
```

**Comment by thecrypticace** [comment]
I'm not sure. I think it's rather niche. I'd say it'd be more useful for us to experiment with some of webpack's auto vendor chunk splitting features in Mix 6.1.

As an aside I haven't updated the documentation (yet) but mix.extract() can now take an object:

```js
mix.extract({
    libraries: ['lodash', 'axis', 'moment'],
    // more options here
})
```

So we could extend that syntax to allow for separate file extraction **if** this is a feature we end up adding.
