### ISSUE TITLE
`import` without file extension causes error (6.0.0-beta.10).

### ISSUE THREAD

**Issue by yaquawa** [JeffreyWay/laravel-mix#2569]
-   Laravel Mix Version: 6.0.0-beta.10
-   Node Version : 14.11.0
-   NPM Version : 6.14.8
-   OS: MacOS

### Description:
After I updated to version 6.0.0-beta.10, 
***in the dependency codes(this time, the `graphql` package)***

this won't work:
```
import { foo } from './foo';
```

this works:
```
import { foo } from './foo.mjs';
```

### Steps To Reproduce:
webpack.mix.js
```js
mix.options({ processCssUrls: false })
    .vue({ version: 3 })
    .ts('resources/js/app.js', 'public/js')
```

app.js
```js
import Amplify, { Auth } from 'aws-amplify'


// error
// error  in ./node_modules/graphql/language/printer.mjs

// Module not found: Error: Can't resolve './visitor' in '/Users/Documents/htdocs/node_modules/graphql/language'
// Did you mean 'visitor.mjs'?
// ...
// ...
```

**Comment by thecrypticace** [comment]
This is because we don't have '.mjs' in our resolved extension list.

**Comment by yaquawa** [comment]
@thecrypticace Thanks for replying. I'm not a webpack export, would you tell me how to fix this? Thanks!

**Comment by thecrypticace** [comment]
Huh we do actually, I just checked. That's super weird. I'll take another look.

**Comment by yaquawa** [comment]
@thecrypticace Thanks man, hopefully it's an easy fix🤥

**Comment by AdrianMrn** [comment]
I'm getting the same error with `.tsx` files even though I'm using the `.ts()` and `.react()` methods in my mix config:
```js
mix.ts('resources/js/react/app.tsx', 'public/js/react').react()
```

I had to manually add the extension to make it work (this wasn't an issue before mix 6):
```js
mix.override((webpackConfig) => {
    webpackConfig.resolve.extensions.push('.tsx');
});
```

**Comment by sebastiansulinski** [comment]
Not sure if this is completely related but when registering vue components without `.vue` extension its is now also throwing the error saying `Module not found: Error: Can't resolve ...` example:

```javascript
Vue.component(
  'widget-component',
  require('../src/components/WidgetComponent').default
);
```

To make it work extension needs to be added:

```javascript
Vue.component(
  'widget-component',
  require('../src/components/WidgetComponent.vue').default
);
```

Not sure if this is a new desired behaviour, but I thought I'll add my findings to this issue :)

**Comment by thecrypticace** [comment]
@yaquawa
The issue with `aws-amplify` has to do with a breaking change in webpack 5 with how it handles imports of `.mjs` files. When importing an `.mjs` file you must specify an extension. This is likely an issue that should be brought up in the `aws-amplify` repo.

In the mean time you can use this to work around it:
```js
mix.webpackConfig({
  module: {
    rules: [
      {
        test: /\.mjs$/i,
        resolve: { byDependency: { esm: { fullySpecified: false } } },
      },
    ],
  },
})
```

@AdrianMrn: I cannot reproduce this with a simple App.tsx file. Can you open a separate issue with a reproduction repo?

**Comment by Tofandel** [comment]
@thecrypticace  The fix seems to have made it without `fullySpecified: false` which doesn't seem to be a good default, any reason why?
