### ISSUE TITLE
Improve error messages with Laravel Mix

### ISSUE THREAD

**Issue by vedmant** [JeffreyWay/laravel-mix#257]
Currently when something fails while compiling scss files it shows tons of error messages in node js modules yet nothing about what actually caused an error in scss file and on which line. Just to find what fails to compile I had to install and run Compass which shows actual error and line. Also it often silently fails to include files with wrong path. Is there any plans to improve error and warning messaging?

**Comment by JeffreyWay** [comment]
It actually does - 

https://www.dropbox.com/s/cltt3j82d3ar1m3/Screenshot%202017-02-01%2010.57.50.png?dl=0

But what's weird is that, if you're running the watcher, and make a syntax error, it doesn't show up in the terminal. It only shows up if you stop and start it up again...

Any ideas what that is, anyone?

**Comment by QWp6t** [comment]
Try using `webpack.NoEmitOnErrorsPlugin()` (formerly `webpack.NoErrorsPlugin()`), which should catch the error and prevent it from emitting, but the error will still display in the console.

(Note: I don't have much experience with webpack-dev-server, so there could be something else at play.)

**Comment by JeffreyWay** [comment]
@QWp6t So if the watcher is running, and you then make a Sass error, you see the exact place where the Sass syntax error occurred? I only see that on the first run.

**Comment by JeffreyWay** [comment]
I can get the errors to display if I turn on the `children` and `errors` stats, but the output isn't as pretty as before.

```js
    children: true,
    errors: true
```

**Comment by QWp6t** [comment]
Ohh, I get what you're saying. Yeah, I see ugly errors. Sorry, I wasn't even paying attention to what the errors actually said when I tested. I was just like yup error shows up. Works fine on my end.™ lol

This is something that could most likely be resolved by using the `additionalTransformers` option in `friendly-errors-webpack-plugin`, or perhaps it's something worth sending a PR to them about.
