### ISSUE TITLE
React + Typescript?

### ISSUE THREAD

**Issue by markbiek** [JeffreyWay/laravel-mix#2571]
-   Laravel Mix Version: 5.0.1
-   Node Version 12.18.2
-   NPM Version 6.14.5
-   OS: OSX 10.12.6

### Description:

Less of a bug and more a point of confusion. The docs clearly show how use Mix with React or use Mix with Typescript.

However, I can't find anything that seems to describe using React _and_ Typescript with Mix.

Is this possible? If it is and someone explains it to me, I'll be happy to submit a PR for a documentation update.

**Comment by JeffreyWay** [comment]
Does this work for you?

```
mix.ts('src/app.ts', 'dist').react();
```

**Comment by markbiek** [comment]
Here's what I've got:

```
mix.ts('resources/js/app.tsx', 'public/js')
	.react()
	.sass('resources/scss/app.scss', 'public/css')
	.version();
```

But I get an `mix.js() is missing required parameter 1: entry` error.

**Comment by markbiek** [comment]
Welp, it seems like it was an issue with my `tsconfig.json` and nothing to do with Mix at all.

This [tsconfig.json](https://gist.github.com/markbiek/cd1910dfdb4fc542cd6d74cb66e46c11) and this `webpack.config.js` did the trick

```
mix.ts('resources/js/app.tsx', 'dist/js')
	.sass('resources/scss/app.scss', 'public/css')
	.version();
```

**Comment by JeffreyWay** [comment]
Sorry, I didn't realize you were still on Mix v5. 

Once you upgrade to v6, you'll need to add `mix.react()` as well.

**Comment by markbiek** [comment]
Good to know, thank you!
