### ISSUE TITLE
[6.*] Will the config object be added in to the mix object in v6?

### ISSUE THREAD

**Issue by Nothing-Works** [JeffreyWay/laravel-mix#2573]
### Description:
This is really a question for v6, in v5 there is the config object being exported [here](https://github.com/JeffreyWay/laravel-mix/blob/v5/src/index.js#L68). It's very handy especially for plugin development, I can get config simply call `mix.config`.

It's not in v6 atm, just wondering any chance to add it back(would take pr?)? If not what's the easier way to get the config in v6?

**Comment by Levivb** [comment]
`global.Config` should work I suppose

**Comment by JeffreyWay** [comment]
@Nothing-Works That has been deprecated for over a year now. You can use the global Config object like @Levivb.

But - I may add it back in for the official Mix 6 release. I'm worried about older plugins breaking.

**Comment by Nothing-Works** [comment]
@Levivb @JeffreyWay Thank you all, I am ok to use `global.Config`, it's not a big change for my plugins.
