### ISSUE TITLE
[6.*] npm run watch issue

### ISSUE THREAD

**Issue by vortechron** [JeffreyWay/laravel-mix#2574]
v6 does not watch any file changes in node_modules, but the previous version does

**Comment by vortechron** [comment]
just found out that v6 ignore node_modules by default

```
        watchOptions: {
            ignored: /node_modules/
        }
```

but how to override this thing?

already did this, still not work
```
mix.webpackConfig({
   watchOptions: {
      ignored: []
   }
});
```

**Comment by thecrypticace** [comment]
What's the use case for _not_ ignoring files inside node_modules?

**Comment by vortechron** [comment]
@thecrypticace I've created a few npm packages and watching node_modules allow me to `temporarily` modify or test some codes instead of publishing it to npm, the previous version has saved me a lot of times tha re-run `npm run watch`

is there any way to disable it for my case?

**Comment by thecrypticace** [comment]
I would expect what you posted to work to override the config. 🤔

**Comment by vortechron** [comment]
@thecrypticace sadly still not work.. 😢

**Comment by JeffreyWay** [comment]
Yeah - it won't do that due to the merge strategy we use. I'll fix.

**Comment by vortechron** [comment]
@JeffreyWay tq jeff

**Comment by JeffreyWay** [comment]
In the meantime, you can always use `mix.override()` to override the webpack config entirely.

```
mix.override((config) => {
    config.watchOptions = {
        ignored: [],
    };
});
```

**Comment by JeffreyWay** [comment]
Actually, this is a unique case. I'm not sure that it's worth adding a custom merge strategy. `mix.override()` is the easier option.

**Comment by vortechron** [comment]
@JeffreyWay unfortunately, using mix.override will cause `npm run watch` to exit after `[webpack-cli] watching files for updates...`

😭

**Comment by JeffreyWay** [comment]
Try deleting it completely.

https://github.com/JeffreyWay/laravel-mix/commit/53ffe9f59d654ad5047daee00f003608b2d440b5

**Comment by vortechron** [comment]
@JeffreyWay tq jeff, cli not exited, but any changes to node_modules does not reflect, any idea? ... hm weird 🤔

**Comment by vortechron** [comment]
@JeffreyWay it detects changes but does not reflect inside output file..

**Comment by risingphoenix** [comment]
### Setup:
Laravel Mix Version: v6.0.10
Node Version: v12.19.0
NPM Version: v6.14.8
OS: Windows 10

### Description

I'm in the same situation of vortechron

I have tried the following configurations, but nothing happens

```
// using glob to exclude only my package
mix.webpackConfig({ watchOptions: { ignored: 'node_modules/!(my-package)*' } })

// ignore nothing
mix.webpackConfig({ watchOptions: { ignored: [] })
```

Any changes made, even in the sources (not in vendor), are not bundled into the final file...
sometimes the changes seem to be detected (the cli window with the recap tableppears to "refresh"), but the produced file is not modified, it has always the same timestamp

Only the following configuration works, but the watch is only on my sources, the changes in my package are not tracked.

```
// ignore with regexp that shouldn't match any of my node_modules folder
mix.webpackConfig({ watchOptions: { ignored: /nothing/ })
```

Hope it helps...

**Comment by jwohlfert23** [comment]
I'm having the same issue as @risingphoenix. It's detecting the changes, but not bundling those changes into the outputted file.

**Comment by risingphoenix** [comment]
@jwohlfert23 i am currently using this configuration
```
mix.webpackConfig({ watchOptions: { ignored: /node_modules([\\]+|\/)+(?!my-package)/ }});
```
every changes are detected but not inserted in the compiled watched js,
even with the command specified by @JeffreyWay nothing changes
```
mix.override((config) => {
	config.watchOptions = {
		ignored: /node_modules([\\]+|\/)+(?!my-package)/,
	};
});
```
very frustrating run every time `npm run dev`

**Comment by chototoro** [comment]
Probably a bit late, but i just encountered the same problem (changes detected, but not included in the build), and finally found a solution, thanks to [this comment](https://github.com/webpack/webpack/issues/11612#issuecomment-705790881), and [this one](https://github.com/webpack/webpack/issues/1866#issuecomment-284571531).

I ended up with the following configuration:
```
mix.webpackConfig({
    resolve: {
        symlinks: false
    },
    snapshot: {
        managedPaths: []
    },
    watchOptions: {
        ignored: /node_modules([\\]+|\/)+(?!my-linked-local-package)/
    }
});
```
Changes made inside the linked local package, now correctly triggers a new build, including these changes 👍

**Comment by risingphoenix** [comment]
Many thanks @chototoro, great solution!

My way of bypassing the problem was to create a local version, and perform an import on that file instead of the one in node_modules. Then make the changes and then publish it on the repository.

**Comment by darekf77** [comment]
@chototoro I've got half success with your solution:
- hot reload for node_modules work 100% PERFECT
- but if I reload the page -> I am getting old version of file (without current node_modules/<my-package> changes)
