### ISSUE TITLE
Versioning static image assets

### ISSUE THREAD

**Issue by sudotribe** [JeffreyWay/laravel-mix#258]
With Elixir we could pass an array of files to version and compile to /public/build.

`.version(['css/app.css', 'js/app.js', 'images/**/*.*']);`

How do we do this with Mix? Seems like the version() function doesn't have params, and only versions css/js files.

**Comment by JeffreyWay** [comment]
Yeah - for Mix, the `version()` method is only applied to files in your main bundle. So it works differently now.

**Comment by pablopaul** [comment]
@JeffreyWay Is there a way to handle image and font assets with Mix and cachebusting right now?
