### ISSUE TITLE
Mix has rewritten and broken CSS

### ISSUE THREAD

**Issue by james090500** [JeffreyWay/laravel-mix#2585]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`): 5.0.7
-   Node Version (`node -v`): v12.18.4
-   NPM Version (`npm -v`): 6.14.6
-   OS: Windows 10

### Description:
Laravel mix seems to be rewritting my SASS into broken CSS. I have pulled the code i've noticed and prettyfied it so you can tell. As you can see below, the opacity levels all go to 1%. 
![image](https://user-images.githubusercontent.com/20372645/97372607-eb3c3d80-18ab-11eb-88ee-6fec65bef07a.png)

### Steps To Reproduce:
I am really unsure, it seems to have happened only for this code and not any other of my keyframes.

**Comment by james090500** [comment]
On some further testing. I created a simple ``app.scss`` file with the following code

```
.cycle {
    animation: cycle 1s infinite;
}

@keyframes cycle {
    0% {
        opacity: 100%;
    }

    50% {
        opacity: 70%;
    }

    100% {
        opacity: 100%;
    }
}
```

and a ``webpack.mix.js`` with this

```
mix.js("resources/js/app.js", "public/js")
    .sass("resources/sass/app.scss", "public/css")
    .copyDirectory("resources/images", "public/images")
    .version();
```

And the issue still occurs.

**Comment by thecrypticace** [comment]
It doesn't look like autoprefixer is the culprit here from what I can tell at a glance. Perhaps Sass is? In the mean time the likely cause is using percentages for opacity instead of decimals. Try `opacity: 0.5` instead of `opacity: 50%`

**Comment by james090500** [comment]
> It doesn't look like autoprefixer is the culprit here from what I can tell at a glance. Perhaps Sass is? In the mean time the likely cause is using percentages for opacity instead of decimals. Try `opacity: 0.5` instead of `opacity: 50%`

Using decimals seems to work,

SCSS
```
.cycle {
    animation: cycle 1s infinite;
}

@keyframes cycle {
	0% {
		opacity: 1;
	}

	50% {
		opacity: 0.7;
    }

    100% {
        opacity: 1;
    }
}
```

Compiled:
```
.cycle {
    -webkit-animation: cycle 1s infinite;
    animation: cycle 1s infinite
}

@-webkit-keyframes cycle {
    0% {
        opacity: 1
    }

    50% {
        opacity: .7
    }

    to {
        opacity: 1
    }
}

@keyframes cycle {
    0% {
        opacity: 1
    }

    50% {
        opacity: .7
    }

    to {
        opacity: 1
    }
}
```

**Comment by JeffreyWay** [comment]
Yeah this is a Sass and CSS thing. I believe it will automatically round the value if you set it higher than 1 (which is already equivalent to 100%) This isn't a Mix bug.
