### ISSUE TITLE
Mix removing duplicate CSS lines

### ISSUE THREAD

**Issue by danielgoodwin97** [JeffreyWay/laravel-mix#2586]
-   Laravel Mix Version: laravel-mix@5.0.5
-   Node Version: v15.0.1
-   NPM Version : 7.0.3
-   OS: Ubuntu 20.04

### Description:
I'm having an issue with what I believe is the `postcss-discard-duplicates`. I'm trying to remove or at least disable it and I'm not having any luck.

The reason I need to disable this is because when creating gradients, you need to add fallbacks for other browsers. For example:
```
.foo
    background: -moz-linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(0,212,255,1) 100%);
    background: -webkit-linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(0,212,255,1) 100%);
    background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(0,212,255,1) 100%);
```

However, with `postcss-discard-duplicates` being on, it removes everything before the last line, meaning that gradients won't work on certain browsers.

I'm figuring I can probably configure mix to not remove duplicates somehow but I've been searching and I can't seem to find anything.

I have also tried removing the module with npm but that just wipes my lock file which is fun.

**Comment by JeffreyWay** [comment]
You shouldn't need to manually add all of those prefixes. If necessary, Autoprefixer will add and remove them automatically based on the Browserlist settings.
