### ISSUE TITLE
extractStyles not working as intended with css in vue components

### ISSUE THREAD

**Issue by sujit-baniya** [JeffreyWay/laravel-mix#2589]
-   Laravel Mix Version: 6
-   Node Version (`node -v`): 14.15.0
-   NPM Version (`npm -v`): 6.14.8
-   OS: Ubuntu 18

### Description:
Laravel mix is unable to extract css from vue component and throwing error.

webpack.mix.js
```js
let mix = require('laravel-mix');
const del = require('del');
const tailwindcss = require('tailwindcss');

del('./public');
mix
    .setPublicPath('public')
    .webpackConfig({
        optimization: {
            providedExports: false,
            sideEffects: false,
            usedExports: false
        }
    })
    .js('resources/src/js/app.js', 'public/js/')
    .sass('resources/src/sass/vendor.scss', 'css')
    .sass('resources/src/sass/landing.scss', 'css')
    .sass('resources/src/sass/app.scss', 'css')
    .copyDirectory('resources/src/img', './public/img')
    .copyDirectory('resources/src/font', './public/font')
    .copy('resources/src/favicon.ico', './public/favicon.ico')
    .vue({
        extractStyles: true
    })
    .options({
        processCssUrls: false,
        postCss: [tailwindcss('./tailwind.config.js')]
    }).extract();
```
Vue component:
```vue
<template>
  <div class="relative w-12 my-1 cursor-pointer" @click="toggle">
    <div v-if="isEnabled" class="w-12 h-8 rounded-full" :class="color">
      <div
        class="absolute top-0 flex items-center justify-center w-6 h-6 mt-1 -ml-6 bg-white border-gray-300 rounded-full transition-all transform ease-linear duration-100 shadow-toggle left-96"
      ></div>
    </div>

    <div v-if="!isEnabled" class="w-12 h-8 bg-gray-300 rounded-full">
      <div
        class="absolute top-0 flex items-center justify-center w-6 h-6 mt-1 bg-white border-gray-300 rounded-full transition-all transform ease-linear duration-100 shadow-toggle left-4"
      ></div>
    </div>
  </div>
</template>

<script>
export default {
  name: "ToggleSwitch",
  model: {
    prop: "isEnabled",
    event: "toggle",
  },
  props: {
    isEnabled: Boolean,
    color: {
      type: String,
      required: false,
      default: "bg-green-600",
    },
  },
  methods: {
    toggle() {
      this.$emit("toggle", !this.isEnabled);
    },
  },
};
</script>

<style scoped>
.shadow-toggle {
  box-shadow: 1px 0px 2px 1px rgba(0, 0, 0, 0.1),
    -1px 1px 4px 1px rgba(0, 0, 0, 0.06);
}

.left-4 {
  left: 4%;
}

.left-96 {
  left: 96%;
}
</style>
```

When running the mix command for watch and visiting the page gave following error:
![image](https://user-images.githubusercontent.com/4959215/97775898-680d3700-1b8c-11eb-891f-cb6bcfbe1913.png)

What is the possible solution to above?

**Comment by thecrypticace** [comment]
It appears that this has to do w/ style extraction + use of async components. I'll take a look today.

**Comment by sujit-baniya** [comment]
@thecrypticace Did you get chance to look into it?

**Comment by Daniel4Digital** [comment]
I've a similar problem. In my case, if I use:
extractVueStyles: '[name].css',

it works perfectly but it created on the wrong folder, so at public/js/app.css and public/js/vendor.css

My first code attemplt was:
extractVueStyles: 'public/js/vue.css', 

But that would create a vue.css with only the content of vendor.css, the app.css seems to be overwritten by the vendor one

So for now, I'm using extractVueStyles: '[name].css', since it works with the only inconvenient of having the css on a js folder.

best regards

**Comment by alexmccabe** [comment]
@Daniel4Digital This pointed me in the direction as to why something isn't working. When using `extractVueStyles: 'path/to/filename.css` the vendor css is just straight up ignored. When setting to `extractVueStyles: [name.css]` it outputs the vendor styles, but in the JS directory. Which is _fine, I guess 🤷 _. Frustrating though. I'd like for a vendor css file to be generated regardless.

**Comment by roitto** [comment]
Any fixes to this?

If i apply 

```
.vue({
    extractStyles: 'app.css',
})
```

in laravel mix vue options, the webpack tries to load chunk called "app.js" when trying to load dynamically imported components.

**Comment by thecrypticace** [comment]
So I've confirmed that async components + style extraction doesn't work properly. If I tell webpack to only extract styles for non-async components things work fine but that's definitely not ideal.

**Comment by Daniel4Digital** [comment]
Today I updated to laravel mix 6 (Saw today too that this issue regards version 6) and try to use vue({
    extractStyles: 'css/app.css'
  })
  
And the app.css is now on the correct folder, but the vendor.css still goes to js folder no matter what.

Even if I use extractStyles: true, the vendor.css still goes to js folder.

Dunno if related to this issue no more. But well.

**Comment by sebastiaanluca** [comment]
In v6, this builds a vendor.css file in `public/styles` but also a main.css file in `public/scripts` (?? 😄):

```js
mix.js('resources/scripts/main.js', 'public/scripts/main.js').vue({extractStyles: 'public/styles/vendor.css'})
```

**Comment by roitto** [comment]
Also when using 
.vue({
    extractStyles: '[name].css',
})

in laravel mix vue options, the build output is a plain "[name].css" file. In laravel-mix 5, the css file was created using the input scripts name

**Comment by rw4lll** [comment]
Faced with the same problem. In my case scss block in single file components was not extracted. After some investigation, this workaround has helped me:
`.js('resources/js/tool.js', 'js').vue({
        extractStyles: true,
        loaders: {
            js: 'buble-loader',
            scss: 'vue-style-loader!css-loader!sass-loader'
        }
    })`

**Comment by roitto** [comment]
If i had two different "main" scripts in my webpack.mix.js config:

```
.js('foo.js')
.js('bar.js')
```

and if I had set option: `extractVueStyles: '[name].css'`

The laravel mix bundled files like this:

```
- foo.js
- foo.css <- contains styles only for the foo.js
- bar.js
- bar.css <-- contains styles only for the bar.js
```

Now if I use the newer Laravel mix version with `.vue({ extractStyles: '[name].css'})`

It generates files like this:

```
- foo.js
- bar.js
- [name].css  <- contains both foo.js styles and bar.js styles and the css extracting does not work like it used to :(

```

If i try to use `.vue({ extractStyles: true})`

it generates files like this:


```
- foo.js
- bar.js
- vue-styles.css <- contains both foo.js styles and bar.js styles :(

```


Is there still any workarounds for this?

**Comment by jakedowns** [comment]
I, too, am curious how i can configure laravel-mix `6.0.43` to extract styles to per-vue-component sheets. in our large webapp, i don't want to load all of them in a single vendor.css, but rather a [name].css per module (both sync and async modules)

ideally i could use something like:

`extractStyles: '[name].css?id=[chunkhash]'`

seems like no matter what string value i set `vue.extractStyles` to, it always outputs `vendor.css` (tho looking at the sourcecode, it seems like the default should be [name].css? so maybe something else in my config is messing things up)
`extractStyles: 'extracted-styles.css',` => `public/dist/vendor.css`

https://github.com/laravel-mix/laravel-mix/blob/6ee2985e3597eb097df8f3e40032b1768f567e51/src/components/CssWebpackConfig.js#L178-L185

also, i'm unclear if `useVueStyleLoader` should be used in this case or not.

**Comment by trd-warren** [comment]
In my case.

I have components with `<styles></styles>` in it.
I am trying to achieve is those  `<styles></styles>` should only be used when the component is used.
I registered each component globally.

Example.
```
CompanyList.vue
ProjectList.vue
```

each component have `<styles></styles>`  in it, 
when I used  `<company_list />` , styles from `<project_list />` is included. :(

```js
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .vue({
      version: 2
   })
   .version();
```

Is there any workaround?
Component styles should not be extracted or put to `app.css`

**Comment by vilbergs** [comment]
> In my case.
> 
> I have components with `<styles></styles>` in it. I am trying to achieve is those `<styles></styles>` should only be used when the component is used. I registered each component globally.
> 
> Example.
> 
> ```
> CompanyList.vue
> ProjectList.vue
> ```
> 
> each component have `<styles></styles>` in it, when I used `<company_list />` , styles from `<project_list />` is included eventhought not called in the page. :(
> 
> ![image](https://user-images.githubusercontent.com/36871215/168271065-54187116-42ce-4ca8-adbf-a2e13dbf55a0.png)
> 
> ```js
> mix.js('resources/assets/js/app.js', 'public/js')
>    .sass('resources/assets/sass/app.scss', 'public/css')
>    .vue({
>       version: 2
>    })
>    .version();
> ```
> 
> Is there any workaround? Component styles should not be extracted or put to `app.css`

I'm not sure if your problem is related to this issue. You might want to look into overwriting https://github.com/webpack-contrib/style-loader with webpack override option.

If registering components locally or registering them as async components fixes your problem, that is the approach I would take instead of messing with the style-loader.
