### ISSUE TITLE
Separate tasks

### ISSUE THREAD

**Issue by SergeyMiracle** [JeffreyWay/laravel-mix#259]
I do not know if it's right place to ask, but i can't figure out how to make separate tasks with mix..

With elixir i did 
```
const args = require('yargs').argv

if (args.client) {
  elixir(function (mix) {
     mix.js(client files)
  })
}

if (args.admin) {
  elixir(function (mix) {
    mix.js(admin files)
  })
}
```
But now yargs not working...

**Comment by adriaanzon** [comment]
Not sure if this is possible, but does it help when you precede the arguments with `--`?

e.g. `npm run dev -- --client`

**Comment by adriaanzon** [comment]
also see #98

**Comment by SergeyMiracle** [comment]
@adriaanzon this gives an error - `npm run dev -- --client`

Ok i see, no separate tasks... I guess i have to think something else
