### ISSUE TITLE
Multiple sass usage

### ISSUE THREAD

**Issue by levipadre** [JeffreyWay/laravel-mix#2590]
-   Laravel Mix Version: 5.0.7
-   Node Version 12.18.3
-   NPM Version 6.14.6
-   OS: macOs Catalina v10.15.7

I would like to know if it's possible to avoid this kind of multiple settings:
```
mix.sass(paths.src.scss + '/style.scss', paths.dev.css)
.sass(paths.src.scss + '/style-dark.scss', paths.dev.css)
```
and use something like this instead:
`mix.sass(paths.src.scss + '/*.scss', paths.dev.css)`

It gives me this error, if it helps:
```
ERROR in multi ./node_modules/laravel-mix/src/builder/mock-entry.js ./src/scss
Module not found: Error: Can't resolve '/Users/foo/html/src/scss' in '/Users/foo/html'
 @ multi ./node_modules/laravel-mix/src/builder/mock-entry.js ./src/scss mix[1]

```

**Comment by thecrypticace** [comment]
No, that is not possible. You can likely use the glob package to achieve what you want. Try something like this:

```js
let glob = require('glob')

for (let path of glob(`${paths.src.scss}/*.scss`)) {
  mix.sass(path, paths.dev.css)
}
```

**Comment by levipadre** [comment]
Thanks for the info @thecrypticace .
I tried, but I got an error:
`glob is not a function or its return value is not iterable`
Any idea what can be the problem?

**Comment by bekahmcdonald** [comment]
For anyone finding this later, you likely need to call `glob.sync()` (instead of just `glob`) which will return an array that you can iterate over.

```javascript
const glob = require('glob');

glob.sync(`${paths.src.scss}/*.scss`).forEach((file) => {
  mix.sass(file, paths.dev.css);
})
```
