### ISSUE TITLE
How to preserve whitespace using Mix 6 and Vue 3?

### ISSUE THREAD

**Issue by martinbean** [JeffreyWay/laravel-mix#2594]
-   Laravel Mix Version: 6.0.0-beta.11
-   Node Version: 12.16.3
-   NPM Version: 6.14.4
-   OS: macOS Catalina 10.15.7

### Description:
As per comment on #2463, whitespace is removed from web pages if I compile JavaScript that contains Vue 3 components, making web pages look awful.

### Steps To Reproduce:
Use Sass with Vue 3. This is my **webpack.mix.js** file:
```js
const mix = require('laravel-mix');

mix
    .sass('resources/sass/admin.scss', 'public/css')
    .sass('resources/sass/app.scss', 'public/css')
    .js('resources/js/admin.js', 'public/js')
    .js('resources/js/app.js', 'public/js')
    .ts('resources/ts/club.ts', 'public/js')
    .vue()
    .options({
        processCssUrls: false
    })
    .sourceMaps()
    .version();

if (mix.inProduction()) {
    mix.disableNotifications();
}
```
When compiled, whitespace between inline elements is “collapsed” in the browser. Happens if I run both `npm run dev` and `npm run prod`.

**Comment by thecrypticace** [comment]
This is a Vue 3 problem, see: https://github.com/vuejs/vue-next/pull/1600

Closing as this not an issue with Mix.
