### ISSUE TITLE
Standalone mix is resulting in a 'Unknown argument: -'

### ISSUE THREAD

**Issue by zandervandermeer** [JeffreyWay/laravel-mix#2595]
-   Laravel Mix Version: 6.0.0-beta.11
-   Node Version (`node -v`): v15.0.1
-   NPM Version (`npm -v`): 7.0.3
-   OS: OSX 10.15.7

### Description:
When running `npm run development` and `npm run watch` the following error is popping up. The related issues here are all different because they show the actual flag that is missing. This is a standalone installation without Laravel so the link that has been referenced in #2559 isn't working. (https://github.com/JeffreyWay/laravel-mix/blob/e2566fba47b12f40753e41a7da697553abb3ecfa/UPGRADE.md#update-your-npm-scripts)

### Steps To Reproduce:
- `npm install`
- `npm run development`

package.json
```
{
  "name": "ProductGuide",
  "version": "1.0.0",
  "description": "company/module-productguide",
  "main": "index.js",
  "devDependencies": {
    "@vue/compiler-sfc": "^3.0.2",
    "cross-env": "^7.0.2",
    "laravel-mix": "^6.0.0-beta.11",
    "resolve-url-loader": "^3.1.0",
    "sass": "^1.28.0",
    "sass-loader": "^8.0.2",
    "vue-loader": "^16.0.0-beta.8",
    "webpack": "^5.3.2",
    "webpack-cli": "^4.1.0"
  },
  "scripts": {
    "development": "mix",
    "watch": "mix watch",
    "watch-poll": "mix watch -- --watch-options-poll=1000",
    "hot": "mix watch --hot",
    "production": "mix --production"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "vue": "^3.0.2"
  }
}
```

webpack.mix.js
```
// webpack.mix.js

let mix = require('laravel-mix');

mix.js('view/adminhtml/assets/js/app.js', 'view/adminhtml/web/js/app.js').vue()
.sass('view/adminhtml/assets/scss/app.scss', 'view/adminhtml/web/css/app.css');
```

![image (11)](https://user-images.githubusercontent.com/16645105/97994716-e1539680-1de5-11eb-8597-d9e74b85f486.png)

```
npm run development
> ProductGuide@1.0.0 development
> mix
[webpack-cli] Unknown argument: -
[webpack-cli] Unknown argument: ../node_modules/laravel-mix/setup/webpack.config.js
? Which flags do you want to use? …
✔ --entry: The entry point(s) of your application e.g. ./src/main.js
✔ --config: Provide path to a webpack configuration file e.g. ./webpack.config.js
✔ --color: Enable/Disable colors on console
✔ --merge: Merge two or more configurations using webpack-merge e.g. -c ./webpack.config.js -c ./webpack.test.config.js --merge
✔ --progress: Print compilation progress during build
✔ --help: Outputs list of supported flags
✔ --output-path: Output location of the file generated by webpack e.g. ./dist/
✔ --target: Sets the build target e.g. node
✔ --watch: Watch for files changes```

**Comment by thecrypticace** [comment]
I can't reproduce this with the webpack.mix.js + package.json file provided. Any more details you can provide? You can also try trashing your node_modules folder (and maybe your package-lock.json file) and trying again.

**Comment by zandervandermeer** [comment]
@thecrypticace thank you for your reply! :)

Trashing node_modules and removing package-lock.json and/or running npm update are all things we've tried already. This makes me believe that it isn't directly related to Mix, but of course something is still up.

Oddly enough we got it "working" on this environment when we _reverted_ the package.json scripts. So on this environment we went from:
```
"scripts": {
    "development": "mix",
```
to:
```
"scripts": {
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
```
and that seemed to work, but on other environments this does break.

**Comment by thecrypticace** [comment]
That's very strange because webpack-cli no longer has a ` --hide-modules` option which makes me think an old version of webpack-cli is being used somehow (even though you're specifying 4.1 in your dev deps). Could you post a gist of your lock file?

**Comment by zandervandermeer** [comment]
@thecrypticace I do agree with you that it is strange, it's why I opened this issue 😅

Please see the attached lock file

https://gist.github.com/zandervandermeer/be04f611e561a4197238907f874685c5

**Comment by zandervandermeer** [comment]
I am not sure if this problem should be closed, the issue hasn't been resolved yet. 

If this is outside of the scope then we will switch away from Mix for this project, but it definitely isn't stale :)
