### ISSUE TITLE
Sourcemaps don't work according to types or docblock

### ISSUE THREAD

**Issue by roelofr** [JeffreyWay/laravel-mix#2600]
-   Laravel Mix Version: `6.0.0-beta.11`
-   Node Version (`node -v`): `v14.15.0`
-   NPM Version (`npm -v`): `6.14.8`
-   Yarn version (`yarn -v`): `1.22.5` 
-   OS: `Ubuntu 20.04.1 LTS`

### Description:

I noticed some weird behaviour surrounding source maps.

First off, the Typescript (and therefore IDE-autocomplete) wrongly suggests `sourceMaps`, while `sourcemaps` is expected in the config. It also specifies `sourceMaps` to be a boolean, and the same mistake is in `src/config.js`, while  `false`  is [a valid devtool][1] but `true` is not. 

This also means a simple `sourcemaps: !mix.inProduction()` won't work, but would require a ternary expression.

Maybe I'm doing this entirely wrong (is there a `mix.sourcemaps` API?), but it should be fixed nevertheless.

As a list:

- `src/config.js` and the actual code uses `sourcemaps`
- `sourcemaps` should be false or [a valid devtool][1].
- `typings/index.d.ts` contains `sourceMaps?: boolean`, should be `sourcemaps?: (false|string)` (or something, I don't know Typescript).
- Maybe `sourcemaps: true` should evaluate to using the `source-map` devtool.

[1]: https://webpack.js.org/configuration/devtool/#root

### Steps To Reproduce:

1. Install `laravel-mix@next`

#### Expected behaviour with IDE-autocomplete (VS Code):

2. Make a `webpack.mix.js`:
```js
const mix = require('laravel-mix')
// …
mix.options({
  sourceMaps: !mix.inProduction()
})
```

##### Expected result:

- on dev build: source maps are created
- on prod build: no source maps are created.

##### Actual result

No source maps are ever created.

#### Expected behaviour using `src/config.js` as leading

2. Make a `webpack.mix.js`:
```js
const mix = require('laravel-mix')
// …
mix.options({
  sourcemaps: !mix.inProduction()
})
```

##### Expected result:

- on dev build: source maps are created
- on prod build: no source maps are created.

##### Actual result

- on dev build: build fails.
- on prod build: no source maps are created.

### Workaround

There is, of course, a simple workaround:

```js
const mix = require('laravel-mix')
// …
mix.options({
  sourcemaps: mix.inProduction() ? false : 'source-map'
})
```

**Comment by thecrypticace** [comment]
Yeah the types are wrong here. I need to do a full audit of the typescript types to make sure everything is correct. As I understand it the intended behavior is to use `mix.sourceMaps()` and not the config option.
