### ISSUE TITLE
[6.*] Passing options after 'mix' results in 'error: unknown option'

### ISSUE THREAD

**Issue by arjendejong12** [JeffreyWay/laravel-mix#2604]
-   Laravel Mix Version: 6.*
-   Node Version: 14.13.1
-   NPM Version: 6.14.8
-   OS: Windows 10 20H2

### Description:
I'm using `const argv = require("yargs").argv;` in my `webpack.mix.js` to do different things based on my custom `--theme` argument.
This was working fine with the 'old' `package.json` scripts, but when I try to convert them to [the following scripts](https://github.com/JeffreyWay/laravel-mix/blob/master/UPGRADE.md#update-your-npm-scripts), I get the following error:
```
$ mix --theme scriptware
error: unknown option '--theme'
```
Is it still possible to pass options to `webpack.mix.js` with the Mix CLI?

**Comment by thecrypticace** [comment]
So you can pass through options to webpack CLI using `mix -- --option=value` however your usage, unfortunately, will not work with webpack-cli 4. I recommend using environment vars instead.

You run the script like so: `THEME=scriptware mix`
And in your `webpack.mix.js` file you check the theme using `process.env.THEME`

**Comment by nickwelsh1** [comment]
asdf

**Comment by nickwelsh1** [comment]
If I'm reading correctly, @thecrypticace said that with webpack-cli 4 pass through options will not work. 
But I did a basic test with Webpack 5.53.0 including webpack-cli ^4.8.0 and it seemed to accept pass through options without error?

In my **Laravel Mix 6** project I'm getting the same error as @arjendejong12 
```
$ yarn dev --env=foo
error: unknown option '--env=foo'
```

**Comment by thecrypticace** [comment]
You would have to run that like `yarn dev -- -- --env=foo` — But this does *not* set process.env vars which is what I was referring to.

**Comment by CaelanStewart** [comment]
Yeah I'm having an issue with this. Why has this been closed? None of the solutions I have found have worked so far with Laravel Mix 6.

```
$ mix --production --ieCompat=true
error: unknown option '--ieCompat=true'
error Command failed with exit code 1.
```


```
$ mix --production -- --ieCompat=true
[webpack-cli] Error: Unknown option '--ieCompat=true'
```

And of course if I add in another `--` it doesn't appear in process.env at all, as @thecrypticace.

@thecrypticace – is that environment variable approach, is that cross platform?

**Comment by CaelanStewart** [comment]
Found an arrangement that works:

```
$ mix --production -- -- --env.ieCompat=true
```

Then use `yargs` to parse:

```

const { argv } = require('yargs');
const yargs = require('yargs/yargs');

...

console.log(yargs().parse(argv._));
```

Which gives:

```
{
  _: [],
  env: { ieCompat: 'true' },
  '$0': '/Users/[redacted]/node_modules/.bin/webpack'
}
```
