### ISSUE TITLE
Standalone : Mix not found

### ISSUE THREAD

**Issue by christophe-44-27** [JeffreyWay/laravel-mix#2607]
-   Laravel Mix Version: 5.0.9
-   Node Version (`node -v`): 12.5.0
-   NPM Version (`npm -v`): 6.9.0
-   OS: Windows 10

### Description:
After add laravel mix in standalone mode, i run "npx mix" like the documentation said, but i received only this :
λ npx mix
npx: installed 1 in 1.226s
command not found: mix

### Steps To Reproduce: 
Install laravel mix in a vue cli app, in standalone mode, that's it.

Regards,
Christophe

**Comment by thecrypticace** [comment]
The mix CLI is only available in Mix v6 which is not yet out of beta. You can grab the scripts to use for Mix 5.x from here: https://github.com/laravel/laravel/blob/d9e85605cbc491e710d9a2df1939ba2db773b404/package.json

**Comment by christophe-44-27** [comment]
Oh, good to know, but i've don't talk about my "Vue Version", i'm using vue-cli, so i don't have this : 

`    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --disable-host-check --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --config=node_modules/laravel-mix/setup/webpack.config.js"
    },`

i've this : 

`  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build"
  },`

How can i use Laravel-mix with this configuration ? I think i'm missing something.

**Comment by thecrypticace** [comment]
Mix cannot be used in conjunction with Vue CLI. If you are using Vue CLI you should use it's built in scripts via yarn or npm.

```
npm run serve
npm run build
```
