### ISSUE TITLE
webpack watch is generating extra new versions of other unchanged files beside the changed file

### ISSUE THREAD

**Issue by thekordy** [JeffreyWay/laravel-mix#261]
Changes to any js file, it generates a new version for other files beside the changed file. 

1. After webpack started watching files, first file change, will generate new version for all watched files.
2. Second change and afterwards, a new unnecessarily version for the app.scss file even there are no new changes to app.scss, is generated beside the changed file 

![extra new verions for all files with any file change 1](https://cloud.githubusercontent.com/assets/11343048/22506409/ddd6a894-e888-11e6-8f4f-39ff9f3d2fdd.png)

![extra new verions for all files with any file change 2](https://cloud.githubusercontent.com/assets/11343048/22506415/e6759bd6-e888-11e6-8872-ff5e59e5b2e5.png)

```js
//webpack.mix.js
let mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for your application, as well as bundling up your JS files.
 |
 */
mix.js('resources/assets/js/app.js', 'public/js')
    .js('resources/assets/js/login.js', 'public/js')
    .js('resources/assets/js/password.js', 'public/js')
    .extract([
        'jquery',
        'bootstrap-sass',
        'retinajs',
        'vue',
        'webui-popover',
        'moment',
        'toastr',
        'quill',
        'lodash'
    ])
    .sass('resources/assets/sass/app.scss', 'public/css')
    .version();
```

**Comment by JeffreyWay** [comment]
This was fixed a while ago.
