### ISSUE TITLE
Support for yarn & don't assume --save-dev

### ISSUE THREAD

**Issue by cubitworx** [JeffreyWay/laravel-mix#2614]
-   Laravel Mix Version: 5.0.7
-   Node Version: 10.19.0
-   NPM Version: 6.13.4
-   Yarn Version: 1.22.4
-   OS: Win10 1909

### Description 1:
When running the webpack bundler using mix as the config wrapper and you have missing dependencies, mix automatically tries to install dependencies but assumes you are using npm as the package manager. We use yarn & need to cancel the build in order to manually install the missing dependencies.

```
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"

Additional dependencies must be installed. This will only take a moment.

Running: npm install sass --save-dev --production=false
```

### Description 2:
Mix assumes you want to install the missing dependencies using flags `--save-dev --production=false`. This assumption should not be made if you are automating steps on behalf of the user.

Since Laravel is not a nodejs application, none of the node packages are used in production, making the distinction between prod & dev arbitrary. We only install packages used for testing as dev dependencies, the rest as prod dependencies.

### Steps To Reproduce:
1. Run `yarn install` to generate your `yarn.lock` file.
2. Make sure one of the dependencies is missing (in our example the `sass` package).
3. Run the bundler `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"`

**Comment by JeffreyWay** [comment]
Yeah I think we can safely get rid of the `--production` flag.

In reference to Yarn, we used to check which tool you used, but I'd rather not do that. I'm open to suggestions, though.
