### ISSUE TITLE
manifest.js file location not configurable

### ISSUE THREAD

**Issue by LaravelFreelancerNL** [JeffreyWay/laravel-mix#2615]
-   Laravel Mix Version: 5.0.9
-   Node Version (`node -v`): v14.15.0
-   NPM Version (`npm -v`):6.14.8
-   OS: linux/ubuntu 18

### Description:
The manifest.js is located at whatever place the last js was build. A fine default but not always desirable. A config option would be most welcome to keep the example below clean.

### Steps To Reproduce:
mix.js('resources/js/site/site.js', 'public/js/site/');
mix.js('resources/js/admin/admin.js', 'public/js/admin/');
mix.extract(['vue', 'axios', 'lodash'], 'public/js/vendor.js');

manifest.js will end up in 'public/js/admin/'

**Comment by thecrypticace** [comment]
This will be configurable in the next version of Mix using `runtimeChunkPath`: https://github.com/JeffreyWay/laravel-mix/blob/340925ccff797361aee069bf512f5c2f6166240b/docs/extract.md
