### ISSUE TITLE
TinyMCE npm run production - compiled js error 'get' of undefined

### ISSUE THREAD

**Issue by milivojsa** [JeffreyWay/laravel-mix#2620]
-   Laravel Mix Version: 1.7.2
-   Node Version: 14.11.0
-   NPM Version: 6.14.8
-   OS: Ubuntu 20.04.1 LTS (Laravel Homestead)

I have an issue with **npm run production** when importing **tinymce** plugin.

When I run **npm run dev** everything works as expected. On **npm run production** it compiles successfully but when I open the page with TinyMCE editor it does not load TinyMCE and it gets a javascript error in console:

`Uncaught TypeError: Cannot read property 'get' of undefined`

I have tried to find a solution and came across similar issues but none of them were related to the npm run production.

I have tried to configure webpack uglify with **"ascii_only": true**

Also, I have tried to setup module loaders for tinymce plugin in webpack.mix.js but still no success.

This is how I use it:

```
// app.js
window.tinymce = require('tinymce/tinymce.js');

// webpack.mix.js
mix.js('resources/js/app.js', 'public/js');
mix.copyDirectory('node_modules/tinymce/icons', 'public/js/icons');
mix.copyDirectory('node_modules/tinymce/plugins', 'public/js/plugins');
mix.copyDirectory('node_modules/tinymce/skins', 'public/js/skins');
mix.copyDirectory('node_modules/tinymce/themes', 'public/js/themes');
```

Everything works after **npm run dev** as expected but the compiled javascript has an error after **npm run production**.

I guess it can be because of minification but I wasn't able to solve it.

**Comment by thecrypticace** [comment]
Laravel Mix 1.7 is a very old version. Do you have the same problem with Mix 5.x?

**Comment by milivojsa** [comment]
Thanks for the answer! You were right, as soon as I updated Mix to 5.x it works as expected.
