### ISSUE TITLE
Laravel mix cannot find config file

### ISSUE THREAD

**Issue by ericp-mrel** [JeffreyWay/laravel-mix#2621]
-   Laravel Mix Version: 6.0.0-beta.14 (`npm list --depth=0`)
-   Node Version (`node -v`): v12.19.1
-   NPM Version (`npm -v`): 6.14.8
-   OS: Pop!_OS 20.04 LTS

### Description:
I am testing out the beta release of laravel mix, but every time I try to compile my assets it throws an error saying it cannot find my config file. `[webpack-cli] The specified config file doesn't exist in /media/storage/Work`
It seems like something isn't passing the current path correctly since the path mentioned above isn't actually the full path to where I am compiling my code from. This is my actual CWD: `/media/storage/Work Files/Code/laravel-mix`

When I tested this, everything worked as expected if I ran it from the following path: `/tmp/laravel-mix` which doesn't contain any spaces in its full path.

### Steps To Reproduce:

1. Create a folder with a space in the name.
2. Try to compile code with laravel mix `npx mix`

### webpack.mix.js file
```js
let mix = require('laravel-mix');

mix.postCss('./resources/css/main.css', 'css')

mix.webpackConfig({
    externals: {
        'jquery': 'jQuery',
    },
})

mix.options({
    processCssUrls: false,
    postCss: [
        require('postcss-import'),
        require('tailwindcss'),
        require('postcss-nested'),
    ]
}).setResourceRoot('..')
    .setPublicPath('./assets');

if (mix.inProduction()) {
    mix.sourceMaps();
}
`

**Comment by danimalweb** [comment]
I have the same issue. Looking forward to seeing the PR merged.
