### ISSUE TITLE
[6.0.0-beta.14] chunk file load with http instead of https when web pack is set to https

### ISSUE THREAD

**Issue by weiloon1234** [JeffreyWay/laravel-mix#2627]
-   Laravel Mix Version: laravel-mix@6.0.0-beta.14
-   Node Version: v15.2.1
-   NPM Version: 7.0.12
-   OS: macOS Big Sur 11.0.1

### Description:
chunk file load with http instead of https when web pack is set to https
the chunk file is properly build if visit via https

### Steps To Reproduce:
1. edit webpack.mix.js(Line 9-26) to ensure https cert path correct
2. composer install && npm install --legacy-peer-deps && npm run hot

### Minimum repo:
https://github.com/weiloon1234/test-laravel-mix-6

![image](https://user-images.githubusercontent.com/7457342/100098263-c6ca8580-2e98-11eb-8434-b62d14b309c5.png)
![image](https://user-images.githubusercontent.com/7457342/100098309-d8ac2880-2e98-11eb-8af5-9f5f3c7e7237.png)
![image](https://user-images.githubusercontent.com/7457342/100098490-14df8900-2e99-11eb-8c74-853977b2632b.png)

**Comment by garrensweet** [comment]
I was recently upgrading a Laravel Project from Mix 4 to 6 and encountered the same problem. 

I noticed that at line 98 in `laravel-mix/src/builder/WebpackConfig.js` the protocol is determined by the presence of the `https` value passed to the `hmrOptions` object, so HRM with HTTPS in Mix 6 is actually contingent on both the `hmrOptions` object` passed to Mix and the `devServer` object passed to the `webpackConfig`

Setting the `https` value and the host/port are defined within the `hmrOptions` object:

```javascript
mix.options({
    hmrOptions: {
        https: true, // now the protocol will load correctly
        host: process.env.host,
        port: process.env.port
    }
})
 ```

Then, providing your key/cert/ca to the underlying `webpack-dev-server` spawn:

```javascript
mix.webpackConfig({
  devServer: {
      https: {
          key: process.env.ssl_key,
          cert: process.env.ssl_cert,
          ca: process.env.ssl_ca
      }
  }
})
```

Hopefully it helps someone.
