### ISSUE TITLE
[6.0.0-beta.14] postCSS ignores output path entirely

### ISSUE THREAD

**Issue by LasseRafn** [JeffreyWay/laravel-mix#2629]
-   Laravel Mix Version: 6.0.0-beta.14
-   Node Version: v12.18.4
-   NPM Version: 6.14.6
-   OS: macOS 10.13.6

### Description:

Filename and path is wrong when using PostCSS and `.pcss` file.

### Steps To Reproduce:

1. Install 6.0.0-beta.14
2. Add the following to your `webpack.mix.js` file:

```js
mix.postCss('resources/sass/app.pcss', 'public/css');
```

3. Run `mix`
4. Output will look similar to:

```
┌──────────────────────────────────┬──────────┐
│ File                                │ Size      │
├──────────────────────────────────┼──────────┤
│ mix.css                             │ 3.74 MiB  │
└──────────────────────────────────┴──────────┘
```

The file is called `mix.css` instead of `app.css` and is placed in my `public` folder, not `public/css`.

If I add `mix.js` calls it will place the file in `public/js` and name it `[NAME OF JS FILE].css`

### Additionally

If I change the filename from `app.pcss` to `app.css` it works correctly. Seems its related to the extension? Although the output misses a `/` in front of the filename only for the CSS file (just something I noticed, doesn't break anything)

```
┌───────────────────────────────────┬──────────┐
│ File                                 │ Size     │
├───────────────────────────────────┼──────────┤
│ css/app.css                          │ 3.74 MiB │
├───────────────────────────────────┼──────────┤
│ /js/app.js                            │ 549 KiB  │
└───────────────────────────────────┴──────────┘

```

**Comment by OwenMelbz** [comment]
This was confusing us for ages!

For the time being we've renamed our entry file to `app.css` until a fix is released 👍
