### ISSUE TITLE
[6.0.0-beta.14] Add ENV variables on mix

### ISSUE THREAD

**Issue by goper-leo** [JeffreyWay/laravel-mix#2631]
-   Laravel Mix Version: 6.0.0-beta.14
-   Node Version (`node -v`): 12.20.0
-   NPM Version (`npm -v`): 6.14.8
-   OS: Ubuntu 16.04

### Description:
How to add `ENV` variables on running `npx mix` ? On previous laravel-mix version I use 
```
cross-env NODE_ENV=staging node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
```
On version 6 how to add `staging` or any other variables on running `production` like command.

### Steps To Reproduce:
- npx mix --staging

**Comment by leonp5** [comment]
Sorry for writing at the closed issue, but i can't find a documentation how to set custom NODE_ENV in the package.json and how to access them in the `webpack.mix.js` in Laravel Mix 6.

```
"scripts": {
       ...
        "prepare-assets": "cross-env NODE_ENV=prepare-assets mix",
       ...
```
That works, but throws the following error:

```
WARNING in DefinePlugin
Conflicting values for 'process.env.NODE_ENV'

2 WARNINGS in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 3 warnings
```

Does anybody has a correct example? Thanks :slightly_smiling_face:
