### ISSUE TITLE
Replace `friendly-errors-webpack-plugin` with webpack 5 compatible equivalent.

### ISSUE THREAD

**Issue by thecrypticace** [JeffreyWay/laravel-mix#2634]
This plugin appears to be unmaintained. We'll need to replace this plugin as it is causing installation issues (installing webpack 4 instead of webpack 5) when using NPM 7 without the `--legacy-peer-deps` flag.

**Comment by JeffreyWay** [comment]
It seems like it. I've been keeping an eye on this issue...

https://github.com/geowarin/friendly-errors-webpack-plugin/issues/123

But, yeah, looks like the project is abandoned.

**Comment by thecrypticace** [comment]
I might either write the replacement plugin or just fork the package until it gets updated. (I know absolutely _nothing_ about npm publishing though)

**Comment by soilSpoon** [comment]
Is there any option not to use this plugin?

**Comment by thecrypticace** [comment]
I'm going to pull this plugin and tweak some things to we should have passable error display.
