### ISSUE TITLE
[6.0.0-beta.14] Can't access environment variables via process.env

### ISSUE THREAD

**Issue by trihargianto** [JeffreyWay/laravel-mix#2639]
-   Laravel Mix Version: 6.0.0-beta.14
-   Node Version: v12.19.0
-   NPM Version: 6.14.8
-   OS: MacOS Catalina 10.15.6

### Description:

Apparently, Laravel-Mix/Webpack can't resolve the `process` variable. An error is shown on browser console like the screenshot below

<img width="918" alt="Screenshot 2020-12-01 at 15 26 55" src="https://user-images.githubusercontent.com/18502234/100715351-a7c47a00-33e9-11eb-8bfb-f34411d604d2.png">

### Steps To Reproduce:

I've created a new minimal fresh repo on https://github.com/trihargianto/laravel-with-mix-6 

What I did is just trying to see all the available environment variables via console like this

```
<template>
  <div>Hello Im from Vue</div>
</template>

<script>
export default {
  name: "App",
  mounted() {
    console.log('1.', process);
    console.log('2.', process.env);
    console.log('3.', process.env.TEST);
    console.log('4.', process.env.MIX_TEST);
  },
};
</script>
```

**Comment by trihargianto** [comment]
I think this is related to Webpack 5 updates https://webpack.js.org/migrate/5/#run-a-single-build-and-follow-advises

<img width="741" alt="Screenshot 2020-12-01 at 15 40 29" src="https://user-images.githubusercontent.com/18502234/100716654-92504f80-33eb-11eb-8484-9dd9cb6174a2.png">

**Comment by thecrypticace** [comment]
Correct, this is related to webpack 5 updates. We automatically register replacements for `process.env.NODE_ENV` and loaded env vars of the form `process.env.MIX_NAME_HERE` but you have to write that string out exactly. You can't reference process or process.env and then iterate over it.

(see: https://github.com/JeffreyWay/laravel-mix/blob/67081b0360ed72c933a0c0b0c83512b465d3a8c6/src/webpackPlugins/MixDefinitionsPlugin.js)
