### ISSUE TITLE
Error running dev when upgrading to laravel-mix 6 with vue 3

### ISSUE THREAD

**Issue by r2get** [JeffreyWay/laravel-mix#2640]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`) 6.0.0 beta14
-   Node Version (`node -v`): 10,16,3
-   NPM Version (`npm -v`): 6,14,8
-   OS: MacOS

this is the error i get 

/node_modules/laravel-mix/src/Log.js:5
    static testing = false;
                   ^

SyntaxError: Unexpected token =
    at new Script (vm.js:83:7)

### Steps To Reproduce:
run "mix"

**Comment by thecrypticace** [comment]
Laravel Mix v6 requires at least Node v12
