### ISSUE TITLE
[6.*] No versioning with mix.options({ processCssUrls: false });

### ISSUE THREAD

**Issue by t0byman** [JeffreyWay/laravel-mix#2647]
-   Laravel Mix Version: 6.0.0-beta.14 
-   Node Version: 14.15.1
-   NPM Version: 6.14.8
-   OS: macOS 11.0.1 Big Sur

### Description:
Using `mix.version()` option in combination with relative url rewriting (`mix.options({ processCssUrls: false })`) will output files without version numbers.

**Comment by thecrypticace** [comment]
I can't reproduce this. The manifest has identifiers in it as expected. Can you provide a reproduction repo?

**Comment by t0byman** [comment]
You're right, I was mistaken. Also, I thought that versioned files themselves were supposed to get a hash too but I have to extract the asset file names from the manifest for cachebusting right? Something like this in my manifest is correct?

`"/scripts/app.js": "/scripts/app.js?id=34c4e205073a37a87369",`

**Comment by thecrypticace** [comment]
Yep, the file names themselves are not versioned. If you're using laravel you can use the `mix()` helper function for this.
