### ISSUE TITLE
Watch no work after change css

### ISSUE THREAD

**Issue by ardanirohman** [JeffreyWay/laravel-mix#265]
hi all
i try laravel-mix now in webpack.mix.js i write
`
mix.combine([
    'resources/assets/css/lib/datatables-net/datatables.min.css',
    'resources/assets/css/separate/vendor/datatables-net.min.css',
    'resources/assets/css/lib/bootstrap-sweetalert/sweetalert.css',
    'resources/assets/css/separate/vendor/sweet-alert-animations.min.css',
    'resources/assets/css/separate/vendor/lobipanel.css',
    'resources/assets/css/lib/jqueryui/jquery-ui.min.css',
    'resources/assets/css/separate/pages/widgets.min.css',
    'resources/assets/css/lib/font-awesome/font-awesome.min.css',
    'resources/assets/css/lib/bootstrap/bootstrap.min.css',
    'resources/assets/css/separate/vendor/bootstrap-select/bootstrap-select.min.css',
    'resources/assets/css/separate/vendor/bootstrap-daterangepicker.min.css',
    'resources/assets/css/main.css',
    'resources/assets/css/custom.css'
],'public/css/default.css')
`
then i run `npm run watch`
i changed custom.css  but watch not detect any changed file.
any problem from my code or i missing something?
thanks

**Comment by JeffreyWay** [comment]
That's expected behavior right now, since anything passed to mix.combine() will be triggered after your main Webpack bundle compiles. In this case, you're not changing any of your Webpack entry files, so nothing happens.

**Comment by JeffreyWay** [comment]
I just pushed a commit that will watch these files for you. It'll be tagged soon.
