### ISSUE TITLE
can't run npm install anymore without Invalid configuration object error showing up

### ISSUE THREAD

**Issue by nerba** [JeffreyWay/laravel-mix#2656]
-   Mix Version: 5.0.5 (`npm list --depth=0`)
-   Node Version (`node -v`): 12.16.1
-   NPM Version (`npm -v`): 6.13.4
-   OS: Win10

### Description:
I've just experienced for first time this error which puzzles me. I could not find solution that worked for me by googling. I've tried reseting everyhing by deleting node_modules and reinstalling, but that did not help.

### Steps To Reproduce:
npm run dev
npm run prod

both generate
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'optimization'. These properties are valid:
```

**Comment by irakan** [comment]
I faced the same issue with `mix v6.0.0-beta.15`, I am not sure what causing it.. but I solve it by installing webpack locally `npm i webpack --save-dev`

**Comment by thecrypticace** [comment]
Are you _sure_ you're using NPM v6? I've seen this happen with NPM 7 but not v6.

**Comment by drthomas21** [comment]
I get this issue with NPM7

My temp solution (which only works if you are using NPM 7) is to remove node_modules and pacakge-lock.json and then use "npm install --legacy-peer-deps"

**Comment by dniccum** [comment]
> Are you _sure_ you're using NPM v6? I've seen this happen with NPM 7 but not v6.

I can confirm that this issue appears when using NPM version 7, but goes away when you down grade to version 6.

**Comment by thecrypticace** [comment]
This error is generally related to a peer dependency of some package that's not compatible with webpack 5. Can you post a gist of your package.json?

**Comment by dniccum** [comment]
```json
{
"devDependencies": {
      "@tailwindcss/ui": "^0.6.0",
      "autoprefixer": "^10.1.0",
      "axios": "^0.19",
      "browser-sync": "^2.26.13",
      "browser-sync-webpack-plugin": "^2.2.2",
      "cross-env": "^7.0",
      "laravel-mix": "^6.0.0",
      "laravel-mix-purgecss": "^6.0.0",
      "lodash": "^4.17.19",
      "postcss": "^8.1",
      "postcss-import": "^12.0.1",
      "resolve-url-loader": "^3.1.0",
      "sass": "^1.32.8",
      "sass-loader": "^10.0.4",
      "tailwindcss": "^1.9.5",
      "vue-template-compiler": "^2.6.12"
  },
}
```

**Comment by thecrypticace** [comment]
Your `browser-sync-webpack-plugin` needs to be `^2.3`

**Comment by dniccum** [comment]
I just checked, the current version that is installed is 2.3

**Comment by sandcore-dev** [comment]
> My temp solution (which only works if you are using NPM 7) is to remove node_modules and pacakge-lock.json and then use "npm install --legacy-peer-deps"

I can confirm this solution works. It will get wiped out with a regular `npm update` and probably `npm audit fix` as well, though.
