### ISSUE TITLE
Feature Request | Yarn support

### ISSUE THREAD

**Issue by shaqaruden** [JeffreyWay/laravel-mix#2658]
-   Laravel Mix Version: 5.0.9 
-   Node Version: 14.15.0
-   NPM Version: 6.14.8
-   OS: macOS

### Description:
Though yarn support was removed with this issue (https://github.com/JeffreyWay/laravel-mix/issues/2196). Extra steps are created from anyone using yarn over npm. Either by detecting the yarn.lock file, an environment variable or through a configurable option allow users to choose which they want to use.

**Comment by thecrypticace** [comment]
This will be the case in Laravel Mix v6 (see https://github.com/JeffreyWay/laravel-mix/pull/2642)
