### ISSUE TITLE
Fallback extractions doesn't work

### ISSUE THREAD

**Issue by 3zzy** [JeffreyWay/laravel-mix#2659]
-   Laravel Mix Version: 6.0.0.beta-15
-   Node Version (`node -v`): 12.19.0
-   NPM Version (`npm -v`): 6.14.8
-   OS: MacOS Big Sur

### Description:
```
mix.extract(
    ["vuex", "axios-mock-adapter", "vue-color"],
    "./application/js/dist/vendor~backend.js"
);
mix.extract({
    to: "./application/js/dist/vendor~frontend.js"
});
mix.extract();
```

Should result in 3 files as per the [doc](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/extract.md#fallback-extractions):

```
// `vendor~backend.js` 
// `vendor~frontend.js` 
// `vendor.js` will contain all other used libraries from node_modules 
```

.. but only three files are generated (including the manifest), there's no `vendor.js` causing the entire app to break.

**Comment by thecrypticace** [comment]
The last two extract calls are effectively the same with a different filename.

This extracts the rest of the files to `vendor~frontend.js`:
`mix.extract({ to: "./application/js/dist/vendor~frontend.js" })`

This extracts the rest of the files to `vendor.js`:
`mix.extract()`

Having them both is probably undefined behavior. I would expect the above to result in 3 files vendor~backend.js, vendor~frontend.js, manifest.js. Perhaps you forgot to specify which libraries you wanted to extract for `vendor~frontend.js`

**Comment by rickdubiel** [comment]
Having the same issue here as well where no "vendor.js" file is getting created (Laravel Mix v5.0.9). Started with a fresh install of Laravel 8, installed `laravel/ui` (the "bootstrap --auth" version), ran `npm install`, and simply added the following 2 lines to the end of webpack.mix.js:

```
mix.extract(['jquery'], 'public/js/jquery.js');
mix.extract();
```

Ran `npm run dev` and got the following ouput:

```
DONE  Compiled successfully in 11264ms         

          Asset      Size        Chunks             Chunk Names
   /css/app.css   139 KiB       /js/app  [emitted]  /js/app
     /js/app.js  1.96 MiB       /js/app  [emitted]  /js/app
  /js/jquery.js   809 KiB    /js/jquery  [emitted]  /js/jquery
/js/manifest.js  6.12 KiB  /js/manifest  [emitted]  /js/manifest
```

Same result as @3zzy with no `vendor.js` file being generated. Can anybody spot what we're missing here?

**Comment by thecrypticace** [comment]
Fallback extractions are a Laravel Mix v6 feature.

**Comment by rickdubiel** [comment]
Well there you have it! Thank you @thecrypticace !

**Comment by 3zzy** [comment]
@thecrypticace Thanks, but I'm still having issues when using fallback extractions. So I have this:

```
mix.extract(
    [
        "vuex",
        "axios-mock-adapter",
        "vue-color",
        "@popperjs/core",
        "invert-color",
    ],
    "./application/js/dist/vendor~backend.js"
);
mix.extract({
    to: "./application/js/dist/vendor.js",
});
```

... followed by a few `mix.js()` calls for Vue SPAs. Most of those works (haven't tested all) but one doesn't work:

`[Vue warn]: Unknown custom element: <my-component> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
`

The component works without issues as soon as I remove the extractions.

**Comment by thecrypticace** [comment]
I'd need to see a reproduction repo.
