### ISSUE TITLE
console.log not being removed in production

### ISSUE THREAD

**Issue by rickbolton** [JeffreyWay/laravel-mix#266]
I think this was done by default using elixir. I've just upgraded a project to Laravel 5.4 and swapped out elixir for Laravel Mix and console.log are still showing when doing a "yarn run production"

Do I need to look at adding something like webpack-strip to my webpack config or is there something easier that I'm missing?

**Comment by roryjarrard** [comment]
Why is this closed? This is happening to me still on my production server. Yarn or npm run production still showing console.log statements

**Comment by rjcrystal** [comment]
You can configure all uglify configuration using mix.options, for dropping the console log try the following configuration.

`
mix.options({
    uglify: {
        uglifyOptions: {
            compress: {
                drop_console: true,
            }
        }
    }
});
`

**Comment by johannesss** [comment]
Still happening for me on a Windows server.

**Comment by chinleung** [comment]
For anyone who needs to remove logs in mix **v4.0.15**:

``` javascript
mix.options({
    terser: {
        terserOptions: {
            compress: {
                drop_console: true,
            }
        }
    }
})
```
```

**Comment by warmwhisky** [comment]
> ```js
> mix.options({
>     terser: {
>         terserOptions: {
>             compress: {
>                 drop_console: true,
>             }
>         }
>     }
> })
> ```

Any idea why I cannot get this to work using `"laravel-mix": "^6.0.49"`
