### ISSUE TITLE
[6.x] Legacy Node Polyfills

### ISSUE THREAD

**Issue by thecrypticace** [JeffreyWay/laravel-mix#2662]
We should either add a config option / component that re-enables these or a note to the docs.

What needs to happen is rather simple:

1. Install `node-libs-browser`
2. Update the webpack config
```js
mix.webpackConfig({
    resolve: {
        fallback: {
            // This handles all of them…
            // ...Object.fromEntries(Object.entries(require("node-libs-browser")).filter(e => e[1] !== null)),

            // … but these are likely the most used and as such should be sufficient
            process: require("node-libs-browser").process,
            buffer: require("node-libs-browser").buffer,
        },
    },
})
```

If we were to add a shortcut for this in Mix I'd probably do something like this:
```js
mix.options({ legacyNodePolyfills: true })
```

What do you think @JeffreyWay? Would documentation suffice or should we add a shortcut for this?

**Comment by JeffreyWay** [comment]
I ran into this with one of my side projects last week. 

Hmm - let's start with simple documentation for now. If this is something a lot of folks need to add, we'll add a helper for it. 👍

**Comment by 3zzy** [comment]
Not sure if related but I did add the polyfills:

```
resolve: {
        fallback: {
            fs: false,
            path: require.resolve("path-browserify"),
            buffer: require.resolve("buffer/"),
        },
    }
```

... and the build is successful but I still get this error:

```
Uncaught (in promise) Error: nodebuffer is not supported by this browser
    at Object.exports.checkSupport (vendor.js?_v=2.31.2.1:2)
    at Object.exports.transformTo (vendor.js?_v=2.31.2.1:2)
    at ZipObject.asNodeBuffer (vendor.js?_v=2.31.2.1:2)
    at vendor.js?_v=2.31.2.1:2
    at Array.forEach (<anonymous>)
    at module.exports (vendor.js?_v=2.31.2.1:2)
    at Function.shp.parseZip (vendor.js?_v=2.31.2.1:2)
    at vendor.js?_v=2.31.2.1:2
```

**Comment by thecrypticace** [comment]
Try this. Note the capital B in `Buffer` and see if that works.

```
mix.webpackConfig({
    resolve: {
        fallback: {
            // … omitted for brevity …
            Buffer: require("node-libs-browser").buffer,
        },
    },
})
```

**Comment by ctf0** [comment]
@JeffreyWay  atm using `mix.options({ legacyNodePolyfills: true })` does nothing & we have to use
```
mix.webpackConfig({
    resolve: {
        fallback: {
            process: require("node-libs-browser").process,
            Buffer: require("node-libs-browser").buffer,
        },
    },
})
```

**Comment by newtek-software-bneff** [comment]
@ctf0 were you able to get legacyNodePolyfills working? I just upgraded to 6 and am getting a whole lot of errors that look like this and I am using `mix.options({ legacyNodePolyfills: true })`

```
ERROR in ./node_modules/laravel-mix/src/Manifest.js 2:11-26
Module not found: Error: Can't resolve 'path' in './node_modules/laravel-mix/src'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }
```

**Comment by thecrypticace** [comment]
We only handle two at the moment as they're the most prevalent.
- Buffer / buffer
- process

If you need `path` support please open another issue or, if possible, a PR and I'll take a look when I can.

**Comment by Kaos-Industries** [comment]
> I ran into this with one of my side projects last week.
> 
> Hmm - let's start with simple documentation for now. If this is something a lot of folks need to add, we'll add a helper for it. 👍

Does that documentation exist anywhere? Laravel 9 documentation on Mix still refers to using the `process.env=MIX...` solution.

**Comment by newtek-bneff** [comment]
FYI for the issue I posted about above [https://github.com/laravel-mix/laravel-mix/issues/2958#issuecomment-989984918](this) solved it for me
