### ISSUE TITLE
No Scrollbar in https://laravel-mix.com/docs/5.0 website's left sidebar menu

### ISSUE THREAD

**Issue by bapidey678** [JeffreyWay/laravel-mix#2667]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`)
-   Node Version (`node -v`):
-   NPM Version (`npm -v`):
-   OS: Windows

### Description:
No Scrollbar in https://laravel-mix.com/docs/5.0 website's left sidebar menu

**Comment by thecrypticace** [comment]
Pretty sure we don't control that site. It's on GitHub though so you could open an issue there: https://github.com/mvdnbrk/laravel-mix.com
