### ISSUE TITLE
Mix automatically downloads vue-template-compiler even though I'm not using VueJS

### ISSUE THREAD

**Issue by colynb** [JeffreyWay/laravel-mix#2670]
-   Laravel Mix Version: 5.0.1 (`npm list --depth=0`)
-   Node Version (`node -v`): v15.4.0
-   NPM Version (`npm -v`): 7.0.15
-   OS: maxOS 11.0.1

### Description:

Mix automatically installed vue-template-compiler even though I clearly am not using Vue.JS. Here is my mix file:

```
const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js').postCss('resources/css/app.css', 'public/css', [
    require('postcss-import'),
    require('tailwindcss'),
    require('autoprefixer'),
]);
```

### Steps To Reproduce:

I installed a brand new Laravel app using the new Laravel Sail docker build according to the instructions. I then installed Laravel Breeze and followed the instructions to install and build npm. I then got a warning that "vue-template-compiler" was not installed and will be installed for me.

**Comment by colynb** [comment]
Looking through the vendor folder of my app, I think it's the error page from Ignition. I'll be happy to close this once I dig a little deeper.

**Comment by thecrypticace** [comment]
No, this is because of the way Laravel Mix v5 is set up. `vue-template-compiler` is auto installed because it's very common to use Vue with Laravel Mix. This will change in v6 and you'll need to write `mix.vue()` to enable vue support out of the box.
