### ISSUE TITLE
[6.x.x] Laravel Mix does not output any error messages or compiled bundles when using TypeScript

### ISSUE THREAD

**Issue by 6XGate** [JeffreyWay/laravel-mix#2676]
-   Laravel Mix Version: `6.0.0`
-   Node Version `12.19.0`
-   NPM Version `6.14.10`
-   OS: Ubuntu 20.04

### Description:
Laravel Mix v6 is not printing out any errors or the table of compiled bundles when building from a TypeScript entry-point.

### Steps To Reproduce:
I have created [this project](https://github.com/6XGate/bugs-laravel-mix-v6-ts-output) that on my system produces this behavior.
The mix file simply has `mix.ts("src/test.ts", "dist/test.js").setPublicPath("dist");` as its only instructions and the _test.ts_ file has an error in it, `_console.log("test");`, that is not being displayed in the console output when running `npx mix`.

**Comment by Ragash** [comment]
mix.webpackConfig({
    stats: 'normal'
});

will solve it

**Comment by 6XGate** [comment]
It should be noted that when using plain JavaScript, a table of assets will appear when done.  TypeScript also breaks that somehow.  I likely expect this behavior is not intended.

**Comment by Blair2004** [comment]
![image](https://user-images.githubusercontent.com/5265663/103127538-78c0c180-4692-11eb-8f16-9f8ed53145ea.png)


Hi, indeed, that's how I'm forced to debug for now.. which is not suitable (using Ubuntu 20.04)

**Comment by JeffreyWay** [comment]
This was fixed in the most recent patch release.
