### ISSUE TITLE
[6.x.x] Mix wont compile if child scss use assets relative to root // SourceMaps are False by default

### ISSUE THREAD

**Issue by Ragash** [JeffreyWay/laravel-mix#2678]
-   Laravel Mix Version: 6.0.0
-   Node Version: v14.15.3
-   NPM Version: 6.14.9
-   OS: Windows 10

### Description:

i've upgraded a project from Mix 4 to 6, i had some url with this format

` src: url('../../assets/fonts/font.woff2') format('woff2'),`

which were resolved and moved correctly.
but after the update, i had to change it to 

` src: url('../assets/fonts/font.woff2') format('woff2'),` 

otherwise mix wont compile. The very same happen with vendor dependency, for example i used to import 
`@import "~rpg-awesome/scss/rpg-awesome";` without issues, but now i get this error:

`ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '../fonts/rpgawesome-webfont.eot?v=0.1.0' in 'G:\laragon\www\tdl_laravel\resources\sass'
    at finishWithoutResolve (G:\laragon\www\tdl_laravel\node_modules\enhanced-resolve\lib\Resolver.js:293:18)
    at G:\laragon\www\tdl_laravel\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at G:\laragon\www\tdl_laravel\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (G:\laragon\www\tdl_laravel\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at G:\laragon\www\tdl_laravel\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (G:\laragon\www\tdl_laravel\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at G:\laragon\www\tdl_laravel\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:87:43
    at G:\laragon\www\tdl_laravel\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (G:\laragon\www\tdl_laravel\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at G:\laragon\www\tdl_laravel\node_modules\enhanced-resolve\lib\forEachBail.js:16:12
    at G:\laragon\www\tdl_laravel\node_modules\enhanced-resolve\lib\AliasPlugin.js:103:14
    at next (G:\laragon\www\tdl_laravel\node_modules\enhanced-resolve\lib\forEachBail.js:14:3)
    at forEachBail (G:\laragon\www\tdl_laravel\node_modules\enhanced-resolve\lib\forEachBail.js:24:9)
    at G:\laragon\www\tdl_laravel\node_modules\enhanced-resolve\lib\AliasPlugin.js:37:5
    at _next0 (eval at create (G:\laragon\www\tdl_laravel\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (G:\laragon\www\tdl_laravel\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:30:1)
    at processResult (G:\laragon\www\tdl_laravel\node_modules\webpack\lib\NormalModule.js:583:19)
    at G:\laragon\www\tdl_laravel\node_modules\webpack\lib\NormalModule.js:676:5
    at G:\laragon\www\tdl_laravel\node_modules\loader-runner\lib\LoaderRunner.js:397:11
    at G:\laragon\www\tdl_laravel\node_modules\loader-runner\lib\LoaderRunner.js:252:18
    at context.callback (G:\laragon\www\tdl_laravel\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (G:\laragon\www\tdl_laravel\node_modules\css-loader\dist\index.js:155:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

it is intended? it seems strange to not points the url relative paths where the files resides, it seems the "../../" messes up the url rewriting

### Steps To Reproduce:

> composer create-project laravel/laravel testbug
> change in package.json `"laravel-mix": "^6",`
> npm i

> create `resources/sass/app.scss` and `resources/sass/example/test.scss` 
> in test.scss do a simple:
```
@font-face {
    font-family: 'base-text';
    src: url('../../assets/fonts/base-text.woff') format('woff'),
    url('../../assets/fonts/base-text.woff2') format('woff2');
    font-weight: normal;
    font-style: normal;
}
```

>obviusly, create folder `resources/assets/fonts` and put you test font in there (it can be whatever you prefer, img, svg, the same problem occur)

>compile and you'll get:

```
ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '../../assets/fonts/base-text.woff' in 'G:\xxx\testbug\resources\sass'
```

**Comment by Ragash** [comment]
more info: 
it seems that mix try to load assets relative from app.scss, despite resolve-url-loader should let child scss files load assets relative to them (it used to work in older verions of mix)

**Comment by Ragash** [comment]
updated with a proper "step to reproduce"

**Comment by Ragash** [comment]
no one can confirm?

same error happen also with images/svg and such

**Comment by Ragash** [comment]
@JeffreyWay @thecrypticace 

**Found the bug!**
_** bonus: even a temp solution **_

it seems there is a problem in Sass.js or Processor.js (still have to figure out why):

to use the "resolve-url-loader" magic there's the need to have SourceMaps setted to **true**

i noticied that into Sass.js there is a default setting for the sourcemaps to true:

```
pluginOptions(pluginOptions) {
        return Object.assign(
            {
                sassOptions: {
                    precision: 8,
                    outputStyle: 'expanded'
                }
            },
            pluginOptions,
            { sourceMap: true } //<- this bad boy i suppose
        );
    }
```

well, it seems to lose the value along the way

i console.logged the value of the loaders in Processor.js, and that's the result:
```

[
  {
    loader: 'D:\\laragon\\www\\tanadelladro\\node_modules\\mini-css-extract-plugin\\dist\\loader.js',
    options: { esModule: true }
  },
  {
    loader: 'css-loader',
    options: { url: true, sourceMap: false, importLoaders: 1 }
  },
  {
    loader: 'postcss-loader',
    options: { sourceMap: false, postcssOptions: [Object] }
  },
  {
    loader: 'resolve-url-loader',
    options: { sourceMap: true, debug: true }
  },
  {
    loader: 'sass-loader',
    options: { sassOptions: [Object], sourceMap: false }
  }                                                                                                              
]      
``` 

so the workaround is pretty simple, just forcing all the way down:
**mix.sass('resources/sass/app.scss', 'public/css').sourceMaps();**
                                              
in anycase this would let the magic of resolve-url-loader to work properly.

**Comment by philbates35** [comment]
Can confirm I was having similar issues with `url()` inside of child SCSS files and adding `.sourcemaps()` fixed it.

**Comment by stephan-v** [comment]
Adding `.sourceMaps()` or `.sourceMaps(true)` does nothing for me. For every `url()` which has a path relative to the root the resolve fails. Unfortunately I don't have the time to debug this right now, but currently this makes laravel-mix 6.0 unusable for me.

**Comment by philbates35** [comment]
@stephan-v Actually I missed off the fact that I converted the path relative from the child component first, and then added `.souceMaps()`. If I leave the url path relative to `app.scss` then it still fails even with `.sourceMaps()`.

**Comment by Ragash** [comment]
> Adding `.sourceMaps()` or `.sourceMaps(true)` does nothing for me. For every `url()` which has a path relative to the root the resolve fails. Unfortunately I don't have the time to debug this right now, but currently this makes laravel-mix 6.0 unusable for me.

truth is that sass-loader to work need `sourcemaps:true` as per sass-loader docs: https://webpack.js.org/loaders/sass-loader/#problems-with-url

>Problems with url(...)
>Since Sass implementations don't provide url rewriting, all linked assets must be relative to the output.
>
>If you pass the generated CSS on to the css-loader, all urls must be relative to the entry-file (e.g. main.scss).
>If you're just generating CSS without passing it to the css-loader, it must be relative to your web root.
>You will be disrupted by this first issue. It is natural to expect relative references to be resolved against the .sass/.scss file in >which they are specified (like in regular .css files).
>
>Thankfully there are a two solutions to this problem:
>
>Add the missing url rewriting using the resolve-url-loader. Place it before sass-loader in the loader chain.
>Library authors usually provide a variable to modify the asset path. bootstrap-sass for example has an $icon-font-path.

you could try to do somethig provisional like i did: putting a `console.log(loaders)` into `node_modules/laravel-mix/src/components/Preprocessor.js ` and look while building if mix mantains the proper settings, maybe are you overriding something in your mix file?

**Comment by Daniel4Digital** [comment]
For me .options({ processCssUrls: true }) fixed it

**Comment by richard-jacklin** [comment]
mix.sourceMaps(true) did it for me, thanks.

**Comment by JeffreyWay** [comment]
Working on this today. Should hopefully have a tagged patch out shortly.

**Comment by JeffreyWay** [comment]
@Ragash Can you update to the latest patch release and let me know if the issue is resolved on your end?

**Comment by richard-jacklin** [comment]
> @Ragash Can you update to the latest patch release and let me know if the issue is resolved on your end?

Works for me

**Comment by Ragash** [comment]
> @Ragash Can you update to the latest patch release and let me know if the issue is resolved on your end?

yep, can confirm it works now! thanks for your help Jeffrey!

**Comment by thecrypticace** [comment]
🎉

**Comment by ArjunKishore** [comment]
I am still having this issue with Laravel mix version 6.0.27

Will appreciate it if anyone could point me in the right direction to resolve this.
