### ISSUE TITLE
Minification not working with ES6

### ISSUE THREAD

**Issue by DerJacques** [JeffreyWay/laravel-mix#268]
Hi there

We have lately upgraded to Laravel Mix, and after some initial hurdles, close to everything is working well now.

However, when running `npm run production` fails with the following error:

```
/js/app.22f7802758e17b8e372a.js from UglifyJs
SyntaxError: Unexpected token punc «(», expected punc «:» [./resources/assets/js/someEs6File.js:13,4][/js/app.22f7802758e17b8e372a.js:5657,18]
```

This issue seems to be related to the fact that Uglifyjs doesn't yet work with ES6.
However, we thought that Uglify did its work _after_ the Babel had transpiled the code?

We also tried using a different minifier called [babili](https://github.com/babel/babili/tree/master/packages/babel-preset-babili#options), but the resulting package is much larger than the one from our old laravel-elixir build (1mb vs 300kb).

Our `.babelrc` looks like this:
```
{
  "presets": ["es2016"],
  "plugins": ["transform-object-rest-spread"],
}
```

Does anyone have some idea on how to solve this issue?

Best,
Manuel

**Comment by DerJacques** [comment]
We were able to make it work using `"presets": ["es2015"]` instead.
Unfortunately, the large file size remains, but that's a different issue.

Closing this one for now.

**Comment by terion-name** [comment]
@DerJacques adding .babelrc with "presets": ["es2015"] did not help or me (

**Comment by DerJacques** [comment]
@terion-name What exact error do you receive? Is it the same `/js/app.22f7802758e17b8e372a.js from UglifyJs
SyntaxError: Unexpected token punc «(», expected punc «:»`?

**Comment by terion-name** [comment]
@DerJacques yes. js file after webpack/babel is not es5

**Comment by vesper8** [comment]
Having the same problem and same error.. any hints?

**Comment by vesper8** [comment]
adding this to my package.json finally made that error go away
```
"uglify-js": "git+https://github.com/mishoo/UglifyJS2.git#harmony",
```

**Comment by yulidai** [comment]
some problem, 
even though can made that error go away
`"uglify-js": "git+https://github.com/mishoo/UglifyJS2.git#harmony",`
but some error occur when running in browser

**Comment by yulidai** [comment]
same problem, 
even though can made that error go away
`"uglify-js": "git+https://github.com/mishoo/UglifyJS2.git#harmony",`
but some error occur when running in browser

**Comment by ruchern** [comment]
Is there a reason to use es2016 over es2015 other than just being a newer version?

The package probably have not been updated to support es2016 yet.
