### ISSUE TITLE
Can't import css from node_modules (Mix v6)

### ISSUE THREAD

**Issue by RomkaLTU** [JeffreyWay/laravel-mix#2682]
-   Laravel Mix Version: 6.0.0
-   Node Version v14.15.1
-   NPM Version 6.14.10
-   OS: OSX Mojave

### Description:

In Laravel mix before version 6, I could do that:

```
import Swiper, { Pagination, Autoplay, EffectFade } from 'swiper'
import 'swiper/swiper-bundle.css'
```

Now swiper-bundle.css import not working. 

The only way I could do that by importing directly into CSS. 

`@import '../../../node_modules/swiper/swiper-bundle.css'; `

**Comment by Ragash** [comment]
seems to be related to my issue
https://github.com/JeffreyWay/laravel-mix/issues/2678

i used to import `@import "~rpg-awesome/scss/rpg-awesome";` 
now im forced to import the compiled css in the app.scsss
`@import "~rpg-awesome/css/rpg-awesome.css";`

**Comment by RomkaLTU** [comment]
> seems to be related to my issue
> #2678
> 
> i used to import `@import "~rpg-awesome/scss/rpg-awesome";`
> now im forced to import the compiled css in the app.scsss
> `@import "~rpg-awesome/css/rpg-awesome.css";`

Except I didn't get any errors, CSS import from JS is just ignored.

**Comment by dwainscheeren** [comment]
Got the exact same problem.

**Comment by minhajul** [comment]
package.json
--------------
     "devDependencies": {     
        "autoprefixer": "^10.1.0",
        "laravel-mix": "^6.0.13",
        "postcss-import": "^14.0.0",
        "trix": "^1.3.1"
    }

resources/css/app.css
-------
@import "~trix/dist/trix.css";

I am getting this below error.

`
ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Failed to find '~trix/dist/trix.css'
`
