### ISSUE TITLE
process.ENV blank in v6

### ISSUE THREAD

**Issue by OwenMelbz** [JeffreyWay/laravel-mix#2685]
Previous versions when we had a .env file we could do things such as...

MIX_API_KEY=123456

Then access it via JavaScript using 

process.env.MIX_API_KEY

however this is now coming up as undefined, I'm assuming this is because webpack removed it by default? https://webpack.js.org/migrate/5/ says to use DefinePlugin or EnvironmentPlugin

Could we bundle that in for compatibility?

**Comment by thecrypticace** [comment]
It _should_ already be set up for those env vars.

**Comment by dwightwatson** [comment]
I think I'm having a similar issue - `process.env.*` is ending up in my compiled scripts and the browser's console is blowing up: `Uncaught ReferenceError: process is not defined`.

```js
var BRAINTREE_ENVIRONMENT = process.env.MIX_BRAINTREE_ENVIRONMENT;
```

**Comment by JeffreyWay** [comment]
This one is confusing. The tests are passing - and I thought we fixed this a while back.

**Comment by sambindoff** [comment]
Sorry to chime in but also getting `Uncaught ReferenceError: process is not defined` after upgrading to 6, let me know if you want more info to help try and identify the issue. Cheers

**Comment by thecrypticace** [comment]
@sambindoff This is because referencing `process` or `process.env` by itself isn't supported by default. You have to reference `process.env.ENV_VAR`.

@JeffreyWay We may want to restore the old behavior for `process` specifically and have a flag to turn it off to reduce code size.

**Comment by dwightwatson** [comment]
Is there a new preferred way to access environment variables in our scripts, or is the intention to phase this feature out?

**Comment by sambindoff** [comment]
@thecrypticace thanks for the response, I am only referencing `process.env.ENV_VAR ` and never just `process` or `process.env`.

The use cases in my application are `process.env.MIX_BUGSNAG_API_KEY`, `process.env.MIX_PUSHER_APP_KEY`, `process.env.MIX_PUSHER_APP_CLUSTER`, but still I get the error.

**Comment by thecrypticace** [comment]
If you're getting `process is not defined` then a dependency might be referencing it. I've had this happen.

@dwightwatson No intention to phase this out. This stems from a change in webpack 5 where node builtins are no longer polyfilled in the browser to reduce code size.

**Comment by thecrypticace** [comment]
In the short term see this issue I filed about this behavior a while ago: https://github.com/JeffreyWay/laravel-mix/issues/2662

**Comment by JeffreyWay** [comment]
Okay, the fact that this popped up day one of the official release means we need to address it better. 

I'll take care of this today and tag a patch release.

**Comment by sambindoff** [comment]
I've just been doing some testing on fresh stacks and this looks to cause an issue with Jetstream Inertia.

A clean `laravel new` and Jetstream Inertia installation as per the docs and the build is unsuccessful. Other less JS heavy stacks are fine as expected, but imagine it's something to do with Vue and more specifically the vue-loader module.

I've also tested with the almost deprecated laravel/ui scaffold `php artisan ui vue ` to test against a very basic vue stack and this build also failed, but this stack doesn't require vue-loader.

Hope this helps, thanks for you time and effort @thecrypticace @JeffreyWay

**Comment by OwenMelbz** [comment]
> I've just been doing some testing on fresh stacks and this looks to cause an issue with Jetstream Inertia.
> 
> 
> 
> A clean `laravel new` and Jetstream Inertia installation as per the docs and the build is unsuccessful. Other less JS heavy stacks are fine as expected, but imagine it's something to do with Vue and more specifically the vue-loader module.
> 
> 
> 
> I've also tested with the almost deprecated laravel/ui scaffold `php artisan ui vue ` to test against a very basic vue stack and this build also failed, but this stack doesn't require vue-loader.
> 
> 
> 
> Hope this helps, thanks for you time and effort @thecrypticace @JeffreyWay
> 
> 
> 
> **EDIT: the workaround didn't fix the issue for me.**

Hey Sam, just an FYI we were using CraftCMS and React and this is where we experienced the issue. Mainly when upgrading to try Tailwind 2 :)

**Comment by sambindoff** [comment]
@OwenMelbz samesies on the tailwind front, I've just shipped that for now with the PostCSS 7 compatibility build and will revisit Mix 6/PostCSS 8 once resolved 👍

**Comment by JeffreyWay** [comment]
Okay, a couple notes:

@OwenMelbz Don't do `process.ENV.MIX_API_KEY` with `ENV` in all capitals. Change it to `process.env.MIX_API_KEY` and it should work.

@thecrypticace I couldn't get your legacy node polyfills example to work. I kept seeing `process is not defined` in the console. If I did `npm install node-libs-browser` and then added:

```
mix.webpackConfig({
    plugins: [
        new webpack.ProvidePlugin({
            process: 'process/browser',
        }),
    ],
});
```

...that seemed to solve the problem. 

@sambindoff We had an issue where errors weren't properly displaying. I fixed that and just tested a fresh Laravel app with Laravel UI, and it seems to be compiling properly.

**Comment by sambindoff** [comment]
@JeffreyWay brilliant, applying your workaround to my particular project looks to do the trick.

Also tested fresh `ui vue` and `jetstream:install inertia` and can confirm both work without requiring the workaround.

Thanks for your quick response and time spent on resolving this, for me anyway.

**Comment by thecrypticace** [comment]
@JeffreyWay yeah it seems resolve.fallback only works when you require/import. Not for when it's available as a global. I've opened a PR that handles both situations.

**Comment by Kaos-Industries** [comment]
> Okay, a couple notes:
> 
> @OwenMelbz Don't do `process.ENV.MIX_API_KEY` with `ENV` in all capitals. Change it to `process.env.MIX_API_KEY` and it should work.
> 
> @thecrypticace I couldn't get your legacy node polyfills example to work. I kept seeing `process is not defined` in the console. If I did `npm install node-libs-browser` and then added:
> 
> ```js
> mix.webpackConfig({
>     plugins: [
>         new webpack.ProvidePlugin({
>             process: 'process/browser',
>         }),
>     ],
> });
> ```
> 
> ...that seemed to solve the problem.
> 
> @sambindoff We had an issue where errors weren't properly displaying. I fixed that and just tested a fresh Laravel app with Laravel UI, and it seems to be compiling properly.

Is this still currently the only fix for this? I'm still getting the same `process is not defined error` using it in a custom .JS file with `process.env.MIX_STRIPE_PUBLISHABLE_KEY`, on Laravel 8 and Mix 6.
