### ISSUE TITLE
Add loader to existing rule?

### ISSUE THREAD

**Issue by yaquawa** [JeffreyWay/laravel-mix#2691]
-   Laravel Mix Version: 6

### Description:
I'm using laravel-mix with vue.js:
```js
mix.vue({ version: 3 })
```

But I want to add another loader to the `*.vue` files, with the raw webpack.config.js I can do it like this:
```js
module.exports = {
  //...
  module: {
    rules: [
      {
        test: /\.vue$/,
        use: [
          {
            loader: 'vue-loader',
            options: {/* ... */}
          },
          {
            loader: 'additional-loader', // HOW TO ADD THIS ONE TO THE existing 'vue-loader' ?
          }
        ]
      }
    ]
  }
};
```

But how to do this in laravel mix?

**Comment by JeffreyWay** [comment]
You'll have to manually do it. Play around with:

```
mix.override(webpackConfig => {
   console.log(webpackConfig);
});
```

You'll need to some variant of `webpackConfig.module.rules.find(rule => rule.test.toString() === '/\\.vue$/')`
