### ISSUE TITLE
When i run watch the error are showing in the windowns notification not in the console, how i can change that ?

### ISSUE THREAD

**Issue by mariojgt** [JeffreyWay/laravel-mix#2692]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`)
-   Node Version (`node -v`):
-   NPM Version (`npm -v`):
-   OS:

**Comment by jonXmack** [comment]
This fixed it for me https://github.com/JeffreyWay/laravel-mix/issues/2680

**Comment by mattbloomfield** [comment]
Ha this was incredibly frustrating, thanks @jonXmack for the workaround
