### ISSUE TITLE
Passing --progress flag does not print out compilation progress

### ISSUE THREAD

**Issue by Ahuahuachi** [JeffreyWay/laravel-mix#2698]
-   Laravel Mix Version: 6.0.2
-   Node Version: v15.5.0
-   NPM Version: 7.3.0
-   OS: Ubuntu 20.04.1 LTS on Windows 10 x86_64 

### Description:
`npx mix -- --progress` does not prints out compilation progress.
Don't know if this is a bug, but could not find any information other than passing the instructions directly to webpack as if using Laravel Mix 5

### Steps To Reproduce:
1. Install laravel-mix as stand-alone
2. Make configuration file and add some assets to compile
3. Run `npx mix -- --progress`

**Comment by thecrypticace** [comment]
This is a odd. We already pass the progress flag internally but even with `stats.all` set to true there's no compilation progress showing anymore. I'm not sure if this is a mix regression or a webpack-cli regression. Will need to look into it.

**Comment by JeffreyWay** [comment]
This was annoying me, too. Looks like it was a webpack bug that has since fixed itself.

**Comment by Ahuahuachi** [comment]
Don't know if this is related or is a different bug, but it seems that this behavior is now occurring with `npx mix watch -- --progress`
Is it also a webpack-cli bug?
