### ISSUE TITLE
getting empty output for app.js because of leftover 'webpackBootstrap' code that generates when running npx mix

### ISSUE THREAD

**Issue by plzwork1** [JeffreyWay/laravel-mix#2699]
-   Laravel Mix Version: 6.0.3
-   Node Version (`node -v`): 14.15.3
-   NPM Version (`npm -v`): 6.19.4
-   OS: Windows 10 x64

### Steps To Reproduce:
1. open fresh project in visual studio code
2. create src folder for app.js in root
3. create app.js
4. run npm init -y to create package.json
5. run npm install laravel-mix --save-dev
6. create webpack.mix.js and edit to:

```
// webpack.mix.js

let mix = require('laravel-mix');

mix.js('src/app.js', '').setPublicPath('dist');
```

7.  just add any simple function to app.js in the src folder, I do:
```
function myAlert() {
    alert('hello');
}
```
8. run npx mix, let dependencies install, then run npx mix again. app.js compiles to:

```
/******/ (() => { // webpackBootstrap
/*!********************!*\
  !*** ./src/app.js ***!
  \********************/
  function myAlert() {
    alert('hello');
}
/******/ })()
;
```
9. run 'npx mix --production' and it compiles to an empty app.js file.

**Comment by thecrypticace** [comment]
The "empty" function you see is an IIFE (https://en.wikipedia.org/wiki/Immediately_invoked_function_expression). Your code in dev mode will be wrapped in one. This doesn't affect behavior.

As far as production compilation goes this looks like the correct behavior to me. There are no calls or other references to the function it (like attaching it to the window object). Tree shaking happens in production which would cause this to result in an empty app.js file.

If you need to disable tree shaking optimizations:
```
mix.webpackConfig({
    optimization: {
        providedExports: false,
        sideEffects: false,
        usedExports: false
    }
});
```

**Comment by plzwork1** [comment]
I appreciate the quick response. Your explanation makes things make a lot more sense !
