### ISSUE TITLE
dist/css/* → dicss/*

### ISSUE THREAD

**Issue by assertchris** [JeffreyWay/laravel-mix#27]
Kicking the tyres and noticed a strange thing happening. I am unsure whether it's something I've goofed or a side-effect of the folder structure I'm aiming for.

* Node 7.3.0
* NPM 3.10.10
* Mix ^0.2.5
* Instructions at https://github.com/JeffreyWay/laravel-mix/blob/master/docs/installation.md#stand-alone-project

```js
let mix = require("laravel-mix").mix

mix.js("src/js/app.js", "dist/js")
mix.sass("src/scss/app.scss", "dist/css")
```

`./src/scss/app.scss` is compiled to `./dicss/app.css`.

```js
let mix = require("laravel-mix").mix

mix.js("src/js/app.js", "build")
mix.sass("src/scss/app.scss", "build")
```

`./src/scss/app.scss` is compiled to `./buiapp.css`.

**Comment by assertchris** [comment]
Additional:

If I add the following log to `Mix.js`:

```js
cssOutput() {
    let regex = new RegExp('.?/?' + this.publicPath);

    console.log(this[this.cssPreprocessor].output[
        this.versioning.enabled ? 'hashedPath' : 'path'
    ], this[this.cssPreprocessor].output[
        this.versioning.enabled ? 'hashedPath' : 'path'
    ].replace(regex, ''))

    return this[this.cssPreprocessor].output[
        this.versioning.enabled ? 'hashedPath' : 'path'
    ].replace(regex, '');
}
```

...I see: `dist/css/app.css dicss/app.css`. This makes me thing the regex (`.?/?`) is incorrectly removing `st/` from the output path, if `publicPath` is not set.

**Comment by assertchris** [comment]
Additional:

I can confirm: if I add `mix.setPublicPath(__dirname + "/dist")` to `webpack.mix.js`, the output is no longer strange.

**Comment by JeffreyWay** [comment]
Thanks, Chris!
