### ISSUE TITLE
Watch command throws "JavaScript heap out of memory" while using with tailwindcss

### ISSUE THREAD

**Issue by ponopress** [JeffreyWay/laravel-mix#2711]
-   Laravel Mix Version: `6.0`
-   Node Version (`node -v`): `15.4`
-   NPM Version (`npm -v`): `6.14.8`
-   OS:

### Description:
I am using `laravel-mix` with `tailwindcss` and compiling with SASS. When running on "`npm run watch`", the first compilation takes some time but does it successfully. After i make a small change on one of the file, the command throws error like "`FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory`".

I hoped that it would be solved in version 6 but it still persists.  After trying out these solutions on #2470 and others but still to no vein. 

So far debugging it i found that if i don't import @tailwind utilities, there's no any issue. However I do not have any work around it.

Here's my webpack.mix.js file:
```
// Compile SASS/CSS.
mix.sass( `${devPath}/scss/app.scss`,             'css', sassConfig )    
    .options({
        processCssUrls: false,
	    postCss: [ tailwindcss('./tailwind.config.js') ]
    })
```
My app.scss file:
```
@tailwind base;
@tailwind components;
@tailwind utilities;

@import 'settings/_index';
@import 'tools/_index';
```

**Comment by thecrypticace** [comment]
1. What version of tailwind
2. Does this happen if you only import the tailwind utilities without any other CSS?
3. What's in your SASS config?
4. Can you reproduce this on a brand new, empty project?
5. How customized is your tailwind config?

**Comment by ponopress** [comment]
1. Tailwind version 2.0.2
2. Only importing tailwind utilities does not have any issue but it's still slow ranging from 6000ms to 7000ms.
3. My SASS config is like this:
```
// Compile SASS/CSS.
mix.sass( `${devPath}/scss/editor.scss`,             'css', sassConfig )
    .sass( `${devPath}/scss/customize-controls.scss`, 'css', sassConfig )
    .sass( `${devPath}/scss/screen.scss`,             'css', sassConfig )    
    .options({
        processCssUrls: false,
	    postCss: [ tailwindcss('./tailwind.config.js') ]
    })
```
4. Yes, I have tried it in an empty project and it persits.
5. My tailwind config is something like this:
```
module.exports = {
    // purge: {
    //     mode: 'all',
    //     preserveHtmlElements: false,
    // },
    theme: {
        extend: {
	        colors: {
	            black: '#1A202C',
	            white: '#F8F8F8',
	            red: '#C41B4D',
	            light: '#4a5568',
	        },
	        typography: {
                default: {
		            css: {
		                color: '#1A202C',
		                a: {
			                color: '#1A202C',
			                // '&:hover': {
			                //     color: '#C41B4D',
			                // },
		                },
		            },
                },
	        },
        },
        fontFamily: {
	        display: ['Gelasio', 'sans-serif'],
	        body: ['Rubik', 'sans-serif'],
        },
        
    },
    variants: {},
    plugins: [
	    require('@tailwindcss/typography'),
    ],
}
```

**Comment by jamesburrow23** [comment]
@ponopress not sure if you're still having this issue but I was able to work around it by adjusting my package.json file to include the node module flag to increase the maximum memory (in my example to 8000 MB):

```
"scripts": {
  "development": "NODE_OPTIONS=\"--max-old-space-size=8000\" mix "
}
```

**Comment by ponopress** [comment]
I tried it but it didn't solve the issue. Is it the issue with the ram space or something?

**Comment by jamesburrow23** [comment]
@ponopress Yeah I eventually ran into this issue again, I never found a solution to the actual problem.  For me I just started using `npx` as documented in the tailwind docs to compile my app's main css file (I then removed that from the mix config and never ran into the issue again).

I'm not the strongest when it comes to troubleshooting this kind of thing so it was a viable workaround for me since I rarely need to recompile my css

**Comment by thecrypticace** [comment]
@ponopress @jamesburrow23 Do you know how much memory do you have on the machine or VM you're using to compile?

**Comment by sinnbeck** [comment]
@jamesburrow23 How do you manage to update the mix-manifest.json then? Or do you handle this some other way?

**Comment by mikebronner** [comment]
@jamesburrow23 can you link to that reference in the tailwind docs? I tried looking everyone for use of the `npx` command but couldn't find anything. Thanks!
