### ISSUE TITLE
How to combine with gulp?

### ISSUE THREAD

**Issue by stephan-v** [JeffreyWay/laravel-mix#272]
How would you combine this with gulp?

I know you can use a webpack gulp plugin to talk to webpack but I would have no clue about how this set this up. Although webpack is ideal as a bundler even the webpack team acknowledges it is not a replacement for a taskrunner. I still need to be able to process images, etc.

Although I could easily just dump `& gulp` inside the npm scripts I would be left with 2 output streams. One from Gulp and one from Webpack. This is far from ideal.

Any tips on how to achieve a good combination of laravel mix alongside gulp?

**Comment by JeffreyWay** [comment]
If you really need Gulp functionality, why not just use Laravel Elixir and be done with it?

Alternatively, I'd just run my Webpack and then Gulp commands together. `webpack && gulp`.

**Comment by stephan-v** [comment]
Are all the image assets from Laracasts in JavaScript then? I am wondering about your image workflow alongside mix. I don't think you have a lesson or info on it. I would love to know how you use it in conjunction with this. 

Would love to hear from you. Thanks for your reply!
