### ISSUE TITLE
Link to laravel-mix.com in GitHub repository page

### ISSUE THREAD

**Issue by binotaliu** [JeffreyWay/laravel-mix#2720]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`)
-   Node Version (`node -v`):
-   NPM Version (`npm -v`):
-   OS:

### Description:

No link in `about` section now:
![a screenshot showing "about" section in laravel-mix's GitHub repository page. Texts showing on the image: About The power of webpack, distilled for the rest of us. Topics: laravel webpack](https://user-images.githubusercontent.com/67255597/103292934-d73ac680-4a29-11eb-8390-736a74fb5fab.png)

Would be nice if there is a link:

![a screenshot showing "about" section in laravel-mix's GitHub repository page with a link to laravel-mix's home page. Texts showing on the image: About The power of webpack, distilled for the rest of us. Link: laravel-mix.com Topics: laravel webpack](https://user-images.githubusercontent.com/67255597/103293046-110bcd00-4a2a-11eb-8fef-f64e2ad13f98.png)

### Steps To Reproduce:

1. Buy a computer.
2. Install an OS.
3. Install `Firefox`.
4. Open `Firefox`.
5. Click on address bar.
6. Type in `https://github.com/JeffreyWay/laravel-mix`.
7. Hit `Enter` key on your keyboard.

**Comment by JeffreyWay** [comment]
I don't maintain laravel-mix.com and can't vouch for it.
