### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by Daniel4Digital** [JeffreyWay/laravel-mix#2722]
-   Laravel Mix Version: 6.0.5
-   Node Version (`node -v`): 15.4.0
-   NPM Version (`npm -v`): 7.2.0
-   OS: Win10

### Description:
Can't run "npm run dev" with .purgeCss({ enabled: true }) (if I put false it works perfectly)

I was using an older version of laravel-mix-purgecss (0.1.2 I guess) and older version of laravel-mix and postCCS etc, the problem happened back then too. I update all packages to last version, so now I'm using:
    "laravel-mix": "^6.0.5",
    "laravel-mix-merge-manifest": "^2.0.0-beta.2",
    "laravel-mix-purgecss": "^6.0.0",

My project uses laravel + vue.

This is the error, any idea why (Not sure if the problem is from this plugin)?

`16% building 0/1 entries 3135/3138 dependencies 600/2139 modules
<--- Last few GCs --->

[4105:0x63c4ff0]   341632 ms: Mark-sweep 5071.2 (5160.3) -> 5060.0 (5162.6) MB, 629.5 / 0.0 ms  (average mu = 0.460, current mu = 0.176) task scavenge might not succeed
[4105:0x63c4ff0]   342368 ms: Mark-sweep 5073.7 (5162.6) -> 5062.1 (5164.8) MB, 600.2 / 0.0 ms  (average mu = 0.353, current mu = 0.184) task scavenge might not succeed
[4105:0x63c4ff0]   343102 ms: Mark-sweep 5075.8 (5164.8) -> 5064.2 (5166.8) MB, 596.7 / 0.0 ms  (average mu = 0.281, current mu = 0.188) task scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0xa68ab0 node::Abort() [webpack]
 2: 0x99bc57 node::FatalError(char const*, char const*) [webpack]
 3: 0xc4214e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [webpack]
 4: 0xc424c7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [webpack]
 5: 0xe0c085  [webpack]
 6: 0xe3b613 v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [webpack]
 7: 0xe481c6 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [webpack]
 8: 0xe342ef v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [webpack]
 9: 0xe34568 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [webpack]
10: 0xe26389 v8::internal::ItemParallelJob::Run() [webpack]
11: 0xe4a150 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [webpack]
12: 0xe4a993 v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [webpack]
13: 0xe4ad55 v8::internal::MarkCompactCollector::Evacuate() [webpack]
14: 0xe5d4c1 v8::internal::MarkCompactCollector::CollectGarbage() [webpack]
15: 0xe19388 v8::internal::Heap::MarkCompact() [webpack]
16: 0xe1ad18 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [webpack]
17: 0xe839dc v8::internal::ScavengeJob::Task::RunInternal() [webpack]
18: 0xd38f5b non-virtual thunk to v8::internal::CancelableTask::Run() [webpack]
19: 0xad9294 node::PerIsolatePlatformData::RunForegroundTask(std::unique_ptr<v8::Task, std::default_delete<v8::Task> >) [webpack]
20: 0xadb0f9 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [webpack]
21: 0x144be86  [webpack]
22: 0x145e965  [webpack]
23: 0x144c7b8 uv_run [webpack]
24: 0x9bbed5 node::SpinEventLoop(node::Environment*) [webpack]
25: 0xaa9f30 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [webpack]
26: 0xa3584a node::Start(int, char**) [webpack]
27: 0x7f0c3e9902e1 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
28: 0x9b8f3c  [webpack]
Aborted`

### Steps To Reproduce:
In my webpack if I enable mix.purgeCss({ enabled: true }), then it doesn't finish the npm run dev

**Comment by mr-feek** [comment]
Have you tried giving the process more memory?

**Comment by Daniel4Digital** [comment]
Thanks! I was using 6Gb, I've given the docker 8Gb and put node with 8gb aswell, and now it worked.
