### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by dotjan37** [JeffreyWay/laravel-mix#2726]
-   Laravel Mix Version: 5.0.1
-   Node Version (`node -v`): 10.23.0
-   NPM Version (`npm -v`): 6.14.8
-   OS: Linux

### Description:
React 17 does not need anymore this import for each component:
import React from 'react';

Will Laravel Mix support this in future? It does not work in Laravel Mix 5.0.1

**Comment by JeffreyWay** [comment]
Can you give me more information about what needs to change in order to support React 17?

**Comment by thecrypticace** [comment]
Note that React 17 still supports the old style usage of `createElement` so there's nothing we need to do to support React 17. However, if you're looking to use the new JSX transform I'd suggest upgrading to Mix v6 which uses the new automatic runtime support:

https://github.com/JeffreyWay/laravel-mix/blob/b112e13d0a3fb5602872b29bde497e4e96f78230/src/components/React.js#L26
