### ISSUE TITLE
Install all dependencies at once

### ISSUE THREAD

**Issue by JeffreyWay** [JeffreyWay/laravel-mix#2728]
One annoying quirk (my fault) is that Mix doesn't install all required dependencies in one go. Instead, when it runs into a missing dependency, it stops and immediately runs the install command. This means you might have to run mix two or more times to pull in all required dependencies for your current webpack.mix.js file. 

<img width="1536" alt="Screen Shot 2020-12-30 at 10 44 28 AM" src="https://user-images.githubusercontent.com/183223/103364523-113cb480-4a8c-11eb-8b2e-2f796ff6eddf.png">

Instead, I'd prefer that it cycle through all relevant components and build up a single install command for everything.

**Comment by thecrypticace** [comment]
I've thought about this too. Something I've had in the back of my head for a while. It should be fairly simple to do.
