### ISSUE TITLE
`mix.inProduction()` is false with `--production` flag set

### ISSUE THREAD

**Issue by RafaelKr** [JeffreyWay/laravel-mix#2729]
-   Laravel Mix Version: 6.0.5 (`npm list --depth=0`)
-   Node Version (`node -v`): v13.7.0
-   NPM Version (`npm -v`): 6.14.9
-   OS: Linux Mint 19.2 Cinnamon

### Description:
I'm using the following npm scripts:
```json
"scripts": {
    "dev": "npm run development",
    "development": "mix",
    "watch": "mix watch",
    "watch-poll": "mix watch -- --watch-options-poll=1000",
    "hot": "mix watch --hot",
    "prod": "npm run production",
    "production": "mix --production"
},
```

My `webpack.mix.js` includes the following code snippet:
```js
console.log(mix.inProduction()) // always false

if (mix.inProduction()) {
    mix.version();
} else {
    mix.sourceMaps();
}
```

But `mix.inProduction()` is always false when running `npm run production`.

I found out production mode is determined in `node_modules/laravel-mix/src/config.js` on line 10:
```js
production: process.env.NODE_ENV === 'production' || process.argv.includes('-p'),
```
And it works when I run `NODE_ENV=production npm run production`.

My `process.argv` outputs the following (Home-Path substituted with `<$HOME>`):
```json
[
  "<$HOME>/.nvm/versions/node/v13.7.0/bin/node",
  "<$HOME>/path/to/project/node_modules/.bin/webpack",
  "--progress",
  "--config=<$HOME>/path/to/project/node_modules/laravel-mix/setup/webpack.config.js"
]
```

I think it should also work with `--production` flag on the `mix` call.

**Comment by JeffreyWay** [comment]
Hmm - can anyone else reproduce this issue? I just did a quick test on a fresh install that `console.log`s `mix.inProduction()`. Everything seems correct.

<img width="484" alt="Screen Shot 2020-12-30 at 3 14 23 PM" src="https://user-images.githubusercontent.com/183223/103378824-ab632380-4ab1-11eb-95f8-9854b7930047.png">

**Comment by florianbouvot** [comment]
@JeffreyWay @RafaelKr I try on a fresh install using Mix 6.0.6 and it works but I've the same issue with a beta last month.

**Comment by RafaelKr** [comment]
I just did a `npm i -D laravel-mix@latest` and the problem still persists with Laravel Mix v6.0.6

Digging deeper I found out where the parameter is lost for me.
https://github.com/JeffreyWay/laravel-mix/blob/ff9ff51b7bf9406987bf08ce45144c237f2603a1/bin/cli.js#L49-L54

I have set `NODE_ENV=development` globally, so everything on my system starts with it by default. This is why laravel-mix always sets `env` to `process.env.NODE_ENV` which is `development` for me.

I think it would make sense to do it the other way around. If `opts.production` is set it should be `production`. If it's not set it should use `process.env.NODE_ENV` and if that's also not set it should fall back to `development`. What do you think about that?

Also webpack itself does it likewise when `webpack -p` is called, at least the docs say so: `https://webpack.js.org/guides/production/#cli-alternatives`

**Comment by RafaelKr** [comment]
I created PR #2744 which implements my suggestion.

Maybe also the ` || process.argv.includes('-p'),` can be removed here?
https://github.com/JeffreyWay/laravel-mix/blob/ff9ff51b7bf9406987bf08ce45144c237f2603a1/src/config.js#L10
But I'm not sure if this is ever used or if it can be safely deleted.
