### ISSUE TITLE
Mix combining to different directory

### ISSUE THREAD

**Issue by gstoa** [JeffreyWay/laravel-mix#273]
I'm trying to simply combine a few css files to a single css file like below:

`    .combine([
        'resources/assets/css/app-stage.css',
        'resources/assets/css/custom.css'
    ], 'public/css/app-full.css')
`

Running npn run dev returns an error indicating that there is no file or directory 'public/css/app-full.css'.  Obviously the two files are physically located in the 'resources/assets/css' directory.  I have tried changing 'public...' to '../public' with no luck.  Worked fine for me with gulp.

**Comment by adriaanzon** [comment]
Duplicate: #271

**Comment by gstoa** [comment]
That's it -- as a workaround I'll just create the appropriate directories in public.  Normally, everything in my public directory is populated with a script.

**Comment by hovsep** [comment]
@gstoa also you can use another trick - copy an empty file to destination directory before combine, it will create all directories. 

It work for me:```

//First i copy dummy file to codemirror directory that not exists
.copy('public/empty.txt', 'public/js/vendor/codemirror/empty.txt')
//Then I use combine and it works,because directories are already created
    .combine([
        'node_modules/codemirror/lib/codemirror.js',
        'node_modules/codemirror/mode/xml/xml.js',
        'node_modules/codemirror/mode/javascript/javascript.js',
        'node_modules/codemirror/mode/css/css.js',
        'node_modules/codemirror/mode/php/php.js',
        'node_modules/codemirror/mode/htmlmixed/htmlmixed.js',
        'node_modules/codemirror/addon/search/search.js',
        'node_modules/codemirror/addon/search/searchcursor.js',
        'node_modules/codemirror/addon/dialog/dialog.js',
        'node_modules/codemirror/addon/selection/active-line.js',
        'node_modules/codemirror/addon/display/fullscreen.js',
    ], 'public/js/vendor/codemirror/editor.js')

```
