### ISSUE TITLE
webpack-cli Unknown option '--hide-modules'

### ISSUE THREAD

**Issue by ashwani65** [JeffreyWay/laravel-mix#2739]
Laravel Mix Version: 6.0.0-beta-4
Node Version: v12.14.0
NPM Version: 6.14.10
OS: Ubuntu 10.04

### Description:
After running `npm run watch` produces an error like `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"
error: unknown option '--hide-modules' `

### Steps To Reproduce:
`npm install laravel-mix --save-dev` 

then adding the script  in package.json

 `"scripts": {
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "npm run development -- --watch",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },`

and now if I run `npm run watch` then it produces an error

**Comment by stefanhuber** [comment]
and how did you resolve it?

**Comment by thecrypticace** [comment]
Please update your scripts when using Mix v6: https://github.com/JeffreyWay/laravel-mix/blob/628f6062cceb77610b1813e3179abcbd043a4642/UPGRADE.md#update-your-npm-scripts
