### ISSUE TITLE
In v6 there is no feedback when changes in source are detected and being recompiled (missing progress)

### ISSUE THREAD

**Issue by prcdpr** [JeffreyWay/laravel-mix#2740]
-   Laravel Mix Version: 6.0.6
-   Node Version: v14.13.1
-   Yarn: 1.22.5
-   OS: Win10 (PowerShell)

### Description:
In previous version of Laravel Mix command line output changed just after changes in source code were detected but before they're recompiled.

In v6, after I edit source code nothing happens in console output, only after everything is recompiled (after 5-10s) there is a summary of compilation.

### Steps To Reproduce:
Launch `mix watch`, edit source code, observe command line output

**Comment by Ahuahuachi** [comment]
Reproduced also in the following environment:

- Laravel Mix Version: 6.0.6
- Node Version: v15.5.0
- NPM Version: 7.3.0
- OS: Ubuntu 20.04.1 LTS on Windows 10

**Comment by mikemand** [comment]
I don't know if this is related or not, but there also used to be a small delay in Mix 5 before `watch` started recompiling. It was almost like `watch` was being debounced so it wouldn't actually start recompiling until there was a pause of `x` seconds after a file change was detected. I don't know if this was the intended behavior of Mix 5, but I have a feeling it is a result of the missing progress indicator.

**Comment by mikemand** [comment]
Jeffrey added a progress bar in https://github.com/JeffreyWay/laravel-mix/commit/85eb3efe4e9a1a2e56e633e2de8822281336e098 that solves the first part of this. There is still no delay between file save and compilation start, but I have learned to live with it.

**Comment by mankowitz** [comment]
In addition, previous versions of mix showed the compile time so you could make sure that you are using the most recent compilation. Is there a way to see the compile time when running npm run watch?
