### ISSUE TITLE
Feature request: Ability to easily include / exclude additional files for babel-loader

### ISSUE THREAD

**Issue by philbates35** [JeffreyWay/laravel-mix#2742]
The default behaviour is that all of `node_modules` is excluded from babel-loader:

In my case, I need to support IE11, and there is 1 package `punycode` in node_modules that I need to feed into babel-loader, using the same babel config used on my app JS files.

The cleanest way I could get this to work was to dig into the source, copy-paste-tweak:

```js
// webpack.mix.js
mix.webpackConfig({
    module: {
        rules: [
            {
                test: path.resolve(__dirname, 'node_modules/punycode'),
                use: [
                    {
                        loader: 'babel-loader',
                        options: Config.babel()
                    }
                ]
            }
        ]
    }
})
```
While this works it felt a clunky, and that I was reaching into the internals a little bit. It got me thinking if there could be an easier way, some psudo code might look like:

```js
// Don't pass any node_modules into babel-loader, default behaviour matching how it is now
mix.js('resources/js/app.js', 'public/js');

// Pass only "punycode" and "someotherpackage" packages files into babel-loader, ignore the rest of node_modules
mix
    .options({
        babelLoader: {
            packages: ['punycode', 'someotherpackage'],
        }
    })
    .js('resources/js/app.js', 'public/js');


// Override the default babel-loader test
mix
    .options({
        babelLoader: {
            test: /\.(jsx?|tsx?)$/,
        }
    })
    .js('resources/js/app.js', 'public/js');
```
I'm sure there there are many reasons why this API isn't possible and probably needs more thought. But I think something like this could be useful as its come up at least a few times before:
* https://github.com/JeffreyWay/laravel-mix/issues/2072
* https://github.com/JeffreyWay/laravel-mix/issues/1906#issuecomment-455241790
* https://github.com/JeffreyWay/laravel-mix/issues/631#issuecomment-299786281
* https://github.com/JeffreyWay/laravel-mix/issues/2033

**Comment by daun** [comment]
I wrote an extension to configure which npm packages get compiled by babel. Might solve your problem. See [laravel-mix-transpile-node-modules](https://github.com/daun/laravel-mix-transpile-node-modules).

```js
mix.transpileNodeModules(['punycode'])
```

**Comment by lk77** [comment]
@daun does mix.transpileNodeModules needs to be called before mix.polyfill ? 

i'm trying to polyfill pdfjs-dist, and i expect the core-js/stable/global-this polyfill to be included which is not the case.

the polyfill is included if i change weback config directly

**Comment by daun** [comment]
@lk77 Can't say, I don't use the polyfill plugin. It's very possible that these two plugins overwrite each other (there's a related [issue](https://github.com/daun/laravel-mix-transpile-node-modules/issues/2) without definite conclusion).

However, pdfjs has a polyfilled ES5 dist version if I remember correctly. You could use that one: `pdfjs-dist/es5/build/pdf.min`

**Comment by lk77** [comment]
ok thanks, i will use that one instead then.
