### ISSUE TITLE
Uncaught TypeError: Vue.component is not a function

### ISSUE THREAD

**Issue by ashwin-nath-m** [JeffreyWay/laravel-mix#2747]
-   Laravel Mix Version: 6.0.6 (`npm list --depth=0`)
-   Node Version (`node -v`): v12.18.2
-   NPM Version (`npm -v`): 6.14.6
-   OS: Win10

### Description:
Unable to get vue to work. Throwing Uncaught TypeError: Vue.component is not a function

### Steps To Reproduce:

1. Fresh install laravel 8
2. Add laravel/ui 
3. Run php artisan ui vue --auth
4. Add .vue() in webpack.mix,js
5. Run npm run dev
6. Load the site and look at the console logs.

**Comment by JeffreyWay** [comment]
It's because we're using the esm build of Vue. The `laravel/ui` package needs an update to either import Vue as an ES6 module, or to add `.default` after the require.

For your issue, use this in `resources/js/app.js`:

```js
window.Vue = require("vue").default;
```

**Comment by rognales** [comment]
Perhaps this can be mentioned in the upgrade guide

**Comment by sPITf1re-dev** [comment]
added `.default` but it didn't help... getting the error again

**Comment by meetsohail** [comment]
> It's because we're using the esm build of Vue. The `laravel/ui` package needs an update to either import Vue as an ES6 module, or to add `.default` after the require.
> 
> For your issue, use this in `resources/js/app.js`:
> 
> ```js
> window.Vue = require("vue").default;
> ```

It doesn't worked in my case! Is there any other way to fix the issue! thanks
