### ISSUE TITLE
Can't find path

### ISSUE THREAD

**Issue by Chintu12a** [JeffreyWay/laravel-mix#2758]
-   Laravel Mix Version: 6.0
-   Node Version (`node -v`): v12.18.4
-   NPM Version (`npm -v`): 6.14.6
-   OS:  @Windows

I cant install laravel-mix v6.0 so please help me  to install it.
![Screenshot (25)](https://user-images.githubusercontent.com/52694889/104090948-24c3f880-52a0-11eb-9e57-c7d28691e62f.png)

**Comment by skeeith** [comment]
`https://laravel-mix.com/docs/6.0/installation`

The instruction here is pretty clear, you don't have the webpack.mix.js in your root folder

```
You should now have the following directory structure:

node_modules/
package.json
webpack.mix.js

Open webpack.mix.js and add the following code:

// webpack.mix.js

let mix = require('laravel-mix');

mix.js('src/app.js', 'dist').setPublicPath('dist');
```

**Comment by Chintu12a** [comment]
and how run laravel-mix file

**Comment by Chintu12a** [comment]
I create this then what after that

**Comment by JeffreyWay** [comment]
Use the forum please.
