### ISSUE TITLE
In v6, when using `npm run hot`, bundled files are not written into public folder but are still served correctly

### ISSUE THREAD

**Issue by yqlim** [JeffreyWay/laravel-mix#2759]
-   Laravel Mix Version: 6.0.9 (`npm list --depth=0`)
-   Node Version (`node -v`): 12.20.0
-   NPM Version (`npm -v`): 6.14.9
-   OS: Windows 10

### Context:

I have a blade component that automatically injects scripts and styles by name when called:

```blade
{{-- asset-injector.blade.php --}}

@props(['name' => ''])

@if(isset($name) && !empty($name))
  @if (file_exists(public_path("js/$name.js")))
    @push('scripts')
      <script src="{{ mix("js/$name.js") }}" defer></script>
    @endpush
  @endif
  @if (file_exists(public_path("css/$name.css")))
    @push('styles')
      <link rel="stylesheet" href="{{ mix("css/$name.css") }}">
    @endpush
  @endif
@endif


{{-- example.blade.php --}}

<div class="any-component>
  @once
    {{-- Automatically injects corresponding "example.js" and "example.css" if exists  --}}
    <x-asset-injector name="example" />
  @endonce
</div>
```

### Description:

Just upgraded to version 6 from version 5.

In version 5, when I run `npm run hot`, bundled files will be written into public folder (or whatever folder set by `mix.setPublicPath`).

That is not the case anymore in version 6.

In version 6, when I run `npm run hot`, the files are bundled, but are not being written into the public folder. 

The files are still served correctly with `mix('path/to/file')`. The problem is that it is not writing into public folder anymore, so that the `file_exists()` call in the component shown above will always be false when in hot reloading mode.

This only happens in `npm run hot`. When running dev, watch, and prod, the files are created and written correctly into public folder.

### Question

Is this behaviour a bug or by design? If it is by design, why are we doing this and where have the bundled files gone and being served from?

### Steps To Reproduce:

Run `npm run hot` and observe bundled files will not be created/written into public path but are still served correctly.

**Comment by thecrypticace** [comment]
I don't recall if HMR previously wrote files to disk but you are correct in saying it doesn't do this now. When you run Mix in "hot" mode webpack dev server gets started and serves the files over HTTP (or HTTPS depending on your config). When this happens the `mix(…)` function returns urls like `http://localhost:8080/js/app.js` instead of paths to a file like `/js/app.js?id=something_here`. This url consequently points to files hosted in memory by webpack dev server. This means it does not matter if the files are on disk are not.

While I have not tested it you should be able to write the files to disk by adding the following to your mix config:
```js
mix.webpackConfig({
  devServer: {
    writeToDisk: true
  }
})
```

**Comment by yqlim** [comment]
> I don't recall if HMR previously wrote files to disk but you are correct in saying it doesn't do this now. When you run Mix in "hot" mode webpack dev server gets started and serves the files over HTTP (or HTTPS depending on your config). When this happens the `mix(…)` function returns urls like `http://localhost:8080/js/app.js` instead of paths to a file like `/js/app.js?id=something_here`. This url consequently points to files hosted in memory by webpack dev server. This means it does not matter if the files are on disk are not. (Note that this was also the case in Mix 5 — files were served from memory by webpack dev server)
> 
> While I have not tested it you should be able to write the files to disk by adding the following to your mix config:
> 
> ```js
> mix.webpackConfig({
>   devServer: {
>     writeToDisk: true
>   }
> })
> ```

@thecrypticace You're right, it most likely also doesn't output actual files into public folder in v5.

Anyway, I tried your solution by extending webpack config, but webpack doesn't recognise the property and throws "Invalid configuration" error.

I searched in the webpack docs, the config option does exists in the webpack version Mix is using. Looking through Mix's type declaration, it seems that `devServer` option is not part of the allowed config to extend from.

I've also tried using `mix.override()` and also didn't work.

Do you know if I'm doing this correctly or if there is any other way to override this writeToDisk behaviour?

**Comment by muhammedraqeeb** [comment]
Gi

**Comment by muhammedraqeeb** [comment]
Gi

**Comment by thecrypticace** [comment]
Ah sorry, the webpack documentation hasn't been updated for webpack dev server v4 configuration.

The correct version is:
```js
mix.webpackConfig({
  devServer: {
    dev: { writeToDisk: true }
  }
})
```

All webpack-dev-middleware compatible configuration was removed in favor of passing it via the `dev` option.

**Comment by yqlim** [comment]
@thecrypticace ah I see. It works now, thank you!
