### ISSUE TITLE
Error on npm run dev with Laravel Project

### ISSUE THREAD

**Issue by emineinnovations** [JeffreyWay/laravel-mix#2761]
Hi,

I get following error when i am try to run **npm run dev** command on windows power-shell
--------------------------------------------------------------------------------------------------

> @ development C:\Users\Praneeth Gamage\Desktop\Laravel_Projects\posty
> mix

[webpack-cli] Running multiple commands at the same time is not possible
[webpack-cli] Found commands: 'bundle', 'Gamage\Desktop\Laravel_Projects\posty\node_modules\laravel-mix\setup\webpack.config.js'
[webpack-cli] Run 'webpack --help' to see available commands and options
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `mix`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Praneeth Gamage\AppData\Roaming\npm-cache\_logs\2021-01-10T12_30_36_179Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Praneeth Gamage\AppData\Roaming\npm-cache\_logs\2021-01-10T12_30_36_230Z-debug.log

**Comment by Wulfheart** [comment]
I have the same problem right now. Even ``npx mix`` doesn't work and the command cannot be found. I'm using it on windows.

**Comment by EdTheDuck** [comment]
I have the same problem.
NPM v6.14.11
Mix v6.0.9
Also on Windows.

**Comment by Wulfheart** [comment]
Guess they have only tested it on linux and mac. 😃

**Comment by thecrypticace** [comment]
The tests run on Node 12, 13, and 14 on Linux and Windows. I'm gonna take a look at this at some point soon. We're quoting the path to the webpack config file in the CLI to fix this very problem on Windows. It seems like something is causing the quotes to be removed.

**Comment by adrian250997** [comment]
I have the same problem, is there a solution?

**Comment by fikrisuheri** [comment]
i have the same problem

**Comment by fikrisuheri** [comment]
![image](https://user-images.githubusercontent.com/61069138/104141703-a32cb180-53ea-11eb-96fe-d341f9bdaea0.png)

**Comment by adrian250997** [comment]
I already solved it, in my case, it was the blank spaces in the path to the project

**Comment by adrian250997** [comment]
@fikrisuheri   verify that this path is complete, if it is cut it is because of the blank spaces, the solution is to move the project from place to a path that does not have spaces.
![image](https://user-images.githubusercontent.com/33580067/104142285-8eb3cf00-5380-11eb-9c46-beeb20311b42.png)

**Comment by fikrisuheri** [comment]
> @fikrisuheri verify that this path is complete, if it is cut it is because of the blank spaces, the solution is to move the project from place to a path that does not have spaces.

thanks, i will try it

**Comment by fedriekchandra2502** [comment]
> 
> 
> @fikrisuheri verify that this path is complete, if it is cut it is because of the blank spaces, the solution is to move the project from place to a path that does not have spaces.
> ![image](https://user-images.githubusercontent.com/33580067/104142285-8eb3cf00-5380-11eb-9c46-beeb20311b42.png)

Thank you adrian! this solved my issue!
i also have the same problem for the last 3 days and can't solved it, but now it's solved thanks to you

**Comment by emineinnovations** [comment]
> @fikrisuheri verify that this path is complete, if it is cut it is because of the blank spaces, the solution is to move the project from place to a path that does not have spaces.
> ![image](https://user-images.githubusercontent.com/33580067/104142285-8eb3cf00-5380-11eb-9c46-beeb20311b42.png)

**Comment by emineinnovations** [comment]
Thanks a lot ! Amazing it solve my problem.. Cheers !

**Comment by emineinnovations** [comment]
![image](https://user-images.githubusercontent.com/76465168/104171838-48ff1100-5429-11eb-9f41-fb41b1293d57.png)

**Comment by Wulfheart** [comment]
What commands have to be run in order to make it work?
I ran ``npm upgrade`` and also ``npm update`` and then ``npm run dev``.

````
🚀❯ npm run dev

> @ dev D:\code\dnw\hannibal\src


> @ development D:\code\dnw\hannibal\src
> mix

Der Befehl "mix" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `mix`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alex\AppData\Roaming\npm-cache\_logs\2021-01-11T11_18_48_485Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alex\AppData\Roaming\npm-cache\_logs\2021-01-11T11_18_48_511Z-debug.log
````

The content of my ``package.json``:
````json
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
    "devDependencies": {
        "@tailwindcss/forms": "^0.2.1",
        "@tailwindcss/typography": "^0.3.0",
        "alpinejs": "^2.7.3",
        "autoprefixer": "^10.2.1",
        "axios": "^0.21",
        "chokidar": "^3.5.0",
        "chokidar-cli": "^2.1.0",
        "cross-env": "^7.0.3",
        "esbuild": "^0.8.31",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "postcss": "^8.2.4",
        "postcss-custom-properties": "^10.0.0",
        "postcss-import": "^12.0.1",
        "postcss-nested": "^5.0.3",
        "precss": "^4.0.0",
        "tailwindcss": "^2.0.2"
    }
}
````

**Comment by wickex** [comment]
@emineinnovations I'd keep this issue open, as the bug that causes Laravel Mix to fail on Windows when there's a space in the path is not resolved yet.

**Comment by emineinnovations** [comment]
@wickex Sure..

**Comment by armleandrosantos** [comment]
Same issue, new project. Old ones still work.

**Comment by scajal** [comment]
I'm having the same issue since version 6. Older versions work fine.

**Comment by thecrypticace** [comment]
I can't reproduce this issue on Windows 10. Can you all post which versions of Windows and Node you are using?

**Comment by scajal** [comment]
**Node**: 12.19.0
**NPM**: 6.14.8
**Windows**: 10 / 2004

**Comment by thecrypticace** [comment]
I've reproduced the issue but I'm not sure what's wrong yet.

Two things I've discovered:
1. The generated command is quoted correctly (you can check this by running ` .\node_modules\.bin\cross-env TESTING=1 npm run dev`)
2. This does not happen if you install dependencies via yarn. Regardless if you run them via yarn, npm, or npx afterwards.

**Comment by riftwebdev** [comment]
NPM: 6.14.11
Node: 12.18.3
Windows: 10 20H2 19042.685
Laravel: 8.5.7

**Comment by thecrypticace** [comment]
Best I can tell this has nothing to do with Mix. Our CLI script just triggers the error in node/npm and apparently npm run scripts bypass this somehow. I'm trying to see if there's a workaround we can implement.

It appears that the scripts written by yarn in `node_modules/.bin` pass arguments with spaces correctly to node but the scripts written by npm do not.

**Comment by OmarHossamEldin** [comment]
> I already solved it, in my case, it was the blank spaces in the path to the project

really really ty bro u saved me <3 @adrian250997

**Comment by PatrickAbkari** [comment]
To anyone who's still not able to run the "npm run dev" command. Make sure to run the command through the debugger a few times, and it should fix the problem.

**Comment by drsavant-pub** [comment]
Yup this error still exists, however I was able to minimize it by doing the following:

1. npm i webpack (it seems webpack was NOT installed and missing in package.json)  
2. removing '--hide-modules' from "Scripts":"development" in package.json eliminated another error


![20200331-webpack-is-now-compiling](https://user-images.githubusercontent.com/7348198/113207934-77bda400-922e-11eb-8bfd-0c2236304243.png)

After doing those two things I got all the way through 98% compilation and then it fails on this:
```
× Mix
  Compiled with some errors in 26.16s

ERROR in ./resources/js/components/ExampleComponent.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|     <div class="container">
|         <div class="row justify-content-center">

webpack compiled with 1 error
```
I'm running down this last error now.  Hopefully this can be easily resolved.

**Comment by scajal** [comment]
This issue is solved for me.

@drsavant-pub from the code you posted, I see you are using Vue.js. Webpack does not automatically load Vue, so you need to install its loader: https://vue-loader.vuejs.org/

**Comment by drsavant-pub** [comment]
@scajal Thank for your help, but I've decided to let Laravel sort out their own issues.  (If I require Laravel I'll install an earlier version.  One that I know works.) For now I'm using CodeIgniter 4 and it works great!

**Comment by muradbdinfo** [comment]
npm upgrade 
is fix my problem. 
![image](https://user-images.githubusercontent.com/56858449/134808654-26497ab1-4371-4511-852a-69f3c741ba00.png)

you can checkout my youtube channel.
https://www.youtube.com/c/EasyITsolutions

**Comment by akil-b15** [comment]
npm upgrade
works for me :)

**Comment by YuSuFApiwi** [comment]
delete package-lock.json and clear npm cache with npm cache clear --force and delete whole node_modules directory
Finally install or update packages again with npm install / npm update You can also add any new packages with npm install <package-name>

This fixed for me.
Thanks and happy coding.

**Comment by vurch** [comment]
npm upgrade
works for me.
