### ISSUE TITLE
[6.0.8] How to see the generated chunk-names?

### ISSUE THREAD

**Issue by pmochine** [JeffreyWay/laravel-mix#2762]
I'm sorry to open up the issue here, but I tried it on [Stack](https://stackoverflow.com/questions/65612603/laravel-mix-6-how-to-see-chunk-names) and [Laracast](https://laracasts.com/discuss/channels/elixir/laravel-mix-6-show-chunk-names-in-output) and had no luck. 

Is it possible to see the chunk names like in the earlier versions of Laravel Mix?

Currently when using `npm run dev`, I only see this result:

    Laravel Mix v6.0.8   
                            
    
    ✔ Compiled Successfully in 20135ms
    ┌───────────────────────────────────┬───────────┐
    │ File                              │ Size      │
    ├───────────────────────────────────┼───────────┤
    │ /js/vendor.js                     │ 26.6 MiB  │
    ├───────────────────────────────────┼───────────┤
    │ js/routes-sell-food.js            │ 2.15 MiB  │
    ├───────────────────────────────────┼───────────┤
    │ js/resources_js_pages_display-of… │ 2.08 MiB  │
    ├───────────────────────────────────┼───────────┤

I need this because I'm getting warnings from Workbox like these. 

    WARNING in The chunk 'js/app' was provided in your Workbox chunks config, but was not found in the compilation.
    
    WARNING in The chunk 'js/moment' was provided in your Workbox chunks config, but was not found in the compilation.

I asked for help in [Workbox](https://github.com/GoogleChrome/workbox/issues/2717) but I only got a tip that doesn't work in my case.

**Comment by thecrypticace** [comment]
We hid them because they're generally not useful for most workflows.

You can use a custom plugin or callback to achieve what you want:
```js

mix.after(stats => {
  const { assets } = stats.toJson({ assets: true });

  console.log("\n")
  console.table(assets.map(asset => ({
    name: asset.name,
    chunks: asset.chunkNames.join(", "),
  })))
})
```

Note that this table appears *above* the table output by Laravel Mix so you may need to scroll up in your terminal to see it.
