### ISSUE TITLE
mix not found

### ISSUE THREAD

**Issue by Wulfheart** [JeffreyWay/laravel-mix#2765]
-   Laravel Mix Version: 6.0.9 (`npm list --depth=0`)
-   Node Version: `v12.13.0`
-   NPM Version: 6.12.0
-   OS: Windows 10

### Description:
````
🚀❯ npm run dev

> @ dev D:\code\dnw\hannibal\src


> @ development D:\code\dnw\hannibal\src
> mix

Der Befehl "mix" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `mix`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alex\AppData\Roaming\npm-cache\_logs\2021-01-11T11_18_48_485Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alex\AppData\Roaming\npm-cache\_logs\2021-01-11T11_18_48_511Z-debug.log
````

The content of my ``package.json``:
````json
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
    "devDependencies": {
        "@tailwindcss/forms": "^0.2.1",
        "@tailwindcss/typography": "^0.3.0",
        "alpinejs": "^2.7.3",
        "autoprefixer": "^10.2.1",
        "axios": "^0.21",
        "chokidar": "^3.5.0",
        "chokidar-cli": "^2.1.0",
        "cross-env": "^7.0.3",
        "esbuild": "^0.8.31",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "postcss": "^8.2.4",
        "postcss-custom-properties": "^10.0.0",
        "postcss-import": "^12.0.1",
        "postcss-nested": "^5.0.3",
        "precss": "^4.0.0",
        "tailwindcss": "^2.0.2"
    }
}
````

Node_modules are present.

Slightly different to #2761 as there was a problem with webpack. I'm unable to run ``mix`` or ``npx mix``.

### Steps To Reproduce:
Use a fresh laravel project. Or a fresh mix install. Doesn't work either way. 😂

**Comment by apocalyarts** [comment]
Having the same issue; https://github.com/JeffreyWay/laravel-mix/issues/2550

**Comment by LuanHimmlisch** [comment]
Same issue, I reported it at laravel/framework but they close it saying that it was my computer :/

**Comment by Wulfheart** [comment]
As you might see it is at least a problem of three computers and not a path issue like in #2761.

**Comment by thecrypticace** [comment]
Are you installing using `npm install --no-bin-links`?

**Comment by Wulfheart** [comment]
> 
> 
> Are you installing using `npm install --no-bin-links`?

No. Just a plain ``npm install``.

**Comment by Wulfheart** [comment]
It seems to be fixed right now.

**Comment by AliN11** [comment]
@Wulfheart I have this error. How did you fix this?

**Comment by Wulfheart** [comment]
@AliN11 which version of mix do you have installed? `npm list --depth=0` should give you a hint.

**Comment by AliN11** [comment]
> @AliN11 which version of mix do you have installed? `npm list --depth=0` should give you a hint.
6.0.6

But it is fixed! I Moved the project to another path and the problem is gone. I think the problem was related to the project path.

**Comment by Wulfheart** [comment]
With 6.10.0 it should also work under your old path.
