### ISSUE TITLE
Laravel Mix & Vue : Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by devhoussam** [JeffreyWay/laravel-mix#2766]
Hi I want to use **Vue 2** with **laravel mix 6** but it didn't work it display this error message :

`Module parse failed: Unexpected token
`

**webpack.mix.js**

const mix = require('laravel-mix');

```
mix.js('resources/js/app.js', 'js')
   .vue({ version: 2 })
   .setPublicPath('public');
   
if (mix.inProduction()) {
    mix.version();
} 

```

**package.json**

```
"devDependencies": {
 ......
"laravel-mix": "^6.0.6",
"vue": "^2.6.12",
"vue-loader": "^15.9.6",
"vue-template-compiler": "^2.6.12"
 }
```

**resources/js/app.js**

```
require('./bootstrap');

import Vue from 'vue';
import App from './components/App.vue';

new Vue({
    el: '#app',
    components: { App }
});

```

**resources/js/components/App.vue**

```
<template>
    <div class="alert" v-text="message"></div>
</template>

<script>
export default {
    data() {
        return {
            message: 'I am an alert.'
        };
    }
};
</script>

<style>

</style




```

**Comment by truongnmt** [comment]
I have the same error 

> Uncaught Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|     <div>
|         Hello 123123

![image](https://user-images.githubusercontent.com/11817656/104334144-5c979e00-5535-11eb-9a2c-b4dc3c6cd67e.png)

**Comment by mishingo** [comment]
same

**Comment by brachycera** [comment]
I had similar problems upgrading Laravel-Mix.

**package.json**
```json
   "laravel-mix": "^6.0.10",
   "vue-loader": "^15.9.6",
   "vue-template-compiler": "^2.6.12"
```

**webpack.mix.js**
```javascript
mix.js('resources/js/app.js', 'public/js').vue({ version: 2 });
```
**app.js**
```javascript
window.Vue = require('vue').default;
```

For me the information from this answer https://github.com/JeffreyWay/laravel-mix/issues/2747#issuecomment-755483920 fixed my problem 

> ...import Vue as an ES6 module, or to add .default after the require....

Also the upgrade guide had some useful information - https://github.com/JeffreyWay/laravel-mix/blob/master/UPGRADE.md

Hope this might help :bowtie:

**Comment by 5baddi** [comment]
Just add `.vue({ version: 2 })` in webpack.mix.js
`mix.js('resources/js/app.js', 'public/js').vue({ version: 2 });`

**Comment by truongnmt** [comment]
@devhoussam above 2 answers should fix your problem. I think this issue could be closed

**Comment by devhoussam** [comment]
thank you you can closed

**Comment by JintoAntony** [comment]
> I had similar problems upgrading Laravel-Mix.
> 
> **package.json**
> 
> ```json
>    "laravel-mix": "^6.0.10",
>    "vue-loader": "^15.9.6",
>    "vue-template-compiler": "^2.6.12",
>    "vue": "^2.6.12"
> ```
> 
> **webpack.mix.js**
> 
> ```js
> mix.js('resources/js/app.js', 'public/js').vue({ version: 2 });
> ```
> 
> **app.js**
> 
> ```js
> window.Vue = require('vue').default;
> ```
> 
> For me the information from this answer [#2747 (comment)](https://github.com/JeffreyWay/laravel-mix/issues/2747#issuecomment-755483920) fixed my problem
> 
> > ...import Vue as an ES6 module, or to add .default after the require....
> 
> Also the upgrade guide had some useful information - https://github.com/JeffreyWay/laravel-mix/blob/master/UPGRADE.md
> 
> Hope this might help :bowtie:

This works fine

**Comment by 33sKamal** [comment]
Thank you

**Comment by hammadshahir** [comment]
> > I had similar problems upgrading Laravel-Mix.
> > **package.json**
> > ```json
> >    "laravel-mix": "^6.0.10",
> >    "vue-loader": "^15.9.6",
> >    "vue-template-compiler": "^2.6.12",
> >    "vue": "^2.6.12"
> > ```
> > 
> > 
> > **webpack.mix.js**
> > ```js
> > mix.js('resources/js/app.js', 'public/js').vue({ version: 2 });
> > ```
> > 
> > 
> > **app.js**
> > ```js
> > window.Vue = require('vue').default;
> > ```
> > 
> > 
> > For me the information from this answer [#2747 (comment)](https://github.com/JeffreyWay/laravel-mix/issues/2747#issuecomment-755483920) fixed my problem
> > > ...import Vue as an ES6 module, or to add .default after the require....
> > 
> > 
> > Also the upgrade guide had some useful information - https://github.com/JeffreyWay/laravel-mix/blob/master/UPGRADE.md
> > Hope this might help :bowtie:
> 
> This works fine
After these changes, if you still get error, run **npm instal**l again and then **npm run dev**

**Comment by exeptionerror** [comment]
[[Solved] Module parse failed: Unexpected token (763:13) in VueJs
](https://exerror.com/module-parse-failed-unexpected-token-76313-in-vuejs/)

**Comment by nomanabdullah-dev** [comment]
thank you so much. 

> > > I had similar problems upgrading Laravel-Mix.
> > > **package.json**
> > > ```json
> > >    "laravel-mix": "^6.0.10",
> > >    "vue-loader": "^15.9.6",
> > >    "vue-template-compiler": "^2.6.12",
> > >    "vue": "^2.6.12"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **webpack.mix.js**
> > > ```js
> > > mix.js('resources/js/app.js', 'public/js').vue({ version: 2 });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **app.js**
> > > ```js
> > > window.Vue = require('vue').default;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > For me the information from this answer [#2747 (comment)](https://github.com/JeffreyWay/laravel-mix/issues/2747#issuecomment-755483920) fixed my problem
> > > > ...import Vue as an ES6 module, or to add .default after the require....
> > > 
> > > 
> > > Also the upgrade guide had some useful information - https://github.com/JeffreyWay/laravel-mix/blob/master/UPGRADE.md
> > > Hope this might help :bowtie:
> > 
> > 
> > This works fine
> > After these changes, if you still get error, run **npm instal**l again and then **npm run dev**

thank you so much, this works for me after reinstalling npm

**Comment by Befk** [comment]
replace  
 mix.js('resources/js/app.js', 'public/js'); 
 by 

mix.js('resources/js/app.js', 'public/js').vue()

**Comment by jasperf** [comment]
Using `.default `at `window.Vue = require('vue').default;` in `bootstrap.js` only caused

```
Uncaught TypeError: Vue is not a constructor
    at new Vuemit (editor.js?id=e5a58fd9a397c1b0062e:146960)
    at Object../node_modules/vuemit/src/Vuemit.js (editor.js?id=e5a58fd9a397c1b0062e:147063)
    at __webpack_require__ (editor.js?id=e5a58fd9a397c1b0062e:148401)
    at Module../resources/assets/vendor/MediaManager/js/manager.js (editor.js?id=e5a58fd9a397c1b0062e:9628)
    at __webpack_require__ (editor.js?id=e5a58fd9a397c1b0062e:148401)
    at Module../resources/js/editor.js (editor.js?id=e5a58fd9a397c1b0062e:17249)
    at __webpack_require__ (editor.js?id=e5a58fd9a397c1b0062e:148401)
    at editor.js?id=e5a58fd9a397c1b0062e:148727
    at Function.__webpack_require__.O (editor.js?id=e5a58fd9a397c1b0062e:148445)
    at editor.js?id=e5a58fd9a397c1b0062e:148734
```

for us.

Using `.vue({ version: 2 });` instead of `.vue();` did not matter either. I also understood that is not really necesasry reading the [documentation](https://laravel-mix.com/docs/6.0/upgrade#api-for-javascript-frameworks).

_Mix will automatically detect whether you have Vue 2 or 3 installed, based on your dependencies list. However, if you'd rather be explicit..._

Main issue:

```
Uncaught TypeError: Vue.use is not a function
    at Module../resources/js/bootstrap.js (editor.js:13667)
    at __webpack_require__ (editor.js:148401)
    at Module../resources/js/editor.js (editor.js:17143)
    at __webpack_require__ (editor.js:148401)
    at editor.js:148727
    at Function.__webpack_require__.O (editor.js:148445)
    at editor.js:148734
    at editor.js:148736
editor.js?id=afa7c0089b47cc547440:143707
```

as mentioned at https://github.com/laravel-mix/laravel-mix/issues/3145 remains the main party stopper.

**Comment by thecrypticace** [comment]
> Vue.use is not a function

Makes it sound like Vue 3 is installed instead of Vue 2.

**Comment by jasperf** [comment]
Yeah @thecrypticace , I wondered about that as well, but  `npm list vue` shows me Vue 2.6.14 for our application:

```
app.com@ /Users/jasper/code/app.com/app.com
├─┬ @tinymce/tinymce-vue@3.2.8
│ └── vue@2.6.14 deduped
├─┬ vue-async-computed@3.9.0
│ └── vue@2.6.14 deduped
├─┬ vue-awesome@2.3.8
│ └── vue@2.6.14 deduped
├─┬ vue-focuspoint-component@2.0.1
│ └── vue@2.6.14 deduped
├─┬ vue-infinite-loading@2.4.5
│ └── vue@2.6.14 deduped
├─┬ vue-intersect@1.1.6
│ └── vue@2.6.14 deduped
├─┬ vue-recaptcha-v3@1.9.0
│ └── vue@2.6.14 deduped
├─┬ vue-tippy@2.1.3
│ └── vue@2.6.14 deduped
├── vue@2.6.14
└─┬ vuex@3.6.2
  └── vue@2.6.14 deduped
```

And the error details refers to`bootstrap.js` and then these lines. One for loading Vue and making it global in Laravel and one to use Vue Portal:

```
window.Vue = __webpack_require__(/*! vue */ "./node_modules/vue/dist/vue.esm.js"); // Require vue-portal so template elements can be rendered outside of it's component
Vue.use((portal_vue__WEBPACK_IMPORTED_MODULE_0___default()));
```

![Screen Shot 2021-11-01 at 7 26 30 AM](https://user-images.githubusercontent.com/344138/139606613-64ef39d2-a78e-4c03-b096-e55aeabbf854.png)


and the `vue.esm.js` referred to also shows 2.6.14:

```
/*!
 * Vue.js v2.6.14
 * (c) 2014-2021 Evan You
 * Released under the MIT License.
 */
/*  */
```

And `"vue": "^2.6.11", is in our main `package.json`  and in the lock file

```
"node_modules/vue": {
      "version": "2.6.14",
      "resolved": "https://registry.npmjs.org/vue/-/vue-2.6.14.tgz",
     ....
"vue": {
      "version": "2.6.14",
      "resolved": "https://registry.npmjs.org/vue/-/vue-2.6.14.tgz",
     ....
    },
```...

So I have no idea how this is happening yet..

**Comment by jasperf** [comment]
Needed

```js
mix.webpackConfig({
  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.common.js' 

    }
  }
})
```

in `webpack.mix.js` in our case running Vue 2.6.14 using `vue.common.js` which _is the Runtime only CommonJS build (vue.runtime.common.js)._  often used with older bundlers. See [Vue Docs Terms](https://vuejs.org/v2/guide/installation.html#Terms) . 

We are using Webpack 5 now, but it seems we need this setup. Also see https://github.com/vuejs-templates/webpack/issues/215 with mention on runtimes

**Comment by sPITf1re-dev** [comment]
> add .vue() on webpack.mix.js file after mix.js()
> 
> mix.js('resources/js/app.js', 'public/js') .vue() .postCss('resources/css/app.css', 'public/css', [ require('postcss-import'), require('tailwindcss'), ]);
> 
> and Then run
> 
> npm install vue-resource npm i vue-loader npm install vue-template-compiler npm install vue-router
> 
> hope it will work

thanks a lot. those advices about .vue(), .default and the packages didn't help without the commands you described. you saved my day! regards!

**Comment by PhucPhan11** [comment]
you can also update your vue-loader

`npm update vue-loader`

And if it is not installed, install it

`npm i vue-loader`
