### ISSUE TITLE
Stop build if callback passed to .before() throws an error

### ISSUE THREAD

**Issue by smares** [JeffreyWay/laravel-mix#2771]
-   Laravel Mix Version: 6.0.9
-   Node Version (`node -v`): 14.15.4
-   NPM Version (`npm -v`): 6.14.10
-   OS: Alpine 3.11 (Dockerized)

### Description:
`.before()` doesn't seem to stop the build process or at least display any error if the function being called throws an error.

### Steps To Reproduce:
```
const ESLintPlugin = require('eslint-webpack-plugin')
const mix = require('laravel-mix')

async function throwError() {
  throw new Error('oh no')
}

/*
|--------------------------------------------------------------------------
| Mix Asset Management
|--------------------------------------------------------------------------
|
| Mix provides a clean, fluent API for defining some Webpack build steps
| for your Laravel applications. By default, we are compiling the CSS
| file for the application as well as bundling up all the JS files.
|
*/

mix
  .before(throwError)
  .js('resources/js/app.js', 'public/js')
  .sourceMaps(false)
  .extract([])
  .postCss('resources/css/app.css', 'public/css', [
    //
  ])
  .webpackConfig({
    plugins: [new ESLintPlugin()]
  })

if (mix.inProduction()) {
  mix.version()
}
```

**Comment by smares** [comment]
Amazing that this counts as enhancement and not as bug, if the current behavior is by-design, it makes the `before()` feature useless and reminds me of Visual Basic times when beginners used `On Error Resume Next`.

**Comment by thecrypticace** [comment]
Given that this only fails to happen for async callbacks I'd agree this is a bug. This has been fixed and will go out in the next release.
