### ISSUE TITLE
Compiled files are changed after each build (even if there are no changes)

### ISSUE THREAD

**Issue by hivokas** [JeffreyWay/laravel-mix#2773]
-   Laravel Mix Version: 6.0.9 
-   Node Version: v15.2.0
-   NPM Version: 6.14.9
-   OS: macOS

### Description:

In the project I'm working on right now we store compiled assets in the repository. We use GitHub Actions to automatically compile assets once changes are pushed to the PR. The problem is that once assets are compiled, the number of changed files in the PR grows up to ~120. I want to find a way to decrease this number.

### Steps To Reproduce:

I've created a repository to demonstrate this issue: https://github.com/hivokas/laravel-mix-playground-random-postcss-input-id

What I've noticed so far:

- it happens only if the Vue component uses TailwindCSS's `@apply`;
- if we use `@apply`, this part of the chunk (the component is imported dynamically via `import()`) is different after each build (same for chunk's `.map` file):
<img width="600" alt="image" src="https://user-images.githubusercontent.com/22997803/104469489-3f101600-55c1-11eb-988a-1019050be6c6.png">
- looks like this part is `Input#id` generated by PostCSS (https://postcss.org/api/#input-id).

I'm looking for a way to avoid this part being different for each build.

Is there a way to do that from within Laravel Mix? Or I should resubmit this issue to another repo?

**Comment by thecrypticace** [comment]
That's some good (and rather useful) research on the PostCSS input ID details! My guess is that this only happens because source maps are enabled. However, I'm not sure this is something we can fix. I believe this is likely something to be fixed in either vue-loader or tailwind. I'll do some poking around hopefully this weekend.

**Comment by hivokas** [comment]
> I believe this is likely something to be fixed in either vue-loader or tailwind.

I've submitted the issue to the TailwindCSS repository: https://github.com/tailwindlabs/tailwindcss/issues/3349. Let's see.

**Comment by hivokas** [comment]
I've submitted the PR to TailwindCSS that should fix this problem: https://github.com/tailwindlabs/tailwindcss/pull/3356

**Comment by hivokas** [comment]
It has been fixed in https://github.com/tailwindlabs/tailwindcss/pull/3356
