### ISSUE TITLE
Vue 3 extract not working 

### ISSUE THREAD

**Issue by Somethingideally** [JeffreyWay/laravel-mix#2777]
-   Laravel Mix Version: 6.0.10
-   Node Version: v15.0.1
-   NPM Version: 7.0.3
-   OS: Mac OS Catalina 10.15.6
-   Vue Version: 3.0.2

### Description:
Laravel Mix can`t extract vue3 from to vendor file

### Steps To Reproduce:
**resources/js/test.js**

```
import { createApp } from 'vue'
import swiper from 'swiper'

window.createApp = createApp
window.swiper = swiper
```

**webpack.mix.js** (First case)

```
const mix = require('laravel-mix')

mix.js('resources/js/test.js', 'public/static/pub/js/test.min.js')
    .extract(['vue', 'swiper'])
    .vue({version: 3, runtimeOnly: true})
```

In this case  **only swiper** library is extracted to **vendor.js** file

```
/static/pub/js/manifest.js │ 1.05 KiB
/static/pub/js/test.min.js │ 64.2 KiB
/static/pub/js/vendor.js   │ 55.2 KiB 
```
___________________________________
**webpack.mix.js** (Second case)

```
const mix = require('laravel-mix')

mix.js('resources/js/test.js', 'public/static/pub/js/test.min.js')
    .extract(['vue'])
    .vue({version: 3, runtimeOnly: true})
```

In this case **nothing** is extracted to **vendor.js** file

```
/static/pub/js/manifest.js │ 1.05 KiB
/static/pub/js/test.min.js │ 118 KiB
/static/pub/js/vendor.js   │ 139 bytes
```
___________________________________
**webpack.mix.js** (Third case)

```
const mix = require('laravel-mix')

mix.js('resources/js/test.js', 'public/static/pub/js/test.min.js')
    .extract()
    .vue({version: 3, runtimeOnly: true})
```

In this case **swiper and vue** libraries are extracted to **vendor.js** file

```
/static/pub/js/manifest.js │ 1.05 KiB
/static/pub/js/test.min.js │ 178 bytes
/static/pub/js/vendor.js   │ 116 KiB
```
___________________________________
How to extract **only vue** library to **vendor.js** file?

**Comment by adriaanzon** [comment]
It seems to work when I use `.extract(['@vue'])`

**Comment by GiftHealthJonHartley** [comment]
> It seems to work when I use `.extract(['@vue'])`

You are right, that works. Thank you. But why? Why doesn't `.extract(['vue'])` work?

**Comment by adriaanzon** [comment]
It's because under the hood, Vue 3 breaks up their library into several [packages](https://github.com/vuejs/core/tree/main/packages) which are stored under the `@vue` namespace, e.g. `@vue/reactivity`, `@vue/runtime-dom`. By using `.extract(['@vue'])`, you're extracting all the code that is stored under `node_modules/@vue`.

For completeness you could also use `.extract(['vue', '@vue'])`, but I don't think the amount of code stored in `node_modules/vue` is significant.

**Comment by GiftHealthJonHartley** [comment]
Great to know. Thank you!
