### ISSUE TITLE
mix not compiling with node 6.9, errors on compilling with node 7.5

### ISSUE THREAD

**Issue by franckysolo** [JeffreyWay/laravel-mix#278]
Hello
i've an issue with a fresh install i'am using homestead
- Os: Ubuntu 16.04
- Laravel: v5.4.8
- PHP: v7.1
- Node: v7.5.0
- Npm: v4.1.2
- Homestead: Vagrant 1.9.1
### Description: 
I've made an upgrade of Node & npm because with 6.9 node version `npm run dev` stop compiling at 11% of the build, no error message, no log error!
### Steps To Reproduce:
```bash
homestead up
homestead ssh
cd projects
composer create-project --prefer-dist laravel/laravel laravel54
cd laravel54
npm i
```
then just modify the app.scss
and run
```bash
npm run dev
```
then i've got  3 errors
```
Module parse failed: /home/vagrant/projects/laravel54/node_modules/lodash/lodash.js Parenthesized pattern (17076:4)
Module parse failed: /home/vagrant/projects/laravel54/node_modules/jquery/dist/jquery.js Parenthesized pattern (8572:3)
Module parse failed: /home/vagrant/projects/laravel54/node_modules/vue/dist/vue.common.js Parenthesized pattern (1694:6)
```
May be i'm missing something!
Could i use the laravel 5.4 version for production?
thanks Jeffrey for all you works!

franckysolo

**Comment by JeffreyWay** [comment]
This might be related: https://github.com/angular/angular-cli/issues/4378

I'll take a look. Never seen that error before.

**Comment by franckysolo** [comment]
Hello Jeffrey thank for reply
this is very strange!
i completely remove the project and re-install a new one 
then do the same action and now its working
I don't what's happen! may be a problem with npm during installation
