### ISSUE TITLE
Get env variable from parent project

### ISSUE THREAD

**Issue by pkrobak** [JeffreyWay/laravel-mix#2780]
-   Laravel Mix Version: 5.0.9 (`npm list --depth=0`)
-   Node Version (`node -v`): 10.19.0
-   NPM Version (`npm -v`): 6.13.4
-   OS: linux

### Description:

Hello.

I have laravel package. It has own webpack and project witch use this package also has. I want to use .env variable (MIX_ prefixed variable) in package from parent project. Is it possible and is it good approach, or should I reproduce a variable? If I should have two variables is there any good way to create variable from reference? I try to avoid changes in two places

**Comment by JeffreyWay** [comment]
I'm not fully clear on your question, but please use forums or StackOverflow for questions like this. The issues section is specifically for reporting problems and bugs.
