### ISSUE TITLE
Prevent writing to file that only differs in casing or query string from already written file.

### ISSUE THREAD

**Issue by alexis-riot** [JeffreyWay/laravel-mix#2781]
-   Laravel Mix Version: 6.0.10 (`npm list --depth=0`)
-   Node Version (`node -v`): v14.12.0
-   NPM Version (`npm -v`): 6.14.8
-   OS: MacOS BigSur

### Description:

After upgrading the laravel-mix, I have an error during the compilation (using `npm run watch`).
```js
mix.js('resources/src/main.js', 'public/js').vue()
    .webpackConfig({
        resolve: {
            alias: {
                '@': path.resolve(__dirname, 'resources/src'),
            }
        }
    });
mix.sass('resources/src/scss/style.scss', 'public/css');
mix.copy('resources/src/assets/images/logo/', 'public/images/');
```

I'm using an image `bg.png` in the Vue files and in the SCSS file. I think the problem come from here.
What can I do to "skip" or "silent" this error ? Or just solve it ?

### Steps To Reproduce:

`npm run watch`

**Comment by rsevero** [comment]
Can you show the actual error you are getting?

**Comment by JeffreyWay** [comment]
Without the actual error, we can't assist.

**Comment by fubaydullaev** [comment]
Hello Guys!

This is actual error:
[webpack-cli] Error: Prevent writing to file that only differs in casing or query string from already written file.
This will lead to a race-condition and corrupted files on case-insensitive file systems.
D:\www\domains\kitab\public\js\app.js
D:\www\domains\kitab\public\js\app.js
    at checkSimilarFile (D:\www\domains\kitab\node_modules\webpack\lib\Compiler.js:620:22)
    at writeOut (D:\www\domains\kitab\node_modules\webpack\lib\Compiler.js:798:11)
    at D:\www\domains\kitab\node_modules\webpack\lib\util\fs.js:227:5
    at FSReqCallback.oncomplete (fs.js:171:23)

**Comment by thecrypticace** [comment]
This error occurs when you import files with different casing In your compiled JS that cause chunks to get created with different casing. For instance if you have dynamic imports for the same file but use a `webpackChunkName` that differs in the casing this error will be thrown. This is not a Mix issue but an issue with imports in your JS or in your webpack.mix.js file where you provide the same file name but mixed casing for resources.

**Comment by dducro** [comment]
The same error is also thrown if they're multiple images with the same name in separate folders. When compiling vue with mix 6 the images are copied to one directory named images. That seems to cause this issue. Any idea to disable this?
