### ISSUE TITLE
 Cannot find module 'cross-spawn'

### ISSUE THREAD

**Issue by karneaud** [JeffreyWay/laravel-mix#2786]
-   Laravel Mix Version: 6.0.10
-   Node Version (`node -v`):  v12.20.0
-   NPM Version (`npm -v`):  6.14.9
-   OS: Linux homestead 4.15.0-124-generic #127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
-   Yarn Version: 1.22.10
### Description:

package.json

```
{
  "private": true,
  "scripts": {
    "dev": "yarn development",
    "development": "npx mix"
  },
  "dependencies": {
    "bootstrap": "^4.6.0",
    "bootstrap-datepicker": "^1.8.0",
    "jquery": ">= 1.9.1",
    "popper.js": "^1.14.3",
    "slick-carousel": "^1.8.0"
  },
  "devDependencies": {
    "laravel-mix": "*"
  }
}

```

Cannot `yarn mix` produces subject error. 

Call stack trace 

> internal/modules/cjs/loader.js:818
>   throw err;
>   ^
> 
> Error: Cannot find module 'cross-spawn'
> Require stack:
> - /home/vagrant/modules/dohlapse/cross-env/src/index.js
> - /home/vagrant/modules/dohlapse/cross-env/src/bin/cross-env.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
>     at Module.require (internal/modules/cjs/loader.js:887:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/home/vagrant/modules/dohlapse/cross-env/src/index.js:1:17)
>     at Module._compile (internal/modules/cjs/loader.js:999:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>     at Module.require (internal/modules/cjs/loader.js:887:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/vagrant/modules/dohlapse/cross-env/src/index.js',
>     '/home/vagrant/modules/dohlapse/cross-env/src/bin/cross-env.js'
>   ]
> }

### Steps To Reproduce:

yarn install
npx mix

**Comment by JeffreyWay** [comment]
cross-spawn is a dependency of the cross-env package we use. Can you try nuking your node_modules directory and reinstalling from scratch?
