### ISSUE TITLE
SyntaxError: Invalid or unexpected token (function (exports, require, module, __filename, __dirname) { ��c 

### ISSUE THREAD

**Issue by olalekan-agbaje** [JeffreyWay/laravel-mix#2787]
-   Laravel Mix Version: 6.0.10 (`npm list --depth=0`)
-   Node Version (`node -v`): v14.15.4
-   NPM Version (`npm -v`): 6.14.11
-   OS: Windows 10

### Description:
I am new to laravel-mix and trying out the installation at _https://laravel-mix.com/docs/6.0/installation_
All steps were carried out **exactly** as in the installation instruction for the stand-alone project.
running **npm mix** throws a **SyntaxError: Invalid or unexpected token** error

I have been at this for two days (deleting the node_modules folder, reinstalling nodejs) with no success and google hasn't helped much either.

### package.json
```
{
  "name": "laramix",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cross-env": "^7.0.3",
    "laravel-mix": "^6.0.10",
    "postcss": "^8.2.4"
  },
  "scripts": {
    "development": "mix",
    "watch": "mix watch",
    "watch-poll": "mix watch -- --watch-options-poll=1000",
    "hot": "mix watch --hot",
    "production": "mix --production"
  }
}
```

### webpack.mix.js
```
let mix = require('laravel-mix');

mix.js('src/app.js', 'dist').setPublicPath('dist');
```

### src/app.js
`alert('hello world');`

### windows terminal
❯ npx mix
[webpack-cli] C:\scotchbox\laramix\webpack.mix.js:1
(function (exports, require, module, __filename, __dirname) { ��c

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:101:7)
    at NativeCompileCache._moduleCompile (C:\scotchbox\laramix\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
    at Module._compile (C:\scotchbox\laramix\node_modules\v8-compile-cache\v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (C:\scotchbox\laramix\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at module.exports (C:\scotchbox\laramix\node_modules\laravel-mix\setup\webpack.config.js:4:5)
    at C:\scotchbox\laramix\node_modules\webpack-cli\lib\webpack-cli.js:908:43

**Comment by thecrypticace** [comment]
Any chance you could compress your webpack.mix.js file into a zip and post it here? (Not just copy & paste). I have a feeling this has to do with some weird invisible UTF-8 markers at the beginning of the file.

**Comment by olalekan-agbaje** [comment]
@thecrypticace here it is. The webpack.mix.js from my root folder.

[webpack.mix.zip](https://github.com/JeffreyWay/laravel-mix/files/5856131/webpack.mix.zip)

**Comment by thecrypticace** [comment]
Yep, you have a UTF-8 Byte Order Mark at the beginning of the file. In addition it looks like it's encoded as UTF-16 not UTF-8. What editor are you using?

<img width="1199" alt="Screen Shot 2021-01-22 at 08 40 06" src="https://user-images.githubusercontent.com/614993/105497858-6f287a80-5c8d-11eb-9f54-77c7c66b7b56.png">

**Comment by olalekan-agbaje** [comment]
Thanks for you time.
This is very strange. I am using vscode. it might have been because I created the file from the command line.

I will recreate the file and try again.

**Comment by olalekan-agbaje** [comment]
@thecrypticace You are right. Fixing the encoding solved the problem.
Thanks once again.

**Comment by thecrypticace** [comment]
Awesome, glad to hear!

**Comment by kenyywes** [comment]
how can i be a best coder
