### ISSUE TITLE
[docs] Custom scrolling behaviour is horrible for accessibility

### ISSUE THREAD

**Issue by roelofr** [JeffreyWay/laravel-mix#2788]
-   Laravel Mix Version: n/a
-   Node Version (`node -v`): n/a
-   NPM Version (`npm -v`): n/a
-   OS: Chrome on Ubuntu

### Description:

The Laravel Mix documentation on https://laravel-mix.com/ has custom scrolling behaviour. Aside from being a strain on the eyes (something to which I might not be the only one[1][]), when I'm searching for code examples I continuously scroll by the section I'm originally aiming for since the inertia usually jumps about 2/3rds of the way down.

Other sites don't do this, for good reasons, and I don't think a documentation that's super likely to get skimmed looking for the right snippet, should either.

### Steps To Reproduce:

1. Visit the docs on https://laravel-mix.com/
2. Open a lengthy page, like "[The full Mix API][2]"
3. Quickly scroll down to the middle of the screen, using a scroll wheel on a mouse.
4. Watch as the window keeps scrolling after you stop.

[1]: https://css-tricks.com/smooth-scrolling-accessibility/#motion-and-accessibility
[2]: https://laravel-mix.com/docs/6.0/api

**Comment by thecrypticace** [comment]
We do not maintain or control laravel-mix.com. It is however on GitHub. Please open an issue with them: https://github.com/mvdnbrk/laravel-mix.com

**Comment by roelofr** [comment]
Thanks, sorry for polluting the issue list here.

I'll take the issue there :)
