### ISSUE TITLE
Multiple mix-manifest files

### ISSUE THREAD

**Issue by sinnbeck** [JeffreyWay/laravel-mix#2789]
-   Laravel Mix Version: 6.0.10
-   Node Version 14.15.4
-   NPM Version 6.14.11
-   OS: Ubuntu 20.04

### Description:
This is more of a question. I am running into memory consumption issues when both compiling tailwind and js (react) at the same time. I therefor am planning to split it up into seperate build (with different webpack.mix files). My problem is that running each of these, will break my mix-manifest file. Is it possible to specify where to put the new mix-manifest file? I have looked over the code, but it does not seem to be possible (I know I can change the public directory, but I would rather just have the file renamed to something like `mix-manifest-css.json`

**Comment by philbates35** [comment]
Did you try `yarn run dev --mix-config=mix-manifest-css.json`?

**Comment by thecrypticace** [comment]
This is not currently possible though it is something we should look at because it'd be rather simple to implement. However, if the core problem is memory consumption we should figure out what's going on there. I'm not sure if there's much we could do regarding memory use but we can at least look into it.

**Comment by sinnbeck** [comment]
My memory issue is the same as listed here #2711. But I am fairly sure that is something to do with webpack, and not mix. I have found several issues on the webpack issue tracker regarding this already.

For a temporary fix I ended up doing the following.

I set my css build to build, directory into the css folder
```javascript
mix.setPublicPath('public/css')
```
I then changed how mix resolved the css file
```php
{{ mix('app.css', 'css') }}
```
I also created commands for each type to I can run them independently. Those with no prefix, are used for compiling JS which is what I need 99% of the time :)
```json
        "dev": "npm run development",
        "development": "mix",
        "dev:css": "npm run development:css",
        "development:css": "mix --mix-config webpack.mix.css ",
        "watch": "mix watch",
        "watch:css": "mix --mix-config webpack.mix.css watch",
        "prod": "npm run production",
        "prod:css": "npm run production:css",
        "production": "mix --production",
        "production:css": "mix --mix-config webpack.mix.css --production"
```
