### ISSUE TITLE
Laravel Mix v6 not compiling React correctly for IE11, SCRIPT5022: Minified React error #31

### ISSUE THREAD

**Issue by flora8984461** [JeffreyWay/laravel-mix#2792]
-   Laravel Mix Version: 6.0.6
-   Node Version (`node -v`): 12.18.3
-   NPM Version (`npm -v`): 6.14.6
-   React version: 16.13
-   OS: Windows

### Description:
I used to use laravel-mix v5 and using mix.react() which works fine on IE. 

My dependencies are: 

```
  "dependencies": {
    "@babel/preset-env": "^7.12.11",
    "@babel/preset-react": "^7.12.10",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-app-polyfill": "^2.0.0",
    "react-dom": "^16.13.1"
  }
```

My babel settings are:
```
module.exports = {
    presets: ['@babel/preset-env', '@babel/preset-react'],
  };

```

And I have react-app-polyfill imported in App.js (The first level of my react app)

```
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
```

On IE11 it shows blank page with error: `SCRIPT5022: Minified React error #31;`

Any help is appreciated! 🙏

**Comment by flora8984461** [comment]
I am still not sure what was the issue. Is Laravel mix 6 incompatible with react-app-polyfill?

I found another workaround, I dropped react-app-polyfill and used promise-polyfill + unfetch, now seems correctly compiled.

**Comment by JeffreyWay** [comment]
Glad you found a solution. 

I would need a little more setup help to reproduce this and let you know if there's a Mix bug here. Not much to go on at the moment.
