### ISSUE TITLE
Error when trying to compile .scss file/s

### ISSUE THREAD

**Issue by emilas44** [JeffreyWay/laravel-mix#2796]
-   Laravel Mix Version: 6.0.10 (`npm list --depth=0`)
-   Node Version (`12.20.1, 14.15.4, 15.6.0`):
-   NPM Version (`6.13.4, 6.14.10, 7.4`):
-   OS: Ubuntu 20.04

### Description:
Error when compiling sass after `npm run dev`

```
ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: EISDIR: illegal operation on a directory, read
    at processResult (/var/www/projects/eight/node_modules/webpack/lib/NormalModule.js:597:19)
    at /var/www/projects/eight/node_modules/webpack/lib/NormalModule.js:691:5
    at /var/www/projects/eight/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /var/www/projects/eight/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/var/www/projects/eight/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/var/www/projects/eight/node_modules/postcss-loader/dist/index.js:56:7)

1 ERROR in child compilations
webpack compiled with 2 errors
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `mix`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-01-24T14_21_01_020Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-01-24T14_21_01_034Z-debug.log

```

### Steps To Reproduce:
You install the latest Laravel 8 and before running npm install  and npm run dev
just create a new file resources/sass/app.scss and leave it empty
and inside webpack.mix.js replace the code with this:
```
mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css');
```
And try to run `npm install && npm run dev`
First it will give a message that it needs the npm package for sass and it will install it
and then you need to run `npm run dev` once more and then that error happens

**Comment by thinkverse** [comment]
Cannot reproduce this issue myself, installed a new version of Laravel 8, renamed the folder and css file, ran `npm install` and `npm run dev`, and `npm run dev` again after the new deps had been installed, and it compiled successfully.
Do you have any other packages installed that could interfere? What does your `package.json` look like? If you provide that maybe I could see if I can reproduce it.

- Node: v15.6.0
- NPM: 7.4.0
- OS: macOS v10

**Comment by emilas44** [comment]
Here is my repo.... maybe it will be more clear here:
https://github.com/emilas44/eight

I would really like to know what is wrong here. 
I'm using Linux Ubuntu

**Comment by thinkverse** [comment]
Works for me, looking around at the error in question - "EISDIR: illegal operation on a directory, read", it seems like mix cannot access the `sass` directory, some write about issues related to `.npmrc` or .`yarnrc` files, but I personally have never experienced this issue so I won't comment it.

Could there be a permissions issue maybe? 🤔

**Comment by emilas44** [comment]
Incredible... maybe there is something really silly going on and I can't see it...
I don't know what to do anymore... 
Here is how it looks like on my laptop.... maybe you can see something what I can't ?
![Peek 2021-01-25 14-58](https://user-images.githubusercontent.com/15637006/105715432-e5431080-5f1d-11eb-89f1-a16ec34d2fb2.gif)

**Comment by emilas44** [comment]
I thought it can't get any weirder...
I tried now everything on a different virtual machine and all works fine... It's just mind-boggling
Why why why???

**Comment by emilas44** [comment]
So to conclude.... this was some weird case and it has something to do with "linux stuff" file system or something... I don't know
I hope it won't happen ever again.
