### ISSUE TITLE
Cache folder is not automatically created

### ISSUE THREAD

**Issue by assertchris** [JeffreyWay/laravel-mix#28]
Not a huge deal, but public/output paths are automatically created. If the cache folder is missing but `setCachePath` is used, a built terminates in the following error: `Error: ENOENT: no such file or directory, open 'cache/Mix.json'`

**Comment by JeffreyWay** [comment]
Thanks. We're no longer using setCachePath. It'll just get popped into your public directory, and that should always exist.
