### ISSUE TITLE
Support for Snowpack?

### ISSUE THREAD

**Issue by ben221199** [JeffreyWay/laravel-mix#2801]
-   Laravel Mix Version: N/A
-   Node Version (`node -v`): N/A
-   NPM Version (`npm -v`): N/A
-   OS: N/A

### Description:

Will this library also get support for Snowpack?

### Steps To Reproduce:
N/A

**Comment by thecrypticace** [comment]
Laravel Mix is intended as a wrapper around webpack. There are no plans to change that. If you want to use snowpack I'd suggest using it directly.

**Comment by ben221199** [comment]
Laravel Mix generates a `mix-manifest.json` that can be used by Laravel's `mix()` function. With Webpack this works fine, but because this library isn't compatible Snowpack, I cannot use it. Is there any possibility to generate a `mix-manifest.json` for Laravel when using Snowpack?

**Comment by thecrypticace** [comment]
I don't know enough about Snowpack to be able to answer this question but I'd imagine you'd have to build a plugin for it to do so: https://www.snowpack.dev/guides/plugins

**Comment by ben221199** [comment]
I think so, some `Laravel Snowmix` or something :)
