### ISSUE TITLE
mix-manifest version() hash value?

### ISSUE THREAD

**Issue by cmarcelly** [JeffreyWay/laravel-mix#2803]
-   Laravel Mix Version: 6.0.10
-   Node Version: 14.15.3
-   NPM Version: 6.14.9
-   OS: MacOS Catalina 10.15.6

Hi!

Not an issue but just a question.

Is there a way to get the hash values generated by the version() function?

I would like to push them to Nunjucks templates during compilation.

Thanks!

**Comment by JeffreyWay** [comment]
It's not stored in memory, but we write the hash to the mix-manifest.json file. So you could read that file and extract it from the querystring.
