### ISSUE TITLE
Feature request: mix watch --production

### ISSUE THREAD

**Issue by tomaszbujnowicz** [JeffreyWay/laravel-mix#2804]
-   Laravel Mix Version: 6.0.10
-   Node Version (`node -v`): 12.18.3
-   NPM Version (`npm -v`): 6.14.9
-   OS: MacOS Catalina

### Description:
Shouldn't we have a `mix watch --production` command available?
That would sound naturally since we have a `mix --production` already there.
Unless there is another easy way of making it work. I couldn't find anything about that in the docs and in issues.

### Steps To Reproduce:
- add script `"watch:prod": "mix watch --production"` to the package.json 
- run command in the terminal
- message: `error: unknown option '--production'`

**Comment by thecrypticace** [comment]
This is intentional for two reasons:
1. `watch` is intended for use during development — not production
2. Production builds take longer due to additional optimizations and minification

If you absolutely **must** you can set your `NODE_ENV` manually when running mix: `NODE_ENV=production mix watch`

**Comment by thisisjamessmith** [comment]
Having separate build/dev processes is not always necessary on small/simple projects, and just adds extra complexity on those that do not require it. Having a single build process triggered by `watch` that also builds for production has the following advantages:

1. You're testing the minified code locally, which could avoid some surprises with the untested minified code in the production build.
2. Your build process is greatly simplified - no need to remember to run the production build process after every small change, or if that's something you typically automate, then there's no need to set up that extra layer of automation to run the production build when you push.
