### ISSUE TITLE
using MiniCssExtractPlugin with filename option generates two files.

### ISSUE THREAD

**Issue by Nothing-Works** [JeffreyWay/laravel-mix#2807]
-   Laravel Mix Version: $ npm list --depth=0
andy@1.0.0 C:\Users\Andy\Desktop\andy
├── laravel-mix@6.0.11
└── mini-css-extract-plugin@1.3.4
-   Node Version (`15.7.0`):
-   NPM Version (`7.4.3`):
-   OS: Windows 10

### Description:
I am trying to extract `css` from `js` using MiniCssExtractPlugin.
```js
let mix = require('laravel-mix');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

mix.webpackConfig({
    plugins: [new MiniCssExtractPlugin({filename:'/css/example.css'})],
    module: {
        rules: [
          {
            test: /\.css$/i,
            use: [MiniCssExtractPlugin.loader, 'css-loader'],
          },
        ],
      },
});

mix.js('src/app.js', 'dist').setPublicPath('dist');
```

This is the output:

![Untitled](https://user-images.githubusercontent.com/18606648/105920967-2150af80-609d-11eb-8dbf-3178f36019b2.png)

So it not only generates `/css/example.css` but also generates `app.css` within `dist` with the same content.
![Untitled](https://user-images.githubusercontent.com/18606648/105921200-6f65b300-609d-11eb-91cf-33f3a67352d5.png)

Am I doing something wrong there?

I just tried setting up with webpack manually with `MiniCssExtractPlugin` and it worked as expected which only creates one file when I specify the filename option.

**Comment by JeffreyWay** [comment]
Why aren't you just doing `mix.css('css/example.css', 'dist'))`?

**Comment by JeffreyWay** [comment]
Why aren't you just doing `mix.css('css/example.css', 'dist'))`?

**Comment by hasan-wajahat** [comment]
@Nothing-Works That is because this will add 2 MiniCssExtractPlugins to your webpack config. Laravel mix adds MiniCssExtractPlugin by default and when you just added yours it just created a duplicate. That is why you see 2 files instead of one.
