### ISSUE TITLE
Add support for Material Web Components (MWC)

### ISSUE THREAD

**Issue by maicol07** [JeffreyWay/laravel-mix#2808]
-   Laravel Mix Version: 6.0.10
-   Node Version (`node -v`): 15.4.0
-   NPM Version (`npm -v`): 7.0.15
-   OS: Windows 10

### Description:
Add support for [material web components (MWC)](https://github.com/material-components/material-components-web-components) (Open Web Components)
### Steps To Reproduce:
1. Try to add a MWC like the mwc-button
2. Button doesn't show up

**Comment by thecrypticace** [comment]
Can you provide more details on what you're doing? This isn't something we need to add special support for.

**Comment by maicol07** [comment]
I want to use MWC, but when I try to use one of it (like the mwc-button) it doesn't appear

**Comment by thecrypticace** [comment]
Understood but I require more details to know if there's a Mix problem here. MWC requires you to install appropriate dependencies and then import them in your JS before you can use them.

**Comment by maicol07** [comment]
Ok, I've run a test and it seems now works. Will reopen if I found an issue.

Thank you for the great Laravel Mix!
