### ISSUE TITLE
Can i compile stylus?

### ISSUE THREAD

**Issue by ElioMS** [JeffreyWay/laravel-mix#281]
Hello,
It is possible to compile stylus i was trying 

`mix.stylus('mystyluspath', 'publicpath')`

but it's not working with laravel 5.4

**Comment by ludo237** [comment]
laravel Mix does not provide stylus support out of the box

**Comment by nejtr0n** [comment]
There is fork 
https://github.com/rogervila/laravel-mix-stylus
You could use it. But it would be better to include stylus from scratch I think.
