### ISSUE TITLE
Output '.gz' files & filesize in console when using compression webpack plugin

### ISSUE THREAD

**Issue by lexxyungcarter** [JeffreyWay/laravel-mix#2813]
-   Laravel Mix Version: 6.0.6 (`npm list --depth=0`)
-   Node Version (`node -v`): 14.5.0
-   NPM Version (`npm -v`): 6.14.11
-   OS: MacOS Big SUR

### Description:
The new stats table is awesome. However, with the latest version of laravel mix, when using `compression-webpack-plugin`, the compressed files are not present in the stats table. It would be a nice idea if it would be included like previous versions.

### Steps To Reproduce:
- install new laravel version
- install compression-webpack-plugin as dev dependency.
- configure `webpack.config.js`
```js
module.exports = {
    plugins: [
        new CompressionPlugin(),
    ],
}
```
- run `npm run watch/dev/prod`

**Comment by thecrypticace** [comment]
I'll have to take a look and see why. It may be that we need to pull related asset information from the asset list but I'm not sure yet. I'll see what I can do hopefully this weekend.
