### ISSUE TITLE
Compiling sass and then combining the results don't work

### ISSUE THREAD

**Issue by ezra-obiwale** [JeffreyWay/laravel-mix#2814]
-   Laravel Mix Version: 6.0.11
-   Node Version (`node -v`): 12.20.0
-   NPM Version (`npm -v`): 6.14.8
-   OS: Debian 10 (buster)

### Description:

Compiling sass and then combining the results don't work.

### Steps To Reproduce:

1. mix.sass('path/to/file/1.scss', 'new/path')
2. mix.sass('path/to/file/2.scss', 'new/path')
3. mix.combine('new/path/*.css', 'new/path.css')

**Comment by jeremy-smith-maco** [comment]
+1

Upgraded to latest Laravel Mix and it has broken my compilation silently but it used to work fine prior. No errors or anything. Took me a long time to figure out such a simple mistake.

**Comment by maiconmva** [comment]
+1 

upgraded to latest version and broken my script!! 

i cant compile and after that combine
