### ISSUE TITLE
Babel plugins are NOT being used on node_module imports

### ISSUE THREAD

**Issue by pryley** [JeffreyWay/laravel-mix#2815]
-   Laravel Mix Version: 6.0.10
-   Node Version: 15.3.0
-   NPM Version: 7.0.14
-   OS: macOS 11.1

### Description:

Laravel Mix is not applying babel plugins to imported modules.

### Steps To Reproduce:

`npm i --save-dev @babel/plugin-proposal-optional-chaining`

#### webpack.mix.js file

```js
const mix = require('laravel-mix');
mix
  .babelConfig({
    "plugins": [
      "@babel/plugin-proposal-optional-chaining",
    ],
  }}
  .js('scripts/app.js', 'assets/scripts')
```

app.js file
```js
import StarRating from 'star-rating.js';

// Test 1: Inline optional-chaining
window.obj1 = {};
window.val1 = obj1?.[0];

// Test 2: This module uses optional-chaining
new StarRating('select');
```

#### Result:

✅ Test 1 Result: Inline optional-chaining
```js
window.obj1={},window.val1=null===(p=obj1)||void 0===p?void 0:p[0]
```

❌ Test 2 Result: This module uses optional-chaining
```js
const s=t.touches?.[0]||t.changedTouches?.[0]||t
```

**Comment by thecrypticace** [comment]
Mix intentionally doesn't transpile code from node_modules: https://github.com/JeffreyWay/laravel-mix/blob/817653efdac048fd10242432dc4e2b9ff793299c/src/components/JavaScript.js#L62

If you need to do this I recommend modifying the webpack rules for your setup using `mix.override`. Something like the following should work (have not tested it though — so it may require some tweaks).
```js
mix.override((config) => {
        config.module.rules.forEach(rule => {
            if (rule.use.some(item => item.loader === "babel-loader")) {
                delete rule.exclude;
            }
        });
    });
``

**Comment by hivokas** [comment]
@thecrypticace thanks a lot for your code snippet! 

I've been using this code snippet for a while, but recently I've noticed that it stopped working (maybe it didn't work initially and I just never realized it).

The thing is that `item.loader` never contains `babel-loader` string, it contains absolute path to loader, so I needed to slightly modify this code to make it work.

Here is my modified version that as of today:

```js
.override((config) => {
  let hasModifiedBabelLoaderRole = false;

  config.module.rules.forEach((rule) => {
    if (
      rule.use?.some((item) =>
        item.loader.startsWith(
          path.resolve(path.join("node_modules", "babel-loader"))
        )
      )
    ) {
      rule.exclude = /node_modules\/((@popperjs|tippy\.js)\/).*/;

      hasModifiedBabelLoaderRole = true;
    }
  });

  if (!hasModifiedBabelLoaderRole) {
    throw new Error("Failed to modify `babel-loader` rule.");
  }
})
```

It uses `path`, so I also included this import at the top of the file:

```js
const path = require("path");
```

Also I've added an extra `hasModifiedBabelLoaderRole` check to be immediately notified during the build if it fails to modify babel loader rule.

I hope my comment helps somebody :)
