### ISSUE TITLE
Setting globalStyles for vue to true causes TypeError: The "path" argument must be of type string.

### ISSUE THREAD

**Issue by JonathanDoelan** [JeffreyWay/laravel-mix#2822]
-   Laravel Mix Version: 6.0.11
-   Node Version: v14.15.4
-   NPM Version: 6.14.10
-   OS: macOs 10.15.7

### Description:

After turning on globalStyles …
```
.vue({
	version: 3,
	extractStyles: true,
    	globalStyles: true,
})
```
… I’ll get the error:
`[webpack-cli] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (true)`

If I set `globalStyles: false` everything works.

**Comment by thecrypticace** [comment]
`glboalStyles` is an array or object of arrays listing the files you want included globally — and false or null to disable them. `true` is not a valid value for globalStyles. It appears that our types are incorrect. I'll put this on my todo list fo fix soon.

Example usage:

```js
mix.vue({
    version: 3,
    extractStyles: true,
    globalStyles: {
        // Any one of these works
        // You can provide multiple if you're using multiple preprocessors
        css: [`example.css`],
        sass: [`example.sass`],
        scss: [`example.scss`],
        less: [`example.less`],
        stylus: [`example.styl`],
    }
})
```
