### ISSUE TITLE
Non adaptive documentation

### ISSUE THREAD

**Issue by ParadiseFallen** [JeffreyWay/laravel-mix#2824]
![Screenshot_2021-02-02-19-36-38-818_com yandex browser](https://user-images.githubusercontent.com/50731756/106639849-1363c880-658e-11eb-86e0-38224a862803.jpg)
Footer non adaptive. Just add flex wrap

**Comment by thecrypticace** [comment]
We do not maintain or control laravel-mix.com. It is however on GitHub. Please open an issue with them: https://github.com/mvdnbrk/laravel-mix.com
