### ISSUE TITLE
TypeError: compiler.plugin is not a function

### ISSUE THREAD

**Issue by SupianIDz** [JeffreyWay/laravel-mix#2826]
-   Laravel Mix Version: laravel-mix@6.0.11
-   Node Version (`node -v`): v15.8.0
-   NPM Version (`npm -v`): 7.5.2
-   OS: Zorin OS 15.3

![xxxx](https://user-images.githubusercontent.com/37969970/106765619-f43f6680-6673-11eb-99eb-a89a69ec4857.png)

### Description:
LiveReload has problems, even on a fresh install.

![zzz](https://user-images.githubusercontent.com/37969970/106766027-6a43cd80-6674-11eb-8c94-1b89b469cd37.png)

### Steps To Reproduce:
```
composer create-project laravel/laravel
cd laravel
composer install

npm install
npm install webpack-livereload-plugin@1 --save-dev
```

Add the following lines to the bottom of your webpack.mix.js:

```
var LiveReloadPlugin = require('webpack-livereload-plugin');

mix.webpackConfig({
    plugins: [new LiveReloadPlugin()]
});
```
Run watch
```
npm run watch
```

**Comment by thecrypticace** [comment]
The live reload plugin you are using does not support webpack 5. Please update the plugin you are using.

**Comment by bagoesz21** [comment]
This plugin : 
[https://www.npmjs.com/package/webpack-livereload-plugin](https://www.npmjs.com/package/webpack-livereload-plugin)
doesn't support webpack 5. use the package below :
[https://www.npmjs.com/package/@kooneko/livereload-webpack-plugin](https://www.npmjs.com/package/@kooneko/livereload-webpack-plugin)

**Comment by SupianIDz** [comment]
> This plugin :
> https://www.npmjs.com/package/webpack-livereload-plugin
> doesn't support webpack 5. use the package below :
> https://www.npmjs.com/package/@kooneko/livereload-webpack-plugin

Hi, thanks mate.

**Comment by asheroto** [comment]
https://github.com/mvdnbrk/laravel-mix-docs/issues/84
