### ISSUE TITLE
There is no webpack.mix.js in my node_modules

### ISSUE THREAD

**Issue by COBNETCKNN** [JeffreyWay/laravel-mix#2827]
- Laravel Mix Version: ^6.0.11
- Node Version: v15.8.0
- NPM Version: 7.5.1
- OS: Windows 10

### **Description:**
After installing laravel mix via terminal and running the command `cp node_modules/laravel-mix/setup/webpack.mix.js ./` I'm getting this error.

```
cp : Cannot find path 'C:\Users\COBNETCKNN\Local Sites\portofolio\app\p
ublic\wp-content\themes\wp-portofolio\node_modules\laravel-mix\setup\we 
At line:1 char:1
+ cp node_modules/laravel-mix/setup/webpack.mix.js ./
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\COBNET...\webp  
   ack.mix.js:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Comman  
   ds.CopyItemCommand
```
I also looked inside `node_modules/laravel-mix/setup/` and there was no `webpack.mix.js` so I couldn't pull it from there, did the directory changed or what happened? Can I copy `webpack.mix.js` from my previous projects and modify it for my needs?

**Comment by COBNETCKNN** [comment]
Managed to solve it by lowering version of the Laravel Mix, it looks like in latest version you just don't get `webpack.mix.js` in your `node_modules` after installing laravel mix, something that should be tackled by the team... So solution for this is that inside your `package.json` file copy these dependencies below

```
"devDependencies": {
    "autoprefixer": "^9.8.6",
    "browser-sync": "^2.26.13",
    "browser-sync-webpack-plugin": "^2.0.1",
    "cross-env": "^7.0.3",
    "laravel-mix": "^5.0.9",
    "postcss": "^7.0.35",
    "sass": "^1.30.0",
    "sass-loader": "^8.0.2",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.1",
    "vue-template-compiler": "^2.6.12"
  },
  "dependencies": {
    "@fortawesome/fontawesome-free": "^5.15.1"
  }
```
This is from my old project `package.json` file, after setting this up you just install laravel mix again via `npm install laravel-mix --save-dev` and then run `cp node_modules/laravel-mix/setup/webpack.mix.js ./ `which will pull `webpack.mix.js` from your `node_modules`

**Comment by thecrypticace** [comment]
> Managed to solve it by lowering version of the Laravel Mix,

Please don't — new features are going into v6. 😄 

> Can I copy webpack.mix.js from my previous projects and modify it for my needs?

Yes, you absolutely can. The Mix config is intended to be rather simple. There were only minor changes made to v6 which are all covered in the upgrade guide.

> I also looked inside node_modules/laravel-mix/setup/ and there was no webpack.mix.js

The installation guide gives you an example webpack.mix.js file (https://github.com/JeffreyWay/laravel-mix/blob/2ac5735f44b2c2716617345e57a0df578f479dee/docs/installation.md).

Additionally, if you're using Laravel this is already provided for you. You can pull it from there too if you wish (https://github.com/laravel/laravel/blob/c1b56831dfb96cfc1e87d40f44f7b2cca07c351c/webpack.mix.js):

```js
// webpack.mix.js

const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js')
mix.postCss('resources/css/app.css', 'public/css', [
    //
]);
```
