### ISSUE TITLE
npm run dev not working

### ISSUE THREAD

**Issue by LuigisDev** [JeffreyWay/laravel-mix#2830]
-   Laravel Mix Version: 5.0.1 (`npm list --depth=0`)
-   Node Version (`node -v`): v10.16.0
-   NPM Version (`npm -v`): 6.9.0
-   OS: Windows 10

### Description:
npm run dev not working, when running the command it does not show anything

### Steps To Reproduce:

![imagen](https://user-images.githubusercontent.com/23205677/106855883-46d44f00-6683-11eb-9407-7e52a882f28c.png)

**Comment by JeffreyWay** [comment]
Without more information, this could be due to anything. First, I'd recommend upgrading to Mix 6, and bumping your Node and NPM versions.
