### ISSUE TITLE
mix production - doesn't kill the process when it's done

### ISSUE THREAD

**Issue by furcic** [JeffreyWay/laravel-mix#2833]
-   Laravel Mix Version: 6.0.11 (`npm list --depth=0`)
-   Node Version (`node -v`): 12.20
-   NPM Version (`npm -v`): 6.14
-   OS: MacOS

### Description:
When I run "mix -p" - it compiles the code just fine, everything works, but the process is not kill at the end, I need to kill it manually. Before upgrading to 6, I had no problems.

**Comment by Daronspence** [comment]
I found something that may be related here. I was seeing the same issue, but clicking on the notification finishes the process and it exits correctly. I'm going to dig in and see if I can tell what's up.

**Comment by Daronspence** [comment]
@furcic I read through the docs and gave these steps a try and it seems to be exiting correctly now. I did remove some packages right before so it could have been cache related.

```sh
rm -rf node_modules
rm package-lock.json yarn.lock
npm cache clear --force
npm install 
```
