### ISSUE TITLE
Issue while compiling .glsl files..

### ISSUE THREAD

**Issue by vgavrilovikj** [JeffreyWay/laravel-mix#2838]
I have GLSL shaders, not sure how to setup the webpack mix to compile the .glsl files..

This is the issue that I get on npm run watch:
![image](https://user-images.githubusercontent.com/29601489/107654802-48090b80-6c83-11eb-822a-51ba1700b359.png)

And this is how my webpack.mix.js looks like:
`

        const mix = require('laravel-mix');

      /*
       |--------------------------------------------------------------------------
       | Mix Asset Management
       |--------------------------------------------------------------------------
       |
       | Mix provides a clean, fluent API for defining some Webpack build steps
       | for your Laravel application. By default, we are compiling the Sass
       | file for the application as well as bundling up all the JS files.
       |
       */
      
      mix.react('resources/js/app.js', 'public/js')
          .sass('resources/sass/bootstrap.scss', 'public/css')
              .less('resources/less/app.less', 'public/css'); 
               
      mix.webpackConfig({
          module: {
            rules: [
                  {
                  test: /\.(glsl|frag|vert)$/,
                  loader: 'raw-loader',
                  exclude: /node_modules/
                  },
          
                  {
                  test: /\.(glsl|frag|vert)$/,
                  loader: 'glslify-loader',
                  exclude: /node_modules/
                  }
              ]
          } 
         });
`

**Comment by thecrypticace** [comment]
Try this:

```js
mix.webpackConfig({
  module: {
    rules: [
      {
        test: /\.(glsl|frag|vert)$/,
        exclude: /node_modules/,
        use: [
          'raw-loader',
          'glslify-loader',
        ],
      },
    ],
  },
})
```

**Comment by vgavrilovikj** [comment]
Still same issue:
![image](https://user-images.githubusercontent.com/29601489/107656652-abe00400-6c84-11eb-9d6b-5bc1a1bfb59f.png)

**Comment by vgavrilovikj** [comment]
@thecrypticace it still has some issues loading them properly... not sure why :/

**Comment by iwasherefirst2** [comment]
> Try this:
> 
> ```js
> mix.webpackConfig({
>   module: {
>     rules: [
>       {
>         test: /\.(glsl|frag|vert)$/,
>         exclude: /node_modules/,
>         use: [
>           'raw-loader',
>           'glslify-loader',
>         ],
>       },
>     ],
>   },
> })
> ```

Thank you! That worked for me :)!
