### ISSUE TITLE
Copy files and don’t flatten the directory structure

### ISSUE THREAD

**Issue by xyNNN** [JeffreyWay/laravel-mix#2839]
When I copy files, in my case images, the directory structure is flatten. Is there any possibility to prevent this?

I want to keep the structure, because also I have some duplicate names of images and then the build stops - which makes sense.

Thanks!

**Comment by xyNNN** [comment]
`mix.copyDirectory('resources/images', 'public/images');` ist the answer

**Comment by damsfx** [comment]
Can't get some file types to be excluded!
