### ISSUE TITLE
Allow to version files that aren't part of the main bundle

### ISSUE THREAD

**Issue by iraklisg** [JeffreyWay/laravel-mix#284]
**Combining** (concatenating) and **copying** files (using `mix.combine` and `mix.copy`  functions respectively)  are stand-alone, separate processes from Webpack compilation. As a result, **versioning** (using `mix.version`)  **could not be applied** to the resulted files.

Especially for **[Laravel](https://laravel.com/)** users, the resulted files are not included in `mix-manifest` and thus cannot be referenced via Laravel's `mix()` handy helper function.

IMHO It would be very helpful if `laravel-mix` would provide the ability to **version combined and copied files, that are not part of the main bundle**, a functionality that was allowed by the laravel-mix's predecessor [laravel-elixir](https://github.com/laravel/elixir)

**Comment by QWp6t** [comment]
But.... why wouldn't you just, idk, follow the progress in one of the other 5 issues that were created for this?

**Comment by iraklisg** [comment]
@QWp6t, thank you for pointing this out,  I suppose you are referring to issue #270 which I falsely didn't previously notice. Please feel free to mark this post as a duplicate of the latter, so that all these issues that referencing basically the same thing to be linked together. In any case, this feature request (allow to version files that aren't part of the main bundle) seems to concerns a lot of users, that want to perform some  additional simple tasks like concatenating and then versioning  some scripts. Just a thought but maybe a help-wanted tag on one of these issues would drew some more attention on the subject

**Comment by JeffreyWay** [comment]
I added a commit that appends mix.combine() files to mix-manifest.json file, but it still won't perform versioning yet.

Closing this, since it's a duplicate.
