### ISSUE TITLE
Error while compiling assets  Unknown option: .esModule.

### ISSUE THREAD

**Issue by arturpuck** [JeffreyWay/laravel-mix#2848]
-Laravel Mix --> 6.0.11
-Node --> 15.8.0
-npm --> 7.5.1
-O.S : Linux Ubuntu 18.04

Recently I updated Laravel-Mix to latest version. This project uses Vue.js When I try to execute npm run development I get the following error : 

> ERROR in ./resources/js/components/navigation/navbar.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib/index.js??ruleSet[0].rules[0].use[0]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./resources/js/components/navigation/navbar.vue?vue&type=script&lang=js&)
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Unknown option: .esModule.

This is my laravel.mix.js file 

```
const mix = require('laravel-mix');
require('laravel-mix-svg-vue');
var path = require('path');

mix.js('resources/js/mainpage.js', 'public/js').vue()
    .sass('resources/sass/mainpage.scss', 'public/css')
    .svgVue()
    .options({autoprefixer : true, 
      processCssUrls: false, 
      postCss: [ require('autoprefixer')]})
    .babelConfig({
      plugins: ['@babel/plugin-syntax-dynamic-import'],
      presets: ["@babel/preset-env", "vue"]
    })
    .webpackConfig({
        resolve: {
            alias: {
                '@js' : path.resolve('resources/js'),
                '@jscomponents' : path.resolve('resources/js/components'),
                '@jsmodules' : path.resolve('resources/js/modules'),
                'sass' : path.resolve('resources/sass'),
                'sasscomponent' : path.resolve('resources/sass/components'),
                '@jscomponents-decoration' : path.resolve("resources/js/components/decoration"),
                '@jscomponents-form-controls' : path.resolve('resources/js/components/form_controls'),
                '@interfaces' : path.resolve('resources/js/interfaces'),
                '@svgicon' : path.resolve('resources/images/decoration/icons/svg')
            },
            extensions: ["*", ".js", ".jsx", ".vue", ".ts", ".tsx", ".svg"]
        },

        module: {
            rules: [
              {
                test: /\.tsx?$/,
                loader: "ts-loader",
                options: { appendTsSuffixTo: [/\.vue$/] },
                exclude: /node_modules/
              },

              {
                test: /\.svg$/,
                use: [
                  'babel-loader',
                  'vue-svg-loader',
              },
            ]
          }
    })            },
            ]
          }
    })

```
Package.json file 

> {
    "private": true,
    "scripts": {
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "production": "mix --production"
    },
    "devDependencies": {
        "@babel/core": "^7.9.0",
        "@babel/preset-env": "^7.9.0",
        "axios": "^0.19",
        "babel-loader": "^8.0.0",
        "bootstrap": "^4.6.0",
        "cross-env": "^5.2.1",
        "jquery": "^3.2",
        "laravel-mix": "^6.0.11",
        "lodash": "^4.17.20",
        "node-sass": "^4.14.1",
        "popper.js": "^1.12",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.32.7",
        "sass-loader": "^7.3.1",
        "ts-loader": "^8.0.17",
        "vue": "^2.6.12",
        "vue-svg-loader": "^0.16.0",
        "vue-template-compiler": "^2.6.12",
        "webpack": "^5.22.0",
        "webpack-cli": "^4.5.0"
    },
    "dependencies": {
        "babel-preset-vue": "^2.0.2",
        "dart-sass": "^1.25.0",
        "image-to-blob": "^0.2.0",
        "laravel-mix-compress-images": "^1.0.4",
        "laravel-mix-imgmin": "^0.1.1",
        "laravel-mix-svg-vue": "^0.3.0",
        "postcss": "^8.2.6",
        "typescript": "^4.1.5",
        "vue-class-component": "^7.2.6",
        "vue-clickaway": "^2.2.2",
        "vue-multiselect": "^2.1.6",
        "vue-property-decorator": "^9.1.2",
        "vue-slider-component": "^3.2.11"
    }
}

I have no idea what to do, I have updated all these babel dependencies many times, I did like someone explained here
https://github.com/babel/babel/issues/11365

I does not work anyway. Surprisingly webpack compiles successfully when I set it to compile only sass or only js files. When I want to copile both types of files I get the error mentioned above. I'm out of ideas I have already spent like 10 hours to solve it. Anyone has any idea?

**Comment by wilmanbarrios** [comment]
I'm having the same issue
