### ISSUE TITLE
[Enhancement] Improved Mix Watch Status Indication 

### ISSUE THREAD

**Issue by clandestine8** [JeffreyWay/laravel-mix#2849]
**Feature Request for Future Releases**

When working with large projects, it can take some time for webpack to do its job. When Mix is running in `watch` or `watch-poll` mode, there is little indication that it has found a reason to recompile the assets, and that it is working on it in the background. 

If Mix could output a line on detection of changes, prior to beginning to compile the assets, stating that it has begun the process then it would be much clearer to the developer what mix is doing. 

I currently work inside a dockized environment on windows and Mix runs within the docker container, so thing such as desktop notifications would not be considered a solution for me, since it would not interface with the operating system under these conditions. 

It would also be great if we could add a timestamp to the `webpack compiled successfully` line as to indicate the last complete compilation

**Comment by clandestine8** [comment]
Adding this plugin helps https://github.com/nuxt-contrib/webpackbar 

It shows the progress of the compilation, which in turn does inform me when it is compiling assets.  


Example Config (webpack.mix.js) for anyone that is interested
```
const mix = require('laravel-mix');
const WebpackBar = require('webpackbar');

mix.webpackConfig({ 
   plugins: [
       new WebpackBar()
   ]
});
```

**Comment by JeffreyWay** [comment]
I agree. Will add this to the upcoming release.

**Comment by thecrypticace** [comment]
Yeah, I've looked at WebpackBar before. I really like the way it works and looks. It'll give us a Nuxt-style progress indicator for builds.

**Comment by wi-development** [comment]
> It would also be great if we could add a timestamp to the `webpack compiled successfully` line as to indicate the last complete compilation

module.exports
stats: {
    timings: true
