### ISSUE TITLE
npm run dev & yarn run dev - Stuck at jQuery

### ISSUE THREAD

**Issue by dugajean** [JeffreyWay/laravel-mix#285]
So I'm running both these commands and the modules start building. The progress gets stuck at around 11-14% at jQuery. I've left it running for over 30 minutes and it didn't move.

I didn't do anything special to the node modules. It was fresh installation with only one extra package installed (https://github.com/puikinsh/gentelella).

What could be the cause of this?

**Comment by JeffreyWay** [comment]
You have to give me specific steps to reproduce your issue.

**Comment by iraklisg** [comment]
@dugajean I had a similar issue using another theme (admin-lte) Maybe I am wrong but I think that there must be a conflict with the JQuery version that your gantelella theme depends on and the JQuery version of the package you are trying to install... Try to comment out JQuery package from your project's `package.json` and try `npm install` again to see if there bundling is exited with no errors

**Comment by ctf0** [comment]
facing the same issue with a slight difference,
i included the jquery cdn in blade and added `window.$ = { jQuery };` to fix the `$ is undefined` which was working without any issues with gulp.

now
```bash
 ERROR  Failed to compile with 1 errors

This dependency was not found in node_modules:

* jquery

Did you forget to run npm install --save for it?
```
