### ISSUE TITLE
How to see details of system notifications

### ISSUE THREAD

**Issue by jozeflambrecht** [JeffreyWay/laravel-mix#2852]
-   Laravel Mix Version: 6.0.1
-   Node Version (`node -v`):
-   NPM Version (`npm -v`):
-   OS: Windows 10

### Description:
![image](https://user-images.githubusercontent.com/11506957/108566697-d8bf9700-72d4-11eb-8f34-fc23728b42f5.png)

### Steps To Reproduce:
When I run `npx mix`  and there is an error/issue, I get a system notification. When I click on the notification to see the full error message, the notification disappears.. I cannot see the error message in the terminal neither..

Is there a way to show the error messages in the terminal?

**Comment by thecrypticace** [comment]
Looks like you're running an older version of Mix v6. Can you update to the latest v6.0.11 and try again?

**Comment by jozeflambrecht** [comment]
that was it! thanks
