### ISSUE TITLE
CSS file not compile

### ISSUE THREAD

**Issue by virendra702** [JeffreyWay/laravel-mix#2853]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`) 5.0.1
-   Node Version (`node -v`): 12.17.0
-   NPM Version (`npm -v`): 6.14.9
-   OS: MacOS

### Description:
While using ReactJs when I am compiling JS externally along with react, I have also added scss to compile with them. at same time scss is not compiling. but react and JS are compiled successfully.

webpack.mix.js
![image](https://user-images.githubusercontent.com/47003593/108592756-77abc800-7395-11eb-8b67-f31f2786e97a.png)

complied css file is empty
![image](https://user-images.githubusercontent.com/47003593/108592686-12f06d80-7395-11eb-83ba-504dd81415c6.png)

**Comment by timothywalter** [comment]
I'm on Windows 10 (20H2) with the same issue, my css isn't being compiled either. My `resources/css/app.css` file contains only plain css. My mix file is dead simple:

```js
const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js')
 .css('resources/css/app.css', 'public/css', [
     //
 ]);
```

**What happens:** I run `npm run watch` or `prod` or `dev` (all same issue) and edit a css file. I get a notification 'Build successful'. Nevertheless looking in the log I do not see the css file, it just lists the javascript and an image file that is loaded from the css, which are the only  things copied/compiled to output. The css is nowhere to be seen.

Unlike virendra702 I do not get any file. The public/css folder remains empty.

```
+-- @tailwindcss/forms@0.2.1
+-- @tailwindcss/typography@0.3.1
+-- alpinejs@2.8.1
+-- autoprefixer@10.2.4
+-- axios@0.21.1
+-- laravel-mix@6.0.13
+-- lodash@4.17.21
+-- postcss@8.2.6
+-- postcss-import@12.0.1
`-- tailwindcss@2.0.3
```

Node / npm
`v12.16.3` / `6.14.5`

**Comment by timothywalter** [comment]
Wow, minutes after posting it I found that because of opening the project through a symlinked directory it didn't work. Not in bash, not in VS Code, not anywhere. I guess mix doesn't like symlinks. So nevermind my previous post
