### ISSUE TITLE
An empty webpack.mix.js file results in `Mix is not defined` when running npx mix CLI

### ISSUE THREAD

**Issue by jon48** [JeffreyWay/laravel-mix#2856]
-   Laravel Mix Version  (`npm list --depth=0`): 6.0.11
-   Node Version (`node -v`): v14.15.5
-   NPM Version (`npm -v`): 6.14.9
-   OS: Windows 10 20H2 (19042.804)

### Description:

Having upgraded to Laravel Mix 6, I am trying to convert my npm run commands to the npx mix ones as suggested on the [upgrade notes](https://laravel-mix.com/docs/6.0/upgrade). 

I am however hitting an issue when trying to run the command straight in a the command prompt:
```dos
npx mix
[webpack-cli] ReferenceError: Mix is not defined
    at module.exports ([my_project_root_path]\node_modules\laravel-mix\src\builder\webpack-default.js:6:18)
    at WebpackConfig.build ([my_project_root_path]\node_modules\laravel-mix\src\builder\WebpackConfig.js:24:30)
    at Mix.build ([my_project_root_path]\node_modules\laravel-mix\src\Mix.js:70:35)
    at module.exports ([my_project_root_path]\node_modules\laravel-mix\setup\webpack.config.js:13:16)
    at async [my_project_root_path]\node_modules\webpack-cli\lib\webpack-cli.js:1222:37
    at async Promise.all (index 0)
    at async evaluateConfig ([my_project_root_path]\node_modules\webpack-cli\lib\webpack-cli.js:1213:35)
    at async Promise.all (index 0)
    at async WebpackCLI.resolveConfig ([my_project_root_path]\node_modules\webpack-cli\lib\webpack-cli.js:1244:38)
    at async WebpackCLI.createCompiler ([my_project_root_path]\node_modules\webpack-cli\lib\webpack-cli.js:1670:22)
```
What I struggle to understand is that it is working fine when I am using it in the Visual Studio code debugger, or as a NPM script with for instance `npm run development` and :
```json
  "scripts": {
    "development": "npx mix"
  },
```
It is working fine as well on another project on the same computer, or if I use the [Intallation example in the Laravel-mix documentation](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/installation.md). I have as well already uninstall and reinstall the laravel-mix library.
I have found out that I can make it work for my project by adding `mix.boot()` in the `setup/webpack.config.js` file.

Having tried several versions in the 6.0 series, it is working fine in my project until v6.0.6, and breaks on v6.0.7 (which could point to the commit b12cefc66676c71404dc7b700ab1df9148257755).

Sorry if this is not the correct place to post, as this is more likely a problem in my setup than an issue with laravel-mix itself, but I have tried posting on a laravel forum without much luck.

### Steps To Reproduce:
Run `npx mix` in a command prompt, at the root of the project.

**Comment by thecrypticace** [comment]
What does your webpack.mix.js file look like?

**Comment by jon48** [comment]
Thanks for the direction, I should have been more careful about that part, and that was where the issue lied.

In my set up, I actually have only the webpack.mix.js used to load other mix.js files based on an environment variable.
As a consequence, the file is basically only : 
```js
if (process.env.section) {
    require(`${__dirname}/webpack.mix.${process.env.section}.js`);
}
```
So in my test, as no environment variable was set, it just exited of the script immediately without having done anything.
To be fair, in normal operations, I would never be running `npx mix` straight out of nothing (as I would set the environment variable beforehand), but as I was just testing the command itself, and it was working in versions prior to v6.0.7, I did not question that part.

By modifying the `webpack.mix.js` to load the laravel-mix library (which was the first line in the subsequent loaded file), it is working fine, even without setting the environment variable (doing nothing of course, but not failing)

```js
let mix = require('laravel-mix');

if (process.env.section) {
    require(`${__dirname}/webpack.mix.${process.env.section}.js`);
}
```

So, it is actually an issue easy to reproduce (just have an empty `webpack.mix.js`), in which case there is a difference of behaviour between versions prior and after v6.0.7, but as it is a bit of an edge case, I guess the issue can be closed.

**Comment by thecrypticace** [comment]
Ah yes indeed. Because boot is called in `src/index.js`. While not necessarily a bug this is something we should think about "fixing". We'll this issue open.

Complete aside:
What's your use case for multiple mix files? I know of some that some people use (I myself have done some interesting things w/ mix files and env vars). Is there something we could do to simplify or eliminate the need to use them?

**Comment by jon48** [comment]
Thanks.
To be honest, I do not have a strong use case for it: I need to have multiple entry points to build independent resources, but I can easily switch to the --mix-config option for that (which I am probably going to do anyway).

**Comment by thecrypticace** [comment]
That's really good to know. Thanks!
