### ISSUE TITLE
Laravel Mix v6 can't handle directories with a ':' in the directory name

### ISSUE THREAD

**Issue by lphilps** [JeffreyWay/laravel-mix#2858]
-   Laravel Mix Version: 6.0.11 (`npm list --depth=0`)
-   Node Version (`node -v`): v12.20.2
-   NPM Version (`npm -v`): 6.14.11
-   OS: Amazon Linux2, (Centos v7)

### Description:
If the directory that contains your Laravel repository contains a ':', then "npm run development" will fail with "sh: mix: command not found".

This is a change in behaviour from Mix v5.  When we extract code as part of our deployment process we extract it into a directory that contains the date/time of the head commit and that includes colons between the components of the timestamp (i.e. hh:mm:ss). That has worked fine with every Laravel version up until mix v6, but this directory naming convention makes mix v6 very unhappy.

Obviously the workaround is "don't use colons in a directory names", but ...

### Steps To Reproduce:

```
composer create-project laravel/laravel laravel8
cd laravel8
npm install
npm run development
# This will work "just fine"

cd ..
mv laravel8 laravel:8
cd laravel:8
npm run development
> @ development /var/www/versions/laravel:8
> mix

sh: mix: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @ development: `mix`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ development script.
```

**Comment by Quezler** [comment]
same on mac
