### ISSUE TITLE
npm run watch does not work

### ISSUE THREAD

**Issue by r1chter1** [JeffreyWay/laravel-mix#2861]
-   Laravel Mix Version: 6.0.11 (`npm list --depth=0`)
-   Node Version 14.15.5 (`node -v`):
-   NPM Version 7.5.6 (`npm -v`):
-   OS: Ubuntu 20.04 LTS

### Description:
I cannot run `npm run watch`. I have written all scripts and config file `webpack.mix.js`. I want to use laravel-mix with React.
### Steps To Reproduce:
This is what I get when I run `npm run watch`:
`
[webpack-cli] Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.chunkFilename should be a string.
   -> The filename of non-entry chunks as relative path inside the `output.path` directory.
 - configuration.stats has an unknown property 'preset'. These properties are valid:
   object { all?, assets?, assetsSort?, builtAt?, cached?, cachedAssets?, children?, chunkGroups?, chunkModules?, chunkOrigins?, chunks?, chunksSort?, colors?, context?, depth?, entrypoints?, env?, errorDetails?, errors?, exclude?, excludeAssets?, excludeModules?, hash?, logging?, loggingDebug?, loggingTrace?, maxModules?, moduleAssets?, moduleTrace?, modules?, modulesSort?, nestedModules?, optimizationBailout?, outputPath?, performance?, providedExports?, publicPath?, reasons?, source?, timings?, usedExports?, version?, warnings?, warningsFilter? }

`

**Comment by thecrypticace** [comment]
Can you please post your package.json file and webpack.mix.js files?

I suspect you have a dependency that is somehow installing webpack 4 as a peer dev and it's messing stuff up.

**Comment by r1chter1** [comment]
> Can you please post your package.json file and webpack.mix.js files?
> 
> I suspect you have a dependency that is somehow installing webpack 4 as a peer dev and it's messing stuff up.

```
// package.json
"scripts": {
    "development": "mix",
    "watch": "mix watch",
    "watch-poll": "mix watch -- --watch-options-poll=1000",
    "hot": "mix --hot",
    "production": "mix --production"
}
// webpack.mix.js
let mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js').react();
```

**Comment by octoquad** [comment]
@r1chter1, I had the same problem. After trying various things, I resorted to:

```
npm remove --save-dev cross-env laravel-mix postcss resolve-url-loader sass sass-loader
npm install --save-dev laravel-mix
npm run dev # needs to run npm install sass-loader@10.* sass resolve-url-loader@^3.1.2 --save-dev --legacy-peer-deps
npm run dev
```

And I finally got `webpack compiled successfully`.

**Comment by r1chter1** [comment]
> @r1chter1, I had the same problem. After trying various things, I resorted to:
> 
> ```
> npm remove --save-dev cross-env laravel-mix postcss resolve-url-loader sass sass-loader
> npm install --save-dev laravel-mix
> npm run dev # needs to run npm install sass-loader@10.* sass resolve-url-loader@^3.1.2 --save-dev --legacy-peer-deps
> npm run dev
> ```
> 
> And I finally got `webpack compiled successfully`.

Can you be more precise? What is in your scripts in package.json?

**Comment by octoquad** [comment]
> Can you be more precise? What is in your scripts in package.json?

Sure.

**Before**
```json
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "npm run development -- --watch",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "@fortawesome/fontawesome-free": "^5.14.0",
    "axios": "^0.19.2",
    "bootstrap": "^4.5.0",
    "bootstrap-daterangepicker": "^3.1.0",
    "cross-env": "^5.1",
    "jquery": "^3.5.1",
    "laravel-mix": "^4.0.7",
    "lodash": "^4.17.19",
    "moment": "^2.27.0",
    "popper.js": "^1.12",
    "resolve-url-loader": "^2.3.1",
    "sass": "^1.26.10",
    "sass-loader": "^7.1.0",
    "standard": "^14.3.4",
    "vue-template-compiler": "^2.6.11"
  },
  "standard": {
    "global": [
      "$",
      "moment"
    ]
  }
}
```
**After**

```json
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "mix",
    "watch": "mix watch",
    "watch-poll": "mix watch -- --watch-options-poll=1000",
    "hot": "mix watch --hot",
    "prod": "npm run production",
    "production": "mix --production"
  },
  "devDependencies": {
    "@fortawesome/fontawesome-free": "^5.14.0",
    "bootstrap": "^4.5.0",
    "bootstrap-daterangepicker": "^3.1.0",
    "cross-env": "^7.0.3",
    "jquery": "^3.5.1",
    "laravel-mix": "^6.0.13",
    "lodash": "^4.17.20",
    "moment": "^2.27.0",
    "popper.js": "^1.12",
    "resolve-url-loader": "^3.1.2",
    "sass": "^1.32.8",
    "sass-loader": "^10.1.1",
    "standard": "^14.3.4"
  },
  "standard": {
    "global": [
      "$",
      "moment"
    ]
  }
}
```

**Comment by r1chter1** [comment]
> > Can you be more precise? What is in your scripts in package.json?
> 
> Sure.
> 
> **Before**
> 
> ```json
> {
>   "private": true,
>   "scripts": {
>     "dev": "npm run development",
>     "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "watch": "npm run development -- --watch",
>     "watch-poll": "npm run watch -- --watch-poll",
>     "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "prod": "npm run production",
>     "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
>   },
>   "devDependencies": {
>     "@fortawesome/fontawesome-free": "^5.14.0",
>     "axios": "^0.19.2",
>     "bootstrap": "^4.5.0",
>     "bootstrap-daterangepicker": "^3.1.0",
>     "cross-env": "^5.1",
>     "jquery": "^3.5.1",
>     "laravel-mix": "^4.0.7",
>     "lodash": "^4.17.19",
>     "moment": "^2.27.0",
>     "popper.js": "^1.12",
>     "resolve-url-loader": "^2.3.1",
>     "sass": "^1.26.10",
>     "sass-loader": "^7.1.0",
>     "standard": "^14.3.4",
>     "vue-template-compiler": "^2.6.11"
>   },
>   "standard": {
>     "global": [
>       "$",
>       "moment"
>     ]
>   }
> }
> ```
> 
> **After**
> 
> ```json
> {
>   "private": true,
>   "scripts": {
>     "dev": "npm run development",
>     "development": "mix",
>     "watch": "mix watch",
>     "watch-poll": "mix watch -- --watch-options-poll=1000",
>     "hot": "mix watch --hot",
>     "prod": "npm run production",
>     "production": "mix --production"
>   },
>   "devDependencies": {
>     "@fortawesome/fontawesome-free": "^5.14.0",
>     "bootstrap": "^4.5.0",
>     "bootstrap-daterangepicker": "^3.1.0",
>     "cross-env": "^7.0.3",
>     "jquery": "^3.5.1",
>     "laravel-mix": "^6.0.13",
>     "lodash": "^4.17.20",
>     "moment": "^2.27.0",
>     "popper.js": "^1.12",
>     "resolve-url-loader": "^3.1.2",
>     "sass": "^1.32.8",
>     "sass-loader": "^10.1.1",
>     "standard": "^14.3.4"
>   },
>   "standard": {
>     "global": [
>       "$",
>       "moment"
>     ]
>   }
> }
> ```
> 
> Forgot to mention, I also ran `npm ci` a number of times with other methods before running the above commands.

are you using React or Vue?

**Comment by octoquad** [comment]
Neither, but the problem is experienced without React or Vue. Hence the removal of `"vue-template-compiler": "^2.6.11"` since that was a hard dependency with Laravel Mix 5.x.

**Comment by r1chter1** [comment]
guys, i need a solution.

**Comment by r1chter1** [comment]
[Solution](https://medium.com/how-to-react/use-npm-watch-to-auto-build-your-reactjs-app-6ed0e5d6cb00)

I have solved my problem.

**Comment by georgejoseph1994** [comment]
I had the same issue in laravel 8 with sail (docker). The issue started when I installed a npm package without sail

"npm i package_name" instead of "./vendor/bin/sail npm i package_name"

After wrestling with this issue for a while I noticed that I had a node version miss match. local node -v was 10 and docker node -v was 16.
This may have caused installation of older webpack and may have broken npm run watch

Worked around by bringing up my node version to 16 in my machine using nvm and deleting node modules and clearing npm cache.
I am compiling assets now without sail, just "npm run watch"

**Comment by jasperf** [comment]
Using Laravel 9 and Laravel Mix 6.0.41 and  `mix watch` and `mix watch --hot` do run but do not work for me.

This is the part in `package.json` with the commands I can trigger using `npm run watch` for example:

```js
"watch": "mix watch",
"watch-poll": "npm run watch -- --watch-poll",
"hot": "mix watch --hot",
```
but no errors. Any ideas why this could be?
