### ISSUE TITLE
Hello, How to I turn Notifications back on (Windows 10)?

### ISSUE THREAD

**Issue by Shomrat-Gil** [JeffreyWay/laravel-mix#2865]
-   Laravel Mix Version: @6.0.11 (`npm list --depth=0`)
-   Node Version (`node -v`): v14.15.4
-   NPM Version (`npm -v`): 6.14.5
-   OS: Windows 10 (Wamp server)

### Description:
I turned Off "notifications & actions" for Laravel Mix and now after npm run dev I`m getting 
Notifications are disabled
Reason: DisabledForApplication Please make sure that the app id is set correctly.
Command Line: Laravel\node_modules\node-notifier\vendor\snoreToast\snoretoast-x64.exe -appID "Laravel Mix" -pipeName \\.\pipe\notifierPipe-cd96c540-4c1f-4ae6-9f87-2213989f66d8 -p Laravel\node_modules\laravel-mix\icons\laravel.png -m "Build successful" -t "Laravel Mix"

Thanks

**Comment by ihpack** [comment]
I have a some problem

**Comment by PrOpOvEdNiK** [comment]
same

**Comment by nekooee** [comment]
same

**Comment by shahsani** [comment]
Hy All,

This solution helped me enable back the Laravel Mix notifications on Win10

https://laracasts.com/discuss/channels/elixir/how-to-enable-laravel-mix-notification?page=1&replyId=751173

**Comment by nekooee** [comment]
> Hy All,
> 
> This solution helped me enable back the Laravel Mix notifications on Win10
> 
> https://laracasts.com/discuss/channels/elixir/how-to-enable-laravel-mix-notification?page=1&replyId=751173
> 
> If it helps anyone, please do feedback! <3

Works well. It was professional. good job.
