### ISSUE TITLE
mix-manifest.json are always generated

### ISSUE THREAD

**Issue by florianbouvot** [JeffreyWay/laravel-mix#2871]
- Laravel Mix Version: 6.0.13 (npm list --depth=0)
- Node Version: 15.10.0
- NPM Version: 7.5.6
- OS: macOS 11.2.2

### Description:

I use the following config and `mix-manifest.json` file are always generated.

With query strings in production and without in development.

```
if (mix.inProduction()) {
  mix.version()
}
```

That not a real issue but why `mix-manifest.json` exist in development mode?

### Steps To Reproduce:

You can look at this config: https://github.com/florianbouvot/laravel-mix-boilerplate/tree/next

**Comment by thecrypticace** [comment]
This is intentional. `.version()` only changes the manifest to add file hashes.

We always generate the manifest to ensure the `mix()` function works as expected all the time.

**Comment by florianbouvot** [comment]
@thecrypticace sorry
