### ISSUE TITLE
How to remove console.log from production 

### ISSUE THREAD

**Issue by Stacey940** [JeffreyWay/laravel-mix#2873]
-   Laravel Mix Version: 6.0.6
-   Node Version (`node -v`): v12.19.0
-   NPM Version (`npm -v`): 6.14.8
-   OS: Windows 10

What I need to add in the options for vue to remove console.log from production. Here is the content of my webpack.mix.js file

```
const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js')
   .vue();
```

**Comment by sdevore** [comment]
I have done it like this in the past 
```javascript
if (mix.inProduction()) {
  mix.options({
    terser: {
      terserOptions: {
        compress: {
          drop_console: true
        }
      }
    }
  })
}
```

**Comment by Stacey940** [comment]
@sdevore  that worked. Thank you for your help.
