### ISSUE TITLE
VUE component style not effect with wrong class name

### ISSUE THREAD

**Issue by GemaDynamic** [JeffreyWay/laravel-mix#2879]
-   Laravel Mix Version: 6.0.13
-   Node Version :v14.15.4
-   NPM Version :6.14.10
-   OS: windows10

### Description:
I make a VUE component in Laravel project and edit like this:  
```
<template>
    <div class="table-box-s" id="chart">
        <div class="table-title">title</div>
        <div class="table-sel-box flex">
            <div class="sel-box flex-between">
                <p class="sel-text">name</p>
                <img
                    class="sel-arrow"
                    src="http://daping.test/assets/imgs/screen-icon-arrow.png"
                    alt="select"
                />
            </div>
           <p>other code</p>
        </div>
        <div id="line" class="table-chart"></div>
    </div>
</template>

<script>
  ...
</script>

<style lang="scss" scoped>
.table-box-s {
   // some css
    z-index: 10;
    .table-title {
       // some css
    }
    .table-info-box {
      // some css
        .table-info-item {
           
        }
    }
   // some css
}
</style>

``` 
when I run `npm run watch` and use it in blade. I get this code in browser html head
```
<style>
._1MK_yfcoY5t_9F79x8VS_ ._2MRNSvxEAzPyahteH9wxak ._2JhTOu_9HO9td3_KWT5WkU[data-v-91b37c4c] {
// css
}
._1MK_yfcoY5t_9F79x8VS_ ._2MRNSvxEAzPyahteH9wxak ._2JhTOu_9HO9td3_KWT5WkU ._32gONQNxzsB53V6EZp4NFM[data-v-91b37c4c] {
// css
}
._1MK_yfcoY5t_9F79x8VS_ ._2MRNSvxEAzPyahteH9wxak ._2JhTOu_9HO9td3_KWT5WkU .XZcjZuLwX7u_iFEWP5dZI[data-v-91b37c4c] {
// css
}
._1MK_yfcoY5t_9F79x8VS_ ._2MRNSvxEAzPyahteH9wxak ._19u80DcXyfFK-LWTms8YQo[data-v-91b37c4c] {
// css
}
.uLQYFZznlB5a-USscx5Ge[data-v-91b37c4c] {
// css
}
._2BfyR80VNlfUh1IEgNq_wk[data-v-91b37c4c] {
// css
}
._2BfyR80VNlfUh1IEgNq_wk[data-v-91b37c4c]::before, ._2BfyR80VNlfUh1IEgNq_wk[data-v-91b37c4c]::after {
// css
}
</style>
```
but my brwoser `html>body>div#app` doesn't have elements with class attribute with `_` 
![image](https://user-images.githubusercontent.com/31176914/110293902-1d179a80-802a-11eb-92a0-fe0c51b9546a.png)
![image](https://user-images.githubusercontent.com/31176914/110293950-2bfe4d00-802a-11eb-9690-744dc690799c.png)

I don't how to fix this 😢 

### Steps To Reproduce:
- create a default laravel project
- install laravel/ui and run `php artisan ui vue`
- edit `resources/js/components/ExampleComponent.vue` like my code
- run `npm install` and `npm run dev/watch`
- run `php artisan serve` and go to [localhost:8000](localhost:8000)

**Comment by thecrypticace** [comment]
That looks like it's using CSS modules for some reason. I'll try to take a look soon-ish

**Comment by GemaDynamic** [comment]
@thecrypticace my `project.json` is:
```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production",
        "webpack": "webpack --version"
    },
    "devDependencies": {
        "bootstrap": "^4.0.0",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "popper.js": "^1.12",
        "postcss": "^8.1.14",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.20.1",
        "sass-loader": "^8.0.0",
        "vue": "^2.5.17",
        "vue-loader": "^15.9.5",
        "vue-template-compiler": "^2.6.10",
        "axios": "^0.21.1",
        "css-loader": "^0.28.11",
        "less": "^4.1.1",
        "less-loader": "^8.0.0",
        "node-sass": "^4.14.1",
        "style-loader": "^2.0.0",
        "stylus-loader": "^5.0.0",
        "vue-style-loader": "^3.0.1"
    },
    "dependencies": {
        "echarts": "^5.0.2",
        "vue-axios": "^3.2.4",
        "vue-router": "^3.5.1"
    }
}
```

**Comment by timmaier** [comment]
+1 I also have this issue
app.js
![Screenshot from 2021-03-12 12-10-25](https://user-images.githubusercontent.com/19884817/110881387-01fba200-832c-11eb-8f11-d733265e769f.png)
vue component
![Screenshot from 2021-03-12 12-11-17](https://user-images.githubusercontent.com/19884817/110881427-1475db80-832c-11eb-83ba-fa01f39d410f.png)
![Screenshot from 2021-03-12 12-11-57](https://user-images.githubusercontent.com/19884817/110881487-29eb0580-832c-11eb-987e-04b1a08f7762.png)

**Comment by timmaier** [comment]
I am running laravel mix v6.0.13

I commented out line 119 in node_modules/laravel-mix/src/components/CssWebpackConfig.js and replaced with modules: false and the styles apply.

```
    // modules: useCssModules
    modules: false
```

**Comment by GemaDynamic** [comment]
> I am running laravel mix v6.0.13
> 
> I commented out line 119 in node_modules/laravel-mix/src/components/CssWebpackConfig.js and replaced with modules: false and the styles apply.
> 
> ```
>     // modules: useCssModules
>     modules: false
> ```
> 
> So this confirms @thecrypticace suspicion that it's related to CssModules

Thanks , I'll try it later 😄

**Comment by AhmadOf** [comment]
I have same issue here, any one knows how to fix it? @GemaDynamic @timmaier @thecrypticace 

thank you
