### ISSUE TITLE
Error when I run 'npm run dev'

### ISSUE THREAD

**Issue by scarlet11-dev** [JeffreyWay/laravel-mix#2880]
-   Laravel Mix Version: 6.0.13
-   Node Version: v14.16.0

-   NPM Version: 6.14.11

-   OS: Windows

### Description: After I run this code " php artisan ui vue --auth " for the dependencies of my auth . It asked me to run "npm install and npm run dev" but when I tried to run "npm run dev" I got this error instead.

> @ development C:\wamp64\www\my_laravel_dir
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

[webpack-cli] Error: Unknown option '--hide-modules'
[webpack-cli] Run 'webpack --help' to see available commands and options
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\McCrigents\AppData\Roaming\npm-cache\_logs\2021-03-08T23_18_45_318Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\McCrigents\AppData\Roaming\npm-cache\_logs\2021-03-08T23_18_45_380Z-debug.log

**Comment by nichalko** [comment]
You seem to be on Laravel Mix version 6, so you should be using these commands to run mix: https://laravel-mix.com/docs/6.0/cli 

Look at your package.json for scripts and update using this:
https://laravel-mix.com/docs/6.0/upgrade#update-your-npm-scripts
