### ISSUE TITLE
Doc for Stand Alone project does not give enough detail.

### ISSUE THREAD

**Issue by nigelwhite** [JeffreyWay/laravel-mix#2882]
The explanation for setting up a Stand Alone project would not be sufficient for a beginner to succeed. Each step needs to be explicitly described.

**Comment by lmeysel** [comment]
I think you probably should formulate the things you are missing exactly?

**Comment by nigelwhite** [comment]
I'm a beginner and I finally got it working so maybe this will help someone else. NB my context is Linux Mint, building a Drupal 9 site with [ddev](https://ddev.readthedocs.io/en/stable/). Hoping to make this guide more generic, I have omitted the steps for installing ddev or Drupal. The bit I could not find instructions for was Live Reload.

Steps
-   make a new project and cd into it
-   npm init -y
-   npm install laravel-mix --save-dev
-   touch webpack.mix.js
-   in this file insert

```js
let mix = require('laravel-mix');
mix.sass('src/app.sass', 'css').setPublicPath('public');
```

-   create directory /public
-   create file /public/index.html
-   in index.html `<link rel="stylesheet" href="css/app.css" />`
-   create src/app.sass and put a sass rule in there
-   $ npx mix watch // this will compile on any change

Live Reload

-   Laravel Mix has the ability to use Browser sync for live reload
-   [Andre Madarang video](https://www.youtube.com/watch?v=mTlf0PgwS9w&ab_channel=AndreMadarang) 11.20
-   npm install -g browser-sync
-   for a Drupal project, in webpack.mix.js

```js
let mix = require('laravel-mix');
mix.sass('scss/style.scss', 'css/')
	.browserSync({
		proxy: 'http://permies-d9.ddev.site:81', // this is the url that ddev provides for display of the local site
		files: ['scss/style.scss'],
	});
```
