### ISSUE TITLE
'npm run hot' doesn't generate CSS

### ISSUE THREAD

**Issue by FunctionDJ** [JeffreyWay/laravel-mix#2885]
-   Laravel Mix Version: 6.0.13
-   Node Version: v15.11.0
-   NPM Version: 7.6.0
-   OS: Windows 10 x64 Pro

### Description:
CSS is not being created or updated by mix when running `npm run hot` even though it logs to the console that it has done so.
`npm run watch` or `dev` work.

### Steps To Reproduce:
1. Create any valid CSS step in the `webpack.mix.js`, for example: `mix.css("resources/foo.css", "css/foo.css");`
2. Validate that the CSS file is being created when running `npm run watch` (`dev` works too)
3. Clear the CSS, then run `npm run hot`

**Comment by thecrypticace** [comment]
HMR serves files from the in memory dev server. Laravel handles this by using the mix helper which prefixes requests by the dev server url in the `hot` file when it exists.

**Comment by FunctionDJ** [comment]
Okay, i understand this is by design, but i still don't understand how i can enable HMR *and* generate CSS at the same time.

**Comment by thecrypticace** [comment]
What's the reason you want that behavior?

**Comment by FunctionDJ** [comment]
As far as i can see, there's no way to have hot reloading with CSS in Mix, which other 'webpack wrappers' like creat-react-app or Next.js can.
