### ISSUE TITLE
Mix ignores spaces in directory names, throws error

### ISSUE THREAD

**Issue by MelvinSnijders** [JeffreyWay/laravel-mix#2886]
-   Laravel Mix Version: 6.0.13
-   Node Version 14.16.0
-   NPM Version 6.14.11
-   OS: Windows 10 Professional

### Description:
When a project is in a directory containing a space, Laravel Mix can't run.
If for example my project is in C:\My Projects\ProjectA, mix tries to execute `mkdir 'C:\My'`.

### Steps To Reproduce:
1. Create a project in a directory containing a space. Update: with a space in the Windows uer directory
2. Try running Laravel Mix.

**Comment by thecrypticace** [comment]
Can you please provide your `webpack.mix.js`? We've already fixed a handful of issues with spaces in paths on Windows

**Comment by MelvinSnijders** [comment]
Just tested it some more, seems like it just tries to create a directory somewhere in my users folder. So none of the projects work, since my user folder contains a space.

I haven't touched the default webpack.mix.js:

`const mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel applications. By default, we are compiling the CSS
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [
        //
    ]);
`

**Comment by thecrypticace** [comment]
Can you post the error output here (or in a gist)? Off the top of my head I'm not aware of anywhere mix would execute a mkdir operation from the shell that could cause this.

**Comment by MelvinSnijders** [comment]
```bash
$ npm run dev

> @ dev C:\Users\Melvin Snijders\Documents\Development\Laravel\MelvinSnijders
> npm run development


> @ development C:\Users\Melvin Snijders\Documents\Development\Laravel\MelvinSnijders
> mix

Error: EPERM: operation not permitted, mkdir 'C:\Users\Melvin'
programma werd niet gevonden in webpack
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `mix`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by thecrypticace** [comment]
hmm okay I'll take a look

**Comment by MelvinSnijders** [comment]
After investigating further, I found [this ](https://github.com/zkat/npx/issues/146) issue from npx.
This is (or has been) an issue with NPM, not with Webpack or Laravel Mix (I guess).

Changing the cache folder with `npm config set cache "C:\tmp\nodejs\npm-cache" --global`
Note: this directory can't contain a space!

**Comment by thecrypticace** [comment]
Oh wow this is good to know. I wasn't aware of that behavior. That'll be a good thing for us to document.
