### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by mikemenard** [JeffreyWay/laravel-mix#289]
I get this error when I run `npm run dev` on a fresh install.

![capture d ecran 2017-02-03 a 15 37 16](https://cloud.githubusercontent.com/assets/12190675/22607636/b5395d74-ea26-11e6-83b7-800c911fee88.png)

[npm-debug.log.zip](https://github.com/JeffreyWay/laravel-mix/files/751508/npm-debug.log.zip)

**Comment by JeffreyWay** [comment]
This will be fixed here - https://github.com/laravel/laravel/pull/4136 - as soon as it's merged. Until then, you can manually add 

```
$icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";
```

to your `resources/assets/sass/_variables.scss` file.

**Comment by mesqueeb** [comment]
This fixed the bug for me!

**Comment by vedmant** [comment]
@JeffreyWay I have the same issue after upgrading to 0.6 version. This fix with font path variable doesn't fix actual problem with relative paths, I have many correct relative paths in my scss files to images, but now all they are not loading. Relative paths to resources are set for all node packages by default, like "font-awesome", "simple-line-icons", "bootstrap-sass" I think they should be loaded using default relative paths, but it fails now.

**Comment by apocalyarts** [comment]
^ +1

Having the same problem with fontawesome and flag-icon-css packages.

**Comment by cmgmyr** [comment]
@apocalyarts for font awesome you'll have to add this to your variables file

```
$fa-font-path: "~font-awesome/fonts/";
```

[Ref](https://github.com/FortAwesome/Font-Awesome/blob/04dad1e192b129ab09cddcd9b1aefb8b189c8d79/scss/_variables.scss#L7)

**Comment by vedmant** [comment]
@cmgmyr What about `~datatables.net-dt/css/jquery.dataTables` or any other package without variables for path, or just plain css.

**Comment by BlazOrazem** [comment]
That's jus terrible. Now I must include bootstrap from npm package, because it doesn't work via bower package.. same error with these fonts..

**Comment by adriaanzon** [comment]
Why? Can't you change the font path variable to where bower puts the files?

**Comment by AdamEsterle** [comment]
@JeffreyWay @cmgmyr 
Is putting
```
$icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";
$fa-font-path: "~font-awesome/fonts/";
```
in your _variables.scss file a fix or a temporary solution?

The font awesome error is weird, because for me, I am including it with composer so I import it via the vendor folder:
`@import "vendor/fortawesome/font-awesome/scss/font-awesome";`
But then it still errors out because it is looking for the fonts in the node modules folder...

`These dependencies were not found in node_modules:`

**Comment by mislam** [comment]
@JeffreyWay Is it merged? How come it's still spitting the same error. My `composer.json` has:
```
"laravel/framework": "5.4.*",
```
Can you help?

**Comment by lasseal** [comment]
What about packages that doesn't have a variable for path, like plain CSS files? In my specific case it's image files from `fronteed/iCheck/`that make `caravel-mix` squawk. Don't want to dive in and go editing vendor files.

**Comment by Hugome** [comment]
For plain css you can use ~ : 

I want to integrate admin-lte so i include the css : 
```sass
@import "node_modules/admin-lte/dist/css/AdminLTE";
@import "node_modules/admin-lte/dist/css/skins/skin-blue";
```
Result :
```
This dependency was not found in node_modules:

* ../img/boxed-bg.jpg

Did you forget to run npm install --save for it? 
```
I replace with :
```sass
@import "~admin-lte/dist/css/AdminLTE.css";
@import "~admin-lte/dist/css/skins/skin-blue.css";
```
And build successful !
With the asset 'img/boxed-bg.jpg' copied in public/images/

**Comment by lasseal** [comment]
Cool, thanks! It seems to resolve regardless in `v8.0.0`.

**Comment by georaldc** [comment]
@Hugome Similar issue to this https://github.com/almasaeed2010/AdminLTE/issues/1360

Adding mix.options({ processCssUrls: false }); works for me. The option was added in version 0.80

https://github.com/JeffreyWay/laravel-mix/releases/tag/v0.8.0
