### ISSUE TITLE
WARNING in Plugin name should be specified

### ISSUE THREAD

**Issue by florianbouvot** [JeffreyWay/laravel-mix#2892]
-   Laravel Mix Version: 6.0.13
-   Node Version (`node -v`): 5.11.0
-   NPM Version (`npm -v`): 7.6.3
-   OS: macOs 11.2.3

### Description:

I'm using `image-minimizer-webpack-plugin` and I've a warning when using npm (not visible with yarn): `WARNING in Plugin name should be specified`.

Is there a way to find more info or to fix that?

```
.webpackConfig({
    plugins: [
      new ImageMinimizerPlugin({
        minimizerOptions: {
          plugins: [
            ['gifsicle'],
            ['mozjpeg', { quality: 50 }],
            ['pngquant', { quality: [0.5, 0.5] }],
            ['svgo', { plugins: [{ removeViewBox: false }] }],
          ],
        },
      }),
    ],
  })
```

### Step to reproduce

https://github.com/florianbouvot/laravel-mix-boilerplate/blob/next/webpack.mix.js

**Comment by mnightingale** [comment]
In svgo 2 config syntax changed.

Ref https://github.com/imagemin/imagemin-svgo/commit/43888a0389bdd4c8e7790d5c2cea25d497a561ea

```
.webpackConfig({
    plugins: [
      new ImageMinimizerPlugin({
        minimizerOptions: {
          plugins: [
            ['gifsicle'],
            ['mozjpeg', { quality: 50 }],
            ['pngquant', { quality: [0.5, 0.5] }],
            ['svgo', { plugins: [{name: 'removeViewBox', active: false}] }],
          ],
        },
      }),
    ],
  })
```

**Comment by florianbouvot** [comment]
@mnightingale thank you 😉
