### ISSUE TITLE
Allow adjusting the loader-configurations explicitly

### ISSUE THREAD

**Issue by lmeysel** [JeffreyWay/laravel-mix#2898]
-   Laravel Mix Version: 6.x.x

When using typescript i had the requirement to pass a tsconfig explicitly (like `tsconfig.mix.json`). Though not documented, it is possible to pass [ts-loader options](https://github.com/TypeStrong/ts-loader#loader-options) to `mix.ts('src/client/main.ts', 'client.js', { configFile: 'tsconfig.mix.json' })`, which works fine.

The problem occurs, when registering multiple TS entry files. Mix will then consider only the options passed to the __last__ `mix.ts(...)` call, which is pretty inconvinient and error-prone, as it suggests, this config does only apply to the given TS entry or suddenly has no effect when changing the order of the `mix.ts(...)`-calls.

Using sass/scss mix behaves more as expected: Applying sass-loader configs only are applied to the corresponding entry-file. This is great, but sometimes I have a one-for-all configuration which would be great to be merged (for me e.g. I often use the custom sass function which I can pass using `mix.sass(... , { sassOptions: { functions: { 'in-production()'() { ... } } } })`.

As a summary, I suggest an additional mix method like `mix.loaderOptions` which allows configuring loaders e.g. by name, like
```typescript
mix
  .loaderOptions('ts-loader', { configFile: 'tsconfig.mix.json' })
  .loaderOptions('sass-loader', { sassOptions: { functions: { ... } } })
```

**Comment by thecrypticace** [comment]
That's a pretty good idea! I'm not 100% sure if this is the the route we'd want to take but the general idea is good. You can achieve something like this by using the .webpackConfig method already by passing in a function but it's a bit cumbersome because you have to loop over the rules and find the respective loader configurations.

**Comment by lmeysel** [comment]
Yep.. this is what I came up with before I found out that i can pass loader options directly to the `mix.ts(...)`-call:

```javascript
mix.extend('tsconfig', function (webpackConfig) {
  const fil = 'tsconfig.webpack.json', loader = 'ts-loader';
  const joinOpts = (opt, fil) => { opt ? opt.configFile = fil : { configFile: fil }; return opt }
  webpackConfig.module.rules.forEach(rule => {
    if (rule.loader === loader)
      joinOpts(rule.options, 'tsconfig.webpack.json');
    else if (rule.loaders && rule.loaders.indexOf(loader) !== -1)
      rule.use = rule.loaders.map(ldr => ldr === loader ? { loader, options: joinOpts(null, fil) } : { loader });
    else if (rule.use && rule.use.find(u => u.loader == loader))
      rule.use.find(u => u.loader === loader && joinOpts(u.options, fil))
  });
}).tsconfig();```
