### ISSUE TITLE
npm run hot doesn't produce manifest file required by mix helper

### ISSUE THREAD

**Issue by rhyek** [JeffreyWay/laravel-mix#290]
Basically what the title says. In order for the `hot` or `hmr` script to work you would have to run either of the other scripts first.

**Comment by dreamburst** [comment]
I receive this error whenever I try to build under any dev environment, if it is of any relevance:

```
 94% asset optimization/path/to/my/project/node_modules/laravel-mix/src/Manifest.js:22
        this.transformStats(stats)
             ^

TypeError: this.transformStats is not a function
...
```

**Comment by JeffreyWay** [comment]
@dreamburst Unrelated. Did you copy our webpack.config.js file to our project root? If so, you need to update it to match what we currently have.

**Comment by dreamburst** [comment]
@JeffreyWay Ah of course. Forgot I did that. Thanks!

**Comment by rhyek** [comment]
@JeffreyWay, fyi, I ported the `mix()` helper function to a Laravel 5.1 project of mine with a few changes to address this issue:

```php
function mix($path) {
  static $manifest;
  static $shouldHotReload;
  if (!starts_with($path, '/')) {
    $path = "/{$path}";
  }
  if ($shouldHotReload = file_exists(public_path('hot'))) {
    return new HtmlString("http://localhost:8080{$path}");
  }
  if (!$manifest) {
    if (!file_exists($manifestPath = public_path('mix-manifest.json'))) {
      throw new Exception('The Mix manifest does not exist.');
    }
    $manifest = json_decode(file_get_contents($manifestPath), true);
  }
  if (!array_key_exists($path, $manifest)) {
    throw new Exception(
      "Unable to locate Mix file: {$path}. Please check your ".
      'webpack.mix.js output paths and try again.'
    );
  }
  return new HtmlString(url($manifest[$path]));
}
```
As you can see, what I'm doing is basically checking if the `hot` file exists early and just return the same string sent as the path parameter. This works more than fine for my needs as it doesn't require the manifest file to exist during development.

**Comment by rhyek** [comment]
Though, I think that `http://localhost:8080` should be dynamic since running more that one dev server means different ports, or maybe webpack is configured to use a different one altogether. Maybe the currently used port should be saved to the `hot` file and `mix()` should use that.

**Comment by JeffreyWay** [comment]
We already have a different thread for making the port dynamic. Thanks for the code snippet!

**Comment by rhyek** [comment]
@JeffreyWay I made a pull request (https://github.com/laravel/framework/pull/18088) addressing this. Not sure if it's still needed or what plans you have.
