### ISSUE TITLE
Laravel-mix with WordPress issue with extract()

### ISSUE THREAD

**Issue by therealgilles** [JeffreyWay/laravel-mix#2913]
-   Laravel Mix Version: 6.0.13
-   Node Version (`node -v`): v15.11.0
-   NPM Version (`npm -v`): 7.6.0
-   OS: Debian GNU/Linux 10 (buster)

### Description:
I'm trying to use laravel-mix with WP and when I try to use extract(), I see things getting bundling into (manifest/vendor/app).js but when I include the script in my page, nothing gets executed.

The js/app.js file looks like this:
```
(self["webpackChunk_theme"] = self["webpackChunk_theme"] || []).push([["/js/app"],{
...
]);
```

so I guess it makes sense that nothing happens, but I'm wondering what I'm supposed to add to get the scripts to run.

Thank you for any insight.

**Comment by WalrusSoup** [comment]
This is not specific to WP. Also finding that in non-laravel environments, using extract() causes no JS to be executed at all when landing on the page.

**Comment by thecrypticace** [comment]
There were some issues in old webpack versions. Can you try upgrading your dependencies and seeing if that fixes it? A good number of our tests don't run in a laravel-like environment so that's unlikely to be an issue.

**Comment by WalrusSoup** [comment]
that was it. Not sure which dependency was causing it, but that fixed it. At least it's Friday....

**Comment by therealgilles** [comment]
I don't think I have any dependency to update in my case.

**Comment by therealgilles** [comment]
Oh I spoke too soon. It is working for me too now. The output file looked the same, so I didn't think something had changed.
