### ISSUE TITLE
Spritesmith

### ISSUE THREAD

**Issue by fearrr** [JeffreyWay/laravel-mix#292]
Hi!
How can I get it with spritesmith?

**Comment by JeffreyWay** [comment]
I don't know what that is, but for any custom configuration, you can copy our webpack.config.js file to your project root, and maintain it yourself.

**Comment by rorc** [comment]
@JeffreyWay Spritesmith is a cool plugin to generate image sprites. Will be great to add support by default this plugin by laravel-mix.
