### ISSUE TITLE
Dynamic imports not working

### ISSUE THREAD

**Issue by tomosterlund** [JeffreyWay/laravel-mix#2921]
-   Laravel Mix Version: 4.0.0 (`npm list --depth=0`)
-   Node Version (`node -v`): 14.15.4

### Description:
Whenever I'm trying to use dynamic imports in my Vue-app, the compilation doesn't seem to work anymore. I do not get any errors at compilation, however. The problem only shows once loading the compiled files in the browser and the page doesn't load any JavaScript or CSS anymore. I tried it out with several different versions of Laravel mix, ranging from the newest, down to 4.0.0.

### Steps To Reproduce:
My webpack config:

```
mix.webpackConfig(
	{
		plugins: config_plugins,
		output: {
			publicPath: '/',
			chunkFilename: '[name].js',
		},
		module: {
			rules: [
				{
					test: /\.jsx?$/,
					exclude: /bower_components/,
					use: {
						loader: 'babel-loader',
						options: {
							presets: ['@babel/preset-env'],
							plugins: ['@babel/plugin-syntax-dynamic-import']
						}
					}
				}
			]
		}
	}
);
```
The usage of dynamic imports in the app.js, defining my Vue-app:

```
Vue.component('async-component', (resolve) => {
	import(/* webpackChunkName: 'js/async-component' */ './sites/some-site/Component.vue')
		.then((asyncComponent) => {
			resolve(asyncComponent.default);
		});
});
```

**Comment by JeffreyWay** [comment]
Mix v4 didn't support dynamic imports due, but the latest version - v6 - does. I'm using it my main project without any problems.

**Comment by tomosterlund** [comment]
@JeffreyWay A colleague just updated our project to Laravel mix 6, and now the dynamic imports work like a charm. Thank you for your work.
