### ISSUE TITLE
Build breaks with v6.0.14 and above

### ISSUE THREAD

**Issue by ultimateBusiness** [JeffreyWay/laravel-mix#2924]
-   Laravel Mix Version: v8.35.1
-   Node Version: v15.13.0
-   NPM Version: v7.7.6
-   Yarn: v1.22.10
-   OS: macOS 11.2.3

### Description:
Build (DEV and PROD) breaks with v6.0.14 and above with the following message:

$ yarn run production
yarn run v1.22.10
warning ../../package.json: No license field
$ cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js

✖ Mix
  Compiled with some errors in 15.10s

[webpack-cli] Compilation finished
ERROR in ./resources/js/app.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/xx/xx/xx/resources/js/app.js: Unknown option: .value. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
    at throwUnknownError (/Users/xx/xx/xx/node_modules/@babel/core/lib/config/validation/options.js:124:27)
    at /Users/xx/xx/xx/node_modules/@babel/core/lib/config/validation/options.js:109:5
    at Array.forEach (<anonymous>)
    at validateNested (/Users/xx/xx/xx/node_modules/@babel/core/lib/config/validation/options.js:85:21)
    at validate (/Users/xx/xx/xx/node_modules/@babel/core/lib/config/validation/options.js:76:10)
    at /Users/xx/xx/xx/node_modules/@babel/core/lib/config/full.js:315:36
    at cachedFunction (/Users/xx/xx/xx/node_modules/@babel/core/lib/config/caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/Users/xx/xx/xx/node_modules/gensync/index.js:244:28)
    at sync (/Users/xx/xx/xx/node_modules/gensync/index.js:84:14)

webpack compiled with 1 error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Steps To Reproduce:
Setting the version in the package.json explicitly to v6.0.13 all works fine - when setting another Version above that the build fails with the error above.

**Comment by thecrypticace** [comment]
Could you please provide a reproduction repo? There was some re-working done around babel configuration loading.

**Comment by thecrypticace** [comment]
Also the contents of your .babelrc and babel.config.js files would be helpful

**Comment by ultimateBusiness** [comment]
I have no .babelrc and no babel.config.js - I only have a webpack.mix.js, webpack.config.js, tailwind.config.js and a postcss.config.js - and I have no public repo - and the issue is within all three projects I am working on.

**Comment by thecrypticace** [comment]
I cannot reproduce this on a fresh installation of laravel with or without Jetstream. I need some more details to be able to help here. Can you provide your package.json, webpack.mix.js, and webpack.config.js (if you have one) files?

**Comment by patrickbrouwers** [comment]
Try running `yarn upgrade` (or deleting the node_modules + running `yarn install`) That did the trick for me.

**Comment by thecrypticace** [comment]
@patrickbrouwers To reproduce the issue or to fix it when you ran into the same issue? I tested a clean install from no lock file and no node_modules.

**Comment by ultimateBusiness** [comment]
I have had deleted the node_modules several times, but never thought about the yarn.lock ;-) - that does the trick - now it work's all with the actual version - thx ;-)
