### ISSUE TITLE
Impossible to set options for cssnano in production

### ISSUE THREAD

**Issue by dangelion** [JeffreyWay/laravel-mix#2926]
I have to disable `postcss-calc` because in production makes wrong calc (see the reported bugs at the end). 
That library, I think, is used by cssnano in Laravel Mix, right?
To do this I usually add `calc: false` in `postcss.config.js` file, like this:

```
const cssnanoConfig = {
  preset: ['default', { discardComments: { removeAll: true }, calc: false }],
};

module.exports = ({ file, options }) => {
  return {
    parser: options.enabled.optimize ? 'postcss-safe-parser' : undefined,
    plugins: {
      autoprefixer: true,
      cssnano: options.enabled.optimize ? cssnanoConfig : false,
    },
  };
};
```

But tried also this:

```
mix
  .sass('resources/styles/app.scss', 'styles')
  .sass('resources/styles/editor.scss', 'styles')
  .options({
    postCss: [
      require('cssnano')({
        preset: ['default', {discardComments: {removeAll: true}, calc: false}],
      }),
    ],
    processCssUrls: false,
  });
```

No solutions work and give no error!
How can do that?

Or how can remove `postcss-calc` at all?

> Bug: cssnano -> postcss-calc compiling in production
> doesn't keep parenthesis inside some calc() with css variables

> https://github.com/postcss/postcss-calc/issues/115
https://github.com/postcss/postcss-calc/issues/107
https://github.com/postcss/postcss-calc/issues/91
https://github.com/postcss/postcss-calc/issues/77
https://github.com/postcss/postcss-calc/pull/116
https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/110
https://github.com/cssnano/cssnano/issues/628

**Comment by loilo** [comment]
For others who pass by (like me): Mix indeed allows to configure cssnano via [its options](https://laravel-mix.com/docs/4.0/options):

```js
mix.options({
  cssNano: {
    // disable postcss-calc
    calc: false
  }
})
```

**Comment by sebastianJofre** [comment]
there are some possible solutions:

- Check the version of cssnano and make sure it is compatible with the version of postcss-calc being used.
- Update both plugins to the latest versions and check if the issue persists.
-Disable cssnano or postcss-calc temporarily and check if the error is resolved.
- Check for conflicts with other PostCSS plugins and, if necessary, update or disable them.
