### ISSUE TITLE
<style> in Vue component is unexpectly removed in Laravel Mix v6.0.16

### ISSUE THREAD

**Issue by danielbachhuber** [JeffreyWay/laravel-mix#2928]
-   Laravel Mix Version: 6.0.16 (`npm list --depth=0`)
-   Node Version (`node -v`): v14.15.4
-   NPM Version (`npm -v`): v6.14.11

### Description:

In Laravel Mix v6.0.16, the CSS within `<style>` in a Vue component isn't included in the built stylesheet.

See this Gist as an example: https://gist.github.com/danielbachhuber/5a8b8d6b74072a9da9d5f83dda3f722a

The CSS within `<style>` is included as expected in Laravel Mix v6.0.13.

**Comment by roko91** [comment]
This sounds very similar to my issue, they may be related:
https://github.com/JeffreyWay/laravel-mix/issues/2927

**Comment by thecrypticace** [comment]
Can you provide a reproduction repository? I'm unable to reproduce this problem.

For reference, to extract styles, I'm using the below:
```
mix.vue({ version: 2, extractStyles: true }) // can also be `version: 3` if you're using Vue 3
```

**Comment by blood72** [comment]
> Can you provide a reproduction repository? I'm unable to reproduce this problem.
> 
> For reference, to extract styles, I'm using the below:
> 
> ```
> mix.vue({ version: 2, extractStyles: true }) // can also be `version: 3` if you're using Vue 3
> ```

I was suffering from the same problem, and it's completely solved. thank you @thecrypticace.
Perhaps the reason is that it worked well in previous versions (in my case 6.0.10) without specifying `extractStyle`.

**Comment by thecrypticace** [comment]
Nah, I tested previous versions and the current version and they inject style tags into `<head>` if you don't specify extractStyle — which is as expected.

**Comment by lephro** [comment]
My css styles also appear to be gone after upgrading from 6.0.13.
Iam using vue + vuetify (with treechakeing) + cssnano

Setting extractStyles true/false didn't work.

**Comment by danielbachhuber** [comment]
Setting `extractStyles: true` doesn't work for me either.

Here's my `webpack.mix.js`

```
const mix = require('laravel-mix');

require('laravel-mix-tailwind');

mix.sass('assets/scss/admin.scss', 'assets/dist/');
mix.sass('assets/scss/editor.scss', 'assets/dist/');
mix.sass('assets/scss/style.scss', 'assets/dist/');

mix.js('assets/js/src/app.js', 'assets/dist').vue({ version: 2, extractStyles: true });

mix.tailwind('./tailwind.config.js');
```

**Comment by danielbachhuber** [comment]
In my testing, the behavior changed in v6.0.14. My bet would be this changeset: 2056b680dc77ccfd701a0e4a59126b836ecb687b

**Comment by thecrypticace** [comment]
@danielbachhuber Can you reproduce this in a fresh project?

**Comment by danielbachhuber** [comment]
@thecrypticace I'll see what I can do. One thing worth noting, that might be relevant, is that my `assets/dist/app.js` is loaded into WordPress with a `<script src="">` tag. When you mention _I tested previous versions and the current version and they inject style tags into `<head>`_ above, the style tags could only be injected into `<head>` if they were added with client-side JavaScript. We don't have any SSR Vue.

**Comment by thecrypticace** [comment]
I'm not testing SSR. When using `style-loader` and `vue-style-loader` styles imported in JS and in Vue `<style>` tags are bundled in the javascript and are subsequently inserted into `<head>` tags on bundle load / initialization.

**Comment by danielbachhuber** [comment]
@thecrypticace Ok, makes sense.

I tried recreating the issue in a [fresh repository](https://github.com/danielbachhuber/laravel-mix-2928/), but was unable to reproduce.

I thought it could be a conflict between Laravel Mix and Tailwind/PostCSS, or Laravel Mix and Tailwind's PurgeCSS implementation. Neither seem to be the case.

@lephro Do you have any ideas that might reproduce the issue?

**Comment by thecrypticace** [comment]
@danielbachhuber Does a `yarn upgrade` in your existing project that exhibits the problems fix the issue for you by chance?

**Comment by danielbachhuber** [comment]
@thecrypticace I'm using npm... `npm update` only brings me to the latest version of Laravel Mix

**Comment by roko91** [comment]
Here is how I resolved similar issue:
https://github.com/JeffreyWay/laravel-mix/issues/2927#issuecomment-816734253

**Comment by maxxscho** [comment]
Same here. Updating from `6.0.13` to `6.0.16` and my styles from Vue Single File components are gone.
`extractStyle: true|false` doesn't have an effect.

**Comment by danielbachhuber** [comment]
@thecrypticace Any luck identifying the issue or a workaround?

**Comment by thecrypticace** [comment]
None yet. At present I really need some kind of reproduction.

@danielbachhuber Is it possible for you to share the project that you experience the issue with? (or a zip file of it?)

**Comment by danielbachhuber** [comment]
@thecrypticace Sure, do you want to email me at the address on my GitHub profile and I'll send you a ZIP?

**Comment by thecrypticace** [comment]
Yeah that's good. I've sent you an email.

**Comment by maxxscho** [comment]
It seems this error is gone - I'm on `6.0.19`.
Didn't change anything else.

Can anyone confirm this?

**Comment by danielbachhuber** [comment]
I can confirm the issue appears to be fixed in `6.0.19`. It's not clear why!

@thecrypticace Were you able to track down the problem?

**Comment by thecrypticace** [comment]
So we haven't released the fix yet that reverts the vue-style-loader change so it's not something we did. 👀

**Comment by danielbachhuber** [comment]
Weird!

**Comment by Krisell** [comment]
The problem remains for us in `6.0.19`.

**Comment by danielbachhuber** [comment]
@thecrypticace You've reverted but it's not released yet?

Also, out of curiosity, what was the vue-style-loader change for in the first place?

**Comment by thecrypticace** [comment]
@danielbachhuber Right.

It allows Vue SFC styles in the shadow dom + some other stuff detailed in the readme: https://github.com/vuejs/vue-style-loader#readme

**Comment by thecrypticace** [comment]
I've decided to make the vue-style-loader bit opt in so this shouldn't be a problem again.

**Comment by Krisell** [comment]
Running `npm update` did indeed resolve the issue, thanks! I don't know exactly what dependency required update, and I don't quite understand how this works. Shouldn't nested node_modules folders be created if different dependencies require different, incompatible, versions of sub-dependencies?

**Comment by thecrypticace** [comment]
It does but incompatible is defined as non-matching version constraints.
