### ISSUE TITLE
npm run hot

### ISSUE THREAD

**Issue by tiagomatosweb** [JeffreyWay/laravel-mix#293]
I have followed the documentation in [here](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/hot-module-replacement.md)

I could setup well, when I change any .vue file the browser is refreshed. However, when I change .scss file the browser doen't refresh itself.

I can see in the console some logs like so

[WDS] Hot Module Replacement enabled.
```
2app.js:23940 [WDS] App updated. Recompiling...
app.js:23940 [WDS] App hot update...

```
however the page is not being refreshed with .scss changes.

Any idea?

**Comment by JeffreyWay** [comment]
.scss files aren't included right now with HMR. It would only apply to Sass that you add directly to your .vue file.

**Comment by tiagomatosweb** [comment]
I would appreciate if this topic is updated once HMR supports .scss files to be auto updated. tks
