### ISSUE TITLE
No option to use custom certificates for the dev server

### ISSUE THREAD

**Issue by ERROPiX** [JeffreyWay/laravel-mix#2933]
- Laravel Mix Version  6.0.16
- Node Version 12.18.0
- NPM Version 6.14.4
- OS: Windows 10

### Description:

Prior to Laravel Mix 6, there was an option to add custom SSL certificate to use with the hot module reloading on HTTPS sites.
The documentation for version 5 which include this option is [here](https://laravel-mix.com/docs/5.0/hot-module-replacement#usage-on-https)
But since the old webpack-dev-server command has been replaced with the new mix for NPM scripts, I can't make it to work.
Also, this is not mentioned in the update section of the documentation.

**Comment by tbruckmaier** [comment]
I've got it to work like this

```js
// webpack.mix.js
mix
    .options({
        hmrOptions: {
            https: true,
        },
    })
    .webpackConfig({
        devServer: {
            https: {
                key: fs.existsSync("/etc/certs/key.pem") ? fs.readFileSync("/etc/certs/key.pem") : null,
                cert: fs.existsSync("/etc/certs/cert.pem") ? fs.readFileSync("/etc/certs/cert.pem") : null,
            },
        },
    });
```

Commands in `package.json` can stay the same: 

```
{

    "scripts": {
        "hot": "mix watch --hot",
        ...
    },
    ...
}
```

**Comment by ERROPiX** [comment]
@tbruckmaier I tried it but with no luck, I am using Windows not Linux.

**Comment by ERROPiX** [comment]
@JeffreyWay can you please look at this issue?

**Comment by ERROPiX** [comment]
@tbruckmaier I solved this issue by providing an object for the `hmrOptions.https` mix option:

```js
mix.options({
    hmrOptions: {
        https: {
            key: 'resources/ssl/key.pem',
            cert: 'resources/ssl/cert.pem',
            cacert: 'resources/ssl/ca.pem',
        },
        host: 'localhost',
        port: 8080,
    }
});
```

No need to use the FS methods, I just put a raw string for the relative path to the certificate files.

**Comment by alexkuc** [comment]
As of May 2022, the following has worked for me:

```js
.webpackConfig({
  devServer: {
    server: {
      type: 'https',
      options: {
        cert: process.env.MIX_SSL_CERT,
        key: process.env.MIX_SSL_KEY,
      },
    },
  },
})
```

Env vars come [.env file](https://laravel.com/docs/9.x/mix#environment-variables)
