### ISSUE TITLE
Ability to use `mix` in a non-interactive way?

### ISSUE THREAD

**Issue by stephendolan** [JeffreyWay/laravel-mix#2936]
-   Laravel Mix Version: v6.0.16
-   Node Version: v14.7.0
-   Yarn Version: v1.22.5
-   OS: Mac OSX Big Sur, v11.2.3

### Description:

Hey there! We use (and love) Laravel Mix in the [Lucky](https://luckyframework.org) framework for Crystal. We actually check for a `manifest.json` file at compile-time to help guarantee that assets you're requesting exist, which is really neat!

To that end, we have a [`script/setup`](https://github.com/luckyframework/lucky_cli/blob/master/src/web_app_skeleton/script/setup.ecr#L18-L19) Bash script that initializes your app and generates the `manifest.json`. Recently, running only `mix` seems to have started blocking the terminal for input, meaning that we could no longer use it in a Bash script or CI context.

We're thinking that the solution will be to simply run `yarn prod` (a wrapper script for `mix --production`), but it does seem a bit weird to run a production compilation in a development/CI environment just to get the manifest file.

Is there a way to run `mix` without blocking on input, or to generate only the manifest file?

### Steps To Reproduce:

- Run `mix` in a non-interactive environment (like GitHub actions)
- Note that the `mix` command causes the workflow to hang

[Here is the workflow on our website where we noticed the issue](https://github.com/luckyframework/website/runs/2371138380?check_suite_focus=true)

**Comment by thecrypticace** [comment]
Mix does not wait for input. You are using the in-preview Tailwind JIT engine which, by default, starts a watcher when NODE_ENV=development. To fix this set the TAILWIND_MODE=build env var.

**Comment by stephendolan** [comment]
🤦  Thanks, @thecrypticace!

**Comment by thecrypticace** [comment]
Happy to help!

**Comment by shmdesign** [comment]
Hi @thecrypticace. I am not sure this is the same issue but when I launch ```npm run watch```, it still starts with firing twice. I am using ```mix 6.0.19``` and ```tailwindcss 2.1.1```. 

Those are my npm scripts:
```
"scripts": {
        "dev": "npm run development",
        "development": "TAILWIND_MODE=build mix",
        "watch": "npm run development watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
 },
```

Any idea how can I fix this?

Thanks
