### ISSUE TITLE
Using webpack-obfuscator with mix (what is the bundle name of vendor.js and manifest.js)

### ISSUE THREAD

**Issue by Personeco** [JeffreyWay/laravel-mix#2938]
-   Laravel Mix Version: 6.0.16 (`npm list --depth=0`)
-   Node Version (`node -v`): 14.15.4
-   NPM Version (`npm -v`): 7.5.2
-   OS: Windows 10

### Description:
Hello,

I would like to obfuscate my own code with webpack-obfuscator, however I don't want to obfuscate the vendor libraries.
I use mix.extract() to split the code. 
When I use webpack-obfuscator I can exclude bundles as stated on their description

> excludes (plugin only)
Bundle name is output file name after webpack compilation. With multiple webpack entries you can set bundle name in output object with aliases [name] or [id].

As stated [here](https://github.com/javascript-obfuscator/webpack-obfuscator#excludes-plugin-only)

This does not work, the vendor.js and manifest.js are obfuscated too. I also use mix.version(). I don't understand mix - webpack internals enough to figure this out on my own, but for someone who understands this it might be an easy problem. Which filenames to I have to input there to exclude vendor.js and manifest.js?

### Steps To Reproduce:
This is my webpack.mix.js file:

```
const mix = require('laravel-mix');
const webpack = require('webpack')
const tailwindcss = require('tailwindcss');
const JavaScriptObfuscator = require('webpack-obfuscator');

mix.disableNotifications();

mix.webpackConfig({
    plugins: [
        new webpack.DefinePlugin({
            __VUE_OPTIONS_API__: true,
            __VUE_PROD_DEVTOOLS__: false,
        }),
    ],
})

if (mix.inProduction()) {
    mix.version();
    mix.extract();
    mix.webpackConfig({
        plugins: [
            new JavaScriptObfuscator ({
                rotateUnicodeArray: true
            }, ['vendor.js', 'manifest.js'])
        ],
    });
} else {
    mix.sourceMaps();
}


mix.js('resources/js/app.js', 'public/js').vue();

mix.sass(
    'resources/sass/app.scss',
    {},
    [tailwindcss('./tailwind.config.js')]
).options({
    processCssUrls: false,
})
```

**Comment by thecrypticace** [comment]
From a quick glance at the plugin code I think you could use `js/vendor.js` and `js/manifest.js` as your filenames to exclude those. I'm closing as this is not a Mix issue. If you need further help I'd ask on the Laracasts forums or StackOverflow.
