### ISSUE TITLE
Upgrading mix to 6.0.16 [webpack-cli] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by zerocarbthirty** [JeffreyWay/laravel-mix#2942]
-   Laravel Mix Version: 6.0.16 (`npm list --depth=0`)
-   Node Version (`node -v`): 14.16.1
-   NPM Version (`npm -v`): 7.10.0
-   OS: Ubuntu 16.04.7

### Description:

Upgrading app from mix 2.1.14 to 6.0.16 is not working. (while upgrading from Laravel 5.7 to 8.0)

### Steps To Reproduce:

This is my package.json:

{
    "private": true,
    "scripts": {
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "production": "mix --production"
    },
    "devDependencies": {
        "@fortawesome/fontawesome-pro": "^5.15.2",
        "axios": "^0.21.1",
        "bootstrap": "^4.6.0",
        "cross-env": "^5.1",
        "jquery": "^3.5.1",
        "laravel-mix": "^6.0.16",
        "lodash": "^4.17.21",
        "popper.js": "^1.16.1",
        "sass": "^1.32.11",
        "vue": "^2.5.7"
    },
    "dependencies": {
        "mobile-menu": "^2.0.8",
        "postcss": "^8.2.10",
        "strip-ansi": "^7.0.0"
    }
}

npm install laravel-mix@latest
changing the scripts in package.json as suggested in the documentation
npm run production':

[webpack-cli] Error: Cannot find module 'strip-ansi'

So naturally I run npm install strip-ansi and re-run npm run production.

Then I get:

[webpack-cli] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /fiveeight/node_modules/strip-ansi/index.js require() of ES modules is not supported.

Anyone know what might be happening? Also anyone know why npm didn't just satisfy it's need of strip-ansi? this upgrade has been a little odd.

**Comment by thecrypticace** [comment]
So we're using `strip-ansi` but we didn't declare it in our dependencies (oops my bad) and you're including the newest version of `strip-ansi` (7.0.0) which moved to ES Modules which doesn't work with `require()`. In the short term you can change your dependency for it to: `"strip-ansi": "^6.0.0"` and you should be golden.

We should still push out a release fixing this on our side as well.

**Comment by thecrypticace** [comment]
New release has been tagged!

**Comment by zerocarbthirty** [comment]
Just fyi something else broke after fixing that

dev@contentdistro:/fiveeight$ npm install

removed 6 packages, changed 1 package, and audited 1133 packages in 1s

found 0 vulnerabilities
xlhost-dev@contentdistro:/fiveeight$ npm run production

> production
> mix --production

        Additional dependencies must be installed. This will only take a moment.
 
        Running: npm install sass-loader@^11.0.1 resolve-url-loader@^3.1.2 --save-dev --legacy-peer-deps
 
        Finished. Please run Mix again.
 
dev@contentdistro://fiveeight$ npm run production

> production
> mix --production

sh: 1: mix: not found

**Comment by zerocarbthirty** [comment]
Just fyi something else broke after fixing that

dev@contentdistro:/fiveeight$ npm install

removed 6 packages, changed 1 package, and audited 1133 packages in 1s

found 0 vulnerabilities
dev@contentdistro:/fiveeight$ npm run production

production
mix --production

    Additional dependencies must be installed. This will only take a moment.

    Running: npm install sass-loader@^11.0.1 resolve-url-loader@^3.1.2 --save-dev --legacy-peer-deps

    Finished. Please run Mix again.
dev@contentdistro://fiveeight$ npm run production

production
mix --production

sh: 1: mix: not found

**Comment by zerocarbthirty** [comment]
I got around that new problem by reinstalling mix with npm install laravel-mix@latest.

Now: 

> production
> mix --production
✖ Mix
  Compiled with some errors in 3.06s

ERROR in /js/app
Module not found: Error: Can't resolve 'css-loader'

Is that another unlisted dependency?

**Comment by zerocarbthirty** [comment]
Yep, npm install css-loader fixed that.... how are we getting to release with hidden dependencies?

**Comment by thecrypticace** [comment]
CSS loader is definitely included in our dependency list (if it wasn't a _lot_ of things would break). That seems like a problem with npm?

https://github.com/JeffreyWay/laravel-mix/blob/34bbcc5553f28a4a20f1d295ab0a1ae35502acaf/package.json#L69

**Comment by thecrypticace** [comment]
I'd try deleting your `package-lock.json` file and node_modules and installing from scratch.
