### ISSUE TITLE
Vue 3 Options API not working

### ISSUE THREAD

**Issue by nonamez** [JeffreyWay/laravel-mix#2949]
-   Laravel Mix Version: 6.0.18
-   Node Version (`node -v`): v15.14.0
-   NPM Version (`npm -v`): 7.7.6
-   OS: BigSur M1

### Description:

Vue 3 Class/Options API (old V2 way) is not working after Laravel-mix. If i use the new composition api style - everything works just fine.

### Steps To Reproduce:

In example below the alert is never fired after mix. Only if vue is used directly without mix.

### Not working
```
let Vue = require('vue');

console.log(Vue.version);

const app = Vue.createApp({
	created() {
		alert('created');
	}
});

app.mount('#dashboard');
```

`<div id="dashboard" v-cloak></div>`

`mix.js('resources/js/dashboard/app.js', 'public/js/dashboard.js').vue();`

### Working

```
<body>
	<div id="dashboard" v-cloak></div>
	<script src="https://unpkg.com/vue@next"></script>
	<script>
		console.log(Vue.version);

		const app = Vue.createApp({
			created() {
				alert('created');
			}
		});

		app.mount('#dashboard');
	</script>
	{{-- <script src="{{ mix('js/dashboard.js') }}" ></script> --}}
</body>
```

The version of both Vue is same: 3.0.11

**Comment by mrleblanc101** [comment]
Same
