### ISSUE TITLE
This dependency was not found in node_modules

### ISSUE THREAD

**Issue by wiisg** [JeffreyWay/laravel-mix#295]
I am using laravel 5.3 and followed the laracast learn vue 2 laravel-mix tutorial. But encountered following error when running 'npm run dev':

 ERROR  Failed to compile with 1 errors

This dependency was not found in node_modules:

* C:\xampp\htdocs\project1\resources\assets\js\main.js

Did you forget to run npm install --save for it?
            Asset      Size  Chunks             Chunk Names
      /js/main.js   1.55 kB       0  [emitted]  /js/main
mix-manifest.json  34 bytes          [emitted]

**Comment by QWp6t** [comment]
Sounds like `C:\xampp\htdocs\project1\resources\assets\js\main.js` doesn't exist.

**Comment by JeffreyWay** [comment]
@wiisg Can you show me your webpack.mix.js? It can't find that file for some reason, so now it's looking in node_modules.

**Comment by mwei0210** [comment]
It does exist in designated path.

webpack.mix.js in my project root:
`let mix = require('laravel-mix');`
`mix.js('resources/assets/js/main.js', 'public/js');`

**Comment by wiisg** [comment]
It does exist in designated path.

webpack.mix.js in my project root:
```
let mix = require('laravel-mix');
mix.js('resources/assets/js/main.js', 'public/js');
```

**Comment by lewishowles** [comment]
Chiming in to say I'm also having this issue. *(I never know whether  doing so is helpful or not, but hey)*

- Brand new project
- Delete the default app.js / app.css
- Add some default files (global.scss / main.js)
- Update webpack.mix.js

Same error as above - can't find the files, but they're definitely there.

e.g. 
![image](https://cloud.githubusercontent.com/assets/1140753/22667740/fbe40ec2-ecb5-11e6-8192-791427c93cef.png)

![image](https://cloud.githubusercontent.com/assets/1140753/22667750/0da63d6a-ecb6-11e6-97d5-1aee42fb93b8.png)

**Comment by wiisg** [comment]
Nope remove and rerun `npm install` doesn't fix my issue, still showing the same error.. helpp

**Comment by JeffreyWay** [comment]
What version of Node and non do you have installed?

**Comment by wiisg** [comment]
I am using v6.95.5..

**Comment by JeffreyWay** [comment]
And npm?

**Comment by wiisg** [comment]
just tried updating npm to 4.1.2, remove my node_modules folder, rerunning `npm install`. Still got the same error.. awww

**Comment by lewishowles** [comment]
Try updating node to 7.4.0, deleting node_modules and running again. That's what did it for me.

**Comment by mwei0210** [comment]
Nope.. not working either..

**Comment by mwei0210** [comment]
OMG i'm so happyy it worked. So the problem was because of a package i use vuetable-2 by ratiw. I guess i  previously installed it incorrectly? By copying all dependency from its git source code package.json into my local package.json when i was using gulp (gulp worked btw).

**Comment by illiamaster** [comment]
How did you do this? Can you explain it again?
