### ISSUE TITLE
trouble in  `npx mix watch --hot`

### ISSUE THREAD

**Issue by marol1210** [JeffreyWay/laravel-mix#2951]
-   Laravel Mix Version: **laravel-mix@6.0.10**
-   Node Version (`node -v`):  **v14.16.0**
-   NPM Version (`npm -v`):  **6.14.11**
-   OS:  windows

### Description:
run cli command  `npx mix watch --hot` ,  console show error .  
thanks advance for help.

```
[webpack-cli] webpack Dev Server Invalid Options

options should NOT have additional properties
options should NOT have additional properties
options should NOT have additional properties
options should NOT have additional properties
options should NOT have additional properties
```

### Steps To Reproduce:
1. install laravel-mix@6.0.10
2. modify webpack.mix.js in PROJECT_ROOT
```
let mix = require('laravel-mix');
let htmlWebPlugin = require('html-webpack-plugin');
let path = require('path');

mix.alias({'@': 'src-inertiajs'}).setPublicPath('./dist')

mix.webpackConfig({
	  	mode: 'development',
		entry:__dirname+"/src-inertiajs/app.js",
		    devServer: {
		      contentBase: './dist',
		      hot: true,
		    },
	    output: { 
			path: path.resolve(__dirname, 'dist'),
			chunkFilename: 'dist/avored/[name].js?id=[chunkhash]' ,
			clean:true
		},
		plugins:[
			new htmlWebPlugin(
				{
					title:"Demo",
					scriptLoading:"blocking"
				}
			)
		]
  })
  .vue()

```

**Comment by thecrypticace** [comment]
`contentBase` is not a valid option for `devServer` in webpack-dev-server v4. Use the `static` option instead. Read the notes here: https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0

**Comment by mylesdc** [comment]
> `contentBase` is not a valid option for `devServer` in webpack-dev-server v4. Use the `static` option instead. Read the notes here: https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0

This doesn't fix the problem for me.

**Comment by sertn** [comment]
I'm dealing with this issue too. I still haven't been able to find a solution.
