### ISSUE TITLE
Laravel Mix 6.0.18 yarn run dev error  

### ISSUE THREAD

**Issue by 957651480** [JeffreyWay/laravel-mix#2959]
-   Laravel Mix Version: 6.0.18 (`npm list --depth=0`)
-   Node Version (`node -v`):v14.15.0
-   NPM Version (`npm -v`):6.14.8
-   OS:

### Description:
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.plugins[11] should be one of these:
   object { apply, … } | function
   -> Plugin of type object or instanceof Function
   Details:
    * configuration.plugins[11] should be an object.
      -> Plugin instance
    * configuration.plugins[11] should be an instance of function
      -> Function acting as plugin
 - configuration.stats has an unknown property 'preset'. These properties are valid:
   object { all?, assets?, assetsSort?, builtAt?, cached?, cachedAssets?, children?, chunkGroups?, chunkModules?, chunkOrigins?, chunks?, chunksSort?, colors?, context?, depth?, entrypoints?, env?, errorDetails?, errors?, exclude?,
excludeAssets?, excludeModules?, hash?, logging?, loggingDebug?, loggingTrace?, maxModules?, moduleAssets?, moduleTrace?, modules?, modulesSort?, nestedModules?, optimizationBailout?, outputPath?, performance?, providedExports?, pub
licPath?, reasons?, source?, timings?, usedExports?, version?, warnings?, warningsFilter? }

### Steps To Reproduce:
yarn run dev

**Comment by thecrypticace** [comment]
This is likely caused by invalid / incompatible dependencies. Please provide a gist of your webpack.mix.js, package.json, and package-lock.json / yarn.lock files.

**Comment by 957651480** [comment]
webpack.config.js 
const path = require('path');
const mix = require('laravel-mix');
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const createThemeColorReplacerPlugin = require('./resources/backend/config/plugin.config')
function resolve(dir) {
  return path.join(
    __dirname,
    '/resources/backend',
    dir
  );
}
const isProd = process.env.NODE_ENV === 'production'

const rawArgv = process.argv.slice(2);
const report = rawArgv.includes('--report');
let plugins = [];
if (report) {
  plugins.push(new BundleAnalyzerPlugin({
    openAnalyzer: true,
  }));
}
if(!isProd){
  plugins.push(createThemeColorReplacerPlugin);
}
module.exports = {
  output: { chunkFilename: 'js/[name].js?id=[chunkhash]' },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      vue$: 'vue/dist/vue.esm.js',
      '@': path.resolve(__dirname, 'resources/backend'),
      '@assets': path.resolve(__dirname, 'resources/backend/assets'),
      '@comp': path.resolve(__dirname, 'resources/backend/components'),
      '@views': path.resolve(__dirname, 'resources/backend/views'),
      '@layout': path.resolve(__dirname, 'resources/backend/layout'),
      '@static': path.resolve(__dirname, 'resources/backend/static'),
    },
  },
  module: {
    rules: [
      {
        test: /\.svg$/,
        loader: 'babel-loader',
        include: [resolve('assets')],
      },
      {
        test: /\.svg$/,
        loader: 'vue-svg-icon-loader',
        include: [resolve('assets')],
        options: {
          symbolId: 'icon-[name]',
        },
      },
      {
        test: /\.less$/,
        loader: 'less-loader',
        options: {
          javascriptEnabled: true
        }
      },
    ],
  },
  plugins: plugins,
};

webpack.mix.js
const mix = require('laravel-mix');
const path = require('path');
const config = require('./webpack.config.js');
//require('laravel-mix-eslint');

function resolve(dir) {
    return path.join(
        __dirname,
        '/resources/backend',
        dir
    );
}

Mix.listen('configReady', webpackConfig => {
    // Add "svg" to image loader test
    const imageLoaderConfig = webpackConfig.module.rules.find(
        rule =>
            String(rule.test) ===
            String(/(\.(png|jpe?g|gif|webp)$|^((?!font).)*\.svg$)/)
    );
    imageLoaderConfig.exclude = resolve('assets');
});

mix.webpackConfig(config);

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */
//mix
//    .js('node_modules/bootstrap/dist/js/bootstrap.min.js', 'resources/js/vendor')
//    .sass('resources/scss/theme/theme.scss', 'resources/css')
//    .options({
//        processCssUrls: false
//    });

// Full API
// mix.js(src, output);
// mix.react(src, output); <-- Identical to mix.js(), but registers React Babel compilation.
// mix.preact(src, output); <-- Identical to mix.js(), but registers Preact compilation.
// mix.coffee(src, output); <-- Identical to mix.js(), but registers CoffeeScript compilation.
// mix.ts(src, output); <-- TypeScript support. Requires tsconfig.json to exist in the same folder as webpack.mix.js
// mix.extract(vendorLibs);
// mix.sass(src, output);
// mix.less(src, output);
// mix.stylus(src, output);
// mix.postCss(src, output, [require('postcss-some-plugin')()]);
// mix.browserSync('my-site.test');
// mix.combine(files, destination);
// mix.babel(files, destination); <-- Identical to mix.combine(), but also includes Babel compilation.
// mix.copy(from, to);
// mix.copyDirectory(fromDir, toDir);
// mix.minify(file);
// mix.sourceMaps(); // Enable sourcemaps
// mix.version(); // Enable versioning.
// mix.disableNotifications();
// mix.setPublicPath('path/to/public');
// mix.setResourceRoot('prefix/for/resource/locators');
// mix.autoload({}); <-- Will be passed to Webpack's ProvidePlugin.
// mix.webpackConfig({}); <-- Override webpack.config.js, without editing the file directly.
// mix.babelConfig({}); <-- Merge extra Babel configuration (plugins, etc.) with Mix's default.
// mix.then(function () {}) <-- Will be triggered each time Webpack finishes building.
// mix.extend(name, handler) <-- Extend Mix's API with your own components.
// mix.options({
//   extractVueStyles: false, // Extract .vue component styling to file, rather than inline.
//   globalVueStyles: file, // Variables file to be imported in every component.
//   processCssUrls: true, // Process/optimize relative stylesheet url()'s. Set to false, if you don't want them touched.
//   purifyCss: false, // Remove unused CSS selectors.
//   terser: {}, // Terser-specific options. https://github.com/webpack-contrib/terser-webpack-plugin#options
//   postCss: [] // Post-CSS options: https://github.com/postcss/postcss/blob/master/docs/plugins.md
// });

mix.options({
    //extractVueStyles: true,
    //globalVueStyles: __dirname+'/resources/backend/styles/element-variables.scss',
})
mix.js('resources/backend/main.js', 'public/backend/js')

//todo 不要提取,否则npm run prod css 打包出来是空文件
mix.js('resources/frontend/frontend.js', 'public/js')
    .sass('resources/frontend/sass/frontend.scss', 'public/css');


if (mix.inProduction()) {
    mix.version();
} else {

        //mix.eslint();

    // Development settings
    mix
        .sourceMaps()
        .webpackConfig({
            devtool: 'eval-source-map', // Fastest for development
        });
}
package.json
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production",
        "report": "mix --production -- --env --report"
    },
    "dependencies": {
        "@ant-design-vue/pro-layout": "^0.3.4",
        "@antv/data-set": "^0.10.2",
        "ant-design-vue": "^1.6.2",
        "axios": "^0.19.0",
        "bootstrap": "^4.0.0",
        "core-js": "^3.1.2",
        "enquire.js": "^2.1.6",
        "jquery": "^3.2",
        "lodash.clonedeep": "^4.5.0",
        "lodash.get": "^4.4.2",
        "lodash.pick": "^4.4.0",
        "md5": "^2.2.1",
        "mockjs2": "1.0.8",
        "moment": "^2.24.0",
        "nprogress": "^0.2.0",
        "popper.js": "^1.12",
        "sass": "^1.26.11",
        "sass-loader": "8.*",
        "store": "^2.0.12",
        "viser-vue": "^2.4.6",
        "vue": "^2.6.10",
        "vue-clipboard2": "^0.2.1",
        "vue-cropper": "0.4.9",
        "vue-i18n": "^8.17.4",
        "vue-quill-editor": "^3.0.6",
        "vue-router": "^3.1.2",
        "vue-svg-component-runtime": "^1.0.1",
        "vuex": "^3.1.1",
        "wangeditor": "^3.1.1"
    },
    "devDependencies": {
        "@ant-design/colors": "^3.2.1",
        "@vue/cli-plugin-babel": "^4.0.4",
        "@vue/cli-plugin-eslint": "^4.0.4",
        "@vue/cli-plugin-router": "^4.0.4",
        "@vue/cli-plugin-vuex": "^4.0.4",
        "@vue/cli-service": "^4.0.4",
        "@vue/eslint-config-standard": "^4.0.0",
        "babel-eslint": "^10.0.1",
        "babel-plugin-import": "^1.12.2",
        "babel-plugin-transform-remove-console": "^6.9.4",
        "cross-env": "^7.0",
        "eslint": "^5.16.0",
        "eslint-plugin-html": "^5.0.0",
        "eslint-plugin-vue": "^5.2.3",
        "git-revision-webpack-plugin": "^3.0.6",
        "laravel-mix": "^6.0.6",
        "less": "^3.0.4",
        "less-loader": "^5.0.0",
        "resolve-url-loader": "^3.1.0",
        "sass": "^1.26.11",
        "sass-loader": "^8.0.2",
        "vue-svg-icon-loader": "^2.1.1",
        "vue-template-compiler": "^2.6.10",
        "webpack-bundle-analyzer": "^4.4.1",
        "webpack-cli": "^4.6.0",
        "webpack-theme-color-replacer": "^1.3.12"
    }
}
