### ISSUE TITLE
Fix 5.0.9 security errors thru dependencies

### ISSUE THREAD

**Issue by juhasev** [JeffreyWay/laravel-mix#2962]
npm fix audit

node_modules/ssri
  cacache  10.0.4 - 11.0.0 || 13.0.0 - 14.0.0
  Depends on vulnerable versions of ssri
  node_modules/cacache
    terser-webpack-plugin  2.1.1 - 2.3.8
    Depends on vulnerable versions of cacache
    node_modules/terser-webpack-plugin
      laravel-mix  5.0.1 - 6.0.0-beta.17
      Depends on vulnerable versions of terser-webpack-plugin
      node_modules/laravel-mix

We haven't been able to  upgrade to mix 6 simply because there appears to be no way to get Vuetify working at the same time. It would be good if Mix 6 was tested against it as it is becoming defacto vue material design framework.

**Comment by taisph** [comment]
Duplicate of #2952.

**Comment by thecrypticace** [comment]
Closing in favor of #2952. I've posted a comment there.
