### ISSUE TITLE
Random ChunkLoadError

### ISSUE THREAD

**Issue by CaptainCannabis** [JeffreyWay/laravel-mix#2963]
-   Laravel Mix Version: 6.0.18
-   Node Version: 14.15.3
-   NPM Version: 7.11.2
-   OS: Ubuntu 20.04.2 LTS

Packages that might be interesting
`
├── axios@0.21.1
├── clean-webpack-plugin@4.0.0-alpha.0
├── cross-env@7.0.3
├── deepmerge@4.2.2
├── easy-autocomplete@1.3.5
├── laravel-echo@1.10.0
├── laravel-mix-clean@0.1.0
├── laravel-mix-merge-manifest@2.0.0
├── laravel-mix@6.0.18
├── material-icons@0.5.5
├── perfect-scrollbar-latest@1.5.2
├── postcss@8.2.14
├── vue@2.6.12
├── vuex@3.6.2
└── webpack@5.36.2
`

### Description:
I am running my app which worked before with laravel-mix ^5.0.1 after i upgraded to v6. In a view which loads 4 components dynamicly

`
Vue.component("FcMainNav", () => import("../components/fc_mainnav.vue"));

Vue.component("overview-table", () => import("../components/Statistic/OverviewTable.vue"));

Vue.component("detail-table", () => import("../components/Statistic/DetailTable.vue"));

Vue.component("top-list", () => import("../components/Statistic/TopList.vue"));`

two of them always fail, sometimes a third one. In console i see ChunkLoadErrors with a message like

`StatisticView.js?id=de476a786dd24668b1ac:73233 [Vue warn]: Failed to resolve async component: function () {
  return __webpack_require__.e(/*! import() */ "resources_js_components_Statistic_DetailTable_vue").then(__webpack_require__.bind(__webpack_require__, /*! ../components/Statistic/DetailTable.vue */ "./resources/js/components/Statistic/DetailTable.vue"));
}
Reason: ChunkLoadError: Loading chunk resources_js_components_Statistic_DetailTable_vue failed.
(missing: https://myapp.com/js/pages/adminMain/resources_js_components_Statistic_DetailTable_vue.js)`

The file which is stated in the Error-Message is created. I cannot determine what in those components causes the break. Anyone experienced something like this?

I changed chunkFilename like mentioned here but it didnt change anything regarding those errors
https://github.com/JeffreyWay/laravel-mix/issues/2516
`
mix.webpackConfig({
  output: {
    chunkFilename: 'chunks/[name].js',
  },
});`

If i import the same components as static imports everything works fine.

### Steps To Reproduce:

yeah, thats the question :D

**Comment by AnwarElbo** [comment]
I have the same error
`Loading chunk 411 failed.
(missing: [domain]/js/views/Dashboard.bundle.js)`

**Comment by luccabassan** [comment]
I have the same error

`app.js?id=906dd92eb26a2363c5e223b7685af1f6:20 ChunkLoadError: Loading chunk 961 failed.
(missing: https://cnpj.test/appjs/js/resources/contatos.f35d2182f6b91519.js)
    at Object.o.f.j (app.js?id=906dd92eb26a2363c5e223b7685af1f6:20:183038)
    at app.js?id=906dd92eb26a2363c5e223b7685af1f6:20:181330
    at Array.reduce (<anonymous>)
    at Function.o.e (app.js?id=906dd92eb26a2363c5e223b7685af1f6:20:181308)
    at component (app.js?id=906dd92eb26a2363c5e223b7685af1f6:1:29304)
    at Se (app.js?id=906dd92eb26a2363c5e223b7685af1f6:20:12989)
    at app.js?id=906dd92eb26a2363c5e223b7685af1f6:20:19339`

whenever I access a route that is in a subdirectory and then come back, the vue router gets lost.

**Comment by mostafaznv** [comment]
Did anybody find a solution?

**Comment by luccabassan** [comment]
> Did anybody find a solution?

At the time I abandoned the Laravel project. I built the frontend in Nuxt, decoupled from the backend.
The backend, yes, in Laravel.
