### ISSUE TITLE
How to detect if mix running in HMR mode?

### ISSUE THREAD

**Issue by BARNZ** [JeffreyWay/laravel-mix#2973]
Just upgrading from mix 5 to 6.

One of the options that was removed was `mix.config.hmr` which I was using to adjust a few things such as chunking path when running in HMR  mode.

This config option no longer appears to be defined, so what is the equivalent/altnerative for `mix.config.hmr` in mix 6? I cant seem to find anything in the docs or upgrade guide.

**Comment by thecrypticace** [comment]
What were you changing based on HMR? Mix 6 handles a bit more re: HMR as well as dynamic imports so overriding `chunkFilename` is not advised.

**Comment by BARNZ** [comment]
Thanks @thecrypticace  for the info.

There were various old hacks in my webpack.mix file that was messing around with paths (setResourceRoot, setPublicPath) to make the older mix versions place nicely with the combination of HMR + output to `public/dist` + dynamic imports.

After removing most of it and keeping things barebones - it all appears to just work nicely for me now.

So no longer need to rely on `mix.config.hmr`, I'm going to close this issue.
