### ISSUE TITLE
Copy and Combine output relative to public path

### ISSUE THREAD

**Issue by iulyanp** [JeffreyWay/laravel-mix#299]
Hello @JeffreyWay 

Hope you are doing well.
I was wondering if it's possible when `setPublicPath()` is set, to make also the output for `copy()` or `combine()` to be relative to the public path?

At the moment, even I set the public path to `web`, for copy and combine functions I have to prefix the output with `web/`.
```
mix
.setPublicPath('web')
.js('assets/js/app.js', 'js')
.sass('assets/sass/app.scss', 'css')
.copy('assets/css/test.css', 'web/css/test.css')
.combine([
        'assets/css/bootstrap.css',
        'assets/css/style.css'
    ], 'web/css/all.css')
.version();
```
This results in the following content of `mix-manifest.json`
```
{
  "js/app.js": "js/app.63c3e765d0e19272856c.js",
  "css/app.css": "css/app.246bed245832d17dc7cf.css",
  "/css/all.css": "/css/all.css"
}
```
It would be nice if there was a consistency in both the output and the manifest content.

Kind regards,

**Comment by JeffreyWay** [comment]
You should be explicit with your output paths, and always assume the project root as your starting point.
