### ISSUE TITLE
Will you support Vite?

### ISSUE THREAD

**Issue by wsy998** [JeffreyWay/laravel-mix#2994]
Will you support Vite?

**Comment by JeffreyWay** [comment]
Not sure how that would work. No plans.

**Comment by thecodeclimber** [comment]
Perhaps a rewrite of mix to use Vite instead of webpack.  Vite is much quicker then webpack.

In short, you can keep the api and just change what happens under the hood.

**Comment by ojvribeiro** [comment]
A Vite version of Mix with the same API would be fantastic.
