### ISSUE TITLE
TypeScript Feature Flag

### ISSUE THREAD

**Issue by JeffreyWay** [JeffreyWay/laravel-mix#2995]
At the moment, we *do* support basic TypeScript compilation via `mix.ts('entry', 'output')`. but there doesn't seem to be an easy way to, for example, add TypeScript support to a Vue project. You'd need to manually drop down to the `mix.webpackConfig()` level.

I think we should make this simpler to activate. A couple options:

### Choice 1: Feature Flag

```js
mix.js('resources/js/app.js', 'dist')
    .vue()
    .typeScript();
```

With this approach, we'd only need to update Mix's existing <code>TypeScript</code> component to make the `register` method's `entry` and `output` parameters optional. That way, it can function as it always has...OR it can behave like a feature flag (just like `mix.vue()`).

### Choice 2: Make it an Option

```js
mix.js('resources/js/app.js', 'dist')
    .vue({ typeScript: true });
```

A second option which I personally like less would be to "turn on" TypeScript support as part of the `mix.vue()` option parameters.

---

Thoughts?

**Comment by thecrypticace** [comment]
Typescript + vue is already supported with `mix.ts()`:
https://github.com/JeffreyWay/laravel-mix/blob/db0dc003551e65fa2354469f8103760a59612e71/src/components/TypeScript.js#L46

Though I'd like to move that line out of the typescript plugin but I'm not sure how b/c that's a typescript-loader option.

**Comment by JeffreyWay** [comment]
Ugh I totally forgot that we already allowed for this when we switched to Vue being a feature flag.

I'm going to update the docs with a couple examples to make this clearer.

**Comment by thecrypticace** [comment]
It's been there since at least Mix v2. 😅 Some doc updates would be def. be good though!

**Comment by JeffreyWay** [comment]
`mix.vue()` wasn't a feature flag back in the v2 days. So I'm not sure how that would have worked.

**Comment by thecrypticace** [comment]
It was just "supported" given that we enabled Vue support all the time.
