### ISSUE TITLE
Use cross-env for NODE_ENV

### ISSUE THREAD

**Issue by PascaleBeier** [JeffreyWay/laravel-mix#3]
Haven't looked through everything yet, but in your scripts your are using

```json
"scripts": {
  "webpack": "webpack --progress --hide-modules",
  "dev": "webpack --watch --progress --hide-modules",
  "hmr": "webpack-dev-server --inline --hot",
  "production": "export NODE_ENV=production && webpack --progress --hide-modules"
}
```

Where export is not supported in non-UNIX platforms. I suggest pulling in cross-env as additional dev dependency.

This way, I am able to run `yarn run production` and `npm run production` on windows.

**Comment by QWp6t** [comment]
Alternatively, you could use `webpack -p` which will automatically set NODE_ENV to production. But that only works when webpack.config is a callback iirc

**Comment by PascaleBeier** [comment]
@QWp6t I thought this wouldnt work because everything is nested in different closures. Did you try that yet?
