### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by Bram-Zijp** [JeffreyWay/laravel-mix#30]
In my Homestead environment and hosts file I mapped the Laravel project to an 'projectname.app' url. When I run the 'npm run hmr' the localhost:8080 ain't working. Also curious how to integrate BrowserSync.

**Comment by nickfederighi** [comment]
@Bram-Zijp What was your solution to this? I've been trying to get HMR working in my Homestead environment and haven't had any success in getting the localhost script to load. I'm assuming it's a port forwarding issue, but it's perplexing me.

**Comment by Bram-Zijp** [comment]
@nickfederighi I will make something from a browsersync hot reload recipe outside of Homestead and transition to Laravel with that skipping Elixir and Mix all together for easy adjustments and education. I will let you know about my findings.
