### ISSUE TITLE
 Invalid configuration object. Webpack has been initialised using a configuration object that does not match the api schema

### ISSUE THREAD

**Issue by akshayp660** [JeffreyWay/laravel-mix#3008]
-   Laravel Mix Version: 6.0.19
-   Node Version: 13.14.0
-   NPM Version : 7.17.0
-   OS: windows 7 32bit

### Description:

[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.optimization.splitChunks should be one of these:
   false | object { automaticNameDelimiter?, automaticNameMaxLength?, cacheGroups?, chunks?, enforceSizeThreshold?, fall
backCacheGroup?, filename?, hidePathInfo?, maxAsyncRequests?, maxInitialRequests?, maxSize?, minChunks?, minSize?, name?
 }
   -> Optimize duplication and caching by splitting chunks by shared modules and cache group
   Details:
    * configuration.optimization.splitChunks.cacheGroups['styles-public\css\app'] has an unknown property 'type'. These
properties are valid:
      object { automaticNameDelimiter?, automaticNameMaxLength?, automaticNamePrefix?, chunks?, enforce?, enforceSizeThr
eshold?, filename?, maxAsyncRequests?, maxInitialRequests?, maxSize?, minChunks?, minSize?, name?, priority?, reuseExist
ingChunk?, test? }
    * configuration.optimization.splitChunks.cacheGroups['styles-public\css\web'] has an unknown property 'type'. These
properties are valid:
      object { automaticNameDelimiter?, automaticNameMaxLength?, automaticNamePrefix?, chunks?, enforce?, enforceSizeThr
eshold?, filename?, maxAsyncRequests?, maxInitialRequests?, maxSize?, minChunks?, minSize?, name?, priority?, reuseExist
ingChunk?, test? }
 - configuration.output.chunkFilename should be a string.
   -> The filename of non-entry chunks as relative path inside the `output.path` directory.
 - configuration.stats has an unknown property 'preset'. These properties are valid:
   object { all?, assets?, assetsSort?, builtAt?, cached?, cachedAssets?, children?, chunkGroups?, chunkModules?, chunkO
rigins?, chunks?, chunksSort?, colors?, context?, depth?, entrypoints?, env?, errorDetails?, errors?, exclude?, excludeA
ssets?, excludeModules?, hash?, logging?, loggingDebug?, loggingTrace?, maxModules?, moduleAssets?, moduleTrace?, module
s?, modulesSort?, nestedModules?, optimizationBailout?, outputPath?, performance?, providedExports?, publicPath?, reason
s?, source?, timings?, usedExports?, version?, warnings?, warningsFilter? }

package.json file

{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --disable-host-check --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "@babel/preset-react": "^7.0.0",
        "admin-lte": "^3.1.0",
        "autoprefixer": "^10.2.6",
        "bootstrap": "^4.0.0",
        "cross-env": "^7.0",
        "jquery": "^3.2",
        "lodash": "^4.17.19",
        "popper.js": "^1.12",
        "postcss": "^8.3.2",
        "resolve-url-loader": "^4.0.0",
        "sass": "^1.15.2",
        "sass-loader": "^7.1.0",
        "tailwindcss": "^2.0.4",
        "vue-template-compiler": "^2.6.12"
    },
    "dependencies": {
        "axios": "^0.21.1",
        "datatables.net": "^1.10.23",
        "datatables.net-dt": "^1.10.23",
        "fastclick": "^1.0.6",
        "font-awesome": "^4.7.0",
        "isotope-layout": "^3.0.6",
        "laravel-mix": "^6.0.19",
        "tinymce": "^5.6.2",
        "webpack": "^4.46.0",
        "webpack-cli": "^4.7.2",
        "webpack-dev-server": "^4.0.0-beta.2"
    }
}

### Steps To Reproduce:
when updated laravel-mix from 5.x.x to 6.x.x and after runing npx mix or npm run dev

error on shell
![npx mix](https://user-images.githubusercontent.com/14879414/121779539-d3ef5d80-cbb9-11eb-856c-c0b9081fe8eb.PNG)

**Comment by thecrypticace** [comment]
Laravel Mix is for Webpack v5. Your package.json is requiring webpack 4. Please update.
