### ISSUE TITLE
Building crashes without error

### ISSUE THREAD

**Issue by arwinvdv** [JeffreyWay/laravel-mix#3009]
-   Laravel Mix Version: 6.0.19 (`npm list --depth=0`)
-   Node Version: 16.0.0
-   NPM Version: 7.17.0
-   OS: macOS Big Sur 11.4

### Description:
Around the 60% building the process crashes without an error:
<img width="898" alt="Schermafbeelding 2021-06-14 om 10 18 47" src="https://user-images.githubusercontent.com/7255485/121861216-ee305500-ccf9-11eb-919c-46873d1d85a8.png">

Note: the browserslist error shows before the buildproces crashes around 55%, so i think that is not the problem. Before the upgrade to laravel mix 6 we didn't had the crashes.

Webpack.mix.js
```js
const mix = require('laravel-mix')
const { resolve } = require('path')

mix.webpackConfig({
    resolve: {
        fallback: {
            "crypto": require.resolve("crypto-browserify")
        },
        extensions: ['.js', '.json', '.vue'],
        alias: {
            '~': resolve(__dirname, './resources/js')
        }
    },
}).js('resources/js/app.js', 'public/js')
    .vue()

mix.less('resources/less/AdminLTE.less', 'public/css/app.css')
    .options({
        processCssUrls: false
    })
    .disableNotifications()
```

Question: is there a way to get more information about the crash?

**Comment by thecrypticace** [comment]
What's interesting is it looks like the process is exiting cleanly as if something is calling process.exit() during the build (based on your zsh prompt — in that theme, by default, the arrow would be red for exit codes != 0). 🤔 

Try adding this to your mix config to see if it helps uncover anything:
```js
mix.override(config => {
  // Configure webpack to show basically everything
  config.stats = {
    all: true,
    logging: 'verbose',
    loggingDebug: /.*/,
  }

  // Remove the table added by Mix
  config.plugins = config.plugins.filter(plugin => plugin.constructor.name !== "BuildOutputPlugin")
})
```

**Comment by arwinvdv** [comment]
@thecrypticace Thanks! I fixed the errors (some css resources that he didn't found and added vm and stream to resolve.fallback) and after that it worked!
