### ISSUE TITLE
Unable to compile any CSS in single file Vue components

### ISSUE THREAD

**Issue by cwhite92** [JeffreyWay/laravel-mix#301]
I've been following the Vue 2.0 Laracasts series to get up a running with laravel-mix and single file Vue components. This is my `webpack.mix.js`:

    let mix = require('laravel-mix').mix;

    mix.js('app/js/app.js', 'public/js')
        .sass('app/scss/app.scss', 'public/css')
        .copy('app/index.html', 'public/index.html');

And my `app/js/app.js`:

    import Vue from 'vue';
    import Notification from './components/Notification.vue';

    new Vue({
        el: '#app',
        components: { Notification }
    });

And finally, my `Notification.vue`:

    <template>
        <div class="notification">
            <h1>{{ message }}</h1>
        </div>
    </template>
    
    <script>
        export default {
            data() { return { message: 'Hello world!' } }
        }
    </script>
    
    <style>
        .notification {
            background: red;
        }
    </style>

When running `npm run dev`, I get the following output:

![Screenshot](https://i.imgur.com/2mrEiMw.png)

As you can see, the `app.css` file has a size of 0 bytes despite the Vue component containing `<style>`s.

Just to confirm the issue, I created a fresh Laravel 5.4 application and added some dummy styles to the `Example.vue` component, and upon running `npm run dev`, those styles never got added to the stylesheet.

I don't know a lot about how webpack works, but what I found interesting is that the compiled JS file has this:

    // module
    exports.push([module.i, "\n.notification {\n    background: red;\n}\n", ""]);

Which is the CSS style that I specified in my `Notification.vue` component?

Anybody experienced this before?

**Comment by adriaanzon** [comment]
Yep, that's the standard behavior when importing styles into your javascript (which is what `.vue` files do behind the scenes). The styles still get applied when you view it in the browser, right?

**Comment by cwhite92** [comment]
Heh... looks like I'm just really unfamiliar with how that whole workflow works. It does indeed work in the browser :)

It looks like webpack takes care of shoving the stylesheet into the `<head>` of the document. Is there a way to make it write to `app.css` instead?

Either way, the main issue is resolved, thanks!

**Comment by Stetzon** [comment]
@cwhite92 you can set this option in Laravel Mix to extract all the styles from the components and bundle them into your styles.css (as opposed to injecting them in the head):

```
mix.options({
  extractVueStyles: true
});
```
