### ISSUE TITLE
webpack.mix.js "No such file or directory"

### ISSUE THREAD

**Issue by xApep** [JeffreyWay/laravel-mix#3011]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`): laravel-mix@6.0.20
-   Node Version (`node -v`): v15.6.0
-   NPM Version (`npm -v`): 7.4.0
-   OS:

### Description:
I'm install clean laravel-mix but when I want to do "cp" I get "No such file or directory".
![image](https://user-images.githubusercontent.com/1315340/122260149-36ef3600-ced3-11eb-8c93-4f66ef7f6a5e.png)

In nodes_modules/laravel-mix/setup there is only webpack.config.js file.
### Steps To Reproduce:
```
npm init -y
npm install -D laravel-mix cross-env
cp node_modules/laravel-mix/setup/webpack.mix.js ./
```

**Comment by JeffreyWay** [comment]
Those are out-dated installation steps. Did you find those in the GitHub docs in this repo somewhere?

Instead work along with this: https://github.com/JeffreyWay/laravel-mix/blob/master/docs/installation.md

**Comment by xApep** [comment]
@JeffreyWay thanks! I think you will need to update official docs, because I have found this in it.
https://laravel-mix.com/docs/5.0/installation

**Comment by JeffreyWay** [comment]
We don't maintain that website. The official docs are here on GitHub in this repo. 

Plus, that links to docs for Mix 5.0. You're using Mix 6.
