### ISSUE TITLE
Mix 6.0.20 not setting correct file paths for fontsource 4.0+ fonts (locally installed/self hosted fonts)

### ISSUE THREAD

**Issue by austriker27** [JeffreyWay/laravel-mix#3012]
-   Laravel Mix Version: 6.0.20
-   Node Version: v15.2.0
-   NPM Version: 7.0.10
-   OS: macOS 10.14.6

### Description:

I've used fontsource.org in the past with prior version of Laravel Mix and they worked super well. (It's a great way to install and use local fonts in projects)

In the past you just need to install them via yarn/npm and then add them to your `.js` project file. However now with Mix 6.0.20 the file paths seem to be generated incorrectly based on what i see in the compiled JS file and the browser errors. 

Browser errors:
`GET http://domain.test/files/montserrat-all-400-normal.woff`
`downloadable font: download failed (font-family: "Montserrat" style:normal weight:400 stretch:100 src index:1): status=2147746065 source: http://domain.test/files/montserrat-all-400-normal.woff`

Webpack mix file:
```
mix.js('resources/js/site.js', 'public/js')
  .sourceMaps()
mix
  .sass("resources/css/tailwind.scss", "public/css/")
  .tailwind("./tailwind.config.js")
  .options({
    processCssUrls: false,
  })

if (mix.inProduction()) {
  mix.version();
}
```

My `site.js` file:
```
import '@fontsource/montserrat'
```

It's probably not relevant but this is in a Statamic project using Tailwind CSS 2.1.4. (Even doing `font-family: "Montserrat"` in the browser doesn't work to render the font so it doesnt seem like a statamic or tailwind bug).

### Steps To Reproduce:

1. 
`yarn add @fontsource/montserrat` (Im using `fontsource/montserrat@4.4.5`)
`yarn add laravel-mix`

2. Add to your project's JS file:
`import '@fontsource/montserrat'`

3. `yarn dev` 

Related issues on github that I found: 
https://github.com/fontsource/fontsource/issues/163
https://github.com/fontsource/fontsource/issues/212

**Comment by austriker27** [comment]
GOOD NEWS! After hours of troubleshooting i found the problem - sass/scss wasn't loading the font files in the JS correctly.... 

This works with PostCSS so I'm going to stick with that - hope this helps save someone else time!

**Comment by austriker27** [comment]
> > GOOD NEWS! After hours of troubleshooting i found the problem - sass/scss wasn't loading the font files in the JS correctly....
> > This works with PostCSS so I'm going to stick with that - hope this helps save someone else time!
> 
> @austriker27 don't suppose you could paste your PostCSS config that worked?

Im not actually using a postcss config file - just laravel mix, is that what you mean?

**Comment by terrancecorley** [comment]
@austriker27 Could you share your laravel mix config that got this to work? I'm running into a similar issue where I'm trying to access a font in React but get this...

![image](https://user-images.githubusercontent.com/20272233/134434003-ca6a1670-22b3-43da-b48a-75c139a906c1.png)

**Comment by b0rt** [comment]
i am experiencing the same problem (albeit using KirbyCMS with laravel-mix)

**Comment by duffpop** [comment]
@austriker27 any chance you could provide your `webpack.mix.js` config for this mate? I've had a look through your repos and thought I'd find the config in here - https://github.com/austriker27/davidalindahl__3.0 - but there wasn't out to be found.
