### ISSUE TITLE
How to convert https://github.com/JeffreyWay/laravel-mix/issues/1072#issuecomment-319401164 to Windows Commands?

### ISSUE THREAD

**Issue by MESHach12345** [JeffreyWay/laravel-mix#3013]
So I seem to be facing an issue metioned in that link however cmd is not recognizing some commands like rm. Can the cmds for windows pls be provided?

**Comment by JeffreyWay** [comment]
Apologies, but repo-specific bugs and issues only. 

Please use Google for things like this.
