### ISSUE TITLE
No matching version found for collect.js@^4.28.6.

### ISSUE THREAD

**Issue by makifgokce** [JeffreyWay/laravel-mix#3014]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`)
-   Node Version (`node -v`): v14.17.1
-   NPM Version (`npm -v`): 6.14.13
-   OS: Windows 10

### Description:
```
npm ERR! notarget No matching version found for collect.js@^4.28.6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'laravel-mix'
npm ERR! notarget
```
### Steps To Reproduce:
`npm install`

**Comment by uchqur** [comment]
```
Laravel Mix Version: #.#.# (npm list --depth=0)
Node Version (node -v): v16.3.0
NPM Version (npm -v): 7.16.0
OS: Mac OS X 11.4 (20F71)
```

## Same error

**Comment by thecrypticace** [comment]
If you're seeing this error it's likely that your npm cache is broken. Please try `npm cache clean --force`.

**Comment by uchqur** [comment]
> If you're seeing this error it's likely that your npm cache is broken. Please try `npm cache clean --force`.

```
$ npm cache clear --force
npm WARN using --force Recommended protections disabled.
$ npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for collect.js@^4.28.6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by makifgokce** [comment]
This error happens when I create a new project.
`npm i collect.js@^4.28.6. ` I get the same error when I run the command, it might be version related.

**Comment by thecrypticace** [comment]
I think the npm tag was unpublished. It worked when the CI ran for the latest release 4 days ago. Yarn reports the latest version as 4.28.5, NPM reports it as 4.28.6 on the project page but 4.28.5 on the listing page.

<img width="378" alt="Screen Shot 2021-06-23 at 22 33 52" src="https://user-images.githubusercontent.com/614993/123193642-26126780-d473-11eb-8f48-6d475bbfb0fc.png">
<img width="416" alt="Screen Shot 2021-06-23 at 22 33 59" src="https://user-images.githubusercontent.com/614993/123193647-2874c180-d473-11eb-8371-3a925f5d92f4.png">
<img width="408" alt="Screen Shot 2021-06-23 at 22 34 04" src="https://user-images.githubusercontent.com/614993/123193654-2ad71b80-d473-11eb-8137-b14f66c24529.png">
