### ISSUE TITLE
Mix6 Vue3 error: Component is missing template or render function.

### ISSUE THREAD

**Issue by yaroslawww** [JeffreyWay/laravel-mix#3030]
-   Laravel Mix Version: laravel-mix@6.0.25 (`npm list --depth=0`)
-   Node Version (`node -v`): v14.17.0
-   NPM Version (`npm -v`): 6.14.13
-   Yarn Version (`yarn -v`): 1.22.5
-   OS: Linux Mint

### Description:
After compilation browser console return error:
```
research.js:6250 [Vue warn]: Component is missing template or render function. 
  at <FrontForm> 
  at <App>
```
### Steps To Reproduce:
resources/front_v2/package.json
```
{
    "name": "frontv2",
    "version": "0.1.0-alpha",
    "private": true,
    "scripts": {
        "development-research": "mix  --mix-config configs/webpack.research.mix.js",
        "production-research": "mix --production --mix-config configs/webpack.research.mix.js",
        "watch-research": "mix watch --mix-config configs/webpack.research.mix.js"
    },
    "devDependencies": {
        "@vue/compiler-sfc": "^3.1.4",
        "laravel-mix": "^6.0.25",
        "vue": "^3.1.4"
    }
}
```
resources/front_v2/configs/webpack.research.mix.js
```
const mix = require('laravel-mix');

mix.setPublicPath('../../public/research-dist');
mix.webpackConfig({
    output: {
        publicPath: '/research-dist/'
    },
});

mix.js("js/research.js", 'js').vue();
```
resources/front_v2/js/components/Form/FrontendForm.vue
```
<template>
    <div>
        test data
    </div>
</template>

<script>
export default {
    name: "FrontendForm"
}
</script>

<style scoped>

</style>
```
resources/front_v2/js/research.js
```
import {createApp} from "vue";
const app = createApp({});
app.component(
    'front-form',
    import("./components/Form/FrontendForm")
);
app.mount('#root');
```
Result: single file component compiled not correctly:
![Screenshot from 2021-07-07 11-10-27](https://user-images.githubusercontent.com/23663794/124723707-fbfd8280-df13-11eb-8638-8cf49b71b06a.png)

Any idea how to fix this?

**Comment by noogen** [comment]
This maybe related/of help: https://stackoverflow.com/questions/64409157/vue-js-component-is-missing-template-or-render-function

If not, would you have example repo somewhere to show the issue?

**Comment by yaroslawww** [comment]
@noogen 
Now the code works with a fresh installation but still does not work as I showed on first comment. So I close issue.
