### ISSUE TITLE
How to run mix.sourceMaps() on development (and watch)?

### ISSUE THREAD

**Issue by tatsuki-happys** [JeffreyWay/laravel-mix#3038]
-   Laravel Mix Version: laravel-mix@6.0.25
-   Node Version : v14.17.3
-   NPM Version : 7.20.0
-   OS: MacOS Catalina

### Description:

I want to source maps on development.
bad, following code does not generate source maps on running `npm run development` and `npm run watch`.
How to run mix.sourceMaps() on development (and watch)?

### Steps To Reproduce:

my code
```webpack.mix.js
mix.js('resources/js/app.js', 'js')
    .sass('resources/sass/app.scss', 'css')
    .sourceMaps(true, "inline-source-map");
```

```webpack.mix.js
mix.webpackConfig({
    devtool: 'inline-source-map' // don't work
})
```

`npm run production` run,  generate source maps.

**Comment by JeffreyWay** [comment]
Source maps already work in development. I use them all the time. 

I just tried again to be extra sure. All works as expected out of the box. You don't need to use `mix.webpackConfig()` to set the devtool. That's what `mix.sourceMaps()` does.

If you can give me reproducible steps in a fresh app, I can take another look.
