### ISSUE TITLE
How to extract styles from vue components?

### ISSUE THREAD

**Issue by terion-name** [JeffreyWay/laravel-mix#304]
It is obvious that styles written in `.vue` components should be extracted to separate files. Is there a built-in support or this? In pevious version I've edited config like this:
```
rules: [
        {
            test: /\.vue$/,
            loader: 'vue-loader',
            options: {
                loaders: {
                    js: 'babel-loader' + Mix.babelConfig(),
                    css: plugins.ExtractTextPlugin.extract({
                        loader: 'css-loader',
                        fallbackLoader: 'vue-style-loader'
                    }),
//
```
but now this fails with error

**Comment by JeffreyWay** [comment]
I've added support for this on master. It'll be tagged at some point this week, likely.

Once tagged, you can turn on Vue style extraction with:

```js
mix.options({ extractVueStyles: true });
```

**Comment by terion-name** [comment]
@JeffreyWay thank you!

**Comment by terion-name** [comment]
@JeffreyWay I'v added your commit to my config and I want to aware you: this makes impossible to use multiple stylesheets.

![2017-02-10 00 59 51](https://cloud.githubusercontent.com/assets/1060205/22806764/3e04f76c-ef2c-11e6-9b4a-5b9238dbdb20.png)

![2017-02-10 01 00 09](https://cloud.githubusercontent.com/assets/1060205/22806778/49dde602-ef2c-11e6-85f5-6209ab440ac0.png)

You can see that styles, extracted from two js files (app.js and ui.js) are extracted to both app.css and home.css. And they are similar at the end
