### ISSUE TITLE
How to minify the whole content of the specific directory?

### ISSUE THREAD

**Issue by MehdiKhoshnevisz** [JeffreyWay/laravel-mix#3042]
-   Laravel Mix Version: 6.0.25
-   Node Version: 14.17.1
-   NPM Version: 6.14.13
-   OS: Windows 10

### Description:
I want to minify the whole content of the specific directory like my **css directory**:
.
├── css
│   ├── pages
│    └── home.css
│   ├── main.css

Is that possible something like `mix.minify('css/*')`?

**Comment by JeffreyWay** [comment]
I don't think so, but you can use Node to scan any directory to get an array of file names within it. Then you can pass that array to `mix.minify()`.
