### ISSUE TITLE
keep original timestaps with copy

### ISSUE THREAD

**Issue by jamesRUS52** [JeffreyWay/laravel-mix#3046]
mix.copyDirectory('resources/plugins', 'public/plugins');

is it possible to keep original timestamp while copy?

The original files changes very rarely but deploy process (via rsync) copy it to production server every time, because they have changed their update timestamp after mix.copy command

**Comment by thecrypticace** [comment]
I think this is a wont fix. Some tools don't preserve timestamp metadata. I would consider such metadata to be volatile and could change regardless of whether or not the content of the file has changed. I'd say this is a very limited use case. If you're using `rsync` I recommend using the `--checksum` flag. This will copy files that have changed in size or content but not based on timestamp.
