### ISSUE TITLE
Missing documentation for removed `--no-progress` and `--inline` options

### ISSUE THREAD

**Issue by williamdes** [JeffreyWay/laravel-mix#3048]
-   Laravel Mix Version: latest

### Description:

```
yarn run v1.22.5
$ cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js
[webpack-cli] Error: Unknown option '--inline'
[webpack-cli] Run 'webpack --help' to see available commands and options
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
```
$ npm run production

> @srexi/purecounterjs@1.1.4 production
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

[webpack-cli] Error: Unknown option '--no-progress'
[webpack-cli] Run 'webpack --help' to see available commands and options
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps To Reproduce:

Project: https://github.com/srexi/purecounterjs
Upgrade to latest, remove `--hide-modules` as advised, get errors on `--no-progress` and `--inline` options that do not exist **but sill are part of the upgrade guide examples**

They where probably removed but this is not documented :)

**Comment by JeffreyWay** [comment]
Those are webpack specific options that were removed as part of webpack 5. 

This was included in the Mix 6 upgrade guide.

https://github.com/JeffreyWay/laravel-mix/blob/master/UPGRADE.md

**Comment by williamdes** [comment]
Oh okay, my bad it was the before example: https://github.com/JeffreyWay/laravel-mix/blob/master/UPGRADE.md#before

I was searching for a textual phrase to explain it

Thanks
