### ISSUE TITLE
npm run prod failing for classes used only in javascript

### ISSUE THREAD

**Issue by Temepest74** [JeffreyWay/laravel-mix#3060]
-   Laravel Mix Version: 6.0.27 (`npm list --depth=0`)
-   Node Version (`node -v`): v16.3.0
-   NPM Version (`npm -v`): 7.15.1
-   OS: Windows 10

### Description:

Running the npm run prod command fails to identify the classes used only inside js. I am using tailwind css.

### Steps To Reproduce:

1. Create a new laravel project
2. Install tailwind.
3. in app.js create an object to append to the DOM ex:  
```
elem.innerHTML += '<img src="' +
                GLOBAL.recipesUrl +
                '/' +
                element +
                '" class="max-h-v-70 max-w-v-60" />';
```

I created max-h-v-70 max-w-v-60 in my tailwind.config.js. They work 100%. Tested with npm run watch.
(The code may not be correctly defined but you get the idea)
4. Never use max-h-v-70 or max-w-v-60 inside a .blade.php file.
5. Run npm run prod
6. They are not present inside public/css/app.css

### Expected Result

Both classes presented inside public/css/app.css

**Comment by thecrypticace** [comment]
You need to configure your purge array in tailwind for it to work correctly.
