### ISSUE TITLE
How to fetch individual object property value and print in console?

### ISSUE THREAD

**Issue by swagatik** [JeffreyWay/laravel-mix#3062]
**`First Question`**

MY CURRENT CODE which is fetching the data as per the provided scenario value (i.e l1, l2 value )

    async function getScenarioID (client, l1, l2)
    {
      const cursor =client.db ('snapp_transactions').collection ('price_check_validation').find ({
        Scenario: {
          $in: [
            l1,
            l2
          ]
        }
      });
      const result=await cursor.toArray ();
      console.log (result);
    }

which i am calling in another main function (i.e ; await getScenarioID (client, 'WH HERA 2.A', 'WH HERA 1.F') ;) and passing the 'l1','l2' value .

The current O/P -

    [ { _id: 6114ce6514796e5fbe316bda,
        App: 'SnApp POS',
        'Other Voucher Code': '',
        'Date and Time Performed': '',
        'SnApp Error': '',
        Done: '',
        'Unit Tax Quoted': '$0.00',
        'AQ perDayNetPrice': '',
        'Gold "Upgrade Tax"': '',
        'Gold Source': '',
        'Execution Time': 2021-08-12T07:31:49.653Z,
        'SnApp API Tax Inclusive (Y/N)': '',
        'Voucher Bridging Amount (7800)': '',
        'SnApp Ticket Value': '',
        'SnApp Ticket Tax': '',
        'AQ netPrice': '',
        Status: 'Complete',
        'Execution Environment': 'STAGE',
        'Order ID': 'VGVXVKRD',
        'Gold "Net Price to Seller"': '',
        'Test #': 'WH HERA 1.F',
        Scenario: 'WH HERA 1.F',
        'Assigned To': '',
        'AQ perDayRetailTax': '',
        'Other Voucher Amount': '',
        'Did See PopUp': '',
        'Ticket Type': '1 Park Per Day',
        'SnApp API Faceprice': '',
        Action: 'Modify dates to the same priced tier in SnApp POS',
        Modified: '',
        'AQ Modification Price': '',
        'AQ perDayNetTax': '',
        'Gold "Upgrade Price"': '',
        'Unit $ Quoted': '$0.00',
        'Total Quoted': '$0.00',
        'Modified By': 'trisha.x.shah.-nd@disney.com',
        'DTI Payload ID': '',
        'Validity End Date': '7/31',
        'Payment Method': 'N/A',
        'AQ netTax': '',
        'Gold "Upgrade Value"': '',
        'Validity Start Date': '7/25',
        'AQ retailPrice': '',
        'Gold "Upgrade Value Without Tax"': '',
        'AQ Modification Tax': '',
        Comments: '',
        'Ticket Code': '4J0Y5',
        Quantity: '1',
        Host: 'BDC6-LX-CKNXY93\\192.168.43.134',
        'AQ perDayRetailPrice': '',
        'Payment Amount': '$0.00',
        'Gold "Seller Pays"': '',
        'AQ retailTax': '',
        Type: '$0 Modify',
        'Gold "Tax to Seller"': '',
        RunID: '081220211301',
        'Transaction Date': '6/16',
        Day: '4' },
      { _id: 6114ce6614796e5fbe316be4,
        App: 'PRO_WH_DS',
        'Other Voucher Code': '',
        'Date and Time Performed': '',
        'SnApp Error': '',
        Done: '',
        'Unit Tax Quoted': '$30.61',
        'AQ perDayNetPrice': '',
        'Gold "Upgrade Tax"': '',
        'Gold Source': '',
        'Execution Time': 2021-08-12T07:31:50.002Z,
        'SnApp API Tax Inclusive (Y/N)': '',
        'Voucher Bridging Amount (7800)': '',
        'SnApp Ticket Value': '',
        'SnApp Ticket Tax': '',
        'AQ netPrice': '',
        Status: 'Complete',
        'Execution Environment': 'STAGE',
        'Order ID': 'KJWT62312828',
        'Gold "Net Price to Seller"': '',
        'Test #': 'WH HERA 2.A',
        Scenario: 'WH HERA 2.A',
        'Assigned To': '',
        'AQ perDayRetailTax': '',
        'Other Voucher Amount': '',
        'Did See PopUp': '',
        'Ticket Type': '1 Park Per Day',
        'SnApp API Faceprice': '',
        Action: '"Purchase 4-Day Variable Date Based, Water Park, Sports"',
        Modified: '',
        'AQ Modification Price': '',
        'AQ perDayNetTax': '',
        'Gold "Upgrade Price"': '',
        'Unit $ Quoted': '$470.77',
        'Total Quoted': '$501.38',
        'Modified By': 'trisha.x.shah.-nd@disney.com',
        'DTI Payload ID': '39750000000003735624',
        'Validity End Date': '07/22/21',
        'Payment Method': 'DC',
        'AQ netTax': '',
        'Gold "Upgrade Value"': '',
        'Validity Start Date': '07/15/21',
        'AQ retailPrice': '',
        'Gold "Upgrade Value Without Tax"': '',
        'AQ Modification Tax': '',
        Comments: '',
        'Ticket Code': '4LO0Z',
        Quantity: '1',
        Host: 'BDC6-LX-CKNXY93\\192.168.43.134',
        'AQ perDayRetailPrice': '',
        'Payment Amount': '$501.38',
        'Gold "Seller Pays"': '',
        'AQ retailTax': '',
        Type: 'Sale',
        'Gold "Tax to Seller"': '',
        RunID: '081220211301',
        'Transaction Date': '',
        Day: '4' },
      { _id: 61161c963aec2265c293dce0,
        App: 'PRO_WH_DS',
        'Other Voucher Code': '',
        'Date and Time Performed': '',
        Done: '',
        'Unit Tax Quoted': '$30.61',
        'AQ perDayNetPrice': '',
        'Gold "Upgrade Tax"': '',
        'Gold Source': '',
        'Execution Time': 2021-08-13T07:17:42.254Z,
        'SnApp API Tax Inclusive (Y/N)': '',
        'Voucher Bridging Amount (7800)': '',
        'SnApp Ticket Value': '',
        'SnApp Ticket Tax': '',
        'AQ netPrice': '',
        Status: 'Complete',
        'Execution Environment': 'STAGE',
        'Order ID': 'KJWT62312828',
        'Gold "Net Price to Seller"': '',
        Scenario: 'WH HERA 2.A',
        'Assigned To': '',
        'AQ perDayRetailTax': '',
        'Other Voucher Amount': '',
        'SnApp API Faceprice': '',
        Action: '"Purchase 4-Day Variable Date Based, Water Park, Sports"',
        Modified: '',
        'AQ Modification Price': '',
        'AQ perDayNetTax': '',
        'Gold "Upgrade Price"': '',
        'Unit $ Quoted': '$470.77',
        'Total Quoted': '$501.38',
        'Modified By': 'trisha.x.shah.-nd@disney.com',
        'DTI Payload ID': '39750000000003735624',
        'Validity End Date': '07/22/21',
        'Payment Method': 'DC',
        'AQ netTax': '',
        'Gold "Upgrade Value"': '',
        'Validity Start Date': '07/15/21',
        'AQ retailPrice': '',
        'Gold "Upgrade Value Without Tax"': '',
        'AQ Modification Tax': '',
        Comments: '',
        'Ticket Code': '4LO0Z',
        Quantity: '1',
        Host: 'BDC6-LX-CKNXY93\\192.168.0.122',
        'AQ perDayRetailPrice': '',
        'Payment Amount': '$501.38',
        'Gold "Seller Pays"': '',
        'AQ retailTax': '',
        Type: 'Sale',
        'Gold "Tax to Seller"': '',
        RunID: '081320211247',
        'Transaction Date': '' },
      { _id: 61161c953aec2265c293dcdc,
        App: 'SnApp POS',
        'Other Voucher Code': '',
        'Date and Time Performed': '',
        Done: '',
        'Unit Tax Quoted': '$0.00',
        'AQ perDayNetPrice': '',
        'Gold "Upgrade Tax"': '',
        'Gold Source': '',
        'Execution Time': 2021-08-13T07:17:41.983Z,
        'SnApp API Tax Inclusive (Y/N)': '',
        'Voucher Bridging Amount (7800)': '',
        'SnApp Ticket Value': '',
        'SnApp Ticket Tax': '',
        'AQ netPrice': '',
        Status: 'Complete',
        'Execution Environment': 'STAGE',
        'Order ID': 'VGVXVKRD',
        'Gold "Net Price to Seller"': '',
        Scenario: 'WH HERA 1.F',
        'Assigned To': '',
        'AQ perDayRetailTax': '',
        'Other Voucher Amount': '',
        'SnApp API Faceprice': '',
        Action: 'Modify dates to the same priced tier in SnApp POS',
        Modified: '',
        'AQ Modification Price': '',
        'AQ perDayNetTax': '',
        'Gold "Upgrade Price"': '',
        'Unit $ Quoted': '$0.00',
        'Total Quoted': '$0.00',
        'Modified By': 'trisha.x.shah.-nd@disney.com',
        'DTI Payload ID': '',
        'Validity End Date': '7/31',
        'Payment Method': 'N/A',
        'AQ netTax': '',
        'Gold "Upgrade Value"': '',
        'Validity Start Date': '7/25',
        'AQ retailPrice': '',
        'Gold "Upgrade Value Without Tax"': '',
        'AQ Modification Tax': '',
        Comments: '',
        'Ticket Code': '4J0Y5',
        Quantity: '1',
        Host: 'BDC6-LX-CKNXY93\\192.168.0.122',
        'AQ perDayRetailPrice': '',
        'Payment Amount': '$0.00',
        'Gold "Seller Pays"': '',
        'AQ retailTax': '',
        Type: '$0 Modify',
        'Gold "Tax to Seller"': '',
        RunID: '081320211247',
        'Transaction Date': '6/16' } ]

But here the drawback is tomorrow if my 'l1','l2' value is getting increase then i have to pass in two area (i.e  in main () and getScenarioID() )  which i don not want  , how can i resolve this issue ?. 

***Second Question*** 

Now as per my O/p it is printing the complete document , but how can i print only a specific object value like 'last Date ' or 'Modified By' etc .

**Comment by thecrypticace** [comment]
This is not the place to ask for JS help / related questions. Ask on the Laracasts forums, StackOverflow, et. al. places.
