### ISSUE TITLE
webpack-cli updated to the lattest version is causing issues to laravel-mix (propably)

### ISSUE THREAD

**Issue by geocfu** [JeffreyWay/laravel-mix#3065]
-   Laravel Mix Version: 6.0.27
-   Node Version: 15.8.0
-   NPM Version: 7.19.0
-   OS: Linux (Ubuntu 20.04.2 LTS)

### Description:
After upgrading this morning the node modules, laravel mix stopped working. This probably has to do with the update of webpack-cli that happened yesterday from version 4.7.2 to 4.8.0.

### Steps To Reproduce:
Create a new project with Laravel, install Jetstream (just because it is already configured with inertia) and install the packages (I used yarn, but it's the same with npm). 

And run

```bash
#yarn
yarn hot
```

```bash
#npm
npm run hot
```

and get the following error:

```bash
➜ yarn hot
yarn run v1.22.4
$ mix watch --hot

● Mix █████████████████████████  (0%)


[webpack-cli] Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'webpackbar'. These properties are valid:
   object { bonjour?, client?, compress?, devMiddleware?, firewall?, headers?, historyApiFallback?, host?, hot?, http2?, https?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, public?, setupExitSignals?, static?, transportMode?, watchFiles? }
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by oprtask-rb** [comment]
I'm experiencing the same issue.

**Comment by geocfu** [comment]
@oprtask-rb  The problem is the peer dependency. This dependency has changed and is causing the issue (although, take this with a grain of salt because I am not aware laravel-mix's codebase).

**Comment by thecrypticace** [comment]
I'll take a look at this today. I don't believe it's related to webpack-cli as I've downgraded it locally and it still causes a problem.

**Comment by sashko-guz** [comment]
Same. Prod and dev builds are fine. Hot — isnt working

**Comment by quantumwebco** [comment]
+1

**Comment by Velmoren** [comment]
Faced the same problem. How difficult is it without hot ((

**Comment by Lezhni** [comment]
@Velmoren agreed, my friend

**Comment by FatihAydin52** [comment]
+1

**Comment by eXist73** [comment]
+1

**Comment by shafter** [comment]
+1

**Comment by tijsbakker** [comment]
+1

**Comment by thecrypticace** [comment]
This has been fixed but a release has not yet been tagged (h/t to @guihigashi). I'll make a note once a release has been tagged.

**Comment by guihigashi** [comment]
You're welcome. Thanks for the mention

**Comment by jhosepharaujo** [comment]
Any predictions for the new version? The previous version 6.0.27 is still bug and yarn and npm still reference it.
