### ISSUE TITLE
How should I use less-loader

### ISSUE THREAD

**Issue by bigrocs** [JeffreyWay/laravel-mix#308]
import less
![qq 20170206153353](https://cloud.githubusercontent.com/assets/15796287/22638205/93ce499e-ec81-11e6-8a84-7e3036156d96.png)

I saw webpack configured less-loader
![qq 20170206153730](https://cloud.githubusercontent.com/assets/15796287/22638266/f1c24f00-ec81-11e6-9793-69cfcfdc3ed6.png)

**Comment by JeffreyWay** [comment]
Do mix.less() to load your styles.
