### ISSUE TITLE
Mix Script Execution Weird Behavior

### ISSUE THREAD

**Issue by gabenz** [JeffreyWay/laravel-mix#309]
I am writing a mix script, these are the lines I used:
```

mix.sass('sass/app.scss', 'bundle1.css');

mix.less('less/app.less', 'bundle2.css');

mix.combine(['css/app.css'], 'bundle3.css');

mix.combine(['bundle2.css', 'bundle1.css', 'bundle3.css'], 'bundle.css');
```

the problem is every time I run 'npm run dev' ( all bundles not created yet ) it will complain that bundle2.css not exist

```
assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: Mix.combine() error: "bundle2.css does not exist.
```

and then I would comment out the fourth line that combine them all, and run again, it will success.  and then enable the fourth line and execute again, it will success now (because bundle2.css now exist).

my observation is, the fourth line would be executed first, since it produce the error, but that is very weird, isn't this script suppose to be executed sequentially? and I also run into a couple times when the first line of the script is not executed, skipped to second line.

for the record, this is the script I used, just that I removed the paths from them.

regards

**Comment by forehalo** [comment]
seems that mix should not verify `combine` arguments immediately, but after all compilations finished.

[src/index.js](https://github.com/JeffreyWay/laravel-mix/blob/master/src/index.js#L144)

**Comment by gabenz** [comment]
hmmhh, seems that's the problem. anyway while I am still here, is there anyway we can have a something like `mix.delete` to remove file ( well I want to remove the `bundle1.css`, `bundle2.css` and `bundle3.css` ). we can do this with the gulp one.

regards

**Comment by JeffreyWay** [comment]
I've removed the part that fails if the source files don' exist.
