### ISSUE TITLE
extract ignores setPublicPath?

### ISSUE THREAD

**Issue by stephan-v** [JeffreyWay/laravel-mix#310]
I am using this in a custom built framework, not Laravel.

It seems like .extract() is ignore the public path I have set when it comes to the manifest. This is my mix code:

```js
mix.js('resources/assets/js/app.js', 'public/js')
  .sass('resources/assets/sass/app.scss', 'public/css')
  .setPublicPath('public')
  .extract(['vue'])
  .version();
```
This is the output I am getting:

![image](https://cloud.githubusercontent.com/assets/2384912/22640415/cb4279c4-ec52-11e6-8ecf-0f9fd1cf5413.png)

The manifest is getting written to `public/js/manifest` but this means it will create a `public/js` directory inside my public directory(the one supplied with setPublicPath).

Am I doing something wrong here?

Also if I move `vue` into a seperate vendor file how does it actually get removed from my main app.js file? It seems like it still shows up there.

### Edit

Currently fixed it by changing the path. It seems to end up directly in the public directory so I hardcoded `/js` for now and it works. Is it suppose to work this way or it something else going on?

From:
```js
if (Mix.js.vendor) {
    module.exports.plugins.push(
        new webpack.optimize.CommonsChunkPlugin({
            names: [Mix.js.base + '/vendor', Mix.js.base + '/' + 'manifest'],
            minChunks: Infinity
        })
    );
}
```
To:
```js
if (Mix.js.vendor) {
    module.exports.plugins.push(
        new webpack.optimize.CommonsChunkPlugin({
            names: [Mix.js.base + '/vendor', '/js/' + 'manifest'],
            minChunks: Infinity
        })
    );
}
```

> I have since updated to the latest version of `laravel-mix` and am now using version `0.6.3`.

Still experiencing this issue, except now the vendor file gets placed in `public/public` directory as well. Right next to the manifest.

### Edit 2

I have tried removing the `setPublicPath('public`) and it works fine. Except for the fact that in that case my mix-manifest.json it not being created inside my public directory but rather in the root of my project which is somewhat unwanted behavior as well.

### Edit 3

I tried my setup in Laravel and everything worked fine which seemed strange so I checked the laravel-mix code for cases where Laravel usage is being taken into account.

If I edit the `Mix.js` file from laravel-mix and change the initialize method everything works brilliantly.

From

`if (this.isUsingLaravel()) this.publicPath = 'public';`

To:

`this.publicPath = 'public';`

It seems the publicpath is getting set when you do setPublicPath in the mix file but not properly so that all files take it into account. The manifest acts strangely upon setPublicPath.

## Solution

After fiddling around with this for awhile I get everything working by using setPublicPath as the first method in the mix chain. Any other order and this won't work.

This might be obvious to some people but I think it might be a good thing to add to the documentation for people who are using this outside of a Laravel project.

**Comment by JeffreyWay** [comment]
Thanks for researching this. We'll add a note to make that more clear.
