### ISSUE TITLE
Compiling scss too many time

### ISSUE THREAD

**Issue by rorc** [JeffreyWay/laravel-mix#311]
After `npm run watch` and then if i modify and save scss files, compiling process is not less than 4 seconds... http://joxi.ru/a2XeBzEUYxE3Ag
With laravel-elixir (with same scss'es) this process was fast.

**Comment by JeffreyWay** [comment]
It looks your CSS file is pretty huge. Not much we can do there.

**Comment by rorc** [comment]
@JeffreyWay But earlier, with laravel-elixir, this compiling with same css files was maximum 0.3 seconds!

**Comment by JeffreyWay** [comment]
Webpack is doing more things than Gulp.

But I have a large project, and the watcher compiles everything down in less than a second. Seems like you have nearly a meg's worth of CSS. That's a lot.
