### ISSUE TITLE
Mix.extract breaks Vue-devtools Events

### ISSUE THREAD

**Issue by mark-vesterskov** [JeffreyWay/laravel-mix#315]
I've noticed that when using Mix.extract Vue Events do not show up in the Vue Devtools Events window. The events work, and listeners are receiving the event, but the event does not show up in the Vue Devtools.

Fresh laravel install, only changes are:

App.js:

```
require('./bootstrap');

window.Event = new Vue();

const app = new Vue({
    el: '#app',
});
```

Working version of webpack.mix.js:

```
const { mix } = require('laravel-mix');
mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css');
```

<img width="1680" alt="screen shot 2017-02-06 at 15 42 15" src="https://cloud.githubusercontent.com/assets/7515900/22651477/71c9d456-ec83-11e6-9354-eab888be5cbf.png">

Nonworking version of webpack.mix.js:

```
const { mix } = require('laravel-mix');
mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .extract(['vue']);
```
<img width="1680" alt="screen shot 2017-02-06 at 15 42 33" src="https://cloud.githubusercontent.com/assets/7515900/22651733/4209dfbc-ec84-11e6-9108-6db712305823.png">

As said before the events fire correctly, but Vue Devtools for some reason cannot see them. Any idea as to how this can be mitigated?

**Comment by JeffreyWay** [comment]
I tried it out, and can't reproduce this.

https://www.dropbox.com/s/d2wa0e0m3jcmvga/Screenshot%202017-02-08%2010.58.36.png?dl=0

Since everything is working for you, other than the Vue Devtools part, I'm assuming it's unrelated to Mix.

**Comment by itzikbenh** [comment]
I have no idea why, but I also had the same problem after switching to laravel-mix. 
In my case I didn't use extract. This is for sure related to laravel-mix as going back to my old config brings everything back to normal.
