### ISSUE TITLE
Windows Homestead Watchers

### ISSUE THREAD

**Issue by nickfederighi** [JeffreyWay/laravel-mix#32]
Just wanted to share an additional Windows/Homestead-related caveat/workaround that I encountered for anybody else who is having trouble with their configuration.

#### My Environment
- Windows 10, Homestead , VirtualBox 5.1.12
- Node 6.9.1
- NPM 3.10.8
- Laravel Mix 0.2.5
### File Watchers
When running `npm run dev` the files would compile properly, but no changes were being watched from the Windows side. Editing a file in the Windows environment didn't trigger a recompile. If I edited the same file in VIM on the virtual machine, everything recompiles as expected. To get around the fact that Windows changes weren't being seen, I added the `--watch-poll` flag to the `dev` and `hmr` scripts in my package.json. Polling isn't as efficient, however, so I'm wondering if anyone has any better workarounds?

**Comment by JeffreyWay** [comment]
Thanks! I'll add this to the FAQ.

**Comment by JeffreyWay** [comment]
Done: https://github.com/JeffreyWay/laravel-mix/blob/master/docs/faq.md
