### ISSUE TITLE
sw-precache integration?

### ISSUE THREAD

**Issue by gcshri** [JeffreyWay/laravel-mix#320]
Hi there, 

Any chance of the sw-precache being integrated into mix? 

https://github.com/goldhand/sw-precache-webpack-plugin

Would be nice cache versioned static assets (css / fonts / js) into a service worker cache.

Something like this.

    mix.js('resources/assets/js/app.js', 'public/js')
    	.autoload({
    		jquery: ['$', 'window.jQuery', 'jQuery'],
    		vue: ['Vue', 'window.Vue'],
    		axios: ['axios', 'window.axios'] 
        })
    	.sass('resources/assets/sass/app.scss', 'public/css')
    	.sass('resources/assets/sass/critical.scss', 'public/css')
    	.extract(['jquery', 'axios','vue', 'bootstrap-sass'])
    	.version()
        .sw-cache();

**Comment by JeffreyWay** [comment]
No plans, but can manually add support with mix.webpackConfig().

**Comment by olivM** [comment]
in fact it's pretty simple : 

var SWPrecacheWebpackPlugin = require('sw-precache-webpack-plugin');
mix.webpackConfig({
    plugins: [
    new SWPrecacheWebpackPlugin(
      {
        cacheId: 'myapp',
        filename: 'sw.js',
        maximumFileSizeToCacheInBytes: 4194304,
        minify: false,
        runtimeCaching: [{
          handler: 'cacheFirst',
          urlPattern: /fonts\/.*$/,
        }],
      }
    ),
    ]
});

which will precache css/app.css, js/app.js, mix-manifest.json   at load
and then precache all fonts/.*  at runtime

pretty awesome  !

i'll start working on a PR for laravel-mix implementation

**Comment by gcshri** [comment]
Did something like that, but with the sw-toolbox to allow for configurable cache sizes and times for different asset types on the /public folder.

**Comment by olivM** [comment]
could you share your implentation, so we find the best way to include it in Mix ?

**Comment by acacha** [comment]
ping to @gcshri  see olivM comment I'm also interested! Thanks!

**Comment by gcshri** [comment]
@acacha  major apologies for missing this one. Would recommend you check out https://workboxjs.org/ - far better integration / build options.

**Comment by cerw** [comment]
Anyone got the workboxPlugin working with Laravel Mix?

**Comment by Nathan4jesus** [comment]
Thanks @olivM ! After messing around trying to apply the tuto i found on this [blog](https://justmegareth.com/2017-07-15-progressive-web-app-in-laravel/?utm_source=learninglaravel.net),
Your above clue helped me to break through and get my code working !
