### ISSUE TITLE
Laravel Mix has error while coping the new complied files

### ISSUE THREAD

**Issue by libern** [JeffreyWay/laravel-mix#322]
It said, "The file could not be found." for the just complied file.

So how do I copy it to a new location after it has been complied?

**Comment by forehalo** [comment]
duplicate #309 

Trying to fix it.

**Comment by adriaanzon** [comment]
Does the output directory exist?

**Comment by JeffreyWay** [comment]
I don't think you can copy sequentially at the moment. The plugin we use performs all the copying asynchronously.

**Comment by nmfzone** [comment]
We need support on this. Hmm, let's wait.
