### ISSUE TITLE
Mix/webpack modules unable to bind to global jQuery when objects are dynamically created

### ISSUE THREAD

**Issue by gstoa** [JeffreyWay/laravel-mix#325]
I'm able to mix/compile my spark project resources where jQuery is globally available in app.js.  The problem I'm having is some of my jQuery modules are called on an ajax success and are not dynamically binding to the global jQuery object.  I've mix/webpacked the [flot chart](https://cdn.jsdelivr.net/jquery.flot/0.8.3/jquery.flot.min.js) jQuery modules into a ux-full.js, for example.  I then make an ajax call where on success I create and render this new chart like below: 

```
$.ajax({
                type: "GET",
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                data: {id: id},
                url: '../../getChart',
                success: function (data) {
                       ...many options set here from the return data object to populate this chart...

                       $.plot($("#sample"), data, options);
                etc..
```

When this page is rendered, the ajax call returns an error indicating that `$.plot is not a function` which make me believe that  the .plot is not binding to the global jQuery object as its being created dynamically.

My fully rendered page contains the app.js (including jQuery as a global) and ux-full.js (containing all of the mix'd flot*.js files) and assembled in the correct order as shown below: 

```
    <!-- JavaScript -->
    <script src="/js/app.js"></script>
    <script src="/js/ux-full.js"></script>

    this script below is injected when the page is rendered because the data is always different

        <script>
        $(document).ready(function() {
            var data = [[1, 12], [2, 25], [3, 4]];
            var options = {
                series: {
                    lines: { show: true },
                    points: { show: true }
                }
            };

            $.plot($("#sample"), data, options)
            ....
       });
      </script>
```

I used to be able to gulp everything, including jQuery, into a single file and this worked perfectly.  However, I'm just sure I'm missing something in being able to correctly associate this object with jQuery when it's being dynamically created.

**Comment by apocalyarts** [comment]
I guess I am having sort of the same problem. I am compiling my JS (which is working fine) but on top of it I am including an additional JS file for a WYSIWYG-editor that depends on jQuery but for some reason can't find it.

**Comment by gstoa** [comment]
I used the same scenario as described above but removed all of the complexities and variables associated with using the jQuery flot charting object and tested using a simple jQueryUI component.

Then scenario and issue remains the same:

1.  use a spark/laravel 5.4 install (or where app.js includes jQuery as global)
2. npm install --save jquery-ui-bundle
3. webpack .combine and .js as appropriate ('node_modules/jquery-ui-bundle/jquery-ui.xx')
4. verify that jqueryui is compiled into supporting css/js files (mine is ux-full.css/js)
5. assemble page resources adding app.js followed by ux-full.js
6. place a button (#opener) and div (#dialog) on the page
7. on page, make an ajax call to a controller where on success set #dialog.text('testing');

so far, so good, at least we know that jQuery is being called successfully.  Now it's time to dynamically call jQueryUI.

8. now that we know that jquery/ajax works, let's replace the on success test with a simple jqueryui component

```

 $.ajax({
                type: "GET",
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                data: {symbol: getsymbol},
                url: '../../getCharts',
                success: function (data) {
                   //$( "#dialog" ).text('testing');                    
                   $( "#dialog" ).dialog({
                        autoOpen: false,
                        show: {
                            effect: "blind",
                            duration: 1000
                        },
                        hide: {
                            effect: "explode",
                            duration: 1000
                        }
                    });

                    $( "#opener" ).on( "click", function() {
                        $( "#dialog" ).dialog( "open" );
                    });
                }
            });


```

Notice the error messaging `Uncaught TypeError: $(...).dialog is not a function` which again indicates that this dynamically created component is not binding to the global jQuery object.

**Comment by gstoa** [comment]
WFIW: the problem was simply that jquery-ui.js was not being compiled into the app.js and therefore not available globally.  Since I'm using laravel/spark/mix, the normal addition the require call to bootstrap.js was not grabbing the jquery-ui.js file.  I had to add this require to the app.js file as follows

```
require('spark-bootstrap');

require('./components/bootstrap');


require('../../../node_modules/jquery-ui-bundle/jquery-ui.min.js');


var app = new Vue({
    mixins: [require('spark')]
});

```

Now jquery-ui, and all of my other supporting jQuery modules are available for my dynamic calls.

**Comment by chriz74x** [comment]
@gstoa Hello. I am trying to make jquery-ui-bundle work too but your solution doesn't work. jquery-ui.js is being compiled into app.js still I get an error "autocomplete is not a function".
