### ISSUE TITLE
Fails to babelify arrow syntax on npm run production

### ISSUE THREAD

**Issue by wells** [JeffreyWay/laravel-mix#332]
I just tried out Laravel mix and found that it would compile without errors with `npm run dev` with a 5.15MB payload (okay for dev-ing). However, when I attempted to run `npm run production`, it failed on some arrow syntax in a .js file.

```
export function addRecords (records, newRecords, type) {
  if (!newRecords) {
    return
  }

  newRecords.forEach(newRecord => {
    addRecord(records, newRecord, type)
  })
}
```

And the error below refers to the `newRecords.forEach(newRecord => {` line above:

```
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
 95% emitting
 ERROR  Failed to compile with 1 errors

 error

/js/app.a25a2e810095631e31db.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./resources/assets/js/vuex/helpers.js:6,21][/js/app.a25a2e810095631e31db.js:5690,32]
```

In addition, the output size is 1.88MB, which is drastically larger compared to the 662 KB that Elixir outputs. Sorry but failing on ES2015 arrow syntax and doubling the output size are two deal breakers for me.

**Comment by JeffreyWay** [comment]
- What version of Node and NPM do you have installed?
- Are you using a custom .babelrc file in your project root?

**Comment by JeffreyWay** [comment]
What does your .babelrc file look like?

**Comment by wells** [comment]
```
{
  "plugins": ["transform-object-rest-spread"]
}
```

Probably need more, hey?

**Comment by JeffreyWay** [comment]
Yep. You're using a custom .babelrc file that doesn't specify ES2015 compilation. And now you're wondering why you're not getting ES2015 compilation. :)

```js
{
    "presets": [
        ["es2015", { "modules": false }],
    ],
    "plugins": [
        "transform-object-rest-spread"
    ]
}
```

**Comment by wells** [comment]
Doh! Thanks for the assist!

**Comment by wells** [comment]
Another note, including `sourceMaps()` in your `webpack.mix.js` file will double your production JS file output. I was getting 5MB with `npm run dev` and 1.8MB with `npm run production`. Once I removed the `sourceMaps()` call, everything went back to the same 662KB size produced by laravel elixir. 

Totally looking forward to using code splitting as well. Thanks @JeffreyWay
