### ISSUE TITLE
npm run dev got errors

### ISSUE THREAD

**Issue by cmzz** [JeffreyWay/laravel-mix#334]
version: ^0.5.0

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2

**Comment by JeffreyWay** [comment]
This doesn't help me. Please show me how to reproduce this error. And you should be able to scroll to reveal more of the error.

**Comment by n8-sd** [comment]
I too have had this error.

Recently updating node and npm but nothing different or unusual in that..
node: v6.9.5
npm: 4.1.2


```npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxx/xxx/xxx/npm-debug.log
```

**Comment by cmzz** [comment]
@n8-sd  See https://github.com/JeffreyWay/laravel-mix/issues/335  

That‘s my errors .  Are yours same as me..

**Comment by n8-sd** [comment]
@cmzz Sort of.

It's nothing to do with f/a or anything, it was working an now not, but that leads me to think its something coming in and failing, or my node / npm has broken down some how.

Will starting striping back until it compiles.
