### ISSUE TITLE
run npm hot got errors

### ISSUE THREAD

**Issue by cmzz** [JeffreyWay/laravel-mix#336]
mix version is 0.6.0

✗ npm run hot

      > @ hot /Users/zyxcba/www/taotaoe
      > node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js

      fallbackLoader option has been deprecated - replace with "fallback"
      loader option has been deprecated - replace with "use"
      Project is running at http://localhost:8080/
      webpack output is served from http://localhost:8080/
      404s will fallback to /index.html
       ERROR  Failed to compile with 4 errors

       error  in [name].[chunkhash].js

      Cannot use [chunkhash] for chunk in '[name].[chunkhash].js' (use [hash] instead)

       error

       error

       error

**Comment by Mathem8tic** [comment]
#338 I suspect **hot** was originally used in the scripts section of your package.json but perhaps it was changed.  See **hmr** instead.

**Comment by forehalo** [comment]
I guess you use `mix.version()` in your webpack.mix.js.

[webpack-cache](https://webpack.js.org/guides/caching/)

>Don’t use [chunkhash] in development since this will increase compilation time. Separate development and production configs and use [name].js for development and [name].[chunkhash].js in production.

Well, laravel-mix will use `[name].[chunkhash].js` when versioning which causes this error.

Comment out `.version()` when you developing.

See more [webpack-dev-server#377](https://github.com/webpack/webpack-dev-server/issues/377)

**Comment by cmzz** [comment]
@forehalo  Has no `.version()` its can run success.

    taotaoe git:(new-5.4-ok) ✗ npm run hot

    > @ hot /Users/zyxcba/www/taotaoe
    > node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js

    fallbackLoader option has been deprecated - replace with "fallback"
    loader option has been deprecated - replace with "use"
    Project is running at http://localhost:8080/
    webpack output is served from http://localhost:8080/
    404s will fallback to /index.html
     DONE  Compiled successfully in 7623ms

But when I request `http://localhost:8080/`, page show `Cannot GET /`

**Comment by JeffreyWay** [comment]
Duplicate thread. This is a known issue and will be fixed soon. :)

**Comment by stephan-v** [comment]
Is there any update on this? Currently I am stuck, because I am working with pages that have 100+ images so I can't turn off caching for development. This means I am forced to use versioning when running `npm run hot`. Unfortunately in version 0.9.2 it still does not work.

**Comment by Frondor** [comment]
@JeffreyWay why you keep closing issues without providing more info or even a fix?
I don't want to sound rude at all, but once in a while, every new installation of laravel becomes a headache for me because Laravel-mix has brought more problems than solutions.

This is a breaking bug actually.

**Comment by JeffreyWay** [comment]
I said it was a duplicate thread before closing. 

It was fixed.

**Comment by tesnim2018** [comment]
i have the same issues can you tell me how exactly you fixed it

**Comment by ruchern** [comment]
@tesnim2018 OP's Laravel Mix version is 0.6.0 and the current is 2.1. They are of totally different versions. Please open a new issue with your exact problems.
