### ISSUE TITLE
Issue #331 Not Resolved

### ISSUE THREAD

**Issue by 19peaches** [JeffreyWay/laravel-mix#337]
Jeffrey, issue #331 was closed and not resolved.

**Comment by 19peaches** [comment]
Used the latest tag 0.7.0 and still no app.js created when using version.

![screen shot 2017-02-07 at 11 23 19 am](https://cloud.githubusercontent.com/assets/1456472/22705242/084479aa-ed28-11e6-80cb-6db4756f025c.png)

**Comment by 19peaches** [comment]
`public/css` directory:

![screen shot 2017-02-07 at 11 27 39 am](https://cloud.githubusercontent.com/assets/1456472/22705385/8ed95922-ed28-11e6-8f72-0f3d2d6342c4.png)


`public/js` directory:

![screen shot 2017-02-07 at 11 27 56 am](https://cloud.githubusercontent.com/assets/1456472/22705416/9f09ebd6-ed28-11e6-84d1-0a71e09b0008.png)

**Comment by JeffreyWay** [comment]
I'll reopen that other thread.
