### ISSUE TITLE
[help] How to set a different base path for images?

### ISSUE THREAD

**Issue by maaxxicarvalho** [JeffreyWay/laravel-mix#339]
Hi,

I'm using the package as stand-alone and I need to change the base path for sass images.
I now I can change the `webpack.config.js` file but, I'm wondering if there's a better way to do that?
Maybe using the `mix.webpackConfig()` method? Otherwise, every time that I update the packaged I need to compare the package `webpack.config.js` against mine and merge the changes, I know, is not that hard but, if there's any way to save time, I'd prefer using that.
Thanks!

**Comment by kohenkatz** [comment]
Right now, the only way to do it is to copy `webpack.config.js` and modify it.

**Comment by kohenkatz** [comment]
@maaxxicarvalho See also #327

**Comment by maaxxicarvalho** [comment]
thanks for your answers @kohenkatz 
For now I'll just change the `publicPath` inside of the `webpack.config.js`.
Let's hope that the MR gets merged!

**Comment by mikeyb** [comment]
> Right now, the only way to do it is to copy webpack.config.js and modify it.

I pressed ctrl+c and nothing happens.  where would someone copy this file to?
