### ISSUE TITLE
TypeError: The "path" argument must be of type string, when running npm run prod in Laravel project 

### ISSUE THREAD

**Issue by felixoakz** [JeffreyWay/laravel-mix#3394]
-   Laravel Mix Version: 4.0.7
-   Laravel Framework 8.83.27 
-   Node Version v20.18.0 (already tried with latest, lts, 16...) 
-   NPM Version: 10.8.2
-   OS: arch linux

### Description:
When running $npm run prod to compile client code, I'm getting this error:
```
> prod
> npm run production

> production
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

DONE  Compiled successfully in 196ms                                                                                        9:18:40 AM

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at Object.isAbsolute (node:path:1228:5)
    at standardizeName (path-to-node-module/node_modules/@babel/core/lib/config/files/plugins.js:76:15)
    at resolveAlternativesHelper (path-to-node-module/node_modules/@babel/core/lib/config/files/plugins.js:81:28)
    at resolveAlternativesHelper.next (<anonymous>)
    at resolveStandardizedNameForRequire (path-to-node-module/node_modules/@babel/core/lib/config/files/plugins.js:159:16)
    at resolveStandardizedName (path-to-node-module/node_modules/@babel/core/lib/config/files/plugins.js:182:12)
    at path-to-node-module/node_modules/babel-merge/dist/index.js:24:24
    at Array.find (<anonymous>)
    at path-to-node-module/node_modules/babel-merge/dist/index.js:23:28
    at Array.reduce (<anonymous>)
    at mergeArray (path-to-node-module/node_modules/babel-merge/dist/index.js:20:36)
    at babelMerge (path-to-node-module/node_modules/babel-merge/dist/index.js:40:19)
    at path-to-node-module/node_modules/babel-merge/dist/index.js:60:26
    at Array.reduce (<anonymous>)
    at Function.value (path-to-node-module/node_modules/babel-merge/dist/index.js:58:49)
    at BabelConfig.generate (path-to-node-module/node_modules/laravel-mix/src/BabelConfig.js:11:22)
    at Object.babel (path-to-node-module/node_modules/laravel-mix/src/config.js:121:45)
    at FileCollection.babelify (path-to-node-module/node_modules/laravel-mix/src/FileCollection.js:58:34)
    at FileCollection.merge (path-to-node-module/node_modules/laravel-mix/src/FileCollection.js:36:31)
    at ConcatenateFilesTask.merge (path-to-node-module/node_modules/laravel-mix/src/tasks/ConcatenateFilesTask.js:18:37)
    at ConcatenateFilesTask.run (path-to-node-module/node_modules/laravel-mix/src/tasks/ConcatenateFilesTask.js:11:14)
    at CustomTasksPlugin.runTask (path-to-node-module/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:36:14)
    at path-to-node-module/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:12:44
    at Array.forEach (<anonymous>)
    at path-to-node-module/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:12:23
    at AsyncSeriesHook.eval [as callAsync] (eval at create (path-to-node-module/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at AsyncSeriesHook.lazyCompileHook (path-to-node-module/node_modules/tapable/lib/Hook.js:154:20)
    at path-to-node-module/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (path-to-node-module/node_modules/webpack/lib/Compiler.js:499:39)
    at path-to-node-module/node_modules/webpack/lib/Compiler.js:298:10
    at path-to-node-module/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (path-to-node-module/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (path-to-node-module/node_modules/tapable/lib/Hook.js:154:20)
```

It doesnt compile sucessfuly. Some files get changed and webpack.mix.js gets wiped out.

```
"scripts": {
  "prod": "npm run production",
  "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
}
```

package.json:

```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "@prettier/plugin-php": "^0.20.1",
        "axios": "^0.19",
        "cross-env": "^5.1",
        "laravel-mix": "^4.0.7",
        "lodash": "^4.17.13",
        "prettier": "^3.0.3",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.15.2",
        "sass-loader": "^7.1.0",
        "vue-template-compiler": "^2.7.14"
    }
}
```
I do not have much experience with the framework nor mix. Sorry if I can't formulate the question any better. Please ask for more info if needed. Appreciate any help in advance.

### Already tried:

Starting the project fresh, updating/downgrading Laravel-mix, webpack, cross-env, rm node modules and package-lock.json and reinstalling them.
running npm cache clean --force
setting $ export NODE_OPTIONS=--openssl-legacy-provider
setting environment variables
Searched the whole web for solutions, this repo issues included. Just found similar answers and solutions that didn't work out for me.

### Steps To Reproduce:
For me its running $npm run prod to compile code in a laravel project with laravel mix.

**Comment by narom4** [comment]
I encountered the same issue, and I’d like to share what I’ve found so far.

It seems that the issue is related to laravel-mix having a dependency on @babel/core, which released a new version [2 days ago](https://www.npmjs.com/package/@babel/core?activeTab=versions), version `7.25.7`

In `laravel-mix` v4 [package.json](https://github.com/laravel-mix/laravel-mix/blob/v4/package.json), it lists the following dependency:
```json
    "dependencies": {
        "@babel/core": "^7.2.0",
        // other dependencies
    }
```

So, unless you explicitly specify a version in your project’s package.json, laravel-mix will automatically pull the latest version.

I temporarily fixed the compilation issues by specifying the previous version of @babel/core in my package.json like this:

```json
    "dependencies": {
        "@babel/core": "7.25.2",
        // other dependencies
    }
```

After doing that, everything went back to normal.

Let’s wait and see if laravel-mix releases a patch.

**Comment by eduhrcastro** [comment]
I has a same problem here. I specified a version of babel in my project but not work it.  

If you look in package.json from laravel-mix v4, it's defined @babel/core version to use 7.2.0 and not a latest version. I mean that solution is not it.

I'll update Laravel Mix for the lastest version because I can't wait of this fix. 😕

**Comment by lanuma** [comment]
Using `"@babel/core": "7.25.2"` works in my case

```
"dependencies": {
        "@babel/core": "7.25.2",
        // other dependencies
    }
```

**Comment by Xieweikang123** [comment]
> I encountered the same issue, and I’d like to share what I’ve found so far.
> 
> It seems that the issue is related to laravel-mix having a dependency on @babel/core, which released a new version [2 days ago](https://www.npmjs.com/package/@babel/core?activeTab=versions), version `7.25.7`
> 
> In `laravel-mix` v4 [package.json](https://github.com/laravel-mix/laravel-mix/blob/v4/package.json), it lists the following dependency:
> 
> ```json
>     "dependencies": {
>         "@babel/core": "^7.2.0",
>         // other dependencies
>     }
> ```
> 
> So, unless you explicitly specify a version in your project’s package.json, laravel-mix will automatically pull the latest version.
> 
> I temporarily fixed the compilation issues by specifying the previous version of @babel/core in my package.json like this:
> 
> ```json
>     "dependencies": {
>         "@babel/core": "7.25.2",
>         // other dependencies
>     }
> ```
> 
> After doing that, everything went back to normal.
> 
> Let’s wait and see if laravel-mix releases a patch.

it is work for me, thank you

**Comment by fredpen** [comment]
> I encountered the same issue, and I’d like to share what I’ve found so far.
> 
> It seems that the issue is related to laravel-mix having a dependency on @babel/core, which released a new version [2 days ago](https://www.npmjs.com/package/@babel/core?activeTab=versions), version `7.25.7`
> 
> In `laravel-mix` v4 [package.json](https://github.com/laravel-mix/laravel-mix/blob/v4/package.json), it lists the following dependency:
> 
> ```json
>     "dependencies": {
>         "@babel/core": "^7.2.0",
>         // other dependencies
>     }
> ```
> 
> So, unless you explicitly specify a version in your project’s package.json, laravel-mix will automatically pull the latest version.
> 
> I temporarily fixed the compilation issues by specifying the previous version of @babel/core in my package.json like this:
> 
> ```json
>     "dependencies": {
>         "@babel/core": "7.25.2",
>         // other dependencies
>     }
> ```
> 
> After doing that, everything went back to normal.
> 
> Let’s wait and see if laravel-mix releases a patch.

This works for me.
Thank you

**Comment by felixoakz** [comment]
I'm just going to close this issue, as thanks to @narom4 we have a quick and temporary fix:

- Just set babel/core version to 7.25.2 in package.lock for now

It looks like the lib wont getting updates anytime soon anyways.
