### ISSUE TITLE
nodejs v23.1.0  not creating public/mix-manifest.json

### ISSUE THREAD

**Issue by it-can** [JeffreyWay/laravel-mix#3396]
-   Laravel Mix Version: 6.0.49
-   Node Version (`node -v`): v23.1.0
-   NPM Version (`npm -v`): 10.9.0
-   OS: mac os / linux

### Description:
i upgrade to node v23.1.0 and ran `npm run mix --production` and it doesnt create the public/mix-manifest.json file.
`npm run development` does seem to work and creates the file.

### Steps To Reproduce:
1. remove public/mix-manifest.json file
2. install node v23.1.0 
3. run mix

on node v22 it does work

**Comment by stefanocurnis** [comment]
it also quits before the ending of the build process and gives no error message.

**Comment by it-can** [comment]
it seems that nodejs v23.2.0 works correct again
