### ISSUE TITLE
[help] There's a way to compile SASS and combine CSS?

### ISSUE THREAD

**Issue by maaxxicarvalho** [JeffreyWay/laravel-mix#340]
I need to compile my SASS files and later combine with some third party CSS files, I'm using the code bellow but sometimes my Docker environment gets crazy.

```javascript
mix.js(['js/src/smoke.js'], 'public/js/smoke.js')
    .sass('sass/app.sass', 'css/app.css')
    .combine([
        'node_modules/flickity/css/flickity.css',
        'css/app.css'
    ], 'app.css');
```

**Comment by nmfzone** [comment]
What do you mean "gets crazy"? You must provide some explanation about it :/
I guess you must use a different name on combined file.

**Comment by maaxxicarvalho** [comment]
it seems that the issue is related to Nginx configuration, so the following was necessary:
**it only happens when using: `npm run watch`**

```
...
sendfile        off;
...
```

the 'strange' part is that before I was using laravel-mix version 5.x.x and I had CSS url lookup turned off, and the issue wasn't happening.

**Comment by JeffreyWay** [comment]
Hmm okay. Good to know. Glad you got it figured out.

**Comment by kinnedev** [comment]
@maaxxicarvalho were you able to fix this with in Valet?

**Comment by maaxxicarvalho** [comment]
Hi @kinnedev I'm not using Valet so, unfortunately, I cannot tell about it.
