### ISSUE TITLE
Code Splitting js path error

### ISSUE THREAD

**Issue by stevieyu** [JeffreyWay/laravel-mix#343]
```
Vue.component('example', System.import('./components/Example.vue'));
```

0.js file is not in the js folder inside

![image](https://cloud.githubusercontent.com/assets/8325201/22726576/14cc267c-ee0f-11e6-8b2b-9876331ee29f.png)

**Comment by strebl** [comment]
I have the same problem.

**Comment by strebl** [comment]
@stevieyu Here a temporary workaround:

Add following code after the line `module.exports.output = Mix.output();` to your `webpack.config.js`:
```js
if (!Mix.hmr) {
    module.exports.output.chunkFilename = 'js/' + module.exports.output.filename;
}

```

**Comment by stevieyu** [comment]
hmr run Is there a problem?

**Comment by ramakrishnamundru** [comment]
@JeffreyWay is it possible to fix this in next release, for now we have to keep a separate copy of `webpack.config.js` for only this reason.

**Comment by JeffreyWay** [comment]
@ramakrishnamundru Yes, it's in the next release.
