### ISSUE TITLE
mix.combine fails if to combine files should be generated with mix.sass before

### ISSUE THREAD

**Issue by sabinekunkel** [JeffreyWay/laravel-mix#352]
- Laravel Mix Version: 0.7.0
- Node Version (`node -v`): v7.5.0
- NPM Version (`npm -v`): 4.1.2
- OS: Windows 10 (64)

### Description:
I've updated my Laravel-Project from 5.3 to 5.4. So I make a change from laravel-elixir to laravel-mix.

**In my new webpack.mix.js I try to make the following steps:**
compile SASS (mix.sass)
combine before compiled SASS -> CSS with other existing css Files. (mix.combine)

**The Result:**
First Time I start "**npm run dev**" the CSS Files I wand to combine don't exists 
(I want to build them with mix.sass).

If I start the process an error that the Files I want to combine don't exists appear.
In the webpack.mix.js mix.sass was called before mix.combine.

As Workaround I make a File Check with "mix.config.File.exists(..)" for the mix.combine Process.
In this case the mix.sass starts correctly, but nothing will be combined.
I've to start "npm run dev" a secod time to make a complete process.

Additional Hint: If I try to use the Helper Function mix.File I've got the error "undefined".
I can use it with mix.config.File - maybe I mak a mistake?

**Comment by nmfzone** [comment]
Use version 0.7.4 instead.

**Comment by JeffreyWay** [comment]
The order of your method calls in webpack.mix.js are not triggered sequentially. So anything you pass to mix.combine() will be triggered after Webpack has fully compiled.
