### ISSUE TITLE
This dependency was not found in node_modules

### ISSUE THREAD

**Issue by micheleivani** [JeffreyWay/laravel-mix#355]
I'm developing a WordPress plugin and I want to use laravel-mix for my js and css. WordPress adds jQuery automatically so I can use it inside my script.

In my main script I simply have:
```
(function( $ ) {
    'use strict';
    
    // ...
})( jQuery );
```
When I run `npm run dev` I got an error: `This dependency was not found in node_modules: * jquery`

I know that I have not jquery inside my node dependencies, but I do need that because WordPress already pulled it for me.

How can I fix the issue?

Thank you.

**Comment by JeffreyWay** [comment]
Can you add `mix.autoload({})` to your webpack.mix.js file and let me know if that changes things?

**Comment by micheleivani** [comment]
@JeffreyWay It works! 👍 Thank you.
