### ISSUE TITLE
[chunckhash] cannot be used with hmr

### ISSUE THREAD

**Issue by michaeldzjap** [JeffreyWay/laravel-mix#357]
- Laravel Mix Version: 0.7.2
- Node Version (`node -v`): 7.4.0
- NPM Version (`npm -v`): 4.0.5
- OS: macOS 10.12.2

### Description:
When running laravel-mix in hmr mode (having this as the command in scripts in my package.json: `"hmr": "cross-env NODE_ENV=development webpack-dev-server --inline --hot"`) and the following in my webpack.mix.js:
```
mix.js('resources/assets/js/app.js', 'dist/')
  .extract(['react'])
  .sass('resources/assets/sass/app.scss', 'dist/')
  .version();
```
I get the following error:
```
error  in [name].[chunkhash].js

Cannot use [chunkhash] for chunk in '[name].[chunkhash].js' (use [hash] instead)
```
I've done a Google search (obviously) and I found this issue which seems related:
[Cannot use 'chunkhash' in webpack dev server](https://github.com/webpack/webpack/issues/2393
)

So it seems that 'chunkhash' cannot be used in conjunction with `webpack-dev-server --inline --hot`. I can confirm that the other modes dev, watch and production given respectively by
```
...
"dev": "cross-env NODE_ENV=development webpack --progress --hide-modules",
"watch": "cross-env NODE_ENV=development webpack --watch --progress --hide-modules",
"production": "cross-env NODE_ENV=production webpack --progress --hide-modules",
...
```
do not throw this error.

### Steps To Reproduce:
1 - use `version()` to append a hash to any bundled files
2 - use hot module replacement `cross-env NODE_ENV=development webpack-dev-server --inline --hot`

Thanks

**Comment by TomKita** [comment]
See #153.

But just remove `.version()`

**Comment by michaeldzjap** [comment]
Yes, it's the same. Thanks for pointing in that direction. I missed that issue on first sight.

**Comment by sebastiandedeyne** [comment]
How is that a solution? What if I want versioning in my project and want to use HMR? I need to comment out the `.version()` call every time?
