### ISSUE TITLE
output error on windows 10

### ISSUE THREAD

**Issue by sinchang** [JeffreyWay/laravel-mix#358]
- Laravel Mix Version: 0.7.4
- Node Version (`node -v`): 7.4.0
- NPM Version (`npm -v`): 4.2.0
- OS: Windows 10

### package.json
```
{
  "name": "webpack-demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack --progress --hide-modules",
    "watch": "cross-env NODE_ENV=development webpack --watch --progress --hide-modules",
    "hmr": "cross-env NODE_ENV=development webpack-dev-server --inline --hot",
    "production": "cross-env NODE_ENV=production webpack --progress --hide-modules"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-preset-es2015": "^6.22.0",
    "laravel-mix": "^0.7.4",
    "webpack": "^2.2.1"
  }
}
```
### Description:
when run `npm run dev`,compiled successfully, output not app.js but mix.js,look the image below for details.

![](https://ooo.0o0.ooo/2017/02/10/589d73b4522bd.png)

project files download: http://sinchang.qiniudn.com/webpack-demo.zip

**Comment by forehalo** [comment]
Have you rightly installed `laravel-mix`? There should not be such a small quantity of dependencies installed in `node_modules`.

A fresh project with your code runs successfully.

![image](https://cloud.githubusercontent.com/assets/8281226/22820203/ae9df7d8-efb0-11e6-96f4-f86d1a804d1f.png)

**Comment by sinchang** [comment]
@forehalo thanks, reinstall laravel-mix on a new PC is working now.
