### ISSUE TITLE
TypeError: this.preparePath is not a function when building

### ISSUE THREAD

**Issue by randohinn** [JeffreyWay/laravel-mix#360]
- Laravel Mix Version: latest from npm
- Node Version (`node -v`): 6.2.2
- NPM Version (`npm -v`): 4.3.0
- OS: Windows 10

### Description:
When running any of the npm commands for building, using a simple mixfile such as `
mix.js('./live.js', './dist/live.js');` Gives back the error of: 

```
TypeError: this.preparePath is not a function
    at flattenedPaths.forEach.path (E:\Webdev\jellyrue-contentful\public\node_modules\laravel-mix\src\Manifest.js:73:25)
```

### Steps To Reproduce:

Install latest and try building.

**Comment by davidangel** [comment]
I'm experiencing the same issue.

 - Laravel Mix Version: 0.7.4
 - Node Version (node -v): 7.2.1
 - NPM Version (npm -v): 3.10.10
 - OS: macOS 10.12.3

**Comment by davidangel** [comment]
@randohinn – fwiw, in the meantime, I've fallen back to v0.5.9 to get the build working.

**Comment by JeffreyWay** [comment]
Can either of you give me steps to reproduce this error? 

Or can you open this file

```
node_modules\laravel-mix\src\Manifest.js:73:25
```

and figure out why it's saying `preparePath` is not a function? Do a `console.log(this)`.

**Comment by davidangel** [comment]
`console.log(this)`
```
{ filename: 'mix-manifest.json',
  fields: [ 'assetsByChunkName' ],
  transform: [Function: transform] }
```

**Comment by davidangel** [comment]
My mix setup is in the root of a symfony app:

```
mix.setPublicPath('web');
mix.js('path/to/my.js', 'assets/js');
```

**Comment by JeffreyWay** [comment]
I'm guessing that you guys copied our webpack.config.js file to your project root? If so, you need to update it to reflect what we currently have. 

https://raw.githubusercontent.com/JeffreyWay/laravel-mix/master/setup/webpack.config.js

Specifically, make sure that the `StatsWriterPlugin` section has this:

```js
    new plugins.StatsWriterPlugin({
        filename: 'mix-manifest.json',
        transform: Mix.manifest.transform.bind(Mix.manifest),
    }),
```

**Comment by davidangel** [comment]
That was indeed the problem. Thanks @JeffreyWay! If I'm not planning on using any custom configurations in `webpack.config.js` for now, do you think aliasing to yours is a bad idea?

**Comment by JeffreyWay** [comment]
If you have no plans to modify webpack.config.js, yes, definitely link to ours.

```
webpack --config="node_modules/laravel-mix/setup/webpack.config.js"
```

**Comment by randohinn** [comment]
Wonderful, works again!
