### ISSUE TITLE
Vue components DOM only seem to render once

### ISSUE THREAD

**Issue by Akhawais** [JeffreyWay/laravel-mix#361]
- Laravel Mix Version: 0.7.4
- Node Version: 6.9.1 
- NPM Version 3.10.8
- OS: Windows 10 (64-bit)

### Description:
The DOM in Vue single file components only seem to render once. The virtual tree seems to update just fine when a property or data is changed (by using Vuejs Devtools), however it seems that the DOM doesn't render these changes and `.$forceUpdate();` has no effect either.

### Steps To Reproduce:
```Vue
<template>
    <div>
        {{ a }}
        <template v-for="i in a">
            <div>Test - {{ i }}</div>
        </template>
    </div>
</template>
<style>
</style>
<script>
    import Vue from 'vue'
    export default{
      data () {
        return {
          a: 5
        }
      },
      mounted () {
        var self = this
        setTimeout(function () {
          Vue.set(self, 'a', 1)
        }, 5000)
      },
      updated () {
        console.log(this.a)
      }
    }
</script>
```
Test.vue

1. In a Laravel installation, add this file into `/resources/assets/js/components`
2. In the `/resources/assets/js/app.js` add `Vue.component('test', require('./components/Test.vue');`
3. In a HTML file that includes `app.js` add in `<test></test>`

You should then see:
```
5
Test - 1
Test - 2
Test - 3
Test - 4
Test - 5
```

### Expected result from here:
After 5 seconds, `a = 1` and the DOM updates to:
```
1
Test - 1
```

### Actual result:
After 5 seconds, `a = 1` (verified by console output and devtools) but the DOM doesn't update.

---

Using `vue-cli` I have created a clean Vue app and the same `Test.vue` file works just fine, leading me to believe this is an issue with Mix.

Thanks.

**Comment by Akhawais** [comment]
I've just tried again, using `Vue.component` in my `app.js` and that has the same issue as single-file components. But works if I call the same `Vue.component` code in my blade file.

**Comment by JeffreyWay** [comment]
I just followed your steps and, after five seconds, your expected results were exactly what I saw. 

https://www.dropbox.com/s/jikef9id49wsi0f/Screenshot%202017-02-16%2000.24.03.png?dl=0

So I'm assuming it's not a Mix issue.
