### ISSUE TITLE
Enhancement: Enable preservation of copyright comment on JS files

### ISSUE THREAD

**Issue by thepenguin1** [JeffreyWay/laravel-mix#365]
My guess is, that this is just a flag that you can set on the underlying UglifyJS?

Could it be added please, because presently copyright comments are stripped from JS files. CSS files retain their copyright notice with: `/*!`

**Comment by poldon** [comment]
I'm running v4.1.14, and this still seems to be an issue with JS files.  I'm happy to set an option myself, but with all the conflicting info out there, I have yet to find the right option and the right location.  Thanks.
