### ISSUE TITLE
Reload for any file changes as like BrowserSync

### ISSUE THREAD

**Issue by hasnat-babur** [JeffreyWay/laravel-mix#371]
Thanks a lot for making this. Currently page only refresh on JavaScript changes. Can we get a feature that refreshes page for css, php, blade file changes as like BrowserSync does. Thanks

**Comment by JeffreyWay** [comment]
Are you using Mix in a Laravel project, or something unrelated? If unrelated, you'll need to specify which file paths should be watched.

```js
// https://browsersync.io/docs/options/
mix.browserSync({
    proxy: 'my-domain.dev',
    files: ['paths/here/**/*.php']
})
```

Otherwise, for Laravel projects, it should automatically watch all relevant directories.

**Comment by stephan-v** [comment]
Could this be added to the documentation? I just stumbled into this issue myself.

**Comment by Yard8** [comment]
Thanks @JeffreyWay that helped me out greatly! I have been banging my head against a wall until i found that.
