### ISSUE TITLE
mix.combine created additional mix-manifest.json

### ISSUE THREAD

**Issue by gabenz** [JeffreyWay/laravel-mix#372]
- Laravel Mix Version: 0.7.4
- Node Version (`node -v`): v7.5.0
- NPM Version (`npm -v`): 4.1.2
- OS: Ubuntu 16.04

### Description:

I am still using the same script from issue [#309](https://github.com/JeffreyWay/laravel-mix/issues/309), after the  compile succeed, I notice that there are 2 `mix-manifest.json` generated, one on the root folder with content: 
```
{
  "/vendor.js": "/vendor.js",
  "/app.js": "/app.js",
  "/bundle1.css": "/bundle1.css",
  "/bundle2.css": "/bundle2.css",
  "/manifest.js": "/manifest.js",
  "public/vendor/module/app.css": "public/vendor/module/app.css"
}
```
and  another one on the `public/vendor/module`:
```
{
  "/vendor.js": "/vendor.js",
  "/app.js": "/app.js",
  "/bundle1.css": "/bundle1.css",
  "/bundle2.css": "/bundle2.css",
  "/manifest.js": "/manifest.js"
}
```
edit: I also use this in the `webpack.config.js`:
```
module.exports.output = {
	filename: "[name].js",
	path: path.join(__dirname, 'public', 'vendor', 'module'),
	publicPath: "/vendor/module/"
};
```

### Steps To Reproduce:
using this in `webpack.mix.js`:
```
mix.sass('sass/app.scss', 'bundle1.css');
mix.less('less/app.less', 'bundle2.css');
mix.combine(['css/app.css'], 'bundle3.css');
mix.combine(['bundle2.css', 'bundle1.css', 'bundle3.css'], 'bundle.css');
mix.js('app.js', 'app.js')
```

**Comment by JeffreyWay** [comment]
I can't reproduce this, and assume it's related to you modifying our webpack.config.js file. You shouldn't change the output.

Also, for readability, it's best to use absolute paths for all of your webpack.mix.js file paths.
