### ISSUE TITLE
Can't override webpack rules/loaders

### ISSUE THREAD

**Issue by phanan** [JeffreyWay/laravel-mix#374]
- Laravel Mix Version: 0.7.4
- Node Version: v6.9.1
- NPM Version: 3.10.8
- OSX El Capitan

So the doc says we can override webpack's configurations with either a `webpack.config.js` at root dir or via `mix.webpackConfig(config)`, but for the life of me, I can't override the loaders/rules. Due to my customized project structure, I wanted to override the generated font paths. This is what I'm trying to do:

``` js
mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.(woff2?|ttf|eot|svg|otf)$/,
                loader: 'file-loader',
                options: {
                    name: '../fonts/[name].[ext]?[hash]',
                    publicPath: '../foo/bar' // notice this customization
                }
            }
        ]
    }
});
```

Now if I'm not wrong, due to the way Mix is merging the config, the code above only _adds_ another rule into the set of rules, resulting in two very similar rules in Mix's webpack config, with the original rule still taking precedence. This results in the generated font paths always started with `/fonts` and break the app (well, at least visually).

Questions:

- Is the assumption above right or just me missing something obvious?
- How can I achieve the desired result?
- Should Mix really _merge_ the rules/loaders based on, for example, the `test` property?

**Comment by KristofMorva** [comment]
You can't override `rules` this way I think, you have to copy `webpack.config.js` and change it there.
If #353 gets accepted, copying the file won't be necessary anymore for the problem of `publicPath`.

**Comment by phanan** [comment]
Even with `webpack.config.js`, it's the same issue – I believe they share the same mechanism under the hood. Your PR looks great, though. Hope @JeffreyWay will merge it!

**Comment by KristofMorva** [comment]
@phanan if you are using the copy of the config file, don't forget to remove `--config=node_modules/laravel-mix/setup/webpack.config.js` from the end of package.json scripts, otherwise it'll keep using the original one.

**Comment by phanan** [comment]
@KristofMorva Oh I didn't notice that. Good to know, thanks!
