### ISSUE TITLE
mix.combine js

### ISSUE THREAD

**Issue by DevDuckEl** [JeffreyWay/laravel-mix#378]
- Laravel Mix Version: 0.7.5
- Node Version (`v6.9.5`): 
- NPM Version (`4.3.0`): 
- OS: Ubuntu 16.04

In elixir we can use .styles and .scripts. Is there a way to use also .combine in mix?

Elixir:
```javascript
elixir(mix => {
    mix.styles(['./resources/library/**/css/*.css'])
       .scripts(['./resources/library/**/js/*.js']);
});
```
Mix:
```javascript
mix.combine([
       './resources/library/**/js/*.js'
   ], 'public/js/all.js')
   .combine([
       'resources/library/**/css/*.css'
   ], 'public/css/all.css');
```
It works in the mix, but if we use ES-2015, `npm run production` is not working. Is there a way to resolve this?

**Comment by JeffreyWay** [comment]
I just pushed a commit to allow you to combine scripts, and then apply Babel compilation on the output. Once this is tagged, you can do `mix.babel(['src/files'], 'output/path');` 

`mix.babel()` is identical to `mix.combine()`, other than it also applies Babel to the output.
