### ISSUE TITLE
sass compiling errors

### ISSUE THREAD

**Issue by camiant** [JeffreyWay/laravel-mix#379]
- Laravel Mix Version: 0.7.5
- Node Version (`node -v`):  7.4.0
- NPM Version (`npm -v`): 4.0.5
- OS: Win10

### Description:

importing [vue-bulma-datepicker](https://github.com/vue-bulma/tooltip) as component returns an error about sass compiler

my code is 

```
import Tooltip from 'vue-bulma-tooltip'
Vue.component('tooltip', Tooltip)
```

and this is the error

```
 ERROR  Failed to compile with 1 errors

 error  in ./~/vue-bulma-tooltip/src/style.scss

Module parse failed: C:\XXX\laravel\node_modules\vue-bulma-tooltip\src\style.scss Unexpected character '@' (1:0)

You may need an appropriate loader to handle this file type.
```

### Steps To Reproduce:

npm install vue-bulma-tooltip
npm run hot

**Comment by nicolay-zlobin** [comment]
The same error..

**Comment by nicolay-zlobin** [comment]
Thank you )
