### ISSUE TITLE
Order of vendor loading

### ISSUE THREAD

**Issue by matthijs110** [JeffreyWay/laravel-mix#38]
I am using Bootstrap-sass (laravel). This requires jQuery. When I load the page, it keeps saying that bootstrap-sass needs jQuery, even though it has been loaded. However, jQuery comes after Bootstrap in `vendor.js`.

This is my mix:
```js
mix.js('resources/assets/js/app.js', 'public/js')
   .extract(['jquery', 'vue', 'vue-cookie', 'vue-resource', 'axios', 'lodash', 'moment', 'autosize', 'bootstrap-sass'])
   .sass('resources/assets/sass/app.scss', 'public/css');
```

Is there a way to load jQuery first?

Also.. The Vue interceptor gives a `Uncaught TypeError: Cannot read property 'interceptors' of undefined` error:
```js
Vue.http.interceptors.push((request, next) => { // Here
    request.headers.set('X-CSRF-TOKEN', Laravel.csrfToken);

    next();
});
```

Vue is being defined in the laravel `bootstrap.js`. Will this compile automaticly? I require it inside `app.js`.

**Comment by angelside** [comment]
Jquery is loaded but somehow bootstrap can't see this. I can't figure out yet.

My temporary fix is modify webpack.config.js

```javascript
module.exports.plugins.push(
    new webpack.ProvidePlugin({
        $: 'jquery',
         jQuery: 'jquery',
         jquery: 'jquery',
        "window.jQuery": "jquery",
        "window.Tether": "tether"
    })
);
```

**Comment by matthijs110** [comment]
jQuery is defined already inside `bootstrap.js`:
```js
window.$ = window.jQuery = require('jquery');
```

**Above** 
```js
require('bootstrap-sass');
`

**Comment by JeffreyWay** [comment]
Fixed. I added the ProvidePlugin to our default `webpack.config.js`.

**Comment by matthijs110** [comment]
Great! Thank you very much!

**Comment by jonathanpmartins** [comment]
I came across some similar problem. It seems that when I use extract on 'vue-resource' and 'vue', 'vue-resource' loads first no matter what.
For now to solve the problem:
 - or I leave everything to be compiled in the app.js file and dont extract anything, so the order of loading is respected. 
 - or I simple extract 'vue' and leave 'vue-resource' to be loaded on compilation of the app.js file.
I have a bunch of vendor libraries that I like to order the load, but I dont know how.
Do someone have came across something similar?

**Comment by jonathanpmartins** [comment]
well, 10 minutes after I figure out that I can do this before the interceptor code
```
Vue.use(require('vue-resource'));
```
Tip came from laracast blog: https://laracasts.com/discuss/channels/vue/vue-resource-cannot-read-property-http-of-undefined

But the order of loading using extract method is not clear.

**Comment by jeff-h** [comment]
Any chance mix could respect the order the vendor libraries are specified in the `extract` array? I don't think this problem is going to go away — I'm using Bootstrap 4, which depends on Tether, and their order is wrong in my `vendors.js`.

If I could fix this by putting tether first in my extract array, it would be great!

```js
   .extract(['tether', 'bootstrap', 'axios', 'vue'])
```

**Comment by amin101** [comment]
the issue hasn't been solved yet. i need jquery to be loaded before owl.carousel but i cant

**Comment by renegaed** [comment]
+1 this please feature to be implemented. Thank you

**Comment by solicomo** [comment]
This issue is still there in v0.9.2.

jQuery is after Bootstrap in the vendor.js.

**Comment by kohei0302** [comment]
I solved in this way
```
  .extract(['lodash', 'jquery', 'bootstrap', 'axios'])
  .autoload({
    jquery: ['$', 'window.jQuery', 'jQuery', 'jquery'],
  })
```

**Comment by gocanto** [comment]
Hey, @kohei0302 this fixed the problem for me as well. The weird thing is I did not have this in another app and still it worked. 

Any thoughts about it?

**Comment by nmfzone** [comment]
This isn't an issue, It's just because since `0.9.0` (I think), jQuery has been removed from Webpack Provided plugin. See here `https://github.com/JeffreyWay/laravel-mix/commit/82004419296f0359bd6ca2fb49f64c8135db3268`.
