### ISSUE TITLE
Non-versioned css/js files removed

### ISSUE THREAD

**Issue by sdebacker** [JeffreyWay/laravel-mix#380]
- Laravel Mix Version: 0.7.5
- Node Version (`node -v`): 7.5.0
- NPM Version (`npm -v`): 4.1.2
- OS: macOS 10.12.3

### Description:

I have this code in webpack.mix.js:
```javascript
const { mix } = require('laravel-mix');

mix.sass('resources/assets/sass/app.sass', 'public/css');

mix.js('resources/assets/js/app.js', 'public/js');

if (mix.config.inProduction) {
    mix.version();
}
```
When I run ```npm run dev```, I have an app.js and app.css files; then if I run ```npm run production```, I have my two versioned files, but app.js and app.css are deleted. Is it the intended behavior ? Is it possible to keep the non versioned files ? Because in my CKEditor config file, I need to give the css filename to load in the iframe.

Thanks in advance.

**Comment by JeffreyWay** [comment]
Yes, it's intended behavior. Sorry about that.
