### ISSUE TITLE
Cannot reference modules from /node_modules

### ISSUE THREAD

**Issue by neutt22** [JeffreyWay/laravel-mix#382]
- Laravel Mix Version: 0.7.2
- Node Version (`node -v`):  v4.2.6
- NPM Version (`npm -v`):  4.0.5
- OS: Ubuntu 16.04

### Description:
Unable to compile SCSS due to Foundation cannot be referenced from node_modules/foundation-sites/scss/foundation

### Steps To Reproduce:
* Add "foundation-sites": "^6.3.0" as project dependencies
* from app.scss, add @import "foundation-sites/scss/foundation"
* Run npm run dev

Am i missing something?

**Comment by lasseal** [comment]
What error do you get?

**Comment by JeffreyWay** [comment]
Add a tilda before your import. Otherwise, it's going to look for `foundation-sites/scss/foundation`, relative to the current file. Instead, do:

```
@import '~foundation-sites/scss/foundation';
```
