### ISSUE TITLE
How do I pass options into minify() or version()?

### ISSUE THREAD

**Issue by phanan** [JeffreyWay/laravel-mix#383]
- Laravel Mix Version: 0.7.4
- Node Version: v6.9.1
- NPM Version: 3.10.8
- OSX El Capitan

### Description:

(Sorry if this isn't the proper platform for these questions).

I'm using [plyr](https://plyr.io) in one of my projects. To my surprise, the styles applied on my local version 

![image](https://cloud.githubusercontent.com/assets/8056274/22962940/17d4c8ac-f38b-11e6-8e1e-a8548bc2005d.png)

are quite different from their production counterpart:

![image](https://cloud.githubusercontent.com/assets/8056274/22962951/244fa426-f38b-11e6-9cab-3f812fbad5c2.png)

I dug a bit deeper into the code and, apparently, all those `::-webkit-progress-*` styles aren't applied on production somehow, resulting in the default green background. Further explorations reveal clean-css has a [bug](https://github.com/jakubpawlowicz/clean-css/issues/693) that can be worked around with `{ restructuring: false }`. Now how do I pass this configuration into `minify()` or `version()` and see if it works? I don't see an option to customize the two functions' settings. Oddly enough, directly modifying Mix's source files and passing the option doesn't work – the code isn't even reached.

**Comment by JeffreyWay** [comment]
It looks like we're using the v3 version of clean-css, and they fixed your issue for v4. So I'm going to upgrade that dependency and tag it today.

**Comment by phanan** [comment]
Confirmed this fixed the issue. Thanks!
