### ISSUE TITLE
versioning cache/last compiled

### ISSUE THREAD

**Issue by pedrolopes10** [JeffreyWay/laravel-mix#388]
Hi, I've upgraded to 5.4 and getting used to webpack/mix. I'm enjoying but there's one feature that i miss on elixir. When versioning, elixir kept on the manifest the last 3/4 files compiled and now it wipes everything and so i'm not able to compile just one file.

it's a big project and i don't like to compile all files every time i make a small change.

Thanks

**Comment by JeffreyWay** [comment]
If the file hasn't changed, it won't create a new entry in the manifest file. 

But, yeah, the manifest will reflect the current state of the last time you ran Webpack. It doesn't retain anything before that.

**Comment by pedrolopes10** [comment]
That doesn't happen to CSS files, they are generating new entry every time.

I'm sorry that i don't understand much about the webpack configuration but there's a Webpack Manifest Plugin that has this option:

cache: In multi-compiler mode webpack will overwrite the manifest on each compilation. Passing a shared {} as the cache option into each compilation's ManifestPlugin will combine the manifest between compilations.

Isn't this possible to implement?
