### ISSUE TITLE
mix.setResourceRoot is attached to mix.setPublicPath

### ISSUE THREAD

**Issue by maaxxicarvalho** [JeffreyWay/laravel-mix#391]
hi, first, thanks for the amazing work.

Now the issue/question.
I updated to the latest version (0.8.0) and I'm trying to use the `mix.setResourceRoot` method but, I realized that I also need to set the `mix.setPublicPath` in order to work properly.

So I need to do something like:
```javascript
mix.setResourceRoot('skin/frontend/rwd/smoke');
```
But with this line only, the images will be placed inside a images directory within the root dir.
It works properly if I do like this
```javascript
mix.setPublicPath('skin/frontend/rwd/smoke');
mix.setResourceRoot('skin/frontend/rwd/smoke');
```
I don't need to change my public path, just the images destination path.

Thanks ;)

**Comment by MicroDreamIT** [comment]
I have tried the same way but i can not get fonts in public/ directory... :(

**Comment by JeffreyWay** [comment]
This was resolved a couple months ago.
