### ISSUE TITLE
Very Long Compile Times vs. Elixir

### ISSUE THREAD

**Issue by danremollino** [JeffreyWay/laravel-mix#392]
- Laravel Mix Version: 0.8.1
- Node Version (`node -v`): 7.5.0
- NPM Version (`npm -v`): 4.1.2
- OS: MacOS 10.12.3 (16D32)

I'm getting very long compile times, averaging about 33s with `npm run dev`. I have one, single file Vue component, and and a main .scss that take roughly 15s each during compilation. Removing sourcemaps and versioning does not seem to affect build time. Using the default mix.config.

![package](https://cloud.githubusercontent.com/assets/11876088/23005968/20b45810-f3cd-11e6-8d42-df1340d415f4.png)

![mix](https://cloud.githubusercontent.com/assets/11876088/23005807/3aa19d56-f3cc-11e6-98c5-97b8f819faf7.png)

![time](https://cloud.githubusercontent.com/assets/11876088/23005835/64033772-f3cc-11e6-897c-7047f8fb1de8.png)

I'd be happy to provide my .scss and .vue if needed, but I don't believe I have anything out of the ordinary going on. I don't recall how fast Elixir was compiling, but it was fast enough that I would not think anything of it. I had manually moved what I needed to a brand new Laravel 5.4 install, so I'd be pretty confident that I should not have any conflicts if that's possible.

Thanks, and please let me know if I can provide you with any other relevant information.

**Comment by eblin** [comment]
It could be the `.copy()` commands, have you tried without them? You could also profile webpack see if you get more info there.

`webpack --profile --json > stats.json` then use https://webpack.github.io/analyse/ to see what it tells you.

**Comment by danremollino** [comment]
Removed the `.copy()` to no effect.

I'm getting a command not found for webpack when I try to run the profile. I never explicitly installed Webpack, just whatever the Laravel 5.4 installer provided. Would installing Webpack globally cause a conflict with this?

**Comment by eblin** [comment]
You don't need to do that, webpack is installed in node_modules already by laravel-mix dependency `ls node_modules/.bin | grep webpack`
just put that line in the `scripts` section in `package.json`

```
    "profile": "cross-env NODE_ENV=development webpack --profile --json > stats.json"
```

**Comment by JeffreyWay** [comment]
It's important to remember that Webpack is doing a lot more work + optimizations than the Gulp equivalent was. You should typically use `npm run watch`, and your recompile times should be fairly short.

But, yeah, run the profiler and see what's taking so long.

**Comment by danremollino** [comment]
Thanks @JeffreyWay, understood.

I was able to generate the stats file, using this...

`node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --profile --json > stats.json --config=node_modules/laravel-mix/setup/webpack.config.js`

Sorting the output now. File is 3.2MB and not sure if the analyzer linked above by @eblin can handle it. Doesn't seem to be responding after giving it the file. I'll keep trying.

Running `npm run watch` and editing my .vue file it re-compiles in less than 1s. Editing the .scss file (~70k, 3k lines) takes about 16s. If this is normal, thats cool, just seemed way out there compared to what I have read you said you were getting. (Can't recall where, of course.)

**Comment by dobromir-hristov** [comment]
@danremollino remove the first line from the generated file, it is not valid JSON with it.

**Comment by danremollino** [comment]
Thanks @dobromir-hristov, should have realized this.

This is new to me, so I'm not sure what exactly what I'm looking for. I'm not getting any errors or warning, and the only 'hint' I'm getting is to 'Use prefetching to increase build performance.' I'll look into what I can do. I'm attaching the file in case anyone can provide any other feedback. Thanks.

[webpack_profile.zip](https://github.com/JeffreyWay/laravel-mix/files/782150/webpack_profile.zip)

**Comment by hamid-a** [comment]
same issue
but when I changed mix version to 0.6 compile time became good
I think the problem is in 0.7 and 0.8 versions

**Comment by Rigorbb** [comment]
It's solved the same problem for me:
1) use 0.8.7 version in package.json
2) Add Mix.options:
```
mix.options({
    processCssUrls: false
});
```

**Comment by danremollino** [comment]
@Rigorbb 

Worked! I swear I tried this with a lower version of Mix with no effect. Brought my `npm run dev` compile time down to 3s.
