### ISSUE TITLE
Create a bundle.js file

### ISSUE THREAD

**Issue by neutt22** [JeffreyWay/laravel-mix#393]
I was just wondering if anyone could share his/her mix configuration so that it would bundle up css and js files in one js file (e.g. bundle.js) and if this is recommended since it would break long term caching for vendor files.

Thanks!

**Comment by JeffreyWay** [comment]
Mix will automatically extract your CSS into a dedicated file. So you can't change that without manually modifying our provided webpack.config.js file.

**Comment by neutt22** [comment]
Hi @JeffreyWay , is mix' `webpackConfig` I need to override webpack if I dont want to mess with the provided webpack.config.js and install a style-loader?
