### ISSUE TITLE
Exports * not working

### ISSUE THREAD

**Issue by mohitpanjwani** [JeffreyWay/laravel-mix#394]
- Laravel Mix Version: 0.7.5
- Node Version (`node -v`): 6.8.0
- NPM Version (`npm -v`): 3.10.8
- OS: OSX El Capitan

### Description:

Exporting all (*) objects from a module throws an unknown error : "exports is not defined"
<img width="707" alt="971a7e932c571ef684c928f062d5985a" src="https://cloud.githubusercontent.com/assets/8002555/23009202/9e1cdc92-f43a-11e6-9d75-2eb713c688aa.png">

This worked perfectly in our webpack only setup but I've been struggling to get this to work with Laravel mix since 3 days now.

Any help would be greatly appreciated.

### Steps To Reproduce:

services/index.js
```javascript
export * from './auth.js'
export * from './ls.js'
```

app.vue
```javascript
import { auth } from 'services/index.js'
```

**Comment by JeffreyWay** [comment]
I just tried it out, and everything worked. 

https://www.dropbox.com/s/wcuodnthph7qmsu/Screenshot%202017-02-16%2009.56.38.png?dl=0

You're writing `export` and not `exports`, right?

**Comment by mohitpanjwani** [comment]
Are you on Laravel Mix Version: 0.7.5 ?

Anyhow I'll try out in the latest version and get back to you.

Thank you for the help :)

**Comment by mohitpanjwani** [comment]
Also I forgot to mention that I use custom Babel Config : 

```
{
  "presets": ["es2015", "stage-2"],
  "plugins": ["add-module-exports", "transform-runtime"]
}
```

& relative root paths
<img width="597" alt="a24cd4c27167c0b0cda6d63faaa69bae" src="https://cloud.githubusercontent.com/assets/8002555/23027494/6605dbce-f48a-11e6-946f-bf90862516a3.png">

Sorry for that.

**Comment by JeffreyWay** [comment]
I'm not sure, but, out of the box, everything seems to be working properly. So I think this issue is unrelated to what Mix ships with.

I'm assuming it's related to your file structure, and the addition of the add-module-exports Babel plugin.

**Comment by mohitpanjwani** [comment]
I wasn't sure really sure if its unrelated to laravel-mix as it worked in our previous webpack only setup. 

Btw `add-module-exports` was the culprit.  It causes problems with named exports. So it looks like we can either use that plugin or named exports.

More info below in case someone else has the same problem: 
http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default

Thank you very much for that hint Jeff! :1st_place_medal:
