### ISSUE TITLE
Confirm this is expected behaviour? Vue files and SASS/SCSS.

### ISSUE THREAD

**Issue by shealan** [JeffreyWay/laravel-mix#395]
Very impressed with Laravel Mix so far, but I have one question...

I am working with .vue files that have style sections.

Laravel mix is running as expected and the styles are showing in my browser. However, they appear to be injected into the head as a <style> element, rather than being compiled into the app.scss.

Is this the expected behaviour?

If so, why? Although *it works* surely this means that browsers with javascript off will show no styling whatsoever? Not to mention the fact it's just a bit ugly injecting huge amounts of style markup into the document dom.

Is my Laravel Mix setup broken?

**Comment by JeffreyWay** [comment]
It's expected behavior, but you can extract it by adding:

```js
mix.options({ extractVueStyles: true });
```

**Comment by shealan** [comment]
Thank you @JeffreyWay, exactly what I was after. And thank you for Laracasts. It's the most valuable thing I pay for.
