### ISSUE TITLE
Mix breaking behavior of class that extends Date

### ISSUE THREAD

**Issue by vTripes** [JeffreyWay/laravel-mix#397]
- Laravel Mix Version: 0.8.1
- Node Version: 7.4.0
- NPM Version: 4.1.2

### Description:
Hello,
It seems that Laravel-mix is breaking the behavior of classes that are extend of Javascript's Date object as the inheritance isn't working as intended. When you instanciate your custom class and that you try to access a Date's method with this newly instanciated object, you get a TypeError saying that your object is not an instance of Date (which shouldn't happend if inheritance were working as it should).

### Steps To Reproduce:
- Create a class that is an extend of Date as the following example:
```JavaScript
// window.classname to have the class available in every scope
window.Myclass = class extends Date {
  constructor ()
  {
    super()
  }
}
```
- Compile the script by running ``npm run dev``
- You can then try with console (or anything else) the following:
```JavaScript
var myvar = new Myclass();
myvar.getDate();
```
This way, you should get a TypeError: this is not a Date object.

**Comment by JeffreyWay** [comment]
I don't think this is specifically related to Mix. See here for a good explanation:

http://stackoverflow.com/questions/34006955/typescript-extends-error-uncaught-typeerror-this-is-not-a-x-object
