### ISSUE TITLE
Fails when laravel-elixir-webpack-official is installed

### ISSUE THREAD

**Issue by skyronic** [JeffreyWay/laravel-mix#398]
- Laravel Mix Version: 0.8.1
- Node Version (`node -v`): v6.9.2
- NPM Version (`npm -v`): 3.10.9
- OS: OS X 10.11

### Description:

When laravel-elixir and laravel-elixir-webpack-official is also installed (latest version) then doing a build with mix fails.

### Steps To Reproduce:

1. new laravel project
2. install `laravel-elixir` and `laravel-elixir-webpack-official`
3. Try to compile a project including vuejs

### Temporary workaround

I was able to make it work by installing `npm install webpack` to get the latest 2.2 version required by mix, which works for both mix and elixir.

**Comment by JeffreyWay** [comment]
You have to uninstall Laravel Elixir, if you're going to use Mix.
