### ISSUE TITLE
npm run <dev|production> hangs after compilation before exiting

### ISSUE THREAD

**Issue by bitdagger** [JeffreyWay/laravel-mix#402]
- Laravel Mix Version: 0.8.1
- Node Version (`node -v`): v7.5.0
- NPM Version (`npm -v`): 4.2.0
- OS: Linux Hyperion 4.9.8-1-ARCH #1 SMP PREEMPT Mon Feb 6 12:59:40 CET 2017 x86_64 GNU/Linux

### Description:
After running `npm run <dev|production>`, while the actual compilation runs in a reasonable amount of time (~800ms for dev and ~4500ms for production), the process hangs for about 60 seconds before returning to the command prompt.  

```
$ time npm run production
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules

 95% emitting                                                                        

 DONE  Compiled successfully in 4475ms
[table omitted to save space]

real	0m55.700s
user	0m6.077s
sys	0m0.157s
```  

This has been the case since at least 0.5.x I believe.   

Obviously it's likely some strange interaction with my terminal config with webpack, since I haven't seen any other complaints about this, but I haven't been able to figure out a root cause so I figured I'd open an issue about it.

### Steps To Reproduce:  
1. `$ time npm run production` 
2. Observe the time data

**Comment by JeffreyWay** [comment]
Hmm, I haven't seen this, personally. Are you able to reproduce this in a fresh install?

**Comment by bitdagger** [comment]
Yep: 

```
$ mkcd testing
$ npm init -y
$ npm install laravel-mix --save-dev
$ cp -r node_modules/laravel-mix/setup/** ./
$ nano webpack.mix.js 
$ mkdir src
$ echo "#sample { background: red; }" > src/app.scss
$ echo "alert('debug');" > src/app.js
$ nano package.json # add scripts
$ time npm run production

> testing@1.0.0 production /home/[redacted]/testing
> cross-env NODE_ENV=production webpack --progress --hide-modules

 95% emitting                                                                      

 DONE  Compiled successfully in 597ms                                                                                                                                                5:21:37 PM

            Asset       Size  Chunks             Chunk Names
      dist/app.js  581 bytes       0  [emitted]  dist/app
     dist/app.css   23 bytes       0  [emitted]  dist/app
mix-manifest.json   72 bytes          [emitted]  

real	0m51.832s
user	0m1.840s
sys	0m0.100s
```  

As you can see although the compilation only took 597ms, the process didn't exit until after 50s

**Comment by kohenkatz** [comment]
I wonder if this may be related to notifications.

What happens if you add `mix.disableNotifications()` to the file?

**Comment by JeffreyWay** [comment]
@bitdagger Hmm, I followed your exact installation steps, and can't reproduce. 

Let me know if you figure out what the issue was!

**Comment by kohenkatz** [comment]
I can't reproduce it as badly as @bitdagger reported it, but I can reproduce some delay.

My test is on Ubuntu 16.04.2 with Node 6.9.5.

Here is the output:

```
$ time node ./node_modules/.bin/cross-env NODE_ENV=production ./node_modules/.bin/webpack --progress --hide-modules
 95% emitting

 DONE  Compiled successfully in 1355ms                                             10:34:23 AM
            Asset       Size  Chunks             Chunk Names
      dist/app.js  581 bytes       0  [emitted]  dist/app
     dist/app.css   23 bytes       0  [emitted]  dist/app
mix-manifest.json   72 bytes          [emitted]

real    0m8.007s
user    0m3.068s
sys     0m0.304s
```

As you can see, the compile took 1355ms, but the wall clock time was 8 seconds. Approximately 1 second of that was startup time before Webpack actually started running, followed by around 5 seconds of waiting afterwards.

**When I add `mix.disableNotifications()`, the problem goes away entirely.** Here is an example:

```
$ time node ./node_modules/.bin/cross-env NODE_ENV=production ./node_modules/.bin/webpack --progress --hide-modules
 95% emitting

 DONE  Compiled successfully in 1023ms                                             10:43:06 AM
            Asset       Size  Chunks             Chunk Names
      dist/app.js  581 bytes       0  [emitted]  dist/app
     dist/app.css   23 bytes       0  [emitted]  dist/app
mix-manifest.json   72 bytes          [emitted]

real    0m2.525s
user    0m2.580s
sys     0m0.272s
```

@bitdagger Please check whether this fixes it for you too.

**Comment by kohenkatz** [comment]
I should also note that I cannot reproduce this on my Windows 10 machine - it works perfectly there, even with notifications enabled.

**Comment by bitdagger** [comment]
Yes! It was related to notifications. 

`mix.disableNotifications()` allows for an exit to console immediately after compilation finishes.  

I'm still not sure why notifications cause the process to hang on my machine, but this is a good workaround in the meantime.
