### ISSUE TITLE
Not deleting old versioned files after new build.

### ISSUE THREAD

**Issue by libern** [JeffreyWay/laravel-mix#406]
When I change from dev to prod with versions, the old files in the manifests file are not being deleted.

It requires manual deleting for outdated built files

**Comment by libern** [comment]
Test at latest 0.8.1 version

**Comment by libern** [comment]
When I put the "version" staff in a separate file, and run it after the normal dev and prod build.

**Comment by JeffreyWay** [comment]
Please give me reproducible steps, like the issue notes request.

**Comment by vmitchell85** [comment]
I'm having a similar issue... when I run npm run watch I'm getting a ton of files that aren't cleaned up...

![image](https://cloud.githubusercontent.com/assets/1248035/23081024/13fc54b0-f521-11e6-9fc4-3af29d76e783.png)

**Comment by corbosman** [comment]
Same here, all old versioned files are not being removed.

**Comment by goodbytes-gb** [comment]
Same problem. Not doing anything out of the ordinary.

```
mix.sass('...').version();
```

Version 0.7.5

Files are not being replaced.

**Comment by corbosman** [comment]
Forgot to mention, im on homestead, totally default setup.

**Comment by n8-sd** [comment]
+1 for `npm run watch` updating the manifest but not deleting the old one.

**Comment by JeffreyWay** [comment]
Can you all ensure that you're on the latest version of Laravel Mix. 

I'm testing it out right now, and each time I change a file, it updates the mix-manifest.json file, and then deletes the old versioned file.

Otherwise, please give me reproducible steps.

**Comment by goodbytes-gb** [comment]
0.8.0 does fix it. Apologies.

**Comment by barnabaskecskes** [comment]
@JeffreyWay I'm having the same problem, not sure what could cause it. This is for a fresh install, nothing fancy about it. Here is my `packages.json` file (containing scripts from Laravel):
```
{
  "name": "simple-project-base",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "laravel-mix": "^0.9.2"
  }
}
```

This is before: 
<img width="926" alt="screen shot 2017-03-26 at 19 19 52" src="https://cloud.githubusercontent.com/assets/3535449/24333950/6c6a00a2-1259-11e7-9e76-60b6ae84f658.png">

And then when I update my app.js file and run `npm run dev` again, this is after:
<img width="929" alt="screen shot 2017-03-26 at 19 20 19" src="https://cloud.githubusercontent.com/assets/3535449/24333954/7d7d7914-1259-11e7-8798-7a440115550d.png">

Not sure whether the bug sneaked back upon you, but as you can see, I'm using a higher version of laravel-mix than the guys above, so should be working just fine?

**Comment by muhamed-didovic** [comment]
Same here, 
It was working fine, I have upgraded npm and node to last versions and laravel mix to 0.12.1 version and now it duplicates.

Any ideas?

**Comment by vmitchell85** [comment]
Same here
