### ISSUE TITLE
Sass source **/*.scss

### ISSUE THREAD

**Issue by rusowyler** [JeffreyWay/laravel-mix#409]
- Laravel Mix Version: 0.8.1
- Node Version (`node -v`): v6.9.1 
- NPM Version (`npm -v`): 3.10.8
- OS: OSX Darwin

### Description:

In Laravel Elixir we compile our sass files like this:

`.sass(['angular/**/*.scss'], 'public/css')
`

Using that source in mix I got the following error:

```
/Users/mwyler/Projects/potato-admin-mix/node_modules/laravel-mix/setup/webpack.config.js:185
            test: new RegExp(toCompile.src.path.replace(/\\/g, '\\\\') + '$'),
                  ^

SyntaxError: Invalid regular expression: //Users/mwyler/Projects/potato-admin-mix/angular/**/*.scss$/: Nothing to repeat
```

Any workaround without including every .scss file? (out application has thousand of components and each one has it own style sheet).

THANKS!

**Comment by JeffreyWay** [comment]
Mix will assume a single entry point Sass file. Generally, that entry point then imports anything else that it requires. 

So if you need a sweeping regular expression, it might be best to stick with Laravel Elixir for now.
