### ISSUE TITLE
net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by xralphack** [JeffreyWay/laravel-mix#410]
- Laravel Mix Version: ^0.7.2
- Node Version (`node -v`): 6.9.4
- NPM Version (`npm -v`): 3.10.10
- OS: Windows10
 
### Description:

I use laradock to run laravel, sometimes chrome console shows 

GET http://localhost/js/app.js net::ERR_CONTENT_LENGTH_MISMATCH

sometimes this will show, but not always

### Steps To Reproduce:

add laradock as git submodule
docker-compose up -d nginx mysql phpmyadmin
npm run watch

**Comment by JeffreyWay** [comment]
I'm not sure, but this doesn't sound like a Mix issue to me. Seems like a server issue.

**Comment by mohitpawar10** [comment]
This is not the server issue. You must be compiling the same assets twice or making one compiled asset file really big. Recheck your webpack.js file, refactor the compiled asset into different files.

**Comment by muffeen** [comment]
@JeffreyWay this issue for me exists on the latest version of laravel mix as of this writing (4.0.14). It happens to me on one of my sass file with a lot of imports and I run `npm run watch`. At first compile it is ok but once I have made changes to the sass file now I get this error.
