### ISSUE TITLE
Modify sass-loader options in webpack.mix.js file

### ISSUE THREAD

**Issue by jety91** [JeffreyWay/laravel-mix#411]
Have any option to modify the sass-loader options in the webpack.mix.js file?
I want to import (override) sass variables into my .vue file <style> tags.

#### Example.vue:
```
<template> ... </template>
<script> export default { ... } </script>
<style lang="scss">
/* ---- I want to import ./styles/custom_variables file here ---- */
@import './styles/imports';

$ui-alert-color             : rgba(black, 0.75) !default;
$ui-alert-font-size         : rem-calc(15px) !default;
$ui-alert-margin-bottom     : rem-calc(16px) !default;
</style>
```

I can modify the [webpack.config.js#L165](https://github.com/JeffreyWay/laravel-mix/blob/master/setup/webpack.config.js#L165) to:
```
options:
    Object.assign(
        toCompile.pluginOptions,
        { data: '@import "./styles/custom_variables";' }
    )
```

But i think it's not a nice workaround.

Ps: It's an awesome tool Jeff, keep it up! :)

**Comment by JeffreyWay** [comment]
You can pass your plugin options as the third argument to `mix.sass()`. So I think you should be able to do:

```js
mix.sass('src', 'output', {
    data: '@import "./styles/custom_variables";'
});
```

**Comment by JonasDoebertin** [comment]
@JeffreyWay Is there a way to achieve SCSS variable "injection" like in your example above into `*.vue`single file components but compiled with `mix.js()`?

@jety91 Are you working with Keen UI? Did you find a solution for this?

**Comment by jety91** [comment]
Jeffrey example did this. You can put those lines to the webpack.mix.js file before the mix.js() function called. It's worked for me.

Yes, I used the Keen UI for few weeks, but I found a better material based Vue Framework: [Vue Material](https://github.com/marcosmoura/vue-material)

**Comment by JonasDoebertin** [comment]
That doesn't work for me. The `@import` from the `data` option only gets applied to the main `app.scss` file im processing. Not to the `*.vue` components imported in the JS.

**Comment by thebrubaker** [comment]
Yes mix is super awesome! I'm still struggling with applying the custom options for sass to `.vue` components. I'm not trying to modify the loader options on `mix.sass` but rather on `mix.js` for Vue component. Is there a way to inject custom options for sass-loader on `.vue` components?

**Comment by amitailanciano** [comment]
@JonasDoebertin did you ever figure out how to do that? I'm digging through the source now looking to do the same thing

**Comment by amitailanciano** [comment]
It looks like the only way to do this is by leveraging `globalVueStyles`, unfortunate

**Comment by codekipple** [comment]
I think I have figured this out by adding some rules to the `webpack` settings in `webpack.mix.js`.
I added a rule targeting all .scss files which triggered the `sass-loader`.
```
.webpackConfig({
      resolve: {
         alias: {
            '@': path.resolve('resources/sass'),
         },
      },
      module: {
         rules: [
            {
               test: /\.scss$/,
               loader: "sass-loader",
               options: {
                  data: `
                        @import "~@/settings/vars.scss";
                        @import "~@/settings/vars-bootstrap.scss";
                        @import "~@/settings/functions.scss";
                  `
               }
            }
         ]
      }
   })
```

**Comment by EvgenyGulyaev** [comment]
> You can pass your plugin options as the third argument to `mix.sass()`. So I think you should be able to do:
> 
> ```js
> mix.sass('src', 'output', {
>     data: '@import "./styles/custom_variables";'
> });
> ```
Doesn't work =(

**Comment by EvgenyGulyaev** [comment]
> I think I have figured this out by adding some rules to the `webpack` settings in `webpack.mix.js`.
> I added a rule targeting all .scss files which triggered the `sass-loader`.
> 
> ```
> .webpackConfig({
>       resolve: {
>          alias: {
>             '@': path.resolve('resources/sass'),
>          },
>       },
>       module: {
>          rules: [
>             {
>                test: /\.scss$/,
>                loader: "sass-loader",
>                options: {
>                   data: `
>                         @import "~@/settings/vars.scss";
>                         @import "~@/settings/vars-bootstrap.scss";
>                         @import "~@/settings/functions.scss";
>                   `
>                }
>             }
>          ]
>       }
>    })
> ```
Doesn't work  too=(

**Comment by codekipple** [comment]
@EvgenyGulyaev I got this solution to work for me, can you give me more info on your setup and what your trying to do? maybe I can help

**Comment by cgodo** [comment]
In order to modify all sass-loader options, even those used for *.vue files, you can use [jsonpath-plus](https://www.npmjs.com/package/jsonpath-plus) npm package to search for all sass-loaders in the config and modify their options.

In my case, I wanted to disable SCSS sourceMaps to fix an issue with chrome dev tools while developing.

```javascript
const { JSONPath } = require('jsonpath-plus');

if (!mix.inProduction()) {
    mix.override((config) => {
        JSONPath("$.module.rules..use[?(@.loader === 'sass-loader')].options", config, (options) => {
            options.sourceMap = false;
        });
    });
}
```

Hope it helps someone.
