### ISSUE TITLE
CSS injection using browsersync?

### ISSUE THREAD

**Issue by marcamos** [JeffreyWay/laravel-mix#413]
- Laravel Mix Version: 0.8.1
- Node Version (`node -v`): 6.9.1
- NPM Version (`npm -v`): 4.0.1
- OS: OS X 10.11.6

### Description:

I'm a front-end developer who's recently been interested in moving from gulp to webpack, but trying to learn webpack always leaves me confused. Laravel Mix seems like it'll help me make the leap.

The first order of business, for me, was to ensure BrowserSync works the way I'm used to it working over in gulp. I was super-happy to see support for it appear in [0.7.4](https://github.com/JeffreyWay/laravel-mix/releases/tag/v0.7.4) and immediately tried it out. I got it up and running using the following:

```
mix.js('_js/app.js', 'html/lib/js')
  .sass('_scss/app.scss', 'html/lib/css')
  .sourceMaps()
  .browserSync({
    proxy: 'http://starter.vbox.bytheoutfit.com/',
    files: [
      'html/_demos/**/*.+(html|php)',
      'mix-manifest.json',
      'html/lib/css/**/*.css',
      'html/lib/js/**/*.js'
    ]
  });
```
…where `http://starter.vbox.bytheoutfit.com/` points to my local VirtualBox.

As expected, the watch script refreshed all connected browsers, which is great, but css-only file-changes resulted in an entire page-refresh as well, whereas I was hoping the compiled css would be injected.

It's not a huge deal, but I got very used to scss/css updates being injected and wonder if that's possible here, using Mix/webpack?

Thanks for your hard work, and for your time!

**Comment by JeffreyWay** [comment]
Fixed in #430

**Comment by marcamos** [comment]
Just wanted to write in and say that this now works perfectly. Thanks so much, @JeffreyWay.

**Comment by pcampina** [comment]
IN 2020, config is:

```
mix
  .js("resources/js/app.js", "public/js")
  .sass("resources/sass/app.scss", "public/css")
  .browserSync({
    proxy: 'localhost', // your domain test
    port: 32816 // your port
  });
```
