### ISSUE TITLE
About the name question!

### ISSUE THREAD

**Issue by francescobianco** [JeffreyWay/laravel-mix#414]
Why such a useful and powerful project that can be integrated into any environment also not PHP, it must remain linked to the name of laravel ??

I propose a project with its own name (eg. AssetsMix, MagicMix)

**Comment by francescobianco** [comment]
i found it:
https://github.com/devanandb/webpack-mix

**Comment by QWp6t** [comment]
lol

![](http://i.imgur.com/Lzcm756.png)

**Comment by JeffreyWay** [comment]
Because it's optimized for Laravel.
