### ISSUE TITLE
Removing webpackBootstrap for Projects without modules =>behavior like laravel-elixer

### ISSUE THREAD

**Issue by stefanpolzer** [JeffreyWay/laravel-mix#423]
- Laravel Mix Version: 0.8.1

Most of my apps do not require the module functionality.
I only have JS files that only needs to be bundled and uglified.

Basically I only need the behaviour that laravel-elixir had in Laravel 5.3.

Since from Laravel 5.4 on laravel-mix is the replacement I assume this is a legitimate request.
Are there any options to to do this?

Having 10 or more some JS files for the different areas of the app, that will produce a lot of data overhead.

**Comment by QWp6t** [comment]
Use .combine() or .babel(), or just stick with elixir.

docs: https://github.com/JeffreyWay/laravel-mix/blob/master/docs/concatenation-and-minification.md#concatenation-and-minification

**Comment by stefanpolzer** [comment]
@QWp6t I assumed that laravel-mix ist the replacement for elixir, and should be working for for the 80% use case.

But you give me a interesting hint:
`.minify()` kind of works but only in combination with copy.

```js
mix
    .minify('resources/assets/js/app.js')
    .copy('resources/assets/js/app.min.js', 'public/js/app.js');
```
Because I want to name my files without `.min`, this would add the `.min` file to my repo or I have to add a .gitignore file...

@JeffreyWay would it be more efficient if we could have a second optional argument where we can specify the output path and/or filename? 
```js
mix.minify('resources/assets/js/app.js', 'public/js');
```

**Comment by stefanpolzer** [comment]
Sorry, I realized you can use `.combine` for that as well...
You may want to add this to the [Laravel Docs](https://laravel.com/docs/5.4/mix)
