### ISSUE TITLE
global plugin config doesn't work

### ISSUE THREAD

**Issue by terion-name** [JeffreyWay/laravel-mix#424]
I need to process and build multiple style-files. I want to set default plugin options.
As far I understand, this should be done like this:

```js
mix.config.css = {
  stylus: {
    paths: ['node_modules', 'resources/assets/stylus'],
    'include css': true,
    'resolve url': true
  }
};
```

But this has no effect. This works:

```js
const stylusOptons = {
  paths: ['node_modules', 'resources/assets/stylus'],
  'include css': true,
  'resolve url': true
};

mix.setPublicPath('./public/assets');

mix.stylus('resources/assets/stylus/home.styl', 'css', stylusOptons);

mix
    .stylus('resources/assets/stylus/vote/main.styl', 'css/vote', stylusOptons)
    .stylus('resources/assets/stylus/vote/alter.styl', 'css/vote', stylusOptons)
    .stylus('resources/assets/stylus/vote/order.styl', 'css/vote', stylusOptons)
    .stylus('resources/assets/stylus/vote/open.styl', 'css/vote', stylusOptons);
```

but this is not good

**Comment by JeffreyWay** [comment]
I think you're confusing Laravel Elixir with Laravel Mix? That `mix.config.css` snippet won't do anything. Are you just trying to compile multiple Stylus source files?

```js
mix.stylus('resources/assets/stylus/one.styl', 'public/css')
mix.stylus('resources/assets/stylus/two.styl', 'public/css');
```

**Comment by terion-name** [comment]
@JeffreyWay so there is no way to add global config without altering plugin settings without editing webpack.config.js? And no plans for it? This really makes sense not only for multiple files to compile, but also if this would affect vue's components preprocessed styles
