### ISSUE TITLE
[Question] Is it possible to create module tree with Laravel mix default configuration file?

### ISSUE THREAD

**Issue by ludo237** [JeffreyWay/laravel-mix#428]
- Laravel Mix Version: 0.8.*
- Node Version (`node -v`): v6.9.5
- NPM Version (`npm -v`): v3.10.10
- OS: Windows 10 but using docker with debian

### Description:

I would like to extract some statistics from my package tree as shown in this issue https://github.com/webpack/webpack/issues/690 but it's seems that with the current mix configuration file is not possible to send the output of the webpack tree to a json file.

### Steps To Reproduce:

- Open your terminal
- Type `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --profile --json > stats.json` 
- Try to upload the generated file to https://webpack.github.io/analyse/
- The file is not correct

Am I missing something or Laravel mix doesn't include the possibility to create the module tree?

**Comment by JeffreyWay** [comment]
I don't know much about that tool, but Mix doesn't have any affect on the profiling. 

Maybe you need to remove the  "DONE  Compiled successfully in 325ms9:52:19 AM" portion from the top of the stats.json file. Not sure.

**Comment by ludo237** [comment]
@JeffreyWay actually by removing the *DONE Compiled successfully in 665ms00:00:00 AM* line the whole thing works. Nothing difficult of course.

If you want to try out here's the script I am using right now

```
"stats": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --config=node_modules/laravel-mix/setup/webpack.config.js --profile --json > stats.json"
```

Maybe you can find it interesting 😄

**Comment by acacha** [comment]
In my case:

```
node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --config=node_modules/laravel-mix/setup/webpack.config.js --profile --json > stats.json
```

**Comment by acacha** [comment]
using source-map-explorer 
https://medium.com/@joeclever/three-simple-ways-to-inspect-a-webpack-bundle-7f6a8fe7195d

**Comment by acacha** [comment]
Solved

**Comment by simonvomeyser** [comment]
In my case it was this (MacOS BigSur, Laravel Mix 5.x)

```bash
node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=production node_modules/.bin/webpack --config=node_modules/laravel-mix/setup/webpack.config.js --profile --json > stats.json
```

Just in case someone stumbles across this :)
