### ISSUE TITLE
Webpack combining order issues

### ISSUE THREAD

**Issue by LiamAird** [JeffreyWay/laravel-mix#429]
- Laravel Mix Version: 0.8.1
- Node Version: v6.5.0
- NPM Version: 3.10.3
- OS:  Windows 10

### Description:

I seem to be have some strange issues with the compile order of my requires and imports in app.scss and app.js. 

They look like this: 
app.scss
```
// Variables
@import "variables";

// Imports
@import "~bootstrap-sass/assets/stylesheets/bootstrap";
@import "~admin-lte/dist/css/AdminLTE.css";
@import "~admin-lte/dist/css/skins/_all-skins.css";
@import "~font-awesome/scss/font-awesome.scss";
@import "~jquery-form-validator/src/theme-default.css";
@import "~simplemde/dist/simplemde.min.css";
// Custom
@import "custom";
```
app.js
```
require('./bootstrap.js');

require('admin-lte/dist/js/app.js');
require('jquery-form-validator/form-validator/jquery.form-validator.js');
require('jquery-form-validator/form-validator/security.js');`
```

Webpack looks like this: 
```
mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .sourceMaps();`
```

However, the order of the combined files are not how they are required or imported. 
For example, the AdminLTE styles is loaded in before the Bootstrap styles.
Last inserted is Fontawesome, second to last is Bootstrap styles. In the middle of it all I have my Custom, which is imported lastly in the app.scss - hard to make custom changes, if they aren't combined in the right order.

So what is wrong? 
Do webpack combine them in a specific order? Gulp did combine in the order of imports and requires. 

### Steps To Reproduce:
1. Install fresh laravel
2. Import NPM components as described above
3. Insert them in app.js and app.scss
4. Run npm run dev
5. Check browser for the ordering.

**Comment by JeffreyWay** [comment]
This seems to be a Webpack-specific issue that we have no control over. 

https://github.com/webpack/webpack/issues/215

I'll nudge the Webpack team to see if any progress has been made.

**Comment by jblyberg** [comment]
I'm experiencing the same exact issue. Makes mix/webpack unusable, really. Are there any workarounds?

- Laravel Mix Version: 0.11.4
- Node Version: v7.9.0
- NPM Version: 4.5.0
- OS: OSX 10.12.4

**Comment by wadified** [comment]
Any updates for this please??

**Comment by xdemocle** [comment]
I have to admit this laravel elixir implementation mixing gulp/webpack utilities is really bad.
On custom implementation add only more trouble instead to solve it.
I'm going to switch entirely to gulp or webpack and rid off of stupid and not flexible elixir.

**Comment by aso824** [comment]
Bug still exists, even with updated `extract-text-webpack-plugin` in dependencies to v3.0.0 with Mix@1.4.2 version (I found in webpack issue 215 information that this bug comes from this package in version below 3.0.0).
Is there any workaround? Mix is currently unusable, I must compile and link files separately.

**Comment by medelasri** [comment]
Please update this!

**Comment by Snaver** [comment]
Silly issue.. Surprised webpack haven't fixed this yet.

You can work around this however, and still keep everything within laravel-mix - it just requires you to split out to multiple CSS files..

**webpack.mix.js**
```
mix.sass('resources/assets/sass/bootstrap.scss', 'public/css');
mix.sass('resources/assets/sass/vendor.scss', 'public/css');
mix.sass('resources/assets/sass/app.scss', 'public/css');
```

**bootstrap.scss**
```
// Variables
@import "variables";

// Bootstrap
@import "~bootstrap-sass/assets/stylesheets/bootstrap";
```

**app.blade.php**
```
<link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet">
<link href="{{ asset('css/vendor.css') }}" rel="stylesheet">
<link href="{{ asset('css/app.css') }}" rel="stylesheet">
```

**Comment by dclmetal87** [comment]
This is still an issue which makes Laravel Mix unusable... Has anyone find a fix?

Node Version: v8.9.4
NPM Version: 5.6.0
OS: Ubuntu 16.04

**Comment by sherbastian** [comment]
+1

**Comment by fake-fur** [comment]
+1

**Comment by itepifanio** [comment]
+1

**Comment by csimpi** [comment]
+1

**Comment by kasiakorber** [comment]
+1

**Comment by cliffordy** [comment]
+1

**Comment by gbelot2003** [comment]
+1

**Comment by Akecel** [comment]
+1

**Comment by hassanimtiaz26** [comment]
+1

**Comment by handhikadj** [comment]
+1

**Comment by bansalvinay** [comment]
+1

**Comment by SUXUMI** [comment]
Today is 2021 and the issue still exists.

So the solution what I found is to use third party plugins .scss files OR .css files only. In this case importing order is OK.
But if I mix third party plugins' .css and .scss files, then .css files always goes first.

**Comment by SUXUMI** [comment]
> This seems to be a Webpack-specific issue that we have no control over.
> 
> [webpack/webpack#215](https://github.com/webpack/webpack/issues/215)
> 
> I'll nudge the Webpack team to see if any progress has been made.

Dear @JeffreyWay 

I've got reply that the issue is not connected with webpack
https://github.com/webpack/webpack/issues/215#issuecomment-836692810 
on my comment (https://github.com/webpack/webpack/issues/215#issuecomment-835450609)

so where is the real problem?
