### ISSUE TITLE
Extract not work well with version

### ISSUE THREAD

**Issue by natocTo** [JeffreyWay/laravel-mix#43]
Version function creates new hash everytime when something change even for "vendor files (manifest, vendor). So everytime I need downloading all files again.

I have never use Webpack before, just research some articles about that. Maybe it is related to using [hash] instead of [chunkhash]. Article about this https://medium.com/@okonetchnikov/long-term-caching-of-static-assets-with-webpack-1ecb139adb95

Some interesting thoughts about hashing are there https://github.com/webpack/webpack-dev-server/issues/377

> Closing this, because you should not use [chunkhash] or [hash] for development. This will cause many other issues, like a memory leak, because the dev server does not know when to clean up the old files.

**Comment by JeffreyWay** [comment]
Yeah - I'm aware of this one. Will fix it soon. Otherwise, PR's appreciated.

**Comment by natocTo** [comment]
Thanks for information. This is not my area so I think I can not help with this. Hope you solve this .) or maybe some tweet can bring some 'experts'.

**Comment by JeffreyWay** [comment]
We're now using chunkhash for versioning. 

Thanks!

**Comment by bedus-creation** [comment]
```
let mix = require('laravel-mix');

mix.setPublicPath('public');

mix.webpackConfig({
    output: {
        chunkFilename: 'js/[name].[hash].js',
    },
});

mix.js('resources/assets/js/app.js', 'public/js')
    .extract(["vue"])
    .version();

```
