### ISSUE TITLE
Not deleting old versioned files after new build @v0.8.0

### ISSUE THREAD

**Issue by libern** [JeffreyWay/laravel-mix#437]
#406 The issue has been closed. 

I am here to address the issue in more details. 

As of v0.8.0, I have create another config, let say `version.config.js` + `version.mix.js` to do only version actions for some custom files. The files are been versioned correctly and added to the `manifests.json`. And, the previous default config `webpack.config.js` + `webpack.mix.js` runs basic js compiling and file combines with hot reload support. 

Run sequence:
1. `npm run dev`
2. `npm run version` (the config is pointed to `version.config.js` + `version.mix.js`)

Issues:
1. The second config with mix files run after the default config with mix files, doesn't delete the old versioned files.
2. It is because the hot reload HMR doesn't support versioned files, so that I have to put the second config files in order to have both versions support and HMR support.

**Comment by JeffreyWay** [comment]
We do have some HMR work to do, so files not being versioned is a known issue and is detailed in one of the other open issues here.

**Comment by libern** [comment]
@JeffreyWay How to address the first issue?
