### ISSUE TITLE
Not working for complied css file to output under resources folder

### ISSUE THREAD

**Issue by libern** [JeffreyWay/laravel-mix#438]
I have tried to set the output path under `resources` folder:

```
mix.less('resources/assets/less/app.less', 'resources/assets');
```

The output says:

```
Compiled successfully in 1591ms


                   Asset      Size  Chunks             Chunk Names
                  mix.js   2.75 kB       0  [emitted]  mix
resources/assets/app.css   80.2 kB       0  [emitted]  mix
       mix-manifest.json  86 bytes          [emitted]  
```

However, no matter which folder under `resources` I have set the output to, I can't find it after the compile as of v0.8.0.

It works when I set to `public/assets/css`

**Comment by libern** [comment]
UPDATE 

After some tests, it seems that if I point to `resources/..` instead of `public/..` as output folder,

The file been generated will be put under `public/resources/..`, looks like WIRED.

**Comment by JeffreyWay** [comment]
We assume a public/ base directory for your output. You can override that with the `mix.setPublicPath()` method.

```js
mix.less('resources/assets/less/app.less', 'output')
   .setPublicPath('resources');
```
