### ISSUE TITLE
The '$().modal is not a function' error in my project when I use 'bootstrap-sass'.

### ISSUE THREAD

**Issue by ElanMu** [JeffreyWay/laravel-mix#443]
- Laravel Mix Version: 0.8.0
- Node Version (`node -v`): 6.9.4 
- NPM Version (`npm -v`): 4.2.0
- OS: mac

### Description:
  I add the module of 'modal' to the bootstrap in my 'bootstrap-sass'. But there is always a error that is '$().modal is not a function' in my console.

### Steps To Reproduce:

# **in my bootstrap-sass**
![image](https://cloud.githubusercontent.com/assets/22315478/23194776/0a957672-f8eb-11e6-8312-b4cfcc9e1117.png)

# **## in my webpack.mix.js:**
mix.js(['resources/assets/js/app/app.js',
	'resources/vendor/layer/layer.js',
	'resources/assets/js/app/main.js'
	], 'public/js/app.js')
	.extract(['jquery', 'bootstrap-sass', 'bootstrap-datepicker', 'admin-lte', 'lodash', 'vue']);

**# in my php file**
![image](https://cloud.githubusercontent.com/assets/22315478/23194808/4578e0a8-f8eb-11e6-8b01-0288aceef4dc.png)

**# **in my console****
![image](https://cloud.githubusercontent.com/assets/22315478/23194826/6778a2ec-f8eb-11e6-8558-155f7aa62b51.png)

Thanks for your help!

**Comment by benkelukas** [comment]
Hi,
did you ever find solution for this? I'm facing a similiar issue :)

**Comment by Glorian** [comment]
Dirty hack:

In your app.js
```javascript
 window.$ = jQuery; // jQuery - global variable inside your js application.
```

**Comment by NicolaLeonardi** [comment]
@Glorian Man you saved my life. Really.

**Comment by simonberton** [comment]
Hi. also:
`import $ from 'jquery';`
