### ISSUE TITLE
laravel 5.4's package.json still hardcoded to "laravel-mix": "^0.8.0",

### ISSUE THREAD

**Issue by thetechyhub** [JeffreyWay/laravel-mix#444]
{
  "private": true,
  "scripts": {
    "dev": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "build" : "webpack"
  },
  "devDependencies": {
    "axios": "^0.15.2",
    "bootstrap-sass": "^3.3.7",
    "clean-webpack-plugin": "^0.1.15",
    "del": "^2.2.2",
    "jquery": "^3.1.0",
    "laravel-mix": "^0.5.0",
    "lodash": "^4.16.2",
    "spin": "0.0.1",
    "spin.js": "^2.3.2",
    "vue": "^2.0.1",
    "webpack-load-plugins": "^0.1.2"
  },
  "dependencies": {
    "fs-extra": "^2.0.0",
    "spin": "0.0.1",
    "spin.js": "^2.3.2",
    "webpack": "^2.2.1"
  }
}

It cant auto upgrade to "laravel-mix": "^0.8.0" to latest version.

**Comment by QWp6t** [comment]
just change it to `^0.8.1` ezpz lol
