### ISSUE TITLE
v0.8.3 mix.js outputs file relative to public folder

### ISSUE THREAD

**Issue by adifaidz** [JeffreyWay/laravel-mix#452]
- Laravel Mix Version: 0.8.3
- Node Version : v6.9.1
- NPM Version : 3.10.8
- OS: Windows 10

### Description:
The new v0.8.3 outputs the compiled javascript relative to public folder. So if now I were to compile this code, 

```javascript
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');
```

It will output the files to:

```
public/public/js/app.js
public/css/app.css
```
### Steps To Reproduce:

+ Install v0.8.3 and run `npm run dev`

**Comment by weldricks** [comment]
As a quick fix, I believe the error lies in the webpack path for public/js which Jeffery is probably fixing as I type, just removing the public part seems to work:

mix.js('resources/assets/js/app.js', '/js')
   .sass('resources/assets/sass/styles.scss', 'public/css');

**Comment by Hendriksie** [comment]
I think this works as it should, probably because it now uses the `publicPath` variable.

If you look at the `initialize` function in the `Mix.js`:

`if (this.isUsingLaravel()) this.publicPath = 'public';`

I'm not sure if this is relevant but I thought it could be useful to tell you.

**Comment by adifaidz** [comment]
@weldricks yeah, forgot to point that out. Thanks 👍

**Comment by JeffreyWay** [comment]
I can't reproduce this. Can any of you do `npm update laravel-mix` to bump to 0.8.4, and then confirm that this is still an issue?

**Comment by d3radicated** [comment]
Can confirm in 0.8.4.

**Comment by JeffreyWay** [comment]
So if you do:

```
laravel new test && cd test
npm install
npm run dev
```

...you get `public/public/js/app.js`??

**Comment by d3radicated** [comment]
public/js/app.js   1.16 MB       0  [emitted]  [big]  public/js/app
        /css/app.css    684 kB       0  [emitted]  [big]  public/js/app

Yep.

**Comment by JeffreyWay** [comment]
Windows or Mac? You're positive that you're on 0.84? Fresh install gives me:

https://www.dropbox.com/s/szrtzb71n112bxx/Screenshot%202017-02-23%2011.25.28.png?dl=0

**Comment by d3radicated** [comment]
Windows 10. It might be an OS-specific issue.

[Imgur](https://i.imgur.com/ySqupKX.png)

**Comment by ichmbch** [comment]
I can confirm this issue on a fresh laravel installation on Windows 10.

laravel/installer - 1.3.5
laravel-mix - 0.8.4
node - 6.10.0
npm - 4.2.0

**Comment by QWp6t** [comment]
I can confirm as well.

![](http://i.imgur.com/1uP5ZuG.png)

**Comment by JeffreyWay** [comment]
Okay, well it would be great if some of you Windows users could dig in and figure out what's happening here.

Maybe open this file and do a few console.logs() to figure out what the deal is.

https://github.com/JeffreyWay/laravel-mix/blob/master/src/EntryBuilder.js#L39

**Comment by d3radicated** [comment]
I added the following lines before `this.entry.add()`.

    console.log(paths);
    console.log(this.entryName(paths.output));

![Imgur](https://i.imgur.com/JEOr2Av.png)

**Comment by JeffreyWay** [comment]
@d3radicated Perfect. Can you go to that file, and change the `entryName` method to this?

```js
    entryName(output) {
        return output.pathWithoutExt
            .replace(/\\/g, '/');
            .replace(this.mix.publicPath + '/', '/')
    }
```

And then run it again. Does that fix it?

**Comment by d3radicated** [comment]
That solves it.

![Imgur](https://i.imgur.com/7s2trLI.png)

**Comment by JeffreyWay** [comment]
Wahoo! I've fixed and tagged it. `npm update laravel-mix`

**Comment by gags88** [comment]
Hi @JeffreyWay ...

Finally a long Day and i came across this post.
Degrading from v1.0 to v 0.8 worked for me.

But can you let me know that what is the alternative for
`Mix.output().path` in `laravel-mix v1.0` that comes with laravel v5.4.22

as I am facing issues in below code with v1.0

```
let HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports.plugins.push(
  new HtmlWebpackPlugin({
    template: Mix.Paths.root('resources/views/index.html'),
    inject: false
  })
)

let PrerenderSpaPlugin = require('prerender-spa-plugin');
console.log(Mix.output().path);
module.exports.plugins.push(
  new PrerenderSpaPlugin(
    Mix.output().path,
    [ '/' ]
  )
)
```
