### ISSUE TITLE
How do I configure webpack to expose my javascript class in the global context?

### ISSUE THREAD

**Issue by iainheng** [JeffreyWay/laravel-mix#454]
- Laravel Mix Version: 0.8.3
- Node Version (`node -v`): 7.6.0 
- NPM Version (`npm -v`):  4.2.0
- OS: Windows 10

### Description:
How do I configure webpack to expose my javascript class in the global context within a variable of my own, like `MyClass`? I have the same question as in this post http://stackoverflow.com/questions/34357489/calling-webpacked-code-from-outside-html-script-tag

How do we configure that in our `webpack.mix.js`?

**Comment by JeffreyWay** [comment]
Can't you just assign it to the window object after your import it?

```js
import MyClass from './MyClass.js';
window.MyClass = MyClass;
```
