### ISSUE TITLE
mix.styles([]) is not a function

### ISSUE THREAD

**Issue by tprifti** [JeffreyWay/laravel-mix#457]
- Laravel Mix Version: "^0.6.0",
- Node Version (`node -v`): v.6.10.0
- NPM Version (`npm -v`): 4.1.1
- OS: Windows 7 32 bit

### Description:

When I try to combine multiple css files into one files using this code it doesnt work : 
`let mix  = require('laravel-mix');`
`mix.styles([
	'resources/assets/back/plugins/bootstrap/css/bootstrap.css',
        'resources/assets/back/plugins/node-waves/waves.css',
        'resources/assets/back/plugins/animate-css/animate.css',
        'resources/assets/back/plugins/material-design-preloader/md-preloader.css'
    ], 'public/back/css/vendor.css');`

Command prompt throws this error : mix.styles(...) is not a function

**Comment by d3radicated** [comment]
Change `let mix = require('laravel-mix');` to `const { mix } = require('laravel-mix');`

**Comment by tprifti** [comment]
@d3radicated Same error even i changed that line.

**Comment by d3radicated** [comment]
I think `mix.styles` has been deprecated. If your just combining the css together, try using [mix.combine()](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/concatenation-and-minification.md).

**Comment by tprifti** [comment]
That did the trick. Thanks a lot!

**Comment by dmarman** [comment]
Documentation should be updated then.
