### ISSUE TITLE
Failed on Custom Webpack Configuration

### ISSUE THREAD

**Issue by SamXiao** [JeffreyWay/laravel-mix#458]
- Laravel Mix Version: 0.8.4
- Node Version (`node -v`): 7.5.0
- NPM Version (`npm -v`): 4.1.2
- OS:  MacOS 10.12.3

### Description:
Got error when I try to custom Webpack configuration.

    /Library/WebServer/Documents/bright-tech/dms/webpack.mix.js:21
        path.resolve(__dirname, 'vendor/bright-tech/inspinia-admin/dist')
    ReferenceError: path is not defined

### Steps To Reproduce:

add

    mix.webpackConfig({
        resolve: {
            modules: [
                path.resolve(__dirname, 'vendor/bright-tech/inspinia-admin/dist')
            ]
        }
    });
into webpack.mix.js and 

    npm run dev
my webpack.mix.js is

    const { mix } = require('laravel-mix');

    /*
     |--------------------------------------------------------------------------
     | Mix Asset Management
     |--------------------------------------------------------------------------
     |
     | Mix provides a clean, fluent API for defining some Webpack build steps
     | for your Laravel application. By default, we are compiling the Sass
     | file for the application as well as bundling up all the JS files.
     |
     */

    mix.js('resources/assets/js/app.js', 'public/js')
       .sass('resources/assets/sass/app.scss', 'public/css');

    mix.webpackConfig({
        resolve: {
            modules: [
                path.resolve(__dirname, 'vendor/bright-tech/inspinia-admin/dist')
            ]
        }
    });

**Comment by d3radicated** [comment]
Try adding `let path = require('path');` after requiring laravel-mix.

**Comment by SamXiao** [comment]
It works. Thanks!
BTW should we add this solution into Laravel Docs?
