### ISSUE TITLE
laravel mix fails if the working dir path contains and exclamation mark "!"

### ISSUE THREAD

**Issue by nmirceac** [JeffreyWay/laravel-mix#463]
ERROR  Failed to compile with 2 errors                                                                                                                                                          12:41:30 PM

These dependencies were not found in node_modules:

* /var/www/!htdocs-new/resources/assets/js/app.js in multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
* /var/www/!htdocs-new/resources/assets/sass/app.scss in multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

Did you forget to run npm install --save for them?
                          Asset      Size  Chunks             Chunk Names
/js/app.d41d8cd98f00b204e980.js    6.5 kB       0  [emitted]  /js/app
              mix-manifest.json  53 bytes          [emitted]  

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/opt/node/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/!htdocs-new/npm-debug.log

I guess all would be ok with a \! instead of ! (in the specified paths)

**Comment by QWp6t** [comment]
It might be related to this: https://webpack.js.org/concepts/loaders/#via-require

**Comment by nmirceac** [comment]
so how would one escape the "!"? shouldn't the PWD be escaped?

**Comment by devcircus** [comment]
looks like its not specific to mix. Here's a couple of similar issues i found:
https://github.com/jantimon/html-webpack-plugin/issues/530
https://github.com/davezuko/react-redux-starter-kit/issues/916#issuecomment-231394811

**Comment by Varin6** [comment]
This still exists, took me almost half a day to figure this one out, tried different npm/node versions to no avail. Finally moved the whole project to a different folder and it all magically started to work. I think it would be worth reopening this one and taking a second look at escaping `!` in the path.

**Comment by nmirceac** [comment]
> This still exists, took me almost half a day to figure this one out, tried different npm/node versions to no avail. Finally moved the whole project to a different folder and it all magically started to work. I think it would be worth reopening this one and taking a second look at escaping `!` in the path.

Sorry about it... Also took me some time. Hope it will save people some time in the future. Just abandoned "!" paths.
Good luck

**Comment by saad2128** [comment]
> This still exists, took me almost half a day to figure this one out, tried different npm/node versions to no avail. Finally moved the whole project to a different folder and it all magically started to work. I think it would be worth reopening this one and taking a second look at escaping `!` in the path.
  
I am having the same issue,dont know this ! path.Can anyone help me out for this
