### ISSUE TITLE
Allow the use of environment variables in scripts (pull request attached)

### ISSUE THREAD

**Issue by adiachenko** [JeffreyWay/laravel-mix#465]
This is a common pattern present in webpack apps. You can define environment variable (for example, in your `.env` file) and use it in javascript via `webpack.DefinePlugin`.

Notes:
- this doesn't present security vulnerabilities. Firstly, only explicitly requested variables are substituted by definitions from DefinePlugin. Secondly, we filter out variables by `/^MIX_/i` regex.
- there is no noteworthy impact on performance
- the pattern is already proven and battle tested by several popular boilerplates including [CRA](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/env.js)
- this is not a breaking change for existing `laravel-mix` users

Pull request is attached: #464

**Comment by JeffreyWay** [comment]
Thanks. Going over your PR tonight. Closing this.
