### ISSUE TITLE
Mixing single JS file not creating expected file

### ISSUE THREAD

**Issue by PauBenetPrat** [JeffreyWay/laravel-mix#468]
I'm compiling a test.js file located on my resources and the output generated file doesn't work.

I've just created a new laravel5.4 project from scratch. Created `resources/assets/js/test.js`with a single function:
```
function testFunction() {
    console.log('test');
}
```

I've cleaned welcome.blade and instead I simply import js/test.js script from public folder and execute my function
```
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
    <head>
        <script src="{{ url("js/test.js") }}"></script>
    </head>
    <body>
    <script>
        testFunction();
    </script>
    </body>
</html>
```

On my webpack.mix I'm only compiling test.js
`mix.js('resources/assets/js/test.js', 'public/js');`

It compiles succesfully but when I visit welcome page I receive 
`testFunction is not defined`

Any idea what's going on? On inspector I can see that my js is loading ok too.

**Comment by danremollino** [comment]
Use `{{ mix('js/test.js') }}` as your script src.

**Comment by PauBenetPrat** [comment]
This does not appear to be my problem, url or mix does work. My problem is the resulting public/js/test.js was weird and not working. I found a workaround using mix.combine and now it seems to work correctly.

`mix.combine(['resources/assets/js/test.js'], 'public/js/test.js');`

**Comment by JeffreyWay** [comment]
When it compiles, it won't automatically be in the global space. You have to explicitly request that.

```js
window.testFunction = function () {
    console.log('test');
}
```
