### ISSUE TITLE
mix() method not working in Blade templates

### ISSUE THREAD

**Issue by gmask** [JeffreyWay/laravel-mix#47]
Hello, I am on Laravel Framework version 5.3.28 and have installed Laravel Mix via NPM. Using the `version()` API option results in the following error in my blade template: `Call to undefined function mix() (View: /var/www/html/servicedesk/resources/views/welcome.blade.php)`

I am implementing in the following way, per docs:
```
<link rel="stylesheet" href="{{ mix('css/app.css') }}">
<script src="{{ mix('js/app.js') }}"></script>
```

How can I resolve this?

**Comment by JeffreyWay** [comment]
Laravel Mix hasn't been integrated into Laravel yet. Once it has been, you can use that function. Until then, either write your own, or reference the app.js file directly.

**Comment by Germey** [comment]
mix method will be supported since 5.4.x? How can I add it in 5.3.x?

**Comment by Hasgaroth** [comment]
@Germey - As @JeffreyWay said earlier, you need to either create your own, or upgrade to Laravel 5.4.x to gain access to the `mix()` function.
I have just upgraded my (small) Laravel app in under an hour from v5.3.x to v5.4.19.

**Comment by 7ammer** [comment]
Try this:

```php
function cacheBuster($asset_url) {
	try {
		$file = file_get_contents(base_path() . "/public/mix-manifest.json");
	} catch (Exception $e){
		return url('/') . $asset_url;
	}

	$json = json_decode($file, true);

	foreach ($json as $key => $a) {
		if($asset_url == $key) return url('/') . $a;
	}

	return url('/') . $asset_url;
}
```

**Comment by AFortune** [comment]
If you do not feel like updating [this is the 5.3 way of doing things.](https://laravel.com/docs/5.3/elixir#versioning-and-cache-busting)

**Comment by jamestangeres** [comment]
> 7ammer

Where Can I add this? Tia
