### ISSUE TITLE
npm run watch not working

### ISSUE THREAD

**Issue by DevDuckEl** [JeffreyWay/laravel-mix#473]
- Laravel Mix Version: 0.8.7
- Node Version (`v6.9.5`): 
- NPM Version (`4.3.0`): 
- OS: Ubuntu 16.04

### Description:
After running `npm run watch` or `npm run watch-poll` I get the message: ` DONE  Compiled successfully in 11019ms.` Next, I change js or css files, but recompiling is not happening. But `npm run dev` or `npm run production` are working fine. What's wrong?

webpack.mix.js:
```javascript
const { mix } = require('laravel-mix');

mix.js('resources/assets/js/app.js', 'public/js')
   .js('resources/assets/js/pages.js', 'public/js')
   .js('resources/assets/js/srext.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .combine([
       'resources/library/**/css/*.css'
   ], 'public/css/all.css')
   .js('resources/library/ext/js/notjs.js', 'public/js/all.js')
   .version();
```

### Steps To Reproduce:
`npm run watch` or `npm run watch-poll`

**Comment by jastend** [comment]
Hi @DevDuckEl,

Not sure whether that's intended, but I've seen the same behaviour whenever I tried to use Wildcard characters for files. In this case, the watching doesn't work.

Try it without the following to confirm:

```
   .combine([
       'resources/library/**/css/*.css'
   ], 'public/css/all.css')
```

**Comment by DevDuckEl** [comment]
Hi @jastend!

I replaced:
```javascript
 .combine([
       'resources/library/**/css/*.css'
   ], 'public/css/all.css')
```
to:
```javascript
.stylus('resources/library/ext/css/notjs.css', 'public/css/all.css')
```

Recompiling is not happening.

**Comment by jastend** [comment]
Ah, that makes sense. Thanks @DevDuckEl

**Comment by JeffreyWay** [comment]
It's really tough to say, when it comes to watcher issues. You might start here:

https://github.com/JeffreyWay/laravel-mix/blob/master/docs/faq.md#im-using-a-vm-and-webpack-isnt-picking-up-my-file-changes

**Comment by CabdirisaaQ** [comment]
Guys, JeffreyWay linked helped alot. this is my previouse script object in packages.json
  
`  "watch": "cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",

change that to the following 

    "watch": "cross-env NODE_ENV=development webpack --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",


if you notice I've added " --watch-poll " after --watch

**Comment by markskayff** [comment]
I wonder if there's some reason why this suddenly stopped working and this --watch-poll must be added now.

**Comment by thibaultvanc** [comment]
sudo sysctl fs.inotify.max_user_watches=900000000

**Comment by hayjay01** [comment]
i fixed this just now by navigating to my webpack.mix.js file located in the root directory this was commented out before ```mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css');``` i then uncommented it and everything works fine with running npm run watch-poll in the terminal

**Comment by nwaweru** [comment]
@thibaultvanc worked fine for me. Ubuntu 16.04. Thanks.

**Comment by poncianodiego** [comment]
Can someone explain why this happens please would be awesome :)

**Comment by skyArony** [comment]
--watch-poll is useful ，but it consume a lot hardware （cpu）@JeffreyWay

**Comment by BeGnuLinux** [comment]
@thibaultvanc worked fine for me.on kali rolling 2018.1

**Comment by mmamoonkhan** [comment]
@thibaultvanc i waste to much time to solve this issue but your solution saved me thank you

**Comment by santi755** [comment]
@thibaultvanc Oh thanks! that worked for me!

**Comment by Jafo232** [comment]
I am just now having these issues out of nowhere.  No fixes suggested here or in the docs have worked.

**Comment by SturmB** [comment]
I am, likewise, having issues with this now. I did recently upgrade my Laravel-based apps from 5.7/5.8 to the current version (8.0 as of this writing), so I don't know if I need to make changes to my `webpack.mix.js` file to compensate.

As the OP said, the watcher seems to run just fine (like running `npm run dev`), but then fails to pick up any subsequent changes to the files.
