### ISSUE TITLE
mix.stylus is not a function

### ISSUE THREAD

**Issue by jakubkratina** [JeffreyWay/laravel-mix#475]
- Laravel Mix Version: 0.6.0
- Node Version: 7.6.0
- NPM Version: 
- OS: OS X

### Description:
When I create a new Laravel project (`composer create-project --prefer-dist laravel/laravel laravel-5.4`), run `npm install`, change default `webpack.mix.js` from:
```
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');
```
to
```
mix.js('resources/assets/js/app.js', 'public/js')
   .stylus('resources/assets/sass/app.scss', 'public/css');
```

and run `npm run dev`, I get:

```
mix.stylus('resources/assets/sass/app.scss', 'public/css');
    ^

TypeError: mix.stylus is not a function
```

How is that? Shouldn't be stylus supported out of the box?

Thank you.

**Comment by jakubkratina** [comment]
Same with `mix.scripts is not a function`.

**Comment by jakubkratina** [comment]
Well, I used a 0.6.0. version. I thought the installation via `composer create-project` installs the latest version of laravel (with the latest mix version), but it installed me 5.4.13 version of Laravel with 0.6.0 of mix.

**Comment by lucasmezencio** [comment]
Same issue here.

**Comment by sacerdos82** [comment]
Same here.

**Comment by jakubkratina** [comment]
@lucasmezencio @sacerdos82 For now, you can go here and install these versions: https://github.com/laravel/laravel/blob/master/package.json

**Comment by JeffreyWay** [comment]
Yeah, update to the latest version of Mix that supports `mix.scripts()` and `mix.stylus()`.
