### ISSUE TITLE
Tip for Ubuntu Users

### ISSUE THREAD

**Issue by swt83** [JeffreyWay/laravel-mix#476]
On Ubuntu I had to run this to get ``npm install`` working:

```bash
$ sudo apt-get install nodejs-legacy
```

Had something to do with this issue that is specific to Ubuntu machines:

http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu

Might add this to the documentation.

**Comment by swt83** [comment]
Ya, it was a mess.  What I ended up doing was using this process to install an updated version of node.  Apparently the apt-get version was super old:

```
On Ubuntu 14.04.5 LTS the easier way is

Install npm:
sudo apt-get install npm

Install n
sudo npm install n -g

Get latest version of node
sudo n latest
```

http://stackoverflow.com/questions/34974535/install-latest-nodejs-version-in-ubuntu-14-04

Then I did a massive purge of the old version:

```
sudo apt-get purge node-abbrev node-ansi node-archy node-async node-block-stream node-combined-stream node-cookie-jar node-delayed-stream node-forever-agent node-form-data node-fstream node-fstream-ignore node-github-url-from-git node-glob node-graceful-fs node-gyp node-inherits node-ini node-json-stringify-safe node-lockfile node-lru-cache node-mime node-minimatch node-mkdirp node-mute-stream node-node-uuid node-nopt node-normalize-package-data node-npmlog node-once node-osenv node-qs node-read node-read-package-json node-request node-retry node-rimraf node-semver node-sha node-sigmund node-slide node-tar node-tunnel-agent node-which nodejs nodejs-dev nodejs-legacy
```

**Comment by JeffreyWay** [comment]
Thanks for this. Will go ahead and close.
