### ISSUE TITLE
Minifying css is not working when the processCssUrls option is false

### ISSUE THREAD

**Issue by Rigorbb** [JeffreyWay/laravel-mix#477]
- Laravel Mix Version: 0.8.7
- Node Version 7.5.0
- NPM Version 4.1.2
- OS: macOs Sierra

### Description:

I have the problem with minifying css if processCssUrls option is false.

Minify is not working because raw-loader (which use in this case) does not support minify. Can we use css-loader in this case too? In #471 request i fix this.

### Steps To Reproduce:

1) add this to webpack.mix.js: 
```
mix.options({
    processCssUrls: false
});
```
2) run npm run production.
3) The minifying css was expected to be working but it is not. If the processCssUrls is true then minifiyng working fine

**Comment by JeffreyWay** [comment]
Closing in favor of the PR.

**Comment by CBox** [comment]
How to fix that? I'm heaving the same issue.

**Comment by Rigorbb** [comment]
What version are you using? In 0.9.1 this bug was fixed

**Comment by CBox** [comment]
I've used 0.8 :/ updated to 0.11 everything working great thanks!
