### ISSUE TITLE
Cannot find module cross-env

### ISSUE THREAD

**Issue by phuclh** [JeffreyWay/laravel-mix#478]
- Laravel Mix Version: 0.8.7
- Node Version (`node -v`): 7.6.0
- NPM Version (`npm -v`): 4.3.0
- OS: MacOS

### Description:
I am using Spark (latest version) but when I compiled css and js by using `npm run dev` then I got an error:

```
Cannot find module '/PATH/node_modules/cross-env/bin/cross-env.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.6.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/.npm/_logs/2017-02-26T08_26_31_924Z-debug.log
```

I tried to update npm, node, laravel-mix and remove all modules in node_modules and re-install but I still got that error.

**Comment by mirbatworks** [comment]
I have same problem on Ubuntu 16.04. It seams that is some problem with syntax in webpack.config.js

**Comment by JeffreyWay** [comment]
Can you check your installed version of Mix again?  0.8.7 doesn't exist.

**Comment by iHazzam** [comment]
If you're using homestead, you get this error if you run the command in the VM. 

https://github.com/JeffreyWay/laravel-mix/issues/447

Try the scripts in the link rather than the ones you are currently using in your config

**Comment by tgustinak** [comment]
I'm having the same issue.

```bash
$ npm -v 
4.3.0
$ node -v
v7.6.0
```

package.json
```json
{
  "private": true,
  "scripts": {
    "dev": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.15.2",
    "bootstrap-sass": "^3.3.7",
    "jquery": "^3.1.0",
    "laravel-mix": "^0.5.0",
    "lodash": "^4.16.2",
    "vue": "^2.0.1"
  }
}
```

webpack.mix.js
```javascript
const { mix } = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/assets/js/app.js', 'public/js');
```

npm log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.6.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@4.3.0
3 info using node@v7.6.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 silly lifecycle @~predev: no script for predev, continuing
7 info lifecycle @~dev: @
8 verbose lifecycle @~dev: unsafe-perm in lifecycle true
9 verbose lifecycle @~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/tomasgustinak/Code/seduco-clients/node_modules/.bin:/usr/local/sbin:vendor/bin:/Users/tomasgustinak/.composer/vendor/bin:/usr/local/git/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle @~dev: CWD: /Users/tomasgustinak/Code/seduco-clients
11 silly lifecycle @~dev: Args: [ '-c',
11 silly lifecycle   'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js' ]
12 silly lifecycle @~dev: Returned: code: 1  signal: null
13 info lifecycle @~dev: Failed to exec dev script
14 verbose stack Error: @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @
16 verbose cwd /Users/tomasgustinak/Code/seduco-clients
17 error Darwin 16.4.0
18 error argv "/usr/local/Cellar/node/7.6.0/bin/node" "/usr/local/bin/npm" "run" "dev"
19 error node v7.6.0
20 error npm  v4.3.0
21 error code ELIFECYCLE
22 error errno 1
23 error @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
23 error Exit status 1
24 error Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the  package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by phuclh** [comment]
I run the command out the VM but still got this error :(

**Comment by dwoodard** [comment]
cross-env must have updated its paths, it has "cross-env/dist/bin" not "cross-env/bin/"

in package.json
change:
    "watch": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",

to

    "watch": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",

**Comment by Jam0r85** [comment]
@dwoodard +1 thank you! This worked for me. Been trying top figure this out all day!

**Comment by marcusrall** [comment]
@dwoodard  nice, thanks

**Comment by devcronix** [comment]
@dwoodard, works, thank you!

**Comment by jivemonkey2000** [comment]
First result on Google, and worked first time. Thank you @dwoodard.

**Comment by Alfred-W** [comment]
@dwoodard Thanks alot for this!!!

**Comment by garethdaine** [comment]
You'll need to change the references to this path for all scripts, including:

- dev
- watch
- hot
- production

**Comment by michaeljoshua55555** [comment]
@dwoodard  Thank a lot

**Comment by mostafa6765** [comment]
@phuclh 

* `npm install --save-dev cross-env`
* `npm install`

Now 
npm run dev 
npm run watch

**Comment by wakaranja** [comment]
Thank you. Had split some hairs because of this.

**Comment by amitbk** [comment]
Replacing "cross-env/bin/" with "cross-env/dist/bin" in package.json solved my issue...

Now its working fine.
Thanks @dwoodard 

@JeffreyWay can you please update package.json with laravel default installation?

**Comment by bellalMohamed** [comment]
Thanks @dwoodard :smile:

**Comment by driesvints** [comment]
@amitbk already been done: https://github.com/laravel/laravel/pull/4167

**Comment by Daniel-Griffiths** [comment]
Thanks @dwoodard

**Comment by kjunggithub** [comment]
Thanks for the detailed information @mostafa6765!

**Comment by silviolleite** [comment]
Thanks @phuclh it works perfectly :)

**Comment by cristianmeza** [comment]
Many thanks @dwoodard, after hours of fighting in Windows, finally I have Laravel Mix working. Greetings from Chile.

**Comment by wagelvis** [comment]
@dwoodard cool, thanks !!

**Comment by zcmyworld** [comment]
This worked for me.Thanks!

**Comment by estebangallego** [comment]
@dwoodard Thanks!

**Comment by bart** [comment]
We had the same issue here but changing the package.json file is not a good option when you work in a big team with different dev environments. My solution here is a simple ```npm install -g cross-env```. That should do the trick.

**Comment by realtebo** [comment]
Actually, I fixed with this sequence. 
After that, I'm able to run `npm run dev` inside `vagranth ssh` connection

```
sudo rm node_modules/ -rf

# Execute two times to resolve the problem with ` Maximum call stack size exceeded` 
# while finalizing 
# Also note: I'm using --no-bin-links because I've a Windows 7 host
npm install --no-bin-links || npm install --no-bin-links

# this avoid problem with `cross-env not found`
sudo npm install cross-env -g --no-bin-links

# this avoid problem with `Module build failed: ModuleBuildError: Module build failed:
# Error: ENOENT: no such file or directory, scandir 
#'/home/vagrant/Code/phonix/node_modules/node-sass/vendor' `

npm rebuild node-sass --no-bin-links
```

I do not alter `package.json` file

**Comment by patlecat** [comment]
It's July 2017, I did a fresh installation of Homestead (on Windows 10) and Laravel 5.4 and still got this cross-env error during npm install !! But now the mix file looks different with the paths so the above tips won't work anymore. Why is this still a problem after such a long time at this very basic and important functionality?

**Comment by ruchern** [comment]
@patlecat Because `cross-env` is now removed from `Laravel-Mix` by default. If you are a Windows user, then you will have to install `cross-env` manually.

**Comment by laracasts** [comment]
Look at your package.json file. Laravel includes cross-env as a dependency.

**Comment by patlecat** [comment]
@laracasts Yes Jeffrey I saw that it is included but somehow was not installed until I did it manually :( 

@ruchern  And no by using Homestead I'm not a Windows user when it comes to Laravel installation, this is on the Linux VM and uses Linux components, commands, libs  and paths. I checked (since I use all the latest components with a fresh Homestead install, it's using nodejs 6.11.x LTS, I leave it as is, because before I had very bad experience with updating node + npm it broke everything and I had to go back to the original version of Homestead again.

**Comment by devcircus** [comment]
Frontend should be handled by your local machine. You can make it work on the vm but every recommendation I've ever read was to run your backend on vm and frontend locally. I've been doing it for years with homestead and never had an issue. 

Maybe it's improved over the years and recommendations have changed though...

**Comment by ruchern** [comment]
@patlecat I know by using Homestead you are creating a Linux environment. I wrote that just in case you accidentally ran the command on Windows CMD instead.

npm v3 could be a little outdated. You might want to try the latest version of v4.

**Comment by kwebble** [comment]
@ruchern thanks for the info.

> Because cross-env is now removed from Laravel-Mix by default. If you are a Windows user, then you will have to install cross-env manually.

For me this means an application that previously build successfully suddenly failed. I hope this will be fixed, manually adding the package isn't a great solution.

**Comment by JeffreyWay** [comment]
> For me this means an application that previously build successfully suddenly failed. I hope this will be fixed, manually adding the package isn't a great solution.

We removed the dependency with the 1.0 release. It was the right time to remove that dependency. It takes five seconds to do `npm i cross-env`.

**Comment by patlecat** [comment]
@JeffreyWay I have no problem following installation instructions, if all that is documented there. Things change, I accept and welcome that, but I'm no psychic I can't guess what changed.

@ruchern Okay so you recommend compiling the website in the VM (on linux) right? I would be totally confused if that was not the intention after all. And you recommend staying on nodejs 6.11.x but updating only npm and to the latest version 4.x?

**Comment by ruchern** [comment]
@patlecat Yes, you should be and I assume you did, run the scripts in the Homestead environment.

As for the npm version, the latest now is v5.3.0, but it is plagued with a lot of problems. v4 is very stable so to speak. I am not sure if v4 is outdated that it won't work anymore.

**Comment by georaldc** [comment]
> Frontend should be handled by your local machine. You can make it work on the vm but every recommendation I've ever read was to run your backend on vm and frontend locally. I've been doing it for years with homestead and never had an issue.

@devcircus Doesn't that become an issue if say, the project uses yarn and depends on its generated lock file? If the lock file was built under a unix environment, won't you run into issues if you install dependencies using it on your local machine if it runs on something else like Windows?

**Comment by kwebble** [comment]
@JeffreyWay it takes a short time to install, but much more time to investigate why a script that comes with the framework ends in error. 

The way to describe that a Node application needs additional code to run is by including it in `package.json`, why not use that mechanism?

(Added to my [list of Laravel tips & pitfalls](http://kwebble.com/blog/2017/05/17/laravel-tips))

**Comment by realtebo** [comment]
@JeffreyWay 

>  It was the right time to remove that dependency

Why? If it IS NEEDED it IS a dependency...

I'm sure I've lost something ....

**Comment by JeffreyWay** [comment]
@realtebo It's not required. I don't think people understand that the only need for cross-env is to allow for cross-platform npm scripts. If you're a Mac user, you don't need it. If you're a Windows users, either pull it in, or tweak the npm script to fit your platform.

**Comment by ruchern** [comment]
In addition to @JeffreyWay, Linux also do not need `cross-env`.

**Comment by devcircus** [comment]
I use windows without cross-env. I simply adjusted my script in package.json as below:
```js
"development": "set NODE_ENV=development&& webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "set NODE_ENV=development&& webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
//
```

**Comment by patlecat** [comment]
Is Laravel-Mix actually known to work consistently and flawlessly on any other platform than **Mac OSX**? I wonder, do you guys even test it as thoroughly under Linux like Ubuntu and Homestead?

**Comment by ruchern** [comment]
@patlecat Yes. I am running macOS 10.12 and Linux (Ubuntu) on my production server (NOT Homestead) and it worked right out from the box.

**Comment by patlecat** [comment]
@ruchern Okay so you tested it personally like a dev on 2 OS? And do you know of any more formal testing environments and methods?

@JeffreyWay Maybe you can also comment on this? It would be an invaluable information.

**Comment by devcircus** [comment]
Mix has a full test suite. Just fork, clone, and run the tests on the OS of your choosing.

**Comment by ruchern** [comment]
@patlecat Yes, I did. I think you should use a CI and push your code to Github repo and see if the CI builds your stuff properly.

**Comment by patlecat** [comment]
@ruchern To push what exactly into the CI? My fresh installation out of the box of Laravel and Mix that produced errors? Or what do you suggest?

**Comment by jmanzo** [comment]
I just install yarn command globally: https://yarnpkg.com/en/docs/install

This help me a lot to clear my panoram...

**Comment by brian-lamb-software-engineer** [comment]
@phuclh thats what i had, and had to switch to what @dwoodard initially recommended.   This is working fine on my other package, today i used powershell to run npm, as opposed to vbox linux, and ran into this in the new app.  not sure, if they just changed something then i should be seeing this on all apps after running npm install.

**Comment by adanwo** [comment]
From Windows:
Right clic over folder.
Git bash
npm run dev

**Comment by OnlyCRed** [comment]
HOMESTEAD (v6.2.2 VAGRANT BOX WINDOWS 10, RUNNING GITBASH AS AN ADMINISTRATOR 
LARAVEL 5.4 FROM SCRATCH: Episode 14 Laravel Mix and the Front-end
cd /home/vagrant/Code/Laravel
<enter>
sudo chown -R $USER:$(id -gn $USER) /home/vagrant/.config
<enter>
	NOT NECESSARY sudo apt-get purge nodejs npm
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
<enter>
sudo apt-get install -y nodejs
<enter>
node -v
<enter>
npm -v
<enter>
npm install -g yarn
<enter>
sudo npm install --save-dev cross-env
<enter>
sudo npm install --no-bin-links
<enter>
sudo yarn install
<enter>
	composer manage PHP dependencies
	the package.json manages the NODE dependencies
sudo npm dev
<enter>

**Comment by petiibhuzah** [comment]
@phuclh try to check the installation path of node.js in Environment variables

**Comment by 977developer** [comment]
In package.json, **npm run dev** is directly trying to run **'cross-env + command'**

If you install cross-env globally, it will fix the problem.

`sudo npm i -g cross-env`

It is that simple.

**Comment by ruchern** [comment]
@977developer If you are on macOS or Linux, just remove `cross-env` from the `scripts` in `package.json`

**Comment by progietheus** [comment]
@977developer Thank you, this is the answer!

**Comment by flik** [comment]
here is a complete solution:[ http://rapidsol.blogspot.com/2018/04/laravel-5-cross-env-is-not-recognized.html]( http://rapidsol.blogspot.com/2018/04/laravel-5-cross-env-is-not-recognized.html)

**Comment by waiyanhein** [comment]
@flik That is the best solution. (y)

**Comment by ibanks** [comment]
@977developer This did not work and made the error appear twice.

**Comment by tanvir93** [comment]
I deleted node_modules directory completely and then run `npm install`. It works for me. Thanks

**Comment by cbj4074** [comment]
For those who are forced to bounce-around between environments (e.g., developing on Windows with Vagrant and a mounted filesystem but deploying to GNU/Linux), this issue can arise if you `npm install --no-bin-links`, which is sometimes necessary to resolve symbolic linking issues on Windows when using a mounted filesystem within a development VM.

Using the `--no-bin-links` switch effectively causes the `cross-env` binary location to change from just just `cross-env` (`node_modules/.bin/cross-env`, technically) to `node_modules/cross-env/dist/bin/cross-env.js`, in which case it is necessary to specify the full path, explicitly, in `package.json`, [as described in  a previous comment](https://github.com/JeffreyWay/laravel-mix/issues/478#issuecomment-284191242).

**Comment by najathi** [comment]
> @phuclh
> 
> `package.json ` paste this
> 
> ```json
> {
>   "private": true,
>   "scripts": {
>     "dev": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "watch-poll": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
>   },
>   "devDependencies": {
>     "axios": "^0.15.3",
>     "bootstrap-sass": "^3.3.7",
>     "cross-env": "^3.2.3",
>     "jquery": "^3.1.1",
>     "laravel-mix": "^0.8.1",
>     "lodash": "^4.17.4",
>     "vue": "^2.1.10"
>   }
> }
> ```
> 
> * `npm install --save-dev cross-env`
> * `npm install`
> 
> Now
> npm run dev
> npm run watch

It works. Thanks.

**Comment by NicolaeCasir** [comment]
For the latest `"laravel-mix": "^5.0.0",` I had to change from `dist` to `src` cause there is no dist in `cross-env`. So my scripts are:
```
"scripts": {
    "dev": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
```

**Comment by christian-manrique** [comment]
Thank you my friend you save my day @dwoodard

**Comment by florencebib** [comment]
>     "dev": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "watch": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "watch-poll": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "hot": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "production": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"

Thanks, I solved my problem by following your advice. This works. Just for sharing, after that I am still facing another error: "Cannot read property 'js' of undefined" then I have to do the followint steps then only it is fixed: 

Simply remove the braces surrounding the mix on your first line:
const mix = require('laravel-mix');

Reference: https://stackoverflow.com/questions/56891915/laravel-typeerror-cannot-read-property-js-of-undefined

**Comment by danielleplatt2020** [comment]
> For the latest `"laravel-mix": "^5.0.0",` I had to change from `dist` to `src` cause there is no dist in `cross-env`. So my scripts are:
> 
> ```
> "scripts": {
>     "dev": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "watch": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "watch-poll": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "hot": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "production": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
>   },
> ```

I have tried doing this but I am getting the error:

`<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa295e0 node::Abort() [node]
 2: 0x9782df node::FatalError(char const*, char const*) [node]
 3: 0xb99c2e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb99fa7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd3a3b5  [node]
 6: 0xd3ad5b v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd48b52 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xd499a5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd4c36c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xd1ba0b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
11: 0x104bdaf v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x13a5a99  [node]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1`

Can anybody help please?

**Comment by recaic** [comment]
> 
> 
> @phuclh
> 
> `package.json ` paste this
> 
> ```json
> {
>   "private": true,
>   "scripts": {
>     "dev": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "watch-poll": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
>   },
>   "devDependencies": {
>     "axios": "^0.15.3",
>     "bootstrap-sass": "^3.3.7",
>     "cross-env": "^3.2.3",
>     "jquery": "^3.1.1",
>     "laravel-mix": "^0.8.1",
>     "lodash": "^4.17.4",
>     "vue": "^2.1.10"
>   }
> }
> ```
> 
>     * `npm install --save-dev cross-env`
> 
>     * `npm install`
> 
> 
> Now
> npm run dev
> npm run watch

Thanks. It's working.

**Comment by karcshub** [comment]
Holy smoke!!, i have been battling with this for almost a week but this solution has worked for me.

**Comment by omarfaruk542** [comment]
"scripts": {
        "dev": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch-poll": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "hot": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },

**Comment by omarfaruk542** [comment]
"scripts": {
        "dev": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch-poll": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "hot": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },

**Comment by ice-bou** [comment]
npm run dev       

> PACKAGE_NAME@1.0.0 dev
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module 'D:\purpose-application-ui-kit-v1.0.0-6\node_modules\cross-env\dist\bin\cross-env.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)       
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.9.0
PS D:\purpose-application-ui-kit-v1.0.0-6>

**Comment by ice-bou** [comment]
i tried all the tips it not works

**Comment by raihan71** [comment]
if you guys still face the same issue, try using the latest version and read the documentation code changes
