### ISSUE TITLE
Error of require a vue component module with variable

### ISSUE THREAD

**Issue by lichnow** [JeffreyWay/laravel-mix#481]
require a path `'./template/default/views/' + $view` work fine
```
view: function($view) {
		let $template = 'default';
		return require('./template/default/views/' + $view);
	}
```

require a path with $template be variable `./template/' + $template + '/views/' + $view` webpack build fail

```
view: function($view) {
		let $template = 'default';
		return require('./template/' + $template + '/views/' + $view);
	}
```

require a path with full path be variable throw a exception
`app.js:12 Uncaught Error: Cannot find module "."`
```
module.exports = {
	view: function($view) {
		let $template = './template/default/views/';
		return require($template + $view);
	}
};
```
please tell me what it happen...

**Comment by JeffreyWay** [comment]
I don't know, but this wouldn't be a Mix issue. Without seeing the issue notes that we ask you to fill out, it's too hard to say.

**Comment by JzKUO** [comment]
I have the same problem!
