### ISSUE TITLE
Unable to compile Sass on Windows

### ISSUE THREAD

**Issue by rohan-krishna** [JeffreyWay/laravel-mix#486]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`): 7.5.0 
- NPM Version (`npm -v`): 4.1.2
- OS: Windows 10

### Description:

Hi,

I'm trying to compile sass on windows with the fresh install of Laravel 5.4. I get the following error every single time.

```
 error  in D:/xampp/htdocs/nestcare/resources/assets/sass/app.scss

Module parse failed: D:\xampp\htdocs\nestcare\resources\assets\sass\app.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .input {
|
| }

 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
```
Currently the app.scss file only has ** .input {} ** class. Even with this, the compiler keeps throwing errors.

**Comment by JeffreyWay** [comment]
Hmm, I can't reproduce this on Windows. Have you modified your webpack.mix.js file at all?

**Comment by cretueusebiu** [comment]
@JeffreyWay Same problem here. Managed to fix it by replacing `this.src.path` with `this.src.file` in the [Preprocessor.js](https://github.com/JeffreyWay/laravel-mix/blob/master/src/Preprocessors/Preprocessor.js#L60) class.

**Comment by rohan-krishna** [comment]
@cretueusebiu Can't seem to find the file in my build. Can anyone come up with a fix?

**Comment by cretueusebiu** [comment]
Make sure you use the latest version of Mix.

**Comment by rohan-krishna** [comment]
Hurray! ... @cretueusebiu  Thanks a lot. It's working now.
