### ISSUE TITLE
Icheck not getting all skin images

### ISSUE THREAD

**Issue by ramakrishnamundru** [JeffreyWay/laravel-mix#487]
- Laravel Mix Version:0.8.1
- Node Version (`7.6.0`): 
- NPM Version (`4.1.2`): 
- OS: Linux-mint

### Description:
When using Icheck all.css file only square skin images are being loaded, and remaining skins are using the square skin.

### Steps To Reproduce:
```
git clone https://github.com/ramakrishnamundru/icheck_issue.git
cd icheck_issue/
npm install
npm run hot
```

if you run `npm run dev` you can see only square skin images are loaded in the images folder,

Any way to get the required images with folder structure or different names?

**Comment by JeffreyWay** [comment]
I assume it's because you're lazy loading that icheck dependency. Maybe just reference that file in your HTML as you traditionally would.

**Comment by ramakrishnamundru** [comment]
I think this is happening because of output path flattening(like in `mix.copy()`).
But in `mix.copy()` we can pass false to get the directory structure, but in my case I am using `mix.js()` to compile vue components, and I can't see anything in the JavaScript documentation to stop output flattening.
After referencing Icheck through the link and script tags in index.html, It is saying
`Cannot read property 'fn' of undefined` in console.
I tried changing provide plugin to
```
 jQuery: 'jquery',
 $: 'jquery',
 jquery: 'jquery',
 'window.jQuery': 'jquery',
 'window.jquery': 'jquery',
 'window.$': 'jquery'
```
But still it is of no use.
Is there a way to stop output path flattening when compiling vue files through `mix.js()`
