### ISSUE TITLE
postCss plugins not working in webpack mix

### ISSUE THREAD

**Issue by alihaddadkar** [JeffreyWay/laravel-mix#491]
Hello.
I'm use this code for add postcss plugins, And runs without problems, But in the output file does not happen.

```
mix.sass('resources/assets/sass/app.scss', 'public/css')
   .options({
        postCss: [
           require('autoprefixer')(),
           require('cssnano')(),
           require('css-mqpacker')()
        ]
   });
```

**Comment by JeffreyWay** [comment]
You deleted the issue template, so I have to ask what version of Mix you have installed?

**Comment by alihaddadkar** [comment]
"laravel-mix": "^0.7.2"

**Comment by alihaddadkar** [comment]
I update to the latest version (version 0.8.8). The problem was resolved.
Thanks
