### ISSUE TITLE
Running 'hot' with absolute image paths

### ISSUE THREAD

**Issue by Braunson** [JeffreyWay/laravel-mix#492]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`): 7.5.0
- NPM Version (`npm -v`): 4.3.0
- OS: Windows 10

### Description:
Running `npm run hot` and I have an absolute image path (`/images/codewall.jpeg`) in my styles but hot isn't serving them at all. Hot styles work but seems to not include images with them

http://localhost:8080/images/codewall.jpeg returns `Cannot GET /images/codewall.jpeg`

### Steps To Reproduce:
Add a background to a div, run `npm run hot` try viewing the page.

**Comment by JeffreyWay** [comment]
This was fixed in 0.10.0.
