### ISSUE TITLE
Watcher doesn't recompile correctly

### ISSUE THREAD

**Issue by JeramyNS** [JeffreyWay/laravel-mix#493]
- Laravel Mix Version: 0.6.3
- Node Version: 7.3.0
- NPM Version: 4.2.0 
- Yarn Version: 0.20.3
- OS: Fedora 25 & Centos 7

### Description:
It seems that certain types of changes to vue files aren't re-compiled. 
For example, if I add a new method or add a console.log I'll see webpack recompile and show a success message but the changes don't get applied. 
If I cancel npm run dev, then re-run "npm run dev" then the main.js file won't be re-compiled as it is assumed that it's already correct according to the manifest. 
I have to add a new line or some other edit to the file and re-run it; making sure it's not running already

This happens on both the local fedora system and also in the remote server centos.

### Steps To Reproduce:
1. Run "yarn run dev" (or npm).
2. Edit vue function and add console.log(anything); or a new method
3. Reload page and try function. No console message.

Same thing happens when trying to call newly added methods etc.

I don't mind the whole re-running part, but having to edit the file by adding a space just so it recognises the change is annoying as hell.

I would have thought that this sort of thing would already have an issue created if others where experiencing it, unless I've missed it in my search.

**Comment by JeffreyWay** [comment]
I can't reproduce this. 

If it picks on your change and gives you a recompile notification, everything should be working properly. At that point, Webpack takes over completely. Are you sure it's not just an issue where you have to do a hard refresh in the browser to see the change?

**Comment by JeramyNS** [comment]
Yeah definitely not a hard refresh issue. I'm noticing that sometimes it won't even list the main.js in the list of re-compiled files, perhaps its related to that.
Anyway, I'll close this for now until I have time to try and reproduce elsewhere.

**Comment by JeramyNS** [comment]
Figured it out.
My problem was caused by failing to chain my mix commands one after another.
Didn't realise it was async, so when it was combining my JS it was using the previously compiled js file rather than the latest one.

Sorry for wasting your time dude.
