### ISSUE TITLE
Uncaught ReferenceError: Invalid left-hand side expression in postfix operation

### ISSUE THREAD

**Issue by Daniesy** [JeffreyWay/laravel-mix#494]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`): v6.9.1
- NPM Version (`npm -v`): 3.10.8
- OS: Macos Sierra 10.12.3

### Description:

Whenever i run `npm run production` i get this error on all my .js files
`Uncaught ReferenceError: Invalid left-hand side expression in postfix operation`
If i run only `npm run dev` everything works ok. I traced the problem to the uglify plugin. If i comment `new webpack.optimize.UglifyJsPlugin(Mix.options.uglify)`, everything works as expected.

### Steps To Reproduce:

Just run `npm run production`. 

### Webpack.mix
    
    const { mix } = require('laravel-mix');
    mix.sass('resources/assets/sass/app.scss', 'public/css')
          .js('resources/assets/js/auth.js', 'public/js')

### 

### Auth.js
    require('./bootstrap');

    var app = new Vue({
      el: '#app',
      data: {
        message: 'Hello Vue!'
      }
    })

**Comment by seansch** [comment]
Same issue. Appears to come from compressing jQuery with UglifyJsPlugin. If you set `compress: false` in '/node_modules/laravel-mix/src/Options.js' in the uglify section or commenting out `window.$ = window.jQuery = require('jquery');` in bootstrap.js the error goes away.  (Obviously not a solution)

- Laravel Mix Version: 0.8.8
- Node Version (node -v): v7.6.0
- NPM Version (npm -v): 4.1.2
- OS: Ubuntu 16.10

**Comment by Daniesy** [comment]
Hey @seansch thanks for the reply. I was watching the Uglify issue as well. I'll test again tomorrow at work and close this issue if it gets fixed.

**Comment by Daniesy** [comment]
It works ok with Uglify(v2.8.2). I'll close this now.
