### ISSUE TITLE
Using another webpack loader not included with mix? (string-replace-loader)

### ISSUE THREAD

**Issue by adrianocr** [JeffreyWay/laravel-mix#496]
- Laravel Mix Version: 0.8.8
- Node Version: 7.1.0
- NPM Version: 3.10.9 (Yarn v0.20.3)
- OS: macOS 10.12.3

### Description:
How do I go about using a third-party loader with mix? Let's I want to replace all instances of "string" with "replaced" in my outputted CSS file (compiled from sass). How do I add the string-replace-loader module to my webpack.mix.js file in a way that will allow me to do that? 

Loader in question: https://www.npmjs.com/package/string-replace-loader

**Comment by JeffreyWay** [comment]
Something like this:

```js
mix.webpackConfig({
  module: {
    loaders: [
      {
        test: /fileInWhichJQueryIsUndefined\.js$/,
        loader: 'string-replace',
        query: {
          search: 'jQuery',
          replace: 'window.$'
        }
      }
    ]
  }
});
```

**Comment by VasiliDarozhkin** [comment]
I am using 
`mix.webpackConfig({
	module: {
		loaders: [
			{
				test: /package\.json$/,
				loader: 'string-replace',
				query: {
					search: 'a',
					replace: 'b',
					flags: 'g'
				}
			}
		]
	}
});`

But nothing is changed in `package.json` when I execute `npm run prod`, am I missing something?
How to debug this? 

Thank you?
