### ISSUE TITLE
React with browsersync autocompile and refresh problem

### ISSUE THREAD

**Issue by filipveschool** [JeffreyWay/laravel-mix#497]
Hi,

Is there a possibility to auto refresh the browser page with browsersync when I make changes to React .jsx files and autocompile and refresh them?

**Comment by JeffreyWay** [comment]
Are you using `mix.react()` to compile your JavaScript? 

Browsersync should automatically pick on your changes.

**Comment by filipveschool** [comment]
I am using mix.react() now yeah, and suddenly everything works for this.
