### ISSUE TITLE
Issue about webpackconfig in webpack.

### ISSUE THREAD

**Issue by filipveschool** [JeffreyWay/laravel-mix#499]
Hi,

How can we update the webpack config by using mix.webpackconfig()_ in the file webpack.mix.js?

I want to update this settings that I added, because otherwise React wouldn't compile with me?

It goes about the **JSX babel-loader query part** that I added myself !!

I would wanna move this to the mix file instead of the config file if possible? I hope my question and problem is clear?

``
module.exports.module = {
    rules: [
        {
            test   : /\.vue$/,
            loader : 'vue-loader',
            options: {
                loaders: Mix.options.extractVueStyles ? {
                    js    : 'babel-loader' + Mix.babelConfig(),
                    scss  : vueExtractTextPlugin.extract({
                        use     : 'css-loader!sass-loader',
                        fallback: 'vue-style-loader',
                    }),
                    sass  : vueExtractTextPlugin.extract({
                        use     : 'css-loader!sass-loader?indentedSyntax',
                        fallback: 'vue-style-loader',
                    }),
                    stylus: vueExtractTextPlugin.extract({
                        use     : 'css-loader!stylus-loader?paths[]=node_modules',
                        fallback: 'vue-style-loader',
                    }),
                    css   : vueExtractTextPlugin.extract({
                        use     : 'css-loader',
                        fallback: 'vue-style-loader',
                    }),
                } : {
                    js    : 'babel-loader' + Mix.babelConfig(),
                    scss  : 'vue-style-loader!css-loader!sass-loader',
                    sass  : 'vue-style-loader!css-loader!sass-loader?indentedSyntax',
                    stylus: 'vue-style-loader!css-loader!stylus-loader?paths[]=node_modules',
                },
                postcss: Mix.options.postCss,
            },
        },

           {
            test   : /\.jsx?$/,
            exclude: /(node_modules|bower_components)/,
            loader : 'babel-loader' + Mix.babelConfig(),
            query  : {
                babelrc: false,
                presets: [
                    'es2015',
                    'react',
                    'stage-1',
                ],
            },
        },

        {
            test   : /\.css$/,
            loaders: ['style-loader', 'css-loader'],
        },
        {
            test   : /\.s[ac]ss$/,
            include: /node_modules/,
            loaders: ['style-loader', 'css-loader', 'sass-loader'],
        },

        {
            test   : /\.html$/,
            loaders: ['html-loader'],
        },

        {
            test   : /\.(png|jpe?g|gif)$/,
            loader : 'file-loader',
            options: {
                name      : 'images/[name].[ext]?[hash]',
                publicPath: Mix.resourceRoot,
            },
        },

        {
            test   : /\.(woff2?|ttf|eot|svg|otf)$/,
            loader : 'file-loader',
            options: {
                name      : 'fonts/[name].[ext]?[hash]',
                publicPath: Mix.resourceRoot,
            },
        },

        {
            test   : /\.(cur|ani)$/,
            loader : 'file-loader',
            options: {
                name      : '[name].[ext]?[hash]',
                publicPath: Mix.resourceRoot,
            },
        },
    ],
};
``

**Comment by JeffreyWay** [comment]
Can you fix your code highlighting, and fill out the issue template that we provide? I'd also need to see your webpack.mix.js file. 

So can't help right now.
