### ISSUE TITLE
path is not defined when using mix.webpackConfig

### ISSUE THREAD

**Issue by Faisal0sal** [JeffreyWay/laravel-mix#503]
I have :
1. Updated Laravel Mix to the latest version.
2. Nuke my dependencies, and reinstall from scratch: `rm -rf node_modules && npm install`.
3. Checked my `package.json` file, and ensure that there are no old Laravel Elixir dependencies that might be interfering with Mix.

- Laravel Mix Version: 0.8.8
- Node Version (7.5.0): 
- NPM Version (4.1.2): 
- OS: 

### Description:
Trying to merge web configuration using the example: 
```
mix.webpackConfig({
    resolve: {
        modules: [
            path.resolve(__dirname, 'vendor/laravel/spark/resources/assets/js')
        ]
    }
});
```

Running `npm run dev` will get me an error of:
```
            path.resolve(__dirname, 'vendor/laravel/spark/resources/assets/js')
            ^

ReferenceError: path is not defined
```

**Comment by JeffreyWay** [comment]
Add 

```js
var path = require('path');
```

to the top of your `webpack.mix.js` file.
