### ISSUE TITLE
mix.scripts no error if file is not found

### ISSUE THREAD

**Issue by Max-Hutschenreiter** [JeffreyWay/laravel-mix#508]
"laravel-mix": "^0.8.1",
node v7.2.1
npm 3.10.10

If a file specified in .script is not existing compile is running normal. 
I expected an error like it is happening in .js.

By the way thanks for this great tool!

Best Max

**Comment by JeffreyWay** [comment]
That's because you could provide a regular expression, so we can't easily check if the file exists (I don't think). So it just skips over it, if it can't read the file.

**Comment by rhyudek1** [comment]
Hi, I have the same trouble..
mix.styles([
    'node_modules/html5-boilerplate/dist/css/main.css',
    'node_modules/datatables/media/css/dataTables.bootstrap.css'
], 'public/css/vendor.css'));

**results**
`/css/vendor.css  58.5 kB          [emitted]`

**results If I change the filenames**
`/css/vendor.css  0 kB          [emitted]`

But no errors or warnings.

**Comment by fbingha** [comment]
I need a solution for this as well. I don't want to resort to having to run another script to verify the filenames in the manifest.
