### ISSUE TITLE
A bunch of issues I've encountered in Laravel Mix

### ISSUE THREAD

**Issue by xperator** [JeffreyWay/laravel-mix#510]
- Laravel Mix Version: 0.8.1
- Node Version (`node -v`): 6.9.1
- NPM Version (`npm -v`): 4.4.0
- OS: macOS Sierra (10.12.3)

### Description:
I have been playing around with the new Laravel 5.4 for the past few days and honestly I'm not liking Laravel Mix compared to Elixir  because I've encountered many weird issues which I'm gonna list them here. I got these issues while making a very simple app ( a login page and a dashboard ).

First of all, about the javascript compilation:

1. Whenever there is an error within my JS file, the console on my browser doesn't output any errors. The page either just comes up blank, or my javascript functions won't work at all. I have no idea where and what I did wrong. I have to go through my entire JS files and change this and that in order to find out the line that's causing the problem.
2. I feel like the compilation has a fraction of failure. like 30% of the time it fails for no reason and very randomly. For example, just a few minutes ago, I commented out 2 lines, saved the file. the page was working fine. Then I went back to my editor, uncommented those 2 lines, saved the file and the page stopped working! I knew the problem wasn't my code because the exact same code was running just fine before that. So I tried to add/remove a bunch of linebreaks, save the file and hope the webpack compiles the file properly. It took like 5-6 saves for it to recompile successfully.
3. Everytime I change something in my JS file and save it, the webpack also updates my css files even though I haven't changed them. Why does it recompiles my css files when the js file are the one getting modified.

The stylus/css compilation:

4. Just 1 tiny issue with the stylus compilation. And that is, It doesn't pick up the new files. For example I have this code in my `app.styl`:
```
@import '/vendor/colors'
@import '/vendor/base'
@import '/vendor/normalize'

@import '/pages/*'
```
This works fine in Elixir but with Laravel Mix whenever I create a new file in the `/pages` directory, the webpack doesn't do anything. I use `npm run watch` my guess is that the webpack doesn't watch over that directory since it's not expecting it in the first place. 

This is my current `webpack.mix.js`:
```
const { mix } = require('laravel-mix');

mix.js('resources/assets/js/app.js', 'public/js')
    .disableNotifications();

mix.stylus('resources/assets/stylus/app.styl', 'public/css', {
    use: [
        require('rupture')()
    ]
    }).disableNotifications();

mix.styles('resources/assets/stylus/fonts.css', 'public/css/fonts.css').disableNotifications();

mix.browserSync({
    proxy: 'test.app',
    ghostMode: false,
});
```

**Comment by JeffreyWay** [comment]
To respond to your notes:

1. Every time I make a JS syntax error, the console shows me exactly where, so not sure what you're referring to. Can you give me a reproducible example? https://www.dropbox.com/s/t6t2frd3ld9su95/Screenshot%202017-03-03%2011.21.25.png?dl=0
2. You'd be the first to report that issue. The compile is going to be the same every time, so I'd again need a reproducible example.
3. It depends upon how your JavaScript is constructed. Webpack extracts all relevant CSS when it compiles. 
4. Yeah if you add more partials, you need to refresh Webpack. Just close out `npm run watch` and start it up again, so it can see the new files. I can research a way to automate this.
