### ISSUE TITLE
`setPublicPath()` affecting different methods inconsistently.

### ISSUE THREAD

**Issue by mikebronner** [JeffreyWay/laravel-mix#511]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`): 7.4.0
- NPM Version (`npm -v`): 4.0.5
- OS: macOS 10.12.3

### Description:
It appears that using mix.setPublicPath('public') is applied inconsistently across .js() and .sass().

### Steps To Reproduce:
```js
mix
    .setPublicPath('public/')
    .js('resources/assets/js/app.js', 'public')
    .sass('resources/assets/scss/app.scss', 'public')
    .version()
   ;
```

Results in:
```
- public
-- public
--- app.xxxx.js
-- app.xxxx.css
-- mix-manifest.json 
```

I don't know which way would be the intended way. I would maybe expect the second parameter on the js() and sass() methods to become optional if setPublicPath is set? Or have them completely ignore it, and apply it only to version() method?

Temporary workaround in webpack.mix.js:

```js
mix
    .setPublicPath('public/')
    .js('resources/assets/js/app.js', '')
    .sass('resources/assets/scss/app.scss', 'public')
    .version()
    ;
```

Thanks! :)

**Comment by devcircus** [comment]
Curious if you figured this out.

I just tried to reproduce, however it works as advertised. I copied your above code into a fresh install of Laravel 5.4.15 with Laravel Mix 0.8.8
My node version is 6.9.4 and npm is 4.1.2

Both app.js and app.css are compiled into public as expected.

Do you possibly have something in your webpack.config.js that is interfering?

**Comment by mikebronner** [comment]
@devcircus Not sure. I'm using it in package development, but I wouldn't think it would inherit settings from the parent project? I have just reproduced this issue in the parent project, as well.

**Comment by devcircus** [comment]
Stumped. Been trying to reproduce but if I setPublicPath to "public" then add "public" as the second parameter to .js and .sass, then it's uses public\public for both app.js and app.scss as I would expect.....

**Comment by JeffreyWay** [comment]
Weirdly enough, it's because you have a slash at the end of `mix.setPublicPath()`. If you remove it, the CSS and JS files are placed in the public directory as expected. 

I've pushed a commit that removes the slash. Thx.

**Comment by mikebronner** [comment]
Yikes, forgot to test without the slash. Thanks for trimming it out for us :)
