### ISSUE TITLE
import css through app.scss

### ISSUE THREAD

**Issue by amin101** [JeffreyWay/laravel-mix#517]
I'm trying to import css file through `app.scss`
`@import "node_modules/bootstrap-rtl/dist/css/bootstrap-rtl.min.css";`

after running `npm run dev` , the css file is not imported but the above line is printed in the output css file.
- Laravel Mix Version: 0.8.8
- Node Version : v6.10.0
- NPM Version : 4.3.0
- OS: win10

similar issue is posted[ here](https://github.com/JeffreyWay/laravel-mix/issues/130)

**Comment by JeffreyWay** [comment]
Try changing it to:

```css
@import "~bootstrap-rtl/dist/css/bootstrap-rtl.min.css";
```

If it's still not working, we need to see your webpack.mix.js file.

**Comment by amin101** [comment]
not working!
webpack file: 
`const {mix} = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .options({
        processCssUrls: false
    })
    .extract(['jquery','vue','axios','bootstrap-sass','lodash'])
    .browserSync('sherkat.dev')
    .disableNotifications();
    // .version();

`

**Comment by JeffreyWay** [comment]
You set `processCssUrls` to false, which means Mix will ignore those.
