### ISSUE TITLE
Mix.json in production

### ISSUE THREAD

**Issue by strebl** [JeffreyWay/laravel-mix#52]
Hi Jeffrey

I played a little bit with laravel-mix and I really love it so far.
But how would you use it in production?
I normally compiled everything locally, so I don't have to compile the scripts on deployment.
That worked really great with Laravel Elixir.
Now I need access to the `Mix.json` if I use `.version()`or `.extract()`.
Sure I can move it to another folder with `.setCachePath()` and add it to git.
But the file is in my case over 6MB.

Therefore I tried to lower the file size. I saw that even the source code is in that file. Changing the the stats property in the `webpack.config.js` just changes the console output on compile, but not the `Mix.json` content.

What's your opinion?
Is it possible to optimize the `Mix.json` file?
Is the source code in that file necessary? If yes, also for production?

Just ask if I didn't provide enough information! 😊

**Comment by strebl** [comment]
To clarify why I need the `Mix.json` file: I'm using your `mix()` helper which needs that file.

```php
function mix($path, $json = false, $shouldHotReload = false)
{
    if (! $json) static $json;
    if (! $shouldHotReload) static $shouldHotReload;

    if (! $json) {
        $manifestPath = storage_path('framework/cache/Mix.json');
        $shouldHotReload = file_exists(storage_path('framework/cache/hot'));

        if (! file_exists($manifestPath)) {
            throw new Exception(
                'The Laravel Mix manifest file does not exist. ' .
                'Please run "npm run webpack" and try again.'
            );
        }

        $json = json_decode(file_get_contents($manifestPath), true);
    }

    $path = collect($json['assetsByChunkName'])
        ->flatten()
        ->first(function ($compiledFile) use ($path, $json) {
            $compiledFile = trim(str_replace($json['hash'].'.', '', $compiledFile), '/');

            return $compiledFile === trim($path, '/');
        });

    return $shouldHotReload ? "http://localhost:8080{$path}" : url($path);
}
```

And that helper just need so few information from the `Mix.json` file.

**Comment by strebl** [comment]
Ok I changed the output by changing following line in the webpack config from:

```js
    this.plugin('done', stats => Mix.manifest.write(stats));
```

to:

```js
    function() {
        this.plugin('done', stats => {
            new Mix.File(Mix.manifest.path).write(
                JSON.stringify(stats.toJson({
                    hash: true,
                    version: false,
                    timings: false,
                    children: false,
                    errors: false,
                    modules: false,
                    source: false
                }))
            );
        });
    },
```

As you see, I just modify your `Manifest.write()` method a little bit by passing a configuration to the `toJson()` method.

**Comment by JeffreyWay** [comment]
Yeah, we need to update the manifest contents to be much smaller. I'll do that today.

**Comment by RomainLanz** [comment]
When there's multiple file with the same name (e.g. `app.css` & `app.js`) they will be in the same array of the manifest.

```json
{
  "hash": "fb1ff050eb67d5823983",
  "assetsByChunkName": {
    "vendor": "/js/vendor.fb1ff050eb67d5823983.js",
    "app": [
      "/js/app.fb1ff050eb67d5823983.js",
      "/css/app.fb1ff050eb67d5823983.css"
    ],
    "manifest": "/js/manifest.fb1ff050eb67d5823983.js"
  }
}
```

How to write a `mix()` helper to be able to differ between my two files?

```js
mix
  .setPublicPath('public')
  .js('resources/assets/js/app.js', 'public/js')
  .extract(['vue', 'axios', 'jquery'])
  .sass('resources/assets/sass/app.scss', 'public/css')
  .version()
```

**Comment by strebl** [comment]
The one I posted should work
