### ISSUE TITLE
problem with Require vue-router from bootstrap file

### ISSUE THREAD

**Issue by pixieaka** [JeffreyWay/laravel-mix#522]
Bootstrap file
----------------
![bootstrap](https://cloud.githubusercontent.com/assets/17777237/23586228/8fe3f45a-0199-11e7-962e-2678b1e85607.JPG)

App file
----------------
![app](https://cloud.githubusercontent.com/assets/17777237/23586233/a08558f8-0199-11e7-8393-cf9809916874.JPG)

Problem is
----------------
![prob](https://cloud.githubusercontent.com/assets/17777237/23586234/a7b48c34-0199-11e7-94fc-4201c0cbbcd3.JPG)

The solution add to app file this lines
-----------------
![done](https://cloud.githubusercontent.com/assets/17777237/23586429/25a9acac-019d-11e7-8d7a-965c9f4d9d95.JPG)

Dependencies
-----------------
![de](https://cloud.githubusercontent.com/assets/17777237/23586248/edfdd196-0199-11e7-84de-7af1ea3c0388.JPG)

**Comment by terrylow** [comment]
@pixieaka change `window.Vue = require('vue')`
to
`import Vue from 'vue'
window.Vue = Vue;
` instead

https://vuejs.org/v2/guide/typescript.html#Important-2-2-Change-Notice-for-TS-webpack-2-users

**Comment by pixieaka** [comment]
Thanks it work great now 👍
