### ISSUE TITLE
Laravel-Mix and File-loader plugin is not working properly.

### ISSUE THREAD

**Issue by barisbora** [JeffreyWay/laravel-mix#524]
- Laravel Mix Version: 0.8.1
- Node Version: 6.9.4
- NPM Version: 4.1.1
- OS: Windows 10

### Description:
The file-loader plugin is not working properly. Adding ">" characters to the end of the files while moving the SVG files to the "public / fonts" folder.

#### My file construction is as follows
1 - package.json
 `
...
"devDependencies": {
    "flag-icon-css": "^2.8.0",
    "jquery": "^2.2.4",
    "laravel-mix": "^0.8.1"
  }
...
`
2 - webpack.mix.js
`
...
mix.sass('resources/assets/sass/app.scss', 'public/css/app.css');
...
`
3 - app.scss
`
...
@import "~flag-icon-css/sass/flag-icon";
...
`

### Conclusion

When i "npm run dev"

Everything works perfectly. All fonts are automatically copied to the "public/fonts" folder. But the contents of the fonts svg files are changing. Adding ">" characters to the end of the SVG File

Original SVG file: [https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/tr.svg](url)
Copied SVG file: 9 th line extra ">" character added.

![export](https://cloud.githubusercontent.com/assets/10472206/23589950/bb272524-01df-11e7-8cbe-2cade8cf9d4c.png)

![svg](https://cloud.githubusercontent.com/assets/10472206/23589916/4d174906-01df-11e7-8d86-aeaf6d41b082.png)

**Comment by JeffreyWay** [comment]
I've never experienced this or heard of it before. If there is some issue, though, it would be specific to the file-loader plugin. There's nothing we can do in the Mix repo.

**Comment by edgarsdavidsons** [comment]
@barisbora did you solved this issue? I also today faced it. In my case there is extra closing </g> and </svg> tags.
