### ISSUE TITLE
Laravel npm run errors

### ISSUE THREAD

**Issue by linasslepikas** [JeffreyWay/laravel-mix#530]
- Laravel Mix Version: ^0.8.1
- Node Version (`node -v`): 7.7.1
- NPM Version (`npm -v`): 4.1.2
- OS: Mac

### Description:

Running "npm run dev" (and all the rest- dev .. etc.) gives an error:
"npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.7.1_1/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/linasslepikas/Documents/Development/20170306CiliSkunduRegistravimas/npm-debug.log"

Just pulled in latest Laravel release, dvd troubleshooting as adviced (removed node_modules etc.). NPM debug log attached. package.json attached.

Any help would be appreciated.

[Archive.zip](https://github.com/JeffreyWay/laravel-mix/files/821214/Archive.zip)

**Comment by linasslepikas** [comment]
Took, latest package.json file and it fixed my issue.

**Comment by NicolasVanhecke** [comment]
How did you fix this problem? I don't understand your 'answer'?

**Comment by ruchern** [comment]
@NicolasVanhecke `npm install laravel-mix@0.10.0`

**Comment by NicolasVanhecke** [comment]
@ruchern thanks, installed a bunch of sstuff, but didn't fix the problem. Not sure why this is an issue for me all of a sudden

**Comment by ruchern** [comment]
Did you run `npm install` before doing anything else?

**Comment by NicolasVanhecke** [comment]
@ruchern Yes I did, found the solution here: https://github.com/JeffreyWay/laravel-mix/issues/478#issuecomment-284191242
Some files were replaced in different folders.. npm uninstall laravel-mix did not do the trick for me, manually changing the file locations did.
