### ISSUE TITLE
jQuery and laravel mix

### ISSUE THREAD

**Issue by benjamindoe** [JeffreyWay/laravel-mix#539]
I'm feeling a bit confused with laravel mix and jQuery. 

Should we be separating our jQuery into different files, each with a `$(document).ready()`? Do we need the `app.js` and `bootstrap.js` if we're just simply using jQuery for UX stuff?

**Comment by JeffreyWay** [comment]
This is probably a better question for a forum. 

If you're only doing some basic jQuery work, you might do `mix.scripts()` to simply concatenate jQuery and the related files you need.
