### ISSUE TITLE
wrong output path for mix.js

### ISSUE THREAD

**Issue by aocneanu** [JeffreyWay/laravel-mix#54]
Hello,

Awwesome work!!! Finally I can use watch and hmr, it's magic!

But I have one problem with the output path for mix.js()

mix.js('resources/assets/js/pages/dashboard/index.js', './public/js/dashboard/')

results in an output of /js/index.js  3.01 kB       7  [emitted]         index.

What am I doing wrong?

**Comment by TNovalis** [comment]
Try removing the `./` from `'./public/js/dashboard/'`

**Comment by ramonsenadev** [comment]
Basically the same problem here...

**The dist folder...**
```
mix.js('resources/js/app.js', '../publicpublic_html/js')
  .sass('resources/sass/app.scss', '../public_html/css')
  .version();
```


It will generate the same thing:
```
public_html/js/app.js
public_html/css/app.css
```

**Comment by aocneanu** [comment]
> Try removing the ./ and the trailing slash from './public/js/dashboard/'

Tried that too with no luck. Same output.

**Comment by TNovalis** [comment]
Are you on the latest version? I have just tried yours and it seems to have given the desired result.

**Comment by aocneanu** [comment]
Yes I'm on the latest version, but it seems that it's another problem.

What I try to do is:

> mix.js('resources/assets/js/pages/generic.js', 'public/js')
>       js('resources/assets/js/pages/dashboard/index.js', 'public/js/dashboard')

In this situation the output directory will be public/js for both files.

When I swap the order the output is public/js/dashboard for both files. It seems that mix is using the first output declaration for all the following files.

**Comment by JeffreyWay** [comment]
Yeah, right now all of your JS will output to the same base output directory. It's a known issue. if we can fix that, it'll be part of the next release.
