### ISSUE TITLE
mix.copy(from,to,false) incorrectly replicates the source directory structure

### ISSUE THREAD

**Issue by mattyglover** [JeffreyWay/laravel-mix#540]
- Laravel Mix Version: 0.8.1
- Node Version (`node -v`): 6.8.1 
- NPM Version (`npm -v`):  3.10.8
- OS: osx 10.11.6

### Description:

This could very well be user error here, but: mix.copy(from,to,flatten) using glob params with flatten=false incorrectly replicates the source directory structure instead of making it relative to the path as taken from the start of the pattern match. eg.

mix.copy('resources/assets/s11/images/**/*', 'public/assets/images', false);

will create:

public/assets/images/resource/assets/s11/images/directory1/image1.xxx instead of
public/assets/images/directory1/image1.xxx

**Comment by JeffreyWay** [comment]
Do this instead:

```
mix.copy('resources/assets/s11/images', 'public/assets/images', false);
```
