### ISSUE TITLE
Can't copy exact folder structure with mix.copy()

### ISSUE THREAD

**Issue by ilijabradas** [JeffreyWay/laravel-mix#541]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`): 6.10.0
- NPM Version (`npm -v`): 3.10.10
- OS: Windows 10 Pro 1607 

### Description:
I am having a problem using mix.copy(). It won't copy exact folder structure when using glob patterns.
e.g if i have have this kind of folder structure in src/assets/css

│   animate.css
│
└───select2
         select2.css

and if this command was applied `mix.copy('src/assets/css/**/*', 'dist/css/plugins');`
i get this kind of structure without select2 folder anywhere in it:

 animate.css
    select2.css

**Comment by JeffreyWay** [comment]
Pass `false` as the third argument to `mix.copy()`.
