### ISSUE TITLE
TypeError: mix.sass(...).options is not a function

### ISSUE THREAD

**Issue by DrewNeon** [JeffreyWay/laravel-mix#542]
- Laravel Mix Version: 5.4.15
- Node Version (`node -v`): 7.6.0
- NPM Version (`npm -v`): 4.1.2
- OS: macOS Sierra 10.12.3

### Description:
I followed the instructions of the official document of Laravel 5.4 about MIx. It did work without customizing the original webpack.mix.js. However, after I included some web fonts into my SASS, there were errors copying the fonts by Mix. So I copied the `processCssUrls: false` code directly from the document to my webpack.mix.js, now I got TypeError: mix.sass(...).options is not a function.

I tried several times by starting with a fresh Laravel project, and ended up at this error all the time.

### Steps To Reproduce:
1. `laravel new laravel_proj`
2. `cd laravel_proj`
3. `npm install`
4. open webpack.mix.js
5. revise to 
```
mix.sass('resources/assets/app/app.scss', 'public/css')
   .options({
      processCssUrls: false
   });
```
6. `npm run dev`
7. error message
```
TypeError: mix.sass(...).options is not a function
    at Object.<anonymous>
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Mix.initialize 
    at Object.<anonymous> 
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
```

**Comment by gudorian** [comment]
Update laravel-mix to 0.8.8 solved this problem for me. 

Set

`"laravel-mix": "^0.5.0",`

to

`"laravel-mix": "^0.8.8"`

in package.json and run `npm i` .

**Comment by DrewNeon** [comment]
@gudorian Thanks for help! I did what you suggested, the `.options` issued was solved, but another weirder one showed up.

My webpack.mix.js is like this
```
mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/app/app.scss', 'public/css')
    .options({
      processCssUrls: false
    });
```

And I got this error message now
```
This dependency was not found:

* /.../laravel_proj/resources/assets/app/app.scss in multi ./resources/assets/js/app.js ./resources/assets/app/app.scss

To install it, you can run: npm install --save /.../laravel_proj/resources/assets/app/app.scss
```

I do have the original `app.scss` in the correct path and of course the `npm install --save` worn't work.

**Comment by DrewNeon** [comment]
@gudorian Thanks for your help! It did fixed the `.options` error. 

And I added `mix.sourceMaps();` to my webpack.mix.js, but no source map mixed. However, if I delete the `.options` part, source map is fine. What shall I do next?

**Comment by ankurk91** [comment]
@DrewNeon 
Laravel mix generates ```#inline-source-map```, it means source map can be found in your output css file itself.
Sourcemaps are disabled for production.

**Comment by DrewNeon** [comment]
@ankurk91 Thanks for your reply!

I know the source map is included in the generated .css files, but merely from the file size, you can tell the souce map is not generated correctly when `.options()` is applied along with `souceMaps()` .

File size without `processCssUrl: false`
```
            Asset      Size  Chunks                    Chunk Names
     /css/app.css   1.61 MB       0  [emitted]  [big]  /js/app
```

File size with `processCssUrl: false`
```
            Asset      Size  Chunks                    Chunk Names
     /css/app.css    146 kB       0  [emitted]         /js/app
```

What I'm reporting is that with both `souceMaps()` and `processCssUrl: false` applied, the css sourcemap does not work properly.

**Comment by ankurk91** [comment]
@DrewNeon
I was able to re-produce the sourcemap issue when ```processCssUrl: false```, can you file a new issue.

**Comment by JeffreyWay** [comment]
@DrewNeon This will be fixed in the next tagged release of Mix.

**Comment by henriquecode** [comment]
@gudorian Thanks!!
