### ISSUE TITLE
laravel-mix not working in windows 10

### ISSUE THREAD

**Issue by armesas** [JeffreyWay/laravel-mix#543]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`):  7.7.1
- NPM Version (`npm -v`): 4.3
- OS: Windows 10, using vagrant and cmder

Description:

I get errors whenever i run npm run dev.  I've run through all of the fixes in other threads to no avail.

**When running "sudo npm run dev":**

npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.7.1
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/.npm/_logs/2017-03-08T13_41_50_996Z-debug.log

**When running "sudo node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js":**

internal/child_process.js:319
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1029:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at Object.exports.spawn (child_process.js:386:9)
    at spawn (/var/www/node_modules/cross-spawn/index.js:17:18)
    at crossEnv (/var/www/node_modules/cross-env/dist/index.js:30:38)
    at Object.<anonymous> (/var/www/node_modules/cross-env/dist/bin/cross-env.js:10:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Here is a copy/paste from my error log from the first command:**

0 info it worked if it ends with ok                                                                            
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]                                    
2 info using npm@4.3.0                                                                                         
3 info using node@v7.7.1                                                                                       
4 verbose run-script [ 'predev', 'dev', 'postdev' ]                                                            
5 info lifecycle @~predev: @                                                                                   
6 silly lifecycle @~predev: no script for predev, continuing                                                   
7 info lifecycle @~dev: @                                                                                      
8 verbose lifecycle @~dev: unsafe-perm in lifecycle true                                                       
9 verbose lifecycle @~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/var/www/node_modules/.bin:/u
sr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                                                     
10 verbose lifecycle @~dev: CWD: /var/www                                                                      
11 silly lifecycle @~dev: Args: [ '-c',                                                                        
11 silly lifecycle   'node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpa
ck/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js' ]       
12 silly lifecycle @~dev: Returned: code: 1  signal: null                                                      
13 info lifecycle @~dev: Failed to exec dev script                                                             
14 verbose stack Error: @ dev: `node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_mod
ules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
`                                                                                                              
14 verbose stack Exit status 1                                                                                 
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16
)                                                                                                              
14 verbose stack     at emitTwo (events.js:106:13)                                                             
14 verbose stack     at EventEmitter.emit (events.js:194:7)

Any help would be greatly appreciated, this package looks awesome and I don't want to miss out!

**Comment by JeffreyWay** [comment]
It might be related to you using Cmder. I think I remember somebody saying that... 

Can anyone else confirm?

**Comment by QWp6t** [comment]
I use cmder for everything, never had any issues like that. Been using it for a couple years. But I'm not sure what sort of issues might arise when using node within the VM instead of the host OS.

Does Laravel community typically recommend that Homestead users run node on the VM instead of on the host operating system? Because that's what those logs indicate. If it were me, I'd try nuking the node_modules folder and running node on Windows, not within the VM.

**Comment by devcircus** [comment]
I use Cmder on Windows 8.1 and run all npm commands locally. Everything works as expected on the latest versions of everything.

**Comment by armesas** [comment]
@QWp6t Thank you so much, running outside of the VM worked!
