### ISSUE TITLE
Laravel mix and Laravel package development

### ISSUE THREAD

**Issue by nezaboravi** [JeffreyWay/laravel-mix#546]
This is more a question then an issue. I tried to find solution but could not read anything on this topic so far.
Developing package in /packages/vendor/package/src
Having a resource/assets/scss and resource/assets/js folders.
webpack.mix.js does the job and mix js and style for me into a public folder so i can see results while developing package:
`
mix.js('packages/vendor/package/src/resources/assets/js/app.js', 'public/vendor/js')
    .sass('packages/vendor/package/src/resources/assets/sass/app.scss', 'public/vendor/css/app.css');
`
Plan is that later user of package can publish package: php artisan vendor:publish --tag=public 
How my css and js from package will be published? they exists only in /packages/vendor/package/src/resources/assets and they are not mixed there.

Is it possible to have laravel mix to out put on more then one destination?
Eg mix.js('packages/vendor/package/src/resources/assets/js/app.js', ['public/vendor/js', 'another/destination/js'])

Or, if not, is it possible to have mix.copy to copy entire folder?
so, when mix.js and mix.sass create files in public/vendor/js and public/vendor/css we can just copy them in packages/vendor/package/src/public (for example)
mix.copy(['public/vendor/*'], 'packages/vendor/package/src/public');

**Comment by huypn** [comment]
I have same question, I want to develop a package and make it stand alone, ex: backend . and I want to use it for another project, but how can I config for webpack.mix.js? I need copy and paste it? or any way to create a file webpack.mix.js in package and call it from root website.mix.js?

**Comment by JeffreyWay** [comment]
You can't have it output to more than one destination. 

For your copy method, just remove the star, and it'll copy the whole directory.

```js
mix.copy(public/vendor, 'packages/vendor/package/src/public');
```

**Comment by emamie** [comment]
You can copy your webpack.mix.js to your package and run npm with this argument : 
` npm run dev -- --env.mixfile vendor/YOUR-VENDOR/YOUR-PACKAGE/webpack.mix`

**Comment by cristian-araujo** [comment]
> You can copy your webpack.mix.js to your package and run npm with this argument :
> ` npm run dev -- --env.mixfile vendor/YOUR-VENDOR/YOUR-PACKAGE/webpack.mix`

I have the same issue and trying that but it retrieve errror:

```
ERROR in ./node_modules/webpackbar/dist/webpackbar.js 6:14-29
Module not found: Error: Can't resolve 'path' in '/node_modules/webpackbar/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }

ERROR in ./node_modules/which/which.js 5:13-28
Module not found: Error: Can't resolve 'path' in '/node_modules/which'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }

```
