### ISSUE TITLE
laravel mix not importing all files.

### ISSUE THREAD

**Issue by vinod-neptrox** [JeffreyWay/laravel-mix#547]
In my webpack.mix.js , i include this files:
```
const { mix } = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');
   
mix.styles([
            'bootstrap.min.css',
            'bootstrap-datetimepicker.min.css',
            'select2-bootstrap.css',
            'font-awesome.min.css',
            'smartadmin-production-plugins.min.css',
            'smartadmin-production.min.css',
            'smartadmin-skins.min.css',
            'menu.css',
            'chosen.min.css',
            'your_style.css'

        ],
        'public/smartadmin/css/all.css',
        'resources/assets/smartadmin/css');

    /*main js*/
    mix.scripts([
            'plugin/pace/pace.min.js',
            'libs/jquery-2.1.1.min.js',
            'libs/jquery-ui-1.10.3.min.js',

        ],
        'public/smartadmin/js/jquery.js',
        'resources/assets/smartadmin/js');
    
    mix.scripts([
            'app.config.js',
            '/plugin/jquery-touch/jquery.ui.touch-punch.min.js',
            '/bootstrap/bootstrap.min.js',
            // '/bootstrap/moment.js',
            '/bootstrap/bootstrap-datetimepicker.min.js',
            '/notification/SmartNotification.min.js',
            '/smartwidgets/jarvis.widget.min.js',
            '/plugin/easy-pie-chart/jquery.easy-pie-chart.min.js',
            '/plugin/sparkline/jquery.sparkline.min.js',
            '/plugin/jquery-validate/jquery.validate.min.js',
            '/plugin/masked-input/jquery.maskedinput.min.js',
            '/plugin/select2/select2.min.js',
            '/plugin/bootstrap-slider/bootstrap-slider.min.js',
            '/plugin/bootstrap-timepicker/bootstrap-timepicker.min.js',
            '/plugin/colorpicker/bootstrap-colorpicker.min.js',
            '/plugin/clockpicker/clockpicker.min.js',
            '/plugin/msie-fix/jquery.mb.browser.min.js',
            '/plugin/fastclick/fastclick.min.js',
            '/plugin/chosen/chosen.jquery.min.js',
            'app.min.js',
            '/smart-chat-ui/smart.chat.ui.min.js',
            '/smart-chat-ui/smart.chat.manager.min.js',
            '/nestable/jquery.nestable.js',
            '/plugin/summernote/summernote.min.js',
            '/smartwidgets/jarvis.widget.min.js',
            '/plugin/easy-pie-chart/jquery.easy-pie-chart.min.js',
            '/plugin/fastclick/fastclick.min.js',
            'site.js'

        ],
        'public/smartadmin/js/all.js',
        'resources/assets/smartadmin/js');
     /*charts*/
        mix.scripts([
            'plugin/flot/jquery.flot.cust.min.js',
            'plugin/flot/jquery.flot.resize.min.js',
            'plugin/flot/jquery.flot.time.min.js',
            'plugin/flot/jquery.flot.tooltip.min.js',
            'plugin/vectormap/jquery-jvectormap-1.2.2.min.js',
            'plugin/vectormap/jquery-jvectormap-world-mill-en.js',
            'plugin/moment/moment.min.js',
            'plugin/fullcalendar/jquery.fullcalendar.min.js',
            'plugin/morris/raphael.min.js',
            'plugin/morris/morris.min.js',

        ],
        'public/smartadmin/js/charts.js',
        'resources/assets/smartadmin/js');

    /*stream datatable*/

    mix.scripts([
            'plugin/streamtable/stream_table.js',
            'plugin/streamtable/mustache.js',

        ],
        'public/smartadmin/js/streamtable.js',
        'resources/assets/smartadmin/js');

    /*stream table*/
    mix.scripts([
            'plugin/bootstrap-wizard/jquery.bootstrap.wizard.min.js',
            'plugin/fuelux/wizard/wizard.min.js',

        ],
        'public/smartadmin/js/wizard.js',
        'resources/assets/smartadmin/js');
    /*stream table*/
    mix.scripts([
            'plugin/streamtable/table.js',

        ],
        'public/smartadmin/js/table.js',
        'resources/assets/smartadmin/js');

```
after run npm run dev it gives:
                                                        

>             Asset      Size  Chunks                    Chunk Names
>   fonts/glyphicons-halflings-regular.eot?f4769f9bdb7466be65088239c12046d1   20.1 kB          [emitted]         
>   fonts/glyphicons-halflings-regular.svg?89889688147bd7575d6327160d64e760    109 kB          [emitted]         
>   fonts/glyphicons-halflings-regular.ttf?e18bbf611f2a2e43afc071aa2f4e1512   45.4 kB          [emitted]         
>  fonts/glyphicons-halflings-regular.woff?fa2772327f55d8198301fdb8bcfc8158   23.4 kB          [emitted]         
> fonts/glyphicons-halflings-regular.woff2?448c34a56d699c29117adc64c43affeb     18 kB          [emitted]         
>                                                                /js/app.js   1.17 MB       0  [emitted]  [big]  /js/app
>                                                              /css/app.css    683 kB       0  [emitted]  [big]  /js/app
>                                                         mix-manifest.json  66 bytes          [emitted]  

in my package.json i have:
{
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.15.3",
    "cross-env": "^3.2.3",
    "laravel-mix": "^0.8.8",
    "lodash": "^4.17.4",
    "vue": "^2.1.10",
    "webpack": "^2.2.1"
  },
  "dependencies": {
    "express": "^4.15.2",
    "ioredis": "^2.5.0",
    "socket.io": "^1.7.3"
  }
}

**Comment by JeffreyWay** [comment]
Can you be more specific about what your question is? What do you mean when you say Mix isn't importing all the files?

**Comment by ankurk91** [comment]
As far as i know ```mix.scripts()``` and ```mix.styles()``` methods accepts only two parameters, ```src``` and ```output```.

You are passing 3 arguments.
```src``` can be array of strings or a string.

Do it like this -
```js
// webpack.mix.js
 mix.scripts([
          'path/to/file1.js',
          'path/to/file2.js',
        ],
       // path where you wants to store output file
        'public/buld/js/app.min.js');
```
```blade
<script src="{{ mix('build/js/app.min.js') }}"></script>
```
