### ISSUE TITLE
Cannot get HMR enabled with Laravel 5.3

### ISSUE THREAD

**Issue by oshaggy** [JeffreyWay/laravel-mix#549]
- Laravel Mix Version: 0.8.8
- Node Version: 6.9.1
- NPM Version: 3.10.8
- OS: Windows 7x64

### Description:

I'm working on adding laravel-mix into an existing Laravel 5.3 installation.

After installation and configuration, the --hot option does not appear to be enabling the HMR module.

### Steps To Reproduce:

Install a blank Laravel 5.3 installation.

Install laravel-mix as per documentation and configure webpack.mix.js to locate assets as expected.

Remove node_modules and npm install them back again to make sure old Elixir packages are gone.

"npm run hot" compiles successfully and is running on port 8080 with the "--inline --hot" options set as per the package.json script command.

I have also adjusted my HTML template to load the support scripts from port 8080 ( Laravel 5.3 doesn't have mix() yet )

On my browser side I cannot see the [HMR] [WDS] messages in console.

Further, inspecting the compiled //localhost:8080/public/js/app.js shows that HMR is not enabled "if(false)":

> /* hot reload */
> if (false) {(function () {
>   var hotAPI = __webpack_require__(0)
>   hotAPI.install(__webpack_require__(1), false)
>   if (!hotAPI.compatible) return
>   module.hot.accept()
>   if (!module.hot.data) {
>     hotAPI.createRecord("data-v-5f1cc15a", Component.options)
>   } else {
>     hotAPI.reload("data-v-5f1cc15a", Component.options)
>   }
> })()}

From what I understand the "--hot" option should be enabling the HMR for every module, but it doesn't appear to be doing that as above. Any ideas what I'm missing in my config to get this running?

Here is my package.json file

> {
>   "private": true,
>   "scripts": {
>     "dev": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "watch-poll": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
>     "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
>   },
>   "devDependencies": {
>     "axios": "^0.15.3",
>     "bootstrap-sass": "^3.3.7",
>     "jquery": "^3.1.1",
>     "laravel-mix": "^0.8.8",
>     "lodash": "^4.17.4",
>     "vue": "^2.1.10"
>   }
> }

Here is my webpack.mix.js

> let mix = require('laravel-mix');
> 
> mix.js('resources/assets/js/app.js', 'public/js/')
>    .sass('resources/assets/sass/app.scss', 'public/css/');
> 

Using the default webpack.config.js from the 0.8.8 setup folder.

**Comment by Namesonic** [comment]
I have this working now ...

Two issues:

1) I had the wrong asset path on my blade template which should be "//localhost:8080/js/app.js" instead of "//localhost:8080/public/js/app.js" ( which is weird because this path exists, just without HMR enabled )

2) Node-sass may also have been out of date and was giving me some troubles and I wasn't seeing a dependency in node_modules upon re-installation so I added this to my package.json file and re-installed the node_modules directory:

"node-sass": "^4.0.0",

HMR working in Laravel 5.3 now!
