### ISSUE TITLE
Cannot find module '/home/vagrant/Code/blog/node_modules/cross-env/bin/cross-env.js

### ISSUE THREAD

**Issue by doncadavona** [JeffreyWay/laravel-mix#551]
- Laravel Mix Version: 0.6.0
- Node Version (`node -v`): 5.10.1
- NPM Version (`npm -v`): 3.8.3
- OS: macOS Sierra 10.12.3

### Description:
On my fresh Laravel 5.4.14, running `npm run dev` gets into this error:

```
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

module.js:341
    throw err;
    ^

Error: Cannot find module '/home/vagrant/Code/blog/node_modules/cross-env/bin/cross-env.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/repoducing-laravel-mix-issue-519/npm-debug.log
```

So I read through these similar issues, https://github.com/JeffreyWay/laravel-mix/issues/519, https://github.com/JeffreyWay/laravel-mix/issues/523, https://github.com/laravel/framework/issues/17528, but got no luck.

After updating my Laravel from **5.4.14** to **5.4.15** by running `composer install` and `npm install` afterwards, still got the same error.

Also reproduced on a fresh Laravel 5.4.15 installation by running `composer global require "laravel/installer"`, the error still persist in `npm run dev`.

### Steps To Reproduce:

1. Install Laravel: $ ``composer global require "laravel/installer"``
2. Install NPM modules: $ `npm install`
3. Run: $ `npm run dev`

**Comment by coder77** [comment]
sudo npm install
sudo npm run dev

**Comment by shemi** [comment]
The cross-env package change the bin directory path from cross-env/bin to cross-env/dist/bin

just update your package.json file:

```json
...
scripts: {
    "dev": "node node_modules/cross-env/dist/bin/cross-env.js...
```

**Comment by doncadavona** [comment]
@shemi Can you share what exactly should he scripts.dev contain in package.json? Mine currently is:
`"node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"`

**Comment by shemi** [comment]
"node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"

**Comment by doncadavona** [comment]
Thanks, but doing so gets this error:

```
> @ dev /home/vagrant/Code/merchant2
> node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/home/vagrant/Code/merchant2/node_modules/laravel-mix/setup/webpack.config.js:126
        let extractPlugin = new plugins.ExtractTextPlugin(
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at requireConfig (/home/vagrant/Code/merchant2/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/vagrant/Code/merchant2/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/merchant2/npm-debug.log
```

**Comment by doncadavona** [comment]
Thanks, but doing so get this error:

```
Thanks, but doing so get this error:

```
> @ dev /home/vagrant/Code/blog
> node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/home/vagrant/Code/blog/node_modules/laravel-mix/setup/webpack.config.js:126
        let extractPlugin = new plugins.ExtractTextPlugin(
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at requireConfig (/home/vagrant/Code/blog/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/vagrant/Code/blog/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/blog/npm-debug.log
```
```

**Comment by shemi** [comment]
Try deleting the node_modules folder and run npm install

**Comment by doncadavona** [comment]
@coder77 running sudo results to the same error for me.

**Comment by doncadavona** [comment]
@shemi, Also did just that with: `rm -rf node_modules`, then `npm install`. Same error afterwards.

**Comment by shemi** [comment]
@doncadavona  share your package.json

**Comment by asimshazad** [comment]
Hi,i am also getting this error,while using this command
npm run production

Error: Cannot find module '/Applications/MAMP/htdocs/revamp/node_modules/cross-env/bin/cross-env.js'

Here is my package.json file.

{
  "private": true,
  "scripts": {
    "dev": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "bin": {
    "cross-env": "dist/bin/cross-env.js"
  },
  "devDependencies": {
    "axios": "^0.15.2",
    "bootstrap-sass": "^3.3.7",
    "jquery": "^3.1.0",
    "laravel-mix": "^0.6.0",
    "lodash": "^4.16.2",
    "vue": "^2.0.1"
  }
}

**Comment by JeffreyWay** [comment]
@doncadavona Update Node. You have an outdated version. 

@asimshazad @shemi already posted a solution for your issue.

**Comment by doncadavona** [comment]
@JeffreyWay, I updated my node from **v5.10.1** to **v5.11.1**, same error, then updated to **v6.10.0** LTS, same error, then **v7.7.2**, still got the same error. Also tried on another mac with same tests, also getting the same error.

**Comment by gummiforweb** [comment]
I'm having same issue. With a brand new Laravel install. Node and Npm are also the latest version.

A temporarily fix is to change the script to load from `node_modules/cross-env/bin/cross-env.js` to `node_modules/cross-env/dist/bin/cross-env.js`. Just need to add the dist folder.

I'm not sure why, but every time i do `npm install`, there's that dist folder. 

<img width="1084" alt="screen shot 2017-03-11 at 5 58 00 pm" src="https://cloud.githubusercontent.com/assets/10493135/23828389/b2e0305a-0684-11e7-853f-94e141a37034.png">

**Comment by doncadavona** [comment]
Here's my package.json:

```json
{
  "private": true,
  "scripts": {
    "dev": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "bootstrap-sass": "^3.3.7",
    "jquery": "^3.1.0",
    "laravel-mix": "^0.6.0",
    "lodash": "^4.16.2",
    "vue": "^2.0.1"
  }
}

```

The only thing changed here is that I've changed:

`"dev": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",`

to:

`"dev": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",`

Still having the errors thou up to now.

**Comment by StephanDisberg** [comment]
@doncadavona 
I think the issue is you have to update your laravel-mix version. Can you try this with replacing your package.json with the following (and then reinstall node-modules):

{
  "private": true,
  "scripts": {
    "dev": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.15.3",
    "bootstrap-sass": "^3.3.7",
    "jquery": "^3.1.1",
    "laravel-mix": "^0.8.1",
    "lodash": "^4.17.4",
    "vue": "^2.1.10"
  }
}

Hope this will work ;)

**Comment by JeffreyWay** [comment]
Everyone - the solution has been posted many times. If you get an error related to cross-env not being found, do `npm install cross-env -D` in your project, and then update your package.json file to remove the full node_modules/**/cross-env path, and replace it with simply "cross-env"

**Comment by logancollinsworth** [comment]
I'm having the same issue here on Laravel 6

`vagrant@homestead:~/code/tdd$ nrd

> @ dev /home/vagrant/code/tdd
> npm run development


> @ development /home/vagrant/code/tdd
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

98% after emitting SizeLimitsPlugin

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                              2:20:10 AM

This dependency was not found:

* /home/vagrant/code/tdd/resources/less/app.less in multi ./resources/js/app.js ./resources/less/app.less

To install it, you can run: npm install --save /home/vagrant/code/tdd/resources/less/app.less
     Asset      Size   Chunks             Chunk Names
/js/app.js  1.39 MiB  /js/app  [emitted]  /js/app

ERROR in multi ./resources/js/app.js ./resources/less/app.less
Module not found: Error: Can't resolve '/home/vagrant/code/tdd/resources/less/app.less' in '/home/vagrant/code/tdd'
 @ multi ./resources/js/app.js ./resources/less/app.less /js/app[1]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-02-12T02_20_10_922Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-02-12T02_20_10_934Z-debug.log
vagrant@homestead:~/code/tdd$ npm install --save /home/vagrant/code/tdd/resources/less/app.less
[..................] / rollbackFailedOptional: verb npm-session 219c57393fc6f8e0
npm ERR! code ENOLOCAL
npm ERR! Could not install from "resources/less/app.less" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-02-12T02_21_09_037Z-debug.log
`
