### ISSUE TITLE
vue-template-compiler and vue version mismatch

### ISSUE THREAD

**Issue by neuotq** [JeffreyWay/laravel-mix#552]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`): v6.9.4
- NPM Version (`npm -v`): 4.1.2
- Yarn Version :  v0.21.3
- OS: Windows 10

### Description:
Error while assets compiling, **vue version 2.2.2** but **vue-template-compiler** in laravel-mix is **2.2.1**, need to update

### Steps To Reproduce:

update to latest version via Yarn and run  
`yarn run dev`  
or  
`npm run dev`

**Comment by JeffreyWay** [comment]
You should be able to nuke your node_modules folder and redo npm install.

**Comment by raulghm** [comment]
Tip: 
`yarn cache clean `
`rm -rf node_modules`
`yarn`

👌
