### ISSUE TITLE
Using extract(); the manifest.js output path is different from vendor.js

### ISSUE THREAD

**Issue by etiennellipse** [JeffreyWay/laravel-mix#553]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`): 6.10.0
- NPM Version (`npm -v`): 3.10.10
- OS: Windows

### Description:

When using `extract()` with an output path, the webpack manifest.js is written in the directory specified in the last `mix.js()` call. I would expect it to be written alongside the vendor.js, since it is also a common library.

In our product, we have a set of independent Vue applications that are output into a "module" directory, while the common scripts (vendor.js, manifest.js and so on) are in a "script" directory.

### Steps To Reproduce:

With this configuration:
```
mix.js('src/teacher.js', 'module/teacher/teacher.js')
   .js('src/student.js', 'module/student/student.js')
   .extract(['vue'], 'script/vendor.js')
   .webpackConfig({
      output: { chunkFilename: 'module/[name].bundle.js', publicPath: publicPath }
   })
   .sourceMaps();
```

The manifest.js file is written to the *module/student* directory, which matches the last call to `mix.js()` since the `Mix.js.base` is used here: https://github.com/JeffreyWay/laravel-mix/blob/master/setup/webpack.config.js#L356

Workaround: hardcoding the path in webpack.config.js.

**Comment by blogui91** [comment]
Same problem here

**Comment by trevorgehman** [comment]
Yeah, I'm having this issue as well.

**Comment by pprins** [comment]
Yes, same here. This should also work with #488

**Comment by VinceG** [comment]
@JeffreyWay  This was fixed in master which i just pulled but same behavior happens. it generates only one manifest file.

any specific configuration required to make this work?

**Comment by moyvera** [comment]
I see @JeffreyWay made the commit but for me it's not working and a new user just referenced a new issue with the same problem

@etiennellipse, @VinceG  can you share your workaround or configuration ? please

**Comment by etiennellipse** [comment]
@moyvera For this specific issue with v0.8.8, I could hack the webpack.config.js file to hardcode a path for the manifest. There was a section for the "CommonsChunkPlugin" declaring where the manifest is output, that used `Mix.js.base` which was causing the issue.

I replaced the base path, doing something link:
```
const myScriptBasePath = 'path/to/scripts';

if (Mix.extract) {
   module.exports.plugins.push(
       new webpack.optimize.CommonsChunkPlugin({
          names: Mix.entryBuilder.extractions.concat([
              path.join(myScriptBasePath, 'manifest').replace(/\\/g, '/')
          ]),
          minChunks: Infinity
       })
   );
}
```

However Mix has changed a lot since then, I don't expect it to work with the latest version.

**Comment by dvlpr91** [comment]
빨리 고쳐라
