### ISSUE TITLE
Laravel-mix, extensions

### ISSUE THREAD

**Issue by dung13890** [JeffreyWay/laravel-mix#557]
Sorry @JeffreyWay, your laravel-mix is very awesome but why it don't have extensions. I want use `mix.extend` same elixir.extend. 

- Laravel Mix Version: 0.8.8
- Node Version (`node -v`):  6.10.0
- NPM Version (`npm -v`):  3.10.10
- OS: Ubuntu 16.04

### Description:
And Cannot find module package.json `node node_modules/cross-env/bin/cross-env.js`, so I fixed it by
` node node_modules/cross-env/dist/bin/cross-env.js`

### Steps To Reproduce:
1. Install a new Laravel app: $ composer create-project --prefer-dist laravel/laravel blog
2. Install NPM modules: $ npm install
3. Run: $ npm run dev

**Comment by JeffreyWay** [comment]
That was done on purpose. You can use mix.webpackConfig to add any custom functionality.
