### ISSUE TITLE
Can we Have BrowserSync added? 

### ISSUE THREAD

**Issue by g0ld3lux** [JeffreyWay/laravel-mix#56]
Right Now , if we Run npm run hmr , and we change anything in our vue files its being hot reloaded....
But what if we change something in our blade files?

I hope we Can Use Again Browsersync like in laravel elixir, 
lets say we will proxy it on localhost:3000 
and still we have it also hot reloaded... at localhost:8080 via npm run hmr...
hope we can add some alias like npm run browsersync... 
which behind the scene will check any changes in our blade template...

**Comment by QWp6t** [comment]
for what it's worth, i'll be making sure that my browsersync plugin works with laravel-mix 

https://github.com/QWp6t/browsersync-webpack-plugin

(i think there would be issues right now because i'm pretty sure webpack-dev-middleware would conflict with webpack-dev-server)

**Comment by g0ld3lux** [comment]
would be waiting for the update, thanks

**Comment by Bram-Zijp** [comment]
@QWp6t  You sound like you know the answer to my question that got no answer in a week or two. Could you be so kind and take a peek?  https://laracasts.com/discuss/channels/general-discussion/cannot-get-when-proxying-with-browsersync

**Comment by Bram-Zijp** [comment]
The browser-sync-webpack-plugin coops nicely with the Webpack Dev Server. Check out [the repository](https://github.com/Bram-Zijp/Webpack-BrowserSync-HMR---Laravel) in which I composed a working example for an Homestead Environment.

**Comment by tormjens** [comment]
For the time being you can also run BrowserSync from the command line.

I use this:
```
browser-sync start --proxy example.dev --files="dist/**/*.css,dist/**/*.js,templates/**/*.blade.php"
```

**Comment by rogierborst** [comment]
@tormjens For some reason your solution works great for js and css files, but my blade templates don't seem to trigger a refresh. Any idea why that would be? Even `**/*.php` won't do the job...

**Comment by Bram-Zijp** [comment]
@rogierborst After some time of playing around with BrowserSync paired with HMR and the dev server, I recommend installing BrowserSync and use it like so:

Note: the usePolling/poll claims to have a performance impact but in my Windows + Homestead environment it is required. The host path constants are setup for a non Laravel build.

```
"browser-sync": "^2.6.0",
"webpack-dev-middleware": "^1.9.0",
"webpack-dev-server": "^2.2.0-rc.0",
"webpack-hot-middleware": "^2.15.0",


import BrowserSync from 'browser-sync'

const HOST              = 'lol.dev',
      HOST_PATH         = 'resources/views'


BrowserSync({
    host: HOST,
    port: 3000,
    proxy: `http://${HOST}:8080`,
    ui: false,
    open: false,
})

BrowserSync.watch(
    'resources/views/**/*.{php,html}',
    {usePolling: true},
    BrowserSync.reload,
)
module.exports {
    devServer: {
        inline: true,
        hot: true,
        contentBase: '/',
        proxy: { '*': `http://${HOST}/${HOST_PATH}` },
        host: HOST,
        port: 8080,
        stats: { colors: true },
        watchOptions: { poll: 1000 },
    },
}

```

**Comment by rogierborst** [comment]
I'm not sure what file you do this in. `scripts` and `devDependencies` is in `package.json`, I assume. But where do you put the other config lines?

**Comment by Bram-Zijp** [comment]
Normally you place all in webpack.config.js. With laravel mix you need to setup atleast the devServer there. You should be able to add the BrowserSync parts in both webpack.config.js and the webpack.mix.js. but mind the constant HOST and the `import BrowserSync from 'browser-sync'` should become `var BrowseSync = require('browser-sync')` as I don't recall Laravel Mix has import availeble

**Comment by Bram-Zijp** [comment]
@rogierborst I updated to comment to be more explanatory

**Comment by rogierborst** [comment]
Thanks, I have it working now! Can't get hrm to work, but that has never worked for me anyways. Something to do with me running on a windows machine I believe. I think there's a pr out there that tries to solve it.

**Comment by Bram-Zijp** [comment]
@rogierborst  HMR should be working. Try adding this  `if(module.hot) module.hot.accept() `  at the bottom of your script. Everything above this line (imports and the code in the file itself) should trigger Hot Reloads.

**Comment by rogierborst** [comment]
@Bram-Zijp It's the `Mix()` php helper function that doesn't find the newly processed js file. So it's not node related. I can go to `localhost:8080/public/js/app.js` and see the file is updated (so yes, hrm works on that end), but my view throws an `Unable to locate Mix file` exception.

**Comment by ashokgelal** [comment]
If anyone is interested, I got it working without much fuss. I wrote a little blog post on how to setup Browsersync with Laravel Mix: https://ashokgelal.com/2017/01/29/laravel-mix-browsersync/

**Comment by baoyudou** [comment]
@ashokgelal I have used it form windows, it works!! Thanks, you save my life!!

**Comment by 1oginov** [comment]
@ashokgelal works on Windows, thank you!

I have projects using names like `appname.localhost:8056` and no one solutions works with this, BrowserSync haven't loaded _http://localhost:3000_ until I've added `appname.localhost` to the **hosts** file. So, turned out it just can't resolve address. BTW, [documented](https://laravel.com/docs/5.4/mix#browsersync-reloading) `mix.browserSync('appname.localhost:8056');` works too.

**Comment by corysimmons** [comment]
### Laravel 5.4

1. `$ yarn add -D browser-sync`
2. Add [this proxy snippet](https://laravel.com/docs/5.4/mix#browsersync-reloading) to `webpack.mix.js`:

```js
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .browserSync({
       proxy: 'blog.dev'
   });
```

3. `yarn run watch`

#### Bit more seamless

- Disable those `Injected app.css` messages: https://browsersync.io/docs/options#option-notify
- Disable auto opening (so you don't end up with a bunch of the same tabs): https://browsersync.io/docs/options#option-open

```js
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .browserSync({
       proxy: 'blog.dev',
       notify: false,
       open: false
   });
```

By default, it seems like Laravel Mix watches `public/{*,**/*}` (all compiled assets) and Blade files, but it doesn't seem to other php files. You can change that with the `files` BrowserSync property.

```js
// webpack.mix.js
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .browserSync({
       proxy: 'blog.dev',
       notify: false,
       open: false,
       files: [
'!node_modules', '!vendor', 'public/{*,**/*}', '{*,**/*}.php']
   });
```

This will watch everything in `public` and **all** your `.php` files (which is pretty nice). 

Hope this helps.

**Comment by nok** [comment]
Thanks @corysimmons!

**Comment by corysimmons** [comment]
np. I'm sure there's a better way to do it via overriding the [`webpackConfig` object](https://laravel.com/docs/5.4/mix#custom-webpack-configuration) but I'm too lazy to figure it out.

@JeffreyWay If possible, it'd be nice if we could get Webpack to watch styles and all php (sans `vendor`) by default. If you'd be interested in that I can figure out the Webpack way to do it and possibly submit a PR.
