### ISSUE TITLE
Resolve problem [ location ] not in css folder ,, and watch file didn't delete files and not added to [ mix-manifest ] file

### ISSUE THREAD

**Issue by pixieaka** [JeffreyWay/laravel-mix#561]
We have to add this to css folder and mix-manifest file as we added all files and watch it for any update for delete old files.

![untitled-1](https://cloud.githubusercontent.com/assets/17777237/23828395/aecf8606-06d8-11e7-938d-9703bdd783f6.jpg)

**Comment by JeffreyWay** [comment]
This is fixed in the next release.
