### ISSUE TITLE
can't render {{ }} in file .vue 

### ISSUE THREAD

**Issue by jrpikong** [JeffreyWay/laravel-mix#562]
I have successfully installed laravel vue 5.4 and 2.
I get into trouble if I want to render vue component in file .vue

ex:
resources / assets / js / components / Home.vue 
`<template>
    <div class="container">
        <div class="row">
            <div v-if="Loading">Loading</div>
            <div class="panel panel-default" v-for="user in users">
                <div class="panel-heading">{{user.name}}</div>
            </div>
        </div>
    </div>
</template>

<script>
    export default{
        data(){
            return{
                users:[],
                Loading:false
            }
        },
        mounted(){
            this.Loading = true;
            axios.get('api/user').then((response)=>{this.users=response.data; this.Loading=false});

        }
    }
</script>`

app.js

`import router from './routes.js';
require('./bootstrap');

const app = new Vue({
    el: '#app',
    router
});`

webpack.mix.js
let mix = require('laravel-mix');
mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css');

I'm can't render '<div class="panel-heading">{{user.name}}</div>' element in Home.vue
{{ }} not work

**Comment by JeffreyWay** [comment]
Without filling out the issue template or providing the error message, I can't help.
