### ISSUE TITLE
[Suggestion] Adding polyfills on demand to the bundle.

### ISSUE THREAD

**Issue by Frondor** [JeffreyWay/laravel-mix#564]
We're using different polyfills almost all the time, and that means merging our `webpack.config` with Laravel-mix.

If possible, why not to include an option like this
```
mix.js('resources/assets/js/app.js', 'public/js')
   .options({
      polyfills: [
         'Promise'
      ]
   });
```
which should take the polyfills from something like [polyfill-service](https://github.com/Financial-Times/polyfill-service)s and add them to our `app.js` bundle.

Or probably there's a simpler solution, but I think something like this won't hurt and it's quite practical.

**Comment by adiachenko** [comment]
I'm fine with the idea, assuming it would be an opt-in behavior (meaning I can choose myself whether to require polyfills by hand, install babel-polyfill, use polyfill.io or whatever).

**Comment by Frondor** [comment]
That's the idea. Although it may count as "require polyfills by hand" but yes.

**Comment by adiachenko** [comment]
Well, the difference is polyfill.io requests polyfills at runtime by looking into User agent. It has very small footprint in the bundle, but you rely on external service.

In any case, I think this is a great idea.

**Comment by Frondor** [comment]
I wasn't aware of that, I though webpack could extract the polyfill code and use it "offlineish" in the bundle.
Anyway, it was just an example. We can generate our own list of polyfills and call them on demand
