### ISSUE TITLE
Allow wildcards

### ISSUE THREAD

**Issue by TheDeadCode** [JeffreyWay/laravel-mix#566]
Feature request to allow the user to add wildcard to JS files, such as:

```javascript
mix.js('resources/assets/js/pages/*.js', 'public/js/pages')
```

**Comment by JeffreyWay** [comment]
You can do this with mix.scripts(), but for the main mix.js(), it's best to provide a single entry file.

**Comment by TheDeadCode** [comment]
`mix.babel('resources/assets/js/pages/*.js', 'public/js/pages')` still doesn't work..

`scripts` seems to only do ES5, so I need `babel`.


Also, what I was saying in the original post is:

Let's imagine this dir structure
```
resources/assets/js/pages
    -> index.js
    -> login.js
    -> register.js
    -> edit.js
```

Using this command: `mix.js('resources/assets/js/pages/*.js', 'public/js/pages')`, it should generate those files:

```
public/js/pages
    -> index.js
    -> login.js
    -> register.js
    -> edit.js
```

Is there anything right now that allows that?

**Comment by JeffreyWay** [comment]
Ah I misunderstood. `mix.babel()` will combine all of those files into, and apply Babel compilation.

```js
 mix.babel('resources/assets/js/pages/**/*.js', 'public/js/all.js');
```

In your case, either specify the files manually, or create a single entry point that requires all of those other pages.

**Comment by TheDeadCode** [comment]
Cool, thank you. Is there any plans in the future to allow what I described?

**Comment by JeffreyWay** [comment]
I don't think so.

**Comment by KarlJakober** [comment]
+1 for this, pretty big

**Comment by kirov117** [comment]
+1, would be very useful.

**Comment by scottbaggett** [comment]
+1

**Comment by pr4xx** [comment]
+1

**Comment by daanhaitsma** [comment]
+1

**Comment by penance316** [comment]
+1
multiple output files would be really helpful for me.

I would like to include page specific scripts by using the following:
.babel('resources/assets/js/pagescripts/*.js', 'public/js/')

Ideally, this would generate multiple files using the names from the source files, then i could just add a script tag to any page that required any one script.

currently, we need to specify each script individually for transpiling through babel like:
.babel('resources/assets/js/pagescripts/asd.js', 'public/js/asd.js')
.babel('resources/assets/js/pagescripts/two.js', 'public/js/two.js')
.babel('resources/assets/js/pagescripts/another.js', 'public/js/another.js')

**Comment by dharkness** [comment]
Allowing a simple one-for-one compilation with wildcards would be very beneficial when dealing with old projects. We compile each SASS file to a separate CSS file and merge them on a page-by-page basis on-the-fly. While I'd love to rewrite it all to be more modern, we don't have time for that.

But we also are moving to Mix, and the same codebase needs to be used by both systems as we migrate old code. It may seem like a bad practice, but it's the process we have. I imagine many other people are in the same boat and don't have the luxury to start from scratch. Please reconsider adding this.

**Comment by pixelpaulaus** [comment]
+1

**Comment by priyankmaniar** [comment]
@penance316 Give [this](http://priyank.rocks/laravel-mix-how-to-output-separate-files-rather-than-a-combined-one/) a try.

**Comment by penance316** [comment]
@priyankmaniar thanks for the link it worked great.
I sometimes forget that the build system is just JS code and we have the power to do things like this.
I would suggest others on this thread check the link mentioned.

**Comment by dmitry-ivanov** [comment]
+1

Would be really great to create all the bundles by one line.

**Comment by modder2** [comment]
There is still no updates on this issue?

**Comment by g0d13** [comment]
Any updates?

**Comment by ArsalaBangash** [comment]
Surprised to see no updates on this issue

**Comment by f-laino** [comment]
workaround:

```js
const fs = require("fs");

fs.readdirSync("resources/js/containers/").forEach(fileName => mix.js(`resources/js/containers/${fileName}`, "public/js"));
```

**Comment by flyke** [comment]
I needed something that converted from:
- src
- - js
- - - file1.js
- - - file2.js
- - - subfolder
- - - - file3.js
to:
- js
- - file1.js
- - file2.js
- - - subfolder
- - - - file3.js

I did it like this in my webpack.mix.js:
```
...
const fs = require("fs");

// Helper to get all files of a given extension in a given directory and its subfolders.
function getFilesRecursive(dir, type) {
    // The list of files that we will return.
    let files = []
    // Loop everything in given location.
    fs.readdirSync(dir).forEach(file => {
        let fileName = `${dir}/${file}`
        // Add if its a file and it is of the correct file type.
        if(fs.statSync(fileName).isFile() && fileName.endsWith(type)) {
            files.push(fileName)
        }
        // Process subfolder.
        if(!fs.statSync(fileName).isFile()) {
            // Recusively loop this function for the subfolder.
            files = files.concat(getFilesRecursive(fileName, type))
        }
    })
    return files
}

...

getFilesRecursive('src/js', '.js').forEach(file => {
    subfolder = file.match(/(.*)[\/\\]/)[1]||''; // 'src/js/libraries'
    subfolder = subfolder.replace('src/js', ''); // '/libraries'
    mix.js(file, 'js' + subfolder);
});
```
