### ISSUE TITLE
Async chunk loading (code splitting) doesn't work

### ISSUE THREAD

**Issue by adiachenko** [JeffreyWay/laravel-mix#567]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`): v6.9.2
- NPM Version (`npm -v`): 3.10.9
- OS: Windows 10

### Description:

Async chunks are dropped directly into public directory and are unable to load on demand.

### Steps To Reproduce:

```
if (document.getElementsByClassName('datepicker').length) {
  Vue.component('datepicker', (resolve) => {
    require(['./components/Datepicker.vue'], resolve)
  })
}
```

**Comment by Uriziel01** [comment]
Having exactly the same issue here. `admin.js` and `vendors.js` generated as intended into `js/dist` but all async files just emmited to root directory.

Also shouldn't webpack async loader be using main entry output directory? Now its just trying to load my async chunks directly from `http://domainname.com/0.js' and all my js files are in fact under `http://domainname.com/js/dist/0.js`

**Comment by etiennellipse** [comment]
Did you set an output directory for your async chunks?
```
mix.js(your_files)
   .webpackConfig({
      output: { chunkFilename: 'chunks/[name].bundle.js', publicPath: '/js/' }
   })
```

By setting these webpackConfig, the async chunks will be written /js/chunks/...

**Comment by adiachenko** [comment]
@etiennellipse Thanks, you're correct. Although I changed publicPath to make it work (and also added chunkhash to align with established convention):

```
  .webpackConfig({
    output: { chunkFilename: 'chunks/[name].[chunkhash].bundle.js', publicPath: '/' }
  })
```

But this should be handled by `laravel-mix` without additional configuration as it's a core webpack feature. 

Can someone else test this with their own setup and check different use cases (like hmr) so this can be safely merged into the library.

**Comment by adiachenko** [comment]
@Uriziel01 @etiennellipse This issue has been fixed as of **0.9.2** and async chunks are now working without any additional configuration, therefore I'm closing this.

**Comment by sullyfischer** [comment]
I'm having this very issue even after upgrading to v2.0.0.

**Comment by loyd-cpi** [comment]
Is there any workaround with this issue? I'm also using v2.0.0
