### ISSUE TITLE
Running 'hot' complains about [chunkhash]

### ISSUE THREAD

**Issue by bahjaat** [JeffreyWay/laravel-mix#568]
- Laravel Mix Version: 0.8.2
- Node Version (`node -v`): 6.4.0
- NPM Version (`npm -v`): 4.4.1
- OS: Darwin Kernel Version 16.4.0

### Description:
Just tried running 'hot'. It complains about [chunkhash]:

    Cannot use [chunkhash] for chunk in '[name].[chunkhash].js' (use [hash] instead)

### Steps To Reproduce:

    npm run hot

### Possible fix

replace ***[chunkhash]*** with ***[hash]*** I guess.

**Comment by hydrarulz** [comment]
Changing chunkhash with hash still does not fix the issue, because after that navigating to `localhost:8080` does not open any laravel route, it's just saying it could not find `/`

**Comment by alanaasmaa** [comment]
I had the same problem but little google solved my issue:

```
if (mix.config.inProduction) {
    mix.version();
}
```

**Comment by ankurk91** [comment]
https://github.com/JeffreyWay/laravel-mix/issues/344#issuecomment-313580161

**Comment by ctf0** [comment]
having the same issue, neither of the above solutions works, still getting
```bash
 ERROR  Failed to compile with 2 errors                                                                               12:10:04 PM

 error  in [name].[chunkhash].js

Cannot use [chunkhash] for chunk in '[name].[chunkhash].js' (use [hash] instead)

 error  in [name].[chunkhash].js

Cannot use [chunkhash] for chunk in '[name].[chunkhash].js' (use [hash] instead)
```
