### ISSUE TITLE
No confirmation output in build for mix.combine/scripts/styles().

### ISSUE THREAD

**Issue by danielbaylis** [JeffreyWay/laravel-mix#569]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`): 7.7.1 
- NPM Version (`npm -v`): 4.1.2
- OS: MacOS

### Description:
The results of the `mix.combine()`, `mix.scripts()` and `mix.styles()` methods do not produce any console output after the build process (i.e. `npm run dev`). Therefore there is no confirmation that assets created by these methods were successful.

Not sure if this is mix related or webpack, but it would be great to see confirmation of the build as we get when using `mix.js()` or `mix.sass()`. Example:
`/js/app.ce184b19987605b8f123.js    1 MB       0  [emitted]`

Related - If there is an invalid file referenced in the array supplied to combine/scripts/styles, it is silently skipped over by the build process. At the very least it would be great to see mix squawk about the missing file, perhaps even better it should halt as a critical `npm ERR!` instead?

``` js
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .combine([
        'resources/css/main.css',
        'resources/css/non-existent-file.css'
    ], 'public/css/styles.css');
```

### Steps To Reproduce:

1. Utilize the combine(), styles() or scripts() methods in webpack.mix.js
2. `npm run dev`

``` js
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .combine([
        'resources/css/main.css',
        'resources/css/non-existent-file.css'
    ], 'public/css/styles.css');
```

Maybe add `npm list --depth=0` to the issue template for an easy way to get the current laravel-mix version?

Thanks for bringing us mix!

**Comment by ionesculiviucristian** [comment]
I get the feeling that Laravel Mix is a big regress. I've just installed it and I don't have any relevant output (in Elixir, the table structure was pretty informative), the destination param is not what I specify to be and I don't see where to modify those settings (like elixir.config.css.outputFolder in Elixir).

**Comment by JeffreyWay** [comment]
@danielbaylis It's because basic concatenation like mix.styles() isn't part of your core Webpack build. It's just extra functionality that we offer. 

@ionesculiviucristian You can create a separate issue with your question about the destination not working. Mix is significantly more powerful than Elixir. You probably have an error in your config.

**Comment by danielbaylis** [comment]
@JeffreyWay Thanks for the clarification! I can see now how Mix/Concat is providing this and why it wouldn't be in the webpack output.
