### ISSUE TITLE
processCssUrls doesn't seems to apply to .vue files

### ISSUE THREAD

**Issue by amitailanciano** [JeffreyWay/laravel-mix#571]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`): v7.3.0
- NPM Version (`npm -v`): 4.4.1
- OS: Sierra 10.12.3

### Description:

`processCssUrls: false` doesn't work with `.vue` files using `<style lang="sass">` or `<style lang="scss">`.

### Steps To Reproduce:

```
# some .vue file
<template>
<div></div>
</template>

<script>
export default {}
</script>

<style scoped lang="scss">
div {
    background-image: url('../../some/path/image.jpg');
}
</style>

# webpack.mix.js

mix.
    ...
    .options({
        processCssUrls: false
    });
```

rewrites the property to `url('/some/path/image.jpg')`, when it should remain `url('../../some/path/image.jpg')`

**Comment by gskgrek** [comment]
I have the same problem on Laravel Mix Version: 2.1.11.
When useing in .vue files
```
<style lang="scss" scoped>
    div {
        background-image: url('../../some/path/image.jpg');
    }
</style>
```
Option `processCssUrls: false` is ignored and error `Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve '../../some/path/image.jpg'` occures.
