### ISSUE TITLE
Phantom mix.js file referenced but doesn't exist.

### ISSUE THREAD

**Issue by kahunacoder** [JeffreyWay/laravel-mix#572]
- Laravel Mix Version: laravel-mix@0.8.8
- Node Version v7.7.2: 
- NPM Version 4.1.2: 
- OS: macOS Sierra 10.12.3

### Description:
I'm adding laravel-mix to a non laravel legacy project. I'm using mix.styles and mix.scripts to concate and minimize my scripts and styles. Everything works as expected but in my mix-manifest.json file and in the terminal when webpack finishes I see a file called mix.js. The file doesn't exist though. If I add something to the mix.js() function the issue goes away. I don't need that function for this project though. I'm not having any errors because of it, I just wanted to let you know. 

### Steps To Reproduce:
In a fresh install of laravel 5.4 edit the webpack.mix.js file and comment out the mix.js function and just run mix.sass.
```
//mix.js('resources/assets/js/app.js', 'public/js')
   mix.sass('resources/assets/sass/app.scss', 'public/css');
```
Here is the contents of the mix-manifest.json file.
```
{
  "/mix.js": "/mix.js",
  "/css/app.css": "/css/app.css"
}
```

**Comment by JeffreyWay** [comment]
Webpack requires a JS entry point. If you don't provide one, we create a temporary entry and then delete the file after it compiles. So that's the mix.js file you're seeing.
