### ISSUE TITLE
Question: Versioning inconsistent between NPM and Github

### ISSUE THREAD

**Issue by sergeifilippov** [JeffreyWay/laravel-mix#574]
I'm getting confused here and maybe some one clear this up for me.

Why would is it that the version of `laravel-mix` on Github releases is `0.8.2` but on npm it's `0.8.8`?

---

This question come about because I saw a new method `mix.copyDirectory()` in the [docs](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/copying-files.md) but it can not be found in the master branch other than in [this](https://github.com/JeffreyWay/laravel-mix/commit/23a91bed6281bdbb54bb7eaebe55523b7f2c0265) commit.

**Comment by JeffreyWay** [comment]
You're looking at the master docs, not the docs for 0.8.2 or 0.8.8. The `copyDirectory` method is here: https://github.com/JeffreyWay/laravel-mix/blob/master/src/Api.js#L265-L267

You can use that method once we tag 0.9.0 later this week.
