### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by RomainGoncalves** [JeffreyWay/laravel-mix#576]
Hello,

I've started a barebones project. Only added laravel-mix. And I'm trying to get browser-sync to work for faster reload. But I can't seem to be able to connect to the page.

Here's the config:

```javascript
let mix = require('laravel-mix');

mix
  .sass('src/app.scss', 'public/css')
  .react('src/app.js', 'public/js')
  .browserSync('my-site.dev');
```

Knowing that "my-site.dev" is a totally random string, that I don't have Valet/Homestead setup for it.
I just want to be able to run that and get the page to reload each time I make a change and it rebuilds.

What am I missing?

Thanks for any help

**Comment by JeffreyWay** [comment]
Do you have an index.html file within your public directory? I just tested the entire process, and it reloaded properly with your config.

**Comment by RomainGoncalves** [comment]
Ah I don't. I put the index file at the root of the project. Let me check when I put it in public

**Comment by RomainGoncalves** [comment]
Ok I moved index.html to public folder, but still nothing loads. I see that the "site" is set, as Browsersync's debug page shows it to me. But the browser doesn't get there.

<img width="683" alt="screen shot 2017-03-16 at 16 07 14" src="https://cloud.githubusercontent.com/assets/1366477/24003258/4a9be9ac-0a63-11e7-8da5-e0a3f0cb66b8.png">

![screen shot 2017-03-16 at 16 08 01](https://cloud.githubusercontent.com/assets/1366477/24003298/5efa5c62-0a63-11e7-8a54-b3094d4c2a6c.png)


<img width="551" alt="screen shot 2017-03-16 at 16 07 31" src="https://cloud.githubusercontent.com/assets/1366477/24003324/6bf28778-0a63-11e7-8054-f7d2ff2d7059.png">


The build passes, I have no errors, just not loading...

**Comment by JeffreyWay** [comment]
Not sure, but I just confirmed that it's working. 

Make sure that my-site.dev actually loads your website.

**Comment by RomainGoncalves** [comment]
It doesn't.

**Comment by JeffreyWay** [comment]
Ah okay, so this isn't related to Mix at all. You can use something like Laravel Valet to quickly set up these custom domains, or you can Google how to look up a dev domain to a local website.

**Comment by RomainGoncalves** [comment]
hahaha. I've tried installing Valet this morning. Composer is squeaking. When I run composer global require laravel/valet, I get 1 error:

Your requirements could not be resolved to an installable set of packages.

and a list of illuminate/container version:

```
Problem 1
    - Conclusion: don't install laravel/valet v2.0.4
    - Conclusion: don't install laravel/valet v2.0.3
    - Conclusion: don't install laravel/valet v2.0.1
    - Conclusion: remove illuminate/container v4.2.9
    - Installation request for laravel/valet ^2.0 -> satisfiable by laravel/valet[v2.0.0, v2.0.1, v2.0.3, v2.0.4].
    - Conclusion: don't install illuminate/container v4.2.9
    - laravel/valet v2.0.0 requires illuminate/container ~5.1 -> satisfiable by illuminate/container[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.9].
    - Can only install one of: illuminate/container[v5.1.1, v4.2.9].
    - Can only install one of: illuminate/container[v5.1.13, v4.2.9].
    - Can only install one of: illuminate/container[v5.1.16, v4.2.9].
    - Can only install one of: illuminate/container[v5.1.2, v4.2.9].
    - Can only install one of: illuminate/container[v5.1.20, v4.2.9].
    - Can only install one of: illuminate/container[v5.1.22, v4.2.9].
    - Can only install one of: illuminate/container[v5.1.25, v4.2.9].
    - Can only install one of: illuminate/container[v5.1.28, v4.2.9].
    - Can only install one of: illuminate/container[v5.1.30, v4.2.9].
    - Can only install one of: illuminate/container[v5.1.31, v4.2.9].
    - Can only install one of: illuminate/container[v5.1.41, v4.2.9].
    - Can only install one of: illuminate/container[v5.1.6, v4.2.9].
    - Can only install one of: illuminate/container[v5.1.8, v4.2.9].
    - Can only install one of: illuminate/container[v5.2.0, v4.2.9].
    - Can only install one of: illuminate/container[v5.2.19, v4.2.9].
    - Can only install one of: illuminate/container[v5.2.21, v4.2.9].
    - Can only install one of: illuminate/container[v5.2.24, v4.2.9].
    - Can only install one of: illuminate/container[v5.2.25, v4.2.9].
    - Can only install one of: illuminate/container[v5.2.26, v4.2.9].
    - Can only install one of: illuminate/container[v5.2.27, v4.2.9].
    - Can only install one of: illuminate/container[v5.2.28, v4.2.9].
    - Can only install one of: illuminate/container[v5.2.31, v4.2.9].
    - Can only install one of: illuminate/container[v5.2.32, v4.2.9].
    - Can only install one of: illuminate/container[v5.2.37, v4.2.9].
    - Can only install one of: illuminate/container[v5.2.43, v4.2.9].
    - Can only install one of: illuminate/container[v5.2.45, v4.2.9].
    - Can only install one of: illuminate/container[v5.2.6, v4.2.9].
    - Can only install one of: illuminate/container[v5.2.7, v4.2.9].
    - Can only install one of: illuminate/container[v5.3.0, v4.2.9].
    - Can only install one of: illuminate/container[v5.3.16, v4.2.9].
    - Can only install one of: illuminate/container[v5.3.23, v4.2.9].
    - Can only install one of: illuminate/container[v5.3.4, v4.2.9].
    - Can only install one of: illuminate/container[v5.4.0, v4.2.9].
    - Can only install one of: illuminate/container[v5.4.13, v4.2.9].
    - Can only install one of: illuminate/container[v5.4.9, v4.2.9].
    - Installation request for illuminate/container (locked at v4.2.9) -> satisfiable by illuminate/container[v4.2.9].
```

Sorry if we are moving away from the initial issue.

**Comment by RomainGoncalves** [comment]
OK all good. I removed my ``
~/.composer`` folder. Installed Valet successfully. Parked valet at the right spot, and now everything works.

Thanks @JeffreyWay
