### ISSUE TITLE
How to enable Tree-shaking?

### ISSUE THREAD

**Issue by ricardovf** [JeffreyWay/laravel-mix#577]
First of all, congrats on the great work, for now it is all working (using vue and semantic-ui).

One question. Is Tree-shaking enabled by default? It does not seem like so, here. How do i enable it?

Here you say its supported: https://github.com/JeffreyWay/laravel-mix/blob/master/docs/mixjs.md

Thanks in advance!

**Comment by JeffreyWay** [comment]
Where supported, tree-shaking will take place automatically when you do `npm run production`.

**Comment by njbarrett** [comment]
@JeffreyWay could you elaborate a little on "where supported" ? Is it either a fully on or fully off feature? If I use one CommonJS module will that mean the whole project cannot be tree shaken?

Thanks 👍

**Comment by FrozenDroid** [comment]
@njbarrett @JeffreyWay I'd also like to know this.

**Comment by CaelanStewart** [comment]
This seems to be an issue still, @JeffreyWay . I'm using `2.1.11`.

For example:

`npm install gsap`

test-1.js:
```
import {CSSPlugin} from 'gsap/all';
```

`npm run production` gives a file size of: 178 kB

test-2.js:
```
import {CSSPlugin} from 'gsap/CSSPlugin';
```

`npm run production` gives a file size of: 71.1 kB

That's quite a difference.

Inside of `gsap/all` is the following:
```
/*!
 * VERSION: 2.0.1
 * DATE: 2018-05-30
 * UPDATES AND DOCS AT: http://greensock.com
 *
 * @license Copyright (c) 2008-2018, GreenSock. All rights reserved.
 * This work is subject to the terms at http://greensock.com/standard-license or for
 * Club GreenSock members, the software agreement that was issued with your membership.
 *
 * @author: Jack Doyle, jack@greensock.com
 **/
import TweenLite, {Ease, Power0, Power1, Power2, Power3, Power4, Linear, _gsScope} from "./TweenLite.js";

import TweenMax from "./TweenMaxBase.js";
import TimelineLite from "./TimelineLite.js";
import TimelineMax from "./TimelineMax.js";

// plugins
import AttrPlugin from "./AttrPlugin.js";
import BezierPlugin from "./BezierPlugin.js";
import ColorPropsPlugin from "./ColorPropsPlugin.js";
import CSSPlugin from "./CSSPlugin.js";
import CSSRulePlugin from "./CSSRulePlugin.js";
import DirectionalRotationPlugin from "./DirectionalRotationPlugin.js";
import EaselPlugin from "./EaselPlugin.js";
import EndArrayPlugin from "./EndArrayPlugin.js";
import ModifiersPlugin from "./ModifiersPlugin.js";
import PixiPlugin from "./PixiPlugin.js";
import RoundPropsPlugin from "./RoundPropsPlugin.js";
import ScrollToPlugin from "./ScrollToPlugin.js";
import TextPlugin from "./TextPlugin.js";


// utils
import Draggable from "./Draggable.js";

// easing
import {
	Back,
	Elastic,
	Bounce,
	RoughEase,
	SlowMo,
	SteppedEase,
	Circ,
	Expo,
	Sine,
	ExpoScaleEase
} from "./EasePack.js";

export {
	TweenLite,
	TweenMax,
	TimelineLite,
	TimelineMax,
	_gsScope,

	// plugins
	AttrPlugin,
	BezierPlugin,
	ColorPropsPlugin,
	CSSPlugin,
	CSSRulePlugin,
	DirectionalRotationPlugin,
	EaselPlugin,
	EndArrayPlugin,
	ModifiersPlugin,
	PixiPlugin,
	RoundPropsPlugin,
	ScrollToPlugin,
	TextPlugin,

	// utils
	Draggable,

	// easing
	Ease,
	Power0,
	Power1,
	Power2,
	Power3,
	Power4,
	Linear,
	Back,
	Elastic,
	Bounce,
	RoughEase,
	SlowMo,
	SteppedEase,
	Circ,
	Expo,
	Sine,
	ExpoScaleEase

};
```

So, from what I understand about tree shaking, my file size should be identical regardless of if I import from `gsap/all` or `gsap/CSSPlugin`.

Perhaps this is my misunderstanding of webpack (which is possible since I use laravel-mix specifically to avoid it).

Historically, I know that GSAP [had issues preventing tree shaking](https://github.com/greensock/GreenSock-JS/issues/170). But that seems to be [all](https://github.com/greensock/GreenSock-JS/issues/215) fixed [now](https://greensock.com/docs/NPMUsage).

Is there a problem with tree shaking, or am I doing something wrong?

Cheers!

**Comment by Linton-Samuel-Dawson** [comment]
I've tried `npm run prod` with and without tree shaking.
the size of bundle is bigger with tree shaking.I think it's not working with `npm run prod`.
am I doing anything wrong?
here is webpack.mix.js


       let mix = require('laravel-mix');
       const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
       mix.react('resources/assets/app', 'public/build/js')
      .sass('resources/assets/sass/app.scss', 'public/build/css');
      mix.webpackConfig({
       resolve: {
        modules: [
            path.resolve('./resources/assets'),
            path.resolve('./node_modules'),
        ]
    },

      module: {
        rules: [{
            test: [/\.js$/, /\.jsx$/],
            exclude: /node_modules/,
            use: {
                loader: 'babel-loader',
                options: {
                    presets: ['react', 'stage-2']
                }
            }
        },
        ]
    },
    plugins: [
        new BundleAnalyzerPlugin()
    ]
    });

**Comment by vedmant** [comment]
I'm also having some issues understanding tree shaking in my project, cause it doesn't look like it's working, any updates here?

**Comment by hackur** [comment]
Shouldn't this maybe be reopened? I just downloaded the latest laravel 6 and tried out tree shaking and it didn't seem to work out of the box.

**Comment by tonix-tuft** [comment]
It seems to me that GSAP 3 does some stuff under the hood to prevent tree shaking of `CSSPlugin`  and `gsap-core`. I opened an issue here: https://github.com/greensock/GSAP/issues/374 .
