### ISSUE TITLE
Feature Request: Ability to disable mix-manifest.json generation.

### ISSUE THREAD

**Issue by sergeifilippov** [JeffreyWay/laravel-mix#580]
Add ability to disable `mix-manifest.json` generation when using `laravel-mix` in non laravel projects.

It's a pain having to add extra tasks to remove the file all the time.

Possible syntax `mix..version().disable()`

**Comment by JeffreyWay** [comment]
Why do you need to remove that file?

**Comment by jerguslejko** [comment]
👍 I'm using mix outside Laravel and I have no use for the file. I'd great if we could just disable it's creation.

**Comment by sergeifilippov** [comment]
I'm using `laravel-mix` with the following frameworks/products:

- magento
- shopify

The manifest file is nuisance more than anything, hence low priority to this request.

This could be one of those tasks to do when you're having an off day and just need a quick win to get your on track. 👍  😄

**Comment by JeffreyWay** [comment]
You guys could update your npm script to `rm public/mix-manifest.json` after you trigger Webpack.

**Comment by jerguslejko** [comment]
....

**Comment by tditlu** [comment]
Had the same problem, so I created and added this to my webpack.mix.js:

```
// Disable mix-manifest.json
(function(StatsWriterPlugin) {
  if (!StatsWriterPlugin) {
    return;
  }

  mix.plugins['StatsWriterPlugin'] = function(opts) {
    if (opts.filename === 'mix-manifest.json') {
      return {
        apply: function() {}
      };
    }
    return new StatsWriterPlugin(opts);
  };
}(mix.plugins['StatsWriterPlugin']));
```

**Comment by Daniel15** [comment]
> I'm using mix outside Laravel and I have no use for the file

It's not specific to Laravel. It's a manifest that contains the names of the CSS and JS files, including a cache buster (https://www.npmjs.com/package/webpack-manifest-plugin). Most sites that use Webpack would be using it, unless you're also using some other CSS/JS combination/minification pipeline that does its own versioning.

**Comment by impeto** [comment]
This may be like beating a dead horse, but I'm using mix with the electron framework... it's not a problem, but it annoying 👎

**Comment by zarkin404** [comment]
Add these codes to webpack.mix.js:

```
// Disable mix-manifest.json
Mix.manifest.refresh = _ => void 0
```

**Comment by the-alex-mark** [comment]
> Add these codes to webpack.mix.js:
> 
> ```
> // Disable mix-manifest.json
> Mix.manifest.refresh = _ => void 0
> ```

Deprecated symbol used, consult docs for better alternative
