### ISSUE TITLE
[Suggestion] webpack md5 hash alternative

### ISSUE THREAD

**Issue by wppd** [JeffreyWay/laravel-mix#581]
please refer to this issue https://github.com/erm0l0v/webpack-md5-hash/issues/7 

it's not a reliable way for long term caching.

may want to consider other alternatives.

maybe this one

https://webpack.js.org/guides/caching/#deterministic-hashes

**Comment by tillkruss** [comment]
Using `HashedModuleIdsPlugin` doesn't fix the `Cannot read property 'call' of undefined` bug for me. There seems to be a solution in https://github.com/webpack/webpack/issues/4445.

**Comment by JeffreyWay** [comment]
@wppd This is done in 0e8e32d32d60f1f983a8a7bd1273c7962d45b095.
