### ISSUE TITLE
Compiling for Laravel mail themes use case

### ISSUE THREAD

**Issue by aHxShUM** [JeffreyWay/laravel-mix#583]
### Description:
As to make email match with the theme, mail/html/themes is compiled from Laravel-mix.
But if versioning is enabled, I cannot find an option to exclude the theme asset.

**Comment by JeffreyWay** [comment]
This is far too vague for me to understand and help.

**Comment by aHxShUM** [comment]
Sorry for being too rough.

In `webpacke.mix.js`
```javascript
mix.js('resources/assets/js/app.js', 'public/js/')
  .sass('resources/assets/sass/app.scss', 'public/css/')
  .sass('resources/assets/sass/mail/custom.scss', '../resources/views/vendor/mail/html/themes/')

if (mix.config.inProduction) {
  mix.version();
}
```

The `custom.css` is hashed when `npm run production` and therefore, I am looking for an option for excluding from `mix.version()`.
