### ISSUE TITLE
Remove jQuery autoloader

### ISSUE THREAD

**Issue by richardsweeney** [JeffreyWay/laravel-mix#585]
Mix is AMAZEBALLS! Such a simple, yet powerful api. A massive thanks to you Jeffrey for the resource!

I'm trying to use mix for WordPress dev where jQuery is (almost) always loaded in the frontend.

I'd very much like to remove the autoloader for jQuery which is found in `webpack.config.js` but I can't quite figure out if this is possible to do in `webpack.mix.js`.

I realize I can just remove the lines below, but I'd ideally like to avoid that if at all possible.

    new webpack.ProvidePlugin(Mix.autoload || {
        jQuery: 'jquery',
        $: 'jquery',
        jquery: 'jquery'
    }),

laravel-mix v. 0.8.8
npm v. 4.1.2

**Comment by devcircus** [comment]
Looks like that plugin first looks for mix.autoload before it loads jquery. So would it be possible to just add mix.autoload({}) to your mix.js file to prevent this?
```
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .autoload({});
```
I haven't tested this, just thought it may work.

**Comment by JeffreyWay** [comment]
Yeah you can do `mix.autoload({})`, but I think we might still want to remove the jQuery reference entirely.

**Comment by richardsweeney** [comment]
Many thanks!
