### ISSUE TITLE
Export default in ES6 isn't working with laravel mix

### ISSUE THREAD

**Issue by darkylmnx** [JeffreyWay/laravel-mix#586]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`): v6.9.2
- NPM Version (`npm -v`): 3.10.9
- OS: windows

### Description:
When doing "npm run dev" i get a syntax error because i think the full es6 is not enabled like when using Vue(s webpack template.

Syntax Error: Unexpected token (6:0)
  5 |
> 6 | export default {
    | ^
  7 |     testFunc() {
  8 |         return true
  9 |     },

### Steps To Reproduce:

- create a file, say : test.js
- inside this file just do a simple : export default { prop: 'value' }
- inside app.js do : 
```
 import Vue from 'vue'
import test from './test'

const app = new Vue({
    el: '#app'
});
```

And weird thing to vue seems to be loaded globally whereas i want to use Vue within webpack and without the compiler (just Vue with render functions)

**Comment by JeffreyWay** [comment]
You can definitely do export default with Mix. I do it in all of my projects.

Do you have a custom .babelrc file in your project root by any chance?

**Comment by darkylmnx** [comment]
Nope I just used a fresh install

**Comment by JeffreyWay** [comment]
I just followed your instructions exactly, and everything compiled properly.

**Comment by darkylmnx** [comment]
@JeffreyWay after multiple tests, it seems the problem wasn't at all at this line though the console said it was, so yeah the export works fine.
