### ISSUE TITLE
Combining stylesheets it not working

### ISSUE THREAD

**Issue by bandicsongor** [JeffreyWay/laravel-mix#587]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`): 6.10.0
- NPM Version (`npm -v`): 4.4.1
- OS: Win 8.1

### Description:
Combining plain css files not working as described in [Laravel documentation](https://laravel.com/docs/5.4/mix#plain-css). The 'npm run dev' executes with success but the output file is not generated.

Thanks a lot!

### Steps To Reproduce:
1. Create files:
resources/theme/style1.css
resources/theme/style2.css
resources/theme/style3.css
2. Content of webpack.mix.js:
mix
    .js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .styles([
        'resources/theme/style1.css',
        'resources/theme/style2.css',
        'resources/theme/style3.css'
    ], 'public/css/theme.css');
3. Exec `npm run dev`
4. The command executes with success but the 'public/css/theme.css' is not generated.

**Comment by bandicsongor** [comment]
Everything it's ok! The only problem is that the file is not showing in final report (compiled files list).

**Comment by vrajroham** [comment]
@bandicsongor Do you got any solution on file not showing problem?

**Comment by bandicsongor** [comment]
I think mix.styles() generate some static things, it runs only once when you execute `npm run dev` / `npm run watch`. 
My solution was:
- I've mad a sass file with some @imports, for my example:
~ theme.scss ~
@import style1.css
@import style2.css
@import style3.css
- I've add `mix.sass('resources/assets/sass/theme.scss', 'public/css');` to the webpack.mix.js
This way if you execute `npm dev watch` than files will be generated for every modification.

_PS1: You need to do some nodeJs workarounds to generate the valid output files like: you have to remove '@charset ...' from imported files and add only once to main theme.scss; you have to add some aliases if files are in different folders. I'm not a nodeJs and Sass expert so I'm not sure that my script is the best but it's working :) If you do not succeed I can give as example._

_PS2: Sorry for my English :)_

**Comment by vrajroham** [comment]
@bandicsongor  thanks! your solution works in my case.
