### ISSUE TITLE
watch for copy images with subfolders

### ISSUE THREAD

**Issue by MichalKrakow** [JeffreyWay/laravel-mix#588]
Well, i'm not really sure is this an issue or me doing sometging wrong. 

Expected behaviour wold be that with:
`Mix.copy('resources/assets/images', 'public/images', false);`
files will be watched and copied.

But that's only the case for resources/assets/images and not for resources/assets/images/subfolder .

The copy works fine so any change to images root will trigger copying all tree structure but there's no watch for subfolders.

**Comment by ankurk91** [comment]
@MichalKrakow 

Try this -

```js
Mix.copy('resources/assets/images/**/*', 'public/images', false);
``

**Comment by MichalKrakow** [comment]
Thank's for reply.
This is not a gulp so it's not gonna work. 
I've tested anyway and the result is all path so - all resources copied into images directory.

Still no watch on subfolders.

**Comment by MichalKrakow** [comment]
Ok, so it only watches for files that i actually use in blade template or css. No need to change anything. 
You need to reference it with `{{ URL::asset('/images/subfolder/file.png' )}}` in your template, but not in css - what probably made me confused.

**Comment by pablopaul** [comment]
@MichalKrakow does it really watch in Blade templates for files you are including via

`{{ URL::asset('/images/subfolder/file.png' )}}`

and versions them?

**Comment by MichalKrakow** [comment]
With this included mix copied image from src to dst, still without versioning.

**Comment by yathu** [comment]
@MichalKrakow it's works fine for me `mix.copy('resources/img', 'public/img')`. 
Try this, it is possible to keep a hierarchical structure (like Gulp).

`mix.copyWatched(
    'resources/images/**/*.{jpg,jpeg,png,gif}',
    'public/images',
    { base: 'resources/images' }
);`
