### ISSUE TITLE
file combined with Mix.combine() does not exist on dev-server while running HMR

### ISSUE THREAD

**Issue by mohitpanjwani** [JeffreyWay/laravel-mix#589]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`): v6.8.0
- NPM Version (`npm -v`): v3.10.8
- OS: El Capitan

### Description:
I am actually forced to use laravel's `mix` function because the combined js file does get versioned but its not included on the HMR server.

So I can use laravel's `asset()` while working locally with HMR and that would work but I will be forced to use `mix()` function again when deploying code for production with versioning.

Also its a not valid solution for an end-product which I resale to other developers.

<img width="810" alt="d70468ef6f8dbd7630493ae17e2f31e8" src="https://cloud.githubusercontent.com/assets/8002555/24078704/fb92102c-0c9a-11e7-9786-f0eb6e42e6ee.png">

Please help out if you can! Thanks

### Steps To Reproduce:
webpack.mix.js
```
mix.combine([
    pluginPath + 'jquery/jquery.js',
    pluginPath + 'bootstrap/tether.js',
    pluginPath + 'bootstrap/bootstrap.js',
],'public/assets/js/core/plugins.js')
```

app.blade.php
```
<script type="text/javascript" src="{{mix('/assets/js/core/plugins.js')}}"></script>
```

**Comment by bvangraafeiland** [comment]
Same issue here. I can either disable versioning and use `asset` instead of `mix` for the combined file, or not use HMR.

**Comment by shane-scalable** [comment]
Same here,  I can use the mix.js or mix.sass methods but when i use mix.combine it acts as if the combine statements aren't even there and no file (or error) is generated in reference to the combine.

I am not very experienced with Node and am not setup to debug into webpack.js file to see where the issue is.

````
mix.js('resources/assets/js/app.js', 'js/'); // <-- works
mix.combine(['influencer.js', 'product-search.js'], 'public/js/products.js'); // <-- Doesn't create products.js (I have tried adjusting the paths)
mix.combine(['resources/assets/sass/influencer.scss', 'resources/assets/sass/admin.scss'], 'css/combined.css'); // <-- Doesn't create combined.css (I have tried adjusting the paths)
mix.sass('resources/assets/sass/influencer.scss', 'css/') // <-- works
    .sass('resources/assets/sass/manager.scss', 'css/') // <-- works
    .sass('resources/assets/sass/app.scss', 'css/') // <-- works
    .sass('resources/assets/sass/af.scss', 'css/') // <-- works
    .sass('resources/assets/sass/homepage.scss', 'css/') // <-- works
    .sass('resources/assets/sass/admin.scss', 'css/'); // <-- works
````
