### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by Bram-Zijp** [JeffreyWay/laravel-mix#59]
On 'npm run hmr' I get the error 'Cannot GET /'  when visiting localhost:8080 . It also can't find <script src="http://localhost:8080/js/app.js"></script> in Laravel 5.3. I also get this error when working with other webpack builds in both Wamp & Homestead Laravel environments.

**Comment by lukepolo** [comment]
Thats perfect for visiting `localhost:8080` as it should not find anything, now for the `http://localhost:8080/js/app.js` that should be working . If your using vagrant you will have to proxy it
