### ISSUE TITLE
Feature Request: regex file matching

### ISSUE THREAD

**Issue by Micaso** [JeffreyWay/laravel-mix#590]
it would be nice if we can do things like mix.js('path/to/my/modules/MATCH_ANYTHING/fileExistInEachModule.js');

this would be shorthand for:
mix.js('path/to/my/modules/module1/fileExistInEachModule.js');
mix.js('path/to/my/modules/module2/fileExistInEachModule.js');
....

**Comment by JeffreyWay** [comment]
I don't think that's a good pattern to use for Webpack builds. You should have one or two entry points at most.

**Comment by rogervila** [comment]
Could it be implemented as an optional package? 
For multitennant projects it would be a nice feature.

**Comment by mas-iota** [comment]
> I don't think that's a good pattern to use for Webpack builds. You should have one or two entry points at most.

What if am combining multiple js files into one entry point, e.g:
```
mix.js([
  'resources/assets/js/file.js',
  'resources/assets/js/file2.js',
], 'public/js/app.js').version();
```

Also for Scss see how it's done currently:
```
mix.sass('resources/assets/sass/skin-black.scss', 'public/css');
mix.sass('resources/assets/sass/playwin.scss', 'public/css');
mix.sass('resources/assets/sass/login.scss', 'public/css');
mix.sass('resources/assets/sass/loading.scss', 'public/css');
```
