### ISSUE TITLE
SASS files always trigger even updates only on js file

### ISSUE THREAD

**Issue by iainheng** [JeffreyWay/laravel-mix#591]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`):  6.9.4
- NPM Version (`npm -v`):  4.1.1
- OS: Windows 10

### Description:
I was editing my js file `order.js` and I have watch running `npm run watch` and I noticed that my `scss` files are compiled even I was only changing `order.js`. 

![image](https://cloud.githubusercontent.com/assets/3263759/24093862/f4641bdc-0d90-11e7-99b0-163d088f3bc9.png)

This is how my webpack.mix.js looks like now:
```
mix.sass('./resources/assets/sass/backend/app.scss', 'css/app.backend.css');
mix.sass('./resources/assets/sass/backend/app.dialog.scss', 'css/dialog.backend.css');
mix.sass('./resources/assets/sass/backend/app.editor.scss', 'css/editor.backend.css');

---

mix.js(['./resources/assets/js/backend/order.js'], 'js/order.js');

mix.sourceMaps();
mix.version();
```

Not sure if this is normal behavior or any miss configurations on my side. Any advice is very much appreciated.

**Comment by JeffreyWay** [comment]
It's because the CSS is being extracted from the JS file. But I want to figure out a solution for this soon.

**Comment by iainheng** [comment]
Understood. Thanks for the explanation. 👍
