### ISSUE TITLE
Mix incompatible with Webpack 2.3.0?

### ISSUE THREAD

**Issue by voydz** [JeffreyWay/laravel-mix#595]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`): 7.6.0
- NPM Version (`npm -v`): 4.3.0
- Yarn Version: 0.21.3
- OS: Mac (Sierra)

### Description:

It seems that mix is incompatible with the 2.3.0 release of webpack. I ran a `yarn install --force` to clean up my obsolete dependencies, which behind the curtains upgraded webpack to version 2.3.0
(just released a few minutes ago, https://github.com/webpack/webpack/releases/tag/v2.3.0).

**The real problem is, that every fresh installation of mix will not work without rolling webpack back to a 2.2.x version (See reproduce steps).**

### Steps To Reproduce:

1. Take a fresh laravel (mix) project
2. `yarn install`
3. `node node_modules/webpack/bin/webpack.js -v` should return `2.3.0`
4. `npm run dev`
5. Fails with error: 
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "public" is not an absolute path!
```

**Comment by sebestenyb** [comment]
Second this, had to lock webpack to 2.2.1:

```
    "devDependencies": {
       ...
       "webpack": "2.2.1",
       "laravel-mix": "^0.8.1",
       ...
    }
```

**Comment by orrd** [comment]
For anyone else wondering how to take advantage of that fix, you can edit your package.json and make sure your larave-mix version is 0.10 or higher:

      "laravel-mix": "^0.10.0",

Then run npm update.

**Comment by PenAndPapers** [comment]
adding **"laravel-mix": "^0.10.0"**  in package,json file fix the issue on my end

**Comment by Hasgaroth** [comment]
@orrd this worked for me - thanks!
@JeffreyWay - thanks for all the great work 😄

**Comment by giviz** [comment]
@orrd Thanks, you saved my day :)

**Comment by ruchern** [comment]
@ibanjo You might want to try `v1.0.3` now.

**Comment by odera89** [comment]
Thank you, @orrd
using "laravel-mix": "^0.10.0", in package.json saved my day too. :) 👍

**Comment by codemt** [comment]
Same here , this solved my issue too 👍
