### ISSUE TITLE
hmr in windows dosnt work in 0.8.9

### ISSUE THREAD

**Issue by kpilard** [JeffreyWay/laravel-mix#599]
- Laravel Mix Version: 0.8.9
- Node Version (`node -v`):  7.4.0
- NPM Version (`npm -v`): 4.4.1
- OS: Windows 10

### Description:
`npm run hot` doesn't work in windows anymore.  I'm opening `localhost:8080/js/app.js` and get the response `Cannot GET /js/app.js`. #78
It works in 0.8.8 but not in 0.8.8. Is the problem maybe in c3da413

**Comment by vutrungduc7593** [comment]
Check your webpack.mix.js file. 
Try to remove 'public' word. It work on Laravel Mix v0.9.2, Windows 10
ex:
Change .js(['resources/assets/js/app.js'], 'public/js/app.js') to 
.js(['resources/assets/js/app.js'], 'js/app.js')

**Comment by vutrungduc7593** [comment]
I fixed it in laravel-mix 0.9.2, windows 10, follow below steps:
1. Remove 'public' from path in webpack.mix.js. Ex: .js(['resources/assets/js/app.js'], 'public/js/app.js') to .js(['resources/assets/js/app.js'], 'js/app.js')

2. Add below lines to webpack.mix.js:
mix.webpackConfig({
  output: {
    publicPath: 'http://localhost:8080/'
  }
})

I added slash to end of 'http://localhost:8080'

**Comment by kpilard** [comment]
Hey thank you this works for me. 

@JeffreyWay if you see this as an workaround, feel free to open the issue again :)

**Comment by Gimcrack** [comment]
Removing public from webpack.mix.js fixed it for me. Thanks @vutrungduc7593!
