### ISSUE TITLE
Output path of mix.js()

### ISSUE THREAD

**Issue by Robert-Jan** [JeffreyWay/laravel-mix#6]
First of all... Awesome work! Runs a lot faster then gulp.

But i have a problem, here is my mix file:
```
mix.js('./JS/default.js', '../Assets/js/default.js')
   .sass('./SASS/default.scss', '../Assets/css/default.css');
```

This is the result from the terminal:
```
.Assets/js/default.js 2.74 kB 0 [emitted] app
../Assets/css/default.css 461 bytes 0 [emitted] app
```

As you can see. The path for SASS works as expected but the JS path removes one dot and slash.

**Comment by Robert-Jan** [comment]
In addition: Is there a variable where i can set the output path for every function?

**Comment by JeffreyWay** [comment]
Would you mind updating to the latest version of Laravel Mix (including the webpack.config.js) file, and letting me know if this is still an issue?

**Comment by assertchris** [comment]
This may be related to https://github.com/JeffreyWay/laravel-mix/issues/27
