### ISSUE TITLE
Mix versioning helper function will be made available for 5.1 LTS projects ?

### ISSUE THREAD

**Issue by unitedworx** [JeffreyWay/laravel-mix#60]
I am already using webpack and gulp with the latest elixir on 5.1 LTS so moving to mix should be fairly easy to take advantage of hmr and library code splitting!

However I am versioning my js and css files which rely on the elixir global Function to grab the respective file. 

As i understand the equivalent mix function will be available in laravel 5.4. Will this function be made available to install in 5.1 LTS so we can take advantage of mix in laravel projects prior to 5.4?

**Comment by TNovalis** [comment]
To get Laravel Mix versioning (and subsequently HMR) working for Laravel 5.1 you will need to add the following helper.

```php 
function mix($path, $json = false, $shouldHotReload = false)
{
    if (! $json) static $json;
    if (! $shouldHotReload) static $shouldHotReload;

    if (! $json) {
        $manifestPath = storage_path('framework/cache/Mix.json');
        $shouldHotReload = file_exists(storage_path('framework/cache/hot'));

        if (! file_exists($manifestPath)) {
            throw new Exception(
                'The Laravel Mix manifest file does not exist. ' .
                'Please run "npm run webpack" and try again.'
            );
        }

        $json = json_decode(file_get_contents($manifestPath), true);
    }

    $path = collect($json['assetsByChunkName'])
        ->flatten()
        ->first(function ($compiledFile) use ($path, $json) {
            $compiledFile = trim(str_replace($json['hash'].'.', '', $compiledFile), '/');

            return $compiledFile === trim($path, '/');
        });

    return $shouldHotReload ? "http://localhost:8080{$path}" : url($path);
}
```

**Comment by JeffreyWay** [comment]
That function will likely be tweaked and added to Laravel 5.4, once it is released.

**Comment by unitedworx** [comment]
Many thanks Jeffry, will make sure to grab a copy of this function again from laravel 5.4 once its released.
