### ISSUE TITLE
0.9.0 compiles but fails to load site with errors

### ISSUE THREAD

**Issue by VinceG** [JeffreyWay/laravel-mix#601]
- Laravel Mix Version: 0.9.0
- Node Version 6.10.0 
- NPM Version 4.2.0 
- OS: Mac OS

### Description:

It seems that 0.8.8 worked fine, upgrading to 0.9.0 now shows an error when viewing the Vue based website.

npm run dev works in both cases and creates the files (manifest, vendor and app) however when visiting the website it returns an error as if jQuery is not loaded.

I saw the note regarding the mix.autoload and i've tried adding that too with the same result.

since our webpack.mix.js is too long i'll include the extract of the actual mix.js and extract methods:

```
mix.js('modules/WMA/Assets/wma/application/js/app.js', 'public/modules/wma/build/js')
    .extract(['jquery', 'vue', 'bootstrap-sass', 'lodash', 'axios', 'moment', 'vue-router',
            'timecircles/inc/TimeCircles.js', 'jcarousel/dist/jquery.jcarousel.js', 'vue-scrollTo',
            'jquery.easing/js/jquery.easing.js', 'ui-to-top/js/jquery.ui.totop.js', 'vue-strap', 'vee-validate',
            'vue-cookie', 'vue-meta', 'jquery-popup-overlay/jquery.popupoverlay.js',
            'bootstrap3-typeahead/bootstrap3-typeahead.js']);
```

as i said, i compiles down fine and the files are created, when visiting the site it shows the following error:

![screen shot 2017-03-22 at 10 55 18 am](https://cloud.githubusercontent.com/assets/195199/24212957/2d06837c-0eee-11e7-8e16-9f97b3ac4580.png)

### Steps To Reproduce:

Since this is specific to a use case we have i can't really provide steps to reproduce to any setup. However, if you just use 0.8.8 and have the above code and then use 0.9.0 it should compile down in both cases but fail to load when visiting the actual site.

**Comment by JeffreyWay** [comment]
I'm thinking it could be related to the autoloading update. Check the release notes.

https://github.com/JeffreyWay/laravel-mix/releases

Can you try adding this to your webpack.mix.js file?

```js
mix.autoload({
   jquery: ['$', 'window.jQuery']
});
```

**Comment by JeffreyWay** [comment]
I'm pretty sure that it's related to the autoloading change. So you did add this to your webpack.mix.js file?

```js
mix.autoload({
   jquery: ['$', 'window.jQuery']
});
```

**Comment by VinceG** [comment]
Yes, i'll include it here with some reduction since our webpack.mix.js is long

```
const { mix } = require('laravel-mix');
var glob_entries = require('webpack-glob-entries');
var argv = require('yargs').argv;

mix.disableNotifications();

module.exports.devServer = 'errors-only';

var skipCombine = typeof(argv.env) != 'undefined' && typeof(argv.env.nocombine) != 'undefined' && argv.env.nocombine;

var config = {
 resolve: {
   modules: ["node_modules", "resources/assets/bower"]
 }
};

if(mix.config.inProduction) {
 config.performance = {
   maxAssetSize: 1000000,
   maxEntrypointSize: 2500000,
   hints: 'warning'
 }
}

mix.webpackConfig(config);

mix.autoload({
   jquery: ['$', 'window.jQuery']
});

if(!skipCombine) {

   // js awards|voting vendor
   mix.combine([
       "public/vendor/app/bower/jquery/dist/jquery.min.js",
       "public/vendor/app/bower/jquery-ui/jquery-ui.min.js",
       "public/vendor/app/bower/bootstrap/dist/js/bootstrap.min.js",
       "public/vendor/app/bower/handlebars/handlebars.js",
       "public/modules/awards/js/awards/jquery.scrollTo.min.js",
       "public/modules/awards/js/awards/jquery.nav.js",
       "public/modules/awards/js/awards/shadowbox/shadowbox.js",
   ], 'public/modules/awards/js/voting/vendor.js');

// .... more combines....


   // Copy all contents
   mix.copy('public/modules/admin', 'public/build/modules/admin');
   // Copy contents of the img folder to come above the CSS folder
   mix.copy('public/modules/admin/avn/css/img', 'public/build/modules/admin/img');
}

 /**
  * Webmaster Access
  *
  */
  mix.js('modules/WMA/Assets/wma/application/js/app.js', 'public/modules/wma/build/js')
    .extract(['jquery', 'vue', 'bootstrap-sass', 'lodash', 'axios', 'moment', 'vue-router',
            'timecircles/inc/TimeCircles.js', 'jcarousel/dist/jquery.jcarousel.js', 'vue-scrollTo',
            'jquery.easing/js/jquery.easing.js', 'ui-to-top/js/jquery.ui.totop.js', 'vue-strap', 'vee-validate',
            'vue-cookie', 'vue-meta', 'jquery-popup-overlay/jquery.popupoverlay.js',
            'bootstrap3-typeahead/bootstrap3-typeahead.js']);
    //.sass('modules/WMA/Assets/wma/application/sass/app.scss', 'public/modules/wma/build/css');

  //mix.js('modules/Ads/Assets/server/app.js', 'public/modules/ads/build');
  // .extract(['axios'], 'public/modules/ads/build');


  if (mix.config.inProduction) {
      mix.version();
  }

```

**Comment by VinceG** [comment]
@JeffreyWay Another issue with laravel mix we are having is the fact that we can only have one webpack.mix.js file. it's hardcoded in the Paths.js file and there is no way to specify the build script.

We have one application running multiple sites (currently 4) and each has it's own assets and build process, having the ability to specify the build script (ie webpack.mix.js) for each one is paramount for us. 

Will you consider a PR of such sort if i submitted one? by default it'll use webpack.mis.js but you can specify a different file using an export or an option?

Thank You.

**Comment by VinceG** [comment]
I've created a repository that recreates this issue

https://github.com/VinceG/laravel-mix-issue

**Comment by JeffreyWay** [comment]
@VinceG So I downloaded your repo, and then install laravel-mix@0.8.9...but that doesn't work either. So are you positive that this was working before the upgrade to 0.9.0?

**Comment by VinceG** [comment]
Yes 100%. if you set 

```
"laravel-mix": "0.8.9",
"webpack": "2.2.1"
```

in the package.json file run npm update and then npm run dev
there are no errors.

Make sure to also comment out 

```
// mix.autoload({
//    jquery: ['$', 'window.jQuery']
// });
```

it seems that's the issue the code above.

**Comment by JeffreyWay** [comment]
What if you use: 

```js
mix.autoload({
   jquery: ['$', 'window.jQuery', 'jQuery']
});
```

**Comment by VinceG** [comment]
@JeffreyWay That worked.

**Comment by VinceG** [comment]
@JeffreyWay Thank You Jeffery!

Will it be possible to get your feedback regarding the comment above

https://github.com/JeffreyWay/laravel-mix/issues/601#issuecomment-288493817

I can submit a PR if this is something you'll consider.

Thanks Again.
