### ISSUE TITLE
Feature request, add option to delete old version of file when using version()

### ISSUE THREAD

**Issue by whoacowboy** [JeffreyWay/laravel-mix#602]
This is more of a feature request than an issue, but it does slow me down. 

I'd like to see the option to delete the previous file when using `mix.version()`

```
if (mix.config.inProduction) {
  mix.version({delete: true});
}
```

**Comment by JeffreyWay** [comment]
It already does that, as long as the old file name is in your mix-manifest.json file.

**Comment by whoacowboy** [comment]
OK, I was moving around dev machines, so that was probably it. Thanks, great tool.
