### ISSUE TITLE
0.9.1 - chunks didn't deleted

### ISSUE THREAD

**Issue by pixieaka** [JeffreyWay/laravel-mix#605]
First I run { npm run watch }
Then { npm run production }

The result it didn't delete previous chunk.

I guess we must track chunks in { mix-manifest.json } for better results.

![capture](https://cloud.githubusercontent.com/assets/17777237/24216847/6d0fb616-0f46-11e7-928f-257a4a037f6f.JPG)

**Comment by adiachenko** [comment]
Yeah, I briefly mentioned this in #567 before async chunk loading have been fixed.

Not sure if it's something that can be quickly addressed so for anyone concerned can circumvent the issue by versioning assets in production only:

```
if (mix.config.inProduction) mix.version()
```

**Comment by pixieaka** [comment]
Another thing I just noticed 
[ setResourceRoot ] Setting in { webpack.mix.js } Is not applied for chunks URL when it loaded instead it load from base URL.

**Comment by JeffreyWay** [comment]
Undeleted chunks is now fixed in Mix 1.0+.

**Comment by pixieaka** [comment]
I use now version 1.2.2

1- is not issue but it weird behavior the chucks save in public folder directly not in {{public/js}} folder

2- i just try it but in one case it didn't delete chunk unfortunately

when try this
Vue.component('example2', resolve => require(['./components/example2.vue'], resolve));
it make 0.js in public folder
and when i watch it it going very good and replace it very well

{{ BUT THE PROBLEM HERE }} 
when i change the line with
Vue.component('example2', require('./components/example2.vue'));
it didn't realize it no more chunks and it didn't delete 0.js 

we can delete all chunks before run npm automatically 

Great work ,, all the best to make it better ;) @JeffreyWay
