### ISSUE TITLE
Has setPublicPath gone on 0.9.0 and above?

### ISSUE THREAD

**Issue by edcs** [JeffreyWay/laravel-mix#606]
- Laravel Mix Version: 0.9.0 (`npm list --depth=0`)
- Node Version (`node -v`): 7.4.0
- NPM Version (`npm -v`): 4.0.5
- OS: macOS

### Description:

Has `mix.setPublicPath('path/to/public')` been removed from the API in version v0.9.0 and above? I've just upgraded and my build broke - looking through the source I've noticed that `publicPath` is an option and have set that which has fixed my problems.

I thought I'd raise this issue, and if it has been removed I'll create a PR updating the documentation as it still speaks about `setPublicPath()`. However, if I'm doing something wrong please could someone advise?

### Steps To Reproduce:

This was my pre-0.9.0 config which worked just fine:

```javascript
laravelMix
    .setPublicPath('../../../public')
    .js('js/app.js', '/js/app.js')
    .sass('scss/app.scss', '/css/app.css')
    .browserSync({
        proxy: 'www.site.dev',
        files: ['**/*.html', '**/*.scss', '**/*.js']
    })
    .sourceMaps()
    .version();
```

This is what I had to change to in order to get it working after upgrading to 0.9.0:

```javascript
laravelMix
    .js('js/app.js', '/js/app.js')
    .sass('scss/app.scss', '/css/app.css')
    .browserSync('www.site.dev')
    .options({
        publicPath: '../../../public'
    })
    .sourceMaps()
    .version();
```

**Comment by JeffreyWay** [comment]
Just a small regression. Can you npm upgrade to 0.9.2?
