### ISSUE TITLE
manifest.json file is not created if multiple .js calls are present

### ISSUE THREAD

**Issue by VinceG** [JeffreyWay/laravel-mix#607]
- Laravel Mix Version: 0.9.0
- Node Version 6.10.0 
- NPM Version 4.2.0 
- OS: Mac

### Description:

It seems if we have more than one .js() call with extract([...], 'dist/vendor.js') the manifest file is only generated once.

### Steps To Reproduce:

See this repository as an example to reproduce the issue

https://github.com/VinceG/laravel-mix-issue-manifest

run npm run dev

what will happen dist/ folder will not have the manifest.js file dist2/ will.

mix-manifest.json file will only have one instance (dist2/manifest.js).

This came up when we used mix() in laravel to load the appropriate js file from the build folder, since only the last call to extract has the manifest anything before that will result in an error.

Unable to locate Mix file: /modules/wma/build/js/manifest.js. Please check your webpack.mix.js 

the above repository just calls the manifest.js file as is, but it demonstrates the issue.

**Comment by pix2D** [comment]
Having the same issue. Even though https://github.com/JeffreyWay/laravel-mix/pull/609 allows for a workaround via separate mix files it would be nice if it worked without having to resort to that. :)

**Comment by ultrasamad** [comment]
@VinceG A rather similar issue I'm facing is `manifest.js` and `vendor.js` will not be created when I do multiple calls to js. The *manifest* and *vendor* files will be created for the first js in the mix file, but the remaining js will not.
