### ISSUE TITLE
Webpack hot middleware

### ISSUE THREAD

**Issue by stephan-v** [JeffreyWay/laravel-mix#611]
In the full Vue webpack CLI setup I see that there is a webpack-hot-module client overlay available when you run the server. Would it also be possible to integrate something like this into laravel-mix as an option?

I find it incredibly useful to have these messages pop up in chrome so I do not have to tab, use a shortcut to open my terminal or constantly have my terminal open on a second monitor to watch my build status.

Notifications are ok but they just do not work well. Not on Ubuntu, OSX or any system. They lag and they are not responsive when you make a lot of small changes in a row.

If there is an easy way to currently add this, I would be much helped as well. In the meantime I will try and dig a little bit deeper into this since I am not familiar with that package and all of it's options.

Hopefully it is ok to post such a  suggestion here, let me know otherwise.

![image](https://cloud.githubusercontent.com/assets/2384912/24240212/1528cc2e-0fb1-11e7-855e-7e52745d36be.png)

HTML:

![image](https://cloud.githubusercontent.com/assets/2384912/24240418/d20f99c6-0fb1-11e7-8fd8-24d4e42e9674.png)

**Comment by hinaloe** [comment]
(You can use overlay option. but I think it should can use more easy too.)

```js
mix.webpackConfig({
        devServer: {
            overlay: true,
        },
    })
```

**Comment by stephan-v** [comment]
@hinaloe Thanks, it works. The styling is a bit different though, it would be nice to replicate what Vue.js has with the opacity background, error button and error indicator. That implementation show you a bit of code as well to display exactly what is wrong.

Although this helps, I would be pretty psyched to have all of that included when I use the overlay. 
Much appreciated though.

**Comment by hasusuf** [comment]
@hinaloe unfortunately it doesn't work with BrowserSync implementation. 
Version 0.11.3

**Comment by mazyvan** [comment]
I'm trying setting `overlay: true,` but I can't see errors on browser. Can you explain the full process please?
