### ISSUE TITLE
Compiled SCSS doesn't get minified

### ISSUE THREAD

**Issue by JonasDoebertin** [JeffreyWay/laravel-mix#612]
- Laravel Mix Version: 0.8.9
- Node Version: v7.1.0
- NPM Version: 3.10.9
- OS: macOS 10.12.3

### Description:

Same issue as mentioned in #427 with SCSS and `"laravel-mix": "^0.8.9"`.

Compiled scss doesn't get minified in production mode with this setup:

```js
mix.setPublicPath('assets');

mix.options({
    processCssUrls: false
});

mix.js('src/js/main.js', 'assets/js')
   .sass('src/sass/main.scss', 'assets/css')
   .extract(['jquery', 'basiclightbox', 'classlist-polyfill'])
   .sourceMaps()
   .version();
```

If I comment out the `mix.options()` call, it gets minified properly.

JS get's minified properly.

**Comment by JonasDoebertin** [comment]
Just updated to 0.9.2 and this issue seems to be fixed.

On a related note: I tend to miss that there's a new version of mix if it's not listed as a release on Github. Are there specific reasons for not tagging them here? Or better, only tagging some releases?

**Comment by ankurk91** [comment]
For now try this -

```js
  mix.sass('src/sass/main.scss', 'assets/css', {
    outputStyle: mix.inProduction ? 'compressed' : 'expanded'
  })
```
When in production mix should always set ```outputStyle``` to ```compressed``` by default.

**Comment by JonasDoebertin** [comment]
@ankurk91 Thank you! Came to that conclusion as well. But as I said, upgrading to `0.9.2` solved the issue for me.
