### ISSUE TITLE
jQuery no longer autoloaded by default despite docs stating otherwise

### ISSUE THREAD

**Issue by deframe** [JeffreyWay/laravel-mix#615]
This is pretty self-explanatory but the 0.9.0 docs (specifically https://github.com/JeffreyWay/laravel-mix/blob/v0.9.0/docs/autoloading.md) state that 

> ...jQuery autoloading is shipped out of the box...

However, it's been removed from the Mix.autoload config in https://github.com/JeffreyWay/laravel-mix/blob/v0.9.0/setup/webpack.config.js#L299

**Comment by manniL** [comment]
Well, you could've made a PR by yourself :wink: It isn't that much.

**Comment by deframe** [comment]
@manniL A PR for what, adding jQuery back into the autoloader or removing the reference from the documentation? Not so easy when you don't know the intention behind the change...

**Comment by adiachenko** [comment]
@deframe Obviously, documentation needs to be brought up to date. It was mentioned in release notes to 0.9. Also, the intention to remove implicit auto-loading has already been stated here by Jeffrey weeks before the change went live so no question here.

**Comment by deframe** [comment]
:thumbsup:
