### ISSUE TITLE
PostCSS Plugins not working on plain css concatenation

### ISSUE THREAD

**Issue by travisbotello** [JeffreyWay/laravel-mix#617]
- Laravel Mix Version: 0.8.9
- Node Version: v6.10.1
- NPM Version: 3.10.10
- OS: macOS 10.12.3

### Description:
When using PostCSS Plugins on vanilla/plain css concatenation PostCSS is doing nothing. However using PostCSS Plugins after `mix.sass` or `mix.less` is working

### Steps To Reproduce:
1. Add the following to your `webpack.mix.js`
```
// PostCSS Test
mix.styles([
   'resources/assets/css/test.css',
   'resources/assets/css/test2.css'
], 'public/css/all.css')
  .options({
    postCss: [
      require('postcss-import')(),
      require('postcss-cssnext')(),
      require('postcss-css-variables')()
    ]
  });
```
2. Install the plugins `postcss-import, postcss-cssnext and postcss-css-variables`
3. Create the example .css files
4. Run `npm run dev`
5. Check output file at `public/css/all.css`
6. Nothing has beend changed/modified except for concatenation of css files

**Comment by JeffreyWay** [comment]
Yeah mix.styles() is exclusively for basic concatenation.
