### ISSUE TITLE
Hot reloading on https

### ISSUE THREAD

**Issue by jericopulvera** [JeffreyWay/laravel-mix#622]
Description:
  'http://localhost:8080/js/app.js'. This request has been blocked; the content must be served over HTTPS.

Steps To Reproduce:

1. Valet Secure
2. npm run hot
3. access the site

**Comment by stephan-v** [comment]
The laravel mix helper in the `helpers.php` file should probably explain why this happens:

```
return $shouldHotReload = file_exists(public_path('hot'))
                    ? new HtmlString("http://localhost:8080{$manifest[$path]}")
                    : new HtmlString(url($manifest[$path]));
```

I guess a check needs to be added with something like `$request->secure()` or you could hardcode it for now. I currently can not test any of this but hopefully this points you in the right direction.

**Comment by JeffreyWay** [comment]
We have a PR for this. Will merge soon.

**Comment by oscarmorrison** [comment]
Hey @JeffreyWay I was wondering if there was any update on this?

```
Mixed Content: The page at <MY_DOMAIN> was loaded over HTTPS, but requested an insecure stylesheet 'http://localhost:8080/css/app.css'. 

This request has been blocked; the content must be served over HTTPS.
```

**Comment by connor11528** [comment]
I am getting the same error. Is there a fix for this? When I deploy my Laravel 5 app to Heroku I get the following error and am unsure how to fix it.

```
Mixed Content: The page at 'https://laravel5boilerplate.herokuapp.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://laravel5boilerplate.herokuapp.com/css/frontend.css?id=8c9be6a9c6b0ffb6b0ab'. This request has been blocked; the content must be served over HTTPS.
laravel5boilerplate.herokuapp.com/:1 Mixed Content: The page at 'https://laravel5boilerplate.herokuapp.com/' was loaded over HTTPS, but requested an insecure script 'http://laravel5boilerplate.herokuapp.com/js/frontend.js?id=4a60179c1d3f89b5b37e'. This request has been blocked; the content must be served over HTTPS.
laravel5boilerplate.herokuapp.com/:1 Mixed Content: The page at 'https://laravel5boilerplate.herokuapp.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://laravel5boilerplate.herokuapp.com/css/frontend.css?id=8c9be6a9c6b0ffb6b0ab'. This request has been blocked; the content must be served over HTTPS.
```

![screen shot 2017-08-29 at 11 06 30 am](https://user-images.githubusercontent.com/3578908/29836811-2fbaa5fe-8cab-11e7-95a6-2a8f9ca3f048.png)

**Comment by btkostner** [comment]
I have an app being served with `https` at `https://katayama.dev`.

I was able to get browserSync to work just by setting the configuration to this:
```js
mix.browserSync({
    proxy: 'https://katayama.dev'
})
```

And hot reloading by adding `--https` to my `hot` scripts like so:
```json
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --https --config=node_modules/laravel-mix/setup/webpack.config.js",
```

Hope this helps you.

**Comment by cerw** [comment]
If I use my cert (from Valet example) How do I overwrite localhost to project.test? SO the SSL match?

**Comment by ricnic** [comment]
@cerw to use the Valet certificate I needed to tackle this in two places (replace your-app and base path placeholders):

1. In `webpack.mix.js`:
```
mix.options({
    hmrOptions: {
        host: 'your-app.test',
        port: '8080'
    }
});
```

2. In `package.json` for the "hot" entry add the following params after '--https':
```
--key /your/base/path/.valet/Certificates/your-app.test.key 
--cert  /your/base/path/.valet/Certificates/your-app.test.cert
```

Hope that helps

**Comment by cerw** [comment]
@ricnic Hi there, 

I solved it like this too but I used the .env variable. (for dev only)
```js
 let hosts = process.env.APP_URL.split('//')
  mix.options({
    hmrOptions: {
      host: hosts[1],
      port: '8080'
    }
  })
``

**Comment by simensen** [comment]
Has anyone found a way to handle this that also allows for some .env configuration of the package.json file?

**Comment by theixbass** [comment]
> @cerw to use the Valet certificate I needed to tackle this in two places (replace your-app and base path placeholders):
> 
> 1. In `webpack.mix.js`:
> 
> ```
> mix.options({
>     hmrOptions: {
>         host: 'your-app.test',
>         port: '8080'
>     }
> });
> ```
> 
> 1. In `package.json` for the "hot" entry add the following params after '--https':
> 
> ```
> --key /your/base/path/.valet/Certificates/your-app.test.key 
> --cert  /your/base/path/.valet/Certificates/your-app.test.cert
> ```
> 
> Hope that helps

It is now

`--key /your/base/path/.config/valet/Certificates/your-app.test.key`
`--key /your/base/path/.config/valet/Certificates/your-app.test.crt`

**Comment by cerw** [comment]
@theixbass correct I have new **hotssl** command in packages

```
  "hotssl": "cross-env APP_VERSION=`git describe` NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --https --key ~/.config/valet/Certificates/operations.test.key --cert ~/.config/valet/Certificates/operations.test.crt --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
```

**Comment by nelson6e65** [comment]
There is a way to set  `--key` and `--cert` paths from a `.env` variable or something like that?

**Comment by BenjaminBrandtner** [comment]
**For Valet users:** I got it working so it reads the hostname from your .env file.  
I'm assuming you've executed `valet secure` and set APP_URL to something like `https://my-project.test`.

Add `--https` to the hot-script in package.json:

```
"hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --https --config=node_modules/laravel-mix/setup/webpack.config.js",
```

The rest happens in webpack.mix.js:

```js
const mix = require('laravel-mix');
const fs = require('fs');
const path = require('path');

const homeDir = process.env.HOME;
const host = process.env.APP_URL.split('//')[1];

mix
    //your project-specific .js .sass etc. calls
    .options({
        hmrOptions: {
            host: host,
            port: '8080',
        }
    })
    .webpackConfig({
        devServer: {
            https: true,
            key: fs.readFileSync(path.resolve(homeDir, `.config/valet/Certificates/${host}.key`)),
            cert: fs.readFileSync(path.resolve(homeDir, `.config/valet/Certificates/${host}.crt`)),
        }
    })
```

These docs helped my solve it: 

- https://laravel-mix.com/docs/4.0/quick-webpack-configuration
- https://webpack.js.org/configuration/dev-server/#devserverhttps

**Comment by squatto** [comment]
A HUGE thank you to @BenjaminBrandtner for sharing how to make this work!!

I'm using Mix version 6 and it wouldn't work, however. According to [the webpack docs](https://webpack.js.org/configuration/dev-server/#devserverhttps), the `devServer` format is _slightly_ different than in [@BenjaminBrandtner's comment](https://github.com/JeffreyWay/laravel-mix/issues/622#issuecomment-685600704). It should be this:

```javascript
mix
  .options({
    hmrOptions: {
      host: host,
      port: '8080',
    }
  })
  .webpackConfig({
    devServer: {
      https: {
        key: fs.readFileSync(path.resolve(homeDir, `.config/valet/Certificates/${host}.key`)),
        cert: fs.readFileSync(path.resolve(homeDir, `.config/valet/Certificates/${host}.crt`)),
        ca: fs.readFileSync(path.resolve(homeDir, `.config/valet/CA/LaravelValetCASelfSigned.pem`)),
      }
    }
  })
```

1. `https` is either `true` _or_ an object with `key`, `cert`, and `ca`. Since we have to use the site-specific certificate, we have to use the object format.
2. The object format requires a `ca` value, so we point it to Valet's self-signed CA.

Oddly, to get this to work, you also need to _remove_ `--https` from the command in `package.json`. It should be the default:

```
"hot": "mix watch --hot",
```

**Comment by cerw** [comment]
@squatto that laodes ok but update gets download from wrong URL ? (wrong port really)

![image](https://user-images.githubusercontent.com/16146/124065624-bbac8900-da69-11eb-9b73-32a03ae651a4.png)

Request URL: https://$host/_js_manifest.55434799535810f1351a.hot-update.json

Ta

**Comment by squatto** [comment]
@cerw That's odd 🤔 Is it not using the port from `hmrOptions`?

**Comment by cerw** [comment]
> @cerw That's odd 🤔 Is it not using the port from `hmrOptions`?

Yes it uses first time you load it from the socket server but does not work when it pushes the upload?

**Comment by cerw** [comment]
This is still happening for me.. anyone else?

**Comment by aakarim** [comment]
Webpack can now generate self-signed certificates, so you don't need to use your own.

```  
mix.webpackConfig({
    devServer: {
      server: 'https',
    },
  });
```

The issue I now have is I can't get the hot reloaded modules to be loaded with https, it's always using http://localhost:8080 to load the chunks. Even though the `mix()` helper uses the https:// protocol for the initial bundle load. If anyone has any pointers with this that would be greatly appreciated.

My `hot` file is:
`http://localhost:8080`.
