### ISSUE TITLE
Webpack exports loader support

### ISSUE THREAD

**Issue by nervo** [JeffreyWay/laravel-mix#626]
- Laravel Mix Version: 0.9.2
- Node Version (`node -v`): 7.7.3
- NPM Version (`npm -v`): 4.4.4
- OS: Linux

### Description:

Do you plan to support webpack exports loader (https://github.com/webpack-contrib/exports-loader) ?

This could solve some issues with old js library loadings. In my case, i need to import bootstrap 4 alpha 6 modules in dist flavour (to work around es6 minification issues in src flavour ), and - as far as i can see - the only way would be to use exports loader so that local vairables would be exported.

**Comment by JeffreyWay** [comment]
Is there anything preventing you from installing exports-loader yourself and then referencing it wherever you need?

**Comment by nervo** [comment]
@JeffreyWay Nothing at all :)

But as you add a kind of abstraction layer over webpack's ProvidePlugin on Api.js autoload function, i wonder if you plan to extend its functionnalities to avoid ugly things like

```
mix
    ...
    .autoload({
        ...
        'exports-loader?Util!bootstrap/js/dist/util': ['Util'],
        'exports-loader?Tooltip!bootstrap/js/dist/tooltip': ['Tooltip']
    })
```

**Comment by adiachenko** [comment]
@nervo It's unnecessary. Shimming modules has always been a hack meant for legacy libraries, brining that ugliness into an abstraction will only complicate package maintenence without brining anything to the table. 

Also, why would you want to use prettier syntax in mix config when your requires (imports) still use the one in the example above? That's just adding to confusion.

**Comment by adiachenko** [comment]
And besides `exports-loader` there is also `script-loader`, `imports-loader` that have their own options and arguments and need to be applied in the correct order. In short, better to just leave this stuff alone.

**Comment by nervo** [comment]
I'm ok with that, thanks for your answer :)

Btw, i don't need to use exports-loader syntax in my imports if i define them in autoload.  Giving the same example:
```
import 'bootstrap/js/dist/util';
import 'bootstrap/js/dist/tooltip';
```
One more thing: what about adding such an example in the autoload documentation ?

**Comment by Tsuintora** [comment]
> I'm ok with that, thanks for your answer :)
> 
> Btw, i don't need to use exports-loader syntax in my imports if i define them in autoload. Giving the same example:
> 
> ```
> import 'bootstrap/js/dist/util';
> import 'bootstrap/js/dist/tooltip';
> ```
> 
> One more thing: what about adding such an example in the autoload documentation ?

Author, please, can your share your solution?
`const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js')
    .extract(['jquery',  'jquery-easing'])
    .sass('resources/sass/app.scss', 'public/css', {
        outputStyle: 'compressed'
    });

mix.autoload({
    'jquery': ['$', 'window.jQuery', 'jQuery'],
    collapse: ['window.collapse', 'collapse']
});
`

How do your import your bootstrap modules?
Thanks for your attention

**Comment by nervo** [comment]
@Tsuintora i already share my solution right there: https://github.com/JeffreyWay/laravel-mix/issues/626#issuecomment-291253730 :)
Is there something unclear ?!?

**Comment by Tsuintora** [comment]
> @Tsuintora i already share my solution right there: [#626 (comment)](https://github.com/JeffreyWay/laravel-mix/issues/626#issuecomment-291253730) :)
> Is there something unclear ?!?

Can you show your webpack.mix.js? I don't understand how make imports in webpack.mix.js...
Big thanks
```
import 'bootstrap/js/dist/util';
import 'bootstrap/js/dist/tooltip';
```

**Comment by nervo** [comment]
These imports are not in `webpack.mix.js` , dude, these are in my javascript code :)

**Comment by Tsuintora** [comment]
> These imports are not in `webpack.mix.js` , dude, these are in my javascript code :)

Ohh .. anyway thank you very much for your attention. I understand that for you this information does not make any sense, but maybe you know how to put bootstrap, jquery and etc modules in vendor.js? When i try put them, they are not working.. Of course i have access to window.$, window.jQuery etc but have conflicts with bootstrap modules..
```
mix.js('resources/js/app.js', 'public/js')
    .extract([
        'jquery',
        'jquery-easing',
        'bootstrap/js/dist/collapse'
    ])
    .autoload({
        'jquery': ['$', 'window.jQuery', 'jQuery']
    })
    .sass('resources/sass/app.scss', 'public/css', {
        outputStyle: 'compressed'
    });
```
jQuery working and bootstrap collapse in vendor.js but bootstrap collapse has a something conflict.. t(...).collapse is not a function..

Have you encountered this?

**Comment by nervo** [comment]
@Tsuintora please, open a new issue, or search the internet, this one is closed :)
