### ISSUE TITLE
Does not notify user of missing files

### ISSUE THREAD

**Issue by infernobass7** [JeffreyWay/laravel-mix#627]
- Laravel Mix Version: 0.8.9 (`npm list --depth=0`)
- Node Version (`node -v`): 3.9.5
- NPM Version (`npm -v`): 6.2.2
- OS: Windows

### Description:
Laravel Mix does not notify the user if files are missing, when combining scripts.

### Steps To Reproduce:

1 Add files to webpack.mix.js
```
mix.scipts([
   'path/to/fileA.js',
   'path/to/fileB.js',
   'path/to/fileC.js' //File does not actually exist
], 'public/js/scripts.js');
```
2. Run npm run dev (or other)
3. Does not notify the user that the file does not exist and finishes as normal.

**Comment by modisimre** [comment]
I can confirm that too. Is there any solution?

**Comment by JeffreyWay** [comment]
Fixed in 1.0. You'll now see an error if the file doesn't exist.

**Comment by wouter2203** [comment]
This is not working for me.

Steps to reproduce:

```
composer create-project laravel/laravel testmixcombine
cd testmixcombine
npm i
```

Change `webpack.mix.js` to:

```js
mix.combine([
  'i/do/not/exist.js',
  'neither/do/i.js',
], 'public/shoulderror.js');
```

Now run `npm run dev`

Output contains no warnings/errors:
![image](https://user-images.githubusercontent.com/8761962/28209479-ee8fc3fc-6892-11e7-9064-d1db6ce1f91c.png)

**Comment by ethanbeyer** [comment]
I'm having this issue, too. No fix or change?
