### ISSUE TITLE
Is there any way to let laravel-mix transpile third party js files?

### ISSUE THREAD

**Issue by larryu** [JeffreyWay/laravel-mix#631]
- Laravel Mix Version: 0.9.2
- Node Version (`node -v`):  v6.9.4
- NPM Version (`npm -v`):  3.10.10

- OS: Cent OS 7.3

### Description:
I am new to Laravel and Vue. and currently I use Larave5.4 + Vue 2.0 to develop a website.
I imported a third party UI component, which is from vue-strap.
Everything goes well on Chrome, Safari and Firefox.
However, because IE11 doesn't support ES6, and the js files in vue-strap lib are written in ES6,
there are erros on IE11.
I thought Laravel-mix will compile all the file into ES5 format.
But when I check the app.js file, those js files in vue-strap lib are not transpiled into ES5.
My .babelrc in the root is as below. 
-------------------------------------------------------------
{
    "presets": [
        ["es2015", { "modules": false }],
    ],
    "plugins": ["transform-es2015-destructuring", "transform-object-rest-spread"]
}
-------------------------------------------------------------
My understanding is that laravel-mix will compile all the js and vue files including those imported from the third party lib based on .babelrc into public/js/app.js. Am I right?
But in my case, it seems that larabel-mix only compile the js and vue file of own project.

Thus, I have to manually compile third those js file into ES5 format,then run [npm run dev] to complie all js files into app.js. This will solve the problem.

My question is that is there any way to let laravel-mix compile all imported js and vue files from third party lib as well?

**Comment by JeffreyWay** [comment]
Can you try deleting your custom .babelrc file entirely and trying again? Does that change the output?

**Comment by larryu** [comment]
@JeffreyWay Thanks for your reply. I have tried but no luck.

**Comment by Anluis** [comment]
I met the same problem.Use babel app.js -o app.es5.js, but it's not cool...233

**Comment by ruchern** [comment]
You do not need the `.babelrc` file because Laravel Mix handles ES6 compilation on its own.

Check [package.json](https://github.com/JeffreyWay/laravel-mix/blob/master/package.json) and the babel-loader is already in there.

And [here](https://github.com/JeffreyWay/laravel-mix/blob/ce6c7b76d27dbb847a1ed974003b907b6e79e333/setup/webpack.config.js#L108) is all that's needed.

**Comment by Anluis** [comment]
@ruchern The question is not all scripts are compile into ES5 format, if you delete .babelrc or not.

**Comment by Anluis** [comment]
Add `{
    test: /\.js$/,
    loaders: ['babel-loader']
  },`
in your webpack.config.js , it works!
@larryu

**Comment by larryu** [comment]
@Anluis Thanks mate. This works. Seems a good way to solve this issue.
