### ISSUE TITLE
mix css broken in hot

### ISSUE THREAD

**Issue by camiant** [JeffreyWay/laravel-mix#633]
when declaring

``<link href="{{ mix('/css/app.css') }}" rel="stylesheet" type="text/css" />``

it doesn't work during "hot" developing

**Comment by dobromir-hristov** [comment]
https://github.com/JeffreyWay/laravel-mix/issues/549 Fixed it for me. 
```js
 .webpackConfig({
    devServer: {
      contentBase: 'public'
    },
```

**Comment by jbruni** [comment]
Well... there is similar declaration in the app I'm working, and it works:

    <link href="{{ mix('css/app.css') }}" rel="stylesheet" type="text/css" />

Just try removing the leading `/` - maybe this is the cause of the issue.

**Comment by rdpascua** [comment]
I'm having the same issue as well

Attempting to access the file gives me 404. This happens when I'm doing less and css compile at the same time.

```js
const { mix } = require('laravel-mix');

mix
  .less('resources/assets/less/main.less', 'public/css')
  .js([
    'resources/assets/js/app.js'
  ], 'public/js/app.js')
  .options({
    processCssUrls: false
  })

mix.styles([
    'resources/assets/fonts/nucleo-webfonts/mini/css/nucleo-mini.css',
    'resources/assets/fonts/nucleo-webfonts/glyph/css/nucleo-glyph.css',
    'resources/assets/fonts/nucleo-webfonts/outline/css/nucleo-outline.css',
    'public/css/main.css'
], 'public/css/all.css')

if (mix.config.inProduction) {
  mix.version()
}

```

While the `http://localhost:8000/css/main.css` works the `http://localhost:8000/css/all.css` doesn't.
Is there anything to debug this hot server? I'm not well versed using webpack

**Comment by JeffreyWay** [comment]
For mixing styles, it's best to use npm run watch with `mix.browserSync()`.
