### ISSUE TITLE
Add ability to specify custom view file locations

### ISSUE THREAD

**Issue by panda-madness** [JeffreyWay/laravel-mix#635]
It would be nice to add a feature that would allow us to specify custom template file paths and extensions, like .twig and such. This is mainly for browsersync watching and purifycss.

**Comment by ankurk91** [comment]
You can pass [options](https://browsersync.io/docs/options/) to ```browserSync``` method.

https://github.com/JeffreyWay/laravel-mix/blob/master/docs/browsersync.md

**Comment by panda-madness** [comment]
@ankurk91 That would work for browsersync, but what about PurifyCSS?
