### ISSUE TITLE
PurifyCss show rejected CSS.

### ISSUE THREAD

**Issue by stephan-v** [JeffreyWay/laravel-mix#636]
PurifyCss has an option to display rejected CSS rules. This would be extremely handy for a large project later on in the future where unused CSS bits could be left in the codebase.

https://github.com/purifycss/purifycss#example-with-both-glob-file-patterns-and-source-strings--minify--logging-rejected-selectors

I am wondering where to add the `rejected: true` property in the webpack file.

So far I tried this to no avail:

    plugins.push(new PurifyCSSPlugin(
        Object.assign({ paths }, Mix.options.purifyCss, { minimize: Mix.inProduction, rejected: true })
    ));

Hopefully someone can help me out. I think it would be a useful feature to add at least in my personal projects.

Cheers.

**Comment by JeffreyWay** [comment]
Try doing something like:

```
mix.options({
   purifyCss: { 
      purifyOptions: { rejected: true }
   }
});
```

The purifyOptions object is for the Webpack Purify plugin, so if you want to pass options to the underlying purify process, I think you need to nest them as shown above.

**Comment by stephan-v** [comment]
Thanks a lot, worked perfectly. :+1:

**Comment by stephan-v** [comment]
@JeffreyWay I tried to disable purifyCSS but that does not seem to work when I try this:

```
    .setPublicPath('public')
    .js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/scss/app.scss', 'public/css')
    .extract([
        'vue',
        'vuex',
        'vue-touch',
        'vue-resource'
    ])
    .version()
    .options({
        purifyCss: {
            purifyOptions: {
                rejected: false,
                purifyCss: false
            },
        }
    });
```

It still runs perfectly fine when I use `npm run watch` and execute purifyCSS regardless of the `false` setting.

**Comment by h-stoyanov** [comment]
> @JeffreyWay I tried to disable purifyCSS but that does not seem to work when I try this:
> 
> ```
>     .setPublicPath('public')
>     .js('resources/assets/js/app.js', 'public/js')
>     .sass('resources/assets/scss/app.scss', 'public/css')
>     .extract([
>         'vue',
>         'vuex',
>         'vue-touch',
>         'vue-resource'
>     ])
>     .version()
>     .options({
>         purifyCss: {
>             purifyOptions: {
>                 rejected: false,
>                 purifyCss: false
>             },
>         }
>     });
> ```
> It still runs perfectly fine when I use `npm run watch` and execute purifyCSS regardless of the `false` setting.

As seen in [documentation](https://laravel-mix.com/docs/3.0/options) if you don't want to purify CSS you have to set purifyCSS to false
