### ISSUE TITLE
Prod build vs Dev Build

### ISSUE THREAD

**Issue by oscarmorrison** [JeffreyWay/laravel-mix#639]
laravel-mix@0.8.9
v7.7.1
4.1.2
macOS 10.12.3

### Description:
I am having an issue where the dev build is fine, but the production build does not perform as expected. 

I have only a single file that I want to build using webpack. Lets call it `webpacked-stuff.js`, I want to then include (concatenate) that with the rest of my front end assets. for an output file of `bundle.min.js`

This works fine for **dev**, but does not work for **prod** build. 

This is what my webpack.mix file looks like for the example:

```js
mix.js('./resources/assets/js/webpacked-stuff.js', 'public/js/webpacked-stuff.js');

mix.scripts([
      'resources/assets/js/some-front-end-file.js',
      'resources/assets/js/lib/jquery.js',
 -    'public/js/webpacked-stuff.js'
  ], 'public/js/bundle.min.js');

```

### Steps To Reproduce:

Create a file that requires webpack `webpacked-stuff.js`, use the mix.js to build that file,
use mix.scrips to concat that with your other front end files.

**Comment by JeffreyWay** [comment]
When you say that it doesn't work for production, what specifically happens? Do you see an error?

**Comment by kodumen** [comment]
I think I'm also experiencing a similar problem. When I use the file built via `npm run production`, my code throws a `ReferenceError` on runtime. The file built with `npm run dev` works fine.

**Comment by JeffreyWay** [comment]
Closing this after no response.

**Comment by oscarmorrison** [comment]
Sorry @JeffreyWay i missed the notification for your response. Not of the code that is in the `webpacked-stuff.js`  does anything. Its really hard to debug as the production build strips out the `console.log` statements

**Comment by oscarmorrison** [comment]
Can we reopen this ticket @JeffreyWay ?

**Comment by oscarmorrison** [comment]
I have updated the example code above. I believe it has to do with my `mix.js` is getting versioned,
and then `mix.scripts` cant find that file.

I tried the `'public/js/webpacked-stuff.*.js'` (add a .*.js) but then the development build cannot find this file.
