### ISSUE TITLE
{{ mix }} function should take devServer.host into account when running HMR

### ISSUE THREAD

**Issue by mark-vesterskov** [JeffreyWay/laravel-mix#64]
My current setup is a Homestead VM running the Laravel Mix Example on my Mac. 

When i _npm run hmr_ the node.js server is started on localhost, which i cannot access outside the VM. 

Adding _host: "laravel-mix.app"_ within webpack.config.js i get the following output:

`Project is running at http://laravel-mix.app:8080/`
`webpack output is served from http://localhost:8080/`
`404s will fallback to /index.html`

I've added port 8080 to my Homestead ports, and can now access the node server from my local machine. 

When using the mix() function in a blade template, the localhost:8080 is hardcoded into the asset path, and not pulled from the webpack config file, thus making the loading of assets fail when accessing the site in my local browser.

I think the fix might be a bit more complex than just editing the path, as i tried hardcoding the url to laravel-mix.app instead, but still no dice.

**Comment by nickfederighi** [comment]
I agree that we need an easier way to clean this up. Running HMR from within a Homestead VM isn't out-of-the-box ready at this point.

**Comment by shealan** [comment]
Is there a way of doing this now, even hardcoding? Or do we just need to wait for a little while for a solution to be settled on?

**Comment by mark-vesterskov** [comment]
I did it by running the `npm run hpr` command on my local machine - kinda hacky, but it works.

**Comment by nickfederighi** [comment]
@shealan whats your current setup, and what have you managed to get working so far?

**Comment by nmfzone** [comment]
@shealan It's normal. `localhost:8080` is the only location to serve the webpack-dev-server, that would be listening by HMR. You can get nothing from it.

**Comment by Evertt** [comment]
I'm sorry, but where did you guys find the `mix()` function at all? No matter which branch of the laravel framework I look at, I can't find the `mix()` helper function anywhere...

**Comment by shealan** [comment]
@Evertt it doesn't exist yet so we've been manually hardcoding the js/css url that's being served up by webpack. Eg:

```
<script src="http://localhost:8080/public/assets/js/app.js"></script>
```

**Comment by nmfzone** [comment]
@Evertt @shealan No, the `mix()` function is available if you're using Laravel (if isn't, of course, you can make your own). You can see it [here](https://github.com/JeffreyWay/laravel-mix-example/blob/master/app/mix.php).

**Comment by JeffreyWay** [comment]
Closing this, as it's a duplicate.
