### ISSUE TITLE
.vue <style module> not working as expected

### ISSUE THREAD

**Issue by joltmode** [JeffreyWay/laravel-mix#641]
- Laravel Mix Version: 0.9.2
- Node Version: 7.2.1
- NPM Version: 3.10.10
- OS: Windows 7 x64

### Description:
Laravel Mix isn't css-module'arizing Vue components <style> with module support, namely: `<style module>`.

The resulting css-module variable gets generated and appended to compiled component, but it isn't populated. Neither the styles themselves are being modularized, classes are left as-is.

### Steps To Reproduce:
1. <kbd>git clone https://github.com/joltmode/laravel-mix-vue-style-module.git</kbd>
2. <kbd>npm install</kbd>
3. <kbd>npm run dev</kbd>
4. <kbd>php -S localhost:20202 -t public</kbd>
5. open browser and navigate to <kbd>localhost:20202</kbd>
6. see how the **BLUE** message isn't actually blue
7. debug `<style>` nodes, see how it's not actually _css-module_'arized
8. if you have _Vue inspector_, also can notice how `Example` node contains `$style` property with no values

**Comment by mariomka** [comment]
Any update?

**Comment by krisscox** [comment]
I've also just encountered this, did any of you find a solution?

**Comment by mnengerman** [comment]
Just encountered the same problem... Any solutions yet?
