### ISSUE TITLE
0.9.2 - mix.babel() requires babel-preset-es2015

### ISSUE THREAD

**Issue by rogervila** [JeffreyWay/laravel-mix#643]
- Laravel Mix Version: 0.9.2
- Node Version: 6.10.0
- NPM Version: 4.4.4
- OS: OS X El Capitan

### Description:
`mix.babel()` "Couldn't find preset "es2015" relative to directory "path/to/app"

### Steps To Reproduce:

1 - use `mix.babel()` on `webpack.mix.js`:
```js
mix.babel('from/app.js', 'to/');
```

2 - run `npm run dev`. Then this message appears (I had to censor the paths):
![captura de pantalla 2017-03-30 a las 10 21 04](https://cloud.githubusercontent.com/assets/6053012/24497263/2984e2cc-153b-11e7-9909-a1edc44225aa.png)

3 - run `npm install babel-preset-es2015`

4 - everything works.

**Comment by JeffreyWay** [comment]
Already fixed on master. Will be tagged later today.
