### ISSUE TITLE
Set custom folder for scanned directories purifyCSS

### ISSUE THREAD

**Issue by stephan-v** [JeffreyWay/laravel-mix#644]
I am wondering how I could pass a custom path to the purifyCSS plugin when using laravel-mix outside of the Laravel framework(**non Laravel project**).

From what I have seen, it seems that it would be easy to edit the `webpack.config.js` that comes with the package:

```JS
// By default, we'll scan all Blade and Vue files in our project.
let paths = glob.sync(Mix.Paths.root('resources/views/**/*.blade.php')).concat(
    Mix.js.reduce((carry, js) => {
        return carry.concat(glob.sync(js.entry.map(entry => entry.base) + '/**/*.vue'));
    }, [])
);
```

Unfortunately I am extending this `webpack.config.js` file like so:

```JS
mix.webpackConfig({
    devServer: {
        overlay: true,
    },
    module: {
        rules: [
            {
                test: /.(vue|js)$/,
                loader: 'eslint-loader',
                enforce: 'pre',
                exclude: /node_modules/
            }
        ]
    }
});
```

Could I just add the path to my extended variant? I have no clue what the syntax would be from what I can see it does not really seem possible?

**Comment by JeffreyWay** [comment]
You can do something like this:

```js
mix.sass('resources/assets/sass/app.scss', 'css')
   .options({
        purifyCss: {
            paths: ['resources/views/welcome.blade.php']
        }
    });
```
