### ISSUE TITLE
scss() always publishes to public even though other path specified

### ISSUE THREAD

**Issue by komirad** [JeffreyWay/laravel-mix#647]
So in the docs, sass is like `mix.sass('resources/assets/sass/app.scss', 'public/css');`

I changed `public/css` to `resources/build/css`. The css file ends up in `public/resources/build/css/app.css`. I would expect it to go to `resources/build/css/app.css` instead.

**Comment by JeffreyWay** [comment]
Add `mix.setPublicPath('resources')`

**Comment by komirad** [comment]
@JeffreyWay but that limits me to one directory.

I want to first build scss to css in resource folder. Then use scripts() to combine it that file to public folder.

This wouldn't work either:
```
mix.setPublicPath('resources')
    .sass('resources/assets/sass/app.scss', 'build/css');

mix
    .setPublicPath('public')
    .styles([
        'resources/build/css/app.css',
        'resources/semantic/dist/semantic.css'
    ], 'public/css/all.css');
```

Also, if public path is already `public` why would the argument `public/css` not go to `public/public/css`?

**Comment by JeffreyWay** [comment]
It's assumed that your Sass should compile directly to the public directory. You can't change that right now. 

> Also, if public path is already public why would the argument public/css not go to public/public/css?

"public" in your output path is optional. So if you include it, we strip it off to avoid confusion.

**Comment by komirad** [comment]
> It's assumed that your Sass should compile directly to the public directory. You can't change that right now.

Even then, there doesn't seem to be a way to queue the tasks so that the combine method `scripts()` uses the compiled sass.

**Comment by JeffreyWay** [comment]
When you say "queue the task," do you mean combine the stylesheets only after the Sass has compiled? 

This works for me:


```js
mix.sass('resources/assets/sass/app.scss', 'build/css')
    .styles([
        'public/build/css/app.css',
        'resources/semantic/dist/semantic.css'
    ], 'public/css/all.css');
```

**Comment by komirad** [comment]
Okay that worked.

Must have been confused by the stripping. :smile: 

I think the auto-stripping adds more confusion since setPublicPath is set by default unbeknownst to the developer.

It would make more sense to have it optional but pre-populate the file with `setRelativePath('public')` so that the second parameter is relative to root by default. Less confusing this way. (Also `setPublicPath()` is not mentioned in Laravel docs)

```
// default webpack file
mix.setRelativePath('public')
    .sass('resources/assets/sass/app.scss', 'css');
```

**Comment by komirad** [comment]
@JeffreyWay Also, I tried your code with version(). It stopped working -- I think because the build intermediate file is also versioned.

**Comment by JeffreyWay** [comment]
When you add versioning, it no longer creates `resources/build/css/app.css`. It creates something like `resources/build/css/app.13241212512.css`. So compensate for that by using a star.

```js
mix.sass('resources/assets/sass/app.scss', 'build/css')
    .styles([
        'public/build/css/app.*.css',
        'resources/semantic/dist/semantic.css'
    ], 'public/css/all.css');
```
