### ISSUE TITLE
Does not compile assets on Linux Servers

### ISSUE THREAD

**Issue by cerw** [JeffreyWay/laravel-mix#650]
- Laravel Mix Version: #.#.# laravel-mix@0.10.0
- Node Version: v6.10.1 
- NPM Version:  4.4.4
- OS: LInux ADM64 Ubuntu Xenial

### Description:

Hi

I have very strange problem, I have spinned off brand new 16.04 Ubuntu and same results, when deploy from git (or full checkout) and run ```npm run dev``` or ```npm run prod``` it just compiled very limited amount of assets: 

```
            Asset       Size  Chunks             Chunk Names
           mix.js  537 bytes       0  [emitted]  mix
mix-manifest.json   26 bytes          [emitted]
```

Then the Laravel App complains that can not find mix ```Unable to locate Mix file: /css/login.css. Please check your webpack.mix.js output paths and try again.```

When I run this on Mac I get this result: 

```
                              Asset       Size  Chunks                    Chunk Names
  /js/login.14837ff8fc3cfefcf6bf.js     287 kB       0  [emitted]  [big]  /js/login
/css/login.22c40956ea8991802501.css    40.7 kB       0  [emitted]         /js/login
                  mix-manifest.json  116 bytes          [emitted]
```

And everything works. 

I have same version of node, npm, i have done clean fresh install of npm install, even clean fresh of OS. 

Any ideas? 

Thanks

Petr

### Steps To Reproduce:

run ```npm run dev``` or ```npm run prod``` on server.

**Comment by ankurk91** [comment]
Works well for me on Ubuntu 16.04 x64.

**Comment by cerw** [comment]
It worked for me 1 out of 10 and not sure why :( Spent hours on this. very random problem. Results is that we can not deploy ..

**Comment by ankurk91** [comment]
How did you install node there ? Through [nvm](https://github.com/creationix/nvm) ?
Can you also post your ```webpack.mix.js``` code.

**Comment by cerw** [comment]
Installed it via ```curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - ``` 


```
const { mix } = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */
//
// mix.js('resources/assets/js/app.js', 'public/js')
//    .sass('resources/assets/sass/app.scss', 'public/css');
//
//
   mix.js('resources/assets/js/login.js', 'public/js')
   .sass('resources/assets/sass/login.scss', 'public/css')
   .version().sourceMaps()
```

**Comment by panda-madness** [comment]
@cerw You can try to increase the swap file size on your server. I've had similar issues with automated builds (not with Mix, but still) on Digital Ocean with limited RAM, same as @ankurk91, and increasing the  swap size helped me solve that.

**Comment by cerw** [comment]
@panda-madness I increased my DO Droplet to 4GB ,then run
``` 
rm /~.npm 
rm ./node_modules
npm install
npm run prod
```
And then I got this as output:
![image](https://cloud.githubusercontent.com/assets/16146/24538168/1ef5f30c-161a-11e7-952c-73850588036b.png)


It does not even include the right files anymore..  😕

**Comment by SabatinoMasala** [comment]
This issue happens on my server when using a symlinked node_modules directory.

`module.exports.context` would contain a reference to the parent of the original node_modules directory, making it unable to locate a `webpack.mix.js` file.
https://github.com/JeffreyWay/laravel-mix/blob/master/setup/webpack.config.js#L33

**Comment by cerw** [comment]
@SabatinoMasala That must be it! I have my node_modules symlinked (same as storage) to speed up the deployment, trying #533  hack now and it works! **Thank you**, I thought was I was going bit crazy :) 👍 

More about this subject:

Who does compile assets on the server and who locally (if locally, how do you deploy to the server(s))? Some [guys](https://laracasts.com/discuss/channels/elixir/laravel-mix-webpack-does-not-work-on-linux-when-deploying-work-on-mac) telling me to commit compiled assets into VCS, which I found very dull for many reasons. 

If you use GIT -> CI -> CD (in a cloud) there is really no other way then compile assets on deploy? Am I wrong? 

P

**Comment by AdnanMoghal** [comment]
@cerw did you find any help regarding compiling assets locally  or on production? I am also using gitlab ci / cd and want to figure out the best way to do it. 
Thanks.

**Comment by cerw** [comment]
@AdnanMoghal  Hi there, I am using this trick, instead of symbolink link I just copy the file from cache
```
cp -a ~/node_modules .
npm install
export APP_VERSION="{{ branch }}-{{ short_sha }}"
npm run dev
rsync -a node_modules ~/
```

This way is fast and it work.
