### ISSUE TITLE
Laravel-mix & common chuncks plugin

### ISSUE THREAD

**Issue by mementoneli** [JeffreyWay/laravel-mix#651]
So everything is working perfectly but my project has a lot of javascript wich made me consider using the common chuncks pluign.

I've been searching all over the web for a answer on how to use it with laravel-mix(without trying to modify to much in the webpack.config.js file), but without result.
So the question is how would one use the "webpack common chuncks plugin" with laravel / laravel-mix, if even possible

Thanks

**Comment by tianyong90** [comment]
https://github.com/JeffreyWay/laravel-mix/blob/master/docs/extract.md

Can this document help you? You can extract some third-part libraries in a vendor.js file. @mementoneli

**Comment by JeffreyWay** [comment]
We already use the common chunks plugin internally.

**Comment by mementoneli** [comment]
Yes, but , you still did not answer my question, I know how to extract the vendor etc... but I need to make chuncks of the main javascript files , so I can lazy-load them after the required javascript has been loaded.

Anyways thanks for trying to help tinyong90
