### ISSUE TITLE
BrowserSync reloads but new style is 404

### ISSUE THREAD

**Issue by Kyslik** [JeffreyWay/laravel-mix#652]
- Laravel Mix Version: 0.8.9
- Node Version (`node -v`): v7.7.3
- NPM Version (`npm -v`): 4.0.5
- OS: OS X 10.10.5

### Description:
After any change BrowserSync reloads page but injected **css** can not be found so page renders un-styled. After manual reload everything works fine.

<strike>Tried removing cache busting (`version()`), same issue. </strike> 

Everything works with **versioning off**.

### Steps To Reproduce:

**mix.js**

```
mix.js('resources/assets/js/docs.js', 'public/js')
    .sass('resources/assets/sass/docs.scss', 'public/css')
    .version()
    .copy('resources/assets/svg', 'public/svg')
    .copy('resources/assets/fonts', 'public/fonts');

mix.browserSync({
        proxy: 'my.dev/docs'
    });
```

**Comment by Kyslik** [comment]
Everything works with **versioning off** is this how it should work? (no information about that in documentation so far)

**Comment by JeffreyWay** [comment]
Yeah that's to be expected. When you change a style, the stylesheet href changes, but Browsersync doesn't pick up the change. 

You could always do versioning in production only.

**Comment by RobertCordes** [comment]
> You could always do versioning in production only.

@JeffreyWay I can't find out how to do that. Can you give me a hint? 😄

**Comment by ruchern** [comment]
@RobertCordes 

```javascript
if (mix.config.inProduction) {
    mix.version()
}
```

Add that into your `app.js` file.
