### ISSUE TITLE
Another failure

### ISSUE THREAD

**Issue by ionesculiviucristian** [JeffreyWay/laravel-mix#653]
Why is mix putting a /images/ path to my background url in app.css after processing app.scss ?

background: url('img/login_bg.jpg') no-repeat center; =>  background: url(/images/login_bg.jpg?817126c9835b6f8cd0ca821f2dcd58fe) no-repeat center;

Why is it making assumptions ?!

**Comment by webmarkelov** [comment]
default configuration: https://github.com/JeffreyWay/laravel-mix/blob/master/setup/webpack.config.js#L150

**Comment by ionesculiviucristian** [comment]
Yes, by setting the config works. But why is that by default ?

**Comment by webmarkelov** [comment]
Because this is how the webpack works, see [webpack documentation](https://webpack.js.org/configuration/)
