### ISSUE TITLE
illegal operation on a directory: Directory was created instead of file

### ISSUE THREAD

**Issue by trinvh** [JeffreyWay/laravel-mix#655]
- Laravel Mix Version: 0.10.0
- Node Version (`node -v`):  6.9.1
- NPM Version (`npm -v`):  3.10.8
- OS: Windows 10

### Description:

npm throws ````EISDIR: illegal operation on a directory, open 'E:\Projects\ebook\public\js\app.js'```` when run laravel mix.
Directory was created instead of file (directory named app.js).

````
npm run dev

> @ dev E:\Projects\ebook
> npm run development


> @ development E:\Projects\ebook
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emittingError: EISDIR: illegal operation on a directory, open 'E:\Projects\ebook\public\js\app.js'
    at Error (native)
````

### Steps To Reproduce:
- Create new Laravel by composer.
- Install npm dependencies.
- Run ````npm start dev````

**Comment by ankurk91** [comment]
@trinvh 
Can you post your ```webpack.mix.js``` code ?

**Comment by trinvh** [comment]
@ankurk91 I use default config:
````
const { mix } = require('laravel-mix');

mix.js('resources/assets/js/app.js', '/public/js/app.js')
   .sass('resources/assets/sass/app.scss', '/public/css/app.css');
````

**Comment by ankurk91** [comment]
**EISDIR** meaning on [stackoverflow](http://stackoverflow.com/questions/34959038/npm-stuck-giving-the-same-error-eisdir-illegal-operation-on-a-directory-read-a#answer-42677294)

**Comment by trinvh** [comment]
Yes, I knew its mean. But why the script create a directory, not a file?

Ok, I also tried to create public/js/app.js and public/css/app.css. Then run ````npm start dev```` again.

Another error was thrown: "EEXIST: file already exists" => why it doesn't delete original file or simply override it?

I remove js mixing in webpack.mix.js then run again:
````
mix .sass('resources/assets/sass/app.scss', '/public/css/app.css');
````
It run to the end with no error but /public/css/app.css is empty.

I think this is a windows path problem, i will try again on mac when I'm free.

**Comment by FerdivdWoerd** [comment]
I had the same problem as you. I figured out that my css was moved to a wrong location, there shoul be a pulbic directory inside of you public/css directory.

Change this: mix .sass('resources/assets/sass/app.scss', '/public/css/app.css'); to this: mix .sass('resources/assets/sass/app.scss', 'public/css/app.css'); Should work for the js methods as well.
