### ISSUE TITLE
Plain js watching

### ISSUE THREAD

**Issue by ionesculiviucristian** [JeffreyWay/laravel-mix#656]
With this setup:
```javascript
mix
    .scripts(['resources/assets/js/functions.js', 'resources/assets/js/app.js'], 'public/js/app.js')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .options({
        processCssUrls: false
    });
```

I don't get notifications on compile but the compile happens. The other thing is that changes take effect after 2 or 3 compiles. I have a timestamp added to public/js/app.js.

**Comment by sburina** [comment]
@ionesculiviucristian Are you using WebStorm/PhpStorm? There's an option that stops npm run watch to see the changes and needs to be disabled: Settings -> Appearance & Behaviour -> System Settings -> Use "safe write".

**Comment by ionesculiviucristian** [comment]
Didn't get any feedback like I get on css files after changing the setting in phpstorm. Is the console output correct, based on my above webpack file ?

![untitled](https://cloud.githubusercontent.com/assets/7398490/24747130/165172b8-1ac4-11e7-9cd6-079054c8cc29.png)

**Comment by sburina** [comment]
Yes, watch unfortunately does not produce any console output, but it works - check your resulting files for changes, they should be visible.

**Comment by ankurk91** [comment]
I can confirm this issue.
I can see the new build files on each change in js but no output on console.

**Comment by andyunleashed** [comment]
I can confirm this is also the case for me, no output is generated in the console, but they do compile.

**Comment by JeffreyWay** [comment]
mix.scripts() isn't part of your core Webpack bundle, so that's why you're not seeing it.

**Comment by stephan-v** [comment]
Notification would be nice.
