### ISSUE TITLE
.Vue instead of .vue causes compile error.

### ISSUE THREAD

**Issue by suhaibmalik** [JeffreyWay/laravel-mix#657]
This might dress some of the compiling issues out there. When adding in components to a Vue instance, even if the file extension is capital `.Vue`, and not `.vue` it throws an error about "module parse failed". Simply replacing the case of the extension in the app.js file fixes everything.

**Comment by webmarkelov** [comment]
os system? I had a similar error on linux

**Comment by JeffreyWay** [comment]
Yeah we check specifically for a .vue extension. I'm not sure that many people use .Vue.

**Comment by suhaibmalik** [comment]
@JeffreyWay It probably has to do with Passport vue components having the capital V. Maybe that aught to be changed on Passport then?

**Comment by devcircus** [comment]
Looking [at the Passport repo](https://github.com/laravel/passport/tree/2.0/resources/assets/js/components), the components use a lowercase 'v'. Where is the uppercase 'V' referenced?
