### ISSUE TITLE
Not envoyer linked folder compatible

### ISSUE THREAD

**Issue by jbreuer95** [JeffreyWay/laravel-mix#66]
Alright so for my website i used to run gulp production on envoyer just fine, with node_modules as a linked folder so npm install wouldn't take forever. Now when i try to run npm run production things go wrong because of this line in paths.js:

`return path.resolve(__dirname, '../../../', append)`

because its in a linked folder mix now thinks ./website is the root and not ./website/releases/number
when i nano into this file on the server and add the folder path to this line it works.

Can anyone think of a work around? for now i just removed the linked folder and wait a little longer for a deploy.

**Comment by jbreuer95** [comment]
seems to be a problem with webpack itself

**Comment by gabrielkoerich** [comment]
@jbreuer95 how did you solve that? I have the same problem and can't wait that long in my deploys.
It was working fine with gulp + webpack, so I think it's not a webpack issue.

**Comment by jbreuer95** [comment]
@gabrielkoerich I stopped working at that company so dont know if they fixed it. You could upgrade to the newest node or install yarn to decrease the `npm install` time. This also allows  you to de a true revert.

**Comment by gabrielkoerich** [comment]
@jbreuer95 I ended up compiling my assets locally and committing them to git. I was already using yarn and the build time was almost 4 minutes :/

**Comment by jbreuer95** [comment]
@gabrielkoerich yeah thats an option too. I did create a roadmap how to achieve working symlinking on envoyer but cant remember... If i ever have to do envoyer administration again, i will figure it out and post here :)
