### ISSUE TITLE
[Request] Configure purifyCss Path

### ISSUE THREAD

**Issue by Log1x** [JeffreyWay/laravel-mix#660]
- Laravel Mix Version: 0.10.0 (`npm list --depth=0`)
- Node Version (`node -v`): 7.3.0
- NPM Version (`npm -v`): 3.10.10
- OS: Windows 8

### Description:
Hi. Could you please add the ability to configure the path to blade templates that `purifyCss` uses?

Unless I'm mistaken, it appears to be currently hardcoded to `'resources/views/**/*.blade.php'`

Thanks in advance.

**Comment by panda-madness** [comment]
[Options](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/options.md)

You can pass custom purifycss-webpack options to Mix, where you can set custom paths.

Here's the snippet that I use: 
```
let options = {};

if(mix.config.inProduction) {

    let paths = [
        glob.sync(path.join(__dirname, 'public/theme/limservice/**/*.twig')),
        glob.sync(path.join(__dirname, 'public/theme/limservice/src/js/**/*.js')),
        glob.sync(path.join(__dirname, 'public/theme/limservice/src/js/**/*.vue'))
    ];

    options.purifyCss = {
        paths: [].concat.apply([], paths)
    }
}

mix.options(options);
```
