### ISSUE TITLE
Happypack

### ISSUE THREAD

**Issue by Grawl** [JeffreyWay/laravel-mix#661]
Would be cool to integrate Mix with [`happypack`](https://github.com/amireh/happypack) to speed up build times.

**Comment by JeffreyWay** [comment]
I think we'll hold off for now, but I'll keep an eye on that project. Thanks!

**Comment by stephan-v** [comment]
Although this has been closed for now I would love to see this integrated since builds times are quickly going up for a large project that I am working on. Or at least check to see if we can get more performance out of the current configuration.

**Comment by Dwood15** [comment]
@JeffreyWay Would be nice if we could take another look at happypack//parallel build processing for laravel-mix.

**Comment by marufmax** [comment]
Hi, still waiting for happypack integration

**Comment by UdaraJay** [comment]
Would like to see this too, build times on bigger projects are horrible.
