### ISSUE TITLE
SVG Corruption

### ISSUE THREAD

**Issue by mtdavidson** [JeffreyWay/laravel-mix#666]
- Laravel Mix Version: 0.8.9
- Node Version: 7.7.3
- NPM Version: 4.1.2
- OS: MacOS 10.12.3

### Description:

I'm using the CSS flag icon library flag-icon-css https://github.com/lipis/flag-icon-css when using this with mix and the assets are copied it seems to be messing with the file.

The Original File ( fr.svg )

```
<svg xmlns="http://www.w3.org/2000/svg" height="480" width="640" viewBox="0 0 640 480">
  <g fill-rule="evenodd" stroke-width="1pt">
    <path fill="#fff" d="M0 0h640v480H0z"/>
    <path fill="#00267f" d="M0 0h213.337v480H0z"/>
    <path fill="#f31830" d="M426.662 0H640v480H426.662z"/>
  </g>
</svg>
```

The File that is copied to the `public/fonts` directory

```
<svg xmlns="http://www.w3.org/2000/svg" height="480" width="640" viewBox="0 0 640 480">
  <g fill-rule="evenodd" stroke-width="1pt">
    <path fill="#fff" d="M0 0h640v480H0z"/>
    <path fill="#00267f" d="M0 0h213.337v480H0z"/>
    <path fill="#f31830" d="M426.662 0H640v480H426.662z"/>
  </g>
</svg>
vg>
```

This does not always happen for example with the gb flag `gb.svg` it copies fine

```
<svg xmlns="http://www.w3.org/2000/svg" height="480" width="640" viewBox="0 0 640 480">
  <defs>
    <clipPath id="a">
      <path fill-opacity=".67" d="M-85.333 0h682.67v512h-682.67z"/>
    </clipPath>
  </defs>
  <g clip-path="url(#a)" transform="translate(80) scale(.94)">
    <g stroke-width="1pt">
      <path fill="#006" d="M-256 0H768.02v512.01H-256z"/>
      <path d="M-256 0v57.244l909.535 454.768H768.02V454.77L-141.515 0H-256zM768.02 0v57.243L-141.515 512.01H-256v-57.243L653.535 0H768.02z" fill="#fff"/>
      <path d="M170.675 0v512.01h170.67V0h-170.67zM-256 170.67v170.67H768.02V170.67H-256z" fill="#fff"/>
      <path d="M-256 204.804v102.402H768.02V204.804H-256zM204.81 0v512.01h102.4V0h-102.4zM-256 512.01L85.34 341.34h76.324l-341.34 170.67H-256zM-256 0L85.34 170.67H9.016L-256 38.164V0zm606.356 170.67L691.696 0h76.324L426.68 170.67h-76.324zM768.02 512.01L426.68 341.34h76.324L768.02 473.848v38.162z" fill="#c00"/>
    </g>
  </g>
</svg>
```

With other files it corrupts in different ways I wonder if it could be something to do with `file-loader` https://github.com/webpack-contrib/file-loader but from my limited understanding of webpack I can't see any reason it would be corrupting the file in this way. 

### Steps To Reproduce:

- `npm install flag-icon-css`
- Add `@import "node_modules/flag-icon-css/sass/_flag-icon.scss";` to `app.scss`
- `npm run`
- Check `public/fonts/fr.svg`

**Comment by JeffreyWay** [comment]
Hmm I haven't seen this before. Sounds like a file-loader bug more than a Mix issue. Not sure that there's anything we can do about that.
