### ISSUE TITLE
Extract not working with multiple libraries

### ISSUE THREAD

**Issue by RaiserWeb** [JeffreyWay/laravel-mix#669]
When using extract, I get the following console error:
`Uncaught ReferenceError: Vue is not defined  at new Vuemit`

My webpack.mix.js file is:
`mix.js('resources/assets/js/app.js', 'public/js')
	.extract([ 'axios', 'lodash','vue', 'jquery', 'vuemit'])`

I have included the scripts as per:
`    <script src="{{ asset('js/manifest.js') }}"></script>  
    <script src="{{ asset('js/vendor.js') }}"></script>  	
    <script src="{{ asset('js/app.js') }}"></script>  `

When not using extract, I do not get this error.

I have required all these packages in my bootstrap.js file

My package versions:
`+-- axios@0.15.3
+-- bootstrap-sass@3.3.7
+-- cross-env@3.2.4
+-- gentelella@1.3.0
+-- google-autocomplete-vue@1.0.17
+-- jquery@3.2.1
+-- laravel-mix@0.10.0
+-- lodash@4.17.4
+-- moment@2.18.1
+-- vue@2.2.6
+-- vue2-animate@1.0.4
+-- vue2-dropzone@2.0.0
`-- vuemit@1.0.3`

Thanks for mix - it's such an ace tool

**Comment by JeffreyWay** [comment]
If you can reproduce this in a fresh project, that would help. 

But I'm certain that extract works with multiple libraries. I use it in my own projects.
