### ISSUE TITLE
Extending Webpack config with SVGO loader.

### ISSUE THREAD

**Issue by stephan-v** [JeffreyWay/laravel-mix#670]
- Laravel Mix Version: 0.10.0
- Node Version: 7.4 
- NPM Version: 4.1.2. 
- OS: Ubuntu 16.04

### Description:

I am trying to get SVGO set up to I can optimize SVG images and remove all the metadata. I would love webpack to do this alongside the config I already have. I have tried the following to no avail:

```
mix.webpackConfig({
    devServer: {
        overlay: true,
    },
    module: {
        rules: [
            {
                test: /.(vue|js)$/,
                loader: 'eslint-loader',
                enforce: 'pre',
                exclude: /node_modules/
            },
            {
                test: /\.svg$/,
                loader: 'svgo-loader',
                options: {
                    plugin: [
                        { removeDocType: true }, // Changed from default of `false`
                    ]
                }
            }
        ]
    }
});

mix.copy('resources/assets/images/**/*.svg', 'public/images/svg');

```

I assume that when the assets are copied that webpack picks up on this and the `test` regex will call the `svgo-loader`. Is this correct?

My assets are being copied to their output directory but the `svgo-loader` is not taking effect. I am not getting any errors and in my console I can see the SVG images, but they are completely unchanged. 

I tried adding more plugin options to SVG to make sure of this.

What am I doing wrong here?

**Edit**

I tried to just `require()` a file to test it out but it works perfectly fine then. How can I mimic this behavior for an entire folder so that the contents are being watched compared with another folder and minified if they do not exist in the build folder(or even have a different modified date)?

Preferably I would like run the `svgo-loader` on images whenever I copy them. Is it even possible to chain this somehow?

**Comment by taylorhoward92** [comment]
@stephan-v did you ever get this working?

**Comment by scsskid** [comment]
tried this as well, seams just not to work, but also no error, I guess doing in "manually" via CLI is the way to go
I guess mix is great when juts using standard compiling stuff and similar, otherwise use native webpack
