### ISSUE TITLE
Failed at the @ development script out of the box

### ISSUE THREAD

**Issue by dib258** [JeffreyWay/laravel-mix#671]
- Laravel Mix Version: 0.10.0 
- Node Version: 7.8.0
- NPM Version: 4.4.4
- OS: OSX El Capitan 10.11.6

### Description:

I just created a new Laravel project, to migrate from a old one and copied two or three files ( css,vue & js ) but nevertheless, I just tried to compile all the dependencies and out of the box I get the following error.

I searched in the issues in this repository and found this thread (https://github.com/JeffreyWay/laravel-mix/issues/165) created by Jeffrey Way himself but looks like it's only showing for windows user. So, I'm on mac and I get this error.

I tried to follow the thread but nothing fix it. I deleted node_modules, update node and npm but I can't seems to make this work...

### Steps To Reproduce:

Laravel new MyProject
Npm install
npm run dev

### Result

[2017-04-06T11_30_05_309Z-debug.txt](https://github.com/JeffreyWay/laravel-mix/files/902386/2017-04-06T11_30_05_309Z-debug.txt)

<img width="639" alt="screen shot 2017-04-06 at 13 30 21" src="https://cloud.githubusercontent.com/assets/4132137/24752380/ebe2f79a-1acd-11e7-83d1-8e9888728f3b.png">

### Solution

Ok, so I didn't saw the error on top and focused on the error below. Now that I corrected it, everything is compiling fine. That's weird but the problem is gone below... Kind of misleading !

**Comment by adam-devapp** [comment]
Same issue here on a mac. 

This relative module was not found:

Have npm install relative-module, but issue still exists.

What did you change?

**Comment by MAH1987** [comment]
The relative module isn't a package you have to install. 
In the Line under "This relative module was not found:" you can see what npm can't found.

for Example: 
* ./components/Example.vue in ./resources/assets/js/app.js

**Comment by ruchern** [comment]
Your file is not linked properly. `./components/Hypothesis.vue`
