### ISSUE TITLE
JS is not minified properly

### ISSUE THREAD

**Issue by vocanic-saumini** [JeffreyWay/laravel-mix#677]
- Laravel Mix Version: 0.10.0 (`npm list --depth=0`)
- Node Version (`node -v`): 7.8.0
- NPM Version (`npm -v`): 4.2.0
- OS: Ubuntu 14.04.5 LTS

### Description:
Hi

Generated JS file is not minified, I only see the spaces are strip out. I hope just striping out spaces not considered as minfied.

### Steps To Reproduce:

**package.json**

```
{
	"private" : true,
	"scripts" : {
		"dev": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
		"watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
		"watch-poll": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
		"hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
		"production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
	},
	"devDependencies" : {
		"cross-env" : "^3.2.3",
		"laravel-mix": "^0.10.0"
	}
}
```

**webpack.mix.js**

```
const { mix } = require('laravel-mix');

mix.combine(['resources/assets/js/app.min.js', 'resources/assets/js/admin.js'], 'public/js/admin.js');

```
Run `npm run production`

The file `public/js/admin.js` is not minified as I described. Also tried adding this line `mix.minify('public/js/admin.js');` after `combine`. It also returns the same bytes size file but with `.min.js` extension.

**Comment by ankurk91** [comment]
For vanilla JS use ```mix.scripts()``` method instead. 
```js
mix.scripts([
    'public/js/admin.js',
    'public/js/dashboard.js'
], 'public/js/all.js');
```

However according to [docs](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/concatenation-and-minification.md)  ```combine()``` should also minify in production.
I never used combine method.

**Comment by VinceG** [comment]
@vocanic-saumini we are using combine and it does in-fact minify the file. you should try and provide an example repository where this issue occurs.
