### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by VinceG** [JeffreyWay/laravel-mix#678]
This isn't an issue but rather a request or discussion. Will you consider adding api methods to support angular and typescript compilation to laravel mix? we already have react() method, it only makes sense to add support to the other big player.

I've made a simple repository that allows using Laravel with Angular 4. it works with webpack.mix.js or just a webpack.config.js file

https://github.com/vinceg/laravel-angular

It won't be hard to add support for typescript and angular compilation.

Thank You.

**Comment by JeffreyWay** [comment]
Yes, I'm more than happy to add `mix.angular()` to the main API. Just submit a PR and we'll merge it.

Let me know if you have any questions. You can review the `mix.react()` implementation for ideas.

https://github.com/JeffreyWay/laravel-mix/blob/master/src/Api.js#L29

**Comment by juanleal** [comment]
Hey...can i run this proyect laravel-angular with php artisan serve?
