### ISSUE TITLE
SASS Inject Reload Issue (v0.10.0) when using .scripts()

### ISSUE THREAD

**Issue by andyunleashed** [JeffreyWay/laravel-mix#681]
Mix Version: 0.10.0
Node Version: 6.10.0
NPM Version: 3.10.10
OS: Mac OS Sierra 

### Description
Hi! I follow steps 1 thru 4 to confirm this is an issue for the latest version.

If using .scripts([]) when you compile your SASS it triggers a compilation of your JS as well which will initiate a refresh regardless of the BrowserSync setting.

If I remove .scripts() from my mix file, then the new CSS is injected without issue and no reload occurs.

I checked out #413 and #430 - and am up to date with these, but in my scenario it reloads anyway.

I'm not sure if there is a way to ignore the app.js being recompiled when a SASS change triggers it and yet still reload if the JS was changed directly.

Basically the best way would be like Laravel 5.3/Gulp whereby SASS/JS compiling occurs in a  decoupled fashion and therefore SASS changed can be injected without reload and without compiling the JS.

### Steps To Reproduce:

Install a regular Laravel 5.4 project, have mix.sass and mix.scripts present and use mix.browserSync()

Unfortunately I cannot provide access to the repo, but I have included a stripped down version of the webpack.mix.js file:

```
const { mix } = require('laravel-mix');

mix.browserSync({
    proxy: 'example-app.dev',
    notify: false,
    ghostMode: {
        clicks: false,
        forms: false,
        scroll: false,
    }
});

mix.sass('resources/assets/sass/app.scss', 'public/css');

mix.scripts([
    'resources/assets/js/some-jquery-plugin.js',
    'resources/assets/js/another-jquery-plugin.js',
    'resources/assets/js/global.js'
], 'public/js/app.js');

mix.copy(
    'resources/assets/example.svg',
    'public/js/ui/example.svg'
);
```

**Comment by AndreasHerss** [comment]
Hi,

Have you found a solution for this? 
I have kinda the same problem, im just using the standard .js and .sass in my webpack.mix file, but when i change something in my js, it trigger compilation of my css too when running "npm run watch".

Perhaps it could be related, even though yours is the other way around.

**Comment by andyunleashed** [comment]
@AndreasHerss I ended up going back to Gulp unfortunately for this particular project.

**Comment by ruchern** [comment]
Your `Laravel-Mix` version is 0.10.0 at time of posting. Perhaps you want to create a new branch and test the latest version, which is 0.11.4? I am not sure what exactly are fixed, but I think the SASS injection thing might be fixed.

**Comment by jpirela** [comment]
The correct way is:
    mix.js(['resources/assets/js/some-jquery-plugin.js',
         'resources/assets/js/another-jquery-plugin.js',
         'resources/assets/js/global.js'
], 'public/js/app.js');
