### ISSUE TITLE
a bug with LoaderOptionsPlugin 's minimize in production

### ISSUE THREAD

**Issue by lichnow** [JeffreyWay/laravel-mix#685]
a bug with webpack.config.js
when " production run ",the less file to css will not work,i fix it,like this
```
new webpack.LoaderOptionsPlugin({
        // minimize: Mix.inProduction,
        options: {
            postcss: Mix.options.postCss,
            context: __dirname,
            output: {
                path: './'
            }
        }
    })
```
remove the code 'minimize: Mix.inProduction',and worked

**Comment by lichnow** [comment]
I found it's clean-css problem,it can not minify some css content,after minify ,css will all be annotation...

**Comment by lichnow** [comment]
before minify
![b78b827b-88b1-4bfb-afab-52d3a0651cbe](https://cloud.githubusercontent.com/assets/1695900/24850710/b39bb9e2-1e03-11e7-9349-5c94612bb3e3.png)
after minify
![f0abcaff-27be-4af8-a35c-63cf267a1cde](https://cloud.githubusercontent.com/assets/1695900/24850748/d357b6d2-1e03-11e7-9ecf-c8cfa07601fa.png)

**Comment by ruchern** [comment]
@lichnow Well, it sure did minify well. So well that it left the comments only. LOL

**Comment by JeffreyWay** [comment]
So do we need a PR to fix something here?

**Comment by lichnow** [comment]
@ruchern yes,you are right
