### ISSUE TITLE
in production  less or sass generate css file can't combine or styles with other css file!

### ISSUE THREAD

**Issue by lichnow** [JeffreyWay/laravel-mix#686]
like this code
```
mix
		.less(config.resource('styles/app.less'), config.compile('css/app.css'), {
			relativeUrls: false
		})
		.styles([
			config.resource('vendor/jquery-ui/themes/base/jquery-ui.css'),
			config.resource('vendor/jvectormap/jquery-jvectormap.css'),
			config.resource('vendor/bootstrap_calendar/css/bootstrap_calendar.css'),
			config.resource('vendor/jquery.gritter/css/jquery.gritter.css'),
			config.resource('vendor/morris.js/morris.css'),
			config.resource('vendor/animate.css/animate.css'),
			config.resource('styles/animate.css'),
			config.resource('vendor/bootstrap-treeview/src/css/bootstrap-treeview.css'),
			config.resource('vendor/datatables.net-bs/css/dataTables.bootstrap.css'),
			config.resource('vendor/datatables.net-responsive-bs/css/responsive.bootstrap.css'),
			config.resource('vendor/sweetalert/dist/sweetalert.css'),
			config.resource('vendor/Progress.js/src/progressjs.css'),
			config.resource('vendor/ladda/dist/ladda-themeless.min.css'),
			config.resource('vendor/ladda/dist/ladda.min.css'),
			config.resource('vendor/parsleyjs/src/parsley.css'),
			config.compile('css/app.css')
		], config.compile('css/all.css'))
```
 
`npm run dev`  command generate `css/all.css`  include both app.less and other css file contents,
`npm run prod` generate a file which  only include vendor's css file contents

**Comment by JeffreyWay** [comment]
I can't reproduce this. 

Please submit a new issue with the template filled out and basic steps to recreate the problem in a fresh app. That would help a lot.

**Comment by wcadena** [comment]
I have the same problem 
my archiv is:

mix.js('resources/assets/js/app.js', 'public/js')
   .js('resources/assets/js/app-landing.js', 'public/js/app-landing.js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .less('node_modules/bootstrap-less/bootstrap/bootstrap.less', 'public/css/bootstrap.css')
   .less('resources/assets/less/adminlte-app.less','public/css/adminlte-app.css')
   .less('node_modules/toastr/toastr.less','public/css/toastr.css')
   .combine([
       'public/css/app.css',
       'node_modules/admin-lte/dist/css/skins/_all-skins.css',
       'public/css/adminlte-app.css',
       'node_modules/icheck/skins/square/blue.css',
       'public/css/toastr.css',
       'node_modules/select2-bootstrap-theme/dist/select2-bootstrap.min.css',
   ], 'public/css/all.css')
   .combine([
       'public/css/bootstrap.css',
       'resources/assets/css/main.css'
   ], 'public/css/all-landing.css')
   //APP RESOURCES
   .copy('resources/assets/img/*.*','public/img')
   //VENDOR RESOURCES
   .copy('node_modules/font-awesome/fonts/*.*','public/fonts/')
   .copy('node_modules/ionicons/dist/fonts/*.*','public/fonts/')
   .copy('node_modules/admin-lte/bootstrap/fonts/*.*','public/fonts/bootstrap')
   .copy('node_modules/admin-lte/dist/css/skins/*.*','public/css/skins')
   .copy('node_modules/admin-lte/dist/img','public/img')
   .copy('node_modules/admin-lte/plugins','public/plugins')
   .copy('node_modules/icheck/skins/square/blue.png','public/css')
   .copy('node_modules/select2-bootstrap-theme/dist/select2-bootstrap.min.css','public/css')
   .copy('node_modules/select2/dist/css/select2.min.css','public/css')
   .copy('node_modules/select2/dist/js/select2.min.js','public/js')
    
   .copy('node_modules/icheck/skins/square/blue@2x.png','public/css');

if (mix.config.inProduction) {
  mix.version();
}

the problem are 

.combine([
       'public/css/app.css',


now 

'public/css/app.css',  ----> .sass('resources/assets/sass/app.scss', 'public/css')

and 


'public/css/adminlte-app.css',    ----> .less('resources/assets/less/adminlte-app.less','public/css/adminlte-app.css')


this files no exist when run 
npm run production

**Comment by wcadena** [comment]
Solution are
npm run dev
npm run prod

al dar los dos comandos seguidos el primero crea los archivos de donde estan los copilados y el otro junta todo.

saludos
