### ISSUE TITLE
Webpack Extract Text Plugin For React Application

### ISSUE THREAD

**Issue by mjangir** [JeffreyWay/laravel-mix#690]
First of all its not an issue but may be a new enhancement in the repo.

What I needed to extract the styles separately from my react components. Although, laravel-mix provides a very nice way to configure Webpack outside and I modified the webpack config from webpack.mix.js as below:

```
mix.webpackConfig({
        module: {
            rules: [
              {test: /(\.css|\.scss|\.sass)$/, loader: ExtractTextPlugin.extract('css-loader?sourceMap!postcss-loader!sass-loader?sourceMap')}
            ]
        },
        plugins: [
            new ExtractTextPlugin('[name].css'),
        ]
});
```

It works nicely. But wouldn't it be good if we have a separate **React** folder alongside the folder **Vue** to have its own webpack plugins like extract etc.

**Comment by JeffreyWay** [comment]
Mix should already extract any of your Sass code. If there's something specific to React for extraction, yeah, probably best to just use mix.webpackConfig() like your example.
