### ISSUE TITLE
Fonts relative paths are changed when compiled

### ISSUE THREAD

**Issue by Humeira** [JeffreyWay/laravel-mix#696]
Hello, 

I have a theme which I have included from `node_modules`, I am using LESS.

When I'm compiling my `style.less` file, I found out that the relative path of the fonts in the less files are changed 

Here's an example of `font-awesome`

Less file from node_modules : 

![image](https://cloud.githubusercontent.com/assets/3885848/24992154/e29da24e-2030-11e7-8151-0ac2bea9d2d7.png)

Compiled CSS

![image](https://cloud.githubusercontent.com/assets/3885848/24992186/085f1012-2031-11e7-92d0-683f7e720741.png)

I have no idea where it's getting `icons/font-awesome` when compiled, when it should have been `../` as it was originally before compilation.

Any ideas what caused this?

**Comment by QWp6t** [comment]
normal webpack behavior

**Comment by ankurk91** [comment]
Yes, this is normal behaviour.
You can turn off this and copy fonts files via ```copy()``` method.
```
mix. sass ('src/app.scss' , 'dist/' )
.options ({
processCssUrls : false
});

```
This should work for less as well.

Read more:
https://github.com/JeffreyWay/laravel-mix/blob/master/docs/css-preprocessors.md
