### ISSUE TITLE
Stylus support

### ISSUE THREAD

**Issue by nuernbergerA** [JeffreyWay/laravel-mix#7]
Any plans to include Stylus like u did for [Elixir](https://github.com/JeffreyWay/laravel-elixir-stylus)?

**Comment by PascaleBeier** [comment]
@nuernbergerA until there is an official api, you can install the `stylus-loader` and add something like

```javascript
{
  test: /\.styl$/,
  loader: 'stylus-loader'
}
```

to your webpack.config.js, just as you would without Mix.

**Comment by JeffreyWay** [comment]
Things like that should manually added by you to your webpack.config.js file.
