### ISSUE TITLE
does laravel-mix support gsap?

### ISSUE THREAD

**Issue by marko-mlinarevic** [JeffreyWay/laravel-mix#700]
As the title say, does laravel-mix support usage of gsap npm package. Thanks for the answer

**Comment by evsign** [comment]
why not? just npm install and use it...

**Comment by ruchern** [comment]
Yes of course.

`import { gsap, TweenMax, TimelineLite} from 'gsap';`

Apparently, you can specifically specify which plugins you want in the `{}` parenthesis, the above is just an example.
