### ISSUE TITLE
Columns padding is not right. Windows 10 - Command Prompt - Creators Update.

### ISSUE THREAD

**Issue by pixieaka** [JeffreyWay/laravel-mix#701]
When [ Command Prompt ] Maximized

![a1](https://cloud.githubusercontent.com/assets/17777237/25028217/193f83a8-20b3-11e7-899e-4f0ba453c9c1.JPG)

When [ Command Prompt ] Restored Down

![a2](https://cloud.githubusercontent.com/assets/17777237/25028220/1b6100d0-20b3-11e7-9952-33e10edebcd1.JPG)

**Comment by JeffreyWay** [comment]
That's all Webpack and has nothing to do with Mix, specifically. So we can't control that.
