### ISSUE TITLE
Cant extract new fancybox3

### ISSUE THREAD

**Issue by rorc** [JeffreyWay/laravel-mix#703]
Name of this plugin is `"@fancyapps/fancybox": "^3.0.48"` (https://www.npmjs.com/package/@fancyapps/fancybox)
And if i use laravel-mix:
```javascript
mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .extract(['axios', 'jquery', 'vue', 'slick-carousel', '@fancyapps/fancybox'])
    .version();
```
This plugin is present in `vendor.js`, but not working (`TypeError: t is not a function` because cant find dependency jQuery.
If i remove this plugin from extract array, all works fine.

**Comment by ankurk91** [comment]
Can you try autoloading 
```js
mix. autoload({
jquery : [ '$' , 'window.jQuery' ]
});

```

https://github.com/JeffreyWay/laravel-mix/blob/master/docs/autoloading.md

**Comment by rorc** [comment]
@ankurk91 Ty dude, i will try 😃

**Comment by implenton** [comment]
@rorc did you manage to fix it?

**Comment by rorc** [comment]
@implenton Yea 👍

**Comment by implenton** [comment]
@rorc can you provide the solution? I had the same problem yesterday.

**Comment by rorc** [comment]
@implenton Shure, here my mix file:
```javascript
const { mix } = require('laravel-mix');

mix.autoload({
    jquery: [ '$' , 'window.jQuery' ]
});

mix.js('resources/assets/js/app.js', 'public/js')
    .standaloneSass('resources/assets/sass/app.scss', 'public/css')
    .extract(['axios', 'jquery', 'vue', 'slick-carousel', '@fancyapps/fancybox'])
    .version();
```

**Comment by implenton** [comment]
@rorc I see. You extracted fancybox to its own file. Thanks.
