### ISSUE TITLE
frontend and backend config 

### ISSUE THREAD

**Issue by nazzart** [JeffreyWay/laravel-mix#709]
Hey, I really like laravel-mix and I'm new to webpack. Just have a little question here. 
My project folder structure is:
-  public
   - frontend
   - backend

- resources
  - assets
    - frontend
    - backend

How to set up a webpack.config.js to have fonts and images folder both for a backend and frontend? So those 2 folders would be inside backend and frontend folders. 

Thank you in advance.

**Comment by JeffreyWay** [comment]
Probably best to use a forum for a question like this.
