### ISSUE TITLE
Release upgrade

### ISSUE THREAD

**Issue by webmarkelov** [JeffreyWay/laravel-mix#712]
By What Do condition upgrade a release?
From the master branch pull a mix can turn into a problem :(

**Comment by JeffreyWay** [comment]
I don't understand your question. 

You can view the releases page to decide which version you want to install: https://github.com/JeffreyWay/laravel-mix/releases

**Comment by webmarkelov** [comment]
I want using a fresh mix, where additional new features and resolve issues but last release was 18 day ago

**Comment by JeffreyWay** [comment]
We'll likely make a new release this week.

**Comment by webmarkelov** [comment]
Thanks!
