### ISSUE TITLE
Reason for infrequent releases?

### ISSUE THREAD

**Issue by SethTompkins** [JeffreyWay/laravel-mix#713]
Is there a reason why there are so few releases with this project? The last release was 18 days ago, and in the release sass maps are still broken. They were fixed by a merge that occurred on April 1st and a release has still not been tagged to push that fix.

It is odd for a library not to have minor version number bumps when a bugfix is merged in. Is there some philosophy around why a release has not been tagged?

Apologies for the flame issue, but it is frustrating when a bugfix for a feature as elemental as sourcemaps is not considered for a tag 18 days after it is made part of the repo.

**Comment by JeffreyWay** [comment]
18 days is not some crazy-long span. I've been on vacation for the last two weeks. A new release will be tagged this week.
