### ISSUE TITLE
[Question] How to properly import css code from node_modules?

### ISSUE THREAD

**Issue by Frondor** [JeffreyWay/laravel-mix#714]
With Laravel-elixir I was able to load a `@import "ui-kit.scss"` at `app.scss` in my projects.

`ui-kit.scss` loads various components, like:
`@import "node_modules/ui-kit/components/select.css";`

that `@import` rule was supposed to extract the code and place it on the bundle, but now it only writes 
`@import url(node_modules/ui-kit/components/select.css);` to `app.css`, doesn't extract the code. This happens when running `npm run dev`. If I do `npm run production` it outputs nothing at all.
The building process has no errors though, even if I write wrong paths.

What am I missing here? I also tried without success:
`@import "ui-kit/components/select.css";`
`@import "~ui-kit/components/select.css";`

I'm using laravel-mix v0.10.
`webpack.mix.js` is untouched, since I'm using `app.scss`

**Comment by JeffreyWay** [comment]
Are you sure that select.css file actually exists in your node_modules directory? I just did a test, and it correctly inlined the imported file. 

Are you sure that your webpack.mix.js hasn't been changed at all?

**Comment by Frondor** [comment]
Thanks.
Managed the fix it by suppressing some .css file extensions and found that I was dealing with `postCss` in some of those vendor .css files.

I'll open a new issue after some more testing about postcss.
