### ISSUE TITLE
Disable JS sourcemaps 

### ISSUE THREAD

**Issue by tillkruss** [JeffreyWay/laravel-mix#715]
Is there a way to disable JavaScript sourcemap manually? `mix.sourceMaps(false)` doesn't seem to have any effect.

**Comment by ankurk91** [comment]
Sourcemaps are disabled when you run ```npm run prod```, [see](https://github.com/JeffreyWay/laravel-mix/blob/master/src/Api.js#L278-L282).
If you remove ```mix..sourceMaps()``` from your ```webpack.mix.js``` then sourcemaps will not be generated in ```dev``` mode as well.

**Comment by tillkruss** [comment]
Ah great, thanks!
