### ISSUE TITLE
Can't specify files to have version

### ISSUE THREAD

**Issue by claide** [JeffreyWay/laravel-mix#716]
Hi, I tried to apply versioning/cache busting only on my CSS files but when I run the npm, it applies to all from the css down to the scripts.

This is what my webpack.min.js looks like:

```
mix.sass('resources/assets/sass/app.scss', 'public/css')
	.sass('resources/assets/sass/login.scss', 'public/css')
        .version(['public/css/login.css', 'public/css/app.css']);

mix.js('resources/assets/js/users/main.js', 'public/js/user.js')
      .js('resources/assets/js/staff/main.js', 'public/js/staff.js');
```

**Comment by QWp6t** [comment]
That's normal mix behavior.

I don't think mix can do what you're trying to do.

**Comment by claide** [comment]
Thanks for the response. I've been using the laravel gulpfile for awhile and did the same thing and it worked. Now this new mix is a little bit confusing to me since I saw all the js files generates a new versioned files unlike in the laravel 5.3 mix.

`.version(['public/css/login.css', 'public/css/app.css']);`

**Comment by JeffreyWay** [comment]
With Mix, the version() method will automatically version all relevant bundled assets, so this is expected behavior.
