### ISSUE TITLE
Source maps disabled for production?

### ISSUE THREAD

**Issue by rhyek** [JeffreyWay/laravel-mix#718]
Just found [this](https://github.com/JeffreyWay/laravel-mix/blob/4fdbb1483a1ef6bacc4b9240e832c644f011d8ad/src/Api.js#L279) and #223.

What is the reasoning behind disabling source maps for production builds? I have a Vue application that will report client-side errors to sentry.io which benefits from having source maps available for debugging.

Sentry is usually used on production systems and I think in general source maps are most useful in production environments where you are sure to have transpiled/minified code.

Disabling them specifically for production seems backwards to me.

**Comment by rhyek** [comment]
Also, I think for production you wouldn't want to use `inline-source-map` as you probably only want them loaded when using dev tools or something like sentry specifically queries them.

**Comment by ankurk91** [comment]
Related to PR #704

**Comment by JeffreyWay** [comment]
They won't be disabled in the next point release.
