### ISSUE TITLE
Mix 0.10.0 Manifest: combine method does not add slash to the beginning of the path.

### ISSUE THREAD

**Issue by sebastiansulinski** [JeffreyWay/laravel-mix#720]
I have the following set up:

```javascript
let mix = require('laravel-mix');

mix
    .js('resources/js/src/app.js', 'public/js/')
    .sass('resources/scss/app.scss', 'public/css/')
    .sass('resources/scss/wysiwyg.scss', 'public/css/')
    .js('resources/js/admin/admin.js', 'public/js/')
    .combine([
        'resources/css/admin/core.css',
        'resources/css/admin/fileuploader.css'
    ], 'public/css/admin.css')
    .autoload({
        jquery: ['$', 'window.jQuery']
    })
    .sourceMaps();
```

which produces the following `mix-manifest.json` file:

```json
{
  "/public/js/app.js": "/public/js/app.js",
  "/public/css/app.css": "/public/css/app.css",
  "/public/css/wysiwyg.css": "/public/css/wysiwyg.css",
  "/public/js/admin.js": "/public/js/admin.js",
  "public/css/admin.css": "public/css/admin.css"
}
```
As you can see, the path generated by the `combine()` method does not have the slash at the beginning, wheres `js` and `sass` add it.

The quick and dirty fix would be to prepend it manually from within `Manifest::appendCombinedFiles` method, but perhaps there is a better way to tackle it?

```javascript
appendCombinedFiles(toCombine) {
    let output = '/' + this.preparePath(toCombine.output);

    this.manifest[
        output.replace(/\.(\w{32})(\..+)/, '$2')
    ] = output;

    this.refresh();
}
```

**Comment by sebastiansulinski** [comment]
By the way - this is standalone usage of the package.

**Comment by JeffreyWay** [comment]
Can you add `mix.setPublicPath('public')` as the first call to your webpack.mix.js file. Does that change anything?

**Comment by sebastiansulinski** [comment]
Thanks very much @JeffreyWay - this did the trick. It also changed location of the `mix-manifest.json`, which is now directly within the `public` directory.

```javascript
let mix = require('laravel-mix');

mix
    .setPublicPath('public')
    .js('resources/js/src/app.js', 'public/js/')
    .sass('resources/scss/app.scss', 'public/css/')
    .sass('resources/scss/wysiwyg.scss', 'public/css/')
    .js('resources/js/admin/admin.js', 'public/js/')
    .combine([
        'resources/css/admin/core.css',
        'resources/css/admin/fileuploader.css'
    ], 'public/css/admin.css')
    .autoload({
        jquery: ['$', 'window.jQuery']
    })
    .sourceMaps();
```

**Comment by johnRivs** [comment]
I happen to have the same problem but using `mix.scripts` instead. I am setting the public path to `public` and my `mix-manifest.json` is not prepending the key and the value with `/`.

**Comment by decadence** [comment]
@JeffreyWay 
I have the same problem with standalone usage of the package and combine method.
Any workaround for that if I have public path in project root?

`mix.setPublicPath("/");` produces SyntaxError: Invalid regular expression: /^\/: \ at end of pattern
