### ISSUE TITLE
processCssUrls option does not work per-render

### ISSUE THREAD

**Issue by benlipp** [JeffreyWay/laravel-mix#721]
- Laravel Mix Version: 0.10.0
- Node Version: v7.9.0
- NPM Version: 4.2.0
- OS: Ubuntu 16.04

### Description:
`processCssUrls` option does not work per-render. If any `mix.sass().options()` contains `processCssUrls: false` it will not run on any of them, even if the others contain `processCssUrls: true`.

### Steps To Reproduce:
1. Have two different mix.sass rules in your webpack.mix.js
2. Give one `.options({
    processCssUrls: true
})` and the other `.options({
    processCssUrls: false
})`

3. Run `npm run dev`

Both files will act as though `processCssUrls: false` was set.

#### Example
```
const { mix } = require('laravel-mix');

mix.js('resources/assets/js/app.js', 'public/js');
mix.sass('resources/assets/sass/app.scss', 'public/css').options({
    processCssUrls: true
});
mix.sass('resources/assets/sass/download.scss', 'public/css').options({
    processCssUrls: false
});
```

**Comment by benlipp** [comment]
It is clear from the code that this is actually working as intended, but the documentation on [the Laravel site](https://laravel.com/docs/5.4/mix#url-processing) is super unclear about that.

**Comment by JeffreyWay** [comment]
`mix.options()` is a one-time call, so this is expected behavior.

**Comment by benlipp** [comment]
@JeffreyWay is there any way to have this operate on multiple files like I want?
