### ISSUE TITLE
copy() / copyDirectory() destination directories with '.' (period) in name generates a single file, rather than copying directory structure

### ISSUE THREAD

**Issue by ljcrampton** [JeffreyWay/laravel-mix#723]
- Laravel Mix Version: laravel-mix@0.10.0
- Node Version: v7.7.2 
- NPM Version: 4.1.2
- OS: Ubuntu 16.04 x86_64

### Description:
mix.copy('xxx/datatables.net', 'xxx/xxx/datatables.net/',false);
mix.copyDirectory('xxx/datatables.net', 'xxx/xxx/datatables.net/');

Given a target directory with a period in its name, laravel-mix will not copy the source directory structure, but instead creates a file (in this case, 'datatables.net') containing the contents of a (random?) file in the source directory.

**Comment by JeffreyWay** [comment]
This is fixed as part of 329ed0ccffb51d52111ec11359f2617c528c60c0.
