### ISSUE TITLE
setPublicPath & combine paths issue

### ISSUE THREAD

**Issue by Broutard** [JeffreyWay/laravel-mix#731]
- Laravel Mix Version: 0.11.2
- Node Version (`node -v`): v7.8.0
- NPM Version (`npm -v`): 4.2.0
- OS: 

### Description:
Hi !
I want to build all my files to "public/assets/backend" path.
So I used setPublicPath/setResourceRoot to have my fonts/images in this path too.

```
mix.setPublicPath('public/assets/back').setResourceRoot('/assets/back/')
    .sass('app/back/Resources/assets/sass/app.scss', 'css')
    .combine([
        'app/back/Resources/assets/vendor/**/*.css'
    ], 'public/assets/back/css/vendor.css');
```

My generated public/assets/back/mix.manifest.json seems to be bugged :
```
{
  "/css/app.css": "/css/app.css",
  "public/assets/back/css/vendor.css": "public/assets/back/css/vendor.css"
}
```

Sass & Combine do not seem to treat the paths the same way.

NB: Laravel "mix" helper add a "/" at the beginning of my path, so it can not find my vendor.css !

I think you should remove "publicPath" to combined output path.

**Comment by JeffreyWay** [comment]
This is fixed in Mix 1.0+.
