### ISSUE TITLE
Feature request -  'mix()' function for javascript

### ISSUE THREAD

**Issue by 7ammer** [JeffreyWay/laravel-mix#740]
Issue: There are situations in a project where I need to reference a versioned file in a javascript file. I could of course get the `mix-manifest.json` file contents and print that to the page as a javascript object, then on the client side I could lookup the correct versioned path but this is a bit messy.

Solution: It would be nicer if perhaps there was a function like laravel's `mix()` function but for javascript. Perhaps something like below:

```javascript
//laravel-mix.js
window.laravelMix = function($assetUrl) {
  var json = require('../../../public/mix-manifest.json');
  for (var prop in json) if($assetUrl == prop) return json[prop];
  return $assetUrl;
};

// Usage
laravelMix('/css/base.css'); // OUTPUTS: /css/base.fdsa89f0dsa890fdsa890.css
```

```javascript
// webpack.mix.js
mix.js('resources/assets/js/laravel-mix.js', 'public/js/laravel-mix.js')
```

Unfortunately this won't work as `laravel-mix.js` `requires` `mix-manifest.json` before `mix-manifest.json` is updated meaning its contents is outdated.

Alternatively, perhaps creating a webpack plugin that transforms the paths to versioned paths would be better. Unfortunately I'm not that good with webpack so I wouldn't know how to do this.

**Comment by JeffreyWay** [comment]
We could inline the mix-manifest json into your JavaScript bundle. That would be an option. 

Right now, my instinct is to hold off since nobody else has requested this.

**Comment by jdhtm** [comment]
We would also like to have mix function in javascript. We have the same issue that need a versioned file in a javascript file. It would be very nice to have it!

**Comment by furey** [comment]
Hi! 👋

Long time [Laravel Project](https://laravel-mix.com/docs/4.0/installation#laravel-project) user; first time [Stand-Alone Project](https://laravel-mix.com/docs/4.0/installation#stand-alone-project) user.

I just built a non-Laravel SPA that used Mix's [versioning](https://laravel-mix.com/docs/4.0/versioning) and [hmr](https://laravel-mix.com/docs/4.0/hot-module-replacement) features.

I implemented my own JavaScript `mix()` helper by porting Laravel's [`Illuminate\Foundation\Mix`](https://github.com/laravel/framework/blob/e6c8aa0e39d8f91068ad1c299546536e9f25ef63/src/Illuminate/Foundation/Mix.php) class to JavaScript, then compiling it into my HTML template via [`lodash.template`](https://lodash.com/docs#template) each time Mix dispatches a `build` event.

Here's my simplified HTML template…

```html
<!-- ./src/index.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="<%= mix('css/app.css') %>">
</head>
<body>
    <div id="app"></div>
    <script src="<%= mix('js/app.js') %>"></script>
</body>
</html>
```

Here's my `webpack.mix.js` file (with `version()` toggle and `build` event listener)…

```js
// ./webpack.mix.js

const fs = require('fs');
const path = require('path');
const mix = require('laravel-mix');
const template = require('lodash.template');
const mixHelper = require('./mixHelper.js');

// …etc…

if (mix.inProduction()) {
    mix.version();
}

Mix.listen('build', () => {
    const inputPath = path.join(__dirname, 'src/index.html');
    const outputPath = path.join(__dirname, 'dist/index.html');
    const templateString = fs.readFileSync(inputPath, 'utf-8');
    const compiled = template(templateString);
    const outputString = compiled({ mix: mixHelper });
    fs.writeFileSync(outputPath, outputString);
});
```

Here's my JavaScript `mix()` helper…

```js
// ./mixHelper.js

const fs = require('fs');
const path = require('path');
const $manifests = {};

module.exports = function($path, $manifestDirectory = '') {
    if (! $path.startsWith('/')) {
        $path = `/${$path}`;
    }

    if ($manifestDirectory && ! $manifestDirectory.startsWith('/')) {
        $manifestDirectory = `/${$manifestDirectory}`;
    }

    const $hotPath = path.join(__dirname, Config.publicPath, 'hot');
    
    if (fs.existsSync($hotPath)) {
        const $url = fs.readFileSync($hotPath, 'utf-8').trimEnd();

        if ($url.startsWith('http://') || $url.startsWith('https://')) {
            return $url.slice($url.indexOf(':') + 1) + $path;
        }

        return `//localhost:8080${$path}`;
    }

    const $manifestPath = path.join(__dirname, Config.publicPath, $manifestDirectory, 'mix-manifest.json');

    if (! $manifests[$manifestPath]) {
        if (! fs.existsSync($manifestPath)) {
            throw Exception('The Mix manifest does not exist.');
        }

        $manifests[$manifestPath] = require($manifestPath);
    }

    const $manifest = $manifests[$manifestPath];

    if (! $manifest[$path]) {
        throw Exception(`Unable to locate Mix file: ${$path}.`);
    }

    return $manifestDirectory + $manifest[$path];
};
```

With the JavaScript `mix()` helper implemented, running the following `npm` commands produce the resulting `dist` HTML template output…

### `npm run dev`, `npm run watch`, etc

```html
<!-- ./dist/index.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="/css/app.css">
</head>
<body>
    <div id="app"></div>
    <script src="/js/app.js"></script>
</body>
</html>
```

### `npm run prod`

```html
<!-- ./dist/index.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="/css/app.css?id=1a05221a819af3149e65">
</head>
<body>
    <div id="app"></div>
    <script src="/js/app.js?id=d80a9ad8e827bafc2594"></script>
</body>
</html>
```

### `npm run hot`

```html
<!-- ./dist/index.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="//localhost:8080//css/app.css">
</head>
<body>
    <div id="app"></div>
    <script src="//localhost:8080//js/app.js"></script>
</body>
</html>
```

I hope this approach helps others looking for a similar end result.

Cheers!

🤓👍

**Comment by garimaI22** [comment]
Thanks it helped. Is this feature not yet in laravel-mix
