### ISSUE TITLE
ES6 transform-class-properties

### ISSUE THREAD

**Issue by jhayiwg** [JeffreyWay/laravel-mix#741]
Hello, first thanks for this project.

Just wanted to know how to reconfigure by adding a support of class properties especially for reactjs

Many thanks

**Comment by adiachenko** [comment]
Mix checks if there is `.babelrc` present in project root. For example, the reasonable default disregarding react support would be:

```
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": "> 1%"
      }
    }]
  ]
}
```

Then you add whatever presets and plugins you need for react here after installing corresponding packages from npm. I am sure that `babel-preset-env` and `babel-preset-react` are already bundled with mix. 

In short, this isn't really the concern of this project how you handle your babel transformations. The only gotcha is that declaring babel settings in `package.json` won't work from what I gather skimming through the source files.

**Comment by KuroThing** [comment]
An alternative way to add additional babel transformations would be to do something like this in your `webpack.mix.js` file.

```js
var babelOptions = global.options.babel
if (!babelOptions.plugins)
	babelOptions.plugins = []

babelOptions.plugins.push("transform-decorators-legacy")
babelOptions.plugins.push("transform-class-properties")
```

I'm not sure there is a better way to get `global.options`, but there is code throughout the code base that accesses it that way, so monkey see monkey do :D
