### ISSUE TITLE
Version image files that are not part of Sass preprocessing

### ISSUE THREAD

**Issue by pablopaul** [JeffreyWay/laravel-mix#746]
- Laravel Mix Version: 0.11.3
- Node Version: 6.10.2
- NPM Version: 3.10.10
- OS: Ubuntu inside Homestead

### Description:

I use images directly in Blade templates and want to version them via `mix.version('public/image.png'). This produces a corrupt image file.

### Steps To Reproduce:

1. Right click the following link and ave this image https://avatars2.githubusercontent.com/u/635526?v=3&s=88 into `public` as `image.jpg`
2. Just open `image.jpg` to make sure it is a working image
3. Call `mix.version('public/image.jpeg')` in your `webpack.mix.js` file
4. Run `npm run dev`
5. Try to open `image.jpg` again, it is no renamed with a hash like `image.fe944b6945ad889ff8c39c4b5f2ce3dc.jpeg`--> it will fail since the image is broken

![image](https://cloud.githubusercontent.com/assets/635526/25423185/04ff2f78-2a64-11e7-8f48-8493de9b2239.png)

### Temp. fix for my situation

As a temporary fix I am going to move the `img` tags out of my templates and include the image as background in CSS since the image processing in Sass is working fine and the number of the affected images is just 3.

**Comment by blazeu** [comment]
I'm having this issue as well, using Windows 10

**Comment by JeffreyWay** [comment]
Confirmed. Until this is fixed, only manually version text files.

**Comment by JeffreyWay** [comment]
This is fixed in Mix 1.0+.
