### ISSUE TITLE
CSS referenced images 404ing when using HMR

### ISSUE THREAD

**Issue by OwenMelbz** [JeffreyWay/laravel-mix#747]
As the title describes, when using HMR images inside the `public/images` folder are 404ing

As you can see we're definitely on the latest verison

![laravel-mix_package_json_ ___sites_1st-choice-spares](https://cloud.githubusercontent.com/assets/1094740/25433759/71c7d3b8-2a81-11e7-8ef2-39da17ae3e99.jpg)

This is what we're running and the terminal output

```sh
node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js --https
```

![1st-choice-spares_ _node_node_modules_cross-env_dist_bin_cross-env_js_node_env_development___--ho](https://cloud.githubusercontent.com/assets/1094740/25433790/91f223d2-2a81-11e7-9a18-bdee1a10b67f.jpg)

the `webpack.mix.js` looks like

```js
const { mix } = require('laravel-mix');

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
```

This is our scss

![sass__home_scss_ ___sites_1st-choice-spares](https://cloud.githubusercontent.com/assets/1094740/25433823/bb9db552-2a81-11e7-97c4-19e7c9b15675.jpg)

However all images that are referenced in the css are 404ing

![homepage____1st_choice_spares](https://cloud.githubusercontent.com/assets/1094740/25433936/33bbbdea-2a82-11e7-9dce-fb6a6b665de8.jpg)

But you can see when just running `npm run watch` it works as expected

![homepage____1st_choice_spares](https://cloud.githubusercontent.com/assets/1094740/25434662/1184f888-2a85-11e7-8a70-452a7d279c34.jpg)

**Comment by KuroThing** [comment]
As per the tip in the documentation (RTM helps, yo) about [css preprocessors](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/css-preprocessors.md#css-url-rewriting) absolute urls (like your `url('/images/bg-homepage.jpg')`) will not be touched.

Removing the `/`, *should* solve your problem.
