### ISSUE TITLE
Absolute path for fonts

### ISSUE THREAD

**Issue by anishdcruz** [JeffreyWay/laravel-mix#75]
Hi,

right now Webpack outputs fonts inside the css folder.

<img width="876" alt="screen shot 2017-01-11 at 12 31 10 pm" src="https://cloud.githubusercontent.com/assets/2182620/21842914/df80647c-d7f9-11e6-9240-0ca1b403bc6b.png">

updating webpack.conf.js from

```
{
            test: /\.(woff2?|ttf|eot|svg)$/,
            loader: 'file-loader',
            options: {
                name: '/fonts/[name].[ext]?[hash]'
            }
        }
```

to 

`name: '../fonts/[name].[ext]?[hash]'`

fix the issue

Thanks

**Comment by JeffreyWay** [comment]
I'm not getting fonts in the CSS directory. Can you paste in your webpack.mix.js file?

**Comment by anishdcruz** [comment]
Sorry about the css folder. 
I think file-loader rewrites the wrong path inside app.css

1. Actual app.css file

<img width="756" alt="screen shot 2017-01-11 at 8 02 48 pm" src="https://cloud.githubusercontent.com/assets/2182620/21858152/200bdcee-d839-11e6-83ef-1cae368958e7.png">

2. http request based on app.css

<img width="714" alt="screen shot 2017-01-11 at 8 03 14 pm" src="https://cloud.githubusercontent.com/assets/2182620/21858177/3911e422-d839-11e6-8448-e4c9aacdc22a.png">

3. output from `npm run production`

<img width="987" alt="screen shot 2017-01-11 at 8 02 23 pm" src="https://cloud.githubusercontent.com/assets/2182620/21858198/46cd223e-d839-11e6-8c05-e1af9d394423.png">

4. webpack.min.js

<img width="557" alt="screen shot 2017-01-11 at 8 06 46 pm" src="https://cloud.githubusercontent.com/assets/2182620/21858271/8984f278-d839-11e6-8868-595edc817d99.png">

**Comment by nmfzone** [comment]
+1 Same here.

@JeffreyWay

**Comment by harrynewsome** [comment]
Completely agree with @nmfzone regarding the images as all my images were broken because webpack was changing the url. Had to add `publicPath: '../images/'` inside `webpack.config.js`.

@JeffreyWay is there a way to have laravel mix leave the paths alone for images inside `url()`?

**Comment by eblin** [comment]
> @JeffreyWay is there a way to have laravel mix prevent webpack from touching the image paths inside url()?

Yes you have to tell `css-loader` to disable it [1] in your config 

```js
...
            loader: extractPlugin.extract({
                fallbackLoader: 'style-loader',
                loader: [
                    'css-loader?-url', // <-- notice the ?-url
                    'postcss-loader',
                    'resolve-url-loader',
                    (Mix.cssPreprocessor == 'sass') ? 'sass-loader?sourceMap' : 'less-loader'
...
```

[1] https://github.com/webpack/css-loader#options-1

**Comment by zgabievi** [comment]
+1 same problem

**Comment by nmfzone** [comment]
@JeffreyWay What's your opinion about this?

**Comment by JeffreyWay** [comment]
I've fixed the fonts public path issue. 

For images, can someone create a new issue and give me the exact steps to reproduce the problem where image paths are screwed up?

**Comment by nmfzone** [comment]
@JeffreyWay No, there is no issue with images. I only give a suggestion. I only imagine that would be nice if images stored in the folder. That will be well organized.

**Comment by z1haze** [comment]
I'm not certain this is fixed. I am pulling in bootstrap to my main app.scss file, and in my _variables I am using `$icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";` - I am getting unfavorable results thought. I expect that since my `app.css` file is output to public/assets/css/app.css` that my fonts should be output to `public/assets/fonts/*` but this is not happening. The fonts are being output to public/fonts, which breaks all the relative paths. Please give your input on this.

**Comment by z1haze** [comment]
The solution @anishdcruz  provided in the first message on this issue is the fix, I had to create a my own webpack config and override the ones in the package. I think it should be by that way by default though.

**Comment by nmfzone** [comment]
@z1haze As far as I know, It isn't an issue. Because the output fonts can't automatically relative to your app.css file. If you need to have font placed in `/public/assets/fonts`, you must override the configuration.

**Comment by z1haze** [comment]
But why wouldn't they be relative by default? It doesn't make any sense why it shouldn't be relative

**Comment by nmfzone** [comment]
@z1haze Because no one who sent the PR with such feature 😕 
By the way, what you want isn't a good feature I guess. What you think if you have `public/assets/A/a.css`, `public/assets/B/b.css` and `public/assets/C/c.css`. Should every `images/` placed in each folder? 🤔

**Comment by z1haze** [comment]
How do I just tell my configuration to put them where i want? How do I override this webpack.config.js?

**Comment by vrajroham** [comment]
Don't know this solution will work for any other user. I upgraded Laravel 5.4 from 5.3. I got exactly same issue. Tried all option suggested above. Just 1 tweak solved my issue.

I commented `$icon-font-path` in `_variable.scss` in [this file](https://github.com/laravel/laravel/blob/master/resources/assets/sass/_variables.scss#L20) . 

**comment following line in `_variables.scss`**
    
    //Comment following line
    //$icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";

> NOTE : I upgraded to 5.4 from 5.3

Hope it helps

**Comment by fudgelabs** [comment]
I had the same problem in that it was looking for fonts at:
public/css/fonts/..etc

Compiled /public/css/app.css had font urls as:
url(/fonts/...etc);
Which is the correct absolute path..?

Anyway, I had to edit line 204 for /node-modules/laravel-mix/setup/webpack.config.js from:
`publicPath: Mix.options.resourceRoot`
To:
`publicPath: '../'`

**Comment by bankgt** [comment]
@fudgelabs You can use this function for set a path.
mix.setPublicPath('themes/ilp/assets/dist');
mix.setResourceRoot('/themes/ilp/assets/dist/');

**Comment by tedsecretsource** [comment]
I'm trying to add theming to a project. I've added themes/{theme-name}/sass to ~/resources and things mostly work. The only issue is I too am seeing fonts always being copied to the public root. The only way to get them into the theme folder is by copying them manually and using a site-relative URL (aka absolute URL) since those URLs are ignored, but this seems broken. I would expect document relative URLs to resolve the location and copy accordingly. What am I missing?

Thanks.

**Comment by Kristories** [comment]
```js
let mix = require('laravel-mix');

mix.setPublicPath('public');
mix.setResourceRoot('../');
```
