### ISSUE TITLE
Why is it necessary to prepend .env vars with MIX_ ?

### ISSUE THREAD

**Issue by michaeldzjap** [JeffreyWay/laravel-mix#750]
I see v0.11.3 now supports reading vars from .env, which is great. One question though; why is it necessary to prepend the vars laravel-mix is going to pick up with `MIX_`? Is this as a sort of extra backup safety so as to not expose confidential .env vars? I was under the assumption that `DefinePlugin` only injects those .env vars that you actually reference in the source. So as long as you don't make the mistake of exposing any private .env vars in your frontend code you should be safe.

It just seems like a bit of an unnecessarily restrictive thing. But perhaps I am wrong or overlooking something regarding `DefinePlugin`?

**Comment by adiachenko** [comment]
@michaeldzjap You are correct in a sense that DefinePlugin only injects requested variables. However, Laravel Mix also conventionally exposes `process.env` which makes for potential security and memory issues if we didn't prefix the variables. To change it now would be backwards incompatible even if we wanted to. And I am not sure it will be for the best anyway. Namely, [CRA](https://github.com/facebookincubator/create-react-app) is doing the same with their DefinePlugin setup so there may be other implications I don't know yet. It was simply the most safe way to go about it.

**Comment by adiachenko** [comment]
[Here](https://github.com/facebookincubator/create-react-app/issues/102#issuecomment-234960880) is where they came up with this idea. It seems like contributors simply agreed of the fact that they needed additional security measures to prevent abuse of this feature.

**Comment by michaeldzjap** [comment]
I see. Well, the prefixing thing is not ideal from a stylistic point of view (for me at least), but it is not a major inconvenience either. Thanks for the explanation.
