### ISSUE TITLE
how to copy the font files to public folder when compiling a css file?

### ISSUE THREAD

**Issue by stalkercn** [JeffreyWay/laravel-mix#752]
- Laravel Mix Version: 0.8.9 (`npm list --depth=0`)
- Node Version (`node -v`): 6.10.2
- NPM Version (`npm -v`): 4.5.0
- OS: Ubuntu 16.04.2 LTS

### Description:
When I copy a css file to public folder, the font source url cannot be copied to /fonts/ folder or /public/ folder, but the font files in bootstrap and font-awesome can be copied correctly and automatically, what need I do?

### Steps To Reproduce:

mix.css('node_modules/element-ui/lib-theme-default/index.css', 'public/css/element-ui.css');

**Comment by stalkercn** [comment]
I see. Only the url in less or sass file will be handled automatically, css file will not.

**Comment by ruchern** [comment]
It's probably `mix.styles()` rather than `mix.css()`
