### ISSUE TITLE
Integrate Semantic UI

### ISSUE THREAD

**Issue by b8ne** [JeffreyWay/laravel-mix#757]
Im looking to integrate Semantic UIs build tools into my laravel project.
Id say it will be going into `/resources/assets/lib/semantic` or something similar, however gulp tasks will still need to run if the build is changed.
Is there any way to add the Gulp tasks into my webpack.mix.js so that all updates are watched from a single process?

**Comment by JeffreyWay** [comment]
I'm not sure honestly. But you can always include gulp as part of your npm script. `gulp && npm run dev`
