### ISSUE TITLE
node unsupported "node@v7.9.0" is incompatible with laravel-mix@0.11.3

### ISSUE THREAD

**Issue by nikbobo** [JeffreyWay/laravel-mix#758]
- Laravel Mix Version: #.#.# (`npm list --depth=0`)
- Node Version (`node -v`): v7.9.0
- NPM Version (`npm -v`): 4.5.0
- OS: macOS Sierra 10.12.4

### Description:
When I install, I got this warning, and failed.
WARN node unsupported "node@v7.9.0" is incompatible with laravel-mix@0.11.3 › img-loader@2.0.0 › imagemin-optipng@5.2.1 › optipng-bin@3.1.4 › bin-wrapper@3.0.2 › download@4.4.3 › got@^5.0.0, expected node@>=0.10.0 <7

**Comment by JeffreyWay** [comment]
Hmm, everything seems to be compiling properly for me, when using Node 7.9.0. Can you try deleting your node_modules directory and reinstalling everything again?

**Comment by nikbobo** [comment]
Oh, sorry. I found and solved the problem, the problem is I use the cnpm instead of npm.
But original npm is too slow.
Thank you.
