### ISSUE TITLE
Copied files are not listed in asset page

### ISSUE THREAD

**Issue by manniL** [JeffreyWay/laravel-mix#759]
- Laravel Mix Version: 0.11.3 (`npm list --depth=0`)
- Node Version (`node -v`): 7.6.0
- NPM Version (`npm -v`): 4.5.0
- OS: Ubuntu 17.04

### Description:

In older versions of Laravel Mix (Version 0.10.0 and lower), files were listed as successfully compiled assets when copying a directory including them through `copy()`. Since 0.11, those files are not listed anymore. Files that went through `js` or `sass` are still listed, but fonts or images inside of copied directories are not. Versioned files are listed too.

I guess this is related to https://github.com/JeffreyWay/laravel-mix/commit/329ed0ccffb51d52111ec11359f2617c528c60c0

### Steps To Reproduce:

1. Create a directory with some files or
2. Setup a copy method, for example `mix.copy("resources/assets/img", "public/img")`
3. Run `npm run dev`
4. See that those files are not listed

### Images

Before (0.10 and lower)
![image](https://cloud.githubusercontent.com/assets/640208/25554586/0c0cde04-2cd1-11e7-9a1e-f70a92ed2576.png)
(the list continues with more images)
After (current)
![image](https://cloud.githubusercontent.com/assets/640208/25554587/0ed1d0f4-2cd1-11e7-9771-88e42a349375.png)

**Comment by JeffreyWay** [comment]
Unless I'm mistaken, I don't think copied assets need to be included in the output there.
