### ISSUE TITLE
can't compile object spread operator unexpected token error

### ISSUE THREAD

**Issue by jericopulvera** [JeffreyWay/laravel-mix#76]
>  this code works before when I'm using laravel elixir after I switched I got this error. 

error  in ./~/babel-loader/lib?{"cacheDirectory":true,"presets":[["es2015",{"modules":false}]]}!./~/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/chat/Chatbox.vue

SyntaxError: Unexpected token (18:2)

  16 | 	components: ['user-list', 'message'],
  17 | 	computed: {
> 18 | 		...mapState({
     | 		       ^
  19 | 			chatStore: state => state.chatStore
  20 | 		})
  21 | 	},

**Comment by JeffreyWay** [comment]
More information please, so I can try to reproduce this.

**Comment by kpilard** [comment]
You are missing the Object rest spread transform:
https://babeljs.io/docs/plugins/transform-object-rest-spread/

One solution is 
`npm install --save-dev babel-preset-stage-3`

and than create a .babelrc file in your project directory

```
{
  "presets": ["stage-3"]
}
```

**Comment by JeffreyWay** [comment]
Thanks, @kpilard! Closing this now.

**Comment by claytonrcarter** [comment]
This just caught me, too.  @JeffreyWay, will this fix be included in a future release, or will it be a manual fix for a while?

**Comment by manogi** [comment]
+1 for including this in laravel-mix

**Comment by JeffreyWay** [comment]
This isn't a bug with Mix, though. It's an experimental Babel feature, and not part of the main ES2015 preset. For anything experimental, you should manually add it to your .babelrc.

**Comment by manogi** [comment]
@JeffreyWay Thanks for answering. I know and I'm fine with the manual "fix" - but you are maybe going to receive some more requests in this direction, because the object spread operator is mentioned a log in the Vuex docs and it does save you a lot of lines of code...

Thanks again for your great work!

**Comment by mesqueeb** [comment]
+1 for adding to Laravel mix because of Vuex! : D

**Comment by villers** [comment]
+1 for adding to Laravel mix because of react! : D

**Comment by richlove1** [comment]
+1 for adding to Laravel mix because of react! : D

**Comment by 82rules** [comment]
So when I add this to my .babelrc, I get other errors from compile, I'm also trying to enable spread but I'm not sure how to add configs to .babelrc in mix without overriding what's there

**Comment by villers** [comment]
Hello just put this in your babel rc

https://github.com/villers/priscillablog/blob/master/.babelrc

**Comment by luongs3** [comment]
+1m for Vuex

**Comment by samarhaider** [comment]
I am getting below error

Syntax Error: Unexpected token (22:10)

  20 | 
  21 | class Dashboard extends Component {
> 22 |     state = {};
     |           ^
  23 | 

Can any one help ?

**Comment by 55Cancri** [comment]
@samarhaider did you ever fix that bug? I am receiving the exact one and I have no idea what to do!

**Comment by samarhaider** [comment]
@55Cancri 

I changed 

`//    state = {};`

to

   ```
 constructor() {
       super();

       this.state = { };
     }
```

**Comment by samarhaider** [comment]
@55Cancri 
I replaced
  `state = {};`
to 
    ```
constructor() {
       super();

       this.state = { };
     }
```

Its fixed

**Comment by pavke** [comment]
npm install --save-dev babel-preset-env
npm install --save-dev babel-preset-stage-0

Create .babelrc file at root folder with 
{
  "presets": [
    "env",
    "stage-0",
    "react"
  ]
}

**Comment by nickosepulveda** [comment]
this config is correct!
{
    "presets": [
        "env",
        "stage-0",
        "react"
      ],
    "plugins": ["transform-object-rest-spread"]
  }

**Comment by aligajani** [comment]
Works fine on latest Mix version, thanks @JeffreyWay  for adding it.

**Comment by smsbhatt** [comment]
methods:Object.assign({
		    getCompanyStatus([expiry,status]){
		    	return 'active'
		    }
	    },mapActions([
	    	'limitUsers',
	    	'sendResetLink',
	    	'showCompanyModal',
	    	'removeCompany',
	    	'toggleAddons',
	    	'getCompanies',
	    	'getReferencePermissions'
	   	])),
