### ISSUE TITLE
Unable to remove comments in CSS and/or JS during compiling

### ISSUE THREAD

**Issue by ruchern** [JeffreyWay/laravel-mix#760]
- Laravel Mix Version: 0.11.3 (`npm list --depth=0`)
- Node Version (`node -v`): 7.9.0
- NPM Version (`npm -v`): 4.5.0
- OS: 

### Description:
Unable to remove comments in CSS and/or JS during compiling. The only way is to manually edit `webpack.config.js` to add the parameters:

```
{ comments: false }
```

However, `webpack.config.js` is inside the `node_modules` directory, so the changes will not be pushed to git.

### Steps To Reproduce:
Just run any `npm run <script>` and comments are not removed.

**Comment by ruchern** [comment]
@JeffreyWay Any clue to this?

**Comment by JeffreyWay** [comment]
Comments will automatically be stripped when you compile for production. `npm run production`.

**Comment by ruchern** [comment]
@JeffreyWay 

I still have this chunk showing up in the minified css.

```
*  Font Awesome 4.7.0 by @davegandy - http://fontawesome.io - @fontawesome
*  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
*/
```

**Comment by ruchern** [comment]
It appears that Font Awesome comments, in the form of this chunk is not being removed.

```
*!
 *  Font Awesome 4.7.0 by @davegandy - http://fontawesome.io - @fontawesome
 *  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
 */
```

However, the one in SimpleMDE is being removed.

**Comment by ReneLems** [comment]
@ruchern To anyone that needs a solution to this.
You can provide custom options to the webpack modules in `webpack.mix.js`, the original options are displayed in `/node_modules/laravel-mix/src/Options.js`

In laravel 5.4 i provided additional config option like below and all comments were stripped from my minified code, js and css alike.
```
mix.options({
    postCss: [
        require('postcss-discard-comments')({
            removeAll: true
        })
    ],
    uglify: {
        comments: false
    }
})
```

You do need the `postcss-discard-comments` module for this.
