### ISSUE TITLE
Ability to pause watch

### ISSUE THREAD

**Issue by trevorgehman** [JeffreyWay/laravel-mix#761]
So this is not an issue, but just a thought. Whenever I'm coding in a coffee shop and have `npm run watch` going, it kills my battery life.

<img width="652" alt="screen shot 2017-04-29 at 2 28 39 pm" src="https://cloud.githubusercontent.com/assets/3209864/25557853/75e852f6-2ce8-11e7-94c1-7a45a101209b.png">

Obviously I can just manually run `npm run dev`, but then I have to wait over a minute for that to finish.

So, I'm just wondering if there is a middle ground here. Something like the ability to pause the watchers, or have them stop watching if there is no change in 5 minutes or something, and then restart when receiving some input.

Anyways, I'm open to other solutions if someone else has experienced this.

**Comment by JeffreyWay** [comment]
There isn't an option to do that at the moment, but we can look into it.
