### ISSUE TITLE
Only version specific files version(['public/js/app.js'] not working

### ISSUE THREAD

**Issue by kiwo12345** [JeffreyWay/laravel-mix#763]
I am trying to only version specific files:

I am trying to version a specific file. And bellow I am trying to only version app.js

```
mix.js('resources/assets/js/app.js', 'public/js')
  .sass('resources/assets/sass/app.scss', 'public/css')
  .babel([
    'resources/assets/js/libs/xxxx.js',
    'resources/assets/js/libs/xxxx.js',
    'resources/assets/js/libs/xxxx.js',
    'resources/assets/js/libs/xxxx.js',
    'resources/assets/js/libs/xxxx.js',
    'resources/assets/js/libs/xxxx.js',
    'resources/assets/js/libs/xxxx.js',
    'resources/assets/js/libs/xxxx.js',
    'resources/assets/js/libs/xxxx.js',
    'resources/assets/js/libs/xxxx.js',
    'resources/assets/js/libs/xxxx.js',
    'resources/assets/js/libs/xxxx.js'
  ], 'public/js/libs.js')
  .scripts('resources/assets/js/pages/xxxx.js', 'public/js/xxxx.js')
  .scripts('resources/assets/js/pages/xxxx.js', 'public/js/xxxx.js')
  .scripts('resources/assets/js/pages/xxxx.js', 'public/js/xxxx.js')
  .scripts('resources/assets/js/pages/xxxx.js', 'public/js/xxxx.js')
  .scripts('resources/assets/js/pages/xxxx.js', 'public/js/xxxx.js')
  .scripts('resources/assets/js/pages/xxxx.js', 'public/js/xxxx.js')
  .scripts('resources/assets/js/pages/xxxx.js', 'public/js/xxxx.js')
  .scripts('resources/assets/js/pages/xxxx.js', 'public/js/xxxx.js')
  .version([
    'public/js/app.js'
  ]);
```

I am trying to version app.js but I get the error:
**Error: ENOENT: no such file or directory, open 'public/js/app.js'**

I have also tried: `app.*.js`

And if I only call `version();` it will ofc version all files.

So is there no way I only can version specific files?
I am tarting to think that I have to run my webpack.mix file multiple times in order to version specific files..

Also I ran npm install and upgraded to **laravel-mix@0.8.9**

**Comment by ruchern** [comment]
As far as I know, you cannot version a single file.

**Comment by JeffreyWay** [comment]
Right. mix.version() automatically versions the relevant files for your Webpack bundle. Whatever you pass as an array to the method will be files to version on top of that.

**Comment by kiwo12345** [comment]
@JeffreyWay Ah okey, guess I gotta run my mix files multiple times then
