### ISSUE TITLE
Issues with mix.less not processing

### ISSUE THREAD

**Issue by dmeltzer** [JeffreyWay/laravel-mix#77]
Hello,

Appologies if this is something terribly dumb on my end, but I've been banging my head against it for a bit now and haven't solved anything.

my webpack.mix.js:
```
mix.js('./resources/assets/js/bootstrap.js', 'public/assets/js/all.js')
    .extract(['vue', 'jquery'])
    .less('resources/assets/less/build.less','public/assets/css/')
    .sourceMaps();
```

My webpack.config.js is basically default with laravel mix, with the addition of a jsx loader.

My build.less:
```
@import "AdminLTE.less";
@import "skins/skin-blue.less";
@import "ekko-lightbox.less";
@import "overrides.less";
```

When trying to run webpack, I see the following:
 ERROR  Failed to compile with 1 errors

 error  in ./resources/assets/less/build.less

Module parse failed: /home/hydrogen/work/snipe-it/resources/assets/less/build.less Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "AdminLTE.less";
| @import "skins/skin-blue.less";
| @import "ekko-lightbox.less";

 @ multi all

Which makes me think that the less-loader isn't being found/run, but I can't figure out why/where?

**Comment by JeffreyWay** [comment]
Hmm, having trouble reproducing this. You're using an up-to-date version of Laravel Mix and the webpack.config.js file? Can you reproduce this in a fresh app as well?

**Comment by dmeltzer** [comment]
I just tried a `laravel new test --dev` and installed laravel-mix into it Following the instructions here: https://github.com/JeffreyWay/laravel-mix/blob/master/docs/installation.md

The same issue occurs.  Stripped overrides.less down to:
.div {
    color: red;
}
for testing.  Running this on ubuntu 16.04 if it makes any difference.

 ```
ERROR  Failed to compile with 2 errors

 error  in ./resources/assets/less/build.less

Module parse failed: /home/hydrogen/work/test/resources/assets/less/build.less Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "overrides.less"

 @ multi app

 error  in ./resources/assets/js/components/Example.vue

Module parse failed: /home/hydrogen/work/test/resources/assets/js/components/Example.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <template>
|     <div class="container">
|         <div class="row">

 @ ./resources/assets/js/app.js 16:25-60
 @ multi app

            Asset     Size  Chunks             Chunk Names
/assets/js/app.js  1.15 MB       0  [emitted]  app
   [9] ./resources/assets/js/app.js 577 bytes {0} [built]
  [10] ./resources/assets/less/build.less 221 bytes {0} [built] [failed] [1 error]
  [34] ./resources/assets/js/bootstrap.js 1.32 kB {0} [built]
  [36] multi app 40 bytes {0} [built]
    + 33 hidden modules
```

**Comment by nmfzone** [comment]
@dmeltzer You must use the latest version of Laravel Mix 0.4.0. And by the way, nowadays the docs aren't up-to-date. You can see the example setup and usage in [here](https://github.com/JeffreyWay/laravel-mix-example). Hope that helps.

**Comment by PsychicCat** [comment]
I had the same issue bringing this in an existing project that uses Elixir. Removed my node_modules and reinstalled everything, now vue loader and sass loaders work.

**Comment by JeffreyWay** [comment]
Yeah I think updating should do the trick for you. I can't reproduce any of this.

**Comment by thats4shaw** [comment]
Same scenario as @PsychicCat.  Removing node_modules and reinstalling as he suggested corrected the issue for me.

**Comment by ekandreas** [comment]
I had the same issue. Removing node_modules and `npm install` solved the issue.
