### ISSUE TITLE
Laravel-Mix npm run dev syntax error!

### ISSUE THREAD

**Issue by ravisharmaa** [JeffreyWay/laravel-mix#772]
[debuglog.txt.txt](https://github.com/JeffreyWay/laravel-mix/files/972699/debuglog.txt.txt)

> @ dev C:\xampp\htdocs\projects\melungtse
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

undefined:1

SyntaxError: Unexpected token

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script 'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\projects\melungtse\npm-debug.log

And my NODE is 6.10.3
NPM is 3.10.10
OS Windows 10

**Comment by ruchern** [comment]
Upgrade npm.

**Comment by ravisharmaa** [comment]
@ruchern done !! already and it says it is in version 3.10.10

**Comment by ravisharmaa** [comment]
@JeffreyWay After I have updated npm and node what is the is solution to these problems???

**Comment by ruchern** [comment]
@ravisharmaa Still having what problems? Same?

**Comment by JeffreyWay** [comment]
I don't know. You ignored the issue template and haven't given me enough information.

**Comment by spearmootz** [comment]
@JeffreyWay My brother was having this exact same issue after he got Blue Screen on windows and restarted. After a lot of debugging and thinking it was npm i went into the code and found where it was breaking.

Manifest.js -> this.read()

it was finding a mix-manifest.json file but it was empty for some reason and because the JSON was invalid it was throwing that error. so maybe a try catch around that.  Just say the word and ill make a PR

**Comment by spearmootz** [comment]
@ravisharmaa try deleting the mix-manifest.json file from /public and report if it fixed it

**Comment by andikahmadr7** [comment]
OMG!! thanks dude @spearmootz  , it's workin!

**Comment by spearmootz** [comment]
Welcome my dude @andikahmadr7

**Comment by jayGorio** [comment]
@spearmootz Thanks. It solved my problem.

**Comment by mohammadreza2012** [comment]
just trying to delete mix-manifest.json from /public folder and run `npm run watch` again.

**Comment by andreworks** [comment]
@spearmootz thank you!
