### ISSUE TITLE
Laravel compressing javascript using mix.scripts(); renames function in compressed file

### ISSUE THREAD

**Issue by kiwo12345** [JeffreyWay/laravel-mix#775]
I am compressing a js file like this:
`
mix.scripts('resources/assets/js/pages/login.js', 'public/js/login.js');`
My pre-compressed file contains this function:

```
function zoomInForm() { 
$('#login-page').toggleClass('zoom animated'); 
........ ........ 
}
```
But in my compressed file the function zoomInForm is renamed so I can never call the `zoomInForm();` function on my page.

How can I just compress a js file to one line without renamig functions?

**Comment by ankurk91** [comment]
Can you share your webpack.mix.js code. I believe you are using ```mix.scripts()``` to minify this file.
