### ISSUE TITLE
HMR with vanilla javascript files.

### ISSUE THREAD

**Issue by stephan-v** [JeffreyWay/laravel-mix#778]
- Laravel Mix Version: 0.11.4 (`npm list --depth=0`)
- Node Version (7.4): 
- NPM Version (4.1.2): 
- OS: Ubuntu 16.04

### Description:

First of all, I am running this outside of Laravel in a custom framework with the Laravel mix helper function copied over(mostly).

I am trying to run Webpack with hot module reloading on, I am running into a problem with my vanilla javascript files though. I followed the example from the Laravel webpage:

```JS
mix.scripts([
    'public/js/admin.js',
    'public/js/dashboard.js'
], 'public/js/all.js');
```

Whenever I run `npm run hot` now. These files obviously will not be put under hot reload which is no problem. Except that it is now also trying to serve my vanilla javascript file over the webpack server:

```
GET https://localhost:8080/js/all.js 404 ()
```

Could anyone help me out with this? I will try to update this with more info since I will be trying to fix this. Any help or guidance in the right direction would be helpful in the meanwhile.

Thanks!

**Comment by JeffreyWay** [comment]
For that, you can either not use the mix() function that Laravel provides, or use `npm run watch` instead. There's a `mix.browserSync()` method you can call for reloading.
