### ISSUE TITLE
NamedModulesPlugin for HMR

### ISSUE THREAD

**Issue by stephan-v** [JeffreyWay/laravel-mix#779]
Currently the HMR shows updated modules with numbers in the console. This provides little feedback and in this way you even get a suggestion to install the `NamedModulesPlugin`.

What I mean:

https://github.com/react-boilerplate/react-boilerplate/issues/719

I feel like this could be a useful enhancement.

I have already added it like so to my `mix.webpackConfig` object:

```
plugins: [
        new webpack.NamedModulesPlugin(),
        // prints more readable module names in the browser console on HMR updates
    ]
```

This is ok but to prevent the suggestion from popping up on the console and to provide prettier output(can probably strip off a bit of the path) I feel it would be justified incorporating this into this project.

**Comment by JeffreyWay** [comment]
Sure. If anyone wants to submit a PR, that'd be great.

**Comment by JeffreyWay** [comment]
Merged.
