### ISSUE TITLE
[Feature request] Custom path for CSS URL processing

### ISSUE THREAD

**Issue by GustavsR** [JeffreyWay/laravel-mix#783]
- Laravel Mix Version: 0.11.4
- Node Version (`node -v`): 7.9.0
- NPM Version (`npm -v`): 4.2.0
- OS: Windows 10 Pro (Version: 1703)

### Description:
If we have relative paths in our CSS (and `processCssUrls` is `true`), then after the processing, these files are moved to `/public/images` or `/public/fonts`. Some people may not like that the files are moved to the root directory and want to move the files to the `/public/assets/images`, for example.

This path is hardcoded in `setup/webpack.config.js`:
```
if (! /node_modules|bower_components/.test(path)) {
    return 'images/[name].[ext]?[hash]';
}

return 'images/vendor/' + path
    .replace(/\\/g, '/')
    .replace(
        /((.*(node_modules|bower_components))|images|image|img|assets)\//g, ''
    ) + '?[hash]';
```

### Steps To Reproduce:

There is no support for this.

A new config variable could be added to move the files to a custom directory.

**Comment by JeffreyWay** [comment]
I'd rather just stick with a common default for now.

**Comment by TheKalpit** [comment]
+1 for the issue

Just ran into this situation. The website is located in a sub-directory, so it is absolutely necessary to add "/base/path/" before the generated paths.

**Comment by pxwee5** [comment]
+1

**Comment by stefro** [comment]
+1

**Comment by andonovn** [comment]
+1

**Comment by Froxz** [comment]
+1
