### ISSUE TITLE
Uncaught ReferenceError: Vue is not defined

### ISSUE THREAD

**Issue by kiwo12345** [JeffreyWay/laravel-mix#786]
In my webpack mix file I have set `.extract(['vue',... `

Then
`mix.autoload({ validator: ['validator', 'window.validator'], vue: ['window.Vue', 'Vue'] });`

And lastly removed any Vue refrence in app.js and bootstrap.js

But now when I try to use Vue in other js files I still get the error: **Uncaught ReferenceError: Vue is not defined**

So how can I exctract Vue and still use it in other files like: `var app = new Vue({...`

**Comment by ruchern** [comment]
Keep your Vue settings as per factory default for Laravel-Mix, which is to leave `window.Vue = require('vue')` inside `bootstrap.js`

It worked for me and probably many others too.

**Comment by LuisAlejandro** [comment]
@slidenerd I have the same confusion as you.
