### ISSUE TITLE
Cache in `storage/framework/cache` incompatible with Envoyer

### ISSUE THREAD

**Issue by gstjohn** [JeffreyWay/laravel-mix#79]
Hey Jeff,

Been getting Mix rolled into a project this week and made my first deploy with Envoyer to a dev server. I got a message regarding being unable to find the Mix.json file when using `{{ mix(...) }}`. The issue occurs on Envoyer because the `storage` directory is symlinked on deploy.

Is this something you are coordinating with Taylor on handling or should the Mix.json file find a new home? I ended up overriding the cache path to be the root directory and everything works fine now. Just thought I would raise the issue.

**Comment by JeffreyWay** [comment]
I haven't yet talked with Taylor about the default cache path for Laravel projects. We will in time for 5.4. So, yeah, until then, I'd use setCachePath() to set your own.
