### ISSUE TITLE
{...} notation in ES6 for React action

### ISSUE THREAD

**Issue by jaroslawziolkowski** [JeffreyWay/laravel-mix#792]
- Laravel Mix Version: 0.8.3
- Node Version 7.0.0
- NPM Version 3.10.8
- OS: macOS 10.12.4
### Description:
Why I can use full ES6 syntax? For example transpiler throw error when I use 
```
{config: ...config, property: 'x'}

```
I also try to set babelrc file
```
{
  "presets": ["es2016","react"]
}
```
(I have es2016 package) and is the same result. If I use it outside laravel and laravel-mix it works.

**Comment by BilyFish1991** [comment]
See  [#76](https://github.com/JeffreyWay/laravel-mix/issues/76#issuecomment-271920174 "#76")

**Comment by ruchern** [comment]
ES6 comes working out of the box with Laravel-Mix.

Try updating your mix and npm versions.
