### ISSUE TITLE
Autoprefixer not applied when using standaloneSass

### ISSUE THREAD

**Issue by maiolica** [JeffreyWay/laravel-mix#793]
- Laravel Mix Version: 0.11.4
- Node Version: 6.9.4
- NPM Version: 3.10.10
- OS: Win 7 64bit

### Description:

Don't know if this is intended or not: css files compiled with standaloneSass aren't passed through autoprefixer.
Try with a css file containing any rule that require a prefix as today, like:
`body { backface-visibility: hidden; }`

**Comment by PascaleBeier** [comment]
Does your autoprefixer configuration include IE 9 or below? Because backface visibility works in all recent browsers and won't be autoprefixed with the default configuration.

See [backface-visibility on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/backface-visibility)

**Comment by maiolica** [comment]
Try with a scss file with this rule:
`body { background-image: linear-gradient(45deg, blue, red); }`

sass() returns:
```
body {
  background-image: -webkit-linear-gradient(45deg, blue, red);
  background-image: linear-gradient(45deg, blue, red);
}
```

standaloneSass() returns:
```
body {
  background-image: linear-gradient(45deg, blue, red);
}
```

**Comment by PascaleBeier** [comment]
My bad!

Looking throught the standaloneSass() implementation clarifies that the result is not postcss'd and therefore not autoprefixed. So this is literally standaloneSass without any postprocessing more than compiling.

Source: https://github.com/JeffreyWay/laravel-mix/blob/master/src/Preprocessors/StandaloneSass.js

**Comment by maiolica** [comment]
I see... Any chance to include autoprefixer only by default for standaloneSass()?

**Comment by JeffreyWay** [comment]
Yeah standaloneSass() is intended to be simple Sass compilation and nothing else. For other Sass compile steps, try to use mix.sass() instead.
