### ISSUE TITLE
Error while parsing JSON after new installation of Laravel / stand-alone.

### ISSUE THREAD

**Issue by thmsbkkr** [JeffreyWay/laravel-mix#795]
- Laravel Mix Version: 0.11.4
- Node Version: v7.3.0
- NPM Version: 4.5
- OS: macOS Sierra

### Description:

Getting this error for a couple of days now when trying to set up a fresh Laravel project.
Already tried to remove node_modules and reinstall, but does not work. Also tried to use it outside of Laravel but it's giving me the same error. 

```
Syntax Error: Error while parsing JSON - Unexpected end of JSON input
    at JSON.parse (<anonymous>)
```

Screenshot link:
https://www.dropbox.com/s/gq5nkg60kqqg3af/Fullscreen_10_05_2017__14_43.png?dl=0

### Steps To Reproduce:

1. Install new Laravel project (laravel new project-name)
2. Run: npm install / yarn
3. Run: npm run dev / yarn dev

**Comment by ruchern** [comment]
Your error provides too little information.

**Comment by thmsbkkr** [comment]
I've added a screenshot of my terminal output. Maybe that will help.. 

Thanks for the quick response. :+1:

**Comment by ruchern** [comment]
Did you use JSON anywhere in your `app.js`?

**Comment by thmsbkkr** [comment]
That's the thing. It's a fresh install. Haven't touch any of the asset files.

**Comment by thmsbkkr** [comment]
@JeffreyWay Is this something u've came across maybe?

**Comment by ruchern** [comment]
@thmsbkkr My bad, I guess I have completely missed the fact that it was a fresh install. Let me try.

**Comment by ruchern** [comment]
<img width="570" alt="screen shot 2017-05-10 at 11 06 44 pm" src="https://cloud.githubusercontent.com/assets/10343662/25905754/633957e0-35d5-11e7-8dfe-9b662d258955.png">

Fresh install. Not a problem. Check your environment.

**Comment by thmsbkkr** [comment]
I will, thanks !

**Comment by thmsbkkr** [comment]
Removed node and npm, did a system check and installed it again. 
It's working again! Should of tried that sooner .. 

Thank you!

**Comment by ruchern** [comment]
Glad that it worked for you.
