### ISSUE TITLE
No iconfont in mix?

### ISSUE THREAD

**Issue by artemartemov** [JeffreyWay/laravel-mix#796]
Just wondering if there is plans to implement an svg -> iconfont plugin. 

I found a webpack plugin called webfont, however didn't have much luck installing with laravel mix.

**Comment by PascaleBeier** [comment]
Now this is pretty vague. You can pretty much do everything you can with webpack already - just pass in the webpack configuration for your included loader.

When you show off what you tried we may be able to point your way! 👍
