### ISSUE TITLE
Watching and changing a JS file, triggers the sass file compiling

### ISSUE THREAD

**Issue by AndreasHerss** [JeffreyWay/laravel-mix#797]
### Info:
Laravel mix: 0.11.4
Node: 7.9.0
npm: 4.2.0
OS: Win10

### Description
My problem is when running *npm run watch* and then changing my accountplan-app.js file, it also compiles my sass files, this happens no matter what js files i changes, and no matter the order in my *webpack.mix.js* file. 

If i change the order in the *webpack.mix.js* file, it just tells another file in the watch result, alway the file just before the sass line. 

### Webpack.mix.js
![2017-05-11 10_06_42-netconomy - d__projekter_netconomy-1 - _webpack mix js - phpstorm 2017 1](https://cloud.githubusercontent.com/assets/6894019/25939296/9f202268-3632-11e7-927b-fecbd49456f5.png)

### Result of the npm run watch
![2017-05-11 10_07_04-netconomy - d__projekter_netconomy-1 - _resources_assets_js_accountplan_acc](https://cloud.githubusercontent.com/assets/6894019/25939297/9f26a822-3632-11e7-927e-dd7c8bb179d1.png)

**Comment by JeffreyWay** [comment]
It's because the compiled Sass is extracted from your compiled JS file. You could use mix.standaloneSass() if you want a Sass build that knows nothing about Webpack.
