### ISSUE TITLE
mix.copy not working and mix.combine not working with "watch"

### ISSUE THREAD

**Issue by arnbondzinskas** [JeffreyWay/laravel-mix#799]
- Laravel Mix Version: 0.11.4
- Node Version: v7.10.0
- NPM Version: 4.5.0
- OS: Windows 10 Pro

### Description:

Hello, when I try to use mix.copy I get following error:

> /node_modules/webpack/bin/webpack.js:315
>                 throw e;
>                 [^]
> 
> TypeError: arguments[i].apply is not a function
>     at Compiler.apply (/node_modules/tapable/lib/Tapable.js:306:16)
>     at webpack (/node_modules/webpack/lib/webpack.js:32:19)
>     at processOptions (/node_modules/webpack/bin/webpack.js:305:14)
>     at Object.<anonymous> (/node_modules/webpack/bin/webpack.js:363:1)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.runMain (module.js:605:10)
>     at run (bootstrap_node.js:427:7)
>     at startup (bootstrap_node.js:151:9)
>     at bootstrap_node.js:542:3

Also, when I try to use mix.combine or mix.scripts for my .js files it seems that webpack is not compiling my js files because when I make changes for any of mine .js files the watch is not working, also I can't see any js files compiled. I mean when I launch 

> npm run dev 

and I get the file list that were versioned and compiled there is no .js files except app.js.

### Steps To Reproduce:

**webpack.mix.js**

```
const {mix} = require('laravel-mix')
mix.js('resources/assets/js/app.js', 'public/js');


mix.copy('resources/assets/images', 'public/images');
mix.copy('resources/assets/images', 'public/build/images');
mix.copy('resources/assets/fonts', 'public/build/fonts');



mix.combine(['resources/assets/js/*'], 'public/js/front.js');
mix.combine(['resources/assets/admin-js/*'], 'public/js/admin.js');

mix.version();


```

**package.json**

```
{
  "version": "0.11.4",
  "description": "Laravel Mix is an elegant wrapper around Webpack for the 80% use case.",
  "main": "src/index.js",
  "scripts": {
    "webpack": "cross-env NODE_ENV=development webpack --progress --hide-modules",
    "dev": "cross-env NODE_ENV=development webpack --watch --watch-poll --progress --hide-modules",
    "hmr": "cross-env NODE_ENV=development webpack-dev-server --inline --hot",
    "production": "cross-env NODE_ENV=production webpack --progress --hide-modules",
    "test": "sudo nyc ava --verbose",
    "posttest": "nyc report --reporter=html"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/JeffreyWay/laravel-mix.git"
  },
  "bugs": {
    "url": "https://github.com/JeffreyWay/laravel-mix/issues"
  },
  "homepage": "https://github.com/JeffreyWay/laravel-mix#readme",
  "keywords": [
    "laravel",
    "webpack",
    "laravel elixir",
    "laravel mix"
  ],
  "author": "Jeffrey Way",
  "license": "MIT",
  "dependencies": {
    "autoprefixer": "^6.7.3",
    "babel-core": "^6.20.0",
    "babel-loader": "^6.2.9",
    "babel-preset-env": "^1.3.0",
    "browser-sync": "^2.18.7",
    "browser-sync-webpack-plugin": "^1.1.4",
    "chokidar": "^1.6.1",
    "clean-css": "^4.0.7",
    "concatenate": "0.0.2",
    "cross-env": "^3.1.3",
    "css-loader": "^0.14.5",
    "dotenv": "^4.0.0",
    "extract-text-webpack-plugin": "^2.0.0-rc.3",
    "file-loader": "^0.10.1",
    "friendly-errors-webpack-plugin": "^1.5.0",
    "fs-extra": "^2.1.2",
    "html-loader": "^0.4.4",
    "img-loader": "^2.0.0",
    "less": "^2.7.1",
    "less-loader": "^2.2.3",
    "lodash": "^4.17.4",
    "md5": "^2.2.1",
    "mkdirp": "^0.5.1",
    "node-sass": "^4.0.0",
    "on-build-webpack": "^0.1.0",
    "path": "^0.12.7",
    "postcss-load-config": "^1.0.0",
    "postcss-loader": "^1.2.1",
    "resolve-url-loader": "^2.0.0",
    "sass-loader": "^6.0.0",
    "style-loader": "^0.13.1",
    "uglify-js": "^3.0.1",
    "vue-loader": "^11.1.3",
    "vue-template-compiler": "^2.0.0",
    "webpack": "~2.3.0",
    "webpack-chunk-hash": "^0.4.0",
    "webpack-dev-server": "^2.4.0",
    "webpack-merge": "^4.0.0",
    "webpack-notifier": "^1.4.1",
    "webpack-stats-plugin": "^0.1.4",
    "yargs": "^7.0.2"
  },
  "devDependencies": {
    "ava": "^0.19.1",
    "nyc": "^10.0.0",
    "sinon": "^1.17.7"
  },
  "engines": {
    "node": ">=6.0.0"
  }
}

```

**Comment by PascaleBeier** [comment]
Remember to paste in *your* package.json 😄 

Seems more like a problem of a library you are using. Can you provide more information?

**Comment by ruchern** [comment]
Replace `mix.combine()` with `mix.scripts()` for your js files.

**Comment by arnbondzinskas** [comment]
The result is the same, I get front.(hash).js and admin.(hash).js using scripts and combine but I can't get any of my js files watched. I mean when I do some changes in my js files the it's not compiled again automaticaly and it seems bootstrap is broken because I get errors in my page:

```
Uncaught ReferenceError: require is not defined
    at bootstrap.js:19

Uncaught TypeError: $(...).carousel is not a function
    at (index):1030
```

**mix-manifest.json**

```
{
  "/js/app.js": "/js/app.1b133432c70510c76e6c.js",
  "/css/admin_main.css": "/css/admin_main.67332f57cf6c1be402980c7702b45fbd.css",
  "/css/auth.css": "/css/auth.161035da4726a8e1a28722f5d7b2bcff.css",
  "/css/font-awesome.css": "/css/font-awesome.0efd968212da30d2d1cda8a6813f5215.css",
  "/css/main.css": "/css/main.77f0d43eeaa1625ffb07cacbecac97d0.css",
  "/js/front.js": "/js/front.671720d3044cc0a28ec272cf8734a50e.js",
  "/js/admin.js": "/js/admin.6290be2e97868d6c7f71281953c0027c.js"
}
```

**Comment by jameshulse** [comment]
`.babel()` is also not working with 'watch'. When I change these files the bundle is not rebuilt.

**Comment by EugeneAndrievsky** [comment]
if you run "watch" script -  it doesn't copy, but "dev" script copies.
