### ISSUE TITLE
.vue files not being processed correctly

### ISSUE THREAD

**Issue by sailingdeveloper** [JeffreyWay/laravel-mix#80]
I am using all the default settings, but when I run `npm run webpack`, I get the following error:

Module parse failed: 
```
/Users/Workspace/barcode/resources/assets/js/components/Events/Tickets.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <template>
|     <div class="Tickets">
|         <div class="row">
```

**Comment by sailingdeveloper** [comment]
I am pretty sure it's my own fault, but I can't figure it out

**Comment by JeffreyWay** [comment]
More information, please. What does your `webpack.mix.js` file look like?

**Comment by sailingdeveloper** [comment]
Only `mix.js('resources/assets/js/app.js', 'public/js/');`. `webpack.config.js` copied from the `setup` directory as stated in the documentation.

**Comment by JeffreyWay** [comment]
What do you have for app.js and Tickets.vue?

**Comment by sailingdeveloper** [comment]
Nothing special, really: https://gist.github.com/sailingdeveloper/6d46cb1055b15c4f4b338057121ba25a

**Comment by sailingdeveloper** [comment]
I did notice, however, that the documentation is different from the way you described it in the Laracasts video in the Vue series.

**Comment by zue666** [comment]
Hello,
If you use the default webpack.config.js
Make sure that you import/use laravel-mix like so:
let mix = require('laravel-mix').mix

And then run your npm script again.

**Comment by fortael** [comment]
Same
![image](https://cloud.githubusercontent.com/assets/16315079/21919965/be4d0808-d990-11e6-9aeb-e854a3429c55.png)
![image](https://cloud.githubusercontent.com/assets/16315079/21919979/daca2d8a-d990-11e6-9f50-d3c74b15499a.png)

**Comment by sailingdeveloper** [comment]
Weirdest thing: I just created a fresh Laravel app (develop), pulled in laravel-mix and set it up according to the documentation, and everything does work... I am running this my Mac at work, so I will try to figure out what I did wrong at home.

**Comment by nmfzone** [comment]
What mix version that you use? I just believe you aren't using the newest version of the Laravel Mix.

**Comment by JeffreyWay** [comment]
I'm going to close this, if you got it working after all. :)

**Comment by sailingdeveloper** [comment]
I found out what's wrong: I installed Laravel Mix in a project that already has Laravel Elixir installed. When I removed laravel-elixir from`package.json`, removed the`node_modules` directory and reinstalled, everything worked correctly.

**Comment by cmosguy** [comment]
Oh my gosh this is a huge red flag this should be in the docs I spent a lot of time on this today!

**Comment by mirzap** [comment]
Thanks for the response.. Huge time saver 👍
