### ISSUE TITLE
Bootstrap does not compile if was included into scss style section into vue component.

### ISSUE THREAD

**Issue by norkfy** [JeffreyWay/laravel-mix#800]
- Laravel Mix Version: 0.11.4
- Node Version: v7.8.0
- NPM Version: 4.2.0
- OS: macOS Sierra 

### Description:

When in vue component is scss bootstrap include, webpack build is failing.
Code in vue component file like this:

```
<style lang="scss">
  $bootstrap-sass-asset-helper: true;
  @import "~bootstrap-sass/assets/stylesheets/bootstrap";
</style>
```
won't compile. 

Error is:

```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                       

 error  in ./src/components/Hello.vue

Module parse failed: /Users/norkfy/projects/test-mix/node_modules/css-loader/index.js!/Users/norkfy/projects/test-mix/node_modules/vue-loader/lib/style-compiler/index.js?{"id":"data-v-040b1f58","scoped":false,"hasInlineConfig":true}!/Users/norkfy/projects/test-mix/node_modules/sass-loader/lib/loader.js!/Users/norkfy/projects/test-mix/node_modules/vue-loader/lib/selector.js?type=styles&index=0!/Users/norkfy/projects/test-mix/src/components/Hello.vue Unexpected token (2:4290)
You may need an appropriate loader to handle this file type.
| exports = module.exports = require("../../node_modules/css-loader/lib/css-base.js")();

```
### Steps To Reproduce:

Clone this test repository: https://github.com/norkfy/text-mix
run "npm run dev"
open index.html

or add below bootstrap-sass import into vue component

```
  $bootstrap-sass-asset-helper: true;
  @import "~bootstrap-sass/assets/stylesheets/bootstrap";
```

### What can be fixed

I've noticed that laravel mix uses css-loader@0.14.5, this version looks very old. Then I've tried install last version of css-loader and seems like build works. Why laravel mix is using such older css-loader?

**Comment by JeffreyWay** [comment]
> Why laravel mix is using such older css-loader?

It's time to check again, but it was originally because a later version of css-loader introduced a regression that drastically hurt compile speeds. 

As for your question, I think it's because we don't compile anything from the node_modules directory to help with performance. It's assumed that anything you import will be pre-optimized.
