### ISSUE TITLE
purifyCSS: smaller file size on dev (minify: true) than production

### ISSUE THREAD

**Issue by m-lotze-7o7** [JeffreyWay/laravel-mix#801]
- Laravel Mix Version: 0.11.4
- Node Version (`node -v`): v6.10.2
- NPM Version (`npm -v`): 4.6.1
- OS: Windows

### Description:

webpack.mix.js:
```
...
var lookupCssIn = glob.sync(path.join(__dirname, 'resources/**/*.{vue,js,php,scss}'), {
    ignore: '**/*/app.scss'
});
...
mix.options({
    processCssUrls: false,
    postCss: [
        require('postcss-fixes')(),
        require('postcss-merge-rules')
    ],
    purifyCss: {
        paths: lookupCssIn,
        purifyOptions: {
            info: true,
            rejected: true,
            minify: mix.config.inProduction,
            whitelist: [
                '*modal*'
            ]
        }
    }
});
...
mix.sass('resources/assets/sass/app.scss', 'public/css')
    .version();
...
```

When i run `npm run dev` and set `minify: true` in purifyOptions my app.css will be 237Kb. If i run `npm run production` the file is 251Kb. The list of removed selectors is significant longer on `npm run dev`. 

It seems that in production mode, the css gets minified before it is processed by the purifycss plugin. And the plugin may process an unminified file better. Maybe let purifycss handle the minification if the option is set or do it after purifycss in production mode.

**Comment by JeffreyWay** [comment]
This should be resolved in Mix 1.0.
