### ISSUE TITLE
npm run development error

### ISSUE THREAD

**Issue by bravist** [JeffreyWay/laravel-mix#804]
- Laravel Mix Version: 0.11.4(`npm list --depth=0`)
- Node Version (`7.10.0`): 
- NPM Version (`4.2.0`): 
- OS: macOS 

### Description:

├── axios@0.15.3
├── bootstrap-sass@3.3.7
├── cross-env@3.2.4
├── jquery@3.2.1
├── laravel-mix@0.11.4
├── lodash@4.17.4
└── vue@2.3.3

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chenghuiyong/.npm/_logs/2017-05-13T04_00_13_806Z-debug.log

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.10.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'development' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose run-script [ 'predevelopment', 'development', 'postdevelopment' ]
5 info lifecycle @~predevelopment: @
6 silly lifecycle @~predevelopment: no script for predevelopment, continuing
7 info lifecycle @~development: @
8 verbose lifecycle @~development: unsafe-perm in lifecycle true
9 verbose lifecycle @~development: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/chenghuiyong/Applications/Public/ecshop_discount/node_modules/.bin:/usr/local/bin:/usr/local/git/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle @~development: CWD: /Users/chenghuiyong/Applications/Public/ecshop_discount
11 silly lifecycle @~development: Args: [ '-c',
11 silly lifecycle   'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js' ]
12 silly lifecycle @~development: Returned: code: 2  signal: null
13 info lifecycle @~development: Failed to exec development script
14 verbose stack Error: @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @
16 verbose cwd /Users/chenghuiyong/Applications/Public/ecshop_discount
17 error Darwin 16.5.0
18 error argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "run" "development"
19 error node v7.10.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 2
23 error @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
23 error Exit status 2
24 error Failed at the @ development script 'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the  package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]

```

**Comment by bravist** [comment]
I try to solve it like this

## watch the `package.json`

```php

{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  }

....

```


## execute the command `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`

```bash
$ cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
```


## install cross-env

```bash
$ npm install --global cross-env
```

after that, execute above cross-env command and you can find something, good luck for you

**Comment by ruchern** [comment]
What's the point of this? So did you fixed your problem?

**Comment by bravist** [comment]
@ruchern What i said is how to debug the problem. and i sovle it like that

**Comment by poorya6868** [comment]
![capwwture](https://cloud.githubusercontent.com/assets/24212660/26442216/c80316ba-4148-11e7-82b8-705b38d66ed7.PNG)
how can solve this?

**Comment by ruchern** [comment]
@poorya6868 You are missing `dev` in 

```json
"scripts": {}
```
of the file `package.json`

**Comment by naime-hossain** [comment]
@bravist it's working for.Thanks a lot.i just waste one night for this problem now I am getting rid of it.

**Comment by roddyguy22** [comment]
npm install --global cross-env

....is what worked for me. I'm running on Windows 10.

**Comment by Chi-G** [comment]
img 1
![Screenshot (243)](https://user-images.githubusercontent.com/35651026/132484978-eafc3a5e-5912-4c07-a6af-8f1c34259a3d.png) 
img 1 cont...
![Screenshot (244)](https://user-images.githubusercontent.com/35651026/132484974-0226ab55-66ee-44e8-a3e1-d4419baad7ed.png) 
 how do i solve this when i run `npm run dev` ?

**app.scss** file below 
`@import url('https://fonts.googleapis.com/css?family=Nunito');`
`$font-family-sans-serif: 'Nunito', sans-serif;`
`@import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap";`

**package.json** file
`{`
    `"private": true,`
        `"scripts": {`
              `"dev": "npm run development",`
              `"development": "mix",`
             `"watch": "mix watch",`
             `"watch-poll": "mix watch -- --watch-options-poll=1000",`
             `"hot": "mix watch --hot",`
            `"prod": "npm run production",`
            `"production": "mix --production"`
 `},`

`{`
    `"devDependencies":`
            `"axios": "^0.21",`
            `"bootstrap": "^5.1.1",`
            `"laravel-mix": "^6.0.6",`
           `"lodash": "^4.17.19",`
           `"popper.js": "^1.16.1",`
           `"postcss": "^8.1.14",`
          `"resolve-url-loader": "^4.0.0",`
          `"sass": "^1.39.0",`
          `"sass-loader": "^12.1.0"`
  `}`

**webpack.mix.js** file
`const mix = require('laravel-mix');`

`mix.js('resources/js/app.js', 'public/js');`
    
`mix.sass('resources/sass/app.sass', 'public/css')`
   ` .sass('resources/sass/admin.sass', 'public/css/admin');`
