### ISSUE TITLE
publicPath is not set when not using laravel

### ISSUE THREAD

**Issue by askaoru** [JeffreyWay/laravel-mix#807]
- Laravel Mix Version: 0.11.4
- Node Version: 7.10.0
- NPM Version: 4.2.0
- OS: OSX Yosemite 10.10.1

When using laravel mix as a standalone without laravel, the publicPath variable wont be set. So when running npm run hot or npm run dev, mix will try to create the hot file in volume root `/hot`. This will most likely cause a permission issue in unix based system. Sure running it with sudo will solve this, but i dont think the hot file is intended to be there right? Sorry if there's anything that i missed. 

Refer https://github.com/JeffreyWay/laravel-mix/blob/master/src/Mix.js#L80.

This issue https://github.com/JeffreyWay/laravel-mix/issues/785 most likely caused by this issue too.

**Comment by stevieg83** [comment]
yeah, I'm seeing similar. A non-Laravel project but the publicPath is `public`.

The `hot` file used to sit in the root of my project before but now tries to go to volume root like you've said.

**Comment by krisanalfa** [comment]
Confirmed. Running a test script from this repo could simply reproduce this issue.

**Comment by sebastiansulinski** [comment]
What Jeffrey has suggested in one of the issues is to use `setPublicPath` method for use outside of Laravel:

```javascript
mix.setPublicPath('public')
```

**Comment by askaoru** [comment]
Then would it be good to add that line in [webpack.mix.js](https://github.com/JeffreyWay/laravel-mix/blob/master/setup/webpack.mix.js) by default? since the files in the setup dir is mostly only pulled by mix user outside of laravel. Then it wont be confusing to new user encountering the permission issue.

**Comment by stevieg83** [comment]
@sebastiansulinski yeah I tried setting `setPublicPath` as well but that didn't work for me. What I found did work though was keeping `artisan` in the root of my project, even although it's a non-Laravel project. 

I basically copied the working Laravel repo piece by piece and tried `npm run hot` each time until it broke. 

Not an ideal solution but it works for now.

**Comment by askaoru** [comment]
@stevieg83 when you copied `artisan` to your project you just basically lied to mix pretending you are using laravel. The `artisan` file is how mix is determining whether you are using laravel or not. https://github.com/JeffreyWay/laravel-mix/blob/master/src/Mix.js#L141

**Comment by stevieg83** [comment]
@askaoru good to know :) I guess if it works, it's not a huge inconvenience to have the file there.

**Comment by JeffreyWay** [comment]
Yeah, you have to set `mix.setPublicPath()` for non-Laravel projects. This is because we don't know where your public folder should be, like we do with Laravel apps.

**Comment by decadence** [comment]
@JeffreyWay how to set public path to project root folder? Slash doesn't work.
https://github.com/JeffreyWay/laravel-mix/issues/720#issuecomment-305521731

**Comment by jsgv** [comment]
I suggest that `public` be the default path for the package. 

My project is Laravel, but I am using Docker and multi-stage builds to deploy and test. At the time to `mix.version()` I would get an error and took me a while to realize what was going on.

I fixed it by just `COPY artisan /app`, but could've avoided if there was a default path. It is a pretty common default path as well.
