### ISSUE TITLE
Imported js modules not being run through babel

### ISSUE THREAD

**Issue by robbyrice** [JeffreyWay/laravel-mix#815]
- Laravel Mix Version: 0.11.4
- Node Version (`node -v`): 4.6.1
- NPM Version (`npm -v`): 6.10.3
- OS: Ubuntu 16.04

## Description:
Running `npm run production` throws an error
```
/js/app.js from UglifyJs
Unexpected token: name (storedTransformPropertyName_) [./~/@material/drawer/util.js:20,0][/js/app.js:157,4]
```
that leads me to believe that Mix is not applying babel transformation to imported modules in the main js file. If I comment out the imports in the app.js file then the script runs without error. I don't have a .babelrc file and I've tried removing the node_modules folder and reinstalling everything.

### contents of package.json
```
{
  "dependencies": {
    "material-components-web": "^0.11.0",
    "material-design-icons": "^3.0.1",
    "normalize.css": "^7.0.0"
  },
  "devDependencies": {
    "laravel-mix": "^0.11.0"
  },
  "scripts": {
    "dev": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  }
}
```

### contents of webpack.mix.js
```
const { mix } = require('laravel-mix');

mix.sass('resources/assets/sass/app.scss', 'public/css', {
     includePaths: ['node_modules']
   })
   .js('resources/assets/js/app.js', 'public/js/app.js');

if (mix.config.inProduction) {
    mix.disableNotifications();
}
```

### contents of app.js
```
import {MDCIconToggle} from '@material/icon-toggle';
import {MDCTemporaryDrawer} from '@material/drawer';
import {MDCTextfield} from '@material/textfield';

let drawer = new MDCTemporaryDrawer(document.querySelector('.mdc-temporary-drawer'));
```

**Comment by ruchern** [comment]
Remove `includePaths: ['node_modules']` from the `mix.sass()`

You should not be doing this.

Instead, inside of `app.scss`, import the sass from `node_modules` directory.

Example:
```
@import "~/package/sass/package.scss"
```
Where package refers to the package of the one that you want to use.

**Comment by robbyrice** [comment]
Thanks for your response, but it doesn't address my initial issue (which was about js), and your suggestion unfortunately doesn't work for me. If I remove the includePaths option and use the kind of @import to import my sass from node_modules that you gave in your example, I get a `File to import not found or unreadable` error.
Would you mind explaining why I shouldn't be using `includePaths: ['node_modules']`?

**Comment by ruchern** [comment]
Each package should come with tools that you can build it yourself or have already been built inside the `dist` directory. If you want to rebuild the package with some of your edits, you should go into that particular root folder of the package and build it using the instructions provided from their Github repository.

**Comment by robbyrice** [comment]
Ok, thanks for the suggestion, but it's not exactly appropriate for my project.  I'm currently starting to integrate the new [Material Components for Web](https://material.io/components/web) and I am importing only the components that I need so I've got a large number of imports in the app.scss file.

**Comment by ruchern** [comment]
Try this: https://github.com/material-components/material-components-web/#css

**Comment by robbyrice** [comment]
Thank you once again for your response, but css is not my problem, that is working fine.  The problem is with uglifyjs not understanding es2015.

**Comment by ruchern** [comment]
Right. Sorry for going off track with your issue. Guess I misinterpreted.

**Comment by robbyrice** [comment]
Not a problem.

**Comment by robbyrice** [comment]
So what I ended up doing is copying the main Laravel Mix setup/webpack.config.js file to my root directory and removing the exclude parameter from the js test on this line https://github.com/JeffreyWay/laravel-mix/blob/master/setup/webpack.config.js#L148.  This means that I'll have to maintain my own version of this file, but at least npm run production is working now.  Hope this helps someone else.

**Comment by ruchern** [comment]
@robbyrice The reason why @JeffreyWay wrote it this way to exclude `node_modules` because the package have their own way to build the assets and should not let Webpack do the building.

**Comment by robbyrice** [comment]
Yeah, I understand but this is what I need to get my project to work.

**Comment by whodidthis** [comment]
Might be worth looking into [https://github.com/JeffreyWay/laravel-mix/blob/master/docs/quick-webpack-configuration.md](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/quick-webpack-configuration.md). Maybe you could be able to override this particular configuration.

I would also use this project myself if this is possible.

**Comment by robbyrice** [comment]
I've tried just overriding this particular configuration, but for the moment I'm not having any luck.  For now the quickest and simplest approach is maintaining my own webpack.config.js file.
