### ISSUE TITLE
Destination path is wrong when copying multiple files

### ISSUE THREAD

**Issue by santigarcor** [JeffreyWay/laravel-mix#816]
- Laravel Mix Version: 0.11.4 (`npm list --depth=0`)
- Node Version (`node -v`): v6.10.3
- NPM Version (`npm -v`): 3.10.10
- OS: Ubuntu 16.04

### Description:
When using the `copy` method to copy multiple files, it uses the full path inside the destination path instead of using only the file name.

### Steps To Reproduce:

```
mix.copy([
  'resources/assets/img/avatar.jpg',
  'resources/assets/img/avatar2.jpg',
  'resources/assets/img/avatar3.jpg',
], 'public/img');
```
It will copy the files to `public/img/resources/assets/img/`

**Comment by ruchern** [comment]
Are the 3 files `avatar.jpg`, `avatar2.jpg`, `avatar3.jpg` the only files in that directory? If so, try using 

```javascript
mix.copyDirectory('resources/assets/img', 'public/img')
```

**Comment by santigarcor** [comment]
No, i can't do that because there are more files inside the folder

**Comment by ruchern** [comment]
@santigarcor Yeah I was just assuming that you only had that 3 and then you can do that.
