### ISSUE TITLE
ES2015 & Uglify issues

### ISSUE THREAD

**Issue by pix2D** [JeffreyWay/laravel-mix#817]
- Laravel Mix Version:  0.11.4
- Node Version (`node -v`): v7.8.0
- NPM Version (`npm -v`): 4.2.0
- OS: macOS Sierra

### Description:

So I'm developing a custom npm package that is just for my own internal use. I had this package in `~/Sites/_node_modules/my-package` and I used `npm link` to use it in my Laravel projects.

Now when I ran `npm run dev` everything compiled fine **BUT** the resulting file had ES2015 code. If I ran `npm run production` then Uglify broke (since it doesn't understand ES2015).

After tons of troubleshooting I somehow stumbled upon the fact that if I put my package **ANYWHERE** else it worked perfectly fine (ES2015 was transpiled even when running `npm run dev` and `npm run production` worked fine too). If I moved it back to the **_node_modules** folder it instantly broke again.

I'm not sure if this is a bug with Laravel Mix, Webpack, OS specific or what. I'm not even sure it is a bug, perhaps it's expected behavior if one has **_node_modules** in the folder path. In any case I thought I'd mention it here and hopefully it will save someone else the headaches I've gone through the past few weeks.

**Comment by JeffreyWay** [comment]
I think we have it set up so that Mix ignores anything compilation in the node_modules directory, since those files are expected to be pre-optimized. It speeds up performance a good bit with that setting turned on.
