### ISSUE TITLE
Bootstrap's JavaScript requires jQuery with bootstrap build

### ISSUE THREAD

**Issue by Shamoncushbu** [JeffreyWay/laravel-mix#819]
const { mix } = require('laravel-mix');    
    mix.js([
            'public/admin/js/jquery.js',
            'public/admin/js/bootstrap.min.js',
        ],'production/js/final.js');

But when i include `final.js` i got the following error

    Uncaught Error: Bootstrap's JavaScript requires jQuery

I've installed the jquery with `npm install jquery --save` but still i got above error

**Comment by ruchern** [comment]
In `app.js` add

```javascript
window.$ = window.jQuery = require('jquery')
```

**Comment by enghelewa** [comment]
@Shamoncushbu  I had this problem before. The problem solved just by using `scripts` instead of `js` for vanilla JS "as mentioned in [docs](https://laravel.com/docs/5.4/mix#vanilla-js)"

**Comment by ProExpertProg** [comment]
For all the future googlers, I solved the problem with

```
mix.autoload({
    jquery: ['$', 'window.jQuery',"jQuery","window.$","jquery","window.jquery"]
});
```

**Comment by ikskoder** [comment]
@ProExpertProg 
It works! Thank you!!!

**Comment by gocanto** [comment]
This solution worked for me:

```js
mix.autoload({
    jquery: ['$', 'window.jQuery',"jQuery","window.$","jquery","window.jquery"]
});
```
 
thought I would like to know why the following one did not.

```js
window.$ = window.jQuery = require('jquery')
```


Thanks.

**Comment by ProExpertProg** [comment]
@gocanto because bootstrap is loaded separately (in another closure) and jQuery has to be injected by webpack. `mix.autoload(....)` tells mix where does jQuery need to be injected, so whenever webpack finds `$` or `window.$` etc., it will inject jQuery

**Comment by gocanto** [comment]
Oh ok. Thanks a lot

**Comment by rimatla** [comment]
@ProExpertProg In what file did you add your **mix.autoload**? I'm using a creat-react-app and getting the same error as the trend here.

**Comment by ProExpertProg** [comment]
`webpack.mix.js` I'm pretty sure.

>

**Comment by Piterden** [comment]
Loaded from CDN before main.js for legacy Elixir...

**Comment by bilalnaseer** [comment]
Not working for me added 
`mix.autoload({
    jquery: ['$', 'window.jQuery',"jQuery","window.$","jquery","window.jquery"]
})`

in webpack.mix.js

Still getting error http://prntscr.com/s9nld6

**Comment by ProExpertProg** [comment]
@bilalnaseer did you figure it out?
