### ISSUE TITLE
npm run production fail to uglify

### ISSUE THREAD

**Issue by fbmfbm** [JeffreyWay/laravel-mix#823]
Hi all,

- Laravel Mix Version: 0.11.4
- Node Version : 6.10.3
- NPM Version : 4.6.1
- OS: OSX 10.11.6

### Description: when run : npm run production it faill with error on uglify 
(Unexpected token: punc (() ..... ) 

It seam to be a babel error but can't resolve that.

I' have add an .babelrc with 
`
{
  'presets': [
    ['es2015', { 'modules': false }]
  ]
}
`

but it didnt resolve the pbm.

Any one have some way to point me to solution ?

fbm

**Comment by bungcip** [comment]
I also has same issue with uglify. My current workaround is to use `Babili`.
my webpack.mix.js
```javascript
const { mix } = require('laravel-mix');
const BabiliPlugin = require('babili-webpack-plugin');
const webpack = require('webpack');
const webpackConfig = {
 ...
};

...

if (mix.config.inProduction) {
    webpackConfig.plugins.push(new BabiliPlugin());

    mix.options({
        uglify: false
    });
    mix.disableNotifications();
    //    mix.version();
    
} else {
    mix.sourceMaps();
}

mix.webpackConfig(webpackConfig);

```

**Comment by fbmfbm** [comment]
Hi bungcip,
Thnak's for this workaround. i'll try it.
But i'm not very fluent with webpack and not sure how to make my config in laravel replacement...
hop i can make it.
fbm

**Comment by dskozin** [comment]
bungcip, thanks for help!

But i'm find in webpack.mix.js  section
`if (Mix.inProduction)`
and do this 
`
        new BabiliPlugin()

        //new webpack.optimize.UglifyJsPlugin(Mix.options.uglify)
`

**Comment by dev-seahouse** [comment]
i'm having similar issue here trying to require foundation framework javascript
```
app.js
-------
require('foundation-sites/js/foundation.core.js')
mix.js
-----
 mix.js('resources/assets/js/app.js', 'public/js')
```
output: 
```
/js/foundation.js from UglifyJs
Unexpected character '`' [./~/foundation-sites/js/foundation.core.js:56,0]
```

**Comment by jbruni** [comment]
I just had this  `Unexpected token: punc` issue, and this is how I resolved it, @fbmfbm:

My `.babelrc` was:

```
{
  "plugins": ["transform-object-rest-spread"]
}
```

I have changed it to:

```
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
          "browsers": ["> 2%"],
          "uglify": true
      }
    }]
  ],
  "plugins": ["transform-object-rest-spread"]
}
```

The fact is: when we use a custom `.babelrc` file, [the default Laravel Mix configuration for babel](https://github.com/JeffreyWay/laravel-mix/blob/bfce0e75879d243dae4f57c6a7096291f75ad934/src/config.js#L196-L222) **is lost**.

So, I have prepended the lost default configuration to my custom `.babelrc`  configuration, and got it working.

**Comment by JeffreyWay** [comment]
> The fact is: when we use a custom .babelrc file, the default Laravel Mix configuration for babel is lost.

I agree that this can be confusing. The 1.0 release of Mix merges your Babel config in with ours to prevent this issue from popping up.

**Comment by LorrainInfinity** [comment]
Hi everyone!

I'm facing the very same problem (Unexpected token: punc (() ..... ).  All my npm packages are up to date and I can't figure out how to solve this.  I tried absolutely everything :/

**Comment by Dsudenfield** [comment]
I get this output as well:
```
/js/foundation.js from UglifyJs
Unexpected character '`' [./~/foundation-sites/js/foundation.core.js:56,0]
```

Does anybody have the answer for this. There has to be an answer to this problem and I cant seem to find anything on any forum.

I read on another thread to use this so it doesn't transpile any of the packages in the node_module folder.
```  
.webpackConfig({
        module: {
            rules: [
                {
                    test: /\.jsx?$/,
                    exclude: /node_modules(?!\/foundation-sites)|bower_components/,
                    use: [
                        {
                            loader: 'babel-loader',
                            options: Config.babel()
                        }
                    ]
                }
            ]
        }
    });
```
that doesn't error but it also doesn't compile the file when running `npm run production`

**Comment by tillkruss** [comment]
Checkout https://github.com/JeffreyWay/laravel-mix/issues/1216.

**Comment by Dsudenfield** [comment]
@tillkruss Looks like you have found a precompiled version of the package you were using. Is there a precompiled version of foundation-sites? I have not seen this.

**Comment by sebastiaanluca** [comment]
Any update on this, @JeffreyWay? Having it in the latest version Mix when using `@ckeditor/ckeditor5-build-classic` (an ES2015 package). It contains backticks to echo variables, and uglifying using `uglify-js` instead of (`uglify-es`) fails:

```
ERROR in /assets/js/vendor.js from UglifyJs
Unexpected character '`' [/assets/js/vendor.js:1,47183]
```

**Comment by mukesh17mj** [comment]
Same issue : **UglifyJs Unexpected token: name (i) [./~/jspdf/dist/jspdf.es.min.js**

**.babelrc** is as 

`{

`"presets": [`
`["es2015",`
`{`
`"modules": false`
`}`
`]`
`],`
`"plugins": [`
`[`
`"transform-es2015-arrow-functions",`
`{`
`"spec": true`
`}`
    `],`
    `"transform-es2015-template-literals",`
    `"transform-object-rest-spread"`
  `]`
`}`

and 

**webpack.mix.js** is as:

`const { mix, config } = require('laravel-mix');`
`const webpackConfig = {`
    `resolve : {`
       ` alias : { 'videojs-contrib-hls' : __dirname + '/node_modules/videojs-contrib-hls/dist/videojs-contrib-hls' }`
    `},`
`};`
`mix.webpackConfig(webpackConfig).options({`
    `uglify: {`
        `compress: false,`
        `mangle: {`
            `toplevel: true,`
            `keep_fnames: true`
        `}`
    `}`
`});`

mix.js('resources/assets/backend/backend.js', 'public/backend/js').js('resources/assets/backend/app/auth.js', 'public/backend/js')`

**Anyone got solution to this issue**
