### ISSUE TITLE
[Question] How to disable notification if the build is successful?

### ISSUE THREAD

**Issue by ajcastro** [JeffreyWay/laravel-mix#824]
I want to disable os notifications on success builds when I hit save. I just want be notified if there are errors or warnings.. I tried the code below but didn't work.
```javascript
mix.js('resources/assets/js/app.js', 'public/dist/vendor.js')
   .sourceMaps().then(function (stats) {
        // if (!stats.hasErrors() || !stats.hasWarnings()) {
            mix.disableNotifications();
        // }
   });
```

**Comment by ankurk91** [comment]
I don't think it is possible right now. But i like the idea.

**Comment by JeffreyWay** [comment]
You can't at the moment.

**Comment by JohnnyWalkerDesign** [comment]
This would be a great feature. The notification in the top right hand corner of my window is extremely distracting (MacOS). Would love to be able to disable it for everything but errors.

**Comment by HSPDev** [comment]
@JohnnyWalkerDesign I've made a fix at https://github.com/JeffreyWay/laravel-mix/pull/894 
Just waiting for @JeffreyWay  <3

**Comment by dschreij** [comment]
Awesome! Thanks @JeffreyWay and @HSPDev.
Is it possible to add this to the docs? It only mentions .disableNotifications() there so I only found out about the `disableSuccessNotifications()` function by looking at the pull request of HSPDev.
