### ISSUE TITLE
Version to exclude certain files

### ISSUE THREAD

**Issue by sebastiansulinski** [JeffreyWay/laravel-mix#825]
This isn't an issue - just a suggestion / request if possible.

I'm using versioning with the mix, but I have one particular file, which when compiled I'd like to leave without versioning / hashing. Suggestion would be to add second argument (Array) to the `version()` method, which would contain list of files to ignore:

```javascript
mix.
...
.version([], ['path/to/file/to/ignore.js'])
```

**Comment by JeffreyWay** [comment]
Webpack does this versioning internally, so it's not practical to allow for this, as far as I'm aware. Sorry about that.
