### ISSUE TITLE
Laravel mix versioning a directory.

### ISSUE THREAD

**Issue by stephan-v** [JeffreyWay/laravel-mix#829]
- Laravel Mix Version: 0.11.4 (`npm list --depth=0`)
- Node Version (`node -v`): 7.4.0
- NPM Version (`npm -v`): 4.1.2
- OS: Ubuntu 16.04

### Description:

When trying to version a directory of images separately like described here:

https://github.com/JeffreyWay/laravel-mix/blob/master/docs/versioning.md#versioning-extra-files

I am getting the following error:

> Error: EISDIR: illegal operation on a directory, read...

Obviously it fails because it wants a file instead of a directory but is there not a way to put a directory of images under versioning for cache busting? Does this not make sense or something? I would expect something like this to be extremely helpful and needed.

### Steps To Reproduce:

This is my webpack configuration file, with line 40 being the issue:

https://gist.github.com/stephan-v/c705e78939718692a4762b62fbbbcbdf#file-webpack-mix-js-L40

The only thing I have besides that is a seperate webpack config file so I can use SVG's properly:

```
const config = require('laravel-mix/setup/webpack.config');

// See also: https://github.com/JeffreyWay/laravel-mix/issues/350
for (const rule of config.module.rules) {
    if (rule.test.toString() === '/\\.(woff2?|ttf|eot|svg|otf)$/') {
        rule.test = /\.(woff2?|ttf|eot|otf)$/;
    }
}

module.exports = config;
```

**Comment by ankurk91** [comment]
@stephan-v 
You can always use node js native fs [functions](https://nodejs.org/api/fs.html).

```js
// webpack.mix.js
const imageFolder = './public/img/';
const fs = require('fs');

console.log('Reading dir - ' + imageFolder);
let images = fs.readdirSync(imageFolder);
console.log('Finished reading dir');
images = images.map(function (image) {
  return imageFolder + image;
});

mix.version(images);

```
This is not the best solution but it worked for me.

**Comment by JeffreyWay** [comment]
I added support for this in the 1.0 release of Mix. 

```js
mix.version('path/to/folder');
```
