### ISSUE TITLE
CSS file not being served (Not Found, 404) in HMR

### ISSUE THREAD

**Issue by ajcastro** [JeffreyWay/laravel-mix#830]
- Laravel Mix Version: 0.12
- Node Version (`node -v`): v7.6.0 
- NPM Version (`npm -v`): 4.1.2
- OS: Ubuntu Mate 16.04

### Description:
It's weird that when running `npm run hot`, my css files cannot be found.. `Cannot GET /dist/all.css`. The path is changed to `http://localhost:8080/dist/all.css` but it is not found. Anyone knows the solution for this? Im not sure if this related to #766. All javascript files is served well, except for my css file.
It is fine if I run `npm run dev`.

Possible related: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/30#issuecomment-125757853

**Comment by nickknissen** [comment]
Does `http://localhost:8080/public/dist/all.css` work? I am running into the same problem. 
A solution was to add `contentBase: "./public"` to [`webpack.config.js:331`](https://github.com/JeffreyWay/laravel-mix/blob/v0.12.1/setup/webpack.config.js#L331)

**Comment by ajcastro** [comment]
Really? Wait and Im gonna try it right now

**Comment by ajcastro** [comment]
But why are the javascript files are working?

**Comment by ajcastro** [comment]
Also, you can add `--content-base ./public` in the `hot` script in your package.json.

**Comment by ajcastro** [comment]
But a change in a css file doesnt trigger HMR. Only changes in javascript files trigger HMR.

I am using/refering to `mix.styles()`.

**Comment by nickknissen** [comment]
Also just found out there a no hot reloading when doing this. 
Just checked out a "older" project that uses laravel-mix and it loads files without any problems.


My system:
Laravel Mix Version: 0.12
Node Version (node -v): v7.5.0
NPM Version (npm -v): 4.1.2
OS:  Windows 10

**Comment by ajcastro** [comment]
Whoop! Even if I refresh the browser,  the changes in my css files didn't take effect. Seems like I need to switch back using `npm run watch` because of this.

**Comment by nickknissen** [comment]
It help to upgrade to beta `npm install laravel-mix@beta`

**Comment by ankurk91** [comment]
https://github.com/JeffreyWay/laravel-mix/issues/344#issuecomment-313580161
