### ISSUE TITLE
0.12.0 extract broken with browsersync with `npm run watch`

### ISSUE THREAD

**Issue by lukepolo** [JeffreyWay/laravel-mix#831]
- Laravel Mix Version: 0.12.0
- Node Version (`node -v`): 7.10.0
- NPM Version (`npm -v`): 4.2.0
- OS: mac 10.12.4

### Description:
No longer creates manifest / vendor files , sometimes even the app.js

### Steps To Reproduce:
Start `npm run watch`

![image](https://cloud.githubusercontent.com/assets/2066668/26450194/30e7eb4e-4124-11e7-856b-35f6a1ba5c43.png)

 ### Webpack.js

```
mix.js('./resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .extract([
        'vue',
        'vuex',
        'axios',
        'jquery',
        'lodash',
        'select2',
        'nprogress',
        'pusher-js',
        'flatpickr',
        'vue-router',
        'fullcalendar',
        'laravel-echo',
        'vuedraggable',
        'moment-timezone',
        'lodash-inflection',
        'vue-froala-wysiwyg',
    ])
    .autoload({
        vue : 'Vue',
        lodash : '_',
        store :  'browser',
        select2 : 'select2',
        'pusher-js' : 'Pusher',
        jquery: ['$', 'jQuery'],
        clipboard : 'Clipboard',
        flatpickr : 'flatpickr',
    })
    .sourceMaps()

if (mix.config.inProduction) {
    // mix.version() -- disabled for testing to make sure it wasn't versioning 
} else {
    mix.browserSync({
        open: 'external',
        host : 'nucleus.dev',
        proxy : 'nucleus.dev'
    })
}
```

Forgot to mention , works in 0.11.4

**Comment by gstjohn** [comment]
I was digging around and it seems it's an undocumented change to the `extract()` method signature/functionality that is causing this to happen.

https://github.com/JeffreyWay/laravel-mix/blob/master/src/Entry.js#L65

You must now extract after your `js()` calls or specify a path as the second parameter.

Does that help you as well?

**Comment by lukepolo** [comment]
Nope, still broken for me,  infact does some really funky things , like putting a js.js file outside of the public etc. 

![image](https://cloud.githubusercontent.com/assets/2066668/26462534/32717784-414f-11e7-8c90-72f73715bf1f.png)

Regardless the comment does say to at least call .js before which it does, so seems like its another culprit hanging around

**Comment by JeffreyWay** [comment]
@lukepolo - Can you bump to v1.0 of Mix and let me know if it's still an issue on you rend?
