### ISSUE TITLE
"npm run watch-poll" not working with plain css

### ISSUE THREAD

**Issue by luunguyenbk** [JeffreyWay/laravel-mix#837]
I've installed the latest Laravel-Mix, but when I run "npm run watch-poll", it only watch for sass and js file. With css file, the system can't detect when I edit file.

Here is my webpack.mix.js

```
mix.styles([
    'resources/assets/css/main.css',
], 'public/css/main.css');

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .options({
      processCssUrls: false
});
```

When I edit main.css, npm run watch is not working.
But I edit app.js or app.scss, it works.

I use Homestead - Ubuntu Vagrant NFS.

**Comment by ankurk91** [comment]
AFIAK watch does not works with ``styles()`` , ``scripts()`` methods, because these files does not go through webpack.

**Comment by luunguyenbk** [comment]
Thank you,
I found some issues about Laravel-Mix.

Now I'm using Laravel-Mix: 0.12.0
And file package.json, I changed to mix.copy
`mix.copy('resources/assets/css/main.css', 'public/css/main.css');
`
So, when I edit `resources/assets/css/main.css`, Watch won't recomplie it.

-----
After that, I installed the previous Laravel-Mix version: 0.10.0 ,and Watch run correctly with Mix.copy. I think Laravel-Mix version: 0.12.0 had issue with Mix.copy.

About styles() , scripts(), I agree that they are not run by Watch.

**Comment by jbbr** [comment]
I can confirm this problem with Laravel Mix 1.2.0 with combine/scripts/babel
Watching files is implemented in the code also for non-webpack tasks.
I added a small debug output to the `onChange` method of the task and it seems to be triggered once when I change a file but then never again.

As it works the first time I assume there is some issue in the mix code or the used watch/notify-library.

**Comment by jbbr** [comment]
I now tracked the problem down to the "atomic writes"/"safe writes" feature of my IDE and how watching of non-webpack files is handled:

- After the first "atomic save" chokidar looses track of the file and further changes are not detected
- When changing chokidar options to `usePolling` everything is working fine (except inefficient polling is used of course)

I think it would be good if `usePolling` would be set automatically when starting webpack in polling mode.
