### ISSUE TITLE
Win10  the app.js is not created correctly for production when mixing multiple js files

### ISSUE THREAD

**Issue by czmole** [JeffreyWay/laravel-mix#839]
- Laravel Mix Version: #.#.# (`npm list --depth=0`)
+-- axios@0.15.3
+-- bootstrap-sass@3.3.7
+-- cross-env@3.2.4
+-- jquery@3.2.1
+-- laravel-mix@0.12.0
+-- lodash@4.17.4
`-- vue@2.3.3

- Node Version (`node -v`):  6.10.0
- NPM Version (`npm -v`):  4.6.1
- OS:  Windows 10 

### Description:
When I am trying to combine multiple js files like below but ONLY for production (`npm run production`) the app.js is created but all it writes inside is undefined, all the other files are created (mix.js.map, mix-manifest.json). Everything works fine when issuing `npm run dev`

> .scripts([
		'resources/assets/js/bootstrap/*.js',
		'resources/assets/js/vendor/*.js',
		'resources/assets/js/custom/*.js',
		'resources/assets/js/theme.js',
], 'public/js/app.js')

### Steps To Reproduce:
Setting up the webpack.min.js like above  and running `npm run production`

**Comment by czmole** [comment]
I found a possible solution for this problem: loading the js files like below, specifying each file name,

.js([
 'resources/assets/js/script1.js',
 'resources/assets/js/script2.js',
...
], 'public/js/app.js')

Was I doing it wrong? strange thing that the previous way was working for dev env.

**Comment by ryzr** [comment]
@czmole There is currently an issue with using `.scripts()`: https://github.com/JeffreyWay/laravel-mix/issues/828

It looks like you resolved your issue by using the `.js()` function, which works slightly differently. Nothing wrong with your syntax/usage, just an issue with the current version of Mix.

**Comment by czmole** [comment]
Thank you @ryzr ! I will close this one.
