### ISSUE TITLE
Extract not working

### ISSUE THREAD

**Issue by tillkruss** [JeffreyWay/laravel-mix#84]
I'm seeing this error:

```js
Uncaught ReferenceError: webpackJsonp is not defined
```

For both, `vendor.js` and `app.js`.

I'm also curios about the limitations for `mix.extract()`. jQuery and Vue seem to get extracted, but `laravel-echo` or `pusher-js` for example do not when using `import` or `require()`.

**Comment by eblin** [comment]
You need to also serve `manifest.js` file that webpack creates.

```
<script src="{{ mix('js/manifest.js') }}"></script>
<script src="{{ mix('js/vendor.js') }}"></script>
<script src="{{ mix('js/app.js') }}"></script>
```
