### ISSUE TITLE
copyDirectory not working in event hook

### ISSUE THREAD

**Issue by d-lamers** [JeffreyWay/laravel-mix#840]
- Laravel Mix Version: #.#.# (`npm list --depth=0`)
- Node Version (`node -v`): v7.7.3
- NPM Version (`npm -v`): 4.1.2
- OS: MacOS Sierra 10.12.4

### Description:
When trying to copy a directory using mix.copyDirectory within an event hook it just does nothing. While doing that same function outside of the event hook would work. It just be to early.

### Steps To Reproduce:

Try a mix.copyDirectory inside an event hook; mix.then(() =>) for example

### Code snippet

```
mix.then(() => {
    console.log('Finished, doing postprocessing..');

    mix.copyDirectory('fonts/', 'public/fonts').then(() => {
        del('fonts');
    });
});

```

**Comment by ankurk91** [comment]
Does other methods like ``scripts()`` or ``styles()`` works in the ``then()`` callback ?

You can always use native node-js methods OR a package like [ncp](https://github.com/AvianFlu/ncp) to perform such file operations.

**Comment by d-lamers** [comment]
Thanks ankurk91 for the response. Other mix functions don't seem to work either. I could use other libraries and it would do the job. But that is not the solution I'd prefer.

**Comment by JeffreyWay** [comment]
```js
mix.then(() => {
    console.log('Finished, doing postprocessing..');

    mix.copyDirectory('fonts/', 'public/fonts').then(() => {
        del('fonts');
    });
});
```

This isn't how Mix works, so you can'd do that.
