### ISSUE TITLE
Image url not correct in HMR

### ISSUE THREAD

**Issue by CasperLaiTW** [JeffreyWay/laravel-mix#845]
- Laravel Mix Version: 0.12.1 (`npm list --depth=0`)
- Node Version (`node -v`): v7.10.0
- NPM Version (`npm -v`): 5.0.0
- OS: OSX

### Description:
In HMR, using `<img src="../../images/logo.png">` in the `.vue` file can't load image in browser. the image url is `/images/logo.png?[hash]`.

I think image url must be `http://localhost:8080/images/logo.png?[hash]` in HMR.

### Steps To Reproduce:

1. app.js
```js
window.Vue = require('vue');

Vue.component('example', require('./components/Example.vue'));

const app = new Vue({
    el: '#app'
});
```

2. Example.vue
```vue
<template>
    <div class="container">
        <img src="../../images/logo.png" />
    </div>
</template>

<script>
    export default {
    }
</script>
```

3. Add `logo.png` to directory

4. run `npm run hot`

### Result
<img width="639" alt="screen shot 2017-06-01 1 59 15" src="https://cloud.githubusercontent.com/assets/5094008/26646386/f518a082-466d-11e7-82fc-22a92a6acda9.png">

**Comment by ruchern** [comment]
It is correct. You used a relative path, so the image url will be handled by `url-loader`.

**Comment by CasperLaiTW** [comment]
@ruchern Thanks for help, I know it will be handled by `url-loader`

but image will be processed by webpack, so image file in the webpack dev server, is it?

image didn't export to `public/images` directory, so browser can't get image.

**Comment by ruchern** [comment]
@CasperLaiTW If you want the image to be in `public/images` you need to manually configure [`copy-webpack-plugin`](https://github.com/kevlened/copy-webpack-plugin) to copy the image into `public/images`

**Comment by CasperLaiTW** [comment]
If I use `npm run production` it's all working. image will be processed to `public/images/` automatic


if I remove `publicPath` from loader or setup `resourceRoot` to be `//localhost:8080/` - it's working in `HMR`.

https://github.com/JeffreyWay/laravel-mix/blob/v0.12.1/setup/webpack.config.js#L179

so my workaround is
```js
if (mix.config.options.hmr) {
    mix.setResourceRoot('//localhost:8080/');
}
```

**Comment by CasperLaiTW** [comment]
So I am not sure it's bug or something wrong in the config.

In my point, I think I didn't change any setting or hard code in the `HMR` or `Production` mode.

**Comment by zhouyixiang** [comment]
In HMR mode, new images are served in webpack dev server, but the generated urls point to Laravel server. I think the solution from @CasperLaiTW should be integrated into laravel-mix or at least be documented.

**Comment by pyrostrex** [comment]
How is this not documented yet? Thanks @CasperLaiTW , Anyhoo in the latest laravel-mix/webpack, i had remove the .options to get it to work. In case anyone wondering...
```js
if (mix.config.hmr) {
    mix.setResourceRoot('//localhost:8080/');
}
```

**Comment by scottasmith** [comment]
I have spent far too long wondering why my images were not being copied across in HMR.
This fix worked even in the latest mix, thanks!
