### ISSUE TITLE
Exclude files from being versioned.

### ISSUE THREAD

**Issue by Braunson** [JeffreyWay/laravel-mix#846]
- Laravel Mix Version: 0.12.1
- Node Version: v7.5.0
- NPM Version: 5.0.0
- OS: Windows 10

### Description:
I have a `front.css` and a `app.js` that get compiled and versioned, however I need to link to those files from a third party server (running WordPress, not running the Laravel Project or Mix). So in order to do that I need to generate a 'static' file, at least a file where the name doesn't change every time I run `yarn run production`.

My issue comes where regardless of how I use `.version()` every file get's versioned. I'm trying to exclude a "static named" version (that will be included in a WordPress theme on another server). I've even tried using the `copy()` option but even that copied file get's versioned.

### Steps To Reproduce:

```js
const { mix } = require('laravel-mix');
let webpack = require("webpack");

mix.options({
    clearConsole: true,
    processCssUrls: false
});

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/front.scss', 'public/css');

mix.version();

// Still get's versioned :\
mix.copy('public/js/app.js', 'public/js/app_static.js')
   .copy('public/css/front.css', 'public/css/front_static.css');

mix.webpackConfig({
    module: {
        loaders: [
            { test: /jquery-mousewheel/, loader: "imports?define=>false&this=>window" },
            { test: /malihu-custom-scrollbar-plugin/, loader: "imports?define=>false&this=>window" }
        ]
    },
    resolve: {
        alias: {
            'morris.js': 'morris.js/morris.js',
            'jquery-migrate': 'jquery-migrate/dist/jquery-migrate.min.js'
        }
    },
    plugins: [
        new webpack.ContextReplacementPlugin(/moment[\\\/]locale$/, /^\.\/(en|fr)$/)
    ]
});
```

**Comment by JeffreyWay** [comment]
The 1.0 release of Mix uses a querystring approach for file versioning, so this would fix your issue. It'll be available in a few days.
