### ISSUE TITLE
Generate only mix-manifest.json on specific folder

### ISSUE THREAD

**Issue by leonfather** [JeffreyWay/laravel-mix#849]
- Laravel Mix Version: #.#.# (`npm list --depth=0`)
- Node Version (`node -v`): 
- NPM Version (`npm -v`): 
- OS: 

### Description:
I need your help about the file mix-manifest.json, when webpack compile my js and css files he place them on my www folder with (in my webpack.mix.js): 
<img width="587" alt="screen shot 2017-06-01 at 13 23 09" src="https://cloud.githubusercontent.com/assets/25527820/26681697/8c4ef032-46cd-11e7-88a0-fa4b0a2917f9.png">

in my racine "/" i have myApp folder and www folder and all laravel logic is placed in myApp folder
and my index.php is in www folder, i want that the file mix-manifest.json be generated in myApp folder and the rest of compiled files (js,sass,less...) in www folder
how can i do this please ?

**Comment by JeffreyWay** [comment]
You can't override the default location of the mix-manifest.json file. It will always be placed in the project's public directory. You can use mix.setPublicPath() to explicitly set the public folder for your app.
