### ISSUE TITLE
File helper doc

### ISSUE THREAD

**Issue by decadence** [JeffreyWay/laravel-mix#851]
Not an issue with Laravel Mix but with docs.
Here (4cc6c8483f64cd614bc38eeba34f6560501bf4ba) you deleted documentation about File helper (mix-helpers.md).
But I see it's still available but as global.File not as mix.File.
Shouldn't it be in docs or it's deprecated (I hope it's not because it can be very helpful)?

**Comment by JeffreyWay** [comment]
People are free to use that File class if they need it, but I removed it because very few people actually will. And it's not something that I want to include as part of the main API.

**Comment by decadence** [comment]
Thanks. Though I think number of people that are using this class would be bigger if it was in docs as a small note at least.
