### ISSUE TITLE
Laravel Mix way to use webpack's DefinePlugin

### ISSUE THREAD

**Issue by jbruni** [JeffreyWay/laravel-mix#853]
Is there a Laravel Mix simple way to use webpack's DefinePlugin?

I see there is a "MixDefinitionsPlugin". Not sure if it is for internal purposes only; there is no documentation about it.

Thank you.

**Comment by ankurk91** [comment]
https://github.com/JeffreyWay/laravel-mix/blob/master/docs/quick-webpack-configuration.md
