### ISSUE TITLE
How to add custom webpack config options?

### ISSUE THREAD

**Issue by liuzhen2008** [JeffreyWay/laravel-mix#854]
I am using laravel mix, but i also want to add some extra custom webpack config options

How do I go about adding it?

```
watchOptions: {
  aggregateTimeout: 2000,
  poll: 2000,
  ignored: /node_modules/
}

```
This is the watch options I would like to add. But i don't quite understand how to modify the packaged webpack.config.js.

I can obviously fork it and use that version, but how do I simply extend it?

**Comment by ankurk91** [comment]
https://github.com/JeffreyWay/laravel-mix/blob/master/docs/quick-webpack-configuration.md

**Comment by liuzhen2008** [comment]
@ankurk91  Thanks. This is exactly what i was looking for.

**Comment by benyanke** [comment]
Could you share your final config file, with these watch options implemented. @liuzhen2008 ? I'm having trouble getting this working, and trying to do the exact same as you.

**Comment by liuzhen2008** [comment]
@benyanke  Hey. I think I did was
