### ISSUE TITLE
CSS url() Rewriting with subfolder

### ISSUE THREAD

**Issue by marcelogarbin** [JeffreyWay/laravel-mix#855]
- Laravel Mix Version: 0.12.1
- Node Version 8.0.0
- NPM Version 5.0.0
- OS: Win10 / Homestead-7

### Description:
URL Processing is not working with subfolder.

### Steps To Reproduce:
**style.scss**
```
body{
  background: url("../images/bg/bg1.png");
}
```
**webpack.mix.js**
`mix.sass('resources/assets/painel/sass/style.scss', 'public/css');`

**resources folder**
![screenshot_26 20170605 09 22 17](https://cloud.githubusercontent.com/assets/9335588/26783807/816ec72c-49d0-11e7-879e-43710585ce56.png)
![screenshot_26 20170605 09 23 34](https://cloud.githubusercontent.com/assets/9335588/26783842/af24194c-49d0-11e7-9768-49f9a6b096ee.png)

**public folder**
![screenshot_26 20170605 09 20 53](https://cloud.githubusercontent.com/assets/9335588/26783767/54af473e-49d0-11e7-8348-e5073c60b405.png)

## Result:
**style.css**
```
body {
  background: url(/images/bg1.png?810b1859b0d5c6f6273fb7818a633b03);
}
```

**Comment by Romchik** [comment]
I have same problem...

Is it a laravel-mix bug or something wrong with settings?

**Comment by Romchik** [comment]
@marcelogarbin 
Fixed in 1.0.3.
Path to image schould be started with `"/images..."`:
`
    body {
        background: url("/images/bg/bg1.png");
    }
`

**Comment by marcelogarbin** [comment]
@Romchik  How to upgrade to new version?

**Comment by Romchik** [comment]
Open `package.json` file and edit `laravel-mix` depency:

`"laravel-mix": "^1.0.*",`

Then run `npm update laravel-mix`.

**Comment by marcelogarbin** [comment]
@Romchik Thank you very much!

**Comment by marcelogarbin** [comment]
@Romchik Not wanting to bother, but can you help me? I did the procedure, removed the node_modules folder and ran npm_install again, but it is giving an error.

package.json
```
{
  "private": true,
  "scripts": {
    "dev": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.16.2",
    "clean-webpack-plugin": "^0.1.16",
    "copy-webpack-plugin": "^4.0.1",
    "cross-env": "^5.0.1",
    "imagemin-mozjpeg": "^6.0.0",
    "imagemin-webpack-plugin": "^1.4.4",
    "laravel-mix": "^1.0.*",
    "lodash": "^4.17.4",
    "purifycss-webpack": "^0.7.0",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
    "postcss-discard-comments": "^2.0.4"
  }
}
```

![image](https://user-images.githubusercontent.com/9335588/27386953-bb063002-566d-11e7-8b4c-c9676de48d58.png)

**Comment by Romchik** [comment]
Sorry, I have no idea...

Maybe you can try to update npm to the last version.
Tnen remove the 'node_modules' folder.
Run `npm cache clean`.
Run `npm install`.

**Comment by marcelogarbin** [comment]
I removed the `package-lock.json` file and ran the `npm install` again. It worked. Only condition `if(mix.config.inProduction){}` stopped working, before updating it worked normally.

![image](https://user-images.githubusercontent.com/9335588/27396147-962b49d2-5688-11e7-87ad-f3d31657f17e.png)

![image](https://user-images.githubusercontent.com/9335588/27396625-f715cf78-5689-11e7-94d4-1e7e653378da.png)

**Comment by JeffreyWay** [comment]
@marcelogarbin Yeah, that was changed with 1.0. It's in the release notes. Change it to `mix.inProduction()`. :)

**Comment by audetcameron** [comment]
Question related:    Laravel-mix appears to move files from my assets/img  folder to public/images      however when using the asset()  helper function it looks for /img    is there a way to set them to the same folder so their are not two folders in public with images?  aka  img  and images  ? 

Thanks in advance :)
