### ISSUE TITLE
{{ mix('js/bundle.js') }} prepending "/" to path

### ISSUE THREAD

**Issue by ramakrishnamundru** [JeffreyWay/laravel-mix#856]
- Laravel Mix Version: 0.12.1
- Node Version (`node -v`): 7.10.0
- NPM Version (`npm -v`): 4.2.0
- OS: Linux-mint

### Description:
I use this to compile my vue component with HMR.
`<script src="{{ mix('js/bundle.js') }}"></script>`
It is normal when used with `npm run hot` but when run `npm run dev`
is outputting 
`<script src="/js/bundle.js"></script>`
I set the resource root like this
`mix.setResourceRoot('/myapp/public/');`

Because of the "/" the browser is looking for the file in the root directory of the server instead of "myapp"

**Comment by decadence** [comment]
It's intended.

Look [here].(https://github.com/laravel/framework/blob/1fbc7cf6e89fe2cf720ecfe26b4912fb1bea2347/src/Illuminate/Foundation/helpers.php#L532)

**Comment by ramakrishnamundru** [comment]
Hi,
Any workaround for this?

**Comment by decadence** [comment]
Maybe you could try call `setPublicPath` instead of `setResourceRoot`

**Comment by ramakrishnamundru** [comment]
I am using 
mix.setPublicPath('public')
But no use.

**Comment by JeffreyWay** [comment]
This repo doesn't control that function. So that would be a Laravel framework issue.

**Comment by ruchern** [comment]
@ramakrishnamundru Workaround is using `url(mix())` helper as per Taylor Otwell's suggestion.

**Comment by decadence** [comment]
@ruchern And how does that resolve forcing leading slash behaviour?
