### ISSUE TITLE
Object spread operator does not get transpiled properly.

### ISSUE THREAD

**Issue by liuzhen2008** [JeffreyWay/laravel-mix#857]
Laravel mix: v0.12.1
Node: 6.10
NPM: 3.10.10

I am using the webpack.config.js in laravel-mix directly to compile my javascript resources directly.

I notice that the spread operator does not work (doesn't get compiled at all, the page will simply show an error and fail to load).

Is the spread operator supposed to work? Or do I need to add some extra configurations?

This works.
```
function k([one, two, ...rest]) {
    console.log(rest);
}
k([1,2,3,4,5,6]);
```

But this doesn't.
```
var one = {a: 3, b: 4};
var two = {...one};
```

Is this expected? What do I need to add so that it will work?

**Comment by jbruni** [comment]
1. Install `babel-plugin-transform-object-rest-spread` package as dev dependency, using Yarn or NPM.

2. Add a `.babelrc` file in your project root, to configure Babel:

```
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
          "browsers": ["> 2%"],
          "uglify": true
      }
    }]
  ],
  "plugins": ["transform-object-rest-spread"]
}
```

**Comment by liuzhen2008** [comment]
Ahh ok! tyty

**Comment by liuzhen2008** [comment]
@jbruni After I made changes you suggested, I get this error

 ERROR  Failed to compile with 1 errors                              11:13:37 AM

```
 error  in ./resources/assets/js/helper/constants.js

Syntax Error: Unexpected token (8:9)

  6 | 
  7 | let k = {a: 3};
> 8 | let w = {...k};
    |          ^

```

Are there some other stuff that I need to add?
I am using the webpack.config.js imbedded in laravel-mix. Do i need to extend it to make it aware of this .babelrc?

**Comment by jbruni** [comment]
Usually, no. So, you are not using the `webpack.mix.js` which comes from a Laravel framework project setup. Instead, you have copied the `webpack.config.js` from laravel-mix `setup` folder to your project root and you are using it. I do not have such experience.

Try inspecting the value of `rules.options.loaders.js`. You can do it inserting a `console.log(rules); process.exit()` at [line 250 of webpack.config.js](https://github.com/JeffreyWay/laravel-mix/blob/v0.12.1/setup/webpack.config.js#L251)

This way you will see how babel-loader is being configured. Anyway, it should be using the `.babelrc` configuration.

Maybe you have old version of the "env" preset or the "object-rest-spread" plugin installed: https://github.com/babel/babel-preset-env#caveats
