### ISSUE TITLE
Mix is not cleaning old versioned files

### ISSUE THREAD

**Issue by jbruni** [JeffreyWay/laravel-mix#858]
- Laravel Mix Version: 0.12.1
- Node Version: v6.10.3
- NPM Version: 5.0.2
- OS: Lubuntu 16.04

### Description:

I currently have two projects using Laravel Mix. One is using version 0.10.0, and all works well.

Now, most recent project is using version 0.12.1, and unlike before, now the previous compiled versions of the assets are not deleted anymore, thus a pile of "uncollected garbage files" grows fast.

This includes all: the generated manifest, the CSS files, and the JS files.

### Steps To Reproduce:

I believe it is just a matter of using `mix.version` and check that it is not deleting the old versioned files, when a new one is created.

**Comment by jeffturcotte** [comment]
IMO the default behavior should not be destructive. This could work as option perhaps?

My solution for this was to put all compiled assets/resources into a `/build` directory and then add the following to the top of my webpack.mix.js file so everything gets cleaned up on every run:

```
const fs = require('fs-extra');

// Clean up old build dir
fs.removeSync(__dirname + '/build/');
```

**Comment by jeffturcotte** [comment]
Also I think this is a dupe: #814

**Comment by JeffreyWay** [comment]
Fixed in the 1.0 release.

**Comment by bbashy** [comment]
Thanks Jeffrey for fixing that.

Waiting for v1.0 to be released then! Multiple projects with untracked files annoyance will be over 🤒 

![](https://d.pr/i/FZ0y5/17qyCl1q.jpg)

**Comment by ruchern** [comment]
@bbashy Is that on development (`npm run watch`) or production?

**Comment by bbashy** [comment]
@ruchern Both `yarn watch` and `yarn dev`. I can't test production as I get the uglify-js error.

```
undefined:1625
    throw new JS_Parse_Error(message, filename, line, col, pos);
    ^
SyntaxError: Unexpected token: name (markup)
    at JS_Parse_Error.get (eval at <anonymous> (/somepath/project/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
```

**Comment by ruchern** [comment]
@bbashy Which version of `Laravel-Mix` are you on? Not that I may know how to solve the problem, but `0.11.4` seems stable. I am actually very lucky to have not face this problem.

**Comment by bbashy** [comment]
@ruchern `laravel-mix@0.12.1` but I've been having the issue for a few releases.
