### ISSUE TITLE
How to change path of fonts?

### ISSUE THREAD

**Issue by halcyonl** [JeffreyWay/laravel-mix#864]
- Laravel Mix Version: 0.12.1
- Node Version: 7.7.4
- NPM Version: 4.1.2
- OS: macOS Sierra 10.12.5

### Description:
I want to change path of fonts. But i can't see any option to do this. I try set value for option: `publicPath` but it is fail too. Anyone can't help me?

**Comment by halcyonl** [comment]
```
let path = 'resources/themes/abc/assets';
mix.options({ publicPath: 'public/static' });

mix
    .js(path + '/js/vendor.js', 'public/static/js')
    .js(path + '/js/app.js', 'public/static/js')
    .sass(path + '/scss/vendor.scss', 'public/static/css')
    .sass(path + '/scss/app.scss', 'public/static/css');
```

**Comment by ankurk91** [comment]
Disable url processing
```js
mix.options({
  processCssUrls: false,
})
```
Then copy yourself
```js
mix.copy('./node_modules/font-awesome/fonts/*.*',  './public/your-folderfonts/');
```

**Comment by halcyonl** [comment]
Thanks, but i have alot of picture and font, this is good way but it's not best way. I want to move my pictures and fonts to `/static`. I think we can do different ways.
