### ISSUE TITLE
ENOENT: no such file or directory, open '.../schema/loader.json'

### ISSUE THREAD

**Issue by jasperf** [JeffreyWay/laravel-mix#865]
- Laravel Mix Version: #.#.# (`npm list --depth=0`)
````
├── axios@0.15.3
├── bootstrap-sass@3.3.7
├── cross-env@3.2.4
├── jquery@3.2.1
├── laravel-mix@0.12.1
├── lodash@4.17.4
└── vue@2.3.4
````
- Node Version (`node -v`): v8.0.0
- NPM Version (`npm -v`): 5.0.0
- OS: macOS Sierra 10.12.5
- Running locally and using `php artisan serve` for basic testing for now

### Description:
Been having issues right from the start with a clean Laravel app running `npm run dev`. Decided to add some scss and run the command to see if it would all compile well and show. But despite multiple attempts, node_modules wipes and npm installs I cannot get past this error.

### Steps To Reproduce:
run `npm run dev` for the first time, and again post npm and node upgrades and get:
````
> @ development /Users/jasper/webdesign/larastud.io
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
fs.js:638
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/Users/jasper/webdesign/larastud.io/schema/loader.json'
    at Object.fs.openSync (fs.js:638:18)
    at Object.fs.readFileSync (fs.js:540:33)
    at validateOptions (/Users/jasper/webdesign/larastud.io/node_modules/schema-utils/dist/validateOptions.js:35:27)
    at ExtractTextPlugin.extract (/Users/jasper/webdesign/larastud.io/node_modules/extract-text-webpack-plugin/index.js:206:3)
    at Sass.rules (/Users/jasper/webdesign/larastud.io/node_modules/laravel-mix/src/Preprocessors/Preprocessor.js:46:42)
    at Mix.preprocessors.forEach.preprocessor (/Users/jasper/webdesign/larastud.io/node_modules/laravel-mix/setup/webpack.config.js:243:33)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/jasper/webdesign/larastud.io/node_modules/laravel-mix/setup/webpack.config.js:242:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
````
Well there is no schema/loader.js of course.. So not sure why it is looking for that file there. Here the full log missing that same error... :
````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 silly lifecycle @~predev: no script for predev, continuing
7 info lifecycle @~dev: @
8 verbose lifecycle @~dev: unsafe-perm in lifecycle true
9 verbose lifecycle @~dev: PATH: /Users/jasper/webdesign/larastud.io/npm/bin/node-gyp-bin:/Users/jasper/webdesign/larastud.io/node_modules/.bin:/Users/jasper/.rvm/gems/ruby-2.3.3/bin:/Users/jasper/.rvm/gems/ruby-2.3.3@global/bin:/Users/jasper/.rvm/rubies/ruby-2.3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jasper/.composer/vendor/bin:/Users/jasper/.rvm/bin
10 verbose lifecycle @~dev: CWD: /Users/jasper/webdesign/larastud.io
11 silly lifecycle @~dev: Args: [ '-c', 'npm run development' ]
12 silly lifecycle @~dev: Returned: code: 1  signal: null
13 info lifecycle @~dev: Failed to exec dev script
14 verbose stack Error: @ dev: `npm run development`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/jasper/webdesign/larastud.io/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/jasper/webdesign/larastud.io/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:887:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid @
16 verbose cwd /Users/jasper/webdesign/larastud.io
17 verbose Darwin 16.6.0
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
19 verbose node v8.0.0
20 verbose npm  v5.0.0
21 error code ELIFECYCLE
22 error errno 1
23 error @ dev: `npm run development`
23 error Exit status 1
24 error Failed at the @ dev script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
````

Similar issues mentioned here here an hour before I had it https://laracasts.com/discuss/channels/elixir/npm-run-dev-does-not-work

**Comment by sebestenyb** [comment]
Locking the following package solved the issue for me:

`"extract-text-webpack-plugin": "2.1.0"`

Tho I use `"laravel-mix": "0.5.6"`

**Comment by jasperf** [comment]
@sebestenyb And how did you do this lockdown? Still quite new to Laravel and Laravel mix..

**Comment by sebestenyb** [comment]
Sorry, just add to the `package.json`:

```
  "devDependencies": {
    "axios": "^0.15.3",
    "bootstrap-sass": "^3.3.7",
    "cross-env": "^3.2.3",
    "jquery": "^3.1.1",
    "laravel-mix": "0.*",
    "lodash": "^4.17.4",
    "vue": "^2.1.10",
    "extract-text-webpack-plugin": "2.1.0"
  }
```

**Comment by ruchern** [comment]
@sebestenyb I think you should remove the `extract-text-webpack-plugin` from your devDependencies and update your Laravel-Mix to minimum 0.11.4

0.11.4 should have that package by default.

**Comment by rabol** [comment]
But.... this is default installation of Laravel, so it should not fail

**Comment by sebestenyb** [comment]
Upgrading the package was the first I've tried after encountering the issue - no luck.
The problem is that this package just has got updated by something, and that broken the build.

So I actually froze it in the version I know it worked.

**Comment by rabol** [comment]
This worked for me:
1 ) laravel new mytest
2) modify package.json - "laravel-mix": "0.11.4",
3) npm install
4) npm run dev

**Comment by jasperf** [comment]
Still working on it. Adding the line `"extract-text-webpack-plugin": "2.1.0"`, removed all packages and installed again. Then I ran `npm run dev` again. seems to not work as 2.1.1 is still added.  Will look at it this afternoon.

**Comment by jasperf** [comment]
Well I just did a new installation running `laravel new bug`. Then I did a `composer update` and `npm install` and `npm run dev`. It worked just fine. Then I copied only newer files over to my project using `jasper@~/webdesign/larastud.io $ rsync -aru ../bug/ .` Then I ran npm run dev again and all started to work. No idea what was left over after the previous change, but this did the trick.

**Comment by jasperf** [comment]
Yeah, the fixed the path issue https://github.com/webpack-contrib/extract-text-webpack-plugin/commit/87668210a886ceed8c18516e01957e53b2d291f1
