### ISSUE TITLE
Dist file being deleted when saving src file with no changes

### ISSUE THREAD

**Issue by eddiemf** [JeffreyWay/laravel-mix#866]
- Laravel Mix Version: 0.12.1
- Node Version (`node -v`): 7.9.0 
- NPM Version (`npm -v`): 4.2.0
- OS: Mac OS Sierra Version 10.12.5

### Description:
Whenever I save my src/js/app.js or src/scss/app.scss, my dist/js/app.js and vendors (if I extract them) will get deleted, so I have to make a real change like writing a console.log() or deleting some lines for it to recompile and recreate the file.

### Steps To Reproduce:
I've tested a clean installation of laravel-mix in a non-laravel project, with the following config in webpack.mix.js:

mix.js('src/js/app.js', 'dist/js')
	.sass('src/scss/app.scss', 'dist/css');

1 - $ npm run watch
2 - Save any of the src/.. files without making changes and the dist/js/app.js will disappear.

Note: I've tested with laravel-mix 0.8.* as I had that version in another project and the problem doesn't occur, then I $ rm -rf node_modules && npm install laravel-mix -S and installed the latest version and the problem began to happen.

Note 2: The problem only occurs in $ npm run watch, $ npm run dev doesn't delete it.

Note 3: I've not tested with a Laravel project, but I'm afraid it shouldn't make a difference.

**Comment by ankurk91** [comment]
Wait for [v1.0](https://github.com/JeffreyWay/laravel-mix/issues/860) to be stable

**Comment by tobz-nz** [comment]
I have the same issue. Pretty much same setup except using Yarn.

**Comment by randohinn** [comment]
Same issue.

**Comment by ruchern** [comment]
@eddiemf Can you try reverting to 0.11.4 and see if the problem persist? 0.12.1 seems to be having this issue.

**Comment by tobz-nz** [comment]
Yes, downgrading to `0.11.4` is working for me.

**Comment by mediabeastnz** [comment]
Same issue for me - will downgrade and wait for stable :)

**Comment by JeffreyWay** [comment]
Fixed in 1.0.
