### ISSUE TITLE
Hot reload not publishing changes

### ISSUE THREAD

**Issue by alejodiazg** [JeffreyWay/laravel-mix#868]
- Laravel Mix Version: 0.11.4
- Node Version:  v6.10.3
- NPM Version: 3.10.10
- OS: Ubuntu / Docker container

### Description:

Im running laravel with a laravel-mix configuration inside a docker container, but cant seem to get hot reload to work, I can access the static js file, but while running hot and changing files, and even reloading manually the page Im not getting the changes even when the console output from npm run hot seems to be compiling the files.

### Steps To Reproduce:

webpack.mix.js 
```const { mix } = require('laravel-mix')

mix
	.options({
		processCssUrls: false
	})
	//.sourceMaps()
	.js('resources/assets/js/admin.js', 'public/js')
       .sass('resources/assets/sass/admin.scss', 'public/css')
```
Package.json hot reload configuration
```
"hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --host=0.0.0.0 --public=10.20.30.1 --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",

```
U can see I made some changes so the host machine can access the webpack-dev-server

In my index I import the js this way (maybe this could be the problem)
```
<script src="http://10.20.30.1:8080/public/js/admin.js"></script>
```

I have checked that I have no WebSocket connections open with the server, even when the websockets code seems to be in my admin.js file

```
/******/ (function(modules) { // webpackBootstrap
/******/ 	function hotDisposeChunk(chunkId) {
/******/ 		delete installedChunks[chunkId];
/******/ 	}
/******/ 	var parentHotUpdateCallback = this["webpackHotUpdate"];
/******/ 	this["webpackHotUpdate"] = 
/******/ 	function webpackHotUpdateCallback(chunkId, moreModules) { // eslint-disable-line no-unused-vars
/******/ 		hotAddUpdateChunk(chunkId, moreModules);
/******/ 		if(parentHotUpdateCallback) parentHotUpdateCallback(chunkId, moreModules);
/******/ 	} ;
```

just a small part of the start of the bundled file

the file also is being loaded on the page
![image](https://user-images.githubusercontent.com/5624658/26956323-be27c616-4c8a-11e7-81e1-bba08fc43b07.png)

theres some extra configuration needed for this to work? or could be a problem brought by the webpack server configuration?

**Comment by nickknissen** [comment]
You should include `<script src="http://10.20.30.1:8080/js/admin.js"></script>` for hot reloading

**Comment by alejodiazg** [comment]
Thanks, I'll test it out tomorrow and Ill close the issue if it works correctly.

**Comment by alejodiazg** [comment]
seems to workbut still having some config issues

```
/#/:1 XMLHttpRequest cannot load http://10.20.30.1/sockjs-node/info?t=1497480609221. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://admin.laravel.dev' is therefore not allowed access. The response had HTTP status code 404.
admin.js:14404 [WDS] Disconnected!
log @ admin.js:14404
close @ admin.js:14485
sock.onclose @ admin.js:20348
EventTarget.dispatchEvent @ admin.js:13659
(anonymous) @ admin.js:17787
2admin.js:13923 GET http://10.20.30.1/sockjs-node/info?t=1497480610694 
AbstractXHRObject._start @ admin.js:13923
(anonymous) @ admin.js:13812
/#/:1 XMLHttpRequest cannot load http://10.20.30.1/sockjs-node/info?t=1497480610694. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://admin.laravel.dev' is therefore not allowed access. The response had HTTP status code 404.
2admin.js:13923 GET http://10.20.30.1/sockjs-node/info?t=1497480612786 
AbstractXHRObject._start @ admin.js:13923
(anonymous) @ admin.js:13812
/#/:1 XMLHttpRequest cannot load http://10.20.30.1/sockjs-node/info?t=1497480612786. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://admin.laravel.dev' is therefore not allowed access. The response had HTTP status code 404.
```

I see some weird behaviour http://10.20.30.1/sockjs-node/info?t=1497480609221 when it should be requesting it trough port 8080? seems like Ill have to modify the webpack server configuration but not a clue where to start

**Comment by alejodiazg** [comment]
Removed previous comment

The suggested change and changing the hot reload script to
```
"hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --host=0.0.0.0 --public=10.20.30.1:8080 --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js", 
````

helped a bit, but getting still this output when running
```
Project is running at http://10.20.30.1:8080/
webpack output is served from http://localhost:8080/
404s will fallback to /index.html
```
this means when it requests the  hot-update.json it request it to localhost (which fails), ill keep trying to see if I found a solution

**Comment by jonatangerman** [comment]
Hi @alejodiazg , I was following your approach as well and hit the same walls :( 
I finally get my HMR working! 
The last piece missing for this config to work was the 'localhost:8080' still used to load the .hot-update.json. And it was apparently due to the generated manifest.js still having 'localhost:8080' from the output config in the laravel-mix WebpackConfig.js file
I just added:
`output: {
    publicPath: Mix.isUsing('hmr') ? 'http://my-vm-ip:8080/' : '',
}, `
to my local webpack.mix.js > mix.webpackConfig, and actually worked!
Hope it could be helpful,
Cheers,

**Comment by alejodiazg** [comment]
@jonatangerman thanks ill try it in a few days to see if it works, right now im in my vacations.
