### ISSUE TITLE
Versioning HTML file

### ISSUE THREAD

**Issue by zishanj** [JeffreyWay/laravel-mix#872]
I am using Angular with Laravel. In Angular I am using interpolation to load template files with HTML extension. Is it possible to manually version these HTML files also using `mix.version`?

**Comment by ankurk91** [comment]
https://github.com/JeffreyWay/laravel-mix/blob/master/docs/versioning.md#versioning-extra-files

**Comment by ruchern** [comment]
@ankurk91 I am not sure if you can version `HTML` files though.

**Comment by zishanj** [comment]
I have already tried it and It does not work for HTML files

**Comment by ankurk91** [comment]
It works for me, i am on v0.12.1

![screenshot from 2017-06-12 17-48-57](https://user-images.githubusercontent.com/6111524/27033616-d3cbd9e8-4f97-11e7-93a4-48d8621169bf.png)

**Comment by QWp6t** [comment]
@zishanj then you should consider filling out the issue template, which would include providing the steps to reproduce, because yes, as @ankurk91 has demonstrated above, it works just fine with html files.

**Comment by zishanj** [comment]
I am using Laravel 5.4, Laravel-Mix 0.12.1 and to reproduce it, just use `mix.version(['test.html"])` it will even does not create entry in manifest.json

**Comment by ankurk91** [comment]
@zishanj 
Consider removing your ``node_modules`` and npm-shrinkwrap.json then re-install.
Remove everything from webpack-mix.js and only keep the ``mix.version(['test.html"])``.
This solution works most of the time.

**Comment by zishanj** [comment]
Others r not drunky like you
-- 
Sent from my Android phone. Please excuse my brevity.On 6/13/17, 8:47 AM Ankur Kumar <notifications@github.com> wrote:
@zishanj
Consider removing your node_modules and npm-shrinkwrap.json then re-install.
Remove everything from webpack-mix.js and only keep the mix.version(['test.html"]).
This solution works most of the time.

**Comment by ankurk91** [comment]
@zishanj 

> Others r not drunky like you

Sorry i could not understand you last comment
