### ISSUE TITLE
Sass compilation deleting JS file

### ISSUE THREAD

**Issue by edolyne** [JeffreyWay/laravel-mix#873]
- Laravel Mix Version: 0.12.1
- Node Version: 6.10.0
- NPM Version 5.0.1
- OS: MacOS Sierra

### Description:

While running watch a change to the `scss` file using `mix.sass()` deletes `js` file.

### Steps To Reproduce:

Running `npm run watch` compiles all files successfully on the first run, however when changes are made to the `master.scss` file the `master.scss` recompiles and removes the`master.js` file.

Current `webpack.mix.js`

```
const { mix } = require("laravel-mix");

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix
  .js(
    "./@source/javascripts/master.js",
    "./public/assets/site/js/master.js"
  ).standaloneSass(
    "./@source/stylesheets/cp.scss",
    "./public/assets/site/css/cp.css"
  )
  .sass(
    "./@source/stylesheets/master.scss",
    "./public/assets/site/css/master.css"
  ).options({
    processCssUrls: false,
    postCss: [
        require('css-mqpacker')(),
        require('cssnano')()
    ]
  })
  .copyDirectory(
    "@source/templates",
    "craft/templates"
  )
  .browserSync(
    {
      files: ["public/**/*", "craft/config/**/*", "craft/templates/**/*"],
      proxy: "https://sargentmetal.dev"
    }
  );
```

**Comment by ankurk91** [comment]
Try [v1.0 beta](https://github.com/JeffreyWay/laravel-mix/issues/860)

**Comment by edolyne** [comment]
@ankurk91 I had upgraded yesterday to try that route, but ended up with this error:

<img width="1238" alt="screen shot 2017-06-12 at 10 27 55 am" src="https://user-images.githubusercontent.com/3417857/27038770-ec4c896a-4f59-11e7-8cd3-c28b148a6c4c.png">

**Comment by ruchern** [comment]
@edolyne The source found seems to be wrong. Check again,.

**Comment by edolyne** [comment]
@ruchern The files that it's referencing are local files specific to the project, and are not on npm. Is there possibly something that I missed in my config to handle that.

**Comment by ruchern** [comment]
Yes. Correct. While npm is trying to compile your files, they cannot find that local file that you had specified in the `webpack.mix.js`.

**Comment by edolyne** [comment]
@ruchern Changing from `mix.js()` to `mix.scripts()` fixed the JS error but I'm still getting a `sass` error when using `mix.sass()`. So it is finding the files, just not when I use `.js()` or `.sass()` I've also added a screen shot of my file directory.

<img width="231" alt="screen shot 2017-06-12 at 11 15 01 am" src="https://user-images.githubusercontent.com/3417857/27041031-ca3b56ba-4f60-11e7-8f04-da5a34899452.png">

**Comment by edolyne** [comment]
@ruchern I ended up deleting the `node_modules` and `package-lock.json` and everything is compiling correctly. Thanks for the help.

**Comment by ruchern** [comment]
@edolyne Sorry, went to sleep. I off a different timezone from most of you guys.
