### ISSUE TITLE
No automatic polyfill for Array.prototype.includes()

### ISSUE THREAD

**Issue by manniL** [JeffreyWay/laravel-mix#874]
- Laravel Mix Version: 0.12.1
- Node Version (`node -v`): 8.0.0
- NPM Version (`npm -v`): 5.0.3
- OS: Ubuntu 17.04 zesty

### Description:

When using include a a Vue component and compiling the javascript assets through Laravel Mix, the polyfill is included, but isn't used by the javascript.

### Steps To Reproduce:

1. Create a fresh project with a VueJS component (single file)
2. Use the Array.prototype.includes method in the component (in the mount function for example)
3. See an error in older browsers who don't support it (like Internet Explorer 11)
![image](https://user-images.githubusercontent.com/640208/27036777-3b1d34e6-4f86-11e7-80c9-647567828022.png)

**Comment by morloderex** [comment]
babel-polyfill is what you are looking for :)

**Comment by manniL** [comment]
Thanks @morloderex 
Closing this as related to https://github.com/JeffreyWay/laravel-mix/issues/436
