### ISSUE TITLE
Add options to Vue CSS loaders

### ISSUE THREAD

**Issue by mrcsmcln** [JeffreyWay/laravel-mix#875]
### Description:
I can't seem to find a way to add options to Vue CSS loaders. For example, I'd like to add `includePaths` to Vue's `sass-loader`, but I don't see an option anywhere in the API. I've looked in `laravel-mix/src/builder/webpack-rules.js`, but there doesn't seem to be a place I can leverage.

Thoughts?

**Comment by lbjones** [comment]
I'm also having the same problem!  

In the previous versions of mix I solved this (after hours of research) by changing a line in the webpack.config.js to this:
`scss: 'vue-style-loader!css-loader!sass-loader?{"includePaths":["./node_modules"]}',`

This was a workaround I found by reading this issue: https://github.com/webpack-contrib/sass-loader/issues/412
But it's not working in this version of mix.  Looks like we'll have to find another workaround :(

In webpack-rules.js there is a section like this:
```
                stylus: vueExtractPlugin.extract({
                    use: 'css-loader!stylus-loader?paths[]=node_modules',
                    fallback: 'vue-style-loader'
                }),
```

I'm wondering why we can't add this path to the scss or sass loader?  It likely is a bug, that for some reason, not a lot of people care about.  According to the documentation in sass loader, something like this should work:

```
                scss: vueExtractPlugin.extract({
                    use: [{loader:'css-loader'},{loader:'sass-loader',options:{includePaths:["node_modules"]}}], // 'css-loader!sass-loader',
                    fallback: 'vue-style-loader'
                }),
```

I changed this in line 186 of webpack-rules.js but it seemed to have no effect.

If anyone else can figure this one out I would appreciate it greatly!

I'm using this library https://github.com/material-components/material-components-web in my project and it's a requirement that node_modules is in the path, and I need to import scss from my .vue files.

**Comment by xxRockOnxx** [comment]
Same situation as @lbjones . I would like to know also.

**Comment by charlielondon** [comment]
+1

**Comment by xxRockOnxx** [comment]
I managed to find a solution. Laravel-mix allows us to put extra webconfig. I just copied and pasted the default one and then added the extra configs.

I use `material-components-web` and needed to have an `includePath` so here's what I did:

```
mix.webpackConfig({
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',

        /**
         * For some reason I don't know why removing exclude does not compile properly
         */
        exclude: /bower_components/,

        options: {
          loaders: {
            js: {
              loader: 'babel-loader',
              options: Config.babel()
            },

            /**
             *  Here's where you put your extra configs
             */
            scss: [
              { loader: 'vue-style-loader' },
              { loader: 'css-loader' },
              {
                loader: 'sass-loader',
                options:{
                  includePaths: [path.resolve('./node_modules')]
                }
              }
            ]
          }
        }
      }
    ]
  }
});
```

**Comment by lbjones** [comment]
Solid work!  I just tried it and worked like a charm.  I tried several variations of the webpackConfig and never could find just the right formula.  Not having a good way to debug really makes for a difficult task.

Now the only thing left is to fix the uglifyjs error when you run `npm run prod`, I thought I had some good leads but still haven't successfully figured it out yet.

**Comment by robbyrice** [comment]
If you'd like to simplify things you might try adding this to your webpack.mix.js file.  It adds the node_modules folder to the include path for SASS and adds a config option to exclude all node_modules folders from uglifyjs processing except for the folder needed by Material Design Components (@material).  I had the same problems a while back and this is how I fixed them.  Hope it helps.

const { mix } = require('laravel-mix');

mix.options({})
  .webpackConfig ({
    module: {
      rules: [
        {
          test: /\.jsx?$/,
          exclude: /node_modules(?!\/@material)|bower_components/,
          use: [
            {
              loader: 'babel-loader',
              options: mix.config.babel()
            }
          ]
        }
      ]
    }
  })
  .sass('resources/assets/sass/app.scss', 'public/css', {
    includePaths: ['node_modules']
  });

**Comment by mrcsmcln** [comment]
@xxRockOnxx you need the `exclude` property in that config because Mix uses [`merge.smart()`](https://github.com/survivejs/webpack-merge#mergesmartconfiguration-configuration) and `merge.smart()` requires that the properties be the same to override a specific rule block.

**Comment by xxRockOnxx** [comment]
@mrcsmcln ahh, thanks for explaining. I thought `merge.smart()` only looks for same `test` not every properties.

**Comment by lysz210** [comment]
with laravel-mix 2.0 it can be done [extending mix](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/extending-mix.md).
With the mix.extend function you get the compiled webpack config, then find vue-loader and add the i18n loader, i preferd webpack-merge.smart
```
mix.extend('addI18nLoader', (webpackConfig, ...args) => {
    let vueLoader = webpackConfig.module.rules.find(loader => loader.loader == 'vue-loader')
    vueLoader.options = require('webpack-merge').smart(
        vueLoader.options,
        {
            loaders: {
                i18n: '@kazupon/vue-i18n-loader'
            }
        }
    )
})
mix.addI18nLoader()
...
```

**Comment by kennblvnp** [comment]
where is the solution?

**Comment by sentiasa** [comment]
I'm trying to change the "style-loader" for `target: node`. Do you guys know how to do that?

I explained my issue in detail on [StackOverflow](https://stackoverflow.com/questions/58296413/laravel-mix-window-is-not-defined-with-style-loader-in-target-node). I'd highly appreciate any help 🙏
