### ISSUE TITLE
Path in mix-manifest won't detect correct server url.

### ISSUE THREAD

**Issue by joshuajazleung** [JeffreyWay/laravel-mix#877]
My production app resides in a subfolder, example.com/laravel.
Apparently mix-manifest only assumes that my app is installed in the root folder, so that assets always point to example.com/js/..... and the like but not example.com/laravel/js/.

Therefore when I push my code to the server, the assets won't show correctly.

I am not sure if this is a bug or what, is there any way to fix it?

**Comment by ruchern** [comment]
Use `url()` or `asset()` helper.

Example:

`url(mix('js/app.js'))`

`asset('js/app.js')`

**Comment by snipe** [comment]
`<link rel="stylesheet" href="{{ asset('js/plugins/iCheck/all.css') }}">` does not seem to reflect subdirectories (using mix with laravel 5.4.20). It's still displaying the root URL.
