### ISSUE TITLE
Error on npm run production on shapecss

### ISSUE THREAD

**Issue by MicroDreamIT** [JeffreyWay/laravel-mix#878]
I am have error on `npm run production`, and its killing me :(

`/js/shapecss.js from UglifyJs
Unexpected token: name (Accordion) [./~/shapecss/resources/assets/js/component/Accordion.js:1,0][/js/shapecss.js:19054,6]
`

I am using shapecss developed in laravel mix.

here is code is look like,

```
'use strict';

import {Accordion} from "./component/Accordion";
import {Modal} from "./component/Modal";
import {getTab} from "./component/Tab";
import {Nav} from "./component/Nav";
import {Circle} from "./component/shapes/Circle";
import {Parallelogram} from "./component/shapes/Parallelogram";
import {Rectangle} from "./component/shapes/Rectangle";
import {Square} from "./component/shapes/Square";


window.onload = function () {
  new Accordion();
  new Modal();
  getTab();
  new Nav();
  new Circle();
  new Parallelogram();
  new Rectangle();
  new Square();
}
```

Accordion class is look like, 

```
export class Accordion{
        constructor(){
            this.accordionDivs = document.getElementsByClassName('accordion');
            if(this.accordionDivs)
            this.processAccordions();
        }
processAccordions() {
...
}

```

for detail please check, 

[Accordion class](https://github.com/MicroDreamIT/shapecss-framework/blob/master/resources/assets/js/component/Accordion.js)

[and entry file](https://github.com/MicroDreamIT/shapecss-framework/blob/master/resources/assets/js/shape.js),

**Comment by lucassmacedo** [comment]
have same problem

**Comment by lucassmacedo** [comment]
@JeffreyWay help us =(

**Comment by MicroDreamIT** [comment]
I have checked the reference and applied but did not worked. @JeffreyWay please take a look at it.

**Comment by ruchern** [comment]
@MicroDreamIT Can we see your `webpack.mix.js` file?

**Comment by MicroDreamIT** [comment]
Sure brother, 

```

mix.js('resources/assets/js/app.js', 'public/js/shapecss.js')
   .sass('resources/assets/sass/app.scss', 'public/css/shapecss.css')
    // .browserSync({'proxy':'localhost:8000'})
    // .options({processCssUrls: false})
    // .version()
;
```

**Comment by ruchern** [comment]
Can you remove the curly braces `{ }` for each import lines? Those are destructuring assigment.

Example for Accordion: 

```javascript
import Accordion from './components/Accordion'
```

**Comment by MicroDreamIT** [comment]
Yes sir, I have applied, now the error is,

```
WARNING in ./~/shapecss/resources/assets/js/shape.js
22:6-15 "export 'default' (imported as 'Accordion') was not found in './component/Accordion'
```

**Comment by ruchern** [comment]
```javascript
export default {
window.onload = function () {
  new Accordion();
  new Modal();
  getTab();
  new Nav();
  new Circle();
  new Parallelogram();
  new Rectangle();
  new Square();
}
}
```

**Comment by MicroDreamIT** [comment]
Sir I think the problem is on export default please take a look,

```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                                    4:19:45 PM


 error  in ./~/shapecss/resources/assets/js/shape.js

Module parse failed: C:\wamp64\www\OurProject\MicroDreamIT\node_modules\shapecss\resources\assets\js\shape.js Unexpected token (21:10)
You may need an appropriate loader to handle this file type.
|
| export default {
|     window.onload = function () {
|     new Accordion();
|     new Modal();

 @ ./resources/assets/js/bootstrap.js 4:15-63
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

```

**Comment by ruchern** [comment]
Sorry, I think I read the error message wrongly.

Revert back to this in `shapes.js`
    window.onload = function () {
        new Accordion();
        new Modal();
        getTab();
        new Nav();
        new Circle();
        new Parallelogram();
        new Rectangle();
        new Square();
    }

Try in `Accordion`,

```javascript
export default {
constructor() {
            this.accordionDivs = document.getElementsByClassName('accordion');
            if(this.accordionDivs)
            this.processAccordions();
        }
processAccordions() {
...
}
}
```

**Comment by MicroDreamIT** [comment]
sure sir let me try.

**Comment by MicroDreamIT** [comment]
no improvement, 

```

 error  in ./~/shapecss/resources/assets/js/component/Accordion.js

Module parse failed: C:\wamp64\www\OurProject\MicroDreamIT\node_modules\shapecss\resources\assets\js\component\Accordion.js Unexpected token (8:4)
You may need an appropriate loader to handle this file type.
|             this.processAccordions();
|     }
|     processAccordions() {
|         for(let i=0; i<this._accordionDivs.length;i++){
|             let accordionDiv = this._accordionDivs[i];

 @ ./~/shapecss/resources/assets/js/shape.js 10:0-46
 @ ./resources/assets/js/bootstrap.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

```

**Comment by ruchern** [comment]
@MicroDreamIT 

Also to note, why did your `shapecss` ending up in `node_modules`? I thought you're creating the framework?

**Comment by MicroDreamIT** [comment]
Yes I have created this framework, now i am using it in other project, as other people will do...

**Comment by MicroDreamIT** [comment]
We need transformer to uglify the script. I think laravel-mix is not well configured for that or webpack has those problem. It was good previously.

https://github.com/material-components/material-components-web/issues/531

**Comment by MicroDreamIT** [comment]
@lucassmacedo any update?

**Comment by ruchern** [comment]
@MicroDreamIT I'll pull your framework and try to run from my side. I was on the way home earlier.

**Comment by MicroDreamIT** [comment]
Sure Sir i will be waiting. 

Yes That's may be could happen. But here is the site, https://shapecss.com works very well. 

Here is the shapecss repository, waiting for your modification, https://github.com/MicroDreamIT/shapecss-framework/

**Comment by MicroDreamIT** [comment]
@ruchern @lucassmacedo any update bro?

**Comment by TheLarkInn** [comment]
This is not working be ause the es6 version of uglify has not landed yet, you will need to transpiled the js used to es5 before uglify can support it

**Comment by MicroDreamIT** [comment]
@TheLarkInn are you suggesting us to wait?

**Comment by TheLarkInn** [comment]
No im suggesting that you use a tool like babel to transpiled this code to es5 so uglify can minify it. ORRR use a tool like babili (babel-minify) to minify your code.

**Comment by JeffreyWay** [comment]
Mix's webpack config file doesn't run Babel on any files in your node_modules directory, so that's likely the issue.

**Comment by MicroDreamIT** [comment]
@JeffreyWay, I am really feeling great to have your reply. I have been trying to get your attention by tweeting and creating issues.

@TheLarkInn Thank you to join with me. Its an honor to get direction directly from you.

I have created a [framework shapecss](https://github.com/MicroDreamIT/shapecss-framework) (you can take a look at the file structure). Though I am not too much knowledgeable person as you guys. I just tried to build some thing by my own. Usually my base is laracasts. I dont know grunt, or to much core webpack. I have used Laravel mix to create this framework. 

I have followed code convention of [Mix ](https://github.com/JeffreyWay/laravel-mix/blob/master/src/Mix.js), I have found its pretty much es6 and compiling from node_modules.

The conclusion is, I need to convert my code to es5. If I am wrong please correct me and pardon me if my English is bad or for anything. I will be waiting for your answer.

**Comment by MicroDreamIT** [comment]
@TheLarkInn @JeffreyWay 

Question 1: if I wanted to use `babili (babel-minify)` then what will be `package.json` , or root `.babelrc` or `webpack.mix.js` file will look like?

Question 2: If I want to use `shapecss-framework` like `bootstrap` or `materialize` as standalone package in node_modules then what will be the best way to go?
