### ISSUE TITLE
.version() only works in production?

### ISSUE THREAD

**Issue by claytonrcarter** [JeffreyWay/laravel-mix#88]
It took me a while to track down the comments in the code that mention that file versioning is only performed when in production.  (Did I overlook this in the docs or API?)  I used to use versioning in development to make sure my changes were reloading when I refreshed the browser.  Is the assumption that we should use HMR for this now?

Regardless, issuing a warning that versioning is being skipped might be a nice touch.

**Comment by JeffreyWay** [comment]
I've added a note here: https://github.com/JeffreyWay/laravel-mix/releases/tag/v0.4.0

Don't forget that Laravel Mix hasn't even been officially released yet.
