### ISSUE TITLE
Compile not working

### ISSUE THREAD

**Issue by TWG-Matt** [JeffreyWay/laravel-mix#880]
- Laravel Mix Version: 0.12.1
- Node Version (`node -v`): 7.5.0
- NPM Version (`npm -v`): 4.1.2
- OS: Sierra 10.12.5

### Description:
I'm using this in a non-laravel project.  It was working until about a week ago.  When I try to run ```npm run dev``` nothing compiles anymore.  Here is my webpack.config.js file.

```
let mix = require('laravel-mix').mix;

mix.js('dev/js/site.js', 'public/assets/js')
    .sass('dev/scss/**/*.scss', 'public/assets/css');
```

### Steps To Reproduce:
I updated Laravel mix last week and after that I can no longer generate compiled CSS & JS files.

**Comment by ruchern** [comment]
Downgrade to 0.11.4

**Comment by JeffreyWay** [comment]
I can't help without more information. But try upgrading to the 1.0 release.
