### ISSUE TITLE
Laravel Mix errors on *.scss folder path

### ISSUE THREAD

**Issue by hardikdangar** [JeffreyWay/laravel-mix#882]
- Laravel Mix Version: #.#.# (`npm list --depth=0`) :  **0.12.1**
- Node Version (`node -v`): v8.1.0
- NPM Version (`npm -v`): 5.0.3
- OS: Ubuntu 16.04.2 LTS

### Description:

@import "metronics/global/**/*.scss";

does not work. i was expecting it will add all scss files from global folders recursively instead it give error.
File to import not found or unreadable: metronics/global/**/*.

### Steps To Reproduce:

default laravel mix file add following
@import "metronics/global/**/*.scss";

create metronics/global folder and add few scss files in that. and run
npm dev

**Comment by ruchern** [comment]
Correct me if I am wrong, you cannot use wildcards during import. Just manually add them line by line.

**Comment by hardikdangar** [comment]
I am not sure but i looked it up and i found,
https://www.npmjs.com/package/import-glob-loader and installed that 

but it seems its not working too. do we need too do something in webpack to enable that plugin?

**Comment by ruchern** [comment]
@hardikdangar You have to read the docs for the `import-glob-loader` and configure it in your `webpack.mix.js` file.

**Comment by tomsjac** [comment]
I have the same problem
webpack.mix.js file : 

`
mix.webpackConfig({
    module: {
        rules: [
              {
                test: /\.scss$/,
                loader: 'import-glob-loader'
            },
        ]
    }
});
`
The loader is not loaded
`
Module build failed: ModuleBuildError: Module build failed:
@import "../../../modules/**/assets/sass/*.scss";
`

**Comment by JeffreyWay** [comment]
I don't think this is a Mix issue, so closing.

**Comment by shooftie** [comment]
Did anyone fix this?
