### ISSUE TITLE
Add support for variable expansion?

### ISSUE THREAD

**Issue by eberkund** [JeffreyWay/laravel-mix#884]
It would be nice to be able to do something like this in my `.env` file,

    STRIPE_KEY=xxx
    MIX_STRIPE_KEY=${STRIPE_KEY}

Laravel handles this fine because _phpdotenv_ allows [nesting variables](https://github.com/vlucas/phpdotenv#nesting-variables) but it looks like the JavaScript version used by _laravel-mix_ [does not](https://www.npmjs.com/package/dotenv#what-about-variable-expansion). This would be a very helpful addition and it looks pretty simple [to add](https://github.com/motdotla/dotenv-expand#usage).

    var dotenv = require('dotenv')
    var dotenvExpand = require('dotenv-expand')

    var myEnv = dotenv.config()
    dotenvExpand(myEnv)

**Comment by JeffreyWay** [comment]
Merged.
