### ISSUE TITLE
i found mix difficulty to customize, is it?

### ISSUE THREAD

**Issue by buuug7** [JeffreyWay/laravel-mix#887]
@JeffreyWay 's work is very excellent,but i found it difficulty to customize. laravel make things simple ,but i found this tool make things more complex ,like how to watch pug template and compile with this tools, watch and copy file  seems has problem. 
if you copy file with html extension under src directory to dist directory  ,it will copy file to `dist/src/`directory,but i hope it will be `dist` directory ,what should i do? the directory structure like this
+ src
    - styles
    - scripts
    - index.html
    - content.html
+ dist
    - styles
    - scripts
 
```javascript
mix.copy('src/**/*.html','./dist');
```

**Comment by ankurk91** [comment]
Really ? 
Ever tried to configure build with webpack or gulp ?
Laravel-mix is helping millions so please don't blame just because you could not make it.

Have you gone through its documententation? You will find it easier than webpack.

**Comment by buuug7** [comment]
@ankurk91 but why copy file not work with me ,the situation is shown in the up

**Comment by ankurk91** [comment]
No one can help you unless you tell us what actually happened.

I would suggest you to fill [ISSUE_TEMPLATE](https://github.com/JeffreyWay/laravel-mix/blob/master/.github/ISSUE_TEMPLATE.md) so that one can reproduce the issue and post a solution.

**Comment by JeffreyWay** [comment]
If you need a lot of custom Webpack rules and watchers, you can either hook in with `mix.webpackConfig()`, or just maintain your own custom webpack.config.js file.

**Comment by buuug7** [comment]
@JeffreyWay thanks for your replay, i will read laravel-mix docs carefully and have a full understad it.
