### ISSUE TITLE
ProcessCssUrls + sourcemaps broken

### ISSUE THREAD

**Issue by stephan-v** [JeffreyWay/laravel-mix#890]
- Laravel Mix Version: 0.12.1
- Node Version (`node -v`): 7.4.0
- NPM Version (`npm -v`): 4.1.2
- OS: Ubuntu 16.04

### Description:

I thought this was resolved but whenever I add:

```
.options({
    processCssUrls: false
});
```

My sourcemaps stop working. With `processCssUrls` removed from my options It works fine again. 

When sourcemaps work I see a generated piece of code within my built file that contains a `sourceMappingUrl` this is no longer being generated when `processCssUrls` is set.

### Steps To Reproduce:

Generate a CSS file with sourcemapping enabled  and add `processCssUrls` to the `options` object.

**Comment by ruchern** [comment]
Did it worked previously on `0.11.4`?

**Comment by stephan-v** [comment]
I can't remember exactly but my previous package.json contained `0.11.4` and I don't always check sourcemaps but I think it worked fine. For certain it has worked fine on that version or a previous one since I haven't made any changes to my asset workflow during updates.

**Comment by JeffreyWay** [comment]
Pretty sure this is resolved in the latest version of Mix, which I'll tag later this week.
