### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by lspoor** [JeffreyWay/laravel-mix#891]
Delete

**Comment by ruchern** [comment]
Do not directly link files from `node_modules` directory.

Use `app.js` to import the scripts.

Example:

`app.js`
```javascript
window.$ = window.jQuery = require('jquery')
```

Then in your `webpack.mix.js`

```javascript
mix.js('resources/assets/js/app.js', 'public/js')
```

**Comment by lspoor** [comment]
@ruchern Right, Ill look at that then.

So is this correct?
```
window.$ = window.jQuery = require('jquery');
require('foundation-sites');

$(document).ready(function(){

});
```

Any ideas with my original issue of images not copying on watch task and why watch task fails?
