### ISSUE TITLE
Add support for typescript

### ISSUE THREAD

**Issue by Olian04** [JeffreyWay/laravel-mix#892]
Are there any plans to add ts support?

**Comment by JeffreyWay** [comment]
Yes, it's added in the 1.0 version coming soon.

**Comment by Olian04** [comment]
@JeffreyWay 1.0 is now released, but it said nothing of ts in the release notes. Did the plan change in the last 7hours or did I miss something?

**Comment by JeffreyWay** [comment]
I forgot, but it was actually added before 1.0. So you can do Mix.ts() now.

**Comment by Olian04** [comment]
Cool, thank you for the quick response :)
