### ISSUE TITLE
Webpack 3 - Scope Hoisting

### ISSUE THREAD

**Issue by lukepolo** [JeffreyWay/laravel-mix#893]
Webpack 3 was just released , and looks awesome , and we should put in the scope hosting in for beta 2

Should only be ran in production ~ 

```
module.exports = {  
  plugins: [
    new webpack.optimize.ModuleConcatenationPlugin()
  ]
};
```

**Comment by ruchern** [comment]
Just bump to Webpack 3.

https://github.com/JeffreyWay/laravel-mix/commit/7f37d5a8daf249ca7dd93ce878563330952fb2c8

**Comment by lukepolo** [comment]
Damn , hes quick!
