### ISSUE TITLE
mix.version() seems to be broken in v1.0

### ISSUE THREAD

**Issue by ruchern** [JeffreyWay/laravel-mix#895]
- Laravel Mix Version: 1.0.0 (`npm list --depth=0`)
- Node Version (`node -v`): 8.1.2
- NPM Version (`npm -v`): 5.0.3
- OS: macOS Sierra 10.12.5

### Description:
`mix.version()` seems to be broken. The files are not being hashed.

[![asciicast](https://asciinema.org/a/125383.png)](https://asciinema.org/a/125383)

`*.min.{js,css}` files were not created with the `mix.minify()` changes.

### Steps To Reproduce:
Running the script `npm run production` did not postfix hashes to the files. `mix.version()` was using it with 

```javascript
if (mix.inProduction()) {
    mix.version()
}
```

**Comment by coolcodemy** [comment]
Read the release note:

4. mix.minify() no longer overwrites the current file. Instead, it creates a *.min.js file alongside the original.

**Comment by ruchern** [comment]
@coolcodemy `*.min.{js,css}` was not created at all.

**Comment by JeffreyWay** [comment]
This is all covered in the release notes. 

https://github.com/JeffreyWay/laravel-mix/releases/tag/v1.0.0

Versioning is now applied within your `mix-manifest.json` file.

**Comment by ruchern** [comment]
@JeffreyWay Right, I see. It seemed like there are conflicting documentation in the release section and the documentation under versioning.md
