### ISSUE TITLE
[Proposal] A way to add mix commands which doesn't need to restart npm run watch/hot. Plus better mix files management.

### ISSUE THREAD

**Issue by ajcastro** [JeffreyWay/laravel-mix#896]
Currently, whenever I add a new mix command (e.g. compile a new src files to one dist file), I will edit my webpack.mix.js, then restart `npm run watch` so that it will take effect. I would like to propose to do that without restarting `npm run watch`. 

I am not sure if maybe it's possible that, we can separate the mix files from webpack.mix.js. My solution is somehow like this:
```
// root dir of laravel installation
/mix_files/
 |_ home.js     // mix file for home page
 |_ about.js    // mix file for about page
 |_ contact.js  // mix file for contact page
/webpack.mix.js
```
__webpack.mix.js__
```js
const { mix } = require('laravel-mix');

mix.watchFiles('./mix_files/'); 
// method name watchFiles is a suggestion only
// can accept string or array of filepaths or path pattern
```

__Sample content of `/mix_files/home.js`__
```js
const { mix } = require('laravel-mix');

mix.js([
 'resources/modules/home/some_home_fn.js',
 'resources/modules/home/another_home_fn.js',
], 'public/dist/home.js');

```

Another advantage is it is easy to manage mix files like this especially when your application js/css/any files becomes too large.

**Comment by JeffreyWay** [comment]
You edit your webpack.mix.js file so rarely to the point that I don't see a huge benefit. So for now we'll keep things as is.
