### ISSUE TITLE
Standlone Project failing

### ISSUE THREAD

**Issue by oyed** [JeffreyWay/laravel-mix#898]
- Laravel Mix Version: 1.0.0
- Node Version: 8.1.1
- NPM Version: 5.0.3
- OS: macOS Sierra

### Description:

The commit [9d2d80b](https://github.com/JeffreyWay/laravel-mix/commit/9d2d80b77c77f3631b0daabed45994cd43baaf60) removes the `webpack.config.js` from the standalone docs, and (as expected) on a new project, there is no `webpack.config.js` in the project root. As a result of this, calling `webpack` on the project root will obviously just fail.

### Steps To Reproduce:

- `npm install --save-dev laravel-mix`
- `cp -r node_modules/laravel-mix/setup/webpack.mix.js ./`
- Insert Mix Scripts in to `package.json`
- `npm run dev`

**Comment by implenton** [comment]
I managed to fix this by doing the following changes in the `webpack.config.js` file:

`require('../src/index');`

*and*

`let WebpackConfig = require('../src/builder/WebpackConfig');`

**changed to:**

`require('laravel-mix/src/index');`

*and*

`let WebpackConfig = require('laravel-mix/src/builder/WebpackConfig');`

**Comment by JeffreyWay** [comment]
The recommended approach now is to use our config file. So you'll want to add `--config=node_modules/laravel-mix/setup/webpack.config.js` to your npm script.
