### ISSUE TITLE
extensions is not defined

### ISSUE THREAD

**Issue by pderiy** [JeffreyWay/laravel-mix#900]
- Laravel Mix Version: 1.0
 Version (`node -v`): 6.11
- NPM Version (`npm -v`): 4.6.1 
- OS: Ubuntu 17.04

### Description:
I have an error when I'm trying to use typescript like this:
```
node_modules/laravel-mix/src/builder/webpack-rules.js:29
        extensions.push('.ts', '.tsx');
ReferenceError: extensions is not defined
```

There is no variable named 'extensions'. I think it happened after big refactoring on v1.0

### Steps To Reproduce:

```
mix
    .setPublicPath('static')
    .ts('angular/index.main.ts', 'vendor.js')
```

**Comment by JeffreyWay** [comment]
Thanks - this was fixed in 1da78b6ea0c1b256c582f5dbdea9b14802699e50. I just tagged it.
