### ISSUE TITLE
1.0.3: Webpack still asks for config file, errors when it gets one

### ISSUE THREAD

**Issue by moso** [JeffreyWay/laravel-mix#907]
- Laravel Mix Version: 1.0.3
- Node Version: v6.11.0
- NPM Version: v3.10.10 
- OS: Ubuntu 17.04

### Description:
I have recently updated from 0.12.1 to 1.0.3, and edited my `package.json`-scripts accordingly. And by the new structure design, one doesn't need a `webpack.config.js` in the root folder anymore.

However, when I run `npm run dev` to compile my JS and Sass, I get this error:
```bash
$ npm run dev

> moso-vue@1.0.0 dev /home/moso/Code/moso-vue
> NODE_ENV=development webpack --progress --hide-modules

No configuration file found and no output filename configured via CLI option.
A configuration file could be named 'webpack.config.js' in the current directory.
```

If I copy the shipped `webpack.config.js` from `node_modules/laravel-mix/setup/` to my project root, I get the following error:
```bash
$ npm run dev                                                                                                                          1 ↵

> moso-vue@1.0.0 dev /home/moso/Code/moso-vue
> NODE_ENV=development webpack --progress --hide-modules

module.js:471
    throw err;
    ^

Error: Cannot find module '../src/index'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/moso/Code/moso-vue/webpack.config.js:8:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

### Steps To Reproduce:
- `npm init -y`
- `npm install --save-dev laravel-mix`
- `cp -r node_modules/laravel-mix/setup/webpack.mix.js ./`
- Edited `webpack.mix.js` to my needs (`mix.js('src', 'output').sass('src', 'output');`)
- `npm run dev` (or any of the scripts from the documentation)

**Comment by JeffreyWay** [comment]
Add --config=node_modules/laravel-mix/setup/webpack.config.js to your npm script in package.json.
