### ISSUE TITLE
How to retrieve webpack config from elsewhere ?

### ISSUE THREAD

**Issue by monkeymonk** [JeffreyWay/laravel-mix#908]
Hi there,

is someone have an idea on how to retrieve the actual webpack config object from mix ?

I'm trying to setup an e2e testing and want to retrieve those settings... :-/

**Comment by ruchern** [comment]
It's in this directory ` --config=node_modules/laravel-mix/setup/webpack.config.js`

See docs/installation.md#npm-scripts

**Comment by monkeymonk** [comment]
Thank you @ruchern ! I'll try that ASAP and let you know.
