### ISSUE TITLE
Is it possible to compile multiple Javascript file with either a glob syntax, or simply compile all the files in a folder?

### ISSUE THREAD

**Issue by weaversam8** [JeffreyWay/laravel-mix#909]
Does Laravel Mix have the ability to compile all Javascript files in a folder?

Example of what I'm imagining:
```
mix.js('resources/assets/js/vendor/*.js', 'public/js/app.js');
```

Or would I need to use some node builtin to iterate through the files in the directory and construct an array?

Thanks!

**Comment by JeffreyWay** [comment]
You'd have to `require('glob')` and do it manually. But I wouldn't really recommend it. You should have a single entry file into your app.
