### ISSUE TITLE
[Proposal] Use multiple app

### ISSUE THREAD

**Issue by heyanlong** [JeffreyWay/laravel-mix#912]
Hi~
I want to create more than one app
e.g.
```
mix.js('resources/assets/vue/admin/admin.js', 'public/js/').extract(['vue'], "public/js/admin/vendor.js"); // site 1

mix.js('resources/assets/vue/mobile/mobile.js', 'public/js/').extract(['vue'], "public/js/mobile/vendor.js"); // site2
```
output
```
/js/admin.js
/js/admin/vendor.js
/js/admin/manifest.js
// ---
/js/mobile.js
/js/mobile/vendor.js
/js/mobile/manifest.js
```

- Laravel Mix Version: 1.0.3
- Node Version: v7.8.0
- NPM Version: 4.2.0
- OS: Darwin

**Comment by JeffreyWay** [comment]
You can call `mix.js()` multiple times, but there's no way right now to have entirely different builds.

**Comment by bhaidar** [comment]
@JeffreyWay Is there support for multiple apps now?

**Comment by ThaDaVos** [comment]
Anything on this?

**Comment by thecrypticace** [comment]
You can try something like this: https://gist.github.com/thecrypticace/52b5e54c74bd53077a058ba1cb958d9b

**Comment by ThaDaVos** [comment]
It looks amazing and I tried that but there's one issue -> the both want to use the same `mix-manifest` file - which will cause issues if you have to build both but keep them seperate - any solution for that?

**Comment by ThaDaVos** [comment]
I got it moved with this: https://github.com/JeffreyWay/laravel-mix/issues/1150
Using `mix.setPublicPath` seems to do the trick

**Comment by ThaDaVos** [comment]
This also helped: https://github.com/JeffreyWay/laravel-mix/issues/912#issuecomment-718750971
