### ISSUE TITLE
Importing a compiled .js file always comes empty

### ISSUE THREAD

**Issue by eddiemf** [JeffreyWay/laravel-mix#913]
- Laravel Mix Version: 1.0.3
- Node Version (`node -v`): 7.9.0
- NPM Version (`npm -v`): 4.2.0
- OS: Mac OS Sierra 10.12.5

### Description:
I'm building a vue plugin with laravel-mix. Whenever I try to `import plugin from 'plugin.js'`, this plugin variable comes always empty, but if I try to import the non-compiled plugin.js file, it works and the plugin is installed with Vue.use(plugin). I'm not sure, but may that have something to do with webpack output? 

### Steps To Reproduce:
You can reproduce trying to install the plugin it self at: https://github.com/eddiemf/vue-scrollactive

- Import using `import Scrollactive from 'vue-scrollactive'`
- console.log(Scrollactive)

It will return an empty object. But if you try to import the 'src/index.js' it will work.

PS.: I'm not quite sure it is a laravel-mix related problem, but I tried everything I could do and didn't find any solution.

**Comment by ankurk91** [comment]
You are developing a library, you have to configure your build system to generate a umd module by excluding any 3rd party library (vue in your case) 

https://webpack.js.org/guides/author-libraries/
You can see how I am doing here -

https://github.com/ankurk91/vue-bootstrap-datetimepicker/blob/master/webpack.config.js
