### ISSUE TITLE
External font (Raleway) not loaded anymore after update to v1.x

### ISSUE THREAD

**Issue by ThomHurks** [JeffreyWay/laravel-mix#917]
- Laravel Mix Version: 1.0.3
- Node Version (`node -v`): 8.0.0
- NPM Version (`npm -v`): 5.0.3
- OS: macOS Sierra 10.12.5
- Browser: Google Chrome 60

### Description:
After updating to Laravel-Mix 1.0.3 from 0.12.1, suddenly the external font I use does not load anymore. I'm working on a Laravel 5.4 project, and it loads the Raleway font in app.scss. My webpack.mix.js is pretty much the default (I just load the CSS of some packages and combine it) and I didn't change anything else when I updated to 1.0.3. Before update: everything looks good. After update: all my text looks different. I do see Raleway being mentioned in the output CSS, but I can see that Google Chrome does not actually load the Raleway font in the networks tab. When I revert to 0.12.1 it loads it up fine again and my text looks good.

### Steps To Reproduce:
I'm not exactly sure. I simply updated to 1.0.3 and my external font (Raleway) isn't downloaded anymore. I revert to 0.12.1 and everything works again. My project is based on the default Laravel 5.4 project and follows it pretty closely; the default Laravel project also loads up Raleway in the same way.

**Comment by ThomHurks** [comment]
@JeffreyWay I found what the issue is. The call to combine() doesn't seem to preserve order anymore! I'm using sass() for my own CSS, but of course I have tons of libraries whose CSS I still need to copy as Webpack doesn't collect CSS automatically, unlike the JS. 
So I'm copying in a bunch of CSS files from node_modules and use combine() to put them in one file. That's where it goes wrong. Previously, my own sass file with an @import url("") statement was at the *top* of the file. Now it isn't anymore! It ends up in the middle of the combined file, even though it's first in the input array.

What does CSS documentation say about this?

> The \@import CSS at-rule is used to import style rules from other style sheets. These rules must precede all other types of rules, except \@charset rules; 

And that's another problem; the @charset rule also follows *after* the @import url("") rule.

So with Mix v1.x I need to manually fix my CSS after compiling each time to make it valid. Not nice! Mix should always generate valid CSS.

**Comment by bellwood** [comment]
What I did to overcome this was make a css file just for my google font imports and specified it first:

```
mix.styles([
	'public/css/vendor/google-fonts.css',
        'public/css/vendor/bootstrap.min.css',
        'public/css/custom.css'
    ], 'public/css/app.css')
    .version();
```

This ensures my fonts are imported properly.

HTH

**Comment by ThomHurks** [comment]
@bellwood I ended up fixing it by only having a single ```mix.sass()``` call in my webpack.mix.js file and then ```@import()```ing all CSS files in my app.scss file.
