### ISSUE TITLE
Compiling the same SCSS asset twice with two different node-sass options?

### ISSUE THREAD

**Issue by weaversam8** [JeffreyWay/laravel-mix#918]
I am trying to compile an asset in two different ways, with two different configurations.

Example:

```js
mix.sass('path/to/same/file.scss', 'public/css/1.css', {
  importer: [
    function1
  ]
});
mix.sass('path/to/same/file.scss', 'public/css/2.css', {
  importer: [
    function2
  ]
});
```

The options you see above are passed to `node-sass` which compiles the sass, and the importer option can be detailed on their project page [here.](https://github.com/sass/node-sass#importer--v200---experimental) I can confirm that this has worked as expected once, and only becomes an issue when I attempt to do the above scenario compiling the same file.

With the following actual function calls:

```js
mix.js(["resources/assets/js/app.js","resources/assets/js/vendor/core/core.js"],'public/js/app.js');
mix.copy("node_modules/winstrap/dist/fonts", 'public/fonts')
mix.sass('resources/assets/sass/app.scss', 'public/css/app.css', { ... });
mix.sass('resources/assets/sass/app.scss', 'public/css/red.css', { ... });
```

I am getting the following very verbose error that talks a lot about JS, but I know for a fact that this issue is with SCSS because it is only apparent when I run the code relating to SCSS:

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   The entry point(s) of the compilation.
   Details:
    * configuration.entry['\js\app'] should be a string.
    * configuration.entry['\js\app'] should NOT have duplicate items (items ## 2 and 3 are identical) ({
        "keyword": "uniqueItems",
        "dataPath": ".entry['\\js\\app']",
        "schemaPath": "#/definitions/common.nonEmptyArrayOfUniqueStringValues/uniqueItems",
        "params": {
          "i": 3,
          "j": 2
        },
        "message": "should NOT have duplicate items (items ## 2 and 3 are identical)",
        "schema": true,
        "parentSchema": {
          "items": {
            "minLength": 1,
            "type": "string"
          },
          "minItems": 1,
          "type": "array",
          "uniqueItems": true
        },
        "data": [
          "C:\\Users\\{username}\\Documents\\{project_name}\\resources\\assets\\js\\app.js",
          "C:\\Users\\{username}\\Documents\\{project_name}\\resources\\assets\\js\\vendor\\core\\core.js",
          "C:\\Users\\{username}\\Documents\\{project_name}\\resources\\assets\\sass\\app.scss",
          "C:\\Users\\{username}\\Documents\\{project_name}\\resources\\assets\\sass\\app.scss"
        ]
      }).
      [non-empty string]
    * configuration.entry['\js\app'] should be one of these:
      non-empty string | [non-empty string]
    * configuration.entry should be a string.
    * configuration.entry should be an array:
      [non-empty string]
    * configuration.entry should be an instance of function
      function returning an entry object or a promise..
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_module
s/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\{username}\AppData\Roaming\npm-cache\_logs\2017-06-21T23_42_34_644Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\{username}\AppData\Roaming\npm-cache\_logs\2017-06-21T23_42_34_877Z-debug.log
```

Why is this occurring, and how can I accomplish my goal?

**Comment by JeffreyWay** [comment]
What version of Laravel Mix do you have installed?

**Comment by weaversam8** [comment]
@JeffreyWay The version constraint I have in my `package.json` is `^1.0.3`, and my `package-lock.json` indicates that that version is indeed installed.

**Comment by weaversam8** [comment]
So, what it seems like the error is is that the schema asks for `"uniqueItems": true` but the `"data"` array has a duplicate.

I'm not insanely familiar with webpack, so I'm assuming that this is the data object passed to webpack, but it makes sense why the error is occurring. I would assume that webpack should be able to compile the same file differently in two ways, i.e. if I wanted to compile to both minified and unminified output, so I assume there's something that can be done in laravel-mix to allow what's going on. If I understand more, I might be able to submit a PR.

**Comment by weaversam8** [comment]
In the interest of providing more information, I've also extracted the result of compiling my mix files, into what I believe is the options object passed to webpack. This can be found on a secret gist [here.](https://gist.github.com/weaversam8/4fdfd07abf5b89a73eb2ab1c1c7f40e0)

**Comment by JeffreyWay** [comment]
Yeah, you can't request to compile the same file twice. Mix doesn't work that way, so it just looks like you're passing the exact same file to webpack twice.

**Comment by weaversam8** [comment]
@JeffreyWay is there a way in full webpack to do what I want?

**Comment by KaiFuglem** [comment]
@weaversam8 did you ever find a solution to this issue? ...I'm in the same boat as you

**Comment by weaversam8** [comment]
@KaiFuglem Wow, this was quite a while ago. I don't remember my solution, but I'm willing to bet I ended up building a custom Webpack configuration to do it... The [webpack documentation](https://webpack.js.org/concepts/) is pretty good, so I'm sure there's a way to do it the way you want.
