### ISSUE TITLE
versioning in 1.0.3

### ISSUE THREAD

**Issue by exwizzard** [JeffreyWay/laravel-mix#920]
- Laravel Mix Version: 1.0.3 (`npm list --depth=0`)
- Node Version (`node -v`): 8.1.2
- NPM Version (`npm -v`):  5.0.3
- OS: 

### Description:

When I use mix.version() after updating everything works fine but the npm run dev output doesn't show that the files are being versioned in the output. When I check mix-manifest.json they are actually versioned correctly, so not sure why the npm output is not saying it anymore.
```
/js/adminPanel.js  1.37 MB       0  [emitted]  [big]  /js/adminPanel
/js/app.js  1.21 MB       1  [emitted]  [big]  /js/app
/css/app.css   185 kB       1  [emitted]         /js/app
/css/adminPanel.css   352 kB       1  [emitted]  [big]  /js/app

```

### Steps To Reproduce:

Add mix.version() and do npm run dev

**Comment by ruchern** [comment]
Related #895

**Comment by Tchanove** [comment]
Hi there ! :)
Can I ask why the query string based versioning is now mandatory when it's well know that it can put you in trouble when using CDN ?
Is it possible to have an option choose which type of versioning we want to use ?

Keep up the good work btw ! :)

**Comment by ruchern** [comment]
@Tchanove Why are you using CDN? With Laravel-Mix and npm packages, there are literally no reasons to use CDN now.

**Comment by devcircus** [comment]
This was discussed before it was implemented and virtual, if not all, cdns allow for the query string. It may have to be enabled but it will work.
Per the release notes: 
> If using a service like Cloudflare, please ensure that you've enabled querystring-based cache-busting.

**Comment by Tchanove** [comment]
Okay okay, I think CDN can still be useful for large scale multilingual website.
But I agree that the first part of the job is the lower level optimization that Laravel-Mix provide.

I was mainly curious about what pushed the choice of query string versioning (for educational purpose).

Ty for your help and your answers ! 👍

**Comment by JeffreyWay** [comment]
> I was mainly curious about what pushed the choice of query string versioning (for educational purpose).

It simplifies the codebase and the work Mix has to do drastically. It also makes the API easier for folks to use, for a variety of small reasons.

**Comment by kdekooter** [comment]
Browsers seems to ignore everything after `?=` when deciding is a file is a new version. So this method of versioning does _not_ help with caching issues.
