### ISSUE TITLE
Preprocessing as task

### ISSUE THREAD

**Issue by VRuzhentsov** [JeffreyWay/laravel-mix#922]
For example, i need to compile a several sass files, but it is not so good, to do something like that:
`mix.sass("resources/assets/sass/pages/about.scss", "public/assets/pages/css")
    .sass("resources/assets/sass/pages/blog.scss", "public/assets/pages/css")
    .sass("resources/assets/sass/pages/coming-soon.scss", "public/assets/pages/css")
    .sass("resources/assets/sass/pages/contact.scss", "public/assets/pages/css")
    .sass("resources/assets/sass/pages/error.scss", "public/assets/pages/css")
    .sass("resources/assets/sass/pages/faq.scss", "public/assets/pages/css")
    .sass("resources/assets/sass/pages/home.scss", "public/assets/pages/css")`

So, to implement several defenition like 
`.sass("resources/assets/sass/pages/*.scss", "public/assets/pages/css")`
OR
`.sass("resources/assets/sass/pages/", "public/assets/pages/css")`
i found, that it could be implemented via `Mix Tasks` like the latest `copy` implementation. 
I think, that could do some PR this weekend

@JeffreyWay What do you think?

**Comment by ruchern** [comment]
Create a file `pages.scss` or whatever name you want it to be. 

Use the `@import` method for all your `.scss` files above.

Example:
```
@import "path/to/1.scss"
@import "path/to/2.scss"
```

After which, just add one line to your `webpack.mix.js` file linking to that `pages.scss`

**Comment by VRuzhentsov** [comment]
it could save my situation. Thanks
