### ISSUE TITLE
A publicPath pointing outside the root folder -> incorrect paths for the js file

### ISSUE THREAD

**Issue by LostKobrakai** [JeffreyWay/laravel-mix#924]
- Laravel Mix Version: 1.0.5
- Node Version (`node -v`): 8.1.2
- NPM Version (`npm -v`): 5.0.3
- OS: MacOS X 10.12.5

### Description:

A publicPath pointing outside the root folder where npm is run does result in incorrect paths for the js file (css/copyDirectory does still work). The elixir framework phoenix does have a nested assets folder for it's npm stuff, whereas the public path is in a different branch from the project root:

```
root
|-assets
| |- static
| | |- logo, …
| |- package.json
| |- webpack.mix.js
|-priv
  |- static
    |- js
    |- css
```

### Steps To Reproduce:

```js
mix.setPublicPath('../priv/static')
   .js('js/app.js', 'js/app.js')
   .sass('css/app.scss', 'css/app.css')
   .copyDirectory('./static', '../priv/static');
```
This results in the following output of webpack:

```
/Users/benni/Sites/madeit/priv/static/js/app.js  182 kB       0  [emitted]  …
                                    css/app.css  152 kB       0  [emitted]  …
```
Meaning the js file is being put in `../priv/static/Users/benni/[…]`

### Temp. fix

`ln -s ../priv/static output` and
```js
mix.setPublicPath('output')
   .js('js/app.js', 'js/app.js')
   .sass('css/app.scss', 'css/app.css')
   .copyDirectory('./static', 'output');
```
Using that results in:
```
 /js/app.js  182 kB       0  [emitted]  /js/app
css/app.css  152 kB       0  [emitted]  /js/app
```
and therefore correct paths (still curious about the leading /).

**Comment by TopFuel** [comment]
I'm having the same problem, I reported it [here](https://github.com/JeffreyWay/laravel-mix/issues/860#issuecomment-306694655), at the moment I'm using that fix I mentioned.

**Comment by routegroup** [comment]
Same here.

- Laravel Mix Version: 1.0.7
- Node Version: 8.1.2
- NPM Version: 5.0.4
- OS: MacOS X 10.12.5

Problem is that the File instance is not resolving publicPath, only rootPath. Because of files that are in root path we should resolve both cases. 

In file: [src/File.js:93](https://github.com/JeffreyWay/laravel-mix/blob/master/src/File.js#L93) something like

```js
return this.path().replace(Mix.paths.root() + path.sep, '')
            .replace(path.resolve(Mix.paths.root(), Config.publicPath), '');
```

should does job.

**Comment by wanted80** [comment]
I have the same issue with this new 1.0 version. My combined js scripts are saved into Laravel dir and not into my public dir that is placed outside Laravel (same level of Laravel dir).

This code below works fine in the 0.12.1 version but give me an error on the new 1.0 version:

```javascript
mix
    .setPublicPath('../public_html')
    .copyDirectory(paths.bootstrap + 'fonts/bootstrap/', '../public_html/fonts/bootstrap')
    .copyDirectory(paths.fontawesome + 'fonts/', '../public_html/fonts/fontawesome')
    .sass('resources/assets/sass/app.scss', '/css/all.css')
    .combine([
        'resources/assets/js/admin/plugins.js',
        'resources/assets/js/admin/main.js'
    ], '../public_html/js/admin.js')
    .version();
```

After some tests i changed my code to this and partially works but the 'js/admin.js' script is generated under Laravel dir and not under my public_html dir.

```javascript
mix
    .setPublicPath('../public_html')
    .copyDirectory(paths.bootstrap + 'fonts/bootstrap/', '../public_html/fonts/bootstrap')
    .copyDirectory(paths.fontawesome + 'fonts/', '../public_html/fonts/fontawesome')
    .sass('resources/assets/sass/app.scss', '/css/all.css')
    .combine([
        'resources/assets/js/admin/plugins.js',
        'resources/assets/js/admin/main.js'
    ], 'js/admin.js')
    /* Temp Fix */
    .copyDirectory('./js/', '../public_html/js')
    .version();
```

Is there a fix for that issue? Any suggestion? Thanks.

**Comment by routegroup** [comment]
@wanted80 look for to my post above. I said what happend and temporary fix (sadly inside node modules... time to make pr...)

**Comment by wanted80** [comment]
@routegroup I tried to solve the issue with your fix but didn't work in my case...

**Comment by TopFuel** [comment]
@wanted80 try with the fix I posted [here](https://github.com/JeffreyWay/laravel-mix/issues/860#issuecomment-306694655), it's working fine for me, I'm on windows but it should work on linux too, just skip the part about changing from `/` to `\\`.

**Comment by wanted80** [comment]
@TopFuel tried your fix and now it works fine. With that i can revert my code to the previous version and works. Thank you.

**Comment by TopFuel** [comment]
The PR #964 fixed the issue, it should be released soon 👍

**Comment by brian-lamb-software-engineer** [comment]
I found that using this path style, on windows solves the issue for me
`mix.setPublicPath('..\\html\\public')`
