### ISSUE TITLE
Laravel-mix `npm run production` hangs at "91% additional asset processing" then exits to command line

### ISSUE THREAD

**Issue by shorlbeck** [JeffreyWay/laravel-mix#926]
- Laravel Mix Version: 1.0.6
- Node Version: 6.11.0
- NPM Version: 5.0.3
- OS: Ubuntu Server 16.04.2 LTS

### Description:

During my application's deploy process, running `npm run production` causes `laravel-mix` and/or `webpack` to hang at `91% additional asset processing`, and then exits to the command line without completing asset compilation. This issue has been mentioned on the [webpack issue tracker](https://github.com/webpack/webpack/issues/4558) and has been closed, but I can't seem to figure out what the actual solution is for a `laravel-mix` user, aside from updating everything to the latest version(s) which did not seem to help. I believe this is occurring because I have a very large SPA project with many Vue components and it is running out of memory while minifying/concatenating everything. (Running `npm run dev` works fine.) I don't know enough about `webpack` personally, I just use `laravel-mix`.

### Steps To Reproduce:

- Large single-page-app project with lots of Vue components and `vue-router`. (Sorry I cannot provide this.)

- Use the following `package.json` file:

```
{
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development webpack --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "cross-env NODE_ENV=development webpack-dev-server --watch-poll --inline --hot --output-public-path http://myapp.local/ --host myapp.local --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "cross-env NODE_ENV=production webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.15.2",
    "bootstrap": "^3.3.7",
    "bootstrap-sass": "^3.3.7",
    "jquery": "^3.2.1",
    "laravel-mix": "^1.0.3",
    "lodash": "^4.16.2",
    "pusher-js": "^4.0.0",
    "select2": "^4.0.3",
    "vue": "^2.2.6",
    "vue-multiselect": "^2.0.0-beta.15",
    "vue-resource": "^1.3.1",
    "vue-router": "^2.4.0"
  },
  "dependencies": {
    "cross-env": "^5.0.1",
    "laravel-echo": "^1.3.0",
    "moment": "^2.18.1",
    "moment-timezone": "^0.5.13",
    "rrule": "^2.2.0",
    "webpack": "^3.0.0"
  },
  "peerDependencies": {
    "webpack": "^2.2.0"
  }
}

```

- Then run `npm run production` to compile all assets.

As a side note, the `package.json` file above also gives me issues with unmet peer dependencies when I run `npm list --depth=0`. I see an `UNMET PEER DEPENDENCY` for `webpack@3.0.0` but also `npm ERR! peer dep missing: webpack@^2.2.0` for multiple other packages. This is why I was trying to include them both somehow, but I don't know how to install multiple versions of webpack the correct way to meet these peer dependencies.

**Comment by ruchern** [comment]
Check if your Ubuntu server has a pagefile. Like you have mentioned that it could be a lack of memory.

**Comment by shorlbeck** [comment]
@ruchern It's a default Amazon EC2 instance, and apparently they don't have swap files enabled by default. (Running `swapon -s` gives an empty result.) I will look into setting up swap on it. Meanwhile, I'm wondering if there is any `laravel-mix` or `webpack` configuration that can take care of this, as well.

**Comment by ruchern** [comment]
Create a swapfile 2x the size of the phyiscal ram.

**Comment by shorlbeck** [comment]
> I don't think `laravel-mix` or `webpack` has anything to do with this. It is definitely a lack of ram where `npm` actually needs.

@ruchern You sure about that? [This comment](https://github.com/webpack/webpack/issues/4550#issuecomment-289096445) says that "reading the string content should be avoided until you are done appending" -- so probably a `webpack` issue more than `laravel-mix` issue. I am just hoping that `laravel-mix` picks up the version of `webpack` that contains the fix, which is [supposedly already fixed](https://github.com/webpack/webpack/issues/4550#issuecomment-289404644).

**Comment by shorlbeck** [comment]
Ok, so I did two things to remedy this situation:

1. I rewrote my deploy script so that `npm run production` is run locally and then rsynced to the server. This alone solved the problem, but since memory was an issue and there was no swap enabled, I also...
2. Enabled swap as per [this comment](https://stackoverflow.com/a/17173973/1071874) and made sure it was 2x the size of physical ram.

Things are working now, although I did step 1 first, so I haven't had a chance to confirm that the swap alone would resolve it.

**Comment by ruchern** [comment]
@shorlbeck It happened to me on my production server where I only had 512MB of RAM. I added a 2 GB swapfile and the compiling continued past `91% additional processing`.

**Comment by 4eck-media** [comment]
.setPublicPath('public') worked here!

**Comment by BibekStha** [comment]
Anyone coming back to this page, I can confirm creating swapfile fixed the problem for me.

OS: Ubuntu 18.04.3 LTS
Node: 10.17.0
NPM: 6.11.3
Laravel-mix: 2.1.14

RAM: 4GB
Swap: 4GB

**Comment by bhavinjr** [comment]
I had the same issue. sometimes it's working sometimes not.

@BibekStha as you suggest I created a swapfile now. now `yarn production` is working fine.

I Followed https://linuxize.com/post/how-to-add-swap-space-on-ubuntu-18-04/ this link

@BibekStha can u suggest tutorial for this or above link will work perfectly
