### ISSUE TITLE
How to copy only new or modified files and directories?

### ISSUE THREAD

**Issue by monkeymonk** [JeffreyWay/laravel-mix#928]
- Laravel Mix Version: 0.10.0 (`npm list --depth=0`)
- Node Version (`node -v`):  6.9.2
- NPM Version (`npm -v`): 3.10.9
- OS: OS X 10.11.6

### Description:

Hello there,

I'm trying to optimize a little bit the "copy" task that I use :

```
if (options.copy) {
    Object.keys(options.copy).map((key) => mix.copy(options.copy[key], `${options.directories.dist}/${key}`));
}
```

every thing go fine but I want that this task executes only when there is something new... and not each time I ran a "dev", "watch" or "production" command.

Any clues or ideas?

**Comment by JeffreyWay** [comment]
It's nothing that Mix supports out of the box. I suppose you could check the last time the file was created, but I typically don't worry about it.

**Comment by monkeymonk** [comment]
Ok ! Fait enough, 'will ask StakOverflow then! ;-)
And, by the way, thank's again for the hard work!
