### ISSUE TITLE
Referencing a custom webpack.mix.js file

### ISSUE THREAD

**Issue by grafikkaos** [JeffreyWay/laravel-mix#931]
Hi guys,

I am currently working on a modular theme structure and I would like to use Laravel Mix and Webpack.  In my previous iterations, I was using gulp and was able to successfully use custom gulp configurations by passing the --gulpfile option and the path to gulpfile.js.

I am trying to do the same with laravel mix and webpack.  I have attached an image of my theme folder structure.
![custom_webpack_mix_js](https://user-images.githubusercontent.com/124558/27519823-473a55b0-59f4-11e7-91a4-138e5070109a.png)

While I have the webpack.config.js and webpack.mix.js files in the theme folder and added a new line in the package.json file 
[package.json.txt](https://github.com/JeffreyWay/laravel-mix/files/1100655/package.json.txt), when I run npm run dev-1, everything seems to work, except that it does not read the webpack.mix.js file.

It seems that somewhere, laravel mix is looking for the webpack.mix.js file at the root of the project and ignoring the one in the theme folder.

Anyway I can fix this?

THanks

**Comment by VinceG** [comment]
@grafikkaos see #989 

It was an option in 0.12.0 but somehow got dropped in the rewrite of Mix.
