### ISSUE TITLE
Hot Module Replacement not working with React (reloads the page)

### ISSUE THREAD

**Issue by morrislaptop** [JeffreyWay/laravel-mix#937]
- Laravel Mix Version: 1.0.7
- Node Version (`node -v`): v8.1.2
- NPM Version (`npm -v`): 5.0.3
- OS: Mac 10.12

### Description:

Trying to enable this, however it reloads the page whenever the JS is recompiled. Is this supposed to work out of the box? 

### Steps To Reproduce:

1. Clone https://github.com/morrislaptop/laravel54-react
2. Run npm install
3. Run npm run hot
4. Load website in browswer
5. Make a change to resources/assets/js/components/Example.js
6. Observe browser reloads instead of HMR

**Comment by morrislaptop** [comment]
?

**Comment by pderiy** [comment]
Hi,
I have the same issue with AngularJS using TS.

**Comment by xiomai** [comment]
I've had this issue before which was fixed by adding this lines at the end to my root react js file:
```
if (process.env.NODE_ENV === 'development') {
	if (module.hot) {
		module.hot.accept();
	}
}
```
it also works if I put it in `resources/assets/js/app.js`

**Comment by oneso** [comment]
You can install this: `babel-preset-react-hmre` and add a .babelrc file with:
`{
  "presets": ["babel-preset-react-hmre"]
}`

**Comment by pderiy** [comment]
@oneso what is about AngularJS with Typescript?

**Comment by oneso** [comment]
Sorry i am not familiar with AngularJS. But i just set up webpack + react + typescript + hot reload. But this would be complete out of topic.

**Comment by pderiy** [comment]
@oneso 
This works great for me:
```js
module.hot.accept()
```
What if laravel-mix will append it autimatically when we use HMR?
