### ISSUE TITLE
How to modify custom rules since webpack.config.js has been splitted >

### ISSUE THREAD

**Issue by dib258** [JeffreyWay/laravel-mix#942]
- Laravel Mix Version: 1.0.3
- Node Version : 8.1.0 
- NPM Version : 5.0.3
- OS:  OSX

I was on the 0.8.8 version of Laravel mix and had a custom `webpack.config.js`. Since I updated because of some recurring errors. I found out that this `webpack.config.js` file was completly remodeled. How can we make a custom one now ?

I have some custom options in the `webpack-rules.js`.

If I want to make  these modifications, do I need to export from the node_modules :

- webpack.config.js 
- WebpackConfig.js
- webpack-rules.js

In the right directory to be able to modify just the options ?

Let me know how you are doing your customs modifications since the `webpack.config.js` is now splitted into multiple files !

Thanks in advance for you answer,

**Comment by JeffreyWay** [comment]
Can you use mix.webpackConfig() to inject your custom rules?

**Comment by c0defre4k** [comment]
I have a similar problem. Injecting via mix.webpackConfig() usually works. In my case I'm loading my icons via the svg-sprite-loader. Since the default fonts rule also applies to *.svg files they are process twice.

A possible solution would be to provide options in mix to override the include/exclude options (see: https://webpack.js.org/configuration/module/#rule-exclude) for default rules.

**Comment by dib258** [comment]
I tried using mix.webpackConfig() but don't have enough knowledge to extract the modifications I made in the config file and translate them in the webpackConfig.

For now, I downgraded to the version I was using (0.8.8) for the current project and I'll look into this when I will have time. 

Thanks anyway and Thank you Jeffrey for the Laravel Mix package !

**Comment by hdl-helsinki** [comment]
Does somebody have an example? I need to change the file loader rules as it was on 0.12.1:

```js
    {
        test: /\.(woff2?|ttf|eot|svg|otf)$/,
        loader: 'file-loader',
        options: {
            name: path => {
                if (! /node_modules|bower_components/.test(path)) {
                    return 'my/custom/path/[name].[ext]?[hash]';
                }

                return 'my/custom/path/' + path
                    .replace(/\\/g, '/')
                    .replace(
                        /((.*(node_modules|bower_components))|fonts|font|assets)\//g, ''
                    ) + '?[hash]';
            },
            publicPath: Mix.options.resourceRoot
        }
    },
```
