### ISSUE TITLE
HMR not working on a fresh larvel app ('Cannot GET /')

### ISSUE THREAD

**Issue by rleger** [JeffreyWay/laravel-mix#944]
- Laravel Mix Version: #.#.# (`npm list --depth=0`)
├── axios@0.15.3
├── bootstrap-sass@3.3.7
├── cross-env@3.2.4
├── jquery@3.2.1
├── laravel-mix@1.0.7
├── lodash@4.17.4
└── vue@2.3.4
- Node Version (`node -v`): v8.1.2
- NPM Version (`npm -v`): 5.0.4
- OS: 10.12.15

### Description:

Hi,
Trying to use hot module reload with vue. I get "Cannot GET /" when browsing to localhost:8080. I've rebooted, updated brew (node), npm and such. For information I have Valet set up on my machine.
I reference my scripts and css via mix blade helper.

Thanks very much for the hard work to make our lives easier !

### Steps To Reproduce:
`
laravel new hot
cd hot
yarn
npm run hot

browse to http://localhost:8080
Error : 'Cannot GET /'
`

**Comment by ruchern** [comment]
What is your configuration in `webpack.mix.js`?

**Comment by rleger** [comment]
I left it unchanged as I wanted to eliminate a potential error on my part.

```
let mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');
```

**Comment by ankurk91** [comment]
https://github.com/JeffreyWay/laravel-mix/issues/344#issuecomment-313580161

**Comment by rleger** [comment]
Thanks so much !
