### ISSUE TITLE
Watch working correctly?

### ISSUE THREAD

**Issue by it-can** [JeffreyWay/laravel-mix#945]
- Laravel Mix Version: v1.0.7
- Node Version (`node -v`): v8.1.2
- NPM Version (`npm -v`): v5.0.3
- OS: mac os x sierra

### Description:
Okay it's a bit weird, when changing my less files the notifier etc is triggered and I see the compiling on my console. But when changing my js files this does not happen, it seems to update though.
It also seems not to run uglify when running ```npm run watch```, when running ```npm run prod``` it seems to run uglify...

This is my package.json file
```
{
  "private": true,
  "scripts": {
    "dev": "npm run production",
    "development": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=production node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "cross-env": "^5.0.1",
    "laravel-mix": "^1.0",
    "less": "^2.7.2",
    "less-loader": "^4.0.4",
    "css-loader": "^0.14.5"
  }
}
```

This is my webpack file.

```
let mix = require('laravel-mix');

var paths = {
    'jquery': 'resources/vendor/jquery',
    'bootstrap': 'resources/vendor/bootstrap',
    'fontawesome': 'resources/vendor/font-awesome',
    'scripts': 'resources/assets/js'
};

mix.options({
    processCssUrls: false,
    purifyCss: false,

    postCss: [
        require('postcss-discard-comments')({
            removeAll: true
        }),

        require('autoprefixer')({
            browsers: ['last 2 versions', '> 1%']
        })
    ],

    uglify: {
        comments: false
    }
});

mix.less('resources/assets/less/production.less', 'public/assets/css')
    .scripts([
        paths.jquery + '/jquery.js',
        paths.bootstrap + '/bootstrap.js',
        paths.bootstrap + '/ie10-viewport-bug-workaround.js',
        paths.scripts + '/scripts.js'
    ], 'public/assets/js/app.js')
    .scripts([
        paths.scripts + '/moment.js',
        paths.scripts + '/fullcalendar.js',
        paths.scripts + '/fullcalendar-nl.js',
        paths.scripts + '/daterangepicker.js',
        paths.scripts + '/jstree.js'
    ], 'public/assets/js/admin.js')
    .version();
```

**Comment by devcircus** [comment]
Is any of that supposed to show in the console?
From the docs: 
> Combine Files

Consider the following snippet:

mix.combine(['one.js', 'two.js'], 'merged.js');
This will naturally merge one.js and two.js into a single file, called merged.js. As always, during development, that merged file will remain uncompressed. However, for production (export NODE_ENV=production), this command will additionally minify merged.js.

So it seems like npm watch isn't supposed to use uglify and mix.scripts(mix.combine) doesn't touch webpack at all. I know pre 1.0.0, if webpack wasn't involved, you didn't get console feedback. Maybe that has changed since 1.0.0, I'm not sure.

**Comment by devcircus** [comment]
Ok, it does look like 1.0.0 added the ability to show non-webpack task results in the console.
Per the release notes:
> The terminal compile output will now better reflect all files that are being processed.

**Comment by it-can** [comment]
I expect that uglify works on watch, calling it with the production flag... worked pre 1.0 version...

**Comment by JeffreyWay** [comment]
I'm trying to think of why you would ever want uglification for development mode. 

As for your other question, `mix.scripts()` and `mix.styles()` are custom tasks that aren't part of your main Webpack build. So you won't get any special feedback in the terminal.
