### ISSUE TITLE
--env.mixfile and mix-manifest.json

### ISSUE THREAD

**Issue by pix2D** [JeffreyWay/laravel-mix#946]
- Laravel Mix Version: 1.0.7 (`npm list --depth=0`)
- Node Version (`node -v`): 7.8.0
- NPM Version (`npm -v`): 5.0.4
- OS: macOS 10.12.5

### Description:

Previously (pre 1.0.0) when utilizing multiple mix.js files the output to mix-manifest.json would be merged and would contain references to files from both mix.js configs. Now mix-manifest.json is overwritten each time mix is run.

### Steps To Reproduce:

1. Copy `webpack.mix.js` to `webpack-two.mix.js`
2. Edit `webpack-two.mix.js` and change both instances of `app.js` to `app2.js` (create a dummy file with that name where appropriate)
3. Run `npm run dev` followed by `NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=webpack-two.mix.js`

Expected behavior:

`mix-manifest.json` should contain references to both app.js and app2.js

What happens instead:

`mix-manifest.json` contains references to either app.js OR app2.js, but not both (whatever was run last overwrites the whole file)

---

The reason I have 2 separate mix.js configs in the first place is because I have an "external" JS file that is part of the project and is included by 3rd party sites, this file shares some (but not all) dependencies with the main app.js file.

If I process both files in one mix.js config then when .extract() is called it extracts vue and axios (dependencies shared by both files) to vendor.js, while I only want this to happen for app.js and on my external JS file I want all dependencies in the file and not extracted.

If there's a way to do this through 1 mix.js config I'm all ears.

Now you may wonder why mix-manifest.json matters for my use case, I also have a local test page where the external JS file is pulled in for demo purposes and since I use .version() with both it makes sense to have it work out of the box rather than hardcoding it.

Even if I were to hardcode it though I would have to make sure to always run the main mix.js config after the external config or risk a inaccurate mix-manifest.json breaking the main site.

**Comment by pix2D** [comment]
Figured out a temporary(?) solution. I added .version() cross-referencing outputs of both configs. So now mix-manifest.json contains all files no matter what is run.

Still would be nice if this worked out of the box.

**Comment by VinceG** [comment]
@JeffreyWay @pix2D this is confirmed. it seems during the rewrite of Mix the relevant code didn't make it.

**Comment by yajra** [comment]
I have the same issue after upgrading from `0.12.1` to `1.4.2`. Works well on lower version.

**Comment by mr-mmmmore** [comment]
I encounter this problem too.

I use two mix files because my Laravel project handles two different subdomains. Although mix doesn't support it, it can work using the workaround proposed [here](https://stackoverflow.com/a/45134898). The problem described here removes the map for one of the domains when the other one is built.

@pix2D's trick worked for me two in the wait of the fix. But it would be nice to be able to define the desired mix-manifest.json output file for a given webpack config.
