### ISSUE TITLE
Could we make the port for HMR editable?

### ISSUE THREAD

**Issue by Evertt** [JeffreyWay/laravel-mix#95]
I'm talking about [this line](https://github.com/JeffreyWay/laravel-mix/blob/master/src/Mix.js#L101). Sometimes my webserver is already running on localhost:8080 and I'd like to be able to configure this to run on a different port when I need it to.

**Comment by nmfzone** [comment]
@Evertt I think this section is for issue only. My advice, use gitter, laracast forum or other social sharing, not here.

**Comment by JeffreyWay** [comment]
Yes, we'll make it configurable soon.

**Comment by barryvdh** [comment]
Similar to the webpack template, could this be done with ENV var first and config later (with default to 8080); https://github.com/vuejs-templates/webpack/blob/ff9c817aef660edce82f900d91d1b730382f1e1c/template/build/dev-server.js#L14

So we could do something like `PORT=3000 npm run dev` to set the port to 3000. That would make it easy to switch ports on the fly :)

**Comment by barryvdh** [comment]
And preferably also the app url, if it's different then localhost (eg. remote server). You can run the dev server on different port/host already, but fails when new files are pushed; `yarn run hot -- --port=3000 --host=0.0.0.0`

**Comment by 3lpsy** [comment]
I am attempting to implement the same functionality (I believe). I currently set the --port option to 7770.

My cli output looks like:

```
Project is running at http://localhost:7770/
webpack output is served from http://localhost:8080/
404s will fallback to /index.html
```
On update, I see
```
GET http://localhost:8080/0faa46fc8c8619784541.hot-update.json net::ERR_CONNECTION_REFUSED
```
I believe this could be remedied by changing the hmr port (though if you suspect otherwise, please let me know).  I've attempted to manually set the "port" property on the devServer object in webpack.config.js in the mix source code but it didn't seem to affect which port was used.

**Comment by jbbr** [comment]
Workaround for setting host/port in Laravel-Mix 1.x:

put the following code in your webpack.mix.js:
```
if (Config.hmr) {
  mix.webpackConfig({
    output: {
      publicPath: 'http://localhost:8082/'
    }
  })
}
```
And add `--port 8082` to your webpack-dev-server call (likely in your `package.json`)

**Comment by lorvent** [comment]
can this get some light?

---
just want to bump this thread

**Comment by sifex** [comment]
@lorvent This probably fixes it

https://github.com/JeffreyWay/laravel-mix/pull/1246

**Comment by lorvent** [comment]
yes, that fixes it.

**Comment by sifex** [comment]
@lorvent Just waiting on Jeffery to look over it

**Comment by JeffreyWay** [comment]
Done.
