### ISSUE TITLE
Homestead + BrowserSync doesn't watch view files

### ISSUE THREAD

**Issue by marcelogarbin** [JeffreyWay/laravel-mix#950]
- Laravel Mix Version: 1.0.7
- Node Version: 8.1.2
- NPM Version:  5.0.3
- OS: Win10 + Homestead

### Description:
When using the command "npm run watch" or "npm run watch-poll" to update view files, the screen is not reloaded. However for CSS it works normally.
This running with Homestead. However, if the commands are executed via Windows10, the view files update normally.
I'm not using Windows directly because I use browsersync with other devices on the network, and only via homestead I can do this.

my config (_I already tried several paths ... I left what works on Windows_):
```
// Configs
let config = {
    host:     '192.168.1.80',
    port:     3000,
    base_url: 'admin.dev',
    watchFiles: [
        'app/Modules/**/Resources/views/**/*.{php,html}',
        'app/Modules/**/Resources/views/*.{php,html}',
        //'app/**/*.*',
        //'public/**/*.*',
        //'resources/assets/**/*.*',
        //'resources/views/**/*.*',
        //'app/Modules/**/Resources/views/**/*.*',
        //'public/css/**/*.*',
        //'public/js/**/*.*',
        //'resources/views/**/*.*',
        //'aap/Modules/**/Resources/views/**/*.*',
        //'app/Modules/**/Resources/views/*.*'
    ]
};

//Browserfy
mix.browserSync({
    files: config.watchFiles,
    host: config.host,
    proxy: config.base_url,
    port: config.port,
    online: true,
    logConnections: false,
    reloadOnRestart: true,
    notify: false,
    open: false //false, local, external, ui, tunnel
});
```

### Steps To Reproduce:
1. Access Homestead via ssh
2. Access Project Folder
3. Run "npm run watch-poll"
4. Change some view file

**Comment by marcelogarbin** [comment]
Anyone with this problem?

**Comment by irineujunior** [comment]
Same thing here.

Laravel Mix: 1.4.2
Node: 6.11.1
NPM: 3.10.10
OS: Linux (Elementary OS Loki) + Homestead (3.0)

Even with default configuration.

```
mix.browserSync({
    proxy: 'demo.local',
    open: false,
    files: [
        'app/**/*.php',
        'resources/views/**/*.php',
        'public/js/**/*.js',
        'public/css/**/*.css'
    ]
});
```

**Comment by Fuxy22** [comment]
Same thing here.

Laravel Mix: 1.7.2
Node: 8.9.1
NPM: 5.5.1
OS: Linux Mint 17 + Homestead (7.0.1)

Although thx to @irineujunior 's update `npm run watch-poll` seems to work properly now.

**Comment by betapixel** [comment]
Excelente solución.
Muchas gracias.
