### ISSUE TITLE
Extending rules (adding SassResourcesLoader)

### ISSUE THREAD

**Issue by RobinScout** [JeffreyWay/laravel-mix#955]
- Laravel Mix Version: 1.0.7

For an easy way to use sass-variables in a vue-component you can use the SassResourcesLoader. 
Currently you have to replace the complete rule (it does not merge) and manually add all of the loaders to add a new loader other than the ones already present in laravel mix.

```
mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.vue$/,
                loader: 'vue-loader',
                exclude: /bower_components/,
                options: {
                    loaders: {
                        js: {
                            loader: 'babel-loader',
                            options: {
                                cacheDirectory: true,
                                presets: [
                                    ['env', {
                                        'modules': false,
                                        'targets': {
                                            'browsers': ['> 2%'],
                                            uglify: true
                                        }
                                    }]
                                ]
                            }
                        },
                        scss: [
                            'vue-style-loader',
                            'css-loader',
                            'sass-loader',
                            sassResourceLoader
                        ],
                        sass: [
                            'vue-style-loader',
                            'css-loader',
                            'sass-loader?indentedSyntax',
                            sassResourceLoader
                        ],
                    },
                }
            }
        ]
    }
});
```

This can be some trouble because you have to manually change everything if laravel mix should change something and you have to see that all of them match up if you want the same behaviour. You also can not use the ExtractTextPlugin because you do not have access to the instance that is running in webpack-rules.js in laravel mix.

Is there an easier way to do this (plugin?), maybe I am missing something? Otherwise I propose a way to extend rules by adding new loaders.

**Comment by JeffreyWay** [comment]
I don't think there's an easy way to change it at the moment. We can add a config option if many people need it, but right now you're stuck with the defaults.
