### ISSUE TITLE
 When I execute the command npm run watch everything compiles well but in the browser when I enter with app.dev it does not pass I do not see my app

### ISSUE THREAD

**Issue by mosama1** [JeffreyWay/laravel-mix#958]
Hey I need help with compunets vue. I started a new project with laravel and vue.

I configured my project according to a video tutorial that I am following but when I execute the command npm run watch everything compiles well but in the browser when I enter with 

> app.dev

 nothing happens I searched for many solutions but none with success help please

my system is window 7
This is my webpack.mix.js file

> let mix = require('laravel-mix');
//const BrowserSyncPlugin = require('browser-sync-webpack-plugin');
/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .version();

> 

Here is what the console throws when executing the command npm run dev
 

> 

$ npm run watch
> @ watch C:\Users\JoseM\Desktop\Webs\recipe-box
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
 10% building modules 1/1 modules 0 active
Webpack is watching the filesâ¦
 95% emitting 
DONE  Compiled successfully in 1833ms16:03:20                                                                                                                                                             Asset       Size  Chunks                    Chunk Names
              /js/app.380a5bd858b26595419e.js     264 kB       0  [emitted]  [big]  /js/app
/css/app.d41d8cd98f00b204e9800998ecf8427e.css    0 bytes       0  [emitted]         /js/app
                            mix-manifest.json  144 bytes          [emitted]

>

**Comment by JeffreyWay** [comment]
We would need more information than you've given here. It looks like Mix compiled properly for you, so I'm assuming your issue is related to something else.
