### ISSUE TITLE
Cannot access environment variables through process.env in 1.x

### ISSUE THREAD

**Issue by njbarrett** [JeffreyWay/laravel-mix#959]
- Laravel Mix Version: 1.0.3
- Node Version: 7.10.0
- NPM Version: 4.2.0
- OS: OSX Sierra

### Description:
Using mix 0.11.4 I can access environment variables specified in the `.env` file with `process.env.ENV_NAME` - however this no longer seems to work on 1.0.3.

How can I access environment variables specified in the .env file in mix 1.x ?

**Comment by oldskool73** [comment]
working for me with `dotenv`...

`yarn add dotenv --dev`

```
require('dotenv').config();
mix
	.browserSync(process.env.APP_URL)
```

**Comment by njbarrett** [comment]
Thanks, that works. I didn't know I add to add dotenv as a dependency in the upgrade.
