### ISSUE TITLE
setPublicPath sets wrong path when using mix.js()

### ISSUE THREAD

**Issue by omnichronous** [JeffreyWay/laravel-mix#960]
- Laravel Mix Version: **1.0.7**
- Node Version: **6.10.2**
- NPM Version: **5.0.4**
- OS: **Windows 7 Ultimate x64**

### Description:
![image](https://user-images.githubusercontent.com/8319869/27796350-65e0a676-6012-11e7-8cf1-8fded120a563.png)

I'm trying to relocate my assets to an 'assets' subfolder inside /public. The mix-manifest.json gets created in the correct location and mix.less() outputs my CSS files and updates the reference in the manifest with the correct location as well. The mix.js() method however behaves strangely, as you can see in the screenshot.

I'm using the simplest possible setup to demonstrate this - a fresh installation of Laravel and npm install. I have tried adding and removing slashes all over the place, but to no avail.

### Steps To Reproduce:
1. Edit the webpack.mix.js file with the following:
```
mix.setPublicPath('public/assets');
mix.js('resources/assets/js/index.js', 'js');
mix.less('resources/assets/less/index.less', 'css');
```
2. `npm run dev`

**Comment by JeffreyWay** [comment]
Hmm, strange. I just used your exact setup, and it created `public/assets/mix-manifest.json` that contains:

```js
{
    "/js/app.js": "/js/app.js",
    "/css/app.css": "/css/app.css"
}
```

**Comment by demyan1411** [comment]
I have this issue too http://prntscr.com/fr8qqc

mix.setPublicPath(path.join(__dirname, "/dist"))
mix.js('src/assets/js/app.js', 'js')
   .extract(['jquery','bootstrap','vue','tether']);

**Comment by omnichronous** [comment]
Another thing I forgot to mention is that Mix will not create the assets directory on its own - unless I create it myself I get the 'no such file' error:

`Error: ENOENT: no such file or directory, open 'D:\TRANSIT\boilerplate\public\assets\mix-manifest.json'`

---

So my buddy also tested it on a fresh install and it created the files correctly, his setup was

- Laravel Mix Version: **0.12.1**
- Node Version: **6.9.5**
- NPM Version: **4.9.5**
- OS: **Windows 7 x64**

Apparently it's something in the major version update. demyan1411's fix works for me right now but it would be nice to not edit inside node_modules.

**Comment by JeffreyWay** [comment]
@omnichronous I fixed this yesterday. Just need to tag it.

**Comment by omnichronous** [comment]
@JeffreyWay that's great, thank you very much :)

**Comment by gabrieldasilva** [comment]
Hey! I'm having some throubles with this too. Actually I have a project from tree weeks ago with last mix version at that moment (0.*) and the public path was working fine. Today I start a new project and I realize that already comes with the Mix 1.1.1. 

So, I basically copy / paste my **webpack.mix** and this issue appears... 

My public path is somehing like **'public/assets/www/...'** so then I have website folders for css, images, fonts, js etc...

I think I figure it out by using the path.normalize inside setPublicPath like this:

`mix.setPublicPath(path.normalize('public/assets/www/'));` 

but I want to know if now this is the way to use the custom path.

My configuration its actually the same that @omnichronous uses...

Btw, I'm using Windows 10 x64.

**Comment by omnichronous** [comment]
I also confirm this on 1.1.1. Thanks for the quick fix @gabrieldasilva

**Comment by laminbarrow** [comment]
@omnichronous I had the same issue also on a non laravel project I'm using mix on. However, setting the paths like

```
mix.setResourceRoot(path.normalize('themes/themeName'));
mix.setPublicPath(path.normalize('themes/themeName'));

mix
      .js([
            'themes/themeName/src/js/app.js'
	], 'dist')
   	.sass('themes/themeName/src/scss/app.scss', 'dist')
   	.version();
```

Worked for me.

So now, my manifest,json file looks like this with all the correct file paths

```
{
    "/dist/app.js": "/dist/app.js?id=ca6f22b52a9619b553b2",
    "/dist/app.css": "/dist/app.css?id=aee4b6d59927ce2a8b74"
}
```

when it had the wrong js path previously like so
```
{
    "/themes/eco/dist/app.js ": "/dist/app.js?id=ca6f22b52a9619b553b2",
    "/dist/app.css": "/dist/app.css?id=aee4b6d59927ce2a8b74"
}
```

**Comment by neilcarpenter1** [comment]
Just come accross this issue too with version 1.2.2 on a windows machine...
webpack.mix.js
`
mix.setPublicPath('themes/my-theme')
mix.sass('resources/assets/sass/app.scss', 'assets/css')
	.js('resources/assets/js/app.js', 'assets/js')
	.options({ processCssUrls: false });
`
Puts css in..
`/themes/my-theme/assets/app.css`

Puts js in...
`/themes/my-theme/themes/my-theme/assets/js/app.js`

If I do path.normalize...
`mix.setPublicPath(path.normalize('themes/my-theme'))`

Then js is placed in `/themes/my-theme/assets/js/app.js`

**Comment by gabrieldasilva** [comment]
Yeap, this solves the issue on windows paths.

It would be nice to add this to the docs or a quick fix on the core publicPath function. Don´t know if this is already done

**Comment by TopFuel** [comment]
- Laravel Mix Version: 1.2.2
- OS: Windows 10 Creators Update x64

Can confirm that using `path.normalize` on `mix.setPublicPath` fixes the issue where I needed to change from:
```
mix.setPublicPath('../public');
mix.js('resources/assets/js/app.js', '../public/js/app.js'); // or 'js/app.js'
```
to:
```
mix.setPublicPath('..\\public');
mix.js('resources/assets/js/app.js', '..\\public/js/app.js'); // or 'js/app.js'
```
for it to work correctly, or it would freeze at `95% emitting`  on the `npm run development` command, and outputs this to the mix-manifest.json:
```
{
    "/E:/projects/test-project/public/E:/projects/test-project/public/js/app.js": "/E:/projects/test-project/public/E:/projects/test-project/public/js/app.js"
}
```

But adding `path.normalize` fixes it:
```
mix.setPublicPath((path.normalize('../public'));
mix.js('resources/assets/js/app.js', '../public/js/app.js'); // or 'js/app.js'
```
mix-manifest.json:
```
{
    "/js/app.js": "/js/app.js"
}
```

**Comment by Binternet** [comment]
+1 for this, also works on Mac (macOS Sierra)

**Comment by nickwelsh1** [comment]
This issue still exists on Windows.

Workarounds I've found
 - use WSL on Windows 10 with the extra overhead that entails.
 - or set both:
 `mix.setResourceRoot(path.normalize('dist/assets'));`
 `mix.setPublicPath(` path.normalize('dist/assets') );
