### ISSUE TITLE
less Unexpected character '@'

### ISSUE THREAD

**Issue by iyezhou** [JeffreyWay/laravel-mix#963]
- Laravel Mix Version: 1.0.7 (`npm list --depth=0`)
- Node Version (`v8.1.2`): 
- NPM Version (`5.0.3`): 
- OS: Windows 10

### Description:

Hi, I import a less file in my js file, like in app.js:

`import './app.less'`

then when I execute `npm run dev`, I get an error:

```
 error  in ./resources/assets/js/routes/app.less

Module parse failed: D:\www\laravel-antd\resources\assets\js\routes\app.less Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "../themes/vars.less";
|
| :global {

 @ ./resources/assets/js/routes/app.js 27:0-21
 @ ./resources/assets/js/router.js
 @ ./resources/assets/js/app.js
```

app.less:

```
@import "../themes/vars.less";

:global {
  #nprogress {
    pointer-events: none;
    ...
```

webpack.mix.js:

```
mix.react('resources/assets/js/app.js', 'public/js');
```

**Comment by stevieg83** [comment]
I'm seeing the exact same thing with Sass

**Comment by stevieg83** [comment]
@iyezhou Are you importing your LESS into a JavaScript file?

**Comment by ruchern** [comment]
Make sure `var.less` is actually `_var.less`

**Comment by stevieg83** [comment]
@ruchern tried that with my case using `_vars.scss` and the same thing still happens.

**Comment by ruchern** [comment]
Try removing importing of `LESS` file in your Javascript file.

**Comment by iyezhou** [comment]
@stevieg83 I did imported my less into a JavaScript file.  then imported an other less file into the first less file

**Comment by stevieg83** [comment]
@iyezhou seems to be the same for me. Works just fine when I compile the Sass to a standalone CSS file but importing to JS is where it's tripping up.

**Comment by jeremy-smith-maco** [comment]
Also getting this with `.sass()`. `.standaloneSass()` runs fine but doesn't actually output a .css file.

**Comment by maxonly** [comment]
I have same error for import less

**Comment by iyezhou** [comment]
@jeremy-smith-maco how to fix

**Comment by jeremy-smith-maco** [comment]
I don't have a fix for it. I was just saying that it needs to be fixed. Lol.
