### ISSUE TITLE
Laravel mix not showing notifications

### ISSUE THREAD

**Issue by hubertokf** [JeffreyWay/laravel-mix#967]
- Laravel Mix Version: 0.11.3
- Node Version: 7.10.0
- NPM Version: 4.2.0 
- OS: Linux Mint 17.3 Rosa

### Description:
When I run watch (or dev) i dont get notifications popup

webpack.mix.js
`const { mix } = require('laravel-mix');

mix.autoload({
    jquery: ['$', 'jQuery', 'window.jQuery'],
    tether: ['Tether', 'window.Tether']
});
mix.js([
        'node_modules/jquery/dist/jquery.js',
        'resources/assets/js/app.js',
        'node_modules/tether/dist/js/tether.js',
        'node_modules/vue-moment/vue-moment.js',
        'node_modules/bootstrap/dist/js/bootstrap.js'
    ], 'public/js/app.js')
   .sass('resources/assets/sass/app.scss', '../resources/assets/build/app.css')
   .combine([
        'node_modules/vue-multiselect/dist/vue-multiselect.min.css',
        'resources/assets/build/app.css'
    ], 'public/css/app.css');`

### Steps To Reproduce:

I'm not using homestead, but i'm runing "sudo npm run watch" from a terminal Screen

**Comment by JeffreyWay** [comment]
Not sure. I just tested, and notifications seem to be displaying properly. Make sure your OS isn't blocking them. 

Mix just defers to a notification plugin, so we don't have much control over this.
