### ISSUE TITLE
[Feature Request] Add support for webpack-bundle-analyzer

### ISSUE THREAD

**Issue by Olian04** [JeffreyWay/laravel-mix#968]
It would really help if laravel-mix supported some kind of bundle analyzer.
Example of a bundle analyzer would be [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer).

**Comment by JeffreyWay** [comment]
You can pull this in manually, using `mix.webpackConfig()`, but I don't have plans to make it part of Mix's core right now.

**Comment by wmcmurray** [comment]
Just a quick article demonstrating how to use `webpack-bundle-analyzer` with laravel mix :
http://paul-beigang.de/laravel-mix-analyze-webpack-bundle-size

**Comment by InstanceOfMichael** [comment]
@wmcmurray link is broken

**Comment by wmcmurray** [comment]
Thanks @InstanceOfMichael , I edited my comment with an example taken from a project of mine instead.
