### ISSUE TITLE
summernote doesn't register with jQuery object

### ISSUE THREAD

**Issue by Remo** [JeffreyWay/laravel-mix#969]
- Laravel Mix Version: 1.0.7
- Node Version: v6.9.1
- NPM Version (`npm -v`): 
- Yarn: v0.17.8
- OS: Windows 10

### Description:

I'm trying to use summernote in my laravel application. I've tried a number of things like autoloading and removing the global jquery from bootstrap, but nothing works, it always fails with `TypeError: $(...).summernote is not a function`. 

### Steps To Reproduce:

You can see all my attempts here: https://github.com/ortic/laravel-summernote-test/commits/master
Each commit is another attempt, all fails in more or less the same way.

Just clone the repo, run `yarn` and `yarn run dev` and fire up the webserver. Summernote should be shown on the home page. I had a look at a number of issues related to autoload, but nothing works. All posts I've found I've tried in my repo. Someone please tell me what I haven't tried. Thanks!

**Comment by JeffreyWay** [comment]
It's probably because your jQuery plugin expects jQuery to live in the global scope. You can use mix.autoload() for this.

https://github.com/JeffreyWay/laravel-mix/blob/master/docs/autoloading.md

**Comment by Remo** [comment]
I did, doesn't work https://github.com/ortic/laravel-summernote-test/commit/583e9ee15da61cb4beaccdd79fa836f93862b46b#diff-61877038a5575038809abf03f0009520R14

**Comment by Remo** [comment]
Me and webpack will probably never be best friends, but at least I found a way now.
It turns out that summernote has added a jQuery dependency not too long ago, one that is different from the version I'm including. Because of that the summernote function doesn't get registered in the jQuery scope. My wish for Christmas would be a warning, but for anybody in the same position, here's my change https://github.com/ortic/laravel-summernote-test/commit/0b9fc0b2350687e1fdee6d0b98b652f220f5dae0
