### ISSUE TITLE
[Help / Request] Vue option loaders. (Not preLoaders | postLoaders)

### ISSUE THREAD

**Issue by xxRockOnxx** [JeffreyWay/laravel-mix#972]
Laravel Mix Version: 1.0.7
- Node Version (`node -v`): Node v8.0.0
- NPM Version (`npm -v`): npm 5.1.0
- OS: Ubuntu 17.04 GNOME

### Description:
I currently do this:

```
} : {
                js: {
                    loader: 'babel-loader',
                    options: Config.babel()
                },
                scss: 'vue-style-loader!css-loader!sass-loader?' + JSON.stringify({
                    includePaths: [
                        path.resolve('./node_modules'),
                    ]
                })
            },
            postcss: Config.postCss,
            preLoaders: Config.vue.preLoaders,
            postLoaders: Config.vue.postLoaders
```

on `webpack-rules.js`. Tried adding/replacing from `webpack.mix` but it doesn't work. I really needed to put it there.

Is there a method I don't know that could help? I thought options will be `merged` with the one from `webpack.mix` like stated in the docs but it seems that it only pushes it.

How can I do this?

**Comment by JeffreyWay** [comment]
I don't think you can change those settings right now. If there's a better default, you can submit a PR and we'll merge it.
