### ISSUE TITLE
copyDirectory using regular expressions

### ISSUE THREAD

**Issue by pderiy** [JeffreyWay/laravel-mix#977]
- Laravel Mix Version: 1.1.1
- Node Version (`node -v`): 6.11.0
- NPM Version (`npm -v`): 5.1.0
- OS: Ubuntu 17.04

### Description:
Hi, when I try to use copyDirectory with regular expressions (angular/app/**/*.html) it makes a copy of html files without nested directories.

### Steps To Reproduce:
I have next files in angular folder (from):
```
angular/app/layouts/default.html
angular/app/pages/lessons/lessons.html
```
I have a views folder (to):
```
public/views (without any file)
```
webpack.mix.js
```
mix
  .copyDirectory('angular/app/**/*.html', 'public/views/app')
```
[Uncorrect]After compile it looks like:
```
public/views/app/default.html
public/views/app/lessons.html
```
[Correct] But I think it should looks like:
```
public/views/app/layouts/default.html
public/views/app/pages/lessons/lessons.html
```

I think laravel-mix should create nested folders, because without it  using regular expressions (example: **) is not much powerful as it should be.

### Tooltip
When I was using laravel-mix v.0.12.0, I overwrote 'FileCollection.js' to fix my issue. (I'm not sure that it will help you):
```
let DefaultFileCollection = require('../node_modules/laravel-mix/src/FileCollection');

class FileCollection extends DefaultFileCollection {

	/**
	 * Create a new FileCollection instance.
	 *
	 * @param {string|array} files
	 */
	constructor(files) {
		super(files);

		if (typeof files === 'string' && files.includes('*')) {  // edited
			this.rmDestSymbolsCount = files.indexOf('*'); // edited
		} // edited
	}

	outputPath(src) {
		let output = new File(this.destination).parsePath();

		// If the src path is a file, but the output is a directory,
		// we have to append the src filename to the output path.
		if (src.isFile && output.isDir) {
			var sufix = Array.isArray(this.files) ? src.file : src.path.replace(this.files, ''); // edited

			if(this.rmDestSymbolsCount) { // edited
				sufix = sufix.substring(this.rmDestSymbolsCount, sufix.length); // edited
			} // edited
			output = path.join(output.path, sufix); // edited

			if (new File(output).parsePath().isDir) {
				output = path.join(output, src.file);
			}

			return output;
		}

		return output.path;
	}
}

module.exports = FileCollection;
```

P.S. Sorry for my bad english

**Comment by JeffreyWay** [comment]
This is expected behavior for using a regex of files.

**Comment by pderiy** [comment]
@JeffreyWay Okay, no problem. What would you recommend when I have next files?
```
angular/lessons/index.html
angular/orders/index.html
```
Sometimes I have 50+- html files to copy. Do I need register all of them without regular expressions?
