### ISSUE TITLE
Compile a single entry-point

### ISSUE THREAD

**Issue by jbruni** [JeffreyWay/laravel-mix#98]
Consider the following scenario:
- multiple entry-points (not a SPA)
- big app with many components, ie, compiling time of a single entry-point may be considerable
- a developer makes a change affecting a single entry-point

How the developer can compile that single entry-point (either for production, or unminified), instead of going through the whole build of everything?

-------------------

What I really want to know is if Laravel Mix is considering this type of scenario and providing some straightforward way to enable multiple tasks definitions.

Just like in Gulp we can run a single task: `gulp task1` or `gulp task2`, can we also run a specific "task" (subset of the build process) from command-line?

Hmmm... Maybe this is more a feature request than a question. It's like I'm asking for a thin "task runner" layer/support, from Laravel Mix itself.

**Comment by JeffreyWay** [comment]
Laravel Mix doesn't really work that way. It's not a general task runner, like Gulp. If you need that functionality, stick with Gulp or use Laravel Elixir.

**Comment by markszymik** [comment]
OK, @JeffreyWay are you saying that there's no way to build a large application with Laravel Mix?
How to tackle this issue?

**Comment by theHarvester** [comment]
I'm certainly no expert with webpack so let me know if this isn't possible. But could we extend

```mix.js('somefile.js', 'output/js')```

to

```mix.js(['somefile.js'], 'output/js')```

and it could use the multiple entry points plugun when an array is detected?

 https://github.com/webpack/webpack/tree/master/examples/multiple-entry-points

**Comment by theHarvester** [comment]
I take it all back. You only need one entry point for the vue file and you can mount a different vue component depending on a data attribute. 

@markszymik this is hacky but it works:

```
import Vue from 'vue';
import TestTemplate from './templates/TestTemplate.vue';

const container = document.getElementById('app');

if (container) {
    const key = container.getAttribute('data-vue');
    const containerMap = {
        example: TestTemplate,
    };

    new Vue({
        el: '#app',
        render: function (createElement) {
            return createElement(containerMap[key])
        }
    });
}
```
