### ISSUE TITLE
Images not copied on watch

### ISSUE THREAD

**Issue by lspoor** [JeffreyWay/laravel-mix#980]
- Laravel Mix Version: 1.1.1
- Node Version: 6.8.1 
- NPM Version: 3.10.8 
- OS: macOS Sierra 10.12.5

### Description:
Linking to an image in blade/html, e.g.
```
<a href="#" id="logo">
    <img src="/images/logo.jpg" alt="" width="117">
</a>
```

Then copying the image `logo.jpg` into `/resources/assets/images/`

Upon doing this, nothing happens, my browser refreshes and the image is broken because it hasn't been copied.

### Steps To Reproduce:

Using the following `webpack.mix.js` file:
```
// Require Laravel Mix
// ==================================================
let mix = require('laravel-mix');

// Styles
// ==================================================
mix.sass('resources/assets/scss/app.scss', 'public/css');

// Scripts
// ==================================================
mix.js('resources/assets/js/app.js', 'public/js')
mix.copy('resources/assets/js/libraries', 'public/js/libraries', false);

// Images
// ==================================================
mix.copy('resources/assets/images/**/*', 'public/images', false);

// Browser Reload
// ==================================================
mix.browserSync('frogsquad.local');

// Disable Notifications
// ==================================================
mix.disableNotifications();
```

Use the following code in a blade template and then copy an image named `logo.jpg` into `/resources/assets/images/`

```
<a href="#" id="logo">
    <img src="/images/logo.jpg" alt="" width="117">
</a>
```

**Comment by JeffreyWay** [comment]
Hmm, I just did a little test app and everything copied over properly.

**Comment by lspoor** [comment]
Any idea why it isn't copying then? If I quit `npm run watch` and re-run it, the image is copied over but not while `npm run watch` is running

**Comment by JeffreyWay** [comment]
Are you referring to when you add new images to your resources/assets/images directory?

**Comment by lspoor** [comment]
Correct, I copy an image into that directory while `npm run watch` is running

**Comment by JeffreyWay** [comment]
You have to stop npm run watch and restart it for new assets to take effect.
