### ISSUE TITLE
Parsing js file for picture and add the hash when versionning

### ISSUE THREAD

**Issue by dib258** [JeffreyWay/laravel-mix#984]
Laravel Mix version : 0.8.8
Node version : 6.0.12
Npm : 3.10.10
Os : OSX El Capitan

Description :

Hi,

I see when a css file is parsed by webpack that If I put a picture url in it it'll search for it, deploy it to the public file and because I'm versionning I have a hash added after.

Now, I have also a js file that is using one of the same picture I use in css (to preload it). And It seems that webpack doesn't care about this string (in general or) in my situation which is the following :

`function preloadFirstPicture() {
    var picture = new Image();

    $(picture).on('load', function () {

        $('.jumbotron').animate({opacity : 1}, 1000, function () {

            $('.intro').addClass('ombrage');

            setInterval(nextBackgroundImage, 3500);

        }).addClass('one');

    });

    picture.src = "./images/css/friendsitting-background-001.jpg";
}`

Is there a way to tell Laravel mix ( or webpack ) to parse the picture in this string or to force to add the specific hash to this string only.

Thanks in advance for your help, 

And it's not an error it's more a lack of knowledge with webpack.

**Comment by JeffreyWay** [comment]
Your JavaScript should just reference the final location where that JPG should live. So if Webpack compiles resources/assets/images/image.jpg to public/js/image.jpg, then your JS should reference /public/js/image.jpg.

**Comment by dib258** [comment]
Yes, it's what I'm actually doing but when I tested with PageSpeed they are setting a super low score because they say I'm using two different file but they are the same and the reason is only because of the hash. That's stupid I know and I don't even know if this is a real slow down on the website.

> The following resources have identical contents, but are served from different URLs. Serve these resources from a consistent URL to save 1 request(s) and 356.9KiB.
> 
> xxx-background-001.jpg
> xxx-background-001.jpg?154ddef55cc00d720cc4f99abb59372b
