### ISSUE TITLE
Manifest conflict

### ISSUE THREAD

**Issue by matthijs110** [JeffreyWay/laravel-mix#99]
Hello,

By default (on Laravel), the `manifest.json` file is stored in the public folder. I want to use a `manifest.json` for website metadata. Normally you would store this in the public folder. However, I can't do that because Laravel-Mix overwrites the file.

What could be a propper solution to this? A different filename for Laravel-Mix' `manifest.json`?

**Comment by eblin** [comment]
You have `mix.setPublicPath('dist/');` [1] to tell `laravel-mix` where to output manifest + files. However, if you want to use default `public` then yes the `manifest.json` file would have to be configurable.
[1] https://github.com/JeffreyWay/laravel-mix/blob/master/docs/faq.md#my-manifestjson-file-shouldnt-be-in-the-project-root

**Comment by JeffreyWay** [comment]
I just pushed a commit that renames the file to `mix-manifest.json`.
