### ISSUE TITLE
wrong paths in mix-manifest.json under windows10 and  95% emitting                                                                   

### ISSUE THREAD

**Issue by epnlespieux** [JeffreyWay/laravel-mix#991]
- Laravel Mix Version: 1.2 (`npm list --depth=0`)
- Node Version : v8.1.4
- NPM Version (`npm -v`): 5.1.0
- OS: Windows 10

### Strange paths in the mix-manifest.json...
My webpack.mix.js

-------------------
let { mix } = require('laravel-mix');
mix.js('js/app.js', 'dist/bundle.js')
      .extract('jquery','uikit');
mix.sass('sass/theme-avec-uikit.scss', 'style.css');

--------------------
gives that result  in mix-manifest.json

{
    "/C:/dist/bundle.js": "/C:/dist/bundle.js",
    "/style.css": "/style.css",
    "/uikit.js": "/uikit.js",
    "/C:/dist/manifest.js": "/C:/dist/manifest.js"
}

Why this "/C:/" ?

the npm run watch gets stuck at 95 %

the npm run hot 

> @ hot C:\Users\nlb\Code\cmlespieux.local\app\public\wp-content\themes\_satie
> cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js

Project is running at http://localhost:8080/
webpack output is served from http://localhost:8080/
404s will fallback to /index.html
 DONE  Compiled successfully in 4914ms18:26:54

Thanks for your help.

**Comment by arcanedev-maroc** [comment]
Duplicated: #925

**Comment by epnlespieux** [comment]
Sorry for this dupplicated issue. The solution is given in #925 

Indeed i do not use laravel but only laravel-mix
The solution is to add this line 

mix.setPublicPath('./');

```
let { mix } = require('laravel-mix');

mix.setPublicPath('./');

mix.js('js/app.js', 'dist/bundle.js')
      .extract('jquery','uikit');

mix.sass('sass/theme-avec-uikit.scss', 'style.css');

```
