### ISSUE TITLE
laravel 5.4 dependency not found

### ISSUE THREAD

**Issue by simoebenhida** [JeffreyWay/laravel-mix#992]
`> npm run development

> @ development /Users/mohamed/Projets/concoursWebsite
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting                                                                      

 ERROR  Failed to compile with 1 errors                                                                                            19:50:22

This dependency was not found:

* /Users/mohamed/Projets/concoursWebsite/resources/assets/js/app.js in multi ./resources/assets/js/app.js

To install it, you can run: npm install --save /Users/mohamed/Projets/concoursWebsite/resources/assets/js/app.js
     Asset     Size  Chunks             Chunk Names
/js/app.js  2.64 kB       0  [emitted]  /js/app
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
`

**Comment by Chinese1904** [comment]
Looks like a duplicate

https://github.com/JeffreyWay/laravel-mix/issues/991
https://github.com/JeffreyWay/laravel-mix/issues/925

**Comment by simoebenhida** [comment]
@Chinese1904 i fixed the previous issue by installing babel-loader

`npm install --save-dev babel-loader babel-core babel-preset-env webpack`

but now i have this issue with vuejs file

` ERROR  Failed to compile with 1 errors                                                                                          20:07:55

This relative module was not found:

* ./components/Example.vue in ./resources/assets/js/app.js`

**Comment by JeffreyWay** [comment]
Yep, this is an npm 5.2 issue. Downgrade until they patch it up.

**Comment by simoebenhida** [comment]
Lol i didn't remember the previous version that i had npm 5 is fine ?

**Comment by Smileysoftware** [comment]
Hi,
I've found the same issue. How in the world do I downgrade npm without wrecking the node version too?
Sorry might seem a stupid question.

**Comment by ruchern** [comment]
@Smileysoftware What OS are you using?

**Comment by simoebenhida** [comment]
Just use this command `npm install -g npm@4.6.1` Like i did

**Comment by Smileysoftware** [comment]
I'm using OSX 10.12.6

@simoebenhida I have run that command and I have the same result, I did something similar previously.

I now have node version 8.4.0 and npm version 4.6.1 if thats any help.

Thanks in advance.

**Comment by Smileysoftware** [comment]
I have to confess to being utterly baffled by this. I'm no NPM expert so this might be simple to some but I just cant get to do any work.
I cannot load any Vue components.

**Comment by Smileysoftware** [comment]
Just tested using npm version 5.1.0 and I get the exact same issue.

Any help would be amazing. Thanks

**Comment by Smileysoftware** [comment]
I have just set up a brand new Laravel installation and the webpack task works fine.

I've updated the Laravel 5.5 on my existing project. Is there an obvious reason why this wont work on this project?

**Comment by Smileysoftware** [comment]
So I decided to see what the difference was between the projects,

I literally replaced the following from the new project to the old.
node_modules
package.json
webpack.mix.js
