### ISSUE TITLE
Trouble on windows

### ISSUE THREAD

**Issue by demyan1411** [JeffreyWay/laravel-mix#993]
- Laravel Mix Version: 1.2.0
- Node Version (`node -v`): 6.11 (the same issue in 8.1.4)
- NPM Version (`npm -v`): 4.6.1 (the same on 5.1.0 and 5.2.0)
- OS: windows 8.1

### Description:

```
This dependency was not found:

* e:\openserver\domains\webster\src\assets\js\app.js in multi ./src/assets/js/app.js

To install it, you can run: npm install --save e:\openserver\domains\webster\src\assets\js\app.js
                            Asset     Size  Chunks             Chunk Names
webster\webster\webster\js\app.js  2.64 kB       0  [emitted]  webster\webster\webster\js\app
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! webster@1.0.0 development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the webster@1.0.0 development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-07-12T20_06_54_579Z-debug.log
error Command failed with exit code 2.
```

### Steps To Reproduce:
in my webpack.mix.js I have only: `mix.js('src/assets/js/app.js', 'js');`

**Comment by roennow** [comment]
Same issue here (osx 10.12.5, node 8.0.0, npm 5.2.0). When i run the scripts (dev/watch/production) I get a osx notification from Mix with this info: `Error: undefinedError: Can't resolve 'babel-loader' in '/Users/....'`. That error is not present in the console or in the debug log.

**Comment by JeffreyWay** [comment]
It's related to npm 5.2. If you downgrade, make sure you `rm -rf node_modules && npm cache clear && npm install`.

**Comment by demyan1411** [comment]
It's not help i tried  versions 4.6.1, 5.1.0, and I removed node_modure and cleared cash

**Comment by Elypson** [comment]
I have the exactly same issue on Mac OS High Sierra, npm5.2.0 and Laravel5.5
