### ISSUE TITLE
Cannot find module 'uglifyjs-webpack-plugin'

### ISSUE THREAD

**Issue by msonowal** [JeffreyWay/laravel-mix#994]
- Laravel Mix Version: #.#.# (`npm list --depth=0`) laravel-mix@1.2.1
- Node Version (`node -v`): v8.1.2
- NPM Version (`npm -v`): 5.2.0
- OS: macOS Sierra 10.12.5 

### Description:
Just updated laravel mix to v1.2.1 from v1.1.0 and after updated I ran the command npm run dev and it throws the error. I have vue JS installed and working fine till the last update

**Comment by JeffreyWay** [comment]
Pretty sure it's related to you upgrading to npm 5.2. There's a bug with that new release. It has been fixed, but they haven't yet tagged it. 

For now, downgrade npm, and then do `rm -rf node_modules && npm cache clear && npm install`.
