### ISSUE TITLE
NODE_ENV vs APP_ENV

### ISSUE THREAD

**Issue by mike-grinspan** [JeffreyWay/laravel-mix#995]
Laravel uses the `APP_ENV` environmental variable to figure out if the application is in production or not, while Laravel Mix uses `NODE_ENV`. This is a little annoying as it forces you to have 2 identical environment variables in your `.env` file.

Currently my "workaround" is the following code before I `require('laravel-mix')`;

```js
require('node-env-file')(__dirname + '/.env');
process.env.NODE_ENV === 'production' || (process.env.NODE_ENV = process.env.APP_ENV);
```

Unfortunately this requires another library, which I think is a bit much.

Can we update Laravel Mix to check both of these variables? I could write the code, but I don't want to work on it if the change is not welcome.

**Comment by JeffreyWay** [comment]
We use NODE_ENV to determine what environment you want Mix to compile in...not the environment for your application.

**Comment by mike-grinspan** [comment]
I understand that, but aren't these the same 99% of the time? (I assume) no one compiles their assets for development on their production server, and if I wanted to compile for production on dev, I could by adding `-p` to the command.

**Comment by tadejgasparovic** [comment]
I agree with @mike-grinspan . Mix really **should** use `APP_ENV` as the default when compiling. Something should definitely be done about this. I don't think it was the right decision to just close the issue without even considering it first.
