### ISSUE TITLE
Browsersync makes full reload after CSS-inject

### ISSUE THREAD

**Issue by nivv** [JeffreyWay/laravel-mix#999]
- Laravel Mix Version: 1.2.1
- Node Version: v8.1.4 
- NPM Version: 5.0.3: 
- OS: macOS 

### Description:
When running Laravel Mix with the `mix.browserSync()`-option enabled it makes a hard refresh when styles change. The weird thing is that I can see the style updated (while watching a file) but then Browsersync makes a full reload anyways.

### Steps To Reproduce:

```bash
$ mkdir laravel-mix-test && cd laravel-mix-test
```

```bash
$ npm init
```

```bash
$ npm install laravel-mix --save-dev
```

webpack.mix.js
```javascript
mix.sass('src/app.scss', 'dist/')
    .browserSync('test.dev');
```

Run `npm run watch`. Install more dependencies because of BrowserSync.

Run `npm run watch`again.

(I've served a site at `test.dev` with Laravel Valet)

## Update
While writing the issue I came across a potential fix. It seems that you have to specify which files should be triggered. 

My updated webpack.mix.js

```javascript
let config = {
    base_url: 'test.dev',
    watchFiles: [
        'app/*.*',
        'app/**/*.*',
        'dist/*.css',
    ]
};

mix.sass('src/app.scss', 'dist/')
    .browserSync({
        files: config.watchFiles,
        proxy: config.base_url,
    });
```

**Comment by nivv** [comment]
Closing this, but could be useful for others as a reference.

**Comment by ElysianWebDesign** [comment]
`"use strict";

// ------------------------------------------------- load plugins
const gulp         = require('gulp'),
      // svgSprite     = require('gulp-svg-sprite'),
      // imagemin      = require('gulp-imagemin'),
      rename       = require('gulp-rename'),
      uglify       = require('gulp-uglify'),
      autoprefixer = require('autoprefixer'),
      browsersync  = require('browser-sync').create(),
      sourcemaps   = require('gulp-sourcemaps'),
      cssnano      = require('cssnano'),
      del          = require('del'),
      plumber      = require('gulp-plumber'),
      postcss      = require('gulp-postcss'),
      sass         = require('gulp-sass');

// ------------------------------------------------- vars for site and browserSync
const siteName = 'gatesinsurance-wp',
      userName = 'evanmarshall';

// ------------------------------------------------- configs
const paths = {
  svg: {
    src: './src/images/icons/',
    dest: './build/assets/images/sprites/',
    glob: '**/*.svg',
    config: {
      "log": "debug",
      "shape": {
        "dimensions": {
          "maxWidth": 200,
          "maxHeight": 200
        },
      },
      "mode": {
        "css": {
          render: {
            scss: {
              dest: "/src/styles/modules/_sprite.scss",
              template: "./gulpfile.js/templates/sprite.scss"
            }
          }
        },
      },
      "variables": {}
    }
  },
  styles: {
    src: './src/styles/**/*.scss',
    dest: './build/themes/gatesinsurance/assets/styles',
    opts: {

    }
  },
  images: {
    src: './src/images/**/*',
    dest: './build/themes/gatesinsurance/assets/images',
    opts: {

    }
  },
  scripts: {
    src: './src/scripts/**/*.js',
    dest: './build/themes/gatesinsurance/assets/scripts',
    opts: {

    }
  },
  watchedFiles: [
      './src/styles/**/*.scss',
      './build/themes/gatesinsurance/assets/styles/**/*.css',
    ],
  assets: './build/themes/gatesinsurance/assets',
  php: './build/themes/gatesinsurance/**/*.php'
};

// ------------------------------------------------- browserSync fxn
function serve(done) {
  browsersync.init({
    files: paths.watchedFiles,
    proxy: 'http://' + siteName + '.test',
    host: siteName + '.test',
    open: 'external',
    port: 8000,
    http: {
      key:
          '/Users/' +
          userName +
          '/.valet/Certificates/' +
          siteName +
          '.test.key',
      cert:
          '/Users/' +
          userName +
          '/.valet/Certificates/' +
          siteName +
          '.test.crt'
    }
  });
  done();
}

// ------------------------------------------------- browserSync reload fxn
function reload(done) {
  browsersync.reload();
  done();
}

// ------------------------------------------------- clean fxn
function clean() {
  return del(paths.assets)
}

// ------------------------------------------------- styles fxn
function styles(done) {
  return gulp
    .src(paths.styles.src)
    .pipe(plumber())
    .pipe(sourcemaps.init())
    .pipe(sass({
      outputStyle: 'expanded'
    }))
    .pipe(gulp.dest(paths.styles.dest))
    .pipe(rename({
      suffix: '.min'
    }))
    .pipe(postcss([
      autoprefixer(), cssnano()
    ]))
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest(paths.styles.dest))
    // .pipe(browsersync.reload({ stream: true }));
    .pipe(browsersync.stream());
  done();
}

// ------------------------------------------------- scripts fxn
function scripts(done) {
  done();
}

// ------------------------------------------------- watch fxn
function watchFiles() {
  gulp.watch(paths.styles.src, styles);
  gulp.watch(paths.php, reload);
  gulp.watch(paths.scripts.src, gulp.series(scripts, reload));
}

// ------------------------------------------------- define tasks
// js = gulp.series(scriptsLint, scripts),
const build = gulp.series(clean, gulp.parallel(styles, scripts)),
      watch = gulp.parallel(watchFiles, serve);

// ------------------------------------------------- export tasks
// exports.images = images;
exports.styles  = styles;
exports.js      = scripts;
exports.clean   = clean;
exports.build   = build;
exports.watch   = watch;
exports.default = build;

styles.description = "This task compiles scss files, outputs expanded version for debug and then minifies/autoprefixes css into styles folder.";
`

I still have issues with the styles not injecting. I still have to do a manual browser reload

**Comment by pcampina** [comment]
IN 2020 (Laravel 7), config is:

```
mix
  .js("resources/js/app.js", "public/js")
  .sass("resources/sass/app.scss", "public/css")
  .browserSync({
    proxy: 'localhost', // your domain test
    port: 32816 // your port
  });
```
